sonic-net/sonic-buildimage

- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cq2-lc.json
Address build failures due to sonic config engine unit tests failing. Failures are due to referencing format used in Arista 7800 sample output for buffer template
Remove referencing format
Sonic config engine wheel should be built successfully
> Remove referencing in unit test for arista7800

- files/image_config/interfaces/interfaces-config.sh
The PR is aimed to fix a bug that mgmt port eth0 may loss IP even if user configured static IP of eth0. This is not a always reproduceable issue, the reproducing flow is like:
1.	Systemd starts networking service, which runs a dhcp based configuration and assigned an ip from dhcp.
2.	Systemd starts interface-config service who depends on networking service
3.	Interface-config service runs command  “ifdown –force eth0”, check [line](https://github.com/Azure/sonic-buildimage/blob/16717d2dc51f74fa711ed7b4392ce5e4f7e71c29/files/image_config/interfaces/interfaces-config.sh#L4). but networking service is still running so that this [line](https://github.com/CumulusNetworks/ifupdown2/blob/ac32bec0e24d64c583778f387050a7b6f4269db0/ifupdown2/ifupdown/main.py#L74) failed with error: “error: Another …
> Fix race condition between networking service and interface-config service

- slave.mk
Some places were not correctly setting the HTTPS proxy, and were only
setting the HTTP proxy. This was fine until Docker 20.10.10, which then
started using `https_proxy` for HTTPS connections.
> Fix setting the HTTPS proxy

- rules/sonic-pcied.dep
Python 2 support for sonic-pcied was removed, and the Python 2 version
of the variable no longer exists.
> Change source path for sonic-pcied to use Python 3 variable

- src/sonic-config-engine/portconfig.py
- src/sonic-config-engine/sonic-cfggen
Reverts Azure/sonic-buildimage#10581
Below error seen when sonic-cfggen tries to get the hwsku(/usr/local/bin/sonic-cfggen -H -v DEVICE_METADATA.localhost.platform) for device path directory, during boot up
File "/usr/local/bin/sonic-cfggen", line 451, in <module>
main()
File "/usr/local/bin/sonic-cfggen", line 304, in main
SonicDBConfig.load_sonic_db_config()
File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1252, in load_sonic_db_config
SonicDBConfig.initialize(sonic_db_file_path)
File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1247, in initialize
return _swsscommon.SonicDBConfig_initialize(*args, **kwargs)
RuntimeError: Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json
> Revert "[portconfig]: Remove try block for db config initialization"

- dockers/docker-mux/supervisord.conf
[master][sonic-linkmgrd] submodule updates
df51322 Longxiang Lyu   Fri May 6 10:01:46 2022 +0800   Add `ActiveActiveStateMachine` implementation (#64)
e721ceb Jing Zhang      Wed May 4 10:07:14 2022 -0700   Add doc for default route related changes  (#63)
7bb06fb Jing Zhang      Tue May 3 09:48:28 2022 -0700   Add Cli support to enable or disable default route related feature (#68)
e4b02cb Jing Zhang      Mon May 2 13:27:54 2022 -0700   Reset WaitActiveUp count before switching to active (#70)
212d960 Jing Zhang      Wed Apr 27 10:35:05 2022 -0700  lower log level to warning (#69)
48abc9e Jing Zhang      Thu Apr 14 16:50:04 2022 -0700  Add support to enable switchover time measurement (with link prober interval decreased to 10ms) feature  (#61)
c4858a6 Jing Zhang      Thu Apr 14 11:27:55 …
> [master][sonic-linkmgrd] submodule updates

- rules/sonic-config.dep
PR validation will use cached package to bypass PR validation.
Add dependencies 'device/*' for sonic-config-engine to block bad PR.
It will reduce cache hit rate but increase build success rate.
check PR calidation dependency file.
> [build] Add dependencies for sonic-config-engine to block bad PR.

- src/iproute2/patch/0001-patch-macsec-xpn-support.patch
The SSCI is wrong in the output of MACsec so that the virtual SAI cannot parse the output corretly.
The wrong output:
```
142: macsec_eth1: protect on validate strict sc off sa off encrypt on send_sci on end_station off scb off replay off
cipher suite: GCM-AES-XPN-256, using ICV length 16
TXSC: 5254008f4f1c0001 on SA 0
0: PN 103, state on, key 12cbc4b64e26c9a1ba14d810da20d16e
SSCI 33554432,    RXSC: 525400edac5b0001, state on
0: PN 107, state on, key 12cbc4b64e26c9a1ba14d810da20d16e
offload: off
```
Expected
```
142: macsec_eth1: protect on validate strict sc off sa off encrypt on send_sci on end_station off scb off replay off
cipher suite: GCM-AES-XPN-256, using ICV length 16
TXSC: 5254008f4f1c0001 on SA 0
0: PN 252, state on, SSCI 33554432, key …
```
> [iproute2]: Fix the output error of SSCI

- push_docker.sh
Support multi tags when pushing docker image.
> [ci] Support multi tags when pushing docker image

- src/sonic-yang-mgmt/sonic_yang.py
- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-models/tests/files/sample_config_db.json
Backport https://github.com/Azure/sonic-buildimage/pull/10291 to 202111
Fix issue: Non compliant leaf list in config_db schema: https://github.com/Azure/sonic-buildimage/issues/9801
The basic flow of DPB is like:
1.	Transfer config db json value to YANG json value, name it “yangIn”
2.	Validate “yangIn” by libyang
3.	Generate a YANG json value to represent the target configuration, name it “yangTarget”
4.	Do diff between “yangIn” and “yangTarget”
5.	Apply the diff to CONFIG DB json and save it back to DB
The fix:
•	For step #1, If value of a leaf-list field string type, transfer it to a list by splitting it with “,” the purpose here is to make step#2 happy. We also need to save <table_name>.<key>.<field_name> to a set named “leaf_list_with_string_value_set”.
•	For step#5, loop …
> [202111] [YANG] Fix issue: Non compliant leaf list in config_db schema 

- build_debian.sh
- files/build_templates/sonic_debian_extension.j2
The image size is too large, when there are multiple lazy packages and multiple platforms. It is not necessary to keep the lazy installation packages in multiple copies.
For cisco image, the image size will reduce from 3.5G to 1.7G.
Use symbol links to only keep one package for each of the lazy package.
Make a new folder fsroot/platform/common
Copy the lazy packages into the folder.
When using a package in each of the platform, such as x86_64-grub, x86_64-8800_rp-r0, x86_64-8201_on-r0, etc, only make a symbol link to the package in the common folder.
```
ls target/sonic-cisco-8000.bin target/sonic-cisco-8000.bin.bk1 -lh
-rwxr-xr-x 1 xumia xumia 1.7G May  7 08:10 target/sonic-cisco-8000.bin
-rwxr-xr-x 1 xumia xumia 3.5G May  7 05:59 target/sonic-cisco-8000.bin.bk1
```
> Reduce image size for lazy installation packages

- device/accton/x86_64-accton_as7326_56x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7326_56x-r0/sensors.conf
- device/accton/x86_64-accton_as7726_32x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7726_32x-r0/sensors.conf
- device/accton/x86_64-accton_as7816_64x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7816_64x-r0/sensors.conf
Renaming temp for cmd sensors and show platform temp. To let user is easy to know temp location from naming.
1. Modify name in sensors.conf
2. Modify or add display_name in pddf-device.json
Test cmd, sensors, and show platform temp.
For as7816,
root@sonic:/home/admin# show platform temperature
Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
-------------------------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
CpuBoard_temp(0x4B)           21.5       80.0       N/A             N/A            N/A      False  20220321 02:51:19
FB_1_temp(0x4D)           22.5       80.0       N/A             N/A            N/A      False  20220321 …
> [PDDF] Rename temp for as7816/7326/7726

- Makefile.cache
In `Makefile.cache`, for `$(1)_DEP_PKGS_SHA`, the intention is to include
the `DEP_MOD_SHA` and `MOD_HASH` of each of the current package's
dependencies. However, there's a level of dereferencing missing; instead
of grabbing the value of `$(dfile)_DEP_MOD_SHA`, it is literally using the
variable name `$(dfile)_DEP_MOD_SHA`. This means that the value of this
variable will not change when some dependency changes.
The impact of this is in indirect dependencies. For a specific
example, if there is some change in sairedis, then sairedis will be
rebuilt (because there's a change within that component), and swss will
be rebuilt (because it's a direct dependency), but
docker-swss-layer-buster will not get rebuilt, because only the direct …
> Fix calculation of $(1)_DEP_PKGS_SHA in Makefile.cache

- push_docker.sh
- src/sonic-build-hooks/scripts/buildinfo_base.sh
[[ci] Support multi tags when pushing docker image](https://github.com/Azure/sonic-buildimage/pull/10771)
[Fix docker-sonic-mgmt reproducible related issue. ](https://github.com/Azure/sonic-buildimage/pull/9647)
[[build] docker-sonic-mgmt replace USER by whoami ](https://github.com/Azure/sonic-buildimage/pull/9702)
> Cherry-pick some PRs from master branch.

- .azure-pipelines/run-test-template.yml
- azure-pipelines.yml
Existing pools cannot test MACsec scenario, So I add sonictest-sonic-t0 pool that can run MACsec testcases.
Add `sonictest-sonic-t0` to azurepipelines.yml
Check Azp status
> [azurepipelines]Add pool: sonictest-sonic-t0

- src/sonic-yang-models/tests/yang_model_tests/tests/bgp_voq_chassis_neighbor.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp_voq_chassis_neighbor.json
- src/sonic-yang-models/yang-models/sonic-bgp-voq-chassis-neighbor.yang
Fixes #10793 
Removed the `switch_type` validation from the Yang model.
compile `sonic_yang_mgmt-1.0-py3-none-any.whl` and `sonic_yang_mgmt-1.0-py3-none-any.whl`
> remove voq chassis check

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml
- src/sonic-config-engine/tests/test_j2files.py
There is a need to select different mmu profiles based on deployment type
There will be separate subfolders (RDMA-CENTRIC, TCP-CENTRIC, BALANCED) in each hwsku folder which contains deployment specific mmu and qos settings. SonicQosProfile attribute in the minigraph will be used to determine which settings to use. If that attribute is not present, the default settings that exist in the hwsku folder will be used
Manually verified by creating subfolders under DX010 folder and updated minigraph on the device with SonicQosProfile pointing to one of the subfolders. Verified by loading minigraph and confirming the mmu and ecn settings are as expected.
Unit tests have been updated to include the SonicQosProfile attribute in the minigraphs used for buffer and qos rendering. Since the dir …
> [201811] Minigraph parser changes to select mmu profiles based on SonicQosProfile attribute

- src/sonic-config-engine/tests/sample-graph-resource-type.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/simple-sample-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
Previous subport unit tests uses port channel names like `PortChannel01`, so for subport name generated `PortChannel01.10`, it exceeds Linux network interface name 15 char limit.
Modify `PortChannel01` to `PortChannel1`.
> [sonic-config-gen] Modify lag names to enforce 15 chars limit

- files/build_templates/init_cfg.json.j2
- files/build_templates/lldp.timer.j2
- files/build_templates/per_namespace/lldp.service.j2
- files/build_templates/per_namespace/lldp.timer.j2
- files/build_templates/sonic_debian_extension.j2
- files/scripts/syncd.sh
- slave.mk
This PR is to backport a fix https://github.com/Azure/sonic-buildimage/pull/10568
This PR is dependent on PR: https://github.com/Azure/sonic-buildimage/pull/10745
Profiling the system state on init after fast-reboot during create_switch function execution, it is possible to see few python scripts running at the same time.
This parallel execution consume CPU time and the duration of create_switch is longer than it should be.
Following this finding, and the motivation to ensure these services will not interfere in the future, LLDP is delayed in 90 seconds until the system finish the init flow after fastboot.
Add a timer for LLDP service.
Copy the timer file to the host bin image.
Run fast-reboot on MLNX platform and observe faster create_switch execution time.
> [202012] [Fastboot] Delay LLDP service for better fastboot performance

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
This is part of HLD  Azure/SONiC#925
Add link-training support
Update SONiC YANG for port link-training support
Add "link_training" to sonic-port.yang
https://github.com/sonic-net/SONiC/wiki/Configuration#port
> sonic-port.yang: add link training support

- .azure-pipelines/azure-pipelines-image-template.yml
- .azure-pipelines/trigger-publish-artifacts-build.yml
Support to trigger a pipeline to download and publish artifacts to storage and container registry.
Support to specify the patterns which docker images to upload.
Pass the pipeline information and the artifact information by pipeline parameters to the pipeline which will be triggered a new build. It is to decouple the artifacts generation and the publish logic, how and where the artifacts/docker images will be published, depends on the triggered pipeline.
Trigger a new pipeline:
```
2022-05-12T12:43:24.1163401Z Found parameter artifactContext with value: {"artifactName":"sonic-buildimage.broadcom", "artifactPatterns":"**/*.bin\n
2022-05-12T12:43:24.1164110Z         **/*.swi\n
2022-05-12T12:43:24.1164377Z         **/*.raw\n
2022-05-12T12:43:24.1164840Z         **/*-rpc.gz\n …
```
> [Ci] Support to trigger a pipeline to download and publish artifacts to storage

- src/sonic-yang-models/doc/Configuration.md
Update Configuration doc: fix separator and indentation
> Update Configuration doc: fix separator and indentation

- platform/broadcom/sai.mk
What:
Updated BRCM SAI Version to 3.7.6.1-1
Why:-
Following fixes:
```
CS00012204307 SID articleid=25192/SDK-233993 & SDK-260647
CS00012182148,SONIC-46555:Rate Limit Parity error message to syncd/sonic
SONIC-47434:(SID) Integrate SDK patch from SDK-261158, SDK-258005
CS00012208995,SONIC-48752:Reconfigure MMU Buffer and OBM settings after port speed change
CS00012229816,SONIC-56721:Segmentation fault in DMA timeout retry, need uplift for SDK-286668
CS00012239291,SONIC-60152:RFE - throttle ECC events based on sai_switch_ecc_event_throttle soc property setting
Pick up fixes (CS00012204307,CS00012182148,SONIC-47434:(SID),CS00012208995,CS00012225760,CS00012229816,CS00012239291) and manual default not to report correctable ECC error via syslog
```
How I verify:
Basic Sanity looks good. Run …
> [201911] Updated Broadcom SAI version to 3.7.6.1-1

- src/scapy.patch/0003-Do-not-resolve-the-interface-name-globally.patch
- src/scapy.patch/series
PR #10457 introduces a known scapy bug (https://github.com/secdev/scapy/issues/3191). The bug is fixed upstream in scapy here (https://github.com/secdev/scapy/pull/3240) but is not available in a release yet. This bug causes the `tunnel_packet_handler` to fail silently, causing the test `dualtor/test_tunnel_memory_leak.py` to fail.
Add a patch for the bug fix into the existing series of patches applied to scapy.
Run `dualtor/test_tunnel_memory_leak.py` and ensure it passes
> [scapy]: Patch scapy 2.4.5 for sniffing on intfs

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Script fails when there is an exception while reading
Add more logs and checks. Fix wrong variable naming and messages.
Provoke exception while **read_eeprom()** and check that it is handled properly
> [Mellanox] Credo Y-cable | add more log info, checks, fix exception message

- platform/broadcom/sai.mk
- slave.mk
To fix compilation issue on libsaithrift on brcm image
Updated libsaibcm to install SAI experimental files at correct location
Compilation goes fine after the change. Also loaded the image on DUT to verify basic things.
Updated libsaibcm to fix libsaithrift compile issue on BRCM image
> Updated libsaibcm to fix libsaithrift compile issue on BRCM image

- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py
SFP mgmt-test case was failing in Dell S6100.
Added type_abbrv_name to resolve the issue.
Execute SFP mgmt-test case and verify whether TC passes.
UT log: 
[SFP_UT.txt](https://github.com/Azure/sonic-buildimage/files/8699308/SFP_UT.txt)
SFP mgmt TC: 
[test_sfp_log.txt](https://github.com/Azure/sonic-buildimage/files/8699315/test_sfp_log.txt)
> Dell S6100: Addition of SFP type_abbrv_name field

- .azure-pipelines/azure-pipelines-image-template.yml
- .azure-pipelines/trigger-publish-artifacts-build.yml
It is not necessary to trigger the publish pipeline when build is failed.
Remove the condition in the azp task, change to use template condition.
> [Ci]: Fix to trigger the publish pipeline in failure build issue

- platform/mellanox/hw-management/0004-Make-SONiC-system-health-service-service-start-after.patch
Error message: "ERR healthd: Failed to read from file /var/run/hw-management/led/led_status_capability" is observed during system starting
The system-health daemon will wait for 5 minutes before it starts to run.
During this time, the only thing it does is to set the LED even before it starts.
However, the corresponding sysfs has not been ready at the time it is being read, which causes the error message.
Defer system-health daemon until hw-management service starts
Run regression test
> [202111] [Mellanox] Fix issue: error message from system-health daemon is observed during system starting

- platform/marvell-armhf/sai.mk
Addressed system-health failure, when src-mac learned same as switchMac when two ports connected in fiber-loopback
Signed-off-by: rajkumar38 <rpennadamram@marvell.com>
system-health status goes to "NOT OK" state on connecting two ports in fiber loop-back in l2 topology.
Drop FDB mac notification to NOS when learned src mac address is same as switch mac address.
sonic-cfggen -H -k Nokia-7215 –preset l2
> [Marvell] Marvell armhf SAI debian

- .azure-pipelines/run-test-template.yml
The pool `t0-sonic` isn't stable.
Follow the PR: https://github.com/Azure/sonic-mgmt/pull/5577 to ignore the result in PR status.
Check Azp status.
> [Azp]: Ignore the result of t0-sonic pool

- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/chassis.py
Reboot cause is not updated properly in DellEMC S5232f.
Modified chassis.py to fix the issue
Execute different reboot methods and confirm the behavior.
UT: 
[reboot_cause UT.txt](https://github.com/Azure/sonic-buildimage/files/8650377/reboot_cause.UT.txt)
> DellEMC: S52xx Reboot cause fix

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
To further add `cable_type` and `soc_ipv4` field to table `MUX_CABLE`, this PR tries to parse minigraph like the following:
```
<Device i:type="SmartCable">
<ElementType>SmartCable</ElementType>
<SubType>active-active</SubType>
<Address xmlns:d5p1="Microsoft.Search.Autopilot.NetMux">
<d5p1:IPPrefix>192.168.0.3/21</d5p1:IPPrefix>
</Address>
<AddressV6 xmlns:d5p1="Microsoft.Search.Autopilot.NetMux">
<d5p1:IPPrefix>::/0</d5p1:IPPrefix>
</AddressV6>
<ManagementAddress xmlns:d5p1="Microsoft.Search.Autopilot.NetMux">
<d5p1:IPPrefix>0.0.0.0/0</d5p1:IPPrefix>
</ManagementAddress>
<ManagementAddressV6 xmlns:d5p1="Microsoft.Search.Autopilot.NetMux">
<d5p1:IPPrefix>::/0</d5p1:IPPrefix>
</ManagementAddressV6>
<SerialNumber i:nil="true" />
<Hostname>svcstr-7050-acs-1-Servers0-SC</Hostname>
</Device> …
```
> [dualtor][minigraph.py] Add `soc_ipv4` and `cable_type` to `MUX_CABLE`

- dockers/docker-macsec/cli-plugin-tests/conftest.py
- dockers/docker-macsec/cli-plugin-tests/test_config_macsec.py
- dockers/docker-macsec/cli/config/plugins/macsec.py
There is a bug that the Port attributes in CONFIG_DB will be cleared if using `sudo config macsec port add Ethernet0` or `sudo config macsec port del Ethernet0`
To fetch the port attributes before set/remove MACsec field in port table.
Check Azp.
> [macsec-cli]: Fixing to config MACsec on the port will clear port attributes in config db

- dockers/docker-dhcp-relay/cli-plugin-tests/test_show_dhcp6relay_counters.py
- dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py
- src/dhcp6relay/src/relay.cpp
- src/dhcp6relay/src/relay.h
Fixed option parsing function and added missing dhcpv6 messages.
Confirm message type was not added in PR https://github.com/Azure/sonic-buildimage/pull/10486 when client side message types are checked.
> [dhcp6relay] Fix option parsing and add dhcpv6 client messages

- platform/mellanox/hw-management/0001-set_psu_led_to_green_in_init.patch
As a result of race condition, PSU led may appear as red.
This fix set the PSU led color to green on init.
Add a new patch for hw-mgmt package to set led color to green in init.
Build SONiC image for Nvidia platform and observe PSU led set to green on init.
> [Mellanox] [hw-mgmt] [201911] Add a new patch to set PSU led to green on init by hw-mgmt package

- device/celestica/x86_64-cel_e1031-r0/sonic_platform/psu.py
- device/celestica/x86_64-cel_e1031-r0/sonic_platform/thermal.py
Fix snmp test case(snmp/test_snmp_phy_entity.py) failed.
Update the return value of the get_position_in_parent method in psu.py and thermo.py.
Rerun test case to verify.
> [device/celestica]:Fix failed test case of Haliburton snmp 

- src/sonic-config-engine/tests/sample-graph-resource-type.xml
To ensure that some internal testcases do not break due to external changes
Ran test_cfggen.py with the changes and it passed
> [sonic-config-engine] Change hwsku for sample graph in unit tests

- build_debian.sh
- files/build_templates/sonic_debian_extension.j2
This reverts commit 15cf9b0d70b3d839a40a06cec6b6fc10124017ae.
Revert the PR #10775, for it has impact on onie installation.
It is caused by the symbol links not supported in some of the onie unzip.
We will enable after fixing the issue, see https://github.com/Azure/sonic-buildimage/pull/10914
> Revert "Reduce image size for lazy installation packages (#10775)"

- src/sonic-fips/Makefile
It is to improve the build performance, when building multiple targets.
The modified time of downloaded files should be not older than the file .platform.
If not, the file will be downloaded again, when building any dependent targets.
When downloading the packages from web site, the modified time will be changed by the command "touch".
> [Build] Touch the download files to change the modified time

- src/sonic-yang-models/tests/files/sample_config_db.json
For yang model, sample_config_db.json file was missing Sample data for the features SNAT/DNAT/IPMC
Added the SNAT,DNAT,IPMC(low Threshold/high threshold/threshold_type)entries in CRM table.
With sanity Build/test only.
> Add crm sample data for snat/dnat/ipmc entries for Yang Model

- src/sonic-yang-models/tests/files/sample_config_db.json
Adding sample configuration for ACL_TABLE_TYPE
Adding sample tables in sample_config_db.json
Existing UT infrastructure verifies it against yang model during build.
> [yang]Adding Sample configuration for ACL_TABLE_TYPE

- src/sonic-config-engine/tests/sample-graph-resource-type.xml
There was a typo in hwsku specified as part of #10889
Replaced with the correct hwsku
test_cfggen.py is passing
> [sonic-config-engine] Fix typo in hwsku name in sample graph

- platform/mellanox/docker-syncd-mlnx/Dockerfile.j2
syncd is linking to libasan v6 during build after the bullseye upgrade (https://github.com/Azure/sonic-buildimage/pull/10580) and libasan v5 is installed in the syncd container for the mellanox platform which is causing runtime errors.
Install libasan6 on docker-syncd-mlnx
Build sonic with `ENABLE_ASAN=y` and verify syncd starts successfully. 
Upgrade libasan to version 6 in docker-syncd-mlnx to align with bullseye libasan
> Upgrade libasan to version 6 in docker-syncd-mlnx to align with bullseye libasan

- src/sonic-build-hooks/scripts/buildinfo_base.sh
- src/sonic-build-hooks/scripts/pre_run_buildinfo
It is to fix issue: https://github.com/Azure/sonic-buildimage/issues/10952
[Build]: Support to use the base image version when a package version not specified
Cherry-pick to 202012 to verify it as below:
https://dev.azure.com/mssonic/build/_build/results?buildId=104102&view=results
https://dev.azure.com/mssonic/build/_build/results?buildId=104100&view=results
> [Build]: Support to use the base image version when a package version not specified

- .azure-pipelines/azure-pipelines-image-template.yml
To help debug building timeout issues.
publish logs when azp canceled.
> [ci] Publish logs when building image job is canceled by timeout.

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case-remap-disabled.xml
- src/sonic-config-engine/tests/simple-sample-graph-case-remap-enabled.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
Signed-off-by: bingwang <wang.bing@microsoft.com>
This PR is to cherry-pick PR#10877 into `202012` branch after resolving conflicts.
This PR is to define a new table `SYSTEM_DEFAULTS`  to turn on/off new features in SONiC.
Currently, only the flag to turn on/off `tunnel_qos_remap` is in the new table.
HLD https://github.com/sonic-net/SONiC/pull/982
1. Define a new section in `minigraph.xml`
```
<SystemDefaultsDeclaration>
<a:SystemDefaults xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.Search.Autopilot.Evolution">
<a:SystemDefault>
<a:Name>TunnelQosRemapEnabled</a:Name>
<a:Value>True</a:Value>
</a:SystemDefault>
</a:SystemDefaults>
</SystemDefaultsDeclaration>
```
2. Update `minigrapg.py` to parse the new section, and write into `config_db`.
3. The Tunnel Qos remapping feature …
> [202012][cherry-pick] Define `SYSTEM_DEFAULTS` table to control tunnel_qos_remap

- src/sonic-build-hooks/scripts/buildinfo_base.sh
Some of the PRs are missed to cherry-pick to the 202111 branch.
[build] docker-sonic-mgmt replace USER by whoami (Azure#9702)
[Build]: Fix pip version constraint conflict issue (Azure#10525)
> [Build]: fix build version conflict issue in 202111 branch

- platform/broadcom/sonic-platform-modules-cel/services/fancontrol/fancontrol
[SONiC-CEL]: fix platform fancontrol testcase failure issue
1. fix platform fancontrol testcase failure
Running fancontrol platform test case would kill fancontrol daemon directly, the exit logic in fancontrol process detection logic would cause fancontrol daemon could not been pull up by supervisord and lead to the fancontrol daemon fail to start after the test case.
Run pmon fancontrol test cases, all cases would successfully pass.
```
$ ./run_tests.sh -d cel-e1031-01 -n cel_e1031_t0 -t t0,any -u -c platform_tests/daemon/test_fancontrol.py
platform_tests/daemon/test_fancontrol.py::test_pmon_fancontrol_running_status PASSED                            [ 25%]
platform_tests/daemon/test_fancontrol.py::test_pmon_fancontrol_stop_and_start_status PASSED                     [ 50%] …
```
> [SONiC-CEL]: fix platform fancontrol testcase failure issue

- build_image.sh
- files/Aboot/boot0.j2
- installer/arm64/install.sh
- installer/armhf/install.sh
- platform/centec-arm64/platform.conf
- platform/marvell-arm64/platform.conf
- platform/marvell-armhf/platform.conf
Support symcrypt fips config for aboot/uboot
For uboot, use fw_setenv to variable linuxargs to change the boot options.
```
fw_setenv linuxargs "$OTHER_OPTIONS sonic_fips=1"
```
For Aboot, add the config in /host/image-{version}/kernel-cmdline, example:
```
reboot=p console=ttyS0 acpi=on Aboot=Aboot-norcal7-7.2.0-pcie2x4-6128821 <other parameters...> sonic_fips=1
```
Download the image sonic-aboot-broadcom.swi from the pipeline in the PR checks. The sonic_fips=1 can be found in /proc/cmdline
```
Aboot# boot sonic-aboot-broadcom.swi
448.25: Cleaning flash content /mnt/flash
448.25: Generating boot-config, machine.conf and cmdline
448.41: Installing image under /mnt/flash/image-master-10729.100664-f781129cc
...
oot@sonic:/host/image-master-10729.100664-f781129cc# cat kernel-cmdline …
```
> Support symcrypt fips config for aboot/uboot

- src/sonic-host-services/scripts/hostcfgd
- src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- src/sonic-host-services/tests/hostcfgd/test_vectors.py
Recently the nightly testing pipeline found that the `autorestart` test case was failed when it was run against **master** image. The reason is `Restart=` field in each container's systemd configuration file was set to `Restart=no` even the value of `auto_restart` field in `FEATURE` table of `CONFIG_DB` is `enabled`. 
This issue introduced by https://github.com/Azure/sonic-buildimage/pull/10168 can be reproduced by the following steps:
1. Issues the `config` command to disable the `auto-restart` feature of a container
2. Runs command `config reload` or `config reload minigraph` to enable `auto-restart` of the container
3. Checks `Restart=` field in the container's systemd config file mentioned in step 1 by running the command 
`sudo …
> [hostcfgd] Initialize `Restart=` in feature's systemd config by the value of `auto_restart` in `CONFIG_DB`

- platform/broadcom/sonic-platform-modules-dell/common/ipmihelper.py
- platform/broadcom/sonic-platform-modules-dell/common/onie_stage_fwpkg
- platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
To update the available and current firmware versions provided by Component APIs (backport #10187)
Update the platform API methods in component.py
Verified that component data is displayed by show platform firmware status.
Logs:[UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/8813396/UT_logs.txt)
[202012] DellEMC: Z9332f - Component API Fixes
> [202012][cherry-pick] DellEMC: Z9332f - Component API Fixes

- platform/centec-arm64/sai.mk
- platform/centec/sdk.mk
Change makefile to reference to new SAI debian package of v1.10.1-0
Modify sai.mk of arm64 platform and sdk.mk of x86 platform for Centec
> update centec-sai reference to v1.10.1-0

- src/dhcp6relay/src/relay.cpp
- src/dhcp6relay/src/relay.h
(cherry picked from commit https://github.com/Azure/sonic-buildimage/commit/cfdb8431df86105698eabe9e5e1ee112c06fd7db)
(cherry picked from commit https://github.com/Azure/sonic-buildimage/commit/2ead3aaefc1c20ff987faab6133accdff43de122)
To prevent relaying client packets with malformed payload
Check for invalid dhcpv6 options
> [dhcp6relay] Add dhcpv6 option check

- azure-pipelines.yml
Some PR test are timing out on T1-lag kvm test.
Increase the timeout to 5 hours.
Test on this PR.
> [pr test] increase T1-lag PR test timeout to 5 hours

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_pool_sizes_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_pool_sizes_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/buffers_pool_sizes_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_pool_sizes_t0.j2
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7260-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7260-t1.json
- src/sonic-config-engine/tests/test_j2files.py
As part of PCBB changes, we need to enable 2 extra lossless queues. The changes in this PR are done to adjust only the reserved sizes on Th2 for the additional 2 lossless queues
Calculations are done based on 40 downlinks for T1 and 16 uplinks for dual ToR
- Verified that the rendering works fine on Th2 dut
- Unit tests have been updated to reflect the modified buffer sizes when pcbb is enabled. There are existing testcases that will test the original buffer sizes when pcbb is disabled. With these changes, was able to build sonic-config-engine wheel successfully
> Adjust 7260 buffer sizes to accomodate extra lossless queues

- scripts/build_debian_base_system.sh
[Build]: Fix the version files in host-base-image for armhf/arm64 not used issue
https://dev.azure.com/mssonic/build/_build/results?buildId=105620&view=logs&j=88e1b2d1-110a-5bbf-c794-091704096bca&t=41cf5733-fbe6-5db0-23ba-ae081db3aefb
```
+ scripts/build_debian_base_system.sh arm64 bullseye ./fsroot-centec-arm64
E: Version '8.32-4+b1' for 'coreutils' was not found
```
The version "8.32-4+b1" is not as expected, the correct version should be "8.32-4", see https://github.com/Azure/sonic-buildimage/blob/ca284a1bf2bcdb65dd67d5d739dd6a68021f65f7/files/build/versions/host-base-image/versions-deb-bullseye-arm64#L1
See the test on 202111 branch: https://dev.azure.com/mssonic/build/_build/results?buildId=105896&view=results
> [Build]: Fix the version files for armhf/arm64 not used issue

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7260-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7260-t1.json
- src/sonic-config-engine/tests/simple-sample-graph-case-remap-enabled-no-tunnel-attributes.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
Signed-off-by: bingwang <wang.bing@microsoft.com>
This PR is to update `minigraph.py` to generate necessary qos remap attributes for mux tunnel.
The auto generated attributes are
```
"decap_dscp_to_tc_map": "[DSCP_TO_TC_MAP|AZURE_TUNNEL]",
"decap_tc_to_pg_map": "[TC_TO_PRIORITY_GROUP_MAP|AZURE_TUNNEL]",
"encap_tc_to_dscp_map": "[TC_TO_DSCP_MAP|AZURE_TUNNEL]",
"encap_tc_to_queue_map": "[TC_TO_QUEUE_MAP|AZURE_TUNNEL]"
```
The `dscp_mode` is hardcoded to `pipe` if `tunnel_qos_remap` is enable.
Update `minigraph.py`.
Verified by adding a new test scenario.
Automatically generate extra attributes for tunnel qos remapping.
> [202012] Automatically generate extra attributes for tunnel qos remapping

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_pool_sizes_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/buffers_pool_sizes_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/buffers_pool_sizes_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_pool_sizes_t0.j2
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7260-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7260-t1.json
- src/sonic-config-engine/tests/test_j2files.py
> [202012] Adjust 7260 buffer sizes to accomodate extra lossless queues

- device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot
- device/mellanox/x86_64-nvidia_sn2201-r0/ACS-SN2201/sai_2201.xml
1. SN2201 sai profile needs to be updated according to the latest hardware.
2. In the reboot script, need to use the common symbol link of the power_cycle sysfs instead of directly accessing it due to SN2201 sysfs is different than other platforms.
3. `echo 1 > $SYSFS_PWR_CYCLE` will trigger the reboot immediately, the following `sleep 3` and `echo 0 > $SYSFS_PWR_CYCLE` will never be executed, can be removed.
1. Replace the SN2201 sai profile with the latest one.
2. In the platform_reboot script, replace the direct sysfs path with the symbol link path.
3. Remove the redundant code from platform_reboot
Perform reboot on all the Nvidia platforms, and check all can be rebooted successfully.
> [Mellanox] Update SN2201 sai profile and platform reboot script

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
"import sonic_platform" takes about 600ms ~ 1000ms, it is kind of slow. After this optimization, the time is about 100ms. The benefit is that those CLIs which does not need the slow import sentence would be faster than before.
Find slow import and call them when need.
Measure the import time.
> [Mellanox] optimize platform API import time

- scripts/build_debian_base_system.sh
[Bug]: fix the version file name issue
Fix the build failure: https://dev.azure.com/mssonic/build/_build/results?buildId=107211&view=results
```
+ scripts/build_debian_base_system.sh amd64 bullseye ./fsroot-centec
sed: can't read /tmp/tmp.glTzJefV24/version-deb: No such file or directory
Not found host-base-image packages, please check the version files in files/build/versions/host-base-image
```
Change the version-deb, to versions-deb
And add an improvement for host base image build, if the version path not exist, skipped the version control for base image.
https://dev.azure.com/mssonic/build/_build/results?buildId=107587&view=results
> [Bug]: fix the version file name issue

- Makefile.work
Make reset didn't clean-up all fsroot folders.
Remove all fsroot folders used during build.
Run local build and local make reset:
sudo mkdir fsroot-test
sudo touch fsroot-test/foo
make reset
(Without this change, make reset cannot remove fsroot-foo, with the change, the repo become clean after make reset.)
> [makefile] remove all fsroot folders

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-arista-7050cx3-dualtor-minigraph.xml
- src/sonic-config-engine/tests/sample-arista-7260-dualtor-minigraph.xml
- src/sonic-config-engine/tests/sample-arista-7260-t1-minigraph.xml
- src/sonic-config-engine/tests/simple-sample-graph-case-remap-disabled.xml
- src/sonic-config-engine/tests/simple-sample-graph-case-remap-enabled-no-tunnel-attributes.xml
- src/sonic-config-engine/tests/simple-sample-graph-case-remap-enabled.xml
Signed-off-by: bingwang <wang.bing@microsoft.com>
This PR is to enable `tunnel_qos_remap` on `T1` and `T0` in DualToR deployment.
On T1, we check the property `DownstreamRedundancyTypes`. On T0, we check the property `RedundancyType`.
`tunnel_qos_remap` is set to `enabled` if `gemini` is in  `DownstreamRedundancyTypes` (on T1) or `RedundancyType` (on T0).
The change is implemented in `minigraph.py`.
Verified by `test_minigraph_case.py` and 'test_j2files.py`.
Automatically enable tunnel_qos_remap on T1 and T0 in DualToR deployment.
> [202012] Automatically enable tunnel_qos_remap on T1 and T0 in DualToR deployment

- platform/broadcom/sonic-platform-modules-dell/s5212f/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-dell/s5248f/scripts/s5248f_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/sfp.py
Chassis initialization in S5248f is taking longer time.
Loaded native optic drivers in platform init script
Check SFP output in python3 interpreter.
[S5248f_UT.txt](https://github.com/Azure/sonic-buildimage/files/8860262/S5248f_UT.txt)
> [DellEMC] Fix S5248f platform issues

- src/sonic-config-engine/tests/test_j2files.py
To address internal build failures where the cable len for some of the skus is set to 300m for all tiers. 
For the buffers test, generate a new output file based off the original expected output with CABLE_LENGTH table updated to use 300m. In the comparison logic, compare against each of the expected output files and if any matches, the testcase is set to pass
Build sonic-config-engine wheel with the changes
> [202012] [sonic-config-engine] Generate expected output with different cable len

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
Add yang model for configuring TX power and laser frequency of ZR transceiver module
```
root@sonic:~#  config interface transceiver tx_power Ethernet0 -- -27.3
Setting target Tx output power to -27.3 dBm on port Ethernet0
root@sonic:~# redis-cli -n 4 hgetall "PORT|Ethernet0"                  
1) "admin_status"
2) "up"
3) "alias"
4) "Ethernet1/1"
5) "index"
6) "1"
7) "lanes"
8) "1,2,3,4,5,6,7,8"
9) "laser_freq"
10) "170000"
11) "speed"
12) "400000"
13) "tx_power"
14) "-27.3"
root@sonic:~# 
```
```
root@sonic:~# config interface transceiver tx_power Ethernet0 -27   
Usage: config interface transceiver tx_power [OPTIONS] <interface_name> <tx-
power>
Try "config interface transceiver tx_power -h" for help.
Error: no such option: -2
root@sonic:~# config interface transceiver frequency …
```
> Yang model for xcvr tx power and frequency configuration

- build_image.sh
- platform/marvell-armhf/platform.conf
This fixes the build for armhf to be able to use '/device/<company>/<platform>/installer.conf' files.  Specifically, armhf needs support to be able to change the size of /var/log/ directory.  It is hardcoded to 512 bytes on all armhf platforms currently.  This change will allow any armhf platform to be able to use an installer.conf file to customize the installed image.
Build and verify that armhf platform installer.conf is used.
This fixes the build for armhf to be able to use /device/\<company\>/\<platform\>/installer.conf files.
> fix armhf for installer.conf usage

- .github/pull_request_template.md
> [github]: update pr template to include 202205 backport option

- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh
To port DellEMC S6100 SSD upgrade status checker changes from master (based on https://github.com/Azure/sonic-buildimage/pull/7289) to 201811 branch
- Handle newer SSD firmware version (S210506G - 3IE devices)
- Recover SSD upgrade state if in case ssd_fw_upgrade folder got deleted
Update `s6100_ssd_upgrade_status.sh`.
Logs: [201811_SSD_status_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/8786672/201811_SSD_status_UT_logs.txt)
[201811] DellEMC S6100 - Port SSD upgrade status checker changes
> [201811] DellEMC S6100 - Port SSD upgrade status checker changes

- platform/barefoot/sonic-platform-modules-bfn-montara/configs/network/interfaces.d/usb0
- platform/barefoot/sonic-platform-modules-bfn-newport/configs/network/interfaces.d/usb0
- platform/barefoot/sonic-platform-modules-bfn/configs/network/interfaces.d/usb0
Signed-off-by: Taras Keryk <tarasx.keryk@intel.com>
In some situations, the connection to the BMC may be lost when the ip settings differ on the BMC and CPU (SONiC) sides
I changed ipv6 neighbor base_reachable_time_ms on the CPU (SONiC). Currently, base_reachable_time_ms  on the CPU and BMC sides will be the same.
> [BFN] Fixed settings for BMC interface

- device/mellanox/x86_64-mlnx_msn2700-r0/pmon_daemon_control.json
The community introduced a CMIS cable sub-task to the XCVRD daemon to take care of the CMIS cable initializing work, which is not required on the Mellanox platform due to the different ways of managing the CMIS cable. Detail info please check PR https://github.com/sonic-net/SONiC/pull/971
Set flag 'skip_xcvrd_cmis_mgr' to true in  pmon_daemon_control.json for all the Mellanox platforms.
Check CMIS task is not started on Mellanox platforms.
> [Mellanox] Add flag 'skip_xcvrd_cmis_mgr' to skip CMIS task on Mellanox platform

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/config.bcm.j2
- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/config.bcm.j2
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-C32/th-a7060-cx32s-32x100G-t1.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-D48C8/th-a7060-cx32s-8x100G+48x50G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q24C8/th-a7060-cx32s-8x100G+24x40G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t0.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t1.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-T96C8/th-a7060-cx32s-8x100G+96x25G.config.bcm
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t1.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm
- src/sonic-device-data/tests/permitted_list
According to this PR https://github.com/Azure/sonic-buildimage/pull/7547, we need to add 'phy_an_lt_msft' attribute to bcm config files to be consistent with 202012 branch settings.
- Add 'phy_an_lt_msft' to BCM config permitted list.
- Set 'phy_an_lt_msft' attribute in bcm config files of some Broadcom-based platforms [Arista 7060CX, 7260CX3, 7050cx3, Celestica DX010].
> [AN/LT][Enable]:enable phy_an_lt_msft attribute on broadcom platforms

- build_debian.sh
SSHD keepalive timeout feature not enabled on sonic.
Enable SSHD keepalive timeout feature by set ClientAliveCountMax to 1.
Pass All E2E test case.
Manually test with following steps:
1. Change config and restart sshd
2. Connect a ssh with -vvv option to show debug message
3. Get running ssh by command and stop it:
```
azureuser@liuh-dev-vm-02:~$ ps -auxww | grep vvv
azureus+ 1614153  0.0  0.0  12244  6004 pts/1S+   15:48   0:00 ssh admin@10.250.0.101 -vvv
azureus+ 1615570  0.0  0.0   8168  2424 pts/3S+   15:49   0:00 grep --color=auto vvv
azureuser@liuh-dev-vm-02:~$ kill -Stop 1614153
```
4. Check TCP status from server side with ss command:
https://man7.org/linux/man-pages/man8/ss.8.html
```
admin@vlab-01:~$ ss | grep -i ssh
tcp   ESTAB  0  010.250.0.101:ssh 10.250.0.1:58150
tcp …
```
> [SSHD] Enable SSHD keepalive timeout feature.

- platform/broadcom/sai.mk
- Enable Microsoft AN/LT patch
> [202205][bcm sai] upgrade Broadcom SAI to 7.1.0.0-5

- .azure-pipelines/azure-pipelines-build.yml
- .azure-pipelines/template-skipvstest.yml
- .azure-pipelines/vstest-exclude
- .azure-pipelines/vstest-include
- azure-pipelines.yml
Some changes didn't change vs image. We should not run vstest in such cases.
```
example:
├── folderA
│  ├──  fileA (skip vstest)
│  ├──  fileB
│  └──  fileC
If we want to skip vstest when changing /folderA/fileA, and not skip vstest when changing fileB or fileC.
vstest-include:
^folderA/fileA
vstest-exclude:
^folderA
```
> [ci] Support to skip vstest using include/exclude config file.

- build_debian.sh
- files/build/versions/host-image/versions-deb-buster
- rules/openssh.mk
- sonic-slave-buster/Dockerfile.j2
- src/openssh/Makefile
Reverts Azure/sonic-buildimage#10910
Reason can be found in this issue: https://github.com/Azure/sonic-buildimage/issues/11134
1. The change will cause armhf sshd failed to start
2. The change will introduce a double-free memory corruption issue (CVE-2021-28041)
> Revert "[202012][openssh] openssh: Upgrade from 7.9 to 8.4, to match version in buster-backports"

- dockers/docker-macsec/cli-plugin-tests/mock_tables.py
- dockers/docker-macsec/cli/show/plugins/show_macsec.py
To support gearbox macsec counter display, following https://github.com/Azure/sonic-swss-common/pull/622.
Use swsscommon CounterTable API
> [macsec] CLI Supports display of gearbox macsec counter

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/sai_postinit_cmd.soc
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/sai_postinit_cmd.soc
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_ndk.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/system_health_monitoring_config.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/platform.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_ndk.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_reboot
[Nokia][Nokia-IXR7250E] Update  Nokia-IXR7250E-SUP-10 & Nokia-IXR7250E-36x400G platform device data files and BCM config files
Updated platform and BCM config files to support the latest nokia platform changes.
updated Nokia-IXR7250E-SUP-10 & Nokia-IXR7250E-36x400G platform device data files and BCM config files
Verified OC tests pass with Nokia chassis
> Updated Nokia device BCM and platform config

- Makefile.cache
Docker image cache need involve package versions.
When we update version dependencies, we need to build new docker image. Loading from old cache may have unmatched dependencies.
Add version files to dpkg cache dependency file.
```
shilongliu@50adfce3534b:/sonic$ make -f slave.mk target/docker-database.gz -p > log
dpkg: error: cannot access archive 'amd64/buildinfo/sonic-build-hooks_*.deb': No such file or directory
cp: cannot stat 'amd64/buildinfo/*': No such file or directory
/bin/bash: line 4: /sonic/target/files/buster/sysctl-net.conf.log: No such file or directory
make: *** [slave.mk:335: target/files/buster/sysctl-net.conf] Error 1
shilongliu@50adfce3534b:/sonic$ grep "docker-database.gz_DEP_FILES " log    
docker-database.gz_DEP_FILES :=  .platform slave.mk rules/functions …
```
> [build] Add version files to docker image dependencies

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests/portchannel.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vlan.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vlan_sub_interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan_sub_interface.json
- src/sonic-yang-models/yang-models/sonic-interface.yang
- src/sonic-yang-models/yang-models/sonic-portchannel.yang
- src/sonic-yang-models/yang-models/sonic-vlan-sub-interface.yang
- src/sonic-yang-models/yang-models/sonic-vlan.yang
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Add IP interface loopback action related content to the required YANG models.
Update the relevant YANG models.
New unittests were added.
> Add IP interface loopback action related content to YANG models.

- files/image_config/config-setup/config-setup
- files/image_config/updategraph/updategraph
Minigraph will be deprecated in the future. So minigraph related reload should be deleted.
Remove unused load_minigraph
> Remove minigraph loading in script

- build_debian.sh
- files/Aboot/boot0.j2
- files/build_templates/sonic_debian_extension.j2
- installer/arm64/install.sh
- installer/armhf/install.sh
- installer/x86_64/install.sh
Support to use symbol links in platform folder to reduce the image size.
The current solution is to copy each lazy installation targets (xxx.deb files) to each of the folders in the platform folder. The size will keep growing when more and more packages added in the platform folder. For cisco-8000 as an example, the size will be up to 2G, while most of them are duplicate packages in the platform folder.
Create a new folder in platform/common, all the deb packages are copied to the folder, any other folders where use the packages are the symbol links to the common folder.
Why platform.tar?
We have implemented a patch for it, see https://github.com/Azure/sonic-buildimage/pull/10775, but the problem is the the onie use really old unzip version, cannot support the symbol links.
The current …
> [Build]: Support to use symbol links for lazy installation targets to reduce the image size

- .azure-pipelines/azure-pipelines-build.yml
- .azure-pipelines/template-skipvstest.yml
- .azure-pipelines/vstest-exclude
- .azure-pipelines/vstest-include
- Makefile.cache
- azure-pipelines.yml
Cherry pick PR from master:
[[build] Add version files to docker image dependencies](https://github.com/Azure/sonic-buildimage/pull/11179)
[[ci] Support to skip vstest using include/exclude config file. ](https://github.com/Azure/sonic-buildimage/pull/11086)
> Cherry-pick two PRs

- .azure-pipelines/run-test-template.yml
The t0-sonic pool has been fixed, so add it back to azp checker.
Remove continueOnError in run-test-template.yml.
Check Azp.
> [azurepipeline]: Add t0-sonic pool back to Azp checker

- files/image_config/interfaces/interfaces.j2
- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample_output/py2/two_mgmt_interfaces
- src/sonic-config-engine/tests/sample_output/py3/two_mgmt_interfaces
- src/sonic-config-engine/tests/t0-sample-graph-two-mgmt.xml
- src/sonic-config-engine/tests/test_j2files.py
Signed-off-by: George Chen gechen@microsoft.com
The interfaces template, interfaces.j2, currently hardcodes to eth0 and therefore cannot support multiple management interfaces.  This pull request introduces change to support multiple management interfaces.
1) Update interfaces.j2 to iterate over MGMT_INTERFACE where it is currently not, and refer to interface name rather than hardcoded eth0.
2) Update minigraph.py to process mgmt_intf in sorted order.  This is needed because in Python 3.x, the dictionary keys are presented in such a way that eth1 in [t0-sample-graph-two-mgmt.xml](https://github.com/Azure/sonic-buildimage/compare/master...geogchen:dev/gechen/multi_mgmt_interface?expand=1#diff-0a80119cc01db12d4686c311fc7be9281147ff487247d611610f4784e526f454) appears first, and it gets …
> Add support for generating interface configuration in /etc/network/interfaces for multiple management interfaces

- src/iccpd/src/scheduler.c
Signed-off-by: ouxiaolong <ouxiaolong@asterfusion.com>
The return statement does not end with a semicolon in function scheduler_csm_socket_cleanup, which generates a compilation warning and may cause unexpected problems.
the build log is like this:
```
scheduler.c: In function 'scheduler_csm_socket_cleanup':
scheduler.c:876:19: warning: 'return' with a value, in function returning void
event.data.fd = csm->sock_fd;
~~~~~~~~~~~~~~^~~~~~~~~~~~~~
scheduler.c:861:6: note: declared here
void scheduler_csm_socket_cleanup(struct CSM* csm, int location)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
add the missing semicolon
rebuild the iccpd.deb package and check the build log
> [iccpd] Fix missing semicolon.

- dockers/docker-orchagent/enable_counters.py
Backport form master
Appropriate PR on master: https://github.com/Azure/sonic-buildimage/pull/7735
Appropriate PR on master https://github.com/Azure/sonic-buildimage/pull/6444
PG drop counters should be enabled by default (merge from master)
After "config reload" or "docker swss restart" all counters were enabled even if they were disabled before
1)Add PG drop counter enable option to dockers/docker-orchagent/enable_counters.py
2) Check if entry already exist before set default values
1) install image and run `counterpoll show` CLI command and then you will see PG_STAT_DROP enabled
2) Disable few counters
```
counterpoll pg-drop disable
counterpoll port disable
```
3) Save and reload
```
config save
config reload
```
4) Check enable status
> Enable PG drop counters by default, set default values only on the first start

- dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
CMIS manager needs to be skipped if a platform wants to. The changes are as per the HLD:-
[https://github.com/sonic-net/SONiC/pull/971/](https://github.com/sonic-net/SONiC/pull/971/)
Platform provides input to supervisord via pmon_daemon_control.json to pass "skip_cmis_mgr" argument to Xcvrd while launching it
Use SN2700 platform to verify and ensure CMIS manager is not running.
> Skip CMIS manager

- src/system-health/health_checker/service_checker.py
There might be a case where service checker periodic operation determined that specific container is running but when it tries to perform an operation on it, it was already closed by the user. This is a valid flow and we should not log an error message, informative warning is enough. 
I reduce log severity.
I verified it manually.
> Change severity of log messages for cases where docker container was stopped during service checker operation

- files/build_templates/init_cfg.json.j2
- src/sonic-host-services/scripts/hostcfgd
Update the feature table in STATE_DB in database running in namespace for multi-asic platforms.
This will be used by features running in namespaces.
This is needed by features like https://github.com/Azure/sonic-swss/pull/2286, which need to know the state of feature before adding feature based condition
Also add the support to enable macsec when type == "SpineRouter"
Updated the init_cfg.json.j2 file and hostcfgd.
Verified with feature running in multiple namespaces
> Update include_macsec flag if type is SpineRouter

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml
- src/sonic-config-engine/tests/test_j2files.py
There is a need to select different mmu profiles based on deployment type
There will be separate subfolders (RDMA-CENTRIC, TCP-CENTRIC, BALANCED) in each hwsku folder which contains deployment specific mmu and qos settings. SonicQosProfile attribute in the minigraph will be used to determine which settings to use. If that attribute is not present, the default settings that exist in the hwsku folder will be used
> [201911] Minigraph parser changes to select mmu profiles based on SonicQosProfile attribute

- rules/sairedis.mk
- rules/syncd.mk
Fix the build with updated sairedis
Specify nopython2 for syncd and fixed a copy paste mistake for libsairedis
Run build with updated sairedis
> [sairedis] fix incorrect package specified in sairedis rules

- dockers/docker-orchagent/tunnel_packet_handler.py
This PR aims to add a whitespace in the warning syslog message of process `tunnel_packet_handler`.
This minor issue was found by an incident ticket.
I added a whitespace in the log string.
I tested on a lab device to intentionally raise an expection and check the fomrat of log messages in syslog.
`WARNING swss#tunnel_packet_handler.py: PEER_SWITCH or TUNNEL table not found in config DB`
- [ x] 202012
- [x ] 202111
- [ x] 202205
> [tunnel_packet_handler] Add a whitespace in the warning syslog message

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/feature.json
To address https://github.com/Azure/sonic-buildimage/issues/11110 - Add yang model unit test for check_up_status field type
Add check_up_status with different values in sample_config_db.json and
the field with correct and incorrect values in feature.json
Build sonic_yang_models-1.0-py3-none-any.whl
> Add yang model unit test for check_up_status field type

- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Fix https://github.com/Azure/sonic-buildimage/issues/11224
TCP_FLAGS supports `flags/mask` pattern. Refs https://github.com/Azure/sonic-utilities/blob/master/acl_loader/main.py#L574
Change the pattern.
Add unit test.
> [yang] update TCP_FLAGS format in sonic-acl.yang

- files/scripts/write_standby.py
Avoid write_standby in warm restart context.
In warm restart context, we should avoid mux state change. 
Check warm restart flag before applying changes to app db. 
* Ran write_standby in table missing, key missing, field missing scenarios. 
* Did a warm restart, app db changes were skipped. Saw this in syslog:  
`WARNING write_standby: Taking no action due to ongoing warmrestart.`
> Avoid write_standby in warm restart context 

- sonic-slave-bullseye/Dockerfile.j2
Fix issue
```
The following packages have unmet dependencies:
libssl-dev : Depends: libssl1.1 (= 1.1.1n-0+deb11u3) but 1.1.1n-0+deb11u2 is to be installed
E: Unable to correct problems, you have held broken packages.
```
libssl-1.1.1n-0+deb11u2 and u3 are located at bullseye-security.
Add bullseye-security in apt sources.
> [build] Fix libssl version issue.

- src/sonic-config-engine/tests/sample-port-data.json
- src/sonic-config-engine/tests/sample-ztp-inband-ip.json
- src/sonic-config-engine/tests/sample-ztp-inband.json
- src/sonic-config-engine/tests/sample-ztp-ip.json
- src/sonic-config-engine/tests/sample-ztp.json
- src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt
- src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp
- src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_inband
- src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_inband_ip
- src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_ip
- src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces_nomgmt
- src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt
- src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp
- src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_inband
- src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_inband_ip
- src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_ip
- src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces_nomgmt
- src/sonic-config-engine/tests/t0-sample-graph-mvrf-nomgmt.xml
- src/sonic-config-engine/tests/t0-sample-graph-nomgmt.xml
- src/sonic-config-engine/tests/t0-sample-port-config-tiny.ini
- src/sonic-config-engine/tests/test_j2files.py
The tests that are available for interfaces.j2 only covers the case when ZTP is disabled and MGMT_INTERFACE is defined.  This change adds unit tests for:
1) When ZTP is enabled, with combination of (ip enabled/disabled, inband enabled/disabled)
2) When ZTP is disabled, and MGMT_INTERFACE is not defined, with mgmtVrfEnabled set to true/false
I created multiple mock-up files to:
1) Enable/disable ZTP, and subconditions under ZTP
2) Created graph file that has no management interface defined
Compared output with interfaces.j2 template to ensure the output is expected.
> [Interfaces] Add more unit tests for interfaces.j2

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-device-desc-ipv6-only.xml
- src/sonic-config-engine/tests/simple-sample-device-desc.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
Signed-off-by: Jing Kan jika@microsoft.com
https://github.com/Azure/sonic-buildimage/pull/11095
> [cherry-pick][202012][minigraph] Support parse IPv6 in device_desc.xml (#11095)

- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
The build below was broken, it was caused by one of the required debian mirror missing.
https://dev.azure.com/mssonic/build/_build/results?buildId=116719&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=88f376cf-c35d-5783-0a48-9ad83a873284
```
libpci-dev : Depends: libudev-dev (>= 196) but it is not going to be installed
libsystemd-dev : Depends: libsystemd0 (= 232-25+deb9u14) but 232-25+deb9u13 is to be installed
```
Add the missing mirrors for buster and stretch.
> [Build] Add the missing debian security mirrors in slave images

- files/build_templates/init_cfg.json.j2
This PR #11141 introduced the template specific check for macsec feature to be enabled if 'type' is 'SpineRouter'. The rendering of init_cfg.json.j2 file is done by hostcfgd daemon.
Currently hostcfgd does update the feature state by template rendering only only in host config db. This fix was earlier verified only on single asic platforms.
Close issue https://github.com/Azure/sonic-buildimage/issues/11302
Removed the earlier fix and setting macsec to be disabled by default. Need to explicitly enable.
Will plan to bring this change in along with fixes in hostcfgd to update the feature state after rendeding in namespace config_db also. Need more testing in hostcfgd to add full namespace support there
> Revert "Update include_macsec flag if type is SpineRouter (#11141)"

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/tests/test_chassis.py
During the system boot up when 'show platform status' or 'show version' command is executed before STATE_DB CHASSIS_INFO table is populated, the show will try to fallback to use the platform API. The DMI file in mellanox platforms require root permission for access. So if the show commands are executed as admin or any other user, the following error log will appear in the syslog
Jun 28 17:21:25.612123 sonic ERR show: Fail to decode DMI /sys/firmware/dmi/entries/2-0/raw due to PermissionError(13, 'Permission denied')
Check the file permission before accessing it.
Added UT to verify. Manually verified if the error log is not thrown.
> [Mellanox]Check dmi file permission before access

- .azure-pipelines/azure-pipelines-build.yml
The asan-enabled docker image will be used in other CIs that run DVS tests.
To add a possibility to run DVS tests with ASAN for other CIs (e.g. swss).
Added the 'asan_image' flag to the vs job group.
Run the CI and check the docker-sonic-vs-asan.gz artifact.
> [ci][asan] add docker-sonic-vs with ASAN build

- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
Cherry-pick from https://github.com/Azure/sonic-buildimage/pull/11305
The build below was broken, it was caused by one of the required debian mirror missing.
https://dev.azure.com/mssonic/build/_build/results?buildId=116719&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=88f376cf-c35d-5783-0a48-9ad83a873284
```
libpci-dev : Depends: libudev-dev (>= 196) but it is not going to be installed
libsystemd-dev : Depends: libsystemd0 (= 232-25+deb9u14) but 232-25+deb9u13 is to be installed
```
Add the missing mirrors for buster and stretch.
> [Build][202111] Add the missing debian security mirrors in slave images (#11305)

- files/Aboot/boot0.j2
When performing a `warm-reboot` or `fast-reboot` from `201811` or `201911` to `202012` the kernel command line contains duplicate information.
This issue is related to a change that was made to make `202012` `boot0` file more futureproof.
A cold reboot brings everything back into a clean slate though not always desirable.
Added some logic to properly detect the end of the Aboot cmdline when `cmdline-aboot-end` delimiter is not set (clean case)
Added some logic to regenerate the Aboot cmdline when `cmdline-aboot-end` is set but duplicate parameters exists before (dirty case)
Reorganized  some code to handle duplicate parameter handling in the allowlist.
Clean case (device only ran and installed 201811 and 201911, first installation of 202012)
- Cold boot into `201811`
- Install `202012`
- …
> [202012][Arista] Fix cmdline generation during warm-reboot from 201811/201911

- platform/centec-arm64/sai.mk
Fix Centec-Arm64 compile error, Centec SAI Dev package reference is error
Modify sai.mk of arm64 platform  for Centec
> for fixing centec-arm64 compile error

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
To further support parse out `soc_ipv4` and `soc_ipv6` out of `Dpg`:
```
<DeviceDataPlaneInfo>
<IPSecTunnels />
<LoopbackIPInterfaces xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.Search.Autopilot.Evolution">
<a:LoopbackIPInterface>
<ElementType>LoopbackInterface</ElementType>
<Name>HostIP</Name>
<AttachTo>Loopback0</AttachTo>
<a:Prefix xmlns:b="Microsoft.Search.Autopilot.NetMux">
<b:IPPrefix>10.10.10.2/32</b:IPPrefix>
</a:Prefix>
<a:PrefixStr>10.10.10.2/32</a:PrefixStr>
</a:LoopbackIPInterface>
<a:LoopbackIPInterface>
<ElementType>LoopbackInterface</ElementType>
<Name>HostIP1</Name>
<AttachTo>Loopback0</AttachTo>
<a:Prefix xmlns:b="Microsoft.Search.Autopilot.NetMux">
<b:IPPrefix>fe80::0002/128</b:IPPrefix>
</a:Prefix>
<a:PrefixStr>fe80::0002/128</a:PrefixStr> …
```
> [minigraph][dualtor] Support parsing `soc_ip` out of dpg

- platform/centec-arm64/tsingma-bsp/src/ctc-phy/mars.c
- platform/centec-arm64/tsingma-bsp/src/i2c-ctc/i2c-ctc.c
- platform/centec/sonic-platform-modules-v682/48x8c/sonic_platform/sfp.py
- platform/centec/sonic-platform-modules-v682/48y8c/sonic_platform/sfp.py
Fix some bugs on centec tsingma bsp and v682 sonic_platform package.
1.  add module license for centec mars phy driver
2.  Fix i2c function ability setting for tsingma soc i2c controller
3.  Fix eeprom read error on v682 sonic_platform sfp module
Build SONiC image and verify it on centec E530-48T4X and V682-48Y8C board.
> [centec] fix some bugs on centec tsingma bsp and v682 sonic_platform package

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-device-desc-ipv6-only.xml
- src/sonic-config-engine/tests/simple-sample-device-desc.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
…l (#11095) (#11273)
* [minigraph] Support parse IPv6 in device_desc.xml (#11095)
Signed-off-by: Jing Kan jika@microsoft.com
https://github.com/Azure/sonic-buildimage/pull/11095
> [cherry-pick][201811][minigraph] Support parse IPv6 in device_desc.xml

- rules/sairedis.mk
- rules/syncd.mk
This PR is a backport of https://github.com/Azure/sonic-buildimage/pull/10950 and a fix for it https://github.com/Azure/sonic-buildimage/pull/11227
To not build python2 pysairedis on bullseye
Cherry-picked above PRs from master
Build
> [202205][sonic-sairedis] don't try to build python-pysairedis (python2) on bullseye

- files/build_templates/backend_acl.j2
- files/build_templates/sonic_debian_extension.j2
- src/sonic-config-engine/tests/data/backend_acl/acl_multi_vlan.json
- src/sonic-config-engine/tests/data/backend_acl/acl_single_vlan.json
- src/sonic-config-engine/tests/data/backend_acl/multi_vlan.json
- src/sonic-config-engine/tests/data/backend_acl/single_vlan.json
- src/sonic-config-engine/tests/test_j2files.py
Storage backend has all vlan members tagged. If untagged packets are received on those links, they are accounted as RX_DROPS which can lead to false alarms in monitoring tools. Using this acl to hide these drops.
Created a acl template which will be loaded during minigraph load for backend. This template will allow tagged vlan packets and dropped untagged
Unit tests
> Add backend acl template

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-graph-storage-backend.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/test_cfggen.py
For storage backend, certain rules will be applied to the DATAACL table to allow only vlan tagged packets and drop untagged packets. 
Create DATAACL table if the device is a storage backend device
To avoid ACL resource issues, remove EVERFLOW related tables if the device is a storage backend device
Added the following unit tests
- verify that EVERFLOW acl tables is removed and DATAACL table is added for storage backend tor
- verify that no DATAACL tables are created and EVERFLOW tables exist for storage backend leaf
> Minigraph parser changes for storage backend acl

- rules/phy-credo.mk
Add support for reacting to speed change between 40G and 100G in CONFIG_DB
Fix a bug on optical bit setting.
Avoid the random error in shutdown for issue: https://github.com/aristanetworks/sonic/issues/40  
Avoid to run on SmartsvilleBkMs, which depends on a different driver (credo-sai).
Verified on the duts that the commands printed in the log are matching the expectation and the interfaces are up.
> [phy-credo]: update deb for speed change and bug fix

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
For 7800 LCs, set LAG mode to support 1024 number of 16-member system
LAGs.
The SOC property changes are necessary to match https://github.com/Azure/sonic-buildimage/pull/10519 which increases the number of system LAG IDs to 1024.
For 7800 LCs, set LAG mode to support 1024 number of 16-member system
LAGs.
> [Arista] Enable larger number of LAGs on 7800 LCs

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/tests/test_chassis.py
Signed-off-by: Sudharsan Dhamal Gopalarathnam sudharsand@nvidia.com
Cherry-pick of https://github.com/Azure/sonic-buildimage/pull/11309
Why I did it
During the system boot up when 'show platform status' or 'show version' command is executed before STATE_DB CHASSIS_INFO table is populated, the show will try to fallback to use the platform API. The DMI file in mellanox platforms require root permission for access. So if the show commands are executed as admin or any other user, the following error log will appear in the syslog
Jun 28 17:21:25.612123 sonic ERR show: Fail to decode DMI /sys/firmware/dmi/entries/2-0/raw due to PermissionError(13, 'Permission denied')
How I did it
Check the file permission before accessing it.
Added UT to verify. Manually verified if the error …
> [202205][Mellanox]Check dmi file permission before access 

- src/sonic-py-common/sonic_py_common/port_util.py
- src/sonic-py-common/sonic_py_common/util.py
- src/sonic-py-common/tests/test_port_util.py
To deprecate sonic-py-swsssdk, need move some code to sonic-py-common.
Porting util.py and port_util.py from sonic-py-swsssdk to sonic-py-common.
Pass UT.
Porting util.py and port_util.py from sonic-py-swsssdk to sonic-py-common.
> [sonic-py-common] Porting util.py and port_util.py from sonic-py-swsssdk to sonic-py-common

- src/sonic-build-hooks/hooks/apt-get
Fix the missing debian package for reproducible build issue.
The gnupg2 should be added into the version file.
https://dev.azure.com/mssonic/build/_build/results?buildId=118139&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318
```
The following packages have unmet dependencies:
gnupg2 : Depends: gnupg (>= 2.2.27-2+deb11u2) but 2.2.27-2+deb11u1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
The issue was caused by the gnupg2 removed, and not detected.
https://github.com/Azure/sonic-buildimage/blob/4fb6cf03e68856620038a1d3577ede15e89f8211/build_debian.sh#L250
Export the debian packages when any debian package being removed.
> [Build] Fix the missing debian package for reproducible build issue

- platform/marvell-armhf/platform.conf
Change-Id: I015856d173d50d94e30d8c555590efb70eb712ae
Signed-off-by: Pavan Naregundi <pnaregundi@marvell.com>
Kernel hang was cause due to increase in size of kernel during the upgrade to 5.10.103 and uboot env setting for fdt and initrd address was not good enough.
Have given sufficient room for kernel, by moving fdt_addr and initrd_addr.
Verified by loading image on Marvell Armada 380/385.
- [x ] 202205
> [Marvell-armhf] Fix kernel hang due to kernel upgrade to 5.10.103

- azure-pipelines.yml
When any of the test job failed in the test stage, the rerun will not work, the test stage will be skipped automaticall, so we do not have chance to rerun the test stage again, and the checks of the test will be always in failed status, block the PR to merge forever.
It should be caused by the condition in the Test stage, we should specify the status of the BuildVS stage.
Fix stage dependency logic.
> [ci] Fix azure pipeline test stage dependency issue.

- src/dhcp6relay/src/relay.cpp
Daemon dhcp6relay may crash due to null pointer access to `ifa_addr` member of `struct ifaddrs`.  It's not guaranteed that the interface must have available `ifa_addr`. That is true for some special virtual/pseudo interfaces. 
Check the pointer to `ifa_addr` is valid ahead of accessing it.
```
admin@a7280:~$ sudo config reload -y
...
admin@a7280:~$ docker exec dhcp_relay ps ax |grep dhcp6
44 pts/0    Sl     0:00 /usr/sbin/dhcp6relay
```
> [dhcp6relay] Check interface address is not NULL

- azure-pipelines.yml
When any of the test job failed in the test stage, the rerun will not work, the test stage will be skipped automaticall, so we do not have chance to rerun the test stage again, and the checks of the test will be always in failed status, block the PR to merge forever.
It should be caused by the condition in the Test stage, we should specify the status of the BuildVS stage.
Fix stage dependency logic.
> [ci] Fix azure pipeline test stage dependency issue. (#11386)

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-graph-storage-backend.xml
- src/sonic-config-engine/tests/test_cfggen.py
Backport #11221
For storage backend, certain rules will be applied to the DATAACL table to allow only vlan tagged packets and drop untagged packets.
Create DATAACL table if the device is a storage backend device
To avoid ACL resource issues, remove EVERFLOW related tables if the device is a storage backend device
Added the following unit tests
- verify that EVERFLOW acl tables is removed and DATAACL table is added for storage backend tor
- verify that no DATAACL tables are created and EVERFLOW tables exist for storage backend leaf
> [202012] Minigraph parser changes for storage backend acl

- src/sonic-host-services-data/debian/sonic-host-services-data.process-reboot-cause.service
Database container takes long time ( more than 1.5 minutes ) on some vendor platforms.
This makes the determine-reboot-cause starts later than process-reboot-cause service.
And that results in the incorrect reboot-cause determination.
Database container takes long time ( more than 1.5 minutes ) on some vendor platforms.
This makes the determine-reboot-cause starts later than process-reboot-cause service.
And that results in the incorrect reboot-cause determination.
Add the dependency of determine-reboot-cause service to process-reboot-cause service
Reboot and check the reboot-cause once the device boots up.
> Add dependency of determine-reboot-cause to process-reboot-cause service

- dockers/docker-sonic-mgmt/Dockerfile.j2
sonic-mgmt docker image build error, because of the textfsm new version(1.1.3).
https://dev.azure.com/mssonic/build/_build/results?buildId=119147&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=44e6c678-cb87-52d9-8547-bcdbd0ad6ae4&l=43043
Fix textfsm version to 1.1.2
I build the image on my local env, and reproduce the issue with 1.1.3, it's fixed after I change the version to 1.1.2 .
> FIX the build error introduced by textfsm 1.1.3(Published on 2022/7/6)

- rules/openssh.mk
Fix the openssh build issue, upgrade from 8.4p1-5 to 8.4p1-5+deb11u1.
https://dev.azure.com/mssonic/build/_build/results?buildId=120209&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318
```
+ sudo dpkg --root=./fsroot-broadcom -i target/debs/bullseye/openssh-server_8.4p1-5_amd64.deb
dpkg: warning: downgrading openssh-server from 1:8.4p1-5+deb11u1 to 1:8.4p1-5
(Reading database ... 44818 files and directories currently installed.)
Preparing to unpack .../openssh-server_8.4p1-5_amd64.deb ...
Unpacking openssh-server (1:8.4p1-5) over (1:8.4p1-5+deb11u1) ...
dpkg: dependency problems prevent configuration of openssh-server:
openssh-server depends on openssh-client (= 1:8.4p1-5); however:
Version of openssh-client on system is 1:8.4p1-5+deb11u1.
dpkg: …
```
> Upgrade openssh to 8.4p1-5+deb11u1

- dockers/docker-database/flush_unused_database
- dockers/docker-orchagent/enable_counters.py
- dockers/docker-orchagent/tunnel_packet_handler.py
- dockers/docker-sflow/port_index_mapper.py
- dockers/docker-snmp/snmp_yml_to_configdb.py
- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
- src/sonic-frr-mgmt-framework/tests/test_config.py
- src/sonic-frr-mgmt-framework/tests/test_constructor.py
Update scripts in sonic-buildimage from py-swsssdk to swsscommon
Change code to use swsscommon.
Update scripts in sonic-buildimage from py-swsssdk to swsscommon
> Update scripts in sonic-buildimage from py-swsssdk to swsscommon

- scripts/build_debian_base_system.sh
Why I did it
Cherry pick PR: https://github.com/Azure/sonic-buildimage/pull/11072
[Bug]: fix the version file name issue
[Bug]: fix the version file name issue
Fix the build failure: https://dev.azure.com/mssonic/build/_build/results?buildId=107211&view=results
```
+ scripts/build_debian_base_system.sh amd64 bullseye ./fsroot-centec
sed: can't read /tmp/tmp.glTzJefV24/version-deb: No such file or directory
Not found host-base-image packages, please check the version files in files/build/versions/host-base-image
```
Change the version-deb, to versions-deb
And add an improvement for host base image build, if the version path not exist, skipped the version control for base image.
https://dev.azure.com/mssonic/build/_build/results?buildId=107587&view=results
> [Bug]: fix the version file name issue (#11072)

- rules/openssh.mk
Fix the openssh build issue, upgrade from 8.4p1-5 to 8.4p1-5+deb11u1.
https://dev.azure.com/mssonic/build/_build/results?buildId=120209&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318
```
+ sudo dpkg --root=./fsroot-broadcom -i target/debs/bullseye/openssh-server_8.4p1-5_amd64.deb
dpkg: warning: downgrading openssh-server from 1:8.4p1-5+deb11u1 to 1:8.4p1-5
(Reading database ... 44818 files and directories currently installed.)
Preparing to unpack .../openssh-server_8.4p1-5_amd64.deb ...
Unpacking openssh-server (1:8.4p1-5) over (1:8.4p1-5+deb11u1) ...
dpkg: dependency problems prevent configuration of openssh-server:
openssh-server depends on openssh-client (= 1:8.4p1-5); however:
Version of openssh-client on system is 1:8.4p1-5+deb11u1.
dpkg: …
```
> [202111] Upgrade openssh to 8.4p1-5+deb11u1

- src/sonic-build-hooks/scripts/post_run_buildinfo
Cleanup the version deb preference file after build.
The version file is no use after build.
Remove the no use version file.
> [Build] Cleanup the version deb preference file after build

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml
- src/sonic-config-engine/tests/test_j2files.py
There is a need to select different mmu profiles based on deployment type
There will be separate subfolders (RDMA-CENTRIC, TCP-CENTRIC, BALANCED) in each hwsku folder which contains deployment specific mmu and qos settings. SonicQosProfile attribute in the minigraph will be used to determine which settings to use. If that attribute is not present, the default settings that exist in the hwsku folder will be used
> [202012] Minigraph parser changes to select mmu profiles based on SonicQosProfile attribute

- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
Cherry-pick from https://github.com/Azure/sonic-buildimage/pull/11305
The build below was broken, it was caused by one of the required debian mirror missing.
https://dev.azure.com/mssonic/build/_build/results?buildId=116719&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=88f376cf-c35d-5783-0a48-9ad83a873284
```
libpci-dev : Depends: libudev-dev (>= 196) but it is not going to be installed
libsystemd-dev : Depends: libsystemd0 (= 232-25+deb9u14) but 232-25+deb9u13 is to be installed
```
Add the missing mirrors for buster and stretch.
> [Build][202205] Add the missing debian security mirrors in slave images (#11305)

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/tests/caclmgrd/caclmgrd_feature_test.py
- src/sonic-host-services/tests/caclmgrd/test_bfd_vectors.py
- src/sonic-host-services/tests/caclmgrd/test_dhcp_vectors.py
Add infrastructure to support adding feature specific acls.
If feature specific ACLs has to be added:
```
if feature_name in self.feature_present and self.feature_present.get('feature_name'):
add_feature_specific_acls()
```
Add function to get features present in feature table.
unit-test passes.
> [caclmgrd]: Add infrastructure to support adding feature specific acls

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml
- src/sonic-config-engine/tests/test_j2files.py
There is a need to select different mmu profiles based on deployment type
There will be separate subfolders (RDMA-CENTRIC, TCP-CENTRIC, BALANCED) in each hwsku folder which contains deployment specific mmu and qos settings. SonicQosProfile attribute in the minigraph will be used to determine which settings to use. If that attribute is not present, the default settings that exist in the hwsku folder will be used
> Minigraph parser changes to select mmu profiles based on SonicQosProfile attribute

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
- platform/mellanox/mlnx-platform-api/tests/test_utils.py
Fix bug: pmon report error on start up because some SKUs do not have hwsku.json
If hwsku.json, do not extract RJ45 port information
Manual test.
Unit test.
> [Mellanox] Fix issue: failed to decode Json while there is no hwsku.json

- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample-arista-7050-t0-storage-backend-minigraph.xml
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7050-t0-storage-backend.json
- src/sonic-config-engine/tests/test_j2files.py
This PR is to add a flag to control whether to generate `PORT_QOS_MAP|global` entry or not.
It's because for some HWSKU, such as `BackEndToRRouter` and `BackEndLeafRouter`, there is no `DSCP_TO_TC_MAP` defined.
Hence, if the `PORT_QOS_MAP|global` entry is generated, OA will report some error because the `DSCP_TO_TC_MAP` map `AZURE` can not be found.
```
Jul 14 00:24:40.286767 str2-7050qx-32s-acs-03 ERR swss#orchagent: :- saiObjectTypeQuery: invalid object id oid:0x7fddb43605d0
Jul 14 00:24:40.286767 str2-7050qx-32s-acs-03 ERR swss#orchagent: :- meta_generic_validation_objlist: SAI_SWITCH_ATTR_QOS_DSCP_TO_TC_MAP:SAI_ATTR_VALUE_TYPE_OBJECT_ID object on list [0] oid 0x7fddb43605d0 is not valid, returned null object id
Jul 14 00:24:40.286767 str2-7050qx-32s-acs-03 ERR swss#orchagent: :- …
```
> Add flag to control the generation of `PORT_QOS_MAP|global` entry

- dockers/docker-fpm-frr/base_image_files/TS
To fix an error in log message introduced by https://github.com/Azure/sonic-buildimage/pull/11257
Fixed the log message
Validate console output and syslog for TSB
> Log message fix for TSB

- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample-arista-7050-t0-storage-backend-minigraph.xml
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7050-t0-storage-backend.json
- src/sonic-config-engine/tests/test_j2files.py
This PR is to cherry-pick #11448 to `202012` branch after resolving conflicts.
There are conflicts in 
```
files/build_templates/qos_config.j2
src/sonic-config-engine/tests/test_j2files.py
```  
Please find details in PR #11448 .
> [cherry-pick][202012] Add flag to control the generation of global level map

- platform/mellanox/mlnx-platform-api/tests/test_chassis.py
Fix compiling issue
```
=================================== FAILURES =================================== 
____________________ TestChassis.test_get_port_or_cage_type ____________________ 
self = <tests.test_chassis.TestChassis object at 0x7f7e81fecaf0> 
def test_get_port_or_cage_type(self): 
chassis = Chassis() 
> chassis.RJ45_port_list = [0] 
E AttributeError: can't set attribute 
tests/test_chassis.py:289: AttributeError 
=============================== warnings summary ============
```
It was caused by #11336 but the root cause is that the ci/merge flow of PR #11336 and #11436 interleaved.
> [Mellanox] Fix chassis test issue

- azure-pipelines.yml
[multi-asic]: Add build param to build multi-asic KVM image.
Require sonic-4asic-vs.img.gz to run multi-asic tests.
BUILD_MULTIASIC_KVM=y has to be added to build parameter to generate multi-asic KVM image which can be eventually used in multi-asic VS testbed.
This is a pipeline that we currently have to generate multi-asic KVM image:
https://github.com/Azure/sonic-buildimage/blob/master/.azure-pipelines/official-build-multi-asic.yml
Add BUILD_MULTIASIC_KVM=y to build parameter in pipeline script to generate multi-asic KVM image.
The build param is already used in official-build-multi-asic.yml pipeline.
> [multi-asic]: Add build param to build multi-asic KVM image.

- install_sonic.py
Increase timeout value when installing SONiC on kvm. Sometimes installation will timeout.
It is ok to have a bigger timeout value. Because it will exit whenever installing finished.
> [build] Increase timeout value when installing SONiC image on kvm

- files/image_config/rsyslog/rsyslog.conf.j2
**HLD:** https://github.com/sonic-net/SONiC/pull/1002
**Example:**
```
root@sonic:/home/admin# cat /etc/rsyslog.conf | grep "^*.*"
*.* action(type="omfwd" target="10.0.0.5" protocol="udp" address="1.1.1.1" port="514")
*.* action(type="omfwd" target="10.0.0.6" protocol="udp" address="1.1.1.1" port="514" device="mgmt")
```
[sonic-utilities](https://github.com/Azure/sonic-utilities)
```
ea11b22 [sonic-bootchart] add sonic-bootchart (#2195)
8e5d478 [ssip]: Add CLI (#2191)
1dacb7f Replace pyswsssdk with swsscommon (#2251)
```
* To implement Syslog Source IP feature
* In order to include the following commit: `8e5d478 [ssip]: Add CLI (#2191)`
* Updated syslog config template
* Advanced submodule
* N/A
* …
> [ssip]: Update config generator

- src/sonic-config-engine/minigraph.py
Active-active dualtor has new indicator for peering link.
allow LibraPeeringLink to be dualtor indication as well.
Tested on the dut with the new peering link type.
> [minigraph] allow LibraPeeringLink to be dualtor indication as well

- dockers/docker-macsec/cli-plugin-tests/conftest.py
- dockers/docker-macsec/cli-plugin-tests/mock_single_asic.py
- dockers/docker-macsec/cli-plugin-tests/mock_tables.py
- dockers/docker-macsec/cli-plugin-tests/test_config_macsec.py
- dockers/docker-macsec/cli/config/plugins/macsec.py
- dockers/docker-macsec/cli/show/plugins/show_macsec.py
Enable multi-asic platform support for macsec cli
Add an option `-n, --namespace <name>` in config/show macsec.
```
admin@dut:~$ show macsec -h
Usage: show macsec [OPTIONS] [INTERFACE_NAME]
Options:
-d, --display [all]  Show internal interfaces  [default: all]
-n, --namespace []   Namespace name or all
-?, -h, --help       Show this message and exit.
admin@dut:~$ sudo config macsec -h
Usage: config macsec [OPTIONS] COMMAND [ARGS]...
MACsec-related configuration tasks
Options:
-n, --namespace []  Namespace name
-?, -h, --help      Show this message and exit.
```
> [macsec] cli multi-namespace support

- platform/checkout/cisco-8000.ini
update cisco-8000 platform version to 202012-v0.107
> Update cisco-8000 submodule to v0.107

- src/iproute2/patch/0001-patch-macsec-xpn-support.patch
ip command cannot update packet number if the cipher is XPN.
Specify SSCI when update packet number and ignore SSCI value if update action.
Manually check.
> [iproute2]: Enhance iproute2 to update PN for XPN

- Makefile.work
Not all build environments have passwordless sudo enabled for all users
Instead of using `sudo` to delete fsroot directories, mount them in a small, temporary docker container and delete them from there
Build in an environment where the build user does not have passwordless sudo enabled and confirm that no sudo password prompts are seen
Needs to be included in any branch that contains #11111 
Re-allow builds without passwordless sudo authentication
> [build] don't require passwordless sudo (Closes #11292)

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/psu.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/thermal.py
Fix snmp test case(snmp/test_snmp_phy_entity.py) failed.
Update the return value of the get_position_in_parent method in psu.py and thermo.py.
Rerun test case to verify.
> [device/celestica]:Fix failed test case of Seastone snmp 

- device/arista/x86_64-arista_720dt_48s/td3x2-a720dt-48s-flex.config.bcm
- src/sonic-device-data/tests/permitted_list
Signed-off-by: Jiahua Wang <jiahua.wang@broadcom.com>
The sai switch api as of now only has "switch_mdio_read/switch_mdio_write" functions. SAI needs another configuration parameter to distinguish  mdio access clause 22 from clause 45.
Adding the new soc property "sai_mdio_access_clause22" will allow the mdio device using the mdio clause 22 access with the same sai switch api functions "switch_mdio_read/switch_mdio_write".
On a platform with mdio clause 22 device connected to broadcom NPU mdio bus, PAI/gearbox will only work with the new soc property "sai_mdio_access_clause22=1".
> Add sai_mdio_access_clause22=1 in td3x2-a720dt-48s-flex.config.bcm

- .azure-pipelines/official-build-multi-asic.yml
- .azure-pipelines/run-test-template.yml
- azure-pipelines.yml
Require multi-asic VS tests to be run during PR checks and merges in master branch.
- Add job to run multi-asic VS tests in sonic-buildimage pipeline. Currently pipeline will run basic bgp fact test to ensure the testbed comes up, load minigraph works and bgp sessions are up.
- Use new multi-asic VS agent pool sonictest-ma in official-multi-asic-vs pipeline
- Make multi-asic VS test optional for now. There are two known issues:
1. Announce route failure during refresh-dut in setup testbed stage.
2. bgp sessions not getting established.
Tested using test azure pipelines.
> [multi-asic]: Add job to run multi-asic VS tests in sonic-buildimage pipeline

- files/image_config/monit/memory_checker
Fix in Monit memory_checker plugin. Skip fetching running containers if docker engine is down (can happen in deinit).
This PR fixes issue https://github.com/Azure/sonic-buildimage/issues/11472.
Signed-off-by: liora <liora@nvidia.com>
In the case where Monit runs during deinit flow, memory_checker plugin is fetching the running containers without checking if Docker service is still running. I added this check.
Use systemctl is-active to check if Docker engine is still running.
Use systemctl to stop docker engine and reload Monit, no errors in log and relevant print appears in log.
The fix is required in 202205 and 202012 since the PR that introduced the issue was cherry picked to those branches (https://github.com/Azure/sonic-buildimage/pull/11129).
> [memory_checker] Do not check memory usage of containers if docker daemon is not running

- device/celestica/x86_64-cel_e1031-r0/sonic_platform/sfp.py
Why I did it:
To fix hlx platform sfp+ module tx disable issue
How I did it:
Fix sfp+ tx disable function according SFF-8472 specification
To fix hlx platform sfp+ module tx disable issue.
Fix sfp+ tx disable function according SFF-8472 specification.
``` python3
import sonic_platform
platform = sonic_platform.platform.Platform()
sfp49 = platform._chassis.get_all_sfps()[48]
sfp49.tx_disable(True)
sfp49.get_tx_disable()
sfp49.tx_disable(False)
sfp49.get_tx_disable()
sfp50 = platform._chassis.get_all_sfps()[49]
sfp50.tx_disable(True)
sfp50.get_tx_disable()
sfp50.tx_disable(False)
sfp50.get_tx_disable()
```
> [hlx/sfp] fix hlx platform sfp+ tx disable issue

- azure-pipelines.yml
Why I did it
Transfer organization from Azure to sonic-net for sonic-mgmt
Transfer organization from Azure to sonic-net for sonic-mgmt
> [ci] Transfer organization from Azure to sonic-net for sonic-mgmt (#11559)

- files/image_config/warmboot-finalizer/finalize-warmboot.sh
Spanning from https://github.com/Azure/sonic-linkmgrd/pull/76, this PR is to update warm restart finalizer to wait for linkmgrd to be reconciled. 
To make sure finalizer save config after linkmgrd's reconciliation. 
Add linkmgrd to the reconciliation wait list of warmboot finalizer. 
Verified on lab device, linkmgrd reconciled as expected. (Otherwise we would see ```Some components didn't finish reconcile: ...``` in syslog.)
```
admin@****************:~$ sudo zgrep "WARMBOOT_FINALIZER" /var/log/syslog --text
Jul 27 23:00:56.819553 **************** NOTICE root: WARMBOOT_FINALIZER : Wait for database to become ready...
Jul 27 23:00:57.488231 **************** NOTICE root: WARMBOOT_FINALIZER : Database is ready...
Jul 27 23:00:57.792936 …
```
> Update WARM START FINALIZER to wait for linkmgrd to reconcile

- platform/broadcom/sai.mk
Update Broadcom SAI debian package. New Package has following changes:
CaseCS00012248135: Fix shows error message "linux-bcm-knet: Fatal error: Incomplete chain" followed by malformed LACP/LLDP packets
How I verify:
Validated by @gechiang 
Qualified it on 7050qx HW SKU (T1-Lag Topo) running the following set of tests:
pfcwd/test_pfcwd_all_port_storm.py 
ipfwd/test_dip_sip.py 
everflow/test_everflow_ipv6.py 
everflow/test_everflow_per_interface.py 
lldp/test_lldp.py 
pc/test_lag_2.py
> [201911] Updated Broadcom SAI Debian Package

- src/sonic-bgpcfgd/bgpcfgd/managers_setsrc.py
- src/sonic-bgpcfgd/tests/test_setsrc.py
The bgpcfgd doesn't support deletion of 'zebra set src', if an interface is deleted, the bgpcfgd will drop a warning message. In current implementation, we only care about the loopback0 interface but not others. 
To improve the log print to have the key info, which will give the name of the deleted interface. We can ignore it if it is not the loopback0 interface. The application layer should be aware of that update and deletion is not supported, delete or update with a new address of loopback0 could cause issue, this log can give enough info to root cause the issue.
> [bgpcfgd] improve the log when delete a loopback interface

- device/mellanox/x86_64-mlnx_msn4410-r0/get_sensors_conf_path
- device/mellanox/x86_64-mlnx_msn4410-r0/sensors.conf.a1
New SN410 A1 system has a different sensor layout with A0 system, needs a new sensor conf file to support it.
Since the SN4410 A1 system use exactly the same sensor layout as the SN4700 A1 system, so add a symbol link linking to the SN4700 A1 sensor conf file to reuse.
Run sensor test against the SN4410 A1 system;
Run platform related regression test against the SN4410 A1 system
> [202012] [Mellanox] Add new sensor conf to support SN4410 A1 system

- files/scripts/swss.sh
What I did:
Added bgp as a dependent of swss
Why I did it:
bgp container was not restarting on swss crash. When swss crashes, linkmgrd
doesn't initate a switchover because it cannot access the default route from
orchagent. Bringing down bgp with swss will isolate the ToR, causing linkmgrd
to initiate a switchover to the peer ToR avoiding significant packet loss.
How I did it:
Added bgp to DEPENDENT
Signed-off-by: Nikola Dancejic <ndancejic@microsoft.com>
> [swss] Adding bgp container as dependent of swss

- .azure-pipelines/run-test-template.yml
202012 PR test is failing due to some recent change in sonic-mgmt master branch.
Use matching sonic-mgmt branch to run 202012 branch PR tests.
this PR test.
> [202012][prtest] use matching sonic-mgmt branch for 202012 branch PR tests

- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/buffers_defaults_objects.j2
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t1-dynamic.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t1.json
Configure buffer for queue 7 on T1 uplink ports in dual ToR scenario
On uplink ports `DSCP 48` => `TC 7` => `queue 7`
> [Mellanox] Configure buffer for queue 7 on T1 uplink ports in dual ToR scenario

- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/buffers_defaults_objects.j2
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t1-dynamic.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t1.json
Configure buffer for queue 7 on T1 uplink ports in dual ToR scenario
On uplink ports `DSCP 48` => `TC 7` => `queue 7`
> [Mellanox][202012] Configure buffer for queue 7 on T1 uplink ports in dual ToR scenario

- src/sonic-yang-models/tests/yang_model_tests/tests/crm.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/crm.json
- src/sonic-yang-models/yang-models/sonic-crm.yang
To support Yang models for SRV6 CM
Added yang models for SRV6 MY_SID_ENTRY and Nexthop
Added SRV6 CRM yang tests.
202111
> Yang model support for SRV6 CRM

- azure-pipelines.yml
> Extend t1-lag timeout to 360 minutes

- installer/default_platform.conf
- installer/install.sh
- onie-mk-demo.sh
The %%EXTRA_CMDLINE_LINUX%% is not replaced to the real value, it has impact on the kernel parameter settings.
See the log sonic-vs.img.gz.log in the latest master build. In the grub.cfg, the %%EXTRA_CMDLINE_LINUX%% is set in the linux command line.
```
Installing for i386-pc platform.
Installation finished. No error reported.
Switch CPU vendor is: GenuineIntel
Switch CPU cstates are: disabled
EXTRA_CMDLINE_LINUX=%%EXTRA_CMDLINE_LINUX%%
Installed SONiC base image SONiC-OS successfully
ONIE: NOS install successful: file://dev/vdb/onie-installer.bin
```
> [Bug][Build] Fix the variable patterns not replaced issue

- .azure-pipelines/official-build.yml
- azure-pipelines.yml
When transfer repo to another organization, azp reference also need change.
Change azp reference to avoid pipeline failure.
> [ci] Update azp reference to support transfering organization from Azure to sonic-net

- src/sonic-bgpcfgd/bgpmon/bgpmon.py
Update bgpmon.py from py-swsssdk to swsscommon
Change bgpmon.py to use swsscommon.
Update bgpmon.py from py-swsssdk to swsscommon
> Replace swsssdk with swsscommon in bgpmon.py

- dockers/docker-database/docker-database-init.sh
- dockers/docker-database/flush_unused_database
Fix docker-database flush_unused_database failed issue: https://github.com/Azure/sonic-buildimage/issues/11597
When change flush_unused_database from use swsssdk to use swsscommon, get_instancelist() and get_dblist() name changed but not update.
Change flush_unused_database code to use swsscommon API:
Change get_instancelist to getInstanceList.
Change get_dblist to getDbList.
Manually check syslog make sure error log not exist and swss, syncd, bgp service started.
Search code in Azure make sure there all similer case are fixed in this PR.
Fix docker-database flush_unused_database failed issue: https://github.com/Azure/sonic-buildimage/issues/11597
When change flush_unused_database from use swsssdk to use swsscommon, get_instancelist() and get_dblist() name changed but …
> [database] Fix docker-database flush_unused_database failed issue

- dockers/docker-platform-monitor/Dockerfile.j2
ping command is not working inside PMON docker (bullseye)
Use case: chassisd checks for module reachability inside PMON for "show chassis modules midplane-status" CLI, and on Cisco chassis, this uses ping command to check network reachability
Add iputils-ping package in pmon dockerfile
Run ping command inside PMON container
[pmon] Add ping package to pmon docker
> [pmon] Add ping package to pmon docker

- files/build_templates/docker_image_ctl.j2
To fix https://github.com/Azure/sonic-buildimage/issues/11381
Preventing ebtables rules to be applied on KVM image. The ebtables rules in  SONiC are added to prevent ARP as well as L2 forwarding to be blocked in linux kernel since the hardware will take care of the actual L2 forward. However this is not the case with KVM where linux needs to forward even L2 packets
Added check in docker_image_ctl.j2 to apply the ebtables rules only when platform is not vs which is set for KVM
Loaded KVM image built with the changes and verified ebtables are not present
Before
```
root@sonic:~# ebtables -L
Bridge table: filter
Bridge chain: INPUT, entries: 0, policy: ACCEPT
Bridge chain: FORWARD, entries: 3, policy: ACCEPT
-d BGA -j DROP
-p ARP -j DROP
-p 802_1Q --vlan-encap ARP -j DROP
Bridge chain: …
```
> [KVM]Preventing ebtables cfg to be applied on KVM

- dockers/docker-sonic-p4rt/Dockerfile.j2
- dockers/docker-sonic-p4rt/p4rt.sh
- dockers/docker-sonic-p4rt/p4rt_vars.j2
The initial commit for the P4RT docker hard coded all the flags which makes it difficult to configure at runtime. Reading them from the CONFIG_DB allows for more flexibility.
Updated the p4rt.sh startup script to first read from CONFIG_DB then apply any configs it finds. If a config is not set then a default (specified by the executable) is used. 
Update data in the CONFIG_DB and restart the P4RT docker.
The P4RT app can be configured through the CONFIG_DB.
> [PINS] Allow P4RT App to read configs from CONFIG_DB.

- build_debian.sh
- dockers/docker-base-bullseye/Dockerfile.j2
The default stable version of rsyslog on bullseye has a bug about rate limit. It causes rate limit not work. The bug has been fixed on backport version 8.2206.0-1~bpo11+1.
Buster has no such issue.
Upgrade rsyslog from 8.2110.0 to 8.2206.0-1~bpo11+1
Manual test
> Fix issue: rsyslog rate limit does not work on version 8.2110.0

- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-orchagent/docker-init.sh
- dockers/docker-orchagent/supervisord.conf
- dockers/docker-orchagent/tunnel_packet_handler.conf
Tunnel packet handler running on non dualtor devices generates error logs
At SWSS docker init time, check the device subtype and enable tunnel packet handler only if it is dualtor
- Apply changes to dualtor device, verify that tunnel packet handler is running after restarting swss
- Apply changes to non dualtor device, verify that tunnel packet handler is not running and does not show in `supervisorctl status` after restarting swss (verified on both T0 and T1 devices)
- The SWSS docker built from this PR has been validated on both dualtor and non-dualtor devices
> [202012][swss] Only run tunnel packet handler on dualtor devices

- files/image_config/config-setup/config-setup
This reverts commit 6c2f99a32766f0cb3f0fbfad24c50f8ee6290e7a.
No current plan to backport the feature and the required PRs to 202012
> Revert "Add load_minigraph option to include traffic-shift-away during config migration (#11403)"

- files/scripts/arp_update
202012 duplicate of https://github.com/sonic-net/sonic-buildimage/pull/11615 to get around failing PR checks on master branch
On dual ToR devices, failed neighbor entries result in tunnel routes being added to the peer switch by orchagent. These tunnel routes prevent the neighbor entries from being resolved if the neighbor ever becomes responsive again.
In arp_update, check for FAILED or INCOMPLETE kernel neighbor entries and manually ping them to try and resolve the neighbor
Run sonic-mgmt test dualtor/test_orchagent_active_tor_downstream.py::test_active_tor_remove_neighbor_downstream_active[ipv6] (requires changes in this PR to pass: https://github.com/sonic-net/sonic-mgmt/pull/6071)
> [202012][arp_update]: Resolve failed neighbors on dualtor

- src/thrift_0_13_0/Makefile
- src/thrift_0_13_0/patch/0002-cve-2017-1000487.patch
Fix CVE-2017-1000487 alert in thrift 0.14.1.
See https://nvd.nist.gov/vuln/detail/CVE-2017-1000487
Change the version of org.codehaus.plexus:plexus-utils from 3.0.14 to 3.0.16.
> [202012] Fix CVE-2017-1000487 security alert

- src/thrift_0_14_1/thrift.patch/0002-cve-2017-1000487.patch
- src/thrift_0_14_1/thrift.patch/series
Fix CVE-2017-1000487 alert in thrift 0.14.1.
See https://nvd.nist.gov/vuln/detail/CVE-2017-1000487
Change the version of org.codehaus.plexus:plexus-utils from 3.0.14 to 3.0.16.
> Fix CVE-2017-1000487 alert for thrift 0.14.1

- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
Add more log while doing sysfs reading to increase the debug capability
Log the relevant file path and error number while sysfs reading return None
Manual test
> [Mellanox] add more log while doing sysfs reading

- platform/broadcom/sai.mk
Update the DNX SAI to 7.1.0.0-7. This debian will not have macsec support enabled.
Validated with the JR2 and J2C+ based boards, with interfaces up, traffic ok. Validated a few sonic-mgmt tests as well.
```
admin@str2--lc1-1:~$ show int status
Interface                            Lanes    Speed    MTU    FEC          Alias            Vlan    Oper    Admin                                             Type    Asym PFC
--------------  -------------------------------  -------  -----  -----  -------------  --------------  ------  -------  -----------------------------------------------  ----------
Ethernet0          72,73,74,75,76,77,78,79     400G   9100    N/A      Ethernet0          routed    down     down  QSFP-DD Double Density 8X Pluggable Transceiver         off
Ethernet1 …
```
> Update the  DNX SAI to 7.1.0.0-7

- files/scripts/write_standby.py
The initial value has to be present for the state machines to work. In active-standby dual-tor scenario, or any hardware mux scenario, the value will be updtaed eventually with a delay.
However, in active-active dual-tor scenario, there is no other mechanism to initialize the value and get state machines started.
So this script will have to write something at start up time.
For active-active dualtor, 'active' is a more preferred initial value, the state machine will switch the state to standby soon if
link prober found link not in good state.
Update the script to always provide initial values.
Tested on active-active dual-tor testbed.
> [write_standby] update write_standby.py script

- files/scripts/arp_update
There is a separate PR to bring this change into the 202012 branch https://github.com/sonic-net/sonic-buildimage/pull/11641
On dual ToR devices, failed neighbor entries result in tunnel routes being added to the peer switch by orchagent. These tunnel routes prevent the neighbor entries from being resolved if the neighbor ever becomes responsive again. 
In arp_update, check for FAILED or INCOMPLETE kernel neighbor entries and manually ping them to try and resolve the neighbor
Run sonic-mgmt test dualtor/test_orchagent_active_tor_downstream.py::test_active_tor_remove_neighbor_downstream_active[ipv6] (requires changes in this PR to pass: https://github.com/sonic-net/sonic-mgmt/pull/6071)
> [arp_update]: Resolve failed neighbors on dualtor

- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-orchagent/docker-init.j2
- dockers/docker-orchagent/supervisord.conf.j2
- dockers/docker-orchagent/tunnel_packet_handler.conf
Master branch duplicate of #11626 
Tunnel packet handler running on non dualtor devices generates error logs
At SWSS docker init time, check the device subtype and enable tunnel packet handler only if it is dualtor
- Apply changes to dualtor device, verify that tunnel packet handler is running after restarting swss
- Apply changes to non dualtor device, verify that tunnel packet handler is not running and does not show in supervisorctl status after restarting swss (verified on both T0 and T1 devices)
- The SWSS docker built from this PR has been validated on both dualtor and non-dualtor devices
> [swss] Only run tunnel packet handler on dualtor devices

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/tests/test_psu.py
Depends on https://github.com/sonic-net/sonic-platform-common/pull/295 and https://github.com/sonic-net/sonic-platform-daemons/pull/276
Add PSU input voltage and input current to mlnx platform api.
Implement 2 function of getting the psu voltage and psu current input:
Get the values from "power/psu{}_curr_in" , "power/psu{}_volt_in"
Manual test.
Run sonic-mgmt regression
> [Mellanox] add PSU input voltage and current

- files/scripts/swss.sh
- files/scripts/syncd_common.sh
When using trap on SIGTERM the script will not react to the SIGTERM signal sent while a child is executing.
I.e, the following script does not react on SIGTERM sent to it if it is
waiting for sleep to finish:
```
#!/bin/bash
trap "echo Handled SIGTERM" 0 2 3 15
echo "Before sleep"
sleep inf
echo "After sleep"
```
On SIGTERM sent to the followig script:
```
+ trap 'echo Handled SIGTERM' 15
+ echo Before sleep
Before sleep
+ sleep inf
Terminated
++ echo Handled SIGTERM
Handled SIGTERM
+ echo After sleep
After sleep
```
"echo After sleep" shouldn't be printed, the script has to exit.
Instead, trap only on EXIT which covers also a scenario with exit on
SIGINT, SIGTERM.
When NVIDIA switch is first booting FW upgrade process starts, if user …
> [swss.sh/syncd.sh] Trap only on EXIT

- src/sonic-bgpcfgd/bgpcfgd/managers_allow_list.py
- src/sonic-bgpcfgd/tests/test_allow_list.py
2 things are missing in current allow-prefix list implementation. 
1. In some usecase, need to tell the BGP neighbor and have different allow-prefix list for different neighbors, which is not supported.
2. for the prefix list, can't support flexible le and ge.
To enhance the bgp allow-prefix list feature to have:
1. To include the neighbor type info for the allow-prefix list. 
2. To support flexible le and ge length for allow-prefix list. 
4 new unit test cases are added in this PR to cover changes. 
Yang model changes would be implemented by another PR.
> [bgp-cfgd] BGP allow list enhancement

- files/scripts/swss.sh
bgp should be a per-asic service, and runs for each namespace on
multi-asic platforms. However, putting bgp in MULTI_INST_DEPENDENT
causes swss to be restarted as well as bgp. this is causing issues after #11000
Issue: https://github.com/sonic-net/sonic-buildimage/issues/11653
This fix:
- removes bgp from dependents list
- adds a conditional that either adds bgp, or bgp@$DEV to separate
between single and multi-asic platforms
Signed-off-by: Nikola Dancejic <ndancejic@microsoft.com>
> [swss] Adding conditional for bgp when on multi ASIC platform

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml
- src/sonic-config-engine/tests/sample-voq-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
Generate the port configuration required 400G ZR port from minigraph.
Add parse logic to get `tx_power` and `laser_freq` from `LinkMetadata` section of the minigraph.
Add UT for packet-chassis and voq chassis
UT
> parse 400g zr port config from minigraph

- files/scripts/syncd.sh
Change ```sxdkernel start``` to ```sxdkernel restart```. If ```syncd``` service crashes in ```ExecStartPre``` systemd will not call ```ExecStop``` and thus will not call ```sxdkernel stop```. Use of ```sxdkernel restart``` is more robust in terms of guarantees to restore the system after unexpected crashes.
Changed ```syncd.sh```
Run regression.
> [syncd.sh] 'sxdkernel start' => 'sxdkernel restart'

- src/sonic-config-engine/minigraph.py
This PR is to disable tunnel qos remap on KVM testbed. It's because we have no qos map defined for tunnel on KVM.
Fixes: https://github.com/sonic-net/sonic-mgmt/issues/6162
Update minigraph parser to check the `platform` name. If `kvm` is found, then tunnel qos remap is disabled.
Verified on a KVM dualtor testbed.
Disable tunnel qos remap on KVM testbed
> Disable tunnel qos remap on KVM testbed

- src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json
- src/sonic-yang-models/yang-models/sonic-port-qos-map.yang
This PR is to update Yang model for  `pfc_enable` and `pfcwd_sw_enable` fields to support more than 2 queues, like `2,3,4,6`.
Before this change, the regex `"[0-7](,[0-7])?"` accepts only no more than 2 queues.
Update the regex pattern for `pfc_enable` and `pfcwd_sw_enable`, from `"[0-7](,[0-7])?"` to `"[0-7](,[0-7])*`
The change is verified by UT. The test input is updated to cover the change.
```
collected 3 items                                                                                                                                                                                     
tests/test_sonic_yang_models.py ..                                                                                                                                                              [ 66%] …
```
> [Yang] Update Yang for `pfc_enable` and `pfcwd_sw_enable` fields

- device/arista/x86_64-arista_720dt_48s/Arista-720DT-48S/phy24_config.json
Port index 22 is associated with phy23_config.json, then same port index 22 in phy24_config.json may cause gearbox port creation error. Port Ethernet22 maps to index 23. 
The related error messages:
```
Aug 12 01:59:09.077562 bjw-pikez-112 NOTICE swss#orchagent: :- initGearboxPort: BOX: port_id:0x1000000000018 index:23 alias:Ethernet22
Aug 12 01:59:09.077562 bjw-pikez-112 NOTICE swss#orchagent: :- initGearboxPort: BOX: Gearbox port Ethernet22 assigned phyOid 0x1621010000000016
Aug 12 01:59:09.078782 bjw-pikez-112 ERR swss#orchagent: :- meta_generic_validation_create: SAI_PORT_ATTR_SPEED:SAI_ATTR_VALUE_TYPE_UINT32 attribute is mandatory but not passed in attr list
Aug 12 01:59:09.078782 bjw-pikez-112 ERR swss#orchagent: :- initGearboxPort: BOX: Failed to create Gearbox system-side port for …
```
> [PikeZ] Correct port index in Arista-720DT-48S/phy24_config.json

- src/sonic-py-common/sonic_py_common/device_info.py
Put yang_config_validation in common lib and make it reusabe
Move the definition to device_info.py
> Add yang_config_validation in device_info

- src/systemd-sonic-generator/systemd-sonic-generator.c
Replace unsafe functions to safe functions
Replace `strtok()` by `strtok_r()`
> Replace strtok in systemd-sonic-generator

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Fix issue: set lpmode by platform API does not work
Fix miss return value in code
Manual test
> [Mellanox] Fix issue: set lpmode by platform API does not work

- .gitmodules
> Change submodule path from Azure to sonic-net

- build_debian.sh
We need to validate arp response in some cases.
Install the arping tool in the base image.
This PR test.
> [arping] install arping utility in the base image

- files/image_config/monit/container_checker
- src/sonic-py-common/sonic_py_common/multi_asic.py
On Supervisor/RP card, some application containers may not run if
the asic is not present due to a missing Fabric card. The container checker
should skip those container instances.
Container instances which run only if asic present: swss, syncd, lldp,
teamd
Exception: All instances of database and bgp containers run irrespective
of asic presence.
On a supervisor card in a chassis, syncd/teamd/swss/lldp etc dockers are created for each Switch Fabric card. However, not all chassis would have all the switch fabric cards present. In this case, only dockers for Switch Fabrics present would be created.
The monit 'container_checker' fails in this scenario as it is expecting dockers for all Switch Fabrics (based on NUM_ASIC defined in asic.conf file). …
> container_checker on supervisor should check containers based on asic presence

- src/sonic-host-services/scripts/determine-reboot-cause
- src/sonic-host-services/tests/determine-reboot-cause_test.py
Why I did it
Add the hardware reboot cause when the previous software reboot failed
How I did it
Check both hardware reboot cause and software reboot cause.
Add the hardware reboot as actual reboot cause
if any hardware reboot cause is available for any software reboot.
Perform reboots and verify the reboot-cause
> Add the hw reboot cause if it happened during a software reboot

- src/sonic-py-common/sonic_py_common/multi_asic.py
Currently the CLI commands `show interface status` `show interface counters` and `show interface description` displays `Ethernet-IB` and `Ethernet-Rec` ports in the output. These are internal ports should only be displayed when the option `-d all` is used for the above mentioned CLI commands
Add the port  roles `Inb` and `Rec` when classifing a port as internal port.
Verify the CLI output of the command  `show interface status` doesnt display the `Ethenet-IB` and `Ethernet-Rec` port when `-d all` option in not present
Before
```
admin@Ssonic:$ show interface counters
IFACE    STATE    RX_OK      RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK     TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR …
```
> filter inband and recirc ports as internal ports

- device/accton/x86_64-accton_minipack-r0/plugins/led_control.py
Update scripts in sonic-buildimage from py-swsssdk to swsscommon
Remove unused swsssdk import from accton device code
Remove unused swsssdk import from accton device code
> [Accton] Remove unused swsssdk import from accton device code

- device/centec/x86_64-centec_e582_48x2q4z-r0/plugins/led_control.py
- device/centec/x86_64-centec_e582_48x6q-r0/plugins/led_control.py
- platform/centec/sonic-platform-modules-e582/48x2q4z/scripts/48x2q4z_platform_monitor.py
- platform/centec/sonic-platform-modules-e582/48x6q/scripts/48x6q_platform_monitor.py
Update scripts in sonic-buildimage from py-swsssdk to swsscommon
Replace swsssdk with swsscommon in centec devices.
Replace swsssdk with swsscommon in centec devices.
> [Centec] Replace swsssdk with swsscommon in centec devices.

- device/alphanetworks/x86_64-alphanetworks_snh60a0_320fv2-r0/plugins/led_control.py
- device/alphanetworks/x86_64-alphanetworks_snh60b0_640f-r0/plugins/led_control.py
Update scripts in sonic-buildimage from py-swsssdk to swsscommon
Replace swsssdk with swsscommon in alphanetworks devices code.
Replace swsssdk with swsscommon in alphanetworks devices code.
> [AlphaNetworks] Replace swsssdk with swsscommon in alphanetworks devices

- sonic-slave-bullseye/Dockerfile.j2
To support saithriftv2 build for bullseye dockers
Added the dependencies documented in the SAI docs and used in sonic-slave-buster
Build saithriftv2 in the sonic-slave-bullseye
> [bullseye] add dependencies for saithriftv2 build

- .azure-pipelines/azure-pipelines-build.yml
With the Broadcom syncd containers getting upgraded to Bullseye, the DNX
RPC container is no longer automatically built. Explicitly add a make
command to build it.
Can only be verified when the official build pipeline runs.
> Build the Broadcom DNX RPC container as part of the official build

- Makefile.work
- Pass TARGET_BOOTLOADER variable value to slave build infra
The TARGET_BOOTLOADER is always blank when referred to in the Makefiles which are executed inside the slave build container.
Pass it on the make command invoking slave.mk explicitly similar to other environment variables.
kdump-tools package is installed on sonic-broadcom.bin image.
> Fix TARGET_BOOTLOADER variable assignment

- dockers/docker-dhcp-relay/dhcp-relay.monitors.j2
- dockers/docker-dhcp-relay/dhcp-relay.programs.j2
- dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
- dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
- src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay-no-ip-helper.supervisord.conf
- src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay.supervisord.conf
- src/sonic-config-engine/tests/sample_output/py3/docker-dhcp-relay-no-ip-helper.supervisord.conf
- src/sonic-config-engine/tests/t0-sample-no-ip-helper-graph.xml
- src/sonic-config-engine/tests/test_j2files.py
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/10654
dhcp6relay reads ipv6 helpers from DHCP_RELAY table. Docker supervisord should rely on DHCP_RELAY instead of VLAN table to determine if dhcpv6 relay needs to be started. Added "vlan missing ip helper" dhcp relay unittest
Change docker supervisord to check for DHCP_RELAY table for ipv6 helpers
Added unittests
Run dhcp_relay docker, ensure ipv6 helper is present is only DHCP_RELAY table and not VLAN table, and dhcp6relay should start up
> [202012] Replace VLAN table with DHCP_RELAY table for verifying ipv6 helpers and add unittests

- src/snmpd/patch-5.7.3+dfsg/0022-etherlike-mib-memleak.patch
- src/snmpd/patch-5.7.3+dfsg/series
Signed-off-by: Sangita Maity <samaity@linkedin.com>
This fixed memory leak in ETHERLIKE-MIB. The fix is not part of net-snmp(5.7.3 version). This PR includes the patch to fix memory leak issue.
```
ke->name in stdup-ed at line 297: n->name = strdup(RTA_DATA(tb[IFLA_IFNAME]));
```
patched the fix.
[net-snmp] upstream fix link -> [snmpd}upstream link](https://github.com/net-snmp/net-snmp/commit/ed4e48b5fab165d1ba4c431e31e543f808a2c25f)
**Before The fix**
used valgrind to find memory leak.
```
root@lnos-x1-a-csw06:/# grep "definitely lost" valgrind-out.txt
==493== 4 bytes in 1 blocks are definitely lost in loss record 1 of 333
==493== 16 bytes in 1 blocks are definitely lost in loss record 25 of 333
==493== 757 bytes in 71 blocks are definitely lost in loss record 214 of 333
==493== 1,168 …
```
> [snmpd] Fixed snmpd memory leak issue

- dockers/docker-sonic-mgmt/Dockerfile.j2
In order to support Python3 migration of docker-sonic-mgmt, the docker base image should be upgrade first.
Modify docker build file(docker-sonic-mgmt/Dockerfile.j2):
1. Update base image from ubuntu18.04 to ubuntu20.04
2. Fix necessary dependencies.
Randomly select supported testbed, manually run a few tests and all pass:
vxlan/test_vxlan_decap.py
pfcwd/test_pfcwd_all_port_storm.py
acl/null_route/test_null_route_helper.py 
acl/test_acl.py
vlan/test_vlan.py
platform_tests/test_reboot.py
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit[None-xoff_1]
Update docker-sonic-mgmt/Dockerfile.j2. After upgrade, Py2 is 2.7.18, Py3 is 3.8.10, Ubuntu is 20.04.
> Upgrade docker-sonic-mgmt base image from Ubuntu18.04 to 20.04

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/peer-switch.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/peer-switch.json
- src/sonic-yang-models/yang-models/sonic-peer-switch.yang
Address issue https://github.com/sonic-net/sonic-buildimage/issues/10966
sign-off: Jing Zhang zhangjing@microsoft.com 
Add sonic-peer-switch.yang and unit tests.
Compile Compile target/python-wheels/sonic_yang_mgmt-1.0-py3-none-any.whl and target/python-wheels/sonic_yang_models-1.0-py3-none-any.whl.
https://github.com/sonic-net/sonic-buildimage/blob/b721ff87b976a6a38bdd65443ea3bc686014e783/src/sonic-yang-models/doc/Configuration.md#peer-switch
> [YANG] add peer switch model

- src/sonic-py-common/sonic_py_common/multi_asic.py
Modify get_all_namespaces to get fabric namespace
to support VoQ chassis.
VoQ chassis supervisor will have Fabric asics and the sub_role for fabric asics will be "Fabric".
The fabric asics namespaces are not being returned in get_all_namespaces() and is required in caclmgrd to add right cacl to allow internal docker traffic from fabric asic namespaces.
test_cacl_application fails on VoQ chassis Supervisor with the error:
Failed: Missing expected iptables rules: set(['-A INPUT -s 240.127.1.1/32 -d 240.127.1.1/32 -j ACCEPT', '-A INPUT -s 240.127.1.3/32 -d 240.127.1.1/32 -j ACCEPT', '-A INPUT -s 240.127.1.2/32 -d 240.127.1.1/32 -j ACCEPT'])
Update get_all_namespaces to return fabric namespaces list.
Verified on VoQ chassis.
> [chassis]: Add support to get list of fabric asic namespaces

- platform/checkout/cisco-8000.ini
Update cisco-8000 submodule to v0.111 drop
> Update cisco-8000 submodule to v0.111

- device/arista/x86_64-arista_720dt_48s/Arista-720DT-48S/hwsku.json
Fixes link training issue seen on 720DT-48S running SONiC image using SAI 7.1.7.1 that causes orchagent to crash
Update hwsku.json to set autoneg to "on" for Ethernet24-47.
Verified on 720DT-48S platform that orchagent does not exit, all links are up.
> [Arista] Enable AN for Ethernet24-47 on 720DT-48S

- platform/broadcom/docker-saiserver-brcm/Dockerfile.j2
- platform/mellanox/docker-saiserver-mlnx/Dockerfile.j2
Upgrade libboost-atomic1.71 to libboost-atomic1.74
Upgrade libboost-atomic1.71 to libboost-atomic1.74
Upgrade libboost-atomic1.71 to libboost-atomic1.74
local build with NOSTRETCH=y NOJESSIE=y NOBUSTER=y SAITHRIFT_V2=y make target/docker-saiserverv2-brcm.gz
> [SAIServer] support saiserver v2 in bullseye

- platform/components/docker-gbsyncd-broncos.mk
- platform/template/docker-gbsyncd-base.mk
The directory `/var/warmboot` as top directory for warmboot feature is also needed in docker gbsyncd. Some vendor SAI might save data under it. Without it, the SAI init/creation API failure has happened on PikeZ platform.
Mount host directory /host/warmboot as /var/warmboot in docker gbsyncd, which is same as what it has done on docker syncd.
The directory /var/warmboot exists in docker gbsyncd.
> [gbsyncd] Add mount directory /var/warmboot in docker gbsyncd

- device/arista/x86_64-arista_720dt_48s/platform.json
Content of `platform.json` was outdated and some `platform_tests/api` of sonic-mgmt were failing.
Added the necessary values to `platform.json`
Running `platform_tests/api` of sonic-mgmt should yield 100% passrate.
Fix content of platform.json for DCS-720DT-48S
> [Arista] Fix content of platform.json for DCS-720DT-48S

- build_debian.sh
- files/scripts/syncd.sh
Collecting MST dump before syncd restart on shutdown notification during a SAI failure
Dump can be found under:
```
root@sonic:/home/admin# ls -l /var/dump/mstdump/
total 10684
-rw-r--r-- 1 root root 5460332 Aug 15 18:41 mstdump_20220815_184143.tar.gz
-rw-r--r-- 1 root root 5473253 Aug 15 21:46 mstdump_20220815_214642.tar.gz
root@sonic:/home/admin# tar -xvzf /var/dump/mstdump/mstdump_20220815_214642.tar.gz
├── ir-gdb
│   └── core
└── mstdump
├── mstdump1
├── mstdump2
├── mstdump3
└── mststatus
```
Checked for shutdown notification log in sairedis and used it to determine whether the shutdown is normal or due to SAI failure
Simulated a SAI failure event and verified it. Verified it also on different reboots and config reload scenarios the dump is not generated
> [201911][Mellanox] Collect MST dump before syncd restart on shutdown notification

- src/sonic-py-common/sonic_py_common/device_info.py
- src/sonic-py-common/tests/device_info_test.py
Backport https://github.com/sonic-net/sonic-buildimage/pull/11696 to 202205, since direct cherry-pick is causing build failure
> [202205] [sonic_py_common] Cache Static Information in device_info to speed up CLI response

- slave.mk
The current error handling code for when a deb package fails to be
installed currently has a chain of commands linked together by && and
ends with `exit 1`. The assumption is that the commands would succeed,
and the last `exit 1` would end it with a non-zero return code, thus
fully failing the target and causing the build to stop because of bash's
-e flag.
However, if one of the commands prior to `exit 1` returns a non-zero
return code, then bash won't actually treat it as a terminating error.
From bash's man page:
```
-e      Exit immediately if a pipeline (which may consist of a single simple
command), a list, or a compound command (see SHELL GRAMMAR above),
exits with a non-zero status.  The shell does not exit if the
command that …
```
> Fix error handling when failing to install a deb package

- check_install.py
Fix a build not stable issue: https://github.com/sonic-net/sonic-buildimage/issues/11620
The vs vm has started successfully, but failed to wait for the message "sonic login:".
There were 55 builds failed caused by the issue in the last 30 days.
```
AzurePipelineBuildLogs
| where startTime > ago(30d)
| where type =~ "task"
| where result =~ "failed"
| where name =~ "Build sonic image"
| where content contains "Timeout exceeded"
| where content contains "re.compile('sonic login:')"
| project-away content
| extend branchName=case(reason=~"pullRequest", tostring(todynamic(parameters)['system.pullRequest.targetBranch']),
replace("refs/heads/", "", sourceBranch))
| summarize FailedCount=dcount(buildId) by branchName
branchName	FailedCount
master	37
202012	9
202106	4
202111	2
202205	1
201911	1 …
```
> Fix vs check install login timeout issue

- platform/broadcom/docker-saiserver-brcm/Dockerfile.j2
- platform/mellanox/docker-saiserver-mlnx/Dockerfile.j2
- sonic-slave-bullseye/Dockerfile.j2
Support build saiserverv2 in bullseye
Add dependencies for building saiserverv2
Upgrade libboost-atomic1.71 to libboost-atomic1.74
Local builded with NOSTRETCH=y NOJESSIE=y NOBUSTER=y SAITHRIFT_V2=y make target/docker-saiserverv2-brcm.gz
> [202205][SAIServer] support saiserver v2 in bullseye

- .azure-pipelines/official-build.yml
Fix the official build not triggered correctly issue, caused by the azp template path not existing.
Change the azp template path.
> [ci] Fix build template not existing issue

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-z9332f.install
- platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/fast-reboot_plugin
- platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/override.conf
- platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/platform_reboot_override
- platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/soft-reboot_plugin
- platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/warm-reboot_plugin
- To gracefully unmount filesystems and stop containers while performing a cold reboot.
- Unmount ONIE-BOOT if mounted during fast/soft/warm reboot
- Override systemd-reboot service to perform a cold reboot.
- Unmount ONIE-BOOT if mounted using fast/soft/warm-reboot plugins.
On reboot, verify that the container stop and filesystem unmount services have completed execution before the platform reboot. 
Logs: [UT_Logs.txt](https://github.com/Azure/sonic-buildimage/files/8252901/UT_Logs.txt)
DellEMC: Z9332f - Graceful platform reboot
> DellEMC: Z9332f - Graceful platform reboot

- build_debian.sh
Add linux perf tool to sonic image
Use apt install in build_debian.sh
Run build
> [202205] Add linux perf tool to sonic image

- device/dell/x86_64-dell_s6000_s1220-r0/platform.json
- device/dell/x86_64-dell_s6100_c2538-r0/platform.json
- device/dell/x86_64-dellemc_z9332f_d1508-r0/platform.json
- device/dell/x86_64-dellemc_z9332f_d1508-r0/system_health_monitoring_config.json
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
To include capabilities fields in platform.json of DellEMC S6000, S6100, Z9332f platforms.
(Backport PRs: #9168, #9459)
Add the capabilities fields in each platform's respective platform.json.
Run sonic-mgmt platform api test cases that use capabilities fields and verify that the results are as expected.
[202012] DellEMC: S6000, S6100, Z9332f - Add capabilities fields in platform.json
> [202012] DellEMC: S6000, S6100, Z9332f - Add capabilities fields in platform.json

- build_debian.sh
Add linux perf tool to sonic image
Use apt install in build_debian.sh
Run build
> Add linux perf tool to sonic image

- dockers/docker-base-bullseye/Dockerfile.j2
In latest `syncd` container, it is installed bullseye, can't find command '`/usr/bin/python`'.
Some scripts such as `test_copp` still calls `/usr/bin/python` in `syncd`.
Submitted the change in #11807 for syncd docker, but it's better to add it in bullseye base docker.
Install `python-is-python3` package in bullseye base docker to resolve this issue, whatever run python or python3, it will run `/usr/bin/python3`, will not cause the error of can't find command '`/usr/bin/python`' 
run `python` in syncd container.
> Add python-is-python3 package for bullseye base docker

- device/arista/x86_64-arista_720dt_48s/Arista-720DT-48S/hwsku.json
Backport of #11839
Enable port AN ON explicitly and then port will become (oper status) UP. Somehow those ports AN are not default ON in bcm sdk.
> [202205][Arista] Enable AN for Ethernet24-47 (#11839)

- .github/workflows/label.yml
GITHUB_CONTEXT didn't been passed to label action.
PR approval failed.
> [actions] Add github context env in label action.

- files/scripts/arp_update
If IPv6 neighbor entries become "FAILED", then any subsequent neighbor advertisement messages will not be able to resolve these entries in the neighbor cache, only a ping or other traffic being sent from the device will be able to resolve these. This means that standby ToRs may have such FAILED entries stuck in the neighbor cache for a long time.
After pinging any failed IPv6 neighbor entries, set the remaining failed/incomplete entries to a permanent INCOMPLETE state. This manual setting to INCOMPLETE prevents these entries from automatically transitioning to FAILED state, and since they are now incomplete any subsequent NA messages for these neighbors is able to resolve the entry in the cache.
1. Add a failed IPv6 neighbor entry to the …
> [arp_update]: Set failed IPv6 neighbors to incomplete

- files/build_templates/per_namespace/bgp.service.j2
- files/scripts/write_standby.py
MuX related operations are not warm reboot ready previously.
- Enhance write_standby.py script to skip actions during warm shutdown.
- Expand the support to BGP service.
- MuX support was added by a previous PR.
- Addressed a bug: the action should not be skipped during warm recovery.
Run test on device with following settings and validate behavior is expected:
- warm reboot/restart is not enabled.
- system level warm reboot is enabled.
- bgp warm restart was enabled.
- mux warm restart was enabled.
> [mux] skip mux operations during warm shutdown

- .azure-pipelines/run-test-template.yml
- azure-pipelines.yml
Define whether a test job is required before merging by code.
Let the failure of multi-asic and t0-sonic don't block pr merge.
The 'required' configuration can be modified by the owner in the future.
Required:
t1-lag, t0
Not required:
multi-asic, t0-sonic
AZP itself verifies it.
> Define whether a test is required by code

- device/mellanox/x86_64-nvidia_sn2201-r0/ACS-SN2201/pg_profile_lookup.ini
Remove extra empty lines in the SN2201 pg_profile_lookup.ini to make it aligned with other platforms.
This extra empty line could confuse some test cases which need to parse this file.
remove the extra empty lines
> [Mellanox] [SN2201] Remove extra empty lines in the pg_profile_lookup.ini

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/tests/caclmgrd/cacl_external_client_acl_test.py
- src/sonic-host-services/tests/caclmgrd/test_external_client_acl_vectors.py
- src/sonic-host-services/tests/common/mock_configdb.py
Currently Sonic supports the following ACL tables.
IPV6_SNMP_ACL
EVERFLOW
SSH_ONLY
..
For the Restapi/gnmi use-cases, Sonic has to support a new Table: EXTERNAL_CLIENT of type CTRLPLANE, stage ingress
This shall match on 'src ip prefix' and dst port '8080'. Caclmgrd must parse this from acl.json and install as in the below example:
iptables -A INPUT -s 20.20.20.20/27 -p tcp --dport 8080 -j ACCEPT
or ip6tables if the 'src ip prefix' is IPv6.
This change for master branch is in PR https://github.com/sonic-net/sonic-host-services/pull/9
**Steps:**
1. add EXTERNAL_CLIENT_ACL in config_db.json
```
"ACL_TABLE": {
"NTP_ACL": {
"policy_desc": "NTP_ACL",
"services": [
"NTP"
],
"stage": "ingress",
"type": "CTRLPLANE"
},
... …
```
> Support Restapi/gnmi control plane acls in 202012 branch

- files/image_config/misc/docker-wait-any
It could happen that a container has already crashed but docker-wait-any
will wait forever till it starts. It should, however, immediately exit
to make the serivce restart.
It is observed in some circumstances that the auto-restart mechanism does not work. Specifically for ```swss.service```, ```orchagent``` had crashed before ```docker-wait-any``` started in ```swss.sh```. This led ```docker-wait-any``` wait forever for ```swss``` to be in ```"Running"``` state and it results in:
```
CONTAINER ID   IMAGE                                COMMAND                  CREATED        STATUS                    PORTS     NAMES
1abef1ecebff   bcbca2b74df6                         "/usr/local/bin/supe…"   22 hours ago   Up 22 hours …
```
> [docker-wait-any] immediately start to wait 

- dockers/docker-fpm-frr/Dockerfile.j2
- files/build_templates/sonic_debian_extension.j2
- rules/docker-eventd.mk
Some PR builds fails to find this file. Remove it temporarily until we root cause it
> Fix PR build failure

- dockers/docker-macsec/cli/clear/plugins/clear_macsec_counter.py
- dockers/docker-macsec/cli/show/plugins/show_macsec.py
- rules/docker-macsec.mk
To support clear MACsec counters by `sonic-clear macsec`
Add macsec sub-command in sonic-clear to cache the current macsec stats, and in the `show macsec` command to check the cache and return the diff with cache file.
```
admin@vlab-02:~$ show macsec  Ethernet0
MACsec port(Ethernet0)
---------------------  -----------
cipher_suite           GCM-AES-128
enable                 true
enable_encrypt         true
enable_protect         true
enable_replay_protect  false
replay_window          0
send_sci               true
---------------------  -----------
MACsec Egress SC (52540067daa70001)
-----------  -
encoding_an  0
-----------  -
MACsec Egress SA (0)
-------------------------------------  --------------------------------
auth_key …
```
> [macsec]: Add MACsec clear CLI support

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
Some of the sonic-mgmt test cases failed in DellEMC Z9332f switch 
Handled the platform API to fix the issue  
Run sonic-mgmt SFP test cases.
UT logs:
[SFP UT.txt](https://github.com/sonic-net/sonic-buildimage/files/9401012/SFP.UT.txt)
> DellEMC Z9332f: Fix SFP issue

- platform/checkout/cisco-8000.ini
Update cisco-8000 submodule to v0.112
> Update cisco-8000 submodule to v0.112

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/tests/caclmgrd/cacl_external_client_acl_test.py
- src/sonic-host-services/tests/caclmgrd/test_external_client_acl_vectors.py
- src/sonic-host-services/tests/common/mock_configdb.py
Currently Sonic supports the following ACL tables.
IPV6_SNMP_ACL
EVERFLOW
SSH_ONLY
..
For the Restapi/gnmi use-cases, Sonic has to support a new Table: EXTERNAL_CLIENT of type CTRLPLANE, stage ingress
This shall match on 'src ip prefix' and dst port '8080'. Caclmgrd must parse this from acl.json and install as in the below example:
iptables -A INPUT -s 20.20.20.20/27 -p tcp --dport 8080 -j ACCEPT
or ip6tables if the 'src ip prefix' is IPv6.
This change for master branch is in PR https://github.com/sonic-net/sonic-host-services/pull/9
**Steps:**
1. add EXTERNAL_CLIENT_ACL in config_db.json
```
"ACL_TABLE": {
"NTP_ACL": {
"policy_desc": "NTP_ACL",
"services": [
"NTP"
],
"stage": "ingress",
"type": "CTRLPLANE"
},
... …
```
> Support Restapi/gnmi control plane acls in 202205 branch

- platform/vs/docker-sonic-vs/Dockerfile.j2
Fix the dbus-pyhon installation failure when building docker-sonic-vs, caused by the command dbus-run-session not found.
The command "dbus-run-session" should be the new dependency introduced in dbus-python 1.3.2, the old version 1.2.18 does not have the issue.
Install the dbus debian package which contains the command dbus-run-session.
It is not a blocking issue on release branches. The release branches with reproducible build feature can avoid such issue in official builds and PR builds, it only block the version upgrade (trying to upgrade from 1.2.18 to 1.3.2).
> [Build] Fix dbus-run-session command not found issue when install dbus-python

- src/sonic-frr/patch/0009-ignore-route-from-default-table.patch
- src/sonic-frr/patch/series
Fixes #11995 and #9188 
Add a patch for zebra to ignore sending netlink messages for routes in the table `RT_DEFAULT_TABLE`
Test mentioned in the github issues  #11995 and #9188
> [FRR] add patch in zebra to ignore route update on RT_TABLE_DEFAULT

- check_install.py
Why I did it
Cherry-pick  from https://github.com/sonic-net/sonic-buildimage/pull/11727 and fix conflict.
Fix a build not stable issue: #11620
The vs vm has started successfully, but failed to wait for the message "sonic login:".
There were 55 builds failed caused by the issue in the last 30 days.
AzurePipelineBuildLogs
| where startTime > ago(30d)
| where type =~ "task"
| where result =~ "failed"
| where name =~ "Build sonic image"
| where content contains "Timeout exceeded"
| where content contains "re.compile('sonic login:')" | project-away content
| extend branchName=case(reason=~"pullRequest", tostring(todynamic(parameters)['system.pullRequest.targetBranch']),
replace("refs/heads/", "", sourceBranch))
| summarize FailedCount=dcount(buildId) by branchName
branchName	FailedCount
master …
> [202012] Fix vs check install login timeout issue (#11727)

- files/build_templates/tacacs-config.timer
The timer execution may fail if triggered during a config reload (when the sonic.target is stopped). This might happen in a rare situation if config reload is executed after reboot in a small time slot (for 0 to 30 seconds) before the tacacs-config timer is triggered:
```
systemctl status tacacs-config.timer
tacacs-config.timer - Delays tacacs apply until SONiC has started
Loaded: loaded (/lib/systemd/system/tacacs-config.timer; enabled-runtime; vendor preset: enabled)
Active: failed (Result: resources) since Mon 2022-08-29 15:53:03 IDT; 1min 28s ago
Trigger: n/a
Triggers:  tacacs-config.service
Aug 29 15:47:53 r-boxer-sw01 systemd[1]: Started Delays tacacs apply until SONiC has started.
Aug 29 15:53:03 r-boxer-sw01 systemd[1]: tacacs-config.timer: Failed to queue unit startup job: …
```
> [services] Update "WantedBy=" section for tacacs-config.timer.

- files/build/versions/default/versions-web
- files/build/versions/dockers/sonic-slave-bullseye/versions-web
- files/build/versions/dockers/sonic-slave-buster/versions-web
- files/build/versions/dockers/sonic-slave-stretch/versions-web
bazelisk package with hash value 1227b24db77557d552701f6add122edc is deleted from github release.
Reproducible build only cached hash value. Package file didn't be cached. Because they are in different pipelines.
Using latest package hash instead.
> [build] Fix version of bazelisk which is lost acccidently

- files/build/versions/default/versions-web
- files/build/versions/dockers/sonic-slave-bullseye/versions-web
- files/build/versions/dockers/sonic-slave-buster/versions-web
- files/build/versions/dockers/sonic-slave-stretch/versions-web
- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
This tries to avoid builds failures due to the latest version of bazelisk changing and causing hash mismatches.
> Pin version of bazelisk to v1.13.0

- dockers/docker-sonic-mgmt/Dockerfile.j2
Issue is raised: https://github.com/sonic-net/sonic-buildimage/issues/11950
Revert PR: https://github.com/sonic-net/sonic-buildimage/pull/11831
Docker image can be built
N/A
N/A
> Revert PR#11831 "Upgrade docker-sonic-mgmt base image from Ubuntu18.04 to 20.04"

- src/sonic-frr/patch/0009-ignore-route-from-default-table.patch
- src/sonic-frr/patch/series
Fix issue #11995 : when management port goes down, zebra will remove the default route and causing ASIC to blackhole IO.
Ignore route changes in default table.
Cause management port to go down and verify that default route is not removed.
> [zebra] ignore route from default table

- dockers/docker-router-advertiser/radvd.conf.j2
Fixed the if block scope to prevent traceback due to undefined vlan_list when
VLAN_INTERFACE is not defined.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/12031
Fixed the if - endif block scope
Bring up router without VLAN_INTERFACE configuration.
'Check docker logs radv' for no traceback
/etc/radvd.conf  and /usr/bin/wait_for_link.sh files are generated properly in radv docker.
Fixed radvd.conf generation traceback when VLAN_INTERFACE is not defined
> Fixed radvd.conf generation traceback when VLAN_INTERFACE is not defined

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py
Issue#11785
Unable to get/set low power mode for QSFP28 and QSFP+
Platforms which use PDDF have common PDDF platform APIs. Since sfp_refactor framework takes care of only CMIS transceivers and platform APIs are supposed to take care of the low power mode for QSFPs.
Modified pddf_sfp.py to include get/set APIs for lpmode in case of QSFP
> sfputil show lpmode
> sfputil lpmode on/off <>
LOGS:
```
>>> platform_chassis.get_sfp(55).set_lpmode(True)
True
>>> 
>>> platform_chassis.get_sfp(55).get_lpmode()
True
>>> platform_chassis.get_sfp(55).set_lpmode(False)
True
>>> 
>>> platform_chassis.get_sfp(55).get_lpmode()
False
```
> Adding support for get/set low power mode for QSFPs in PDDF common APIs

- src/iccpd/src/cmd_option.c
- src/iccpd/src/iccp_ifm.c
- src/iccpd/src/iccp_main.c
- src/iccpd/src/iccp_netlink.c
- src/iccpd/src/mclagdctl/mclagdctl.c
Replace unsafe functions in iccpd
Replace `memset()` by zero initialization
Replace `strtok()` by `strtok_r()`
> Replace unsafe functions in iccpd

- .github/pull_request_template.md
…ised.
Signed-off-by: kannankvs <kannan_kvs@dell.com>
> Updated PR Template for a comment to add label/tag for the feature

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
ethtool print error logs when EEPROM of a SFP is not available. It prints error like this:
```
INFO pmon#/supervisord: xcvrd Cannot get module EEPROM information: Input/output error
INFO pmon#/supervisord: xcvrd Cannot get Module EEPROM data: Invalid argument
```
However, this log does not contain the relevant SFP index which is hard for developer/qa to find the exactly SFP.
Redirect ethtool stderr to subprocess and log it better
Manual test
> [Mellanox] Redirect ethtool stderr to subprocess for better error log

- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
What I did:
Cherry-pick the commit from master where in multi-asic platforms bgp template rendering fails which needs Loopback4096 IP Address. Issue happens because of timing/race condition where if peer gets added first and then Loopback4096 notification comes to bgpcfgd. For 201911 this causes failure of rendering on this 2 lines:
https://github.com/sonic-net/sonic-buildimage/blob/201911/dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2#L22
https://github.com/sonic-net/sonic-buildimage/blob/201911/dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2#L25
Corresponding Master commit with fix: https://github.com/sonic-net/sonic-buildimage/pull/8966/files#diff-0d6a37ad8efc25e66a5187da192766ce7473ff7809bb6c82e81616f4b7413575
Fix is to add dependency for BGP …
> [201911] Fix BGP Template rendering failure that needs Loopback4096 IP Address

- dockers/docker-database/docker-database-init.sh
- dockers/docker-database/flush_unused_database
Reverts sonic-net/sonic-buildimage#11677
The master branch PR https://github.com/sonic-net/sonic-buildimage/pull/11600 been cherry to 202205 branch by mistake.
Revert change in sonic-net/sonic-buildimage#11677
Fix docker-database flush_unused_database failed issue: https://github.com/Azure/sonic-buildimage/issues/11597
When change flush_unused_database from use swsssdk to use swsscommon, get_instancelist() and get_dblist() name changed but not update.
> Revert "[database] Fix docker-database flush_unused_database failed issue"

- device/arista/x86_64-arista_7800_sup/chassisdb.conf
- files/build_templates/docker_image_ctl.j2
Multi-asic Docker instances are created behind Docker's default bridge
which doesn't allow talking to other Docker instances that are in the
host network (like database-chassis).
On linecards, we configure midplane interfaces to let per-asic docker
containers talk to CHASSIS_DB on the supervisor through internal chassis
network.
On the supervisor we don't need to use chassis internal network, but we
still need a similar setup in order to allow fabric containers to talk
to database-chassis
Reusing existing code used to setup the midplane network on a linecard,
except that we only need a pair of veth interfaces on the supervisor to allow
per-asic docker instances access to the midplane subnet.
> [chassis] Configure midplane network on supervisor

- files/build_templates/sonic_debian_extension.j2
- src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py
- src/sonic-ctrmgrd/ctrmgr/kube_commands.py
- src/sonic-ctrmgrd/tests/common_test.py
- src/sonic-ctrmgrd/tests/kube_commands_test.py
Need to change sonic current k8s worker code to make sonic join current k8s cluster with local AME cert 
Generate client identity by sonic local AME cert
File path is /etc/sonic/kube_admin.conf
> Make client indentity by AME cert

- src/isc-dhcp/patch/0013-Fix-dhcrelay-agent-option-buffer-pointer-logic.patch
- src/isc-dhcp/patch/series
Current isc-dhcp uses below code to remove DHCP option:
`memmove(sp, op, op[1] + 2);`
`sp += op[1] + 2;`
sp points to the option to be stripped, we can call it as option S.
op points to the option after options S, we can call it as option O.
DHCP option is a typical type-length-value structure, the first byte is type, the second byte is length, and remain parts are value.
In this case, option O length is bigger than option S, and more than 2 bytes, after the memmove, we will get this result:
Now Option S and Option O are overwritten, op[1] was the length of Option O, and it's modified after memmove.
But current implementation is still using op[1] as length to update sp (sp+=op[1]+2), so we get the wrong sp.
Create patch from …
> Fix dhcp option buffer issue

- files/build_templates/tacacs-config.timer
Manually cherry-picking #11893 
The timer execution may fail if triggered during a config reload (when the sonic.target is stopped). This might happen in a rare situation if config reload is executed after reboot in a small time slot (for 0 to 30 seconds) before the tacacs-config timer is triggered:
systemctl status tacacs-config.timer
tacacs-config.timer - Delays tacacs apply until SONiC has started
Loaded: loaded (/lib/systemd/system/tacacs-config.timer; enabled-runtime; vendor preset: enabled)
Active: failed (Result: resources) since Mon 2022-08-29 15:53:03 IDT; 1min 28s ago
Trigger: n/a
Triggers:  tacacs-config.service
Aug 29 15:47:53 r-boxer-sw01 systemd[1]: Started Delays tacacs apply until SONiC has started.
Aug 29 15:53:03 r-boxer-sw01 systemd[1]: tacacs-config.timer: Failed to …
> [202205] [services] Update "WantedBy=" section for tacacs-config.timer. (#11893)

- files/build_templates/per_namespace/bgp.service.j2
interfaces-config service restarts networking service, during the restart loopback interface address is being removed and reassigned back, leaving loopback without an ipv4 address for a while.
On SONiC startup and config reload interfaces-config and bgp services start in parallel and sometimes
fpmsyncd in bgp attempts bind to loopback while it does not have an address, fails with the log
`Exception "Cannot assign requested address" had been thrown in daemon`
and exits with rc 0.
```
root@sonic:/# supervisorctl status
fpmsyncd                         EXITED    Jul 20 05:04 AM
zebra                            RUNNING   pid 35, uptime 6:15:05
zsocket                          EXITED    Jul 20 05:04 AM
```
```
docker logs bgp
INFO …
```
> [bgp][service] Start bgp service after interfaces-config service

- device/arista/x86_64-arista_common/plugins/ssd_util.py
Some Arista products do not have an SSD but use an eMMC instead.
The SsdUtil plugin is therefore extended to support both.
Implemented `ssd_util.py` platform plugin loaded by `ssdutil`.
This plugin fallback to the default SONiC implementation if the arista one can't be found.
Run `show platform ssdhealth` on a product with an eMMC
Implement ssd_util plugin for Arista products
> [Arista] Implement ssd_util plugin

- build_debian.sh
Improve SSHD config to use more secure settings
According to Sonic OS review result, SSHD config file /etc/ssh/sshd_config using insecure settings.
Change build_debian.sh script to set following settings to /etc/ssh/sshd_config:
ClientAliveInterval is set to 300
MaxAuthTries is set to default of 3
Banner set to /etc/issue
LogLevel is set to VERBOSE
Improve SSHD config to use more secure settings
> Improve SSHD config to use more secure settings

- platform/checkout/cisco-8000.ini
Update cisco-8000 submodule to v0.116
> Update cisco-8000 submodule to v0.116

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.init
Signed-off-by: Xichen Lin <lukelin0907@gmail.com>
Haliburton device has very little memory, and turning on swap will potentially increase the stability of the device.
Turn on swap in the init file.
Modified the script and did reboot to see if things are as expected.
Turn on swap space for Haliburton device.
> [HLX] Enable swap for haliburton device.

- src/sonic-py-common/sonic_py_common/general.py
- src/sonic-py-common/tests/test_general.py
`getstatusoutput()` function from `subprocess` module has shell injection issue because it includes `shell=True` in the implementation
Eliminate duplicate code
Reimplement `getstatusoutput_noshell()` and `getstatusoutput_noshell_pipe()` functions with `shell=False`
Add `check_output_pipe()` function
Pass UT
> [sonic-py-common] Add getstatusoutput_noshell() functions to general module

- device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-C128/port_config.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-C128/sai_4700_128x100g.xml
- platform/mellanox/mlnx-platform-api/tests/input_platform/__init__.py
- platform/mellanox/mlnx-platform-api/tests/input_platform/output_sfp.py
- platform/mellanox/zero_profiles.j2
Add NVIDIA Copyright header for new "NVIDIA" files
Add the copyright header as remark at the head of the file
> [202205] [Mellanox] update NVIDIA copyright header for NVIDIA added files

- src/system-health/health_checker/service_checker.py
Fix the command "sudo show system-health summary" shows the following error on the supervisor card.  Fixes #10630
This issue is caused by the function get_critical_process_list_from_file() that is not able to handle the empty line in the file critical_processes.  On supervisor card,  the critical_processes file under swss which is derived from the critical_processes.j2 file and contains empty lines.  Added code the check the the re.match result is None, don't continue to process it  
1)  boot the image on supervisor card,  issue command "sudo show system-health summary".  The output should be shown as below:
```
admin@supervisor:~$ sudo show system-health summary 
System status summary
System status LED  green
Services:
Status: OK
Hardware:
Status: OK
```
> [chassis][supervisor] show system-health summary fails on the supervisor card

- build_image.sh
Newer versions of Aboot will expect this `BUILD_DATE=` attribute to exist and contain valid data.
It is only use for the `secureboot` feature and does not impact regular boot.
Added the new attribute declaration in `build_image.sh`
Build a SWI and boot it on a secureboot enabled product with the latest Aboot version.
Add new SWI attribute required by Aboot for secureboot
> [Arista] Add new SWI attribute required by Aboot for secureboot

- .azure-pipelines/docker-sonic-slave-template.yml
Fix docker-sonic-slave pipeline issues.
> [ci] Use absolute template file path in docker-sonic-slave pipeline.

- dockers/docker-sonic-mgmt/Dockerfile.j2
The python packages azure-kusto-data and azure-kusto-ingest packages for python2 are too old and not really used. The python3 environment has newer version of these packages installed. This change is to deprecate these two packages for python2 in docker-sonic-mgmt image.
Removed the lines for installing old version of packages `azure-kusto-data` and `azure-kusto-ingest` in python2 in the Dockerfile template.
> [docker-sonic-mgmt] Deprecate azure-kusto-data & azure-kusto-ingest for py2

- platform/vs/docker-sonic-vs/Dockerfile.j2
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/12009, and fix code conflict.
Fix the dbus-pyhon installation failure when building docker-sonic-vs, caused by the command dbus-run-session not found.
The command "dbus-run-session" should be the new dependency introduced in dbus-python 1.3.2, the old version 1.2.18 does not have the issue.
Install the dbus debian package which contains the command dbus-run-session.
It is not a blocking issue on release branches. The release branches with reproducible build feature can avoid such issue in official builds and PR builds, it only block the version upgrade (trying to upgrade from 1.2.18 to 1.3.2).
> [202111] [Build] Fix dbus-run-session command not found issue when install dbus-python #12009

- platform/vs/docker-sonic-vs/Dockerfile.j2
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/12009, and fix code conflict.
Fix the dbus-pyhon installation failure when building docker-sonic-vs, caused by the command dbus-run-session not found.
The command "dbus-run-session" should be the new dependency introduced in dbus-python 1.3.2, the old version 1.2.18 does not have the issue.
Install the dbus debian package which contains the command dbus-run-session.
It is not a blocking issue on release branches. The release branches with reproducible build feature can avoid such issue in official builds and PR builds, it only block the version upgrade (trying to upgrade from 1.2.18 to 1.3.2).
> [202106] [Build] Fix dbus-run-session command not found issue when install dbus-python #12009

- files/build_templates/docker_image_ctl.j2
This PR should be merged together with the sonic-utilities PR (https://github.com/sonic-net/sonic-utilities/pull/2286) and sonic-sairedis PR (https://github.com/sonic-net/sonic-sairedis/pull/1100).
Use redis contents from dump file in fast-reboot.
Improve fast-reboot flow by utilizing the warm-reboot infrastructure.
This followes https://github.com/sonic-net/SONiC/blob/master/doc/fast-reboot/Fast-reboot_Flow_Improvements_HLD.md
Use redis contents from dump file in fast-reboot as it is being used in warm-reboot
Community test for fast-reboot
> [fastboot] fastboot enhancement: Use warm-boot infrastructure for fast-boot

- platform/mellanox/mlnx-fw-upgrade.j2
Porting https://github.com/sonic-net/sonic-buildimage/pull/3723 to 201911
Extend Mellanox FW utils with CPLD update feature
Added support for CPLD upgrade to Mellanox FW utility
Updated Mellanox FW utility
mlnx-fw-upgrade.sh --upgrade --cpld # Regular CPLD update flow
UPDATE_MLNX_CPLD_FW=1 mlnx-fw-upgrade.sh --upgrade # Force CPLD refresh only
> [201911][mellanox] Extend Mellanox FW utils with CPLD update

- src/ifupdown2/patch/0003-Fix-the-return-value-of-utils._execute_subprocess-me.patch
- src/ifupdown2/patch/series
Patch bug in ifupdown2 package which may cause dhclient not to run properly.
Backport ifupdown2 patch https://github.com/CumulusNetworks/ifupdown2/pull/242 on ifupdown2 v3.0.0-1
It fixes the return value of the utils._execute_subprocess() method in case the subprocess output is empty.
Run the flow described in issue #9630
Fix issue that may cause dhclient not to run properly.
> [ifupdown2]:Patch ifupdown2 (#9630)

- scripts/build_kvm_image.sh
Fix the build unstable issue caused by the kvm 9000 port is not ready to use in 2 seconds.
```
2022-09-02T10:57:30.8122304Z + /usr/bin/kvm -m 8192 -name onie -boot order=cd,once=d -cdrom target/files/bullseye/onie-recovery-x86_64-kvm_x86_64_4_asic-r0.iso -device e1000,netdev=onienet -netdev user,id=onienet,hostfwd=:0.0.0.0:3041-:22 -vnc 0.0.0.0:0 -vga std -drive file=target/sonic-6asic-vs.img,media=disk,if=virtio,index=0 -drive file=./sonic-installer.img,if=virtio,index=1 -serial telnet:127.0.0.1:9000,server
2022-09-02T10:57:30.8123378Z + sleep 2.0
2022-09-02T10:57:30.8123889Z + '[' -d /proc/284923 ']'
2022-09-02T10:57:30.8124528Z + echo 'to kill kvm:  sudo kill 284923'
2022-09-02T10:57:30.8124994Z to kill kvm:  sudo kill 284923
2022-09-02T10:57:30.8125362Z + ./install_sonic.py …
```
> [Build] Fix the build unstable issue caused by the kvm not ready

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
This reverts commit 9750cb48c642281157ddd405674bdca9710e1edc.
There is a PR to handle master branch revert: https://github.com/sonic-net/sonic-buildimage/pull/12183
The PR to be reverted introduced many notice logs every 1 minute if SFP is not plugged:
```
Cannot get module EEPROM information: Input/output error
```
Before the "bad" PR, the message format is like this:
```
INFO pmon#supervisord: xcvrd Cannot get module EEPROM information: Input/output error
```
It was truncated by rsyslog because every message is the same. However, the "bad" PR introduces SFP index to the message:
```
NOTICE pmon#xcvrd: Failed to get EEPROM data for sfp 39: Cannot get module EEPROM information: Input/output error
```
Rsyslog no longer truncate such log and many such messages are flooded to syslog.
Revert …
> [Mellanox] [202205] Revert "[Mellanox] Redirect ethtool stderr to subprocess for better error log (#12038)"

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
This reverts commit 9750cb48c642281157ddd405674bdca9710e1edc.
There is a PR to handle 202205 branch revert: https://github.com/sonic-net/sonic-buildimage/pull/12184
The PR to be reverted introduced many notice logs every 1 minute if SFP is not plugged:
```
Cannot get module EEPROM information: Input/output error
```
Before the "bad" PR, the message format is like this:
```
INFO pmon#supervisord: xcvrd Cannot get module EEPROM information: Input/output error
```
It was truncated by rsyslog because every message is the same. However, the "bad" PR introduces SFP index to the message:
```
NOTICE pmon#xcvrd: Failed to get EEPROM data for sfp 39: Cannot get module EEPROM information: Input/output error
```
Rsyslog no longer truncate such log and many such messages are flooded to syslog.
Revert …
> [Mellanox] Revert "[Mellanox] Redirect ethtool stderr to subprocess for better error log (#12038)"

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Fix a typo in chassis platform API which causes the following error
```
>>> import sonic_platform as P
>>> c = P.platform.Platform().get_chassis()
>>> sl = c.get_all_sfps()
>>> sl[0].get_lpmode()
Sep 28 07:48:33 INFO    LOG: Initializing SX log with STDOUT as output file.
False
>>> del c
Exception ignored in: <function Chassis.__del__ at 0x7f1d166ef8b0>
File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 126, in __del__
self.sfp_module.deinitialize_sdk_handle(sfp_module.SFP.shared_sdk_handle)
NameError: name 'sfp_module' is not defined
```
Use self while using the SDK handle 
Manual test
```
>>> import sonic_platform as P
>>> c = P.platform.Platform().get_chassis()
>>> sl = …
```
> [Mellanox] Fix a typo in platform API

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Fix a typo in chassis platform API which causes the following error
```
>>> import sonic_platform as P
>>> c = P.platform.Platform().get_chassis()
>>> sl = c.get_all_sfps()
>>> sl[0].get_lpmode()
Sep 28 07:48:33 INFO    LOG: Initializing SX log with STDOUT as output file.
False
>>> del c
Exception ignored in: <function Chassis.__del__ at 0x7f1d166ef8b0>
File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 126, in __del__
self.sfp_module.deinitialize_sdk_handle(sfp_module.SFP.shared_sdk_handle)
NameError: name 'sfp_module' is not defined
```
Use self while using the SDK handle 
Manual test
```
>>> import sonic_platform as P
>>> c = P.platform.Platform().get_chassis()
>>> sl = …
```
> [202205][Mellanox] Fix a typo in platform API

- .gitmodules
- src/sonic-py-common/setup.py
- src/sonic-py-common/sonic_py_common/sonic_db_dump_load.py
Porting sonic_db_dump_load.py from sonic-py-swsssdk to sonic-py-common.
sonic-py-swsssdk will be deprecate, so porting sonic_db_dump_load.py to sonic-py-common.
Copy sonic_db_dump_load.py to sonic-py-common, and fix minor API different.
The platform_tests/test_advanced_reboot.py::test_warm_reboot will cover this script.
Porting sonic_db_dump_load.py from sonic-py-swsssdk to sonic-py-common.
> [sonic-py-common] porting sonic_db_dump_load.py from sonic-py-swsssdk to sonic-py-common

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/component.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/platform_utils.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
Co-authored-by: Taras Keryk <tarasx.keryk@intel.com>
Sometime, SIGTERM processing by psud takes more then default 10sec (please see stopwaitsecs in http://supervisord.org/configuration.html).
Due to this, the following two testcases may fail:
```
test_pmon_psud_stop_and_start_status
test_pmon_psud_term_and_start_status
```
Also, limited `get_bmc_version()` execution time to 1 sec.
Introduced two levels of SIGTERM handlers:
1. The PSU class level `signal_handler()` that executes a default handler (`psud` SIGTERM handler) and avoids subsequent `psu_info_get()` executions.
2. The `cancel_on_sigterm()` decorator that executes class level `signal_handler()` and raises an exception to cancel current `psu_info_get()` execution.
Run SONiC …
> [BFN] Canceling PSU platform API calls on SIGTERM

- azure-pipelines.yml
With continueOnError: true, a failed job returns the result: partiallySuccess, which cause it can't be rerun, since AZP consider it as passed. Then we can't only rerun t0 jobs when it fails.
Mark t0 part1 and part2 as continueOnError: false.
The pipeline will verify it.
> Make t0 part1 and part2 be able to be rerun if failed

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
get_rx_los and get_tx_fault is not supported via the exisitng interface used, need provide dummy implementation for them.
NOTE: in later releases we will get them back via different interface.
Return False * lane_num for get_rx_los and get_tx_fault
Added unit test
> [Mellanox] Provide dummy implementation for get_rx_los and get_tx_fault

- azure-pipelines.yml
[AzurePipeline] Fix vstest step failed by libyang missing. 
Fix PR merge failed because 'vstest' step does not install libyang.
Install libyang in azure pipeline.
Pass vstest step.
[AzurePipeline] Fix vstest step failed by libyang missing.
> [AzurePipeline]  Fix vstest step failed by libyang missing.

- device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-C128/port_config.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-C128/sai_4700_128x100g.xml
- platform/mellanox/mlnx-platform-api/tests/input_platform/__init__.py
- platform/mellanox/mlnx-platform-api/tests/input_platform/output_sfp.py
- platform/mellanox/zero_profiles.j2
Add NVIDIA Copyright header for new "NVIDIA" files
Add the copyright header as remark at the head of the file
> [Mellanox] update NVIDIA copyright header for NVIDIA added files

- Makefile
- Makefile.work
- slave.mk
- The Makefile.work becomes complex and it is very difficult to manage the changes across branches.
- Restructured the Makefile.work and it becomes more readable.
- Added $(QUIET) option to turn on command echo mode through command line option.
- Exported the SONIC_BUILD_VARS variable, through which make options can be set dynamically.
Eg: make SONIC_BUILD_VARS='INCLUDE_NAT=y'
> 01.Version-cache - restructuring of Makefile.work

- azure-pipelines.yml
The step was using master branch artifact, and it should use the same branch.
> Fix the wrong branch in build step "Download sonic-buildimage.vs artifact"

- rules/sonic-config.dep
When sending a PR only CI change, as expected, the target target/python-wheels/buster/sonic_config_engine-1.0-py2-none-any.whl should be from the cache, because the depended files were not changed, but it rebuilt.
See log in PR: https://github.com/sonic-net/sonic-buildimage/pull/12240
```
2022-09-30T07:16:16.9270567Z [ building ] [ target/python-wheels/buster/sonic_config_engine-1.0-py2-none-any.whl ] 
2022-09-30T07:17:52.6637892Z [ finished ] [ target/python-wheels/buster/sonic_config_engine-1.0-py2-none-any.whl ] 
```
Comparing the dpkg dep file sonic_config_engine-1.0-py3-none-any.whl.dep with the official build, the depended files are in different order, it leads to the different hash value.
The cache hit rate of the last 30 days was 11.9%, lower than expected, all the targets that …
> [Build] Fix sonic-config low dpkg hit rate issue

- build_debian.sh
This is being done for 201911 -> 202205 warmboot upgrade, and Mellanox platforms need to be able to mount the squashfs file in the old image.
Fixes #12171.
This reverts commit d5365928d4dc1fa9081cf9fe61ab47e0ef306e9c.
> Revert "[build]: Use zstd compression for base filesystem squashfs"

- files/build_templates/sonic_debian_extension.j2
- files/image_config/readline/inputrc
Since bash version 5.1, readline's bracketed-paste mode is enabled by default. This is causing these escape sequence ESC [ 2 0 0 to appear in the prompt and the command output.
Added the following in readline's init file to disable bracketed-paste mode by default
```
set enable-bracketed-paste off
```
Verified that the escape sequence are no longer seen
> Disable brackted-paste mode off by default

- device/arista/x86_64-arista_7050cx3_32s/platform.json
- device/arista/x86_64-arista_7050cx3_32s/platform_components.json
Some tests under `platform_tests/api` were failing on the 7050CX3 due to outdated facts in platform.json
Updated platform.json facts with appropriate values
Run tests under `platform_tests/api` to verify no failures
> [202205][Arista] Fix content of platform.json for DCS-7050CX3-32S

- platform/marvell-armhf/platform.conf
When using "sonic-installer install" to install a new image on  Marvell  armhf platform., the installation fails in the middle of the install process as the following:  
```
Installing image SONiC-OS-20220531.06 and setting it as default...
Command: bash /tmp/sonic_image
Error: illegal character '=' in variable name "rootfstype=ext4"
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in SONiC
ONIE Installer: platform: armhf-marvell-armhf-r0
onie_platform: armhf-nokia_ixs7215_52x-r0
Preparing for installation ...
Intalling SONiC from sonic on Platform armhf-nokia_ixs7215_52x-r0
Removing old SONiC installation /host/image-202205.0-dirty-20221003.184014
Archive:  fs.zip
creating: /host/image-20220531.06/boot/
inflating: …
```
> [armhf][sonic-installer] Fix the sonic-installer install images on  armhf platform issue

- device/centec/arm64-centec_e530_24x2c-r0/platform_reboot
- device/centec/arm64-centec_e530_24x2q-r0/platform_reboot
- device/centec/arm64-centec_e530_48s4x-r0/platform_reboot
- device/centec/arm64-centec_e530_48t4x_p-r0/platform_reboot
- device/centec/x86_64-centec_v682_48x8c-r0/platform_reboot
- device/centec/x86_64-centec_v682_48x8c-r0/plugins/led_control.py
- device/centec/x86_64-centec_v682_48x8c-r0/plugins/psuutil.py
- device/centec/x86_64-centec_v682_48y8c-r0/platform_reboot
- device/centec/x86_64-centec_v682_48y8c-r0/plugins/led_control.py
- device/centec/x86_64-centec_v682_48y8c-r0/plugins/psuutil.py
- device/centec/x86_64-ew_es6220_x48q2h4-r0/plugins/psuutil.py
- device/centec/x86_64-ew_es6220_x48q2h4-r0/plugins/sfputil.py
`subprocess.Popen()` and `subprocess.run()` is used with `shell=True`, which is very dangerous for shell injection.
Replace `os` by `subprocess`, remove `shell=True`
Remove unused functions
> [device/centec] Replace os.system and remove subprocess with shell=True

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
slb and bgp mon peers are not needed for storage backend. These neighbor are present in the minigraph.
After minigraph parsing, remove these neighbors if it is a storage backend device
Unit tests
Verified on the device that once these tables are removed, these peers don't show up in "show runningconfig bgp" output
> [minigraph] Remove SLB and bgp monitor peers for storage backend

- .github/workflows/README.md
- .github/workflows/pr_cherrypick_poststep.yml
- .github/workflows/pr_cherrypick_prestep.yml
Add github actions to auto cherry pick PRs into release branch.
1. When add tag 'Request for * Branch', create PR into release branch.
a. if failed, add 'Cherry Pick Conflict_*' label.
b. if succeeded, add 'Created PR to * Branch' label and add comment in original PR.
2. After cherry picked PRs are merged into release branch, use comment to redirect to original PR and add label 'Included in * Branch'
> [actions] Add auto cherry-pick actions to release branch

- device/virtual/x86_64-kvm_x86_64-r0/brcm_gearbox_vs/gearbox_config.json
For the change to support gearbox taps by gearbox_config.json (https://github.com/Azure/sonic-swss/pull/2158), I need to add tests to sonic-swss/tests/test_gearbox.py to satisfy the test coverage of the change. The existing code in test_gearbox.py has already used brcm_gearbox_vs and here is to add some gearbox tap value to its gearbox_config.json, for the added tests in sonic-swss/tests/test_gearbox.py.
This change itself will not affect existing code.
> Add gearbox taps to vs gearbox_config.json

- src/sonic-build-hooks/hooks/apt-get
Fix apt-get remove/purge version not locked issue when the apt-get options not specified.
Add a space character before and after the command line parameters.
> [Build][Bug] Fix apt-get remove version not locked issue

- device/barefoot/x86_64-accton_as9516_32d-r0/platform.json
- device/barefoot/x86_64-accton_wedge100bf_32x-r0/platform.json
- device/barefoot/x86_64-accton_wedge100bf_65x-r0/platform.json
- device/barefoot/x86_64-accton_wedge100bf_65x-r0/platform_components.json
- device/barefoot/x86_64-accton_wedge100bf_65x-r0/thermal_thresholds.json
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/component.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/thermal.py
- To reduce an access to I2C bus
- To speed-up thermals polling time
- To fix platform.json info as per wedge100bf_65x requirements
Added local thermal cache that is updated on read once in >5sec
```
show platform temperature
show platform firmware status
```
Run SONiC platform CTs
> [BFN] Reworked BFN platform thermals plugin

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_components.template
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_ndk.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/platform.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/platform_components.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_ndk.json
Update Nokia platform IXR7250 platform_ndk.json files with the nokia_log_level option to  allow users to override the logging level for the Nokia NDK processes -- sr_device_mgr,  ndk-qfpga_mgr and eth_switch
Modify the platform_ndk.json file with the following option. And default value is "error"
```
{
"key": "sonic_log_level",
"stringval": "error"
}
```
On running platform, verify the change by checking file /etc/opt/srlinux/startup_debug.json
```
admin@ixre-egl-board40:~$ cat /etc/opt/srlinux/startup_debug.json 
{
"options": [
{
"key": "sfp_init_tx_en",
"stringval": "yes"
},
{
"key": "midplane_subnet",
"stringval": "10.6.0.0/16"
},
{
"key": "midplane_monitor",
"stringval": "yes"
},
{
"key": "monitor_action",
"stringval": "reboot"
},
{
"key": "grpc_thermal_monitor",
"stringval": "yes"
}, …
```
> [Nokia] Update Nokia platform IXR7250E device data

- .github/workflows/pr_cherrypick_prestep.yml
The pre-cherry-pick action get a wrong author: sonic-net.
Fix it to help PR owner to realize that there is conflict.
> [action] Fix PR pre-cherry-pick action wrong author issue.

- src/sonic-build-hooks/hooks/dpkg
'dpkg -i' maybe conflict with 'apt-get install'.
Use the same lock with apt-get when running 'dpkg -i'.
> [build] Fix dpkg front lock issue caused by apt-get install

- device/nokia/armhf-nokia_ixs7215_52x-r0/platform_asic
changed the platform device name under nokia directory; we now need to specify marvell armhf/arm64 to provide more accurate platform identity. otherwise onie discovery won't recognize the asic being installed.
when we load images using onie discovery, the process was failing because of marvell ASIC mismatch
replace the platform asic with marvell-armhf under 7215
load a new image using http server and verify that the image can be loaded successfully
> fixed nokia platform m0 asic mismatch

- device/common/pddf/plugins/fanutil.py
`eval()` - not secure against maliciously constructed input, can be dangerous if used to evaluate dynamic content. This may be a code injection vulnerability.
`eval()` - use `literal_eval()`
> [device/common] Replace eval function

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/restapi.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/restapi.json
- src/sonic-yang-models/yang-models/sonic-restapi.yang
> [Yang model] add Restapi yang file

- files/build_templates/sonic_debian_extension.j2
- platform/vs/docker-sonic-vs.mk
- rules/sonic-py-common.mk
- slave.mk
Remove swsssdk from sonic OS image and docker image
swsssdk is deprecated, so need remove from image.
Update config file to remove swsssdk from image.
Pass all test case.
Remove swsssdk from sonic OS image and docker image
> Remove swsssdk from sonic OS image and docker container image

- scripts/build_kvm_image.sh
Why I did it
Fix the build unstable issue caused by the kvm 9000 port is not ready to use in 2 seconds.
2022-09-02T10:57:30.8122304Z + /usr/bin/kvm -m 8192 -name onie -boot order=cd,once=d -cdrom target/files/bullseye/onie-recovery-x86_64-kvm_x86_64_4_asic-r0.iso -device e1000,netdev=onienet -netdev user,id=onienet,hostfwd=:0.0.0.0:3041-:22 -vnc 0.0.0.0:0 -vga std -drive file=target/sonic-6asic-vs.img,media=disk,if=virtio,index=0 -drive file=./sonic-installer.img,if=virtio,index=1 -serial telnet:127.0.0.1:9000,server 2022-09-02T10:57:30.8123378Z + sleep 2.0
2022-09-02T10:57:30.8123889Z + '[' -d /proc/284923 ']' 2022-09-02T10:57:30.8124528Z + echo 'to kill kvm:  sudo kill 284923' 2022-09-02T10:57:30.8124994Z to kill kvm:  sudo kill 284923 2022-09-02T10:57:30.8125362Z + ./install_sonic.py …
> [Build] Fix the build unstalbe issue caused by the kvm not ready (#12180)

- .gitmodules
- files/image_config/environment/motd
> [201803] Change submodule path from Azure to sonic-net

- .gitmodules
- files/image_config/environment/motd
> [201811] Change submodule path from Azure to sonic-net

- .gitmodules
- files/image_config/environment/motd
> [201807] Change submodule path from Azure to sonic-net

- .gitmodules
- files/image_config/environment/motd
> [201712] Change submodule path from Azure to sonic-net

- .gitmodules
- files/image_config/environment/motd
> [201709] Change submodule path from Azure to sonic-net

- Makefile.work
This PR fixes the issue reported in PR#12367
https://github.com/sonic-net/sonic-buildimage/pull/12367
The issue is that exit code always being 0 for the builds that are failed.
Fix is added in the Makefile.work to return the error code when the slave build is failed with an error.
> Fixes the exit status of slave build.

- files/build_templates/per_namespace/bgp.service.j2
BGP service has always been starting after interface-config. However, recently we discovered an issue where some BGP sessions are unable to establish due to BGP daemon not able to read the interface IP.
This issue was clearly observed after upgrading to FRR 8.2.2. See more details in #12380.
Delaying starting BGP seems to be a workaround for this issue.
However, caution is that this delay might impact warm reboot timing and other timing sequences.
This workaround is reducing the probability of hitting the issue by close to 100X. However, this workaround is not bulletproof as test shows. It is still preferrable to have a proper FRR fix and revert this change in the future.
Continuously issuing config reload and check BGP session status afterwards.
Signed-off-by: Ying Xie …
> [BGP] starting BGP service after swss

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/dhcp_server.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/dhcp_server.json
- src/sonic-yang-models/yang-models/sonic-dhcp-server.yang
changes:
-- yang model for dhcp_server table.
-- tests.
Signed-off-by: Praveen Chaudhary <pchaudhary@linkedin.com>
Why I did it
yang model for dhcp_server table.
How I did it
-- yang model for dhcp_server table.
-- yang model tests.
-- yang model build time tests.
> [sonic-dhcp-server.yang]: yang model for dhcp_server table.

- device/delta/x86_64-delta_ag5648-r0/plugins/psuutil.py
- device/delta/x86_64-delta_ag9032v1-r0/plugins/psuutil.py
- device/delta/x86_64-delta_ag9032v2a-r0/plugins/psuutil.py
- device/delta/x86_64-delta_ag9064-r0/plugins/psuutil.py
- device/delta/x86_64-delta_agc032-r0/plugins/psuutil.py
- device/delta/x86_64-delta_et-c032if-r0/plugins/psuutil.py
`os` execution functions are not secure against maliciously constructed input.
Use `subprocess` module
> [device/delta] Mitigation for command injection vulnerability

- platform/broadcom/sonic-platform-modules-inventec/common/utils/asic_monitor.py
- platform/broadcom/sonic-platform-modules-inventec/common/utils/led_proc.py
- platform/broadcom/sonic-platform-modules-inventec/common/utils/platform_status.py
- platform/broadcom/sonic-platform-modules-inventec/common/utils/transceiver_monitor.py
- platform/broadcom/sonic-platform-modules-inventec/d6332/sonic_platform/qsfp.py
- platform/broadcom/sonic-platform-modules-inventec/d6332/utils/inventec_d6332_util.py
- platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform/qsfp.py
- platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-inventec/d7054q28b/sonic_platform/sfp.py
Dependency: [https://github.com/sonic-net/sonic-buildimage/pull/12065](https://github.com/sonic-net/sonic-buildimage/pull/12065)
1. `getstatusoutput` is used without a static string and it uses `shell=True`
2. `subprocess()` - when using with `shell=True` is dangerous. Using subprocess function without a static string can lead to command injection.
3. `os` - not secure against maliciously constructed input and dangerous if used to evaluate dynamic content.
1. use `getstatusoutput` without shell=True
2. `subprocess()` - use `shell=False` instead. use an array string. Ref: [https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation](https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation)
3. `os` - use with …
> [inventec] Replace os.system and remove subprocess with shell=True

- src/sonic-frr/patch/0010-zebra-Note-when-the-netlink-DUMP-command-is-interrup.patch
- src/sonic-frr/patch/series
There is an outstanding FRR issue #12380. This seems to be a known issue but without good fix so far. The root cause is around zebra and kernel netlink interaction. The failure was previously not noticed by zebra.
Port the patch that would make the issue obvious.
> [FRR] import FRR patch: zebra: Note when the netlink DUMP command is interrupted

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
To disable DLR_INIT capability as well as get few SAI fixes for chassis QoS work
Updated config files as well SAI debian.
Verified on chassis HWSKU
To disable DLR_INIT capability as well as get few SAI fixes for chassis QoS work
> Update config file to disable DLR_INIT capability 

- rules/thrift_0_14_1.mk
PYTHON_THRIFT_0_14_1 couldn't be built on the pipeline which caused building docker-saiserverv2 to be failed.
Remove PYTHON_THRIFT_0_14_1 from rules/thrift_0_14_1.mk.
Run pipeline internally and docker-saiserverv2 is built successfully.
> Remove PYTHON_THRIFT_0_14_1 to help building saiserverv2

- .azure-pipelines/azure-pipelines-image-template.yml
- azure-pipelines.yml
Now, checkout code step and KVM test job can't be cancelled even though the whole build is cancelled.
That's because by using Azure Pipeline Conditions, we customized the running condition, and we need to react to the Cancel action explicitly by asserting 'succeeded'
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#succeeded
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#ive-got-a-conditional-step-that-runs-even-when-a-job-is-canceled-how-do-i-manage-to-cancel-all-jobs-at-once
Assert 'succeeded' condition explicitly.
Verified by cancelling and rerunning the azure pipeline.
> [Pipeline]Fix the issue that test job and checkout code job can't be cancelled

- device/quanta/x86_64-quanta_ix1b_rglbmc-r0/plugins/psuutil.py
- platform/broadcom/sonic-platform-modules-quanta/ix1b-32x/utils/quanta_ix1b_util.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-32x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-32x/utils/quanta_ix7_util.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-bwde-32x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-bwde-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-bwde-32x/utils/quanta_ix7_bwde_util.py
- platform/broadcom/sonic-platform-modules-quanta/ix8-56x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-quanta/ix8-56x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix8-56x/utils/quanta_ix8_util.py
- platform/broadcom/sonic-platform-modules-quanta/ix8a-bwde-56x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-quanta/ix8a-bwde-56x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix8a-bwde-56x/utils/quanta_ix8a_bwde_util.py
- platform/broadcom/sonic-platform-modules-quanta/ix8c-56x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-quanta/ix8c-56x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix8c-56x/utils/quanta_ix8c_util.py
- platform/broadcom/sonic-platform-modules-quanta/ix9-32x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-quanta/ix9-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix9-32x/utils/quanta_ix9_util.py
Dependency: [https://github.com/sonic-net/sonic-buildimage/pull/12065](https://github.com/sonic-net/sonic-buildimage/pull/12065)
`shell=True` is dangerous because this call will spawn the command using a shell process
`os` - not secure against maliciously constructed input and dangerous if used to evaluate dynamic content.
`os` - use with `subprocess`
Use `shell=False` with shell features
- redirection: [https://stackoverflow.com/questions/4965159/how-to-redirect-output-with-subprocess-in-python/6482200#6482200?newreg=53afb91b3ebd47c5930be627fcdf2930](https://stackoverflow.com/questions/4965159/how-to-redirect-output-with-subprocess-in-python/6482200#6482200?newreg=53afb91b3ebd47c5930be627fcdf2930)
- `|` operator: …
> [device/quanta] Mitigation for security vulnerability

- src/sonic-frr/patch/0011-bgpd-enhanced-capability-is-always-turned-on-for-int.patch
- src/sonic-frr/patch/series
Fixing issue  https://github.com/FRRouting/frr/issues/11108
For interface based peers with peer-groups, "no neighbor capability extended-nexthop" gets added by default. This will result in IPv4 routes not having ipv6 next hops.
Porting the commit https://github.com/FRRouting/frr/commit/8e89adc1edfb4200843e1cbbff1404172bebd9e5 to FRR 8.2.2 which fixes the issue
Load FRR and verify if the "no neighbor capability extended-nexthop" not gets added for interfaces associated with peer-groups
```
show running-config
Building configuration...
Current configuration:
!
frr version 8.2.2
frr defaults traditional
hostname r-lionfish-16
no service integrated-vtysh-config
!
router bgp 65001
no bgp suppress-duplicates
neighbor PEER_V6 peer-group
neighbor PEER_V6 remote-as internal
neighbor PEER_V6 …
```
> [FRR]Adding patch to fix enhanced capability turned on for interface

- dockers/docker-orchagent/tunnel_packet_handler.py
Sometimes the process will try to get the status of non-existent portchannel interfaces
Skip the interface status check if the interface does not exist. In the future, when the interface is created/comes up this check will be triggered again.
> [tunnel_pkt_handler]: Skip nonexistent intfs

- src/lm-sensors/patch/0002-Patch-to-peform-dh_installinit-to-include-sensord.in.patch
https://github.com/sonic-net/sonic-buildimage/issues/4021 describes an issue that is still being observed on master image whereby sensord does not start in pmon due to missing service.
Updated the lm-sensors install patch with a case for systemd
Verified that sensord is up in pmon after boot
> Fix sensord service install

- sonic-slave-bullseye/Dockerfile.j2
When updating the container from Buster to Bullseye in azure pipelines in sonic-utilities repo, the build checker failed due to missing one of the dependencies in libswsscommon
```
+ sudo dpkg -i libswsscommon_1.0.0_amd64.deb
Selecting previously unselected package libswsscommon.
(Reading database ... 196324 files and directories currently installed.)
Preparing to unpack libswsscommon_1.0.0_amd64.deb ...
Unpacking libswsscommon (1.0.0) ...
dpkg: dependency problems prevent configuration of libswsscommon:
libswsscommon depends on libboost-serialization1.71.0; however:
Package libboost-serialization1.71.0 is not installed.
dpkg: error processing package libswsscommon (--install):
dependency problems - leaving unconfigured
Processing triggers for …
```
> [bullseye] Update libswsscommon deps

- .azure-pipelines/run-test-scheduler-template.yml
Fix the issue that test plan can't be canceled by KVM dump stage
Fix the issue that test plan can't be canceled by KVM dump stage
> Fix the issue that test plan can't be canceled by KVM dump stage

- dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
Add dual tor option for dhcp6relay in dual tor mode as per PR https://github.com/sonic-net/sonic-dhcp-relay/pull/10
Option listed in dhcp6relay code:
https://github.com/sonic-net/sonic-dhcp-relay/blob/9c3b73837f768b3220d68ed01030d204c650d476/src/main.cpp#L17
Add "-d" when subtype is 'DualToR"
> Add dhcp6relay dualtor option

- files/Aboot/boot0.j2
A recent change modified the `platform` folder of the image into a tarball `platform.tar.gz`
The `boot0` script was modified for regular boot but not secureboot.
This means that the `platform/firstime` does not get created and `rc.local` therefore skips initial configuration.
Updated the secureboot image extraction logic to properly handle `platform.tar.gz`
Boot the image on a secureboot enabled product and make sure that `rc.local` enters the firstime codepath.
Also verify that `/host/image-XXX/platform` exists.
Fix extraction of platform.tar.gz in secureboot
> [Arista] Fix extraction of platform.tar.gz in secureboot

- platform/mellanox/mlnx-platform-api/sonic_platform/component.py
This fixes the following error
```
admin@sonic:~$ sudo fwutil show status
mount: /mnt/onie-fs: special device /dev/sda2
does not exist.
Error: Command '['mount', '-n', '-r', '-t', 'ext4', '/dev/sda2\n', '/mnt/onie-fs']' returned non-zero exit status 32.. Aborting...
Aborted!
admin@sonic:~$ sudo vi /usr/local/lib/python3.9/dist-packages/sonic_platform/
```
> Remove \n from the end of fs_path in ONIEUpdater

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
co-authorized by: jianquanye@microsoft.com
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
Why I did it
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
How I did it
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
Remove ceos type setting
Use 202205 branch as sonic-mgmt branch
> [202205][TestbedV2]Migrate t0 and t1-lag to TestbedV2 (#12383)

- slave.mk
Add the original docker tag without username to support some of the docker file not changed build broken issue.
The username suffix only required when the native build feature enabled, but if not enabled, the docker file not necessary to change, the build should be succeeded.
It is to support cisco 202205 build.
> Add the original docker tag without username

- sonic-slave-buster/Dockerfile.j2
Sonic-swss-common requires gmock for staged unit tests
Signed-off-by: Don Newton <don@opennetworking.org>
Cherry-pick from https://github.com/sonic-net/sonic-buildimage/pull/8950
Sonic-swss-common requires gmock for staged unit tests
Installed dependency in sonic-buster-build docker file
rebuild the build container
> [sonic-slave]: Add gmock for sonic-swss-common tests (#8950)

- platform/checkout/cisco-8000.ini
Why I did it
Fix for fan sensor critical alarms causing some devices to reboot
How I did it
Update cisco-8000 submodule to v0.120
Which release branch to backport (provide reason below if selected)
Description for the changelog
> Update cisco-8000 submodule to v0.120

- files/image_config/hostname/hostname-config.sh
If config_db.json is missing hostname entry, hostname-config.sh ends up deleting existing entry too and hostname changes to default 'localhost'
If hostname is not available from config_db.json, do not edit /etc/hostname and exit
with missing hostname entry in config_db.json, /etc/hostname entry is not cleared
> Fix to improve hostname handling

- src/lldpd/.gitignore
- src/lldpd/patch/0012-fix-recreate-socket-on-ifindex-change.patch
- src/lldpd/patch/series
Cherry pick https://github.com/sonic-net/sonic-buildimage/pull/9519.
when we remove a port and add it back immediately - lldp is keep failing
warning message keeps appearing:
`[WARN/lldp] unable to send packet on real device for Ethernet4: No such device or address`
on delete link events it will immediately execute delete without using aggregate events mechanism.
Run `autorestart/test_container_autorestart.py` in sonic-mgmt repo
Or manual test steps:
sudo config feature autorestart swss disabled
docker exec swss supervisorctl status
docker exec swss kill -SIGKILL 111(orchagent)
docker inspect -f {{.State.Running}} swss => make sure swss is running
docker exec swss supervisorctl start orchagent
> [202012][LLDPD] fix to port remove and immediately create problem

- build_image.sh
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>
Issue was caused by this  https://github.com/sonic-net/sonic-buildimage/pull/11341
***.bin image structure in 202205:** 
```
vkarri@19d5638dde2d:/sonic$ ls -l  /tmp/tmp.jyuZXWEkTC/installer/
total 1363776
-rw-r--r-- 1 vkarri dip 1396439962 Oct 13 21:44 fs.zip
-rwxr-xr-x 1 vkarri dip      24419 Oct 13 21:44 install.sh
-rw-r--r-- 1 vkarri dip         45 Oct 13 21:44 machine.conf
-rw-r--r-- 1 vkarri dip       1192 Oct 13 21:44 onie-image-arm64.conf
-rw-r--r-- 1 vkarri dip       1192 Oct 13 21:44 onie-image-armhf.conf
-rw-r--r-- 1 vkarri dip       1402 Oct 13 21:44 onie-image.conf
-rw-r--r-- 1 vkarri dip          0 Oct 13 21:44 platform.conf
drwxr-xr-x 2 vkarri dip      12288 Oct 13 21:44 platforms
-rw-r--r-- 1 vkarri dip        541 Oct 13 …
```
> [Build] Fix the installer conf file location according to the updated onie-mk-demo script

- src/sonic-config-engine/minigraph.py
- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
New field `yang_config_validation` needs to be represented in DEVICE_METADATA yang model, configured in minigraph.py
Add field to yang model, set value in minigraph.py
Use GCU to apply patch configuring `yang_config_validation` field
> Add yang_config_validation to DEVICE_METADATA yang model

- platform/barefoot/sonic-platform-modules-netberg/aurora-610/sonic_platform/component.py
- platform/barefoot/sonic-platform-modules-netberg/aurora-610/sonic_platform/qsfp.py
- platform/barefoot/sonic-platform-modules-netberg/aurora-610/sonic_platform/sfp.py
> [netberg] Replace os.system

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
> [202012][TestbedV2]Migrate t0 and t1-lag to TestbedV2 (#12383)

- .azure-pipelines/run-test-scheduler-template.yml
use the pr_test_scripts.yaml from sonic-mgmt's 202205 branch
use the pr_test_scripts.yaml from sonic-mgmt's 202205 branch
> [202205] use the pr_test_scripts.yaml from sonic-mgmt's 202205 branch

- .github/workflows/codeql-analysis.yml
Now codeQL scanning needs approval for the first time a contributor creates a PR.
> [action] Use pull_request_target trigger instead to avoid codeQL check approval

- files/Aboot/boot0.j2
Added a kernel parameter to add quirks to
Check that the settings is properly set on the cmdline when running on a 7060CX-32S
> [202205][Arista] Add emmc quirks to boot0

- src/sonic-config-engine/tests/sample-voq-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/voq-inband-interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/voq-inband-interface.json
- src/sonic-yang-models/yang-models/sonic-voq-inband-interface.yang
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/12306 to 202205 branch 
Add yang model definition for VOQ_INBAND_INTERFACE defined and implemented for VOQ chassis. HLD for voq-inband-interface is included in https://github.com/sonic-net/SONiC/blob/master/doc/voq/voq_hld.md
Added yang model definition, unit tests, sample config and documentation for the table
1. Validated config tree generation using "pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/sonic-voq-inband-interface.yang"
2. Built the below python-wheels to validate unit tests and other changes
target/python-wheels/bullseye/sonic_yang_mgmt-1.0-py3-none-any.whl 
target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl 
target/python-wheels/bullseye/sonic_config_engine-1.0-py3-none-any.wh …
> Add yang model definition for VOQ_INBAND_INTERFACE (#12306)

- files/Aboot/boot0.j2
The cmdline generation has changed between 201911 and 202012 for Arista products.
Doing a fast/warm reboot from 201811 or 201911 to a newer release would lead to cmdline issues.
Cherry-picked the fix #11161 that was applied to 202012 onto 202205
Perform a warm-reboot from 201811/201911 to 202205 to validate.
Fix cmdline generation during warm-reboot from 201811/201911
> [202205][Arista] Fix cmdline generation during warm-reboot from  201811/201911

- src/sonic-yang-models/tests/yang_model_tests/tests/restapi.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/restapi.json
- src/sonic-yang-models/yang-models/sonic-restapi.yang
Fix for multiple names in client cert name
> [Restapi Yang] Fix issue with multiple certs

- src/isc-dhcp/patch/0014-Fix-dhcrelay-agent-option-buffer-pointer-logic.patch
- src/isc-dhcp/patch/series
Signed-off-by: Gang Lv [ganglv@microsoft.com](mailto:ganglv@microsoft.com)
#12033
> [cherry-pick][201911] Fix dhcp option buffer issue

- src/sonic-bgpcfgd/bgpmon/bgpmon.py
`getstatusoutput()` function from `subprocess` module has shell injection issue because it includes `shell=True` in the implementation
Use `getstatusoutput_noshell()` from sonic_py_common library
Tested in DUT
> [sonic-bgpcfgd] Replace getstatusoutput function

- dockers/docker-database/Dockerfile.j2
closes #12343 
Today in SONiC the `notify-keyspace-events` is from DbInterface class when application try do any configdb set.
In Chassis the chassis_db may  not get any configdb set operations, so there is chance this configuration will never be set.
So the chassis_db updates from one line card will not be propogated to other linecards, which are doing a `psubscribe` to get these event.
update the redis.conf to set `notify-keyspace-events AKE`  so that the `notify-keyspace-events` are set when the redis instance is started
Test on chassis
- [ x] 202205
> update notify-keyspace-events in redis.conf

- build_debian.sh
Upgrade systemd to fix timer elapsed issue.
On 201911 release, snmp.timer become elapsed status and snmp.service will not be trigger by snmp.timer:
● snmp.service - SNMP container
Loaded: loaded (/usr/lib/systemd/system/snmp.service; static; vendor preset: enabled)
Active: inactive (dead)
● snmp.timer - Delays snmp container until SONiC has started
Loaded: loaded (/usr/lib/systemd/system/snmp.timer; enabled; vendor preset: enabled)
Active: active (elapsed) since Wed 2022-08-03 18:12:59 UTC; 2 months 17 days ago
This issue caused by systemd bug: https://github.com/systemd/systemd/pull/10778/files
This issue can be reproduce with following steps:
1. reboot system.
2. continusly run following commands till  timer elapsed:
systemctl status snmp.timer
sudo systemctl daemon-reload
Install …
> [201911] [Systemd] Upgrade systemd to fix timer elapsed issue

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
1. For QSFP cables(SFF 8636), if the cable is only compliant with some old revision(e.g. lower than 0x08), in these revisions some of the DOM support status bits are not defined yet, so the DOM support status of the cable is also 'unknown', currently will treat this case as DOM support status 'supported', but for copper cables, it never can support DOM, copper cables should be ruled out in this case.
2. For CMIS cable, there is a bug in determining the DOM support status, the temperature and voltage support statuses are always set to true, this is not correct, they shall be determined in the same way as other DOM capability support statuses.
1. Add a function to judge whether a QSFP cable is a copper cable or not, it judges from the specification compliance bytes and ext specification …
> [202012] [Mellanox] [SFP Platform API] Fix DOM support capability issues on QSFP and CMIS cables

- src/sonic-config-engine/sonic-cfggen
- src/sonic-config-engine/tests/common_utils.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_cfggen_from_yang.py
- src/sonic-config-engine/tests/test_cfggen_pfx_filter.py
- src/sonic-config-engine/tests/test_cfggen_platformJson.py
- src/sonic-config-engine/tests/test_cfggen_t2_chassis_fe.py
- src/sonic-config-engine/tests/test_frr.py
- src/sonic-config-engine/tests/test_j2files.py
- src/sonic-config-engine/tests/test_j2files_t2_chassis_fe.py
- src/sonic-config-engine/tests/test_minigraph_case.py
- src/sonic-config-engine/tests/test_multinpu_cfggen.py
`yaml.load` can create arbitrary Python objects
Replace `os` by `subprocess`, remove `shell=True`
Use `yaml.safe_load()`
Pass UT
> [sonic-config-engine] Replace os.system, replace yaml.load, remove subprocess with shell=True

- src/sonic-yang-mgmt/tests/test_cfghelp.py
> [sonic-yang-mgmt] Replace subprocess using with shell=True

- src/sonic-ctrmgrd/ctrmgr/container_startup.py
- src/sonic-ctrmgrd/ctrmgr/ctrmgr_iptables.py
- src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py
- src/sonic-ctrmgrd/tests/ctrmgr_iptables_test.py
`subprocess.Popen()` and `subprocess.run()` is used with `shell=True`, which is very dangerous for shell injection.
Replace `os` by `subprocess`, remove `shell=True`
Passed UT
Tested in DUT
> [sonic-ctrmgrd] Replace os.system and remove subprocess with shell=True

- src/tacacs/nss/patch/0010-Send-remote-address-in-TACACS-authorization-message.patch
- src/tacacs/nss/patch/series
Send remote address in TACACS+ authorization message.
TACACS+ authorization message not send remote address to server side.
Send remote address in TACACS+ authorization message.
Create new test case to validate remote address been send to server side.
Send remote address in TACACS+ authorization message.
> [TACACS] Send remote address in TACACS+ authorization message.

- src/sonic-build-hooks/hooks/apt-get
Why I did it
Fix apt-get remove/purge version not locked issue when the apt-get options not specified.
How I did it
Add a space character before and after the command line parameters.
> [Build][Bug] Fix apt-get remove version not lock issue

- src/sonic-ctrmgrd/.gitignore
- src/sonic-ctrmgrd/ctrmgr/container
- src/sonic-ctrmgrd/ctrmgr/container_startup.py
- src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py
- src/sonic-ctrmgrd/ctrmgr/kube_commands.py
- src/sonic-ctrmgrd/ctrmgr/remote_ctr.config.json
- src/sonic-ctrmgrd/tests/container_startup_test.py
- src/sonic-ctrmgrd/tests/container_test.py
- src/sonic-ctrmgrd/tests/ctrmgrd_test.py
- src/sonic-ctrmgrd/tests/kube_commands_test.py
Improve feature mode switch process
Refine ctrmgrd service, feature service and start service inside feature container
Connect to k8s cluster as worker and scheduled by k8s 
Fix existing bugs
Refine ctrmgrd service, feature service and start service inside feature container
> Improve feature mode switch process

- src/system-health/health_checker/service_checker.py
- src/system-health/health_checker/sysmonitor.py
- src/system-health/health_checker/utils.py
- src/system-health/tests/test_system_health.py
> [system-health] Remove subprocess with shell=True

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/tests/caclmgrd/cacl_external_client_acl_test.py
- src/sonic-host-services/tests/caclmgrd/test_external_client_acl_vectors.py
Creating this PR to take changes from https://github.com/sonic-net/sonic-host-services/pull/21
> [202205][multi-asic] Fix the issue where if dest port is not specified in ACL rule than caclmgrd gets exception

- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t1.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm
DX010 didn't have LPM enabled. Which could cause device to crash when tcam is full.
Enable LPM.
Check crm after enabling.
> [201811][DX010] enable LPM

- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7050cx3-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7260-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7260-t1.json
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4600c-c64.json
This PR is to add scheduler for Queue 7 for all ports if `tunnel_qos_remap_enable` is `True`.
PR https://github.com/sonic-net/sonic-buildimage/pull/10176 update the default `DSCP_TO_TC_MAP` to map DSCP 48 to TC 7, and TC 7 is mapped to Queue 7. However, the scheduler for Queue  7 is missing.
This PR fixed the issue by adding lossy scheduler for Queue 7.
Thanks @stephenxs  reporting this issue.
This PR fixed the issue by adding lossy scheduler for Queue 7.
Verified by UT.
This PR is to add scheduler for Queue 7 for all ports if `tunnel_qos_remap_enable` is `True`.
> Add lossy scheduler for queue 7

- device/celestica/x86_64-cel_silverstone-x-r0/sonic_platform/thermal.py
- platform/innovium/sonic-platform-modules-cel/debian/platform-modules-silverstone-x.init
- platform/innovium/sonic-platform-modules-cel/debian/platform-modules-silverstone-x.install
- platform/innovium/sonic-platform-modules-cel/debian/platform-modules-silverstone-x.postinst
.gitignore in source code root path ignores files in platform/**/debian/* , therefore Celestica Silverstone-X platform deb dependency files are missing in merge and need to upload these files.
Add Celestica Silverstone-X platform deb dependency files.
verified by SONiC tested platform APIs
verified by SONiC APIs including
"psuutil
psushow(show platform psustatus)
sfputil
sfpshow
tempershow(show platform temperature)
fanshow(show platform fan)
watchdogutil
fwutil(show platform firmware status)
decode-syseeprom -d(show platform syseeprom)
show platform ssdhealth
show platform summary
show interfaces status
"
Add Celestica Silverstone-X platform deb dependency files.
One sensor name needs to be revised.
> [Celestica] Add Celestica Silverstone-X platform deb dependency files

- src/sonic-config-engine/sonic-cfggen
- src/sonic-config-engine/tests/common_utils.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_cfggen_from_yang.py
- src/sonic-config-engine/tests/test_cfggen_pfx_filter.py
- src/sonic-config-engine/tests/test_cfggen_platformJson.py
- src/sonic-config-engine/tests/test_cfggen_t2_chassis_fe.py
- src/sonic-config-engine/tests/test_frr.py
- src/sonic-config-engine/tests/test_j2files.py
- src/sonic-config-engine/tests/test_j2files_t2_chassis_fe.py
- src/sonic-config-engine/tests/test_minigraph_case.py
- src/sonic-config-engine/tests/test_multinpu_cfggen.py
Reverts sonic-net/sonic-buildimage#12533
> Revert "[sonic-config-engine] Replace os.system, replace yaml.load, remove subprocess with shell=True"

- slave.mk
[Build] Fix the docker-sync not found issue
When SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD not enabled, not to remove the docker-sync tag.
> [Build] Fix the docker-sync not found issue

- src/sonic-ctrmgrd/ctrmgr/container_startup.py
- src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py
- src/sonic-ctrmgrd/ctrmgr/kube_commands.py
Still some comments for PR https://github.com/sonic-net/sonic-buildimage/pull/12188
Change the code per comments
> Fix code irregular issues

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Add dualtor test using TestbedV2 in buildimage repo. 
Add dualtor test using TestbedV2 in buildimage repo. 
Add dualtor test using TestbedV2 in buildimage repo.
> [TestbedV2] Add dualtor test using TestbedV2. 

- files/build_templates/dhcp_relay_regex.json
- files/image_config/monit/memory_checker
- files/scripts/supervisor-proc-exit-listener
- src/system-health/health_checker/service_checker.py
Add event_publish code or regex for rsyslog plugin for additional events
> Publish additional events

- files/image_config/logrotate/rsyslog.j2
Fix logrotate firstaction script to reflect correct size. The size was modified to change dynamically based on disk size. However this variable was not updated
https://github.com/sonic-net/sonic-buildimage/pull/9504
Updated the variable based on disk size
Verify in the generated rsyslog file if the variable is correctly generated from jinja template
> [logrotate]Fix logrotate firstaction script to reflect correct size

- device/arista/x86_64-arista_7800r3a_36d2_lc/platform_env.conf
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_env.conf
- files/build_templates/init_cfg.json.j2
- src/sonic-py-common/sonic_py_common/device_info.py
Plan to use the macsec capability flag in the platform - to enable macsec feature which inturn hep hostcfgd to start the macsec dockers 
Add a new flag "macsec_enabled" in the platform_env.conf in the platform directory - which states if that platform  has macsec capability
Add a new API in device_info to get the macsec capability from platform and export to an environment variable MACSEC_SUPPORTED used in hostcfgd.
Verified that the MACSEC_SUPPORTED variable is updated as per the "macsec_enabled" flag set in the platform_env.conf -- and hostcfgd updates the macsec feature state accordingly.
> Use the macsec_enabled flag in platform to enable macsec feature state

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
bgpd.main.conf.j2: bugfix-9739
* Update bgpd.main.conf.j2 to gracefully handle the bgp configuration cases for when 'bgp_asn' is set to 'None', 'Null', or missing.
Signed-off-by: cchoate54@gmail.com
resolves #9739 
Include a conditional statement to avoid configuring bgp in FRR when 'bgp_asn' is missing or set to 'None' or 'Null'
Configure 'bgp_asn' as 'None', 'Null' or have it missing from configurations and verify that /etc/frr/bgpd.conf does not have invalid bgp configurations like 'router bgp None'
Update bgpd.main.conf.j2 to gracefully handle the bgp configuration cases for when 'bgp_asn' is set to 'None', 'Null', or missing for bugfix 9739.
> Bugfix #9739: Support when 'bgp_asn' is set to 'None', 'Null', or missing.

- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t1.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm
Without LPM enabled, the routing table size is very small.
Enabling LPM.
> [202012][DX010] enable LPM

- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7050cx3-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7260-dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7260-t1.json
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4600c-c64.json
This PR is to cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/12596 into `202012` branch after resolving conflicts
This PR is to add scheduler for Queue 7 for all ports if `tunnel_qos_remap_enable` is `True`.
PR https://github.com/sonic-net/sonic-buildimage/pull/10176 update the default `DSCP_TO_TC_MAP` to map DSCP 48 to TC 7, and TC 7 is mapped to Queue 7. However, the scheduler for Queue  7 is missing.
This PR fixed the issue by adding lossy scheduler for Queue 7.
Thanks @stephenxs  reporting this issue.
This PR fixed the issue by adding lossy scheduler for Queue 7.
1. Verified by UT.
2. Verified by wrr test in sonic-mgmt.
This PR is to add scheduler for Queue 7 for all ports if `tunnel_qos_remap_enable` is `True`.
> [202012] Add lossy scheduler for queue 7

- files/build_templates/init_cfg.json.j2
DHCP relay feature needs to be enabled for BmcMgmtToRRouter by default
Update device type list
> [dhcp_relay] Enable DHCP Relay for BmcMgmtToRRouter in init_cfg

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Migrate t0-sonic test jobs to TestbedV2.
Migrate t0-sonic test jobs to TestbedV2.
1. Add two parameters to create testplan.
2. Modify azure-pipelines.yml to run t0-sonic on tbv2.
> [master][TestbedV2] migrate t0-sonic test jobs to TestbedV2.

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Migrate multi-asic test jobs to TestbedV2.
Migrate multi-asic test jobs to TestbedV2.
1. Add one parameter `num_asic` to create testplan.
2. Modify azure-pipelines.yml to run multi-asic on tbv2.
> [master][TestbedV2] Migrate multi-asic test jobs to TestbedV2.

- azure-pipelines.yml
Add dualtor test jobs using TestbedV2 in 202205 branch.
Add dualtor test jobs using TestbedV2 in 202205 branch.
Add dualtor test jobs using TestbedV2 in 202205 branch.
> [202205][TestbedV2] Add dualtor test jobs using TestbedV2.

- dockers/docker-fpm-frr/docker_init.sh
- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
The values for config_db "docker_routing_config_mode" are:
- separated: FRR config generated from ConfigDB, each FRR daemon has its own config file
- unified: FRR config generated from ConfigDB, single FRR config file
- split: FRR config not generated from ConfigDB, each FRR daemon has its own config file
This commit adds:
- split-unified: FRR config not generated from ConfigDB, single FRR config file
In docker_init.sh, when split-unified is used, the FRR configs are not generated
from ConfigDB. What's more, "service integrated-vtysh-config" is configured in vtysh.conf.
FRR config not overwritten when FRR container starts.
- [] 201811
- [] 201911
- [] 202006
- [] 202012
- [] 202106
- [] 202111
- [] 202205
Add a "split-unified" option to "docker_routing_config_mode" …
> [docker-fpm-frr]: Add unified-split mode to routing config

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal.py
Add new thermal sensors for SN5600
Add new thermal sensors for SN5600: PCH and SODIMM
Manual test
> [Mellanox] Add new thermal sensors for SN5600

- src/systemd-sonic-generator/systemd-sonic-generator.c
Pointer variable platform not initialized before use in get_num_of_asic of src/systemd-sonic-generator/systemd-sonic-generator.c. Then wild pointer will introduce undetermined exception when use in snprintf at line 545 .
Other pointers in this function like token will be assigned the value before use, and will not have such issue.
Initialized pointer platform to NULL when defined and before use.
> Initialize pointer variable platform before use in get_num_of_asic

- dockers/docker-platform-monitor/Dockerfile.j2
This is part of a corresponding change to the pcie daemon that enables it to verify PCI peripherals on a platform against a preconfigured YAML file, and enables the pcied daemon to call the system commands needed for PCI peripheral verification
Adding aforementioned libraries to the Dockerfile.j2 file
run 'which setpci' from the pmon docker - would show the path of the binary
Modified pmon's Dockerfile.j2 to include pciutils and libpci libraries.
> Added libpci and pciutils to the pmon docker

- dockers/docker-database/database_config.json.j2
- platform/vs/docker-sonic-vs/database_config.json
- src/sonic-config-engine/tests/mock_tables/asic0/database_config.json
- src/sonic-config-engine/tests/mock_tables/asic1/database_config.json
- src/sonic-config-engine/tests/mock_tables/asic2/database_config.json
- src/sonic-config-engine/tests/mock_tables/asic3/database_config.json
- src/sonic-config-engine/tests/mock_tables/database_config.json
- src/sonic-eventd/tests/redis_multi_db_ut_config/database_config.json
- src/sonic-eventd/tests/redis_multi_db_ut_config/database_config0.json
- src/sonic-eventd/tests/redis_multi_db_ut_config/database_config1.json
- src/sonic-py-common/sonic_py_common/sonic_db_dump_load.py
This PR is part of the following HLD:
Persistent loglevel HLD: https://github.com/sonic-net/SONiC/pull/1041
After the Logger tables moved from the LOGLEVEL_DB to the CONFIG_DB and the jinja2_cache was deleted the LOGLEVEL_DB is not in use.
Removed the LOGLEVEL_DB from the SONiC code
All tests were passed
> Remove LOGLEVEL DB since is no longer used

- device/arista/x86_64-arista_7280cr3_32d4/pcie.yaml
- device/arista/x86_64-arista_7280cr3_32d4/platform_asic
- device/arista/x86_64-arista_7280cr3_32p4/pcie.yaml
- device/arista/x86_64-arista_7280cr3mk_32d4/pcie.yaml
- device/arista/x86_64-arista_7280cr3mk_32d4/platform_asic
- device/arista/x86_64-arista_7280cr3mk_32p4/pcie.yaml
- device/arista/x86_64-arista_7280cr3mk_32p4/platform_asic
Even though the Pcie api is implemented, pcie-check still fails if a `pcie.yaml` configuration isn't provided.
Added the `pcie.yaml` configuration to the `7280CR3-32D4` platform and variants.
pcie-check.sh now passes at startup
Add pcie.yaml to 7280CR3-32D4 variants
> [Arista] Add pcie.yaml to 7280CR3-32D4 variants

- build_debian.sh
Master PR: https://github.com/sonic-net/sonic-buildimage/pull/12592
nameserver and domain entries from build system fsroot gets into sonic image.
Clear /etc/resolv.conf before building image
Built image with it and verified with install that /etc/resolv.conf is empty
> [202012] Clear /etc/resolv.conf before building image

- Makefile.cache
- Makefile.work
After #12557 sources.lists are generated.
So we need to recalculate SLAVE_BASE_TAG if mirrors were changed.
Also we need to rebuild DPKG cache in this case.
1. Use generated sources.list for SLAVE_BASE_TAG
2. Add MIRROR_URLS and MIRROR_SECURITY_URLS to SONIC_COMMON_FLAGS_LIST
Signed-off-by: Konstantin Vasin k.vasin@yadro.com
> [Build] Update SLAVE_BASE_TAG and DPKG cache if Debian mirrors were changed

- device/arista/x86_64-arista_7260cx3_64/pcie.yaml
On some products from this line one of the management NIC might be unpopulated.
On such products this leads to errors from `pcied` and `pcie-check.sh`
Remove this PCIe device from `pcie.yaml`
Run `pcieutil check` on the 2 hardware variants and validate that it passes.
Restart `pcied` and make sure that there is no more error logs in the syslog.
Remove pcie device monitoring for 7260CX3-64
> [Arista] Remove pcie device monitoring for 7260CX3-64

- src/sonic-bgpcfgd/bgpcfgd/main.py
- src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
- src/sonic-bgpcfgd/bgpcfgd/static_rt_timer.py
This is to resubmit https://github.com/sonic-net/sonic-buildimage/pull/11743, original PR always failed with pipeline, suspect old code base issue.
Modify BgpCfgD to support static route expiry
Add a new class StaticRouteTimer to monitor old and unrefreshed static routes in APP DB and remove them
New key/value in appl_db:
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:5.5.5.0/24' nexthop 10.0.0.27 expiry 'false'    
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:5.5.5.0/24' nexthop 10.0.0.27 expiry 'true' refresh 'true'
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:2001::1/64' nexthop 2002::1 expiry 'false' 
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:2001::1/64' nexthop 2002::1 expiry 'true' refresh 'true'
expiry == 'false' means non-persistent static route, but will never …
> Add support for static route expiry

- build_debian.sh
Revert SSHD config change.
Some test case and code may impact by SSHD config change.
Revert following change in build_debian.sh script:
ClientAliveInterval change back to 900.
MaxAuthTries change back to default value.
Banner change to disabled.
Revert SSHD config change.
> Revert SSHD config change.

- device/arista/x86_64-arista_7260cx3_64/platform.json
- device/arista/x86_64-arista_7260cx3_64/platform_components.json
Some sonic-mgmt `platform_tests/api` were failing on the 7260CX3-64
Added the missing metadata in `platform.json` and `platform_components.json`
This is purely test data and does not impact our API implementation.
Run `platform_tests/api` and expect 100% passrate.
Update platform.json for 7260CX3-64
> [Arista] Update platform.json for 7260CX3-64

- rules/phy-credo.mk
A recent migration of `SonicV2Connector` from `swsssdk` to `swsscommon.swsscommon` broke `phy-credo`.
Change the import path while keeping a fallback on the previous one for 202205
`phy-credo.service` no longer fails due to an import error
Fix import error in phy-credo package
> [Arista] Fix import error in phy-credo package

- src/sonic-bgpcfgd/bgpcfgd/static_rt_timer.py
when key STATIC_ROUTE_EXPIRY_TIME is not exist in APPL_DB, self.db.get(self.db.APPL_DB, "STATIC_ROUTE_EXPIRY_TIME", "time") will rise runtime error, and python thread silent exist.
Add key check before access it's value
Try it on DUT
> add fix for STATIC_ROUTE_EXPIRY_TIME key not exist

- build_debian.sh
- dockers/docker-base-bullseye/Dockerfile.j2
- dockers/docker-base-bullseye/apt-multiple-retries
- files/apt/apt.conf.d/apt-multiple-retries
- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-bullseye/apt-multiple-retries
There were some changes in apt source code in version 2.1.9.
As a result apt used in bullseye (2.2.4) is intolerant to network issues.
This was fixed in https://salsa.debian.org/apt-team/apt/-/commit/10631550f1f9788bdfd64d2434237a1448ab0626 Already fixed version is used in bookworm (2.5.4)
And not yet affected version is used in buster (1.8.2.3)
Set Acquire::Retries to 3 for sonic-slave-bullseye, docker-base-bullseye and final Debian image.
Ref: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1876035
Signed-off-by: Konstantin Vasin <k.vasin@yadro.com>
> [Build] set apt Acquire::Retries to 3 for bullseye

- src/system-health/health_checker/hardware_checker.py
- src/system-health/tests/test_system_health.py
Support PSU power threshold checking in the system health daemon.
The system health daemon will check whether PSU's `power_overload` is `True` and treat it as not health if it is.
Unit test and regression test.
> [system health daemon] Support PSU power threshold checking

- device/arista/x86_64-arista_7060_cx32s/platform.json
- device/arista/x86_64-arista_7060_cx32s/platform_components.json
Some sonic-mgmt `platform_tests/api` were failing on the 7060CX-32S
Added the missing metadata in `platform.json` and `platform_components.json`
This is purely test data and does not impact our API implementation.
Run `platform_tests/api` and expect 100% passrate.
Update platform.json for 7060CX-32S
> [Arista] Update platform.json for 7060CX-32S

- device/arista/x86_64-arista_7050cx3_32s/platform.json
The platform_tests.api.test_thermal::test_set_low_threshold testcase fails because by default the thermals on this platform are not controllable via the API.
Mark thermals as not controllable in platform.json
Verified that testcase is skipped instead of failing
> [202205][Arista] Mark thermals as not controllable for 7050CX3-32S platform

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/tests/test_psu.py
Support PSU power threshold checking on Mellanox platform: support platform APIs
- get_psu_power_warning_suppress_threshold
- get_psu_power_critical_threshold
> [Mellanox] Support PSU power threshold checking

- src/thrift_0_14_1/Makefile
PYTHON_THRIFT_0_14_1 couldn't be built on the pipeline which caused some building target failed, likedocker-saiserverv2.
In order to make the thrift 0.14.1 can be used by other build target and prepare for latter upgrade from thrift 0.11 to 0.14. Add this target.
Without this target the error is
```
tar: target/debs/buster/python-thrift_0.14.1_amd64.deb: Cannot stat: No such file or directory
```
This fix can also resolve the previous issue in PR https://github.com/sonic-net/sonic-buildimage/pull/12169
Add the build target for python-thrift_0.14.1_amd64.deb in thrift make file.
Local docker build
> Add build target to build thrift 014 for python2

- device/common/profiles/th2/7260/RDMA-CENTRIC/qos.json.j2
This PR is to add the missing flags in `device/common/profiles/th2/7260/RDMA-CENTRIC/qos.json.j2`.
The flags are missing by this PR https://github.com/sonic-net/sonic-buildimage/pull/11569
Add the missing flags
For T1, `different_dscp_to_tc_map = true` is added.
For dualtor, `different_dscp_to_tc_map = true` and `different_tc_to_queue_map = true` are added.
> Add missing flags in qos template file

- slave.mk
Cherry-pick PR: https://github.com/sonic-net/sonic-buildimage/pull/11846
The current error handling code for when a deb package fails to be
installed currently has a chain of commands linked together by && and
ends with `exit 1`. The assumption is that the commands would succeed,
and the last `exit 1` would end it with a non-zero return code, thus
fully failing the target and causing the build to stop because of bash's
-e flag.
However, if one of the commands prior to `exit 1` returns a non-zero
return code, then bash won't actually treat it as a terminating error.
From bash's man page:
```
-e      Exit immediately if a pipeline (which may consist of a single simple
command), a list, or a compound command (see SHELL GRAMMAR above), …
```
> Fix error handling when failing to install a deb package (#11846)

- files/image_config/monit/memory_checker
Fix error when calling events API, required value is string, passing float
Change type of value from float to string
Manual test:
`Nov 22 08:24:56.181145 str-s6000-on-4 INFO memory_checker: [telemetry]: Memory usage (20573061.12 Bytes) is larger than the threshold (200 Bytes)!`
`Nov 22 08:26:02.651165 str-s6000-on-4 INFO memory_checker: [telemetry]: Memory usage (20573061.12 Bytes) is larger than the threshold (200 Bytes)!`
`Nov 22 08:26:02.851088 str-s6000-on-4 NOTICE memory_checker: :- publish: EVENT_PUBLISHED: {"sonic-events-host:mem-threshold-exceeded":{"ctr_name":"telemetry","mem_usage":"20573061.12","threshold":"200","timestamp":"2022-11-22T08:26:02.850599Z"}}`
> Change value type of params in memory_checker

- Makefile.work
When build the sonic-slave-bash target, it cannot go to the shell failed in the step to build sonic-build-hooks, the error logs as below. It may have impact on some of the users, it may be relative to different version of the make.
```
$ QUIET=n BLDENV=bullseye make NOJESSIE=1 NOSTRETCH=1 sonic-slave-bash
+++ Making sonic-slave-bash +++
BLDENV=buster make -f Makefile.work sonic-slave-bash
make[1]: Entering directory `/builds2/stephens/wip/update-submodule/sonic-buildimage'
echo -n ""
pushd src/sonic-build-hooks; TRUSTED_GPG_URLS=https://packages.trafficmanager.net/debian/public_key.gpg,https://packages.microsoft.com/keys/microsoft.asc make all; popd
/builds2/stephens/wip/update-submodule/sonic-buildimage/src/sonic-build-hooks /builds2/stephens/wip/update-submodule/sonic-buildimage …
```
> [Build] Fix the build exit unexpected in false condition in Makefile issue

- src/sonic-build-hooks/Makefile
Ubuntu 22.04 leverages Zstandard compression to dpkg by default.
Debian doesn't support it yet https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664
Fix #12822
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
> Force xz as compression type when building sonic-build-hooks debs

- src/sonic-bgpcfgd/bgpcfgd/static_rt_timer.py
1. swss-common behavior change between 202012 and master
https://github.com/sonic-net/sonic-swss-common/commit/e95a4666ad90f13c3675efb9238f273df5232e91
2. This behavior change will cause different return value:
master:  key not exist, swss-common api will return None.
202012:  key not exist, swss-common api will return empty string.
3. Based on 1 and 2, modify the original static route expiry code to make the code safe for different kinds of key/value pair in both master and 202012.
Add protection code when swss-common api return None/"". 
apply in bgpcfgd, verify different key/value pair.
> better solution for STATIC_ROUTE_EXPIRY_TIME check

- rules/thrift_0_14_1.mk
- src/thrift_0_14_1/Makefile
This PR is a cherry-pick of #12790 and a revert of #12169 to add build target to help build thrift 0.14.1 for python2.
PYTHON_THRIFT_0_14_1 couldn't be built on the pipeline which caused some building targets to fail, like docker-saiserverv2.
In order to make the thrift 0.14.1 can be used by other build targets and prepare for the latter upgrade from thrift 0.11 to 0.14.1. Add this target.
Cherry-pick #12790 from master to 202205 and re-add the target PYTHON_THRIFT_0_14_1.
Local docker build.
> [Cherry-pick] Add build target to build thrift 0.14.1 for python2

- src/systemd-sonic-generator/systemd-sonic-generator.c
The variable is not initialized in src/systemd-sonic-generator/systemd-sonic-generator.c. I fixed this one.
Assure pointer is initialized to NULL when defined and before use.
> Fix variable in systemd not initialized issue

- platform/broadcom/sonic-platform-modules-ruijie/b6510-48vs8cq/sonic_pcie/pcie_common.py
- platform/broadcom/sonic-platform-modules-ruijie/b6510-48vs8cq/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-ruijie/b6510-48vs8cq/sonic_platform/common.py
- platform/broadcom/sonic-platform-modules-ruijie/b6510-48vs8cq/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-ruijie/common/lib/plat_hal/osutil.py
- platform/broadcom/sonic-platform-modules-ruijie/common/script/device_i2c.py
- platform/broadcom/sonic-platform-modules-ruijie/common/script/fancontrol.py
- platform/broadcom/sonic-platform-modules-ruijie/common/script/ruijieutil.py
Dependency: [https://github.com/sonic-net/sonic-buildimage/pull/12065](https://github.com/sonic-net/sonic-buildimage/pull/12065)
1. `getstatusoutput` is used without a static string and it uses `shell=True`
2. `subprocess()` - when using with `shell=True` is dangerous. Using subprocess function without a static string can lead to command injection.
3. `os` - not secure against maliciously constructed input and dangerous if used to evaluate dynamic content.
1. use `getstatusoutput` without shell=True
2. `subprocess()` - use `shell=False` instead. use an array string. Ref: [https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation](https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation)
3. `os` - use with `subprocess`
> [ruijie] Replace os.system and remove subprocess with shell=True

- device/arista/x86_64-arista_720dt_48s/td3x2-a720dt-48s-flex.config.bcm
Added to allow test_crm_route to pass; the test tries to add a /126 ipv6 route and this change is required in order for the count of available routes to be updated correctly.
> [Arista] Enable ipv6 128b lpm on 720DT-48S

- sonic-slave-buster/Dockerfile.j2
Fix the python3  dbus-python installation issue in arm.
See https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/180980/logs/96
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.15 or higher is required.  You are running version 3.13.4
```
Install the cmake package from buster-backports
Succeeded:
```
docker run --rm -it 8380970b72ea bash
sudo apt-get install -y -t buster-backports cmake
sudo pip3 install dbus-python
```
Where the docker image 8380970b72ea is the buster slave image in armhf.
Failed:
```
docker run --rm -it 8380970b72ea bash
sudo pip3 install dbus-python
```
> [Build] Fix dbus-python installation issue in armhf

- src/sonic-host-services/scripts/hostcfgd
- src/sonic-host-services/tests/common/mock_configdb.py
- src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- src/sonic-host-services/tests/hostcfgd/test_vectors.py
Cherry-pick [sonic-host-services/pull/19](https://github.com/sonic-net/sonic-host-services/pull/19) into 202205
> [202205] Cherry-pick sonic-host-services/pull/19 into 202205

- src/sonic-bgpcfgd/bgpcfgd/main.py
- src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
- src/sonic-bgpcfgd/bgpcfgd/static_rt_timer.py
static route expiry feature support in 202012.  This is double commit job from master to 202012.
Modify BgpCfgD to support static route expiry
Add a new class StaticRouteTimer to monitor old and unrefreshed static routes in APP DB and remove them
New key/value in appl_db:
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:5.5.5.0/24' nexthop 10.0.0.27 expiry 'false'    
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:5.5.5.0/24' nexthop 10.0.0.27 expiry 'true' refresh 'true'
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:2001::1/64' nexthop 2002::1 expiry 'false' 
sonic-db-cli APPL_DB hmset 'STATIC_ROUTE:default:2001::1/64' nexthop 2002::1 expiry 'true' refresh 'true'
expiry == 'false' means non-persistent static route, but will never expire in APPL_DB
refresh == 'true' means …
> static route expiry feature support in 202012

- slave.mk
Cherry pick of #11846 to 202205 branch.
The current error handling code for when a deb package fails to be
installed currently has a chain of commands linked together by && and
ends with `exit 1`. The assumption is that the commands would succeed,
and the last `exit 1` would end it with a non-zero return code, thus
fully failing the target and causing the build to stop because of bash's
-e flag.
However, if one of the commands prior to `exit 1` returns a non-zero
return code, then bash won't actually treat it as a terminating error.
From bash's man page:
```
-e      Exit immediately if a pipeline (which may consist of a single simple
command), a list, or a compound command (see SHELL GRAMMAR above),
exits with a non-zero status.  The …
```
> [202205] Fix error handling when failing to install a deb package (#11846)

- files/scripts/syncd.sh
Signed-off-by: Michael Li <michael.li@broadcom.com>
There is an issue on the Arista PikeZ platform (using T3.X2: BCM56274) while running SONiC. If the 'syncd' container in SONiC is restarted, the expected behaviour is that syncd will automatically restart/recover; however it does not and always fails at create_switch due to BCM SDK kmod DMA operation cancellation getting stuck.
`
Sep 16 22:19:44.855125 pkz208 ERR syncd#syncd: [none] SAI_API_SWITCH:platform_process_command:428 Platform command "init soc" failed, rc = -1.
Sep 16 22:19:44.855206 pkz208 INFO syncd#supervisord: syncd CMIC_CMC0_PKTDMA_CH4_DESC_COUNT_REQ:0x33#015
Sep 16 22:19:44.855264 pkz208 CRIT syncd#syncd: [none] SAI_API_SWITCH:platformInit:1909 initialization command "init soc" failed, rc = -1 (Internal error).
Sep 16 …
> Reload BCM SDK kmods on syncd start to handle syncd restart issues

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Previously, we hard code the min and max numbers of instance in a plan. In this pr, we support passing the instance numbers of a testplan.
Previously, we hard code the min and max numbers of instance in a plan. In this pr, we support passing the instance numbers of a testplan.
Use a variable to set the instance number.
> [TestbedV2][master] Support passing the instance numbers of a testplan. 

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Previously, we hard code the min and max numbers of instance in a plan. In this pr, we support passing the instance numbers of a testplan.
Previously, we hard code the min and max numbers of instance in a plan. In this pr, we support passing the instance numbers of a testplan.
Use a variable to set the instance number.
> [TestbedV2][202012] Support passing the instance numbers of a testplan.

- slave.mk
**FIXES**: https://github.com/sonic-net/sonic-buildimage/issues/11521
When build SONiC dockers, SONiC build system tags all of them with ```latest``` tag. This is Ok for all built-in dockers because we will also tag them with image version tag in ```sonic_debian_extension.j2``` script. On the other hand, some of these dockers are SONiC packages and they are installed by ```sonic-package-manager``` which creates a only one tag whcih is recorded in the corresponding .gz file. This leads to having these dockers tagged only with ```latest``` tag. This change saves the tag as an image version string in .gz file, so that these dockers have version identification in their tag.
I modified slave.mk to save the version tag instead of latest tag.
I …
> [dockers] save extension dockers with an image tag

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Previously, we hard code the min and max numbers of instance in a plan. In this pr, we support passing the instance numbers of a testplan.
Previously, we hard code the min and max numbers of instance in a plan. In this pr, we support passing the instance numbers of a testplan.
Use a variable to set the instance number.
> [TestbedV2][202205] Support passing the instance numbers of a testplan.

- src/system-health/health_checker/config.py
- src/system-health/health_checker/manager.py
- src/system-health/tests/test_system_health.py
HLD: https://github.com/sonic-net/SONiC/pull/1106
Currently, system status LED is always red during booting stage. User cannot tell if it is a real issue or system is under initialization. This HLD change introduces a booting stage for the system health daemon and allow user to configure the system status led color for booting state.
Led color is determined by system status and uptime.
Manual test
> [system-health] Led color shall be controlled by configuration when system is booting

- .azure-pipelines/azure-pipelines-build.yml
- .azure-pipelines/build-template.yml
Publish docker saiserverv2 in the build pipeline.
Add docker saiserverv2 target in the build template.
Run test in #12837  and it has been built out successfully.
> [202211][SAI-PTF] Publish docker saiserverv2 in 202211 branch

- .azure-pipelines/azure-pipelines-build.yml
- .azure-pipelines/build-template.yml
Publish docker saiserverv2 in the build pipeline.
Cherry-pick #12842 from master to 202205 branch.
Run test in #12843 and it has been built out successfully.
> [202205][Cherry-Pick][SAI-PTF] Publish docker saiserverv2 in 202205 branch

- device/nokia/armhf-nokia_ixs7215_52x-r0/plugins/eeprom.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/chassis.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/component.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/psu.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp_event.py
Dependency: [https://github.com/sonic-net/sonic-buildimage/pull/12065](https://github.com/sonic-net/sonic-buildimage/pull/12065)
`subprocess.Popen()` and `subprocess.run()` is used with `shell=True`, which is very dangerous for shell injection.
`getstatusoutput` is dangerous because it contains `shell=True` in the implementation
Replace `os` by `subprocess`, use with `shell=False`
Remove unused functions
> [nokia] Replace os.system and remove subprocess with shell=True

- Makefile
The only platforms that currently need the stretch slave container are innovium and nephos, and both are not building with the current code due to other issues. All other platforms only need buster and bullseye slave containers.
> Disable stretch slave container

- Makefile.work
- files/build_templates/build_docker_cache.j2
- scripts/collect_build_version_files.sh
- scripts/collect_docker_version_files.sh
- scripts/collect_host_image_version_files.sh
- scripts/prepare_docker_buildinfo.sh
- slave.mk
- sonic-slave-buster/Dockerfile.j2
- src/sonic-build-hooks/scripts/buildinfo_base.sh
- src/sonic-build-hooks/scripts/post_run_buildinfo
- src/sonic-build-hooks/scripts/pre_run_buildinfo
During docker build, host files can be passed to the docker build through
docker context files. But there is no straightforward way to transfer
the files from docker build to host.
This feature provides a tricky way to pass the cache contents from docker
build to host. It tar's the cached content and encodes them as base64 format
and passes it through a log file with a special tag as 'VCSTART and VCENT'.
Slave.mk in the host, it extracts the cache contents from the log and stores them
in the cache folder. Cache contents are encoded as base64 format for
easy passing.
> 02.Version cache - docker cache build framework

- platform/marvell-armhf/platform.conf
When using sonic-installer to set-default and cleanup image or install a third image as the following steps, issues ocur. 
1) (onie-nos-install ) Install first image A
2) (sonic-installer) Install Image B and not reboot it
3) (sonic-installer) set default to back to Image A
4) sudo sonic-installer cleanup
At this time, executing sonic-installer list will throw exception
5) If install an image C, the current running image A been removed unexpected
When install a image without rebooting, uboot setting is not able to identify which (sonic_version_ sonic_version_2) should be use for the next image installed or cleanup after the set default.  Modified the platform.conf to use the current running image from /proc/cmdline to identify eother sonic_version_ or sonic_version_2 should be used for …
> [armhf][sonic-installer] Fix an issue of the sonic-installer install after the cleanup

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Previously, we set timeout in each step such as Lock testbed, Prepare testbed, Run test and KVM dump. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled.
Previously, we set timeout in each step such as Lock testbed, Prepare testbed, Run test and KVM dump. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled.
Remove the …
> [TestbedV2][master] Remove timeout in each step.

- platform/centec-arm64/platform.conf
- platform/centec-arm64/sonic_fit.its
support multi-platform device tree for default dtb may not suitable on all vender hardware designs.
use onie_platform variable to load device tree blob
build centec arm64 image and verify it on centec e530-24x2c board
> [centec][arm64] support multi-platform device tree

- platform/broadcom/sai.mk
In order to make the sai update easier, change the URL pattern to a more unified format, which can be update automated latter.
use the public URL instead of the package url
Pipeline test
> [submodule]Update SAI SDK URL from package storage to public

- scripts/prepare_docker_buildinfo.sh
arm64 bullseye docker image source is set to jessie for VERSION_CODENAME is miss.
```
shil@localhost:~/sonic-buildimage$ docker run -it multiarch/debian-debootstrap:arm64-bullseye bash
root@b2e2fea86e2d:/# cat /etc/os-release | grep VERSION_CODENAME | cut -d= -f2
root@b2e2fea86e2d:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
if DISTRO is NULL, find it in /etc/apt/sources.list
```
root@b2e2fea86e2d:/# cat /etc/apt/sources.list | grep deb.debian.org | awk '{print $3}'
bullseye
root@b2e2fea86e2d:/# cat /etc/apt/sources.list
deb http://deb.debian.org/debian bullseye main
root@b2e2fea86e2d:/#
```
compile arm64 …
> [build][arm64] fix debian source for arm64 bullseye docker image

- platform/centec-arm64/tsingma-bsp/src/ctc_wdt/ctc_wdt.c
fix centec arm64 tsingma bsp compile error caused by linux kernel api change
fix centec arm64 tsingma bsp compile error caused by linux kernel api change
compile centec arm64 image and verify on centec arm64 E530 series device
> [centec][arm64] fix tsingma bsp compile error

- slave.mk
pre-compiled bazel is not work in arm64 docker container
```
shil@2f910d8d37b2:/sonic/src/sonic-p4rt/sonic-pins$ uname -a
Linux 2f910d8d37b2 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 aarch64 GNU/Linux
shil@2f910d8d37b2:/sonic/src/sonic-p4rt/sonic-pins$ bazel
Opening zip "/proc/self/exe": lseek(): Bad file descriptor
FATAL: Failed to open '/proc/self/exe' as a zip file: (error: 9): Bad file descriptor
shil@2f910d8d37b2:/sonic/src/sonic-p4rt/sonic-pins$
```
disable p4rt compile on arm64
compile centec arm64 sonic image
> [build][arm64] disable p4rt compile on arm64 for bazel not work

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Previously, we set timeout in each step such as Lock testbed, Prepare testbed, Run test and KVM dump. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled.
Previously, we set timeout in each step such as Lock testbed, Prepare testbed, Run test and KVM dump. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled.
Remove the …
> [TestbedV2][202012]Remove timeout in each step.

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Previously, we set timeout in each step such as Lock testbed, Prepare testbed, Run test and KVM dump. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled.
Previously, we set timeout in each step such as Lock testbed, Prepare testbed, Run test and KVM dump. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled.
Remove the …
> [TestbedV2][202205] Remove timeout in each step.

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
Fix Seastone syseeprom tlv header read incorrect issue
Set mux idle_state to MUX_IDLE_DISCONNECT.
``` shell
```
or
``` python
python3
F = open("/sys/class/i2c-adapter/i2c-12/12-0050/eeprom", "rb")
F.seek(0)
o = F.read(11)
o
F.seek(0)
F.close()
```
> [Platform/Seastone]: fix syseeprom tlv read issue

- src/thrift_0_14_1/Makefile
This PR is a cherry-pick of #12790 to add a build target to help build thrift 0.14.1 for python2 on 202211 branch.
Add the build target for python-thrift_0.14.1_amd64.deb in thrift make file.
Local docker build.
> [202211][Cherry-Pick]Add build target to build thrift 014 for python2

- files/scripts/syncd.sh
Signed-off-by: Michael Li <michael.li@broadcom.com>
Limiting #12804 changes to PikeZ platform only (Arista-720DT-48S).   Note that this is a short term workaround for this platform until SDK investigation on SDK init failure on docker syncd restart due to DMA issues is resolved.
Retrieve platform name from /host/machine.conf and only reload SDK kmods on Arista-720DT-48S platform.
Steps to reproduce:
1. Run 'docker stop syncd'
2. Wait ~1 minute.
3. Run 'docker ps' to see that syncd is missing.
4. Check logs to see messages below
`pkz403 INFO syncd#supervisord: syncd 0:soc_cmicx_dma_abort: Failed to abort packet DMA in CMC 0 channel 0, check with the design team#015`
> Limit reload BCM SDK kmods on syncd start to PikeZ platform

- slave.mk
PR #12829 modified the docker tagging scheme such that optional docker containers would be tagged with the SONiC image version. However, the docker-image-load macro wasn't updated for these changes. Update it here.
> Fix docker load image tag not being the expected tag

- onie-image-arm64.conf
- onie-image-armhf.conf
- onie-image.conf
3GB disk size is not enough for broadcom raw image.
Increase from 3GB to 4GB
Creating SONiC raw partition : target/sonic-broadcom.raw of size 3072 MB
+ fallocate -l 3072M target/sonic-broadcom.raw
+ sudo mount proc /proc -t proc
+ sudo chmod a+x target/sonic-broadcom.bin.tmp
+ sudo ./target/sonic-broadcom.bin.tmp
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in BUILD
ONIE Installer: platform: x86_64-broadcom-r0
onie_platform: 
mke2fs 1.46.2 (28-Feb-2021)
Discarding device blocks:   4096/786432             done                            
Creating filesystem with 786432 4k blocks and 196608 inodes
Filesystem UUID: 7a5d7ab4-efb6-4a59-8c9c-f8b9b069e49a
Superblock backups stored on blocks: 
32768, 98304, 163840, 229376, 294912 …
> [build]: increase raw image disk size to 4GB

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
SIGTERM takes more than 10 seconds to be processed, so psud is stopped by SIGKILL, this causes unexpected behavior since data base is not cleared
Decorate get_presence api to cancel it on SIGTERM signal in order to avoid long processing.
test_pmon_psud_stop_and_start_status
test_pmon_psud_term_and_start_status
> [BFN]: Fix SIGTERM processing

- platform/broadcom/saibcm-modules/sdklt/linux/knetcb/Kbuild
- platform/broadcom/saibcm-modules/sdklt/linux/knetcb/ngknetcb_main.c
- platform/broadcom/saibcm-modules/sdklt/linux/knetcb/psample-cb.h
- platform/broadcom/saibcm-modules/systems/linux/kernel/modules/knet-cb/knet-cb.c
Fixed sflow feature code breakage in BRCM ESW platform.
*Replaced BRCM SDK's psample support flag(PSAMPLE_SUPPORT) with linux kernel psample module support config flag(CONFIG_PSAMPLE) in saibcm-modules. 
*Replaced BUILD_PSAMPLE conditioanl check with CONFIG_PSAMPLE to build psample callback library(psample-cb.o), only if psample config is enabled in linux kernel. 
*Cleaned up PSAMPLE_SUPPORT related commented code.
Signed-off-by: haris@celestica.com
SFLOW configuration(config sflow enable) causes swss docker to exit in Broadcom Td3-X2 family chipset platform. Reason is as part of the sflow configuration, Broadcom tries to open the file /proc/bcm/knet_cb/psample/rate and it got failed since the file doesn't exists. psample-cb.o object file is responsible for loading …
> [sflow]: Unblocked psample_*() function calls  related to BRCM specific procfs for sflow feature's working in ESW platforms

- dockers/docker-orchagent/docker-init.j2
- files/scripts/asic_status.py
- src/sonic-py-common/sonic_py_common/multi_asic.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/12575 and https://github.com/sonic-net/sonic-buildimage/issues/12575
In the PR https://github.com/sonic-net/sonic-platform-daemons/pull/311 `chassisd` updates to `CHASSIS_FABRIC_ASIC_INFO` with the fabric asic info.
Updating the `asic_status.py` to read from the correct table.
test on chassis
> [chassis] update the asic_status.py to read from CHASSIS_FABRIC_ASIC_INFO_TABLE

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.conf.j2/all.json
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/all.json
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/defaults.json
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.json
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_frontend_asic.conf
- src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-bgpd.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_frontend_asic.conf
- src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-bgpd.conf
What I did:
Cherry-pick of PR https://github.com/sonic-net/sonic-buildimage/pull/9486
> [202012] [bgp] Enable BGP Graceful Restart based on device role

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/watchdog.py
Initial implementation of Watchdog platform plugin for BMC-based boards
Run platform_tests/test_reload_config.py
```
platform_tests/test_reload_config.py::test_reload_configuration PASSED   [ 50%]
platform_tests/test_reload_config.py::test_reload_configuration_checks PASSED [100%]
```
> [BFN] Added watchdog platform plugin

- src/sonic-frr/patch/0009-ignore-route-from-default-table.patch
Fix issue https://github.com/sonic-net/sonic-buildimage/issues/12753.
As described in detail in https://github.com/sonic-net/sonic-buildimage/issues/12753, the current FRR patch `0009-ignore-route-from-default-table.patch` is causing unwanted FRR/zebra error logs. This change gets rid of the error messages for routes from kernel default table while these routes are ignored in prefix encoding.
This fix updates the original 0009 patch by checking if the routes are from table default before printing the error logs. The original patch checks the same condition and ignores the routes from table default in prefix encoding.
Follow the steps to repro as described in https://github.com/sonic-net/sonic-buildimage/issues/12753.
Also verify the test case `ipfwd/test_nhop_count.py` no longer fails due …
> [PATCH]: Update FRR patch 0009 to avoid inappropriate error messages

- dockers/docker-orchagent/docker-init.j2
In the PR https://github.com/sonic-net/sonic-platform-daemons/pull/311 the table for updating the fabric asic was changed. This PR is update docker-init.sh to use the correct table to detect the fabric asic.
update `docker-init.sh`
Check on chassis
> [chassis][202205] fix to use the correct table in chassis_state_db

- files/build_templates/sonic_debian_extension.j2
- files/image_config/cron.d/logrotate
- files/image_config/logrotate/timerOverride.conf
Debian is shipping a systemd timer unit for logrotate, but we're also packaging in a cron job, which means both of them will run, potentially at the same time. Remove our cron file, and add an override to the shipped timer file to have it be run every 10 minutes.
Fixes #12392.
> Replace logrotate cron file with (adapted) systemd timer file

- .azure-pipelines/docker-sonic-slave.yml
- Makefile.work
Now sonic-build-hooks is built at first and copied into sonic-slave.
We don't need to calculate it in sonic slave tag.
Remove sonic-build-hooks from sonic slave tag.
> [build] Remove sonic-build-hooks in slave base tag.

- dockers/docker-dhcp-relay/dhcp-relay.monitors.j2
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>
1. config vlan add 100
2. config vlan member add Ethernet0
3. config interface ip add Vlan100 <ip_addr>
4. config load 
```
{
"DHCP_RELAY" :{
"Vlan100" : {
"dhcpv6_servers" : ["fc02:2000::2"]
}
}
}
```
5. Systemctl restart dhcp_relay
1. dhcp_relay container doesn't start with the following log
```
Dec  8 21:19:47.779998 sonic  INFO dockerd[572]: time="2022-12-08T21:19:47.779415981+02:00" level=error msg="Error setting up exec command in container dhcp_relay: Container 4a64823d9a9a3617f5fdb8f9b54a10e6ebf003df1c3dafeea1606ca38a9ae0d8 is not running"
```
2. Happened because of the wrong jinja formatting of supervisord.conf file which results in:
```
root@sonic:/home/admin# sonic-cfggen -d -t docker-dhcp-relay.supervisord.conf.j2 …
```
> [dhcpv6_relay] Fix dependency of dhcp-mon on VLAN with only v6 cfg is provided

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/sflow.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/sflow.json
- src/sonic-yang-models/yang-models/sonic-sflow.yang
Porting fix https://github.com/sonic-net/sonic-buildimage/pull/12897
- Why I did it
Fixed sflow yang model to include collector_vrf field.
- How I did it 
-Added leaf for collector_vrf under sflow_collector. Additionally aligned the configuration guide
- How to verify it 
Added UT to verify.
> [202205][yang] Add collector_vrf to sflow yang model   (#12897)

- platform/marvell-armhf/sai.mk
Signed-off-by: rajkumar38 <rpennadamram@marvell.com>
Update Marvell armhf sai debian version. Includes supports for,
1) Autoneg
2) Everflow 
Compile and load SONiC armhf bin
> [Marvell] Update armhf sai debian

- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
`system_ref_core_clock_khz` was missing in Arista-7800R3A-36D2-C36 and Arista-7800R3A-36D2-C72 for ASIC1.
> Add missing system_ref_core_clock_khz in Arista-7800R3A-36D2-C36 and Arista-7800R3A-36D2-C72

- platform/broadcom/sai.dep
We download libsaibcm.deb every time when we use make to build.
That's because we use build hook but not real wget to get hash for SAI_FLAGS.
As a result we also call curl for libsaibcm.deb inside of function download_packages.
Add SKIP_BUILD_HOOK=y to use real wget instead of build hook.
I redirected all requests to proxy to log them (1st column is timing).
Without fix (curl, curl , wget):
1668034736.348  0 CONNECT sonicstorage.blob.core.windows.net:443
1668034831.997  40064209 GET https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm_7.1.17.4_amd64.deb
1668034832.601  0 CONNECT sonicstorage.blob.core.windows.net:443
1668034833.212  113911 GET https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm-dev_7.1.17.4_amd64.deb …
> [build] use real wget for SAI_FLAGS

- platform/mellanox/mlnx-platform-api/sonic_platform/module.py
- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
Remove TODO comments which are no longer needed
Remove TODO comments which are no longer needed
Only comment change
> [Mellanox] Remove TODO comments which are no longer needed

- dockers/docker-platform-monitor/Dockerfile.j2
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/bfn_extensions/psu_sensors.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
Platform interface doesn't provide all sensors and using it isn't effective
Request sensors via http from BMC server and parse the result
Related daemon in pmon populates redis db, run this command to view the contents
```
show platform psustatus
```
> [BFN]: Implement getting psu related sensors in sonic_platform directly from BMC

- platform/s3ip-sysfs/s3ip_sysfs_frame/fan_sysfs.c
- platform/s3ip-sysfs/s3ip_sysfs_frame/include/fan_sysfs.h
Signed-off-by: tianshangfei <tian_shangfei@163.com>
Provide a Fan driver framework that complies with s3ip sysfs specification
1、	The framework module provides register and unregister interface and implementation. 
2、	The framework will help you create the sysfs node
A demo driver base on this framework will display the sysfs node wich conform to the s3ip sysfs specification
> The FAN driver framework module complies with s3ip sysfs specification

- platform/s3ip-sysfs/s3ip_sysfs_frame/include/transceiver_sysfs.h
- platform/s3ip-sysfs/s3ip_sysfs_frame/transceiver_sysfs.c
Provide a transceiver driver framework that complies with s3ip sysfs specification
1、	The framework module provides register and unregister interface and implementation. 
2、	The framework will help you create the sysfs node
A demo driver base on this framework will display the sysfs node wich conform to the s3ip sysfs specification
> Kernel framework transceiver

- platform/s3ip-sysfs/scripts/s3ip-sysfs.service
- platform/s3ip-sysfs/scripts/s3ip_load.py
- platform/s3ip-sysfs/scripts/s3ip_sysfs_conf.json
- platform/s3ip-sysfs/scripts/s3ip_sysfs_tool.sh
Signed-off-by: tianshangfei <tian_shangfei@163.com>
The user framework module complies with s3ip sysfs specification
1、	create a s3ip_sysfs service
2、 the s3ip_sysfs service call the “s3ip_sysfs_tool.sh” to install kernel module and  run s3ip_load.py
3、 s3ip_load.py will parse the s3ip_sysfs_conf.json configuration file and create /sys_switch/ directory
A demo driver base on this framework will display the sysfs node wich conform to the s3ip sysfs specification
> The user framework module complies with s3ip sysfs specification

- platform/mellanox/docker-syncd-mlnx/ecmp_calculator/README.md
Update ECMP calculator README file with new instructions how to run the calculator.
Update README file.
Read README file.
> [Mellanox] Update ECMP calculator README file

- slave.mk
It is to fix the broadcom build failure, it is caused by the build image docker-dhcp-relay:latest not found.
```
2022-12-14T00:09:57.5464893Z [ FAIL LOG START ] [ target/docker-dhcp-relay.gz-load ]
2022-12-14T00:09:57.5466036Z Attempting docker image lock for docker-dhcp-relay load
2022-12-14T00:09:57.5467113Z Obtained docker image lock for docker-dhcp-relay load
2022-12-14T00:09:57.5468206Z Loading docker image target/docker-dhcp-relay.gz
2022-12-14T00:09:57.5469361Z Loaded image: docker-dhcp-relay:internal.65852159-11ad82a07a
2022-12-14T00:09:57.5470686Z Tagging docker image docker-dhcp-relay:latest as docker-dhcp-relay-sonic:latest
2022-12-14T00:09:57.5471997Z Error response from daemon: No such image: docker-dhcp-relay:latest
2022-12-14T00:09:57.5473122Z [  FAIL LOG END  ] [ …
```
> [Build] Fix the docker image docker-dhcp-relay:latest not found issue

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/config.bcm.j2
- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/config.bcm.j2
- device/arista/x86_64-arista_7050cx3_32s/td3-a7050cx3-32s-flex.config.bcm
…"
revert PR https://github.com/sonic-net/sonic-buildimage/pull/12900
This reverts commit dd87a791b4973c170314ae861514250f26eb31d1.
> Revert "[Arista] Disable pcie checking on x86_64-arista_7050cx3_32s (#12900)

- src/sonic-build-hooks/scripts/buildinfo_base.sh
Fix #12279
Curl can fail when we calculate md5sum of web package.
E.g. if server responsed with 503 error.
But we don't validate this and pass any output from curl directly to md5sum.
After that we save incorrect md5 hash to versions-web file.
1. use option --retry 5 for transient errors (default value is 0)
2. use option -f for curl and set -o pipefail for shell to detect errors
3. stop build if curl failed
Signed-off-by: Konstantin Vasin <k.vasin@yadro.com>
> [Build] fix md5sum calculation of web packages if transient error

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/sai.profile
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/sai.profile
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/sai.profile
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/sai.profile
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/sai.profile
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/sai.profile
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/sai.profile
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/sai.profile
fixes #12608 by reserving NON_ECMP Fec entries for single path Nexthops/V4/v6NBR Entries.
On DNX (J2/J2c/J2c+) platforms, Single Path Nexthops and ECMp Nexthop resources(FECs) are shared. BRCM SAI do not have partition of this resource, and hence more single path Nexthop entries, causes ECMP programming to fail in scaled setup.
Broadcom provided SAI changes to reserve resources for single path nexthop entries(More details in CSP: https://brcmsemiconductor-csm.wolkenservicedesk.com/wolken-support/allcases/request-details?requestId=CS00012251649). 
Along with SAI changes, they provided configurable Macro/flag to reserve NON_ECMP entries. 
This PR is to add that flag in various sai.profile files wherever applicable. 
PS: We are reserving 3072 single path Nexthop entries on each Linecard. …
> [BRCM-DNX(J2/J2c/J2c+)]:Reserve Non-ECMP Fec Resource for Non-ECMP Route Nexthops/NBR Entries

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/tests/caclmgrd/caclmgrd_soc_rules_test.py
- src/sonic-host-services/tests/caclmgrd/test_soc_rules_vectors.py
This PR is a required for changing the L3 IP forwarding Behavior to SoC in active-active toplogy. 
Basically a src IP is added to the SNAT rule so that only packets originating from ToR with src IP as vlan IP get natted by the rule and change the src IP to LoopBack IP
Master Branch PR with combined change is here
https://github.com/sonic-net/sonic-host-services/pull/3
check the config DB if the ToR is a DualToR and has an SoC IP assigned.
put an iptable rule
iptables -t nat -A POSTROUTING --destination -j SNAT --to-source "
Signed-off-by: vaibhav-dahiya [vdahiya@microsoft.com](mailto:vdahiya@microsoft.com)
```
Rules are only added once
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
Chain INPUT (policy ACCEPT)
target     prot opt source …
```
> [caclmgrd][dualtor] add src IP to the SNAT rule for allowing gRPC packets forwarded via Loopback3

- files/docker/docker
Ubuntu 22.04 uses cgroup2 by default, but docker.sh doesn't  mount it.
As a result we get an error when trying to run `docker info` in chroot env:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
mount cgroup2 in chroot if all enabled kernel cgroup controllers are currently not in use by cgroup1
With this fix the build finished successfully on ubuntu 22.04
> [Build] mount cgroup2 in chroot to fix build on ubuntu 22.04

- device/arista/x86_64-arista_720dt_48s/td3x2-a720dt-48s-flex.config.bcm
This is to fix test_forward_ip_packet_with_0xffff_chksum_tolerant test failure on 720DT-48S. IP packets with checksum set to 0xffff will be forwarded with the same checksum on this platform, instead of updating to the correct value.
Add bcm config sai_verify_incoming_chksum=0 so that checksum is updated instead of being left unchanged when checksum is 0xffff. Note that packets with invalid checksum are still dropped with this config.
Test passes
> [Arista] Update ip packet checksum when set to 0xffff on 720DT-48S

- platform/pddf/i2c/modules/include/pddf_psu_api.h
- platform/pddf/i2c/modules/include/pddf_psu_driver.h
- platform/pddf/i2c/modules/psu/driver/pddf_psu_api.c
- platform/pddf/i2c/modules/psu/driver/pddf_psu_driver.c
- platform/pddf/i2c/utils/pddfparse.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_psu.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_thermal.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddfapi.py
1) Consolidating multiple read functions in a PSU driver on the basis of byte, word or block read, 
2) Enhancing PDDF parsing script support for CPU and PCH temperature reading, 
3) Adding missing methods in PDDF common APIs
- PSU driver changes are to optimize the code and increase the code coverage
- PDDF parser script enhancements to accommodate the CPU and PCH temp reading using hwmon device path
- Some of the new APIs were missing from the PDDF common platform classes
Added code changes and verified them on AS7816 adn AS7726 platforms.
*AS7816*
```
root@sonic:/home/admin# show platform summary
Platform: x86_64-accton_as7816_64x-r0
HwSKU: Accton-AS7816-64X
ASIC: broadcom
ASIC Count: 1
Serial Number: AAA1903AAEV
Model Number: FP3AT7664000A
Hardware Revision: N/A …
```
> Adding PDDF common framework enhancements.

- Makefile.work
- build_debian.sh
- build_docker.sh
- build_image.sh
- rules/config
- slave.mk
- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
It's possible to speed up some parts of a build using parallel compression/decompression.
This is especially important for build_debian.sh.
pigz is a parallel implementation of gzip: https://zlib.net/pigz/
Some programs like docker and mkinitramfs can automatically detect and use it instead of gzip.
For tar we need to select it directly.
To enable this feature you need to set GZ_COMPRESS_PROGRAM=pigz
> [Build] use pigz to speed up a build

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py
Fixes #12634 
Observing the following error while running 'sfputil show lpmode' command.
AttributeError: 'Sfp' object has no attribute 'get_power_set'
Root Cause: get_power_set() is defined for QSFP28 and QSFP+ i.e. Sff8636 and Sff8634. However, the function is not defined in the optoe_base class.
To use get_power_set(), we need to initialise the 'api' via get_xcvr_api() and then use it to run get_power_set().
> # sfputil show lpmode 
```
root@sonic:/home/admin# sfputil show lpmode
Port         Low-power Mode
-----------  ----------------
Ethernet88   Off
Ethernet96   Off
Ethernet248  Off
Ethernet240  Off
Ethernet32   Off
root@sonic:/home/admin# sfputil lpmode on Ethernet240
Enabling low-power mode for port Ethernet240 ... OK
root@sonic:/home/admin# sfputil show …
```
> Fixing #12634

- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
**This PR is to backport https://github.com/sonic-net/sonic-buildimage/pull/13100 to the 202205 branch since can not be cleanly cherry-picked.**
Following code to judge whether a process is running inside a docker could get stuck on the simx platform
```
subprocess.Popen(["docker", "--version"],
stdout=subprocess.PIPE,
stderr=subprocess.STDOUT,
universal_newlines=True)
```
When it gets stuck, the **config-chassisdb** service can not be successfully started, thus the system can not be booted up.
```
root@sonic:/# service config-chassisdb status
config-chassisdb.service - Config chassis_db
Loaded: loaded (/lib/systemd/system/config-chassisdb.service; enabled; vendor preset: enabled)
Active: activating (start) since Thu 2022-12-15 09:23:02 UTC; 29min ago
Main PID: 571 (config-chassisd) …
```
> [202205][Mellanox] change the implementation of is_host() to fix a stuck issue on simx platform

- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
Following code to judge whether a process is running inside a docker could get stuck on the simx platform
```
subprocess.Popen(["docker", "--version"],
stdout=subprocess.PIPE,
stderr=subprocess.STDOUT,
universal_newlines=True)
```
When it gets stuck, the **config-chassisdb** service can not be successfully started, thus the system can not be booted up.
```
root@sonic:/# service config-chassisdb status
config-chassisdb.service - Config chassis_db
Loaded: loaded (/lib/systemd/system/config-chassisdb.service; enabled; vendor preset: enabled)
Active: activating (start) since Thu 2022-12-15 09:23:02 UTC; 29min ago
Main PID: 571 (config-chassisd)
Tasks: 14 (limit: 9501)
Memory: 132.4M
CGroup: /system.slice/config-chassisdb.service
├─571 /bin/bash /usr/bin/config-chassisdb
├─575 /usr/bin/python3 …
```
> [Mellanox] change the implementation of is_host() to fix a stuck issue on simx platform

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
In order to prevent the [sonic-mgmt/tests/platform_tests/sfp/test_sfputil.py](https://github.com/sonic-net/sonic-mgmt/blob/1224b087efe5635c3bd7c643388a95cd28d80b2b/tests/platform_tests/sfp/test_sfputil.py#L90) test failing on the log analyzer step.
The mentioned test is performing the `sfputil reset EthernetX` for every interface on the SONiC switch, this action will flap the SFP device status (`INSTERTED -> REMOVED -> INSTERTED`).
The SONiC XCVRD daemon will catch this SFP device status change (because it is monitoring the presence status of the cable).
To judge the cable presence status, currently, we are still leveraging to read the first bytes of the EEPROM, and the EEPROM could be not ready at some moment and the SONiC XCVRD daemon will print the error log to Syslog:
```
ERR …
```
> [SFP] Change logging severity when failed to read EEPROM

- slave.mk
In PR check pipelines, there are too many duplicated warnings:
fatal: No names found, cannot describe anything.
SONIC_IMAGE_VERSION will not change in one build. We don't need to calculate in every reference. We just need calculate one time, then record it.
In Makefile, '=' will calculate again and again when it is referred.
Fix it in Makefile.
Check this PR's check pipeline result.
> [build] Fix unexpected warnings: No names found, cannot describe anything.

- .github/workflows/pr_cherrypick_poststep.yml
To keep 'Request for xxx branch' label when finished auto-cherry-pick.
Change logic in post cherry pick action.
> [action] Keep 'request for xxx branch' label when finished auto-cherry-pick

- platform/broadcom/sonic-platform-modules-dell/s5212f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5212f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5296f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5296f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/z9432f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/z9432f/sonic_platform/component.py
- When a non-root user tries to run 'show interface status' command, the command got break as 2.0 API throws permission denied error.
- Using default definitions for sfp presence and fw version.
- By running the command 'show interface status'
On branch s6100-int-status                                                                                                                      
Changes to be committed:                                                                                                                          
(use "git restore --staged <file>..." to unstage)                                                                                                     
modified:   s5212f/sonic_platform/chassis.py …
> [DellEMC] Fixing 'show interface status' break in DellEMC platforms

- device/accton/x86_64-accton_as4630_54pe-r0/sonic_platform/helper.py
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/helper.py
- device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/helper.py
- device/accton/x86_64-accton_as7312_54x-r0/sonic_platform/helper.py
- device/accton/x86_64-accton_as7816_64x-r0/sonic_platform/helper.py
- device/accton/x86_64-accton_as9726_32d-r0/sonic_platform/helper.py
Signed-off-by: roger530-ho <roger530_ho@edge-core.com>
Why I did it
The is_host function causes the system to get some errors, as below.
1. The thermalctld got exception.
```
admin@sonic:~$ show platform temperature
Thermal Not detected
admin@sonic:~$ sudo cat /var/log/syslog | grep thermalctld
Dec 19 07:04:41.905942 sonic INFO pmon#supervisord 2022-12-19 07:04:41,905 INFO spawned: 'thermalctld' with pid 66
Dec 19 07:04:42.190356 sonic INFO pmon#supervisord: thermalctld Traceback (most recent call last):
Dec 19 07:04:42.190405 sonic INFO pmon#supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 922, in <module>
Dec 19 07:04:42.190476 sonic INFO pmon#supervisord: thermalctld     sys.exit(main())
Dec 19 07:04:42.190544 sonic INFO pmon#supervisord: thermalctld   File …
```
> [Edgecore][device/accton] Fix subprocess.call issue in is_host().

- .azure-pipelines/docker-sonic-slave-template.yml
tag sonic-slave-* image with branch.
Only keep sonic-slave-* latest tag when it is master branch and amd64 arch.
> [ci] Adjust sonic-slave-* image tags.

- dockers/docker-dhcp-relay/cli/clear/plugins/clear_dhcp6relay_counter.py
Avoid traceback on sonic-clear command
```
sonic-clear dhcp6relay_counters 
File "/usr/local/bin/sonic-clear", line 8, in <module>
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File …
```
> [dhcp_relay]Fix the clear dhcp6relay_counters CLI

- files/build_templates/per_namespace/swss.service.j2
- files/build_templates/per_namespace/syncd.service.j2
Remove dependency on interfaces-config.service to speed up boot, because interfaces-config.service takes a lot of time on boot.
Changed service files for swss, syncd.
Boot and check swss/syncd start time comparing to interfaces-config
> [swss/syncd] remove dependency on interfaces-config.service

- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/docker-sonic-slave.yml
1. Currently sonic-slave-* tag is confusing. Set correct tag on sonic-slave-* image.
2. Fix job name to fit the build.
build amd image in amd64:
sonic-slave-bullseye:cfe29bff67c
sonic-slave-bullseye:latest
sonic-slave-bullseye:master
build armhf image in amd64:
sonic-slave-bullseye-march-armhf:33614806dc3
sonic-slave-bullseye-march-armhf:latest
sonic-slave-bullseye-march-armhf:master
build arm64 image in amd64:
sonic-slave-bullseye-march-arm64:f3b1b16c801
sonic-slave-bullseye-march-arm64:latest
sonic-slave-bullseye-march-arm64:master
build arm64 image in arm64:
sonic-slave-bullseye:75cb326c9a7
sonic-slave-bullseye-arm64:latest
sonic-slave-bullseye:master
build armhf image in armhf:
sonic-slave-bullseye:64d178951fc
sonic-slave-bullseye-armhf:latest
sonic-slave-bullseye:master
> Fix sonic slave pipeline to set correct tag on sonic slave image.

- files/build_templates/init_cfg.json.j2
- slave.mk
The followup to https://github.com/sonic-net/sonic-buildimage/pull/12920 PR.
If the feature compilation is disabled its configuration should not be included into init_cfg.json.
Update `init_cfg.json.j2` template to include teamd and radv features configuration only if their compilation is enabled.
The default behavior is preserved. To verify the changes compile the image without overriding `INCLUDE_TEAMD` and `INCLUDE_ROUTER_ADVERTISER` options. The generated `/etc/sonic/init_cfg.json` should remain with no changes. Install the image and verify that both teamd and radv containers are present and running. Verify that feature state returned by `show feature status` command is `enabled`.
Change the `INCLUDE_TEAMD` or `INCLUDE_ROUTER_ADVERTISER` value to "n". Compile and install the image. …
> [build] Adjust teamd and radv features configuration according to the compilation options.

- files/build_templates/sonic_debian_extension.j2
- sonic-slave-buster/Dockerfile.j2
The libyang cannot be built with the latest version of cmake.
Example: https://dev.azure.com/mssonic/build/_build/results?buildId=181862&view=logs&j=993d6e22-aeec-5c03-fa19-35ecba587dd9&t=d0538dec-1681-5ff8-bd45-c0de13be9706
```
[ 96%] Building CXX object swig/python2/CMakeFiles/_yang2.dir/yangPYTHON_wrap.cxx.o
/sonic/src/libyang/libyang-1.0.73/build/swig/python2/yangPYTHON_wrap.cxx:3292:33: error: expected initializer before '.' token
^
/sonic/src/libyang/libyang-1.0.73/build/swig/python2/yangPYTHON_wrap.cxx:102537:1: note: in expansion of macro 'SWIG_init'
SWIG_init(void) {
^~~~~~~~~
/sonic/src/libyang/libyang-1.0.73/build/swig/python2/yangPYTHON_wrap.cxx:101971:24: warning: 'swig_const_table' defined but not used [-Wunused-variable]
static swig_const_info swig_const_table[] = {
```
See …
> [Build][202106] Fix libyang build broken issue

- .azure-pipelines/docker-sonic-slave-template.yml
In 13177 PR, there is a bug when tagging branch tag.
origin:
```
build arm64 image in arm64:
sonic-slave-bullseye:75cb326c9a7
sonic-slave-bullseye-arm64:latest
sonic-slave-bullseye:master
```
after fix:
```
build arm64 image in arm64:
sonic-slave-bullseye:75cb326c9a7
sonic-slave-bullseye-arm64:latest
sonic-slave-bullseye-arm64:master
```
> [ci] Fix docker sonic slave tag issue.

- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/docker-sonic-slave.yml
Currently sonic-slave-* tag is confusing. Set correct tag on sonic-slave-* image. Fix job name to fit the build.
build amd image in amd64:
sonic-slave-bullseye:cfe29bff67c
sonic-slave-bullseye:latest
sonic-slave-bullseye:master
build armhf image in amd64:
sonic-slave-bullseye-march-armhf:33614806dc3
sonic-slave-bullseye-march-armhf:latest
sonic-slave-bullseye-march-armhf:master
build arm64 image in amd64:
sonic-slave-bullseye-march-arm64:f3b1b16c801
sonic-slave-bullseye-march-arm64:latest
sonic-slave-bullseye-march-arm64:master
build arm64 image in arm64:
sonic-slave-bullseye:75cb326c9a7
sonic-slave-bullseye-arm64:latest
sonic-slave-bullseye:master
build armhf image in armhf:
sonic-slave-bullseye:64d178951fc
sonic-slave-bullseye-armhf:latest
sonic-slave-bullseye:master
> Fix sonic slave pipeline to set correct tag on sonic slave image. (#13177)

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/tunnel.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/tunnel.json
- src/sonic-yang-models/yang-models/sonic-tunnel.yang
Signed-off-by: Nikola Dancejic <ndancejic@microsoft.com>
Add yang model for TUNNEL config
created sonic-tunnel.yang file and tests
`make target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl`
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md#tunnel
> add Tunnel yang model

- dockers/docker-ptf/Dockerfile.j2
- scripts/prepare_docker_buildinfo.sh
[Build] Support j2 template for Debian sources for docker ptf
Change to use the sources.list from the file generated from the j2 template
> [Build] Support j2 template for Debian sources for docker ptf

- dockers/docker-dhcp-relay/dhcp-relay.monitors.j2
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>
Backport PR https://github.com/sonic-net/sonic-buildimage/pull/13006 to 202012
> [202012] [dhcpv6_relay] Fix dependency of dhcp-mon on VLAN with only v6 cfg is provided

- platform/centec-arm64/sai.mk
- platform/centec/sdk.mk
Change makefile to reference to new SAI debian package of v1.11.0-1
Modify sai.mk of arm64 platform and sdk.mk of x86 platform for Centec
> update centec-sai reference to v1.11.0-1

- functions.sh
./functions.sh script contains twice the command "git describe --tags". Azure pipelines currently retrieves the repository content by using a "git clone" or "git fetch" command with the option "--depth". When the depth is not enough sized to reach a tag in the "git log" history,  "git describe --tags" generates on stderr the warning: "fatal: No names found, cannot describe anything."
https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything
During the build process, the functions.sh script is a lot consumed and this pointless warning appears in CI thousand lines w/o any added value.
This situation can be easily avoided by redirecting related commands stderr output to /dev/null.
Issue #13106
all
[build] fix CI warnings issued by "git …
> [build] fix CI warnings issued by "git describe"

- .azure-pipelines/run-test-scheduler-template.yml
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
1. Each step has its own signature of success or failure.
2. Using the chain of responsibility pattern to …
> [TestbedV2][202012]Improve the display of pipeline.

- .azure-pipelines/run-test-scheduler-template.yml
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
1. Each step has its own signature of success or failure.
2. Using the chain of responsibility pattern to …
> [TestbedV2][202205]Improve the display of pipeline.

- .azure-pipelines/run-test-scheduler-template.yml
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
1. Each step has its own signature of success or failure.
2. Using the chain of responsibility pattern to …
> [TestbedV2][202211]Improve the display of pipeline.

- platform/broadcom/sonic-platform-modules-dell/s5212f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5212f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
- When a non-root user tries to run 'show interface status' command, the command got break as 2.0 API throws permission denied error.
- Porting changes from #13021  to 202205 branch as cherry-pick failed.
- Using default definitions for sfp presence and fw version.
- By running the command 'show interface status'.
```
On branch 202205-s6100-int                                                                                                                      
Changes to be committed:                                                                                                                          
(use "git restore --staged <file>..." to unstage)                                                                                                     
modified: …
```
> [202205][DellEMC] Fixing 'show interface status' break in DellEMC platforms porting changes

- src/sonic-eventd/rsyslog_plugin_tests/rsyslog_plugin_ut.cpp
Timestamp formatter inside UT was failing due to new year change
Use a const stored year that will used as expected value
Run UT
> Fix rsyslog_plugin UT with timestamp formatter

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
[Ci] Remove the platform innovium from version auto upgrade pipeline
There is a build issue in the specific platform innovium, it blocks the upgrade job to run successfully, disable the version upgrade temporarily.
Remove the upgrade job for innovium
> [Ci][202106] Remove the platform innovium from version auto upgrade pipeline

- src/dhcpmon/src/dhcp_device.cpp
- src/dhcpmon/src/dhcp_device.h
- src/dhcpmon/src/dhcp_mon.cpp
1. Fix issue caused by dualtor support PR https://github.com/sonic-net/sonic-buildimage/pull/11201
2. Improve code
1. On single ToR, packets received count was duplicated due to socket filter set to "inbound"
2. Tx count not increasing due to filter set to "inbound". Added an outbound socket to count tx packets
3. Added vlan member interface mapping for Ethernet interface to vlan interface lookup in reference to PR https://github.com/sonic-net/sonic-dhcp-relay/pull/27
4. Exit when socket fails to initialize to allow dhcp_relay docker to restart
Tested on vstestbed single tor and dual tor, sent packets and verify printed out dhcpmon rx and tx counters is correct
- Correct number of tx increases
- Tx does not increase when ToR is on standby
> [dhcpmon] Fix dhcpmon socket filter and tx count issue

- files/image_config/platform/rc.local
[Centec arm64] Solve the abnormal console speed of centec-arm64 switch board
Signed-off-by: centecqianj <qianj@centec.com>
The console of the centec-arm64 board is ttyAMA0.The current regular expression cannot be correctly parsed.
Optimize the regular expression of console.
The console of the centec-arm64 board displays normally, and changes do not affect other boards.
> [Centec arm64] Solve the abnormal console speed of centec-arm64 switch board

- .azure-pipelines/run-test-scheduler-template.yml
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
The display of azure pipeline is not specific now, such as when the step Run test fails, the display of itself shows successful, but the display of step Kvmdump shows fails, but actually, the step Kvmdump doesn't fail. I improve the display of azure pipeline in this pr, each step has its own success or failure, and is shown in azure pipeline.
1. Each step has its own signature of success or failure.
2. Using the chain of responsibility pattern to …
> [TestbedV2][master]Improve the display of pipeline.

- .azure-pipelines/docker-sonic-slave-template.yml
docker-sonic-slave pipeline has a different tag with PR build.
It leads to ENABLE_DOCKER_BASE_PUll=y not work.
set reproducible build option in bash.
> [ci] Fix docker-sonic-slave pipeline template build options.

- device/alphanetworks/x86_64-alphanetworks_snh60a0_320fv2-r0/plugins/led_control.py
- device/alphanetworks/x86_64-alphanetworks_snh60b0_640f-r0/plugins/led_control.py
Fix code issue when SonicV2Connector.get() return None.
When database key does not exist, SonicV2Connector.get() will return None.
Code will break if not check return value.
Check SonicV2Connector.get() return value before use it.
Add new Redis database PROFILE_DB
> Fix code issue when SonicV2Connector.get() return None.

- src/sonic-host-services/setup.py
The deepdiff python package was recently updated to 6.2.3. As part of this, a dependency was introduced on orjson. There's no armv8l python wheel available for orjson, which means it needs to be built from source. However, building it requires rust (which Buster and Bullseye don't have a new enough version of) and maturin.
As a quick fix, pin this to version 6.2.2, before the orjson dependency is introduced.
> [202205] sonic-host-services: Pin deepdiff to version 6.2.2

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/tests/test_chassis.py
In case of warm/fast reboot, the hardware reboot cause will NOT be cleared because CPLD will not be touched in this flow. To not confuse the reboot cause determine logic, the leftover hardware reboot cause shall be skipped by the platform API, platform API will return the 'REBOOT_CAUSE_NON_HARDWARE'  instead of the "hardware" reboot cause.
Check the proc cmdline to see whether the last reboot is a warm or fast reboot, if yes skip checking the leftover hardware reboot cause.
a. Manual test:
1. Perform a power loss
2. Perform a warm/fast reboot
3. check the reboot cause should be "warm-reboot" or "fast-reboot" instead of "power loss" 
b. Run reboot cause related regression test.
> [Mellanox] Skip the leftover hardware reboot cause in case of last boot is warm/fast reboot

- files/image_config/platform/rc.local
[Bug] Fix SONiC installation failure caused by pip/pip3 not found
```
[   13.214043] rc.local[523]: Reading package lists...
[   13.282396] rc.local[427]: + LANG=C DEBIAN_FRONTEND=noninteractive apt-get -y install /host/image-20201231.84/platform/x86_64-cel_e1031-r0/platform-modules-haliburton_0.9_amd64.deb
[   13.491331] rc.local[538]: Reading package lists...
[   13.562286] rc.local[538]: Building dependency tree...
[   13.634080] rc.local[538]: Reading state information...
[   13.706067] rc.local[538]: The following NEW packages will be installed:
[   13.794253] rc.local[538]:   platform-modules-haliburton
[   13.866269] rc.local[538]: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
[   13.970064] rc.local[538]: Need to get 0 B/313 kB of archives.
[   14.046052] …
```
> [Bug] Fix SONiC installation failure caused by pip/pip3 not found

- src/sonic-yang-models/yang-models/sonic-dash.yang
> [Dash] Fix a typo in yang model

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/radius.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/radius.json
- src/sonic-yang-models/yang-models/sonic-system-radius.yang
Added SONiC YANG model for RADIUS. 
Fixes https://github.com/sonic-net/sonic-buildimage/issues/12477 
Added the RADIUS and RADIUS_SERVER tables for global and per RADIUS server configuration. RADIUS statistics reside in COUNTERS_DB and are not part of the configuration. These are not a part of this PR.
Compiled sonic_yang_mgmt-1.0-py3-none-any.whl.
SONiC YANG model for RADIUS.
> SONiC YANG model for RADIUS.

- sonic-slave-buster/Dockerfile.j2
sonic_host_services depends on deepdiff.
But latest deepdiff version has error.
pin deepdiff to previous version.
> [build] Fix sonic-host-services dependency deepdiff version issue

- device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C32D4/jr2-a7280cr3-32d4-32x100G+4x400G.config.bcm
- device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C40/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7280cr3_32p4/Arista-7280CR3-C28S8/jr2-a7280cr3-32p4-28x100G-8x10G.config.bcm
- device/arista/x86_64-arista_7280cr3_32p4/Arista-7280CR3-C32P4/jr2-a7280cr3-32p4-32x100G+4x400G.config.bcm
- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
Disabled polled_irq_mode for all Arista DNX devices as this mode leads to excessive use of the CPU via an unneeded interrupt polling thread.
To resolve https://github.com/aristanetworks/sonic/issues/59
Disabled DNX SDK SOC property corresponding to an unnecessary thread used for polling interrupts.
After loading the image, the CPU utilization is no longer excessive.
- [ X] 202205
> [device/arista] Disabled polled_irq_mode for DNX SKUs

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
[Seastone] Enhancement fix for PR12200 syseeprom issue.
Enhance the fix through replace the hardcoded devnum to bash variable
```
show platform syseeprom or decode-syseeprom
```
> [Seastone] Enhancement fix for PR12200 syseeprom issue

- files/Aboot/boot0.j2
Many of these switches have had flash upgraded beyond 2G however, in boot0 both were assigned 2GB for legacy reasons.
Remove the hardcoding of the flash size and let boot0 autodetect the available space.
Signed-off-by: Graham Hayes <gr@ham.ie>
> [Arista] Rely on automatic flash size detection for Raven

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
This PR is to update `minigraph.py` to support both port alias and port name as input of `AttachTo` attribute of ACL table.
Before this change, only port alias is supported.
1. Add a global variable to store port names
2. Search both port names and port alias wheh parsing the value of `AttachTo`.
1. Verified by a new unit test case `test_minigraph_acl_attach_to_ports`
2. Verified by copying the new `minigraph.py` to a testbed and run `conflg load_minigraph`.
This PR is to update `minigraph.py` to support both port alias and port name as input of `AttachTo` attribute of ACL table.
> Support port name in ACL table `AttachTo` attribute

- platform/mellanox/mlnx-onie-fw-update.sh
Partial cherry-pick of:
1. https://github.com/sonic-net/sonic-buildimage/pull/9608
* To allow user manual reboot control over ONiE FW upgrade
* Added a dedicated script argument handling
* `mlnx-onie-fw-update.sh update --no-reboot`
* N/A
```
'//||\\`
''``
```
> [202012][Mellanox]: Update ONiE FW tool: manual reboot control

- src/system-health/health_checker/sysmonitor.py
This PR fixes the following issue: https://github.com/sonic-net/sonic-buildimage/issues/13180
There is a queue in sysmonitor.py that is created based on an object of multiprocessing.Manager.
After performing fast-reboot, system health monitor is being shut down, what causes this Manager to be shut down as well, since it is a child-process of healthd.
That's why I moved the creation of this Manager from the top of the file to the function Sysmonitor.system_service() (The only place it is used), to make Manager a child-process of Sysmonitor, instead of Healthd. This way both the queue (the Manager) and the processes that uses this queue will be child-processes of the same process, and the problematic scenario of sysmonitor sending messages to a dead queue will not be possible.
Removed the …
> Moving multiprocessing.Manager to the correct sub-process

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Backport https://github.com/sonic-net/sonic-buildimage/pull/13246 to 202012 branch.
In case of warm/fast reboot, the hardware reboot cause will NOT be cleared because CPLD will not be touched in this flow. To not confuse the reboot cause determine logic, the leftover hardware reboot cause shall be skipped by the platform API, platform API will return the 'REBOOT_CAUSE_NON_HARDWARE' instead of the "hardware" reboot cause.
Check the proc cmdline to see whether the last reboot is a warm or fast reboot, if yes skip checking the leftover hardware reboot cause.
a. Manual test:
> 1. Perform a power loss
> 2. Perform a warm/fast reboot
> 3. check the reboot cause should be "warm-reboot" or "fast-reboot" instead of "power loss"
b. Run reboot cause related …
> [Mellanox][202012][backport] Skip the leftover hardware reboot cause in case of last boot is warm/fast reboot

- src/ptf.patch/0001-Use-VXLAN-module-defined-in-packet.py.patch
- src/ptf.patch/series
The current PTF library contains a typo - when building a VxLAN packet, it uses the VxLAN module directly from the scapy library which will cause test failures.
Patch `simple_vxlan_packet` to use the `VxLAN` module wrapped/defined in `packet.py` from the PTF library.
> [PTF] Patch PTF library to use correct VXLAN module

- slave.mk
If make fails, we can't rerun the make process, because existing patches can't apply again.
Check if patches are applied. if yes, don't apply patches again.
> [build] Check if patches are applied before applying patches

- src/sonic-py-common/sonic_py_common/device_info.py
When getting system mac of centec platform, it would increase by 1 the last byte of mac, but it could not consider the case of carry.
Firstly, I would replace the ":" with "" of mac to a string.
And then, I would convert the mac from string to int and increase by 1, at last convert it to string with inserting ":".
> [Device/Centec]Fix the bug that it gets error system-mac of centec platform

- device/celestica/x86_64-cel_seastone-r0/platform_components.json
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/component.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/psu.py
- device/celestica/x86_64-cel_seastone-r0/system_health_monitoring_config.json
Fix the following issues for Seastone platform:
1. system-health issue: #9530, #11322
2. show platform firmware updates issue: #11317
3. other platform optimization
Modify and optimize the platform implememtation.
Manual run the test commands described in these issues.
> [Celestica Seastone] fix multi sonic platform issues

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
Backport https://github.com/sonic-net/sonic-buildimage/pull/9795
Python select.select accept a optional timeout value in seconds, however, the value passes to it is a value in millisecond.
Transfer the value to millisecond.
Manual test
> [202012] [Backport] [Mellanox] Fix select timeout in sfp event

- Makefile.work
The variable name SONIC_USERFACL_DOCKERD_FOR_MULTIARCH is mispelled in Makefile.work
> [build] Fix SONIC_USERFACL_DOCKERD_FOR_MULTIARCH typo in Makefile.work

- src/libyang2/Makefile
According to its manual page,
"[dget in its] first form, [..] fetches the requested URLs. If this is a .dsc or .changes file, then dget acts as a source-package
aware form of wget: it also fetches any files referenced in the
.dsc/.changes file.
The downloaded source is then checked with dscverify and, if successful, unpacked by dpkg-source."
Thus, when possible, dget use is preferable to wget so that sources authenticity can be performed automatically by dscverify"
all branches using libyang2 sources
[build] Migrate libyang2 sources download from wget to dget
.".
/  |
/  /
/ ,"
.-------.--- /
"._ __.-/ o. o\  
"   (    Y  )
)     /
/     (
/       Y
.-"         |
/  _     \    \ 
/    `. ". ) /' )
Y       )( / /(,/
,|      /     )
( |     /     /
" \_  (__   (__        [nabis] …
> [build] Migrate libyang2 sources download from wget to dget

- files/scripts/service_mgmt.sh
`radv` sends a good-bye packet when the service is stopped, which causes a IPv6 route update on SoC side. And this update leads to an interface bouncing and causes traffic disruption even though the ToR device might already be isolated. 
This PR is to mitigate the traffic disruption issue during planned maintenance, by killing radv instead of stopping. So the cease packet won't be sent. 
Verified on dev clusters: 
* Traffic disruption was no longer reproducible.
* `radv` took the killing path
* if knob was off, `radv` would take the stopping path
> [dualtor][active-active]Killing radv instead of stopping on `active-active` dualtor if config knob is on

- platform/mellanox/fw.mk
Signed-off-by: dprital <drorp@nvidia.com>
Add SIMX version tag to fw.mk file
> [202211][Mellanox] Add ASIC simulation version tag to fw.mk

- platform/mellanox/fw.mk
Signed-off-by: dprital <drorp@nvidia.com>
Add SIMX version tag to fw.mk file
> [202205] [Mellanox] Add ASIC simulation version tag to fw.mk

- platform/mellanox/fw.mk
Signed-off-by: dprital <drorp@nvidia.com>
Add SIMX version tag to fw.mk file
> [Mellanox] Add ASIC simulation version tag to fw.mk 

- src/dhcpmon/src/dhcp_device.cpp
- src/dhcpmon/src/dhcp_device.h
This is a cherry-pick of PR https://github.com/sonic-net/sonic-buildimage/pull/13065
Why I did it
Fix issue caused by dualtor support PR [dhcpmon] Open different socket for dual tor to enable interface filtering #11201 Improve code
How I did it
On single ToR, packets received count was duplicated due to socket filter set to "inbound" Tx count not increasing due to filter set to "inbound". Added an outbound socket to count tx packets Added vlan member interface mapping for Ethernet interface to vlan interface lookup in reference to PR Fix multiple vlan issue sonic-dhcp-relay#27 Exit when socket fails to initialize to allow dhcp_relay docker to restart How to verify it
Tested on vstestbed single tor and dual tor, sent packets and verify printed out dhcpmon rx and tx counters is correct …
> [202205][dhcpmon] Fix dhcpmon socket filter and tx count issue (#13065)

- files/scripts/service_mgmt.sh
Changing the default config knob value to be `True` for killing `radv`, due to the reasons below: 
* Killing RADV is to prevent sending the "cease to be advertising interface" protocol packet.
* [RFC 4861](https://www.rfc-editor.org/rfc/rfc4861) says this ceasing packet as "should" instead of "must", considering that it's fatal to not do this. 
* In active-active scenario, host side might have difficulty distinguish if the "cease to be advertising interface" is for the last interface leaving.
>   [6.2.5](https://www.rfc-editor.org/rfc/rfc4861#section-6.2.5).  Ceasing To Be an Advertising Interface
> 
>   - shutting down the system.
> 
>    In such cases, the router SHOULD transmit one or more (but not more
>    than MAX_FINAL_RTR_ADVERTISEMENTS) final multicast Router
>    Advertisements …
> [dualtor][active-active] changing the default value of config knob for killing `radv` to be `True`

- platform/mellanox/mlnx-fw-upgrade.j2
To improve ASIC FW upgrade logging and have information about the cause of FW update failure in the log.
Added syslog logger support
In case the FW update has failed the update tool will give the cause of the failure in the output in the last line, starting with "Fail".
When running the tool, in case of a failed update, we will parse the output to retrieve the cause and log it.
```
Device #1:
----------
Device Type:      ConnectX6DX
Part Number:      MCX623106AN-CDA_Ax
Description:      ConnectX-6 Dx EN adapter card; 100GbE; Dual-port QSFP56; PCIe 4.0/3.0 x16;
PSID:             MT_0000000359
PCI Device Name:  /dev/mst/mt4125_pciconf0
Base GUID:        0c42a103007d22d4
Base MAC:         0c42a17d22d4
Versions:         Current        Available     
FW             22.32.0498     22.32.0498 …
```
> [Mellanox] Improve FW upgrade logging

- src/system-health/health_checker/service_checker.py
- src/system-health/health_checker/sysmonitor.py
- src/system-health/health_checker/utils.py
- src/system-health/tests/test_system_health.py
This reverts commit b3a81679684d64ff380ab6f7e761587d9281679b.
Due to issue https://github.com/sonic-net/sonic-buildimage/issues/13432
> Revert "[system-health] Remove subprocess with shell=True (#12572)"

- src/sonic-frr/patch/0009-ignore-route-from-default-table.patch
…(#12912)
Why I did it
As described in detail in #12753, the current FRR patch 0009-ignore-route-from-default-table.patch is causing unwanted FRR/zebra error logs. This change gets rid of the error messages for routes from kernel default table while these routes are ignored in prefix encoding.
How I did it
This fix updates the original 0009 patch by checking if the routes are from table default before printing the error logs. The original patch checks the same condition and ignores the routes from table default in prefix encoding.
Follow the steps to repro as described in #12753.
Also verify the test case ipfwd/test_nhop_count.py no longer fails due to the error messages.
Signed-off-by: Stephen Xu <stexu@linkedin.com>
Resolve cherry-pick conflict for …
> [202012][PATCH]: Update FRR patch 0009 to avoid inappropriate error messages

- files/image_config/sudoers/sudoers
Adding `/usr/local/bin/storyteller` to `READ_ONLY_CMDS`. So no write access or prompt for password is needed to run `storyteller`. 
Tested on 202205 clusters, user who didn't request write access was able to grep log using storyteller. 
> [sudoers] add `/usr/local/bin/storyteller` to `READ_ONLY_CMDS`

- files/image_config/rsyslog/rsyslog-config.service
Fixes #12408
We are running into https://github.com/sonic-net/sonic-buildimage/issues/12408 very frequently. 
This results in no syslogs from any containers as rsyslog server could not start.
some of the sonic-mgmt scripts look for log statements and error out if log is not present. 
`Interfaces-config` service configures the loopback interface along with other interfaces. `rsyslog-config` reads ip address of loopback interface and generates `/etc/rsyslog.conf`. When this race condition happens, `lo` interface ip is not yet programmed and `rsyslog-config` ends up writing UDP server as `null` in `/etc/rsyslog.conf`.
rsyslog-config service is started after interfaces-config service.
Did multiple reboots and verified that `$UDPServerAddress` is valid.
- [ X] 202205
> rsyslog to start after interfaces-config

- .azure-pipelines/run-test-scheduler-template.yml
- azure-pipelines.yml
Add multi-asic test jobs using TestbedV2 in 202205 branch.
Add multi-asic test jobs using TestbedV2 in 202205 branch.
1. Add a job in azure-pipelines.yml to add a multi-asic test job using TestbedV2 in 202205 branch.
2. Add a parameter num_asic in .azure-pipelines/run-test-scheduler-template.yml to appiont the specific image version.
> [202205][TestbedV2] Add multi-asic test jobs using TestbedV2.

- src/dhcpmon/src/dhcp_device.cpp
- src/dhcpmon/src/dhcp_device.h
This is a cherry-pick of PR https://github.com/sonic-net/sonic-buildimage/pull/13065
Why I did it
Fix issue caused by dualtor support PR [dhcpmon] Open different socket for dual tor to enable interface filtering #11201 Improve code
How I did it
On single ToR, packets received count was duplicated due to socket filter set to "inbound" Tx count not increasing due to filter set to "inbound". Added an outbound socket to count tx packets Added vlan member interface mapping for Ethernet interface to vlan interface lookup in reference to PR Fix multiple vlan issue sonic-dhcp-relay#27 Exit when socket fails to initialize to allow dhcp_relay docker to restart How to verify it
Tested on vstestbed single tor and dual tor, sent packets and verify printed out dhcpmon rx and tx counters is correct …
> [202012][dhcpmon] Fix dhcpmon socket filter and tx count issue (#13065)

- Makefile.work
- dockers/docker-base-stretch/Dockerfile.j2
- dockers/docker-base/Dockerfile.j2
- dockers/docker-basic_router/Dockerfile
- dockers/docker-config-engine/Dockerfile.j2
- dockers/docker-fpm-quagga/Dockerfile.j2
- sonic-slave-jessie/Dockerfile.j2
The GPG key used for Jessie's official repos has since expired, which means building 201911 images no longer works.
Fake the time to be before the expiry date.
> Fix build break for jessie apt key expiration.

- device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C32D4/jr2-a7280cr3-32d4-32x100G+4x400G.config.bcm
- device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C40/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7280cr3_32p4/Arista-7280CR3-C28S8/jr2-a7280cr3-32p4-28x100G-8x10G.config.bcm
- device/arista/x86_64-arista_7280cr3_32p4/Arista-7280CR3-C32P4/jr2-a7280cr3-32p4-32x100G+4x400G.config.bcm
- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
Earlier the SDK stat polling was erroneously set to once every msec which is far more frequent than required by SWSS. The new setting, which is consistent with other vendor SKUs, is once a second. The net result is reduced CPU MHz by syncd.
To address https://github.com/aristanetworks/sonic/issues/59
Updated BCM SOC property `bcm_stat_interval` accordingly. 
Loaded the image and checked MHz usage with `top`
> [device/arista] Reduce SDK stat polling freq in DNX devices

- device/arista/x86_64-arista_7050dx4_32s/platform_env.conf
- device/arista/x86_64-arista_7050px4_32s/platform_env.conf
- device/arista/x86_64-arista_7060dx5_64s/platform_env.conf
- device/arista/x86_64-arista_7060px5_64s/platform_env.conf
- device/broadcom/x86_64-broadcom_common/syncd_shm.ini
- device/common/profiles/syncd_shm.ini
- files/build_templates/docker_image_ctl.j2
After upgrade to brcmsai 8.1, the sdk running environment (container) recommended with mininum memory size as below
- TH4/TD4(ltsw) uses 512MB
- TH3 used 300MB
- Helix4/TD2/TD3/TH/TH 256 MB
Base on this requirement, adjust the default syncd share memory size and set the memory size for special ACISs in platform_env.conf file for different types of Broadcom ASICs.
Add the platform_env.conf file if none of it for broadcom platform (base on platform_asic file)
Add the 'SYNCD_SHM_SIZE' and set the value
- for ltsw(TD4/TH4) devices set to 512M at least (update the platform_env.conf)
- for Td2/TH2/TH devices set to 256M
- for TH3 set to 300M
verify the image with code fix
Check with UT
Check on lab devices
- On a problematic device which cannot start successfully
Run with the command
```
$ cat …
```
> Set default SYNCD_SHM_SIZE for Broadcom XGS devices

- scripts/run_with_retry
- src/sonic-build-hooks/scripts/buildinfo_base.sh
issue https://github.com/sonic-net/sonic-buildimage/issues/13395
1. Fix a bug about sudo failure.
```
/usr/local/share/buildinfo/scripts/buildinfo_base.sh: line 24: sudo: command not found
```
2. Fix an issue about warning message.
```
./scripts/run_with_retry: line 4: [: : integer expression expected
```
> Fix sonic-slave-* build errors about sudo command not found

- files/build_templates/config-setup.service.j2
- files/build_templates/sonic_debian_extension.j2
- files/image_config/config-topology/config-topology.service
- files/image_config/config-topology/config-topology.sh
- src/systemd-sonic-generator/systemd-sonic-generator.c
This service invokes the platform plugin for platform specific topology
configuration.
The path for platform plugin script is:
/usr/share/sonic/device/$PLATFORM/plugins/config-topology.sh
If the platform plugin is not available, this service does nothing.
Signed-off-by: anamehra <anamehra@cisco.com>
For the chassis, the platform requires to generate the chassis topology from the available inventory. Based on the inventory config files for the platform and ASICs are generated. Some configs are global as well as ASIC specific. This needs to be done on both RP and LC and requires the availability of database-chassis and database services.
Adding this systemd dependency in platform side service unit files causes first boot issues as the database service is not known when rc.local starts the …
> Add support for platform topology configuration service

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/t0-sample-deployment-id.xml
- src/sonic-config-engine/tests/t0-sample-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
Create Vxlan and Vnet default configs as below for certain cases:
```
"VNET": {
"Vnet-default": {
"scope": "default",
"vni": "8000",
"vxlan_tunnel": "Tunnel-default"
}
},
"VXLAN_TUNNEL": {
"Tunnel-default": {
"src_ip": "10.1.0.32"
}
},
```
Master PR - https://github.com/sonic-net/sonic-buildimage/pull/13409
> [201911] Create Vxlan and Vnet default configs

- files/Aboot/boot0.j2
This is to reduce writes to disk, which might cause the SSD to get worn out faster.
Loaded it on an Arista 7260CX3, verified that /var/log was backed by tmpfs instead of disk.
> Use tmpfs for /var/log for Arista 7260

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan_drawer.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_psu.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddfapi.py
LED driver changed due to introduction of FPGA support. The PDDF parser and APIs need to be updated. In turn the common platform APIs also require changes.
1. Changed the get/set status LED APIs for PSU, fan and fan_drawer.
2. Changed the color strings to plain color name. e.g. 'STATUS_LED_COLOR_GREEN' has been changed to 'green'
3.  Added support for LED color get operation via BMC
Verified the new changes on Accton AS7816-64X platform.
```
root@sonic:/home/admin# show platform summary
Platform: x86_64-accton_as7816_64x-r0
HwSKU: Accton-AS7816-64X
ASIC: broadcom
ASIC Count: 1
Serial Number: AAA1903AAEV
Model Number: FP3AT7664000A
Hardware Revision: N/A
root@sonic:/home/admin# show ver |more
SONiC Software Version: …
```
> Modifying the PDDF common platform APIs as per the LED driver changes

- files/build_templates/docker_image_ctl.j2
- platform/mellanox/docker-syncd-mlnx/Dockerfile.j2
- platform/mellanox/docker-syncd-mlnx/platform_syncd_dump.sh
HLD: https://github.com/sonic-net/SONiC/pull/1212
Added platform specific script to be invoked during SAI failure dump. Added some generic changes to mount /var/log/sai_failure_dump as read write in the syncd docker
Added script in docker-syncd of mellanox and copied it to /usr/bin
Manual UT and new sonic-mgmt tests
> [Mellanox][sai_failure_dump]Added platform specific script to be invoked during SAI failure dump

- slave.mk
If make fails, we can't rerun the make process, because existing patches can't apply again.
https://github.com/sonic-net/sonic-buildimage/pull/13386  missed some change.
Check if patches are applied. if yes, don't apply patches again.
> [build] Check if patches are applied before applying patches.

- files/build_templates/docker_image_ctl.j2
- files/image_config/rsyslog/rsyslog-container.conf.j2
Signed-off-by: Chun'ang Li <chunangli@microsoft.com>
In to-sonic and multi-asic KVM-test, pretest sometimes failed. **Reason is rsyslogd process can not start in teamd container**. Because **rsyslog.conf is empty** caused by **sonic-cfggen execute failed**, and failed log is:
If `sonic-cfggen -d` execute failed, execute without `-d` because the template file has the default value.
Build image and test it over 40 times, all passed pretest.
> Fix rsyslogd start failed cause by rsyslog.conf is emtpy.

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan_drawer.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/watchdog.py
fix DX010 fan drawer and watchdog platform test case failure issues
1. Add fan_drawer get_maximum_consumed_power support
2. Adjust maximum watchdog timeout value check
Run test_fan_drawer and test_watchdog test cases.
> [Celestica DX010] fix fan drawer and watchdog platform testcase issues

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/platform_utils.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
Sometime, SIGTERM processing by psud takes more then default 10sec (please see stopwaitsecs in http://supervisord.org/configuration.html).
Due to this, the following two testcases may fail:
```
test_pmon_psud_stop_and_start_status
test_pmon_psud_term_and_start_status
```
Update PSU plugin to process sigterm signal so that psud runs faster to end last cycle in time
Run SONiC CTs:
test_pmon_psud_stop_and_start_status
test_pmon_psud_term_and_start_status
> [BFN] Update psu.py to process sigterm signal

- files/Aboot/boot0.j2
This is to reduce writes to disk, which then can use the SSD to get worn out faster.
Cherry pick of #13587.
> [202012]: Use tmpfs for /var/log for Arista 7260 (#13587)

- device/arista/x86_64-arista_7800r3a_36d2_lc/platform.json
The current `platform.json` contains entries for thermals and SFPs that do not exist on Wolverine.
I removed the incorrect entries.
Verify using applicable sonic-mgmt platform API tests.
This change is required for 202205 sonic-mgmt testing
> arista: Fix platform.json on Wolverine for thermal sensors and SFPs

- src/sonic-bgpcfgd/bgpcfgd/managers_rm.py
- src/sonic-bgpcfgd/tests/test_rm.py
Add support for Set 'origin' and 'AS Path' for T1 SLB routes.
When SLB programs routes to T1 (overlay routes), T1 must advertise such routes to match with the existing SLB 'origin' and AS path length. Following changes to be done during T1 advertisement:
'origin' set to 'incomplete' (value 2)
AS path to be appended as "x" + "x" (two prepend) to match the current AS path at T1 layer
Add origin and as-path prepend for routemap FROM_SDN_SLB_ROUTES.
Follow test steps in HLD.
> Set 'origin' and 'AS Path' for T1 SLB routes

- build_image.sh
Cherry pick from #10083
It is to fix the issue #10048
When building .raw image, for instance, target/sonic-broadcom.raw, it will generate a .bin image, target/sonic-broadcom.bin, as the intermediate file. The intermediate file is a build target which may contains different dependencies with the raw one.
Rename the intermediate file.
> [Build][202012]: Fix the bin image generated from raw image issue (#10083)

- build_debian.sh
Fix some version info missing in version control files issue
Change to collect version before it cleaned up
> [Build][202012]: fix some version info missing in version control files issue (#10211)

- files/Aboot/boot0.j2
Added a kernel parameter to add quirks to
The quirk added is `SDHCI_QUIRK2_BROKEN_HS200` used to downgrade the link speed for the eMMC.
> [Arista] Add emmc quirks in boot0 to improve reliability

- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
Command "sudo sfputil show error-status -hw" shows "OK (Not implemented)" in the output.  
Add a new SFP API get_error_description  support in Nokia sonic-platform  sfp.py module.
Run the new image and execute command "sudo sfputil show error-status -hw"
```
admin@sonic:~$ sudo sfputil show error-status -p Ethernet49 -hw
Port        Error Status
----------  --------------
Ethernet49  Unplugged
admin@sonic:~$ sudo sfputil show error-status -p Ethernet50 -hw
Port        Error Status
----------  --------------
Ethernet50  OK
```
Implement PMON SFP API get_error_description for Nokia-7215 platform
> [armhf][Nokia-7215] Implement PMON SFP API get_error_description for Nokia-7215 platform 

- device/arista/x86_64-arista_720dt_48s/platform_components.json
The 720DT-48S platform has variants with different chassis names, and these need to all be included in platform_components.json to ensure that sonic-mgmt platform_tests/fwutil/test_fwutil.py::test_fwutil_show passes
Updated platform_components.json with the variant names for 720DT-48S.
Ran aforementioned testcase and verified that it passes on the different variants.
> [Arista] Add other chassis names to platform_components.json for 720DT-48S

- files/Aboot/boot0.j2
To address error sometimes seen when running sonic-mgmt test_stress_routes.py::test_announce_withdraw_route on 720DT-48S
Update boot0 logic to set platform specific varlog size for 720DT-48S
Verified that /var/log size increased and error is no longer observed when running test
> [Arista] Increase 720DT-48S varlog size to 2G

- device/celestica/x86_64-cel_seastone-r0/platform.json
- device/celestica/x86_64-cel_seastone-r0/platform_components.json
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/eeprom.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
1. fix chassis test_set_fans_led case
2. fix chassis get_name case mismatch issue
3. fix fan_drawer test_set_fans_speed
4. fix component test_components test case
Add corresponding configuration into chassis json file
Run platform tests cases to verify these failure cases
> [DX010 platform] fix dx010 platform testcase issues

- build_debian.sh
The lsof and sysstat packages make determining what files/sockets a program has open a bit easier. This helps if, for example, some application has a file open that's been deleted from disk.
> Add lsof and sysstat packages to the base system for debugging purposes

- slave.mk
If make fails, we can't rerun the make process, because existing patches can't apply again.
cherry-pick PR for https://github.com/sonic-net/sonic-buildimage/pull/13566
Check if patches are applied. if yes, don't apply patches again.
> [build] Check if patches are applied before applying patches. (#13566)

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/radius.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/radius.json
- src/sonic-yang-models/yang-models/sonic-system-radius.yang
Added SONiC YANG model for RADIUS.
Added the RADIUS and RADIUS_SERVER tables for global and per RADIUS server configuration. RADIUS statistics reside in COUNTERS_DB and are not part of the configuration. These are not a part of this PR.
Compiled sonic_yang_mgmt-1.0-py3-none-any.whl.
SONiC YANG model for RADIUS.
> SONiC YANG model support for RADIUS.

- src/system-health/health_checker/service_checker.py
On a supervisor card in a chassis, syncd/teamd/swss/lldp etc dockers are created for each Switch Fabric card. However, not all chassis would have all the switch fabric cards present. In this case, only dockers for Switch Fabrics present would be created.
system-health indicates errors in this scenario as it is expecting dockers for all Switch Fabrics (based on NUM_ASIC defined in asic.conf file).
system-health process error messages were also altered to indicate which container had the issue; multiple containers may run processes with the same name, which can result in identical system-health error messages, causing ambiguity.
Port container_checker logic from https://github.com/sonic-net/sonic-buildimage/pull/11442 into service_checker for system-health.
Bringup Supervisor card with one …
> system-health service_checker should check containers based on asic presence

- files/scripts/service_mgmt.sh
Raising PR for cherry-pick conflict: https://github.com/sonic-net/sonic-buildimage/pull/13495
> [202211][dualtor][active-active] changing the default value of config knob for killing `radv` to be `True` (#13495)

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Commit https://github.com/sonic-net/sonic-platform-daemons/commit/153ea47e6ecddf750d67978f6704f832afea0d5f changed SfpStateUpdateTask from Process to Thread. In this commit, it raises an exception in SfpStateUpdateTask to make shutdown flow fast. But it does not work on Nvidia platform as Nvidia platform is passing timeout parameter of get_change_event to select. Linux select function can not be interrupted by a Python exception. There is no such issue on Nvidia platform before that commit. However, in order to comply with the commit and make shutdown flow fast, we decided to change Nvidia platform API implementation.
To fix issue https://github.com/sonic-net/sonic-buildimage/issues/13591.
1. The select call in get_change_event should use no more than 1 second as timeout parameter. 
2. …
> [Mellanox] set select timeout to no more than 1 sec to make sure fast shutdown

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/tests/test_psu.py
Support per PSU slope value for PSU power threshold according to hardware team requirement
Pass the PSU number as a parameter when fetching the slope value of PSU.
Running regression and manul test
> [Mellanox] Support per PSU slope value for PSU power threshold

- files/docker/docker.service.conf
Go's runtime (and dockerd inherits this) uses own DNS resolver implementation by default on Linux. It has been observed that there are some DNS resolution issues when executing ```docker pull``` after first boot.
Consider the following script:
```
admin@r-boxer-sw01:~$ while :; do date; cat /etc/resolv.conf; ping -c 1 harbor.mellanox.com; docker pull harbor.mellanox.com/sonic/cpu-report:1.0.0 ; sleep 1; done
Fri 03 Feb 2023 10:06:22 AM UTC
nameserver 10.211.0.124
nameserver 10.211.0.121
nameserver 10.7.77.135
search mtr.labs.mlnx labs.mlnx mlnx lab.mtl.com mtl.com
PING harbor.mellanox.com (10.7.1.117) 56(84) bytes of data.
64 bytes from harbor.mtl.labs.mlnx (10.7.1.117): icmp_seq=1 ttl=53 time=5.99 ms
--- harbor.mellanox.com ping statistics ---
1 packets transmitted, 1 received, 0% packet …
```
> [dockerd] Force usage of cgo DNS resolver

- Makefile.work
- scripts/build_mirror_config.sh
Change the mirror config file
Use the files/build/versions/default/versions-mirror only when reproducible build enabled.
The config in files/build/versions is only for reproducible build, while snapshot mirror feature does not have the dependency on the reproducible build.
Skip the mirror config in files/build/versions/default/versions-mirror if reproducible build not enabled.
> [Build] Change the default mirror version config file

- device/arista/x86_64-arista_7050dx4_32s/platform_env.conf
- device/arista/x86_64-arista_7050px4_32s/platform_env.conf
- device/arista/x86_64-arista_7060dx5_64s/platform_env.conf
- device/arista/x86_64-arista_7060px5_64s/platform_env.conf
- device/broadcom/x86_64-broadcom_common/syncd_shm.ini
- files/build_templates/docker_image_ctl.j2
After upgrade to brcmsai 8.1, the sdk running environment (container) recommended with mininum memory size as below
TH4/TD4(ltsw) uses 512MB
TH3 used 300MB
Helix4/TD2/TD3/TH/TH 256 MB
Base on this requirement, adjust the default syncd share memory size and set the memory size for special ACISs in platform_env.conf file for different types of Broadcom ASICs.
How I did it
Add the platform_env.conf file if none of it for broadcom platform (base on platform_asic file) Add the 'SYNCD_SHM_SIZE' and set the value
for ltsw(TD4/TH4) devices set to 512M at least (update the platform_env.conf) for Td2/TH2/TH devices set to 256M
for TH3 set to 300M
verify
verify the image with code fix
Check with UT
Check on lab devices
On a problematic device which cannot start successfully Run with …
> [cherry-pick][202211][broadcom]: Set default SYNCD_SHM_SIZE for Broadcom XGS devices (#13297)

- Makefile.work
- previously "make reset" was expecting user input from the terminal to do its job
- setting UNATTENDED to any non-zero string will allow "make reset" to run without interactive confirmation
When doing automated builds of SONiC images, we need to reset the working repositories between each build.
Adding an environment variable that is read by Makefile.work
running
`UNATTENDED=1 make reset
`
should make an automatic reset of all working directories
add an environment variable to run "make reset" unattended
N/A
N/A
> [build] add an environment variable to run make reset unattended

- dockers/docker-dhcp-relay/cli-plugin-tests/conftest.py
- dockers/docker-dhcp-relay/cli-plugin-tests/test_config_dhcp_relay.py
- dockers/docker-dhcp-relay/cli/config/plugins/dhcp_relay.py
DHCPv6 relay config entry is not useful while del dhcpv6 relay config.
Remove dhcpv6_relay entry if it is empty and not check entry exist while adding dhcpv6 relay
1. unit test
```
2023-02-15T14:35:30.9629795Z ----------- coverage: platform linux, python 3.9.2-final-0 -----------
2023-02-15T14:35:30.9630243Z Name                                                Stmts   Miss Branch BrPart  Cover
2023-02-15T14:35:30.9630753Z -------------------------------------------------------------------------------------
2023-02-15T14:35:30.9631093Z acl_loader/__init__.py                                  0      0      0      0   100%
2023-02-15T14:35:30.9631409Z acl_loader/main.py                                    602    226    268     39    56%
2023-02-15T14:35:30.9631702Z clear/__init__.py …
```
> [dhcp_relay] Remove exist check while adding dhcpv6 relay

- dockers/docker-dhcp-relay/cli-plugin-tests/conftest.py
- dockers/docker-dhcp-relay/cli-plugin-tests/test_config_dhcp_relay.py
- dockers/docker-dhcp-relay/cli/config/plugins/dhcp_relay.py
Cherry-pick of this PR: https://github.com/sonic-net/sonic-buildimage/pull/13822/commits
> [202211][dhcp_relay] Remove exist check while adding dhcpv6 relay

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/mirror_session.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/mirror_session.json
- src/sonic-yang-models/yang-models/sonic-mirror-session.yang
Fixes Mirror Yang model src_port to match CONFIG_DB
Fixes issue https://github.com/sonic-net/sonic-buildimage/issues/12397#issuecomment-1343109874
> [Yang-models] Modify mirror yang model src_port to match CONFIG_DB

- files/Aboot/boot0.j2
This is to reduce writes to the SSD on the device.
```
Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-C32
```
Before:
```
admin@str2-7050cx3-acs-12:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           797M  9.0M  788M   2% /run
root-overlay    7.1G  4.9G  2.3G  69% /
/dev/mmcblk0p1  7.1G  4.9G  2.3G  69% /host
/dev/loop1      380M  138M  219M  39% /var/log
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/tmp            3.9G     0  3.9G   0% /tmp/tmp.WpfOFZAt3p
```
After:
```
admin@str2-7050cx3-acs-12:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs …
```
> Use tmpfs for /var/log on Arista 7050CX3-32S

- src/systemd-sonic-generator/systemd-sonic-generator.c
Fix an issue that services do not start automatically on first boot and start only after hostcfgd enables them.
This is due to a bug in systemd-sonic-generator:
```
admin@arc-switch1004:~$ /usr/lib/systemd/system-generators/systemd-sonic-generator dir
Failed to open file /usr/lib/systemd/system/database.servcee
Error parsing targets for database.servcee
Error parsing database.servcee
Failed to open file /usr/lib/systemd/system/bgp.servcee
Error parsing targets for bgp.servcee
Error parsing bgp.servcee
Failed to open file /usr/lib/systemd/system/lldp.servcee
Error parsing targets for lldp.servcee
Error parsing lldp.servcee
Failed to open file /usr/lib/systemd/system/swss.servcee
Error parsing targets for swss.servcee
Error parsing …
```
> [systemd-sonic-generator] Fix overlapping strings being passed to strcpy/strcat

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/dns.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/dns.json
- src/sonic-yang-models/yang-models/sonic-dns.yang
Add SONiC YANG model for DNS to provide the possibility to configure static DNS entries in Config DB.
Added sonic-dns.yang file that contains the YANG model for the static DNS configuration.
This PR extends YANG model tests to cover DNS configuration.
To run the test sonic_yang_models-1.0-py3-none-any.whl should be compiled.
> [DNS] yang model for static DNS

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
There are 3 tasks in xcvrd: 
1.	main task, run a loop to recover missing SFP static information to DB every 1 minute
2.	SFP state task, a process which listens cable plug in/out event, insert SFP static information to DB while a cable is inserted
3.	SFP DOM update task, a thread which handles cable DOM information update every 1 minute
Let assume user replaces QSFP with QSFP-DD. There are two issues:
1.	Only SFP state task listens cable plug in/out event, main task and SFP DOM update task does not know SFP type has changed, they still “think” the SFP type is QSFP. So, main task and SFP DOM update task uses QSFP standard to parse QSFP-DD EEPROM which causes corrupted data.
2.	There is a race condition between main task and SFP state task. They both insert SFP static information to DB. …
> [202012] [Mellanox] Fix issue: SFP eeprom corrupted after replacing cable with different sfp type

- src/sonic-build-hooks/scripts/post_run_cleanup
Support to upgrade packages, do better cleanup after the build.
Remove the no use preference version control file after the build.
> [Build] Clean up the debian preference config file

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
sfp_event.py gets a PMPE message when a cable event is available. In PMPE message, there is no label port available. Current sfp_event.py is using sx_api_port_device_get to get 64 logical ports attributes, and find the label port from those 64 attributes. However, if there are more than 64 ports, sfp_event.py might not be able to find the label port and drop the PMPE message.
Don't use hardcoded 64, get  logical port number instead.
Manual test
> [Mellanox] Fix issue: cannot find label port for logical port when logical port number is larger than 64

- platform/mellanox/docker-syncd-mlnx/ecmp_calculator/ecmp_calc.py
- platform/mellanox/docker-syncd-mlnx/lib/port_utils.py
Add support for systems 4600/4600C/2201 that are using sonic interface names aligned to 4 instead of 8 (which is the max number of lanes per port).
Improve DB access calls, now we use Python library functions.
Use addition information taken from Config DB in order to create map from SDK logical index to sonic interface name.
Run ECMP calculator on 4600, 4600C and 2201 platforms.
> [Mellanox] [ECMP calculator] Add support for 4600/4600C/2201 platforms with different interface naming method

- device/arista/x86_64-arista_7050_qx32s/sensors.conf
- device/arista/x86_64-arista_7050cx3_32s/sensors.conf
- device/arista/x86_64-arista_7060_cx32s/sensors.conf
The sensors and sensord processes were reporting data on unused sensors.
This lead to `ALARM` messages or erroneous values that could be misinterpreted.
Ignore the affected sensors in the sensors.conf
Check that there are no longer `ALARM` messages from `sensord` in the syslog or in the output of `sensors`
Update sensors.conf to ignore sensors on Arista platforms
> [Arista] update sensors.conf to ignore sensors

- src/sonic-build-hooks/scripts/post_run_buildinfo
Support to upgrade packages, do better cleanup after the build.
Remove the no use preference version control file after the build.
> [Build][202211] Clean up the debian preference config file

- Makefile.work
- previously "make reset" was expecting user input from the terminal to do its job
- setting UNATTENDED to any non-zero string will allow "make reset" to run without interactive confirmation
This is the backport to 202211 from master (see PR https://github.com/sonic-net/sonic-buildimage/pull/12207)
When doing automated builds of SONiC images, we need to reset the working repositories between each build.
Adding an environment variable that is read by Makefile.work
running
`UNATTENDED=1 make reset
`
should make an automatic reset of all working directories
add an environment variable to run "make reset" unattended
N/A
N/A
> [202211] build: add an env var to run make reset unattended

- platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
- platform/mellanox/mlnx-platform-api/tests/test_eeprom.py
- platform/mellanox/mlnx-platform-api/tests/test_utils.py
On Mellanox platform, system EEPROM is a soft link provided by hw-management. There is chance that config-setup service accessing the EEPROM before hw-management creating it. It causes errors. The PR is aim to fix it. 
Waiting EEPROM creation in platform API up to 10 seconds.
Manual test
> [Mellanox] Check system eeprom existence in a retry manner

- files/build_templates/docker_image_ctl.j2
Fixe #12047.  After the c++ implementation of the sonic-db-cli,  sonic-db-cli PING command tries to initialize the global database for all instances database starting.  If all instance database-config.json are not ready yet. it will crash and generate core file.  PR https://github.com/sonic-net/sonic-swss-common/pull/701 only fix the crash and the process abortion.  With this PR, many core files are still generated: 
The following error are logged in the syslog
```
Dec 28 16:44:34.811893 ixre-cpm-chassis8 ERR sonic-db-cli: :- parseDatabaseConfig: Sonic database config file doesn't exist at /var/run/redis/sonic-db/../../redis0/sonic-db/database_config.json
Dec 28 16:44:34.812099 ixre-cpm-chassis8 ERR sonic-db-cli: :- initializeGlobalConfig: Sonic database config file syntax error >> Sonic …
```
> [Chassis][multiasic] Fix the sonic-db-cli core files issue on multiasic platform after the c++ implementation of sonic-db-cli

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
Add the Recirc ports to the INTERFACES table to make it routed intf. So that there is no need to configure IP address on Recirc interface.
Updated the minigraph parser to add the Ethernet-Rec0/1 to the INTERFACE table as below 
```
"INTERFACE": {
"v": {},
"Ethernet64|FC00::9/126": {},
"Ethernet64|10.0.0.4/31": {},
"Ethernet64": {}
},
```
Run the Everflow sonic-mgmt tests with VoQ chassis without the need to configure an IP address on Ethernet-Rec0 interface. everflow_per_interface is a known failure - to be fixed.
```
--------------------------------------------------------------------------- generated xml file: /home/jujoseph/CHASSIS/CHASSIS/sonic-mgmt-int/tests/logs/tr.xml ---------------------------------------------------------------------------- …
```
> Voq Chassis: Add the Recirc ports to the INTERFACES table to make it routed intf

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
Support to use the same snapshot for all platform builds.
There are multiple builds for the different platforms, such as vs, broadcom, mellanox, etc. The jobs to build each of the platform are not triggered at the same time, depended on if the agents are ready or not. The builds may use different snapshots, and use different version of a package, it is not a desired behavior.
Added another stage to prepare the snapshot version, make sure all the builds using the same snapshot.
Backport to 202205/202211 which support the snapshot based build.
Created a self pipeline to verify it, see https://dev.azure.com/mssonic/build/_build/results?buildId=222340&view=logs&j=cef3d8a9-152e-5193-620b-567dc18af272&t=b9010a6b-c6d1-5dc2-a48b-b94374f4e7e6
> [Ci] Support to use the same snapshot for all platform builds

- files/build_templates/sonic_debian_extension.j2
- platform/mellanox/mlnx-fw-upgrade.j2
Upgrade from old image always requires squashfs mount to get the next image FW binary. This can be avoided if we put FW binary under platform directory which is easily accessible after installation:
```
admin@r-spider-05:~$ ls /host/image-fw-new-loc.0-dirty-20230208.193534/platform/fw-SPC.mfa
/host/image-fw-new-loc.0-dirty-20230208.193534/platform/fw-SPC.mfa
admin@r-spider-05:~$ ls -al /tmp/image-fw-new-loc.0-dirty-20230208.193534-fs/etc/mlnx/fw-SPC.mfa
lrwxrwxrwx 1 root root 66 Feb  8 17:57 /tmp/image-fw-new-loc.0-dirty-20230208.193534-fs/etc/mlnx/fw-SPC.mfa -> /host/image-fw-new-loc.0-dirty-20230208.193534/platform/fw-SPC.mfa
```
202211 and above uses different squashfs compression type that 201911 kernel can not handle. Therefore, we …
> [202012][Mellanox] Place FW binaries under platform directory instead of squashfs

- files/build_templates/sonic_debian_extension.j2
- platform/mellanox/mlnx-fw-upgrade.j2
Fixes https://github.com/sonic-net/sonic-buildimage/issues/13568
Backport of https://github.com/sonic-net/sonic-buildimage/pull/13837
Upgrade from old image always requires squashfs mount to get the next image FW binary. This can be avoided if we put FW binary under platform directory which is easily accessible after installation:
```
admin@r-spider-05:~$ ls /host/image-fw-new-loc.0-dirty-20230208.193534/platform/fw-SPC.mfa
/host/image-fw-new-loc.0-dirty-20230208.193534/platform/fw-SPC.mfa
admin@r-spider-05:~$ ls -al /tmp/image-fw-new-loc.0-dirty-20230208.193534-fs/etc/mlnx/fw-SPC.mfa
lrwxrwxrwx 1 root root 66 Feb  8 17:57 /tmp/image-fw-new-loc.0-dirty-20230208.193534-fs/etc/mlnx/fw-SPC.mfa -> /host/image-fw-new-loc.0-dirty-20230208.193534/platform/fw-SPC.mfa
```
202211 and above uses …
> [202205][Mellanox] Place FW binaries under platform directory instead of squashfs

- files/build_templates/init_cfg.json.j2
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/system_defaults.json
Need to add the possibility to choose between dropping packets (using ACL) on ingress or egress in Dual ToR scenario
Add new attribute "mux_tunnel_ingress_acl" to SYSTEM_DEFAULTS table
check that new attribute exists in redis:
admin@sonic:~$ redis-cli -n 4
127.0.0.1:6379[4]> HGETALL SYSTEM_DEFAULTS|mux_tunnel_ingress_acl
1."state"
2."false"
> [Dual-ToR] add default value for ACL rule for mellanox platform (Standby ToR)

- device/celestica/x86_64-cel_seastone-r0/platform.json
Seastone does not have the psu fans' status led, need to reflect it in platform.json.
Set the psu fans status led available to false.
Verify it with platform_tests/api/test_psu_fans.py::TestPsuFans::test_set_fans_led case.
> [Seastone] add psu fans status led available config

- Makefile.work
- previously "make reset" was expecting user input from the terminal to do its job
- setting UNATTENDED to any non-zero string will allow "make reset" to run without interactive confirmation
This is the backport to 202205 from master (see PR https://github.com/sonic-net/sonic-buildimage/pull/12207)
When doing automated builds of SONiC images, we need to reset the working repositories between each build.
Adding an environment variable that is read by Makefile.work
running
`UNATTENDED=1 make reset
`
should make an automatic reset of all working directories
add an environment variable to run "make reset" unattended
N/A
N/A
> [202205] build: add an env var to run make reset unattended

- src/sonic-build-hooks/scripts/buildinfo_base.sh
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/13395
This fix resolves ownership configuration for `vcache`:
```
Step 24/40 : RUN pip3 install j2cli
---> Running in fcc39df62a98
chown: missing operand after '/sonic/target/vcache/docker-base-bullseye'
Try 'chown --help' for more information.
```
Originally the issue was introduced here: https://github.com/sonic-net/sonic-buildimage/pull/13287
* To fix ownership configuration
* Removed redundant stuff
* N/A
* N/A
* N/A
* N/A
```
'//||\\`
''``
```
> [buildsystem]: Fix error 'chown: missing operand after'

- scripts/populate_file_web_server.py
The flow of SONiC reproducible build assumes that web packages (retrieved by curl and wget) are located in a single web file.
server. Currently there is no way to easily download the packages from the various file servers where they are currently deployed.
In this change we offer a utility to download all relevant packages and upload them to a specific file server.
We implemented python script that parse the various version files (generated by SONIC reproducible build compilation) and identify all relevant packages.
Later the script downloads the file and then upload them to the destination server pointed by the user.
Script is running and was verified manually
Feature will be added to master only
sonic-net/SONiC#976
no changes in DB or object module
:)
> add script to upload packages to web server

- README.md
LGTM is deprecated. LGTM's badge doesn't work now.
Github code scanning shows alerts in Security tab. It doesn't have a badge.
Remove LGTM badge.
> Remove deprecated LGTM badge in README.md.

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
sfp_event.py gets a PMPE message when a cable event is available. In PMPE message, there is no label port available. Current sfp_event.py is using sx_api_port_device_get to get 64 logical ports attributes, and find the label port from those 64 attributes. However, if there are more than 64 ports, sfp_event.py might not be able to find the label port and drop the PMPE message.
Don't use hardcoded 64, get  logical port number instead.
Manual test
> [202012] [Mellanox] Fix issue: cannot find label port for logical port when logical port number is larger than 64

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vrf.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vrf.json
- src/sonic-yang-models/yang-models/sonic-vrf.yang
Added vni field in VRF Yang for VxLAN L3 VNI Support.
The VRF table schema as per EVPN HLD is below
https://github.com/sonic-net/SONiC/blob/master/doc/vxlan/EVPN/EVPN_VXLAN_HLD.md
Addresses Issue #13456
> Added vni field in VRF Yang for VxLAN L3 VNI Support #13456

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
- src/sonic-config-engine/tests/test_multinpu_cfggen.py
- src/sonic-yang-mgmt/tests/test_cfghelp.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/mclag.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan_sub_interface.json
- src/sonic-yang-models/yang-models/sonic-portchannel.yang
Fixes #11873.
When loading from minigraph, for port channels, don't create the members@ array in config_db in the PORTCHANNEL table. This is no longer needed or used.
In addition, when adding a port channel member from the CLI, that member doesn't get added into the members@ array, resulting in a bit of inconsistency. This gets rid of that inconsistency.
> Don't create the members@ array in config_db for PC when reading from minigraph

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/port_config.ini
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/port_config.ini
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/port_config.ini
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/port_config.ini
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/port_config.ini
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/port_config.ini
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/port_config.ini
- src/sonic-device-data/tests/permitted_list
To support 64 cores on arista skus. Fixes https://github.com/aristanetworks/sonic/issues/77
Remapped recycle ports to lowers core port ids and set appl_param_nof_ports_per_modid to 64.
Ran everflow tests on 202205 with these changes and verified IBGP sessions are up with max_cores set to 64 
- [ x ] 202205
>   sonic-buildimage Make changes to arista config.bcm files to support max cores as 64.

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/voq-sample-400g-port-config.ini
- src/sonic-config-engine/tests/voq-sample-masic-graph.xml
On SONiC VoQ chassis, the speed changes are done from 400G to 100G needs to be supported on 400G linecards. 
To enable this, along with speed change the port lanes need to be changed. This PR has the changes to update the port lanes when such speed change happens.
This PR is intended only for VoQ chassis linecards. These platforms today have 400g port with 8 serdes lines, and 100g will operate with 4 serdes lane. When the port speed changes from 400G to 100G the first 4 lanes will be used for 100G port.
Platforms which support 2x50g PAM4 or support 100G PAM4 serdes or other combinations are not handled in the PR.
Updated the port lanes when the port speed is changed from 400g to 100g.
UT and test on sonic chassis
- [x ] 202205
- [x ] 202211
> [chassis][voq] 400g to100g speed changes for chassis linecards

- files/Aboot/boot0.j2
Fix similar issue seen on #13739 but only for `DCS-7050CX3-32S`
Add a kernel parameter to tell libata to disable NCQ
The message `ata2.00: FORCE: horkage modified (noncq)` should appear on the `dmesg`.
Test results using: `fio --direct=1 --rw=randrw --bs=64k --ioengine=libaio --iodepth=64 --runtime=120 --numjobs=4`
with NCQ
```
READ: bw=26.1MiB/s (27.4MB/s), 26.1MiB/s-26.1MiB/s (27.4MB/s-27.4MB/s), io=3136MiB (3288MB), run=120053-120053msec
WRITE: bw=26.3MiB/s (27.6MB/s), 26.3MiB/s-26.3MiB/s (27.6MB/s-27.6MB/s), io=3161MiB (3315MB), run=120053-120053msec
```
without NCQ
```
READ: bw=22.0MiB/s (23.1MB/s), 22.0MiB/s-22.0MiB/s (23.1MB/s-23.1MB/s), io=2647MiB (2775MB), run=120069-120069msec
WRITE: bw=22.2MiB/s (23.3MB/s), 22.2MiB/s-22.2MiB/s (23.3MB/s-23.3MB/s), io=2665MiB (2795MB), …
```
> [Arista] Disable SSD NCQ on DCS-7050CX3-32S

- src/sonic-build-hooks/scripts/post_run_buildinfo
Why I did it
Support to upgrade packages, do better cleanup after the build.
How I did it
Remove the no use preference version control file after the build.
> [Build][202012] Remove deb pref 202012

- dockers/docker-base-stretch/Dockerfile.j2
Fix the docker-base-stretch build issue in nephos platform. see
https://dev.azure.com/mssonic/build/_build/results?buildId=223711&view=logs&j=1111c693-39b7-5a16-3aee-406c790b3886&t=c5703f10-3eba-5015-d19a-321c17c94619
```
Collecting supervisord-dependent-startup==1.4.0
Downloading https://files.pythonhosted.org/packages/0e/66/d386c3d2cf36846ded0b9f4999a6c59fd04fb15d768e59d3acfa039102bc/supervisord_dependent_startup-1.4.0-py2.py3-none-any.whl
Collecting toposort>=1.5 (from supervisord-dependent-startup==1.4.0)
Downloading https://files.pythonhosted.org/packages/8d/c3/44e51b42160145e4ebeb7d86ab93bd933fa9498f94e183ef8a47c6de8b2f/toposort-1.9.tar.gz
Complete output from command python setup.py egg_info:
File "<string>", line 1, in <module>
IOError: [Errno 2] …
```
> [Build][202012] Pin the toposort version to 1.7 in python2

- .azure-pipelines/official-build-cache.yml
It is affected by recent PR which changed pipeline teamplate reference.
pipeline failed.
> [ci] Fix SONiC cache build pipeline, which breaks for template change.

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vrf.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vrf.json
- src/sonic-yang-models/yang-models/sonic-vrf.yang
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/13735
Why I did it
Added vni field in VRF Yang for VxLAN L3 VNI Support.
The VRF table schema as per EVPN HLD is below
https://github.com/sonic-net/SONiC/blob/master/doc/vxlan/EVPN/EVPN_VXLAN_HLD.md
Addresses Issue #13456
> [202211]Added vni field in VRF Yang for VxLAN L3 VNI Support 

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/voq-sample-400g-port-config.ini
- src/sonic-config-engine/tests/voq-sample-masic-graph.xml
port of https://github.com/sonic-net/sonic-buildimage/pull/13935 to 202205 branch
On SONiC VoQ chassis, the speed changes are done from 400G to 100G needs to be supported on 400G linecards. 
To enable this, along with speed change the port lanes need to be changed. This PR has the changes to update the port lanes when such speed change happens.
This PR is intended only for VoQ chassis linecards. These platforms today have 400g port with 8 serdes lines, and 100g will operate with 4 serdes lane. When the port speed changes from 400G to 100G the first 4 lanes will be used for 100G port.
Platforms which support 2x50g PAM4 or support 100G PAM4 serdes or other combinations are not handled in the PR.
Updated the port lanes when the port speed is changed from 400g to 100g.
UT and test on sonic …
> [202205][chassis][voq] 400g to100g speed changes for chassis linecards

- src/system-health/health_checker/service_checker.py
On a supervisor card in a chassis, syncd/teamd/swss/lldp etc dockers are created for each Switch Fabric card. However, not all chassis would have all the switch fabric cards present. In this case, only dockers for Switch Fabrics present would be created.
system-health indicates errors in this scenario as it is expecting dockers for all Switch Fabrics (based on NUM_ASIC defined in asic.conf file).
system-health process error messages were also altered to indicate which container had the issue; multiple containers may run processes with the same name, which can result in identical system-health error messages, causing ambiguity.
**How I did it**
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/13497 into 202205 and resolve conflicts
**How to verify it** …
> system-health service_checker should check containers based on asic presence (cherry-pick #13497)

- dockers/docker-sonic-telemetry/critical_processes
Remove dialout as critical process as it is no longer used in prod. As part of future work, can remove dialout completely
Remove from critical process list
> Remove dialout as critical process

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
- src/sonic-frr-mgmt-framework/tests/test_config.py
Fix swsscommon psubscribe code break in frrcfgd
Fix frrcfgd psubscribe code break: https://github.com/sonic-net/sonic-buildimage/issues/13109
The code issue caused by API change when migrate from swsssdk to swsscommon
Fix frrcfgd code to use swsscommon psubscribe API.
Pass all UT.
Manually check fixed code work correctly.
Fix frrcfgd psubscribe code break: https://github.com/sonic-net/sonic-buildimage/issues/13109
> Fix swsscommon psubscribe code break in frrcfgd
