sonic-net/sonic-buildimage

device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py, platform/broadcom/sonic-platform-modules-cel/dx010/modules/dx010_cpld.c
Platform cases test_tx_disable, test_tx_disable_channel, test_power_override failed in dx010.
Add i2c access algorithm for CPLD i2c adapters.
Verify it with platform_tests/api/test_sfp.py::TestSfpApi test cases.
=> [Seastone] fix dx010 qsfp eeprom data write issue

files/build/versions/dockers/docker-config-engine-bullseye-sonic/versions-py3, files/build/versions/dockers/docker-config-engine-bullseye/versions-py3, files/build/versions/dockers/docker-config-engine-buster-sonic/versions-py3, files/build/versions/dockers/docker-config-engine-buster/versions-py3, files/build/versions/host-image/versions-py3, src/sonic-config-engine/setup.py
It is to fix the security alert CVE-2022-2309, see https://security-tracker.debian.org/tracker/CVE-2022-2309
The fix has already merged in master, See detail in PR https://github.com/sonic-net/sonic-buildimage/pull/11366
Upgrade version to 4.9.1
=> Bump lxml from 4.6.5 to 4.9.1 in /src/sonic-config-engine

platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py, platform/mellanox/mlnx-platform-api/tests/test_thermal.py
Backport sodimm sensor from PR https://github.com/sonic-net/sonic-buildimage/pull/12671
Depends on  https://github.com/sonic-net/sonic-buildimage/pull/13372 to be cherry picked to 202205.
Add sodimm sensor 
Add sodimm sensor 
Manual test
=> [Mellanox] [202205] Add sodimm sensor

src/sonic-config-engine/setup.py, src/system-health/setup.py
SONiC related packages shouldn't be intalled from Pypi.
It is security compliance requirement.
Check SONiC related packages when using setup.py.
=> Check SONiC dependencies before installation.

src/sonic-build-hooks/scripts/buildinfo_base.sh
[Build] Support to use loosen version when failed to install python packages
It is to fix the issue https://github.com/sonic-net/sonic-buildimage/issues/14012
Try to use the installation command without constraint
=> [Build] Support to use loosen version when failed to install python packages

dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/peer-group.conf.j2, src/sonic-bgpcfgd/tests/data/voq_chassis/peer-group.conf/result_all.conf, src/sonic-bgpcfgd/tests/data/voq_chassis/peer-group.conf/result_base.conf
Currently on a VOQ chassis, ipv6 iBGP neighbors do not have any route-map associated, due to typo in the route-map configuration. This results in route-map policies (like TSA) not getting applied to V6 iBGP neighbors, hence not isolating ipv6 iBGP sessions.
Fixed VOQ policy template file to associate the correct V6 route-map to iBGP v6 peer-group
In vtysh,
1.  'show run bgp' should display the correct route-map association
2.  After running TSA on a voq chassis linecard, advertised ipv6 routes to iBGP neighbors should have only the loopback ip address
=> Fix VOQ_CHASSIS_V6_PEER route-map config

src/sonic-config-engine/tests/test_cfggen.py
Fix a typo introduced as part of  #13403
=> [201911] Fix a minigraph typo

dockers/docker-sonic-mgmt/Dockerfile.j2
Add `shellcheck` Linux utility : to enable linter check on bash scripts
Add `mock` pip module: to enable running unit tests on sonic-mgmt container
Added shellcheck and mock
Verified these new packages by manually installting and using them for upgrade path tests.
=> Add shellcheck and mock modules for running unit and linter test

files/scripts/syncd.sh
Signed-off-by: anamehra <anamehra@cisco.com>
Vendor platform may require running platform specific pre-shutdown routine before shutting down the syncd process which runs the SAI and vendor sdk instance.
Added a platform script hook which will be executed if the plugin script is provided by the platform in device/<platform>/plugins/
Add platform plugin script and run systemctl stop syncd<>
=> Add support for platform syncd pre shutdown plugin

dockers/docker-ptf/Dockerfile.j2
We need to have "mergecap" application and use it in sonic-mgmt test infra code
Added  package "wireshark-common" into PTF docker Dockerfile.j2
Bu build PTF docker
Added package "wireshark-common" into PTF docker
It will allow us to have application called "mergecap" - which can merge multiple .pcap files into single .pcapng file and convert it to .pcap file
=> Added package "wireshark-common" into PTF docker

sonic-slave-jessie/Dockerfile.j2
docker.com's gpg key start to work from 2023-02-23. While debian.org's gpg key expired in 2022-11.
We used a walkaround for security checking for debian gpg keys. Now we need to exclude docker.com's gpg key.
Update docker.com's gpg key without faketime.
Update others' gpg key with faketime '2022-11'
=> [build] Fix issues caused by docker.com gpg key update.

azure-pipelines.yml
original ubuntu-20.04 agent pool has a node limit 35.
Use vmss agent pool to get higher node limit.
=> [ci] Migrate test jobs to vmss agent pool to increase node limit.

platform/mellanox/docker-syncd-mlnx/Dockerfile.j2
Some scripts on syncd require Python2 support.
Add Python2 to syncd docker
Run manually python scripts under Nvidia SDK debug to ensure they are working
=> [202205][Mellanox] Install python2 on syncd

src/sonic-host-services/scripts/determine-reboot-cause
Porting/cherry-pick PR https://github.com/sonic-net/sonic-host-services/pull/46
"show reboot-cause history" shows  empty history.  When the previous-reboot-cause has a broken symlink,  And rebooting the system will not be able to generate a new symlink of the new previous-reboot-cause. 
```
admin@sonic:~$ show reboot-cause history 
Name    Cause    Time    User    Comment
------  -------  ------  ------  ---------
```
Somehow, when the  symlink file /host/reboot-cause/previous-reboot-cause is broken (which its destination files doesn't exist in this case),  the current condition check "if os.path,exists(PREVIOUS_REBOOT_CAUSE_FILE)" will return False in determine-reboot-cause script.  Hence, the current previous-reboot-cause is not been removed and the recreation of the new …
=> [reboot-cause] Porting PR to fix a broken symlink of previous-reboot-cause file removal issue (sonic-host-services #46)

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
In sfplpm API, the number of logical ports is hardcoded as 64. When a system contains more port than this, the SDK APIs would fail with a syslog as below
```
Mar 7 03:53:58.105980 r-leopard-58 ERR syncd#SDK: [MGMT_LIB.ERR] Slot [0] Module [0] has logport [0x00010069] in enabled state
Mar 7 03:53:58.105980 r-leopard-58 ERR syncd#SDK: [SDK_MGMT_LIB.ERR] Failed in __sdk_mgmt_phy_module_pwr_attr_set, error: Internal Error
Mar 7 03:53:58.106118 r-leopard-58 ERR pmon#-c: Error occurred when setting power mode for SFP module 0, slot 0, error code 1
```
Remove the hardcoded value of 64. Obtained the number of logical ports from SDK
Manual testing
=> [Mellanox]Fix lpmode set when logical port is larger than 64

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfplpmset.py
This PR is to backport https://github.com/sonic-net/sonic-buildimage/pull/14138 to 202012.
In sfplpm API, the number of logical ports is hardcoded as 64. When a system contains more port than this, the SDK APIs would fail with a trace as below
```
Enabling low-power mode for port Ethernet0... Traceback (most recent call last):
File "/usr/share/sonic/platform/plugins/sfplpmset.py", line 167, in
set_lpmode(handle, cmd, sfp_module)
File "/usr/share/sonic/platform/plugins/sfplpmset.py", line 128, in set_lpmode
SX_MGMT_PHY_MOD_PWR_ATTR_PWR_MODE_E, SX_MGMT_PHY_MOD_PWR_MODE_LOW_E)
File "/usr/share/sonic/platform/plugins/sfplpmset.py", line 115, in pwr_attr_set
mgmt_phy_mod_pwr_attr_set(handle, module_id, attr_type, power_mode)
File "/usr/share/sonic/platform/plugins/sfplpmset.py", line 84, in …
```
=> [202012][mellanox]Fix lpmode set when logical port is larger than 64

platform/marvell-armhf/platform.conf
When using ```sonic-install set-default``` to switch the image from 202012 to 202205.  The system will be stuck at loading kernel while reboot.
The issue is caused by the kernal size related setting in uboot environment is smaller in the 202012 branch while they are larger in 202205 branch.  The "sonic-installer set-default" just changes the boot_next variable.  To fix this issue, we sync up the 202012 branch kernel related setting with the 202205 branch.  This PR is only applicable to 202012 branch.
1) Install the latest 202205 image .89 or latest and reboot
2) Install the 202012 image which contains this fix and reboot
3) using "sonic-installer set-default 202205 image and reboot
4) system should start without any issue.
=> [Nokia-7215][uboot] Fixed the uboot setting for sonic-installer set-default form 202012 to 202205 branch.

dockers/docker-platform-monitor/Dockerfile.j2
This is part of a corresponding change to the pcie daemon that enables it to verify PCI peripherals on a platform against a preconfigured YAML file, and enables the pcied daemon to call the system commands needed for PCI peripheral verification
Adding aforementioned libraries to the Dockerfile.j2 file
run 'which setpci' from the pmon docker - would show the path of the binary
Modified pmon's Dockerfile.j2 to include pciutils and libpci libraries.
**cherry-pick of SHA: 7de04504c9518d68aa00c304b7376fdff4e1d318**
=> [202012] Added libpci and pciutils to the pmon docker (#12684)

src/dhcpmon/src/dhcp_device.cpp, src/dhcpmon/src/dhcp_device.h, src/dhcpmon/src/dhcp_devman.cpp, src/dhcpmon/src/dhcp_devman.h, src/dhcpmon/src/dhcp_mon.cpp, src/dhcpmon/src/dhcp_mon.h, src/dhcpmon/src/main.cpp
Dhcpmon had incorrect RX count for server side packets. It does not raise any false alarms, but could miss catching server side packet count mismatch between snapshot and current counter.
Add debug mode which prints counter to syslog 
Due to dualtor inbound filter requirement, there are currently two filters, each for listening to rx / tx packets.
Originally, we opened up an rx/tx socket for each interface specified, which causes duplicate socket. Now we initialize the sockets only once. Both sockets are not binded to an interface, and we use vlan to interface mapping to filter packets. For inbound uplinks, we use a portchannel to interface mapping.
Previous dhcpmon counter before dual tor change:
[    Agg-Vlan1000- Current rx/tx] Discover:         1/        4, Offer:         1/        1, …
=> Update dhcpmon rx/tx packet filtering and fix server rx count

device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
To fix https://github.com/aristanetworks/sonic/issues/85
Remove unnecessary SAT ports
Speed change from 400-100g without any error.
- [x ] 202205
=> sonic-buildimage Remove unused SAT port from arista configs.

src/sonic-config-engine/minigraph.py
After the renaming of the asic_port_name in port_config.ini file (PR:  https://github.com/sonic-net/sonic-buildimage/pull/13053  ), the asic_ifname in port_config.ini is changed from '<port>-ASIC<asic_id>' to just port. Example: 'Eth0-ASIC0' to 'Eth0'.
However, with this change a config_db generated via config load_minigraph would cause the EVERFLOW and EVERFLOWV6 tables under ACL_TABLE to not have any of non-LAG front panel interfaces. This was causing the EVERFLOW suite to fail.
In parse_asic_external_neigbhors in minigraph.py there was a check that the asic_name.lower() (like asic0) is present in the port_alias_asic_map. However with -ASIC removed from the asic_ifname, the port_alias_asic_map would not have the asic_name and thus any non-LAG neighbor would not be included.
Fix was the …
=> [Chassis][EVERFLOW][ACL_ATBLE] Fix for everflow ACL_TABLE in config_db not having the routed ports when no -ASIC in the asic_port_name

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/portchannel.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json, src/sonic-yang-models/yang-models/sonic-portchannel.yang
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/14045
Fixing issue https://github.com/sonic-net/sonic-buildimage/issues/13983 Added Missing fields in sonic-portchannel yang model. "fallback" and "fast_rate" fields are present in configuration schema but not in yang model. This leads to traceback when yang is validated
sonic_yang(3):All Keys are not parsed in PORTCHANNEL dict_keys(['PortChannel100'])
sonic_yang(3):exceptionList:["'fast_rate'"]
sonic_yang(3):Data Loading Failed:All Keys are not parsed in PORTCHANNEL dict_keys(['PortChannel100'])
exceptionList:["'fast_rate'"]
Data Loading Failed
All Keys are not parsed in PORTCHANNEL
dict_keys(['PortChannel100'])
exceptionList:["'fast_rate'"]
ConfigMgmt Class creation failed
Failed to break out Port. Error: Failed to …
=> [202211][yang]Add missing fields in PortChannel yang model (#14045)

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/14138
- Why I did it
In sfplpm API, the number of logical ports is hardcoded as 64. When a system contains more port than this, the SDK APIs would fail with a syslog as below
Mar 7 03:53:58.105980 r-leopard-58 ERR syncd#SDK: [MGMT_LIB.ERR] Slot [0] Module [0] has logport [0x00010069] in enabled state
Mar 7 03:53:58.105980 r-leopard-58 ERR syncd#SDK: [SDK_MGMT_LIB.ERR] Failed in __sdk_mgmt_phy_module_pwr_attr_set, error: Internal Error
Mar 7 03:53:58.106118 r-leopard-58 ERR pmon#-c: Error occurred when setting power mode for SFP module 0, slot 0, error code 1
- How I did it 
Remove the hardcoded value of 64. Obtained the number of logical ports from SDK
- How to verify it 
Manual testing
=> [202012][Mellanox]Fix lpmode set when logical port is larger than 64 (#14138)

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/portchannel.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json, src/sonic-yang-models/yang-models/sonic-portchannel.yang
Porting fix https://github.com/sonic-net/sonic-buildimage/pull/14045 to 202205. 202205 doesn't have fast_rate and hence only fallback is updated in yang model
Added Missing fields in sonic-portchannel yang model.
"fallback" is present in configuration schema but not in yang model. This leads to traceback when yang is validated
Updated yang model
Added tests to verify
Part of the PR
=> [202205][yang]Add missing fields in PortChannel yang model 

platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_eeprom.py
To enhance pddf_eeprom.py to use caching and fix #13835 
- Utilising the in-built caching mechanism in the base class eeprom_base.py.
- Adding a cache file to store the eeprom data. 
By running 'decode-syseeprom' or 'show platform syseeprom' commands.
```
root@sonic:/home/admin# decode-syseeprom
TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 168
TLV Name             Code Len Value
-------------------- ---- --- -----
Manufacture Date     0x25  19 02/21/2019 02:52:19
Label Revision       0x27   4 R01A
Platform Name        0x28  27 x86_64-accton_as7816_64x-r0
ONIE Version         0x29  13 2018.05.00.08
Manufacturer         0x2B   6 Accton
Manufacture Country  0x2C   2 TW
Vendor Name          0x2D   8 Edgecore
Diag Version …
```
=> Fix issue: enhancing PDDF common eeprom APIs to use caching (#13835)

src/system-health/pytest.ini, src/system-health/scripts/healthd, src/system-health/tests/test_system_health.py
Healthd check system status every 60 seconds. However, running checker may take several seconds. Say checker takes X seconds, healthd takes (60 + X) seconds to finish one iteration. This implementation makes sonic-mgmt test case not so stable because the value X is hard to predict and different among different platforms. This PR introduces an interval 
compensation mechanism to healthd main loop.
Introduces an interval compensation mechanism to healthd main loop: healthd should wait (60 - X) seconds for next iteration
Manual test 
Unit test
=> [system-health] Make check interval more accurate

files/build_templates/docker_image_ctl.j2, files/image_config/ntp/ntp-config.sh, files/image_config/warmboot-finalizer/finalize-warmboot.sh, files/scripts/bgp.sh, files/scripts/service_mgmt.sh, files/scripts/swss.sh, files/scripts/syncd_common.sh, files/scripts/teamd.sh, src/sonic-py-common/sonic_py_common/device_info.py
Dedicated PR for 202205 branch similar to https://github.com/sonic-net/sonic-buildimage/pull/14238 (https://github.com/sonic-net/sonic-buildimage/pull/13484) as part of fast-reboot finalizer implementation.
This PR should come along with sonic-utilities PRs (https://github.com/sonic-net/sonic-utilities/pull/2724 - already merged and https://github.com/sonic-net/sonic-utilities/pull/2733) removing the timer usage from fast-reboot script, and as well with advancing sonic-sairedis pointer to point merged https://github.com/sonic-net/sonic-sairedis/pull/1217.
It will be followed by:
https://github.com/sonic-net/sonic-platform-daemons/pull/343
https://github.com/sonic-net/sonic-sairedis/pull/1217
This set of PRs solves the issue https://github.com/sonic-net/sonic-buildimage/issues/13251
Why I …
=> [202205] Fast reboot finalizer 202205

dockers/docker-lldp/lldpmgrd
Fixes https://github.com/sonic-net/sonic-buildimage/issues/14236
When a redis event quickly gets outdated during port breakout, error logs like this are seen 
```
Mar  8 01:43:26.011724 r-leopard-56 INFO ConfigMgmt: Write in DB: {'PORT': {'Ethernet64': {'admin_status': 'down'}, 'Ethernet68': {'admin_status': 'down'}}}
Mar  8 01:43:26.012565 r-leopard-56 INFO ConfigMgmt: Writing in Config DB
Mar  8 01:43:26.013468 r-leopard-56 INFO ConfigMgmt: Write in DB: {'PORT': {'Ethernet64': None, 'Ethernet68': None}, 'INTERFACE': None}
Mar  8 01:43:26.018095 r-leopard-56 NOTICE swss#portmgrd: :- doTask: Configure Ethernet64 admin status to down
Mar  8 01:43:26.018309 r-leopard-56 NOTICE swss#portmgrd: :- doTask: Delete Port: Ethernet64
Mar  8 01:43:26.018641 r-leopard-56 NOTICE lldp#lldpmgrd[32]: :- …
```
=> [lldpmgrd] Don't log error message for outdated event

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/chassis_module.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/chassis_module.json, src/sonic-yang-models/yang-models/sonic-chassis-module.yang
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/14007
Add yang model definition for CHASSIS_MODULE define and implemented for sonic chassis. HLD for this configuration is included in https://github.com/sonic-net/SONiC/blob/master/doc/pmon/pmon-chassis-design.md#configuration
Added yang model definition, unit tests, sample config and documentation for the table
Validated config tree generation using "pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/sonic-voq-inband-interface.yang"
Built the below python-wheels to validate unit tests and other changes 
1. target/python-wheels/bullseye/sonic_yang_mgmt-1.0-py3-none-any.whl 
2. target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl 
3. …
=> [202205] Add yang model definition for CHASSIS_MODULE table (#14007)

files/build_templates/sonic_debian_extension.j2, files/image_config/backend_acl/backend-acl.service, files/image_config/backend_acl/backend_acl.py
Change in sonic-net/sonic-utilities#2236 was done to load acls on storage backend device. During conversion, it was observed that some rules were getting skipped with the following error
Mar  7 19:33:53 sonic config-setup[999]: Running command: acl-loader update incremental /etc/sonic/backend_acl.json
Mar  7 19:33:53 sonic config-setup[999]: Running command: acl-loader update incremental /etc/sonic/backend_acl.json
Mar  7 19:33:54 sonic python3: :- operator(): Key '{SWITCH_CAPABILITY|switch}' unavailable in database '{STATE_DB}'
Mar  7 19:33:54 sonic python3: :- operator(): Key '{SWITCH_CAPABILITY|switch}' unavailable in database '{STATE_DB}'
Mar  7 19:33:54 sonic /acl-loader: Error processing rule 1: Rule action ACCEPT is not supported in table DATAACL, rule 1. Skipped.
Mar  7 19:33:54 …
=> [storage_backend] Add backend acl service 

build_debian.sh, files/build/versions/dockers/sonic-slave-bullseye/versions-py3, files/build/versions/dockers/sonic-slave-buster/versions-py2, files/build/versions/dockers/sonic-slave-buster/versions-py3, sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2
Fix some of vulnerability issue relative python packages #14269
Pillow: [CVE-2021-27921]
Wheel: [CVE-2022-40898]
lxml: [CVE-2022-2309]
=> [Security] Fix some of vulnerability issue relative python packages

dockers/docker-sonic-telemetry/telemetry.sh
Bug in script that was passing in null as log level value if missing from config_db
Added more robust conditional statement
1) Remove log_level from config db
2) config reload -y
3) telemetry should not crash
=> Fix telemetry.sh passing in null as log level value

src/sonic-yang-models/tests/yang_model_tests/tests/vxlan.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/vxlan.json, src/sonic-yang-models/yang-models/sonic-vxlan.yang
Update VxLAN yang model to include IPv6 source in VxLAN tunnel. The src_ip field can include both ipv4 as well as ipv6 address
Updated yang model.
Added UT to verify
=> [yang]Update VxLAN yang model to include IPv6 source in VxLAN tunnel

files/image_config/warmboot-finalizer/finalize-warmboot.sh
PART OF: https://github.com/sonic-net/sonic-utilities/pull/2744
To clear teamd timer when fast-reboot is finalized to prevent any further affect.
Deleted teamd timer from config-db in fast-reboot finalizer.
Verified manually that entry was deleted after fast-reboot was finailized.
=> [202205] Clear teamd-timer when finalizing fast-reboot

dockers/docker-base-bullseye/Dockerfile.j2, dockers/docker-base-buster/Dockerfile.j2, dockers/docker-config-engine-bullseye/Dockerfile.j2, dockers/docker-config-engine-buster/Dockerfile.j2, dockers/docker-database/Dockerfile.j2, dockers/docker-dhcp-relay/Dockerfile.j2, dockers/docker-fpm-frr/Dockerfile.j2, dockers/docker-lldp/Dockerfile.j2, dockers/docker-macsec/Dockerfile.j2, dockers/docker-mux/Dockerfile.j2, dockers/docker-nat/Dockerfile.j2, dockers/docker-orchagent/Dockerfile.j2, dockers/docker-platform-monitor/Dockerfile.j2, dockers/docker-router-advertiser/Dockerfile.j2, dockers/docker-sflow/Dockerfile.j2, dockers/docker-snmp/Dockerfile.j2, dockers/docker-sonic-mgmt-framework/Dockerfile.j2, dockers/docker-sonic-p4rt/Dockerfile.j2, dockers/docker-sonic-restapi/Dockerfile.j2, dockers/docker-sonic-telemetry/Dockerfile.j2, dockers/docker-swss-layer-bullseye/Dockerfile.j2, dockers/docker-swss-layer-buster/Dockerfile.j2, dockers/docker-teamd/Dockerfile.j2, dockers/dockerfile-macros.j2, platform/broadcom/docker-syncd-brcm-dnx/Dockerfile.j2, platform/broadcom/docker-syncd-brcm/Dockerfile.j2, platform/components/docker-gbsyncd-broncos/Dockerfile.j2, platform/components/docker-gbsyncd-credo/Dockerfile.j2, platform/vs/docker-sonic-vs/Dockerfile.j2, platform/vs/docker-syncd-vs/Dockerfile.j2
Remove the apt package lists (`/var/lib/apt/lists`) from the docker containers. This saves about 100MB.
Also, make a macro to clean up the apt and python cache that can then be used in all of the containers. This helps make the cleanup be consistent across all containers.
Build an image, and note that each docker gz file is less than 200MB (current images have most of the docker gz files above 200MB):
```
-rw-r--r-- 1 sarcot sarcot  95587809 Mar 21 18:58 target/docker-base-bullseye.gz
-rw-r--r-- 1 sarcot sarcot 121847481 Mar 21 19:00 target/docker-config-engine-bullseye.gz
-rw-r--r-- 1 sarcot sarcot 122039910 Mar 21 19:02 target/docker-database.gz
-rw-r--r-- 1 sarcot sarcot 124956680 Mar 21 19:08 target/docker-dhcp-relay.gz
-rw-r--r-- 1 sarcot sarcot 135939759 Mar 21 19:07 …
```
=> [202205] Remove apt package lists and make macro to clean up apt and python cache

device/common/profiles/th/6100/RDMA-CENTRIC/buffers_defaults_t0.j2, device/common/profiles/th/6100/RDMA-CENTRIC/buffers_defaults_t1.j2, device/common/profiles/th/gen/RDMA-CENTRIC/buffers_defaults_t0.j2, device/common/profiles/th/gen/RDMA-CENTRIC/buffers_defaults_t1.j2, src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml, src/sonic-config-engine/tests/sample_output/py2/buffers-dell6100.json, src/sonic-config-engine/tests/sample_output/py3/buffers-dell6100.json, src/sonic-config-engine/tests/test_j2files.py
For better accounting purposes, updating the ingress lossy traffic profile to use static threshold. This change is only intended for Th devices using RDMA-CENTRIC profiles
Update the buffer templates for Th devices in RDMA-CENTRIC folder to use the correct threshold
Verified the changes manually on a Th device.
Existing unit tests render Th template from the RDMA-CENTRIC folder. Updated the expected output to use the correct threshold
=> [qos] Update RDMA-CENTRIC lossy profile to use static threshold for Th devices

src/sonic-py-common/setup.py
Update sonic-py-common, add missing dependency to redis-dump-load.
This is manually cherry-pick PR for https://github.com/sonic-net/sonic-buildimage/pull/14347
After 202211, the redis-dump-load been patched by sonic, so can't cherry-pick master branch PR to 202211 branch.
The script sonic_db_dump_load.py in sonic-py-common is depends on redis-dump-load, however the dependency is missing.
Add redis-dump-load dependency.
Update sonic-py-common, add missing dependency to redis-dump-load.
=> [202211] Update sonic-py-common, add missing dependency to redis-dump-load.

src/sonic-py-common/setup.py
Update sonic-py-common, add missing dependency to redis-dump-load.
The script sonic_db_dump_load.py in sonic-py-common is depends on redis-dump-load, however the dependency is missing.
Add redis-dump-load dependency.
Update sonic-py-common, add missing dependency to redis-dump-load.
=> Update sonic-py-common, add missing dependency to redis-dump-load.

device/common/profiles/th/6100/RDMA-CENTRIC/buffers_defaults_t0.j2, device/common/profiles/th/6100/RDMA-CENTRIC/buffers_defaults_t1.j2, device/common/profiles/th/gen/RDMA-CENTRIC/buffers_defaults_t0.j2, device/common/profiles/th/gen/RDMA-CENTRIC/buffers_defaults_t1.j2, src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml, src/sonic-config-engine/tests/sample_output/py2/buffers-dell6100.json, src/sonic-config-engine/tests/sample_output/py3/buffers-dell6100.json, src/sonic-config-engine/tests/test_j2files.py
Backport #14372 to 202012
For better accounting purposes, updating the ingress lossy traffic profile to use static threshold. This change is only intended for Th devices using RDMA-CENTRIC profiles
Update the buffer templates for Th devices in RDMA-CENTRIC folder to use the correct threshold
=> [202012] [qos] Update RDMA-CENTRIC lossy profile to use static threshold for Th devices

device/common/profiles/th/6100/RDMA-CENTRIC/buffers_defaults_t0.j2, device/common/profiles/th/6100/RDMA-CENTRIC/buffers_defaults_t1.j2, device/common/profiles/th/gen/RDMA-CENTRIC/buffers_defaults_t0.j2, device/common/profiles/th/gen/RDMA-CENTRIC/buffers_defaults_t1.j2, src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/sample-dell-6100-t0-minigraph.xml, src/sonic-config-engine/tests/sample_output/py2/buffers-dell6100.json, src/sonic-config-engine/tests/sample_output/py3/buffers-dell6100.json, src/sonic-config-engine/tests/test_j2files.py
Backport #14372 to 202205 
For better accounting purposes, updating the ingress lossy traffic profile to use static threshold. This change is only intended for Th devices using RDMA-CENTRIC profiles
Update the buffer templates for Th devices in RDMA-CENTRIC folder to use the correct threshold
=> [202205] [qos] Update RDMA-CENTRIC lossy profile to use static threshold for Th devices

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, platform/mellanox/mlnx-platform-api/tests/test_sfp.py
=> [202205] [Mellanox] Fix issue: user must set admin down before toggling LPM

Makefile.work
This is a fix for c63e9fe59c32add15fb5a1876987
SLAVE_TAG should include all dependencies used for SLAVE_BASE_TAG
Take sources.list.* into account when calculate SLAVE_TAG
=> [Build] use sources.list for SLAVE_TAG

src/sonic-bgpcfgd/bgpcfgd/static_rt_timer.py
Change static route expiry timer max timeout value from 1800 to 172800.
To keep same value range as defined in sonic-restapi/sonic_api.yaml
apply change to bgpcfd, restart bgp container see if the value take action.
=> change static rt expiry timer max value

.azure-pipelines/azure-pipelines-build.yml
sonic-slave-stretch build failed for mmh3 version update to 3.10 on Mar 24.
Enable reproducible build for vhdx image.
=> [ci] Fix build issue for vs vhdx image.

sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
This should make sure that the openssl backend of curl is used, instead of the gnutls or nss backend, for consistency reasons.
=> Always use the openssl backend of curl

sonic-slave-buster/Dockerfile.j2
Change to use the default ssl lib openssl not nss
Backport https://github.com/sonic-net/sonic-buildimage/pull/14351.
=> [Build][202012] Change to use the default ssl lib openssl not nss

platform/vs/docker-sonic-vs/Dockerfile.j2
Fix the installation candidate not found issue when building  docker-sonic-vs
Need to run the command "apt-get update" to update the mirror indexes before installing the package gnupg
=> [Build] Fix the installation candidate not found issue when building  docker-sonic-vs

src/sonic-build-hooks/scripts/pre_run_buildinfo
We don't need to install rsync in every docker container if vcache is disabled.
Install rsync in pre_run_buildinfo script only if vcache is enabled.
=> [Build] don't install rsync if vcache is disabled

files/build_templates/arp_update_vars.j2, files/scripts/arp_update
arp_update should resolve the missing arp/ndp static route
entries. Added code to check for missing entries and try ping to
resolve the missing entry.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/14179
chassis-packet: missing arp entries for static routes causing high orchagent cpu usage
It is observed that some sonic-mgmt test case calls sonic-clear arp, which clears the static arp entries as well. Orchagent or arp_update process does not try to resolve the missing arp entries after clear.
arp_update should resolve the missing arp/ndp static route
entries. Added code to check for missing entries and try ping if any
found to resolve it.
1. After boot or config reload, check ipv4 and ipv4 neigh entries to make sure all static route entries are present
manual validation:
2. …
=> chassis-packet: resolve the missing static routes

platform/marvell-armhf/platform.conf
After sonic-install install a new image,  print_menu is set echo without any data.   No image info between ``` Hit any key to stop autoboot:  0 ``` and  ``` Start USB```
```
Board configuration detected:
Net:   
|  port  | Interface | PHY address  |
|--------|-----------|--------------|
No ethernet found.
Hit any key to stop autoboot:  0 
(Re)start USB...
USB0:   Port (usbActive) : 0    Interface (usbType = 2) : USB EHCI 1.00
scanning bus 0 for devices... 3 USB Device(s) found
scanning usb for storage devices... 0 Storage Device(s) found
```
The fw_setenv print_menu is missing the double quotes.  That causes the value is truncated.   Using double quotes to in the environment setting.
Install new image with this fix. And reboot the system. The following section should be shown:
```
No …
```
=> [marvell-armhf][uboot-setting] Fix the print menu for marvell-armhf print menu on Nokia-7215

dockers/docker-base/sources.list.armhf, sonic-slave-jessie/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2
[Build] Fix the jessie mirror removed issue.
Change to use the snapshot mirror http://packages.trafficmanager.net/snapshot.
Warning: The Jessie distribution is EOL, please avoid to use it if you can. And the snapshot mirror will be removed in near future as well.
=> [Build][201911] Fix the jessie mirror removed issue

files/Aboot/boot0.j2
Some products might experience an occasional IO failure in the communication between CPU and SSD. Based on some research it could be attributable to some device not handling ATA NCQ (Native Command Queue).
This issue currently affect 4 products:
DCS-7170-32C*
DCS-7170-64C
DCS-7060DX4-32
DCS-7260CX3-64
DCS-7050CX3-32S
This change disable NCQ on the affected drive for a small set of products.
When the fix is applied, these 2 patterns can be found in the dmesg. ata[0-9]+.00: FORCE: horkage modified (noncq)
NCQ (not used)
Test results using: `fio --direct=1 --rw=randrw --bs=64k --ioengine=libaio --iodepth=64 --runtime=120 --numjobs=4`
with NCQ (ata1.00: 61865984 sectors, multi 1: LBA48 NCQ (depth 32), AA)
```
READ: bw=33.9MiB/s (35.6MB/s), 33.9MiB/s-33.9MiB/s (35.6MB/s-35.6MB/s), io=4073MiB …
```
=> [201911][Arista] Disable ATA NCQ for a few products

src/sonic-bgpcfgd/bgpcfgd/static_rt_timer.py
Manual double commit to 202012 because of conflict.
Original PR:
https://github.com/sonic-net/sonic-buildimage/pull/14397
=> [cherry-pick]change static route expiry time from 1800 to 172800

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh
- To log SSD FW upgrade attempts in syslog.
- Adding logger.
=> [DellEMC] S6100 -  Adding logger to fetch SSD FW Upgrade status

files/build_templates/mux.service.j2, files/build_templates/sflow.service.j2, files/build_templates/snmp.timer
All these 3 services started after swss service, which used to start after interface-config service. But #13084 remove the time constraints for swss.
After that, these 3 services has the chance of start earlier when the inteface-config service is restarting the networking service, which could cause db connect request to fail.
Delay mux/sflow/snmp timer after the interface-config service.
PR test.
Config reload can repro the issue in 1-3 retries. With this change. config reload run 30+ iterations without hitting the issue.
=> Delay mux/sflow/snmp timer after interface-config service

files/image_config/sudoers/sudoers
Improve sudo cat command for RO user.
Manually cherry-pick for https://github.com/sonic-net/sonic-buildimage/pull/14428
RO user can use sudo command show none syslog files.
Improve sudo cat command for RO user.
Pass all UT.
Manually check fixed code work correctly.
Improve sudo cat command for RO user.
=> [201911] Improve sudo cat command for RO user. (#14428)

slave.mk
It is to fix the issue https://github.com/sonic-net/sonic-buildimage/issues/13773
It only has impact on the build triggered manually inside of the slave container. Developers can go to the slave container do a build, it will print a skippable error message complaining the variable not found.
Add the default value for variable SLAVE_DRI.
=> [Build] Fix the SLAVE_DRI not defined issue in the slave container issue

files/build_templates/buffers_config.j2, src/sonic-config-engine/tests/sample-arista-7060-t0-minigraph.xml, src/sonic-config-engine/tests/sample_output/py2/buffer-arista7060-t0.json, src/sonic-config-engine/tests/sample_output/py3/buffer-arista7060-t0.json, src/sonic-config-engine/tests/test_j2files.py
SONiC currently does not identify 'EdgeZoneAggregator' neighbor. As a result, the buffer profile attached to those interfaces uses the default cable length which could cause ingress packet drops due to insufficient headroom. Hence, there is a need to update the buffer templates to identify such neighbors and assign the same cable length as used by the T1.
Modified the buffer template to identify EdgeZoneAggregator as a neighbor device type and assign it the same cable length as a T1/leaf router. 
Unit tests pass, and manually checked on a 7260 to see the changes take effect. 
[Buffer] Added cable length config to buffer config template for EdgeZoneAggregator. Original PR to master: #14280
=> [202205][Buffer] Added cable length config to buffer config template for EdgeZoneAggregator

device/nokia/armhf-nokia_ixs7215_52x-r0/platform.json, platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
Add support for SFP refactor on Nokia-7215 Marvell armhf platform.
Platform: armhf-nokia_ixs7215_52x-r0
HwSKU: Nokia-7215
ASIC: marvell
Port Config: 48x1G + 4x10G (SFP+)
Modify sfp.py to support SFP refactor optoe driver and platform.json to facilitate proper OC test completion.
Build armhf target for Nokia-7215 and verify proper Xcvrd and SFP refactor operation.
[armhf][Nokia-7215]Add SFP refactor support for Nokia-7215 platform
=> [armhf][Nokia-7215]Add SFP refactor support for Nokia-7215 platform

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/port.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json, src/sonic-yang-models/yang-models/sonic-port.yang
Based on the [port breakout HLD](https://github.com/sonic-net/SONiC/pull/1290), we are now using `subport` instead of `channel` in the CONFIG_DB  PORT table to handle port breakout. The yang schema needs to be modified accordingly to handle the corresponding change.
The corresponding code changes have been merged through sonic-net/sonic-platform-daemons/pull/342 merged
Replaced `channel` with `subport` in the Yang model handling PORT table
The corresponding unit-tests passed for this change.
=> Modify yang model to handle subport in PORT table

dockers/docker-snmp/base_image_files/monit_snmp, rules/docker-snmp.mk
When CPU is busy, the sonic_ax_impl may not have sufficient speed to handle the notification message sent from REDIS.
Thus, the message will keep stacking in the memory space of sonic_ax_impl.
If the condition continues, the memory usage will keep increasing.
Add a monit file to check if the SNMP container where sonic_ax_impl resides in use more than 4GB memory.
If yes, restart the sonic_ax_impl process.
Run a lot of this command: `while true; do ret=$(redis-cli -n 0 set LLDP_ENTRY_TABLE:test1 test1); sleep 0.1; done;`
And check the memory used by sonic_ax_impl keeps increasing.
After a period, make sure the sonic_ax_impl is restarted when the memory usage reaches the 4GB threshold.
And verify the memory usage of sonic_ax_impl drops down from 4GB.
* Due to the psubscribe design of …
=> Add monit_snmp file to monitor memory usage

files/scripts/write_standby.py
At service start up time, there are chances that the networking service is being restarted by interface-config service. When that happens, write_standby could fail to make DB connections due to loopback interface is being reconfigured.
Force the db connector to use unix socket to avoid loopback reconfig timing window.
Run config reload test 20+ times and no issue encountered.
=> [write standby] force DB connections to use unix socket to connect

.azure-pipelines/azure-pipelines-image-template.yml
[Ci] Fix the no parallel jobs in some of the platforms issue
We observed some of the pipelines running more time than expected. The issue is the SONIC_BUILD_JOBS using the wrong value 1. It is caused by the runtime variable issue, there is additional single quota mark character added in the make command line.
```
make 'SONIC_BUILD_JOBS=$(nproc)' targe/xxxx
```
Need to change to
```
make SONIC_BUILD_JOBS=$(nproc) targe/xxxx
```
It is to improve the build performance for some of the platforms using the variable SONIC_BUILD_JOBS=1.
Good one vs: https://dev.azure.com/mssonic/build/_build/results?buildId=227986&view=logs&j=cef3d8a9-152e-5193-620b-567dc18af272&t=cf595088-5c84-5cf1-9d7e-03331f31d795
```
"SONIC_BUILD_JOBS"                : "8"
```
Bad one barefoot: …
=> [Ci] Fix the wrong SONIC_BUILD_JOBS build variable used issue in Azp

scripts/build_debian_base_system.sh
[Build] Support to use the snapshot mirror for debian base image
If the MIRROR_SNAPSHOT=n, then use the default mirror http://deb.debian.org/debian
If the MIRROR_SNAPSHOT=y, then use the snapshot mirror, for instance http://packages.trafficmanager.net/snapshot/debian/20230330T000330Z/.
```
+ scripts/build_debian_base_system.sh amd64 bullseye ./fsroot-vs
I: Target architecture can be executed
I: Retrieving InRelease 
I: Checking Release signature
I: Valid Release signature (key id A4285295FC7B1A81600062A9605C66F00D6C9793)
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://packages.trafficmanager.net/snapshot/debian/20230331T000125Z...
I: Retrieving libacl1 …
```
=> [Build] Support to use the snapshot mirror for debian base image

files/scripts/write_standby.py
Orchagent sometimes take additional time to execute Tunnel tasks. This cause write_standby script to error out and mux state machines are not initialized. It results in show mux status missing some ports in output.
```
Mar 13 20:36:52.337051 m64-tor-0-yy41 INFO systemd[1]: Starting MUX Cable Container...
Mar 13 20:37:52.480322 m64-tor-0-yy41 ERR write_standby: Timed out waiting for tunnel MuxTunnel0, mux state will not be written
Mar 13 20:37:58.983412 m64-tor-0-yy41 NOTICE swss#orchagent: :- doTask: Tunnel(s) added to ASIC_DB.
```
Increase timeout from 60s to 90s
Verified that mux state machine is initialized and show mux status has all needed ports in it.
Need it for 202205 as that is the release branch
=> Increase wait_for_tunnel() timeout to 90s

files/build_templates/docker_image_ctl.j2
Enhance the error message output mechanism during swss docker creating
Capture the output to stderr of `sonic-cfggen` and output it using `echo` to make sure the error message will be logged in syslog.
Manually test
=> Enhance the error message output mechanism when swss docker is created

files/image_config/ntp/ntp-config.sh, files/image_config/warmboot-finalizer/finalize-warmboot.sh, files/scripts/bgp.sh, files/scripts/service_mgmt.sh, files/scripts/swss.sh, files/scripts/syncd_common.sh, files/scripts/teamd.sh, src/sonic-py-common/sonic_py_common/device_info.py
This PR should come along with sonic-utilities PRs (https://github.com/sonic-net/sonic-utilities/pull/2621 https://github.com/sonic-net/sonic-utilities/pull/2734, already merged) removing the timer usage from fast-reboot script, and as well with advancing sonic-sairedis pointer to point merged https://github.com/sonic-net/sonic-sairedis/pull/1213.
This should be merged alongside with submodule update PR for sonic-utilities and sonic-sairedis with the above changes.
It will be followed by:
https://github.com/sonic-net/sonic-swss-common/pull/742
https://github.com/sonic-net/sonic-platform-daemons/pull/335
This set of PRs solves the issue https://github.com/sonic-net/sonic-buildimage/issues/13251
To solve an issue with upgrade with fast-reboot including FW upgrade which has been introduced …
=> Finalize fast-reboot in warmboot finalizer

Makefile.work
We don't use  snapshots of debian mirrors for sonic-slave containers even if MIRROR_SNAPSHOT is enabled.
Export MIRROR_SNAPSHOT in Makefile.work to generate sources.list for sonic-slave containers using debian snapshot mirror
=> [Build] use snapshots of debian mirrors for sonic-slave containers

.azure-pipelines/azure-pipelines-repd-build-variables.yml, Makefile.work
Enable the reproducible build for PR build for master branch
Fix the reproducible build variable display error in the slave container.
The below config is none, although the config is set and takes effect.
```
"SONIC_VERSION_CONTROL_COMPONENTS": "none"
``` 
Passing the variable through the slave container command line.
The variable has been passed to the slave container and the other docker container by a config file, it is only used to display the value during the build.
See https://dev.azure.com/mssonic/build/_build/results?buildId=247960&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=88f376cf-c35d-5783-0a48-9ad83a873284
```
"SONIC_VERSION_CONTROL_COMPONENTS": "deb,py2,py3,web,git,docker"
```
=> [Build] Fix the reproducible build variable display error in the slave container

files/build_templates/arp_update_vars.j2, files/scripts/arp_update
Reverts sonic-net/sonic-buildimage#14482
=> Revert "[action] [PR:14230] chassis-packet: resolve the missing static routes"

src/sonic-build-hooks/scripts/buildinfo_base.sh
refine reproducible build.
1. Fix reset map variable in bash.
2. Ignore empty web file md5sum value.
3. If web file didn't backup in azure storage, use file on web.
=> [build] Fix reproducible build version issue when failed to download web file

slave.mk
Fix #14081
By default DOCKER_BUILDKIT is enabled after docker version 23.0.0
So we need to disable it explicitly if SONIC_USE_DOCKER_BUILDKIT is not set.
Otherwise it will produce larger installable images.
set DOCKER_BUILDKIT=0 in slave.mk
=> [Build] disable DOCKER_BUILDKIT if SONIC_USE_DOCKER_BUILDKIT is not set

files/image_config/sudoers/sudoers
Improve sudo cat command for RO user.
Manually cherry-pick for https://github.com/sonic-net/sonic-buildimage/pull/14428
RO user can use sudo command show none syslog files.
Improve sudo cat command for RO user.
Pass all UT.
Manually check fixed code work correctly.
Improve sudo cat command for RO user.
=> [201811] Improve sudo cat command for RO user. (#14428)

Makefile.work, build_debian.sh, files/build_templates/sonic_version.yml.j2, platform/vs/sonic-version.mk, rules/config, slave.mk
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/14601, for code conflict.
Support to add SONiC OS Version in device info.
It will be used to display the version info in the SONiC command "show version". The version is used to do the FIPS certification. We do not do the FIPS certification on a specific release, but on the SONiC OS Version.
```
SONiC Software Version: SONiC.master-13812.218661-7d94c0c28
SONiC OS Version: 11
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
```
- Microsoft ADO **(number only)**: 17894593
=> [202211] Support to add SONiC OS Version in device info (#14601)

src/sonic-py-common/sonic_py_common/multi_asic.py
Fixes #14459.
In `show interface portchannel` and `show ip route`, backend port channels and routes were being displayed. This is due to changes in #13660. Fix these issues by switching to reading from PORTCHANNEL_MEMBERS table instead.
Replaced the `multi_asic.py` script at `/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py` with the fixed version. Verified that `show int portchannel` and `show ip route` no longer showed routes that used the backend port channels.
Current:
```
admin@xxxxx:~$ show ip route
Codes: K - kernel route, C - connected, S - static, R - RIP,
O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
F - PBR, f - OpenFabric,
> - selected route, * - FIB route, q - queued route, r - rejected route …
```
=> Fix backend port channels and routes being displayed

sonic-slave-jessie/Dockerfile.j2
Update golang version for telemetry build in sonic-slave-jessie to fix CVE-2021-33195, this PR will be merged into 201911 branch finally.
Go before 1.15.13 and 1.16.x before 1.16.5 has functions for DNS lookups that do not validate replies from DNS servers, and thus a return value may contain an unsafe injection (e.g., XSS) that does not conform to the RFC1035 format. Now in 201911 and 202012 branch we're using 1.14.2
- Microsoft ADO **(number only)**:17727291
Bump golang version into 1.15.15 which contains corresponding fix.
unit test to do sanity check.
=> Update golang version for telemetry build in sonic-slave-jessie to fix CVE-2021-33195

sonic-slave-buster/Dockerfile.j2
Update golang version for telemetry build in sonic-slave-buster to fix https://security-tracker.debian.org/tracker/CVE-2021-33195, this PR will be merged into 202012 branch finally.
Go before 1.15.13 and 1.16.x before 1.16.5 has functions for DNS lookups that do not validate replies from DNS servers, and thus a return value may contain an unsafe injection (e.g., XSS) that does not conform to the RFC1035 format. Now in 201911 and 202012 branch we're using 1.14.2
- Microsoft ADO **(number only)**:17727291
Bump golang version into 1.15.15 which contains corresponding fix.
unit test to do sanity check.
=> Update golang version for telemetry build in sonic-slave-buster to fix CVE-2021-33195

files/build_templates/sonic_debian_extension.j2, files/image_config/rasdaemon/rasdaemon.timer
rasdaemon is a tool to log hardware errors. It takes 100% CPU during boot for a few seconds. It impacts fast/warm boot by delaying control plane restoration for 5 sec on some platforms.
Improve fast/warm boot performance.
Added a rasdaemon timer.
Perform fast reboot control plane measurement and observe 5 sec improvement.
=> [image_config] add rasdaemon.timer

platform/broadcom/sai.mk
What I did:
Upgrade BRCM SAI to Debian package SAI 3.7.6.1-3.
Why I did:
Fix TX queue for control packets to use Queue 7 for Control packets on TD2 platforms.
How I verify:
Manual Verification by @prabhataravind
=> [201911] Updated Broadcom SAI3.7 Debian package.

sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
Cherry-pick of #14351.
This should make sure that the openssl backend of curl is used, instead of the gnutls or nss backend, for consistency reasons. If some application needs to be compiled and linked with curl, then it may link with the nss backend of curl instead, which doesn't support all of the features of the openssl backend (such as custom certificate verification code).
=> [202205] Always use the openssl backend of curl (#14351)

Makefile.work, scripts/prepare_docker_buildinfo.sh, src/sonic-build-hooks/scripts/buildinfo_base.sh
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/14557
1. Optimize the version control for Debian packages.
2. Fix sonic-slave-buster/sources.list.amd64 not found display issue, need to generate the file before running the shell command to evaluate the sonic image tag.
When using the snapshot mirror, it is not necessary to update the version file based on the base image. It will reduce the version dependency issue, when an image is not run when freezing the version.
Not to update the version file when snapshot mirror enabled.
=> [Build] Optimize the version control for Debian packages (#14557)

files/image_config/warmboot-finalizer/finalize-warmboot.sh
Part of https://github.com/sonic-net/sonic-utilities/pull/2760
Similar to https://github.com/sonic-net/sonic-buildimage/pull/14295
To clear teamd timer when fast-reboot is finalized to prevent any further affect.
Deleted teamd timer from config-db in fast-reboot finalizer.
config save call is moved to after clearing teamd-timer so it won't have any further affect as well.
Verified manually that entry was deleted after fast-reboot was finailized.
=> [Fast-boot] Clear teamd-timer when finalizing fast-reboot

dockers/docker-sflow/port_index_mapper.py
catch system error and log as warning level instead of
error level in case interface was already deleted
Why I did it
sflow process exited when failed to convert the interface index from interface name
How I did it
Added exception handling code and logged when OSError exception.
Recreated the bug scenario https://github.com/sonic-net/sonic-buildimage/issues/11437 and ensured that sflow process not exited.
Description for the changelog
catch system error and log as warning level instead of
error level in case interface was already deleted.
Logs
steps :
```
root@sonic:~# sudo config vlan member del 4094 PortChannel0001
root@sonic:~# sudo config vlan member del 4094 Ethernet2
root@sonic:~# sudo config vlan del 4094
root@sonic:~#
"WARNING sflow#port_index_mapper: no interface …
```
=> [sflow] Exception handling for if_nametoindex (#11437)

rules/config
This is done because when there is a default value, we mount to this path, and this creates this folder on the host.
Fix issue that running without overwriting SECURE_UPGRADE_DEV_SIGNING_KEY and SECURE_UPGRADE_DEV_SIGNING_CERT dummy folders are being created on the host.
Removed the default assignment to SECURE_UPGRADE_DEV_SIGNING_KEY and SECURE_UPGRADE_DEV_SIGNING_CERT
Build SONiC using your own prod script
=> Remove default value from SECURE_UPGRADE_DEV_SIGNING_KEY

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/neigh.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/neigh.json, src/sonic-yang-models/yang-models/sonic-neigh.yang
Yang model for NEIGH table was missing
Fixed https://github.com/sonic-net/sonic-buildimage/issues/13971
added sonic-neigh.yang model
make buildimage
Adding NEIGH yang model
(https://github.com/sonic-net/sonic-buildimage/blob/b721ff87b976a6a38bdd65443ea3bc686014e783/src/sonic-yang-models/doc/Configuration.md#neigh)
=> [yang] add NEIGH yang model

src/sonic-host-services-data/debian/sonic-host-services-data.sonic-hostservice.service
To start host services only when needed. Otherwise it creates additional load on system at boot.
Changed WantedBy directive
Boot the system and verify host service starts when mgmt-framework and telemetry start.
=> [sonic-host-services] start host service on mgmt-framework/telemetry

src/bash/patches/0001-Add-plugin-support-to-bash.patch
Fix per-command authorization failed issue when a command with wildcard match more than hundred files.
When user enable TACACS per-command authorization, and run a command with wildcard , if the command match more than hundreds of files, the per-command authorization will failed with following message:
*** authorize failed by TACACS+ with given arguments, not executing
The root cause of this issue is because bash will match files with wildcard and replace with wildcard args with matched files. when there are too many files, TACACS plugin will generate a big authorization request, which will be reject by server side. 
- Microsoft ADO **(number only)**: 18074861
Fix bash patch file, use original user inputs as authorization parameters.
Pass all UT.
Create new UT to validate the TACACS …
=> Fix per-command authorization failed issue when a command with wildcard match more than hundred files.

src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/snmp.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/snmp.json, src/sonic-yang-models/yang-models/sonic-snmp.yang
Add YANG model for SNMP_USER table defined in the document: https://github.com/sonic-net/SONiC/blob/master/doc/snmp/snmp-schema-addition.md
Passed unit-test
=> [yang-models]: Add YANG model for SNMP_USER table

rules/config
SONiC master image needs GNMI native write.
Update rules/config to enable.
Run end2end test.
=> Enable GNMI native write by default

rules/docker-telemetry.mk
Remove dbus when telemetry does not use it.
- Microsoft ADO **(number only)**: 17852550
Use INCLUDE_SYSTEM_GNMI to determine if telemetry needs dbus.
Build image and check telemetry container.
=> If gnmi is included, remove dbus from telemetry

dockers/docker-macsec/cli-plugin-tests/config_db.json, dockers/docker-macsec/cli-plugin-tests/test_show_macsec.py, dockers/docker-macsec/cli/show/plugins/show_macsec.py
This PR is to add the following 
1. Add a new options "--profile" to the show macsec command, to show all profiles in device
2. Update the currentl show macsec command, to show profile in each interface o/p. This will tell which macsec profile the interface is attached to.
update the show cli plugin in macsec docker 
The following is the test o/p 
```
admin@str2--lc1-2:~$ show macsec 
Last cached time was 2023-02-22 19:48:18.106529
MACsec port(Ethernet184)
---------------------  ---------------
cipher_suite           GCM-AES-XPN-256
enable                 true
enable_encrypt         true
enable_protect         true
enable_replay_protect  false
profile                macsec_profile
replay_window          0
send_sci               true
---------------------  ---------------
MACsec Egress SC …
```
=> show macsec:  add --profile option, include profile name in show command output

src/system-health/health_checker/sysmonitor.py, src/system-health/tests/test_system_health.py
systemd stop event on service with timers can sometime delete the state_db entry for the corresponding service.
Note: This won't be observed on the latest master label since the dependency on timer was removed with the recent config reload enhancement. However, it is better to have the fix since there might be some systemd services added to system health daemon in the future which may contain timers
```
root@qa-eth-vt01-4-3700c:/home/admin# systemctl stop snmp
root@qa-eth-vt01-4-3700c:/home/admin# show system-health sysready-status 
System is not ready - one or more services are not up
Service-Name            Service-Status    App-Ready-Status    Down-Reason
----------------------  ----------------  ------------------  -------------
<Truncated>
ssh                     OK                OK …
```
=> [Sys Mon] Fix the service entry delete in state_db because of timer job

device/arista/x86_64-arista_7800_sup/chassisdb.conf
Today at most 128 LAGs are supported. This is not sufficient if there are many LAGs with just few ports.
Increase LAG Ids to 1024 for DNX device.
=> Increase LAG Ids to 1024

dockers/docker-fpm-frr/TS, dockers/docker-fpm-frr/base_image_files/TSA, dockers/docker-fpm-frr/base_image_files/TSB, dockers/docker-fpm-frr/base_image_files/TSC, files/image_config/config-setup/config-setup, src/sonic-bgpcfgd/bgpcfgd/managers_device_global.py
Support for SONIC chassis isolation using TSA and un-isolation using TSB from supervisor module
- Microsoft ADO **(number only)**: 17826134
When TSA is run on the supervisor, it triggers TSA on each of the linecards using the secure rexec infrastructure introduced in https://github.com/sonic-net/sonic-utilities/pull/2701. User password is requested to allow secure login to linecards through ssh, before execution of TSA/TSB on the linecards
TSA of the chassis withdraws routes from all the external BGP neighbors on each linecard, in order to isolate the entire chassis. No route withdrawal is done from the internal BGP sessions between the linecards to prevent transient drops during internal route deletion.  With these changes, complete isolation of a single linecard using TSA will not be …
=> Changes to support TSA/TSB from supervisor of SONIC chassis

src/sonic-yang-models/tests/yang_model_tests/tests/acl.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json, src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Add support for a new ACL table type L3V4V6 that supports both v4 and v6 Match types.
HLD: sonic-net/SONiC#1267
Added unit-tests:
```
Test 890: ACL_TABLE Validate type L3V4V6.
```
NA (new feature)
Add support for a new ACL table type L3V4V6 that supports both v4 and v6 Match types.
=> Support a new ACL table type called L3V4V6.

README.md
The previous link to instructions for moving the docker directory are outdated.
=> [README] Update link for moving docker directory

platform/mellanox/docker-syncd-mlnx/ecmp_calculator/ecmp_calc.py, platform/mellanox/docker-syncd-mlnx/ecmp_calculator/ecmp_calc_sdk.py, platform/mellanox/docker-syncd-mlnx/ecmp_calculator/packet_scheme.py, platform/mellanox/docker-syncd-mlnx/lib/port_utils.py
Add NVIDIA Copyright header to NVIDIA files added lately
Add NVIDIA Copyright header for the relevant files
N/A (only commented text was added).
=> [Nvidia] Add copyright header to ECMP calculator files

device/mellanox/x86_64-nvidia_sn5600-r0/pcie.yaml, device/mellanox/x86_64-nvidia_sn5600-r0/sensors.conf
Update the sensors.conf and pcie.yaml according to the real hardware.
Update the sensors.conf and pcie.yaml 
run relevant sonic-mgmt test cases.
=> [Mellanox] Update SN5600 sensors.conf and pcie.yaml files

src/sonic-host-services/scripts/caclmgrd, src/sonic-host-services/tests/caclmgrd/cacl_external_client_acl_test.py, src/sonic-host-services/tests/caclmgrd/caclmgrd_chassis_midplane_test.py, src/sonic-host-services/tests/caclmgrd/test_chassis_midplane_vectors.py
1. Allow traffic with source and destination as chassis eth1-midplane ip. Needed for Supervisor Redis-db connection (Redis packet has source and destination ip as eth1-midpane) after we load acl.json that has catch-all drop rule. Changes are generic and not specific to supervisor and applies on LC also.
2. Made multi_asic_ns_to_host_fwd as False for ACL service for External Client. This flag is needed for service SSH and SNMP where traffic can come in namespace over front-panel ports and we need to send the traffic in host where corresponding docker/service are running. There is no use-case of External client service for multi-asic as of now. Having flag as True creates failure when we try to load acl.json.
How I verify:
Manual Verification
UT updated accordingly.
=> [202205] Added changes in caclmgrd for chassis

rules/functions
To be able to see how much time was consumed to build a specific target.
A newly added code does those things:
* Print build start time for target
* Print build end time for target
* Print elapsed time for target
* Add a macro to record the time
* Add macros to print end time and elapsed time
Just build an image and check any *.log file
=> [Profiler] Add ability to print elapsed build time for target packages

platform/marvell-armhf/sonic-platform-nokia/7215/service/fstrim.timer/timer-override.conf, platform/marvell-armhf/sonic-platform-nokia/debian/sonic-platform-nokia-7215.install
Using override.conf, we modify the fstrim.timer service.
For armhf, Nokia-7215 platform, we modify fstrim.timer to run daily
instead of weekly.  This is required because the size of the SSD on
this platform is 16GB, which on average is nearly 10 times smaller than
most other sonic platforms.  With smaller disk and the ever increasing
level of logging done by sonic, this change is required to prevent
the SSD from entering a read-only state due to inadequate free blocks.
Required to prevent the SSD from entering a read-only state due to inadequate free blocks
Verified that override works.
```
admin@sonic-amazon:~$ sudo systemctl status fstrim.timer 
\u25cf fstrim.timer - Discard unused blocks daily
Loaded: loaded (/lib/systemd/system/fstrim.timer; enabled; …
```
=> [armhf][Nokia-7215] changes fstrim.timer to daily

src/sonic-build-hooks/scripts/buildinfo_base.sh
refine reproducible build.
cherry-pick (#14587 )
Fix reset map variable in bash.
Ignore empty web file md5sum value.
If web file didn't backup in azure storage, use file on web. How to verify i
=> [build] Fix reproducible build version issue when failed to download web file (#14587)

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/interface.json, src/sonic-yang-models/tests/yang_model_tests/tests/portchannel.json, src/sonic-yang-models/tests/yang_model_tests/tests/vlan.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/interface.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan.json, src/sonic-yang-models/yang-models/sonic-interface.yang, src/sonic-yang-models/yang-models/sonic-portchannel.yang, src/sonic-yang-models/yang-models/sonic-vlan.yang
SONiC Yang model support for IPv6 link local
What I did
Created SONiC Yang model for IPv6 link local
How I did it
Defined Yang models for IPv6 link local based on https://github.com/sonic-net/SONiC/blob/master/doc/ipv6/ipv6_link_local.md
Added enable test case.
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>
=> SONiC Yang model support for IPv6 link local

dockers/docker-fpm-frr/frr/bgpd/templates/internal/peer-group.conf.j2, src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/param_chasiss_packet.json, src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chasiss_packet.conf
What I did:
In FRR command `update source <interface-name>` is not at address-family level. Because of this 
internal peer route-map for ipv6 were getting applied to ipv4 address family. As a result
TSA over iBGP for Ipv6 was not getting applied.
How I verify:
Manual Verification of TSA over both ipv4 and ipv6 after fix works fine.
Updated UT for this.
Added sonic-mgmt test gap: https://github.com/sonic-net/sonic-mgmt/issues/8170
=> Fixed the internal peer route-map policy

slave.mk
Manual double commit of #14698
=> [build] SONIC_ONLINE_DEBS no longer overwrites local build outputs

src/system-health/health_checker/hardware_checker.py, src/system-health/tests/test_system_health.py
Add fan direction check to system health, all fans should be in the same direction
Add fan direction check to system health, all fans should be in the same direction
Manual test
Unit test
Added sonic-mgmt test case to verify
=> [system-health] Add fan direction check for system health

platform/mellanox/docker-syncd-mlnx/supervisord.conf.j2
To improve ASAN backtrace output when the call stack contains a code that is not compiled with -fno-omit-frame-pointer.
Added fast_unwind_on_malloc=0 to the ASAN_OPTIONS
Build and test docker-syncd-mlnx.gz with ENABLE_ASAN=y
=> [Mellanox][asan] disable fast_unwind_on_malloc for mlnx syncd

platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py, platform/mellanox/mlnx-platform-api/sonic_platform/led.py, platform/mellanox/mlnx-platform-api/tests/test_led.py
Currently, LED sysfs path is hardcoded. We will need change LED code if new LED color is supported for new platforms. This PR is aimed to improve this. By this PR, LED sysfs path is deduced from LED capability file.
Improve LED management on Nvidia platform:
- get LED capability from capability file and deduce sysfs name according to the capability
Unit test
Manual test
=> [Mellanox] get LED capability from capability file

Makefile.work, rules/config
Backport PR https://github.com/sonic-net/sonic-buildimage/pull/14907 to 202205 branch
In order to reduce sonic build time, there is an option to acquire sonic slave docker(s) from artifact server (reduce sonic make configure time).
Current implementation supports only convention of: 
<REGISTRY_SERVER>:<REGISTRY_PORT>/<SLAVE_BASE_IMAGE>:<SLAVE_BASE_TAG>
In case the SLAVE_BASE_IMAGE appear in internal path inside the server, the convention should be like that:
<REGISTRY_SERVER>:<REGISTRY_PORT><REGISTRY_SERVER_PATH>/<SLAVE_BASE_IMAGE>:<SLAVE_BASE_TAG>
When REGISTRY_SERVER_PATH (that is set on rules/config) will have to start with "/".
If REGISTRY_SERVER_PATH will not be set, the behavior will remain the same it works today.
Add ability to set …
=> [202205] Support pulling sonic-slave-docker image from path at REGISTRY_SERVER

files/Aboot/boot0.j2, files/image_config/config-setup/config-setup, files/image_config/platform/rc.local, files/image_config/secureboot/allowlist_paths.conf
This PR is to handle the override minigraph config by golden_config_db.json file if it is present in the backup location.
=> Add override_config to load_minigraph in config-setup service

src/sonic-py-common/sonic_py_common/device_info.py
replace yaml.load to yaml.safe_load because yaml.safe_load is more secure
- Microsoft ADO **(number only)**: 15022050
Verified in DUT 201911 which yaml version < 5.1
=> [sonic_py_common] replace yaml.load to yaml.safe_load

azure-pipelines.yml
1. Remove 'kvmtest-t0' and 'kvmtest-t1-lag' test jobs since all the test jobs are required (continueOnError: false) already, and will only enable one of classical and testbedV2 tests, no need to do an unnecessary 'or' compute test job.
2. Change classic multi-asic and t0-sonic test jobs as required (continueOnError: false) following current testbedV2's logic.
- Microsoft ADO **(number only)**: 21199599
=> Refine test job definition and assert logic

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/interface.json, src/sonic-yang-models/tests/yang_model_tests/tests/portchannel.json, src/sonic-yang-models/tests/yang_model_tests/tests/vlan.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/interface.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan.json, src/sonic-yang-models/yang-models/sonic-interface.yang, src/sonic-yang-models/yang-models/sonic-portchannel.yang, src/sonic-yang-models/yang-models/sonic-vlan.yang
This is backport of https://github.com/sonic-net/sonic-buildimage/pull/14757 
SONiC Yang model support for IPv6 link local
What I did
Created SONiC Yang model for IPv6 link local
How I did it
Defined Yang models for IPv6 link local based on https://github.com/sonic-net/SONiC/blob/master/doc/ipv6/ipv6_link_local.md
Added enable test case.
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>
=> SONiC Yang model support for IPv6 link local (#14757)

platform/mellanox/mlnx-platform-api/sonic_platform/fan.py, platform/mellanox/mlnx-platform-api/sonic_platform/fan_drawer.py, platform/mellanox/mlnx-platform-api/tests/test_fan_api.py
Add PSU fan direction support
Implement fan.get_direction for PSU fan
Manual test
Unit test
```
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/platform/mellanox/mlnx-platform-api, configfile: pytest.ini
plugins: pyfakefs-5.1.0, cov-2.10.1
collecting ... collected 109 items
tests/test_chassis.py::TestChassis::test_psu PASSED                      [  0%]
tests/test_chassis.py::TestChassis::test_fan PASSED                      [  1%]
tests/test_chassis.py::TestChassis::test_sfp PASSED                      [  2%]
tests/test_chassis.py::TestChassis::test_change_event PASSED             [  3%] …
```
=> [Mellanox] add PSU fan direction support

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/sonic_platform/led.py, platform/mellanox/mlnx-platform-api/tests/test_led.py
Signed-off-by: David Xia <daxia@nvidia.com>
As a LED indicator to help user to find switch location in the lab, UID LED is a useful LED in Mellanox switch.
I add a new member _led_uid in Mellanox/Chassis.py, and extend Mellanox/led.py to support blue color.
Relevant platform-common PR https://github.com/sonic-net/sonic-platform-common/pull/369
Add unit test cases in test.py, and do manual test including turn-on/off/show uid led.
=> [Mellanox] Support UID LED in platform API

build_debian.sh, files/apt/sources.list, files/image_config/apt/sources.list.d/debian_archive_trafficmanager_net_debian.list, sonic-slave-stretch/Dockerfile, src/hiredis/Makefile, src/mpdecimal/Makefile
[Build] Fix the stretch mirror removed issue.
- Microsoft ADO **(number only)**:  22627384
Change to use the snapshot mirror http://packages.trafficmanager.net/snapshot.
=> [Build][201811] Fix the stretch mirror removed issue

files/build_templates/per_namespace/swss.service.j2, files/build_templates/per_namespace/syncd.service.j2
This reverts https://github.com/sonic-net/sonic-buildimage/pull/13084
Resolves https://github.com/sonic-net/sonic-buildimage/issues/15076
* To stabilize warm/fast reboot
* Reverted changes
* Run warm/fast reboot
* N/A
* N/A
```
'//||\\`
''``
```
=> [202211] Revert: "[swss/syncd] remove dependency on interfaces-config.service"

files/scripts/arp_update
To resolve NEIGH table entries present in CONFIG_DB. Without this change arp/ndp entries which we wish to resolve, and configured via CONFIG_DB are not resolved.
Modify arp_update script to take NEIGH entries from config db for resolution. For failed entries trigger a ping6/ping command for resolution
Configure NEIGH table in config_db and check if it gets resolved.
=> [master] Resolve neighbors from config_db

platform/broadcom/docker-syncd-brcm-dnx-rpc/Dockerfile.j2
ptf_nn_agent failed to start in dnx rpc syncd because module afpacket was not installed.
Please see issue https://github.com/sonic-net/sonic-mgmt/issues/7822
Add  downloading ptf afpacket module in docker file.
Verified that ptf_nn_agent was started successfully in dnx rpc syncd with the change.
- [ x] 202205
=> Install ptf afpacket module required by ptf_nn_agent.

platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install, platform/broadcom/sonic-platform-modules-dell/s6100/scripts/check-getty.sh, platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_serial_getty_monitor
This is manually cherry-pick PR for https://github.com/sonic-net/sonic-buildimage/pull/14402
[S6100] Improve S6100 serial-getty monitor, wait and re-check when getty not running to avoid false alert. 
On S6100, the serial-getty service some time can't auto-restart by systemd. So there is a monit unit to check serial-getty service status and restart it.
However, this monit will report false alert, because in most case when serial-getty not running, systemd can restart it successfully.
To avoid the false alert, improve the monitor to wait and re-check.
Steps to reproduce this issue:
1. User login to device via console, and keep the connection.
2. User login to device via SSH, check the serial-getty@ttyS1.service service, it's running.
3. Run 'monit reload' from SSH connection.
4. Check …
=> [202205] [S6100] Improve S6100 serial-getty monitor, wait and re-check when getty not running to avoid false alert. (#14402)

files/Aboot/boot0.j2, files/image_config/config-setup/config-setup, files/image_config/platform/rc.local, files/image_config/secureboot/allowlist_paths.conf
Merge PR  (#14834) into 202205 branch
- Microsoft ADO **(number only)**: 23030834
=> [202205] Add override_config to load_minigraph in config-setup service

files/scripts/arp_update
To resolve NEIGH table entries present in CONFIG_DB. Without this change arp/ndp entries which we wish to resolve, and configured via CONFIG_DB are not resolved. 
Modify arp_update script to take NEIGH entries from config db for resolution. For failed entries trigger a ping6/ping command for resolution
Configure NEIGH table in config_db and check if it gets resolved.
202012
=> [202012] Resolve neighbors from config_db

build_debian.sh, dockers/docker-base-stretch/sources.list, dockers/docker-base-stretch/sources.list.arm64, dockers/docker-base-stretch/sources.list.armhf, dockers/docker-base/sources.list, dockers/docker-ptf/Dockerfile.j2, dockers/docker-ptf/no-check-valid-until, dockers/docker-ptf/sources.list.amd64, dockers/docker-ptf/sources.list.arm64, dockers/docker-ptf/sources.list.armhf, files/apt/sources.list.amd64, files/apt/sources.list.arm64, files/apt/sources.list.armhf, files/image_config/apt/sources.list.d/amd64/debian_archive_trafficmanager_net_debian.list, files/image_config/apt/sources.list.d/arm64/debian_mirror_arm64.list, files/image_config/apt/sources.list.d/armhf/debian_mirror_armhf.list, sonic-slave-stretch/Dockerfile.j2, src/hiredis/Makefile, src/iptables/Makefile, src/kdump-tools/Makefile, src/lldpd/Makefile, src/lm-sensors/Makefile, src/mpdecimal/Makefile, src/redis/Makefile
[Build] Fix the stretch/jessie mirror removed issue.
- Microsoft ADO **(number only)**:  22627384
Change to use the snapshot mirror http://packages.trafficmanager.net/snapshot.
=> [Build][201911] Fix the stretch/jessie mirror removed issue

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json, src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Extend device_metadata yang model.
- Microsoft ADO **(number only)**: 22912178
Add rack_mgmt_map field in yang model.
Build sonic_yang_models packages.
=> [yang] Extend device_metadata yang model with rack_mgmt_map

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json, src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-buildimage/pull/15109
Extend device_metadata yang model.
- Microsoft ADO **(number only)**: 22912178
Add rack_mgmt_map field in yang model.
Build image.
=> [202205][yang] Extend device_metadata yang model with rack_mgmt_map

rules/config, src/sonic-ctrmgrd/ctrmgr/container, src/sonic-ctrmgrd/ctrmgr/container_startup.py, src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py, src/sonic-ctrmgrd/ctrmgr/kube_commands.py, src/sonic-ctrmgrd/ctrmgr/remote_ctr.config.json, src/sonic-ctrmgrd/tests/common_test.py, src/sonic-ctrmgrd/tests/container_startup_test.py, src/sonic-ctrmgrd/tests/container_test.py, src/sonic-ctrmgrd/tests/ctrmgrd_test.py, src/sonic-ctrmgrd/tests/kube_commands_test.py
Our k8s feature will pull new version container images for each upgrade, the container images inside sonic will be more and more, but for now we don’t have a way to clean up the old version container images, the disk may be filled up. Need to add cleaning up the old version container images logic.
17979809
Remove the old version container images besides the feature's current version and last version image, last version image is saved for supporting fallback.
Check whether the old version images are removed
=> Clean up the old version container images

platform/pddf/i2c/service/pddf-s3ip-init.service, platform/pddf/i2c/utils/pddf_s3ip.py, platform/pddf/i2c/utils/pddf_util.py
The S3IP (Simplified Switch System INtegration Program) sysfs specification defines a unified interface to access peripheral hardware on devices from different vendors, making it easier for SONiC to support different devices and platforms.
PDDF is a framework to simplify the driver and SONiC platform APIs development for new platforms. This effort is first step in combining the two frameworks.
This specific PR adds support for _pddf-s3ip-init.service_ and enables it in PDDF.
S3IP exposes many more attributes than any SONiC platform APIs require. Hence S3IP sysfs from PDDF point of view are categorised as below,
- Static info: These are static attributes which are written directly into the files of the S3IP /sys_switch file system
- Dynamic Info: For such …
=> Adding and enabling S3IP support in PDDF

platform/pddf/i2c/modules/include/pddf_led_defs.h, platform/pddf/i2c/modules/led/pddf_led_module.c
The S3IP (Simplified Switch System INtegration Program) sysfs specification defines a unified interface to access peripheral hardware on devices from different vendors, making it easier for SONiC to support different devices and platforms.
PDDF is a framework to simplify the driver and SONiC platform APIs development for new platforms. This effort is first step in combining the two frameworks.
This specific PR adds the S3IP supported sysfs attributes in PDDF common LED driver.
S3IP exposes many more attributes than any SONiC platform APIs require. Hence S3IP sysfs from PDDF point of view are categorised as below, 
* Static info: These are static attributes which are written directly into the files of the S3IP /sys_switch file system
* Dynamic Info: For …
=> Adding S3IP supported attribute for LEDs in PDDF

platform/pddf/i2c/modules/fan/driver/pddf_fan_api.c, platform/pddf/i2c/modules/fan/driver/pddf_fan_driver.c, platform/pddf/i2c/modules/include/pddf_fan_api.h, platform/pddf/i2c/modules/include/pddf_fan_defs.h, platform/pddf/i2c/modules/include/pddf_fan_driver.h
The S3IP (Simplified Switch System INtegration Program) sysfs specification defines a unified interface to access peripheral hardware on devices from different vendors, making it easier for SONiC to support different devices and platforms.
PDDF is a framework to simplify the driver and SONiC platform APIs development for new platforms. This effort is first step in combining the two frameworks. 
This specific PR adds S3IP supported sysfs attribute in common FAN driver of PDDF.
S3IP exposes many more attributes than any SONiC platform APIs require. Hence S3IP sysfs from PDDF point of view are categorised as below, 
* Static info: These are static attributes which are written directly into the files of the S3IP /sys_switch file system
* Dynamic Info: For …
=> Adding S3IP supported attribute for FAN in PDDF

build_image.sh, files/Aboot/boot0.j2, files/initramfs-tools/modules, files/initramfs-tools/union-mount.j2
Some devices running SONiC have a small storage device (2G and 4G mainly)
The SONiC image growth over time has made it impossible to install 2 images on a single device.
Some mitigations have been implemented in the past for some devices but there is a need to do more.
One such mitigation is `docker_inram` which creates a `tmpfs` and extracts `dockerfs.tar.gz` in it.
This all happens in the SONiC initramfs and by ensuring the installation process does not extract `dockerfs.tar.gz` on the flash but keep the file as is.
This mitigation does a tradeoff by using more RAM to reduce the disk footprint.
It however creates new issues for devices with 4G of system memory since the extracted `dockerfs.tar.gz` nears the 1.6G. 
Considering debian upgrades (with dual base images) and the continuous …
=> Implement zram compression for docker in RAM

build_debian.sh
Cherry pick [PR#12592](https://github.com/sonic-net/sonic-buildimage/pull/12592)
nameserver and domain entries from build system fsroot gets into sonic image.
Clear /etc/resolv.conf before building image
Built image with it and verified with install that /etc/resolv.conf is empty
=> Clear /etc/resolv.conf before building image (#12592)

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/vnet.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/vnet.json, src/sonic-yang-models/yang-models/sonic-vnet.yang
Created Yang Modle for VNET table.
https://github.com/sonic-net/sonic-buildimage/issues/14534
18215579
=> [Yang model] Add Yang models for VNET table.

build_image.sh
To remove compression of the generated raw image during build.
Removed usage of 'gzip' on the generated raw image.
Initiate build for 'target/sonic-broadcom.raw' and verify that the size of the raw image generated is same as `RAW_IMAGE_DISK_SIZE`.
[build][201811] Remove compression of raw image
=> [build][201811] Remove compression of raw image

onie-image.conf
1GB disk size is not sufficient for latest 201811 broadcom raw image.
Increase raw image disk size from 1024MB to 1216MB
Initiate build for 'target/sonic-broadcom.raw' and verify that the build is successful.
```
Creating SONiC raw partition : target/sonic-broadcom.raw of size 1216 MB
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in BUILD
ONIE Installer: platform: x86_64-broadcom-r0
onie_platform:
mke2fs 1.42.12 (29-Aug-2014)
Discarding device blocks:   4096/311296^H^H^H^H^H^H^H^H^H^H^H^H^H             ^H^H^H^H^H^H^H^H^H^H^H^H^Hdone
Creating filesystem with 311296 4k blocks and 77920 inodes
Filesystem UUID: 5c0c892f-5cef-4776-a5a3-c88dfff94c4b
Superblock backups stored on blocks:
32768, 98304, 163840, 229376, 294912
Allocating group tables: …
```
=> [build][201811] Increase raw image disk size to 1216MB

src/sonic-bgpcfgd/bgpcfgd/utils.py, src/sonic-bgpcfgd/bgpmon/bgpmon.py, src/sonic-bgpcfgd/tests/util.py
It is not safe to call yaml.load with any data received from an untrusted source.
sys.exit is better than exit, considered good to use in production code.
Ref:
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python
https://stackoverflow.com/questions/19747371/python-exit-commands-why-so-many-and-when-should-each-be-used
- Microsoft ADO **(number only)**: 15022050
Replace yaml.load() with yaml.safe_load()
Replace exit() by sys.exit()
pass UT
test in DUT
=> [sonic-bgpcfgd] replace yaml.load() and exit()

dockers/docker-sonic-mgmt-framework/rest-server.sh
Mgmt-framework REST server startup script is using "null" as default value for all optional fields of REST_SERVER table -- due to incorrect use of `jq -r` command. Server was not coming up when REST_SERVER entry exists but some fields were not given (which is a valid configuration).
Fixed the jq query expression to return empty string for non existing fields.
Verify REST server startup with following configurations:
- No REST_SERVER and x509 table entries
- With client_auth config in REST_SERVER entry
- With log_level config in REST_SERVER entry
- With certificate configs in REST_SERVER entry
- WIth all configs in REST_SERVER entry
- With certificate configs in x509 entry
- With client_auth config in REST_SERVER entry and certificate configs in x509 …
=> [mgmt-framework] Fix rest-server startup script

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json, src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-buildimage/pull/15109
Extend device_metadata yang model.
- Microsoft ADO **(number only)**: 22912178
Add rack_mgmt_map field in yang model.
Build image.
=> [202211][yang] Extend device_metadata yang model with rack_mgmt_map

.azure-pipelines/azure-pipelines-repd-build-variables.yml, Makefile.work
Cherry pick [PR#14543](https://github.com/sonic-net/sonic-buildimage/pull/14543)
Enable the reproducible build for PR build for master branch
Fix the reproducible build variable display error in the slave container. The below config is none, although the config is set and takes effect.
"SONIC_VERSION_CONTROL_COMPONENTS": "none"
Passing the variable through the slave container command line. The variable has been passed to the slave container and the other docker container by a config file, it is only used to display the value during the build.
=> [Build] Fix the reproducible build variable display error in the slave container (#14543)

.azure-pipelines/azure-pipelines-build.yml
libsaithriftv2 build fails and nobody is maintaining saiserverv2's build.
Remove them from official build.
- Microsoft ADO **(number only)**:  23764652
=> [ci] Remove saiserverv2 build in official build.

azure-pipelines.yml
1. Remove 'kvmtest-t0' and 'kvmtest-t1-lag' test jobs since all the test jobs are required (continueOnError: false) already, and will only enable one of classical and testbedV2 tests, no need to do an unnecessary 'or' compute test job.
2. Change agent pool to reduce cost and avoid congestion
- Microsoft ADO **(number only)**: 21200453
=> [202012]Refine test job definition and assert logic

Makefile.work
showtag target didn't shows the correct target when setting MIRROR_SNAPSHOT options.
- Microsoft ADO **(number only)**:  23982694
=> [ci] Remove debian mirror timestamp from sonic slave base tag.

device/celestica/x86_64-cel_silverstone-r0/led_proc_init.soc
Optimize Silverstone led init process, this linkscan = off can cause the sonic port link status async with bcm shell after reboot. 
Remove redundant code.
After reboot, the ports can linkup normally.
=> [Celestica] Optimize Silverstone led init process

src/sonic-yang-models/yang-models/sonic-device_neighbor_metadata.yang
Introduce a new valid neighbor element type to YANG.
- Microsoft ADO **(number only)**: 23994521
Add `MgmtLeafRouter` to element network type list.
Passes UTs
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md#device-neighbor-metada
=> [YANG] Add MgmtLeafRouter to Device Neighbor Metadata element type list

.gitmodules
To add branch info for submodules of 202305 branch
- Microsoft ADO **(21450860)**:
To modify the .gitmodule file to have 202305 branch for repos
Pass PR build
=> Add branch info for gitmodules

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/simple-sample-graph-case.xml, src/sonic-config-engine/tests/test_minigraph_case.py
Manually cherry-pick this PR: https://github.com/sonic-net/sonic-buildimage/pull/15064, to fix auto cherry-pick build test failed.
We need to store information of power shelf in config_db for SONiC MX switch. Current minigraph parser cannot parse rack_mgmt_map field.
- Microsoft ADO **(number only)**: 22179645
Add support for parsing rack_mgmt_map.
=> [202205][minigraph] Add rack_mgmt_rack parse support in minigraph.py (#15064)

device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/config.bcm.j2, device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/config.bcm.j2, device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2, device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C10/config.bcm.j2, device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2, device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2, src/sonic-config-engine/tests/data/j2_template/config.bcm.j2, src/sonic-config-engine/tests/sample_output/py3/arista7050cx3-dualtor.config.bcm, src/sonic-config-engine/tests/sample_output/py3/arista7260-dualtor.config.bcm, src/sonic-config-engine/tests/sample_output/py3/arista7260-t1.config.bcm
Update soc properties for certain roles that need to use pfcwd dlr init based recovery mechanism
Updated the templates on a 7050cx3 dual tor and 7260 T1 which satisfies these conditions and validated pfcwd recovery which uses DLR_INIT based mechanism. Also validated that this mechanism is not used on 7050cx3 single tor with the updated templates
=> [202205] Update SOC properties for DLR_INIT based pfcwd recovery

platform/marvell-arm64/prestera/debian/rules
When git clone -b xxx command is used the versions-git will reset the HEAD of the git to the commit ID in the versions-git file. Which causes incorrect commit to be checked out causing build errors. 
Split ‘git clone -b’ into two steps to avoid owerwrite
1.	Git clone
2.	cd mrvl-prestera; git checkout ; cd ..
Build marvell-arm64 target using below instructions
make init
make configure PLATFORM=marvell-arm64 PLATFORM_ARCH=arm64
make target/sonic-marvell-arm64.bin SONIC_BUILD_JOBS=2
=> [arm64] Fix marvell-arm64 pipeline build

platform/marvell-arm64/platform.conf
Update platform.conf to have a successful marvell-arm64 target image.
Modify platform.conf file appropriately
1) Build marvell-arm64 target using below instructions 
- make init
- make configure PLATFORM=marvell-arm64 PLATFORM_ARCH=arm64
- make target/sonic-marvell-arm64.bin SONIC_BUILD_JOBS=2
2) Run this image on arm64-nokia_ixs7215_52xb-r0 and verify all dockers are up and test basic commands like:
- show version
- show platform summary
- show platform syseeprom
- show platform fan
- show platform psustatus
- show platform firmware status
- show platform temperature
- show platform ssdhealth
3) Verify ports are up using "show interface status" command
Update platform.conf to have a successful marvell-arm64 target image.
=> [marvell-arm64] Update platform.conf

src/sonic-bgpcfgd/bgpmon/bgpmon.py
What I did:
Added change to add 'peerType' as element in NEIGH_STATE_TABLE.
'peerType' can be i-BGP vs e-BGP determined based on local and remote AS number.
Why I did:
This is useful to filter neighbors in SONiC as internal vs external in chassis use-case (example: telemetry) 
Verification:
- Manual Verification
```
127.0.0.1:6379[6]> hgetall "NEIGH_STATE_TABLE|10.0.0.5"
1) "state"
2) "Established"
3) "peerType"
4) "e-BGP"
127.0.0.1:6379[6]> hgetall  "NEIGH_STATE_TABLE|2603:10e2:400::4"
1) "state"
2) "Established"
3) "peerType"
4) "i-BGP"
```
- Also sonic-mgmt test case `test_bgp_fact.py` is enhanced: https://github.com/sonic-net/sonic-mgmt/pull/8462
=> Added change to add 'peerType' as element in NEIGH_STATE_TABLE.

.github/workflows/label.yml
Cherry pick https://github.com/sonic-net/sonic-buildimage/pull/15112
Don't auto update package version for release branch.
- Microsoft ADO **(number only)**:  22335854
=> [action] Only add 'automerge' label on master version upgrade PR. (#15112)

files/build_templates/sonic_debian_extension.j2
- Microsoft ADO **17792956**:
In the PR https://github.com/sonic-net/sonic-utilities/pull/2850 , for support remote access of linecards paramiko package is  installed in sonic-utilities.
`libffi-dev` needs to installed to be able to compile for `armhf` image
This change was done in this draft PR https://github.com/sonic-net/sonic-buildimage/pull/14988 and compilation of marvell_armhf build was verified
=> [chassis] add libffi-dev for sonic-utilities

dockers/docker-fpm-frr/base_image_files/TSA, dockers/docker-fpm-frr/base_image_files/TSB, dockers/docker-fpm-frr/base_image_files/TSC
TSA/B/C scripts invoke commands that require root permissions. If the user does not have sudo permissions, the scripts today execute until the command and throw a backtrace with error at the specific command. Added a check to ensure the operations check for root permissions upfront.
- Microsoft ADO **(number only)**: 
Added check for sudo user at the start of the scripts
* TSA/B/C without sudo should throw an error.
=> Add sudo check for TSA/B/C command execution

src/sonic-build-hooks/scripts/buildinfo_base.sh
When a package is referenced from the web through wget command, it downloads the package for every build.
This feature caches all the packages that are being downloaded from the web, so that subsequent build always loads the cache instead of from web.
=> 06.Version Cache - Support for wget

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_sup-r0/chassisdb.conf
Update the device data files to support 1024 LAGs for Nokia IXR7250E platform
fixes https://github.com/Nokia-ION/ndk/issues/15
Update the lag_id_end=1024 in chassisdb.conf file and add the trunk_group_max_members=16  in the BCM config file
check to allow to create lag ids up to 1024 with 16 port members
=> [Nokia-IXR7250E][Devicedata] update the device files for Nokia IXR7250E to support 1024 LAGs

src/sonic-build-hooks/scripts/buildinfo_base.sh
During build, lots of pip packages are getting installed through pip install command.
This feature adds support for caching all the pip packages into local cache path, so that subsequent build always loads from the cache.
=> 07.Version Cache - Support for PIP

dockers/docker-orchagent/docker-init.j2, dockers/docker-orchagent/supervisord.conf.j2, dockers/docker-orchagent/watchdog_processes.j2, files/scripts/supervisor-proc-exit-listener
This PR depends on https://github.com/sonic-net/sonic-swss/pull/2737 merge first.
**What I did**
Add orchagent watchdog to monitor and alert orchagent stuck issue.
Currently SONiC monit system only monit orchagent process exist or not. If orchagent process stuck and stop processing, current monit can't find and report it.
**How I verified it**
Pass all UT.
Add new UT https://github.com/sonic-net/sonic-mgmt/pull/8306 to check watchdog works correctly.
Manually test, after pause orchagent with 'kill -STOP <pid>', check there are warning message exist in log:
Apr 28 23:36:41.504923 vlab-01 ERR swss#supervisor-proc-watchdog-listener: Process 'orchagent' is stuck in namespace 'host' (1.0 minutes).
**Details if related**
Heartbeat message PR: …
=> Add watchdog mechanism to swss service and generate alert when swss have issue.

files/build_templates/init_cfg.json.j2, src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json, src/sonic-yang-models/yang-models/sonic-device_metadata.yang, src/sonic-yang-models/yang-templates/sonic-types.yang.j2
hld [#1219](https://github.com/sonic-net/SONiC/pull/1219)
closes [#1171](https://github.com/sonic-net/SONiC/issues/1171)
depends-on [#2793](https://github.com/sonic-net/sonic-utilities/pull/2793), [#57](https://github.com/sonic-net/sonic-host-services/pull/57)
* To be able to configure timezone
* To be able to show timezones
* Add YANG model
* Add default value to `init_cfg.json`
* Add timezone config YANG model
[Device metadata configuration](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md#device-metadata)
=> [Clock] Add timezone config YANG model

.azure-pipelines/azure-pipelines-image-template.yml
Set build options in pipeline UI.
Support setting reproducible build options to py2,py3 in release branch and none in master branch.
- Microsoft ADO **(number only)**: 22335854
=> [ci] Add OVERRIDE_BUILD_OPTIONS in image build template. (#15309)

platform/mellanox/integration-scripts/helper.py, platform/mellanox/integration-scripts/hwmgmt_kernel_patches.py, platform/mellanox/integration-scripts/tests/data/Patch_Status_Table.txt, platform/mellanox/integration-scripts/tests/data/expected_data/series, platform/mellanox/integration-scripts/tests/data/expected_data/series.patch, platform/mellanox/integration-scripts/tests/test_hwmgmtaction.py
Add the patchwork link to the commit description for non-upstream patches if present
Parse the `patchwork/<patch_name>.txt` file from hw-mgmt
=> [Mellanox] Added patchwork link to commit message

dockers/docker-orchagent/docker-init.j2, dockers/docker-orchagent/supervisord.conf.j2, dockers/docker-orchagent/watchdog_processes.j2, files/scripts/supervisor-proc-exit-listener
Reverts sonic-net/sonic-buildimage#14686
process_monitoring/test_critical_process_monitoring.py failed because there is no file ‘/etc/supervisor/critical_processes’ in the bgp and other containers, so the ‘supervisor-proc-exit-listener’ can’t up:
In the bgp container:
root@vlab-01:/# supervisorctl status
bgpcfgd                          RUNNING   pid 52, uptime 0:12:13
bgpd                             RUNNING   pid 50, uptime 0:12:13
bgpmon                           RUNNING   pid 58, uptime 0:12:13
containercfgd                    RUNNING   pid 36, uptime 0:12:14
dependent-startup                EXITED    Jun 08 10:22 AM
fpmsyncd                         RUNNING   pid 59, uptime 0:12:13
rsyslogd                         RUNNING   pid 31, uptime 0:12:15
staticd …
=> Revert "Add watchdog mechanism to swss service and generate alert when swss have issue."

files/build_templates/init_cfg.json.j2, files/build_templates/sflow.service.j2
Delaying sflow service until interfaces are created.  Starting sflow early leads to CPU contention and issues like [this](https://github.com/sonic-net/sonic-buildimage/issues/13407) where sflow daemon will try to access interfaces even before they are created.
Set delayed to true in init_cfg.j2
Perform config reload and reboot to ensure sflow is started only after interfaces are created
=> [sflow]Delay starting sflow service until ports are created

platform/mellanox/integration-scripts.mk, platform/mellanox/integration-scripts/hwmgmt_kernel_patches.py, platform/mellanox/integration-scripts/tests/data/Patch_Status_Table.txt, platform/mellanox/integration-scripts/tests/test_hwmgmtaction.py
- Why I did it Add the commit-id patch map in the commit message.
- How I did it By parsing the patch DB from hw-mgmt
this is a cherry pick https://github.com/sonic-net/sonic-buildimage/pull/15052
=> Cherrypick to 202211 [Mellanox] Add patch commit-id mapping to description

files/Aboot/boot0.j2
After docker_inram is enabled, the docker folder's default max size is 1.5G.
It's not big enough for some tests which need to install additional docker images or install extra packages.
- Microsoft ADO **24199761**:
add docker_inram into cmdline_allowlist
sudo sh -c 'echo "docker_inram_size=3000M" >> kernel-cmdline-append'
sudo reboot and check the docker folder size
=> allow docker_inram in cmdline_allowlist

dockers/docker-orchagent/docker-init.j2, dockers/docker-orchagent/supervisord.conf.j2, dockers/docker-orchagent/watchdog_processes.j2, files/scripts/supervisor-proc-exit-listener
Add watchdog mechanism to swss service and generate alert when swss have issue. 
**Work item tracking**
Microsoft ADO (number only): 16578912
**What I did**
Add orchagent watchdog to monitor and alert orchagent stuck issue.
Currently SONiC monit system only monit orchagent process exist or not. If orchagent process stuck and stop processing, current monit can't find and report it.
**How I verified it**
Pass all UT.
Manually test process_monitoring/test_critical_process_monitoring.py can pass.
Add new UT https://github.com/sonic-net/sonic-mgmt/pull/8306 to check watchdog works correctly.
Manually test, after pause orchagent with 'kill -STOP <pid>', check there are warning message exist in log:
Apr 28 23:36:41.504923 vlab-01 ERR swss#supervisor-proc-watchdog-listener: …
=> Add watchdog mechanism to swss service and generate alert when swss have issue. 

src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/yang-models/sonic-bgp-common.yang, src/sonic-yang-models/yang-models/sonic-bgp-internal-neighbor.yang, src/sonic-yang-models/yang-models/sonic-bgp-neighbor.yang, src/sonic-yang-models/yang-models/sonic-bgp-voq-chassis-neighbor.yang
The asn 0 in BGP_MONITOR is invalid by YANG definition. However, the asn 0 in BGP_MONITOR is found in many devices. 
It was introduced by minigraph where its value is set to 0.
To unblock Config Updater test, the short term fix is to accept the asn 0 in BGP_MONITOR. 
We can revert this after NGS team make all the ASN change in minigraph.
- Microsoft ADO **(24186140)**:
Change the range
Unit test.
=> [yang] Change asn to start from 0 for bgp monitor

device/mellanox/x86_64-nvidia_sn5600-r0/platform.json
Service port SFP is missing from SN5600 platform.json.
Add the service port SFP object to platform.json
=> [Mellanox] Update SN5600 platform.json with service port sfp

files/image_config/interfaces/interfaces.j2, src/sonic-config-engine/tests/sample_output/py2/interfaces, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_inband, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_inband_ip, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_ip, src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces, src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py2/two_mgmt_interfaces, src/sonic-config-engine/tests/sample_output/py3/interfaces, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_inband, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_inband_ip, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_ip, src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces, src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py3/two_mgmt_interfaces
With #5353, 127.0.0.1/16 was added to the lo interface, and then 127.0.0.1/8 was removed. However, when bringing down the lo interface, like during a config reload, 127.0.0.1/16 gets removed, but 127.0.0.1/8 isn't added back to the interface. This means that there's a period of time where 127.0.0.1 is not available at all, and services that need to connect to 127.0.0.1 (such as for redis DB) will fail.
Fixes #15117.
Fixes #14880.
- Microsoft ADO **(number only)**: 18637195
To fix this, when going down, add 127.0.0.1/8. Add this address before the existing configuration gets removed, so that 127.0.0.1 is available at all times.
Note that running `ifdown lo` doesn't actually bring down the loopback interface; the interface always stays "physically" up.
On a virtual switch, `config reload` …
=> Re-add 127.0.0.1/8 when bringing down the interfaces

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json, src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Supporting WRED and ECN statistics in SONiC
Added new flex counter groups in yang file
Compiled the sonic.bin and loaded the image to DUT with all the WRED feature changes.
* Yang changes for WRED_ECN_QUEUE and WRED_ECN_PORT flex counter groups
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md#flex_counter_table
Dependent Pull Requests: 
Sonic-utilities pull request : https://github.com/sonic-net/sonic-utilities/pull/2807
Sonic-sairedis pull request : https://github.com/sonic-net/sonic-sairedis/pull/1234
Sonic-swss : pull request : https://github.com/sonic-net/sonic-swss/pull/2750
Sonic-swss common pull request : https://github.com/sonic-net/sonic-swss-common/pull/777
=> sonic-yang-models: WRED statistics yang

device/arista/x86_64-arista_7050_qx32/platform.json, device/arista/x86_64-arista_7050_qx32s/platform.json, device/arista/x86_64-arista_7060_cx32s/platform_components.json
sonic-mgmt is failing tests due to invalid test data in `platform.json`
Fwutil is upset the chassis name in the `platform_component.json` of the 7060CX-32S
Fixed the aforementioned issues
fix platform.json for a few Arista devices
=> [Arista] fix platform.json for a few devices

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/t0-sample-deployment-id.xml, src/sonic-config-engine/tests/test_cfggen.py
Create Vxlan and Vnet default configs as below for certain cases:
```
"VNET": {
"Vnet-default": {
"scope": "default",
"vni": "8000",
"vxlan_tunnel": "Tunnel-default"
}
},
"VXLAN_TUNNEL": {
"Tunnel-default": {
"src_ip": "10.1.0.32"
}
},
```
MSFT ADO - 24263117
=> Create default Vxlan and Vnet configs

device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/hwsku.json, device/arista/x86_64-arista_7050_qx32s/platform.json
This is to fix some issues of hwsku.json for Arista-7050QX-32S-S4Q31:
- default_brkout_mode in hwsku.json should be available in platform.json
- interface in hwsku.json should be available in platform.json
Change platform.json add a new breakout mode 4x10G[1G] for SONiC SFP ports Ethernet0, Ethernet1, Ethernet2 and Ethernet3.
Change hwsku.json to update the default_brkout_mode for all ports and remove Ethernet1, Ethernet2 and Ethernet3.
Sanitize a dut and check that the result in 'show int status' as below matches the port_config.ini
root@ck331:/home/admin# show int st
Interface            Lanes    Speed    MTU    FEC         Alias    Vlan    Oper    Admin                                      Type    Asym PFC
-----------  ---------------  -------  ----- …
=> [Arista] Update hwsku.json for Arista-7050QX-32S-S4Q31

files/image_config/interfaces/interfaces.j2, src/sonic-config-engine/tests/sample_output/py2/interfaces, src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces, src/sonic-config-engine/tests/sample_output/py3/interfaces, src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces
Cherry-pick of #15080
* Re-add 127.0.0.1/8 when bringing down the interfaces
With #5353, 127.0.0.1/16 was added to the lo interface, and then 127.0.0.1/8 was removed. However, when bringing down the lo interface, like during a config reload, 127.0.0.1/16 gets removed, but 127.0.0.1/8 isn't added back to the interface. This means that there's a period of time where 127.0.0.1 is not available at all, and services that need to connect to 127.0.01 (such as for redis DB) will fail.
To fix this, when going down, add 127.0.0.1/8. Add this address before the existing configuration gets removed, so that 127.0.0.1 is available at all times.
Note that running `ifdown lo` doesn't actually bring down the loopback interface; the interface always stays "physically" up. …
=> [202205] Re-add 127.0.0.1/8 when bringing down the interfaces

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/mux_cable.json, src/sonic-yang-models/tests/yang_model_tests/tests/peer-switch.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/mux_cable.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/peer-switch.json, src/sonic-yang-models/yang-models/sonic-mux-cable.yang, src/sonic-yang-models/yang-models/sonic-peer-switch.yang
Cherry-pick conflicts: 
0cdef2ebc       Jing Zhang      Thu Aug 25 08:46:45 2022 -0700  [YANG] add peer switch model (#11828)
fdd9130ec       Jing Zhang      Thu Sep 1 11:52:02 2022 -0700   [YANG] Add MUX_CABLE yang model  (#11797)
sign-off: Jing Zhang zhangjing@microsoft.com 
=> [202205][YANG] add model for `MUX_CABLE` and `PEER_SWITCH`

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/t0-sample-deployment-id.xml, src/sonic-config-engine/tests/test_cfggen.py
Cherry-pick #13409 
- Microsoft ADO **24263117**:
=> [202205] Create default Vxlan and Vnet configs (#13409)

files/build_templates/docker_image_ctl.j2, files/image_config/config-setup/config-setup
Reverts sonic-net/sonic-buildimage#14933
The earlier commit caused a race condition that particularly broke cross branch warm upgrade.
Issue happens when db_migrator is still migrating the DB and finalizer is checking DB for list of components to reconcile.
If migration is not complete, finalizer get an empty list to wait for. Due to this, finalizer concludes warmboot (deletes system wide warmboot flag) and cause all the services to do cold restart.
ADO: 24274591
=> Revert "Fix for fast/cold-boot: call db_migrator only after old config is loaded"

.github/workflows/automerge_scan.yml
Refine submodule update commit message.
- Microsoft ADO **(number only)**:  24253804
After refine:
```
commit 4098a90b90a19edb55123b45ba28f88699210b95 (azure/202211)
Author: mssonicbld <79238446+mssonicbld@users.noreply.github.com>
Date:   Tue Jun 13 14:56:44 2023 +0800
[submodule] Update submodule sonic-swss to the latest HEAD automatically (#15441)
src/sonic-swss
```
* bccb1cc - (HEAD -> 202211, origin/202211) [202211] [sflowmgrd] Infer sampling rate dynamically based on oper speed (#2805) (4 hours ago) [Vivek]
```
diff --git a/src/sonic-swss b/src/sonic-swss
index 1e8eaa721c..bccb1cca85 160000
--- a/src/sonic-swss
+++ b/src/sonic-swss
@@ -1 +1 @@
-Subproject commit 1e8eaa721c174ea162e22ddb1826e3f854829009
+Subproject commit bccb1cca85b86a2f009c7218ae124ad1f1fa7a8b
```
=> [action] Fix auto merge workflow commit message.

src/system-health/health_checker/sysmonitor.py
Multiprocessing Manager resources (Queue) to be freed up during task stop
Fix for issue https://github.com/sonic-net/sonic-buildimage/issues/14964 
Free up Multiprocessing Manager resource at task stop request
[self.mpmgr.shutdown() in task_stop]
time systemctl stop system-health.service
=> Multiprocessing Manager resources (Queue) to be freed up during task stop

build_debian.sh, platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
Install smartmontools in host so that any platform can have smartctl accessible. 
Removed smartctl from Dell S6100 and added same in host
Install platform package on S6100
=> Remove smartctl from Dell S6100 debian package

device/celestica/x86_64-cel_seastone-r0/sonic_platform/component.py, device/celestica/x86_64-cel_seastone-r0/sonic_platform/helper.py
fix possible cpld race read issue between watchdog and reboot cause process
Use flock to limit parallel access to cpld sys file
It can be simulate and verified with following python script
```python3
import signal
import subprocess
import threading
exit_flag = False
def run_command(cmd):
status = True
result = ""
try:
p = subprocess.Popen(
cmd, shell=True, universal_newlines=True,
stdout=subprocess.PIPE, stderr=subprocess.PIPE)
raw_data, err = p.communicate()
if err == '':
result = raw_data.strip()
except:
status = False
return status, result
def get_cpld_reg_value(getreg_path, register):
#cmd = "echo {1} > {0}; cat {0}".format(getreg_path, register)
cmd = "flock {0} -c 'echo {1} > {0}; cat {0}'".format(getreg_path,
register)
status, result = …
```
=> [DX010] fix possible cpld race read issue

src/sonic-frr/patch/0029-bgpd-Change-log-level-for-graceful-restart-events.patch, src/sonic-frr/patch/series
Graceful restart is a key event for bgpd, related log print is debug level. To change it to info level to get more visibilities when this kind of event is triggered.
- Microsoft ADO **(13875291)**:
To create patch file to change from debug level to info level. 
To run PR test and capture the print.
=> enable info log for graceful restart events

dockers/docker-ptf/Dockerfile.j2
Need new changes that were added to gnxi inside ptf docker
- Microsoft ADO **(number only)**: 17747466
Update commit number
Pipeline
=> Update gnxi commit in PTF Dockerfile

dockers/docker-sonic-mgmt/Dockerfile.j2
Current docker-sonic-mgmt build is broken. So below are two fixes which can help in mitigating the same.
1. PYAML - Download a specific version in python2 as after https://pypi.org/project/pyaml/23.5.5/ there was support only for python3. This update happened on May 5th. And consequently all daily builds after this changes https://dev.azure.com/mssonic/build/_build/results?buildId=266733&view=results (starting build to break) kept failing
2. Azure-CLI - this can be downloaded by apt-get repository. So modify as an improvement.
- Microsoft ADO **(number only)**: #15567
By manually checking the release notes of pyaml and install azure-cli in newly installed docker container using apt-get
You can run below commands to validate:
make configure PLATFORM=generic
make target/docker-sonic-mgmt.gz …
=> Fix docker-sonic-mgmt build by specific version install of pyaml and azure-cli by apt-get

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/chassis_module.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/chassis_module.json, src/sonic-yang-models/yang-models/sonic-chassis-module.yang
Why I did it
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/14007
Add yang model definition for CHASSIS_MODULE define and implemented for sonic chassis. HLD for this configuration is included in https://github.com/sonic-net/SONiC/blob/master/doc/pmon/pmon-chassis-design.md#configuration
Fixes #12640
How I did it
Added yang model definition, unit tests, sample config and documentation for the table
Validated config tree generation using "pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/sonic-voq-inband-interface.yang"
Built the below python-wheels to validate unit tests and other changes target/python-wheels/bullseye/sonic_yang_mgmt-1.0-py3-none-any.whl target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl …
=> [202211] Add yang model definition for CHASSIS_MODULE table (#14007)

device/arista/x86_64-arista_7050_qx32/platform.json, device/arista/x86_64-arista_7050_qx32s/platform.json
This PR fixes the components names and adds the number so that platform API tests can get consistent results to match vs the expected results.
The way to verify /get the platform API results is run the platform API and get the components name for these SKU x86_64-arista_7050_qx32, x86_64-arista_7050_qx32s
17397061
16428955
Run the Platfrom API and get the components names
- [ x] 202205
- [x ] 202211
=> [Arista][x86_64-arista_7050_qx32] Add Components to platform.json

src/systemd-sonic-generator/systemd-sonic-generator.c
Avoid 'sscanf()' for number conversions. Its use can lead to undefined behavior, slow processing, and integer overflows. Instead prefer the 'strto*()' family of functions.
replace sscanf with strtol
Manual test
=> [systemd-sonic-generator] replace sscanf with strtol

platform/p4/docker-sonic-p4/Dockerfile.j2
Docker best practices prefer COPY to ADD
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
- Microsoft ADO **(number only)**: 17418730
Use the COPY command as opposed to ADD unless working with a tar file.
=> docker prefer COPY to ADD in dockerfile

dockers/docker-lldp/lldpmgrd, src/sonic-py-common/sonic_py_common/device_info.py
Fix issue #14251
In multiasic platform, there is NO front panel port in the host lldp docker.  Because of there is NO front panel port,  the host APPL_DB database will not genernate the "PORT_CONFIG_DONE" and "PORT_INIT_DONE" event.   Therefore, the lldpmgrd  log the error log - ``` Port init timeout reached (300 seconds), resuming lldpd...``` in syslog.
``` 
Apr 18 01:57:03.993698 ixre-cpm-chassis9 ERR lldp#lldpmgrd[29]: Port init timeout reached (300 seconds), resuming lldpd...
```
OC test case failed-- autorestart/test_container_autorestart.py::test_containers_autorestart[ixre-cpm-chassis9-10-snmp
- Microsoft ADO **https://msazure.visualstudio.com/One/_workitems/edit/17966117**:
Since there is NO front panel ports in the host database in the multiasic platform ,  there won't be …
=> [chassis][lldp] Fix the lldp error log in host instance which doesn't contain front panel ports

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/mux-linkmgr.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/mux-linkmgr.json, src/sonic-yang-models/yang-models/sonic-mux-linkmgr.yang
Add yang model for `MUX_LINKMGR|LINK_PROBER` table. 
sign-off: zhangjing@microsoft.com 
24196914
Run UTs.
=> [yang] add Yang model for `MUX_LINKMGR|LINK_PROBER`

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_sup-r0/chassisdb.conf
(cherry picked from commit 478ba478f5aaea347d36bc22021e0c5ab7e7e39b)
Update the device data files to support 1024 LAGs for Nokia IXR7250E platform
=> [Nokia-IXR7250E][Devicedata] update the device data for Nokia IXR7250E platform

dockers/docker-sonic-mgmt/Dockerfile.j2
Fix the issue that azure-cli version is too old.
With apt-get install, we will install the old version of azure-cli: (2.0.81+ds-4ubuntu0.2)
This version can't use azure keyvault command: https://github.com/Azure/azure-cli/issues/17981 
Following https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions to install the newest version of azure-cli
=> [sonic-mgmt] install newest az-cli to mitigate old version az-cli issue

platform/marvell-arm64/sai.mk
- SAI-1.12.0 support
Add support of SAI 1.12.0 arm64 SAI debian for Marvell platform
Upstream SAI 1.12.0 arm64 debian to be used in SONiC compilation
Compile and load SAI 1.12.0 libsai.so in syncd docker
=>  [Marvell] Update arm64 sai debian

.azure-pipelines/run-test-scheduler-template.yml, azure-pipelines.yml
t0-sonic's specific params has been set on sonic-mgmt repo, remove useless SPECIFIED_PARAMS usage
=> [CI/CD] Refine t0 sonic and remove SPECIFIED_PARAMS

.azure-pipelines/run-test-scheduler-template.yml, azure-pipelines.yml
t0-sonic's specific params has been set on sonic-mgmt repo, remove useless SPECIFIED_PARAMS usage
=> [CI/CD, 202205] Refine t0 sonic and remove SPECIFIED_PARAMS

.azure-pipelines/run-test-scheduler-template.yml, azure-pipelines.yml
t0-sonic's specific params has been set on sonic-mgmt repo, remove useless SPECIFIED_PARAMS usage
=> [CI/CD, 202211] Refine t0 sonic and remove SPECIFIED_PARAMS

.azure-pipelines/run-test-scheduler-template.yml, azure-pipelines.yml
t0-sonic's specific params has been set on sonic-mgmt repo, remove useless SPECIFIED_PARAMS usage
=> [CI/CD, 202305] Refine t0 sonic and remove SPECIFIED_PARAMS

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/mux-linkmgr.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/mux-linkmgr.json, src/sonic-yang-models/yang-models/sonic-mux-linkmgr.yang
Manually submitting PR for cherry-pick conflict.
sign-off: Jing Zhang zhangjing@microsoft.com 
- Microsoft ADO **(number only)**: 24196914
=> [202205][yang] add Yang model for MUX_LINKMGR|LINK_PROBER (#15384)

azure-pipelines.yml
[Ci] Support to build sonic-swss-common for test
- Microsoft ADO **(number only)**: 24341479
=> [Ci][202012] Support to build sonic-swss-common for test

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/mux-linkmgr.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/mux-linkmgr.json, src/sonic-yang-models/yang-models/sonic-mux-linkmgr.yang
Add yang model for MUX_LINKMGR|LINK_PROBER table.
sign-off: zhangjing@microsoft.com
- Microsoft ADO **(number only)**: 24196914
=> [202211][yang] add Yang model for `MUX_LINKMGR|LINK_PROBER` (#15384)

files/build_templates/docker_image_ctl.j2, files/build_templates/per_namespace/syncd.service.j2, files/build_templates/sonic_debian_extension.j2, platform/mellanox/nv-syncd-shared/nv-syncd-shared.service
Sharing the storage of syncd with other proprietary application extensions allows them to communicate with syncd in differnt ways.
If one container wants to pass some information to syncd then shared storage can be used. However, today the shared storage isn't cleaned on restarts making it possible for syncd to read out-of-date information generated in the past.
NOTE: No plans to use it for standard SONIC dockers and we are working on removing the SDK dependency from PMON docker
Implemented new service to clean the shared storage.
Do reboot/fast-reboot/warm-reboot/config-reload/systemctl restart swss and verify /tmp/ is cleaned after each restart in syncd container.
=> [Mellanox] make sure shared storage with syncd is cleared on restarts

dockers/docker-database/flush_unused_database
Migrate flush_unused_database from py-redis to sonic-swss-common
flush_unused_database using py-redis, but sonic-swss-common already support flushdb, so we need migrate to sonic-swss-common
- Microsoft ADO **(number only)**: 24292565
Migrate flush_unused_database from py-redis to sonic-swss-common
Pass all UT and E2E test
Migrate flush_unused_database from py-redis to sonic-swss-common
=> Migrate flush_unused_database from py-redis to sonic-swss-common

files/scripts/arp_update
A race condition exists which makes it possible for the kernel to resolve a trapped packet's destination IP at the same time that arp_update is running the `ip neigh replace` command for that neighbor IP. When this occurs, the kernel's neighbor entry for this IP is in the INCOMPLETE state, and the `ip neigh replace` command sets it to permanently incomplete. This means no netlink message will be generated for this neighbor, since the kernel doesn't generate netlink messages for INCOMPLETE neighbors (it would only generate a message once the neighbor transitions to FAILED, which doesn't happen due to the `ip neigh replace` command). As a result, no APPL_DB neighbor table entry is ever created and no tunnel route for the IP is ever installed, leading to dropped traffic.
- Microsoft ADO …
=> [arp_update]: Fix IPv6 neighbor race condition

src/system-health/health_checker/sysmonitor.py
Fix for issue https://github.com/sonic-net/sonic-buildimage/issues/14964
Free up Multiprocessing Manager resource at task stop request
[self.mpmgr.shutdown() in task_stop]
time systemctl stop system-health.service
=> Multiprocessing Manager resources (Queue) to be freed up during task stop (CherryPick PR#15212 to 202205)

files/build_templates/sonic_debian_extension.j2, platform/mellanox/mlnx-ffb.sh
BACKPORT OF https://github.com/sonic-net/sonic-buildimage/pull/14925
ISSU version check fails due to inability to mount squashfs from 202211 on 201911
Put ISSU version file under platform directory
202012 (with [202012][mlnx-ffb.sh] Update issu-version location  #14927) to master
=> [202012][mlnx-ffb.sh] Update issu-version location 

src/sonic-host-services/scripts/caclmgrd, src/sonic-host-services/tests/caclmgrd/cacl_external_client_acl_test.py, src/sonic-host-services/tests/caclmgrd/caclmgrd_scale_test.py, src/sonic-host-services/tests/caclmgrd/test_scale_vectors.py, src/sonic-host-services/tests/common/mock_configdb.py
Cherry pick PR for https://github.com/sonic-net/sonic-host-services/pull/62
Fix the issue https://github.com/sonic-net/sonic-buildimage/issues/10883.
- Microsoft ADO **(17795594)**:
For performance reason, libswsscommon is not thread safe by design.
caclmgrd share config DB connection cross thread, so change to use new db connector in child thread.
Load scale ipv4/ipv6 rules and verify if caclmgrd is crashed
=> [202012] Fix caclmgrd crash issue when applying scale cacl rules

platform/components/docker-gbsyncd-credo.mk
Reverts sonic-net/sonic-buildimage#14149
This SAI `libsaicredo_0.9.0_amd64.deb` causing packet forwarding issues on Linecards https://github.com/aristanetworks/sonic/issues/92
=> Revert "[gearbox] use credo sai v0.9.0"

src/tacacs/nss/patch/0011-Replace-popen-shell-execution-with-safer-execle.patch, src/tacacs/nss/patch/series
Tacacs nss library uses popen to execute useradd and usermod commands. Popen executes using a shell (/bin/sh) which is passed the command string with "-c". This means that if untrusted user input is supplied, unexpected shell escapes can occur. In this case the username supplied can be untrusted user input when logging in via ssh or other methods when tacacs is enabled. Debian has very little limitation on usernames and as such characters such as quotes, braces, $, >, | etc are all allowed. Since the nss library is run by root, any shell escape will be ran as root.
In the current community version of tacacs nss library, the issue is mitigated by the fact that the useradd command is only ran if the user is found to exist on the tacacs server, so the bad username would have to already …
=> Use execle instead of popen in tacas nss to avoid shell escape exploits

build_debian.sh, sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
This makes sure the latest version of the Docker daemon is used.
- Microsoft ADO **(number only)**: 24405378
Booted on KVM setup, verified that docker containers came up. Also verified that the built image size is roughly the same as current KVM image.
=> Update the docker daemon to 24.0.2

src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py, src/sonic-bgpcfgd/tests/test_static_rt.py
fixes #15574 
fix static route uninstall issue when all nexthops are not reachable. 
the feature was working but the bug was introduced when support dynamic bfd enable/disable. 
If a static route is bfd protected, when all the bfd sessions are down and all the nexthop need to be removed from the static route, it fails because a kip condition is missing.
To support bfd config dynamic change and avoid race condition when delete static route, there is a skip checking for staticRouteMgr(appl_db) to check if the deletion should be skipped. Besides checking if the route exists in config_db, also need to check if the route is bfd protected.  
verified it both in UT and in real testbed.
=> [staticroutebfd] fix static route uninstall issue if no nexthop

src/sonic-bgpcfgd/staticroutebfd/main.py, src/sonic-bgpcfgd/tests/test_static_rt_bfd.py
use lower case for IPv6 address as internal key and bfd session key.
fixes #15764 
staticroutebfd uses the IPv6 address string as a key to create bfd session and cache the bfd sessions using it as a key.
When the IPv6 address string has uppercase letter in the static route nexthop list,  the string with uppercase letter key is stored in the cache, but the BFD STATE_DB uses lowercase for IPv6 address, so when the staticroutebfd get the bfd state event, it cannot find the bfd session in its local cache because of the letter case.
convert the IPv6 address string to lower case inside the staticroutebfd, and use the lowercase address to create BFD session.
Verified it both in UT and testbed.
=> [staticroutebfd]  fix ipv6 letter case issue

dockers/docker-sonic-mgmt/Dockerfile.j2
This is part of sonic-mgmt-docker Python3 migration project.
Currently Python3 packages are in the Python3 virtual environment. This PR will add Python3 packages to real file system.
After we migrate all script to use Python3 in real file system, the Python3 venv will be deleted.
After this PR, in sonic-mgmt-docker,
**Directly run cmd - pytest will use Python2's version.
python3 -m pytest will use Python3's version.**
- Microsoft ADO: 24397921
Modify sonic-mgmt-docker j2 script.
Build a private sonic-mgmt-docker and run basic test case with Python3.
=> Add Python3 packages to sonic-mgmt-docker

src/tacacs/pam/0006-Add-support-for-source-ip-address.patch, src/tacacs/pam/0007-Fix-memory-leak-when-parse-configuration.patch, src/tacacs/pam/0008-Extract-tacacs-support-functions-into-library.patch, src/tacacs/pam/0009-Add-setting-flag-for-authorization-and-accounting.patch, src/tacacs/pam/0010-handle-bad-password-set-by-sshd.patch, src/tacacs/pam/Makefile
This pull request extract tacacs support functions into library to share TACACS config file parse code with other project. Also fix memory leak issue in parse config code.
To support TACACS per command authorization, we need reuse the TACACS config file parse code in bash plugin project.
- Microsoft ADO **(number only)**: 24433713
Add libtacsupport.pc.in to extract tacacs support functions into library.
Fix memory leak issue in TACACS config parse code by convert the dynamic memory allocation memory to static memory allocation.
Pass all current UT.
Check shared library generated manually.
Extract tacacs support functions into library, this will share TACACS config file parse code with other project.
Also fix memory leak issue in parse config code.
Extract tacacs support functions into …
=> [202012] [TACACS+]: Extract tacacs support functions into library and fix memory leak issue. (#8659)

rules/dhcprelay.dep
Failed to build sonic-dhcp6relay_1.0.0-0_amd64.deb
src/dhcprelay has git submodule.
Dependency files by "git ls-files" are not picked files in submodules.
Add --recurse-submodules, work again.
make all
=> Pick dependency files in submodules.

build_debian.sh, files/build_templates/sonic_debian_extension.j2, rules/tacacs.mk, slave.mk, sonic-slave-buster/Dockerfile.j2, sonic-slave-jessie/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2, src/sonic-host-services/scripts/hostcfgd, src/tacacs/.gitignore, src/tacacs/audisp/Makefile, src/tacacs/audisp/patches/0001-Porting-to-sonic.patch, src/tacacs/audisp/patches/0002-Remove-user-secret-from-accounting-log.patch, src/tacacs/audisp/patches/0003-Add-local-accounting.patch, src/tacacs/audisp/patches/series
This pull request integrate audisp-tacplus to SONiC for per-command accounting.
- Microsoft ADO **(number only)**: 24433713
To support TACACS per-command accounting, we integrate audisp-tacplus project to sonic.
1. Add auditd service to SONiC
2. Port and patch audisp-tacplus to SONiC
UT with CUnit to cover all new code in usersecret-filter.c
Also pass all current UT.
N/A
Extract tacacs support functions into library, this will share TACACS config file parse code with other project.
Also fix memory leak issue in parse config code.
Add audisp-tacplus for per-command accounting.
=> [202012] [TACACS+] Add audisp-tacplus for per-command accounting. (#8750)

src/tacacs/pam/0008-Extract-tacacs-support-functions-into-library.patch
Fix libtacsupport.so  can't parse tacplus_nss.conf issue and not reset server list before parse config file issue.
- Microsoft ADO **(number only)**: 24433713
1. Fix libtacsupport.so can't parse tacplus_nss.conf correctly issue:
Support debug=on setting.
Support put server address and secret in same row.
2. Fix the parse_config_file method not reset server list before parse config file issue.
Fix libtacsupport.so  can't parse tacplus_nss.conf issue and not reset server list before parse config file issue.
UT with CUnit cover all code in this plugin.
Also pass all current UT.
N/A
Extract tacacs support functions into library, this will share TACACS config file parse code with other project.
Also fix memory leak issue in parse config code.
Fix libtacsupport.so  can't parse tacplus_nss.conf …
=> [202012] [TACACS+] Fix libtacsupport.so  can't parse tacplus_nss.conf issue and not reset server list before parse config file issue. (#8715)

src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py, src/sonic-ctrmgrd/ctrmgr/kube_commands.py, src/sonic-ctrmgrd/tests/kube_commands_test.py
When do clean up container images, current code has two bugs need to be fixed. And some variables' name maybe cause confused, change the variables' name.
- Microsoft ADO **(number only)**: 24502294
- We do clean up after tag latest successfully. But currently tag latest function only return 0 and 1, 0 means succeed and 1 means failed, when we get 1, we will retry, when we get 0, we will do clean up. Actually the code 0 includes another case we don't need to do clean up. The case is that when we are doing tag latest, the container image we want to tag maybe not running, so we can not tag latest and don't need to cleanup, we need to separate this case from 0, return -1 now.
- When local mode(v1) -> kube mode(v2) happens, one problem is how to handle the local image, there are two cases. one …
=> Container image clean up bug fix

files/image_config/logrotate/rsyslog.j2
For some devices whose log folder size is larger than 200M, for example, 256M, the LOG_FILE_ROTATE_SIZE_KB should be 16M. and 
THRESHOLD_KB=$((USABLE_SPACE_KB - (NUM_LOGS_TO_ROTATE * LOG_FILE_ROTATE_SIZE_KB * 2)))
= $(( (VAR_LOG_SIZE_KB * 90 / 100) - RESERVED_SPACE_KB)) -  (NUM_LOGS_TO_ROTATE * LOG_FILE_ROTATE_SIZE_KB * 2)))
= $(( (256M * 90 / 100) - 4096)) -  (8 * 16M * 2)))
the result would be a negative value 
24524827
Add a case for 400M, if the log folder size is between 200M and 400M, set the log file size to 2M
Do cmd "sudo logrotate -f /etc/logrotate.conf" on DUT which val/log folder size is 256M, and check the syslog.
=> update rsyslog log size conf

dockers/docker-ptf/Dockerfile.j2
This is primarily to fix a bug in scapy hitting an error when trying to listen on multiple interfaces in a single `sniff` call. This also upgrades it to the current latest version.
This also enables the `arp_responder.py` script in the sonic-mgmt repo to be converted to Python 3.
- Microsoft ADO **(number only)**: 24341833
Tested with the `arp_responder.py` script converted to Python 3, and ran `route/test_static_route.py` to at least exercise that script in the Python 3 virtualenv.
=> Upgrade scapy in the PTF's python3 virtualenv to 2.5.0

src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py, src/sonic-ctrmgrd/tests/ctrmgrd_test.py
Why I did it
During the upgrade process via k8s, the feature's systemd service will restart as well, all of the feature systemd service has restart number limit, and the limit number is too small, only three times. if fallback happens when upgrade, the start count will be 2, just once again, the systemd service will be down. So, need to bypass this. This restart function will be called when do local -> kube, kube -> kube, kube ->local, each time call this function, we indeed need to restart successfully, so do reset-failed every time we do restart. When need to go back to local mode, we do systemd restart immediately without waiting the default restart interval time so that we can reduce the container down time.
Work item tracking
Microsoft ADO (number only):
24172368
How I did it
Before …
=> [k8s]: Bypass the systemd service restart limit and do immediately restart when change to local mode (#15432)

src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py, src/sonic-ctrmgrd/ctrmgr/kube_commands.py, src/sonic-ctrmgrd/tests/kube_commands_test.py
Why I did it
When do clean up container images, current code has two bugs need to be fixed. And some variables' name maybe cause confused, change the variables' name.
Work item tracking
Microsoft ADO (number only): 24502294
How I did it
We do clean up after tag latest successfully. But currently tag latest function only return 0 and 1, 0 means succeed and 1 means failed, when we get 1, we will retry, when we get 0, we will do clean up. Actually the code 0 includes another case we don't need to do clean up. The case is that when we are doing tag latest, the container image we want to tag maybe not running, so we can not tag latest and don't need to cleanup, we need to separate this case from 0, return -1 now.
When local mode(v1) -> kube mode(v2) happens, one problem is how to handle the …
=> [ctrmgr]: Container image clean up bug fix (#15772)

platform/mellanox/mlnx-platform-api/sonic_platform/component.py
Add support for updating BIOS through dev signed ONIE. Add support for update BIOS using cap/cab files
Bios on new generation switch can come with a file type of cap or cab. Needs to add support to these file type.
Also ONIE version on new devices can have a suffix of 'dev'. 
Added cap & cab as possible component extensions for ComponentBIOS.
Update the ONIE version regex to include dev signed versions.
Update bios.
=> [Mellanox] Add support for BIOS update on Spectrum-4

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
The reset cause "reset_from_comex" has been removed by hw-management, hence removing it from platform API code
Remove reset_from_comex from reboot cause mapping
Manual test
=> [Mellanox] Remove reset_from_comex from reboot cause mapping

src/system-health/health_checker/hardware_checker.py, src/system-health/tests/test_system_health.py
Adjust PSU power threshold logic in system health.
Update the description message in PSU power threshold checking
`power of PSU x (xx w) exceeds threshold (xx w)` => `System power exceeds xx threshold (xx w)`
Manual test and unit test
=> Update the description message of PSU power threshold checking in system health

dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
1. sonic-build image side change to fix source interface selection in dual tor scenario.
dhcprelay related PR:
https://github.com/sonic-net/sonic-dhcp-relay/pull/42
2. Announce dhcprelay submodule to 6a6ce24([to invoke [#40](https://github.com/sonic-net/sonic-dhcp-relay/pull/40
) PR](https://github.com/sonic-net/sonic-dhcp-relay/pull/42))
- Microsoft ADO 24243215
run test case, dhcp_relay/test_dhcpv6_relay.py
=> [Master] fix v6relay dual tor source if selection issue, advance dhcprelay to 6a6ce24

build_debian.sh, dockers/docker-config-engine-bullseye/Dockerfile.j2, dockers/docker-config-engine-buster/Dockerfile.j2, sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
```
```
Error message:
```
....
WARNING: Discarding https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz …
```
=> [Build] Fix the PyYang python package installation issue

device/mellanox/x86_64-mlnx_msn2700-r0/pcie.yaml, device/mellanox/x86_64-mlnx_msn4600c-r0/pcie.yaml
Certain all-numeric device IDs of PCI devices in the pcie.yaml file are left unquoted, leading to false mismatch flags in the pcie daemon and subsequently leads to log flooding. This PR fixes that issue.
- Microsoft ADO **(number only)**: 24578930
Added quotes around numeric PCI devices in the pcie.yaml files of the following platforms:
x86_64-mlnx_msn2700-r0
x86_64-mlnx_msn4600c-r0
Install latest image after the merge and verify that syslogs are not flooded with PCI device mismatch errors
Quoted device IDs to prevent false flags in pcied
=> [master] Mellanox: 2700, 4600c - Quoted device IDs to prevent false flags in pcied

build_debian.sh, dockers/docker-config-engine-bullseye/Dockerfile.j2, dockers/docker-config-engine-buster/Dockerfile.j2, sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
Cherry pick from PR: https://github.com/sonic-net/sonic-buildimage/pull/15890
```
```
Error message:
```
....
WARNING: Discarding …
```
=> [Build][202205] Fix the PyYang python package installation issue (#15890)

dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
1. sonic-build image side change to fix source interface selection in dual tor scenario.
dhcprelay related PR:
https://github.com/sonic-net/sonic-dhcp-relay/pull/42
2. Announce dhcprelay submodule to 6a6ce24 to include [PR #42](https://github.com/sonic-net/sonic-dhcp-relay/pull/42)
- Microsoft ADO 24243215
run test case, dhcp_relay/test_dhcpv6_relay.py
=> [202205] fix v6relay dual tor source if selection issue, advance dhcprelay to 6a6ce24

rules/sonic-dash-api.dep
[Build] Fix the dash cache dependency issue
```
12:47:34  [ finished ] [ target/files/bullseye/ctrmgrd.service ]
12:47:36  fatal: Unable to hash src/sonic-dash-api/sonic-dash-api
12:47:36  make: *** [Makefile.cache:528: target/debs/bullseye/libdashapi_1.0.0_amd64.deb.smdep] Error 123
12:47:36  make: *** Waiting for unfinished jobs....
```
- Microsoft ADO **(number only)**: 24547630
=> [Build] Fix the dash cache dependency issue

build_debian.sh, dockers/docker-config-engine-buster/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
Cherry pick from PR: https://github.com/sonic-net/sonic-buildimage/pull/15890
```
```
Error message:
```
....
WARNING: Discarding …
```
=> [Build][202106] Fix the PyYang python package installation issue (#15890)

dockers/docker-sonic-mgmt/Dockerfile.j2
Upgrade celery in the python3 to 5.2.7,
Upgrade ipython to 8.12.2 since 5.4.1 requires prompt-toolkit<2.0.0,>=1.0.4, 
But celery 5.2.7 relies click-repl>=0.2.0 , click-repl>=0.2.0 relies prompt-toolkit>=3.0.36.
So upgrade ipython to resolve the prompt-toolkit version incompatible issue.
Upgrade celery in the python3 to 5.2.7
Upgrade ipython to 8.12.2
=> [sonic-mgmt docker image] Upgrade celery in the python3 to 5.2.7, upgrade ipython to 8.12.2

rules/sairedis.mk, rules/swss-common.mk, rules/syncd.mk, slave.mk
Add support for a separate DEB_BUILD_PROFILES environment variable, to be able to set build profiles. This may be used to specify whether python 2 bindings/libraries should be built, or what configuration options should be specified for a package.
This also makes it easier to append/remove build profiles from our rules files, which will be needed for the sairedis build.
- Microsoft ADO **(number only)**: 24405994
=> Add support for deb build profiles env variable

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/mux-linkmgr.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/mux-linkmgr.json, src/sonic-yang-models/yang-models/sonic-mux-linkmgr.yang
Add yang model for `MUX_LINKMGR|MUXLOGGER`.
sign-off: Jing Zhang zhangjing@microsoft.com 
18445750
UTs.
```
collected 3 items
tests/test_sonic_yang_models.py ..                                       [ 66%]
tests/yang_model_tests/test_yang_model.py .                              [100%]
============================== 3 passed in 2.03s ===============================
```
=> [YANG] add yang model for `MUX_LINKMGR|MUXLOGGER`

slave.mk
Fix some of the patches in .patches folder not applied issue.
The command "quilt applied" only lists the applied patches, if some of the patches have issues, then the patches will not be applied when you run the build command again.
- Microsoft ADO **(number only)**: 24410730
1. Run the command to apply the patches without any conditions.
2. If failed, check if the failure reason is "series fully applied".
=> [Build] Fix some of the patches not applied issue

build_debian.sh, dockers/docker-config-engine-buster/Dockerfile.j2, dockers/docker-platform-monitor/Dockerfile.j2, sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
Cherry pick from PR: https://github.com/sonic-net/sonic-buildimage/pull/15890
```
```
Error message:
```
....
WARNING: Discarding …
```
=> [Build][202111] Fix the PyYang python package installation issue (#15890)

build_debian.sh, dockers/docker-config-engine-buster/Dockerfile.j2, dockers/docker-platform-monitor/Dockerfile.j2, dockers/docker-sonic-mgmt-framework/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
Cherry pick from PR: https://github.com/sonic-net/sonic-buildimage/pull/15890
```
```
Error message:
```
....
WARNING: Discarding …
```
=> [Build][202012] Fix the PyYang python package installation issue (#15890)

files/build_templates/init_cfg.json.j2
There is a redundant line in init_cfg.json.j2. It would cause pmon service always has "delayed=False". However, we know that PMON has a timer now. So, I try to fix it here.
Remove the redundant line
=> Fix issue: set delayed attribute to true for platform monitor service

dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
1. sonic-build image side change to fix source interface selection in dual tor scenario.
dhcprelay related PR:
https://github.com/sonic-net/sonic-dhcp-relay/pull/40
2. Announce dhcprelay submodule to 3578eb3 (to invoke [#40](https://github.com/sonic-net/sonic-dhcp-relay/pull/40
) PR)
- Microsoft ADO 24243215
run test case, dhcp_relay/test_dhcpv6_relay.py
=> [202012] dhcprelay add Loopback0 as source interface in dualtor scenario 

files/image_config/monit/conf.d/sonic-host
This depends on PR https://github.com/sonic-net/sonic-utilities/pull/2840.
And it is to enable `dualtor_neighbor_check.py` as a periodical check.
- Microsoft ADO **(number only)**: 22571694
Verify on testbed, for any inconsistencies, `monit` will write `ERROR` syslogs:
```
Jul 10 07:05:12.014885 lab-dev-1 ERR dualtor_neighbor_check.py: Found neighbors that are inconsistent with mux states: ['192.168.0.7', '192.168.0.35']
Jul 10 07:05:12.017086 lab-dev-1 ERR dualtor_neighbor_check.py: NEIGHBOR      MAC                PORT        MUX_STATE    IN_MUX_TOGGLE    NEIGHBOR_IN_ASIC    TUNNERL_IN_ASIC    HWSTATUS
Jul 10 07:05:12.017251 lab-dev-1 ERR dualtor_neighbor_check.py: ------------  -----------------  ----------  -----------  ---------------  ------------------  ----------------- …
```
=> [monit][dualtor] Periodically check mux neighbors consistency

.azure-pipelines/template-skipvstest.yml
1. Line:7 will exit when k8s file didn't change.
2. Use 'System.PullRequest.TargetBranchName' instead of 'System.PullRequest.TargetBranch'. Because git server in AzDevOps don't support 'System.PullRequest.TargetBranch'.
- Microsoft ADO **(number only)**:    24636791
=> [ci] Fix pipeline 'Check if vstest is needed.' issue.

src/sonic-py-common/sonic_py_common/device_info.py
Change-Id: Ifeb78f366d80e70043db1f9828f2f75a8a710f46
fixes #15375 
get_system_mac was returning 'None' mac for system without eeprom. 
get_system_mac for marvell platform checks for mac in eeprom, profile.ini(hwsku file) and eth0. Check for valid mac returned by syseeprom was incorrect. Which was resulting in bypassing mac get from profile.ini and eth0.
get_system_mac already has a logic to get first valid mac.
Removed null check for mac returned by eeprom.
Corrected the check for profile.ini file by checking if file exist.
Executed sonic-cfggen to check valid mac address is getting configured in config_db.json with/without profile.ini.
=> [Marvell] Fix get_system_mac for system without eeprom

src/sonic-yang-models/tests/yang_model_tests/tests/snmp.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/snmp.json, src/sonic-yang-models/yang-models/sonic-snmp.yang
https://github.com/sonic-net/sonic-utilities/pull/472 Added SNMP_AGENT_ADDRESS_CONFIG table in config db.
This PR is to add corresponding YANG model for that table.
Added YANG modesl for SNMP_AGENT_ADDRESS_CONFIG.
keys: agent_ip, port number, vrf.
CLI implementaion checks if agent_ip, port number already exists in CONFIG_DB table, if it does, then new entry is not added.
So added another condition to ensure combination of agent_ip and port is unique.
Below is an example of how data looks like in DB:
```
127.0.0.1:6379[4]> HGETALL  "SNMP_AGENT_ADDRESS_CONFIG|10.1.1.1|161|foo"
1) "NULL"
2) "NULL"
127.0.0.1:6379[4]> HGETALL "SNMP_AGENT_ADDRESS_CONFIG|10.1.0.32|161|"
1) "NULL"
2) "NULL"
```
Added unit-test for various combinations and ensures that it passes.
=> [YANG][SNMP]: Add YANG model for SNMP_AGENT_ADDRESS_CONFIG table

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.init
ADO: 24524572
[E1031] fix pca9548 initializes failed occasionally in stress test. When failure happened, ismt i2c bus hang up and need power cycle to recover it.
Add 0.5s delay between setuping and configuring pca9548 i2c mux.
Reboot stress test at least 100 times without failure.
=> [E1031] fix pca9548 initializes failed occasionally

platform/innovium/sonic-platform-modules-cel/midstone-200i/modules/mc24lc64t.c
Why I did it
Midstone platform has compilation error in master branch, fixed the same.
How I did it
Due to bullseye migration i2c_new_dummy API is deprecated modified with i2c_new_dummy_device.
Verified target/debs/bullseye/platform-modules-midstone-200i_0.2.2_amd64.deb is generated
=> [Celestica]Midstone Compilation Error in master branch

rules/protobuf.mk
tar: target/debs/bullseye/libprotoc_3.21.12-3_amd64.deb: Cannot stat: No such file or directory
The protoc-dev library with the wrong declaration.
- Microsoft ADO **(number only)**: 24707066
Revise the wrong declaration from: 
`PROTOC = libprotoc_$(PROTOBUF_VERSION_FULL)_$(CONFIGURED_ARCH).deb` to `PROTOC_DEV = libprotoc-dev$(PROTOBUF_VERSION_FULL)_$(CONFIGURED_ARCH).deb`
Check Azp log error.
=> [protobuf]: Fix protoc-dev cache error

azure-pipelines.yml
Use remote PR test template from sonic-mgmt master to run PR test.
Signed-off-by: Chun'ang Li [chunangli@microsoft.com](mailto:chunangli@microsoft.com)
- Microsoft ADO **(24658850)**:
Modify PR test azure pipeline yml file.
PR test executing normally.
=> [CI/CD] Use remote PR test template from sonic-mgmt master to run PR test

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/mux-linkmgr.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/mux-linkmgr.json, src/sonic-yang-models/yang-models/sonic-mux-linkmgr.yang
Adding yang model for CONFIG_DB table `MUX_LINKMGR|SERVICE_MGMT`.
- Microsoft ADO **(number only)**: 18445751
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-yang-models
plugins: pyfakefs-5.2.3, cov-2.10.1
collected 3 items                                                                                                                                                                           
tests/test_sonic_yang_models.py .. …
```
=> [YANG] add `MUX_LINKMGR|SERVICE_MGMT`

device/celestica/x86_64-cel_e1031-r0/platform_reboot, device/celestica/x86_64-cel_e1031-r0/platform_update_reboot_cause
E1031(HLX): add platform specific cold reboot support, using CPLD board level power cycle functionality for cold reboot.
Use the CPLD to trigger board level power cycle when cold reboot
Do reboot stress test and check the reboot cause history
=> [E1031] add platform specific reboot command support

platform/mellanox/mlnx-sai/Makefile
There is an unnecessary file manipulation in the SAI make file, "chmod a+x autogen.sh", however file "autogen.sh" has never been executed during SAI binary building, so it shall be removed.
At the same time, in the new SAI code,  "autogen.sh" has been deleted since it's not needed anymore, if keep this line will cause build failure when upgrading to the new SAI.
Remove the unnecessary line in the Make file
Make a Mellanox SONiC image, and make sure SAI can be built and installed correctly.
=> [Mellanox] Remove unnecessary file manipulation in the SAI Make file

device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot
When a kernel crash occurs, the system will reboot to the kdump capture kernel if kdump is enabled (`config kdump enable`). In the kdump capture boot, it only stores the crash information, and then reboot the system to a normal boot.
In this boot, no SONiC service is started but it invokes `reboot` which is actually the SONiC reboot that depends on SONiC services. There is a logic to skip all SONiC stuff and invoke platform reboot in SONiC reboot to avoid issues.
However, on Nvidia platforms, the platform reboot still depends on SONiC services, which can cause issues.
So, the Debian reboot is called directly in platform reboot if it is invoked from the kdump capture boot.
Manual test
=> [Mellanox] Use Debian reboot in Nvidia platform reboot when it is invoked from kdump capture boot

files/scripts/syncd.sh
The hw resources should be released before updating firmware.
Added logic to release hw resources in `syncd.sh` script
Scenario:
1. Write a bash script to kill `mlxfwmanager` process in the infinite loop and run it in the background.
```
#!/bin/bash
while :;
do
pkill -9 mlnxfwmanager
done
```
2. Try to start the `mlnfwmanager` utility a few times.
3. Stop the bash script.
4. Start the `mlxfwmanager` and make sure that the semaphore is taken.
5. Run the `config reload -y` command and make sure that all the dockers are in up state.
=> [syncd.sh] Clear semaphore before updating firmware

files/scripts/syncd.sh
Backport of https://github.com/sonic-net/sonic-buildimage/pull/15818 
The hw resources should be released before updating firmware.
Added logic to release hw resources in `syncd.sh` script
Scenario:
1. Write a bash script to kill `mlxfwmanager` process in the infinite loop and run it in the background.
```
#!/bin/bash
while :;
do
pkill -9 mlnxfwmanager
done
```
2. Try to start the `mlnfwmanager` utility a few times.
3. Stop the bash script.
4. Start the `mlxfwmanager` and make sure that the semaphore is taken.
5. Run the `config reload -y` command and make sure that all the dockers are in up state.
=> [202211][syncd.sh] Clear semaphore before updating firmware (#15818)

dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2, src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/packet_chassis.conf, src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/voq_chassis.conf
What I did:
Fix the Loopback0 IPv6 address of LC's in chassis not reachable from peer devices.
Why I did:
For Ipv6 Loopback0 address we only advertise /64 subnet to the peer devices. However, in case of chassis each LC will have it own /128  address of that /64 subnet . Since this /128 address does not get advertised peer devices can-not ping/reach the LC's loopback0.
How I fix:
Advertise /128 Loopback0 Ipv6 address only between i-BGP peers. This way even though /64 is advertised to e-BGP peer devices when packet reaches any of LC's it can reach the appropriate LC's.
How I verify:
Manual verification
UT added for same.
=> [chassis] Fix the Loopback0 IPv6 address of LC's in chassis not reachable from peer devices

dockers/docker-snmp/snmpd.conf.j2
fixes: https://github.com/sonic-net/sonic-buildimage/issues/16001
Caused by: https://github.com/sonic-net/sonic-buildimage/pull/15487
The above PR introduced change to use Management and Loopback Ipv4 and ipv6 addresses as snmpagent address in snmpd.conf file.
With this change, if Link local IP address is configured as management or Loopback IPv6 address, then snmpd tries to open socket on that ipv6 address and fails with the below error:
```
Error opening specified endpoint "udp6:[fe80::5054:ff:fe6f:16f0]:161"
Server Exiting with code 1
```
From RFC4007, if we need to specify non-global ipv6 address without ambiguity, we need to use zone id along with the ipv6 address: <address>%<zone_id>
Reference: https://datatracker.ietf.org/doc/html/rfc4007
Modify …
=> [SNMP][IPv6]: Fix to use link local IPv6 address as snmp agentAddress

dockers/docker-sonic-mgmt/Dockerfile.j2
1. Remove useless temporary protobuf deb packages
2. Import dash_api to python3 env
1. There are some temporary Debian packages,protobuf packages, needs to be deleted
2. The dash-api was installed in the system folder that cannot be imported by the virtual python3 environment. But the testcases of DASH in sonic-mgmt are executed in virtual python3 environment.
- Microsoft ADO **(number only)**: 17417902
1. Add missed `&&` so that all protobuf debian packaged can be downloaded to the /tmp folder
2. Add ` --system-site-packages ` to env-python so that the system library can be accessed by virtual environment
Check the dash_api can be imported in env-python3
```
AzDevOps@46a900cf8477:~$ source env-python3/bin/activate
(env-python3) zegan@46a900cf8477:~$ ls
bin  env-python3
(env-python3) …
```
=> [sonic-mgmt]: Remove temporary files and import dash_api to python3 env

rules/phy-credo.mk
1. A recent migration of SonicV2Connector from swsssdk to swsscommon.swsscommon broke phy-credo.
2. Support 40G/100G speed change on 7800R3-48CQ2-LC
N/A
1. Change the import path while keeping a fallback on the previous one for 202205.
2. Handle the lane mapping for speed change.
This updated of phy-credo package was already merged into the master branch (https://github.com/sonic-net/sonic-buildimage/commit/1302a31eee5f5284eccb13d0f16ba229cfd528bf). for 202205, I have verified that:
1. phy-credo.service no longer fails due to an import error
2. links come up after the speed change between 40G and 100G.
N/A
- [x ] <202205>
N/A
N/A
N/A
=> [Arista] Update phy-credo package to support 40G/100G speed change on 7800R3-48CQ2-LC

build_image.sh
To report a build failure if the raw image generation is not successful.
If the 'build' install mode of the installer exits with an error, delete the incomplete raw image file generated.
Modify the raw image disk size to an insufficient value and verify that the raw image build fails.
```
make target/sonic-broadcom.raw
+++ --- Making target/sonic-broadcom.raw --- +++
BLDENV=stretch make -f Makefile.work stretch
make[1]: Entering directory '/home/abalac/repos/201811/raw_image/sonic-buildimage'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 27736  100 27736    0     0  24654      0  0:00:01  0:00:01 --:--:-- 24676
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total …
```
=> [build][201811] Make the build to fail if raw image generation is not successful

rules/protobuf.mk
The protoc-dev isn't used by SONiC, but it was added to the derived package.
- Microsoft ADO **(number only)**: 17417902
Remove protoc-dev from protobuf.mk
Check Azp
=> [fixbug]: Remove useless protobuf package

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.install, platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.postinst, platform/broadcom/sonic-platform-modules-cel/haliburton/script/cpu_wdt, platform/broadcom/sonic-platform-modules-cel/haliburton/systemd/cpu_wdt.service
Enable CPU watchdog on Celestica-E1031.
- Microsoft ADO **(number only)**: 24792364
Add a system service `cpu_wdt` to enable CPU watchdog and send keep-alive signal to watchdog periodically.
Build SONiC image and installed on physical device. Can see the `cpu_wdt` work as expected.
```
$ sudo systemctl status cpu_wdt.service
● cpu_wdt.service - CPU WDT
Loaded: loaded (/lib/systemd/system/cpu_wdt.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2023-08-09 14:37:12 UTC; 1min 11s ago
Main PID: 324656 (cpu_wdt)
Tasks: 2 (limit: 2329)
Memory: 2.1M
CGroup: /system.slice/cpu_wdt.service
├─324656 /bin/bash /usr/local/bin/cpu_wdt start
└─325540 sleep 60
Aug 09 14:37:12 e1031-1 systemd[1]: Started CPU WDT.
Aug 09 14:37:12 e1031-1 cpu_wdt[324657]: Enable CPU WDT..
Aug 09 …
```
=> [Celestica-E1031] Enable CPU watchdog

dockers/docker-orchagent/orchagent.sh
Background running lua script may cause redis-server quite busy if batch size is 8192.
If handling time exceeded default 5s, the redis-server will not response to other process and will cause syncd crash.
```
Aug  9 07:46:29.512326 str-s6100-acs-5 INFO database#supervisord: redis 68:M 09 Aug 2023 07:46:29.511 # Lua slow script detected: still in execution after 5186 milliseconds. You can try killing the script using the SCRIPT KILL command. Script SHA1 is: 88270a7c5c90583e56425aca8af8a4b8c39fe757
Aug  9 07:46:29.523716 str-s6100-acs-5 ERR syncd#syncd: :- checkReplyType: Expected to get redis type 5 got type 6, err: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.
Aug  9 07:46:29.524818 str-s6100-acs-5 INFO syncd#supervisord: syncd terminate called …
```
=> Change orchagent pop batch size from 8192 to 1024

dockers/docker-orchagent/orchagent.sh
Background running lua script may cause redis-server quite busy if batch size is 8192.
If handling time exceeded default 5s, the redis-server will not response to other process and will cause syncd crash.
```
Aug  9 07:46:29.512326 str-s6100-acs-5 INFO database#supervisord: redis 68:M 09 Aug 2023 07:46:29.511 # Lua slow script detected: still in execution after 5186 milliseconds. You can try killing the script using the SCRIPT KILL command. Script SHA1 is: 88270a7c5c90583e56425aca8af8a4b8c39fe757
Aug  9 07:46:29.523716 str-s6100-acs-5 ERR syncd#syncd: :- checkReplyType: Expected to get redis type 5 got type 6, err: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.
Aug  9 07:46:29.524818 str-s6100-acs-5 INFO syncd#supervisord: syncd terminate called …
```
=> [202205]Change orchagent pop batch size from 8192 to 1024

rules/docker-lldp.mk
Reduce linux capabilities in privileged flag, retain NET_ADMIN capability
=> [docker-lldp] limit privileged flag for lldp container

sonic-slave-bullseye/Dockerfile.j2
It appears that this was initially added to provide the `git-retry` command (which doesn't appear to be used today). However, this repo is now also providing `bazel` (which is actually used in our build today), and this command (along with `git-retry`) expects some `vpython3` binary to be set up/installed. The sonic-p4rt code runs `bazel`, which means this depot_tools version would get called instead of the regular system-installed version.
Rather than going through the process of setting up/installing vpython3, just get rid of this repo.
Fixes #16087.
=> Remove depot_tools repo

rules/docker-teamd.mk
Reduce linux capabilities in privileged flag, retain NET_ADMIN capability
=> [docker-teamd] limit privileged flag for teamd container

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot
Update the platform_reboot of Nokia Platform IXR-7250E-36x400G to displays the correct reboot-cause history when reboot from supervisor card. 
Modify the platform_reboot script to copy the correct reboo-cause.txt file from NDK to the /host/reboot-cause directory at the down cycle when the reboot is issued from Supervisor (for both reboot  right after install a new image and normal reboot)
1)  Execute a CLI command "sudo reboot" on the Supervisor
2)  After system is up, on the Linecard, execute the CLI show reboot-cause history
```
Name                 Cause                                                                           Time                             User    Comment
------------------- …
```
=> [Nokia][DeviceData] Update the Nokia platform IXR-7250E device data

device/arista/x86_64-arista_7060dx5_64s/Arista-7060DX5-64S/hwsku.json, device/arista/x86_64-arista_7060dx5_64s/Arista-7060DX5-64S/port_config.ini, device/arista/x86_64-arista_7060dx5_64s/Arista-7060DX5-64S/th4-a7060dx5-64s.config.bcm, device/arista/x86_64-arista_7060dx5_64s/platform.json, device/arista/x86_64-arista_7060px5_64s/Arista-7060PX5-64S/blackhawk.xml, device/arista/x86_64-arista_7060px5_64s/sensors.conf
Misc platform improvements for DCS-7060DX5-64S.
Includes changes for:
* Add 7060DX5-64S brcm tunnel config support
* Set port config ENABLE:0 in 7060DX5-64S brcm config
* Sensor.conf fixes
* SFP port support
* Add copper 50g tuning to babbagelp
Commits describe the changes
Fixes have been uncovered and validated in our in house testing and running sonic-mgmt testing on DCS-7060DX5-64S.
Misc platform improvements for DCS-7060DX5-64S.
=> Misc platform improvements for DCS-7060DX5-64S

src/sonic-py-common/sonic_py_common/multi_asic.py
Few commands in multiasic platforms when run with the "sudo ip netns exec asic0 <show cmd>" option was taking like 15 mins to get the o/p. This behavior of sudo getting hung was seen by just doing this 
jujoseph@svcstr-server-2:~ sudo ip netns exec asic0 bash
jujoseph@svcstr-server-2:~ sudo ls
The reason was found that when a show command is issued, there is an API to get the current namespace 
```
def get_current_namespace(pid=None):
154     """
155     This API returns the network namespace in which it is
156     invoked. In case of global namepace the API returns None
157     """
158 
159     net_namespace = None
160     command = ['sudo', '/bin/ip', 'netns', 'identify', "{}".format(os.getpid() if not pid else pid)]
161     proc = …
```
=> [multi-asic] sudo not required explicitly as /bin/ip netns identify present in sudoers

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Change Mellanox platform API implementation to use ASIC driver sysfs for the module operational state and status error fields.
Modify the `platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py` file by change the call of sx_mgmt_phy_module_info_get() SDK API to sysfs
1. Simulate the `unplug` cable event
2. Check the CLI output
- `sfputil show presence`
- `sfputil show error-status -hw`
3. Simulate the `plug` cable event
4. Repeat 2 step
=> [sysfs] Change SDK API sx_mgmt_phy_module_info_get() to sysfs

build_debian.sh, files/image_config/systemd/systemd-udevd/fix-udev-rule-may-fail-if-daemon-reload-command-runs.patch
Backport https://github.com/sonic-net/sonic-buildimage/pull/15253
A workaround to back port the fix for a systemd issue.
The systemd issue: https://github.com/systemd/systemd/issues/24668
The systemd PR to fix the issue: https://github.com/systemd/systemd/pull/24673/files
The formal solution should upgrade systemd to a version that contains the fix. But, systemd is a very basic service, upgrading systemd requires heavy test. 
Copy the correct systemd-udevd.service file in build time 
```
SONiC Software Version: SONiC.fix-udev.3-b65c7bdec_Internal
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: b65c7bdec
Build date: Mon Jun 19 10:54:50 UTC 2023
Built by: sw-r2d2-bot@r-build-sonic-ci02-241
Platform: …
```
=> [202205] Fix issue: systemctl daemon-reload would sporadically cause udev handler fail

src/sonic-yang-models/tests/yang_model_tests/tests/acl.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json, src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Fix #16190 .
- Microsoft ADO **(number only)**: 24905710
Update Yang definition of `IN_PORTS` and `OUT_PORTS` to string.
Since we cannot split the string with comma (`,`) and validate each substring is a valid SONiC port name. The only restriction for them is must be a `string`.
1. Verified by building `sonic_yang_models-1.0-py3-none-any.whl`. While building the target package, unit tests were run and passed.
2. Build a SONiC image based on 202205 branch and installed on physical DUT. Re try the steps in #16190 and can see below success response:
```
$ sudo config apply-patch patch.json
Patch Applier: Patch application starting.
Patch Applier: Patch: [{"op": "add", "path": "/ACL_RULE/SAMPLE_ACL_TABLE|RULE_3000", "value": {"PACKET_ACTION": "FORWARD", "PRIORITY": "7000", "IN_PORTS": …
```
=> [YANG SONIC-ACL] Fix Yang definition of IN_PORTS and OUT_PORTS

platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py, platform/mellanox/mlnx-platform-api/tests/test_watchdog.py
watchdogutil uses platform API watchdog instance to control/query watchdog status. In Nvidia watchdog status, it caches "armed" status in a object member "WatchdogImplBase.armed". This is not working for CLI infrastructure because each CLI will create a new watchdog instance, the status cached in previous instance will totally lose. Consider following commands:
```
admin@sonic:~$ sudo watchdogutil arm -s 100      =====> watchdog instance1, armed=True
Watchdog armed for 100 seconds
admin@sonic:~$ sudo watchdogutil status             ======> watchdog instance2, armed=False
Status: Unarmed
admin@sonic:~$ sudo watchdogutil disarm            =======> watchdog instance3, armed=False
Failed to disarm Watchdog
```
Use sysfs to query watchdog status
Manual test …
=> [Mellanox] Fix issue: watchdogutil command does not work

files/build_templates/docker_image_ctl.j2, files/image_config/config-setup/config-setup, files/image_config/warmboot-finalizer/finalize-warmboot.sh, files/scripts/swss.sh, files/scripts/syncd_common.sh
Cherypick of #15685
MSFT ADO: 24274591
Two changes:
There are multiple places where same incorrect logic is used.
Current logic (`until [[ $($SONIC_DB_CLI CONFIG_DB GET "CONFIG_DB_INITIALIZED") ]];`) will always result in pass, irrespective of the result of GET operation.
```
root@str2-7060cx-32s-29:~# sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED"
1
root@str2-7060cx-32s-29:~# until [[ $(sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED") ]]; do echo "entered here"; done
root@str2-7060cx-32s-29:~# 
root@str2-7060cx-32s-29:~# 
root@str2-7060cx-32s-29:~# sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED"                                             
0
root@str2-7060cx-32s-29:~# until [[ $(sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED") ]]; do echo "entered here"; done …
```
=> [202305] Fix CONFIG_DB_INITIALIZED flag check logic and set/reset flag for warmboot

files/build_templates/docker_image_ctl.j2, files/image_config/config-setup/config-setup, files/image_config/warmboot-finalizer/finalize-warmboot.sh, files/scripts/swss.sh, files/scripts/syncd_common.sh
Cherry pick of #15685
MSFT ADO: 24274591
Two changes:
There are multiple places where same incorrect logic is used.
Current logic (`until [[ $($SONIC_DB_CLI CONFIG_DB GET "CONFIG_DB_INITIALIZED") ]];`) will always result in pass, irrespective of the result of GET operation.
```
root@str2-7060cx-32s-29:~# sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED"
1
root@str2-7060cx-32s-29:~# until [[ $(sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED") ]]; do echo "entered here"; done
root@str2-7060cx-32s-29:~# 
root@str2-7060cx-32s-29:~# 
root@str2-7060cx-32s-29:~# sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED"                                             
0
root@str2-7060cx-32s-29:~# until [[ $(sonic-db-cli CONFIG_DB GET "CONFIG_DB_INITIALIZED") ]]; do echo "entered here"; done …
```
=> [202012] Fix CONFIG_DB_INITIALIZED flag check logic and set/reset flag for warmboot 

Makefile.work
Fix: https://github.com/sonic-net/sonic-buildimage/issues/16086
faketime package url expired. It breaks 201911 build.
Update package url.
- Microsoft ADO **(number only)**:  24930879
=> Fix faketime package downloading issue.

platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py, platform/mellanox/mlnx-platform-api/tests/test_watchdog.py
Backport https://github.com/sonic-net/sonic-buildimage/pull/16091 to 202205
watchdogutil uses platform API watchdog instance to control/query watchdog status. In Nvidia watchdog status, it caches "armed" status in a object member "WatchdogImplBase.armed". This is not working for CLI infrastructure because each CLI will create a new watchdog instance, the status cached in previous instance will totally lose. Consider following commands:
```
admin@sonic:~$ sudo watchdogutil arm -s 100      =====> watchdog instance1, armed=True
Watchdog armed for 100 seconds
admin@sonic:~$ sudo watchdogutil status             ======> watchdog instance2, armed=False
Status: Unarmed
admin@sonic:~$ sudo watchdogutil disarm            =======> watchdog instance3, armed=False
Failed to disarm Watchdog
```
- …
=> [202205] [Mellanox] Fix issue: watchdogutil command does not work

src/sonic-py-common/sonic_py_common/multi_asic.py
Cherry-pick PR :https://github.com/sonic-net/sonic-buildimage/pull/16115
- Microsoft ADO **(number only)**: 24914440
Cherry-pick PR :https://github.com/sonic-net/sonic-buildimage/pull/16115
=> sudo not required explicitly as /bin/ip netns identify is part of READ_ONLY_CMDS in sudoers file

device/mellanox/x86_64-nvidia_sn5600-r0/ACS-SN5600/sai_5600.xml, device/mellanox/x86_64-nvidia_sn5600_simx-r0/ACS-SN5600/sai_5600.xml
**DEPENDS:**
1. https://github.com/sonic-net/sonic-swss/pull/2564
**HLD:** https://github.com/sonic-net/SONiC/pull/1084
* Enabled port late create on SN5600 Spectrum-4 switch boots up with no ports
* N/A
* Updated SAI xml config file
* N/A
* N/A
```
'//||\\`
''``
```
=> [Mellanox] [PPI] Enable global port late create for SN5600

platform/mellanox/mlnx-fw-upgrade.j2
Use "{#-" and "-#}" to mark comments in jinja template
=> Fix issue: unprintable character is rendered when handling comments in j2

src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/qosmaps.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json, src/sonic-yang-models/yang-models/sonic-port-qos-map.yang
Add yang model for scheduler in PORT_QOS_MAP
unit test
=> Add yang model for scheduler in PORT_QOS_MAP

src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py, src/sonic-yang-models/tests/yang_model_tests/tests/acl.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json, src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Fix #16243 
- Microsoft ADO **(number only)**: 24909793
1. Update Yang definition of `ACL_TABLE_TYPE`.
2. Update existing testcase.
3. Add new testcase to cover lowercase key scenario.
1. Verified by building `sonic_yang_models-1.0-py3-none-any.whl`. While building the target package, unit tests were run and passed.
=> [YANG SONIC-ACL] Fix Yang definition of ACL_TABLE_TYPE

platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py, platform/mellanox/mlnx-platform-api/tests/test_watchdog.py
Backport PR https://github.com/sonic-net/sonic-buildimage/pull/16091 to 202211
watchdogutil uses platform API watchdog instance to control/query watchdog status. In Nvidia watchdog status, it caches "armed" status in a object member "WatchdogImplBase.armed". This is not working for CLI infrastructure because each CLI will create a new watchdog instance, the status cached in previous instance will totally lose. Consider following commands:
```
admin@sonic:~$ sudo watchdogutil arm -s 100      =====> watchdog instance1, armed=True
Watchdog armed for 100 seconds
admin@sonic:~$ sudo watchdogutil status             ======> watchdog instance2, armed=False
Status: Unarmed
admin@sonic:~$ sudo watchdogutil disarm            =======> watchdog instance3, armed=False
Failed to disarm Watchdog
```
- …
=> [202211] [Mellanox] Fix issue: watchdogutil command does not work (#16091)

src/sonic-build-hooks/hooks/curl
To support SKIP_BUILD_HOOK for curl command so the targets downloaded by curl (SONIC_ONLINE_DEBS, SONIC_ONLINE_FILES) can utilize it.
Add a logic to invoke a real command instead of a `download_packages()` (the same way it's done for wget)
Add an online target (with URL attribute).
Add the "SKIP_VERSION=y" to this target.
Check that download_packages is not invoked.
=> [build] add SKIP_BUILD_HOOK support for curl

src/sonic-frr/patch/0011-bgpd-avoid-notify-race-between-io-and-main-pthreads.patch, src/sonic-frr/patch/series
Cherry-Pick [#11926](https://github.com/FRRouting/frr/pull/11926) into 202012 
- Microsoft ADO **(17850717)**:
Create patch file to avoid notify race between io and main pthreads.
PR test, physical DUT for bgp related regression tests.
=> [sonic-frr] avoid notify race between io and main pthreads

device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm, src/sonic-device-data/tests/permitted_list
Update CPU transmitted packets to q=7 so it doesn't get impacted by other lossy traffic
- Microsoft ADO **(24164290)**:
Updated config file for affected HWSKUs as well as saibcm
It is verified on sonic chassis to be working fine.
=> Update CPU transmitted packets to queue 7 for chassis

azure-pipelines.yml
Test_telemetry test module is currently failing at “test_on_change_updates” as the code to support the test is not in 202211,
Skip the newly added test within test_telemetry for 202211 for now
=> [PRTest, 202211] Skip telemetry/test_telemetry.py::test_on_change_updates

device/mellanox/x86_64-nvidia_sn5600-r0/ACS-SN5600/sai_5600.xml, device/mellanox/x86_64-nvidia_sn5600_simx-r0/ACS-SN5600/sai_5600.xml
**DEPENDS:**
1. https://github.com/sonic-net/sonic-swss/pull/2821
**HLD:** https://github.com/sonic-net/SONiC/pull/1084
* Enabled port late create on SN5600 switch boots up with no ports
* N/A
* Updated SAI xml config file
Run sonic-mgmt tests fastboot
* N/A
* N/A
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/15866
```
'//||\\`
''``
```
=> [202211] [Mellanox] [PPI] Enable global port late create for SN5600 (#15866)

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/dhcp_server_ipv4.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/dhcp_server_ipv4.json, src/sonic-yang-models/yang-models/sonic-dhcp-server-ipv4.yang
https://github.com/sonic-net/sonic-buildimage/pull/15955 import sonic-vlan in yang model, which would cause YANG backlink issue. So https://github.com/sonic-net/sonic-buildimage/pull/15955 was reverted by https://github.com/sonic-net/sonic-buildimage/pull/16322.
This PR is re-submitted of https://github.com/sonic-net/sonic-buildimage/pull/15955 without import sonic-vlan.
Add yang model for IPv4 DHCP Server.
- Microsoft ADO **(number only)**: 24905905
Add yang model for IPv4 DHCP Server.
Add four new tables: DHCP_SERVER_IPV4, DHCP_SERVER_IPV4_CUSTOMIZED_OPTIONS, DHCP_SERVER_IPV4_RANGE, DHCP_SERVER_IPV4_PORT.
Add related unit test.
HLD: https://github.com/yaqiangz/SONiC/blob/master_dhcp_server_hld/doc/dhcp_server/port_based_dhcp_server_high_level_design.md#rev-01
Build sonic_yang_models …
=> [yang][dhcp_server] Add dhcp_server_ipv4 yang model

src/sonic-frr/patch/0021-zebra-remove-duplicated-nexthops-when-sending-fpm-msg.patch, src/sonic-frr/patch/series
Fixes #15803 
In SONiC chassis, routes have recursive nexthop resolution when the routes are learnt from remote linecard. 
In some cases after recursive nexthop resolution the number of nexthop for a route could reach `256`.
Zebra ran out of space when filling up 256 nexthops which causes zebra crash.
- Microsoft ADO **(24997365)**:
Create a patch to port https://github.com/FRRouting/frr/pull/14096 which has change to ignore duplicate nexthop when filling up fpm message
=> [chassis][voq] Fix to ignore duplicate nexthop in zebra

src/system-health/health_checker/sysmonitor.py
To fix https://github.com/sonic-net/sonic-buildimage/issues/15935
https://github.com/sonic-net/sonic-buildimage/issues/15935 mentioned issue occurring when a service encounters a start-limit-hit failure. Handling the failure result from sysbus event in sysmonitor processing code
Mimic start-limit-hit failure for a service. Issue show system-health sysready-status CLI.
```
[#]show system-health sysready-status
System is not ready - one or more services are not up
Service-Name                      Service-Status    App-Ready-Status    Down-Reason
--------------------------------  ----------------  ------------------  ---------------
as7326-56x-pddf-platform-monitor  OK                OK                  -
auditd                            OK …
```
=> Handle service start-limit-hit failure event case in sysmonitor

files/build_templates/sonic_debian_extension.j2, files/image_config/kubernetes/kubernetes_master_entrance.sh
Need a tool to check certificate's detail of information.
- Microsoft ADO **(number only)**: 25020260
Install pyOpenSSL package for k8s master
Pip3 list to check whether it's installed when include_kubernetes_master=y
=> Install pyOpenSSL package for k8s master

files/scripts/swss.sh
In an operational system, after some configuration is changed (that involves line cards generating entries to chassis db), if config reload or system reboot is done without saving the new configuration changes and when system comes up,  entries created by the new config are still present in the chassis db and hence the corresponding voq system entries (such as system interface, system neighbor and so on ) in all other line cards. These stale entries may affect the accuracy of the current entries and hence the intended operation of chassis. To fix this, we cleanup the chassis db when the an asic comes up. The chassis db is cleaned up for entries created by the asic that is coming up.
N/A
Cleanup the entries from the following tables in chassis app db in redis_chassis server in the …
=> [chassis] Chassis DB cleanup when asic comes up

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_ndk.json, device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_ndk.json
On Nokia IXR7250E platform, per latest requirement,  linecard no longer to reboot itself when midplane heartbeat is missing.
This PR address issue https://github.com/Nokia-ION/ndk/issues/20
- Microsoft ADO **(number only)**: 25036266
Modify the platform_ndk.json file and change the value of "monitor_action" from "reboot" to "warn" to let Linecard's NDK to log the Error message instead of reboot itself. 
1) Log in supervisor card, issue the following command to bring down the midplane communication.
```
sonic#> sudo ethtool -s xe0 autoneg on
```
2) On the linecard console, wait for 1 minute or more. The following log message should be shown up.  And No reboot action happened.
```
Aug 31 02:46:59.786135 ixre-egl-board25 WARNING sr_device_mgr: Unable to reach CPM over 10.6.0.100 (missing …
```
=> [Nokia-IXR7250E] Modify the platform_ndk.json for Nokia-IXR7250E platform

installer/x86_64/install.sh
This is a fix for PR https://github.com/sonic-net/sonic-buildimage/pull/6051
The original PR will disable intel idle driver but it cannot limit the max c-state to 1 due to system will fall back to acpi idle driver.
Currently intel_idle.max_cstate=0 is already present, which will disable intel idle driver. With the added option, common idle driver will be disabled as well, so there will not be idle management. This is to prevent a bug that can be triggered by idle instruction on intel platform.
- Microsoft ADO **(number only)**: 24867921
Add the option to installer file beside intel_idle.max_cstate=0
Manually changed kernel boot option to include the new parameter and reboot.
20201231.82,20181130.101,20220531.36
=> [installer] add processor.max_cstate=1 to intel kernel cmdline

files/scripts/arp_update
Fixes https://github.com/sonic-net/sonic-buildimage/issues/16312
1. Fixing an issue with FAILED entry resolution retry. Neighbor entries in arp table may sometimes enter a FAILED state when the far end is down and reports the state as follows:
```
2603:10e2:400:3::1 dev PortChannel19 router FAILED
```
While the arp_update script handles the entries for FAILED in the following format, the above was not handled due to the token location (extra router keyword at index 4):
```
2603:10e2:400:3::1 dev PortChannel19 FAILED
```
The former format may appear if an arp resolution is tried on a link that is known but the far end goes down, e.g., pinging a STALE entry while the far end is down.
2. Refreshing STALE entries to make sure the far end is …
=> chassis-packet: Update arp_update script for FAILED and STALE check

src/sonic-frr/patch/0030-zebra-remove-duplicated-nexthops-when-sending-fpm-msg.patch, src/sonic-frr/patch/series
Fixes #15803 
In SONiC chassis, routes have recursive nexthop resolution when the routes are learnt from remote linecard. 
In some cases after recursive nexthop resolution the number of nexthop for a route could reach `256`.
Zebra ran out of space when filling up 256 nexthops which causes zebra crash.
- Microsoft ADO **(24997365)**:
Create a patch to port https://github.com/FRRouting/frr/pull/14096 which has change to ignore duplicate nexthop when filling up fpm message 
The Fix was commit in this PR in master https://github.com/sonic-net/sonic-buildimage/pull/16275. This PR is port of the fix to 202205
Testing on voq chassis
=> patch fix to ignore dup nh in netlink msg

dockers/docker-database/docker-database-init.sh, dockers/docker-database/supervisord.conf.j2
Running the Redis server as the "root" user is not recommended. It is suggested that the server should be operated by a non-privileged user.
- Microsoft ADO **(number only)**: 15895240
Ensure the Redis process is operating under the 'redis' user in supervisord and make redis user own REDIS_DIR inside db container.
Built new image, verify redis process is running as 'redis' user and all containers are up.
=> [database] make Redis process runs as non-root user

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
To avoid errors when the `sfputil show error-status -hw` is called from the host OS (not from the `pmon` docker).
Remove the `self.sdk_handle` parameter from the `_get_module_info()` function.
Execute the `sfputil show error-status -hw`
=> [Mellanox][SFP] Remove unused function parameter

files/scripts/syncd.sh, platform/mellanox/mlnx-fw-upgrade.j2
1. Enhance the diagnosis information collecting mechanism
- If the option `-v` is fed, it will pass additional diagnosis flags to mlxfwmanager
- Collect all the output from mlxfwmanager and print them to syslog if it fails
2. Abort syncd in case waiting for device or upgrading firmware fails
Regression and manual test
=> [Mellanox] Enhance FW upgrade mechanism

files/build_templates/init_cfg.json.j2
Backport PR https://github.com/sonic-net/sonic-buildimage/pull/15816
There is a redundant line in init_cfg.json.j2. It would cause pmon service always has "has_timer=False". However, we know that PMON has a timer now. So, I try to fix it here.
Remove the redundant line
=> [202205] Fix issue: set has_timer attribute to true for platform monitor service (#15816)

device/celestica/x86_64-cel_e1031-r0/installer.conf, device/celestica/x86_64-cel_seastone-r0/installer.conf, device/dell/x86_64-dell_s6100_c2538-r0/installer.conf, files/Aboot/boot0.j2
On S6100 we are seeing almost 100K interrupts per second on intels i801 SMBUS controller which affects systems performance. 
We now disable the i801 driver interrupt and instead enable polling
- Microsoft ADO **(number only)**: 24910530
Disable the interrupt by passing the interrupt disable feature argument to i2c-i801 driver
This fix is NOT applicable for ARM based platforms. Applicable only for intel based platforms:-
1. On SN2700 its already disabled in Mellanox hw-mgmt
2. Celestica DX010 and E1031
4. Dell S6100 verified the interrupts are no longer incrementing.
5. Arista 7260CX3
=> Disable interrupt for intel i2c-i801 driver

sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
The json.hpp header file from that package is used in the sonic-swss-common build. An old version of that header file (from 2016) has been checked into the sonic-swss-common repo. However, since then, there have been changes to that header file, and starting with GCC 12 in Bookworm, generates some errors about variables being possibly uninitialized before use.
- Microsoft ADO **(number only)**: 25027439
To fix this, install the nlohmann-json3-dev package, and allow using the header file from the Debian package instead of a static checked-in version. The version in Debian Bullseye is much newer than this version.
With this change alone, sonic-swss-common will still be using the json.hpp file in its own codebase. The change to actually use the system header file instead of the local header …
=> Add nlohmann-json3-dev package into the slave container

onie-image.conf
Maximum RAM availability for NOS to SONiC migration using raw image in Dell S6100 is 1700MB.
Raw images larger than that cannot be used for NOS to SONiC migration.
Change raw image disk size to 1700MB.
Initiate build for 'target/sonic-broadcom.raw' and verify that the build is successful only if the raw image generated is within the specified size.
[build] Change raw image disk size to 1700MB
=> [build] Change raw image disk size to 1700MB

build_debian.sh, files/image_config/kubernetes/kubernetes_master_entrance.sh
Need a tool to extend disk size
- Microsoft ADO **(number only)**: 25094467
Install parted package
Use apt list parted command to check if it's installed
=> Install parted package for k8s master

dockers/docker-ptf/Dockerfile.j2
Need new gnmi client for dash test.
I have updated gnxi repo, and this PR is used to get latest change.
Run end2end test for DASH.
=> Upgrade gnxi to support dash

src/sonic-frr/patch/0031-lib-Fix-corruption-when-routemap-delete-add-sequence.patch, src/sonic-frr/patch/series
Zebra core sometimes seen during config reload. Series of route-map deletions and then re-adds, *and* this triggers the hash table to realloc to grow to a larger size, then subsuquent route-map operations will be against a corrupted hash table.
Issue is seen when we have BFD Enable on Static Route table we see Static route-map being created/deleted based on bfd session state. However issue itself is very generic from FRR perspective.
Thie issue has detailed core info https://github.com/sonic-net/sonic-frr/issues/37 . This PR fixes this issue.
Fixes#https://github.com/sonic-net/sonic-frr/issues/37
- Microsoft ADO **(17952227)**:
This fix is already in Master frr/8.2.5. Porting this fix to 202205 branch to address this Zebra core.
https://github.com/sonic-net/sonic-frr/commit/5f503e5f5aecc94 …
=> [FRR Patch] lib: Fix corruption when routemap delete/add sequence happens

dockers/docker-snmp/snmpd.conf.j2, dockers/docker-snmp/start.sh
Reverting PR added to support SNMP over IPv6 as there is an open issue https://github.com/sonic-net/sonic-buildimage/issues/16165 
Revert https://github.com/sonic-net/sonic-buildimage/pull/16013 and https://github.com/sonic-net/sonic-buildimage/pull/15487 form 202211 branch
=> [202211][SNMP][IPv6]: Revert PRs to support SNMP over IPv6

dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py
Add another cli entry: show dhcp_relay ipv4 counter
Fix get all interface offset issue
- Microsoft ADO **(17271822)**:
show dhcp_relay ipv4 counter -i [ifname]
show dhcp4relay_counters counts -i [ifname]
show dhcp4relay_counters counts | more 10
Message Type    Ethernet144(RX)
--------------  -----------------
Unknown                  0
Discover                  0
Offer                  0
Request                  0
Decline                  0
Ack                  0
Nak                  0
Release                  0
Inform                  0
Message Type    Ethernet144(TX)
--------------  -----------------
Ack                  1
Decline                  0
Discover                  1
Inform                  0
Nak                  0
Offer                  1
Release                  0
Request …
=> Add show dhcp_relay ipv4 counter entry, fix interface name offset issue

files/scripts/swss.sh
The PR is for the following:
- For the following chassis DB clean up optimization:
- To avoid delay before deleting system interfaces when no system neighbors were deleted before
- To avoid delay before deleting system lag when no system lag members were deleted before
- To avoid stale kernel neighbor after clearing system neighbors when asic comes up.
- To avoid accessing CHASSIS_APP_DB in pizzabox devices (PR #16451) 
N/A
- Fix for regression failure due to error in finding CHASSIS_APP_DB in pizzabox (#PR 16451)
- Chassis clean up code is re-arranged to avoid accessing CHASSIS_APP_DB for non voq switches.
- After attempting to delete the system neighbor entries from chassis db, before starting clearing the system interface entries,
wait for sometime only if some system neighbors were …
=> [swss] Chassis db clean up optimization and bug fixes

platform/pddf/i2c/modules/cpldmux/driver/pddf_cpldmux_driver.c
This feature was meant to be enabled but was accidentally left disabled.
I also changed the default log level for normal usage to KERN_INFO as the log spam can be quite severe otherwise.
Fixes #14546.
Enabled the option by default.
- Requires a PDDF CPLDMUX driver.
- Access an I2C bus through the CPLDMUX
- Observe the message that the bus was deselected.
I am working on stabilizing 202211 for our internal needs, so I would prefer if the change can be backported so I do not have to carry the patch internally as well.
202211 internal build.
- [pddf] CPLDMUX now correctly allows usage of deselect logic.
N/A
=> [pddf] Enable deselect logic for CPLDMUX

.azure-pipelines/azure-pipelines-build.yml, .azure-pipelines/build-template.yml, .azure-pipelines/official-build-cache.yml
raw image is failing for disk issue.
I confirmed with Ying that raw image only runs on Dell S6100, it has a disk size limit 1700MB.
Currently it is only built on 201811 branch.
=> [ci] Disable building broadcom raw image because of S6100 device disk space limit.

src/tacacs/nss/patch/0001-Modify-user-map-profile.patch, src/tacacs/nss/patch/0010-Send-remote-address-in-TACACS-authorization-message.patch, src/tacacs/nss/patch/0011-Replace-popen-shell-execution-with-safer-execle.patch
Write error message to syslog when add user failed or connect to TACACS server failed.
With these messages, we can downgrade TACACS server with issue to lower priority.
- Microsoft ADO: 24667696
Write error message to syslog when add user failed or connect to TACACS server failed.
Pass all UT.
Manually verify error message generated.
Write error message to syslog when add user failed or connect to TACACS server failed.
=> Write error message to syslog when add user failed or connect to TACACS server failed.

Makefile.work
Fix: #16086
faketime package url expired. It breaks 201811 build. Update package url.
- Microsoft ADO **(number only)**:  24930879
=> Fix faketime package downloading issue. (#16263)

sonic-slave-buster/Dockerfile.j2
Fix UT failure caused by typing-extensions version update.
- Microsoft ADO **(number only)**:  25123371
=> [build] Pin typing-extensions version to fix UT issue in sonic-utilities.

dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
Added a check for DEVICE_METADATA before accessing the data. This prevents the j2 failure when var is not available.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/16526
During a fresh image install, it is observed that pmon docker fails to come up when no config has been applied yet. pmon docker is important as it hosts the chassisd daemon to populate chassis db, which may be required in some circumstances to check system state before applying any config.
Added a check for DEVICE_METADATA before accessing the data. This prevents the j2 failure when var is not available.
Bringup chassis after image install and check docker pmon status before loading DEVICE_METADATA config.
Tested on 202205 …
=> Chassis: fix pmon docker failure when DEVICE_METADATA is not available

device/dell/x86_64-dell_s6100_c2538-r0/platform.json
ADO: 25136360
sonic-mgmt component test failed 
Change the order of components in platform file.
Run sonic-mgmt component API test scripts
=> Dell S6100: Change the order of platform components

files/image_config/interfaces/interfaces.j2, src/sonic-config-engine/tests/sample_output/py2/interfaces, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_inband, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_inband_ip, src/sonic-config-engine/tests/sample_output/py2/interfaces_nomgmt_ztp_ip, src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces, src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py2/two_mgmt_interfaces, src/sonic-config-engine/tests/sample_output/py3/interfaces, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_inband, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_inband_ip, src/sonic-config-engine/tests/sample_output/py3/interfaces_nomgmt_ztp_ip, src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces, src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces_nomgmt, src/sonic-config-engine/tests/sample_output/py3/two_mgmt_interfaces
In #15080, there was a command added to re-add 127.0.0.1/8 to the lo interface when the networking configuration is being brought down. However, the trigger for that command is `down`, which, looking at ifupdown2 configuration files, runs immediately after 127.0.0.1/16 is removed. This means there may be a period of time where there are no loopback addresses assigned to the lo interface, and redis commands will fail.
- Microsoft ADO **(number only)**: 24833037
Fix this by changing this to pre-down, which should run well before 127.0.0.1/16 is removed, and should always leave lo with a loopback address.
This is a race condition with a small timing window for the issue to occur. Killing the teamd container or repeated config reloads may be the best way to try to trigger this.
=> Fix potentially not having any loopback address on lo interface

files/scripts/swss.sh
The PR is for the following:
- For the following chassis DB clean up optimization:
- To avoid delay before deleting system interfaces when no system neighbors were deleted before
- To avoid delay before deleting system lag when no system lag members were deleted before
- To avoid stale kernel neighbor after clearing system neighbors when asic comes up.
- To avoid accessing CHASSIS_APP_DB in pizzabox devices (PR #16451) 
N/A
- Fix for regression failure due to error in finding CHASSIS_APP_DB in pizzabox (#PR 16451)
- Chassis clean up code is re-arranged to avoid accessing CHASSIS_APP_DB for non voq switches.
- After attempting to delete the system neighbor entries from chassis db, before starting clearing the system interface entries,
wait for sometime only if some system neighbors were …
=> [swss] Chassis db clean up optimization and bug fixes (#16454)

files/scripts/supervisor-proc-exit-listener
ConfigDBConnector in supervisor-proc-exit-listener uses default parameter to connect CONFIG_DB (connect by 127.0.0.1:6379) which would fail at non-host network mode container, because they are not sharing the same network and socket.
- Microsoft ADO **(number only)**: 25156255
Add a new parameter `use_unix_socket_path` to this script to indicate whether to use socket to connect CONFIG_DB.
Build image and install it, kill critical processes in container and container crushed.
=> [supervisor] Add use_unix_socket_path to supervisor-proc-exit-listener

dockers/docker-platform-monitor/Dockerfile.j2, files/build/versions/dockers/docker-platform-monitor/versions-py3
Updating the grpc and grpc tools library to 1.57.0 to get the latest changes. This is required to get the latest stable source from https://github.com/grpc/grpc
This gives a chance to use some more channel/stub attributes to be included in gRPC request and response monitoring service. This also helps in removing all the bugs which are known issues for gRPC before 1.57.0
- 24923612
On the mixed topo testbed, these tests were run and passed successfully
```       
tests/dualtor_io/ test_tor_failure.py
tests/dualtor_io/test_heartbeat_failure.py    
tests/dualtor_io/test_tor_bgp_failure.py 
dualtor_io/test_heartbeat_failure.py::test_standby_tor_heartbeat_failure_downstream_active[active-standby] PASSED …
```
=> [pmon] update gRPC library and gRPC IO tools version to 1.57.0

src/sonic-frr/patch/0022-bgpd-Don-t-read-the-first-byte-of-ORF-header-if-we-a.patch, src/sonic-frr/patch/0023-bgpd-Make-sure-we-have-enough-data-to-read-two-bytes.patch, src/sonic-frr/patch/series
Created patches to address two CVEs from FRR CVE-2023-41359 and CVE-2023-41360.
| Patch | FRR commit| CVE fixed |
| ------  |--------- | ------------ |
| 0022-bgpd-Don-t-read-the-first-byte-of-ORF-header-if-we-a.patch | https://github.com/FRRouting/frr/commit/3515178de4a56d66ed948a774efcbe4a854e1ca7 | CVE-2023-41360 |
| 0023-bgpd-Make-sure-we-have-enough-data-to-read-two-bytes.patch  | https://github.com/FRRouting/frr/commit/460ee930d6dbce6e96ecbfcd568a291f31bae24e | CVE-2023-41359 |
Porting fixes as patches from FRR.
Azure Pipeline tests should cover the sanity. In addition ran basic tests.
=> [FRR] Adding patches for CVE-2023-41360 and CVE-2023-41359

src/sonic-bgpcfgd/staticroutebfd/vars.py, src/sonic-bgpcfgd/tests/test_static_rt_bfd.py
staticroutebfd should use singlehop bfd. Because of a bug (portchannel+singlehop) in the SDK, we were using multi-hop as a temporary workaround. Now the SDK issue is solved, need to switch to singlehop BFD mode.
- Microsoft ADO **(25039238)**:
change the multihop variable to "false" in staticroutebfd/vars.py 
verified it both in UT and testbed. using show bfd sum to confirm the Multihop field is false.
=> [staticroutebfd] change bfd to singlehop

src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/qosmaps.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json, src/sonic-yang-models/yang-models/sonic-port-qos-map.yang
=> [202211] Add yang model for scheduler in PORT_QOS_MAP (#16244)

platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/component.py
sonic-mgmt test failure is seen for update_firmware component API
Edited API 2.0 to fix this issue.
Run sonic-mgmt test after the fix and verify it passes.
=> Dell S6100 component API fix

dockers/docker-ptf-sai/Dockerfile.j2
docker-ptf-sai build fails on setuptools_scm's new release on 09/20/2023.
Use old version instead.
=> [build] Fix build issue in docker-ptf-sai caused by setuptools_scm new release

files/scripts/swss.sh
The PR is for the following:
- For the following chassis DB clean up optimization:
- To avoid delay before deleting system interfaces when no system neighbors were deleted before
- To avoid delay before deleting system lag when no system lag members were deleted before
- To avoid stale kernel neighbor after clearing system neighbors when asic comes up.
- To avoid accessing CHASSIS_APP_DB in pizzabox devices (PR #16451) 
N/A
- Fix for regression failure due to error in finding CHASSIS_APP_DB in pizzabox (#PR 16451)
- Chassis clean up code is re-arranged to avoid accessing CHASSIS_APP_DB for non voq switches.
- After attempting to delete the system neighbor entries from chassis db, before starting clearing the system interface entries,
wait for sometime only if some system neighbors were …
=> [swss] Chassis db clean up optimization and bug fixes #16454

src/sonic-ctrmgrd/setup.py
Fixing the following build issue
```
[2023-09-20T04:42:00.004Z] [ FAIL LOG START ] [ target/python-wheels/bullseye/sonic_bgpcfgd-1.0-py3-none-any.whl ]
[2023-09-20T04:42:00.004Z] Build start time: Wed Sep 20 04:41:54 UTC 2023
[2023-09-20T04:42:00.004Z] [ REASON ] :      target/python-wheels/bullseye/sonic_bgpcfgd-1.0-py3-none-any.whl does not exist   NON-EXISTENT PREREQUISITES: target/python-wheels/bullseye/sonic_config_engine-1.0-py3-none-any.whl-install target/python-wheels/bullseye/sonic_yang_mgmt-1.0-py3-none-any.whl-install target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl-install target/debs/bullseye/libyang_1.0.73_amd64.deb-install target/debs/bullseye/libyang-cpp_1.0.73_amd64.deb-install target/debs/bullseye/python3-yang_1.0.73_amd64.deb-install …
```
=> Fixing netaddr build issue

platform/marvell-arm64/sai.mk
- Add sai_query_api_version API support
Add sai_query_api_version() API support to MRVL libsai.so
Implemented the sai_query_api_version() API to return current supported version of sai debian.
compile and load the libsai.so in syncd docker.
=>  [Marvell] Update arm64 sai debian to 1.12.0-2

build_debian.sh, files/apparmor/usr.bin.tcpdump
Fix tcpdump report error when tacacs enabled.
Fix tcpdump report error when tacacs enabled:
Sep  1 09:25:18.189395 vlab-01 ERR tcpdump: nss_tacplus: /etc/tacplus_nss.conf fopen failed
Sep  1 09:25:18.189606 vlab-01 ERR tcpdump: nss_tacplus: bad config or server line for nss_tacplus
This is because debian add a patch create AppArmor profile for resource access control. The profile need update to allow tcpdump access /etc/tacplus_nss.conf.
- Microsoft ADO: 17667308
Modify tcpdump AppArmor profile, add new line to allow tcpdump access TACACS config file:
/etc/tacplus_nss.conf r,
Pass all UT.
Manually verify error fixed.
Fix tcpdump report error when tacacs enabled.
=> Fix tcpdump report error when tacacs enabled.

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Sfp api can now be called from the host which doesn't have the python_sdk_api installed. Also, sfp api has been migrated to use sysfs instead of sdk handle.
Remove all the redundant sdk methods and hardcode constants.
Before this change:
```
root@sonic:/home/admin# sudo sfputil show error-status --fetch-from-hardware
File "/usr/local/bin/sfputil", line 8, in <module>
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return …
```
=> [Nvidia] Remove the dependency on python_sdk_api for sfp api

platform/centec-arm64/sai.mk, platform/centec/sdk.mk
Change makefile to reference to new SAI debian package of v1.11.0-2 for centec of 202211
Modify sai.mk of arm64 platform and sdk.mk of x86 platform for Centec
=> update sonic centec-sai reference to v1.11.0-2 for 202211

platform/broadcom/sonic-platform-modules-accton/as4630-54pe/udev/70-persistent-net.rules, platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/restart_ixgbe.sh, platform/broadcom/sonic-platform-modules-accton/debian/rules, platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as4630-54pe.postinst
Management port currently broken for Edgecore AS4630-54PE platform due to NIC hardware numbering.
Created new PR with typo from Edgecore in original PR fixed. Here is a link to the old PR that has broken logic:
https://github.com/sonic-net/sonic-buildimage/pull/9560
Here is current master branch on AS4630-54PE with broken eth0 (note RUNNING flag):
root@t9845swta0001:/home/admin# ifconfig eth0
eth0: flags=4099<UP,BROADCAST,MULTICAST> mtu 1500
inet 10.121.38.158 netmask 255.255.254.0 broadcast 10.121.39.255
ether 90:3c:b3:2c🆎67 txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 0 bytes 0 (0.0 B)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0
Here is master branch with fix applied: …
=> Fix eth0 hardware numbering using udev for AS4630-54PE platform.

sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
We install many deb packages when building sonic slave images.
To guarantee that the filesystem data is always consistent and safe,
dpkg performs fsync(2)s on its database and files unpacked from packages. 
We don't need to use fsync for sonic slave images.
So we can reduce build time using eatmydata.
1. Install deb package eatmydata in sonic-slave-buster and sonic-slave-bullseye docker images.
2. Pass `apt-get install`, `apt install`, `apt-get upgrade`, and `dpkg -i` with arguments directly to eatmydata.
Compare the build time of sonic-slave images with and without eatmydata.
For some NVME SSD I improved it by 30-40%.
You get no performance boost if your fs is mounted with options like `nobarrier`.
=> [Build] use eatmydata to reduce build time of sonic slave images

platform/vs/docker-sonic-vs/Dockerfile.j2
[Build] Remove the debian jessie mirror in docker-sonic-vs
The debian jessie is no use in debian bullseye
- Microsoft ADO **(number only)**: 24597767
=> [Build] Remove the debian jessie mirror in docker-sonic-vs

dockers/docker-fpm-frr/start.sh
Back port https://github.com/sonic-net/sonic-buildimage/pull/6478 and https://github.com/sonic-net/sonic-buildimage/pull/6519 to 201911 branch.
24978836
Add checking the connection between zebra and bgp during bgpd start.
Modify start.h, add debug log and check the syslog
_Sep 22 02:41:29.716356 str-a7060cx-acs-10 INFO bgp#root: ####: start zebra
Sep 22 02:41:30.815341 str-a7060cx-acs-10 INFO bgp#root: ####: start check connection
Sep 22 02:41:30.868784 str-a7060cx-acs-10 INFO bgp#root: ####: It took 0.029979 seconds to wait for zebra to be ready to accept connections
Sep 22 02:41:30.873685 str-a7060cx-acs-10 INFO bgp#root: ####: start bgpd
Sep 22 02:41:35.270569 str-a7060cx-acs-10 INFO bgp#root: ####: done_
_Sep 22 03:28:02.423438 str-a7060cx-acs-10 …
=> [201911] add checking the connection between zebra and bgp

platform/broadcom/sonic-platform-modules-cel/haliburton/script/cpu_wdt
Add info syslog for cpu_wdt.service when trigger watchdog arm action.
- Microsoft ADO **(number only)**: 25267950
Add info syslog for cpu_wdt.service when trigger watchdog arm action.
Verified on Celestica-E1031 device with SONiC.202012 image installed. Can find below logs from `/var/log/syslog`:
```
admin@e1031$ sudo grep -i cpu_wdt /var/log/syslog
Sep 25 03:47:32.952409 str-e1031-acs-3 INFO systemd[1]: cpu_wdt.service: Succeeded.
Sep 25 03:47:32.996541 str-e1031-acs-3 INFO cpu_wdt: Enable CPU WDT..
Sep 25 03:47:34.411250 str-e1031-acs-3 INFO cpu_wdt: CPU WDT has been enabled with 180 seconds timeout
Sep 25 03:47:34.417476 str-e1031-acs-3 INFO cpu_wdt: Enable keep alive messaging every 60 seconds
Sep 25 03:47:35.810653 str-e1031-acs-3 INFO cpu_wdt: Keep alive message sent [RC=0]. Will …
```
=> [HLX] Add info syslog for cpu_wdt.service when trigger watchdog arm action

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/buffers_defaults_t2.j2, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/buffers_defaults_t2.j2, src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x100g.json, src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x100g.json
sonic-mgmt xoff test was failing for [100g,120km]. Needed to update total headroom pool size when 100G line card is used as T2 uplink.
- Microsoft ADO **(25266920)**:
Updated total headroom size in buffer config
Verified with sonic-mgmt xoff test passing for [100g,120km]
=> Updated total headroom pool size to accommodate 100G ports on T2 uplinks

dockers/docker-dhcp-relay/dhcp_relay_regex.json, dockers/docker-dhcp-relay/events_info.json
Fix regex such that dhcp bind failure event is detected as well as process name since dhcp relay processes that need to be detected are dhcprelay6 and dhcrelay.
Manual testing and nightly test event
=> Fix dhcp relay regex and process name

dockers/docker-sonic-telemetry/telemetry.sh
Fix issue #16533 , telemetry service exit in master and 202305 branches due to no telemetry configs in redis DB.
Enable default config if no TELEMETRY configs from redis DB.
After the fix, telemetry service would work with the following two scenarios:
1. With TELEMETRY config in redis DB, load service configs from DB.
2. No TELEMETRY config in redis DB, use default service configs.
=> [Telemetry] enable default service config if no configs from DB

rules/frr.dep
Now build will fail on:
```
fatal: Unable to hash src/sonic-frr/frr/tests/topotests/grpc_basic/lib
fatal: Unable to hash src/sonic-frr/frr/tests/topotests/ospfapi/lib
make: *** [Makefile.cache:528: target/debs/buster/frr_8.5.1-sonic-0_amd64.deb.smdep] Error 123
make: *** Waiting for unfinished jobs....
```
Root cause is that these files are symbol links.
git hash-object can't hash symbol links.
- Microsoft ADO **(number only)**:  25271730
These two files are symbol links.
When calculate sha value, skip these two files.
=> [build] Fix frr dpkg cache calculation issue on symbolic link file.

build_debian.sh
To speed up final image build.
Remove 15s unconditional sleep.
Instead check every second that /proc is not mounted.
Go to the next step if /proc is not mounted anymore or after 15s.
=> [Build] remove 15s sleep in build_debian.sh

files/build_templates/docker_image_ctl.j2
Fix: https://github.com/sonic-net/sonic-buildimage/issues/16699
Fast reboot is failing from old OS versions (eg., 201911 image) to latest (eg., master branch) after PR https://github.com/sonic-net/sonic-buildimage/pull/15685
The system wide flag for FAST_REBOOT is still required when the base OS version does not support the new fast-reboot reconciliation logic (no db dump)
Set system flag for fast reboot during boot up path
Change restores the state as it was before PR 16225, and fast-reboot worked before 16225
Manual tests are in progress.
=> [fast-reboot] Fix regression: set state_db flag to support fast-reboot from older images

device/dell/x86_64-dell_s6100_c2538-r0/installer.conf, platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh
- To support iTCO watchdog in Dell S6100.
[Backport PR #9149]
- Update installer.conf for initializing the required drivers.
- Update the reboot cause determination logic to check for iTCO watchdog reset if the BIOS version supports iTCO watchdog.
Verified that the watchdog APIs' return values are as expected.
UT logs: [202012_UT_logs.txt](https://github.com/sonic-net/sonic-buildimage/files/12737416/202012_UT_logs.txt)
[202012][Dell] S6100 - Add iTCO watchdog support
=> [202012][Dell] S6100 - Add iTCO watchdog support

src/sonic-frr/patch/0024-bgpd-Do-not-process-NLRIs-if-the-attribute-length-is.patch, src/sonic-frr/patch/0025-bgpd-Use-treat-as-withdraw-for-tunnel-encapsulation-.patch, src/sonic-frr/patch/series
Created patches to address two CVEs from FRR CVE-2023-41358 and CVE-2023-38802.
| Patch | FRR commit| CVE fixed |
| ------  |--------- | ------------ |
| 0024-bgpd-Do-not-process-NLRIs-if-the-attribute-length-is.patch | https://github.com/FRRouting/frr/commit/f291f1ee9434f56d4b185db0652794a92e313b00| CVE-2023-41358 |
| 0025-bgpd-Use-treat-as-withdraw-for-tunnel-encapsulation-.patch  | https://github.com/FRRouting/frr/commit/8a4a88c46d15004b1a584cd47f9f6b8278f8da66| CVE-2023-38802 |
Porting fixes as patches from FRR.
Azure Pipeline tests should cover the sanity. In addition ran basic tests.
=> [FRR] Adding patches for CVE-2023-41358 and CVE-2023-38802

build_debian.sh, files/image_config/kubernetes/kubernetes_master_entrance.sh
Need a tool to debug network issue
- Microsoft ADO **(number only)**: 25295998
Install netcat package
Use apt list parted command to check if it's installed
=> Install nc cmd for debugging k8s master VM network issue

src/isc-dhcp/patch/0014-enable-parallel-build.patch, src/isc-dhcp/patch/series
To speed up build
Fix debian/rules for isc-dhcp to run make in parallel
Before: 52s
After: 26s
md5sum of isc-dhcp-relay_4.4.1-2.3+deb11u2_amd64.deb is not changed.
=> enable parallel build for isc-dhcp-relay

src/snmpd/Makefile, src/snmpd/patch-5.9+dfsg/0009-Makefile.in-agent-Makefile.in-Fix-parallel-compilati.patch, src/snmpd/patch-5.9+dfsg/0010-Makefile.in-Make-sure-that-sedscript-is-built-before.patch, src/snmpd/patch-5.9+dfsg/0011-agent-Makefile.in-Build-the-MIB-module-code-once.patch, src/snmpd/patch-5.9+dfsg/0012-agent-Makefile.in-Unbreak-the-enable-minimalist-buil.patch, src/snmpd/patch-5.9+dfsg/0013-enable-parallel-build-for-net-snmp.patch, src/snmpd/patch-5.9+dfsg/series
parallel build is available for net-snmp since 2021 year:
https://github.com/net-snmp/net-snmp/issues/283
So we can also build net-snmp 5.9 in parallel to reduce build time.
Use patches for parallel build from net-snmp upstream and enable parallel build in debian/rules for version 5.9
=> enable parallel build for snmpd 5.9

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/tests/test_chassis.py
Depends on https://github.com/sonic-net/sonic-buildimage/pull/16483
SONiC service `determine-reboot-cause` might run before driver creating reset cause files. In that case, the reset cause will be "Unknown". This PR introduces a wait mechanism to wait for reset cause sysfs files ready.
/run/hw-management/config/reset_attr_ready is the file to indicate all reset cause files are ready. In `chassis.get_reboot_cause` function, it waits /run/hw-management/config/reset_attr_ready for up to 45 seconds.
Manual test on master/202211/202205
=> [Mellanox] wait reset cause ready

sonic-slave-bullseye/Dockerfile.j2
Fix the build break of marvell-armhf/sonic-ycabled
=> Fix the dependency grpcio-tools version

platform/centec-arm64/sai.mk, platform/centec/sai.mk
1. Upgrade Centec SAI debian package version to v1.13, in order to match syncd's requirement.
2. Fix syncd compile fail for missing sai_query_api_version function in verdor sai
Upload latest sai debian package and modify sai.mk of arm64 and x86 platform for Centec
Build centec amd64 and arm64 sonic image, syncd compile pass
=> [centec] Upgrade SONiC centec-sai reference to v1.13.0-1

dockers/docker-snmp/snmpd.conf.j2, dockers/docker-snmp/start.sh
Revert https://github.com/sonic-net/sonic-buildimage/pull/16013 and https://github.com/sonic-net/sonic-buildimage/pull/15487 form 202305 branch
- Microsoft ADO **25243527**:
=> [202305][SNMP][IPv6]: Revert PRs to support SNMP over IPv6 

slave.mk
Cherry-pick  from https://github.com/sonic-net/sonic-buildimage/pull/15660
Fix some of the patches in .patches folder not applied issue.
The command "quilt applied" only lists the applied patches, if some of the patches have issues, then the patches will not be applied when you run the build command again.
- Microsoft ADO **(number only)**: 24410730
1. Run the command to apply the patches without any conditions.
2. If failed, check if the failure reason is "series fully applied".
=> [Build] Fix some of the patches not applied issue (#15660)

dockers/docker-orchagent/orchagent.sh, dockers/docker-sonic-telemetry/telemetry.sh
Enable ZMQ on gnmi and orchagent
Improve GNMI API performance for Dash resources
Modify gnmi and orchagent service start script, add ZMQ parameter.
Pass all UT & E2E test
Manually verify with create Dash resources via gnmi API.
=> Enable ZMQ between GNMI and Orchanget

rules/openssh.mk
Failures are seen while building sonic-broadcom.bin image in bookworm branch.
**Logs:**
sudo dpkg --root=./fsroot-broadcom -i target/debs/bookworm/openssh-server_9.2p1-2_amd64.deb
dpkg: warning: downgrading openssh-server from 1:9.2p1-2+deb12u1 to 1:9.2p1-2
(Reading database ... 51746 files and directories currently installed.)
Preparing to unpack .../openssh-server_9.2p1-2_amd64.deb ...
Unpacking openssh-server (1:9.2p1-2) over (1:9.2p1-2+deb12u1) ...
dpkg: dependency problems prevent configuration of openssh-server:
openssh-server depends on openssh-client (= 1:9.2p1-2); however:
Version of openssh-client on system is 1:9.2p1-2+deb12u1.
dpkg: error processing package openssh-server (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing: …
=> [Bookworm] Update openssh version

src/sonic-host-services/scripts/hostcfgd, src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
**BACKPORT**: https://github.com/sonic-net/sonic-host-services/pull/58
Closes #16841
* N/A
* N/A
* N/A
* N/A
* N/A
* N/A
```
'//||\\`
''``
```
=> [202205][hostcfgd] Fix issue: FeatureHandler might override user configuration

files/build_templates/sonic_debian_extension.j2, rules/openssh.mk, slave.mk, src/openssh/Makefile
Openssh in Debian Bullseye has been updated to 1:8.4p1-5+deb11u2 to fix CVE-2023-38408. Since we're building openssh with some patches, we need to update our version as well.
=> Update openssh to 1:8.4p1-5+deb11u2

dockers/docker-snmp/snmpd.conf.j2, dockers/docker-snmp/start.sh
Revert https://github.com/sonic-net/sonic-buildimage/pull/16013 and https://github.com/sonic-net/sonic-buildimage/pull/15487 form 202205 branch
=> [202205][SNMP][IPv6]: Revert PRs to support SNMP over IPv6

rules/openssh.mk, slave.mk
The current `slave.mk` code installs the dependencies of derived packages (i.e. the main package) into the slave container, even though it's not actually needed for the "build". Because of that, with openssh, when there's different versions built than what is in the slave container, the installation will fail because of conflicting versions.
Therefore, remove the installation prerequisite from the derive deb build command, and re-add openssh-client and openssh-sftp-server as a derived package of openssh-server.
=> Remove main deb installation for derived deb build

files/build_templates/snmp.service.j2
Fixes #16486
- Microsoft ADO **(number only)**: 24780690
As `snmp` depends on `intfmgrd` to work, let's add a check to ensure `intfmgrd` is running.
The check will run for 20 seconds at most.
Do `config reload` and confirms `snmpd` is started after `intfmgrd` setups all the loopback interfaces.
=> [snmp] Sleep for 20 seconds before service starts

files/Aboot/boot0.j2
Networking devices need to be responsive. Such responsiveness is harmed when the CPU change state.
There is a latency penalty when a CPU is idle (e.g C2) and need to exit this state to come back to C1 state.
To prevent this from happening the CPU should be forced to remain in C1 state.
Generalize the cstate forcing to C1 to all Arista products.
This is done by adding `processor.max_cstate=1` to the kernel cmdline for all CPUs.
Additionally Intel CPUs also need `intel_idle.max_cstate=0` to fallback to the `acpi_idle` driver.
Check that `processor.max_cstate=1` is present on the cmdline for AMD CPUs
Check that both `processor.max_cstate=1` and `intel_idle.max_cstate=0` are present on the cmdline for Intel CPUs
Disable CPU C-States other than C1 for Arista …
=> [Arista] Disable CPU C-States other than C1

Makefile.cache, slave.mk
My previous change removed the whole dependency on the main deb existing, not just the installation of the main deb. Fix this by readding a dependency on the main deb being built/pulled from cache.
Without this PR, build failures are seen in the PR builds for the VS image build. I suspect it's only for this image and not the others because this is the only image (besides the generic image) for which there are no out-of-tree kernel modules built.
- Microsoft ADO **(number only)**: 25517845
=> Re-add missing dependency for derived debs.

platform/marvell/sai.mk
Added Marvell SAI-1.13.0 debian support for x86_64 platform.
compile marvel libsai.so (with SAI headers from version 1.13.0) and package it with version 1.13.0-1
=> [Marvell] Updated SAI 1.13.0 amd64 debian

dockers/docker-fpm-frr/docker_init.sh
If zebra.conf is cleared:
```
for f in /etc/sonic/frr/*.conf; do cp /dev/null $f; done
```
The following line:
```
sed -i '1i no fpm use-next-hop-groups\nfpm address 127.0.0.1' $FILE_NAME
```
will not insert default zebra configuration as there is no first line.
Replace ```sed``` with simple ```echo``` commands
Configure ```split``` mode. Clear FRR configuration files. Reboot the switch and verify default zebra configuration is applied.
Write some configuration into zebra.conf and reboot. Verify that default and user zebra configuration is present in /etc/frr/zebra.conf.
=> [frr] fix default zebra config not inserted into empty zebra.conf

slave.mk
RFS cache have issues which breaks official build and PR checker.
By reading cache, fsroot-vs/lib/modules folder don't exist.
- Microsoft ADO **(number only)**:  25481484
Disable read cache currently.
=> Disable read cache when building SONiC fs part 1

rules/docker-macsec.mk
Privileges and volumes were incorrectly set in macsec container. Privileged flag is set to false and volumes are not mounted properly.
```
admin@vlab-01:~$ docker inspect macsec0 | grep Privi
admin@vlab-01:~$ docker inspect macsec0 | grep -A 10 Binds
"Binds": [
"/var/run/redis0:/var/run/redis:rw",
"/var/run/redis-chassis:/var/run/redis-chassis:ro",
"/usr/share/sonic/device/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0:/usr/share/sonic/hwsku:ro",
"/var/run/redis0/:/var/run/redis0/:rw",
"/usr/share/sonic/device/x86_64-nokia_ixr7250e_36x400g-r0:/usr/share/sonic/platform:ro"
],
```
Make sure privileged settings remain unchanged and make sure volumes are properly mounted
```
admin@vlab-01:~$ docker inspect macsec | grep Privi …
```
=> [docker-macsec] fix privileged and volumes settings

platform/mellanox/mlnx-platform-api/sonic_platform/psu.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
This PR depends on new hw-management version 7.0030.2000. Revert it for now and waiting for hw-management upgrading.
=> Revert "[Mellanox] Align PSU temperature sysfs node name with hw-management change"

files/build_templates/docker_image_ctl.j2, files/image_config/rsyslog/rsyslog-container.conf.j2
Mellanox MSN2700 platforms have a non-functional error log:  "ERR pmon#sensord: Error getting sensor data: dps460/#10: Can't read".  This error is because of a firmware issue with some PSU, we are not able to upgrade the FW online. Since there is no functional impact, this error log can be ignored safely.
Add a new rsyslog rule to the rsyslog-container.conf.j2, if the docker name is pmon and the platform name matches, the new rule will be inserted into the docker rsyslogd.conf
run regression on the MSN2700 platform to make the error log will not be printed to the syslog.
=> Add special rsyslog filter for MSN2700 platform

dockers/docker-sonic-mgmt/Dockerfile.j2
With Debian Bookworm, Paramiko 2.9 or newer will need to be used to be able to connect to devices running that version of Debian (specifically, to those running OpenSSH 9.2).
Fixes #16851.
Paramiko is currently on 3.3.1. For now, upgrade paramiko in docker-sonic-mgmt to 2.9.5.
Tested by running `tacacs/test_accounting.py` on a KVM image with Bookworm base image, and verifying that it all passed.
Note that there is a small risk of breakage of other tests due to the Paramiko update.
=> Upgrade paramiko in docker-sonic-mgmt to 2.9.5

files/build_templates/docker_image_ctl.j2, files/image_config/rsyslog/rsyslog-container.conf.j2
**backport https://github.com/sonic-net/sonic-buildimage/pull/16684**
Mellanox MSN2700 platforms have a non-functional error log:  "ERR pmon#sensord: Error getting sensor data: dps460/#10: Can't read".  This error is because of a firmware issue with some PSU, we are not able to upgrade the FW online. Since there is no functional impact, this error log can be ignored safely.
Add a new rsyslog rule to the rsyslog-container.conf.j2, if the docker name is pmon and the platform name matches, the new rule will be inserted into the docker rsyslogd.conf
run regression on the MSN2700 platform to make the error log will not be printed to the syslog.
=> [202205] Add special rsyslog filter for MSN2700 platform (#16684)

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/simple-sample-graph-m0.xml, src/sonic-config-engine/tests/simple-sample-graph-mx.xml, src/sonic-config-engine/tests/test_minigraph_case.py
To avoid orchagent crash issue like sonic-net/sonic-swss#2935, disable unsupported counters on SONiC management devices.
- Microsoft ADO **(number only)**: 25437720
Update the minigraph parser to disable unsupported counters on management devices.
1. Verified by unittest.
```
root@dd14c2cb8789:/sonic/src/sonic-config-engine/tests$ pytest-3 -v test_minigraph_case.py
============================================================== test session starts ==============================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-config-engine
plugins: pyfakefs-5.3.0, cov-2.10.1
collected 43 items
test_minigraph_case.py::TestCfgGenCaseInsensitive::test_additional_json_data …
```
=> [minigraph-parser] Disable unsupported counters on management devices

platform/broadcom/rules.mk, platform/broadcom/sonic-platform-modules-dell/common/dell_fpga_ocores.c, platform/broadcom/sonic-platform-modules-dell/debian/rules, platform/broadcom/sonic-platform-modules-dell/e3224f/modules/emc2305.c, platform/broadcom/sonic-platform-modules-dell/n3248pxe/modules/emc2305.c, platform/broadcom/sonic-platform-modules-dell/n3248te/modules/emc2305.c, platform/broadcom/sonic-platform-modules-dell/s6100/modules/dell_s6100_iom_cpld.c, platform/broadcom/sonic-platform-modules-dell/z9100/modules/dell_z9100_cpld.c, platform/broadcom/sonic-platform-modules-dell/z9332f/modules/cls-i2c-mux-pca954x.c, platform/broadcom/sonic-platform-modules-dell/z9332f/modules/mc24lc64t.c, platform/broadcom/sonic-platform-modules-dell/z9432f/modules/mc24lc64t.c
- https://github.com/sonic-net/sonic-buildimage/issues/16735
- Modified platform driver to comply with bookworm kernel.
- Removed MODULE_SUPPORTED_DEVICE wherever used.
- Modified python build commands for building whl packages.
- Verify whether all the platform bookworm debs are built. 
`make target/debs/bookworm/platform-modules-z9100_1.1_amd64.deb`
- Load the platform debian into the device and install it in bookworm image.
- Verify the platform related CLI and the functionality
=> [Bookworm] Upgrade Dell platforms to Bookworm

files/build_templates/sonic_debian_extension.j2, rules/openssh.mk, slave.mk, src/openssh/Makefile
This backports #16826, #16859, and #16896 to the 202205 branch, for updating OpenSSH to 1:8.4p1-5+deb11u2 and for fixing the subsequent build failures. This backport is being done in a single PR to avoid breakages in PR builds introduced by the first two PRs.
- Microsoft ADO **(number only)**: 25436638, 25517845
=> [202205] Update OpenSSH to 1:8.4p1-5+deb11u2

.azure-pipelines/azure-pipelines-build.yml
When using sonic-slave-buster to convert sonic-vs.img.gz to vhdx, it also needs reproducible options.
Otherwise it will rebuild sonic-slave-buster because tag different.
- Microsoft ADO **(number only)**:  25615544
Add build options to use same sonic-slave docker when generating vhdx image.
=> [ci] Fix build error when converting vhdx image.

rules/docker-sflow.mk
Run sflow sonic-mgmt tests
```
admin@vlab-01:~$ docker inspect sflow | grep Privi
admin@vlab-01:~$ docker exec -it sflow bash
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_ra …
```
=> [docker-sflow] limit privileged flag for sflow container

src/sonic-yang-models/yang-models/sonic-device_neighbor_metadata.yang
We use `EdgeZoneAggregator` in `db_migrator`, but we don't support this pattern in sonic yang models. Hence, we update this in the sonic-yang model.
- Microsoft ADO **(number only)**:  25574132
Update the device pattern list.
Update sonic-yang model to take in EdgeZoneAggregator as a device
=> Update sonic-yang model to take in EdgeZoneAggregator as a device

scripts/signing_kernel_modules.sh
```
ERROR: LOCAL_EXTRACT_CERT=/usr/lib/linux-kbuild-6.1/scripts/extract-cert file does not exist
./scripts/signing_kernel_modules.sh: # Display Help
./scripts/signing_kernel_modules.sh -l <LINUX_KERNEL_VERSION> -c <PEM_CERT> -p <PEM_PRIVATE_KEY> -s <LOCAL_SIGN_FILE> -e <LOCAL_EXTRACT_CERT> -k <KERNEL_MODULES_DIR>
Sign kernel modules in <KERNEL_MODULES_DIR> using private & public keys.
Parameters description:
LINUX_KERNEL_VERSION
PEM_CERT                             public key (pem format)
PEM_PRIVATE_KEY                      private key (pem format)
LOCAL_SIGN_FILE                      path of the sign-file tool for signing Kernel Modules, if the value is empty it will used the sign-file installed in /usr/lib/linux-kbuild-<version>/scripts
LOCAL_EXTRACT_CERT                   path of the …
```
=> [Bookworm] [Secure Boot] Fix the updated path for extract-cert binary

src/sonic-eventd/Makefile
Disabling eventd unit tests until https://github.com/sonic-net/sonic-buildimage/issues/16996 is addressed
Removed the UT from compilation target
Building with changes
=> [eventd]Disabling eventd unit tests

platform/checkout/cisco-8000.ini
Fix for MIGSMSFT-353: Addressed the issue where the XOFF rate went down from 10988 fps to 2746 fps. The reduced XOFF rate was not enough to block the 100G port.
move to cisco 202205.2.3.2
=> Update cisco-8000.ini to 202205.2.3.2

platform/broadcom/saibcm-modules/sdklt/linux/knet/ngknet_main.c
This is CSP CS00012280996.
The issue to fix is that the checksum was incorrect for all TCP packets leaving the system so that the BGP connection cannot be established.  We found the issue on BCM56993, and it is possible to affect all platforms using linux_ngknet.
Remove NETIF_F_HW_CSUM
We verified that the BGP connection is established according to 'show ip bgp summary'.
=> Disable NETIF_F_HW_CSUM in KNET

build_debian.sh, platform/marvell-arm64/rules.mk, platform/marvell-arm64/sonic-platform-nokia/7215/modules/nokia_7215_ixs_a1_cpld.c, platform/marvell-arm64/sonic_fit.its
This patch enables compiling of Marvell platform
module and fixes sonic-platform-nokia compilation
issues for bookworm.
For enabling bookworm build on Marvell-arm64 and fixing https://github.com/sonic-net/sonic-buildimage/issues/16734
Port Marvell SDK driver for bookworm  6.1 kernel.
Port Nokia CPLD driver for bookworm 6.1 kernel 
Built image from bookworm branch and installed on Marvell platform to 
verify "show interface status".
=> [marvell-arm64]: Enable SDK module for bookworm

src/sonic-config-engine/minigraph.py
Enable the suppress fib feature by default.
- Microsoft ADO **(25564723)**:
In minigraph.py, to add the field suppress-fib-pending, and enable it for leafrouter.
Build / load image and check the config_db by show CLI.
admin@str-7260cx3-acs-2:~$ show suppress-fib-pending
Enabled
Need to modify the tests/bgp/test_bgp_suppress_fib.py in sonic-mgmt repo, to check the config before restore. Otherwise, after this test, it will turn off the suppress-fib-pending. 
https://github.com/sonic-net/sonic-mgmt/pull/10612
=> Enable fib suppress for leafrouter by default

src/libteam/patch/0016-block-retry-count-changes.patch
Fixes #16875.
On physical devices, when doing a warm reboot on an image that supports the teamd retry count feature, with neighbor devices that are also running SONiC and support the teamd retry count feature, the LAG will become operationally down. Specifically, while the LAG won't go into expired or defaulted state, the DUT undergoing warm reboot will send a LACP PDU indicating it's not ready to send or receive traffic:
```
17:49:21.645115 1c:34:da:eb:bc:80 (oui Unknown) > 01:80:c2:00:00:02 (oui Unknown), ethertype Slow Protocols (0x8809), length 124: LACPv1, length 110
Actor Information TLV (0x01), length 20
System 1c:34:da:eb:bc:80 (oui Unknown), System Priority 65535, Key 1103, Port 121, Port Priority 255
State Flags [none]
Partner Information TLV (0x02), length 20
System …
```
=> Fix LAG going down after warm reboot with SONiC neighbors

device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn2100-r0/ACS-MSN2100/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn2410-r0/ACS-MSN2410/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn2740-r0/ACS-MSN2740/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn3420-r0/ACS-MSN3420/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn3700-r0/ACS-MSN3700/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn3700c-r0/ACS-MSN3700C/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn3800-r0/ACS-MSN3800/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn4410-r0/ACS-MSN4410/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn4600-r0/ACS-MSN4600/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn4600c-r0/ACS-MSN4600C/create_only_config_db_buffers.json, device/mellanox/x86_64-mlnx_msn4700-r0/ACS-MSN4700/create_only_config_db_buffers.json, device/mellanox/x86_64-nvidia_sn2201-r0/ACS-SN2201/create_only_config_db_buffers.json, device/mellanox/x86_64-nvidia_sn4800-r0/ACS-SN4800/create_only_config_db_buffers.json, device/mellanox/x86_64-nvidia_sn5600-r0/ACS-SN5600/create_only_config_db_buffers.json, device/mellanox/x86_64-nvidia_sn5600_simx-r0/ACS-SN5600/create_only_config_db_buffers.json, files/build_templates/docker_image_ctl.j2, src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json, src/sonic-yang-models/yang-models/sonic-device_metadata.yang
**DEPENDS ON:** [[202305][buffers] Add handler for the 'create_only_config_db_buffers' configuration knob](https://github.com/sonic-net/sonic-swss/pull/2941)
Add the `create_only_config_db_buffers` attribute to the `DEVICE_METADATA|localhost`. If the `"create_only_config_db_buffers"` exists and is equal to `"true"` -  the buffers will be created according to the config_db configuration (for example `BUFFER_QUEUE|*` table), otherwise the maximum available buffers (which are read from SAI) will be created, regardless of the `CONFIG_DB` buffers configuration.
Add the `create_only_config_db_buffers.json` files for Mellanox devices (not MSFT SKU's), and inject the content to the `CONFIG_DB` during the `swss` docker container start.
Manual verification:
1. …
=> [202305][buffers] Add 'create_only_config_db_buffers.json' file for the Mellanox devices (not MSFT SKU)

src/sonic-yang-models/tests/yang_model_tests/tests_config/snmp.json, src/sonic-yang-models/yang-models/sonic-snmp.yang
fixes https://github.com/sonic-net/sonic-buildimage/issues/16011
1. seeing below warning ,essage:
libyang[1]: Default value "" in the list key "port" is ignored. (/sonic-snmp:sonic-snmp/SNMP_AGENT_ADDRESS_CONFIG/SNMP_AGENT_ADDRESS_LIST)
libyang[1]: Default value "" in the list key "vrf_name" is ignored. (/sonic-snmp:sonic-snmp/SNMP_AGENT_ADDRESS_CONFIG/SNMP_AGENT_ADDRESS_LIST)
2.  name of list is not <model_name>_LIST.
- Microsoft ADO 25646016:
1. Remove default value provided to key in yang model to avoid seeing below error:
libyang[1]: Default value "" in the list key "port" is ignored. (/sonic-snmp:sonic-snmp/SNMP_AGENT_ADDRESS_CONFIG/SNMP_AGENT_ADDRESS_LIST)
libyang[1]: Default value "" in the list key "vrf_name" is ignored. (/sonic-snmp:sonic-snmp/SNMP_AGENT_ADDRESS_CONFIG/SNMP_AGENT_ …
=> [YANG]: Fix SNMP_AGENT_ADDRESS_CONFIG yang model

src/sonic-config-engine/minigraph.py
Cherry pick #17072
- Microsoft ADO **(25564723)**:
=> Cherry pick to 202305 - Enable fib suppress for leafrouter by default

src/sonic-host-services/scripts/caclmgrd, src/sonic-host-services/tests/caclmgrd/caclmgrd_soc_rules_test.py, src/sonic-host-services/tests/caclmgrd/test_soc_rules_vectors.py
Master branch PR https://github.com/sonic-net/sonic-host-services/pull/82
Need to open because sonic-host-services is not present in 202205 as a submodule
This PR is a required for changing the L3 IP forwarding Behavior to SoC in active-active toplogy. 
Basically a src IP is added to the SNAT rule so that only packets originating from ToR with src IP as vlan IP get natted by the rule and change the src IP to LoopBack IP
However if there are mutiple vlan IP's we only add the source IP as vlan IP,  for which the SoC IP belongs to, this PR adds that change.
check the config DB if the ToR is a DualToR and has an SoC IP assigned.
put an iptable rule
iptables -t nat -A POSTROUTING --destination -j SNAT --to-source "
Signed-off-by: vaibhav-dahiya …
=> [DualToR][caclmgrd] Fix IPtables rules for multiple vlan interfaces for DualToR config

.azure-pipelines/docker-sonic-mgmt-legacy.yml
This is part of Python3 migration project.
This pipeline will build sonic-mgmt-docker with both Python2 and Python3.
The main difference between legacy sonic-mgmt-docker and now is:
make **LEGACY_SONIC_MGMT_DOCKER=y** target/docker-sonic-mgmt.gz
docker tag docker-sonic-mgmt $REGISTRY_SERVER/docker-sonic-mgmt:**legacy**
- Microsoft ADO **(number only)**: 25254349
Add pipeline file.
N/A
=> Add Azure pipeline to build legacy sonic-mgmt-docker

device/mellanox/x86_64-nvidia_sn5600-r0/platform.json, device/mellanox/x86_64-nvidia_sn5600_simx-r0/platform.json
Removing 8x split DPB mode from platform files since it is not fully supported yet.
Updating platform file.
Manual testing.
=> [Mellanox] [SN5600] Removing 8x DPB mode from platform files

src/sonic-config-engine/tests/simple-sample-graph-case.xml, src/sonic-config-engine/tests/test_minigraph_case.py, src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/yang_model_tests/tests/device_neighbor_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_neighbor_metadata.json, src/sonic-yang-models/yang-models/sonic-device_neighbor_metadata.yang
The current DEVICE_NEIGHBOR_METADATA yang model has two issues that would block GCU operation when it checks if the current config aligns with the YANG model：
1. Missing cluster field in YANG
2. Incomplete set of device type. The device type in YANG model doesn't include all the device type.
- Microsoft ADO **(number only)**: 25577813
1. Add cluster field in DEVICE_NEIGHBOR_METADATA YANG model.
2. Change device type to string.
3. Fix the UT test accordingly.
Build the image and verify the unit tests passed.
=> Fix device type and add cluster in DEVICE_NEIGHBOR_METADATA yang model

src/sonic-config-engine/tests/simple-sample-graph-case.xml, src/sonic-config-engine/tests/test_minigraph_case.py, src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/yang_model_tests/tests/device_neighbor_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_neighbor_metadata.json, src/sonic-yang-models/yang-models/sonic-device_neighbor_metadata.yang
Fix device type and add cluster in DEVICE_NEIGHBOR_METADATA yang model (Cherry-pick of #17049)
The current DEVICE_NEIGHBOR_METADATA yang model has two issues that would block GCU operation when it checks if the current config aligns with the YANG model：
1. Missing cluster field in YANG
2. Incomplete set of device type. The device type in YANG model doesn't include all the device types
- Microsoft ADO **(number only)**: 25577813
Add cluster field in DEVICE_NEIGHBOR_METADATA YANG model. Change device type to string.
Build the image and verify the unit tests passed.
=> [Cherry-pick to 202305] Fix device type and add cluster in DEVICE_NEIGHBOR_METADATA yang model

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json, src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Orchagent uses PORTCHANNEL term when parsing this field. Change the YANG model to align to orchagent.
When specifying PORTCHANNEL in ACL_TABLE_TYPE table YAGN model validation does not pass, when using term LAG orchagent does not accept such table type.
Fix it by aligning YANG model to orchagent.
Fix in YANG model.
Create custom ACL table type.
=> [YANG][ACL] Change LAG -> PORTCHANNEL in DB schema

dockers/docker-orchagent/tunnel_packet_handler.py
- A race condition exists while the TPH is processing a netlink message - if a second netlink message arrives during processing it will be missed since TPH is not listening for other messages.
- Another bug was found where TPH was unnecessarily restarting since it was checking admin status instead of operational status of portchannels.
- Microsoft ADO **(number only)**: 23622217
- Subscribe to APPL_DB for updates on LAG operational state
- Track currently sniffed interfaces
- Send tunnel packets with destination IP of an unresolved neighbor, verify that `ping` commands are run
- Shut down a portchannel interface, verify that sniffer does not restart
- Send tunnel packets, verify `ping` commands are still run
- Bring up portchannel interface, verify that sniffer restarts
=> [tph]: Detect LAG flaps from APPL_DB

src/sonic-frr/patch/0026-zebra-Add-encap-type-when-building-packet-for-FPM.patch, src/sonic-frr/patch/series
Back port a patch from upstream FRR - https://github.com/FRRouting/frr/pull/14675
The EVPN route is not treated correctly and thus leading to messages:
```
Oct 30 11:40:00.494083 r-tigris-22 INFO swss#orchagent: :- addRoute: Failed to get next hop 30.0.0.2@Vlan200 for 20.0.0.2/32, resolving neighbor
Oct 30 11:40:00.494083 r-tigris-22 INFO swss#orchagent: :- addRoute: Failed to get next hop 30.0.0.2@Vlan200 for 200.0.0.0/24, resolving neighbor
Oct 30 11:40:00.494083 r-tigris-22 INFO swss#orchagent: :- addRoute: Failed to get next hop ::ffff:30.0.0.2@Vlan200 for 200::/64, resolving neighbor
Oct 30 11:40:00.494083 r-tigris-22 INFO swss#orchagent: :- addRoute: Failed to get next hop ::ffff:30.0.0.2@Vlan200 for 20::/64, resolving neighbor
Oct 30 11:40:00.494083 r-tigris-22 INFO swss#orchagent: …
```
=> [FRR][patch] Add encap type when building packet for FPM

rules/openssh.mk, slave.mk
This backports #16859, and #16896 to the 202211 branch, for fixing the subsequent build failures after the OpenSSH update to 1:8.4p1-5+deb11u2. This backport is being done in a single PR to avoid breakages in PR builds.
- Microsoft ADO **(number only)**: 25517845
=> [202211] Fix build failures after OpenSSH update to 1:8.4p1-5+deb11u2

src/sonic-config-engine/minigraph.py
PR checker is blocked by container_checker.
Disable telemetry in minigraph parser.
Run pipeline and sanity check.
=> Disable telemetry feature

dockers/docker-orchagent/tunnel_packet_handler.py
Why I did it
A race condition exists while the TPH is processing a netlink message - if a second netlink message arrives during processing it will be missed since TPH is not listening for other messages. Another bug was found where TPH was unnecessarily restarting since it was checking admin status instead of operational status of portchannels.
How I did it
Subscribe to APPL_DB for updates on LAG operational state Track currently sniffed interfaces
Send tunnel packets with destination IP of an unresolved neighbor, verify that ping commands are run Shut down a portchannel interface, verify that sniffer does not restart Send tunnel packets, verify ping commands are still run Bring up portchannel interface, verify that sniffer restarts
Cherry pick #16879 
- Microsoft ADO …
=> [202205][tph]: Detect LAG flaps from APPL_DB (#16879)

.azure-pipelines/docker-sonic-mgmt-py3-only.yml, .azure-pipelines/docker-sonic-mgmt.yml
- Microsoft ADO **(number only)**: 25858445
docker-sonic-mgmt.yml will build docker with Python2 and Python3 both.
docker-sonic-mgmt-py3-only.yml will build docker with Python3 only.
=> Add Python3-only sonic-mgmt-docker build pipeline file

src/protobuf/Makefile
In the ubuntu environment, the debian server key wasn't installed by default. So, we will get the following error in the Azp pipeline 
```
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Signature made Sun Apr  9 06:25:32 2023 UTC
gpg:                using RSA key 7D887DC8BA7BBBA7B835E3BADCE310E7864CC8BF
gpg: Can't check signature: No public key
gpg: can't create `/home/vsts/.gnupg/random_seed': No such file or directory
Validation FAILED!!
```
Disable the validation via the option `-u` in the dget.
Check Azp status
=> [Protobuf]: Disable debian verification

sonic-slave-bullseye/Dockerfile.j2
Fix for https://github.com/sonic-net/sonic-buildimage/issues/16204
- Microsoft ADO **(number only)**:  25746782
multiarch/debian-debootstrap:arm64-bullseye is too old.
It needs to add some gpg keys before 'apt-get update'
=> [build] Add gpg keys for sonic-slave-bullseye in arm64 cross build on amd64.

dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
dhcp_relay dual tor tests are failing in 202305
Backport https://github.com/sonic-net/sonic-buildimage/pull/15864 to 202305
Ran sonic-mgmt dhcp_relay tests.
=> [202305] Fix dhcpv6relay dual tor if selection issue

rules/docker-macsec.mk
cherry pick https://github.com/sonic-net/sonic-buildimage/pull/16894
Privileges and volumes were incorrectly set in macsec container. Privileged flag is set to false and volumes are not mounted properly.
```
admin@vlab-01:~$ docker inspect macsec0 | grep Privi
admin@vlab-01:~$ docker inspect macsec0 | grep -A 10 Binds
"Binds": [
"/var/run/redis0:/var/run/redis:rw",
"/var/run/redis-chassis:/var/run/redis-chassis:ro",
"/usr/share/sonic/device/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0:/usr/share/sonic/hwsku:ro",
"/var/run/redis0/:/var/run/redis0/:rw",
"/usr/share/sonic/device/x86_64-nokia_ixr7250e_36x400g-r0:/usr/share/sonic/platform:ro"
],
```
Make sure privileged settings remain unchanged and make sure volumes are …
=> [202305] [docker-macsec] fix privileged and volumes settings

Makefile.work, sonic-slave-bookworm/Dockerfile.user.j2
Fix https://github.com/sonic-net/sonic-buildimage/issues/17155
Check the ticket for more details
```
vkarri@build-server:/sonic-buildimage$ NOBUSTER=1 NOBULLSEYE=1 make SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD=y sonic-slave-bash
vkarri@0fdfd946d5a7:/sonic$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
vkarri@0fdfd946d5a7:/sonic$ docker ps -a
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                      PORTS     NAMES
0fdfd946d5a7   sonic-slave-bookworm-vkarri:969180aefd …
```
=> [bookworm] Fix docker gid mismatch with host 

device/arista/x86_64-arista_7280cr3_32p4/platform_env.conf, device/arista/x86_64-arista_7800r3_48cq2_lc/platform_env.conf, device/arista/x86_64-arista_7800r3_48cqm2_lc/platform_env.conf, device/arista/x86_64-arista_7800r3a_36d2_lc/platform_env.conf
SAI 9.x requires a SYNCD_SHM_SIZE specified otherwise it will default to 64mb which is insufficient for syncd.
E.G. of a few failures seen when insufficient shmem was set
```
ha_init:  The file: warmboot_data_0 is of size=762[MB] and is beyond the directory: /dev/shm available storage of size=64[MB]#015
```
```
syncd.sh[26074]: Cannot get SYNCD_SHM_SIZE for chip: [869] in /usr/share/sonic/device/x86_64-broadcom_common/syncd_shm.ini. Skip set SYNCD_SHM_SIZE.
```
Syncd hangs here:
```
syncd#syncd: [none] SAI_API_SWITCH:_brcm_sai_shr_ha_section_resize:536 start=0x7f6e641b4000, end=0x7f6e645b4000, len=302276608, free=0x7f6e641b4000
```
Broadcom recommended using 1gb for DNX devices.
Since currently we don't use SAI9.x on master and 202305 this change won't fix anything until we upgrade the …
=> Set SYNCD_SHM_SIZE for Arista DNX Devices

dockers/docker-database/Dockerfile.j2, dockers/docker-database/database_config.json.j2, dockers/docker-database/database_global.json.j2, dockers/docker-database/docker-database-init.sh, files/build_templates/docker_image_ctl.j2, src/sonic-py-common/sonic_py_common/device_info.py, src/sonic-yang-models/yang-models/sonic-feature.yang
Sub PRs:
https://github.com/sonic-net/sonic-host-services/pull/84
https://github.com/sonic-net/sonic-buildimage/pull/17191
According to the design, the database instances of DPU will be kept in the NPU host.
- Microsoft ADO **(number only)**: 25072889
To follow the multiple ASIC design, I assume a new platform environment variable `NUM_DPU` will be defined in the `/usr/share/sonic/device/$PLATFORM/platform_env.conf`. Based on this number, NPU host will launch a corresponding number of instances for the DPU database.
1. Defined `NUM_DPU` in the platform_env.conf
2. Declare a new field in the config_db for database feature.
3. remove the existing databse service by 'docker rm -f database' and reboot OS.
We should get multiple database services and global_config as following.
=> [dpu]: Add DPU database service

platform/mellanox/mlnx-fw-upgrade.j2
In order to activate FW after it was upgraded need to perform reboot.
If reboot wasn't performed and user need  to upgrade to another SONiC image then it will fail.
The reason for that is that during SONiC upgrade new FW should be installed but it will fail because previously installed FW wasn't activated.
In order to allow 2nd FW upgrade without reboot in-between need to reactivate FW image.
This change handles such flow.
Example of issue scenario:
- User installed SONiC image on the switch
- Then for some reason FW was upgraded by user or script but reboot was not performed to activate it.
- After that upgrade to new SONiC image will fail because new image need to install FW but it fails due to previous one wasn't activated.
In "mlnx-fw-upgrade" script …
=> [mlnx-fw-upgrade] Add FW reactivation in case 2 FW upgrades were done without reboot

installer/default_platform.conf
GRUB environment file is neither generated when SONiC is installed from ONiE nor when GRUB starts boot chain sequence
```
https://github.com/sonic-net/sonic-buildimage/blob/202305/installer/default_platform.conf#L506
cat <<EOF >> $grub_cfg
if [ -s \$prefix/grubenv ]; then
load_env
fi
if [ "\${saved_entry}" ]; then
set default="\${saved_entry}"
fi
if [ "\${next_entry}" ]; then
set default="\${next_entry}"
unset next_entry
save_env next_entry
fi
if [ "\${onie_entry}" ]; then
set next_entry="\${default}"
set default="\${onie_entry}"
unset onie_entry
save_env onie_entry next_entry
fi
EOF
```
The GRUB environment file is being regenerated (if not present) each time after system cold reboot, when SONiC reboot script is being called
``` …
```
=> [installer] Create a blank grubenv if doesn't exist

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/hash.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/hash.json, src/sonic-yang-models/yang-models/sonic-hash.yang, src/sonic-yang-models/yang-templates/sonic-types.yang.j2
**HLD:** https://github.com/sonic-net/SONiC/pull/1501
* Added YANG model as part of Generic Hash feature development
* N/A
* Added YANG model 
1. Add UT 
2. Verified manually with the feature qualification
* Added hashing algorithm configuration
* [sonic-hash.yang](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-hash.yang)
```
'//||\\`
''``
```
=> [hash]: Add ECMP/LAG Hash Algorithm YANG model

files/build_templates/sonic_debian_extension.j2
To fix broken FW link.
```$SONIC_IMAGE_VERSION``` does not exist in 201911 build system. Use ```$(sonic_get_version)``` instead of ```$SONIC_IMAGE_VERSION```.
Boot the system and see the links are correct:
```
admin@arc-switch1025:~$ ls -al /etc/mlnx/
total 4
drwxr-xr-x 3 root root  103 Jul 17 11:22 .
drwxr-xr-x 1 root root 4096 Jul 17 11:56 ..
drwxr-xr-x 2 root root   42 Jul 17 11:22 cpld
lrwxrwxrwx 1 root root   73 Jul 17 11:22 fw-SPC2.mfa -> /host/image-1911-fix-broken-link.0-6aef24420/platform/fw/asic/fw-SPC2.mfa
lrwxrwxrwx 1 root root   73 Jul 17 11:22 fw-SPC3.mfa -> /host/image-1911-fix-broken-link.0-6aef24420/platform/fw/asic/fw-SPC3.mfa
lrwxrwxrwx 1 root root   72 Jul 17 11:22 fw-SPC.mfa -> …
```
=> [201911][nvidia] Fix broken FW links 

src/sonic-host-services/scripts/hostcfgd, src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py, src/sonic-host-services/tests/hostcfgd/test_vectors.py
This is cherry-pick PR.. Master branch PR. https://github.com/sonic-net/sonic-host-services/pull/83
Issue details and RCA here. https://github.com/sonic-net/sonic-buildimage/issues/16991
- Microsoft ADO **25422412**:
Currently hostcfgd script overrides the systemd service files of the features depending upon auto_restart enable/disable.
I am skipping dependent features(syncd, gbsyncd for now) to have "RESTART=Always"
for them to not start immediately, and instead get started by SWSS through swss.sh script.
The issue of syncd double stop is also applicable to pizza box platforms, however no traffic impact is seen there, whereas on VOQ chassis, we do see traffic impact due to early start of syncd service.
The change can be extended to pizza box platforms as well in future once it gets …
=> Disable systemd auto-restart of dependent services for spineRouters

files/build_templates/lldp.timer.j2, files/scripts/syncd.sh
As part of service start optimization done, we've removed timer units and used PORT_INIT_DONE as the checkpoint for starting delayed services. Thus this logic is redundant
This fixes the following error log. 
```
Nov  3 14:16:54.281546 r-leopard-44 ERR systemctl[10553]: Failed to get unit file state for lldp.timer: No such file or directory
```
Redundant lldp timer code is removed from syncd.sh. 
Build and test
=> [lldp] Clean up service start logic owing to port init start optimization

device/virtual/x86_64-kvm_x86_64-r0/SONiC-VM/fabric_port_config.ini, platform/vs/docker-sonic-vs/start.sh, platform/vs/docker-sonic-vs/supervisord.conf.j2
Add fabric port data for vs test, and start fabricmgrd in vs environment.
This PR depends on https://github.com/sonic-net/sonic-sairedis/pull/1301
https://github.com/sonic-net/sonic-swss/pull/2920 needs this one merge first.
=> Add fabric port data for vs test, and start fabricmgrd in vs environment

rules/docker-restapi.mk
Run restapi sonic-mgmt tests on sn4600c
```
admin@vlab-01:~$ docker inspect restapi | grep Privi
admin@vlab-01:~$ docker exec -it restapi bash
```
=> [docker-restapi] limit privileged flag for restapi container

device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O28/hwsku.json
Fix the issue with configuration generation from the minigrapth:
```
root@sonic:/home/admin# config load_minigraph -y
Disabling container monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
File "/usr/local/bin/sonic-cfggen", line 452, in <module>
main()
File "/usr/local/bin/sonic-cfggen", line 342, in main
deep_update(data, parse_xml(minigraph, platform, asic_name=asic_name))
File "/usr/local/lib/python3.9/dist-packages/minigraph.py", line 1542, in parse_xml
(ports, alias_map, alias_asic_map) = get_port_config(hwsku=hwsku, platform=platform, port_config_file=port_config_file, asic_name=asic_name, hwsku_config_file=hwsku_config_file)
File …
```
=> [Mellanox] Change the default breakout mode for internal ports of the Mellanox-SN4700-O28 SKU.

dockers/docker-database/docker-database-init.sh
Fix bug: https://github.com/sonic-net/sonic-buildimage/pull/17161#discussion_r1397850480
multi-asic platforms it will never go to the else part as DATABASE_TYPE is always ""
- Microsoft ADO **(number only)**: 25072889
Move the checker `NAMESPACE_ID == ""` back
Check Azp
=> [docker-database-init.sh]:Fix wrong creating of database_global.json in multi asic platform

files/image_config/copp/copp_cfg.j2
* Change DHCP rate limit in SONiC copp configuration to 100 PPS as this is necessary to ensure that DHCP flood does not cause LACP/BGP flaps in some scenarios. This is an extension to the change in https://github.com/sonic-net/sonic-buildimage/pull/14859 and sonic-mgmt change in https://github.com/sonic-net/sonic-mgmt/pull/8199
300 PPS is not sufficient to prevent LACP/BGP flaps in all cases. 100 PPS seems to provide better resiliency against DHCP traffic flood to CPU.
- Microsoft ADO **25776614**:
Reduced rate limit for queue4_group3 in copp configuration to 100 PPS from 300 PPS.
Send DHCP broadcast packets to DUT and verify that they are trapped to CPU at 100 PPS.
Change DHCP rate limit in SONiC copp configuration to 100 PPS as this is necessary to ensure that DHCP flood does not cause …
=> [image_config]: Update DHCP rate-limit

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/simple-sample-graph-case.xml, src/sonic-config-engine/tests/test_minigraph_case.py, src/sonic-yang-models/yang-models/sonic-vlan.yang
This is change taken as part of the HLD: https://github.com/sonic-net/SONiC/pull/1470. 
In this PR we add the logic to parse the SecondarySubnets field in the minigraph and add a flag in "secondary" in the vlan_interface table of the config db.
- Microsoft ADO **(number only)**: 16784946
Made changes in the minigraph.py to parse the xml entry and add the parsed value to the config db 
Added python tests in the sonic-config-engine folder to test the config db entries.
Adding new secondary field to VLAN_INTERFACE table
=> Adding new secondary field to VLAN_INTERFACE table

src/sonic-frr/patch/0027-zebra-Fix-non-notification-of-better-admin-won.patch, src/sonic-frr/patch/series
To fix https://github.com/sonic-net/sonic-buildimage/issues/17183.
When a route is getting advertised from two paths through network command, only one of the paths is chosen. This was fixed in FRR through https://github.com/FRRouting/frr/pull/14795
Porting the FRR fix
Manually tested the scenario. Additionally verified through regression.
=> [FRR] Fixing zebra to handle non notification of better admin won

src/sonic-yang-mgmt/sonic-cfg-help, src/sonic-yang-mgmt/tests/test_cfghelp.py
Fixing sonic-cfg-help to handle nested container scenario. In case of nested container, the inner container name acts as key for the table. For e.g. 
```
"AUTO_TECHSUPPORT": {
"GLOBAL": {
}
}
```
Previous output
```
AUTO_TECHSUPPORT
Description: AUTO_TECHSUPPORT part of config_db.json
+-------------------------+----------------------------------------------------+-------------+-----------+-------------+
| Field                   | Description                                        | Mandatory   | Default   | Reference   |
+=========================+====================================================+=============+===========+=============+
| state                   | Knob to make techsupport invocation event-driven   |             |           |             |
|                         | …
```
=> [yang]Fixing sonic-cfg-help to handle nested container

sonic-slave-bullseye/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
The json.hpp header file from that package is used in the sonic-swss-common build. An old version of that header file (from 2016) has been checked into the sonic-swss-common repo. However, since then, there have been changes to that header file, and starting with GCC 12 in Bookworm, generates some errors about variables being possibly uninitialized before use.
- Microsoft ADO **(number only)**: 25027439
To fix this, install the nlohmann-json3-dev package, and allow using the header file from the Debian package instead of a static checked-in version. The version in Debian Bullseye is much newer than this version.
With this change alone, sonic-swss-common will still be using the json.hpp file in its own codebase. The change to actually use the system header file instead of the local header …
=> Add nlohmann-json3-dev package into the slave container (#16308)

src/sonic-config-engine/tests/simple-sample-graph-case.xml, src/sonic-config-engine/tests/test_minigraph_case.py, src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/yang_model_tests/tests/device_neighbor_metadata.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/device_neighbor_metadata.json, src/sonic-yang-models/yang-models/sonic-device_neighbor_metadata.yang
This is the cherry-pick PR for #17049.
The current DEVICE_NEIGHBOR_METADATA yang model has two issues that would block GCU operation when it checks if the current config aligns with the YANG model：
- Missing cluster field in YANG
- Incomplete set of device type. The device type in YANG model doesn't include all the device type. Work item tracking
- Microsoft ADO **(number only)**: 25577813
Add cluster field in DEVICE_NEIGHBOR_METADATA YANG model. Change device type to string.
Fix the UT test accordingly.
Build the image and verify the unit tests passed.
=> [202205] Fix device type and add cluster in DEVICE_NEIGHBOR_METADATA yang model

device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm, src/sonic-device-data/tests/permitted_list
This change was submitted directly to `202205` but it's also needed in `master` and `202305` with SAI9.x
https://github.com/sonic-net/sonic-buildimage/pull/13346
There has been a couple CSPs for this as well:
CS00012273013 - [7.1][J2, J2c+] Disable SA Equals DA trap on DNX
CS00012320965 - SAI9.2: iBGP doesn't work due to SA_EQUALS_DA trap
If SA_EQUALS_DA trap is enabled iBGP won't work as the `Ethernet-IB0` ports are expected to get packets with SA==DA.
E.G. iBGP not working:
```
nfc405-3# show ip bgp summary -d all
IPv4 Unicast Summary:
BGP router identifier 8.0.0.1, local AS number 65100 vrf-id 0
BGP table version 136206
RIB entries 101651, using 19516992 bytes of memory
Peers 5, using 3709880 KiB of memory
Peer groups 4, using 256 bytes of memory
Neighbhor      V     AS    MsgRcvd …
```
=> Disable SA_EQUALS_DA trap on DNX LC SKUs

device/arista/x86_64-arista_7800_sup/chassisdb.conf
port https://github.com/sonic-net/sonic-buildimage/pull/10519 to 202205 branch
- Microsoft ADO **(25260643)**:
Change the `lag_id_end` to `1024`
=> [202205] Increase LAG Ids to 1024

dockers/docker-sonic-mgmt/Dockerfile.j2
- Microsoft ADO **(number only)**: 25254350
Remove Python3 venv in Python3-only sonic-mgmt-docker
There is no impact to sonic-mgmt-docker:latest tag.
Build sonic-mgmt-docker with LEGACY_SONIC_MGMT_DOCKER=y, see python3 venv is there.
Build sonic-mgmt-docker with LEGACY_SONIC_MGMT_DOCKER=n, see python3 venv is NOT included.
=> Remove Python3 venv in Python3-only sonic-mgmt-docker

dockers/docker-platform-monitor/Dockerfile.j2, files/build/versions/dockers/docker-platform-monitor/versions-py3
Cherry-pick conflict 
https://github.com/sonic-net/sonic-buildimage/pull/16257
#16257 
=> [pmon] update gRPC version to 1.57.0 (#16257)

files/scripts/arp_update
- Prevent packet drops due to MAC expiration in hardware
- Mitigate MAC mismatch between kernel and APPL_DB neighbor table
- Microsoft ADO **25135974** and **25647679**:
- Load script onto some DUT, wait for MAC entries to expire (`show arp` will have entries with 'Iface' listed as '-'). Run the arp_update script. After several seconds confirm that the expired entries are no longer present in `show arp`
- For some learned neighbor, manually set the APPL_DB MAC address in the neighbor table to a value different from the MAC address learned in the kernel. Run the arp_update script, confirm that the neighbor is flushed.
- [ 20220531.38]
=> [arp_update]: Flush neighbors with incorrect MAC info

platform/marvell-armhf/sonic-platform-nokia/7215/scripts/cpu_wdt.py, platform/marvell-armhf/sonic-platform-nokia/7215/service/cpu_wdt.service, platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/watchdog.py, platform/marvell-armhf/sonic-platform-nokia/debian/sonic-platform-nokia-7215.install, platform/marvell-armhf/sonic-platform-nokia/debian/sonic-platform-nokia-7215.postinst
Enable watchdog for Nokia 7215 platform
- Microsoft ADO **(number only)**: 24981141 
Implement service which arm's the watchdog and send keep alive every minute.
start service be default on boot up
Verify Watchdog is enabled on boot up:
"sudo systemctl status cpu_wdt.service" should show that service as active 
admin@sonic:~$ sudo watchdogutil status
Status: Armed
Time remaining: 138 seconds
Stop Service and verify watchdog is disarmed:
admin@sonic:$ sudo systemctl stop cpu_wdt.service 
admin@sonic:$ sudo watchdogutil status
Status: Unarmed
Logs added to notify service being armed/Disarmed and for every keep alive(every 55 seconds) 
```
2430:2023-10-13T01:42:11.077639+00:00 sonic Watchdog: CPUWDT Enabled: watchdog armed=True
2988:Oct 13 01:43:06.132343 sonic INFO Watchdog: CPUWDT …
```
=> [armhf][Nokia-7215] Enable Watchdog service 

src/sonic-device-data/tests/media_checker
The format of the media_settings.json file was updated to support the Port SI Per Speed Enhancements. Since media_checker is the validator for the media_settings.json file, it needs to be updated to align with the new format.
I added six new SI parameter names introduced as part of the Port SI Per Speed Enhancements. Additionally, I implemented handling for the new hierarchy level (lane_speed_key) in the updated media_settings.json format while maintaining backward compatibility with vendors whose JSON does not support port SI per speed.
I locally built the Debian package using 'make target/debs/bullseye/sonic-device-data_1.0-1_all.deb,' and it completed successfully. Jenkins also built the entire image, which includes the media_checker as part of its …
=> Media_settings.json Validator Update

files/image_config/rsyslog/rsyslog-container.conf.j2
Mellanox MSN2410 platforms have a non-functional error log: "ERR pmon#sensord: Error getting sensor data: dps460/#10: Can't read". This error is because of a firmware issue with some PSU, we are not able to upgrade the FW online. Since there is no functional impact, this error log can be ignored safely
Add a new rsyslog rule to the rsyslog-container.conf.j2, if the docker name is pmon and the platform name matches, the new rule will be inserted into the docker rsyslogd.conf
run regression on the MSN2410 platform to make the error log will not be printed to the syslog.
=> [Mellanox] Add special rsyslog filter for MSN2410 platform

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/simple-sample-graph-m0.xml, src/sonic-config-engine/tests/simple-sample-graph-mx.xml, src/sonic-config-engine/tests/test_minigraph_case.py
Backport #16937
To avoid orchagent crash issue like sonic-net/sonic-swss#2935, disable unsupported counters on SONiC management devices.
**Work item tracking**
Microsoft ADO (number only): 25437720
**How I did it**
Update the minigraph parser to disable unsupported counters on management devices.
**How to verify it**
Verified by unittest.
Manually apply patch to DUT and do config load_minigraph
- Microsoft ADO **(number only)**: 24802410
=> [202012][minigraph-parser] Disable unsupported counters on management devices

dockers/docker-platform-monitor/Dockerfile.j2, files/build/versions/dockers/docker-platform-monitor/versions-py3
Reverts sonic-net/sonic-buildimage#17218
=> Revert "[pmon] update gRPC version to 1.57.0 (#16257)"

.gitmodules
Lock down some sub-module branches to avoid future confusions.
This PR test.
=> [202311] lock down some sub module branches

device/mellanox/x86_64-mlnx_msn2700a1-r0/installer.conf
Remove logs_inram kernel option
Remove logs_inram kernel option
Regression test
Full sonic-mgmt regression t0/t1-lag passed.
The change is to prevent log to RAM on 2700 A1 platform. It is to align with 2700 platform.
=> [Mellanox] Remove log in RAM kernel option for 2700 A1 platform

dockers/docker-fpm-frr/docker_init.sh, dockers/docker-fpm-frr/frr/zebra/zebra.conf.j2, platform/vs/docker-sonic-vs/frr/zebra.conf, src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/zebra.conf, src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-vni-zebra.conf, src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-zebra.conf, src/sonic-config-engine/tests/sample_output/py2/zebra_frr.conf, src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-vni-zebra.conf, src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-zebra.conf, src/sonic-config-engine/tests/sample_output/py3/zebra_frr.conf
Closes https://github.com/sonic-net/sonic-buildimage/issues/17345
This W/A was proposed by Nvidia FRR team before the long term solution is ready.
* A W/A to fix default route installation during LAG member flap
* N/A
* Disabled FRR next hop group support
1. Do LAG member flap
* N/A
* N/A
```
'//||\\`
''``
```
=> [FRR] Force disable next hop group support

dockers/docker-snmp/snmpd.conf.j2, dockers/docker-snmp/start.sh, src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/sample_graph.xml, src/sonic-config-engine/tests/test_cfggen.py, src/sonic-config-engine/tests/test_multinpu_cfggen.py
table
SNMP query over IPv6 does not work due to issue in net-snmp where IPv6 query does not work on multi-nic environment.
To get around this, if snmpd listens on specific ipv4 or ipv6 address, then the issue is not seen.
We plan to configure Management IP and Loopback IP configured in minigraph.xml as SNMP_AGENT_ADDRESS in config_db., based on changes discussed in https://github.com/sonic-net/SONiC/pull/1457.
- Microsoft ADO **(number only)**:26091228
Modify minigraph parser to update SNMP_AGENT_ADDRESS_CONFIG with management and Loopback0 IP addresses.
Modify snmpd.conf.j2 to use SNMP_AGENT_ADDRESS_CONFIG table if it is present in config_db, if not listen on any IP.
Main change:
1. if minigraph.xml is used to configure the device, then snmpd will listen on mgmt and loopback IP …
=> [SNMP]: Modify minigraph parser to update SNMP_AGENT_ADDRESS_CONFIG

files/image_config/config-chassisdb/config-chassisdb
No cache:
```
root@arc-switch1004:/home/admin# time bash -x /usr/bin/config-chassisdb
+ config_chassis_db
+ startdb_file=/etc/sonic/chassisdb.conf
+ '[' '!' -e /etc/sonic/chassisdb.conf ']'
++ sonic-cfggen -H -v DEVICE_METADATA.localhost.platform
+ platform=x86_64-mlnx_msn2700-r0
+ chassis_config=/usr/share/sonic/device/x86_64-mlnx_msn2700-r0/chassisdb.conf
+ '[' '!' -e /usr/share/sonic/device/x86_64-mlnx_msn2700-r0/chassisdb.conf ']'
+ echo 'no chassisdb.conf found, bypass config-chassisdb service'
no chassisdb.conf found, bypass config-chassisdb service
+ exit 0
real    0m0.512s
user    0m0.429s
sys     0m0.058s
```
With cache:
```
root@arc-switch1004:/home/admin# time bash -x /usr/bin/config-chassisdb
+ '[' -f /etc/sonic/sonic-environment ']'
+ . /etc/sonic/sonic-environment
++ …
```
=> [config-chassisdb] use cached variables

platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py
To modify EEPROM API serial_number_str to return service tag instead of serial number in Dell S6100.
Ref PR: #1239 
Update EEPROM API serial_number_str to return service tag instead of serial number.
Verify `decode-syseeprom -s` returns service tag in Dell S6100.
Logs: [UT_logs.txt](https://github.com/sonic-net/sonic-buildimage/files/13596493/UT_logs.txt)
[Dell] S6100 - Update EEPROM API serial_number_str to return service tag instead of serial number
=> [Dell] S6100 - Update EEPROM API serial_number_str to return service tag instead of serial number

dockers/docker-platform-monitor/Dockerfile.j2, files/build/versions/dockers/docker-platform-monitor/versions-py3
Reverts sonic-net/sonic-buildimage#16257
The version upgraded in #16257 is beyond (newer than) the supported version in bookworm. This new package caused some issues on some platform. Reverting to keep the version within the Debian distribution supported range.
=> Revert "[pmon] update gRPC library and gRPC IO tools version to 1.57.0"

dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Need show range to show dhcp_server range setting.
Add cli
Run unit test
master image from https://github.com/sonic-net/sonic-buildimage/pull/17051
Add show range to dhcp_server cli
=> [dhcp_server] add show range cli

platform/mellanox/mft/Makefile
A W/A to overcome delay of about 20 sec on login due to MFT bash autocompletion bug.
Should be reverted once a formal solution will be available in future MFT release.
* To overcome SN2700 20 sec delay on login
* N/A
* Removed MFT bash autocompletion part
3. Verify no such links after system boot.
* N/A
* N/A
```
'//||\\`
''``
```
=> [Mellanox]: Disable MFT bash autocompletion.

src/sonic-host-services-data/debian/sonic-host-services-data.determine-reboot-cause.service, src/sonic-host-services-data/debian/sonic-host-services-data.process-reboot-cause.service, src/sonic-host-services-data/debian/sonic-host-services-data.process-reboot-cause.timer
Fixes https://github.com/sonic-net/sonic-buildimage/issues/16990  for 202305/202205 branch
**Note: This PR is for 202305 and 202205. For master, a new PR will be raised with a new field (Uphold=) provided by debian bookworm to handle the dependency failure restartability of the processes.**
1. determine-reboot-cause  and process-reboot-cause service does not start If the database service fails to restart in the first attempt. Even if the Database service succeeds in the next attempt, these reboot-cause services do not start.
2. The process-reboot-cause service also does not restart if the docker or database service restarts, which leads to an empty reboot-cause history
3. deploy-mg from sonic-mgmt also triggers the docker service restart. The restart of the docker service caused the issue …
=> Fixed determine/process reboot-cause service dependency

platform/mellanox/mft/Makefile
A W/A to overcome SN2700 20 sec delay on login due to MFT bash autocompletion bug.
Must be reverted once a new MFT is ready.
To overcome SN2700 20 sec delay on login
N/A
Removed MFT bash autocompletion part
1. Build a mellanox image
2. Verify no such links after system boot.
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/17442
* N/A
* N/A
```
'//||\\`
''``
```
=> [202205][Mellanox] Disable MFT bash autocompletion

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, platform/mellanox/mlnx-platform-api/tests/test_sfp.py
backport https://github.com/sonic-net/sonic-buildimage/pull/17096  because of no clean cherry-pick
The current low power mode setting implementation requests the user to set the port to admin down first before toggling LP mode, this is not backward compatible, now revert it to the old way so that the user can toggle the LP mode regardless of the port admin status.
Reverts commit f74c69e876bdc80c38ae6bd06b414e357d1a63fa.
run all sfputil and SFP platform API related tests on all the Mellanox platforms.
=> [202205] [Mellanox] Revert LPM implementation to the old way

src/sonic-yang-models/tests/yang_model_tests/tests_config/sonic-events-swss.json, src/sonic-yang-models/yang-models/sonic-events-swss.yang
Current YANG model of sonic-events-swss:chk_crm_threshold has the type uint8 for leaf used_cnt which is too small of a range to hold values of used_cnt which can greatly exceed that. Updating leaf type of used_cnt and free_cnt to match defined definition.
Changed to uint32 as per defined here: https://github.com/sonic-net/sonic-swss/blob/master/orchagent/crmorch.h#L99
- Microsoft ADO **(number only)**:26091912
Update leaf value
UT and sonic-mgmt PR checker
=> Change leaf value of used_cnt of sonic-events-swss:chk_crm_threshold

files/scripts/gbsyncd.sh
The issue is related to https://github.com/sonic-net/sonic-buildimage/pull/16812. Process syncd does not run in the container gbsyncd on kvm sonic with default hwsku.
- Microsoft ADO : **26151608**
If syncd has not run in container gbsyncd, it is not needed to trigger graceful shudown of syncd. 
None of syncd_request_shutdown coredump  in config reload on KVM sonic
=> Fix syncd_request_shutdown coredump in config reload on KVM sonic 

installer/default_platform.conf
GRUB environment file is neither generated when SONiC is installed from ONiE nor when GRUB starts boot chain sequence
```
https://github.com/sonic-net/sonic-buildimage/blob/202305/installer/default_platform.conf#L506
cat <<EOF >> $grub_cfg
if [ -s \$prefix/grubenv ]; then
load_env
fi
if [ "\${saved_entry}" ]; then
set default="\${saved_entry}"
fi
if [ "\${next_entry}" ]; then
set default="\${next_entry}"
unset next_entry
save_env next_entry
fi
if [ "\${onie_entry}" ]; then
set next_entry="\${default}"
set default="\${onie_entry}"
unset onie_entry
save_env onie_entry next_entry
fi
EOF
```
The GRUB environment file is being regenerated (if not present) each time after system cold reboot, when SONiC reboot script is being called
``` …
```
=> [installer]: Create a blank grubenv if doesn't exist

src/sonic-frr/patch/0033-zebra-The-dplane_fpm_nl-return-path-leaks-memory, src/sonic-frr/patch/0033-zebra-The-dplane_fpm_nl-return-path-leaks-memory.patch, src/sonic-frr/patch/series
Fix zebra leaking memory with fib suppress enabled.  Porting the fix from
https://github.com/FRRouting/frr/pull/14983
While running test_stress_route.py, systems with lower memory started to throw low memory logs. On further investigation, a memory leak has been found in zebra which was fixed in the FRR community.
Creating patch for with the fix
Running test_stress_route.py and confirming that there is no memory leak in zebra after the completion of the test
=> [FRR] Fix zebra memory leak when bgp fib suppress pending is enabled

azure-pipelines.yml, rules/config
Enable sonic-restapi build in two platform to avoid build break on restapi target.
- Microsoft ADO **(number only)**:   26048426
=> [ci] Enable sonic-restapi build in PR validation.

.azure-pipelines/azure-pipelines-build.yml
Update pipeline file to support pensando's build.
- Microsoft ADO **(number only)**:  26087700
=> [ci] Support pensando platform build in pipeline.

dockers/docker-dhcp-relay/dhcp-relay.programs.j2
Comma after dhcprelayd would cause error when dhcpv6relay doesn't exist.
- Microsoft ADO **(number only)**: 26164305
Add comma via dhcp6relay
UT passed and build image success
=> [dhcp_relay] Optimize j2 file in dhcp_relay container

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/tests/test_chassis.py
Fix issue xcvrd crashes due to cannot import name 'initialize_sfp_thermal':
```
Nov 27 09:47:16.388639 sonic ERR pmon#xcvrd: Exception occured at CmisManagerTask thread due to ImportError("cannot import name 'initialize_sfp_thermal' from partially initialized module 'sonic_platform.thermal' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/sonic_platform/thermal.py)")
Nov 27 09:47:16.392544 sonic ERR pmon#xcvrd: Traceback (most recent call last):
Nov 27 09:47:16.392643 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1518, in run
Nov 27 09:47:16.392757 sonic ERR pmon#xcvrd:     self.task_worker()
Nov 27 09:47:16.392757 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1240, in …
```
=> [202305] [Mellanox] Fix race condition while creating SFP

files/initramfs-tools/fsck-rootfs
Fix the fsck check which is not working. Potentially fixes [https://github.com/sonic-net/sonic-buildimage/issues/16938](https://github.com/sonic-net/sonic-buildimage/issues/16938)
Modified fsck script to run on the ext4.fsck on the appropriate disk where SONiC resides
=> Fix the fsck script that does filesystem repair

dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Add show dhcp_server info
Add new subcommand to show dhcp_server command.
Add unit tests for compile time testing. Manually run command in latest master image.
Latest master image
Add show dhcp_server info
=> [dhcp_server] add show dhcp server info

dockers/docker-dhcp-server/cli-plugin-tests/conftest.py, dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py
Add config dhcp_server add
Add "config dhcp_server add" command to dockers-dhcp-server
Passed unit test. Manually run the script in latest image and get expected result.
Latest master
Add config dhcp_server add
=> [dhcp_server] add config dhcp_server add

platform/mellanox/mft/Makefile
A W/A to overcome SN2700 20 sec delay on login due to MFT bash autocompletion bug.
Must be reverted once a new MFT is ready.
To overcome SN2700 20 sec delay on login
N/A
Removed MFT bash autocompletion part
1. Build a mellanox image
2. Verify no such links after system boot.
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/17442
* N/A
* N/A
```
'//||\\`
''``
```
=> [202311][mellanox]: Disable MFT bash autocompletion

dockers/docker-dhcp-server/cli-plugin-tests/conftest.py, dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py
Add config dhcp_server del command.
Add command to dockers-dhcp-server
Run unittest and run manually on latest image and get expected result.
Add config dhcp_server del
=> [dhcp_server] add config dhcp server del

src/sonic-yang-models/yang-models/sonic-versions.yang
To support new sonic DB version format:
Old format: version_a_b_c
New format: version_<branch>_<nn>
* fba4bf0b 2023-12-21 | [202311][db_migrator] add db migrator version space for 202305/202311 branch (#3082) (HEAD -> 202311, github/202311) [Ying Xie]
PR test
=> [202311][YANG][sonic-utilities] update sonic DB version string format

src/sonic-yang-models/yang-models/sonic-versions.yang
Supports:
- old version: version_a_b_c
- new version: version_<branch>_<nn>
sonic-utilities:
* b0908bd7 2023-12-21 | [202305][db_migrator] add db migrator version space for 202305/202311 branch (#3084) (HEAD -> 202305, github/202305) [Ying Xie]
* 8f343ebb 2023-08-16 | [GCU] Add PORT table StateDB Validator (#2936) [isabelmsft]
This PR test
=> [202305][yang][sonic-utilities] update sonic DB version pattern

src/sonic-host-services/scripts/caclmgrd, src/sonic-host-services/tests/caclmgrd/caclmgrd_soc_rules_test.py, src/sonic-host-services/tests/caclmgrd/test_soc_rules_vectors.py
This PR fixes https://github.com/sonic-net/sonic-host-services/pull/95  where a corner case is not covered, if vlan address of DUT is not network address. 
Basically a src IP is added to the SNAT rule so that only packets originating from ToR with src IP as vlan IP get natted by the rule and change the src IP to LoopBack IP
For multiple vlan IP's only the vlan address coming from configuration is picked as the vlan address and not the network address. 
We consider a case where there are multiple vlan IP's are example in such format :
```
Vlan705                 10.131.113.17/28     up/up         N/A                   N/A
Vlan805                 10.131.111.129/26    up/up         N/A                   N/A
"VLAN_INTERFACE": {
"Vlan705|10.131.113.17/28": {},
"Vlan805|10.131.111.129/26": {}, …
```
=> [caclmgrd][DualToR] Fix a case where vlan address is not network address for DualToR Active-active configuration 

src/kdump-tools/patch/0003-Revert-the-MODULES-dep-optimization.patch, src/kdump-tools/patch/series
Fix kdump-tools to not overwrite MODULES conf to dep. Problem is seen if the build is failed and the build is retriggered immediately as part of retry mechanism
This command is failing during the second run
```
+ for kernel_release in $(ls $FILESYSTEM_ROOT/lib/modules/)
+ sudo LANG=C chroot ./fsroot-mellanox /etc/kernel/postinst.d/kdump-tools 6.1.0-11-2-amd64
+ clean_sys
```
https://github.com/sonic-net/sonic-buildimage/blob/master/files/build_templates/sonic_debian_extension.j2#L311
Community Issue: https://www.mail-archive.com/kernel-packages@lists.launchpad.net/msg515013.html
Add a patch to revert the override
```
vkarri@482a053c44f4:/sonic$ sudo unsquashfs -d ./fsroot-mellanox target/sonic-mellanox.bin__mellanox__rfs.squashfs
vkarri@482a053c44f4:/sonic$ sudo …
```
=> Fix kdump-tools to not overwrite MODULES conf to dep

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.install, platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.postinst, platform/broadcom/sonic-platform-modules-cel/haliburton/script/cpu_wdt, platform/broadcom/sonic-platform-modules-cel/haliburton/systemd/cpu_wdt.service
Backport #16083 and #16678 to 202305
- Microsoft ADO **(number only)**: 26066765
=> [202305][Celestica-E1031] Enable CPU watchdog

platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py, platform/mellanox/mlnx-platform-api/tests/test_watchdog.py
watchdog-control service always disarm watchdog during system startup stage. It could be the case that watchdog is not fully initialized while the watchdog-control service is accessing it. This PR adds a wait to make sure watchdog has been fully initialized.  
adds a wait to make sure watchdog has been fully initialized.  
Manual test
sonic  regression
=> [Mellanox] wait until hw-management watchdog files ready

src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/feature.json, src/sonic-yang-models/yang-models/sonic-feature.yang
According to the design, the database instances of DPU will be kept in the NPU host.
- Microsoft ADO **(number only)**:25072889
Declare a new field, `has_per_dpu_scope`, in the config_db for database feature.
Check Azp
=> [yang]: Add yang model for dpu database service

src/sonic-dhcp-utilities/tests/test_dhcp_db_monitor.py, src/sonic-dhcp-utilities/tests/test_utils.py
Fix UT issues in test_utils and test_dhcp_db_monitor 
- Microsoft ADO **(number only)**: 26297134
- test_dhcp_db_monitor:
1. Remove useless parametrize `enabled`
2. Change params in `tested_db_snapshot` to dict
- test_utils
1. Complete UT `test_get_target_process_cmds`
UTs passed
=> [dhcp_server] Fix UT issues in test_utils and test_dhcp_db_monitor

src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_cfggen.py, src/sonic-dhcp-utilities/tests/conftest.py, src/sonic-dhcp-utilities/tests/test_data/mock_config_db.json, src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py
Add boundary condition checks in below scenarios when generating DHCP server configuration:
- `customized_options` is not given
- Interfaces configured in `DHCP_SERVER_IPV4` table doesn't have IPv4 address
- Microsoft ADO **(number only)**: 26297130
- Add boundary condition checks.
- Add related UTs
UTs passed
=> [dhcp_server] Add field not exist checks in dhcp_cfggen

src/sonic-dhcp-utilities/dhcp_utilities/common/dhcp_db_monitor.py, src/sonic-dhcp-utilities/tests/test_data/dhcp_db_monitor_test_data.json, src/sonic-dhcp-utilities/tests/test_dhcp_db_monitor.py
**Depends on https://github.com/sonic-net/sonic-buildimage/pull/17311**
Add table checker for `DPUS` and `MID_PLANE_BRIDGE` tables for smart switch ip assigning, HLD: https://github.com/sonic-net/SONiC/pull/1504/files
- Microsoft ADO **(number only)**: 25973272
Add `DpusTableEventChecker` and `MidPlaneTableEventChecker` and related unit tests.
All UTs passed
```
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-dhcp-utilities, configfile: setup.cfg, testpaths: …
```
=> [smart_switch][dhcp_server] Add related table checkers for smart_switch in dhcp_db_monitor

src/sonic-yang-models/tests/yang_model_tests/tests/dhcp_server_ipv4.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/dhcp_server_ipv4.json, src/sonic-yang-models/yang-models/sonic-dhcp-server-ipv4.yang
**Depends on https://github.com/sonic-net/sonic-buildimage/pull/17311**
Add support for smart swith in dhcp-server-ipv4 yang model:
1. "name" in `DHCP_SERVER_IPV4` would refer to "bridge" in `MID_PLANE_BRIDGE`
2. "port" in `DHCP_SERVER_IPV4_PORT` would refer to "midplane_interface" in `DPUS`
- Microsoft ADO **(number only)**:  25975672
Add support for smart switch in sonic-dhcp-server-ipv4.yang
Unit tests in sonic-yang-models all passed.
=> [yang][dhcp_server] Add support for smart switch in sonic-dhcp-server-ipv4.yang

sonic-slave-bookworm/Dockerfile.j2
PROXY variables are not available to sudo users during docker build
This patch fixes below error during builds using proxy:
Step 57/63 : RUN sudo apt-get install python3-m2crypto
---> Running in ebfa797ebcf8
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
python-m2crypto-doc
The following NEW packages will be installed:
python3-m2crypto
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded. Need to get 169 kB of archives.
After this operation, 725 kB of additional disk space will be used. Ign:1 http://deb.debian.org/debian bookworm/main armhf python3-m2crypto armhf 0.38.0-4+b1 Ign:1 http://deb.debian.org/debian bookworm/main armhf python3-m2crypto armhf 0.38.0-4+b1 Ign:1 http://deb.debian.org/debian bookworm/main armhf …
=> sonic-slave-bookworm/Dockerfile.j2 remove sudo

files/image_config/copp/copp_cfg.j2
Change DHCP rate limit(queue4,group3) in SONiC copp configuration to 300 PPS
for mgmt TORs while keeping the rate limit at 100 PPS for other topologies.
Some mgmt TORs based on Marvell ASIC do not support 100 PPS CIR, so that led
to these devices silently dropping DHCP packets.
- Microsoft ADO **25820076**:
Updated copp_cfg.j2 to set queue4_group3 rate-limit to 300 PPS for mgmt TOR devices and 100 PPS for other device 
topologies.
Send DHCP broadcast packets to an M0 DUT and verify that they are trapped to
CPU at 300 PPS. On non-mgmt devices, the packets should be trapped at CIR of
100 PPS. Also ran sonic-mgmt dhcp_relay test and confirmed that it passes.
=> [image_config]: Update DHCP rate-limit for mgmt TOR devices

dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Add show dhcp_server option
Add show dhcp_server option command to plugin
Add unittest and manually run on latest image.
Latest master branch
=> [dhcp_server] add dhcp server show option

dockers/docker-dhcp-server/cli-plugin-tests/conftest.py, dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py
Add config dhcp server enable
run unittest and manually run on latest image.
Add config dhcp_server enable
=> [dhcp_server] add config dhcp server enable

files/image_config/backend_acl/backend_acl.py
Fix #17552 .
PR #14229 added a service for loading backend ACL rules. There is an issue in below code in `backend_acl.py`.
https://github.com/sonic-net/sonic-buildimage/blob/2ba3c90ad4ac5c03299b86795418702bba26900d/files/image_config/backend_acl/backend_acl.py#L80-L81
Because `table_name` is not specified when calling `acl-loader`, the ACL rules loaded previously will be cleared.
- Microsoft ADO **26167588**:
Specify the ACL table name `DATAACL` when calling `acl-loader`.
The change is verified by running on a physical testbed. The previously loaded ACL rules are not cleared after this change.
```
admin@str2-7050qx-32s-acs-02:/usr/share/sonic/templates$ show acl rule
Table     Rule          Priority    Action    Match
--------  ------------  ----------  -------- …
```
=> Update backend_acl.py to specify ACL table name

files/build_templates/docker_image_ctl.j2
This commit attempts to address the following:
* Make sure swss container is indeed up and running before running any commands on it. In case where swss container is not fully up when swss.sh attempts to create swss:/ready file using "docker exec swss$DEV touch", the command can fail silently and can cause swssconfig to wait forever leading to missing IP decap configuration among other things. Add a wait so that docker commands are run only after swss container status is "Running"
*  Add a log when swss:/ready file is created or if the file creation fails so that it becomes easier to debug such scenarios in the future
- Microsoft ADO: 25832304
Add a wait so that docker commands are run only after swss container status is "Running"
Run /usr/local/bin/swss.sh on a DUT with changes and …
=> [docker_image_ctl.j2]: swss docker initialization improvements

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal_manager.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal_updater.py, platform/mellanox/mlnx-platform-api/tests/test_sfp.py, platform/mellanox/mlnx-platform-api/tests/test_thermal.py, platform/mellanox/mlnx-platform-api/tests/test_thermal_updater.py
1. thermal updater should wait more time for module to be initialized
2. sfp should get temperature threshold from EEPROM because SDK sysfs is not yet supported
3. rename sfp function to fix typo
4. sfp.get_presence should return False if module is under initialization
1. thermal updater should wait more time for module to be initialized
2. sfp should get temperature threshold from EEPROM because SDK sysfs is not yet supported
3. rename sfp function to fix typo
4. sfp.get_presence should return False if module is under initialization
Manual test
Unit test
=> [Mellanox] Fix issues found for CMIS host management

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/setup.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/bgp_bbr.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp_bbr.json, src/sonic-yang-models/yang-models/sonic-bgp-bbr.yang
Enable Yang model for BGP_BBR config entry.
```
{
"BGP_BBR": {
"all": {
"status": "enabled"/"disabled"
}
}
}
```
- Microsoft ADO **(number only)**: 25988660
Add yang model and ut for BGP_BBR.
Use GCU cmd to change bbr status.
Create following json patch: disable_bbr.json-patch
```
[
{
"op": "replace",
"path": "/BGP_BBR/all/status",
"value": "disabled"
}
]
```
Run ```sudo config apply-patch ./disable_bbr.json-patch``` cmd on dut. Success.
=> [YANG] Enable Yang model for BGP_BBR config entry

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py, platform/mellanox/mlnx-platform-api/sonic_platform/modules_mgmt.py, platform/mellanox/mlnx-platform-api/tests/test_chassis.py
Cherry-pick PR https://github.com/sonic-net/sonic-buildimage/pull/16846
- Why I did it Enable CMIS host management for Mellanox devices which are expected to support the feature
- How I did it new thread in a new file and changing logic in platform code in chassis.py which is calling this thread from get_change_event() this thread in the new file handles the state machine per port. first the static detection takes place once the thread is up (during switch bootup sequence), until final decision if it's FW control or SW control module. After it ends, the dynamic detection takes place, listening to changes in the sysfs fds, per port, so it will be able to detect plug in or out events of a cable.
- How to verify it Enhanced unit tests
run sonic mgmt on Nvidia SN4700 with CMIS host management …
=> [202311][Mellanox] Enable CMIS host management (#16846)

src/sonic-py-common/sonic_py_common/device_info.py
Refactor current get_num_dpus function to consuming platform.json which is reliable way to retrieve the number of DPUs.
- Microsoft ADO **number**:
Read platform.json file to retrieve the number of DPU objects in DPUS section.
```json
"DPUs": [
{
"DPU0": {
"Ethernet244": "Ehternet0",
"Ethernet248": "Ethernet1"
}
},
{
"DPU1": {
"Ethernet252": "Ethernet0",
"Ethernet256": "Ethernet1"
},
}
]
```
Create local platform json file which follow the format of [hwsku.json](https://github.com/sonic-net/sonic-buildimage/blob/d4a78665eeba62d597b8a6319dbc1a5ab5cfa775/src/sonic-config-engine/tests/data/smartswitch/SSwitch-32x1000Gb/hwsku.json#L115) then run the function call locally.
```python
import json
def get_num_dpus():
json_file = "/tmp/hwsku.json"
if os.path.isfile(os.path.join(platform_path, …
```
=> Refactor get_num_dpus function.

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal_manager.py, platform/mellanox/mlnx-platform-api/sonic_platform/thermal_updater.py, platform/mellanox/mlnx-platform-api/sonic_platform/utils.py, platform/mellanox/mlnx-platform-api/tests/test_sfp.py, platform/mellanox/mlnx-platform-api/tests/test_thermal.py, platform/mellanox/mlnx-platform-api/tests/test_thermal_updater.py, platform/mellanox/mlnx-platform-api/tests/test_utils.py
Backport PR: https://github.com/sonic-net/sonic-buildimage/pull/16955
When module is totally under software control, driver cannot get module temperature/temperature threshold from firmware. In this case, sonic needs to get temperature/temperature threshold from EEPROM. In this PR, a thread thermal updater is created to update module temperature/temperature threshold while software control is enabled.
Query ASIC temperature from SDK sysfs and update hw-management-tc periodically
Query Module temperature from EEPROM and update hw-management-tc periodically
Manual test
New unit tests
=> [202311] [Mellanox] update asic and module temperature in a thread for CMIS management (#16955)

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot, device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_reboot
When Supervisor card is rebooted by using PMON API, it takes about 90 seconds to trigger the shutdown in down path.  At this time linecards have been up. This delays linecards database initialization which is trying to PING/PONG the database-chassis. To address this issue, we modified the NDK to use the system call with "sudo reboot"  when the request is from PMON API on Supervisor case.  The NDK version is 22.9.20  and greater.  This new NDK requires this modifcaiton of platform_reboot to work with.   
- Microsoft ADO **(number only)**: 26365734
Modify the platform_reboot In Supervisor not to reboot all IMMs since it has been done in the function reboot() in module.py.  Also handle the reboot-cause.txt for on the Supervisor when the reboot is request from PMON API. 
Modify the Nokia …
=> [Nokia-IXR7250E] Modify the platform_reboot on the IXR7250E for PMON API reboot and disable all SFPs

.github/workflows/automerge.yml
automerge and automerge_scan have different behavior when merging PRs.
automerge may left some PRs unmerged. So, use automerge_scan instead.
- Microsoft ADO **(number only)**:  26361240
=> [workflow] Use automerge_scan instead of automerge for correct commit message.

dockers/docker-database/docker-database-init.sh, dockers/docker-orchagent/docker-init.j2
* Improved switch init time
* N/A
* Replaced: `sonic-cfggen` -> `sonic-db-cli`
* Aggregated template list for `sonic-cfggen`
1. Run `warm-reboot`
* N/A
* N/A
```
'//||\\`
''``
```
=> [202305][sonic-cfggen]: Optimize template rendering and database access

dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py
Add config dhcp_server disable
Add dhcp_server disable to config plugin.
Run unittest and run manually on latest image.
Lastest master
Add config dhcp_server disable
=> [dhcp_server] add config dhcp_server disable

dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Add show dhcp_server port
Latest master
=> [dhcp_server] add show dhcp server port

dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Current show dhcp_server output format can be a bit messy
Give show dhcp_server a "grid" format when output with tabulate.
Passed unittests
Latest master image
improve show dhcp_server output
=> [dhcp_server] improve show dhcp server output

device/mellanox/x86_64-mlnx_msn2010-r0/installer.conf, device/mellanox/x86_64-mlnx_msn2700-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3420-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3700c-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3800-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4410-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4600-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4600c-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4700-r0/installer.conf, device/mellanox/x86_64-nvidia_sn4800-r0/installer.conf
Backport of https://github.com/sonic-net/sonic-buildimage/pull/17567
Based on some research some products might experience an occasional IO failures in the communication between CPU and SSD because of NCQ.
There seems to be a problem between some kernel versions and some SATA controllers.
Syslog error message examples:
- Error "ata1: SError: { UnrecovData Handshk }" - "failed command: WRITE FPDMA QUEUED".
- Error "ata1: SError: { RecovComm HostInt PHYRdyChg CommWake 10B8B DevExch }" - "failed command: READ FPDMA QUEUED".
Some vendors already disabled NCQ on their platforms in SONiC due to similar issue:
- https://github.com/sonic-net/sonic-buildimage/pull/13739 [Arista] Disable ATA NCQ for a few products
- https://github.com/sonic-net/sonic-buildimage/pull/13964 [Arista] Disable SSD NCQ …
=> [202205] [Mellanox] Disable SSD NCQ on Mellanox platforms

files/build_templates/init_cfg.json.j2
For some devices with small memory, after upgrading to the latest image, the available memory is not enough. 
- 26324242
Disable restapi feature for LeafRouter which with slim image.
verified on 7050qx T1 (slim image), restapi disabled
verified on 7050qx T0 (slim image), restapi enabled
verified on 7260 T1 (normal image), restapi enabled
=> disable restapi for leafRouter in slim image

platform/mellanox/mft/Makefile
A W/A to overcome SN2700 20 sec delay on login due to MFT bash autocompletion bug.
Must be reverted once a new MFT is ready.
To overcome SN2700 20 sec delay on login
N/A
Removed MFT bash autocompletion part
1. Build a mellanox image
2. Verify no such links after system boot.
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/17442
* N/A
* N/A
```
'//||\\`
''``
```
=> [202211][Mellanox] Disable MFT bash autocompletion

scripts/docker_version_control.sh
Fix a bug that sometimes the script runs in sh not bash.
- Microsoft ADO **(number only)**:  26297955
=> [build] Fix a bash script some times called by sh issue.

src/sonic-dhcp-utilities/dhcp_utilities/dhcprelayd/dhcprelayd.py, src/sonic-dhcp-utilities/tests/common_utils.py, src/sonic-dhcp-utilities/tests/test_data/mock_config_db.json, src/sonic-dhcp-utilities/tests/test_data/mock_config_db_smart_switch.json, src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py, src/sonic-dhcp-utilities/tests/test_dhcprelayd.py, src/sonic-dhcp-utilities/tests/test_smart_switch.py
Add support for smart switch in dhcprelayd
- Microsoft ADO **(number only)**: 26437270
1. Add checker support for smart switch and add related UTs
1.1 Only enable `FEATURE` table checker when dhcprelayd init
1.2 In function `refresh_dhcrelay`, enable or disable VLAN/MID_PLANE table checkers as needed.
1.3 When dhcp_server feature state change, do changes for checkers:
* disable -> enabled: Should enable `DHCP_SERVER_IPV4` checker
* enabled -> enabled: Refer to `refresh_dhcrelay` in 1.2
* enabled -> disabled: Should disable
* disabled -> disabled: not need to update
2. Extract function `_proceed_with_check_res` in function `wait` to let UT cover it.
UTs passed
```
collected 430 items …
```
=> [dhcp_server] Add support for smart switch in dhcprelayd

device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t0.config.bcm, device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t1.config.bcm, src/sonic-device-data/tests/permitted_list
… 
For 40G optics there is SAI handling of T0 facing ports to be set with SR4 type and unreliable los set for a fixed set of ports. For this property to be invoked the requirement is set 
`phy_unlos_msft=1` in config.bcm. 
This change is to meet the requirement and once this property is set, the los/interface type settings is applied by SAI on the required ports. 
For Arista-7060CX-32S-Q32 T1, 40G ports RX_ERR minimalization during connected device reboot
can be achieved by turning on Unreliable LOS and SR4 media_type for all ports which are connected to T0.
The property `phy_unlos_msft=1` is to exclusively enable this property. 
25941176
Changes in SAI and turning on property
Ran the changes on a testbed and verified configurations are as intended. …
=> [Arista] Update config.bcm of 7060_cx32s for handling 40g optics with unreliable los settings

dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py
Add config dhcp server range add / update / delete
Add command to config plugin
Run unittest and run manually on latest image
Latest public image
Add config dhcp_server range related functions
=> [dhcp_server] add config dhcp server range

src/isc-dhcp/patch/0016-Don-t-look-up-the-ifindex-for-fallback.patch, src/isc-dhcp/patch/series
Currently, whenever isc-dhcp-relay forwards a packet upstream, internally, it will try to send it on a "fallback" interface. My understanding is that this isn't meant to be a real interface, but instead is basically saying to use Linux's regular routing stack to route the packet appropriately (rather than having isc-dhcp-relay specify specifically which interface to use).
The problem is that on systems with a weak CPU, a large number of interfaces, and many upstream servers specified, this can introduce a noticeable delay in packets getting sent. The delay comes from trying to get the ifindex of the fallback interface. In one test case, it got to the point that only 2 packets could be processed per second. Because of this, dhcrelay will easily get backlogged and likely get to a point …
=> dhcrelay: Don't look up the ifindex for the fallback interface

src/sonic-config-engine/config_samples.py, src/sonic-config-engine/tests/sample_output/t1-smartswitch.json
Align the smart switch config generator with the YANG model.
Change `MID_PLANE_BRIDGE` table field name in the generated config from `address` to `ip_prefix`.
Run UT. The tests are aligned with the changes.
=> [smartswitch] Align the smart switch config generator with the YANG model.

sonic-slave-bullseye/Dockerfile.j2
cherry pick https://github.com/sonic-net/sonic-buildimage/pull/17182
=> [build] Add gpg keys for sonic-slave-bullseye in arm64 cross build on amd64. (#17182)

dockers/docker-fpm-frr/TS, dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2, dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/policies.conf.j2, dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.isolate.conf.j2, dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.unisolate.conf.j2, files/image_config/constants/constants.yml, src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_all_isolate.conf, src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_all_unisolate.conf, src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_isolate.conf, src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_unisolate.conf, src/sonic-bgpcfgd/tests/data/internal/policies.conf/param_chasiss_packet.json, src/sonic-bgpcfgd/tests/data/internal/policies.conf/param_front.json, src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_back.conf, src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_chasiss_packet.conf, src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_front.conf, src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/isolate.conf, src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/isolate.json, src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/unisolate.conf, src/sonic-bgpcfgd/tests/data/voq_chassis/policies.conf/param_base.json, src/sonic-bgpcfgd/tests/data/voq_chassis/policies.conf/result_base.conf, src/sonic-bgpcfgd/tests/test_device_global.py
What I did: 
Cherry-pick of master  PR: https://github.com/sonic-net/sonic-buildimage/pull/16714
=> [202305] [chassis] Support advertisement of Loopback0 of all LC's across all e-BGP peers in TSA mode 

src/isc-dhcp/patch/0016-Don-t-look-up-the-ifindex-for-fallback.patch, src/isc-dhcp/patch/series
Backport of #17797
Currently, whenever isc-dhcp-relay forwards a packet upstream, internally, it will try to send it on a "fallback" interface. My understanding is that this isn't meant to be a real interface, but instead is basically saying to use Linux's regular routing stack to route the packet appropriately (rather than having isc-dhcp-relay specify specifically which interface to use).
The problem is that on systems with a weak CPU, a large number of interfaces, and many upstream servers specified, this can introduce a noticeable delay in packets getting sent. The delay comes from trying to get the ifindex of the fallback interface. In one test case, it got to the point that only 2 packets could be processed per second. Because of this, dhcrelay will easily get backlogged and likely …
=> [202305] dhcrelay: Don't look up the ifindex for the fallback interface

rules/docker-iccpd.mk
```
admin@vlab-01:~$ docker inspect iccpd | grep Privi
admin@vlab-01:~$ docker exec -it iccpd bash
```
=> [docker-iccpd] limit privileged flag for iccpd container

dockers/docker-base-bookworm/Dockerfile.j2, dockers/docker-base-bookworm/apt-multiple-retries, dockers/docker-base-bookworm/pip.conf
Add a missing pip.conf file needed for docker-base-bookworm. Also fix the armhf and arm64 build of docker-base-bookworm, in a similar way to #17571.
- Microsoft ADO **(number only)**: 26417271
=> Fix docker-base-bookworm build

dockers/docker-database/docker-database-init.sh, dockers/docker-orchagent/docker-init.j2
* Improved switch init time
* N/A
* Replaced: `sonic-cfggen` -> `sonic-db-cli`
* Aggregated template list for `sonic-cfggen`
1. Run `warm-reboot`
* N/A
* N/A
```
'//||\\`
''``
```
=> [sonic-cfggen]: Optimize template rendering and database access

src/sonic-host-services-data/debian/sonic-host-services-data.sonic-hostservice.service
When we disable telemetry.service, sonic-hostservice will not start. And root cause is sonic-hostservice is only wanted by telemetry.service.
Add dependency for gnmi.service.
Disable telemetry.service and build new image, and then check sonic-hostservice with new image.
=> Fix host service for 202311 branch

platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
if a PSU is not present, there could be error log while restarting psud or thermalctld:
```
Jan  8 17:15:52.689616 sonic ERR pmon#psud: Thermal sysfs /run/hw-management/thermal/psu2_temp1_max does not exist
Jan  8 17:15:57.747723 sonic ERR pmon#thermalctld: Thermal sysfs /run/hw-management/thermal/psu2_temp1 does not exist
```
if a PSU is not present, we should not check the PSU temperature sysfs.
=> [Mellanox] Fix error log while creating PSU thermal object

src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_cfggen.py, src/sonic-dhcp-utilities/tests/test_data/mock_config_db_smart_switch.json, src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py, src/sonic-dhcp-utilities/tests/test_smart_switch.py
Fix parse_dpus error in dhcp_cfggen
- Microsoft ADO **(number only)**: 26515431
* Fix parse_dpus error in dhcp_cfggen
* Add ut for it
* UTs passed
* Build python package and install to test
=> [dhcp_server] Fix parse_dpus error in dhcp_cfggen

dockers/docker-dhcp-server/Dockerfile.j2, dockers/docker-dhcp-server/docker_init.sh, dockers/docker-dhcp-server/port-name-alias-map.txt.j2, rules/config, src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_cfggen.py, src/sonic-dhcp-utilities/tests/test_data/mock_config_db.json, src/sonic-dhcp-utilities/tests/test_data/port-name-alias-map.txt, src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py, src/sonic-dhcp-utilities/tests/test_dhcpservd.py
Currently dhcp_cfggen gets port map from file port-name-alias-map.txt, which is actually generated refer to CONFIG_DB. It will encounter error when PORTCHANNEL table or PORT table not exist in CONFIG_DB.
- Microsoft ADO **(number only)**: 26494259
Modify dhcp_cfggen to get port map from CONFIG_DB directly.
- Build successfully.
- UTs passed.
=> [dhcp_server] Remove dependency in port-name-alias-map.txt.j2

src/tacacs/audisp/patches/0002-Remove-user-secret-from-accounting-log.patch
Ignore TACACS accounting trace log when debug disabled.
TACACS accounting trace log is only for debug, improve code to not generate trace log when debug disabled.
- Microsoft ADO: 25270078
Ignore TACACS accounting trace log when debug disabled.
Pass all UT.
Manually verified the auditd-tacplus not generate trace log when debug disabled. 
Ignore TACACS accounting trace log when debug disabled.
=> [TACACS] Ignore TACACS accounting trace log when debug disabled.

rules/docker-p4rt.mk
```
admin@vlab-01:~$ docker inspect p4rt | grep Privi
admin@vlab-01:~$ docker exec -it p4rt bash
```
=> [docker-p4rt] limit privileged flag for p4rt container

files/image_config/resolv-config/resolv-config.sh
Fix the issue detected by[ TestStaticMgmtPortIP::test_dynamic_dns_not_working_when_static_ip_configured ](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/dns/static_dns/test_static_dns.py#L105C9-L105C63) test.
Query MGMT interface configuration. Do not apply dynamic DNS configuration when MGMT interface has static IP address.
Run `tests/dns/static_dns/test_static_dns.py` sonic-mgmt tests.
=> [dns] Do not apply dynamic DNS configuration when MGMT interface has static IP address.

azure-pipelines.yml
Use dynamic variable for branch reference.
- Microsoft ADO **(number only)**:  26563706
=> [ci] Use correct branch when downloading SONiC vs image in elastic test.

src/tacacs/bash_tacplus/bash_tacplus.c
Fix when set TACACS to "tacacs+, local" user can run blocked command with local permission issue.
When set TACACS to "tacacs+, local", user still can run a blocked command with local permission.
- Microsoft ADO: 26399545
Fix code to reject command when authorized failed from TACACS server side.
Pass all UT.
Fix when set TACACS to "tacacs+, local" user can run blocked command with local permission issue.
=> [TACACS] Fix when set TACACS to "tacacs+, local" user can run blocked command with local permission issue.

files/scripts/supervisor-proc-exit-listener
Change orchagent stuck message from ERR to WARNING
During switch initialization, sometime Orchagent will busy for more than 40seconds and will trigger process stuck workdog error.
To improve this issue, change watchdog error message to warning message.
- Microsoft ADO: 26517622
Change orchagent stuck message from ERR to WARNING.
Pass all UT.
Change orchagent stuck message from ERR to WARNING.
=> Change orchagent stuck message from ERR to WARNING

rules/docker-nat.mk
```
admin@vlab-01:~$ docker inspect nat | grep Privi
admin@vlab-01:~$ docker exec -it nat bash
```
=> [docker-nat] limit privileged flag for nat container

device/mellanox/x86_64-mlnx_msn2010-r0/installer.conf, device/mellanox/x86_64-mlnx_msn2700-r0/installer.conf, device/mellanox/x86_64-mlnx_msn2700a1-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3420-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3700-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3700c-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3800-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4410-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4600-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4600c-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4700-r0/installer.conf, device/mellanox/x86_64-nvidia_sn2201-r0/installer.conf, device/mellanox/x86_64-nvidia_sn4800-r0/installer.conf, device/mellanox/x86_64-nvidia_sn5600-r0/installer.conf
Based on some research some products might experience an occasional IO failures in the communication between CPU and SSD because of NCQ.
There seems to be a problem between some kernel versions and some SATA controllers.
Syslog error message examples:
- Error "ata1: SError: { UnrecovData Handshk }" - "failed command: WRITE FPDMA QUEUED".
- Error "ata1: SError: { RecovComm HostInt PHYRdyChg CommWake 10B8B DevExch }" - "failed command: READ FPDMA QUEUED".
Some vendors already disabled NCQ on their platforms in SONiC due to similar issue:
- https://github.com/sonic-net/sonic-buildimage/pull/13739 [Arista] Disable ATA NCQ for a few products
- https://github.com/sonic-net/sonic-buildimage/pull/13964 [Arista] Disable SSD NCQ on DCS-7050CX3-32S
Also there are other discussions on Debian/Ubuntu …
=> [Mellanox] Disable SSD NCQ on Mellanox platforms

files/build_templates/qos_config.j2
Align the keywords to make qos configuration take effect
Change the keyword to ComputeAI
reload minigraph and check the qos configuration
=> [qos] change the template keyword from Compute-AI to ComputeAI

src/sonic-bgpcfgd/bgpmon/bgpmon.py
ICM reported due to "BGPMon Process exited" which was caused by json load exception.
25916773
Add an exception handle during json load.
Verified locally, add debug log to modify the output string of cmd to make it not with json formation, then check the syslog.
Jan 19 03:09:56.275058 str3-7060-acs-1 INFO tmp.py: bgpmon service started
Jan 19 03:09:56.571696 str3-7060-acs-1 WARNING tmp.py: *WARNING* JSONDecodeError: Expecting ':' delimiter: line 109 column 12 (char 2203) when execute: ['vtysh', '-c', 'show bgp summary json'] Retry attempt: 1
Jan 19 03:09:57.891086 str3-7060-acs-1 WARNING tmp.py: *WARNING* JSONDecodeError: Expecting ':' delimiter: line 109 column 12 (char 2203) when execute: ['vtysh', '-c', 'show bgp summary json'] Retry attempt: 2
Jan 19 …
=> handle json load exception in bgpmon

src/sonic-config-engine/minigraph.py
When not all vlans have dhcpv6 servers configured, dhcp6relay fails to start because it expects all vlans under DHCP_RELAY table to have dhcpv6 server configured.
- Microsoft ADO **(number only)**: 26431008
Only add vlan to DHCP_RELAY table if there's dhcpv6 servers
Verified by reloading minigraph with previous minigraph.py and updated minigraph.py when one of the vlan does not have ipv6 address configured. Updated minigraph should not add Vlan with no ipv6 configuration into DHCP_RELAY table
=> Only add interface to DHCP_RELAY if dhcpv6 servers exist

platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2, platform/mellanox/docker-syncd-mlnx-rpc/ptf_nn_agent.conf, platform/mellanox/docker-syncd-mlnx/Dockerfile.j2, platform/mellanox/sdk-src/python-sdk-api/Makefile
Python 2 is obsolete and no longer supported.
Change several packages installation commands in Nvidia syncd dockerfile to Python3 packages.
Change was done for regular image and for RPC image as well.
I tested several SDK API scripts manually (while all others are tested by SDK verification) and ran regression tests that run on RPC version.
=> [Nvidia] Update syncd docker to use python version 3

azure-pipelines.yml
[202211, PR test] Use feature branch as the sonic-mgmt branch
=> [202211, PR test] Use feature branch as the sonic-mgmt branch

src/sonic-bgpcfgd/staticroutebfd/main.py, src/sonic-bgpcfgd/tests/test_static_rt_bfd.py
Fix an error in the log_err call.
this error can be triggered by an invalid static route key. usually the code cannot go here with normal config file. but hit this issue with an invalid key by manual testing with redis-cli directly. the file is scanned by Python lint to prevent such errors.
- Microsoft ADO **()**:26250268
fix the format error.
1, ran pylint to check the design, make sure no such error in the design file.
2, wrote a separate python program to verify the log call.
In the current logging related testing, usually use patch/mock for logging. for this specific error, could not trigger it if we call mock function instead the real function in the design. so need to do lint checking for code change.
=> [staticroutebfd] fix an error in error logging

src/sonic-frr/patch/0033-zebra-The-dplane_fpm_nl-return-path-leaks-memory.patch, src/sonic-frr/patch/series
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/17484
Fix zebra leaking memory with fib suppress enabled. Porting the fix from FRRouting/frr#14983
While running test_stress_route.py, systems with lower memory started to throw low memory logs. On further investigation, a memory leak has been found in zebra which was fixed in the FRR community.
Creating patch for with the fix
Running test_stress_route.py and confirming that there is no memory leak in zebra after the completion of the test
=> [202311][FRR] Fix zebra memory leak when bgp fib suppress pending is enabled

slave.mk
The PR introduced a bug for slim image build, https://github.com/sonic-net/sonic-buildimage/pull/17905, by which the sonic_asic_platform is missing when build docker image for slim image. 
```
[ building ] [ target/docker-dhcp-relay.gz ]
/sonic/dockers/docker-dhcp-relay/cli-plugin-tests /sonic
/sonic
File "/usr/local/bin/j2", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/dist-packages/j2cli/cli.py", line 202, in main
output = render_command(
File "/usr/local/lib/python3.9/dist-packages/j2cli/cli.py", line 186, in render_command
result = renderer.render(args.template, context)
File "/usr/local/lib/python3.9/dist-packages/j2cli/cli.py", line 85, in render
return self._env \
File "/usr/lib/python3/dist-packages/jinja2/environment.py", …
```
=> Fix the compile issue for slim image

platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
To fix uninitialized variable
Add initial value
=> [Mellanox] Fix uninitialized variable on module plug event

azure-pipelines.yml
disable DPU in 202311, because DPU image will not be applied to 202311. 
=> [202311, PR] deprecate DPU

dockers/docker-dhcp-server/supervisord.conf
Fix the issue with running "dhcp-server-ipv4:kea-dhcp4" process after a cold reboot: #17948
The root cause of the issue is that during the cold reboot, the PID file of the process (that is stored on the persisted FS) is not cleared. From the [KEA DHCP server documentation](https://kea.readthedocs.io/en/kea-2.2.0/arm/dhcp4-srv.html):
> If the file already exists and contains the PID of a live process, the server issues a DHCP4_ALREADY_RUNNING log message and exits. It is possible, though unlikely, that the file is a remnant of a system crash and the process to which the PID belongs is unrelated to Kea. In such a case, it would be necessary to manually delete the PID file.
To make sure that the PID file is always cleared during the dhcp-server container …
=> [dhcp-server] Change the kea-dhcp4 PID file directory to tmpfs.

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/dhcp_server_ipv4.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/dhcp_server_ipv4.json, src/sonic-yang-models/yang-models/sonic-dhcp-server-ipv4.yang
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-buildimage/pull/18029
Changes in current PR is totally same as master PR: https://github.com/sonic-net/sonic-buildimage/pull/18029. Conflicts generated because smart switch support in master branch which shouldn't be backported to 202311
Align yang model with implementation and KEA doc https://kea.readthedocs.io/en/latest/arm/dhcp4-srv.html#standard-dhcpv4-options, change type text to string
- Microsoft ADO **(number only)**: 26685449
Update supported option type to string
Image build successfully
=> [202311][dhcp_server][yang] Update supported option type to string (#18029)

device/mellanox/x86_64-mlnx_msn2010-r0/installer.conf, device/mellanox/x86_64-mlnx_msn2700-r0/installer.conf, device/mellanox/x86_64-mlnx_msn2700a1-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3420-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3700-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3700c-r0/installer.conf, device/mellanox/x86_64-mlnx_msn3800-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4410-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4600-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4600c-r0/installer.conf, device/mellanox/x86_64-mlnx_msn4700-r0/installer.conf, device/mellanox/x86_64-nvidia_sn2201-r0/installer.conf, device/mellanox/x86_64-nvidia_sn4800-r0/installer.conf, device/mellanox/x86_64-nvidia_sn5600-r0/installer.conf
Backport of PR https://github.com/sonic-net/sonic-buildimage/pull/17567
Based on some research some products might experience an occasional IO failures in the communication between CPU and SSD because of NCQ.
There seems to be a problem between some kernel versions and some SATA controllers.
Syslog error message examples:
- Error "ata1: SError: { UnrecovData Handshk }" - "failed command: WRITE FPDMA QUEUED".
- Error "ata1: SError: { RecovComm HostInt PHYRdyChg CommWake 10B8B DevExch }" - "failed command: READ FPDMA QUEUED".
Some vendors already disabled NCQ on their platforms in SONiC due to similar issue:
- https://github.com/sonic-net/sonic-buildimage/pull/13739 [Arista] Disable ATA NCQ for a few products
- https://github.com/sonic-net/sonic-buildimage/pull/13964 [Arista] Disable SSD …
=> [202311] [Mellanox] Disable SSD NCQ on Mellanox platforms

dockers/docker-orchagent/critical_processes.j2, dockers/docker-orchagent/supervisord.conf.j2
The fabricmgr daemon started in vs environment for testing from sonic-net/sonic-buildimage#16791, we now start the daemon in product code.  
Start fabric mgr daemon in swss container .
=> Start fabric mgr daemon in swss container.

platform/mellanox/mlnx-platform-api/sonic_platform/modules_mgmt.py
Fix the code to work also after warm reboot to work with FW controlled ports.
In warm reboot the control state sysfs of each port does not change unlike reboot or fast boot.
1. Check procfs cmdline if warm reboot done this is due to the fact pmon don't recognize warm reboot when it's taking place since pmon is loaded after warm reboot is finished.
2. If warm reboot done, check in static detection part for each port if it's FW controlled. If so, leave it this way and stop the state machine flow (set it to final state).
1. Boot a switch with CMIS host management with at least one FW controlled port (non active cables or non cmis cables) then run warm reboot.
2. Verify no errors of sysfs reading appears for control sysfs
=> [Mellanox] fix code for warm reboot to work with FW controlled ports

files/build_templates/sonic_debian_extension.j2
To gather more info in bootchart.
Enabled displaying the whole command line arguments in bootchart.
Run bootchart.
=> [bootchart] enable command line recording

files/build_templates/sonic_debian_extension.j2, files/image_config/smartmontools/smartmontools
Update smartmontool verson to 7.4. This is done to prevent smartmontools service to exit with non-zero exit status on platform that does not have a SSD/disk to be monitored.
Until Debian Bullseye (which had smartmontools 7.2), Debian had a patch applied that changed the default quit mode to never exit. A [bug report](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbugs.debian.org%2Fcgi-bin%2Fbugreport.cgi%3Fbug%3D1006630&data=05%7C02%7CPrince.George%40microsoft.com%7C7523d0e755c74ab63a3e08dc034e9d89%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638388883394086156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pIRsnZSSc8cWF1SrPKyF47FemdXzWcdBEN95kj4jJA8%3D&reserved=0) was filed on Debian, saying that the …
=> Update smartmontool version >= v7.4

platform/marvell-arm64/sonic_fit.its
Change-Id: I411f12963fb8dc0eb3569faf4df68082b852e3a8
After bookworm migration kernel boot was failing as below on rd98DX35xx_cn9131 platform.
===
Loading Kernel Image
"Synchronous Abort" handler, esr 0x96000046
Attempt to access RT service or TEE region (addr: 0x4000000, el2)
Do not use address range 0x4000000-0x5400000 
==
Made load address adjustment in sonic_fit.its, to make sure address from 0x4000000 is not overwritten by vmlinuz. vmlinuz now has 48MB of space from 0x1000000 to 0x4000000.
Build image with change and loaded on rd98DX35xx_cn9131 platform to verify successful boot.
=> [Marvell-arm64] Fix boot issue on rd98DX35xx_cn9131

platform/marvell-arm64/docker-syncd-mrvl-rpc.mk
Change-Id: I0bd4932d03141f3f7bc523b49a1bf3d1809817a8
With 'ENABLE_SYNCD_RPC' flag enabled, compilation for marvell-arm64 was failing. Failure was due to bookworm now being default docker and absence of python2 support in it.
dh: error: unable to load addon python2: Can't locate Debian/Debhelper/Sequence/python2.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python2 module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/aarch64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl-base /usr/lib/aarch64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at (eval 11) line 1.
BEGIN failed--compilation aborted at (eval 11) line 1.
make[2]: *** [debian/rules:91: clean] Error 25 …
=> [Marvell-arm64]: Fix SYNCD_RPC build

dockers/docker-sonic-mgmt/Dockerfile.j2
Recently, netaddr 1.0.0 was released, which dropped Python 2 support entirely. Because of this, an empty netaddr package is installed for Python 2. Ansible still uses Python 2, so this needs to remain functional. The Python 3 part of sonic-mgmt is fine.
Pin the version of netaddr installed in Python 2 to 0.10.1, the last supported version.
Installed netaddr 0.10.1 in the latest sonic-mgmt container, and verified it can now be imported in Python 2.
Also verified from the docker-sonic-mgmt that was built as part of the PR checks that netaddr can be imported in Python 2.
=> Install netaddr 0.10.1 in the Python 2 part of sonic-mgmt

src/system-health/health_checker/service_checker.py
PR https://github.com/sonic-net/sonic-buildimage/pull/17836 added the container checking for database-chassis for Supervisor.  But the related container_feature_dict[] is missing for the database-chassis. This causes the exception failure shows on Supervisor
```
admin@ixre-cpm-chassis13:~$ sudo show system-health sum 
System status summary
System status LED  red
Services:
Status: OK
Hardware:
Status: Not OK
Reasons: PSU 12 is missing or not available
PSU 11 is missing or not available
PSU 10 is missing or not available
PSU 9 is missing or not available
PSU 8 is missing or not available
Failed to perform health check for ServiceChecker due to exception - KeyError('database-chassis')
``` 
Added the database-chassis feature entry to container_feature_dict[] …
=> [service-checker] Fix the service-checker issue which is caused by PR 17836

dockers/docker-dhcp-server/cli-plugin-tests/mock_config_db.json, dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Add config dhcp_server option cli.
Add config dhcp_server option cli.
Add function to config plugin
Run unittests
Add config dhcp_server option cli
=> [dhcp_server] add config dhcp server option

installer/default_platform.conf, installer/install.sh, onie-mk-demo.sh
The existing grub configuration has a hardcoded "amd64" architecture in the kernel and initramfs names. This causes an error in the attempt to load the image compiled for a different architecture.
Use configured architecture in the GRUB config.
Compile the image for Arm64 architecture and install it on the device.
=> [build] Use configured architecture in the GRUB config.

files/image_config/ebtables/ebtables.filter.cfg
Adding rule to ebtables to drop multicast packets in kernel. This was done to address a bug where NS packets were flooding ports with duplicate packets.
ADO: 26395587
Fixes bug where NS packets were flooding ports with duplicate packets
- Microsoft ADO **(number only)**: 26395587
Added ebtables rule to drop multicast packets
1. set up testbed with ebtables rule:  -A FORWARD -d Multicast -j DROP
2. tcpdump from eth4
3. send NS packet from eth8
before this fix, we saw 2 packets received on the tcpdump port. After this fix, we will only see one coming from the basic forwarding
Adding ebtables rule to drop multicast packets.
=> [ebtables] Add multicast drop rule to ebtables

platform/marvell-armhf/sonic-platform-nokia/7215/scripts/nokia-7215init.sh
Disable sysrq  invocation by keyboard and terminal server to prevent accidently triggering it under console overload conditions and performing unintentional actions
- Microsoft ADO **(number only)**:17610243
Disable sysrq by writing 0 into  "/proc/sys/kernel/sysrq" register
1) Verify the register value is 0. also verify that sysrq cannot be triggered by sending a break character via the terminal server.
```
root@sonic:# cat /proc/sys/kernel/sysrq
0
root@sonic:#
telnet> send brk
hh
-bash: hh: command not found
root@sonic:#
```
2) Verify sysrq can still be triggered from procfs
```
root@sonic:# echo u > /proc/sysrq-trigger 
root@sonic:#  sysrq: EmergeRemount R/O
root@sonic:# echo "hi" > /tmp/abc.txt
-bash: /tmp/abc.txt: Read-only file system
```
=> [Nokia-7215-T1] Disable sysrq-trigger from platform init

rules/sonic-dash-api.dep
In some local buildings, an error `/bin/bash: line 0: cd: src/sonic-dash-api/sonic-dash-api: No such file or directory` will be raised due to the directory structure of sonic-dash-api has been changed.
Revised the old path variable in sonic-dash-api.deb
Check Azp and local building
=> [sonic-dash-api]: Fix wrong path in sonic-dash-api.dep

platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
The creation of system EEPROM VPD file "/var/run/hw-management/eeprom/vpd_info" is triggered by the udev event during the system boot up, in case the CPU is busy during the bootup, the udev event handling can be delayed, and need to wait for some more time for the file creation.
Extend the waiting time from 10s to 20s to overcome some extreme case.
continuously run reboot case and verify whether still can see error msg "`ERR decode-syseeprom: Nowhere to read syseeprom from! No symlink found"`
=> [Mellanox] Extend the time to wait for EEPROM VPD file creation

src/systemd-sonic-generator/systemd-sonic-generator.c, src/systemd-sonic-generator/tests/testfiles/test.service
If encountered a line without RequiredBy or WantedBy the code passes uninitialized pointer to get_install_targets_from_line(). Where it can fail with segfault or silently pass randomly.
Uninitialized target_suffix is passed to get_install_targets_from_line() when other fields are present in [Install] section, like this:
```
root@sonic:/home/admin# systemctl cat ntpsec
...
[Install]
Alias=ntp.service
Alias=ntpd.service
WantedBy=multi-user.target
```
Initialize target_suffix with NULL, put an assert in get_install_targets_from_line(). Edited test to cover this scenario.
UT and on the switch.
Without the change - assert fails:
```
[       OK ] SsgFunctionTest.missing_file (2 ms)
[ RUN      ] SsgFunctionTest.insert_instance_number
[       OK ] …
```
=> [systemd-sonic-generator] Fix handling service files with additional fields under [Install] section

device/mellanox/x86_64-mlnx_msn4700-r0/ACS-MSN4700/hwsku.json, device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-C128/hwsku.json, device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O28/hwsku.json, device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/hwsku.json, device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/hwsku.json, device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V48C32/hwsku.json, src/sonic-config-engine/portconfig.py, src/sonic-config-engine/tests/sample_hwsku.json, src/sonic-device-data/tests/hwsku_json_checker
The field 'subport' represents the index of the split port within a physical port. For example, if a port is split into 4, the subport of the first logical port is 1, the subport of the second logical port is 2, and so on.
In xcvrd, the CMIS manager uses the subport to calculate the lane mask, which is used to control the data path per lane. In Nvidia platform, the subport is missing and is always set to 0. According to the xcvrd code, when subport=0, it will always correspond to the first logical port. Therefore, if we shut down any logical port that is not the first one, we will see the operational status of the first logical port also becomes down.
This PR aims to add the subport field to CONFIG DB and prevent such scenarios. This is applicable only for static default breakout mode. …
=> Adding a new field to CONFIG DB: "subport"

platform/marvell-arm64/sai.mk
SDK update to version 1.13.0-1
Build Sonic image running with mrvllibsai 1.13.0-1 and verify the SONIC PTF
=> [Marvell] Update SDK debian to 1.13.0-1

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Changing LPMODE timing is different between cables. 
We want to add functionality to make sure LPMODE has changed.
For that, the wait_until utility is used and every 1 second (until timeout), it will check with lower-layers what is the current Lpmode. 
Once it is the expected mode, set_lpmode() functino will return True. 
If after <timeout> seconds, Lpmode is still not in the expected mode, set_lpmode() function will return False. 
Add use of wait_until function to make sure lpmode was changed.
sfputil lpmode on <port name>
sfputil lpmode off <port name>
=> [Mellanox] Fix timing issue in lpmode change

platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
Error messages occured when trying to read PSU files on init: 
`ERR pmon#psud: Failed to read from file /var/run/hw-management/power/psu1_volt_out2_capability - FileNotFoundError(2, 'No such file or directory')`
This can happen when the power cord is disconnected from the PSU, so some PSU files may be absent, e.g.: 
/var/run/hw-management/power/psu2_volt_out2
/var/run/hw-management/power/psu2_volt_out2_capability
Check if a file exists for a specific PSU parameter If not, return None so we can't read the PSU file any further
1. Disconnect power cord from PSU and power supply from system
2. Wait few minutes and then connect power supply to system without power cord
3. Check logs for errors
=> Check if PSU files exists when getting psu_voltage properties

build_debian.sh, rules/config
When try to install k8s gpg file, there reports an error.
- "E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation   curl: (23) Failed writing body". 
To fix error we need to install gunpg package. But apt-key add is going to be deprecated, mv the gpg file to /etc/apt/trusted.gpg.d/ directly
- Microsoft ADO **(number only)**: 26901718
Download k8s gpg file and put it in /etc/apt/trusted.gpg.d/
We can install k8s gpg file successfully, but no gnupg package installed inside sonic image.
=> Fix missing gnupg package issue during installing k8s gpg file process

dockers/docker-dhcp-relay/Dockerfile.j2, dockers/docker-dhcp-relay/cli-plugin-tests/test_show_dhcp6relay_counters.py, dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py, sonic-slave-bullseye/Dockerfile.j2
Reverting DHCP counter changes due to unexpected packet drops seen in recv buffer, causing counter counts to be inaccurate in dhcpmon and affecting dhcp6relay performance
- Microsoft ADO **(number only)**: 26918588
Reset submodule head and revert related dockerfile changes
Ran mgmt test and stress test
=> [202305] Revert DHCPv4 and DHCPv6 counter

device/celestica/x86_64-cel_e1031-r0/sonic_platform/common.py
The original host check command docker will hang indefinitely when it is run too early in the boot process, halting determine-reboot-cause and lldp/pmon/snmp service from starting. Replace docker with checking /.dockerenv existence.
- Microsoft ADO **(number only)**: 27085874
Replace docker with checking /.dockerenv existence.
Manually modify image and reboot to see if everything work
202305.18
Replace host check command for celestica e1031
=> [e1031] replace host check command in celestica e1031

src/sonic-yang-models/tests/yang_model_tests/tests/acl.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json, src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Fix[ #18137](https://github.com/sonic-net/sonic-buildimage/issues/18137)
This PR is to update the definition of Yang model for ICMP and ICMPv6.
|             | Before change | After change |
|-------------|---------------|--------------|
| ICMP type   |    [1, 44]    |    [0, 44]   |
| ICMP code   |    [1, 16]    |    [0, 16]   |
| ICMPV6 type |    [1, 44]    |   [0, 255]   |
| ICMPV6 code |    [1, 44]    |   [0, 255]   |
References
1. https://datatracker.ietf.org/doc/html/rfc792
2. https://datatracker.ietf.org/doc/html/rfc4443
- Microsoft ADO **27118551**:
Verified by UT.
Update the definition of Yang model for ICMP and ICMPv6.
=> Fix yang model for ICMP and ICMPV6

src/sonic-config-engine/tests/simple-sample-graph.xml, src/sonic-config-engine/tests/test_cfggen.py
BGP monitor asn is 0 in production, and we should have test to cover this configuration.
- Microsoft ADO **(number only)**: 24156888
Update sonic-config-engine unit test, BGP monitor uses asn 0.
Run sonic-config-engine unit test.
=> ASN 0 for BGP monitor

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/port.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json, src/sonic-yang-models/yang-models/sonic-port.yang
Added YANG related changes for adding `dom_polling` field in PORT table of CONFIG_DB. This field can be set with `config interface transceiver dom PORT_NAME (enable|disable)` CLI.
The `dom_polling` field was added through https://github.com/sonic-net/sonic-utilities/pull/3187. Please refer to this PR for the details on the reason for adding `dom_polling` field.
27069573
Added `dom_polling` field to CONFIG_DB PORT table.
Added unit tests for both valid and invalid options for controlling `dom_polling`.
Valid values for for `dom_polling` are `enabled` and `disabled`
Any other value is treated as an invalid value
=> [YANG]: Add Yang model support for adding dom_polling to PORT table

dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
This PR is a dependency of https://github.com/sonic-net/sonic-platform-daemons/pull/383
HLD of sff_mgr: https://github.com/sonic-net/SONiC/pull/1371
Add enable_xcvrd_sff_mgr flag support for sff_mgr
In docker-pmon.supervisord.conf.j2 file, add logic to append enable_sff_mgr flag to xcvrd startup command based on the enable_xcvrd_sff_mgr flag defined in  pmon_daemon_control.json
Also did clean-up on the corresponding j2 logic to make it more read-able and easier to extend.
Verified with different combinations of flags for the output of j2, matched with the original and correct output.
```
sonic-cfggen -a '{"skip_xcvrd_cmis_mgr": false, "enable_xcvrd_sff_mgr": false, "delay_xcvrd": false}' -t /usr/share/sonic/templates/docker-pmon.supervisord.conf.j2 | …
```
=> Add enable_xcvrd_sff_mgr flag support for xcvrd startup command

src/sonic-config-engine/tests/test_minigraph_case.py
Fix issue #18180. 
I suspect this issue caused by race condition during building SONiC image. Some UT cases of minigraph-parser missed `port_config_path`. Hence the testcases will rely on method `device_info.get_path_to_port_config_file` in `sonic-py-common` to read port config info. As multiple components in SONiC are built in parallel, that method may not finish built when it's called by UT.
- Microsoft ADO **(number only)**: 27109878
Transfer value to param `port_config_path` when calling function `parse_xml` in UT. Then the UT will not rely on `sonic-py-common`.
Verified by PR test.
=> [minigraph-parser] Update UT to avoid race condition during build image

files/image_config/kdump/kdump-tools
On certain routers with baud rate 9600, crash kernel is taking a long time , close to ~5mins, to complete kernel dump and reload the box. On contrast to routers with baud rate 115200, crash kernel dump process is observed to be completed under 35s-60s (depending on the platform). Currently, all debug and informational messages are printed on the console which also factors in for the delay seen. Unless the router is monitored on console in real time, these messages are not very useful. Setting the loglevel to warning will help reduce the verbosity of logs on console, in turn allow crash kernel dump process to be completed in a reasonable time which will also help in overall router recovery time.
Setting loglevel attribute in crashkernel cmdline
Install SONiC image with crashkernel cmdline …
=> Set loglevel for crash kernel to reduce verbosity and improve overall router recovery time

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/port.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json, src/sonic-yang-models/yang-models/sonic-port.yang
202305 Cherry-pick for https://github.com/sonic-net/sonic-buildimage/pull/18277
Added YANG related changes for adding `dom_polling` field in PORT table of CONFIG_DB. This field can be set with `config interface transceiver dom PORT_NAME (enable|disable)` CLI.
The `dom_polling` field was added through https://github.com/sonic-net/sonic-utilities/pull/3187. Please refer to this PR for the details on the reason for adding `dom_polling` field.
27069573
Added `dom_polling` field to CONFIG_DB PORT table.
Added unit tests for both valid and invalid options for controlling `dom_polling`.
Valid values for for `dom_polling` are `enabled` and `disabled`
Any other value is treated as an invalid value
=> [202305] [YANG]: Add Yang model support for adding dom_polling to PORT table (#18277)

device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/buffers_defaults_t0.j2, device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/qos.json.j2
Need to provide support for SN4700-O8V48 for Dual-ToR.
DSCP remapping is a part of Dual-ToR feature, so need to update HWSKU files to align with requirements
Use QoS config the same as used in 4600C platform that is already supports Dual-ToR
update buffers for T0
Run DSCP remapping test for Dual-ToR
=> [Mellanox] Support DSCP remapping in Dual-ToR topo for SN4700-O8V48, update buffers for t0

device/celestica/x86_64-cel_e1031-r0/sonic_platform/common.py
Bugfix for Python syntax error in sonic_platform/common.py.
A method of class need to have `self` as parameter.
Fixing below issue:
```
e1031:~$ show int st
File "/usr/local/bin/intfutil", line 836, in <module>
main()
File "/usr/local/bin/intfutil", line 819, in main
interface_stat.display_intf_status()
File "/usr/local/bin/intfutil", line 448, in display_intf_status
self.get_intf_status()
File "/usr/local/lib/python3.9/dist-packages/utilities_common/multi_asic.py", line 157, in wrapped_run_on_all_asics
func(self,  *args, **kwargs)
File "/usr/local/bin/intfutil", line 529, in get_intf_status
self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
File "/usr/local/bin/intfutil", line 334, in po_speed_dict
optics_type = …
```
=> [E1031] Bugfix for Python syntax error in sonic_platform/common.py

src/tacacs/audisp/patches/0003-Add-local-accounting.patch
Fix TACACS local accounting disabled when debug flag disabled.
TACACS local accounting use trace() method to output local accounting log, following PR disable trace log when debug flag disabled, 
https://github.com/sonic-net/sonic-buildimage/pull/16482
Because test case issue, this regression not found. the issue only exists on master branch.
- Microsoft ADO: 25270078
Fix TACACS local accounting disabled when debug flag disabled.
Pass all UT.
Fix TACACS accounting UT to prevent regression.
- [] SONiC.master-16482.360728-2c8b4066f
Fix TACACS local accounting disabled when debug flag disabled.
=> Fix TACACS local accounting disabled when debug flag disabled.

src/sonic-yang-mgmt/sonic_yang_ext.py, src/sonic-yang-mgmt/tests/libyang-python-tests/config_data.json, src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-yang-structure.yang, src/sonic-yang-mgmt/tests/libyang-python-tests/test_SonicYang.json
Fixes "Missing container in list support in YANG Model https://github.com/sonic-net/sonic-buildimage/issues/16704"
Why I did it
Adds support for container in list
How I did it
Identify container in list's leaf and add its data.
Fixes "Update dhcpv6 option yang model" #16290
Why I did it
Adds support for single "choice" statement in container/list
How I did it
Check if choice data is dictionary (instead of list).
Reconstruction details in bug's description.
Tested branch (Please provide the tested image version)
202311
Description for the changelog
Adds support for container in list to yang parsing
Link to config_db schema for YANG module changes
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md#dhcp_relay
Signed-off-by: …
=> Missing container in list support in YANG Model #16704

src/sonic-yang-models/doc/Configuration.md, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests/port.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json, src/sonic-yang-models/yang-models/sonic-port.yang
202311 Cherry-pick for https://github.com/sonic-net/sonic-buildimage/pull/18277
Added YANG related changes for adding `dom_polling` field in PORT table of CONFIG_DB. This field can be set with `config interface transceiver dom PORT_NAME (enable|disable)` CLI.
The `dom_polling` field was added through https://github.com/sonic-net/sonic-utilities/pull/3187. Please refer to this PR for the details on the reason for adding `dom_polling` field.
27069573
Added `dom_polling` field to CONFIG_DB PORT table.
Added unit tests for both valid and invalid options for controlling `dom_polling`.
Valid values for for `dom_polling` are `enabled` and `disabled`
Any other value is treated as an invalid value
=> [202311] [YANG]: Add Yang model support for adding dom_polling to PORT table (#18277)

src/sonic-yang-models/tests/yang_model_tests/tests_config/macsec.json, src/sonic-yang-models/yang-models/sonic-macsec.yang
Fix the issue [18418](https://github.com/sonic-net/sonic-buildimage/issues/18418), The YANG model to MACsec fallback cak/ckn is wrong. We should allow the fallback option is empty.
Add a condition to check whether the fallback is providered
Check Azp
=> [Fixbug 18418] [Yang] MACSEC_PROFILE table does not match yang definition

build_debian.sh
Fix libgrpc++ bookworm debian installation issue.  Fix #18033  
Modified the build_debian.sh to change the libgrpc++1 to libgrcp++1.51 for debian bookworm image build 
After the image is built in the workspace, verify the libgrpc++.so.1.51 is installed in fsroot-broadcom-dnx/lib/x86_64-linux-gnu diretcory
```
~/data/master/sonic-buildimage/fsroot-broadcom-dnx/lib/x86_64-linux-gnu (master)$ ls libgrpc++.so.1.51
libgrpc++.so.1.51
~/data/master/sonic-buildimage/fsroot-broadcom-dnx/lib/x86_64-linux-gnu (master)$ 
```
=> [build_debian] libgrpc++ installation for bookworm debian image build

dockers/docker-database/docker-database-init.sh
redis_chassis process fails to start in the database-chassis on the supervisor card.
The redis and redis_chassis processes in supervisor.conf has been modified to start with 'redis' as user.  The modification only added redis and redis group for database containers except database-chassis container.  This commit adds code to the docker-database-init.sh to add redis and redis group for the database-chassis to address this issue.
Booting the image on Supervisor. And verify the database-chassis container should be in UP state,  and the database-chassis.service is in active(running) state 
```
admin@ixre-cpm-chassis15:~$ docker ps -a
CONTAINER ID   IMAGE                             COMMAND                  CREATED        STATUS        PORTS     NAMES …
```
=> [master][Supervisor][datbase-chassis] Fix  redis_chassis FATAL issue in database-chassis on Supervisor

src/isc-dhcp/patch/0016-Don-t-look-up-the-ifindex-for-fallback.patch, src/isc-dhcp/patch/series
Currently, whenever isc-dhcp-relay forwards a packet upstream, internally, it will try to send it on a "fallback" interface. My understanding is that this isn't meant to be a real interface, but instead is basically saying to use Linux's regular routing stack to route the packet appropriately (rather than having isc-dhcp-relay specify specifically which interface to use).
The problem is that on systems with a weak CPU, a large number of interfaces, and many upstream servers specified, this can introduce a noticeable delay in packets getting sent. The delay comes from trying to get the ifindex of the fallback interface. In one test case, it got to the point that only 2 packets could be processed per second. Because of this, dhcrelay will easily get backlogged and likely get to a point …
=> [202205] dhcrelay: Don't look up the ifindex for the fallback interface (#17797)

files/image_config/rsyslog/rsyslog.conf.j2
An in-band syslog server will not receive any syslog if it is configured without a VRF specified, which is because `eth0` is always specified as the `device` of a syslog server and the syslog packets will be sent to `eth0` regardless of its destination IP address.
Pass the option "device" in rsyslog.conf only if when syslog server's source address is configured with a non-default VRF
Manually test:
1. Configuring a syslog server without VRF specified or with `default` as the VRF: no `device` passed in `rsyslog.conf`
2. Configuring a syslog server with non-default VRF: the configured VRF passed as `device` in `rsyslog.conf`
=> Do not pass the option "device" in rsyslog.conf by default when syslog server's source address is configured

platform/mellanox/mft.mk, platform/mellanox/mft/Makefile
A long-term solution to overcome delay of about 20 sec on login due to MFT bash autocompletion bug.
* To overcome SN2700 20 sec delay on login
* N/A
* Updated MFT to `4.27.0-83`
1. Run `sonic-mgmt/tests/tacacs/test_authorization.py::test_authorization_tacacs_only`
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/18443
* N/A
* N/A
```
'//||\\`
''``
```
=> [202311][Mellanox][MFT]: Update MFT to 4.27.0-83: bash login fix

platform/broadcom/sonic-platform-modules-dell/n3248te/scripts/platform_sensors.py
The command `show environment` has been broken on this platform for quite a while. These adjustments allow it to function again.
I adjusted the `platform_sensors.py` file for the n3248te to appease the errors that it was generating from the Python interpreter.
Run `sudo show environment` on an unchanged n3248te to see that it generates an error right away about `print` statements being malformed. Then place this file at `/usr/bin/platform_sensors.py` in the `pmon` container and run the command again to see the correct output.
master
Updated platform_sensors.py for the Dell N3248TE-ON platform to fix Python errors.
=> fix show environment for n3248te

device/mellanox/x86_64-mlnx_msn2700a1-r0/installer.conf
Removed log in ram option for 2700 A1 platform. Manual cherry-pick of fix https://github.com/sonic-net/sonic-buildimage/pull/17254
Updated installer.conf
Running tests.
=> [202311][Mellanox]Remove log in RAM kernel option for 2700 A1 platform

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
The SAI code was modified to trap and drop the packets if the MAC_SA==MAC_DA and soc variable sai_disable_srcmacqedstmac_ctrl=1 needs to be set in bcm config. There was a PR https://github.com/sonic-net/sonic-buildimage/pull/13346 which added updated bcm config in 202205, but never merged to master.
Updated BCM config
verified that syncd and swss come up in master with SAI 10.x
=> [Nokia][Platform] Update the BCM config file to disable Dos attack when the MAC_SA==MAC_DA

src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py, src/sonic-yang-models/yang-models/sonic-vlan.yang
~
Related to [#3155](https://github.com/sonic-net/sonic-utilities/pull/3155)
Update sonic-vlan.yang model to match requirement as described in #16975 
Update Vlan name regex
Update runVlanSpecialTest to skip Vlan0 (as it is illegal)
master
=> [Yang-models] Update sonic-vlan.yang to better constrain Vlan name

scripts/wait_for_docker.sh
If there is some problem starting the internal dockerd currently the only output in the build output is 60x `errors pretty printing info` spread over a minute. This comes from the stderr on the `docker info` invocations and is not helpful to the user. The final error becomes `make: *** [slave.mk:918: docker-start] Error 1`.
Instead, hide the `errors pretty printing info` messages and print the log of dockerd if we time out.
You can break the build by e.g. not having support for iptables-legacy, which causes dockerd to fail. With the patch the output will now be:
```
does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.`, error: exit status 3" …
```
=> [build] verbose output in wait_for_docker.sh when timing out

platform/innovium/docker-syncd-invm/Dockerfile.j2
This change adds dependent python packages required for innovium platform sdk
Why I did it
To fix innovium sdk issue in syncd docker 
Work item tracking
How I did it
Added dependent python packages in syncd dockerfile
Verified on innovium platforms
Tested branch (Please provide the tested image version)
master
=> Add SDK dependent python packages

onie-mk-demo.sh
I saw an error message in the build logs. `./onie-mk-demo.sh: 176: [: Illegal number: no_sign`.
In shell the operand `-ne` only works on integers. In this case we are trying to compare two strings, which it fails doing:
```
+ [ no_sign -ne no_sign ]                                                        
./onie-mk-demo.sh: 176: [: Illegal number: no_sign
```
Instead, use the != operand which is made for this type of comparison. Reference: `man test`.
Build, when not using signing you should see the message "SECURE_UPGRADE_MODE not defined or defined as no_sign - build without signing".
N/A
N/A
=> [build] fix invalid comparison in onie-mk-demo.sh

files/scripts/asic_status.py
On a Supervisor card of a VOQ chassis, when remove or shutdown a Fabric card, swss.sh shows Stacktrace for all related empty SFM slots in the syslog file.  This PR fixes https://github.com/sonic-net/sonic-buildimage/issues/18384
In the asic_status.py, all empty SFM slots related swss.sh is in the waiting state to wait for the presence event of SFM -- SET operation.  The subscriber event handler also includes the "DEL" operation when a SFM is shutdown/removal.  When a SFM is shutdown, all empty slot's swss.sh also get the "DEL" event although it is not for them.  In the "DEL" operation, the current implementation doesn't check if this "DEL" operation for them, and then they exit the wait state and proceed to docker-wait-any with wrong operation in the …
=> [supervisor][sfm]Fix the issue of swss.sh shows backtrace when shutdown a SFM

files/image_config/rsyslog/rsyslog.conf.j2
cherry pick https://github.com/sonic-net/sonic-buildimage/pull/17616
=> [cherrypick 202305]Do not pass the option "device" in rsyslog.conf by default when syslog server's source address is configured

dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py, dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py, dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py, dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
1. The dhcp_server command didn't receive the db passed by @clicommon.pass_db correctly and there is no unit test case covering this.
2. The feature state checking logic in dhcp_server command won't run when there is no sub-command provided.
- Microsoft ADO **(number only)**: 27384157
1. Add the missing parameter and write UT to test it,
2. Add parameter invoke_without_command=True to make sure the command would check feature state no matter if sub-command provided.
3. Because I add the invoke_without_command=True, so I need to explicitly print help message and exit when there is no sub-command provided.
Write UT to capture the issue before fixing it.
Write UT to check the feature state checking logic.
=> [dhcp_server] Fix config cli plugin missing parameter db

device/celestica/x86_64-cel_e1031-r0/sonic_platform/thermal.py, platform/broadcom/sonic-platform-modules-cel/haliburton/systemd/platform-modules-haliburton.service
Echo #18507 and fix comments.
When determine-reboot-cause is run early, there is very chance it will fail on call to Chassis(), which calls Thermal(), because it checks hwmon that was not yet initialized.
- Microsoft ADO **(number only)**: 27456392
Update platform-modules-haliburton.service file. Let determine-reboot-cause.service start after platform fully initialized.
Built dev image based on 202305 branch.
1. Manually reboot multiple times to confirm determine-reboot-cause.service always start currectly.
2. Run nightly test and confirmed no regression introduced.
=> [E1031] Ensure determine-reboot-cause start after platform fully initialized

device/celestica/x86_64-cel_e1031-r0/sonic_platform/sfp.py
In PR sonic-net/sonic-platform-daemons#435, xcvrd process calls the `get_transceiver_info_firmware_versions` method of `sonic_platform.sfp.Sfp` class. On Celestica-E1031 platform, `Sfp` class inherits `sonic_platform_base.sfp_base.SfpBase` class which doesn't have this method defined. Hence the xcvrd process crash with below error syslog:
```
Mar 28 07:45:12.800226 e1031-3 ERR pmon#xcvrd: Exception occured at DomInfoUpdateTask thread due to AttributeError("'Sfp' object has no attribute 'get_transceiver_info_firmware_versions'")
Mar 28 07:45:12.804729 e1031-3 ERR pmon#xcvrd: Traceback (most recent call last):
Mar 28 07:45:12.805462 e1031-3 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1949, in run
Mar 28 07:45:12.805916 e1031-3 ERR pmon#xcvrd: …
```
=> [E1031] Update sonic_platform.sfp.Sfp class to fix xcvrd crash issue

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/port_config.ini, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/port_config.ini, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/port_config.ini, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm, device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/port_config.ini
HW Lane for Inband and Rec ports were conflicting with front panel ports
Updated the HW lane for Inband and Rec ports
Verified the device in the Nokia chassis 
- [ x] 202205
=> [Nokia-IXR7250E][Devicedata] Update HW Lane for Inband and Rec ports

files/build_templates/sonic_debian_extension.j2
sonic-host-services needs pygobject installed, which is fine for amd64 and arm64, but for armhf, there's no precompiled wheel and requires compilation. This is causing the [upgrade version pipeline](https://dev.azure.com/mssonic/build/_build/results?buildId=513709&view=results) to fail for armhf.
To get around that, just install the version from Debian for armhf. This will cause version 3.42.2-3+b1 to get installed for that architecture.
=> Install pygobject from Debian repos

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py, platform/mellanox/mlnx-platform-api/tests/test_chassis.py
For the SN2201 platform, it includes both RJ45 ports and SFP ports, in the recent new chassis.get_num_sfps() implementation, it only counts the number of SFP ports, however, as per the design, on this platform, RJ45 ports should also be counted to correctly initialize the SFP objects list inside the Chassis. The RJ45 ports are treated as a special type of SFP object in the Mellanox platform API implementation.
count both SFP ports number and RJ45 ports number in  chassis.get_num_sfps().
run SFP-related sonic-mgmt tests on SN2201 and other Mellanox platforms and all the test pass.
=> [Mellanox][SN2201] Fix wrong sfp number on SN2201 platform

platform/pddf/i2c/modules/fan/driver/pddf_fan_driver.c, platform/pddf/i2c/modules/psu/driver/pddf_psu_driver.c, platform/pddf/i2c/modules/xcvr/driver/pddf_xcvr_driver.c
Address the [issue](https://github.com/sonic-net/sonic-buildimage/issues/18287) of the PDDF driver failing to allocate sysfs in kernel 6.1
replaced hwmon_device_register_with_info() with hwmon_device_register_with_groups()
pddf_fanutil
pddf_psuutil
show interface commands
=> address the issue of the PDDF driver failing to allocate sysfs in kernel 6.1

src/system-health/health_checker/sysmonitor.py, src/system-health/tests/test_system_health.py
To fix the issue  https://github.com/sonic-net/sonic-buildimage/issues/15935 where system ready state is 'Not ready' while all expected services are ready. This is due to some FEATURE table entries have state value as template and thus in sysmonitor when the value is checked whether its not [disabled](https://github.com/sonic-net/sonic-buildimage/blob/2e1410c7b7975d3bc5fad19d07fa7958f65ad9c4/src/system-health/health_checker/sysmonitor.py#L186) , the feature is assumed to be enabled and to be started by systemd while the rendering would result in disabled resulting in systemd not starting the feature.
Sysmonitor dnsrvs_name will this have this feature and consider the system wrongly down.
Handled dynamic rendering of the feature
Run UT. Run install of …
=> [System Ready]Handle template value for feature table state field

files/image_config/monit/container_checker
We have used gnmi container to replace telemetry container, and telemetry is still enabled after upgrade.
container_checker script reads from features table and check if the container is running, telemetry is enabled but there's no telemetry container.
It's difficult to disable telemetry in feature table for warm reboot and cold reboot, we need to check docker image in db migrator and minigraph.py.
- Microsoft ADO **(number only)**: 27090944
I modify container_checker script:
If there's docker-sonic-telemetry image, check telemetry container.
If there's no docker-sonic-telemetry image, check gnmi container instead.
If there's no docker-sonic-telemetry image and docker-sonic-gnmi image, do not check telemetry.
Run end to end test with cold-reboot and warm-reboot.
=> Improve container checker for gnmi/telemetry container

device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O28/hwsku.json, src/sonic-config-engine/portconfig.py, src/sonic-config-engine/tests/sample_hwsku.json, src/sonic-config-engine/tests/sample_output/platform_output.json, src/sonic-device-data/tests/hwsku_json_checker, src/sonic-py-common/sonic_py_common/multi_asic.py, src/sonic-py-common/tests/interface_test.py, src/sonic-yang-models/tests/files/sample_config_db.json, src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json, src/sonic-yang-models/yang-models/sonic-port.yang
- Platform api related to xcvr and sfp should not be called for internal ports of SmartSwitch
- To avoid doing this from platform agnostic code of SONiC, a new role called 'Dpc' is added, which would mean DPU-NPU Data Port
- Any new sku which is used as a smartswitch should add this argument to hwsku.json for the ports that fit this category
Added Dpc to the relevant SKU
```
root@mtvr-leopard-01:/home/admin# show interfaces status
Interface                            Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin                                             Type    Asym PFC
-----------  -------------------------------  -------  -----  -----  -------  ------  ------  -------  -----------------------------------------------  ---------- …
```
=> Introduce a new role for DPU-NPU Interconnect

src/systemd-sonic-generator/Makefile, src/systemd-sonic-generator/ssg-test.cc, src/systemd-sonic-generator/systemd-sonic-generator.cpp, src/systemd-sonic-generator/systemd-sonic-generator.h
- Microsoft ADO **27252906**:
Replace char* and C string functions with C++ strings.
=> [ssg]: Use C++ strings for text handling

src/system-health/health_checker/sysmonitor.py
Sysmonitor bug fix
Fix for issue#16596 
When the system reboots, the system-health service is compelled to halt through the transmission of a SIGTERM signal. Consequently, the system_service function encounters an EOFError, leading to the observation of an exception, which is currently being bypassed.
systemctl restart system-health.service 
or perform a reboot and check the syslog
=> Fix for issue#16596

src/sonic-py-common/sonic_py_common/multi_asic.py
This change adds generic functions that can be used to fetch tables from ConfigDB for multi-asic devices based on previous functions created for fetching PORT tables. These functions are to be used in upcoming changes for adding multi-asic support for show/config commands for #15148 to prevent duplicate code.
Modified previously existing helper functions for fetching ports in multi-asic devices and made then generic.
Added generic helper functions for fetching ConfigDB entries for multi-asic devices.
=> Add helpers for fetching ConfigDB entries on multi-asic

sonic-slave-bookworm/Dockerfile.j2
The gcovr package used to have lcov as a runtime dependency. However, that was removed in Debian bug 987818. However, autoconf's code coverage macro file expects lcov and genhtml to be present. This macro is used in sonic-swss-common and likely other submodules.
It's possible that lcov and genhtml are actually not needed for generating the report, and that gcovr is enough. For now, though, just add lcov (which includes genhtml) into the slave container.
=> Add lcov to Bookworm slave container

platform/mellanox/mlnx-platform-api/sonic_platform/modules_mgmt.py
Old flow checked power_good before powering-on the module. 
If the module is not powered, power_good will always remain 0 and flow will stop at the beginning.
Updated the state machine of MDF to have the right order.
I added logs and made sure the right order is being executed.
=> Fix Module Detection Flow in modules_mgmt thread, to check power_on before power_good

dockers/docker-sonic-telemetry/telemetry.sh
Improve visibility for telemetry crashes by allowing core to be dumped.
- Microsoft ADO **(number only)**:27328796
Export GOTRACEBACK=crash as an environment variable.
Manual test
1) Change telemetry binary to crash always, first line of telemetry.go main() -> panic("problem")
2) Add change to telemetry.sh
3) Restart telemetry
4) See core in /var/core
=> Export GOTRACEBACK=crash env variable for telemetry

scripts/versions_manager.py
Reproducible build fails when building dbg containers `make INSTALL_DEBUG_TOOLS=y target/docker-orchagent-dbg.gz`
```
export SONIC_VERSION_CONTROL_COMPONENTS=all
make configure PLATFORM=broadcom
make INSTALL_DEBUG_TOOLS=y target/docker-orchagent-dbg.gz
```
=> [build][reproducible]Fix version file access for dbg container build

build_debian.sh, files/build_templates/sonic_debian_extension.j2
Added support for `minicom` , a terminal based communication tool in the sonic image for enabling communication to other devices.
Added `minicom` to the list of packages to be installed in `sonic_debian_extension.j2` in the platform specific section for mellanox
=> Added new package minicom in the switch image

platform/mellanox/sdk-src/python-sdk-api/Makefile
python-sdk-api is failing in bookworm because it's triggering python2 bindings. 
Fix the invocation by updating the env variable
Compile python-sdk-api from source on bookworm environment and verify on sonic-mgmt tests
=> [Mellanox] Fix python-sdk-api makefile to only compile python3 bindings

dockers/docker-platform-monitor/docker_init.j2
The pmon_daemon_control.json file currently has a platform-specific scope, resulting in all SKUs of the same platform sharing the same pmon daemon configuration. Consequently, this restricts the ability to have distinct pmon daemon configurations for different SKUs. The proposed change aims to enhance flexibility by allowing PMON to load this file from both the platform folder and the HWSKU folder. In case a pmon_daemon_control.json file exists in the HWSKU folder, it will take precedence over the one in the platform folder.
The pmon docker init script will be updated to prioritize the HWSKU folder when searching for the pmon_daemon_control.json file. If the file is present in the HWSKU folder, it will be utilized. However, if the file does not exist in …
=> [PMON] Support to fetch pmon_daemon_control.json file from both platform and HWSKU folders

src/sonic-containercfgd/containercfgd/containercfgd.py, src/sonic-containercfgd/tests/test_syslog_config.py
For multi asic platform, the container name is not the same as service name. For example, service name swss, the container in namespace asic0 will have container name swss0. This PR is to support multi ASIC platform.
Add a global variable service_name and use it to match DB key.
Manual test
Unit test
=> [containercfgd] Add multi ASIC support for syslog rate limit feature

files/build_templates/backend_acl.j2, src/sonic-config-engine/tests/data/backend_acl/acl_multi_vlan.json, src/sonic-config-engine/tests/data/backend_acl/acl_single_vlan.json
Backend acl load is failing since IN_PORTS qualifier is no longer supported. Changing the template to match only on vlan since the only the vlan ports are bound to the DATAACL for backend (https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py#L1346)
- Microsoft ADO: 27172619
Unit test to validate the template rendering
Tested on 202305 branch. Acl loaded successfully after this change.  
```
admin@str2-7050qx-32s-acs-02:~$ sudo systemctl restart backend-acl.service 
admin@str2-7050qx-32s-acs-02:/usr/share/sonic/templates$ show acl rule
Table    Rule          Priority    Action    Match             Status
-------  ------------  ----------  --------  ----------------  --------
DATAACL  RULE_1        9999        FORWARD   ETHER_TYPE: 2048  Active …
```
=> [backend] Update backend acl template and unit tests

src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
Ensure BGP peer bring-up and route advertisements are done only after checking TSA status during reload
- Microsoft ADO **(number only)**: 27171112
Add dependency on tsa_enabled flag before peer configuration
* Validate that the BGP session bring up is not complete until tsa_enabled flag is populated.
* Ensure no traffic is drawn to the device when in TSA and reboot with BGP unshut.
=> Add dependency on tsa_enabled flag for BGP peer config during reload

sonic-slave-bookworm/Dockerfile.j2
Add dependencies required for Nvidia-bluefield image compilation.
Extend a list of the DEB packages installed in the Bookworm slave docker container.
Compile Bookworm slave docker container.
=> [nvidia-bluefield] Add dependencies required for Nvidia-bluefield image compilation.

scripts/build_mirror_config.sh
Buster is EOL, and the backports section has been removed from the main Debian repos. This also means that our default mirror (for non-snapshot builds) is also affected.
- Microsoft ADO **(number only)**: 27691460
Change to using archive.debian.org directly for Buster.
=> Use the archive repo for Buster

device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/port_config.ini, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/port_config.ini, device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/port_config.ini
The alias of the recirc ports on multi-asic systems were the same on both asics.
This change sets the correct asic-id in the recirc port alias.
```
show interfaces status -d all
Interface            Lanes    Speed    MTU    FEC         Alias             Vlan    Oper    Admin             Type    Asym PFC
---------------  ---------------  -------  -----  -----  ------------  ---------------  ------  -------  ---------------  ----------
<snip>
Ethernet-IB0              250      10G   9100    N/A     Recirc0/1           routed      up       up              N/A         off
Ethernet-IB1              250      10G   9100    N/A     Recirc1/1           routed      up       up              N/A         off
Ethernet-Rec0              249      10G   9100    N/A     Recirc0/0           routed      up …
```
=> Prevent alias of recirc ports from colliding on multi-asic

src/sonic-config-engine/portconfig.py, src/sonic-config-engine/sonic-cfggen
**Issue**: 
https://github.com/sonic-net/sonic-buildimage/issues/13137
If run "show interfaces status" we often see error in syslog "SonicDBConfig Global config is already initialized".
**Analysis**: 
During investigation it is found the swsscommon.load_sonic_global_db_config() has been triggered multiple times. Especially in a multi Asic scenario.
CLI triggers "intfutil -c status" with a separate process. Within the process it will trigger IntfStatus init --> MultiAsic() init-->load_db_config()-->load_sonic_global_db_config(). This time initializeGlobalConfig() will run to the end as m_global_init flag is false.
CLI will also run get_port_config() --> db_connect_configdb() --> load_sonic_global_db_config() (for different namepaces. In our case is asic0 and asic1). This time m_global_init …
=> [multi-asic] Fixed 13137 ERR python3: :- initializeGlobalConfig: SonicDBConfig Global config is already initialized 

platform/broadcom/rules.mk
Enable the bookworm image build for platform Nokia-IXR7250E
Modify the platform/broadcom/rules.mk to enabel the bookworm image build for platform Nokia-IXRE7250E
This PR requires PR https://github.com/sonic-net/sonic-buildimage/pull/18445
Image should be able to be ran on Nokia-IXR7250E
=> [master][chassis][Nokia-IXR7250E][bookworm] Enable bookworm build for Nokia-IXR7250E chassis

dockers/docker-orchagent/orchagent.sh, dockers/docker-sonic-gnmi/gnmi-native.sh
Fix smart switch check command in gnmi and orchagent start script.
Smart switch check command in gnmi and orchagent start script check wrong Redis table.
Change smart switch check command check "DEVICE_METADATA|localhost" table.
Pass all UT & E2E test
=> Fix smart switch check command in gnmi and orchagent start script.

files/build_templates/per_namespace/swss.service.j2, files/image_config/hostname/hostname-config.sh, files/scripts/swss.sh
This PR fixes the issue reported in Issu #17945 
We noticed that chassis db clean up is skipped sometimes when the CHASSIS_APP_DB PING fails. Also if host_name and asic_name are not written to CONIG_DB, it could pass the empty strings to CHASSIS_APP_DB EVAL commands.
The service hostname-config.service is restarted whenever the config-reload or load-minigraph is done and this services renames the file /etc/hosts to updates it with the new file. This interferes with swss@.service and when swss.sh script CHASSIS_APP_DPP when the /etc/hosts file is renamed, the error "Unable to connect to redis: Cannot assign requested address" is seen and the CHASSIS_APP_DB EVAL command fails. This causes the chassis db entries not getting cleaned up and causes orchagent crash in  remote LC's.
- Microsoft …
=> Wait till CHASIS_APP_DB PING is successful,  host_name and asic_name are valid in CONIFG_DB before starting chassis-db-cleanup
