sonic-net/sonic-buildimage

- src/sonic-frr/patch/0037-bgp-community-memory-leak-fix.patch
- src/sonic-frr/patch/series
Porting PR https://github.com/sonic-net/sonic-buildimage/pull/18272 to 202311.
Porting fix for https://github.com/FRRouting/frr/issues/15459
Adding patch for PR https://github.com/FRRouting/frr/pull/15466
Ported the fix https://github.com/FRRouting/frr/pull/15466 to 8.5.1
Running the test_stress_route and ensure no memory leak
> [202311][FRR]Adding fix for memory leak seen with BGP community

- dockers/docker-dhcp-server/cli-plugin-tests/conftest.py
- dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py
- dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py
When unbinding customized options, if there is no customized options binding on a dhcp_interface,
the cli will set the key with value empty string which will be parse as [""] by config generator.
- Microsoft ADO **(number only)**: 27708341
Delete the key when value is empty.
Unit test and local build.
> [dhcp_server cli] fix dhcp_server config cli didnt delete customized options when empty

- src/sonic-config-engine/portconfig.py
- src/sonic-config-engine/sonic-cfggen
Reverts sonic-net/sonic-buildimage#18609
This seems to require additional fixes in order to work properly.
Since this fix has no functional value and only has further risks to bring in additional fixes to make it work properly, we decided to just revert this from 202205.
> Revert "[multi-asic] Fixed 13137 ERR python3: :- initializeGlobalConfig: SonicDBConfig Global config is already initialized "

- platform/marvell/platform_arm64.conf
fixes #18681
Fix sonic installer issues for marvell-arm64 platform. Following fixes are part of change,
- Fix illegal character error
- Set second image based on current image
- Fix boot_once uboot environment variable
- Fix print boot menu
Changed the platform.conf scripts which sets uboot environment variables.
Tested following cases to verify the issue,
- sonic-installer install
- sonic-installer set-next-boot
- sonic-installer set-default
> [Marvell-arm64]: Fix sonic-installer

- src/sonic-frr/patch/0038-lib-Do-not-convert-EVPN-prefixes-into-IPv4-IPv6-if-n.patch
- src/sonic-frr/patch/series
Backport based on comment https://github.com/sonic-net/sonic-buildimage/pull/18669#issuecomment-2059288566
Fix the below FRR issues
https://github.com/FRRouting/frr/issues/14419
https://github.com/FRRouting/frr/issues/13792
Ported the following patches
https://github.com/FRRouting/frr/commit/7603eca36d7bf7d73f14f46aa5006063214f03e1
https://github.com/FRRouting/frr/pull/15418
Apply the route map matching evpn type and check if it works.
> [202311][FRR]Fix EVPN route type not matching route map

- src/sonic-build-hooks/scripts/buildinfo_base.sh
Bookworm involved new file /etc/apt/sources.list.d/debian.sources to setup debian mirror repo.
Reproducible build need to support this scenario.
- Microsoft ADO **(number only)**:  27792318
> [build] Fix bookworm reproducible build issue.

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Add bgp_router_id in DEVICE_METADATA yang model
HLD: https://github.com/sonic-net/SONiC/pull/1643
- Microsoft ADO **(number only)**: 27622891
Add bgp_router_id in DEVICE_METADATA yang model
Image built successfully
> [yang][bgp] Add field bgp_router_id in DEVICE_METADATA yang model

- src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_cfggen.py
- src/sonic-dhcp-utilities/tests/test_data/test_kea_config.conf
- src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py
- src/sonic-dhcp-utilities/tests/test_dhcpservd.py
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-buildimage/pull/18796
Comma-sperated string option value would be cut down by kea-dhcp-server
- Microsoft ADO **(number only)**: 27820324
Refer to doc of kea-dhcp-server, escape comma.
> When a data field is a string and that string contains the comma (,; U+002C) character, the comma must be escaped with two backslashes (\\,; U+005C). This double escape is required because both the routine splitting of CSV data into fields and JSON use the same escape character; a single escape (\,) would make the JSON invalid. For example, the string "foo,bar" must be represented as:
1. UT passed
2. Build image and enable dhcp_server, capture packets to verify
> [202311][dhcp_server] Add support for customize string option include comma

- device/arista/x86_64-arista_7060dx5_64s/Arista-7060DX5-64S/hwsku.json
- device/arista/x86_64-arista_7060dx5_64s/Arista-7060DX5-64S/port_config.ini
- device/arista/x86_64-arista_7060dx5_64s/Arista-7060DX5-64S/th4-a7060dx5-64s.config.bcm
- device/arista/x86_64-arista_7060dx5_64s/platform.json
- device/arista/x86_64-arista_7060px5_64s/Arista-7060PX5-64S/blackhawk.xml
- device/arista/x86_64-arista_7060px5_64s/sensors.conf
Misc platform improvements for DCS-7060DX5-64S.
**NOTE:** these changes have been committed to master and 202311 branches via PR #13875.  Objective of this PR is to bring equivalent changes to 202305 branch.
Includes changes for:
- Add 7060DX5-64S brcm tunnel config support
- Set port config ENABLE:0 in 7060DX5-64S brcm config
- Sensor.conf fixes
- SFP port support
- Add copper 50g tuning to babbagelp
Commits describe the changes
Fixes have been uncovered and validated in our in-house testing and running sonic-mgmt testing on DCS-7060DX5-64S.  For this backport request, the fixes are retested on 202305 via in-house testing.
Tested in-house on 202305-based build.
Misc platform improvements for DCS-7060DX5-64S.
> Misc platform improvements for DCS-7060DX5-64S - 202305 port

- dockers/docker-orchagent/orchagent.sh
- files/build_templates/sonic_debian_extension.j2
- files/scripts/syncd.sh
- Add support Nvidia BF-3 platform to swss and syncd containers.
- Add platform-specific extension to include NIC FW into the SONiC image and platform API package.
Extend swss and syncd start scripts to be aware of `nvidia-bluefield` platform.
Extend `sonic_debian_extension.j2` template to include files and packages into the image.
Compile and run `sonic-nvidia-bluefield.bin` image
> [nvidia-bluefield] Add support Nvidia BF-3 platform to swss and syncd containers

- dockers/docker-orchagent/Dockerfile.j2
Fix https://github.com/sonic-net/sonic-buildimage/issues/18765
```
user@server:sonic-buildimage$ make target/docker-orchagent.gz
user@server:sonic-buildimage$ docker load < target/docker-orchagent.gz
user@server:sonic-buildimage$ docker run -it --entrypoint /bin/bash docker-orchagent:latest
root@bc897ed58831:/# dpkg -l | grep protobuf
ii  libprotobuf-lite32:amd64           3.21.12-3                      amd64        protocol buffers C++ library (lite version)
ii  libprotobuf32:amd64                3.21.12-3                      amd64        protocol buffers C++ library
ii  python3-protobuf                   3.21.12-3                      amd64        Python 3 bindings for protocol buffers
```
> Add python3-protobuf package to SwSS Container

- src/sonic-py-common/sonic_py_common/device_info.py
Query base MAC address from the syseeprom or machine.conf for `nvidia-bluefield` platform
Use the same flow as Mellanox platform uses.
Run the image and verify the base MAC address in the config DB.
> [nvidia-bluefield] Query base MAC address from the syseeprom or machine.conf 

- src/sflow/hsflowd/patch/0004-When-interface-removed-just-as-we-discover-it-log-wi.patch
- src/sflow/hsflowd/patch/series
Fixes https://github.com/sonic-net/sonic-buildimage/issues/18804
Ported patch from hsflow that reduces verbosity of log from ERR to INFO when interface is unavailable.
Added patch to the commit https://github.com/sflow/host-sflow/commit/e4689c674b4390681dd8ef725a8d0473abbf0572
Running tests.
> [sflow]Changing the verbosity of ERR log when interface is unavailable

- platform/marvell-arm64/sai.mk
- platform/marvell-arm64/sai/Makefile
- platform/marvell/sai.mk
- platform/marvell/sai/Makefile
Migrate Marvell SAI to new SAI Version 1.13.3
Feature support:
- saiobject
- saidebugcounter
Build Sonic image running with mrvllibsai 1.13.3-1 and verify the SONIC PTF
> [Marvell] Update SDK debian to 1.13.3-1

- device/mellanox/x86_64-mlnx_msn4700_simx-r0/platform.json
- device/mellanox/x86_64-nvidia_sn4280_simx-r0/platform.json
- device/mellanox/x86_64-nvidia_sn5400_simx-r0/platform.json
- device/mellanox/x86_64-nvidia_sn5600_simx-r0/platform.json
To update Mellanox simx platforms chassis name
Updated relevant platform.json files
> [Mellanox] update platform name for simx platforms

- device/mellanox/x86_64-mlnx_msn4410-r0/ACS-MSN4410/hwsku.json
Logic of config generation changed recently
Command : `sonic-cfggen -H -k ACS-MSN4410 --preset t1  will fail after ONIE installation.`
There are missing interfaces for 4410 HWSKU. Need to add them.
Update file device/mellanox/x86_64-mlnx_msn4410-r0/ACS-MSN4410/hwsku.json
`sonic-cfggen -H -k ACS-MSN4410 --preset t1`  will pass successfully on 4410 platform after ONIE installation.
> [Mellanox][SN4410] Add missing interfaces to hwsku

- src/systemd-sonic-generator/ssg-test.cc
- src/systemd-sonic-generator/systemd-sonic-generator.cpp
- src/systemd-sonic-generator/systemd-sonic-generator.h
In addition to /etc/sonic/generated_services.conf, the generator now processes the platform config in /usr/share/sonic/device/%platform/services.conf
This is to support platform-specific systemd-sonic-generator config file. It allows loading additional services based on platform (/etc/machine.conf) information on boot.
Added /usr/share/sonic/device/**%platform**/services.conf processing (if such file exists).
The **%platform** is already available in systemd-sonic-generator (read from /etc/machine.conf)
The unit test is updated to cover new functionality.
Run the systemd-sonic-generator unit tests
> [systemd-generator] add support for platform config file 

- files/build_templates/sonic_debian_extension.j2
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/ldap.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/ldap.json
- src/sonic-yang-models/yang-models/sonic-system-aaa.yang
- src/sonic-yang-models/yang-models/sonic-system-ldap.yang
To support LDAP feature
Similar to Radius/Tacacs authentication methods, the SONiC device is the LDAP client.
Installed the Debian LDAP packages related to making SONiC able to function as an LDAP client.
More description in the following HLD:
https://github.com/sonic-net/SONiC/pull/1487
Do LDAP configuration according to the HLD, then connect to the SONiC switch by using a user that exists in your LDAP server.
YANG Schema can be found attached in the HLD as well.
> Add LDAP feature support

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Support read/write more than 1 page in a single platform API call.
Manual and mock test
> [Mellanox] Support read/write more than 1 page in a single platform API call

- sonic-slave-bookworm/Dockerfile.j2
- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
Remake supports GDB style debugging for Makefiles making it easier to traverse complicated Makefiles and stepping through build steps, printing variables etc. It supports most of the well-known GDB commands for breakpoints, printing, stepping etc.
https://bashdb.sourceforge.net/remake/
`remake` enables developers to debug Makefiles.
Not applicable
Add remake to the apt install list.
Running remake from inside the slave container. For instance, running remake with the `-X` option starts the debugger.
`remake -X -f slave.mk PLATFORM=vs ... EXTRA_DOCKER_TARGETS=docker-ptf.gz buster` 
will run the Makefile and dump into a prompt for further debugging. 
Not applicable.
Not applicable.
Add remake to sonic-slave buster, bullseye and bookworm images for easier Makefile debugging
Not applicable
> [sonic-slave]: Add remake to debug makefiles

- files/image_config/rsyslog/rsyslog.conf.j2
- src/sonic-config-engine/tests/data/rsyslog/config_db.json
- src/sonic-config-engine/tests/test_j2files.py
Include high-precision rfc3339 timestamps in forwarded messages from rsyslog
- Microsoft ADO **(number only)**: 27483313
Create new template for rsyslog that better for kusto to parse with millisec.
Before: 
`<13>Sep 14 22:24:43 PHX70-0101-1019-04T0 pmon#CCmisApi: forwarding state RPC received response port = Ethernet16 portids [0, 1] read_side 1`
After:
`<12>2023-09-14T22:25:03.853194+00:00 PHX70-0101-1019-04T0 WARNING pmon#CCmisApi: Could not retreive fieldvalue pairs for Ethernet24, inside config_db table MUX_CABLE`
Add unit test.
Manual test: create syslog server using CLI/adding to Redis-DB
verify server is added to file /etc/rsyslog.conf and server is functional.
> [rsyslog] Include high-precision rfc3339 timestamps in messages from rsyslog

- platform/components/docker-gbsyncd-credo.mk
Update credo sai package to the latest v0.9.6 to support the blackhawk phys used on Arista platform 7060dx5_64s. It also fixes the issue https://github.com/sonic-net/sonic-buildimage/issues/17716.
- Microsoft ADO: **28013325**
1. Update credo sai url for v0.9.6
2. Include credo sai blackhawk package for blackhawk phy
Basic traffic test on A7280
> [gearbox] use credo sai v0.9.6

- device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C32D4/jr2-a7280cr3-32d4-32x100G+4x400G.config.bcm
- device/arista/x86_64-arista_7280cr3_32p4/Arista-7280CR3-C32P4/jr2-a7280cr3-32p4-32x100G+4x400G.config.bcm
In the following commit the rif_id_max was increased from 0x4000 to 0x6000 but it appears a few 7280cr3 SKUs were missed:
https://github.com/sonic-net/sonic-buildimage/pull/7529/commits/c3506ceaa8fdb1f98ee08239afa426ed0d914f46
Fixing those missing SKUs
> Bump up rif_id_max to match other 7280cr3 SKUs

- src/sonic-frr/patch/0028-zebra-fix-parse-attr-problems-for-encap.patch
- src/sonic-frr/patch/series
Adding patch https://github.com/FRRouting/frr/pull/15968.
This fixes zebra encap problem for multipath with evpn
Ported the fix as patch.
Testing EVPN scenarios.
> [FRR]Fix zebra parse attribute problem for encap

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
- Why I did it
Backport PR #18881 to 202311
Support read/write more than 1 page in a single platform API call.
Manual and mock test
> [202311][Mellanox] Support read/write more than 1 page in a single platform API call (#18881)

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot
For Linecard expected and unexpected reboot, Supervisor needs to log a expected and unexpected lost connectivity message.  After the new mechanism has been introduced by PRs.   For Nokia-IXR7250E-36x600G linecard,  it requires to handle missing heartbeat reboot is unexpected reboot for SUP.   Issue https://github.com/sonic-net/sonic-buildimage/issues/18540
On Nokia-IXR7250E-36x400G platform, missing heartbeat reboot also call the "sudo reboot" which creates a CHASSIS_MODULE_REBOOT_INFO_TABLE entry expected reboot on SUP.  Since heartbeat reboot is unexpected reboot, it requires to modify the platform_reboot check if it is missing heart reboot, then remove the CHASSIS_MODULE_REBOOT_INFO_TABLE entry on the SUP. So that, SUP can log the unexpected log.
1) …
> [Nokia][chassis] modify Nokia-IXR7250E-36x400G platform specified reboot to allow SUP to log expected/unexpected midplane/module connectivity msg

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan.py
Fix issue #18767 fan information could not been shown issue.
Add psu fan get_target_speed api support.
Use `show platform fan` in branch 202311.
> [Seastone] fix issue #18767 psu fan speed issue

- build_debian.sh
In Debian 6.1.38, `rfkill` is used, which uses `cfg80211`. `cfg80211` will attempt to load on boot and will look for `regulatory.db`, which is installed via `wireless-regdb`, a missing package.
Add `wireless-regdb` to packages to install for Debian.
> Added wireless-regdb as package to install for Debian

- dockers/docker-snmp/snmpd.conf.j2
- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample_graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
1. fix https://github.com/sonic-net/sonic-buildimage/issues/16001
2. fix https://github.com/sonic-net/sonic-buildimage/issues/17807
https://github.com/sonic-net/sonic-buildimage/pull/17045 modified minigraph parser to use management and loopback IPs to support SNMP query over IPv6. With this fix, if mgmt or loopback IP contains link local IP, that will not work as link local IP has to be appended with scope id associating the IP address to a specific interface. This PR change is to ensure that snmp works with link local IPv6 address.
1. Modify minigraph parser to append the Ip address with % scope id if snmp agent address being used is link local IP address.
2. Modify snmpd.conf.j2 to take this change while checking if an IP address is ipv4 or ipv6. …
> Fix to use IPv6 linklocal address as snmp agent address

- src/sonic-pac/mab/protocol/mab_auth.c
- src/sonic-pac/mab/protocol/mab_db.c
- src/sonic-pac/mab/protocol/mab_local.c
- src/sonic-pac/mab/protocol/mab_mac_db.c
- src/sonic-pac/mab/protocol/mab_radius.c
- src/sonic-pac/mab/protocol/mab_timer.c
- src/sonic-pac/mab/protocol/mab_utils.c
- src/sonic-pac/mab/protocol/mab_vlan.c
> MAB protocol related changes

- src/iccpd/src/iccp_cli.c
- src/iccpd/src/iccp_cmd.c
Add boundary check before memset, memcpy, strncpy calls to prevent buffer overflow
- Microsoft ADO **(number only)**: 27008041
> Add boundary check before memset, memcpy, strncpy

- files/image_config/resolv-config/resolv-config.service
Cherry Pick of #18670 
To fix `resolv-config.service` being cancelled:
`resolv-config.service` is started from `hostcfgd` each time there is an [update to the dns configuration or during the start of hostcfgd.
](https://github.com/sonic-net/sonic-host-services/blob/6fce4781da508709f11be595e3c7048ffd3138cb/scripts/hostcfgd#L1406) When we perform `config reload` because `hostcfgd` is restarted `resolv-config.service` is also restarted, but due to dependency of [`resolv-config.service` on `sonic.target`](https://github.com/sonic-net/sonic-buildimage/blob/ed839c65055c3cbb446ddabdc9c15b0684988139/files/image_config/resolv-config/resolv-config.service#L5)  `systemd` also tries to restart `resolv-config.service` causing cancellation of one of the instances of `resolv-config.service`. This fix …
> [202311] Fix for DNS service being canceled 

- src/sonic-yang-models/tests/yang_model_tests/tests/aaa.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/aaa.json
- src/sonic-yang-models/yang-models/sonic-system-aaa.yang
This will cover more cases for those only have authentication enabled with tacacs but not authorization enabled. Also, make it algin with the check in load_minigraph
- Microsoft ADO **(number only)**: 26732148
Change to authentication
unit test
> [YANG] Align to authentication check with load_minigraph to cover more scenarios

- files/build_templates/default_manifest
- files/build_templates/sonic_debian_extension.j2
To support Third Party Container Management in Sonic App Extension Framework
The main changes for this feature are in sonic-utilities repo. 
Here in this sonic-buildimage repo, this change is to prepare the directory (subdirectory "manifests" under /var/lib/sonic-package-manager) and the default manifest at build time without the need to create it in runtime every time
Execute commands specified in sonic-utilities repo PR for TPCM.
> Third Party Container Management Support in Sonic App Extension

- files/image_config/rsyslog/rsyslog.conf.j2
Currently SONiC logs do not show the year:
```
root@str2-7050cx3-acs-01:~# tail -f /var/log/teamd.log
Feb 14 00:07:54.856313 str2-7050cx3-acs-01 DEBUG teamd#teamd_PortChannel102[37]: usock: calling method "StateDump"
Feb 14 00:07:54.856795 str2-7050cx3-acs-01 DEBUG teamd#teamd_PortChannel101[29]: usock: calling method "StateDump"
Feb 14 00:07:55.859690 str2-7050cx3-acs-01 DEBUG teamd#teamd_PortChannel104[53]: usock: calling method "StateDump"
```
This PR fixes that issue:
```
2024 Feb 15 02:24:26.091224 str2-7050cx3-acs-01 DEBUG teamd#teamd_PortChannel102[33]: usock: calling method "StateDump"
2024 Feb 15 02:24:26.091224 str2-7050cx3-acs-01 DEBUG teamd#teamd_PortChannel101[25]: usock: calling method "StateDump"
2024 Feb 15 02:24:26.752655 str2-7050cx3-acs-01 DEBUG …
```
> Added current year to all log files

- files/image_config/ntp/ntp.conf.j2
- src/sonic-config-engine/tests/sample_output/py3/ntp.conf
fixes #17906
To fix NTP config generation from the minigraph and save backward compatability
Align `ntp.conf.j2` template to generate config out of empty `NTP_SERVER` DB configuration
Out of that NTP_SERVER configuration:
```json
{
"10.210.25.32": {},
"10.75.202.2": {}
}
```
The next config in `ntp.conf` file should be produced:
```
server 10.210.25.32
restrict 10.210.25.32 kod limited nomodify notrap noquery nopeer
server 10.75.202.2
restrict 10.75.202.2 kod limited nomodify notrap noquery nopeer
```
> [NTP] 🐞 Fix config template to init default parameters

- build_debian.sh
- dockers/docker-platform-monitor/Dockerfile.j2
Add nvme-cli tool 
Add nvme-cli utility tool for platforms using NVMe
```
root@str-D10-U32:~# nvme version
nvme version 2.3 (git 2.3)
libnvme version 1.3 (git 1.3)
root@str-D10-U32:~# 
root@str-D10-U32:~# nvme smart-log /dev/nvme0
Smart Log for NVME device:nvme0 namespace-id:ffffffff
critical_warning                        : 0
temperature                             : 43°C (316 Kelvin)
available_spare                         : 100%
available_spare_threshold               : 10%
percentage_used                         : 0%
endurance group critical warning summary: 0
Data Units Read                         : 4,421,218 (2.26 TB)
Data Units Written                      : 2,590,713 (1.33 TB)
host_read_commands                      : 26,514,410 …
```
> Add nvme-cli tool

- src/sonic-frr/patch/0035-fpm-ignore-route-from-default-table.patch
Fix issue https://github.com/sonic-net/sonic-buildimage/issues/18887
Reintroduced the patch https://github.com/sonic-net/sonic-buildimage/pull/12912 for 202311
Integrate patch and check for error
> [202311][FRR]FRR/zebra error messages for routes from kernel default table

- src/system-health/health_checker/sysmonitor.py
To address #18814
Introduce exclude service list in the code to be parsed and remove the services from the system ready tracking.
In this case, it is ztp.service
show system-health sysready-status output
master branch
> Remove services mentioned in exclude service list for system monitoring

- dockers/docker-orchagent/ipinip.json.j2
- dockers/docker-orchagent/switch.json.j2
- dockers/docker-platform-monitor/docker_init.j2
- The Appliance DPU supports a limited subset of the configuration defined in the [SONiC DASH HLD](https://github.com/sonic-net/SONiC/blob/master/doc/dash/dash-sonic-hld.md).
- Configure SWSS and GMNI to communicate on the Appliance DPU.
- Add a sample configuration for the `appliance` topology.
Disable configuration unsupported by the Appliance DPU based on the device type.
Run VNET-to-VNET sonic-mgmt test.
> Add configuration optimization to run SONiC on DPU

- src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_cfggen.py
- src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py
Manually cherry-pick and resolve conflicts of https://github.com/sonic-net/sonic-buildimage/pull/18945 (In 202311 we didn't have smart_switch support)
Currently, dhcpservd wouldn't monitor option / range change which is referred in DHCP_SERVER_IPV4 table but is invalid or not been defined. It would miss config when they are defined or become valid.
- Microsoft ADO **(number only)**: 28067655
Treat invalid or not defined option / range as interested items.
UT passed
> [202311][dhcp_server] Add support for monitoring used but invalid range/option #18945

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/buffer_queue.json
- src/sonic-yang-models/tests/yang_model_tests/tests/qos.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/buffer_queue.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/qos.json
- src/sonic-yang-models/yang-models/sonic-buffer-queue.yang
- src/sonic-yang-models/yang-models/sonic-queue.yang
The configuration for `QUEUE` and `BUFFER_QUEUE` differs between a `VOQ` device and a `Non-VOQ` devices. 
For the `Voq` device:
The queue and buffer  queue is applied on the system port. The system port is a representation of every port in a chassis, the key for systemport consists of `Linecard Name` , `Asic Name` and `portname` 
On a Non voq device: 
the queue and buffer queue configuration  is applied on the front panel port.
Due to this differences the yang models `sonic-queue.yang` and `sonic-buffer-queue.yang` does not work for Voq devices
This is address in this PR
- Microsoft ADO **(27252773 and 27252696)**:
Update the yang model to have different CONFIG_LIST  with different keys based on the following condition
- when the switch_type is not present or switch_type is not `voq`, the …
> [Chassis][Voq]Update sonic-buffer-queue and sonic-queue for Voq Chassis

- src/sonic-yang-models/yang-models/sonic-system-port.yang
- Microsoft ADO **27934751**:
Fixes #18854 
Update the `sonic-system-port.yang` to remove the check to have `ifname` as leafref in the port table
The system-port config table will have all the ports in the chassis not only to one linecard, so in case of the chassis with different linecards sku with different number of ports this leafref will not work.
> [chassis][voq] Remove the leaf ref for the ifname in sonic-system-port.yang

- dockers/docker-fpm-frr/docker_init.sh
- dockers/docker-fpm-frr/frr/zebra/zebra.conf.j2
- platform/vs/docker-sonic-vs/frr/zebra.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/zebra.conf
- src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-vni-zebra.conf
- src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-zebra.conf
- src/sonic-config-engine/tests/sample_output/py2/zebra_frr.conf
- src/sonic-config-engine/tests/sample_output/py2/zebra_frr_dualtor.conf
- src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-vni-zebra.conf
- src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-zebra.conf
- src/sonic-config-engine/tests/sample_output/py3/zebra_frr.conf
- src/sonic-config-engine/tests/sample_output/py3/zebra_frr_dualtor.conf
- src/sonic-frr/patch/0029-zebra-nhg-fix-on-intf-up.patch
- src/sonic-frr/patch/series
Fix #17345 
To handle the issue https://github.com/sonic-net/sonic-buildimage/issues/17345 in FRR. Previously a work around was added in SONiC https://github.com/sonic-net/sonic-buildimage/pull/17344.
Reverted the workaround https://github.com/sonic-net/sonic-buildimage/pull/17344
Integrate the following fixes
https://github.com/FRRouting/frr/pull/15823
https://github.com/FRRouting/frr/pull/15362
Running regression.
> [FRR][Zebra]Porting fix to handle nexthop group on interface up

- platform/marvell-arm64/sai.mk
Bug fixes: Fixed initialization failures on non-MACSEC AC5X platforms.
Add the SAI SDK fix to skip macsec functionality.
Load the SAI debian on non-macsec AC5x platform and run testbed sanity.
> [Marvell] Update arm64 sai debian

- src/sonic-config-engine/sonic-cfggen
PR 10960  fixed an issue of calling load_sonic_global_db_config() multiple times which causes error log of "SonicDBConfig Global config is already initialized". The load_namespace_config() has logic issue so is fixed with this PR
Tested with the above fix and run "show interface status". Watched there's no error log. And commands works fine.
> Fix a logic issue for load_namespace_config in sonic-cfggen

- dockers/docker-platform-monitor/Dockerfile.j2
- files/build_templates/sonic_debian_extension.j2
- rules/docker-platform-monitor.mk
- sonic-slave-bookworm/Dockerfile.j2
This is a part of a larger commit that adds a storage monitoring daemon to SONiC. This commit is needed to that storagemon daemon can save FS stats JSON file to disk in the event of planned reboots and unintentional powercycles.
[SONiC Storage Monitoring Daemon HLD](https://github.com/sonic-net/SONiC/pull/1481)
Also added `psutil` module to perform process and system monitoring operations pythonically.
- Microsoft ADO **(number only)**: 17468992
- Added a rule to create the directory on the pmon container
- Added a rule to create a bind-mount
Flash a switch with image containing the changes. 
Run:
```
root@str2-7050cx3-acs-13:~# docker inspect pmon
```
and verify the following parameters in the "mounts" section:
```
"Mounts": [
.
.
.
{
"Type": "bind",
"Source": "/host/pmon/stormond", …
```
> Adds a bind mount from host to /usr/share/stormond/ directory on pmon container

- rules/frr.dep
Fix #16713
Variable SMDEP_FILES is empty and smdep file is not generated for sonic-frr.
Need to escape a dollar sign in Makefiles.
Rebuild frr with build cache and make sure smdep file for sonic-frr exists in target.
> [Build] fix DPKG cache for frr

- Makefile
It's enough to execute `make reset` only once.
Now it's executed 3 times.
Fix Makefile.
make init
make reset
> execute make reset command only once

- Makefile.work
- build_debian.sh
- build_image.sh
- rules/config
- slave.mk
- sonic-slave-bookworm/Dockerfile.j2
- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
`pigz`, which stands for parallel implementation of gzip,
is a fully functional replacement for gzip that exploits multiple processors
and multiple cores to the hilt when compressing data.
We can use it for compression instead of gzip  to speed up builds.
It reduces build time (especially at final stage where we compress whole file system).
But solution with special option `GZ_COMPRESS_PROGRAM` is not good,
because it's hard to maintain (developers need to pass this flag to every script).
I think it's better to remove this option at all and use pigz directly where it's possible.
Remove config flag `GZ_COMPRESS_PROGRAM`
Use pigz directly instead of gzip where it's possible.
I have tested builds with pigz almost 1 year and no issues were detected.
So I …
> [build] use pigz by default

- rules/config
- scripts/build_mirror_config.sh
Fix #17113
If we set `MIRROR_SNAPSHOT=y` in `build_mirror_config.sh`
then we have incorrect value of `MIRROR_SNAPSHOT` in other places like `buildinfo/config/buildinfo.config`
Override `MIRROR_SNAPSHOT=y` in `rules/config` if
`SONIC_VERSION_CONTROL_COMPONENTS=all` or
`SONIC_VERSION_CONTROL_COMPONENTS` includes `deb` component.
Start to build with different values of `SONIC_VERSION_CONTROL_COMPONENTS` and `MIRROR_SNAPSHOT` in cmdline
and check value of `MIRROR_SNAPSHOT` in `buildinfo.config` and debian mirrors in sources.list files
> enable MIRROR_SNAPSHOT if SONIC_VERSION_CONTROL_COMPONENTS includes deb

- src/sonic-build-hooks/hooks/dpkg
- src/sonic-build-hooks/scripts/buildinfo_base.sh
Fix #15722
We don't need to use a lock file every time we call dpkg.
For some commands, like `dpkg --print-architecture` or `dpkg --compare-versions`,  this action is not required.
Moreover, sometimes these commands are called by `apt-get` and `dpkg -i`, and we get a deadlock in this case.
Use dpkg lock only for dpkg commands that use /var/lib/dpkg/lock or /var/lib/dpkg/lock-frontend.
I mean `dpkg -i`, `dpkg -P`, ...
Check there is no dpkg lock errors in build log.
Check build time of docker-sonic-vs.gz:
old:
08:57:14[ building ] [ target/docker-sonic-vs.gz ] 
09:12:47 [ finished ] [ target/docker-sonic-vs.gz ] 
new:
01:45:12[ building ] [ target/docker-sonic-vs.gz ] 
01:50:39 [ finished ] [ target/docker-sonic-vs.gz ] 
- [ x] 202305
> Fix dpkg lock

- dockers/docker-database/Dockerfile.j2
With the upgrade of docker-database to Bookworm in #18108 and the new Redis version that was brought in, database saves are enabled by default. However, we don't use (and maybe don't want, at this time) those database saves.
Restore the old behavior by modifying `/etc/redis/redis.conf` to not save at all.
Checked `/var/log/syslog` to make sure there weren't messages from redis every minute saying the database was being saved, and verified `/etc/redis/redis.conf` in the database container has a config line with `save ""`.
> Update save disable code for new Redis version

- azure-pipelines.yml
We are going to onboard a batch of test cases into PR test recently. To achieve this without disrupting the existing PR test processes, we add a separate non-blocking PR checker for onboarding new tests.
> Add a separate non-blocking PR check for onboarding new tests(T0).

- device/mellanox/x86_64-mlnx_msn2010-r0/sensors.conf
- device/mellanox/x86_64-mlnx_msn4600-r0/sensors.conf
- device/mellanox/x86_64-mlnx_msn4600c-r0/sensors.conf
- device/mellanox/x86_64-mlnx_msn4600c-r0/sensors_respin.conf
- device/mellanox/x86_64-nvidia_sn2201-r0/sensors.conf
- device/mellanox/x86_64-nvidia_sn5600-r0/sensors.conf
This PR is used to standardize several sensors.conf psu section
I. Fix 4600/4600c inverted psu number designation
II. Fix 5600 second psu miss set_power_cap label
III. Standardized comments
check `sensors` command output
> [Mellanox] Fix 4600c sensors.conf inverted psu number designation 

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Avoid returning NoneType while reading 0 byte from SFP's EEPROM
In CMIS CDB it is possible to read 0 byte from SFP's EEPROM. It will throw an exception if the platform API returns' NoneType'.
We would like to return `bytearray(0)` here to avoid such exceptions.
> [Mellanox] Avoid returning NoneType while reading 0 byte from SPF's EEPROM

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py
- platform/mellanox/mlnx-platform-api/tests/test_watchdog.py
Currently the platform API will arm the watchdog w/o checking the required watchdog period. If the watchdog period is longer than the max period supported by the platform, it will cause issue on some specific platform. 
Verify whether the required watchdog period is longer than the max period supported, if yes then return failure.
test with watchdog util to set the watchdog period to different values including larger than the max supported period, all case passed.
> [Mellanox] Block setting the watchdog in the case that watchdog period is longer than the max period supported by the platform

- files/build_templates/sonic_debian_extension.j2
- platform/mellanox/mlnx-sonic-bfb-installer.mk
- platform/mellanox/rules.mk
- platform/mellanox/sonic-bfb-installer.sh
In order to install the bfb image from the switch to all the dpus we need a script to execute the bfb_install script on all the detected rshim device parallely. The `sonic-bfb-installer` can be used to install bfb images on the DPUs from the switch using the rshim drivers
Added new makefile and script files for installation of bfb image
`sonic-bfb-installer.sh -b <bfb_image_path> -r all`
`sonic-bfb-installer.sh -b <bfb_image_path> -r rshim1,rshim0`
> [Mellanox] Add bfb image installation script to the switch image

- files/build_templates/init_cfg.json.j2
- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/stormond.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/stormond.json
- src/sonic-yang-models/yang-models/sonic-stormond-config.yang
This is part of a larger feature: [SONiC Storage Monitoring Daemon](https://github.com/sonic-net/SONiC/pull/1481) -- this commit adds the option to configure the daemon's polling interval and fsstats file sync interval (in seconds) of the daemon via config_db by introducing YANG models.
- Microsoft ADO **(number only)**: 17468992
Gives userside the option to dynamically a new table 'STORMOND' with key INTERVALS and fields 'daemon_polling_interval' with default value of '3600' seconds and 'fsstats_sync_interval' with default value of '86400' seconds as defined in the YANG model.
Flash image onto a DUT and add the aforementioned table to the CONFIG_DB. Verify that `stormond` has picked up your config intervals.
> Adds YANG models for configurable intervals in CONFIG_DB for stormond

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/yang_model_tests/tests/vxlan.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vxlan.json
- src/sonic-yang-models/yang-models/sonic-vxlan.yang
Fixed  the Vxlan tunnel yang model to add support for
1) Tunnel name length restriction has been removed
2) dst_ip field.
The yand modle was misisng an element and supported tunnel anme was very small.
27996821
run yang model tests
> [Yang][Bugfix] Vxlan tunnel yang model to support dest_ip and name length.

- src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcpservd.py
We need to reload config on kea-dhcp4 to make new config take effect.
- Microsoft ADO **(number only)**: 28146970
After dump new config, send SIGHUP to kea-dhcp4 process to force refresh config.
Tested on testbed.
> [dhcp_server]  Send signal to kea-dhcp4 to read new config after dump

- src/sonic-yang-models/tests/yang_model_tests/tests/buffer_pool.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/buffer_pool.json
- src/sonic-yang-models/yang-models/sonic-buffer-pool.yang
Added buffer pool type as both for yang model verification
> Adding Buffer pool enum type both for sonic chassis

- files/build_templates/init_cfg.json.j2
- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/bgp_device_global.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp_device_global.json
- src/sonic-yang-models/yang-models/sonic-bgp-device-global.yang
To define a field to track isolation state for the IDF to which the T2 device belongs
Added yang model definition, unit tests, sample config and documentation for the table
Validated config tree generation using "pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/sonic-voq-inband-interface.yang"
Built the below python-wheels to validate unit tests and other changes
target/python-wheels/bullseye/sonic_yang_mgmt-1.0-py3-none-any.whl
target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl
target/python-wheels/bullseye/sonic_config_engine-1.0-py3-none-any.whl
> Yang model changes for Sequential IDF isolation

- files/build_templates/rsyslog_plugin.conf.j2
- src/sonic-eventd/rsyslog_plugin/rsyslog_plugin.cpp
- src/sonic-eventd/rsyslog_plugin/rsyslog_plugin.h
- src/sonic-eventd/rsyslog_plugin_tests/rsyslog_plugin_ut.cpp
Backport (#18835)
Fix #18771
Microsoft ADO (number only):27882794
How I did it
Add signalOnClose for omprog as well as close rsyslog plugin when receives an EOF.
Verify rsyslog_plugin is running inside bgp or swss container
Run docker exec -it bgp supervisorctl restart rsyslogd
Before change:
This will not kill current rsyslog_plugin process but instead rsyslogd will now break off its end of writing to cin and send EOF to rsyslog_plugin, however will not send a signal SIGTERM or SIGKILL to rsyslog_plugin. Therefore, rsyslog plugin will run in an infinite loop forever, constantly calling getline raising CPU to 100% inside docker.
After change of adding signalOnClose="on" to conf file inside omprog, rsyslogd will now send SIGTERM to rsyslog_plugin process running inside …
> [eventd]: Close rsyslog plugin when rsyslog SIGTERM and EOF is sent

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Add `chassis-hostname` leaf to the `sonic-device_metadata.yang`
Add `chassis-hostname` leaf to the `sonic-device_metadata.yang`
UT
> [chassis] add chassis hostname to device metadata

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/buffers_defaults_t1.j2
Add symlink so that config-setup passes
> Add buffers_defaults_t1 for Arista-7260CX3-D108C8

- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
These 2 dependencies were removed by https://github.com/sonic-net/sonic-buildimage/pull/18764 and https://github.com/sonic-net/sonic-buildimage/pull/18727 for decoupling hard dependency between Loopback IPv4 address and BGP.
Actually, these dependencies are to make sure existence of Loopback interface, no need to remove.
- Microsoft ADO **(number only)**: 28210625
Add dependency back
UT passed.
> [bgp] Re-add dependency in managers_bgp for bgpcfgd

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
On Mellanox platforms, changing the control type sysfs value is not supported for ports that are set to firmware control. Therefore, attempting to change this value to firmware control will result in an error log, which we want to avoid.
I added a check to ensure that the control sysfs value is set to firmware control only if it is not already in firmware control.
Ensure that after a warm reboot on the Mellanox platform (an attempt to change the sysfs value from fw_control to fw_control is only applicable in this scenario), the following error does not appear:
sxd_kernel: [error] sx_core_set_module_control: Failed control change: module is dependent (FW control).
> [Mellanox] Verify the value of the control type sysfs before changing it to FW control

- files/image_config/ntp/ntp.conf.j2
fixes #17906
cherry-pick #18736
To fix NTP config generation from the minigraph and save backward compatability
Align `ntp.conf.j2` template to generate config out of empty `NTP_SERVER` DB configuration
Out of that NTP_SERVER configuration:
```json
{
"10.210.25.32": {},
"10.75.202.2": {}
}
```
The next config in `ntp.conf` file should be produced:
```
server 10.210.25.32
restrict 10.210.25.32 kod limited nomodify notrap noquery nopeer
server 10.75.202.2
restrict 10.75.202.2 kod limited nomodify notrap noquery nopeer
```
> [202311][cherry-pick][NTP] 🐞 Fix config template to init default parameters

- dockers/docker-orchagent/orchagent.sh
Fix Orchagent crash during boot because of eth0 not config address.
Fix https://github.com/sonic-net/sonic-buildimage/issues/19044
On SmartSwitch DPU the eth0 might not config any address
- Microsoft ADO: 28188952
Fix Orchagent crash during boot because of eth0 not config address.
Pass all UT.
Manually verified the orchagent not crash when eth not config address:
root       20026  8.3  1.2 748344 49512 pts/0    Sl   06:25   0:03 /usr/bin/orchagent -d /var/log/swss -b 1024 -s -m 22:48:23:27:33:d8 -q tcp://127.0.0.1:8100
Fix Orchagent crash during boot because of eth0 not config address.
> Fix Orchagent crash during boot because of eth0 not config address

- src/tacacs/audisp/patches/0002-Remove-user-secret-from-accounting-log.patch
- src/tacacs/audisp/patches/0003-Add-local-accounting.patch
Ignore TACACS accounting trace log when debug disabled.
TACACS accounting trace log is only for debug, improve code to not generate trace log when debug disabled.
Manually cherry-pick following 2 PR, because fir PR has a code bug, PR validation will block it:
https://github.com/sonic-net/sonic-buildimage/pull/16482
https://github.com/sonic-net/sonic-buildimage/pull/18357
- Microsoft ADO: 25270078
Ignore TACACS accounting trace log when debug disabled.
Pass all UT.
Manually verified the auditd-tacplus not generate trace log when debug disabled. 
Ignore TACACS accounting trace log when debug disabled.
> [202311] Fix TACACS local accounting disabled when debug flag disabled.

- platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
Service like ZTP accesses EEPROM very early at the boot stage. It could cause an issue that EEPROM is not ready. The PR enlarge EEPROM ready timeout from 20s to 60s.
Enlarge EEPROM ready timeout from 20s to 60s.
Manual test
> [Mellanox] enlarge the eeprom ready timeout from 20 to 60

- .azure-pipelines/azure-pipelines-Official.yml
- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/docker-sonic-slave.yml
- .azure-pipelines/dpkg-cache-cleanup.yml
- .azure-pipelines/official-build-cache.yml
- .azure-pipelines/official-build-multi-asic.yml
- .azure-pipelines/official-build.yml
- .azure-pipelines/template-commonlib.yml
- azure-pipelines.yml
Migrate agent pool to fix S360 ticket.
- Microsoft ADO **(number only)**:  27889786
> [ci] Migrate ubuntu and sonicbld agent pool to fix S360 alert.

- platform/marvell-arm64/sai.mk
- platform/marvell/sai.mk
Update Marvell SAI for arm64 and amd64 to include MACsec feature.
Build Sonic image running with mrvllibsai and verify the SONIC PTF
> [Marvell] Update SAI debian

- platform/mellanox/sdk-src/wjh-libs/Makefile
Passing the last installed kernel headers during SDK compilation. Without this the SDK does uname -r which gives the kernel version of the host machine in the slave docker. But these kernel headers are not installed in the slave docker leading to compilation failure.
Passing the kernel version in debuild step by obtaining the latest installed kernel version.
Compilation with sources.
> [Mellanox]Passing the installed kernel headers during SDK compilation

- src/tacacs/audisp/patches/0002-Remove-user-secret-from-accounting-log.patch
- src/tacacs/audisp/patches/0003-Add-local-accounting.patch
Ignore TACACS accounting trace log when debug disabled.
TACACS accounting trace log is only for debug, improve code to not generate trace log when debug disabled.
Manually cherry-pick following 2 PR, because fir PR has a code bug, PR validation will block it:
https://github.com/sonic-net/sonic-buildimage/pull/16482
https://github.com/sonic-net/sonic-buildimage/pull/18357
- Microsoft ADO: 25270078
Ignore TACACS accounting trace log when debug disabled.
Pass all UT.
Manually verified the auditd-tacplus not generate trace log when debug disabled. 
Ignore TACACS accounting trace log when debug disabled.
> [202305] Fix TACACS local accounting disabled when debug flag disabled. 

- dockers/docker-ptf/Dockerfile.j2
This PR fixes a bug in the docker-ptf Dockerfile when executed with `SONIC_PTF_ENV_PY_VER=py3` option.
Without this fix the `docker-ptf` image pushes all the required py3 packages into a virtual environment and prevents it from starting up.
Not applicable
Fixed the jinja condition to initialize virtualenv only for `mixed` case.
Build, load and run the docker image 
- Build with - `make SONIC_PTF_ENV_PY_VER=py3 SONIC_BUILD_JOBS=4 BUILD_MULTIASIC_KVM=y INCLUDE_DHCP_SERVER=y target/docker-ptf.gz`
- Load and run the image - `docker load -i target/docker-ptf.gz`
- Run with - `docker run -it --entrypoint bash docker-ptf:latest`
Verified the packages are installed properly.
Not applicable. This feature is turned off by default. Will be tested with PTF tests and turned on at a later date after …
> [docker-ptf]: Fix issue with Py3 environment

- device/arista/x86_64-arista_7800_sup/Arista-7804R3-FM/fabric_monitor_config.json
- device/arista/x86_64-arista_7800_sup/Arista-7808R3-FM/fabric_monitor_config.json
- device/arista/x86_64-arista_7800_sup/Arista-7808R3A-FM/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cq2_lc/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cqm2_lc/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/fabric_monitor_config.json
feature by default.
The fabric link monitoring feature is disabled by default, and we need to issue CLI to enable it. 
Before figuring out a more generic way of enable it by default, added a monState field in the fabric config file so we can enable the feature by default. 
> Add monState field in config file so we can enable fabric link monitor

- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_env.conf
This PR add the platform specified linecard_reboot_timeout value to the platform_evn.conf.  It works PR https://github.com/sonic-net/sonic-platform-daemons/pull/480 and https://github.com/sonic-net/sonic-utilities/pull/3292 to address issue https://github.com/sonic-net/sonic-buildimage/issues/18540
Add line "linecard_reboot_timeout=180" to Nokia-IXR7250E Supervisor platform_env.conf file.  This will allow the chassisd to derive the linecard_reboot_timeout value.  
Related PRs:
https://github.com/sonic-net/sonic-utilities/pull/3292
https://github.com/sonic-net/sonic-platform-daemons/pull/480
https://github.com/sonic-net/sonic-buildimage/pull/18805
This PR requires PRhttps://github.com/sonic-net/sonic-utilities/pull/3292 and  to work with
1) Test expected …
> [Nokia][supervisor] add linecard_reboot_timeout value to platform_env.conf for Nokia-IXR7250E platform

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_ndk.json
To support SAI native ASIC DRAM thermal sensor polling (as added by BCM in SAI 10.1.15)
Update to latest Nokia PMON submodule and provide appropriate settings in our platform specific .json files to properly identify the DRAM thermal sensor values and to stop our NDK from polling these DRAM thermal sensors.
Be certain to enable SAI native ASIC thermal sensor polling (see below for procedure) and then ensure that all thermal sensor values are listed using the 'show platform temperature' command after the system has booted and quiesced.
[Nokia][sonic-platform] Support SAI native ASIC DRAM thermal sensor polling (as added by BCM in SAI 10.1.15)
> Support SAI native ASIC DRAM thermal sensor polling

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal.py
Currently, on Mellanox platforms, when trying to read from the EEPROM of an unplugged module from thermalctld, we get the following error:
ERR kernel: [ 2446.261799] sxd_kernel: [error] Failed to get module page valid, err: -5
We need to ensure the EEPROM is not accessed if a module is not connected.
I updated the logic of get_presence() to rely on the present/hw_present sysfs values and called get_presence() from within the relevant methods in thermalctld.
Unplug a module and ensure the following error does not appear:
ERR kernel: [ 2446.261799] sxd_kernel: [error] Failed to get module page valid, err: -5
> [Mellanox] Validate Module Presence Via Sysfs Before Accessing EEPROM in Thermal Control Daemon

- build_debian.sh
This version of docker-py has the fix for the issue caused by requests 2.32, and has the added benefit of upgrading to the latest version of docker-py.
> Upgrade docker-py to 7.1.0

- device/arista/x86_64-arista_7800_sup/Arista-7804R3-FM/fabric_monitor_config.json
- device/arista/x86_64-arista_7800_sup/Arista-7808R3-FM/fabric_monitor_config.json
- device/arista/x86_64-arista_7800_sup/Arista-7808R3A-FM/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cq2_lc/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3_48cqm2_lc/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/fabric_monitor_config.json
PR #19128 introduced a regression where the minigraph would fail to load, due to missing quotes in the new monState field in the fabric monitor config.
Quoting the "enable" string fixes the issue.
Verified that `load_minigraph -y -n` does not fail with a traceback due to a parse error.
> arista: Fix monState in fabric monitor config

- rules/config
`overlay2` is more faster comparing to `vfs` (more info in #11111)
And we use this option to build SONiC almost two years.
But it may be not obvious for some people that default choice is slow.
I think we should set overlay2 as a default storage driver for `DinD`.
Change default value of `SONIC_SLAVE_DOCKER_DRIVER` in `rules/config`
Build SONiC and compare build time with vfs and overlay2.
> [build] use overlay2 for DinD by default

- files/scripts/arp_update
On dual TOR devices, excluding INCOMPLETE and FAILED neighbors when checking for neighbor mismatches between APPL_DB and the kernel will result in all zero MAC neighbors being logged as mismatches.
- Microsoft ADO **28266511**:
On a dual TOR device, add a FAILED neighbor entry (can simply `ping` some unreachable IP in the VLAN subnet).
Without the changes, we would expect to see the following log every 5 minutes:
```
swss#arp_update: mismatch arp entry, pinging <neighbor IP> on <VLAN interface>
```
With the changes, we would not see the above log
> Include unresolved neighbors when comparing APPL_DB and kernel neighbors

- platform/vs/tests/breakout/sample_output/sample_new_port_config.json
- platform/vs/tests/breakout/test_breakout_cli.py
- src/sonic-config-engine/portconfig.py
- src/sonic-config-engine/tests/sample_output/platform_output.json
- src/sonic-config-engine/tests/test_cfggen_platformJson.py
This pull request merges https://github.com/sonic-net/sonic-buildimage/pull/18499 to 202311
Automatically populate the correct subport value for an interface and insert into config_db.json
I verified this by checking the output of sonic-cfggen, updating config_db. and checking that both the host and media lane masks were correct for a 400GBASE-DR4 xcvr in both 2x200G-4 mode and 4x100G-2 mode.
All links came up and xcvrd prints the correct lanemasks in logs.
I also made sure that portconfig.py no longer causes an exception; it only checks for the optional HWSKU value if childports are present in hwsku.json file (this is to make sure we don't break Mellanox hwsku's)
I also changed the unit test for config_db generation and ensured the correct values match. The test passes.
> Calulcate subport values and fix key error in hwsku.json

- device/mellanox/x86_64-mlnx_msn4410-r0/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4600-r0/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4600c-r0/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn4280_simx-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn4800-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn4800_simx-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn5400-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn5400_simx-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn5600-r0/pmon_daemon_control.json
- files/scripts/syncd.sh
For doing fast-reboot with CMIS active modules.
Removed PMON delay for SKUs with support for CMIS active modules
Run fast-reboot test
- [] 202311
> [Mellanox] Remove pmon delay for certain platforms

- platform/checkout/cisco-8000.ini
* Fixed syncd crash due to segfault in libsai
> Update cisco-8000.ini to 0.master.0.2 release

- dockers/docker-database/database_config.json.j2
The template has a missing comma in the remote Redis JSON configuration. This causes an error when attempting to start the database container on the DPU in the Smart Switch.
Add missing comma
Compile and run the DPU SONiC image. The database container should run with no errors.
> [database] Fix database config template for remote Redis instance

- dockers/docker-database/supervisord.conf.j2
The local Redis daemon should not run for a remote database.
Do not generate a supervisord configuration entry for the remote database instances.
Compile and run the DPU image. The database container on the DPU should run Redis daemons only for local DB instances.
> [database] Do not run local a Redis instance for the remote database

- files/scripts/arp_update
When a script calls the logger utility, each individual call gets its own PID assigned. Rsyslogd creates an internal rate-limit object per PID that sends a log message. If the logger utility is called repeatedly, it will cause rsyslogd memory usage to increase permanently since a rate-limit object is being created for each call.
- Microsoft ADO **28263484**:
Override the `logger` command in the arp_update script to use the --id argument to specify the parent script PID that rsyslogd should use for rate limiting.
> [arp_update]: Use parent script PID for logger calls

- rules/restapi.mk
Fix build error when enable restapi and debug.
the derived package function is not called correctly.
- Microsoft ADO **(number only)**:  28376451
> [build] Fix restapi debian package dependency error.

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/mux-linkmgr.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/mux-linkmgr.json
- src/sonic-yang-models/yang-models/sonic-mux-linkmgr.yang
A new flag was introduced in https://github.com/sonic-net/sonic-linkmgrd/pull/250 to disable mux oscillations but yang model wasn't updated. We are seeing multiple tests failing due to this, some of them are -
1.  `generic_config_updater/test_dynamic_acl.py`
2. `passw_hardening/test_passw_hardening.py`
3. `dualtor_mgmt/test_toggle_mux.py`
- [#153](https://github.com/aristanetworks/sonic-qual.msft/issues/153)
Ran the failing tests with the image.
> Update sonic-mux-linkmgr yang model

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
Two steps (among others) are required to enable the host CMIS management feature: enabling it in the switch's sai.profile and performing a config reload. During the timeframe between these two steps, the control sysfs might be accessed, but they will not be present on the system until the latter step, the config reload, is completed. The code should try to access the control sysfs only after the config reload step. A good indication that this has been done is to check if the relevant entry is included in syncd's sai.profile. In contrast to the switch's sai.profile, syncd's sai.profile is only updated with the Host CMIS management support flag after the reload is complete.
I updated the is_module_host_management_mode() implementation to first look for the …
> [Mellanox] Enhance is_module_host_management_mode to also check syncd's sai.profile

- src/system-health/health_checker/service_checker.py
- src/system-health/tests/telemetry/etc/supervisor/critical_processes
- src/system-health/tests/test_system_health.py
Fix https://github.com/sonic-net/sonic-buildimage/issues/19081
We have used gnmi container to replace telemetry container, and telemetry is still enabled after upgrade.
service_checker script reads from features table and check if the container is running, telemetry is enabled but there's no telemetry container.
It's difficult to disable telemetry in feature table for warm reboot and cold reboot, we need to check docker image in db migrator and minigraph.py.
When we use warm reboot to upgrade from 202305 to 202311, config_db still has telemetry configuration, and we can't simply remove related configuration.
I modify service_checker script:
If there's docker-sonic-telemetry image, check telemetry container.
If there's no docker-sonic-telemetry image, …
> Improve service checker for gnmi/telemetry container

- dockers/docker-dhcp-relay/Dockerfile.j2
- dockers/docker-fpm-frr/Dockerfile.j2
- dockers/docker-orchagent/Dockerfile.j2
- files/build_templates/init_cfg.json.j2
- files/build_templates/sonic_debian_extension.j2
- files/image_config/rsyslog/rsyslog.d/00-sonic.conf.j2
- Microsoft ADO **(number only)**: 27773623
Added checks after redirect to frr/bgpd.log
Manual test
> Fix rsyslog plugin slim image logic

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Enable get_tx_fault support in CMIS cable host mgmt mode on Mellanox platforms
Use community get_tx_fault implementation instead of the dummy one
API call and run API Test
> [Mellanox] Enable get_tx_fault support in CMIS cable host mgmt mode

- platform/vs/docker-sonic-vs/orchagent.sh
This is required to test DNX specific implementation for PFCWD on VS.
- Add ASIC_TYPE to force orchagent to run with the given ASIC.
- Add PFC_DLR_INIT_ENABLE to allow test to override PfcDlrInitEnable for VS switch. This is required to test PfcWdAclHandler, instead of PfcWdDlrHandler.
> Add environs to test PFCWD on DNX

- platform/marvell-arm64/sai.mk
- platform/marvell/sai.mk
Add support in SAI debian for, 
- Serdes tuning
- PHY LED config 
Compile and load the SAI debian in Marvell SONiC ecosystem.
> [Marvell] Update SAI deb for intel and arm64 arch.

- device/mellanox/x86_64-nvidia_sn5400-r0/ACS-SN5400/create_only_config_db_buffers.json
Create counters for configured buffer objects only on ACS-SN5400
We did this for all generic SKUs but missed it for ACS-SN5400
> [Mellanox] Create counters only for configured buffer objects on SN5400

- azure-pipelines.yml
In this PR, we add two parameters `STOP_ON_FAILURE: "False"` and `RETRY_TIMES: 0` into non-blocking T0 PR checker. Which means, one script will only execute once in a testplan, no matter if it fails. And one failed script will not block other remaining test scripts. Test plan will finish executing all test scripts. 
> Add two parameters into non-blocking T0 PR checker. 

- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE-256x200G/th5-a7060x6-64de.config.bcm
- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE-64x400G/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE/th5-a7060x6-64de.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-128x400G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-256x200G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-64x400G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE/th5-a7060x6-64pe.config.bcm
- device/common/profiles/th5/gen/BALANCED/buffers_defaults_t0.j2
- device/common/profiles/th5/gen/BALANCED/buffers_defaults_t1.j2
Adds egress_lossy_pool and fixes SAI error caused by TH5 default config
This change is needed to fix a SAI crash on boot. These values zero out the reserved buffer space that by default would cause the pools defined in config_db.json to fail to create due to insufficient remaining room.
The buffer pool values were chosen by simply dividing the total available MMU memory into 3 pools.
Without this change device fails to boot correctly.
Fix QoS configuations for Quicksilver
> Fix QoS configuations for Quicksilver

- azure-pipelines.yml
Elastictest performs well in distribute running PR test in multiple KVMs, which support us to add more test scripts to PR checker.
To achieve our goal without disrupting the existing PR test processes, add a separate non-blocking T1 PR checker for onboarding new tests.
> Add a separate non-blocking PR check for onboarding T1 tests

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/fabric_monitor_config.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/fabric_monitor_config.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/fabric_monitor_config.json
PR #19144 was missing quotes in fabric monitor config which causes load_minigraph failure
Added fabric monState config in quotes 
Did load_minigraph and verified that there are no errors.
> [Nokia][Device] Fix monState in farbic monitor config

- dockers/docker-orchagent/switch.json.j2
- src/sonic-config-engine/tests/sample_output/t0-switch-masic1.json
- src/sonic-config-engine/tests/sample_output/t0-switch-masic3.json
- src/sonic-config-engine/tests/sample_output/t0-switch.json
- src/sonic-config-engine/tests/sample_output/t1-switch.json
Reverts sonic-net/sonic-buildimage#19397
This change was taken too early. We need to wait for below swss change to be merged and submodule advanced first.
https://github.com/sonic-net/sonic-swss/pull/3204
> Revert "[action] [PR:18912] [swss]: Add default ECMP/LAG hash offset values for T0 and T1 (#18912)"

- slave.mk
**Bug Fix: RFS is still loading from cache**
```
user@build-server:/sonic-buildimage$ cat target/sonic-mellanox.bin__mellanox__rfs.squashfs.log
Build start time: Tue Jun 25 20:13:00 UTC 2024
[ FLAGS  FILE   ] : [mellanox amd64 bookworm]
[ FLAGS  DEPENDS ] : [mellanox amd64 bookworm]
[ FLAGS  DIFF   ] : []
target/sonic-mellanox.bin__mellanox__rfs.squashfs
target/sonic-mellanox.bin__mellanox__rfs.squashfs.cached.log
File /dpkg_cache/sonic-mellanox.bin__mellanox__rfs.squashfs-adc83b19e793491b1c6ea0f-3bc3261c3a235b9c15daac9.tgz  is loaded from cache into /sonic
[ CACHE::LOADED ] /dpkg_cache/sonic-mellanox.bin__mellanox__rfs.squashfs-adc83b19e793491b1c6ea0f-3bc3261c3a235b9c15daac9.tgz
File /dpkg_cache/sonic-mellanox.bin__mellanox__rfs.squashfs-adc83b19e793491b1c6ea0f-3bc3261c3a235b9c15daac9.tgz …
```
> [Cache] Truly disable loading the RFS cache

- device/mellanox/x86_64-nvidia_sn5400-r0/platform.json
- device/mellanox/x86_64-nvidia_sn5400_simx-r0/platform.json
Removed 8x mode from SN5400 and simx platforms as current DPB infrastructure doesn't support 8x mode with the subsequent port need to be disabled
Updated platform.json of both devices.
Running show interfaces breakout command and verifying this mode doesn't exist.
```
{
"Ethernet0": {
"index": "1,1,1,1,1,1,1,1",
"lanes": "0,1,2,3,4,5,6,7",
"breakout_modes": {
"1x400G[200G,100G,50G,40G,25G,10G]": [
"etp1"
],
"2x200G[100G,50G,40G,25G,10G]": [
"etp1a",
"etp1b"
],
"4x100G[50G,25G,10G]": [
"etp1a",
"etp1b",
"etp1c",
"etp1d"
]
},
"default_brkout_mode": "1x400G[200G,100G,50G,40G,25G,10G]",
"Current Breakout Mode": "1x400G[200G,100G,50G,40G,25G,10G]",
"child ports": "Ethernet0",
"child port speeds": "400G"
},
```
> [Mellanox]Removing 8x DPB mode from SN5400 and SN5400_simx platforms

- platform/nvidia-bluefield/platform-api/sonic_platform/thermal_bf3.py
- platform/nvidia-bluefield/platform-api/tests/test_thermal_bf3.py
- platform/nvidia-bluefield/platform-api/tests/utils.py
To extend nvidia-bluefield thermal platform-api
Added support for a single-port platform
Added SSD as thermal reading
> [nvidia-bluefield] update platform-api thermal logic

- Makefile.work
DEFAULT_CONTAINER_REGISTRY didn't work as expected in some scenario.
When check for docker arch, use DEFAULT_CONTAINER_REGISTRY if it is not null.
> [build] Use DEFAULT_CONTAINER_REGISTRY in Makefile.work instead of dockerhub.

- platform/checkout/cisco-8000.ini
Cisco platform 202405.0.2 release
> Update cisco-8000.ini to 202405.0.2 release

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp_sm.py
When module host management is enabled, all modules are managed by the same state machine which initializes all modules/ports. However, on 5600 and 5400, there is a type of port which we called "service port". Those ports are always under firmware control. In that case, those ports should be managed by a different state machine. This PR is to implement the state machine for always firmware control ports.
Implement a state machine for always firmware control ports.
Manual test
unit test
> [Mellanox] implement state machine for always firmware control ports

- Makefile.work
- platform/vs/docker-sonic-vs/Dockerfile.j2
- sonic-slave-bullseye/Dockerfile.j2
[202311] Support FIPS for armhf
Cherry-pick from the PR: https://github.com/sonic-net/sonic-buildimage/pull/18283
- Microsoft ADO **(number only)**: 26189767
Build the SymCrypt armhf packages and integrate with sonic image.
> [202311] Support FIPS for armhf (#18283)

- src/sonic-config-engine/minigraph.py
The load_mgmt_config generated lo_v6 is missing standalone entry which fail YANG validation
- Microsoft ADO **(number only)**:28665800
Add the standalone entry
Manual test in DUT
Before change:
```
admin@str-msn2700a1-03:~$ sonic-cfggen -M /etc/sonic/device_desc.xml --print-data 
{
"DEVICE_METADATA": {
"localhost": {
"hostname": "CPQ21-0101-0509-04T0",
"hwsku": "Arista-7260CX3-D108C8"
}
},
"LOOPBACK_INTERFACE": {
"lo_v6|2603:10d0:e:5eb::/128": {}         <==== missing standalone entry which fail YANG
},
"MGMT_INTERFACE": {
"eth0|100.84.101.139/26": {
"gwaddr": "100.84.101.129"
},
"eth0|2603:10e2:f0:7478::b/64": {
"gwaddr": "2603:10e2:f0:7478::1"
}
}
}
```
After change:
```
admin@str-msn2700a1-03:~$ sonic-cfggen -M /etc/sonic/device_desc.xml --print-data 
{
"DEVICE_METADATA": { …
```
> Fix no standalone lo_v6 entry which break YANG validation

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_chassis_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
- src/sonic-config-engine/tests/test_multinpu_cfggen.py
In #15058, the NTP server configuration was modified to add additional options, such as conditionally enabling iburst, specifying the association type, and specifying the NTP version. One side effect of this was that the iburst option which was previously always enabled now requires it to be explicitly enabled in the config_db.
Fixes #19425.
- Microsoft ADO **(number only)**: 28623148
To restore the old behavior, when loading from minigraph, add `"iburst": "true"` for each NTP server loaded from minigraph.
Tested on a KVM setup, verified that the generated `ntp.conf` file had the `iburst` option.
> Enable iburst option for NTP servers loaded from minigraph

- dockers/docker-fpm-frr/base_image_files/TS
- dockers/docker-fpm-frr/base_image_files/TSA
- dockers/docker-fpm-frr/base_image_files/TSB
Addressing review comments to use 'SpineRouter' in checks instead of 'voq' and fix few echo msgs.
To address review comments
- https://github.com/sonic-net/sonic-buildimage/pull/19217#discussion_r1667199390
- https://github.com/sonic-net/sonic-buildimage/pull/19217#discussion_r1667199613
Ran reliable_tsa tests from https://github.com/sonic-net/sonic-mgmt/pull/13290 on a T2 chassis.
> Reliable TSA: Addressing review comments to use 'SpineRouter' in checks instead of 'voq' and fix few echo msgs.

- azure-pipelines.yml
In this PR, we add a new PR checker called onboarding dualtor. This new PR checker is for onboarding dualtor speific test scripts.
> Add onboarding dualtor PR checker. 

- Makefile.work
Why I did it
DEFAULT_CONTAINER_REGISTRY didn't work as expected in some scenario.
How I did it
When check for docker arch, use DEFAULT_CONTAINER_REGISTRY if it is not null.
> [202205, build] When check for docker arch, use DEFAULT_CONTAINER_REGISTRY if it is not null (#19466)

- src/sonic-yang-models/tests/yang_model_tests/tests_config/system_port.json
- src/sonic-yang-models/yang-models/sonic-buffer-queue.yang
- src/sonic-yang-models/yang-models/sonic-queue.yang
- src/sonic-yang-models/yang-models/sonic-system-port.yang
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Fixes #19485 
- Microsoft ADO ** 28529095**:
Add a new typedef for `asic_name` and make the pattern case in sensitive
UT and test on voq linecards
202405 and 202205
> [Chassis][Voq][Yang] Make asic_name case sensitive in yang models

- Makefile.work
DEFAULT_CONTAINER_REGISTRY didn't work as expected in some scenario.
- Microsoft ADO **(number only)**:  28739327
When check for docker arch, use DEFAULT_CONTAINER_REGISTRY if it is not null.
> [build] Use DEFAULT_CONTAINER_REGISTRY in Makefile.work instead of dockerhub. (#19445)

- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/hwsku.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/hwsku.json
When CMIS host mgmt is enabled, CMIS active cables' autoneg must be disabled. 
Here, it will generate config_db with autoneg:off by default for all ports. 
deploy/sonic-cfggem
> [Mellanox] Disable Auto Negotiation by default for SN4700

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-256x200G/BALANCED/buffers_defaults_t0.j2
The latest TH5 mmu configuration has some issues where egress pool creation fails with the latest BCM SAI updates.
> Jul 20 12:04:58.163923 str3-7060x6-64pe-2 ERR syncd#syncd: [none] SAI_API_BUFFER:driverEgressPoolSharedLimitSet:3476 configure egress itm 0 buffer pool 0 with size 82830162, gport 0x 800000b COS 0 current reserved size 21805392 shared size 60996322, requested shared size 61024770 failed with error -1
> Jul 20 12:04:58.163923 str3-7060x6-64pe-2 ERR syncd#syncd: [none] SAI_API_BUFFER:ltsw_driverDBLimitSet:3197 set egress buffer pool 0 limit to 82830162 using port 11 queue 0 failed with error -1
- Microsoft ADO **(number only)**: 28775282
This PR fixes the issue by updating the egress pool size to match with the one in the ASIC.
Tested on local testbed
> Jul 20 19:45:35.767569 …
> Fix TH5 egress pool creation failure with BCM YAML file and SAI update on 07/16.

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- src/sonic-device-data/tests/permitted_list
Broadcom requires that `programmability_ucode_relative_path` is set in SAI11.
This soc property replaces the legacy `custom_feature_ucode_path`
Without this we get the following error:
```
syncd#supervisord: syncd 0:dbx_file_get_db_location: DB Resource not defined#015
syncd#supervisord: syncd #015#015
syncd#supervisord: syncd 0:dnx_init_pemla_get_ucode_filepath:  Error 'Invalid parameter' indicated ; #015#015
```
> Set soc property `programmability_ucode_relative_path` for Arista DNX Devices

- rules/config
- src/sonic-dhcp-utilities/dhcp_utilities/dhcprelayd/dhcprelayd.py
dhcpmon is not ready to count packets for dhcp_server, hence remove invoking of it for now
- Microsoft ADO **(number only)**: 28811034
Remove starting dhcpmon when dhcp_server is enabled
UT passed
> [dhcp_server] Remove invoke of dhcpmon when dhcp_server is enabled

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/yang_model_tests/tests/gnmi.json
- src/sonic-yang-models/tests/yang_model_tests/tests/telemetry.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/gnmi.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/telemetry.json
- src/sonic-yang-models/yang-models/sonic-gnmi.yang
- src/sonic-yang-models/yang-models/sonic-telemetry.yang
https://github.com/sonic-net/SONiC/pull/1297
add config_db entries for TELEMETRY|gnmi|save_on_set
> add config_db entries for TELEMETRY|gnmi|save_on_set

- rules/docker-sflow.mk
Starting 6.1.94, Kernel mandates the process to have SYS_ADMIN/NET_ADMIN capability to join events/packets multicast group respectively PSAMPLE used packets and DROPMON uses events
Ref:
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=e03781879a0d https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=44ec98ea5ea9
Without this, the following error is observed and host-sflow couldn't use psample and NET_DB and so the feature is broken
```
2024 Jul 24 22:38:35.140784 r-tigris-04 ERR sflow#hsflowd: error joining PSAMPLE netlink group 20 : Operation not permitted
2024 Jul 24 22:38:35.849822 r-tigris-04 ERR sflow#hsflowd: error joining DROPMON netlink group 1 : Operation not permitted
```
Verify the sflow …
> Enable linux capabilities on sflow container for kernel 6.1.94 compatibility

- files/image_config/logrotate/rsyslog.j2
Currently the logrotate script is susceptible to SIGPIPE issue because of a race condition between the `sort` and `head` commands that leads to the following error:
```
Jun 22 03:20:00.331117 sonic-switch INFO logrotate[1494655]: sort: write failed: 'standard output': Broken pipe
Jun 22 03:20:00.331207 sonic-switch INFO logrotate[1494655]: sort: write error
```
This is because if the `sort` command has not yet finished writing to `stdout` and `head` has finished executing and closes the pipe. Subsequent writes by the previously issued `sort` command would fail because of the closed pipe.
- Microsoft ADO **(number only)**: 28511764
I refactored the code in a way that removes the call to `head` after `sort`.
1. I created a bash script that induces a `write failed: Broken pipe` error on …
> Separated sort and head commands to prevent broken pipe issues

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/buffer_pool.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/buffer_pool.json
- src/sonic-yang-models/yang-models/sonic-buffer-pool.yang
Support yang model for `percentage` field in `BUFFER_POOL` table.
It is used in dynamic buffer model only and represents the percentage of a buffer pool's size compared to the available memory size
Unit test and manual test
> Support yang model for buffer pool percentage

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
The reading of eeprom instantly after switch the module from sw control to fw control might fail, so add a delay
> [Mellanox] fix sfp eeprom unreadable after switching from SW to FW control mode

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
- src/sonic-config-engine/tests/test_multinpu_cfggen.py
Backport of #19424 to 202311 branch.
In #15058, the NTP server configuration was modified to add additional options, such as conditionally enabling iburst, specifying the association type, and specifying the NTP version. One side effect of this was that the iburst option which was previously always enabled now requires it to be explicitly enabled in the config_db.
Fixes #19425.
- Microsoft ADO **(number only)**: 28874651
To restore the old behavior, when loading from minigraph, add "iburst": "true" for each NTP server loaded from minigraph.
Tested on a KVM setup, verified that the generated ntp.conf file had the iburst option.
> [202311] Enable iburst option for NTP servers loaded from minigraph (#19424)

- platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
Backport PR https://github.com/sonic-net/sonic-buildimage/pull/18983 to 202305
Service like ZTP accesses EEPROM very early at the boot stage. It could cause an issue that EEPROM is not ready. The PR enlarge EEPROM ready timeout from 20s to 60s.
Enlarge EEPROM ready timeout from 20s to 60s.
Manual test
> [202305] [Mellanox] enlarge the eeprom ready timeout from 20 to 60 (#18983)

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/buffers_defaults_t2.j2
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cqm2-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-c36-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-d36-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x100g.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x400g.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cqm2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-c36-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-d36-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x100g.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x400g.json
To fix PFC generation issue during congestion on lossy queues.
- Microsoft ADO **(28865646)**:
Updated lossy PG threshold to be higher than Queue threshold not to allow PFC generation.
Verified on sonic chassis with configuration check as well as traffic test.
> Updated MMU settings for ingress lossy profile Nokia and Arista chassis

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-128x400G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-256x200G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-64x400G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE/th5-a7060x6-64pe.config.bcm
Enable pipe mode in TH5 flex counter block to support queue counters for all the ports.
- Microsoft ADO **(number only)**: 28949528
Update TH5 configuration file.
Verified on a TH5 switch.
> Update TH5 flex counter configs

- dockers/docker-ptf/Dockerfile.j2
Latest changes to sflowtool [source](https://github.com/sflow/sflowtool/blob/master/configure.ac#L4) mandates autoconf 2.71+ to build it. Bullseye is at autoconf 2.69. This PR builds autoconf from source in the docker-ptf image.
- Microsoft ADO **(number only)**: Not applicable
Modified dockers/docker-ptf/Dockerfile.j2 to -
- Install dependencies to build autoconf
- Build and install autoconf
docker-ptf image is built successfully.
Not applicable.
Sflowtool requires autoconf 2.71; Build autoconf from source
Not applicable
> [docker-ptf] sflowtool requires autoconf 2.71+

- files/scripts/service_mgmt.sh
Fix https://github.com/sonic-net/sonic-buildimage/issues/19331
Skip the namespace setting if the dev is DPU, because the DPU databases are only in the host namespace
Check there is no error log after fast-reboot
```
admin@vlab-01:~$ sudo cat /var/log/syslog  | grep -i asicdpu
```
> [Fixbug][fast-reboot] [ErrLog] Fix database.sh error log for dpu database

- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_dynamic.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/hwsku.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/media_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/optics_si_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/pg_profile_lookup.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/port_config.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/qos.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/sai.profile
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/sai_4700_32x400g.xml
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_dynamic.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/hwsku.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/media_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/optics_si_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/pg_profile_lookup.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/port_config.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/qos.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/sai.profile
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/sai_4700_64x200g.xml
A new SKUs for MSN4700 Platform: **Mellanox-SN4700-O32** and **Mellanox-SN4700-V64**
Requirements for **Mellanox-SN4700-O32:**
- 8 x 400Gbps uplink to T2 switch (O13 to O20)
- 24 x 400Gbps downlinks to T0 switch (O1-O12, O21-O32)
- Breakout mode No breakout mode. All ports working in 400Gb mode. .
- FEC mode: RS
- Type of transceiver: 400Gb Optical.
- warm boot should be supported “No for T1 role”
- VxLAN source port range set N/A
- Static Policy Based Hashing supported N/A
- Cable length “T0-T1 40m default, 300m max; T1-T2 2000m”
- Tradition buffer model is must “Yes”
- Shared headroom should be supported “Yes”
- Over-subscription ratio: “2”.
Requirements for **Mellanox-SN4700-V64**
- 16 x 200Gbps uplink to T1 switch (V-25&V26 to V-39&40)
- 48 x 200Gbps downlinks to servers (Left panel …
>  [Mellanox]Adding SKU Mellanox-SN4700-O32 and Mellanox-SN4700-V64

- platform/marvell-arm64/sai.mk
- platform/marvell/sai.mk
Add support in SAI debian for
PHY Host side serdes config
> [Marvell] Update SAI 3_0_3 deb for amd64 and arm64

- dockers/docker-ptf/Dockerfile.j2
Newer versions of sflowtool require autoconf 2.71, which is not available in Buster.
For the py3-only version of the PTF container, this is currently based on Bullseye, which should be fine.
This fixes the failure seen in the [upgrade pipeline](https://dev.azure.com/mssonic/build/_build/results?buildId=611739&view=logs&j=cef3d8a9-152e-5193-620b-567dc18af272&t=cf595088-5c84-5cf1-9d7e-03331f31d795).
- Microsoft ADO **(number only)**: 28964264
> Pin version of sflowtool used for the mixed PTF container

- device/dell/x86_64-dellemc_z9432f_c3758-r0/DellEMC-Z9432f-O32/td4-z9432f-32x400G.config.yml
DellEMC **Z9432F** platform onboarding.
Config changes with respect to Z9432F SAI bring up. 
Also changes from swss is required for complete bring up of Z9432F platform(TD4) will be followed thru (https://github.com/sonic-net/sonic-swss/issues/3244)
The following error message is not seen..
sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:brcm_sai_create_switch:3204 setting inter-frame gap failed with error Feature unavailable (0xfffffff0).
> DellEMC: Z9432F platform TD4 config changes

- src/dash-sai/Makefile
Get the following error due to switch_health_dta size changing
```
ASSERT TRUE FAILED(5085): sizeof(sai_switch_health_data_t) == (SAI_SWITCH_HEALTH_DATA_T_SIZE): wrong size of sai_switch_health_data_t, expected 16, got 4
```
- Microsoft ADO **(number only)**: 29062472
This PR is just an adhoc fix by disabling saimetadatatest. We should fix the scripts under OCP/SAI/meta
Check Azp
> [Adhoc fix]: Bypass saimetadatatest for dash sai

- azure-pipelines.yml
Currently we are adding more control plane and data plane test to PR test in master branch, and we added onboarding test job for piloting. When we are working on this goal, 202405 branch was created with onboarding test job, but it's not needed.
Remove onboarding PR test job in 202405 branch
Verify in PR test
> [202405] Remove onboarding PR test job

- src/sonic-py-common/sonic_py_common/syslogger.py
- src/sonic-py-common/tests/test_syslogger.py
SysLogger does not support NOTICE level log. The PR is to support it.
Add a new log level NOTICE to python logging package.
Manual test
```
Jun  3 03:09:44.353536 sonic NOTICE test[364076]: This is a notice
```
> Support notice level log

- dockers/docker-platform-monitor/Dockerfile.j2
After upgrading from bullseye to bookworm, pmon container no longer default installs tool xxd. The tool is used in mellanox simx platforms. The PR is to install xxd tool in the docker build file.
Install xxd in platform monitor docker file.
Manual test
> Install tool xxd to platform monitor container

- files/image_config/interfaces/interfaces-config.sh
- files/image_config/resolv-config/update-containers
The `resolvconfig` service updates the DNS configuration in the host OS and each running Docker container when a configuration change is detected. The DNS configuration update during the shutdown of the management interface is redundant, as the management interface is going down temporarily and, when it is back online, the DNS configuration will remain the same. The update of the DNS configuration adds a couple of seconds (depending on the CPU) to the interface-config service restart time when the management interface uses a dynamic IP address. This can affect the fast boot. To optimize the flow and execute the service restart faster, the update should be skipped.
Do not run DNS configuration update during the shutdown of the management interface. …
> [Static DNS] Optimize DNS configuration update during interface-config service restart

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C10/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- src/sonic-config-engine/tests/data/j2_template/config.bcm.j2
- src/sonic-config-engine/tests/sample_output/py3/arista7260-t1.config.bcm
Reverts sonic-net/sonic-buildimage#16097
The change has to be reverted as warm-reboot is broken.
MSFT ADO: 27996281
> Revert "Always set sai_tunnel_support on Arista-7260cx3"

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C10/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- src/sonic-config-engine/tests/data/j2_template/config.bcm.j2
- src/sonic-config-engine/tests/sample_output/py3/arista7260-t1.config.bcm
Reverts https://github.com/sonic-net/sonic-buildimage/pull/16097 from 202311 branch.
The change has to be reverted as warm-reboot is broken.
MSFT ADO: 27996281
> [202311] Revert "Always set sai_tunnel_support on Arista-7260cx3"

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C10/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- src/sonic-config-engine/tests/data/j2_template/config.bcm.j2
- src/sonic-config-engine/tests/sample_output/py3/arista7260-t1.config.bcm
Reverts https://github.com/sonic-net/sonic-buildimage/pull/16097 from 202405 branch
The change has to be reverted as warm-reboot is broken.
MSFT ADO: 27996281
> [202405] Revert "Always set sai_tunnel_support on Arista-7260cx3"

- dockers/docker-fpm-frr/Dockerfile.j2
- dockers/docker-fpm-frr/bgpd_wait_for_intf.sh.j2
- dockers/docker-fpm-frr/docker_init.sh
- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
With the following PR, make bgp start after swss.
https://github.com/sonic-net/sonic-buildimage/pull/12381
bgp started after the swss but still ahead of the interface init.
Jun 12 04:53:59.768546 bjw-can-7050qx-1 NOTICE root: Starting swss service...
...
Jun 12 04:54:12.725418 bjw-can-7050qx-1 NOTICE admin: Starting bgp service...
...
Jun 12 04:54:43.036682 bjw-can-7050qx-1 NOTICE swss#orchagent: :- updatePortOperStatus: Port Ethernet0 oper state set from down to up
Jun 12 04:54:43.191143 bjw-can-7050qx-1 NOTICE swss#orchagent: :- updatePortOperStatus: Port Ethernet4 oper state set from down to up
Jun 12 04:54:43.207343 bjw-can-7050qx-1 NOTICE swss#orchagent: :- updatePortOperStatus: Port Ethernet12 oper state set from down to up
26557087
Check the …
> check internface status before start bgp

- src/sonic-bgpcfgd/bgpcfgd/managers_bbr.py
- src/sonic-bgpcfgd/tests/test_bbr.py
There are two places which we can configure the BBR disabled/enabled, one is constants.yml, the other is by config_db. During run time, config_db win. But at the init stage, constants.yml win. This is a wrong logic, constants.yml only win when there is no such config in the config_db.
- Microsoft ADO **(number only)**: 28302790
Initialize BBR status from constants.yml only when config_db doesn't have BBR entry.
Build image and run the following:
```
admin@str2-7050cx3-acs-01:~$ redis-cli -n 4 hset "BGP_BBR|all" "status" "enabled"
(integer) 0
admin@str2-7050cx3-acs-01:~$ redis-cli -n 4 hget "BGP_BBR|all" "status"
"enabled"
admin@str2-7050cx3-acs-01:~$ vtysh -c 'show run' | grep 'allowas'
neighbor PEER_V4 allowas-in 1
neighbor PEER_V6 allowas-in 1
admin@str2-7050cx3-acs-01:~$ sudo config …
```
> Prioritize configuration from config_db over constants.yml during BBR status initialization

- rules/phy-credo.mk
PR https://github.com/sonic-net/sonic-buildimage/pull/19891 is separated to
https://github.com/sonic-net/sonic-buildimage/pull/19854 and current PR
it's needed for Arista CW2 linecard for SAI11. 
There is system side mechanism in phy-credo.py to work around the links down issue on CW2 linecard.
This PR is changing $(PHY_CREDO)_URL to point to phy-credo_1.0_amd64.deb that is already merged with the fix in https://github.com/aristanetworks/sonic-firmware/pull/2
Verified links are all up with credo debian update, without this change, 1 portchannel is down on Arista CL2 LC.
take this change locally and rebuilt the images, with this change, links are up on all LCs.
> [SAI 11] [Arista] Update phy-credo.mk

- files/scripts/swss.sh
on Master branch, dhcp_relay is not supported in VOQ chassis. It is disabled in the FEATURE table. But based on the dependency, swss.sh always call "systemctl start" it although it's service file has been masked/disabled. The following error is logged in syslog which causes the logAnalyze failed on some of the OC tests.  Fix issue https://github.com/sonic-net/sonic-buildimage/issues/18822
Added code to swss.sh to check if service is disabled or not.  If it is disabled, do not start the service although it is in the DPENDENT_LIST.  This avoids the ERROR log shown up in the syslog file
1)  Reboot the system or execut the config reload.  The following error messages should not be seen in the syslog file
```
Apr 27 23:15:14.472425 ixre-egl-board7 ERR …
```
> [voq][chassis][dhcp_relay] swss.sh try to start the dhcp_relay service although it is masked

- platform/mellanox/cmis_host_mgmt/cmis_host_mgmt.py
Fixed the name that the script looks for when checking sai_*.xml
Instead of searching with a general regex, the name of sai*.xml is taken from a variable in sai.profile.
> [Mellanox] Fixed sai xml name format bug

- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
- src/sonic-bgpcfgd/bgpcfgd/managers_device_global.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/19379
- Microsoft ADO **(number only)**: 28691372
Changed the lookup from switch_type (which is specific to chassis) to type (which holds the role for all pizzabox and chassis)
sudo idf_isolation <> commands run on chassis shoud add route-maps.
> Fixed switch role check for IDF isolation configuration

- dockers/docker-fpm-frr/frr/zebra/zebra.interfaces.conf.j2
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/zebra.conf
- src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-vni-zebra.conf
- src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-zebra.conf
- src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-vni-zebra.conf
- src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-zebra.conf
- src/sonic-config-engine/tests/sample_output/t2-chassis-fe-pc-zebra.conf
The 'ip nht resolve-via-default' is configured in vrf config by mistake instead of the global setting when vrf is configured causing the bgpl cannot to be established.
- Microsoft ADO **(number only)**: 28726407
Add the missing 'exit' line in FRR zebra.interfaces.conf.j2 file to exit vrf config block and ensure the 'ip nht resolve-via-default' is configured in the global setting.
> [FRR template]Add missing exit to avoid config nht via default route in vrf

- device/arista/x86_64-arista_7060dx5_32/Arista-7060DX5-32-200Gx48-100Gx32/media_settings.json
- device/arista/x86_64-arista_7060dx5_32/Arista-7060DX5-32-25Gx96-100Gx8-200Gx8/media_settings.json
- device/arista/x86_64-arista_7060dx5_32/Arista-7060DX5-32-25Gx96-100Gx8-200Gx8/port_config.ini
- device/arista/x86_64-arista_7060dx5_32/Arista-7060DX5-32/media_settings.json
We have a request to add these desired subports and media_settings.
Added subport values for a previous hwsku's port_config.ini.
Added tuning values for previous hwskus.
Boot the switch using the hwskus. I also checked output of sonic-cfggen -k
Added tuning and suport values for 7060dx5 HwSkus
> 7060dx5 add tuning and subport values for HwSkus

- dockers/docker-ptf/Dockerfile.j2
Backport of #19827.
---------
Newer versions of sflowtool require autoconf 2.71, which is not available in Buster.
- Microsoft ADO **(number only)**: 28964264
> [202311] Pin version of sflowtool used for the mixed PTF container

- files/scripts/arp_update
202311 cherry-pick for https://github.com/sonic-net/sonic-buildimage/pull/19219
> [202311][arp_update]: Use parent script PID for logger calls

- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_dynamic.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/hwsku.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/media_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/optics_si_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/pg_profile_lookup.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/port_config.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/qos.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/sai.profile
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/sai_4700_32x400g.xml
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_defaults_objects.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/buffers_dynamic.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/hwsku.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/media_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/optics_si_settings.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/pg_profile_lookup.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/pmon_daemon_control.json
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/port_config.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/qos.json.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/sai.profile
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V64/sai_4700_64x200g.xml
**Additional changes for 202311**
On master branch, pg_profile_lookup.ini was pointed to pg_profile_lookup.ini from SN4280 as a symlink
But SN4280 wasn't merged to 202311
Need to use files instead of links
A new SKUs for MSN4700 Platform: **Mellanox-SN4700-O32** and **Mellanox-SN4700-V64**
Requirements for Mellanox-SN4700-O32:
- 8 x 400Gbps uplink to T2 switch (O13 to O20)
- 24 x 400Gbps downlinks to T0 switch (O1-O12, O21-O32)
- Breakout mode No breakout mode. All ports working in 400Gb mode. .
- FEC mode: RS
- Type of transceiver: 400Gb Optical.
- warm boot should be supported “No for T1 role”
- VxLAN source port range set N/A
- Static Policy Based Hashing supported N/A
- Cable length “T0-T1 40m default, 300m max; T1-T2 2000m”
- Tradition buffer model is must “Yes”
- Shared headroom …
> [Mellanox][202311] Adding SKU Mellanox-SN4700-O32 and Mellanox-SN4700-V64

- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O32/qos.json.j2
- update buffers and align QoS to add support for DSCP remapping (for Dual-Tor on t1) for Mellanox-SN4700-O32
> [Mellanox] update buffers and align QoS to add support for DSCP remapping (for Dual-Tor on t1) for Mellanox-SN4700-O32

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/pmon_daemon_control.json
Executes "docker exec -it snmp snmpwalk -v2c -c 127.0.0.1 1.3.6.1.4.1.9.9.117.1.1.2.1"  Nokia LC - Nokia_IXR7250E_36x400G will get the following error in the syslog:
Jul 30 02:03:21.836386 ixre-egl-board9 ERR snmp#snmp-subagent [sonic_ax_impl] ERROR: PowerStatusHandler._get_psu_index() caught an unexpected exception during _get_num_psus()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoEntityFruControlMIB.py", line 101, in _get_psu_index#012    num_psus = self._get_num_psus()#012  File "/usr/local/lib/python3.9/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoEntityFruControlMIB.py", line 66, in _get_num_psus#012    return int(num_psus[0])#012ValueError: invalid literal for int() with base 10: ''
This PR will …
> [Nokia][snmpwalk] Fix the snmpwalk cefcFruPowerStatusTable on Nokia LC platform

- src/sonic-frr/patch/0053-bgpd-Set-md5-TCP-socket-option-for-outgoing-connections-on-listener.patch
- src/sonic-frr/patch/series
Fix #19978 
Porting bug fix from https://github.com/FRRouting/frr/pull/13084
Verify BGP sessions in VRF with MD5 password works as expected.
> [BGP] Fix TCP MD5 authentication problem in VRF

- platform/marvell-armhf/sai.mk
Fixed PTF issue related to   [COPP]: test_policer for UDLD
Addressed the issue in SAI 
Re-run the COPP PTF test cases
> [Marvell] Update SAI debian version to 1.13.3-2

- src/sonic-eventd/src/eventd.cpp
- src/sonic-eventd/tests/eventd_ut.cpp
Dropping control character (message sent when XSUB connects to XPUB as part of ZMQ Proxy setup to notify that subscription has been made) in do capture has been flaky since control character is not guaranteed to be the first message sent if there are events (like event-down-ctr) being published to XSUB.
Scenarios
1) Control character is sent and is first message when starting capture service
`eventd#eventd#eventd: :- heartbeat_ctrl: Set heartbeat_ctrl pause=1`
`eventd#eventd#eventd: :- do_capture: Received subscription message when XSUB connects to XPUB`
2) Events like event-down ctr is sent before control character
`eventd#eventd#eventd: :- run: Dropping Message: 22 serialization::archive 18 17 sonic-events-host`
`eventd#eventd#eventd: :- run: Dropping Message: 22 serialization::archive …
> Fix flaky capture service start

- platform/checkout/cisco-8000.ini
Cisco platform 202405.0.3 release
Cisco platform 202405.0.3 release
> Update cisco-8000.ini to 202405.0.3 release

- src/sonic-bgpcfgd/bgpcfgd/managers_rm.py
- src/sonic-bgpcfgd/tests/test_rm.py
This is a bug fix and this change should go into 202305 brranch and onwards.
Added Route map support for BGP profile FROM_SDN_APPLIANCE_ROUTES
With this change the following route map should be added if the BGP profile is added
```
route-map FROM_SDN_APPLIANCE_ROUTES_RM permit 100
set as-path prepend <Prepend value of FROM_SDN_SLB_DEPLOYMENT_ID>
set community <community id>
set origin incomplete
```
28896695
Added test to verify the rotue map creation.
NO yang changes required.
> [Bug Fix] Route map for BGP profile FROM_SDN_APPLIANCE_ROUTES

- src/isc-dhcp/patch/0017-Register-IO-obj-before-create-fd-watch.patch
- src/isc-dhcp/patch/series
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-buildimage/pull/20021
In the scenario dhcrelay startup with DHCP packets come, there is possibility that dhcrelay try to attach FD wather to I/O handler before I/O handler initiated, which cause dhcrelay wouldn't read any packets from FD. This PR is to fix that issue.
- Microsoft ADO **(number only)**: 29209311
1. Move initialization part to place before attach FD watcher
2. Add log when it fails to attach FD watcher
Build image and run tests
> [202311][isc-dhcp-relay] Add patch to init io obj before creating fd watch

- platform/mellanox/mlnx-fw-upgrade.j2
Extend `mlnx-fw-upgrade.j2` to support the upgrade of the DPU NIC FW
Add support for the new device to the script
Compile and install an image
> [Mellanox] Update mlnx-fw-upgrade.j2 to support BF3 DPU NIC FW.

- platform/checkout/cisco-8000.ini
Signed-off-by: anamehra@cisco.com
Cisco platform 202405.0.4 release
Cisco platform 202405.0.4 release
> Update cisco-8000.ini to 202405.0.4 release

- src/sonic-py-common/setup.py
Fix https://github.com/sonic-net/sonic-buildimage/issues/17246
```
root@sn2700:/home/admin# docker exec swss pip3 show natsort
Name: natsort
Version: 8.4.0
root@sn2700:/home/admin# pip3 show natsort
Name: natsort
Version: 8.4.0
root@sn2700:/home/admin# docker exec syncd pip3 show natsort
Name: natsort
Version: 8.4.0
```
> Use latest natsort package

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/sonic_platform/wait_sfp_ready_task.py
- platform/mellanox/mlnx-platform-api/tests/test_change_event.py
In dynamic module detection flow, sonic should wait module become ready.
In dynamic module detection flow, sonic should wait module become ready.
unit test
> [Mellanox] wait SFP ready when receive an insert event with module host management mode enabled

- src/isc-dhcp/patch/0017-Register-IO-obj-before-create-fd-watch.patch
- src/isc-dhcp/patch/series
In the scenario dhcrelay startup with DHCP packets come, there is possibility that dhcrelay try to attach FD wather to I/O handler before I/O handler initiated, which cause dhcrelay wouldn't read any packets from FD. This PR is to fix that issue.
- Microsoft ADO **(number only)**: 29209311
1. Move initialization part to place before attach FD watcher
2. Add log when it fails to attach FD watcher
Build image and run tests
> [isc-dhcp-relay] Add patch to init io obj before creating fd watch

- src/isc-dhcp/patch/0017-Register-IO-obj-before-create-fd-watch.patch
- src/isc-dhcp/patch/series
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-buildimage/pull/20021
In the scenario dhcrelay startup with DHCP packets come, there is possibility that dhcrelay try to attach FD wather to I/O handler before I/O handler initiated, which cause dhcrelay wouldn't read any packets from FD. This PR is to fix that issue.
- Microsoft ADO **(number only)**: 29209311
1. Move initialization part to place before attach FD watcher
2. Add log when it fails to attach FD watcher
Build image and run tests
> [202305][isc-dhcp-relay] Add patch to init io obj before creating fd watch

- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/pg_profile_lookup.ini
- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/qos.json.j2
- update buffers and align QoS to add support for DSCP remapping (for Dual-Tor on t1) for Mellanox-SN4700-O8C48
- use latest pg_profile_lookup.ini file
run related QoS/DSCP remapping test
> [Mellanox] update buffers and align QoS to add support for DSCP remapping (for Dual-Tor on t1) for Mellanox-SN4700-O8C48

- device/mellanox/x86_64-nvidia_sn4280-r0/installer.conf
To avoid the following error message:
`ima: No suitable TPM algorithm for boot aggregate`
Set the IMA hash algorithm to sha384 so the IMA can find the TPM algorithm
Manual test
> [Mellanox] set default IMA algorithm to sha384 on SN4280

- src/sonic-config-engine/tests/test_cfggen_from_yang.py
- src/sonic-config-engine/tests/test_yang_data.json
- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/fabric_monitor_data.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/fabric_port.json
- src/sonic-yang-models/yang-models/sonic-fabric-monitor.yang
- src/sonic-yang-models/yang-models/sonic-fabric-port.yang
The new added attributes related fabric link monitoring are missing YANG model. Adding them in this change. 
For fabric monitor table: 
> monCapacityThreshWarn
> monState
For fabric port:
> forceUnisolateStatus 
> YANG model for enabling fabric monitor attribute

- device/mellanox/x86_64-nvidia_sn4280-r0/platform.json
The presence of the DPUs definition in the `platform.json` file enables Smart Switch flows in SONiC, including the start of the per-DPU database, midplane bridge creation, etc. Since in 202405 release SONiC has run the DPUs in the "dark mode," and the DPUS are always in the power-down state, this is unnecessary. To disable the Smart Switch flows the DPUs definition should be excluded from the `platform.json`.
Exclude the DPUs definition from `platform.json` file.
Compile and run the. Verify that the per-DPU database containers are not started. Verify that the midplane bridge is not created.
> [Mellanox][202405] Remove DPU from SN4280 platform.json file

- files/build_templates/sonic_debian_extension.j2
Pycairo 1.27.0 was recently released, which requires cmake for the build. Pygobject depends on this, and the default of isolated builds means that any already-installed version of pycairo isn't used.
Fix this by explicitly installing pycairo 1.26.0 and disabling build isolation.
> [202311] Fix pygobject installation for armhf

- files/image_config/ntp/ntp.conf.j2
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-buildimage/pull/20205
NTP configuration wouldn't check existence of configured interface in config_db if it is `eth0`. This PR is to add this check
- Microsoft ADO **(number only)**: 29385974
Add interface existence check in config_db for ntp configuration
Generate NTP configuration and run ntp test in sonic-mgmt with new template
```
generic_config_updater/test_ntp.py::test_ntp_server_tc1_suite PASSED                                                                                                                                    [100%]
```
```
ntp/test_ntp.py::test_ntp_long_jump_enabled[False] PASSED …
```
> [202311][ntp] Add interface existence check for eth0 in ntp configuration

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/buffers_defaults_t2.j2
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cqm2-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-c36-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-d36-lc.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x100g.json
- src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x400g.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cqm2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-c36-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-d36-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x100g.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x400g.json
This change is to restrict lossy queue buffer usage in case of congestion state.
- Microsoft ADO **(29315559)**:
Updated alpha from 0 to -4 (400g) & -5 (100g) port speed. This configuration is applied on system port and will be using HWSKU port speed settings.
It is verified using sonic-mgmt tests and running ok.
> [Chassis] Update lossy profile to restrict buffer usage in congestion state

- files/image_config/ntp/ntp.conf.j2
NTP configuration wouldn't check existence of configured interface in config_db if it is `eth0`. This PR is to add this check
- Microsoft ADO **(number only)**: 29385974
Add interface existence check in config_db for ntp configuration
Generate NTP configuration and run ntp test in sonic-mgmt with new template
```
generic_config_updater/test_ntp.py::test_ntp_server_tc1_suite PASSED                                                                                                                                    [100%]
```
```
ntp/test_ntp.py::test_ntp_long_jump_enabled[False] PASSED                                                                                                                                               [ 16%]
ntp/test_ntp.py::test_ntp_long_jump_disabled[False] XFAIL …
```
> [ntp] Add interface existence check for eth0 in ntp configuration

- dockers/docker-orchagent/ipinip.json.j2
- src/sonic-config-engine/tests/sample_output/py2/ipinip_subnet_decap_enable.json
- src/sonic-config-engine/tests/sample_output/py3/ipinip_subnet_decap_enable.json
If subnet decap is enabled on T0, the subnet decap term should be created for VLAN prefixes.
- Microsoft ADO **(number only)**: 28316828
For VLAN prefixes, if subnet decap is enabled, created MP2MP decap terms with subnet type `vlan` and under the subnet decap tunnels.
> [subnet decap] Fix VLAN prefix decap term 

- platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/component.py
As described in https://github.com/sonic-net/sonic-buildimage/issues/16878, every `show` command on the N3248TE-ON results in an error about `dmidecode` not being found. This is because that command is called in the `get_bios_version` function of `component.py`, which is used in a lot of places (many which should not require privileged access).
The error message prior to this change:
```
jdt@sonic:~$ show system-health
failed to import plugin show.plugins.cisco-8000: [Errno 2] No such file or directory: 'dmidecode'
Usage: show system-health [OPTIONS] COMMAND [ARGS]...
Show system-health information
```
On this platform, at least, the BIOS version can be obtained from `/sys/class/dmi/id/bios_version`without requiring `root` privileges. I adjusted …
> eliminate dmidecode in component.py because it requires root privileges

- files/image_config/ntp/ntp.conf.j2
Switch cannot connect to NTP server with Loopback ipv6 in Loopback ipv6 only scenario.
- Microsoft ADO **(number only)**: 29415265
Add support for ntp to listen ipv4/ipv6 address depends on server config
Run ntp test with new template
```
generic_config_updater/test_ntp.py::test_ntp_server_tc1_suite PASSED                                                                                                                                                                                                                                                          [100%]
```
```
ntp/test_ntp.py::test_ntp_long_jump_enabled[False] PASSED …
```
> [ntp] Add support for ntp to listen ipv4/ipv6 address depends on server config

- platform/marvell-armhf/sai.mk
Reverts sonic-net/sonic-buildimage#19966 due to sonic-net/sonic-buildimage#20255
> Revert "[Marvell] Update SAI debian version to 1.13.3-2"

- device/mellanox/x86_64-nvidia_sn4280-r0/services.conf
- files/build_templates/sonic_debian_extension.j2
- platform/mellanox/smartswitch/dpuctl/dpu.conf
- platform/mellanox/smartswitch/dpuctl/dpuctl.service
- platform/mellanox/smartswitch/dpuctl/dpuctl.sh
Smart Switch Dark Mode allows disabling of all DPUs, removing any influence the DPU has on the system.
Add the `dpuctl.service` that runs on system start and shuts down DPUs if needed.
Compile the image and run it on the Nvidia Smart Switch. Verify that all DPUs are down after the system starts.
> [Mellanox] Add dpuctl services to support "dark mode".

- device/mellanox/x86_64-nvidia_sn4280-r0/pcie.yaml
- device/mellanox/x86_64-nvidia_sn4280-r0/sensors.conf
- platform/mellanox/rshim/files/rshim.sh
The pcie ids of some specific devices is updated for the SN4280 device. Due to this there are some changes to be updated in the platform specific code for mellanox
`sensors.conf` - This change is due to pci id change for a sensor
`rshim..sh` - This change is due to the pci id changes for the dpus, which have to be aligned to the platform
`pcie.yaml` - This change is due to pci id change for the devices
> [Mellanox] SN4280 Platform pcie changes

- dockers/docker-platform-monitor/Dockerfile.j2
This module is required in the pmon container for Storage Monitoring Daemon (stormond) to instantiate objects of type (UsbUtil)[https://github.com/sonic-net/sonic-platform-common/pull/493].
- Microsoft ADO **(number only)**: 29203991
Added config to pmon Dockerfile.j2 to install blkinfo
On an image containing this change, verify following output:
```
root@str2-7050qx-32s-acs-03:/# pip3 list | grep -i blkinfo
blkinfo                       0.2.0
```
Added blkinfo module to PMON container
> Adds blkinfo for use by stormond to instantiate UsbUtil object

- files/image_config/monit/memory_checker
https://github.com/sonic-net/sonic-buildimage/pull/19179 removed call to publish_events when memory usage container exceeds threshold, causing test_events to fail.
- Microsoft ADO **(number only)**: 28728116
Add back call to publish_events
Manual test
> Add back publish events to memory_checker

- device/arista/x86_64-arista_7800r3a_36d2_lc/media_settings.json
Need to fix the tuning values in the media_settings.json file because today, the parser of media_settings.json expects unsigned int32 values, instead of signed int32 values. 
N/A
N/A
Without this fix, the TX FIR tuning may fail, displaying an error message like, 'parsePortSerdes: Failed to parse field(pre1): Invalid argument: '-0x8''
Change tuning value from signed int32 to unsigned int32
N/A
N/A
> Fix tuning values in the media_settings.json of 7800r3a_36d2_lc

- platform/mellanox/asic_table.j2
Update ASIC table template for shared headroom pool relevant information
Manual test
Regression test https://github.com/sonic-net/sonic-mgmt/pull/14479
> [Mellanox] Update ASIC table template for shared headroom pool relevant information

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/chassis_data/voq_chassis_data/system_ports.json
The system_port_id generation was based on the loop below
for interface in **interface_metadata.findall**(str(QName(ns1, "DeviceInterfaceMetadata"))):
"DeviceInterfaceMetadata" defined in the minigraph in DeviceInfo section, which is per interface and in this loop we increment the system_port_id++ so that each interface will have a unique ID. 
The for loop was based on interface_metadata list extracted by findall() API matching tag **"DeviceInterfaceMetadata"** [lxml.etree._Element](https://lxml.de/api/lxml.etree._Element-class.html). findall() doesn't guarantee document order. Hence the interface list and the corresponding system_port ids generated - has a possibility of not matching across config_db's in different linecards of a chassis.
When SYSTEM_PORT table entries hve mismatch …
> Sort the system port ID generation in minigraph parser for Chassis

- files/scripts/syncd.sh
- platform/mellanox/mlnx-fw-upgrade.j2
Fixing retry logic when MST device is discovered. The current implementation only fetches the name of the device but doesn't verify if the device is accessible which can be confirmed by querying the device and ensuring the command passes.
Added a query command with device as parameter and ensured it passes.
Running upgrade tests.
> [Mellanox] Fix retry logic on discovery of MST device

- device/ufispace/x86_64-ufispace_s6301_56st-r0/pddf/pddf-device.json
- device/ufispace/x86_64-ufispace_s7801_54xs-r0/pddf/pddf-device.json
- device/ufispace/x86_64-ufispace_s8901_54xc-r0/pddf/pddf-device.json
- device/ufispace/x86_64-ufispace_s9110_32x-r0/pddf/pddf-device-beta.json
- device/ufispace/x86_64-ufispace_s9110_32x-r0/pddf/pddf-device-pvt.json
Update the transceiver control virtual address to avoid an address conflict with SPD
* s6301-56st
* s7801-54xs
* s8901-54xc
* s9110-32x
Update the PDDF config files.
Run the PDDF commands and show commands to check the sysfs and transceiver status.
[s6301-56st.txt](https://github.com/user-attachments/files/16450946/s6301-56st.txt)
[s7801-54xs.txt](https://github.com/user-attachments/files/16450947/s7801-54xs.txt)
[s8901-54xc.txt](https://github.com/user-attachments/files/16450944/s8901-54xc.txt)
[s9110-32x.txt](https://github.com/user-attachments/files/16450945/s9110-32x.txt)
> [Ufispace] Update the transceiver control virtual address to avoid an address conflict with SPD

- dockers/docker-orchagent/orchagent.sh
Bind ZMQ to midplane mgmt interface on SmartSwitch DPU.
SmartSwitch DPU IP address may change after push config: https://github.com/sonic-net/sonic-buildimage/issues/20295
- Microsoft ADO: 29628977
Bind ZMQ to midplane mgmt interface on SmartSwitch DPU.
Pass all UT.
- [] 
Bind ZMQ to midplane mgmt interface on SmartSwitch DPU.
> Bind ZMQ to midplane mgmt interface on SmartSwitch DPU

- src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
In the sonic chassis the port table on the host does not lanes. Add conditions in the lab chassis to make lanes not mandatory for chassis devices
- Microsoft ADO **29108681**:
Add the check in `sonic-port.yang` to make lanes are mandatory in the host config_db only for non-chassis devices.
UT.
> [chassis] add condition is yang model to make lanes not mandatory for chassis

- device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/sai.profile
- dockers/docker-orchagent/orchagent.sh
Migrating Nokia-M0 armhf platform from SONiC 202311 to master and 202405 branch, resulted in syncd create_switch timeout.
It is analyzed to see that SAI SDK code remains the same and time consume by SAI SDK during init when some(snmp mgmt-framework lldp gnmi dhcp_relay radv teamd pmon bgp) of the docker in sonic are disabled is same as running on 202311(with same environment).
Some of the other observations are:
* Switch create time varies from 50sec to 85 sec randomly depending on CPU load.
* Running bullseye based 5.10 sonic kernel yielded same result on latest master.
* Running docker ps -a in 202405 shows all dockers attempting to start, while in 202311 it delays most dockers.
* No single docker seems to have a significant impact.
Added changes to …
> [Marvell][Nokia-M0] Set custom create switch timeout

- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/eeprom.py
CLI crashes without `sudo` permission on Dell 6000 platform
```
sonic@sonic-dev:~$ show interfaces status
File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_eeprom/eeprom_base.py", line 244, in read_eeprom_bytes
F = self.open_eeprom()
File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_eeprom/eeprom_base.py", line 232, in open_eeprom
return io.open(eeprom_file, "rb")
PermissionError: [Errno 13] Permission denied: '/sys/bus/i2c/devices/i2c-10/10-0053/eeprom'
During handling of the above exception, another exception occurred:
File "/usr/local/bin/intfutil", line 836, in <module>
main()
File "/usr/local/bin/intfutil", line 819, in main
interface_stat.display_intf_status()
File …
```
> [S6000] Fix 'show interface status' CLI needs sudo permission

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
Added Support for DHCP rate limit
Modifed sonic-port.yang by adding a new leaf for dhcp rate limit
Updated Config DB and YANG model
> YANG Model for DHCP DoS Mitigation

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- For 40G optics there is SAI handling of T0 facing ports to be set with SR4 type and unreliable los set for a fixed set of ports. For this property to be invoked the requirement is set
phy_unlos_msft=1 in config.bcm.
This change is to meet the requirement and once this property is set, the los/interface type settings is applied by SAI on the required ports.
Why I did it
- For  Arista-7260CX3-Q44 T0, 40G ports RX_ERR minimalization during connected device reboot
can be achieved by turning on Unreliable LOS and SR4 media_type for all ports which are connected to T1/T0.
The property phy_unlos_msft=1 is to exclusively enable this property.
29194161
> [Arista] Update config.bcm of Arista-7260CX3-Q44 for handling 40g optics with  unreliable los settings

- src/sonic-nettools/.gitignore
- src/sonic-nettools/Cargo.lock
- src/sonic-nettools/Makefile
- src/sonic-nettools/wol/Cargo.toml
- src/sonic-nettools/wol/src/main.rs
- src/sonic-nettools/wol/src/socket.rs
- src/sonic-nettools/wol/src/wol.rs
Although the magic pattern is fixed, we can send the magic pattern in UDP payload to leverage the benefits of UDP.
Add code to support sending payload in udp and provide CLI parameters for it.
Unit test and run tests in sonic-mgmt
> [wol]  Extend wol to support sending magic pattern in udp payload

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Nvidia platform API is using SDK API to control module low power mode. This PR is aimed to migrate those logic to 
SDK provided sysfs nodes.
Use SDK provided sysfs nodes for LPM control.
Manual test passed
sonic-mgmt regression test passed
> [Mellanox] use SDK sysfs for module low power mode control

- dockers/docker-orchagent/orchagent.sh
Correcting the platform asic name check done in PR https://github.com/sonic-net/sonic-buildimage/pull/20347 to be "marvell" instead of "marvell-armhf".
> [Orchagent][Marvell] Correct the platform asic name

- platform/mellanox/mlnx-fw-upgrade.j2
Fix the issue with ASIC detection on the SN4280 platform.
The root cause of the issue is in the PCI subsystem race condition. When the Dark Mode is enabled on the system start we do the following actions in parallel:
1.	The dpuctl service starts and powers down the DPUs which causes the DPU PCI devices removal.
2.	At the same time the syncd service starts. It launches mlnx-fw-upgrade.sh script which queries the available ASIC devices from the PCI subsystem using the lspci command. 
There is a small period after the removal of the DPU PCI device when the PCI subsystem in Linux remains inconsistent and lspci command might return an error upon execution. This might cause an error in mlnx-fw-upgrade.sh which interrupts the syncd container start.
Add a retry …
> [Mellanox] Fix the issue with ASIC detection on the SN4280 platform

- device/mellanox/x86_64-nvidia_sn4280-r0/pcie.yaml
Aligning the `SN4280` Platform, since there is only one XGMAC 10GbE Controller present in the platform, the other device is removed from the `pcie.yaml` file 
Generated pcie data using `pcieutil generate` and updated the repository
> [Mellanox] Platform specific pcie changes for SN4280

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
On Mellanox platforms, it was decided that a good way to simulate an I2C stuck scenario would be to have the files representing the module's EEPROM remain empty. When these files are empty, module initialization will not complete because the read_eeprom() function gets stuck in an infinite loop (```while num_bytes > 0:``` will never evaluate to False as the decrement operation ```num_bytes -= read_length``` has no effect). This happens because 0 bytes are always read from the EEPROM when it is empty. This PR addresses this issue.
On Mellanox platforms only, I added a validation check to ensure that if an attempt to read from the EEPROM results in 0 bytes read, the _read_eeprom() function exits and returns None.
Simulate the empty EEPROM (can be done as …
> [Mellanox] Add functionality to handle empty EEPROM files

- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/eeprom.py
This was failing sonic-mgmt test [test_syseepromd](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/daemon/test_syseepromd.py) due to a setup error on account of null bytes being parsed from the S6000 eeprom.
This is due to differences in the way sonic-db-cli handles null values in the part number as parsed by the EEPROM in the 202012 image vs 202205+ image versions:
**202305 image**
```
admin@dell-s6000-device:~$ sudo sonic-installer list
Current: SONiC-OS-20230531.38
Next: SONiC-OS-20230531.38
Available:
SONiC-OS-20230531.38
admin@dell-s6000-device:~$
admin@dell-s6000-device:~$ redis-cli -n 6 HGETALL "EEPROM_INFO|Part Number"
1) "Value"
2) "00NX1V\x00\x00\x00\x00"
admin@dell-s6000-device:~$ sonic-db-cli STATE_DB  HGETALL "EEPROM_INFO|Part Number"
{'Value': …
```
> Strip null bytes from parsed eeprom data before writing to db on S6000 platform

- azure-pipelines.yml
As all dualtor test scripts are stable, we have moved them to dualtor PR checker. We don't need onboarding dualtor PR checker anymore. So in this PR, we comment out the onboarding dualtor PR checker. 
> Comment out onboarding dualtor PR checker. 

- src/sonic-dhcp-utilities/dhcp_utilities/common/utils.py
- src/sonic-dhcp-utilities/dhcp_utilities/dhcprelayd/dhcprelayd.py
- src/sonic-dhcp-utilities/tests/common_utils.py
- src/sonic-dhcp-utilities/tests/test_dhcprelayd.py
- src/sonic-dhcp-utilities/tests/test_utils.py
In master and 202405 branch, dhcp_relay container was updated to Bookworm, hence isc-dhcp-relay was updated from 4.4.1 to 4.4.3. In this version, isc-dhcp-relay would create child process to proceed when there is network io, hence dhcprelayd would get duplicated dhcrelay process when checking
```
2024 Oct  2 03:28:58.972742 sonic ERR dhcp_relay#dhcprelayd: Running processes is not as expected! Runnning: [['/usr/sbin/dhcrelay', '-d', '-m', 'discard', '-a', '%h:%p', '%P', '--name-alias-map-file', '/tmp/port-name-alias-map.txt', '-id', 'Vlan1000', '-iu', 'PortChannel101', '-iu', 'PortChannel102', '-iu', 'PortChannel103', '-iu', 'PortChannel104', '192.0.0.1', '192.0.0.2', '192.0.0.3', '192.0.0.4', '192.0.0.5', '192.0.0.6', '192.0.0.7', '192.0.0.8', '192.0.0.9', '192.0.0.10', '192.0.0.11', …
```
> [dhcp_relay] Only check parent dhcrelay process in dhcprelayd

- .azure-pipelines/azure-pipelines-image-template.yml
- .azure-pipelines/official-build.yml
- azure-pipelines.yml
Changes to `docker-ptf` Dockerfile don't get automatically published to the docker registry accessed by the community. This PR addresses the issue.
- Microsoft ADO **(number only)**: 29869315
Modified the `postSteps` phase in `azure-pipelines-image-template.yml` to invoke the script to push `docker-ptf` image to the docker registry. The push is applicable to build branches (`master`, `202305`, `202311` etc.) and not feature branches.
TBD
Not applicable.
[docker-ptf]: CI change to publish docker-ptf image to the public/community docker registry
* Change pipeline YAML to publish docker-ptf image to docker registry
* Publish only docker-ptf image for main or release branches only and not feature branch
Not applicable
> [docker-ptf]: CI change to publish docker-ptf image to the docker registry

- src/sonic-frr/dplane_fpm_sonic/dplane_fpm_sonic.c
- src/sonic-frr/patch/bgpd-lib-Include-SID-structure-in-seg6local-nexthop.patch
- src/sonic-frr/patch/series
This PR fixes the SRv6 SID uninstall introduced in this PR: https://github.com/sonic-net/sonic-buildimage/pull/18715
This fix has been already merged in the FRR mainline: https://github.com/FRRouting/frr/pull/16835
> Fixing SRv6 SID uninstall

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
On Mellanox platforms, currently only CMIS active ports can be controlled by the SW, and all copper modules are controlled by FW.
We want to let Sonic control passive copper modules as well, for CMIS and SFF (sff8636 and sff8436).
I updated the module detection flow to tag CMIS and SFF passive modules as SW control.
Manual tests.
> [Mellanox] Module detection flow updates to support SW controlled ports for copper passive modules

- src/sonic-py-common/sonic_py_common/daemon_base.py
- src/sonic-py-common/sonic_py_common/syslogger.py
- src/sonic-py-common/tests/test_syslogger.py
HLD link: https://github.com/sonic-net/SONiC/pull/1522
SONiC provides two Python logger implementations: `sonic_py_common.logger.Logger` and `sonic_py_common.syslogger.SysLogger`. Both of them do not provide the ability to change log level at real time. Sometimes, in order to get more debug information, developer has to manually change the log level in code on a running switch and restart the Python daemon. This is not convenient.
SONiC also provides a C/C++ logger implementation in `sonic-platform-common.common.logger.cpp`. This C/C++ logger implementation is also a wrapper of Linux standard `syslog` which is widely used by swss/syncd. It provides the ability to set log level on fly by starting a thread to listen to CONFIG DB LOGGER table change. SONiC infrastructure also provides the …
> Enable runtime config log level

- platform/nvidia-bluefield/recipes/bluefield-soc.mk
- platform/nvidia-bluefield/recipes/dpu-sai.mk
- platform/nvidia-bluefield/recipes/fw.mk
- platform/nvidia-bluefield/recipes/sdk.mk
To include latest fixes and new functionality
* SDK_VERSION 24.7-RC4 -> 24.10-RC2
* FW_VERSION 32.41.1000 -> 32.42.1000
* SAI_VERSION SAIBuild0.0.32.0 -> SAIBuild0.0.36.0
* BFSOC_VERSION: 4.7.0 -> 4.9.0
Build an image and run tests from "sonic-mgmt".
> [Nvidia-bluefield] Update SAI to SAIBuild0.0.36.0, SDK/FW to v24.10-RC2/v32.42.1000, BFSoC to 4.9.0

- files/scripts/syncd.sh
- platform/mellanox/mlnx-fw-upgrade.j2
Manual cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/20389
Fixing retry logic when MST device is discovered. The current implementation only fetches the name of the device but doesn't verify if the device is accessible which can be confirmed by querying the device and ensuring the command passes.
Running upgrade tests.
Added a query command with device as parameter and ensured it passes.
> [202405][Mellanox] Fix retry logic on discovery of MST device

- platform/mellanox/sonic-bfb-installer.sh
The DPU reset after the image installation is required to boot the DPU with the new NIC FW
Trigger DPU reset with the `dpuctl` utility after the image isntallation
Build and install the image
> [Nvidia-bluefield] Extend BFB installer script to reset DPU after image installation

- src/scapy.patch/0004-Fix-fd-leak-in-worker-thread.patch
- src/scapy.patch/series
This PR is to add a patch to fix potential fd leak issue in `AsyncSniffer` in `scapy` python library.
There are two fd leak scenarios.
1. When starting worker thread `_run`, if an interface is down, an `OSError` is thrown, and the sockets that have been created will  be leaked as it never got a chance to be closed.
2. When stopping the worker thread, same error can happen when calling `close`. The sockets not closed will be leaked.
Test code:
```
from scapy.all import *
import time
sniffing_iface = ["PortChannel101", "PortChannel102", "PortChannel106", "PortChannel1024"]
sniffstring = "udp"
sniffer = None
def process_packet(packet):
print("Got a packet {}".format(len(packet)))
while True:
sniffer = AsyncSniffer(iface=sniffing_iface, filter=sniffstring, prn=process_packet, store=False) …
```
> Add a patch for scapy to fix fd leak issue in AsyncSniffer

- platform/mellanox/mlnx-fw-upgrade.j2
> [Mellanox] Fix the issue with ASIC detection on the SN4280 platform (#20397)

- device/nvidia-bluefield/arm64-nvda_bf-bf3comdpu/pmon_daemon_control.json
- platform/nvidia-bluefield/platform-api/sonic_platform/chassis.py
- platform/nvidia-bluefield/platform-api/tests/test_chassis.py
Implement the interface required to run DPU chassisd on the Nvidia Smart Switch.
Implement `get_dpu_id` API that deducts the DPU ID based on the midplane interface IP address.
Implement platform API
The implementation is covered by the UT.
> [Mellanox] Extend Nvidia Bluefield DPU chassis implementation

- dockers/docker-dhcp-server/cli-plugin-tests/mock_state_db.json
- dockers/docker-dhcp-server/cli-plugin-tests/pytest.ini
- dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py
- dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
In smart switch, there is an issue that Cli query dhcp lease got unknow interface due to dpu fdb hasn't present in STATE_DB FDB_TABLE. Issue: https://github.com/sonic-net/sonic-buildimage/issues/20155
- Microsoft ADO **(number only)**: 30001797
Query bridge fdb if there is no fdb record in STATE_DB
UT passed
> [smart_switch][dhcp_server] Fix query dhcp lease get unknown in smart switch by Cli

- platform/mellanox/docker-syncd-mlnx/Dockerfile.j2
Resolves: https://github.com/sonic-net/sonic-buildimage/issues/20419
* To clean up `syncd` environment
* N/A
* Removed python development packages from a `Dockerfile` template
* N/A
* N/A
```
'//||\\`
''``
```
> [Mellanox]: Clean up syncd Python development packages

- files/image_config/warmboot-finalizer/finalize-warmboot.sh
Set cpufreq.default_governor to *performance* for faster boot time. We observe consistent 1 sec improvement across several devices.
The change in finalize-warmboot.sh restores the default governor after fast or warm boot is finished.
**NOTE**: This will apply to upgrades starting from 202405 since this is set in shutdown path to avoid any extra scripts running at boot time. Upgrade from older versions/branches will require a runtime patch to fast-reboot and warm-reboot script.
After fast or warm boot is finished restore to default governor.
Run fast-reboot or warm-reboot. Check:
```
admin@sonic:~$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
performance
```
After boot is finalized check that it is reset back to default:
```
admin@sonic:~$ …
```
> [finalize-warmboot.sh] reset cpufreq governor to default

- dockers/docker-orchagent/orchagent.sh
- dockers/docker-sonic-gnmi/gnmi-native.sh
Add VRF parameter to orchagent and GNMI start script.
Orchagent failed bind to ZMQ when mgmt VRF enabled: https://github.com/sonic-net/sonic-buildimage/issues/19638
- Microsoft ADO: 29064735
Add VRF parameter to orchagent and GNMI start script when mgmt-vrf feature enabled.
Pass all UT.
- [] 
Add VRF parameter to orchagent and GNMI start script.
> Add VRF parameter to orchagent and GNMI start script.

- dockers/docker-macsec/cli-plugin-tests/test_config_macsec.py
- dockers/docker-macsec/cli/config/plugins/macsec.py
Trying to remove macsec from a port without it configured would lead to a crash/backtrace of the config command
- issue #20631
Check if macsec exists on the port before trying to delete it.
Run config macsec del <port> on a port without macsec, and ensure it returns gracefully
- [ x] 202205
Handle the case where macsec is deleted on a port which does not have it configured.
> [macsec/config]: Handle deleting macsec if not configured on port

- dockers/docker-dhcp-server/cli-plugin-tests/mock_state_db.json
- dockers/docker-dhcp-server/cli-plugin-tests/pytest.ini
- dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py
- dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
Manually cherry-pick this PR: https://github.com/sonic-net/sonic-buildimage/pull/20642
In smart switch, there is an issue that Cli query dhcp lease got unknow interface due to dpu fdb hasn't present in STATE_DB FDB_TABLE. Issue: #20155
Query bridge fdb if there is no fdb record in STATE_DB
UT passed
> [202405][smart_switch][dhcp_server] Fix query dhcp lease get unknown in smartswitch by Cli (#20642)

- device/mellanox/x86_64-nvidia_sn4280-r0/platform.json
Add the mapping from the NPU side's data-plane interface to the DPU side interface.
Add the mapping from the DPU to the PCI bus ID.
Extend the `DPUS` section of the `platform.json` file
Compile and run the image.
> [Mellanox] Add SmartSwitch information to the platform.json

- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
Skip the lanes for host config DB for multi asic VS and add UT
UT and compile yang_mgmt and yang_model wheel package
Skip the lanes for host config DB for multi asic VS and add UT
> Skip the lanes for host config DB for multi asic VS

- src/rdb-cli/Makefile
To Fix the issue: redis-cli build broken on Debian/Bookworm (librdb use-after-free) 
https://github.com/sonic-net/sonic-buildimage/issues/20757
This issue is a known open issue below:
https://github.com/redis/librdb/issues/55
According to Walter Doekes's solution, currently to work around it by adding -floto=auto compiler option.
```
make -j$(SONIC_CONFIG_MAKE_JOBS) WARNS='-Wall -Wextra -pedantic -flto=auto'
```
> To Fix the issue: redis-cli build broken on Debian/Bookworm (librdb use-after-free)

- files/build_templates/docker_image_ctl.j2
After a config reload or a config load_minigraph we see the following error messages in the syslog for non existing fabric cards:
```
ixre-cpm-chassis19 ERR container: docker cmd: stop for syncd0 failed with 404 Client Error for http+docker://localhost/v1.43/containers/syncd0/json: Not Found ("No such container: syncd0")
ixre-cpm-chassis19 ERR container: docker cmd: stop for syncd1 failed with 404 Client Error for http+docker://localhost/v1.43/containers/syncd1/json: Not Found ("No such container: syncd1")
```
On Sup, for non-existing Fabric slot, its related swss and syncd containers have not been created yet although its related services have been started.  
Added checking to the  docker_image_ctrl.j2 stop() method.  This change adds code to check if …
> [Supervisor][fabric] Fix the error message for non-present fabric card during config reload on SUP

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
The `show int transceiver status PORT` CLI always displays Rx LOS as False for all the lanes.
```
root@sonic:/home/admin# show int transceiver status Ethernet0 | grep "Rx loss"
Rx loss of signal flag on media lane 1: False
Rx loss of signal flag on media lane 2: False
Rx loss of signal flag on media lane 3: False
Rx loss of signal flag on media lane 4: False
Rx loss of signal flag on media lane 5: False
Rx loss of signal flag on media lane 6: False
Rx loss of signal flag on media lane 7: False
Rx loss of signal flag on media lane 8: False
root@sonic:/home/admin# 
```
- Microsoft ADO **(number only)**: 30180403
On Mellanox platforms, the `get_rx_los` API is overridden through the platform implementation (https://github.com/sonic-net/sonic-buildimage/blob/679997639ede79a7beef53654be101b14d04 …
> [Mellanox] Enable get_rx_los API support in CMIS cable host mgmt mode

- dockers/docker-orchagent/enable_counters.py
- files/build_templates/init_cfg.json.j2
Simplify approach to delaying counters on warm boot and fast boot. Removed FLEX_COUNTER_DELAY_STATUS_FIELD and instead postpone all FC processing to happen after apply view to not delay data plane configuration.
The CONFIG_DB should not be updated in runtime anymore for counters to be delayed.
To address https://github.com/sonic-net/sonic-buildimage/issues/20302.
Put FC into init_cfg.json
Boot the system, verify counters are enabled.
> [FC] Put default counters in init_cfg.json

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/services.conf
- files/build_templates/sonic_debian_extension.j2
- files/build_templates/startup_tsa_tsb.service
Fix https://github.com/sonic-net/sonic-buildimage/issues/20049
Currently, the startup_tsa_tsb.service is started for all the platforms and the service exists if startup-tsa-tsb.conf doesn't exist for the platform.
Don't add startup_tsa_tsb.service to /etc/sonic/generated_services.conf.
Instead add it to services.conf if the platform supports startup_tsa_tsb.service.
1)Verified in Nokia platform that the startup_tsa_tsb.service starts only when the services.conf file exists
> Start startup_tsa_tsb.service only if services.conf file exists

- device/nvidia-bluefield/arm64-nvda_bf-bf3comdpu/chassisdb.conf
To enable CHASSIS_DB support on DPU, This is required to communicate health/ operation status information to the switch from the DPU
By adding chassisdb.conf file in the platform folder, This creates a link to the DB hosted on the Smartswitch platform 
Execute the following command on DPU:
`sonic-db-cli CHASSIS_STATE_DB HSET DPU_TABLE_1 KEY_1 VALUE_1"
sonic-db-cli DPU_APPL_DB HGETALL DPU_TABLE_1` 
and check if the data is available in the Switch
`docker exec -it database-chassis bash -c "sonic-db-cli CHASSIS_STATE_DB HGETALL DPU_TABLE_1"`
> [Nvidia-BF] Enable CHASSIS_DB on DPU

- device/arista/x86_64-arista_7800r3a_36d2_lc/media_settings.json
Copied tuning values for `sm_media_interface` to `nm_850_media_interface` and `active_cable_media_interface`
This should fix issues like https://github.com/aristanetworks/sonic/issues/108
Will ask MSFT to confirm this works with their cables which use `active_cable_media_interface`.
> Adding tuning for other xcvrs for wolverine

- dockers/docker-sonic-gnmi/gnmi-native.sh
- dockers/docker-sonic-telemetry/telemetry.sh
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/gnmi.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/gnmi.json
- src/sonic-yang-models/yang-models/sonic-gnmi.yang
Add GNMI client cert cname list to yang model.
This is cherry-pick PR for https://github.com/sonic-net/sonic-buildimage/pull/18709
Allow gnmi service authentication client cert by cname.
- Microsoft ADO: 25226269
Add GNMI client cert cname list to yang model.
Pass all UT.
- [] SONiC.master-16482.360728-2c8b4066f
- [] SONiC.202405-20731.690016-d47b3771d
- [] SONiC.202311-20734.692072-6612467e4
Add GNMI client cert cname list to yang model.
> [202311]  Add GNMI client cert cname check support. 

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Add a new reset cause "reset_aux_pwr_or_fu" which was added starting from kernel 5.19 for the SN2201 platform.
Add a new reset cause "reset_aux_pwr_or_fu" in chassis.reboot_major_cause_dict.
Test the SN2201 platform by triggering a reboot through power-off and verify that the reboot cause is correctly recognized.
> [Mellanox] Add a new reset cause for SN2201 platform

- dockers/docker-sonic-gnmi/gnmi-native.sh
Currently, we don't have GRPC logs for the GNMI server, making it difficult to debug GRPC-level issues such as invalid certificates.
- Microsoft ADO 30230322:
Update gnmi-native.sh to enable GRPC_GO_LOG.
Send gnmi request and check gnmi log, for example:
2024 Nov 13 07:35:03.454423 str3 INFO gnmi#supervisord: gnmi-native WARNING: 2024/11/13 07:35:03 [core] grpc: Server.Serve failed to complete security handshake from "127.0.0.1:43530": tls: failed to verify client certificate: x509: certificate signed by unknown authority
> Enable GRPC log for GNMI

- .azure-pipelines/azure-pipelines-build.yml
Build Nvidia Bluefield BFB DPU image in the nvidia-bluefield pipeline.
The BFB image allows recovery of the DPU from any SW failure state. The image can be installed from the Smart Switch host without requiring copying an image to the DPU.
Extend Azure pipeline configuration
> [ci] Build nvidia bluefield bfb dpu image

- platform/marvell/sai.mk
- Move SAI version to 1.14.0 for Prestera ASIC (AC3X,AC5X and Falcon)
- Support for Port isolation on AC5x
Compile SAI debian package and validate SONiC PTF.
> [Marvell] Update Prestera SAI deb version

- platform/marvell/platform_arm64.conf
Removed unused bootargs ( mtdparts & otherbootargs ) from platform.conf for marvell arm64. 
Sonic already provides a way to pass extra command line arguments through "ONIE_PLATFORM_EXTRA_CMDLINE_LINUX".
Verified by running sonic to sonic install.
> [Marvell][ARM64]: Remove redundant boot arguments

- Makefile.work
To optionally include "INCLUDE_ICCPD=y" in make command.
Add the missing "INCLUDE_ICCPD" option in makefile.work
Build and verify ICCPD docker is created on the switch.
Build command used:
make configure PLATFORM=marvell PLATFORM_ARCH=arm64 INCLUDE_ICCPD=y
make INCLUDE_ICCPD=y target/sonic-marvell-arm64.bin
master
> Fix ICCPD make option

- dockers/docker-iccpd/Dockerfile.j2
- rules/docker-iccpd.mk
Fix a problem (fixes #19323) where ebtables command cannot be executed by iccpd. This cause the trapped BUM packets (ipv6 neighbor discovery) looping back to the MCLAG port channel.
Replacing the legacy ebtables with the nft-based ebtables command suite by adding iptables package into the iccpd docker container.
Verified the ebtables command can be executed from the iccpd docker. When the MCLAG reaches operational state the isolation rules can be added.
master
202305
202211
> [iccpd] Add nft-based ebtables utilities.

- files/build_templates/qos_config.j2
SONIC warm-reboot command is not working due to unsupported qos configs.
Build and verify that sonic warm-reboot is working fine.
execute the warm-reboot command, and verify it is going though fine.
202405
> remove marvell from pfc_to_pg_map supported asic list

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-256x200G/th5-a7060x6-64pe.config.bcm
The current YAML file for TH5 should be used only with 8 UC and 4 MC queues.
Change the TH5 Yaml settings to use 8 UC and 4 MC queues
Local ixia test is passing in lab.
> [Arista]: Change the TH5 Yaml settings to use 8 UC and 4 MC queues

- .azure-pipelines/azure-pipelines-build.yml
* Add a new mellanox smartswitch build pipeline with the following compile time   options:
- INCLUDE_DHCP_SERVER=y
- SMARTSWITCH=1
> Add new build pipeline for Nvidia smartswitch

- dockers/docker-database/critical_processes.j2
Commit 06c469e added an extra redis instance. This resulted in a two item string without linefeeds in /etc/supervisor/critical_processes:
```
program:redisprogram:redis_bmp
```
That resulted in an error in syslog and docker-database failing.
ERR database#supervisor-proc-exit-listener: Syntax of the line
program:redisprogram:redis_bmp#012 in processes file is incorrect.
Exiting... (#20636)
ossobv/sonic-buildimage#17
Replace the jinja2 whitespace eating hyphens from BOL to EOL.
Note that j2 and the jinja2 parser in sonig-cfggen do not behave the same. The sonig-cfggen is the relevant one.
Before:
```
$ j2 ./dockers/docker-database/critical_processes.j2.old -f json \
<<< '{"INSTANCES":{"foo":"bar","baz":"..."}}'
|
|
program:foo
program:baz
```
```
-j …
```
> [database]: Fix "program:redisprogram:redis_bmp" ERR from supervisor

- src/sonic-yang-models/tests/yang_model_tests/tests/bgp.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp.json
- src/sonic-yang-models/yang-models/sonic-bgp-allowed-prefix.yang
Bugfix for Yang model of BGP Allowed Prefix.
1. Support optional `NEIGHBOR_TYPE` in key.
2. Support optional `le` and `ge` in prefixes_v4/prefixes_v6 list (e.g., `10.20.30.0/24 le 30`).
- Microsoft ADO **(number only)**: 30001113
Updated `sonic-bgp-allowed-prefix.yang`.
1. Define optional value `NEIGHBOR_TYPE` in key.
2. Define type `bgp-allowed-ipv4-prefix` and `bgp-allowed-ipv6-prefix` to support the optional suffix in prefixes_v4/prefixes_v6 list.
Verified by UT:
```
collected 870 items
tests/test_sonic_yang_models.py ..                                                        [  0%]
tests/yang_model_pytests/test_crm.py .................................................... [  6%]
......................................................................................... [ 16%] …
```
> [Yang] Fix Yang model of BGP Allowed Prefix

- files/scripts/sonic-dpu-mgmt-traffic.sh
To add capability to control the inbound traffic for DPUs, Using the script we can now enable:
- Outbound: Allow Traffic from DPU to reach the internet
- Inbound: Allow SSH connection to reach the DPU from a specific port on the switch
Command examples:
`sonic-dpu-mgmt-traffic.sh outbound -e` This enables traffic to reach the internet from the DPU
`sonic-dpu-mgmt-traffic.sh outbound -d` This disables traffic to reach the internet from the DPU
`sonic-dpu-mgmt-traffic.sh inbound -e --dpus dpu1 --ports 9090` This enables SSH traffic to the dpu1 from the internet
We can connect to the DPU using `ssh admin@<switch name/ip> -p 9090`
`sonic-dpu-mgmt-traffic.sh inbound -e --dpus dpu1,dpu2 --ports 9090,5005` This enables SSH traffic to the dpu1 and dpu2 from the internet
We can connect to dpu2 …
> [SmartSwitch] Added inbound traffic capability for DPU management traffic script

- dockers/docker-database/database_config.json.j2
BMP instance should not be launched on DPU database.
Added some condition check to avoid bmp instance from being instantiated on DPU database instances.
local verified on KVM NPU platform.
> Fix bmp instance on DPU database issue

- device/nokia/x86_64-nokia_ixr7250e_sup-r0/chassisdb.conf
- files/build_templates/docker_image_ctl.j2
- files/scripts/swss.sh
To address the issue of the same lagid could be used by two Portchannels in two different linecards. This issue occurs when reboot many Linecards together with 20 seconds delay in each LC reboot.
1) Modify database.sh to create a initial SYSTEM_LAG_IDS_FREE_LIST in the CHASSIS_APP_DB on SUP during database-chassis startup
2) Modify the database consistency check in swss.sh to append the lagid to the end of SYSTEM_LAG_IDS_FREE_LIST when lagid is released.
3) Modify the lag_id_end=1023 (not 1024) in chassisdb.conf since BCM supports the large lagid is 1023
This PR works with the following two PRs:
https://github.com/sonic-net/sonic-swss/pull/3303
https://github.com/sonic-net/sonic-platform-daemons/pull/542
Based on the dependency, the below order to merge …
> [database-chassis][lagid] Initialize SYSTEM_LAG_IDS_FREE_LIST in CHASSIS_APP_DB

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Add support for user to match on TUNNEL_TERM flag in ACL_RULE table.
> [Yang] Add TUNNEL_TERM field to ACL_RULE table

- dockers/docker-sonic-telemetry/telemetry.sh
Added GRPC_GO_LOG flag to enable grpc logging for telemetry process in telemetry docker. Follow up of https://github.com/sonic-net/sonic-buildimage/pull/20798. 
Tested by adding these flags to telemetry.sh inside telemetry docker and sending request from client
Nov 21 23:27:53.652438 Z INFO telemetry#supervisord: telemetry WARNING: 2024/11/21 23:27:53 grpc: Server.Serve failed to complete security handshake from "X:39702": remote error: tls: bad certificate
Nov 21 23:27:54.834302 Z INFO telemetry#supervisord: telemetry WARNING: 2024/11/21 23:27:54 grpc: Server.Serve failed to complete security handshake from "X:39706": remote error: tls: bad certificate
Nov 21 23:27:56.806615 Z INFO telemetry#supervisord: telemetry WARNING: 2024/11/21 23:27:56 grpc: …
> Enable GRPC logs for telemetry process in telemetry docker

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/grpcclient.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/grpcclient.json
- src/sonic-yang-models/yang-models/sonic-grpcclient.yang
Adding yang model for CONFIG_DB table  GRPCCLIENT
Introduced by
https://github.com/sonic-net/sonic-platform-daemons/blob/b276e415d85f3e8a7c64532d95821c9000c9418d/sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py#L407
sign-off: Vaibhav Dahiya [[vdahiya@microsoft.com](mailto:vdahiya@microsoft.com)]
30350460
> [yang] add Yang model for GRPCCLIENT

- device/mellanox/x86_64-nvidia_sn4280-r0/platform.json
The `dpu_tty.py` cli tool requires some platform specific configuration for communication to DPU using picocom. The corresponding configuration is added to the platform.json to enable this tool for the smartswitch
`dpu_tty.py -n dpu0`
> [Mellanox][Smartswitch] Use of the DPU TTY tool for communication

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/0/config-ramon-1-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/1/config-ramon-1-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/10/config-ramon-6-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/11/config-ramon-6-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/12/config-ramon-7-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/13/config-ramon-7-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/14/config-ramon-8-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/15/config-ramon-8-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/2/config-ramon-2-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/3/config-ramon-2-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/4/config-ramon-3-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/5/config-ramon-3-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/6/config-ramon-4-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/7/config-ramon-4-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/8/config-ramon-5-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/9/config-ramon-5-1.bcm
BCM was using default linkscan interval of 250ms and we see high cpu sometimes due to linkscan thread. Increased the interval to 500ms. Also adjusted the stat interval for Ramons
Increased the linkscan interval and stat interval
Ran sonic-mgmt full OC suite in 202405
> [Nokia][Device] Set the BCM linkscan interval via bcm config

- rules/docker-platform-monitor.mk
Mounting /host/reboot-cause on pmon so that the modules can persist their reboot cause history
In SmartSwitch each DPU module's reboot-cause history needs to be persisted on the host
By mounting  "/host/reboot-cause" volume  on pmon
Once the host boot up check the path on the pmon container
> Mounting /host/reboot-cause on pmon so that the modules can persist their reboot cause history

- src/system-health/health_checker/sysmonitor.py
To fix errors that happen when writing to the queue:
```
Jun  5 23:04:41.798613 r-leopard-56 NOTICE healthd: Caught SIGTERM - exiting...
Jun  5 23:04:41.798985 r-leopard-56 NOTICE healthd: Caught SIGTERM - exiting...
Jun  5 23:04:41.799535 r-leopard-56 NOTICE healthd: Caught SIGTERM - exiting...
Jun  5 23:04:41.806010 r-leopard-56 NOTICE healthd: Caught SIGTERM - exiting...
Jun  5 23:04:41.814075 r-leopard-56 ERR healthd: system_service[Errno 104] Connection reset by peer
Jun  5 23:04:41.824135 r-leopard-56 ERR healthd: Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/health_checker/sysmonitor.py", line 484, in system_service#012    msg = self.myQ.get(timeout=QUEUE_TIMEOUT)#012  File "<string>", line 2, in get#012  File …
```
> [healthd] fix healthd shutdown race

- files/build_templates/buffers_config.j2
- src/sonic-config-engine/tests/sample_output/py2/buffers-mellanox2410-dynamic.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox2410-dynamic.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t0-dynamic-remap-disabled.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t0-dynamic.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t1-dynamic-remap-disabled.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox4600c-t1-dynamic.json
Reduce the small packet percentage to 50% as it is more reasonable than 100%.
Run regression
> [Dynamic buffer] Reduce small packet percentage to 50%

- src/system-health/scripts/healthd
- src/system-health/tests/test_system_health.py
To improve boot time and stabilize boot time as well as fast-reboot downtime consistency.
Delay system-health daemon till boot is finished, same as other daemons.
Boot the system, verify system-health service starts with a delay, execute command:
```
admin@sonic:~$ sudo show system-health summary
System status summary
System status LED  green
Services:
Status: OK
Hardware:
Status: OK
```
> [system-health] delay system-health service start

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
get_error_description is not supported when CMIS cable host mgmt. enabled, now enable this function and use the community common implementation. 
When CMIS cable host mgmt. enabled, call the common platform API. Keep using original implementation in FW control mode.
Test this API on different platforms in different modes.
Run SFP related sonic-mgmt test cases
> [Mellanox] [SFP API] Add support to the get_error_description function for when CMIS cable host management is enabled.

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/dpu_vpd_parser.py
- platform/mellanox/mlnx-platform-api/sonic_platform/dpuctlplat.py
- platform/mellanox/mlnx-platform-api/tests/test_device_data.py
- platform/mellanox/mlnx-platform-api/tests/test_dpuctlplat.py
Changes for `dpuctlplat.py`:
- Added option to invoke systemctl rshim start/stop from the pmon container (Using dbus)
- Added no_wait option for reboot (Since we do not need to wait for the dpu to be ready if NPU+DPU reboot is ongoing)
- Added platform JSON parsing for rshim and pcie information
Changed `dpuctlplat.py` to support systemctl commands from pmon container using the dbus-send command
> [Mellanox][Smartswitch] Add no_wait option for dpu reboot and add platform information parsing  

- dockers/docker-dhcp-relay/Dockerfile.j2
- dockers/docker-dhcp-relay/docker_init.sh
- dockers/docker-fpm-frr/Dockerfile.j2
- dockers/docker-fpm-frr/docker_init.sh
- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-orchagent/docker-init.j2
- files/build_templates/docker_image_ctl.j2
- files/build_templates/rsyslog_plugin.conf.j2
- files/build_templates/sonic_debian_extension.j2
Reverts sonic-net/sonic-buildimage#20248 and fixes https://github.com/sonic-net/sonic-buildimage/issues/20544
> Revert "Move eventd enabled check from build time to runtime"

- device/nokia/arm64-nokia_ixs7215_52xb-r0/platform.json
- device/nokia/x86_64-nokia_ixr7220_h4-r0/platform.json
- device/nokia/x86_64-nokia_ixr7220_h4_32d-r0/platform.json
- device/nokia/x86_64-nokia_ixr7220_h5_64d-r0/platform.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform.json
Enable and use the asic_sensors polling on the Nokia platforms:
arm64-nokia_ixs7215_52xb-r0
x86_64-nokia_ixr7220_h4-r0
x86_64-nokia_ixr7220_h4_32d-r0
x86_64-nokia_ixr7220_h5_64d-r0
Fixes https://github.com/Nokia-ION/ndk/issues/36
Modify the platform.json files with the below definition no Nokia platforms to enable the asic_sensors polling.
"asic_sensors": {
"polling_interval": "10",
"poll_admin_status": "enable"
}
This PR works with PR https://github.com/sonic-net/sonic-buildimage/pull/20826
execute CLI "show platform temperature". The output will display the asic_sensors temperature.
```
admin@ixre-egl-board25:~$ show platform temperature 
Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp …
```
> [Nokia][asic-sensors] Modify the platform.json to enable the asic_sensors polling on Nokia platforms

- platform/vs/docker-sonic-vs/supervisord.conf.j2
Redis-chassis doesn't bind to the localhost address intentionally. Because of this, Redis blocks TCP connections that are connecting to non-loopback interface addresses when there's no password set (which is the case for us) unless `--protected-mode no` is set. This has already been done for docker-database, but now needs to be done for docker-sonic-vs following the upgrade to Bookworm.
Therefore, in the supervisord.conf file, add `--protected-mode no` to the arguments passed in for redis-chassis.
> Add `--protected-mode no` flag to redis-chassis

- src/sonic-config-engine/portconfig.py
- src/sonic-config-engine/tests/sample_output/platform_output.json
Currently optional params only get applied to the first child port in group. We want optional parameters to apply to all child ports in group.
For example:
```
"Ethernet0": {
"default_brkout_mode": "2x400G",
"autoneg": "on"
},
```
In this scenario we want autoneg on to be in the config_db entry for
both interfaces that belong to the group; Ethernet0 and Ethernet4.
Currently this only gets applied to Ethernet0:
```
(Pdb++) pp child_ports
{'Ethernet0': {'alias': 'Ethernet1/1',
'autoneg': 'on',
'index': '1',
'lanes': '17,18,19,20',
'speed': '400000',
'subport': '1'},
'Ethernet4': {'alias': 'Ethernet1/5',
'index': '1',
'lanes': '21,22,23,24',
'speed': '400000',
'subport': '2'}}
```
With this change it now gets applied to all interfaces in the group as expected
```
(Pdb) pp child_ports …
```
> Fix optional hwsku params not applying to all interfaces

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/buffers_defaults_t2.j2
- src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cq2-lc.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cq2-lc.json
Set `xoff` of `x86_64-arista_7800r3_48cq2_lc` to the same as `x86_64-arista_7800r3_48cqm2_lc`
In https://github.com/sonic-net/sonic-buildimage/pull/14908 these SKUs diverged in `xoff` values.
This causes the PFC generation behavior to diverge between these SKUs.
Confirmed the pool resources match now on both SKUs.
Previously:
```
root@cmp206-6:~# bcmcmd "tm ing vsq resources"
tm ing vsq resources
========================================================================================
|                              Core 0 Resource Allocation                              |
========================================================================================
| Parameter        | Bytes                   | OCB Buffers    | OCB Packet Descriptors | …
```
> Set `xoff` of `x86_64-arista_7800r3_48cq2_lc` to the same as`x86_64-arista_7800r3_48cqm2_lc`

- device/nvidia-bluefield/arm64-nvda_bf-bf3comdpu/pmon_daemon_control.json
Data port on the DPU is of type "Dpc" i..e no xcvr is present on it. Thus xcvrd can effectively be skipped on this platform
change the pmon configuration
"skip_ycabled": true,
"skip_xcvrd": true
Manual test to ensure xcrvd is skipped for this type of ports.
Load and check if xcvrd is not started
> [SmartSwitch] Skip xcvrd on the DPU

- dockers/docker-fpm-frr/frr/supervisord/critical_processes.j2
- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
- platform/vs/docker-sonic-vs/supervisord.conf.j2
To support srte policy, frr must enable pathd first. 
Enable pathd in frr docker.
Enter frr docker, check the pathd process.
> [FRR] Enable pathd in frr

- src/sonic-yang-models/yang-models/sonic-logger.yang
YANG failures during `config replace` with default configuration.
As of https://github.com/sonic-net/sonic-buildimage/pull/19611 and https://github.com/sonic-net/sonic-utilities/pull/3428 a new database field of `require_manual_refresh` was added.
This leads to YANG failures in the factory-default configuration for the `xcvrd` log entry which by default is written as true.
Updated YANG file for new field.
Verify `config replace` works with factory default configuration.
None, this only exists in master.
master as of 20241129
[yang] LOGGER missing require_manual_refresh
N/A
Signed-off-by: Brad House (@bradh352)
> [yang] LOGGER missing require_manual_refresh

- device/arista/x86_64-arista_common/pmon_daemon_control_linecard.json
SFF Manager in xcvrd needs to run to take non-cmis transceivers out of lpmode as part of the fix for these transceivers remaining in down state.
We wanted to enable SFF Manager on Arista linecards. 
This is intended to work together with the change in https://github.com/sonic-net/sonic-platform-daemons/pull/565.
Can be tested by loading an image containing this change alongside the change from https://github.com/sonic-net/sonic-platform-daemons/pull/565 on an Arista chassis.
Verify that without this image some interfaces were in a down state but with the image all interfaces came up as expected.
Added enable sff mgr in xcvrd by default on Arista linecards.
> Enable SFF Manger on Arista linecards by default

- src/sonic-yang-models/tests/yang_model_tests/tests/flex_counter.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Added a new field in FLEX_COUNTER_TABLE to represent the bulk chunk size for bulk counter polling.
> Support bulk chunk size in bulk counter polling operation

- platform/checkout/cisco-8000.ini
Update cisco-8000.ini to 202311.1.0.8 release
> Update cisco-8000.ini to 202311.1.0.8 release

- device/arista/x86_64-arista_7800_sup/chassisdb.conf
The following PRs made `1024` incorrect:
https://github.com/sonic-net/sonic-buildimage/pull/20369
https://github.com/sonic-net/sonic-swss/pull/3303
This fixes:
https://github.com/sonic-net/sonic-buildimage/issues/21096
> Update Arista SKU lag_id_end to 1023

- src/sonic-frr/patch/0062-zebra-lib-use-internal-rbtree-per-ns.patch
- src/sonic-frr/patch/series
Adding the below fix from FRR https://github.com/FRRouting/frr/pull/17297
This is to fix the following crash which is a statistical issue
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/frr/zebra -A 127.0.0.1 -s 90000000 -M dplane_fpm_nl -M snmp'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fccd7351e2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fccd6faf7c0 (LWP 36))]
(gdb) bt
#0  0x00007fccd7351e2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fccd7302fb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fccd72ed472 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fccd75bb3a9 in _zlog_assert_failed …
```
> [FRR]Fixing zebra to use internal rbtree per NS tree of ifps

- files/image_config/interfaces/interfaces.j2
The Smart Switch DPU uses `midplane-eth0` interface instead of `eth0` for the control plane access. The tails are described in [IP address asignment HLD](https://github.com/sonic-net/SONiC/blob/master/doc/smart-switch/ip-address-assigment/smart-switch-ip-address-assignment.md).
When the `dhclient` is running on top of `eth0` interface that is down on the Smart Switch DPU it generates errors in the logs:
```
ERR dhclient[2083]: send_packet: Network is down
2024 Nov 19 15:27:42.157924 sonic ERR dhclient[2083]: send_packet: Network is down
2024 Nov 19 15:27:42.158000 sonic ERR dhclient[2083]: dhclient.c:2600: Failed to send 300 byte long packet over eth0 interface.
```
Do not run dhclient on the eth0 interface.
Run the image on the Smart Switch DPU. …
> [smart-switch][dpu] Do not run dhclient on the eth0 interface.

- dockers/docker-fpm-frr/frr/bgpd/templates/internal/peer-group.conf.j2
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_back.conf
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chasiss_packet.conf
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chassis_packet_isolate.conf
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chassis_packet_unisolate.conf
- src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_front.conf
What I did:
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/21116
Why I did:
FRR behavior change w.r.t to command `ttl-security hops <>` from being removed from address-family .
> Update internal template peer-group.conf.j2 for ttl-security hops command.

- platform/centec-arm64/platform-modules-fs.mk
For centec-arm64, both platform-modules-fs and platform-modules-e530 try to compile the same directory of kernel sources. If both compilations are running at the same time, then this is going to lead to errors.
Fix this by introducing an artificial dependency between the two so that the compilations are forced to be serialized.
> Add an artificial dependency between two modules for centec-arm64

- platform/nvidia-bluefield/bluefield-platform-modules/bin/bfnet.sh
Remove the virtual smart switch leftovers from the Nvidia DPU initialization flow. 
Remove unused code from the bash script.
Run sonic-mgmt tests.
> [nvidia-bluefield] Remove the virtual smart switch leftovers.

- platform/vs/docker-sonic-vs/Dockerfile.j2
- platform/vs/docker-sonic-vs/start.sh
FRR 10.0.1 upgrade (sonic-net/sonic-buildimage#20269) brought in a mgmtd daemon for FRR. This needs to be started up in docker-sonic-vs as part of the other daemons in this container.
Additionally, Debian Bookworm provides version 2.5.0 of scapy, but the pip3 command later in the file downgraded it to 2.4.5, which does not work in Bookworm. Fix this by removing the pip3 installation for scapy, and updating the other packages installed via pip3.
- Microsoft ADO **(number only)**: 30480849
> Fix docker-sonic-vs following upgrade to Bookworm

- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C224O8/buffers_defaults_t0.j2
- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C224O8/buffers_defaults_t1.j2
Update buffer calculations for Mellanox-SN5600-C224O8 HwSKU.
Update the lossless pull size
Run sonic-mgmt QoS test
> [Mellanox] Update buffer calculations for Mellanox-SN5600-C224O8 SKU

- src/sonic-frr/dplane_fpm_sonic/dplane_fpm_sonic.c
Reduce high CPU usage on zebra after performing port toggle on all interfaces simultaneously
Apply zebra fpm backpressure patches from FRR mainline to dplane_fpm_sonic:
* zebra: Use built in data structure counter (https://github.com/FRRouting/frr/pull/16221)
* Zebra fpm backpressure (https://github.com/FRRouting/frr/pull/16220)
> Apply Zebra fpm backpressure patches to dplane_fpm_sonic

- platform/mellanox/docker-syncd-mlnx/Dockerfile.j2
**syncd** is linking to libasan v8 during build after the bookwork upgrade https://github.com/sonic-net/sonic-buildimage/pull/18651 but libasan v6 is installed in the syncd container for the mellanox platform which is causing runtime errors.
Install libasan8 on docker-syncd-mlnx
Build sonic with ENABLE_ASAN=y and verify syncd starts successfully.
> Upgrade libasan to version 8 in docker-syncd-mlnx to align with bookworm libasan

- rules/config
Found typo (wrong spelling)
enviroment -> environment
typo of comment so no need for backporting.
no test required.
n/a
none
```
/\_/\  
( o.o ) 
> ^ <
```
> fix typo: enviroment

- src/sonic-config-engine/config_samples.py
- src/sonic-config-engine/tests/sample_output/t1-smartswitch.json
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/20730
The generated t1 config fails YANG validation, which leads to config setup failure since we enforce YANG validation in config reload. 
Update config to align with YANG 
Run YANG validate on generated config.
> Update SmartSwitch config to align YANG standard

- platform/nvidia-bluefield/bluefield-platform-modules/bin/platform-dump.sh
Extend platform dump to include MST devices information.
Extend platform-dump.sh scrip.
Run `show techsupport` command
> [nvidia-bluefield] Extend platform dump.

- src/sonic-frr/patch/0064-SRv6-BGP-SID-reachability.patch
- src/sonic-frr/patch/0065-zebra-display-srv6-encapsulation-source-address-when-configured.patch
- src/sonic-frr/patch/0066-lib-fix-srv6-locator-flags-propagated-to-isis.patch
- src/sonic-frr/patch/0067-Add-support-for-SRv6-SID-Manager.patch
- src/sonic-frr/patch/0068-bgpd-Extend-BGP-to-communicate-with-the-SRv6-SID-Manager-to-allocate-release-SRv6-SIDs.patch
- src/sonic-frr/patch/series
Bring the below PRs from FRR mainline to SONiC in order to support SRv6 SID Manager in SONiC.
| Patch             | FRR Pull Request |
| ------------- | ----------------- |
| 0064-SRv6-BGP-SID-reachability.patch | https://github.com/FRRouting/frr/pull/14810 |
| 0065-zebra-display-srv6-encapsulation-source-address-when-configured.patch | https://github.com/FRRouting/frr/pull/16151 |
| 0066-lib-fix-srv6-locator-flags-propagated-to-isis.patch | https://github.com/FRRouting/frr/pull/15673 |
| 0067-Add-support-for-SRv6-SID-Manager.patch | https://github.com/FRRouting/frr/pull/15604 |
| 0068-bgpd-Extend-BGP-to-communicate-with-the-SRv6-SID-Manager-to-allocate-release-SRv6-SIDs.patch | https://github.com/FRRouting/frr/pull/15676 |
> [FRR]: Add support for SRv6 SID Manager

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/asic-sensors.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/asic-sensors.json
- src/sonic-yang-models/yang-models/sonic-asic-sensors.yang
Add Yang Models support for ASIC_SENSORS configuration.
Add Yang Models support for the following ASIC_SENSORs configuration
```
{
"ASIC_SENSORS": {
"ASIC_SENSORS_POLLER_INTERVAL": {
"interval": "10"
},
"ASIC_SENSORS_POLLER_STATUS": {
"admin_status": "enable"
}
}
}
```
1) Image Build should be passed.
> [YangModel][asic_sensors] Add ASIC_SENSORS yang models

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/subnet_decap.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/subnet_decap.json
- src/sonic-yang-models/yang-models/sonic-subnet-decap.yang
Add Yang model to config DB `SUBNET_DECAP` table.
- Microsoft ADO **(number only)**: 30473162
Add the yang model file and UT.
Build sonic-yang-model and sonic-yang-mgmt.
> [YANG] Add yang model to `SUBNET_DECAP` table

- src/ptf-py3.patch/0004-Consider-only-expected-packets-for-timeout.patch
- src/ptf-py3.patch/series
`dhcp_relay/test_dhcp_relay_stress.py::test_dhcp_relay_stress[offer|ack]` tests are failing on dualtor topologies with signature `Failed: /tmp/dhcp_stress_test_offer.json is missing`, see issue https://github.com/aristanetworks/sonic-qual.msft/issues/325 for more details.
`count_matched_packets` method is getting stuck in a while loop as long as ptf server port receives any packet (Ex: in dualtor case, we do see continuous ICMP packets on ptf port). Fix is to consider only expected packets w.r.t timeout (similar to `count_matched_packets_all_ports` logic).
With this PR changes we should not see dhcp_relay/test_dhcp_relay_stress.py failures on dualtor topologies with symptom `Failed: /tmp/dhcp_stress_test_offer.json is missing`.
Reason: Issue is seen in …
> [ptf] Consider only expected packets for timeout

- files/build_templates/docker_image_ctl.j2
To support the emulation of VS chassis, we need to remove the existing critical service containers before transforming the HwSKU of the VS device. A previous PR [#18512](https://github.com/sonic-net/sonic-buildimage/pull/18512) introduced a change to the docker_image_ctl.j2 that forces VS images to recreate database containers every time the OS is cold started while the behaviors of other containers(swss/bgp/teamd/syncd) remained unchanged. As a consequence, when the VS device is rebooted without proper human intervention, the database containers will be recreated while the other services will reuse existing containers. That can cause the swss/bgp/syncd containers to become invalid if the database containers get recreated with a different container ID, because swss/bgp/syncd containers …
> [Bug Fix] docker_image_ctl.j2: remove the logic that recreates database containers on VS platform

- src/sonic-eventd/tests/eventd_ut.cpp
Fixes https://github.com/sonic-net/sonic-buildimage/issues/21140
In https://github.com/sonic-net/sonic-buildimage/pull/20024 and https://github.com/sonic-net/sonic-swss-common/pull/906, we made the change that when a control character is read, zmq_message_read will return with rc 0, which will create an empty internal event. 
As part of eventd design, empty structured events are dropped, which leads to control characters being a no-op which is the expected behavior.
In UT, we are still always expecting a control character to be the first message to be read by zmq which is not the case as described in https://github.com/sonic-net/sonic-buildimage/pull/20024. We are also not ignoring empty events that are read which is being done by eventd. 
With this change, control characters are properly …
> [eventd] Ignore control character event if it comes in UT

- files/image_config/bannerconfig/banner-config.service
fixes #19661
Removed the dependency on sshd service. Banner service will save the config data into the file after setting the config, so it will be available after the boot in any case
Reboot the switch and wait for the serial prompt. SSH should become available after a couple of seconds.
> Banner: Remove dependency on sshd service

- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C224O8/port_config.ini
- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/port_config.ini
- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-O128/port_config.ini
- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-V256/port_config.ini
Removed FEC mode from port_config.ini for SN5600 SKUs. FEC mode needs to come as part of user configuration as it depends on peer end capabilities as well.
Modified port_config.ini
Loading the SKU and testing default configuration generation
> [Mellanox]Removing FEC from port_config.ini for SN5600 SKUs

- dockers/docker-orchagent/ipinip.json.j2
- src/sonic-config-engine/tests/multi_npu_data/py2/ipinip.json
- src/sonic-config-engine/tests/multi_npu_data/py3/ipinip.json
- src/sonic-config-engine/tests/sample_output/py2/ipinip.json
- src/sonic-config-engine/tests/sample_output/py2/ipinip_subnet_decap_enable.json
- src/sonic-config-engine/tests/sample_output/py3/ipinip.json
- src/sonic-config-engine/tests/sample_output/py3/ipinip_subnet_decap_enable.json
Reverts sonic-net/sonic-buildimage#20650, which caused Orchanget crash #21246 
> Revert "[QoS] Add tunnel pipe mode support for IPIP Decap mode to use SAI_TUNNEL_ATTR_DECAP_QOS_DSCP_TO_TC_MAP"

- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
There are several TCP ports bound to localhost that need to be disabled to enhance system security.
By adding -P 0 in supervisord.conf.j2 to disable the ports.
Check the file for -P 0 changes, and confirm port behaviour using netstat.
> Disabling ports by adding parameter ‘-P 0’

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/BALANCED/buffers_defaults_t0.j2
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7050cx3-dualtor-remap-disabled.json
- src/sonic-config-engine/tests/sample_output/py3/buffer-arista7050cx3-dualtor.json
[MSFT ADO 28240256 [SONiC_Nightly][Failed_Case][qos.test_qos_sai.TestQosSai][testQosSaiHeadroomPoolSize][20231110][broadcom][Arista-7050CX3-32S-D48C8]
For Arista-7050CX3-32S-D48C8 (BCM56870_A0 / TD3), in headroom pool size test, 
inject lossless traffic into multiple ingress ports, exhausted share buffer first, then before exhaust all the headroom pool observed egress drop. 
Expected appearance is ingress drop, so test failed.
(Check BRCM CSP CS00012358392 "Egress lossless pool size update for Arista-7050CX3-32S-D48C8 DualToR" in detail)
```
Pool: egress_lossless_pool
----  --------
mode  static
size  32340992
type  egress
----  --------
... ...
Pool: ingress_lossless_pool
----  --------
mode  dynamic
size  32689152
type  ingress
xoff  2058240
----  --------
```
As above output of command …
> [RDMA] correct egress buffer size for Arista-7050CX3-32S-D48C8 DualToR

- dockers/docker-snmp/snmpd.conf.j2
Fix https://github.com/sonic-net/sonic-buildimage/issues/21314
Update and prolong the timeout of the requests between snmpd and SNMP AgentX.
In SONiC SNMP AgentX, the MIB updaters and AgentX client shares the same AsyncIO/Coroutine event loop.
During the MIB updaters update the SNMP values, the AgentX client can't respond to the snmpd request.
The default value of snmpd request is 1s(timeout) * 5(retries)
When the CPU is high, the MIB updaters are slow, 1s timeout is not enough, even if it retries 5 times.
Hence update to 5s(timeout) * 4(retries), the time windows = 20s, which makes sure the SNMP request can be handled even with 100% CPU utilization.
- Microsoft ADO **30112399**:
Update the default value(https://linux.die.net/man/5/snmpd.conf):
agentXTimeout 1(default value) -> 5 …
> Update snmpd.conf.j2 prolong agentXTimeout to avoid timeout failure in high CPU utilization scenario

- dockers/docker-sonic-mgmt/Dockerfile.j2
Adding pytest-stress to sonic-mgmt image will help in running stress tests.
pip install pytest-stress plugin
Manually tested the image with DUT
Not applicable.
Adds pytest-stress to sonic-mgmt image
- Adding pytest-stress to sonic-mgmt image will help in running stress tests.
Not applicable
> Add pytest-stress to sonic-mgmt image

- files/build_templates/buffers_config.j2
- files/build_templates/qos_config.j2
PIE ports are used for internal traffic (telemetry), not for regular data traffic, doesn't support buffer or qos config.
Exclude PIE ports from PORTS_ACTIVE.
config load_minigraph.
```
cisco@ixia-light-dut:/usr/share/sonic/device/x86_64-8122_64eh_o-r0/Cisco-8122-O64$ sudo config load_minigraph 
Reload config from minigraph? [y/N]: y
Acquired lock on /etc/sonic/reload.lock
Disabling container monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Warning: mirror table EVERFLOW in ACL_TABLE does not have any ports bound to it
Warning: mirror table EVERFLOWV6 in ACL_TABLE does not have any ports bound to it
Running command: /usr/local/bin/sonic-cfggen -d -y …
```
> Exclude PIE ports from buffer and qos config

- .gitmodules
Fix typo in branch name for sonic-restapi
> Fix typo in 202411 gitmodule

- azure-pipelines.yml
Disable vstest job because sonictest agent pool is failing.
To unblock PRs.
> [ci] Disable vstest job in Test stage.

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/subnet_decap.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/subnet_decap.json
- src/sonic-yang-models/yang-models/sonic-subnet-decap.yang
Cherry-pick PR https://github.com/sonic-net/sonic-buildimage/pull/21118 into 202405
> 202405 add subnet decap yang

- device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py
- dockers/docker-sflow/port_index_mapper.py
- src/sonic-bgpcfgd/bgpcfgd/runner.py
- src/sonic-bgpcfgd/staticroutebfd/main.py
- src/sonic-eventd/src/eventd.cpp
- src/sonic-py-common/sonic_py_common/daemon_base.py
- src/sonic-py-common/sonic_py_common/multi_asic.py
Change DBConnector to connect redis with unix socket.
Improve SONiC Redis security by switch to unix socket connection.
- Microsoft ADO: 30329015
Change DBConnector parameter to connect redis with unix socket:
DBConnector(const std::string &dbName, unsigned int timeout_ms, bool isTcpConn = false);
Pass all UT.
- [] 
Change DBConnector to connect redis with unix socket.
> Change DBConnector to connect redis with unix socket.

- src/sonic-yang-models/yang-models/sonic-events-host.yang
Add disk full event to sonic-events-host yang model.
This PR need publish disk full event:
https://github.com/sonic-net/sonic-utilities/pull/3700
- Microsoft ADO: 30608100
Add disk full event to yang model.
Pass all UT.
- [] 
Add disk full event to sonic-events-host yang model.
> Add disk full event to sonic-events-host yang model.

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-C256S2/th5-a7060x6-64pe.config.bcm
Arista-7060X6-64PE-C256S2 is missing flex counters configs.
Update flex counters config for Arista-7060X6-64PE-C256S2
Test it locally on Arista-7060X6-64PE-C256S2.
> [Arista] Update flex counters config for Arista-7060X6-64PE-C256S2

- src/sonic-bgpcfgd/bgpcfgd/main.py
- src/sonic-bgpcfgd/bgpcfgd/managers_srv6.py
- src/sonic-bgpcfgd/tests/test_srv6.py
There is a motivation to add capabilities in SONiC that allows static configuration of SRv6 network.
- Microsoft ADO **(number only)**: 30251795
I added a SRv6 manager in Bgpcfgd that subscribes to SRV6_MY_LOCATORS and SRV6_MY_SIDS in CONFIG_DB and programs the changes to FRR's configuration.
Note: this change depends on the availability and implementation details of the following FRR patch [FRR SRv6 Static SID CLI](https://github.com/sonic-net/sonic-buildimage/pull/21380)
- Run unit tests
- Build an image that contains this change and the relevant FRR CLI support.
- Test the Image on a virtual device or physical device
[SRv6 static config HLD](https://github.com/sonic-net/SONiC/pull/1860)
> Add SRv6 support in Bgpcfgd

- src/sonic-frr/patch/0077-frr-vtysh-dependencies-for-srv6-static-patches.patch
- src/sonic-frr/patch/0078-vtysh-de-conditionalize-and-reorder-install-node.patch
- src/sonic-frr/patch/0079-staticd-add-support-for-srv6.patch
- src/sonic-frr/patch/series
Adding FRR CLI to support SRv6 static. The HLD for the feature is available at https://github.com/sonic-net/SONiC/pull/1860
> FRR CLI for SRv6 static

- dockers/docker-sonic-bmp/supervisord.conf
- dockers/docker-sonic-gnmi/supervisord.conf
- dockers/docker-sonic-restapi/supervisord.conf
- dockers/docker-sonic-telemetry/supervisord.conf
if critical process crashes or killed, bmp docker container will not be auto-restarted.
- Microsoft ADO **(number only)**:30807821
/usr/bin/supervisor-proc-exit-listener takes in charge of critical process monitor and event publish, thus it should be autorestar-ted in any case, otherwise there might be issue if supervisor-proc-exit-listener crashes, or in some test cases like
"docker exec bmp kill -SIGKILL -1" critical processes may not work correctly in some race condition (depends on whether supervisor-proc-exit-listener is the last one to be killed)
When a container receives the SIGKILL signal to terminate its processes, the order in which the processes are actually terminated can depend on the scheduling and resource availability within the container.
Scheduling: Within a container, …
> Fix docker auto restart issue

- dockers/docker-snmp/Dockerfile.j2
- dockers/docker-snmp/docker-snmp-init.sh
- dockers/docker-snmp/supervisord.conf.j2
It's one part of the fixes of https://github.com/sonic-net/sonic-buildimage/issues/21314
SNMP walker request will always timeout when 100% CPU utilization.
- Microsoft ADO **30112399**:
Enable SNMP dynamic frequency on packet chassis.
snmp/test_snmp_cpu.py(https://github.com/sonic-net/sonic-mgmt/blob/master/tests/snmp/test_snmp_cpu.py) tests the scenario.
And the test case passes in my local run.
For issue:
https://github.com/sonic-net/sonic-buildimage/issues/21314
Change of SNMP-AgentX https://github.com/sonic-net/sonic-snmpagent/pull/345 will fix the issue.
But we want to limit the scope of the change, since we only see this issue on packet-chassis and old devices with low performance CPUs.
> [chassis-packet][SNMP] Enable SNMP dynamic frequency on packet chassis

- platform/broadcom/docker-syncd-brcm-dnx-rpc/Dockerfile.j2
After docker-syncd-brcm-dnx-rpc is moved to bookworm in master, the libthrift*.so is not installed inside the syncd docker and the syncd process fails to come up.
Installed libthrift-0.17.0
Verified that the syncd dockers  and swss dockers stay up and able to run Qos tests
> Install libthrift in docker-syncd-brcm-dnx-rpc

- platform/broadcom/docker-syncd-brcm-rpc/Dockerfile.j2
libthrift did not get installed in the Broadcom syncd RPC container. However, syncd-rpc requires it.
> Fix RPC container for Broadcom

- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/qosmaps.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json
- src/sonic-yang-models/yang-models/sonic-tc-dscp-map.yang
issue : https://github.com/sonic-net/sonic-buildimage/issues/20575
"config-reload" in dualtor topologies were failing due to absence of TC_TO_DSCP Yang model.
The above failure was seen after the the PR https://github.com/sonic-net/sonic-utilities/pull/3102
Step-1: In DUT add the yang file to "/usr/local/yang-models/sonic-tc-dscp-map.yang" to this path.
Step-2: config reload -y
Adding YANG model for TC_TO_DSCP_MAP along with test files.
> Adding YANG model for TC_TO_DSCP_MAP

- dockers/docker-platform-monitor/Dockerfile.j2
- files/build_templates/docker_image_ctl.j2
This PR is a temporary change, once the rshim interface will be replaced this PR will not be required anymore 
To mount the dbus socket in pmon container as systemctl command has to be executed to start/stop service from PMON container during admin state/ reboot command execution
- `dockers/docker-platform-monitor/Dockerfile.j2` - Addition of dbus package for mellanox specific platform in order to use dbus-send command
- `files/build_templates/docker_image_ctl.j2` - Mount socket, since we need to use the systemctl command to start/stop service from pmon container
`dbus-send` commands in Pmon container can be performed in order to start / stop the `rshim@.service` which is relevant for starting or stopping the rshim service
> [Mellanox][Smartswitch]Changes for mounting dbus socket

- files/build_templates/docker_image_ctl.j2
- src/systemd-sonic-generator/ssg-test.cc
- src/systemd-sonic-generator/systemd-sonic-generator.cpp
Fix #20284
In 202405 and above, two extra steps are added before the start of every container which checks NUM_DPU and IS_DPU_DEVICE by parsing the platform.json file using the jq tool. This is only relevant for Smartswitch. However, this is adding some delay during the reconciliation phase of WR/FR resulting
Set the environment variables for systemd by systemd-sonic-generator.
1. Check there is no `jq` command under the swss.sh start and syncd.sh start from the sonic-bootchart
2. Regression test:
```
echo '{"DPUS":{"dpu0":{}, "dpu1":{}}}' | sudo tee /usr/share/sonic/device/x86_64-kvm_x86_64-r0/platform.json
docker rm -f database
sudo reboot
...
admin@vlab-01:~$ sudo systemctl list-unit-files '*midplane*'
UNIT FILE                    STATE …
```
> [Fix 20284]: Enhance smartswitch environment variables parsing

- src/flashrom/Makefile
flashrom recently started failing to build with the below error:
```
Cloning into 'flashrom-0.9.7'...
/sonic/src/flashrom/flashrom-0.9.7 /sonic/src/flashrom
fatal: 'tags/0.9.7' is not a commit and a branch 'flashrom-src' cannot be created from it
```
Nothing in sonic-buildimage has changed in relation to this so presumably flashrom upstream renamed their tags.
This commit just fixes the formatting of the tag name to use the new format.
Build sonic from scratch with no cached packages.
master as of 20250119
flashrom build fix: incorrect tag name
Signed-off-by: Brad House (@bradh352)
> flashrom build fix: incorrect tag name

- src/sonic-frr/dplane_fpm_sonic/dplane_fpm_sonic.c
- src/sonic-frr/patch/0079-staticd-add-support-for-srv6.patch
The FRR CLI to support SRv6 Static SIDs has been merged in FRR mainline in this PR (https://github.com/FRRouting/frr/pull/16894). The CLI has been ported into SONiC mainline in this PR (https://github.com/sonic-net/sonic-buildimage/pull/21380).
This PR verifies the SRv6 Static SIDs configured by the above FRR CLI. It verifies that the block and node parts of the configured SID matches block and node parts of the locator it belongs to. The PR computes the parameters that will be installed with the SID into APPL DB. The changes in this PR will be also added into FRR mainline.
> [FRR]: Verifying static SRv6 SIDs parameters

- src/sonic-yang-models/tests/yang_model_tests/tests/srv6.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/srv6.json
- src/sonic-yang-models/yang-models/sonic-srv6.yang
Change the YANG schema of the SRv6 module to use an ipv6-prefix type for the key of the SRV6_MY_SIDS table.
> [YANG] SRv6 yang model followup fix

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal.py
Most of the thermal sensor has continues index, for example: module1_temp_input, module2_temp_input. However, there could be some thermal sensors whose index is discrete. For example, some platform only contains thermal sensor for sodimm2_temp_input, but there is no such sensor for sodimm1_temp_input.
This PR is to support thermal sensor which has discrete index. 
Allow sensor with discrete index, create thermal object for it
manual test
unit test
> [Mellanox] support thermal sensor which has discrete index

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/dpuctlplat.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
- platform/mellanox/mlnx-platform-api/sonic_platform/wait_sfp_ready_task.py
- platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py
- platform/mellanox/mlnx-platform-api/tests/test_change_event.py
- platform/mellanox/mlnx-platform-api/tests/test_dpuctlplat.py
Mellanox platform API uses standard python time function `time.time()` in many places. `time.time()` gets time from system clock which could be changed by NTP or user. Adjusting system clock will affect the code logical and causes bugs. For example, in platform/mellanox/mlnx-platform-api/sonic_platform/utils.py there is a Timer class, the timer will trigger event with unexpected interval if user/NTP changes the system clock. This PR changes `time.time()` to `time.monotonic` to avoid such issue.
Use `time.monotonic()` instead of `time.time` .
Manual test.
Unit test.
> [Mellanox] do not use system clock to avoid issues caused by system time change

- src/sonic-bgpcfgd/bgpcfgd/managers_srv6.py
- src/sonic-bgpcfgd/tests/test_srv6.py
To adapt bgpcfgd to the new schema of SRV6_MY_SIDS
> [Bgpcfgd] Update bgpcfgd to handle SRV6_MY_SIDS table's key as an ipv6 prefix

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Not all xcvr API support get_error_description, for example sff8636. For those API types, get_error_description should return "Not supported".
get_error_description should return "Not supported".
Manual test
unit test
> [Mellanox] get_error_descripton should return Not supported for modules that does not support this API

- device/mellanox/x86_64-nvidia_sn5640_simx-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn5640_simx-r0/thermal_policy.json
- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
Support running hw-management service on SN5640 emulation platform.
- Use physical EEPROM instead of the fake one
- Do not skip PSUd, PCId, thermal control daemon
- Adjust PCIe and thermal configuration files
Run Nvidia simulation on SN5640 (ASIC and Platform)
> [Mellanox] Support running hw-management service on SN5640 emulation platform

- dockers/docker-orchagent/ipinip.json.j2
Temporary workaround for #21516. Issue is seen with 200+ interface. So, used >128 as condition instead of >256.
Reset the address list if port count is over 128.  So no more IPv4/IPv6 IPinIP tunnel will be created for interfaces.
tunnel interfaces on loopback and vlan MP2MP are still there.
Loaded the image with more than 200 interfaces, not seeing TABLE_FULL issue anymore.
> skip ipinip tunnel creation if many interfaces

- src/sonic-frr/dplane_fpm_sonic/dplane_fpm_sonic.c
The current SRv6 test cases are implemented by installing the SRv6 SIDs in the kernel. Then the kernel notifies FRR about these SIDs. The current Netlink messages from the kernel does not provide the SID information (block length, node length, function length, argument length).
This PR extends the `dplane_fpm_sonic` to handle this issue by setting the SID information to the locator defaults.
> [dplane_fpm_sonic]: Fix for SRv6 SIDs learnt from the kernel

- dockers/docker-dhcp-server/kea-dhcp4.conf.j2
- src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_cfggen.py
- src/sonic-dhcp-utilities/tests/test_data/kea-dhcp4.conf.j2
- src/sonic-dhcp-utilities/tests/test_data/mock_config_db.json
- src/sonic-dhcp-utilities/tests/test_dhcp_cfggen.py
DHCP default route shoule be an optional config to DHCP client
- Microsoft ADO **(number only)**: 30877295
Support to do not send default route to dhcp client
1. UT
2. Install new image to test
> [dhcp_server] Support scenario that gatway is not configured

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
This change is done because the DPUs are initalized with the `SonicDpu` type from sonic-config-engine https://github.com/sonic-net/sonic-buildimage/blob/9b9da85f5072e2b7e6ff3058ab816b73e7cb491c/src/sonic-config-engine/config_samples.py#L148
This is added to the yang models in order to yang validation doesn't fail
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/21111
Added `SonicDpu` type in src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
> [Smartswitch] Add `SonicDpu` to the type in DEVICE_METADATA yang model

- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/buffers_defaults_objects.j2
To fix buffers_defaults_object.j2 issues:
- missing comma
- missing table name
- use of a removed profile
Updated the file to add comma, table name and use an existing profile
config load_minigraph on the switch with Mellanox-SN5600-C256S1 SKU
> [Mellanox] Fix SN5600 buffers_defaults_objects.j2

- platform/mellanox/mlnx-platform-api/sonic_platform/platform.py
Since the 202411 branch will not have the PMON changes for Smartswitch, the changes which are already merged need to be reverted (Only the chassis is changed back to original chassis) so that the behaviour is consistent to 202405
Removed `SmartSwitchChassis` from platform initialization
> [202411][Smartswitch][Mellanox] Aligned platform with 202411 changes

- src/sonic-frr/dplane_fpm_sonic/dplane_fpm_sonic.c
- src/sonic-frr/patch/0080-SRv6-vpn-route-and-sidlist-install.patch
- src/sonic-frr/patch/series
Add SIDLIST and VPN routes install fpmsyncd with SONIC-FRR communication channel.
Add SIDLIST and VPN routes install fpmsyncd with SONIC-FRR communication channel.
Switch to this communication channel,  SRv6 vpn routes and sidlist install OK.
Add SIDLIST install.
Add SRv6 VPN routes install
> SONiC-FRR communication channel support srv6 vpn

- dockers/docker-sonic-bmp/critical_processes
- dockers/docker-sonic-bmp/supervisord.conf
- src/sonic-bmpcfgd/bmpcfgd/bmpcfgd.py
- src/sonic-bmpcfgd/tests/bmpcfgd_test.py
Previously critical_process was defined duplicated like below:
group:sonic-bmp
program:openbmpd
program:bmpcfgd
which break some mgmt test cases.
- Microsoft ADO **(number only)**:30807821
Get rid of group and follow most of other dockers to define program directly.
verified on DUT, program could work correctly.
> Fix bmp critical_process duplicated bug

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
Mellanox SN5600, SN5640 SIMX platform does not support cpu thermal sensors
Update DEVICE_DATA configuration for the SIMX platform
Check no error exists in syslog
> [Mellanox] [SIMX] Disable cpu_pack and comex_amb for SN5640 and SN5600 

- platform/mellanox/mlnx-platform-api/sonic_platform/inotify_helper.py
During smartswitch initialization, an error is observed during switch bootup. ztp disable runs decode-eeprom.
```
sonic ERR decode-syseeprom: Failed to obtain EEPROM object due to ValueError("invalid literal for int() with base 10: ''"), 
Traceback: Traceback (most recent call last):
#012  File "/usr/local/bin/decode-syseeprom", line 35, in instantiate_eeprom_object#012    eeprom = sonic_platform.platform.Platform().get_chassis().get_eeprom()
#012             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#012  File "/usr/local/lib/python3.11/dist-packages/sonic_platform/platform.py", line 35, in __init__
#012    self._chassis = SmartSwitchChassis()#012                    ^^^^^^^^^^^^^^^^^^^^
#012  File "/usr/local/lib/python3.11/dist-packages/sonic_platform/chassis.py", line 1207, in __init__
#012 …
```
> [Mellanox] Handle exception during Inotify import

- src/sonic-py-common/sonic_py_common/device_info.py
There is a corner case where the MAC address includes a trailing "\n" character in the config_db.json file, leading to switch configuration failure.
- Microsoft ADO **(number only)**: 28355624
To prevent this issue, the final return statement now explicitly strips the MAC in all cases from get_system_mac().
Load the new image to verify the mac does not contain any trailing unnecessary characters in the config_db.json file/
> [sonic-py-common] Strip the MAC before returning from get_system_mac()

- files/build_templates/sonic_debian_extension.j2
Prevent SONiC packages been overwrite by official version
FIPS break on 202405 and later version, because openssl and libk5crypto3 Debian offical version higher than FIPS version, so FIPS openssl been upgrade when install python-dbus:
+ sudo LANG=C DEBIAN_FRONTEND=noninteractive chroot ./fsroot-mellanox apt-get -y install python3-dbus
Reading package lists...
Building dependency tree...
Reading state information...
python3-dbus is already the newest version (1.3.2-4+b1).
The following additional packages will be installed:
libk5crypto3 openssl <== python3-dbus depends on  libk5crypto3 and openssl 
Suggested packages:
krb5-doc krb5-user
The following packages will be upgraded:
libk5crypto3 openssl
2 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
...
Unpacking …
> Prevent FIPS packages been overwrite by official version

- src/sonic-config-engine/config_samples.py
Currently the complete `DPUS` section in the platform.json is copied to the CONFIG_DB by `sonic-cfggen`, leading to yang validation failures if we add any additional information which is irrelevant for CONFIG_DB. 
Added only `midplane_interface` key from the `DPUS` section in the platform.json
> [Smartswtich] Add only necessary information for DPUS in smartswitch

- rules/sonic-fips.mk
Upgrade SymCrypt version to 1.5.2
SymCrypt release new version:
upstream SymCrypt upgrade to v103.8.0
upstream SymCrypt-Openssl upgrade to1.7.0
- Microsoft ADO: 31063369
Upgrade SymCrypt and SymCrypt-Openssl to latest version
Pass all UT.
- [] 
Upgrade SymCrypt version to 1.5.2
> Upgrade SymCrypt version to 1.5.2

- files/build_templates/sonic_debian_extension.j2
Prevent SONiC packages been overwrite by official version
Cherry-pick PR https://github.com/sonic-net/sonic-buildimage/pull/21530
FIPS break on 202405 and later version, because openssl and libk5crypto3 Debian offical version higher than FIPS version, so FIPS openssl been upgrade when install python-dbus:
+ sudo LANG=C DEBIAN_FRONTEND=noninteractive chroot ./fsroot-mellanox apt-get -y install python3-dbus
Reading package lists...
Building dependency tree...
Reading state information...
python3-dbus is already the newest version (1.3.2-4+b1).
The following additional packages will be installed:
libk5crypto3 openssl <== python3-dbus depends on  libk5crypto3 and openssl 
Suggested packages:
krb5-doc krb5-user
The following packages will be upgraded:
libk5crypto3 openssl
2 upgraded, 0 newly …
> [202405] Prevent FIPS packages been overwrite by official version

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
- src/sonic-frr-mgmt-framework/templates/bgpd/bgpd.conf.db.addr_family.evpn.j2
- src/sonic-frr-mgmt-framework/tests/test_config.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/bgp.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp.json
- src/sonic-yang-models/yang-models/sonic-bgp-global.yang
advertise-svi-ip allows the switch to participate in the L2 VXLAN via its unique IP address.
https://docs.frrouting.org/en/latest/bgp.html#evpn-advertise-svi-ip
Updated yang models, frr-mgmt-framework, jinja2 templates, and test cases.
Test cases have been updated for verification purposes.
[frr-mgmt-framework]: VXLAN EVPN should support advertise-svi-ip
No relevant section exists in Configuration.md to document change. 
Signed-off-by: Brad House (@bradh352)
> [frr-mgmt-framework]: VXLAN EVPN should support advertise-svi-ip

- platform/mellanox/mlnx-fw-upgrade.j2
- platform/nvidia-bluefield/installer/install.sh.j2
Apply DPU NIC FW configuration after the FW upgrade to ensure that DPU runs with the required configuration.
The change is temporary and will be removed after the configuration becomes part of the FW.
Extend the FW upgrade script to apply the configuration after the FW installation.
Run sonic-mgmt tests.
> [nvidia-bluefield] Apply FW configuration after the FW upgrade.

- platform/marvell/sai.mk
Updating SDK SAI debian version to 1.15.1-1 and integrate fixes in SDK driver.
Verified by running SONIC PTF.
> [Marvell] Update SAI SDK and driver

- files/build_templates/sonic_debian_extension.j2
- platform/mellanox/rshim/files/rshim.sh
- platform/mellanox/smartswitch/dpumap.sh
- platform/mellanox/sonic-bfb-installer.sh
Introduce `dpumap.sh` script, Which provides the following mappings:
`dpu2pcie` - This subcommand provides mapping from dpu to pcie, If dpu name is provided then pcie is returned
`dpu2rshim` - This subcommand provides mapping from dpu to rshim, If dpu name is provided then pcie is returned
`rshim2dpu` - This subcommand provides mapping from rshim to dpu, If rshim is provided then dpu name is returned
`rshim2pcie` - This subcommand provides mapping from rshim to pcie, If rshim is provided then pcie is returned
`pcie2dpu` - This subcommand provides mapping from pcie to dpu, If pcie is provided then dpu name is returned
`pcie2rshim` - This subcommand provides mapping from pcie to rshim, If pcie is provided then rshim is returned
The command also accept multiple inputs which returns the …
> [Mellanox][Smartswitch] Mapping script for pci rshim and dpu data

- src/sonic-yang-models/tests/yang_model_tests/tests/static_route.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/static-route.json
- src/sonic-yang-models/yang-models/sonic-static-route.yang
Fix issue #21352 
According to the Static Route HLD, the nexthop-vrf field should be optional:
<pre>
;Defines IP static route  table
;
;Status: stable
key                 = STATIC_ROUTE|vrf-name|prefix ;
vrf-name            = 1\*15VCHAR ; VRF name
prefix              = IPv4Prefix / IPv6prefix
nexthop             = string; List of gateway addresses;
ifname              = string; List of interfaces
distance            = string; {0..255};List of distances.
Its a Metric used to specify preference of next-hop
if this distance is not set, default value 0 will be set when this field is not configured for nexthop(s)
nexthop-vrf         = string; list of next-hop VRFs. It should be set only if ifname or nexthop IP  is not
in the current VRF . The value is set to VRF name
to which the interface or …
> [YANG][Bugfix] Fix incorrect pattern of nexthop-vrf in sonic-static-route.yang

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/port_config.ini
Microsoft requested that we update port_config.ini - we use hwsku.json so didnt see this locally - but some tools are being used that require port_config.ini
Changed the lanes to match platform.json
Generate a config_db.json using the port_config.ini
202411
Update 7060X64PEO128S2 hwsku port_config.ini
> Update O128S2 port_config.ini

- platform/mellanox/mlnx-platform-api/sonic_platform/module.py
When a user uses TACACS credentials without permissions this causes `show interfaces status` failure, because the chassis is initialized in this case, and without permissions we get the following error: 
`RuntimeError: Unable to connect to redis (unix-socket) - Permission denied(1): Cannot assign requested address`
Tested fix on a different image, 
Changed path to not use unix socket path
As a TACACS user, try `show interfaces status` the command shouldnt fail
> [Mellanox][Smartswitch] Fix for platform chassis initialization   

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-C224O8/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-C224O8/buffers_defaults_t1.j2
The values in this config were found to be incorrect when testing. With fewer interfaces than the C256, the reserved buffer space is smaller and therefore the shared limit in this config must be smaller.
The BUFFER_QUEUE macro was also not present, causing the defaults to be used which referenced lossless profiles.
> Fix buffer configs for TH5 C224 SKU

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json
- src/sonic-yang-models/yang-models/sonic-port-qos-map.yang
Add missing field introduced from PR: https://github.com/sonic-net/sonic-buildimage/pull/21395
- Microsoft ADO **(number only)**: 31313829
Add the missing field
UT in sample_config_db.json
Also test in specific DUT after merge this change.
before:
```
sonic_yang(3):All Keys are not parsed in PORT_QOS_MAP
dict_keys(['Ethernet16'])
sonic_yang(3):exceptionList:["'tc_to_dscp_map'"]
```
after:
```
sonic_yang(6):Note: Below table(s) have no YANG models: bgpraw
```
> [YANG] Add missing field in port qos map

- files/scripts/core_cleanup.py
Improve existing core_cleanup.py to clean old dump/kernel dump. 
On small disk device, dump file will cause disk full issue.
- Microsoft ADO: 30847835
Delete expired dump files
Only keep 4 kernel dump files.
Pass all UT.
Add new UT to cover this script.
Manually verified:
admin@vlab-01:~$ sudo ls /var/dump/
sonic_dump_bjw-can-7260-8_20230125_030042.tar.gz  sonic_dump_bjw-can-7260-8_20250125_030043.tar.gz  sonic_dump_bjw-can-7260-8_20250125_030045.tar.gz
sonic_dump_bjw-can-7260-8_20250125_030042.tar.gz  sonic_dump_bjw-can-7260-8_20250125_030044.tar.gz  sonic_dump_bjw-can-7260-8_20250125_030046.tar.gz
admin@vlab-01:~$ sudo ls /var/core/
orchagent.1644957238.46.core.gz  orchagent.1944957232.46.core.gz  orchagent.1944957234.46.core.gz  orchagent.1944957236.46.core.gz …
> Improve existing core_cleanup.py to clean old dump/kernel dump. 

- rules/config
Update default build options which breaks mellanox's build.
This change is already in pipeline file but not in config file.
Local build will meet error. Now update default build config.
> [build] Update default reproducible build options.

- src/sonic-yang-models/yang-models/sonic-srv6.yang
Previously, we didn't allow the func_len to zero in YANG model, which conflicts with our use case.
Change the lower bound of the func_len's range.
Configure a locator entry in CONFIG_DB and then do a config reload.
> allow func_len to be 0 in sonic-srv6.yang

- dockers/docker-fpm-frr/base_image_files/TSA
- dockers/docker-fpm-frr/base_image_files/TSB
- files/scripts/startup_tsa_tsb.py
- files/scripts/swss.sh
Fixes issue: https://github.com/sonic-net/sonic-buildimage/issues/21586
- Microsoft ADO **31196012**:
Run TSA-TSB service upon swss/swss0/swss1/.. startup. If the service is already running, reset the TSA-TSB timer.
Ran the T2 process crash sonic-mgmt snappi test to verify the convergence.
Before fix: ~10second
After Fix: <10ms
SONiC.20240532.04
> T2-Route-Conv: Process Crash Optimization

- device/mellanox/x86_64-mlnx_msn2700-r0/pmon_daemon_control.json
As chassisd starts automatically for 202411 on smartswitch platforms, this is not required for 202411 on mellanox platforms since we are operating the Smartswitch and the DPUs in dark mode and the DPUs would be powered off
Added skip_chassisd = True for 202411 only
> [Mellanox][Smartswitch] Skip chassisd for 202411 release

- files/build_templates/sonic_debian_extension.j2
- files/image_config/ntp/hwclock.service
- files/image_config/ntp/hwclock.timer
Currently, during runtime, because of the options that we start ntpd with, ntpd will never tell the kernel that the time is synchronized. This means that during runtime, the hardware clock will never get updated with the current system clock, which means that if there's an unexpected power loss/reboot, then the device will come up with an incorrect time. (In our regular reboot scripts, we explicitly write the system time to the hardware clock, so that is covered.)
- Microsoft ADO **(number only)**: 31121257
To handle that, add a timer and service to update the hardware clock with the current system time every hour. This makes sure that if the device does get rebooted for whatever reason, then the time is close to correct. The first run will happen 30 minutes after bootup.
``` …
```
> [202411] Add a service to sync the system time with the RTC

- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Support yang model for bulk size per counter
HLD: https://github.com/sonic-net/SONiC/pull/1864
> Support yang model for bulk size per counter

- device/mellanox/x86_64-mlnx_msn2700-r0/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O28/pmon_daemon_control.json
- device/mellanox/x86_64-nvidia_sn4280-r0/pmon_daemon_control.json
The fix previously developed on 202411 to skip chassisd for Smartswitch does not work for specific HWSKUs. Removed link and added it specifically for 202411. 
> [Mellanox][Smartswitch] Fix chassisd issue for specific SKU

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_reboot
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_reboot
No need to remove /sys/firmware/efi/efivars/dump* in the platform_reboot since pstore has handled them in 202405 branch and after
- Microsoft ADO **[31408729]**:
Commented out the line "rm /sys/firmware/efi/efivars/dump* " in platform_reboot script. These dump files have been handled by pstore.
1) Trigger system crash to reboot
2) after the system boot up, check if there is any /sys/firmware/efi/efivars/dump*  files -- there should not be any.
-
> [Nokia][chassis] Update Nokia-IXR7250E chassis device data

- .azure-pipelines/docker-sonic-mgmt.yml
Previously, the sonic-mgmt image encountered an issue where the SSH configuration was overly permissive, preventing the Docker container from starting successfully. The error message is provided below. This PR addresses and resolves the issue.
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/etc/ssh/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for …
```
> Fix ssh too open permission issue in sonic-mgmt image.

- scripts/build_mirror_config.sh
Recently microsoft owned debian mirror has an issue. It is using the latest timestamp '20250216'. And this snapshot is a bad snapshot. Bydesign we should use timestamp '20250130', which passed PR validation.
```
Get:18 http://packages.trafficmanager.net/snapshot/debian-security/20250216T001420Z bullseye-security/non-free amd64 Packages [1164 B]
Get:19 http://packages.trafficmanager.net/snapshot/debian-security/20250216T001420Z bullseye-security/main amd64 Packages [346 kB]
Fetched 17.9 MB in 5s (3789 kB/s)
Reading package lists...
E: Failed to fetch http://packages.trafficmanager.net/snapshot/debian-security/20250216T001420Z/dists/bullseye-security/main/source/Sources.xz  File has unexpected size (234932 != 234820). Mirror sync in progress? [IP: 13.107.246.71 80]
Hashes of expected file: …
```
> [build] Fix debian mirror snapshot timestamp not work issue.

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_updater.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal_updater.py
Nvidia thermal control service requires to set temperature file value to 0 when module is not present 
Set temperature file value to 0 when module is not present 
Additional unit test
Manual test to check when module is present and not present. This is not covered on the sonic-mgmt testbed.
> [Mellanox] set temperature file value to 0 when module is not present

- platform/broadcom/sai.mk
Fix #21680 
- Microsoft ADO **(number only)**: 31426582
- Re-compile SAI 12.3 with SAI header from https://github.com/opencomputeproject/SAI/tree/054085547c2042b95ab0fa1a75a44da3288b26bf
Load image on a DUT, all dockers are up and running.
```
admin@bjw2-can-7260-7:~$ show ver
SONiC Software Version: SONiC.master-21746.772945-f8fc18c02
SONiC OS Version: 12
Distribution: Debian 12.9
Kernel: 6.1.0-22-2-amd64
Build commit: f8fc18c02
Build date: Fri Feb 14 13:38:43 UTC 2025
Built by: azureuser@92044be7c000000
Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-D108C8
ASIC: broadcom
ASIC Count: 1
Serial Number: JPA2403P2YQ
Model Number: DCS-7260CX3-64
Hardware Revision: 03.00
Uptime: 11:34:43 up 6 min,  1 user,  load average: 1.05, 1.28, 0.69
Date: Sun 16 Feb 2025 11:34:43
Docker images: …
```
> [Broadcom] Fix syncd crash issue and upgrade xgs SAI to 12.3.2.2

- dockers/docker-sonic-mgmt/Dockerfile.j2
The `pytest-stress` package is only compatible with Python 3. Trying to install it with Python 2 leads to a build failure for the sonic-mgmt docker image.
> Don't install pytest-stress in python2 environment

- dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_chasiss_packet.conf
Initially I made the change that Fallback Route [routes from AH on Upstream LC] not to get programmed [mark them as deny]  on Downstream LC's as reasoning was that on Downstream LC's can forward them based on Default-route. However that assumption is correct for example we have topology like this:
RH is connected to ASIC0 of Upstream LC
AH is connected to ASIC1 of Upstream LC
Downstream LC will learn route from RH [including default-route] and will only forward to ASIC0 of upstream LC .  Above assumption was fine if we always have AH and RH connected to same ASIC of Upstream LC.
How I verify:
UT updated
Manual Verification.
> [chassis-packet] Allow Fallback Route to get programmed on Downstream LC

- dockers/docker-sonic-mgmt/Dockerfile.j2
Modify the sonic-mgmt Dockerfile to install the conserver package. This is needed for running dut_console tests through a conserver connection.
Compiled build and ran conserver commands
> Add conserver to sonic-mgmt container

- .azure-pipelines/docker-sonic-mgmt-py3-only.yml
Previously, the sonic-mgmt image encountered an issue where the SSH configuration was overly permissive, preventing the Docker container from starting successfully. The error message is provided below. This PR addresses and resolves the issue.
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/etc/ssh/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for …
```
> Fix ssh too open permission issue in py3only sonic-mgmt docker image.

- platform/nvidia-bluefield/installer/create_sonic_image
- platform/nvidia-bluefield/installer/install.sh.j2
To ensure the Linux kernel and MFT drivers' signatures are aligned, load the MFT drivers in the BFB installer from the SONiC image root filesystem
Mount SONiC image rootfs and load drives from the rootfs.
Compile and install BFB image. DPU NIC FW upgrade should finish successfully during the image installation
> [nvidia-bluefield] Load MFT drivers from the SONiC rootfs during BFB installation.

- device/arista/x86_64-arista_7800r3a_36d_lc/pmon_daemon_control.json
- device/arista/x86_64-arista_7800r3a_36d_lc/system_health_monitoring_config.json
- device/arista/x86_64-arista_7800r3a_36d_lc/thermal_policy.json
- device/arista/x86_64-arista_7800r3a_36dm2_lc/pmon_daemon_control.json
- device/arista/x86_64-arista_7800r3a_36dm2_lc/system_health_monitoring_config.json
- device/arista/x86_64-arista_7800r3a_36dm2_lc/thermal_policy.json
- device/arista/x86_64-arista_7800r3a_36p_lc/pmon_daemon_control.json
- device/arista/x86_64-arista_7800r3a_36p_lc/system_health_monitoring_config.json
- device/arista/x86_64-arista_7800r3a_36p_lc/thermal_policy.json
- device/arista/x86_64-arista_7800r3ak_36d2_lc/pmon_daemon_control.json
- device/arista/x86_64-arista_7800r3ak_36d2_lc/system_health_monitoring_config.json
- device/arista/x86_64-arista_7800r3ak_36d2_lc/thermal_policy.json
- device/arista/x86_64-arista_7800r3ak_36dm2_lc/pmon_daemon_control.json
- device/arista/x86_64-arista_7800r3ak_36dm2_lc/system_health_monitoring_config.json
- device/arista/x86_64-arista_7800r3ak_36dm2_lc/thermal_policy.json
In https://github.com/sonic-net/sonic-buildimage/pull/21512 we created separate directories for the different Wolverine SKUs but the `pmon_daemon_control.json` symlink was moved to the non-LC file in `x86_64-arista_common`
> Fixing Wolverine LC's incorrect symlinks

- dockers/docker-sonic-gnmi/gnmi-native.sh
- dockers/docker-sonic-telemetry/telemetry.sh
- src/sonic-yang-models/yang-models/sonic-gnmi.yang
- src/sonic-yang-models/yang-models/sonic-telemetry.yang
Enable gnmi/telemetry user authorization by config_db.
gnmi/telemetry user authorization flag not used in SONiC and can't config by config_db
- Microsoft ADO: 30808849
Update Yang model and update gnmi/telemetry start script.
Pass all UT.
- [] 
Enable gnmi/telemetry user authorization by config_db.
> Enable gnmi/telemetry user authorization by config_db

- installer/default_platform.conf
- platform/marvell/platform_arm64.conf
* To optimization installer for marvell arm64 to use create and mount partition logic from default_platform.conf. 
* Given that current default_platform.conf only allows install on same disk as ONIE. Add support for install block device selection.
* Add support for scsi block devices. 
* Use implementation from default_platform.conf for create and mount partition and remove the implementation in platform_arm64.conf.
* Add option to override install block device in default_platform.conf. Also added logic to select the install block device from platform_arm64.conf.
* Added support for selecting scsi disk as install device in platform_arm64.conf. This also needed changes to u-boot env variable.
* Changed to UUID based 'root' disk selection to have a generic …
> [Marvell][arm64] Installer optimization 

- scripts/build_mirror_config.sh
[PR21366](https://github.com/sonic-net/sonic-buildimage/pull/21366/files) wants to use debian snapshot instead of version pinning to improve image quality. But it missed this change. Build is using latest debian snapshot instead of validated snapshot.
Now validated snapshot is '20250130'. details in this [link](https://github.com/sonic-net/sonic-buildimage/blob/master/files/build/versions/default/versions-mirror). But we can find build is using '20250216', which is a bad snapshot. It breaks SONiC build since Feb 16.
```
Get:18 http://packages.trafficmanager.net/snapshot/debian-security/20250216T001420Z bullseye-security/non-free amd64 Packages [1164 B]
Get:19 http://packages.trafficmanager.net/snapshot/debian-security/20250216T001420Z bullseye-security/main amd64 Packages [346 kB]
Fetched …
```
> [build] Fix debian mirror snapshot timestamp not work issue. (#21758)

- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
Reverts sonic-net/sonic-buildimage#21795
Due to sanity failures:
------------------------------ live log teardown -------------------------------
21:03:52 memory_utilization.handle_memory_thresho L0089 WARNING| [ALARM]: monit:memory_usage, Current memory usage 92.0 exceeds high threshold 90.0
route/test_route_perf.py::test_perf_add_remove_routes[4-vlab-03-None] ERROR [ 50%]Sunday 23 February 2025  21:03:52 +0000 (0:00:00.622)       0:06:13.756 *******
> Revert "[202411] Disabling ports by adding parameter ‘-P 0’"

- files/scripts/startup_tsa_tsb.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/21816
- Microsoft ADO **31499777**:
Setting the STATE_DB ALL_SERVICE_STATUS|tsa_tsb_service flag first as part of startup_tsa_tsb service, followed by configuring TSA.
And as part of the case, when tsa_ena is False (genuine or due to race condition), we explictly call TSA again to ensure all asics go to TSA state.
Reboot the multi-asic linecard, and validate that all asics are in TSA state and TSA-TSB timer is running
config_reload
Tested following scenarios:
1. reboot multi-asic linecard
2. config reload
3. execute TSA while the service is running
4. TSA, config save and then config_reload
5. execute TSB while the service is running
20240532.08
> Fix TSA-TSB race condition on multi-asic platforms

- dockers/docker-snmp/snmpd.conf.j2
Related to [PR#16187](https://github.com/sonic-net/sonic-buildimage/issues/16187)
When you configure an SNMP agent address with a VRF, the snmpd service will fail to properly start after the configuration has been applied. The snmpd service shows a status of "FATAL."
```
sudo config snmpagentaddress add 1.1.1.1 -p 161 -v mgmt
docker exec -it snmp supervisorctl status | awk '{print $1, $2}'
dependent-startup RUNNING
rsyslogd RUNNING
snmp-subagent STOPPED
snmpd FATAL
start EXITED
supervisor-proc-exit-listener RUNNING
```
Corrected syntax in the jinja template used to generate the snmpd.conf within the SNMP docker container.
```
sudo config snmpagentaddress add 1.1.1.1 -p 161 -v mgmt
docker exec -it snmp supervisorctl status | awk '{print $1, $2}' …
```
> [SNMP] Fix config template issue when setting snmpagentaddress

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
Fix the issue with the position calculation of the sensors with discrete indexes.
Pass the base position into `create_discrete_thermal` function instead of initializing the position with 1.
Run `snmp/test_snmp_phy_entity.py` sonic-mgmt test on the platform with discrete sensors.
> [Mellanox] Fix the issue with sensors with discrete indexes initialization

- files/image_config/monit/mgmt_oper_status.py
- files/image_config/monit/tests/test_mgmt_oper_status.py
…in STATE_DB
Currently Management interface related data is present in CONFIG_DB and 'oper_status' is present in STATE_DB MGMT_PORT_TABLE.
This PR change is made to ensure that all telemetry data related to management interface is present in STATE_DB.
- Microsoft ADO **27597775**:
Update mgmt_oper_status monit script to update all fields from CONFIG_DB MGMT_PORT table.
Unit test added for the change and passed:
```
/sonic/files/image_config/monit$ pytest-3 tests/test_mgmt_oper_status.py 
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.11.2, pytest-7.2.1, pluggy-1.0.0+repack
rootdir: …
```
> Update management interface related configuration in MGMT_PORT_TABLE STATE_DB

- device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O28/buffers_defaults_objects.j2
- files/build_templates/buffers_config.j2
- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4700-o28-t1-smartswitch.json
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4700-o28-t1-smartswitch_dyn.json
PG's 3 & 4 for Internal ports today have lossy buffer profiles attached, but this is redundant and can be removed as they occupy extra overhead even though it's not significant
Make the cable length for Dpc ports to 0m and create a new TC_PG_MAP for internal ports
Run config qos reload --no-dynamic-buffer, config save -y and config reload -y
```
redis-cli -n 4 hget "CABLE_LENGTH|AZURE" Ethernet224
"0m"
redis-cli -n 4 hget "PORT_QOS_MAP|Ethernet232" tc_to_pg_map
"AZURE_DPC"
root@r-bobcat-01:/home/admin# sonic-db-cli CONFIG_DB HGETALL "TC_TO_PRIORITY_GROUP_MAP|AZURE_DPC"
{'0': '0', '1': '0', '2': '0', '3': '0', '4': '0', '5': '0', '6': '0', '7': '7'}
redis-cli -n 0 keys "BUFFER_PG*Ethernet232*"
1) "BUFFER_PG_TABLE:Ethernet232:0"
redis-cli -n 0 keys …
```
> [SmartSwitch] [Nvidia] Remove PG 3 and 4 for Internal Ports

- dockers/docker-ptf/Dockerfile.j2
Adding freeradius package to docker-ptf to help with RADIUS sonic-mgmt testing.
In a subsequent PR in the sonic-mgmt repo, I will add RADIUS tests, and there needs to be a consumable RADIUS server in the infrastructure. 
Added the `freeradius` package the ptf docker j2 file. 
I build the new docker image locally and then ran few succesfull app-topo tasks inside of sonic-mgmt.  Also verifed that freeradius is installed.
```
make target/docker-ptf.gz
docker load < target/docker-ptf.gz
docker start docker-ptf:lastest
Then inside the docker image:
dt@usschq-asser-t002:~/sonic-buildimage/target$ docker exec -it fe bash
root@fe0000e7dfd0:~# freeradius -v
radiusd: FreeRADIUS Version 3.0.17, for host x86_64-pc-linux-gnu, built on Feb 24 2023 at 12:52:21
FreeRADIUS Version 3.0.17
Copyright (C) …
```
> Add freeRADIUS package to docker-ptf 

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/tests/test_eeprom.py
To return the correct Model Number for MLNX platforms rather than Part Number.
For SPC1-3 read it from eeprom.part_number and for SPC4 and newer read it from VPD file, SYS_DISPLAY value.
Manual testing: 'show platform summary' for each spectrum.
>  [Mellanox] Update the method of reading model number for MLNX platforms

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- src/sonic-device-data/tests/permitted_list
With the current fap initialization sequence, multiple faps in a modular system could come up with  stand alone mode. This is not a recommended configuration.  It might mess up the global clock and might ends up with traffic issue.  
https://github.com/sonic-net/sonic-buildimage/issues/21866
This change adds a required minimum number of links have to be ready before enabling traffic on a fap, which based on the guidance should be able to guarantee the faps in a modular system can form a proper topology.
We manually tested image on a modular system and the topology after boot up looks correct, and there is no more than 1 fap come up with stand alone mode.  We also tested traffic on our system setup and all looks good so far. 
**This change also need to go to 202405.** 
- Microsoft ADO …
> Add link requirement per sku before enabling traffic on a fap

- src/sonic-frr/patch/0082-Revert-bgpd-upon-if-event-evaluate-bnc-with-matching.patch
- src/sonic-frr/patch/series
Fixing route update on duplicate link up event in promiscuous mode. When running tcpdump on interfaces which have BGP neighbors a duplicate link up event is received as the interface enters promiscuous mode. However these shouldn't trigger route updates. Due to the commit [58592be57783a3b24e7351af2a5afc61299768df](https://github.com/FRRouting/frr/commit/58592be57783a3b24e7351af2a5afc61299768df) route updates are published.
```
2025 Feb 19 18:00:14.893285 r-leopard-72 DEBUG bgp#zebra[36]: [V6YM8-PV4KB] MESSAGE: ZEBRA_INTERFACE_UP PortChannel101 vrf default(0)
2025 Feb 19 18:00:14.893492 r-leopard-72 INFO bgp#staticd[49]: [YGHNZ-57CJY] Interface enabled Removing. PortChannel101 SIDs that depend on the interface
2025 Feb 19 18:01:17.900554 r-leopard-72 DEBUG bgp#zebra[36]: [V6YM8-PV4KB] …
```
> [FRR] Fixing route update on duplicate link up event in promiscuous mode

- sonic-slave-bullseye/Dockerfile.j2
The latest version of setuptools-scm i.e. 8.2.0 does not support bdist_wheel. Hence there is a failure in target docker-syncd-rpc.gz due to ptf-py3 build failure. On further investigation found that bookworm installs 8.0.4 version of this package. Hence added this to the current Dockerfile.j2 of sonic-slave-bullseye. This will make it consistent with the earlier build process for ptf-py3 which used 8.1.0 version of setuptools-scm and also the sonic-slave-bookworm
To fix build failure of ptf-py3 on Bullseye
Investigated the build failure and found that the recent update i.e. 8.2.0 of setuptools-scm python package does not support bdist_wheel
Built ptf-py3 and subsequently docker-syncd-rpc.gz with these changes. After the build sanity testing also has been …
> Build fix for ptf-py3 issue on bullseye

- src/sonic-bgpcfgd/bgpcfgd/managers_advertise_rt.py
- src/sonic-bgpcfgd/bgpcfgd/managers_bbr.py
- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
- src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
- src/sonic-bgpcfgd/tests/test_advertise_rt.py
- src/sonic-bgpcfgd/tests/test_bbr.py
- src/sonic-bgpcfgd/tests/test_static_rt.py
Previously, Bgpcfgd generated groups of BGP configuration commands that did not have proper terminating commands. As a consequence, non-BGP configuration commands following the BGP configuration command may be rejected by the FRR because of FRR's context was not properly switched. You check the details in Issue #21829.
Fix #21829 
Add exit and exit-address-family command at the end of BGP configuration command groups.
> [Bgpcfgd]Add correct terminating commands at the end of BGP config command groups

- files/build_templates/sonic_debian_extension.j2
when onboard sonic-package-management extension.
It missed to add sonic version label on docker images.
- Microsoft ADO **(number only)**: 25662623
Check build logs. label is added with this PR.
> [build] Fix command docker images missing name and tag issue.

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Enhance yang model for networking-metadata.
Adding a new field in device metadata YANG model to distinguish the management type of the device. Depends on the users, this field can be used to tell the purpose of deployment or who/how the device is being managed.
- Microsoft ADO **(number only)**: 
This change adds a new field called mgmt_type for this purpose.
Unit test.
> Add mgmt_type into device metadata YANG model.

- src/sonic-bgpcfgd/bgpcfgd/directory.py
- src/sonic-bgpcfgd/bgpcfgd/managers_srv6.py
- src/sonic-bgpcfgd/tests/test_srv6.py
Previously, if the SRv6 manager received a config update that added a SRV6_MY_SID entry before its corresponding LOCATOR entry added, the SRv6 manager would not process the SRV6_MY_SID entry and print an ERR syslog. However, during testing, NVIDIA team found that it is possible to have such a scenario in normal operations, especially during config reload. So, we decide to add a dependency-based caching mechanism to handle out-of-order table processing.
This is the first use case where we will dynamically add/remove the dependency, so we also define a new unsubscribe function for the directory class. The reason why we need to remove the dependency in managers_srv6 is because the on_deps_change function will only process the cache when all dependencies are satisfied. If a locator is removed …
> [Bgpcfgd] Add dependency callback logic in SRv6 Manager to handle out-of-order table processing

- files/build_templates/qos_config.j2
Some code were deleted by mistake in https://github.com/sonic-net/sonic-buildimage/pull/21427
Add it back.
There are some ports (PIE ports in cisco platform) don't support buffer/qos config, this is to exclude those ports from PORT_ACTIVE to bypass buffer/qos config.
> Exclude pie ports from qos config

- files/image_config/rsyslog/rsyslog.conf.j2
- src/sonic-config-engine/setup.cfg
- src/sonic-config-engine/tests/sample_output/py3/rsyslog.conf
- src/sonic-config-engine/tests/sample_output/py3/rsyslog_with_docker0.conf
This fix resolves issue with missing certain types of messages while forwarding to the remote server.
Basically, this moves remote syslog forwarding rules to be executed before any other instructions take place,
so everything received by a local syslog instance will be forwarded to the remote machine.
The fix allows remote forwarding of messages defined as:
https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog.d/00-sonic.conf.j2
> [rsyslog]: Remote logging with the highest rule priority

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/subnet_decap.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/subnet_decap.json
- src/sonic-yang-models/yang-models/sonic-subnet-decap.yang
Cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/21118 into 202411
- Microsoft ADO **(number only)**: 30473162
> [202411][YANG] Add yang model to `SUBNET_DECAP` table (#21118)

- files/build_templates/mux.service.j2
- files/scripts/write_standby.py
Mux service is observed not started due to pre operation timeout:
```
2025 Mar  6 12:39:46.192880 vlab-06 NOTICE switch_hash: 'reload' executing with command: config reload -y
2025 Mar  6 12:40:47.490091 vlab-06 INFO systemd[1]: Starting swss.service - switch state service…
2025 Mar  6 12:40:57.156019 vlab-06 INFO systemd[1]: Starting mux.service - MUX Cable Container…
2025 Mar  6 12:41:22.474031 vlab-06 NOTICE swss#tunnelmgrd: :- doTunnelTask: Tunnel MuxTunnel0 task, op SET
2025 Mar  6 12:42:27.344856 vlab-06 WARNING systemd[1]: mux.service: start-pre operation timed out. Terminating.
2025 Mar  6 12:42:27.346562 vlab-06 WARNING systemd[1]: mux.service: Control process exited, code=killed, status=15/TERM
2025 Mar  6 12:43:11.903374 vlab-06 NOTICE swss#orchagent: :- doDecapTunnelTask: …
```
> [dualtor] Fix `mux` start failure due to pre operation timeout

- src/sonic-py-common/sonic_py_common/device_info.py
This pull request includes a small change to the `is_dpu` function in the `src/sonic-py-common/sonic_py_common/device_info.py` file. The change removes a conditional check for `is_smartswitch()` that previously returned `False` if the check failed.
* [`src/sonic-py-common/sonic_py_common/device_info.py`](diffhunk://#diff-b40a22d6ab8d9024c9c74bfeba8a9b2383fe36cbb2226e87a991028ceec7bf7dL627-L629): Removed the `is_smartswitch()` check from the `is_dpu` function.
The condition `if platform_data: return 'DPU' in platform_data` is sufficient to determine whether the platform is a DPU.
Additionally, is_smartswitch() returns False because "DPUS" is not present in platform.json on a DPU.
> [SmartSwitch] is_smartswitch() is not required inside is_dpu() function

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/0/config-ramon-1-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/1/config-ramon-1-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/10/config-ramon-6-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/11/config-ramon-6-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/12/config-ramon-7-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/13/config-ramon-7-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/14/config-ramon-8-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/15/config-ramon-8-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/2/config-ramon-2-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/3/config-ramon-2-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/4/config-ramon-3-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/5/config-ramon-3-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/6/config-ramon-4-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/7/config-ramon-4-1.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/8/config-ramon-5-0.bcm
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/9/config-ramon-5-1.bcm
To accumulate the VOQ counters (CREDIT_WD_DELETE & PACKET_INTEGRITY) , the soc variable sai_instru_stat_accum_enable needs to be set
Added sai_instru_stat_accum_enable to Nokia device files
Verified that the voq counters are accumulated in SAI 12.X
> [Nokia-device][BCM-DNX] Set BCM soc variable to accumulate VOQ counters

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
- src/sonic-frr-mgmt-framework/templates/bgpd/bgpd.conf.db.nbr_af.j2
- src/sonic-frr-mgmt-framework/templates/bgpd/bgpd.conf.db.nbr_or_peer.j2
- src/sonic-frr-mgmt-framework/tests/test_config.py
Handle up/down (in addition to true/false) as admin_status values for BGP_NEIGHBOR_AF and BGP_PEER_GROUP_AF. Currently only true/false is handled, whereas the yang model identifies up/down as valid values of admin_status
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-bgp-common.yang
```
grouping sonic-bgp-cmn-af {
leaf afi_safi {
type string;
description "Address family";
}
leaf admin_status {
type stypes:admin_status;
description "Indicates address family active/inactive status";
}
```
https://github.com/sonic-net/sonic-buildimage/blob/82956752ac0fd8e39c7fdd69d2afc3f8989fa37d/src/sonic-yang-models/yang-templates/sonic-types.yang.j2#L54
``` 
module sonic-types {
   typedef admin_status {
type enumeration {
enum up;
enum down;
}
}
``` …
> frr-mgmt-framework: Handle up/down as well as true/false as admin_status values for bgp neighbor in frrcfgd

- src/sonic-frr-mgmt-framework/templates/frr/frr.conf.j2
During debugging of VXLAN EVPN using unified vs split configuration, the same BGP configuration is made with one exception, the setting of `no fpm use-next-hop-groups` which is forcibly set for all FRR instances.
This change was introduced in PR #12852 when switching to the new fpm dataplane plugin.
When running `vtysh -c "config" -c "no fpm use-next-hop-groups"` it can be seen the VTEP immediately comes online and traffic flows as expected.
This adds the option as is present in dockers/docker-fpm-frr/frr/zebra/zebra.conf.j2 controlled by the DEVICE_METADATA nexthop_group option.
See #21034 for details
master as of 20241205
[frr/bgpd] fix frr VXLAN EVPN configuration for unified config
N/A
Fixes #21034 
Signed-off-by: Brad House (@bradh352)
> [frr/bgpd] fix frr VXLAN EVPN configuration for unified config

- platform/marvell-teralynx/sai.mk
Correcting the debian path to point to 202411 debians.
Updating sai debian path to point to 202411 release debians
Changed the debian path location
show interface status
> [202411] [Marvell-teralynx] Updating SAI debian path

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
since srv6 locator has changed as https://github.com/BYGX-wcr/SONiC/blob/srv6_static_config_hld/doc/srv6/srv6_static_config_hld.md,
add support for bgp srv6 locator config load.
Srv6 test config updated  in: https://github.com/sonic-net/sonic-mgmt/pull/17283
Tested on daily jenkins job
> feat(frrcfgd): update for bgp locator config

- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/main.py
Request in https://github.com/sonic-net/sonic-swss/pull/3406 to allow software BFD to be enabled independent of switch_type 'dpu'. 
Added checks for new config DB entry instead,
"FEATURE": {
"software_bfd": {
"state": "enabled"
}
}
- pytest testcases
- Tested on vs platform by adding software_bfd to config DB.
> Use software_bfd instead of switch_type.

- .azure-pipelines/docker-sonic-mgmt.yml
Before pushing the newly built docker image to the registry, we add a verification step to ensure the image is valid.
Before pushing the newly built Docker image to the registry, we add a verification step to ensure the image is valid.
For ref https://dev.azure.com/mssonic/build/_build/results?buildId=794495&view=results
If the validate step fails, it won't push the image to registry.
> Validate docker image before uploading to registry

- installer/default_platform.conf
Add CSTATE configuration for the AMD CPU to disable CPU idling.
Related to: https://github.com/sonic-net/sonic-buildimage/pull/16339
Add `processor.max_cstate=1 amd_idle.max_cstate=0` to installer default grub config.
Boot the image. Verify the added option are present in `cat /proc/cmdline` command output.
> [installer] Add CSTATE configuration for the AMD CPU.

- .github/ISSUE_TEMPLATE/01-bug.yml
- .github/ISSUE_TEMPLATE/02-enhancement.yml
- .github/ISSUE_TEMPLATE/03-testgap.yml
- .github/ISSUE_TEMPLATE/04-regression.yml
- .github/ISSUE_TEMPLATE/config.yml
Create a structured issue template for bug, enhancement, regression, and testgap.
Create new issue templates
Similar to sonic-mgmt repository
NA
NA
NA
> Add issue template for bug, enhancement, testgap and regression

- src/sonic-yang-models/tests/yang_model_tests/tests/neigh.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/neigh.json
- src/sonic-yang-models/yang-models/sonic-neigh.yang
NEIGH need to support PORTCHANNEL for t1 topology when VLAN is non-existent.
- Microsoft ADO **(number only)**: 31872308
Add portchannel to port as an alllowed leafref
unit test
> [YANG] sonic-neigh.yang need support portchannel

- files/initramfs-tools/union-mount.j2
Revert "Mount the /tmp directory as tmpfs" on 202411 branch. It was introduced by PR #20640.
We need to reconsider the impact to memory utilization of "Mount the /tmp directory as tmpfs". Especially on the platforms with low memory capacity.
- Microsoft ADO **(number only)**: 31874093
Update mount j2 template.
1. Verified by PR test.
2. Install the image built by PR test on DUT, confirmed /tmp is not mount on tmpfs
```
admin@sonic:~$ df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
root-overlay     15G  5.1G  9.2G  36% /
```
> [202411] Revert "Mount the /tmp directory as tmpfs"

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
since srv6 locator and sid config schema have changed as [https://github.com/BYGX-wcr/SONiC/blob/srv6_static_config_hld/doc/srv6/srv6_static_config_hld.md](https://github.com/sonic-net/sonic-mgmt/pull/url), update corresponding frrcfgd code.
> feat(frrcfgd): update for new locator config way

- dockers/docker-ptf/Dockerfile.j2
- dockers/docker-ptf/gnxi-patches/0001-add-xpath_target-option.patch
- dockers/docker-ptf/gnxi-patches/0002-Adding-support-for-subscribe-mode-1.patch
- dockers/docker-ptf/gnxi-patches/0003-gNMI_client-Add-an-option-to-trigger-memory-spike-on.patch
- dockers/docker-ptf/gnxi-patches/0004-Add-support-for-streaming-structured-events-in-night.patch
- dockers/docker-ptf/gnxi-patches/0005-Enhance-gnmi_cli_py-4.patch
- dockers/docker-ptf/gnxi-patches/series
Change PTF docker image to use GNXI from google repo
Currently PTF docker using GNXI from a private repo
Change PTF docker image to use GNXI from google repo
Generate patch file from private repo and apply to google repo.
Pass all test case.
Download ptf docker image and verified the patched GNXI is same with private repo.
Change PTF docker image to use GNXI from google repo
> Change PTF docker image to use GNXI from google repo

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_pytests/test_smart_switch.py
- src/sonic-yang-models/yang-models/sonic-smart-switch.yang
Updated DPU_LIST table to follow:
DPU|<DPU_NAME>:                        ; Eg DPU name “str-8102-t1-dpu0” 
- state: up|down	               ; admin state of DPU device  
- local_port: port_name ; Physical port<Ethernet-BP0> 
- vip_ipv4: ipv4 prefix    ; Optional  
- vip_ipv6: ipv6 prefix    ; Optional  
- pa_ipv4: ipv4 pa ip     ; from minigraph  
- pa_ipv6: ipv6 pa ip     ; from minigraph  
- dpu_id: id of dpu       ; <0-7> from minigraph 
- vdpu_id: id of vdpu     ; <guid> from minigraph  
- gnmi_port: TCP listening port for gnmi service on DPU 
- orchagent_zmq_port: TCP listening port for ZMQ service on DPU orchagent 
- Microsoft ADO **(number only)**: 31582203
1. Container DPU_PORT renamed to DPU.
2. Added new fields to the DPU_LIST container:
- dpu_id: ID of the DPU from minigraph.
- …
> [smartswitch][YANG] Add new fields to the DPU_LIST container in the sonic-smart-switch YANG module

- src/sonic-config-engine/config_samples.py
- src/sonic-config-engine/tests/sample_output/t1-smartswitch-dpu.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
type changed from SonicSpu to SmartSwitchDPU
- Microsoft ADO **(number only)**: 31841870
> [smartsiwtch][YANG]Rename SonicDpu to SmartSwitchDPU

- files/build/versions/dockers/docker-sonic-vs/versions-py3
The build failed in 202311 due to an error while installing PyGObject 3.46.0, caused by a dependency conflict:
```
ERROR: Cannot install sonic-host-services==1.0 because these package versions have conflicting dependencies.
The conflict is caused by:
sonic-host-services 1.0 depends on pycairo==1.26.1
The user requested (constraint) pycairo==1.24.0
```
Our system includes a fallback mechanism that attempts to install the latest available package version if the specified version fails. However, the latest PyGObject release requires girepository-2.0, which is not supported in our environment.
To resolve this issue, this PR upgrades pycairo to 1.26.1, ensuring that the specified version of PyGObject 3.46.0 can be successfully installed.
The build failed in …
> Upgrade pycairo version to 1.26.1

- dockers/docker-dhcp-relay/start.sh
DHCPV4 per-interface counter is added by https://github.com/sonic-net/sonic-dhcpmon/pull/36, it would store data in counters db and initialize data for interested interface when process start. But it wouldn’t clear outdated data which it doesn’t interested data it doesn’t interested 
Clear all counter data when container start.
Manually verify and pr check
> [dhcp_relay] Clear all DHCPV4 counter data in DB when dhcp_relay container startup 

- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/buffers_defaults_objects.j2
Support dynamic buffer model in 5600
> Do not exclude dynamic buffer model when generating buffer queue table in SN5600

- dockers/docker-platform-monitor/Dockerfile.j2
- files/build_templates/sonic_debian_extension.j2
- Add smbus2 python library to be used inside pmon docker and host for enhanced support while interacting with smbus devices through python.
- Add telnetlib3 python library on host as the default packaged library telnetlib is deprecated from 3.11 and slated for removal from 3.13 python version. (part of fix needed for https://migsonic.atlassian.net/browse/MIGSMSFT-574)
Added smbus2 module to host and pmon docker
Added telnetlib3 module to host
Install image with change, and check the following  
```
host:
root@sonic:/home/cisco# pip3 list | grep smbus2
smbus2                     0.5.0
root@sonic:/home/cisco# python3
Python 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] on linux
>>> …
```
> Add smbus2 library on host and pmon docker, and telnetlib3 library on host

- device/mellanox/x86_64-nvidia_sn5610n-r0/sensors.conf
- device/mellanox/x86_64-nvidia_sn5640-r0/sensors.conf
To have the updated sensors.conf for SN5610N and SN5640 Mellanox platforms
Took the last updated file from Hw mgmt package
Run platform test with latest file
> [Mellanox] Update sensors.conf of SN5610N, SN5640 platforms

- device/mellanox/x86_64-nvidia_sn5610n-r0/platform.json
Supported breakout modes in SN5610N are the same as in SN5600.
Update the file with the supported breakout modes
Run sonic-mgmt tests
> [Mellanox] Fix platform.json breakout modes for SN5610N

- dockers/docker-ptf/Dockerfile.j2
The PR https://github.com/sonic-net/sonic-buildimage/pull/21451 inadvertently missed adding packages for the non-py3 image. This PR fixes the issue by adding the missing packages.
Add missing packages.
Manually verified.
NA
[docker-ptf]: Fix to add missed packages to non-py3 image
NA
> [docker-ptf] Fix to add missed packages to non-py3 image

- platform/vs/docker-sonic-vs/database_config.json
* These are already added to dockers/docker-database/database_config.json.j2 and are needed to get DPU vstests to pass with new smartswitch DB design
> Add DPU tables to vs database_config.json

- dockers/docker-fpm-frr/base_image_files/prefix_list
- dockers/docker-fpm-frr/frr/bgpd/radian/add_radian.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/radian/del_radian.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/managers_prefix_list.py
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/radian/add_radian.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/radian/add_radian.json
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/radian/del_radian.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/radian/del_radian.json
fixes in T2 Radian Resiliency feature support checked in as part of PR https://github.com/sonic-net/sonic-buildimage/pull/21732/
- Microsoft ADO **31982579**:
The changes take care of following
1. Fix a typo which fetching chassis subtype in prefix_list script
2. remove root permission validation during radian status check
3. Input argument parsing fix during status check
4. during add_radian/del_radian template rendering, prefix-list entry to have prefixlen passed as an argument, instead of hardcoding it 
1. Execute the prefix_list script, and make sure add/del radian entries go through as expected.
2. Ensure that status check doesnt require sudo
3. Ensure that status check fails when passed second argument
4. Ensure that backend code renders radian config as per expectation …
> T2: anchor prefix fixes

- dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/param_chasiss_packet.json
- src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_chasiss_packet.conf
…iBGP
Add route-map entry to deny local_anchor_route_entries over iBGP
- Microsoft ADO **31998753**:
Add route-map entry in internal template under packet-chassis
Verify that route-map is available on packet-chassis
202405-chassis
> [T2-packet-chassis]: Add route-map entry to deny local_anchor_route_entries over iBGP

- files/image_config/rsyslog/rsyslog.conf.j2
- src/sonic-config-engine/setup.cfg
- src/sonic-config-engine/tests/sample_output/py3/rsyslog.conf
- src/sonic-config-engine/tests/sample_output/py3/rsyslog_with_docker0.conf
- src/sonic-config-engine/tests/test_cfggen_from_yang.py
- src/sonic-config-engine/tests/test_yang_data.json
This fix resolves issue with missing certain types of messages while forwarding to the remote server.
Basically, this moves remote syslog forwarding rules to be executed before any other instructions take place,
so everything received by a local syslog instance will be forwarded to the remote machine.
The fix allows remote forwarding of messages defined as:
https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog.d/00-sonic.conf.j2
* N/A
* Moved `rsyslog` remote forwarding rules to be on top of other syslog instructions
1. Enable remote syslog forwarding
2. Check for message patterns defined as [00-sonic.conf.j2](https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog.d/00-sonic.conf.j2)
* N/A
* N/A
* Backport from …
> [202311][rsyslog]: Remote logging with the highest rule priority

- dockers/docker-ptf/Dockerfile.j2
- dockers/docker-ptf/gnxi-patches/0001-add-xpath_target-option.patch
- dockers/docker-ptf/gnxi-patches/0002-Adding-support-for-subscribe-mode-1.patch
- dockers/docker-ptf/gnxi-patches/0003-gNMI_client-Add-an-option-to-trigger-memory-spike-on.patch
- dockers/docker-ptf/gnxi-patches/0004-Add-support-for-streaming-structured-events-in-night.patch
- dockers/docker-ptf/gnxi-patches/0005-Enhance-gnmi_cli_py-4.patch
- dockers/docker-ptf/gnxi-patches/series
The release branches use the mixed (Python 2 + Python 3) image. The release branches use latest tag of docker-ptf. The intent is to have release branches have latest changes for docker-ptf so they are built and published from the release branch. As with Python 3 migration for docker-ptf the "latest" tag will contain a Python 3 only image.
- Microsoft ADO **(number only)**: 29869339
Port changes relevant for mixed image setting from master.
This will be in another PR to enable branch-based tag for 202411.
master
[docker-ptf]: Port of latest Dockerfile changes from master
Required to enable branch based docker-ptf tag.
NA
> [docker-ptf] Port changes from master

- dockers/docker-ptf/Dockerfile.j2
- dockers/docker-ptf/gnxi-patches/0001-add-xpath_target-option.patch
- dockers/docker-ptf/gnxi-patches/0002-Adding-support-for-subscribe-mode-1.patch
- dockers/docker-ptf/gnxi-patches/0003-gNMI_client-Add-an-option-to-trigger-memory-spike-on.patch
- dockers/docker-ptf/gnxi-patches/0004-Add-support-for-streaming-structured-events-in-night.patch
- dockers/docker-ptf/gnxi-patches/0005-Enhance-gnmi_cli_py-4.patch
- dockers/docker-ptf/gnxi-patches/series
The release branches use the mixed (Python 2 + Python 3) image. The release branches use latest tag of docker-ptf. The intent is to have release branches have latest changes for docker-ptf so they are built and published from the release branch. As with Python 3 migration for docker-ptf the "latest" tag will contain a Python 3 only image.
- Microsoft ADO **(number only)**: 29869339
Port changes from master
This will be in another PR to enable branch-based tag for 202311.
master
[docker-ptf]: Port of latest Dockerfile changes from master
Required to enable branch based docker-ptf tag.
NA
> [docker-ptf]: Port changes from master

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Yang changes for inner source mac rewrite feature in Smart switch(a new action and inner_src_ip and vni)
- Microsoft ADO **(number only)**:https://msazure.visualstudio.com/One/_workitems/edit/31634070
Added ACL table INNERSRCMACREWRITE, action type INNER_SRC_MAC_REWRITE_ACTION for this ACL type, VNI_ID
 
yang model tests
addition to sample config_db.json
> Add ACL yang changes for INNER SRC MAC REWRITE 

- platform/mellanox/mlnx-platform-api/sonic_platform/module.py
- platform/mellanox/mlnx-platform-api/tests/test_module.py
Addition of reset_pwr_off reboot cause file for smartswitch platforms. 
Add unit test to cover the new reason and verify it is correct.
> [Mellanox][Smartswitch] Addition of power off cause

- files/build_templates/docker_image_ctl.j2
In the case of ASIC detection failures on Broadcom (or if the ASIC couldn't be detected in time), the `/dev/shm` partition in the syncd container will be only 64MB, which might cause issues if syncd/Broadcom SAI library needs more space than that.
Since using a larger `/dev/shm` on its own doesn't cause any issues, bump up the default to 512MB. This should be enough for most platforms.
> Bump up /dev/shm size for Broadcom platforms to 512MB by default

- src/sonic-frr/patch/0084-lib-Return-duplicate-prefix-list-entry-test.patch
- src/sonic-frr/patch/series
The fix from FRR (https://github.com/FRRouting/frr/issues/18493) is taken as a patch in sonic(FRR 10.0.1).
> Port Fix from FRR community for issue https://github.com/FRRouting/frr/issues/18493 in sonic-frr(FRR 10.0.1)

- Makefile.work
- dockers/dockerfile-macros.j2
- platform/vs/syncd-vs.mk
Fix docker dependency packages missing issue in specific scenario.
When run 'apt-get -y install -f', if dependency packages are not installed, it will remove the target package and it will not report error. It is not by design. Dependency missing is critical error.
With this PR, when dependency packages are not installed, it will report error and exit.
- Microsoft ADO **(number only)**:  31996244
Fix apt-get install command.
docker-sonic-vs has never installed DASH_SAI because dependency missing.
I have confirmed with peterosaur(Ze Gan) that docker-sonic-vs don't need DASH_SAI by design.
So when building docker-sonic-vs, don't add dependency for DASH_SAI.
> [build] Fix docker dpkg_qpt removing target package in some scenario.

- src/sonic-frr/patch/0064-mgmtd-clean-session-config-only-when-it-is-needed.patch
- src/sonic-frr/patch/series
(this is cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/22182)
mgmtd configuration management has an issue where any session can clean up outstanding configuration upon destruction.
When a long-lived session is taking configuration changes, and another short-lived session which never took any configuration closes, the outstanding configuration would be lost because the configuration clearing doesn't have protection during session closing.
- Microsoft ADO **(number only)**: 31872199
This change keeps track if a session has received any configuration, and if the configuration has been applied or cleared.
The outstanding configuration should be applied or cleared before session closure (assertion).
When clearing the outstanding session structure, only attempt to clear …
> [202411][FRR] fix FRR mgmtd losing configuration issue

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
- src/sonic-config-engine/tests/test_frr.py
liquid.
Use new feature switch to turn on FRR side bmp tunneling, so that we can control FRR side feature switch in image first, and BMP container side feature will be controlled via kubeSonic rollout.
- Microsoft ADO **(number only)**:30807821
Create new feature switch for FRR side bmp tunneling
Unit test is covered.
> Split frr_bmp feature switch for turn on FRR side bmp tunneling via Liquid

- device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-V256/media_settings.json
To optimize SerDes SI values for SN5600 and SN5610N.
On the Mellanox platform only, I updated the media_settings.json file for SN5600 (and for SN5610N, whose media_settings.json file is a symbolic link to SN5600’s).
Manual testing.
> [Mellanox] SN5600 and SN5610N SerDes signal integrity update

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
- src/sonic-device-data/tests/permitted_list
It's theorized that https://github.com/aristanetworks/sonic/issues/120 could be due to a FIFO underflow which is documented here https://brcmsemiconductor-csm.wolkenservicedesk.com/wolken-support/article?articleId=19817
In EOS we workaround this FIFO underflow issue by setting the `start_tx_threshold=20` for 100G and 400G ports.
Setting the same value via the soc properties in this change to match EOS values.
After the soc property change we can see the start_tx_threshold is 20 (0x14) on active lanes:
```
root@cmp227-4:~# bcmcmd -n 0 "getreg CDB_TX_MLF_CONFIG.CDB0"
getreg CDB_TX_MLF_CONFIG.CDB0
CDB_TX_MLF_CONFIG.CDB0[0x1b7]=0x120240480901202404814: <TX_START_TX_THRESHOLD_TMC_7=9,
TX_START_TX_THRESHOLD_TMC_6=9,TX_START_TX_THRESHOLD_TMC_5=9, …
```
> Adding `custom_feature_start_tx_threshold=20` on Arista SKUs

- dockers/docker-ptf/conf.d/sshd.conf
The docker-ptf image built on 202305 release branch is created with a wrong permission for `/run/sshd` (`/var/run/sshd`) with value `0775`. This fails to start `sshd` with the error below. Thus failing `add-topo`.
```
/run/sshd must be owned by root and not group or world-writable.
```
This PR fixes the permission to `0755` for `/run/sshd` (`/var/run/sshd`) in the docker-ptf image.
Set permissions in `sshd.conf` supervisor config.
Local environment
202305
[docker-ptf]: Fix to set /run/sshd permission affecting 202305
The docker-ptf image built on 202305 release branch is created with a wrong permission for `/run/sshd` (`/var/run/sshd`) with value `0775`. This fails to start `sshd` with the error below. Thus failing `add-topo`.
```
/run/sshd must be owned …
```
> [docker-ptf]: Fix to set /run/sshd permission affecting 202305

- src/sonic-frr/patch/0085-This-error-happens-when-we-try-to-write-to-a-socket.patch
- src/sonic-frr/patch/series
mgmtd: Change log level to INFO for EOF disconnect error, which can also happen in a valid scenario
Description: This error happens when we try to write to a socket or pipe
which is already closed by peer.  For e.g., the other side may have been
killed during warmboot or using pkill. Hence, changing the log level to INFO.
Note: I have avoided changing bgp.sh script because the error could be seen in other scenarios also(apart from warmboot/fast boot, for e.g., if we just kill zebra, we will see this log). 
Signed-off-by: sudhanshukumar22 (sudhanshu.kumar@broadcom.com)
2025 Mar  5 10:22:59.234007 sonic INFO bgp#mgmtd[33]: [GR5PJ-Q2R72] BE-adapter: mgmt_msg_read: got EOF/disconnect
2025 Mar  5 10:22:59.234845 sonic INFO bgp#supervisord 2025-03-05 …
> Mgmt EOF disconnect error log msg

- dockers/docker-ptf/conf.d/sshd.conf
The docker-ptf image built on 202405 release branch is created with a wrong permission for `/run/sshd` (`/var/run/sshd`) with value `0775`. This fails to start `sshd` with the error below. Thus failing `add-topo`.
```
/run/sshd must be owned by root and not group or world-writable.
```
This PR fixes the permission to `0755` for `/run/sshd` (`/var/run/sshd`) in the docker-ptf image.
Set permissions in `sshd.conf` supervisor config.
Local environment
202405. This fix only applicable to 202405 and not required for other branches.
[docker-ptf]: Fix to set /run/sshd permission affecting 202405
The docker-ptf image built on 202405 release branch is created with a wrong permission for `/run/sshd` (`/var/run/sshd`) with value `0775`. This fails to start `sshd` …
> [docker-ptf]: Fix to set /run/sshd permission affecting 202405

- dockers/docker-ptf/conf.d/sshd.conf
The docker-ptf image built on 202311 release branch is created with a wrong permission for `/run/sshd` (`/var/run/sshd`) with value `0775`. This fails to start `sshd` with the error below. Thus failing `add-topo`.
```
/run/sshd must be owned by root and not group or world-writable.
```
This PR fixes the permission to `0755` for `/run/sshd` (`/var/run/sshd`) in the docker-ptf image.
Set permissions in `sshd.conf` supervisor config.
Local environment
202311
[docker-ptf]: Fix to set /run/sshd permission affecting 202311
The docker-ptf image built on 202311 release branch is created with a wrong permission for `/run/sshd` (`/var/run/sshd`) with value `0775`. This fails to start `sshd` with the error below. Thus failing `add-topo`.
```
/run/sshd must be owned …
```
> [docker-ptf]: Fix to set /run/sshd permission affecting 202311

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/fabric_monitor_config.json
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/fabric_monitor_config.json
MSFT has 7 SFM cards in Nokia chassis and each FAP will have 168 fabric links up with 7SFM cards. So 85% threshold is very high, so lowering the threshold to 75%
Lowered the threshold to 75%
Verified in tested bed which has 8 IMMs and 7 SFM cards with fabric capacity sys logs.
> [Nokia] Lower the default warning threshold for fabric capacity

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
The STAN_ALN mode was set incorrectly in BCM DNX asics and was advised by BCM to set these soc variables to correct it (One FAP with STAN_ALN=1 and other FAPs with STAN_ALN=0).
Added the soc variables in BCM config 
Verified the STAN_ALN mode and also passing traffic without any issues.
> [Nokia][Device] Add BCM DNX soc properties to set STAN_ALN mode correctly

- files/Aboot/boot0.j2
Add aboot entry for Arista-7060X6-64PE-B-C448O16, Arista-7060X6-64PE-B-C512S2
> Add aboot entry for Arista-7060X6-64PE-B-C448O16, Arista-7060X6-64PE-B-C512S2

- src/sonic-yang-models/setup.py
The pipeline for `sonic-gnmi` failed. An example failure is shown as below:
https://dev.azure.com/mssonic/build/_build/results?buildId=816337&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=335d3395-6d29-5762-4daa-c188603f3eb8
```
sonic-interface.yang sonic-port.yang sonic-portchannel.yang sonic-sflow.yang
error: sonic-interface:29: module "sonic-vnet" not found in search path
make[2]: *** [Makefile:187: ../../build/yang/.sync_sonic_yangs] Error 1
make[1]: *** [Makefile:70: models] Error 2
make[2]: Leaving directory '/__w/1/s/sonic-mgmt-common/models/yang'
make[1]: Leaving directory '/__w/1/s/sonic-mgmt-common'
dh_auto_build: error: make -j2 returned exit code 2
make: *** [debian/rules:3: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
``` …
> Add ./cvlyang-models/sonic-vnet.yang to data_files

- dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/main.py
- src/sonic-config-engine/config_samples.py
- src/sonic-config-engine/tests/sample_output/t1-smartswitch-dpu.json
The software_bfd flag is currently under FEATURE; it is more appropriate to put it under SYSTEM_DEFAULTS as it is a simple enabled/disabled flag. Additionally, enabling it by default on t1-smartswitch DPU.
Moved software bfd checks from FEATURE to SYSTEM_DEFAULTS, and enabled it by default in src/sonic-config-engine/config_samples.py. 
Build and install DPU image (following https://github.com/sonic-net/sonic-buildimage/pull/22058), check that software_bfd flag is set in config_db.json and runningconfig by default. Unit tests during build also check this using src/sonic-config-engine/tests/sample_output/t1-smartswitch-dpu.json
Move software_bfd to system_defaults and enable for DPU.
> Move software_bfd to system_defaults and enable for DPU.

- dockers/docker-fpm-frr/frr/bgpd/templates/dynamic/instance.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
- src/sonic-bgpcfgd/tests/test_bgp.py
This change allows BGP peer creation inside a VNET through bgpcfgd. The support already exists for peers to be created in VRF. Removing the check which blocks peers to be created inside a VNET. This can already be done directly through FRR configs. However, that method does not persist the configuration. Letting peer addition inside vnet go through via bgpcfgd ensures that the configurations persists after reload or reboot.
We have proper support for handling VNETs and VRFs in sonic now. Hence it is safe to remove the check and allow peers to be created inside a VNET. We are already able to create peers in side VRFs since the support for VRF was added. From FRR perspective, both VNET and VRF translate to a VRF.
Removed check to allow BGP peer in a vnet. …
> Removed check to allow BGP peer in a vnet

- dockers/docker-ptf/gnxi-patches/0006-Add-support-for-extensive-configurations.patch
- dockers/docker-ptf/gnxi-patches/series
The command line has a length limitation, which restricts the number of configurations it can support.
To overcome this limitation, introduce a new argument: arg_file. Users can place extensive configurations within the arg_file, enabling the GNMI client to handle a larger and more complex set of configurations.
Run gnmi end to end test
> Add patch for gnmi client to support extensive configurations

- platform/nvidia-bluefield/recipes/sdk.mk
Fix the issue with the SDK compilation caused by missing dependencies.
Update package dependencies.
Compile the nvidia-bluefield image.
> [nvidia-bluefield] Fix the issue with the SDK compilation caused by missing dependencies.

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/installer.conf
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/installer.conf
Enable support to gather vmcore in the event of kernel panic.
Can be cherry-picked to 202405.
> [Nokia 7250e] enable crashkernel

- dockers/docker-sonic-bmp/base_image_files/monit_bmp
BMP feature is enabled by-default currently, but there's config cli to enable dataset dump into redis-bmp dynamically. Previously we added test https://github.com/sonic-net/sonic-mgmt/pull/16854, added memory checker and thought that's the extremely case which will hit peak usage for both bgp and bmp memory. By recent Nightly, there're other cases like nhop and test_pfc_counters which reports that bmp exceeds the pre-defined monit threshold 400MB from time to time, and usually unable to be reproduced stably. 
Thus we need to update the monit memory threshold for bmp container based on the recent Nightly test result, meanwhile will turn on bmp for cover all existing test cases so that we can measure whether the threshold value makes sense.
- Microsoft ADO **(number only)**:32246488
Updated …
> update memory monit threshold for bmp container according to test.

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Support new device types in device-metadata Yang model:
- M1: MgmtLeafRouter
- M2: MgmtSpineRouter
- M3: MgmtAccessRouter
Update UT to cover M0 (MgmtToRRouter)
- Microsoft ADO **(number only)**: 32261922
Update Yang model and corresponding unittest.
Verified by unittest.
> [Yang] Support M1/M2/M3 in device metadata Yang model

- platform/mellanox/rshim/Makefile
Update path to the rshim package location to align with infrastructure change.
Change the path in the makefile
Compile image for Mellanox platform.
> [mellanox] Update path to the rshim package location.

- platform/mellanox/mlnx-platform-api/sonic_platform/module.py
- platform/mellanox/mlnx-platform-api/tests/test_module.py
The midplane interface IP address is currently part of the CONFIG_DB, but since the IP address for the DPUs will not change it is expected to be removed from the CONFIG_DB. The IP address for the DPUs will still be obtained from the dhcp servers, but it will be consistent . since the IP Prefix will not be present in CONFIG_DB, we are obtaining the IP address directly from the known prefix and the DPU ID
This also prevent the following log error if the config_db does not contain the IP address:
`Failed to check midplane reachability for DPU0! expected str, bytes or os.PathLike object, not NoneType`
Changed `get_midplane_ip` to obtain IP address from known prefix + DPU ID instead of CONFIG_DB
> [Smartswitch][Mellanox] Bug fix for module midplane ip address

- files/build/versions/host-image/versions-py3-all-armhf
sonic-host-services depends on pycairo 1.26.1
But in SONiC image, it installed 1.26.0
- Microsoft ADO **(number only)**: 32264890
Fix version dependency issue in reproducible build.
Remove version constraint in arm build. It will use common version constraint 1.26.1
> [build] Fix sonic-host-services dependency issue.

- platform/broadcom/sswsyncd/Makefile
https://github.com/sonic-net/sonic-buildimage/pull/22153 moved dsserve and bcmcmd to /usr/sbin/ but there are a number of scripts that expect them to be at /usr/bin/.
More details issue: https://github.com/sonic-net/sonic-buildimage/issues/22287
> Move `dsserve` and `bcmcmd` back to `/usr/bin/`

- src/sonic-bgpcfgd/bgpcfgd/directory.py
- src/sonic-bgpcfgd/bgpcfgd/managers_srv6.py
Previously, the bgpcfgd's directory invokes callbacks in the iteration over notification dictionary when it gets a new record. However, the callbacks may change the size of the notification dictionary, which will cause runtime errors.
Fix issue #22239 
I changed the bgpcfgd directory to invoke callbacks after the whole iteration over the notification dictionary.
> [BGPCFGD] Eliminate the possibility of changing key size during iteration over notification dictionary

- src/sonic-bgpcfgd/bgpcfgd/manager.py
- src/sonic-bgpcfgd/bgpcfgd/managers_srv6.py
- src/sonic-bgpcfgd/tests/test_srv6.py
Preivously, every bgpcfgd manager need to wait on all of its dependencies to be ready before it can start processing next SET command. It was very inflexible and hurts performance particularly for SRv6 manager.
To reproduce the issue, a user can try the following config sequence:
```
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_SIDS|loc1|fcbb:bbbb:1::/48' action 'uN'
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_SIDS|loc2|fcbb:bbbb:2::/48' action 'uN'
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_SIDS|loc3|fcbb:bbbb:3::/48' action 'uN'
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_SIDS|loc4|fcbb:bbbb:4::/48' action 'uN'
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_LOCATORS|loc1' prefix "fcbb:bbbb:1::"
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_LOCATORS|loc2' prefix "fcbb:bbbb:2::"
sonic-db-cli CONFIG_DB HSET 'SRV6_MY_LOCATORS|loc3' …
```
> [BGPCFGD] Optimize bgpcfgd directory dependencies design

- src/sonic-bgpcfgd/bgpcfgd/managers_srv6.py
- src/sonic-bgpcfgd/tests/test_srv6.py
- src/sonic-yang-models/tests/yang_model_tests/tests/srv6.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/srv6.json
- src/sonic-yang-models/yang-models/sonic-srv6.yang
The prefix matching constraint hit some unknown problem about libyang in testing and it prevents multiple MYSIDs being used.
fix issue: #[21876](https://github.com/sonic-net/sonic-buildimage/issues/21867)
Remove the prefix matching constraint in sonic-srv6.yang and add prefix matching check in bgpcfgd/managers_srv6.py.
> [Bgpcfgd][YANG] Remove the prefix matching constraint in sonic-srv6.yang and add prefix match checking in bgpcfgd

- files/build_templates/arp_update_vars.j2
- files/scripts/arp_update
We need to proactively resolve static-route neighbors for BT0 to prevent VLAN flooding caused by MAC missing.
- Microsoft ADO **(number only)**: 31751190
Reuse the static-route neighbor probing mechanism (which was for packet-chassis) for BT0.
> [ARP_UPDATE] Update arp_update tool suite to resolve static-route neighbors for BT0

- src/sonic-yang-models/tests/yang_model_tests/tests/qosmaps.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json
- src/sonic-yang-models/yang-models/sonic-port-qos-map.yang
Support empty string in pfc_enable and pfc_wd_enable fields in PORT_QOS_MAP table to represent "disable PFC ".
Unit/manul test
> [Yang model] Support empty string in pfc_enable and pfc_wd_enable fields in PORT_QOS_MAP table

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
To add SRv6 counters support
Extended sonic-flex_counter.yang
Extended the existing yang model test with new entry
> [yang] add SRv6 counters yang

- src/tacacs/bash_tacplus/bash_tacplus.c
Fix TACACS per-command authorization send host as remote address bug.
TACACS per-command authorization send host as remote address.
- Microsoft ADO **(number only)**:32291587
Send correct remote address in TACACS per-command authorization request.
Pass all test case.
Add test case:
https://github.com/sonic-net/sonic-mgmt/pull/18055
Manually verified:
Fix TACACS per-command authorization send host as remote address bug.
> [TACACS] Fix TACACS per-command authorization send host as remote address bug.

- .azure-pipelines/official-build-vs-with-test.yml
[CI]Add variables template for build offical vs image with test
> [CI]Add missed variables template for build offical vs image with test

- src/sonic-bgpcfgd/staticroutebfd/main.py
- src/sonic-bgpcfgd/tests/test_static_rt_bfd.py
Previously, the staticroutebfd module assume that static routes always have both ifname and nexthop configured, which is not true. First, a static route can have only either ifname or nexthop. Second, for blackhole routes, usually it is not configured with any ifname or nexthop. The staticroutebfd will encounter runtime error when those static routes are configured even if bfd is not enabled.
Fixes issue: #22344
Change the staticroutebfd's implementation to skip the processing if the route is a blackhole route or it only has partial info. I also added UT to verify it.
* Run UT.
* Test the new implementation on a SONiC devie.
> Fix staticroutebfd's handling on blackhole static routes and static routes that only have partial info correctly

- dockers/docker-auditd/auditd_config_files/39-exclusions.rules
The original PR: https://github.com/sonic-net/sonic-buildimage/pull/22316 introduced the `gid=0` and `uid=0`rule which will lost syscall and path for sudo operation.
Remove over strict rule if user was using sudo to do operation.
With the rule `-a always,exclude -F msgtype=PATH -F uid=0 -F gid=0`, we cannot see any `x99.json` file deletion event
```
stli@STG01-0101-0101-10T0:~$ sudo touch x99.json
stli@STG01-0101-0101-10T0:~$ sudo rm x99.json
stli@STG01-0101-0101-10T0:~$ sudo grep x99.json /var/log/syslog
```
After removed the rule `-a always,exclude -F msgtype=PATH -F uid=0 -F gid=0`, then we can see corresponding events for both syscall and path with same eventID: 1203041 
```
stli@STG01-0101-0101-10T0:~$ sudo grep x99.json /var/log/syslog
Apr 22 …
```
> Remove uid and gid exclusion

- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/buffers.json.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/port_config.ini
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/qos.json.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers.json.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/qos.json.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/th5-a7060x6-64pe.config.bcm
Found multiple issues when onboarding Arista-7060X6-64PE-B-C512S2 Arista-7060X6-64PE-B-C448O16 HWSKUs.
- config qos reload will fail due to missing buffers.json.j2 file.
- buffers default objects failing to be set to each port, due to buffer ports missing.
- 1 port is missing in port_config.ini.
This change fixes the issues above by updating the HWSKU files.
This PR also contains an initial MMU config based of the paper calculation from Broadcom team.
Validated on real hardware switch:
- qos reload works:
```
sudo config qos reload --no-dynamic-buffer                                                                              
Running command: /usr/local/bin/sonic-cfggen -d -t /usr/share/sonic/device/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O …
```
> Fix Arista-7060X6-64PE-B-C512S2 Arista-7060X6-64PE-B-C448O16 HWSKUs and Add initial buffer config

- files/build/versions/host-image/versions-py3
- files/build/versions/host-image/versions-py3-all-armhf
- files/build_templates/sonic_debian_extension.j2
This package is already available in Debian and doesn't require any compilation on SONiC's end for using this.
This also removes compilation errors related to not having `girepository` installed when upgrading to a newer version of this package from pip.
> Install pygobject from Debian instead of pip

- src/sonic-bgpcfgd/bgpcfgd/main.py
- src/sonic-bgpcfgd/bgpcfgd/managers_as_path.py
- src/sonic-bgpcfgd/tests/test_as_path.py
Add bgp manager to read T2 group asns from DEVICE_METADATA
1. Add bgp manager to read T2 group asns from DEVICE_METADATA
1.1. For set action for DEVICE_METADATA["localhost"]["t2_group_asns"], we would clear all T2 group as path then add new per new data
1.2. For del action for DEVICE_METADATA["localhost"]["t2_group_asns"], we would clear all T2 group as path
2. Only add prefix_manager and as_path_manager for T2 upstreamLC
1. UT
4. Manually test
> [anchor] Add as path manager for anchor

- dockers/docker-sonic-mgmt/Dockerfile.j2
Build for docker-sonic-mgmt (legacy and py3 only) is broken:
```
patch: **** Can't open patch file /azp/0003-extend-dataplane-poll-method-to-support-multi-ptf-nn.patch : No such file or directory
```
https://dev.azure.com/mssonic/build/_build/results?buildId=829403&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=44e6c678-cb87-52d9-8547-bcdbd0ad6ae4
```
ERROR: Could not find a version that satisfies the requirement jinja2==3.1.2 (from versions: 2.0rc1, 2.0, 2.1, 2.1.1, 2.2, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.8, 2.8.1, 2.9, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.9.6, 2.10, 2.10.1, 2.10.2, 2.10.3, 2.11.0, 2.11.1, 2.11.2, 2.11.3)
```
https://dev.azure.com/mssonic/build/_build/results?buildId=829405&view=logs&j=3dc8fd7e-4368- …
> Fix docker sonic-mgmt build issues

- src/sonic-py-common/sonic_py_common/device_info.py
- src/sonic-py-common/tests/device_info_test.py
Supervisor on virtual VoQ chassis does not perform any functionality of a fabric card and does not have necessary config for being either a "voq" or "fabric" type of switch. Thus, we should mark it as a new type of switch object. I set the new type to be 'dummy-sup'. With this change, we should modify the criteria of determining whether a device is chassis.
Define a new is_virtual_chassis function.
Setup a virtual chassis
> Add a new switch_type called dummy-sup for voq chassis

- .azure-pipelines/official-build-vs-with-test.yml
[CI]Fix 202311 official build vs image kvm-test, remove dpu-test
pipeline: https://dev.azure.com/mssonic/build/_build?definitionId=2925&_a=summary&branchFilter=25047
> [CI]Fix 202311 official build vs image kvm-test, remove dpu-test

- .azure-pipelines/docker-sonic-mgmt-mixed.yml
- .azure-pipelines/docker-sonic-mgmt.yml
We are have migrated python3 in recent releases as development environment for SONiC to ensure better compatibility with modern Python tools and eliminate legacy Python2 dependencies. The existing sonic-mgmt:latest image includes both Python2 and Python3, which may lead to ambiguity and maintenance overhead.
To reflect this transition:
1. We are promoting the sonic-mgmt:py3only image as the new default (sonic-mgmt:latest)
2. The current mixed Python 2/3 image previously tagged as latest is being re-tagged as sonic-mgmt:mixed for backward compatibility
1. Re-tagged sonic-mgmt:py3only image as sonic-mgmt:latest
2. Re-tagged the previous sonic-mgmt:latest (Python 2/3 mixed version) as sonic-mgmt:mixed
> Make `sonic-mgmt:py3only` the new `sonic-mgmt:latest` and tag legacy image as `sonic-mgmt:mixed`

- dockers/docker-auditd/auditd_config_files/audit.rules
Limit auditd event rate to 1000 per second
Auditd generate too much record.
Set -r parameter in audit.rules
- Microsoft ADO: 32313402
Pass all test cases.
Manually verified, will create a sonic-mgmt test case to cover this change:
admin@vlab-01:~$ sudo vi /etc/audit/rules.d/audit.rules
admin@vlab-01:~$ sudo cat /etc/audit/rules.d/audit.rules
-D
-b 8192
--backlog_wait_time 60000
-f 1
-r 1000 <== change rate by -r command
admin@vlab-01:~$
admin@vlab-01:~$ sudo service auditd restart
admin@vlab-01:~$ sudo auditctl -s
enabled 1
failure 1
pid 110032
rate_limit 1000 <== rate updated
...
Limit auditd event rate to 1000 per second
> Limit auditd event rate to 1000 per second

- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/fabric_monitor_config.json
- device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/fabric_monitor_config.json
Adjust the default fabric capacity threshold for 7800R3A-36DM2-LC-x to a lower number based on the planed traffic rate and other requirements.
This is for https://github.com/sonic-net/sonic-buildimage/issues/21927
Please add this change to 202405 . 
> Adjust default fabric capacity warning threshold for 7800R3A-36DM2-LC-X

- files/build_templates/docker_image_ctl.j2
- files/image_config/resolv-config/update-containers
Fix a possible race condition during the config reload caused by the concurrent restart of the Docker containers and the resolv-config service. The update of the DNS configuration inside the container is triggered by the container's post-start action.
- Add support for single container updates with container name argument
- Implement parallel updates for bulk operations
- Add comprehensive logging with syslog integration
- Add container state handling (start/wait for stopped containers)
- Add proper error handling and status reporting
- Remove temporary file usage during resolv.conf updates
- Add networking service check for bulk updates only
Integration changes:
- Add automatic DNS update call in docker_image_ctl post-start action
Run sonic-mgmt DNS …
> [resolv-config] Improve container resolv.conf update mechanism

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
Support to config SRV6_MY_SOURCE table
> Add tunnel source config support for srv6 tests

- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/media_settings.json
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t1.config.bcm
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/media_settings.json
- src/sonic-device-data/tests/media_checker
This PR adds a media_settings.json file to apply the parameters for arista x86_64-arista_7060_cx32s platform for 
QSFP+ interface of 40G speed and LR4, SR4 types. 
This change will go together with https://github.com/sonic-net/sonic-platform-daemons/pull/471 which has the support for parsing QSFP+ 40G speed regex style keys in media_settings.json and apply the change to interface parameters in APPL DB
This is indented as a part of long term fix repair item to correct RX_ERR on links facing x86_64-arista_7060_cx32s with 40G optical cables. 
32609588
added the meda_settings.json file
tested by deploying the change and running it with xcvrd/SAI changes
The following test-scenarios was covered to see unreliable LOS is enabled and param …
> [ARISTA] Adding media_settings.json for Arista-7260CX3-Q64 and Arista-7060CX-32S-Q32 for supporting unreliable LOS

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/loopback.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/loopback.json
- src/sonic-yang-models/yang-models/sonic-loopback-interface.yang
Loopback interface is missing admin status therefore `config interface startup/shutdown` does not work for it. Admin status has been added to loopback interface in the below PRs. This PR adds it to the corresponding yang model.
Related PRs: https://github.com/sonic-net/sonic-swss/pull/3565 ; https://github.com/sonic-net/sonic-utilities/pull/3827
Added admin_status to loopback interface for yang models.
> Add admin status to loopback interface yang model

- dockers/docker-ptf/gnxi-patches/0005-Enhance-gnmi_cli_py-4.patch
By default, gnxi/gnmi_cli_py supports SET-REPLACE. It has been patched in to extend it to accept lists of paths. This patch did not preserve the REPLACE functionality. Fix the patch to keep the extended behavior but retain REPLACE handling.
gNMI is being extended to allow configs to be modified using GCU ConfigReplace. The syntax will be a JSON config passed as a file through gNMI using SET-REPLACE. sonic-mgmt tests use gnxi/gnmi_cli_py to test gNMI behavior, so in order to add tests for the new behavior gnxi/gnmi_cli_py must be support SET-REPLACE (see [Issue#357](https://github.com/sonic-net/sonic-gnmi/pull/369)).
We can modify the offending patch directly. This seems better than adding a new patch just to rollback a previous one. It is also the last …
> Issue #22354: Support SET-REPLACE in gnxi/gnmi_cli_py

- build_debian.sh
- dockers/docker-config-engine-bullseye/Dockerfile.j2
- dockers/docker-config-engine-buster/Dockerfile.j2
- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
In PR #15890, to address an armhf build failure, the PyYAML version was pinned to 5.4.1 and the `--no-build-isolation` flag was introduced. However, our reproducible build has since been upgraded to use PyYAML 6.0.1, which leads to version conflicts.
```
target/sonic-cisco-8000.bin__cisco-8000__rfs.squashfs.log-+ sudo https_proxy= LANG=C chroot ./fsroot-cisco-8000 pip3 install PyYAML==5.4.1 --no-build-isolation
target/sonic-cisco-8000.bin__cisco-8000__rfs.squashfs.log-ERROR: Cannot install PyYAML==5.4.1 because these package versions have conflicting dependencies.
target/sonic-cisco-8000.bin__cisco-8000__rfs.squashfs.log-
target/sonic-cisco-8000.bin__cisco-8000__rfs.squashfs.log-The conflict is caused by:
target/sonic-cisco-8000.bin__cisco-8000__rfs.squashfs.log-    The user requested …
```
> Fix package version conflict introduced by PR #15890

- dockers/docker-orchagent/orchagent.sh
FIXES https://github.com/sonic-net/sonic-buildimage/issues/21962
logrotate uses SIGHUP to let orchagent reopen SAI Redis recording. If SIGHUP is sent by logrotate before orchagent register its handler the default action takes place - termination. If we mask the signal in the start script orchagent inherits masked signals and will ignore SIGHUP until signal handler is registered.
This is a rare race condition observed during 1000 warm-reboot testing.
Mask SIGHUP
Place sleep inside orchagent before signal handler for SIGHUP is registered. Send SIGHUP as if it would be sent from logrotate script, ensure no orchagent termination.
Request to backport to all active branches.
> [orchagent.sh] mask SIGHUP before starting orchagent

- dockers/docker-sonic-mgmt/Dockerfile.j2
The `snappi-convergence` package was removed in PR #22345. However, its absence leads to runtime errors when it's implicitly required inside the sonic-mgmt docker environment. This PR resolves the issue by reinstating the package to ensure compatibility.
```
______ ERROR collecting snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py _______
ImportError while importing test module '/var/src/sonic-mgmt/tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py:7: in <module>
from tests.common.snappi_tests.snappi_fixtures import snappi_api_serv_ip, …
```
> Add snappi-convergence package back in sonic-mgmt docker

- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-C48/hwsku.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/hwsku.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8V40/hwsku.json
Fixed missing Dpc role and and AN for DPU ports in hwsku.json for Mellanox-SN4280-C48 Mellanox-SN4280-O8C40 Mellanox-SN4280-O8V40 SKUs
Why I did it
DPU ports on hwsku.json were missing the Dpc role and AN was set to off
> [202411] Fixed hwsku.json for Mellanox-SN4280-C48 Mellanox-SN4280-O8C40 Mellanox-SN4280-O8V40

- dockers/docker-ptf/Dockerfile.j2
Untested upgrades to ExaBGP can lead to unstable test environment. Last upgrade from 4.2.22 -> 4.2.25 caused the `-e` flag to stop working and failed the tests. Pinning it to 4.2.25 with https://github.com/sonic-net/sonic-mgmt/pull/18181 fix in place.
Pin the version in Dockerfile
Manually verified on local environment.
NA
[docker-ptf] Pin ExaBGP version for Python 3 to 4.2.25
* Untested upgrades to ExaBGP can lead to unstable test environment. Last upgrade from 4.2.22 -> 4.2.25 caused the `-e` flag to stop working and failed the tests. Pinning it to 4.2.25 with https://github.com/sonic-net/sonic-mgmt/pull/18181 fix in place.
NA
> [docker-ptf] Pin ExaBGP version for Python 3 to 4.2.25

- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/BALANCED
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/buffers.json.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/pg_profile_lookup.ini
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/qos.json.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/sai.profile
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/BALANCED
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/buffers.json.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/pg_profile_lookup.ini
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/qos.json.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/sai.profile
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/BALANCED
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/buffer_ports.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/buffers.json.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/pg_profile_lookup.ini
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/qos.json.j2
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/th5-a7060x6-16pe-384c.config.bcm
Add QoS settings for Arista-7060X6-16PE-384C-O128S2
> Add QoS settings for Arista-7060X6-16PE-384C-O128S2

- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/BALANCED
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/pg_profile_lookup.ini
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/qos.json.j2
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/th5-a7060x6-64pe.config.bcm
Add QoS settings for Arista-7060X6-64PE-O128S2
> Add QoS settings for Arista-7060X6-64PE-O128S2

- files/image_config/rsyslog/rsyslog.conf.j2
- src/sonic-config-engine/setup.cfg
- src/sonic-config-engine/tests/test_cfggen_from_yang.py
- src/sonic-config-engine/tests/test_yang_data.json
This fix resolves issue with missing certain types of messages while forwarding to the remote server.
Basically, this moves remote syslog forwarding rules to be executed before any other instructions take place,
so everything received by a local syslog instance will be forwarded to the remote machine.
The fix allows remote forwarding of messages defined as:
https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog.d/00-sonic.conf.j2
* N/A
* Moved `rsyslog` remote forwarding rules to be on top of other syslog instructions
1. Enable remote syslog forwarding
2. Check for message patterns defined as [00-sonic.conf.j2](https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog.d/00-sonic.conf.j2)
* N/A
* N/A
* Backport from …
> [202305][rsyslog]: Remote logging with the highest rule priority

- .gitignore
- files/dsc/install_debian.j2
- platform/checkout/pensando.ini
- platform/checkout/template.j2
- platform/pensando/docker-dpu-base.dep
- platform/pensando/docker-dpu-base.mk
- platform/pensando/sdk.mk
- slave.mk
- During make configure, if `pensando.ini` exists at `platform/checkout`, it runs `template.j2` to download pensando dpu build artifacts from `pensando/pensando-sonic-artifacts` repo at path
`$(PLATFORM_PATH)/pensando-sonic-artifacts` i.e (`platform/pensando/pensando-sonic-artifacts`)
- Modified `slave.mk` and `sdk.mk` to use downloaded artifacts at path `platform/pensando/pensando-sonic-artifacts`
- Introduced `COPY_DOCKER_IMAGES` in Makefile to copy Pensando elba firmware docker container image to `target/` which is getting used for `docker-dpu-base.mk` for Pensando
make init
make configure PLATFORM=pensando PLATFORM_ARCH=arm64
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=0 NOBULLSEYE=0 make …
> Add support for MtFuji elba dpu image build

- src/sonic-bgpcfgd/tests/test_as_path.py
DEVICE_METADATA["localhost"]["t2_group_asns"] is a comma separated list of ASNs. bgpcfgd would parse and loop this list and do some operations. Sometimes ut in bgpcfgd would fail due to list parsing order for t2_group_asns
```
=========================== short test summary info ============================
FAILED tests/test_as_path.py::test_metadata_with_asns - AssertionError: Calls not found.
Expected: [call('bgp as-path access-list T2_GROUP_ASNS permit _64120_'),
call('bgp as-path access-list T2_GROUP_ASNS permit _64121_')]
Actual: [call('bgp as-path access-list T2_GROUP_ASNS permit _64121_'),
call('bgp as-path access-list T2_GROUP_ASNS permit _64120_')]
FAILED tests/test_as_path.py::test_metadata_with_asns_update - AssertionError: Calls not found.
Expected: [call('no bgp as-path …
```
> [bgpcfgd] Fix flaky UT failure in test_as_path

- device/virtual/x86_64-kvm_x86_64-r0/DPU-2P/context_config.json
- platform/vs/docker-sonic-vs/orchagent.sh
Related to changes in https://github.com/sonic-net/sonic-buildimage/pull/21940
To improve performance when programming DASH objects
- Microsoft ADO **30024522**:
By enabling zmq b/w orchagent and syncd for DPU-2P vs
> Changes to enable zmq for vs DPU-2P hwsku

- device/pensando/arm64-elba-asic-flash128-r0/Pensando-elba/context_config.json
Related to changes in https://github.com/sonic-net/sonic-buildimage/pull/21940
To improve performance when programming the DPU via gNMI
- Microsoft ADO **30024522**:
> Add context configuration to enable zmq b/w OA and syncd for pensando DPU

- dockers/docker-fpm-frr/frr/bgpd/templates/dynamic/update.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
- src/sonic-bgpcfgd/tests/test_bgp.py
This PR adds the changes back from this PR: https://github.com/sonic-net/sonic-buildimage/pull/22261
Along with 1 more change to fix the UT such that it only asserts if the template for dynamic neighbors exist.
> Fixing dynamic range modification UT

- dockers/docker-sonic-mgmt/Dockerfile.j2
Reverts sonic-net/sonic-buildimage#22487
Build is failing, need to merge this revert PR:
Add the new version failure is fixed with https://github.com/sonic-net/sonic-mgmt/pull/18044, we're good with the snappi new version
> Revert "Add snappi-convergence package back in sonic-mgmt docker"

- azure-pipelines.yml
The azure pipeline uses sonic-mgmt master branch to invoke tests. The default value of PTF_IMAGE_TAG on master branch is "latest" which is a Python 3 only image. For release branches we use mixed image which is tagged under branch specific tag name. This PR overrides it here.
Override PTF_IMAGE_TAG in pipeline
TBD
NA
Override PTF_IMAGE_TAG for release branch PR tests
The azure pipeline uses sonic-mgmt master branch to invoke tests. The default value of PTF_IMAGE_TAG on master branch is "latest" which is a Python 3 only image. For release branches we use mixed image which is tagged under branch specific tag name.
NA
NA
> Override PTF_IMAGE_TAG use release tag [202405]

- platform/pensando/sonic-platform-modules-dpu/sonic_platform/chassis.py
- platform/pensando/sonic-platform-modules-dpu/sonic_platform/helper.py
- platform/pensando/sonic-platform-modules-dpu/sonic_platform/sensor.py
- platform/pensando/sonic-platform-modules-dpu/sonic_platform/thermal.py
- src/sonic-py-common/sonic_py_common/device_info.py
- mac address was null causing sonic-cfggen reload command to fail. Fixed it by using eth0-midplane interface mac addr as DEVICE_METADATA:localhost mac
- Added and modified threshold values for thermal, current and voltage sensors
```
make init
make configure PLATFORM=pensando PLATFORM_ARCH=arm64
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=0 NOBULLSEYE=0 make target/sonic-pensando.tar
```
Load the SONiC image from ONIE and make sure the interfaces are UP. All containers are up.
> Fixed mac null issue in DEVICE_METADATA and sensor values

- platform/mellanox/mlnx-fw-upgrade.j2
- platform/nvidia-bluefield/installer/install.sh.j2
Add firmware configuration reset support to the Nvidia Bluefile BFB image installer.
- Add new option (-r/--reset) to mlnx-fw-upgrade.j2 script to reset firmware configuration on NVIDIA BlueField platform
- Add FORCE_FW_CONFIG_RESET flag to installer/install.sh.j2 to control firmware configuration reset during installation
- Add SKIP_FIRMWARE_UPGRADE flag to installer/install.sh.j2 to control firmware upgrade during installation
- Remove platform-specific reboot logic from installer/install.sh.j2 as it's handled by the host
Install BFB image with FORCE_FW_CONFIG_RESET=true set in bf.cfg configuration.
> [nvidia-bluefield] Add firmware configuration reset support

- platform/mellanox/get_component_versions/get_component_versions.j2
- Remove BFSOC: N/A version displayed in get_component_versions.py output in mellanox platforms and remove 
- Fix HW_MANAGEMENT: N/A version displayed wrongly
Update get_component_versions.j2 jinja template to generate different UNAVAILABLE_COMPILED_VERSIONS based on the platform
Run get_component_versions.py on the switch
```
root@switch:/home/admin# get_component_versions.py
COMPONENT      COMPILATION             ACTUAL
-------------  ----------------------  -------------------------
SDK            4.7.2214                4.7.2214
FW             2014.2214               2014.2214
SAI            SAIBuild2411.2405.30.1  SAIBuild2411.2405.30.1
HW_MANAGEMENT  7.0040.2207             7.0040.2207
MFT            4.30.2-23               4.30.2-23
KERNEL …
```
> [Mellanox] Remove BFSOC version and fix wrong HW_MGMT displayed in nvidia-bluefield DPU

- device/arista/x86_64-arista_7800r3_48cq2_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3_48cqm2_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3a_36d2_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3a_36d_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3a_36dm2_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3a_36p_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3ak_36d2_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_7800r3ak_36dm2_lc/platform_update_reboot_cause
- device/arista/x86_64-arista_common/platform_update_reboot_cause
Fixes graceful reboot part of https://github.com/aristanetworks/sonic/issues/118.
https://github.com/aristanetworks/sonic/issues/118 indicates that when reboot is issued
by supervisor, in the `reboot-cause history` of LC, correct cause is not printed out. This
can lead to test failures and also potentially issues while debugging problems related to
reboot.
A temporary flag file is used for this purpose. When the flag file is created by
supervisor via RPC before it reboots the LC, this can indicate that previous
reboot command for LC has been issued by the supervisor via RPC. This
information can be used to update the reboot cause as 
'reboot from Supervisor' and the user as 'Supervisor' to distinguish
it from typical reboot by admin on LC.
> [Arista SKUs] check for flag file created by supervisor to update LC reboot cause

- dockers/docker-fpm-frr/frr/bgpd/templates/dynamic/delete.conf.j2
- src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
- src/sonic-bgpcfgd/tests/test_bgp.py
This change is to support enhanced CRUD operations on dynamic bgp peers  using a standard template-based mechanism. 
Here is the High level design document explaining this feature:
https://github.com/sonic-net/SONiC/pull/1963
Upon a delete peer ocurring, we render the delete template(instead of executing the current behavior of ```no neighbor {{ neighbor addr}}```), on the other hand if a delete template is not defined then the default behavior of ```no neighbor {{ neighbor addr}}``` applies as usual, thereby making this change backward compatible.
Create a dynamic peer like so in config_db.json:
"BGP_NEIGHBOR": {
"10.0.0.62": {
"admin_status": "up",
"asn": "65100",
"holdtime": "10",
"keepalive": "3",
"local_addr": "10.0.0.63",
"name": "vlab-01", …
> Add delete template for dynamic BGP peers

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_updater.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal_updater.py
Fix issue https://github.com/sonic-net/sonic-buildimage/issues/22505
thermalctld CPU usage is high on NVIDIA platform. It is because there is a thread "thermal updater" who prepares thermal data for NVIDIA thermal control algorithm. I did some optimization regarding to the thread. After the optimization, the CPU usage of thermalctld changes from 20% ~ 2%. (I tested on sn5600 with 32 optical modules, the test results may be different on different platform with different number of optical modules)
1. Combine `get_temperature`, `get_temperature_warning_threshold`, `get_temperature_critical_threshold` into one function `get_temperature_info` to avoid duplicate function calls such as "self.is_sw_control"
2. Previously, `get_temperature`, …
> [Mellanox] Optimize thermal updater performance

- dockers/docker-sonic-bmp/Dockerfile.j2
- dockers/docker-sonic-bmp/supervisord.conf
openbmp is using dedicated logging now, which has potential log spawn issue
- Microsoft ADO **(number only)**: 27588893
switch to use syslog and rotate will be done together with syslog.
verified on device which works fine
> switch to use host syslog to for openbmp logging

- files/image_config/monit/container_checker
frr_bmp is only feature switch used for bgpd to start as "/usr/lib/frr/bgpd -A 127.0.0.1 -M bmp", so that bmp container later rollout could work, thus is should be skipped from container check.
- Microsoft ADO **(number only)**:30807821
skip container check from monit.
before fix
after fix, the error log disappears.
> skip frr_bmp container from monit

- src/libyang/patch/libyang-leaf-must.patch
- src/libyang/patch/series
- src/sonic-yang-mgmt/setup.py
- src/sonic-yang-mgmt/sonic_yang.py
- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-mgmt/sonic_yang_path.py
- src/sonic-yang-mgmt/tests/libyang-python-tests/config_data.json
- src/sonic-yang-mgmt/tests/libyang-python-tests/config_data_merge.json
- src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-acl.yang
- src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-interface.yang
- src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-port.yang
- src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-portchannel.yang
- src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-vlan.yang
- src/sonic-yang-mgmt/tests/libyang-python-tests/sample-yang-models/test-yang-structure.yang
- src/sonic-yang-mgmt/tests/libyang-python-tests/test_SonicYang.json
- src/sonic-yang-mgmt/tests/libyang-python-tests/test_sonic_yang.py
***Important***: Please review each commit (including commit message) individually.  Looking at the patch-set as a whole may cause confusion.
Generic Config Updater (GCU) is notoriously slow.  These patches add some helpers for the GCU overhaul (mostly in sonic-utilities) in order to facilitate the optimizations.  These changes are in sonic-yang-mgmt plus a patch to libyang 1.
Changes include:
* Libyang v1 was not exposing `must` data for leaf nodes (like it does for other node types).  Patch to correct this oversight.
* Loading of sonic configuration data should not mutate the user-provided data, this forces callers to know they need to deepcopy the data, plus in most instances data won't be mutated.
* sonic-yang-mgmt test models should more closely mimic real sonic yang models as we …
> sonic-yang-mgmt: Generic Config Updater - performance dependencies

- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
We need the bgp sid vpn per-vrf export explicit config to enbale a SRV6 static SID attached to a route exported from the current unicast VRF to VPN. This pr add the load of 'sid vpn per-vrf export explicit' config in frrcfgd.
Verified on our daily test jenkins job
> feat(frrcfgd): Add load of bgp sid vpn per-vrf export explicit config

- platform/mellanox/mlnx-platform-api/sonic_platform/dpuctlplat.py
Enhance DPU control platform logging
- Add timestamp to print-based logging for better traceability
- Add verbosity-based debug logging for file write operations
Run `dpuctl` command with `-v` option
> [Mellanox] Enhance DPU control platform logging

- device/nvidia-bluefield/arm64-nvda_bf-bf3comdpu/installer.conf
- platform/nvidia-bluefield/installer/create_sonic_image
Update DPU CPU isolation configuration based on NASA requirements. This optimizes the performance of the SDN application.
Update GRUB configuration.
Compile and run image.
> [nvidia-bluefield] Update DPU CPU isolation configuration based on NASA requirements.

- platform/mellanox/mlnx-platform-api/tests/test_dpuctlplat.py
As the function `setup_logger` was changed to not use print anymore the test case `test_setup_logger` fails during pytest execution. This is the fix PR
> [Mellanox] Fix test test_setup_logger for mellanox platform

- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/qos.json.j2
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4600c-c64-remap-disabled.json
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4600c-c64.json
- src/sonic-config-engine/tests/sample_output/py3/qos-mellanox4600c-d48c40-t0.json
Previously we disable the global dscp_to_tc_map table as sai doesn't support it. Now they have supported it and we need it to enable inner dscp map to tc feature, so remove the old dummy macro and update testing case accordingly.
Remove empty dscp_to_tc_map macro in qos.j2 and update testing case accordingly.
https://github.com/sonic-net/sonic-mgmt/pull/9098 relevant test had been raised
> Remove empty dscp_to_tc_map macro in qos.j2

- azure-pipelines.yml
The azure pipeline uses sonic-mgmt master branch to invoke tests. The default value of PTF_IMAGE_TAG on master branch is "latest" which is a Python 3 only image. For release branches we use mixed image which is tagged under branch specific tag name. This PR overrides it here.
Override PTF_IMAGE_TAG
TBD
NA
Override PTF_IMAGE_TAG for release branch PR tests
The azure pipeline uses sonic-mgmt master branch to invoke tests. The default value of PTF_IMAGE_TAG on master branch is "latest" which is a Python 3 only image. For release branches we use mixed image which is tagged under branch specific tag name.
NA
NA
> Override PTF_IMAGE_TAG for release branch [202311]

- azure-pipelines.yml
The azure pipeline uses sonic-mgmt master branch to invoke tests. The default value of PTF_IMAGE_TAG on master branch is "latest" which is a Python 3 only image. For release branches we use mixed image which is tagged under branch specific tag name. This PR overrides it here.
Override PTF_IMAGE_TAG in pipeline
TBD
NA
Override PTF_IMAGE_TAG for release branch PR tests
The azure pipeline uses sonic-mgmt master branch to invoke tests. The default value of PTF_IMAGE_TAG on master branch is "latest" which is a Python 3 only image. For release branches we use mixed image which is tagged under branch specific tag name.
NA
NA
> Override PTF_IMAGE_TAG for release branch [202305]

- platform/pensando/sonic-platform-modules-dpu/sonic_platform/watchdog.py
Watchdog is controlled by Pensando firmware container for Pensando DPU which is crucial for services running under docker container, hence it cannot be controlled. For watchdog-control.service (as per latest https://github.com/sonic-net/sonic-buildimage/pull/22315), in case of dpu, it is going to be armed hence added support to check if watchdog is armed and what is timeout set for it.
```
make init
make configure PLATFORM=pensando PLATFORM_ARCH=arm64
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=0 NOBULLSEYE=0 make target/sonic-pensando.tar
```
Load the SONiC image from ONIE and make sure the interfaces are UP. All containers are up.
watchdogutil status should show status as armed.
``` …
```
> Added armed support in watchdog.py for watchdog-control.service

- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-C48/hwsku.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/hwsku.json
- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8V40/hwsku.json
Fixed missing Dpc role and and AN for DPU ports in hwsku.json for Mellanox-SN4280-C48 Mellanox-SN4280-O8C40 Mellanox-SN4280-O8V40 SKUs
DPU ports on hwsku.json were missing the Dpc role and AN was set to off
> [202405] Fixed  hwsku.json for Mellanox-SN4280-C48 Mellanox-SN4280-O8C40 Mellanox-SN4280-O8V40

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Nvidia doesn't support Copper Active modules to be SW control.
In case we use this kind of module, it should be classified as FW control. 
Checked the media interface technology for the module. If it is Copper cable, linear active equalizers, it should be classified as FW control. 
Run this code on Mellanox switch with Copper cable, linear active equalizers module. check control sysfs to make sure it is classified as FW control. (control = 0).
202412
> [Mellanox] Add a query in MDF to make copper-active modules be FW control

- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-O128
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-P32O64
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-P64
Reverts sonic-net/sonic-buildimage#22602
The HWSKU can't be reused.
> Revert "Create symbol link in platform x86_64-arista_7060x6_64pe_b"

- platform/pddf/i2c/utils/pddfparse.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_current_sensor.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_voltage_sensor.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddfapi.py
Sensormon is currently not integrated with PDDF. Adding voltage and current sensor monitoring with PDDF support in order to expose system-level current and voltage readouts from peripheral sensors. 
Fixes https://github.com/sonic-net/sonic-buildimage/issues/17032
Implement pddf parsing for current and voltage sensors, as well as pddf_voltage_sensor and pddf_current_sensor classes. 
Run commands "show platform voltage" and "show platform current". 
Should see "Sensor not detected" for platforms that do not have current/voltage sensors implemented. 
For platforms that do have it implemented, should see an output like this:
```
admin@sonic:~$ show platform voltage
Sensor     Voltage    High TH    Low TH    Crit High TH    Crit Low TH    Warning …
```
> Voltage and Current Sensors support with PDDF

- files/build/versions/build/build-sonic-slave-bookworm/versions-py3
- files/build/versions/build/build-sonic-slave-bullseye/versions-py3
- files/build/versions/dockers/docker-config-engine-bookworm/versions-py3
- files/build/versions/dockers/docker-config-engine-bullseye/versions-py3
- files/build/versions/host-image/versions-py3
To fix issue #22569
PyPi package version will not be automatically updated. However natsort old version has a known performance issue.
Upgrade natsort package version in version file.
> [build] Upgrade natsort pypi package from 6.2.1 to 8.4.0

- dockers/docker-auditd-watchdog/watchdog/Cargo.lock
- dockers/docker-auditd-watchdog/watchdog/Cargo.toml
- dockers/docker-auditd-watchdog/watchdog/src/main.rs
Add rate_limit check to auditd container watchdog
Auditd container recently enable rate limit, need watch dock to check this change applied correctly.
- Microsoft ADO **(number only)**:32313402
Add rate_limit check to auditd container watchdog
Pass all test case.
New test case added by: https://github.com/sonic-net/sonic-mgmt/pull/18555
Manually verified the feature works, checked 4 cases:
1. running config match with /etc/audit/audit.rules, will return: OK
2. running config mismatch with /etc/audit/audit.rules, will return: FAIL (rate_limit: {} mismatch with config file setting: {})
2. running config rate limit no set, but rate limit set in /etc/audit/audit.rules, will return: FAIL (rate_limit not set = {}, config file setting: {})
3. rate limit disabled in /etc/audit/audit.rules, will …
> Add rate_limit check to auditd container watchdog

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/mux_cable.json
- src/sonic-yang-models/yang-models/sonic-mux-cable.yang
New prober_type harware is being added to linkmgrd. This is config knob yang addition for the specific field in mUX_CABLE
> Addition of prober_type field for MUX_CABLE

- device/mellanox/x86_64-nvidia_sn5610n-r0/sensors.conf
- device/mellanox/x86_64-nvidia_sn5640-r0/sensors.conf
To have the updated sensors.conf file
Updated sensors.conf for SN5640, SN5610N
Install image on Mellanox SN5640/SN5610N and make sure the right file is there
> [Mellanox] Update sensors.conf for SN5640, SN5610N

- platform/vs/docker-sonic-vs/Dockerfile.j2
1. We already use apt to install python3-gi in SONiC image according to #22326 
But docker-sonic-vs.gz change is missed in that PR.
- Microsoft ADO **(number only)**:  32869072
1. Install python3-gi in docker-sonic-vs.gz image.
> [build] Install python3-gi in docker-sonic-vs as pygobject's dependency

- dockers/docker-dhcp-relay/cli-plugin-tests/test_show_dhcp4relay_counters.py
- dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py
DHCPv4 per-interface counter is added by https://github.com/sonic-net/sonic-dhcpmon/pull/36. Current PR is to add CLI to show counter.
HLD: https://github.com/sonic-net/SONiC/pull/1861
- Microsoft ADO **(number only)**: 32751340
1. Add show cli for per-interface counter
2. Add uts for it
1. UT passed
2. Manually test
2.1 interface not specified
```
admin@sonic:~$ show dhcp_relay ipv4 counters
+----------------+-----------+---------+----------+-------+---------+---------+-----+-----+---------+--------+-------+
| Vlan100 (TX)   | Intf Type | Unknown | Discover | Offer | Request | Decline | Ack | Nak | Release | Inform | Bootp |
+----------------+-----------+---------+----------+-------+---------+---------+-----+-----+---------+--------+-------+
| Vlan100        | VLAN      | 0       | 0 …
```
> [dhcp_relay] Add show CLI for DHCP per-interface counter

- device/mellanox/x86_64-mlnx_msn2700-r0/psu_sensors.json
- device/mellanox/x86_64-nvidia_sn4280-r0/sensors.conf
1. Add new platform's sensors data
2. Correct PSU model AC-E rail out label
use `sensors` command and confirm the output is labeled correctly
> [Mellanox] Update PSU sensors data file

- device/arista/x86_64-arista_7060x6_64pe_b/platform.json
We were seeing platform test failures on `x86_64-arista_7060x6_64pe_b`. We identified that the PCI addresses listed in the corresponding `platform.json` file were incorrect.
Updated the `platform.json` file with the correct scd addresses per `ls /sys/bus/pci/drivers/scd` on dut.
Ran `sonic-mgmt/tests/platform_tests/api/test_component.py` with and without the change. With the change I no longer see an assertion error related to the scd components.
> Fix incorrect scd address in platform.json

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddfapi.py
pddf uses a shared sysfs interface for getting/setting led status for all leds. Our system currently has 3 processes that gets/sets led status using the pddf api:
- healthd
- port-ledd.service
- system-ledd.service
There's the potential for simultaneous sysfs operations to interfere with each other, resulting in errors like:
```
[  124.847956] PDDF_LED ERROR find_led_ops_data invalid index: 36 for type:FANTRAY_LED_1;3
```
This problem is not unique to our system. Any vendor using pddf for leds is susceptible to this.
Fixes #22699
Tested on NH-4010
Let it run for > 30 minutes and confirmed no PDDF_LED "invalid index" errors. Previously it was easily reproducible in that timeframe.
> [PDDF] Add file lock for led ctrl

- dockers/docker-orchagent/docker-init.j2
- dockers/docker-orchagent/ipinip.json.j2
Fixes #22797 
Make broadcom asic detection more robust in ipinip json template
Check if device is in the list of specified hwskus
Tested on switch:
```
{
"TUNNEL_DECAP_TABLE:IPINIP_TUNNEL" : {
"tunnel_type":"IPINIP",
"dscp_mode":"uniform",
"ecn_mode":"copy_from_outer",
"ttl_mode":"pipe"
},
"OP": "SET"
},
...
```
The `ASIC_VENDOR` env var is used which is defined inside the swss container [here](https://github.com/sonic-net/sonic-buildimage/blob/80d660de2f04335ccdd26c3f19b3083528793a92/files/build_templates/docker_image_ctl.j2#L710).
[QoS] Make broadcom asic detection more robust in ipinip json template
> [QoS] Make broadcom asic detection more robust in ipinip json template

- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-FANOUT/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-O128S2-COPPER-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-O128S2-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-O128S2/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE-256x200G/th5-a7060x6-64de.config.bcm
- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE-O128S2/th5-a7060x6-64de.config.bcm
- device/arista/x86_64-arista_7060x6_64de/Arista-7060X6-64DE/th5-a7060x6-64de.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-256x200G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-64x400G/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-C224O8/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-C256S2/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-P32O64/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/th5-a7060x6-64pe.config.bcm
Cherry pick changes from https://github.com/sonic-net/sonic-buildimage/pull/22825
> [202505] Add stat_custom_receive0_management_mode to the Broadcom config file of TH5 platforms

- device/arista/x86_64-arista_7060x6_64pe_b/platform.json
- device/arista/x86_64-arista_7060x6_64pe_b/platform_components.json
`sonic-mgmt/tests/platform_tests/api/test_component.py` was failing due to an order mismatch between the `platform.json` file and our component API implementation. Since the two are not linked together we need to update the json files with the correct order.
Modified `platform.json` and `platform_components.json` with the correct info and order for the components.
Verified by running `sonic-mgmt/tests/platform_tests/api/test_component.py` with and without the change on a x86_64-arista_7060x6_64pe_b switch. With the change `test_get_name` no longer fails.
> Fix info and order of components for x86_64-arista_7060x6_64pe_b platform

- src/sonic-yang-models/tests/yang_model_tests/tests/route_filter.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/route_filter.json
- src/sonic-yang-models/yang-models/sonic-route-map.yang
When using BGP Unnumbered for an underlay network its often desirable to only advertise the loopback interface IP address.  The implementation allows it but the YANG model did not.
Add yang model adjustments and  adds a test to ensure it doesn't regress.
Run test case.
master as of 20250608
YANG: Route Map allow match_interface on Loopback
N/A
Fixes https://github.com/sonic-net/sonic-buildimage/issues/22899
Signed-off-by : Brad House <bhouse@nexthop.ai>
> YANG: Route Map allow match_interface on Loopback

- src/sonic-sysmgr/rebootbackend/rebootbe.cpp
- src/sonic-sysmgr/rebootbackend/rebootbe.h
- src/sonic-sysmgr/tests/rebootbe_test.cpp
Fix to second warm_reboot fails.
Fix Details:
WARM_INIT_WAIT was initially added for a different purpose. Since it is Obsolete, I have removed that code since it was blocking the trigger of second WARM reboot.
> Fix for second warm_reboot failure

- azure-pipelines.yml
At the beginning of this year, we transitioned the PR testing approach in the sonic-mgmt repository from a classical model to an impacted area-based model. This new approach enables automatic collection of relevant test cases, eliminating the need for the previously hardcoded `pr_test_scripts.yaml` list, and we no longer maintain it.
However, the sonic-buildimage repository has continued to use the classical PR testing model. As a result, any new test cases added in the sonic-mgmt repository are not picked up during PR testing in sonic-buildimage.
This PR updates the sonic-buildimage repository to adopt the impacted area-based PR testing model. With this change, all relevant test cases—including newly added ones—will be properly included in the PR testing workflow.
- Microsoft ADO …
> Enable impacted area based PR testing in sonic-buildimage repo

- platform/nvidia-bluefield/recipes/sdk.dep
Image compilation fails when using the same cache tar for build from source and download from artifact. 
Eg:
When building from sources, mlnx-tools is a derived package of mlnx-ofed-kernel-utils and the cache tar has both the packages saved
```
$ tar -tvf  mlnx-tools_25.01-0.2501060_arm64.deb-adc83b19e793491b1c6ea0f-ba387afe3cf420ba021052c.tgz
-rw-r--r-- vkarri/dip    69712 2025-06-11 02:24 target/debs/bookworm/mlnx-tools_25.01-0.2501060_arm64.deb
-rw-r--r-- vkarri/dip    27816 2025-06-11 02:25 target/debs/bookworm/mlnx-ofed-kernel-utils_25.01.OFED.25.01.0.6.0.1-1_arm64.deb
-rw-r--r-- vkarri/dip  2445612 2025-06-11 02:25 target/debs/bookworm/mlnx-ofed-kernel-dkms_25.01.OFED.25.01.0.6.0.1-1_all.deb
-rw-r--r-- vkarri/dip    73036 2025-06-11 02:25 …
```
> [nvidia-bluefield] Differentiate cache based on compilation and download

- src/sonic-frr/patch/0057-mgmtd-remove-bogus-hedge-code-which-corrupted-active.patch
- src/sonic-frr/patch/0058-mgmtd-normalize-argument-order-to-copy-dst-src.patch
- src/sonic-frr/patch/series
Ported the fix https://github.com/FRRouting/frr/pull/18601 from FRR community
Tested using static routes, save and reboot.
K>* 0.0.0.0/0 [0/0] via 10.59.128.1, eth0, 00:03:58
L * 1.1.1.1/32 is directly connected, Loopback0, 00:03:52
C>* 1.1.1.1/32 is directly connected, Loopback0, 00:03:52
C>* 10.59.128.0/20 is directly connected, eth0, 00:03:58
L>  10.59.142.159/32 is directly connected, eth0, 00:03:58
C>* 11.1.0.0/16 is directly connected, vsh0, 00:03:58
L>  11.1.22.238/32 is directly connected, vsh0, 00:03:58
C>* 20.1.1.0/24 is directly connected, Ethernet0, 00:02:22
L>  20.1.1.2/32 is directly connected, Ethernet0, 00:02:22
S>* 40.1.1.1/32 [1/0] is directly connected, Ethernet0, weight 1, 00:00:16
S>* 40.1.1.2/32 [1/0] is directly connected, Ethernet0, weight 1, 00:00:02
FRR 10.0.1
> Ported the fix https://github.com/FRRouting/frr/pull/18601 from FRR community

- files/image_config/resolv-config/resolv.conf.j2
- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/dns.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/dns.json
- src/sonic-yang-models/yang-models/sonic-dns.yang
Some needed DNS configuration options are not available such as search suffixes, ndots, query timeout (s), and query attempts.
Also depends on https://github.com/sonic-net/sonic-host-services/pull/239
Fixes #22311
Added yang models, tests, and documentation.
During build it will run through the test suite.
master as of 20250410
DNS configuration option enhancements
https://github.com/bhouse-nexthop/sonic-buildimage/blob/bhouse-nexthop/dns-config/src/sonic-yang-models/doc/Configuration.md#static-dns
> DNS configuration option enhancements

- src/sonic-yang-models/tests/yang_model_tests/tests/gnmi.json
- src/sonic-yang-models/tests/yang_model_tests/tests/telemetry.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/gnmi.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/telemetry.json
- src/sonic-yang-models/yang-models/sonic-gnmi.yang
- src/sonic-yang-models/yang-models/sonic-telemetry.yang
user_auth can be none, but current yang models do not have this mode.
- Microsoft ADO **(number only)**:33257886
Update sonic-gnmi.yang and sonic-telemetry.yang to add new user_auth value.
Run sonic-yang unit test.
> Update user_auth for gnmi and telemetry yang models

- azure-pipelines.yml
reference: https://github.com/sonic-net/sonic-buildimage/pull/22969
> [CI][202505]update pr test pipeline default timeout to 8 hours to mitigate timeout issues

- platform/checkout/cisco-8000-smartswitch.ini
Code drop for Smartswitch pilot 202411.1.0.9
This is required for pilot FUSE
> Code drop for Smartswitch pilot 202411.1.0.9

- platform/pddf/i2c/modules/xcvr/pddf_xcvr_module.c
- platform/pddf/i2c/utils/pddfparse.py
Add support for optoe3 in pddfparse.py and pddf xcvr module.
Added device type comparison check for optoe3.
Verified using marvell-teralynx OSFP board which uses optoe3 for parsing eeprom.
[   20.991100] PDDF_CLIENT	add_device_table: Adding ptr 0x0000000013c2df9e to the hash table
[   20.992017] optoe 93-0050: 32896 byte optoe3 EEPROM, read/write
[   20.992046] i2c i2c-93: new_device: Instantiated device optoe3 at 0x50
[   21.026281] xcvr 93-0066: chip found
[   21.026334] xcvr 93-0066: hwmon68: xcvr 'pddf_xcvr'
[   21.026363] PDDF_XCVR	Created a PORT64-CTRL client: 0x00000000805cb9f5
> [PDDF][xcvr] Add support for optoe3

- rules/config
Refine Azure resource support for reproducible build.
packages.trafficmanager.net/packages/ is used for cached package.
packages.trafficmanager.net/public/ is used for storing public content.
> [build] Reproducible build change URL for cached packages.

- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Currently, virtual VoQ chassis supervisor use dummy-sup as the switch_type. This failed the yang validation since it is not in the allowed list.
Modify YANG model definition.
> [YANG] Add dummy-sup as an option for switch_type in DEVICE_METADATA table

- slave.mk
- src/sonic-build-hooks/scripts/buildinfo_base.sh
Fix some logging issue when building SONiC image.
> [build] Fix log showing when build SONiC image.

- .azure-pipelines/official-build-vs-with-test.yml
- azure-pipelines.yml
[PR test] Temporarily mark multi_asic test job as optional
Summary:
multi_asic is flaky and with significant failure rate.
Temporarily mark it as optional to unblock PR tests, will revert back after issue fixes.
> [PR test] Temporarily mark multi_asic test job as optional

- src/sonic-yang-models/tests/yang_model_tests/tests/mirror_session.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/mirror_session.json
- src/sonic-yang-models/yang-models/sonic-mirror-session.yang
[PR 3317](https://github.com/sonic-net/sonic-swss/pull/3317) in sonic-swss enables configuration of IPv6 mirror sessions (in which both `src_ip` and `dst_ip` are IPv6 addresses). This PR updates the YANG model for ERSPAN mirror sessions so that IPv6 mirror sessions can be configured using the `config apply-patch` command.
- Microsoft ADO **(number only)**: 33501400
1. Changed the type of `src_ip` and `dst_ip` for ERSPAN mirror sessions to `ip-address` so that IPv6 addresses are also accepted.
2. Added a condition to ensure that both `src_ip` and `dst_ip` have the same IP version.
3. Added a test to verify that a mirror session with IPv6 `src_ip` and `dst_ip` can be successfully configured.
Use `config apply-patch` to configure an ERSPAN mirror session with IPv6 `src_ip` and `dst_ip` …
> Updated the YANG model for ERSPAN mirror sessions

- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128/th5-a7060x6-64pe.config.bcm
Update Arista-7060X6-64PE-B-O128 bcm configs, remove unneeded S2 port configs
> Remove S2 port bcm configs for Arista-7060X6-64PE-B-O128

- dockers/docker-sonic-gnmi/Dockerfile.j2
- dockers/docker-sonic-gnmi/base_image_files/monit_gnmi.j2
Reverts sonic-net/sonic-buildimage#22702
The correct way to fix this would be to read the memory limit from CONFIG_DB or somehow determine based on runtime.
> Revert "Improve monit_gnmi.2 to support smartswitch"

- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128/th5-a7060x6-64pe.config.bcm
… config file
Recently we added stat_custom_receive0_management_mode config to TH5 Broadcom config files, and the changes upstreamed in https://github.com/sonic-net/sonic-buildimage/pull/22825.
There's a separate PR created to add new HWSKU Arista-7060X6-64PE-B-O128
around the same time, see https://github.com/sonic-net/sonic-buildimage/pull/22672/
As a result, stat_custom_receive0_management_mode was missed in Arista-7060X6-64PE-B-O128 config file. This change adds it.
Verified all interfaces are up with this change when using Arista-7060X6-64PE-B-O128
> Add stat_custom_receive0_management_mode to Arista-7060X6-64PE-B-O128 config file

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_pytests/test_trimming.py
- src/sonic-yang-models/yang-models/sonic-trimming.yang
**HLD:** https://github.com/sonic-net/SONiC/pull/1988
* Added YANG model as part of Packet Trimming Asymmetric DSCP feature development
* N/A
* Added YANG model 
1. Run Packet Trimming UTs
* N/A
* [sonic-trimming.yang](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-trimming.yang)
```
'//||\\`
''``
```
> [trim]: Add Packet Trimming Asym DSCP YANG model

- device/arista/x86_64-arista_7280dr3a_36/platform.json
- device/arista/x86_64-arista_7280dr3ak_36/platform.json
- device/arista/x86_64-arista_7280dr3ak_36s/platform.json
- device/arista/x86_64-arista_7280dr3am_36/platform.json
Arista 7280DR3A SKUs don't support controlling thermal and psu fan speed. This makes some platform_tests under sonic-mgmt fail since they assume they are controllable by default.
Tests affected by this:
`platform_tests/api/test_psu_fans.py::TestPsuFans::test_set_fans_speed`
`platform_tests/api/test_thermal.py::TestThermalApi::test_set_low_threshold`
`platform_tests/api/test_thermal.py::TestThermalApi::test_set_high_threshold`
Modify `platform.json` to explicity mention that psu fan speed and thermal sensors are not controllable
Reran the above-mentioned tests and verified that they are skipped.
> Set psu fan speed and thermal controllable to false on Arista 7280DR3A variants

- device/mellanox/x86_64-nvidia_sn4280-r0/Mellanox-SN4280-O8C40/pmon_daemon_control.json
Currently chassisd is enabled for some SKUs even though it is not required for 202411 for SN4280. So we are setting the pmon_daemon_control.json to skip the chassisd for this particular SKU
Change link for `Mellanox-SN4280-O8C40` SKU pmon_daemon_control.json from `Mellanox-SN4700-O8C48` to `Mellanox-SN4280-O28` which has `skip_chassisd` set to True
Tested manually to see that there is no chassisd process in pmon container. Built the image to see that there are no issues 
202411
> [202411][Smartswitch] Fix SN4280 SKU pmon daemon control to skip chassisd 

- azure-pipelines.yml
Temporarily disable SAI validation for now as it is not compatible with the change in https://github.com/sonic-net/sonic-mgmt/pull/19263 due to the usage of concurrent.futures. We will refactor the SAI validation and re-enable it later. Microsoft ADO to track the progress: 33758029.
- Microsoft ADO **(number only)**: 33039693
> fix: temporarily disable sai validation

- src/libyang3-py3/patch/0004-pr141-test-crash.patch
- src/libyang3-py3/patch/series
Issue #23147 noted test case failures of the recent libyang3-py3 code test cases during compilation when using Trixie.
There is an internal Python CFFI pointer that gets invalidated in a test case due to the internal object being mutated.  This test case appears to be malformed and makes incorrect assumptions.
Nothing here in particular appears to be actually related to Trixie so it isn't clear why it shows up. The feature being tested is also in a code path that is not used at all by SONiC.
Triaged underlying issue and submitted upstream PR https://github.com/CESNET/libyang-python/pull/141 to fix the issue
Build SONiC with Trixie and observe libyang3-py3 compiles as expected.
master as of 20250706
libyang3-py3: test crash seen in Trixie
N/A
Fixes #23147 …
> libyang3-py3: test crash seen in Trixie

- device/arista/x86_64-arista_7050cx3_32c/Arista-7050CX3-32C-C28S16
- device/arista/x86_64-arista_7050cx3_32c/Arista-7050CX3-32C-C28S4
- device/arista/x86_64-arista_7050cx3_32c/Arista-7050CX3-32C-C6S104
- device/arista/x86_64-arista_7050cx3_32c/Arista-7050CX3-32C-D48C8
- device/arista/x86_64-arista_7050cx3_32c/Arista-7050CX3-32C-S128
Add HwSkus for x86_64-arista_7050cx3_32c. They are symbolic links to existing HwSkus of x86_64-arista_7050cx3_32s
> [Arista] Add HwSkus for x86_64-arista_7050cx3_32c

- scripts/build_kvm_image.sh
Following #22199, the debug version of `sonic-vs.bin` file is at 4093MB (to be precise, one particular build was at 4291790831 bytes). This, in theory, should've fit fine in the 4096MB FAT32 installer disk that is created for building the sonic-vs.img QCOW2 image. However, it's short by 5MB. My guess for this reason is because FAT32 itself needs some space for metadata, and so we don't get the full 4096MB. This results in a failure to build the debug KVM image.
As a fix, increase the installer disk size that we create by 1GB, which should be enough for now, and switch to ext2 filesystem instead of FAT32. This switch is needed because FAT32 only allows files up to 4GB (minus one byte), and the latest debug images are at around 4.1GB.
I locally made a …
> Increase the installer disk size by 1GB and switch to ext2 for KVM

- files/build_templates/buffers_config.j2
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
This PR is to support `LowerSpineRouter` as `type`.
- Microsoft ADO **33834365**:
1. Support `LowerSpineRouter` as device `type` in buffer template.
2. Update YANG model and relevant tests.
The change is verified by UT.
Support `LowerSpineRouter` as `type`.
> Support device type LowerSpineRouter

- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers_defaults_t1.j2
BRCM SAI 13.2.1 increases the pkt trim buffer pool to 1.7MB, leading to the reduction of available lossy queue buffer.
Without this change, there will be a syncd crash on default buffer profile pairing with SAI 13.2.1.
Reduce default ingress and egress lossy buffer size from 165307264 with 161999982
Verified on Arista-7060X6-64PE-B-C512S2
BRCM SAI 13.2.1 increases the pkt trim buffer pool to 1.7MB, available lossy queue buffer size to be reduced accordingly.
> TH5-512 ingress and egress lossy queue buffer size change

- files/build_templates/docker_image_ctl.j2
This is done in order to be able to start using tag which will provide a user-friendly identifier when running docker ps.
Needed PR: https://github.com/sonic-net/sonic-utilities/pull/3917
To fix https://github.com/sonic-net/sonic-buildimage/issues/22124 while keeping the wanted ability to get real image while using docker ps
- Modified `docker_image_ctl.j2` to add support for using `docker_image_tag` when starting containers
- Added a new condition to check if `docker_image_tag` is defined and not none
- If a tag is specified, it will be used instead of the default `latest` tag
1. Install a package using sonic-package-manager
2. Run docker ps to verify that the container is running with the correct tag
3. Check the container configuration to ensure the …
> [sonic-package-manager] Use tag to start application

- files/build_templates/sonic_debian_extension.j2
- files/image_config/dhcp_dos_logger/dhcp_dos_logger.py
- files/image_config/dhcp_dos_logger/dhcp_dos_logger.service
This PR addresses two issues encountered with the dhcp_dos_logger.service in the PR [18947](https://github.com/sonic-net/sonic-buildimage/pull/18947)
Permission Issue:
The dhcp_dos_logger.py script was missing execute permissions, service to fail with a Permission denied  error.
Fixed by ensuring the script has the correct permissions using chmod 755.
TypeError:
The script attempted to use a string pattern on a bytes-like object, causing a runtime error.
Fixed by decoding the bytes object to a string before using it with re.search.
Testing:
Verified that the service starts correctly and logs DHCP DoS events as expected after applying these changes locally.
Image of Test:
> fix issue in logger

- files/scripts/swss.sh
Workaround for https://github.com/sonic-net/sonic-buildimage/issues/21902
SWSS startup causes APPL_DB to be flushed.
This results in `PORT_TABLE:Ethernet#` losing it's media_settings tunings populated by XCVRD.
Without this change (tuning lost):
```
sonic-db-cli -n asic0 APPL_DB hgetall "PORT_TABLE:Ethernet96"
{'alias': 'Ethernet13/1', 'asic_port_name': 'Eth96', 'core_id': '0', 'core_port_id': '13', 'index': '13', 'lanes': '40,41,42,43', 'num_voq': '8', 'role': 'Ext', 'speed': '100000', 'admin_status': 'up', 'description': 'ARISTA13T3:Ethernet1', 'fec': 'none', 'mtu': '9100', 'pfc_asym': 'off', 'tpid': '0x8100', 'oper_stat
us': 'up', 'flap_count': '1', 'main': '0x4e,0x4e,0x53,0x4b', 'post1': '0xffffffea,0xffffffea,0xffffffea,0xffffffec', 'post2': '0x0,0x0,0x0,0x0', 'post3': …
```
> Restart `XCVRD` when `SWSS` flushes APPL_DB on all SKUs that use `media_settings.json`

- device/arista/x86_64-arista_7280dr3a_36/Arista-7280DR3A-36/0/buffers_defaults_t2.j2
- device/arista/x86_64-arista_7280dr3a_36/Arista-7280DR3A-36/1/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250_x3b-r0/Nokia-IXR7250-X3B/0/buffers_defaults_t2.j2
- device/nokia/x86_64-nokia_ixr7250_x3b-r0/Nokia-IXR7250-X3B/1/buffers_defaults_t2.j2
- files/build_templates/buffers_config.j2
To update cable settings between upperspinerouter and lowerspinerouter. As name spinerouter would be changed to lowerspinerouter in future.
- Microsoft ADO **([33881573])**:
Updated buffer config and template file with additional changes.
> Updated cable length configuration for upperspinerouter to lowerspinerouter

- src/tacacs/nss/patch/0012-Partial-memleak-fix-due-to-unfreed-strdup.patch
- src/tacacs/nss/patch/series
Cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/22600
A small memory leak was found when running TACACS
A patch was created for the libnss-tacplus repository that will fix the memory leak.
Configure TACACS
Use the python script that reproduce the consumption and monitor its memory consumption.
> [202311][TACACS] Fix memory leak when authenticating using tacacs

- device/arista/x86_64-arista_7280dr3a_36/services.conf
- device/arista/x86_64-arista_7280dr3a_36/startup-tsa-tsb.conf
- device/arista/x86_64-arista_7280dr3ak_36/services.conf
- device/arista/x86_64-arista_7280dr3ak_36/startup-tsa-tsb.conf
- device/arista/x86_64-arista_7280dr3ak_36s/services.conf
- device/arista/x86_64-arista_7280dr3ak_36s/startup-tsa-tsb.conf
- device/arista/x86_64-arista_7280dr3am_36/services.conf
- device/arista/x86_64-arista_7280dr3am_36/startup-tsa-tsb.conf
Startup TSA configuration file is required to enable startup-tsa service on the device to automatically TSA after unplanned reboot. 
Add conf file to all supported platform SKUs
Reboot device and confirm that the device remains in TSA for the configured time
> Add startup_tsa configuration file for 7280dr3 devices

- files/scripts/supervisor-proc-exit-listener
It found the following KeyError in syslog, not only for lldp, but also for snmp and bgp.
```
2025 Jul 19 18:13:00.240397 vlab-01 ERR lldp#supervisor-proc-exit-listener: Exception: 'len', trace: Traceback (most recent call last):
File "/usr/bin/supervisor-proc-exit-listener", line 249, in <module>
main(sys.argv[1:])
File "/usr/bin/supervisor-proc-exit-listener", line 182, in main
payload = sys.stdin.read(int(headers['len']))
KeyError: 'len'
```
The context syslog is:
```
2025 Jul 19 18:12:59.505711 vlab-01 INFO lldp#supervisord 2025-07-19 18:12:59,504 INFO waiting for supervisor-proc-exit-listener, rsyslogd, lldpd, lldp-syncd, lldpmgrd to die
2025 Jul 19 18:12:59.761223 vlab-01 INFO containerd[684]: time="2025-07-19T18:12:59.759992163Z" level=info msg="shim disconnected" …
```
> Check if len in headers to avoid KeyError in supervisor-proc-exit-listener

- platform/checkout/cisco-8000-smartswitch.ini
Update 202411 branch cisco-8000-smartswitch.ini with 202411.1.0.12
This release has the potential fix for the smartswitch pilot
> Update 202411 branch cisco-8000-smartswitch.ini with 202411.1.0.12

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_thermal.py
Currently, `PddfThermal` does not support `get_high_threshold` for PSU thermal sensors
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/23082
Add support to `get_high_threshold` method for PSU thermal sensors.
Retrieve the high threshold value from `psu_temp*_high_threshold` SysFS path.
Tested on NH-4010 using `show platform temperature`. 
`High TH` column now displays temperature value instead of `N/A`
> [PDDF] Add support for PSU thermal sensor in get_high_threshold

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_pytests/test_smart_switch.py
- src/sonic-yang-models/yang-models/sonic-smart-switch.yang
- src/sonic-yang-models/yang-models/sonic-vnet.yang
[ssw][ha] add `vnet_name` to global config
This field is needed for hamgrd to program VNET_TUNNEL_ROUTE_TABLE. 
- Microsoft ADO **(number only)**: 32737017
Added another leafref type leaf to global config table as the vnet_name. 
Azp pipelines.
> [ssw][ha] add `vnet_name` to global config

- dockers/docker-fpm-frr/frr/bgpd/templates/general/peer-group.conf.j2
- dockers/docker-fpm-frr/frr/bgpd/templates/general/policies.conf.j2
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/param_UpperSpineRouter.json
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/param_downstream_lc.json
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/param_spine_no_subtype.json
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/param_upstream_lc.json
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_UpperSpineRouter.conf
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_downstream_lc.conf
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_spine_no_subtype.conf
- src/sonic-bgpcfgd/tests/data/general/peer-group.conf/result_upstream_lc.conf
- src/sonic-bgpcfgd/tests/data/general/policies.conf/result_all_chassis_pkt.conf
- src/sonic-bgpcfgd/tests/data/general/policies.conf/result_all_voq.conf
Fixes issue https://github.com/sonic-net/sonic-buildimage/issues/22953 and https://github.com/sonic-net/sonic-buildimage/issues/23324
33812223
Updated BGP templates to ensure SELECTIVE_ROUTE_DOWNLOAD config is only available on upstream LC.
Fixed the Radian route-map sequence numbers to avoid conflicts with TSA seq numbers
Ran newly written tests and verified table-map config is not present on downstream LC
master
> BGP Template change to ensure SELECTIVE_ROUTE_DOWNLOAD config is only available on upstream LC

- platform/checkout/cisco-8000-smartswitch.ini
Update cisco-8000-smartswitch.ini for 202505.1.0.3  release
Smartswitch needs to build with the latest code
> Update cisco-8000-smartswitch.ini for 202505.1.0.3

- platform/checkout/pensando.ini
- platform/pensando/dsc-drivers/debian/rules
- platform/pensando/dsc-drivers/src/drivers/linux/pciesvc/Makefile
- platform/pensando/platform.conf
- changed hardcoded src/sonic-linux-kernel path to /lib/modules/<kernel_version>/ path
- changed platform.conf to use single kernel version variable instead changing all places
- Release artifacts for Pensando dpu to build docker-dpu.tar.gz and libsai debs for 1.87.0-SS-15 release
Picked: https://github.com/sonic-net/sonic-buildimage/pull/22900
Picked: https://github.com/sonic-net/sonic-buildimage/pull/22644
```
<path_to_sonic-builldimage>: make init
<path_to_sonic-builldimage>: make configure PLATFORM=pensando PLATFORM_ARCH=arm64
cd <path_to_sonic-builldimage>/platform/pensando/pensando-sonic-artifacts
<path_to_sonic-builldimage>/platform/pensando/pensando-sonic-artifacts: gh release download …
```
> [202505]: Changed pciesvc driver compilation methods to support linux 6.1.123

- device/arista/x86_64-arista_7280dr3a_36/platform_components.json
- device/arista/x86_64-arista_7280dr3ak_36/platform_components.json
- device/arista/x86_64-arista_7280dr3ak_36s/platform_components.json
- device/arista/x86_64-arista_7280dr3am_36/platform_components.json
The platform_components.json file is used for firmware upgrades via `fwutil`. One such application is to upgrade SCD firmware on the device.
Populated the platform_components.json for all the Arista 7280DR3 SKUs listed below:
- x86_64-arista_7280dr3a_36
- x86_64-arista_7280dr3ak_36
- x86_64-arista_7280dr3ak_36s
- x86_64-arista_7280dr3am_36
Run `fwutil show updates` and verify that no errors are reported
This change populates the platform_components.json with the physical components so that they can be accessed for firmware upgrade via fwutils.
> Add components to platform_components.json for Arista 7280DR3 SKUs

- sonic-slave-bullseye/Dockerfile.j2
Rust was added to bookworm, but is missing in bullseye build. Sonic-swss-common needs rust to build after https://github.com/sonic-net/sonic-swss-common/pull/1044, and bullseye build failures were seen due to missing rust when building Pensando DPU image with:
make init
make configure PLATFORM=pensando PLATFORM_ARCH=arm64
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=0 NOBULLSEYE=0 make target/sonic-pensando.tar
Add rust to bullseye dockerfile similarly to bookworm.
Successfully built Pensando image with:
make init
make configure PLATFORM=pensando PLATFORM_ARCH=arm64
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=0 NOBULLSEYE=0 make target/sonic-pensando.tar
> Add rust to bullseye.

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/pfc.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/pfc.json
- src/sonic-yang-models/yang-models/sonic-pfcwd.yang
New pfc_stat_history leaf attribute for toggling history estimation per-interface in CONFIG_DB
PFC Historical Statistics feature https://github.com/sonic-net/SONiC/issues/1904
https://github.com/sonic-net/sonic-buildimage/issues/21847
- Run the test cases in tests/ and ensure they pass.
- Deploy the changes to a SONiC device and verify the configuration and monitoring functionality using CLI commands.
Addition of PFC_STAT_HISTORY table and Flex Counter group.
> Yang model additions for PFC Stat History

- src/sonic-yang-models/doc/Configuration.md
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
**HLD:** https://github.com/sonic-net/SONiC/pull/2033
* Added YANG model as part of Packet Trimming Drop Counters feature development
* N/A
* Added YANG model 
1. Run Packet Trimming UTs
* N/A
* [sonic-trimming.yang](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-trimming.yang)
```
'//||\\`
''``
```
> [trim]: Add Packet Trimming Drop Counters YANG model

- platform/nvidia-bluefield/installer/create_sonic_image
The create image stage in nvidia-bluefield build is failing in the pipeline due to updates to how packages are handled in the staged build (some files are deleted which are not used- documentation, lintian etc) so, create_sonic_image command fails. The fix is to basically log an error and continue the build when file is not present (it is not an error because these files are not required for the final image)
This is the PR after which the issue was seen in create_sonic_image script:
https://github.com/sonic-net/sonic-buildimage/pull/23164
After the PR was merged the following files are removed before the create_sonic_image script call:
```
+ rm -rf /usr/share/man/cs /usr/share/man/da /usr/share/man/de /usr/share/man/es /usr/share/man/fi /usr/share/man/fr /usr/share/man/hr …
```
> [nvidia-bluefield] Fix bluefield build during create image stage

- files/Aboot/boot0.j2
amd_sfh is a SOC that handles human interface devices using PCIe (ex: gyroscopic sensor, etc.). This is not used on the switch and can be blacklisted.
This module is throwing error messages at boot time due to the lack of devices to manage, where modprobe is failing to probe this device. This is failing mgmt tests (SRv6 tests). Blacklisting this device will resolve this issue.
> Blacklist amd_sfh for Shearwater and Redstart in Aboot

- platform/marvell-prestera/sai.mk
platform/marvell-prestera/sai.mk for branch 202505 points incorrectly to the master branch. For future updates to work correctly and coherently, this should be modified to point to the correct branch.
For future updates to work correctly and coherently, BRANCH in sai.mk should be modified to point to the correct branch name (202505)
Modify BRANCH keyword in platform/marvell-prestera/sai.mk
manual build
make platform/marvell-prestera/sai.mk BRANCH keyword point to 202505
> Update mrvl-prestera BRANCH for 202505

- dockers/docker-orchagent/enable_counters.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
What I did
This PR enables Sonic-buildimage support for DASH Metering counters.
Related to the following PR's:
https://github.com/sonic-net/sonic-swss/pull/3631
Why I did it
To enable support for metering counters .
> [DASH] Add support to enable Metering counters

- files/build_templates/sonic_debian_extension.j2
Fix sonic-ctrmgrd-rs installation for `INCLUDE_KUBERNETES = y` condition. Otherwise the package will not be installed, and the python `container wait` script will break.
- Microsoft ADO **(number only)**: 34121264
> Fix sonic-ctrmgrd-rs installation for INCLUDE_KUBERNETES condition

- src/sonic-bgpcfgd/bfdmon/bfdmon.py
To bring DPU software BFD (bfdmon) database updates inline with https://github.com/sonic-net/SONiC/blob/4fc4f481e24414eb3f5c6c557842723480f6c9cd/doc/smart-switch/smart-switch-database-architecture/smart-switch-database-design.md#architecture-design. Currently the software BFD session info is stored in the local STATE_DB; adding these changes for software BFD session status to be sent to the remote DPU_STATE_DB.
Added connection to DPU_STATE_DB to update DASH_BFD_PROBE_STATE with DPU software BFD session info in bfdmon.py
Loaded on Smartswitch DPU and checked that the software BFD session entries are added/deleted in DPU_STATE_DB for the corresponding DPU in switch SONiC.
> Add remote dpu db to bfdmon.

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py
xcvr reset using sfputil reset is not working for pddf. `ff` is meant to be cleared and show `00`
```
admin@sonic:~$ sudo sfputil read-eeprom -p Ethernet305 -n 0x13 -o 183  -s 1
000000b7 ff                                               |.|
root@sonic:/home/admin# sudo sfputil reset Ethernet305
Resetting port Ethernet305 ... OK
admin@sonic:~$ sudo sfputil read-eeprom -p Ethernet305 -n 0x13 -o 183  -s 1
000000b7 ff
```
The code was missing `f.flush()` to write `1` to the sysfs file. I used a context manager instead, which ensures the file is properly flushed and closed.
```
root@sonic:/home/admin# sudo sfputil read-eeprom -p Ethernet8 -n 0x13 -o 183 -s 1
000000b7 ff                                               |.|
root@sonic:/home/admin# sfputil reset Ethernet8
Resetting port Ethernet8 ... …
```
> PDDF: Fix xcvr reset

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
This test was removed by this PR by mistake https://github.com/sonic-net/sonic-buildimage/pull/22262
Add the test back
UT passed
> [yang] Add test for verifying nexthop_group configuration

- device/nokia/x86_64-nokia_ixr7220_d4-r0/Nokia-IXR7220-D4-36D/buffers_defaults_t0.j2
- device/nokia/x86_64-nokia_ixr7220_d4-r0/Nokia-IXR7220-D4-36D/buffers_defaults_t1.j2
Why I did it
Nokia D4 platform QoS profiles - buffers, PFC profiles, egress queuesfor the newly introduced Nokia-IXR7220-D4-36D platform https://github.com/sonic-net/sonic-buildimage/pull/21853
How I did it
Updated buffers_defaults_t0.j2/t1.j2 file under the device/nokia/x86_64-nokia_ixr7220_d4-r0/Nokia-IXR7220-D4-36D
QoS SAI test OC suite used to verify buffer pools, profiles and various use cases as per dataplane tests.
Which release branch to backport (provide reason below if selected)
> Nokia D4 platform - QoS buffer pool configurations

- device/arista/x86_64-arista_common/platform_update_reboot_cause
Use a more structured file format to hold reboot cause information.
Also match the cause and user to that used in the tests.
During design discussion, it was pointed out that having a file with no schema to
hold the reboot cause info is a bad idea. This patch addresses that change.
> [Arista SKUs] Use more generic JSON reboot cause extra info file

- dockers/docker-fpm-frr/frr/bgpd/templates/general/policies.conf.j2
- src/sonic-bgpcfgd/tests/data/general/policies.conf/param_all_UpperSpineRouter.json
- src/sonic-bgpcfgd/tests/data/general/policies.conf/result_all_UpperSpineRouter.conf
Change done as part of PR https://github.com/sonic-net/sonic-buildimage/pull/23341, caused a regression on Disagg T2 UpperSpine Router. This PR is to fix that.
33812223
subtype field is not defined on UpperSpineRouter Dt2, hence the conditional check in BGP template policy rendering is adjusted to accomodate this.
New testcase written to verify that correct policies are getting applied on UpperSpineRouter device type.
master
> Fix BGP Template issue on UpperSpineRouter

- device/arista/x86_64-arista_7060x6_16pe_384c/Arista-7060X6-16PE-384C-O128S2/hwsku.json
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2/hwsku.json
- src/sonic-config-engine/portconfig.py
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
This is a manual cast of changes in https://github.com/sonic-net/sonic-buildimage/pull/23600 to 202505 due to the conficts.
> [202505] Fix subport of Moby backplane ports

- device/ufispace/x86_64-ufispace_s9321_64e-r0/UFISPACE-S9321-64E/th5-s9321-64e-64x800G.config.yml
- device/ufispace/x86_64-ufispace_s9321_64eo-r0/UFISPACE-S9321-64EO/th5-s9321-64eo-64x800G.config.yml
SAI move Broadcom SDK from 6.5.31 to 6.5.32, it will make switch chip initialization fail on the below Ufispace platforms:
S9321-64E
S9321-64EO
Due to sdk change, 
1. We need to add "stat_custom_receive0_management_mode" to config files of TH5 products. 
Plesae see Broadcom article "SDK - API Behavior Change - Statistics counter: snmpBcmCustomReceive0 is reserved" (ID: 26564)
2. We also need to change "flowtracker_flexctr_alloc_enable" from 1 to 2, according to "Tomahawk-5 Hardware based FlowTracker Configuration" (ID:26311)
pool manager method will make SDK init fail on 6.5.32. Change it to user allocated method.
Update SDK configuration on both platfoms
Reload config and then check "show interface status" to see if all interfaces is OK after system is …
> [Ufispace] Update S9321-64E and S9321-64EO BCM port configuration

- scripts/build_mirror_config.sh
When building a Bullseye-based container with MIRROR_SNAPSHOT=y, the repos used will point to the main Debian repo, but Bullseye packages have been moved to the archive repo. Fix this issue by overriding the `DEFAULT_MIRROR_URLS` variable.
Note that bullseye-security is still in the main Debian repo, and is not yet on the archive repo.
> Fix Debian repos used for Bullseye-based containers

- dockers/docker-lldp/lldpmgrd
We see below backtrace when hostname is not available during boot and lldpmgrd exits
```
Oct 11 03:25:29.131847 sonic INFO lldp#supervisord: lldpmgrd Traceback (most recent call last):
Oct 11 03:25:29.131847 sonic INFO lldp#supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 369, in <module>
Oct 11 03:25:29.132038 sonic INFO lldp#supervisord: lldpmgrd     main()
Oct 11 03:25:29.132038 sonic INFO lldp#supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 351, in main
Oct 11 03:25:29.132209 sonic INFO lldp#supervisord: lldpmgrd     lldpmgr.run()
Oct 11 03:25:29.132209 sonic INFO lldp#supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 319, in run
Oct 11 03:25:29.132333 sonic INFO lldp#supervisord: lldpmgrd     self.lldp_process_device_table_event(op, dict(fvp), key)
Oct 11 …
```
> Fix lldpmgrd traceback when hostname is not available

- dockers/docker-dhcp-server/cli-plugin-tests/test_show_dhcp_server.py
- dockers/docker-dhcp-server/cli/show/plugins/show_dhcp_server.py
If there are not customized options bound to Vlan, show info with customized options would raise exception
```
admin@sonic:~$ show dhcp_server ipv4 info --with_customized_options Vlan1000
File "/usr/local/bin/show", line 8, in <module>
^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line …
```
> [dhcp_server] Fix dhcp_server show info issue

- dockers/docker-sonic-bmp/supervisord.conf
To fix upgrade reboot core issue, simply use stopsignal=KILL so that supervisord will use SIGKILL instead of the default SIGTERM when stopping container, thus the process is terminated immediately by the kernel and skip signal handler. Existing openbmpd code has potential race issue in handling graceful termination.
which has already been used in bgpd/bfpd 
https://github.com/sonic-net/sonic-buildimage/blob/5cedc4f771a02df232b0b6dadd4c5c20e46b9527/dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2#L88
- Microsoft ADO **(number only)**: 33441494
Switch to use stopsignal=KILL in supervisord.conf
supervisord.conf verified on DUT
> Switch to use KILL as stop signal of openbmpd

- installer/default_platform.conf
Make GRUB terminal input/output configurable via environment variables instead of hardcoding `"console serial"`. This allows better flexibility across different platforms and build scenarios.
Previously, GRUB terminal input/output in default_platform.conf was hardcoded to console serial.
This limited flexibility when different platforms or builds required custom GRUB terminal settings.
By parameterizing these values via environment variables (GRUB_TERMINAL_INPUT and GRUB_TERMINAL_OUTPUT), the configuration can now be overridden without modifying the script, improving maintainability and adaptability.
**Work item tracking**
Microsoft ADO (number only):
**How I did it**
Defined default variables:
```
DEFAULT_GRUB_TERMINAL_INPUT="console serial" …
```
> Add support for configurable GRUB terminal input and output

- device/arista/x86_64-arista_7060x6_64pe_b/platform.json
In the case of Arista-7060X6-64PE-B there is a single aggregate PSU status LED whereas test cases expect individually controllable LEDs. Marking these LEDs as not controllable pending further discussion around driver enhancements.
> Fix PSU led controllable status for Arista-7060X6-64PE-B

- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2-FANOUT/sai.profile
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2-FANOUT/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2-LAB/sai.profile
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2/sai.profile
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/sai.profile
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/sai.profile
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128/sai.profile
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128S2/sai.profile
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128S2/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P32O64/sai.profile
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P32O64/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P64/sai.profile
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P64/th5-a7060x6-64pe.config.bcm
Fix failure to create NHG on TH5 with 512 BGP sessions.
This is a manual cherry-pick to 202505 for original PR: https://github.com/sonic-net/sonic-buildimage/pull/23722
Set the following fields in the Broadcom configure for the ___ HWSKUs:
`l3_ecmp_member_first_lkup_mem_size: 0`
`l3_ecmp_member_secondary_mem_size: 0`
Also, disable hierarchical nexthop group via sai.profile:
`SAI_NHG_HIERARCHICAL_NEXTHOP=false`
Run pre-test checks and confirm they pass.
202412
Scale up NHG, Disable Hierarchical Nexthop
> [Arista-7060X6-64PE-B, Arista-7060X6-16PE-384C-B]: Scale Up NHG on 202505

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/azure-pipelines-build.yml
1. centec is still using debian:bullseye as base image. debian bullseye-backports is deprecated on Jun 21.
It blocks docker-base-bullseye build. Stop supporting centec reproducible build.
2. Generic build is not neccessary. Remove it.
3. armhf/arm64 build don't run on amd64 host. Remove special timeout config.
> [ci] Update repd build upgrade version pipeline.

- dockers/docker-sonic-telemetry/Dockerfile.j2
- dockers/docker-sonic-telemetry/docker-telemetry-entry.sh
- Microsoft ADO **(number only)**:34506301
> Update telemetry docker entry flow to detect FEATURE table

- Makefile.work
If building the main slave container fails, then don't continue and try to build the user slave container (or try to collect the versions used in the failed slave container). This reduces the number of errors logged after the actual error message, and makes it a bit easier for reporting the actual cause of failures, besides saying that the user slave container failed to build because the main slave container wasn't available.
Set the `-o pipefail` setting in the group command used to build the slave container, which will report the command as having failed if any command in a piped command fails. The bash shell already has `-e` set; however, in a piped command, the exit of the last command in the pipe is used in determining if the command failed. For …
> Don't attempt building the user container if the main slave fails

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
- src/sonic-yang-models/tests/yang_model_tests/tests/high_frequency_telemetry.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/high_frequency_telemetry.json
- src/sonic-yang-models/yang-models/sonic-high-frequency-telemetry.yang
We must have a dummy HFT table to support dynamically configuring HFT. This Yang model change is to support the dummy table.
- Remove mandatory constraint for object_names list
- Add test cases for empty lists and validation scenarios
- Include high-frequency telemetry model
- 
Check Azp status. This PR includes its test.
master
> [Fix]: Allow empty object lists in high-frequency-telemetry YANG model

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Support MA roles in device-metadata Yang model.
- LMA (LowerMgmtAccessRouter)
- UMA (UpperMgmtAccessRouter)
- Microsoft ADO **(number only)**: 34903273
Update Yang model and corresponding unittest.
Verified by UT.
> [Yang] Support LMA and UMA in device metadata Yang model

- src/sonic-frr/patch/0060-bgpd-Convert-bmp-path_info-tracking-from-hash-to-rbt.patch
- src/sonic-frr/patch/series
Fixing BGP performance issues when running with BMP enabled
Ported fix https://github.com/FRRouting/frr/pull/19548 from FRR community
Running bgp convergence with the test and confirming it improves the performance.  Previously the time to learn 6k IPv6 routes was 30-40 seconds and after this fix it is less than 10 seconds.
> [FRR]Fixing BGP performance issues with BMP enabled

- rules/docker-platform-monitor.mk
For platform using sysfs, the current pmon is broken.
```
admin@sonic:~$ docker exec -it pmon bash
root@sonic:/# python3
Python 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] on linux
>>> open('/sys/class/i2c-adapter/i2c-71/71-0050/eeprom', mode='r+b', buffering=0)
File "<stdin>", line 1, in <module>
OSError: [Errno 30] Read-only file system: '/sys/class/i2c-adapter/i2c-71/71-0050/eeprom'
```
After this fix
```
admin@sonic:~$ docker exec -it pmon bash
root@sonic:/# python3
Python 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] on linux
>>> open('/sys/class/i2c-adapter/i2c-71/71-0050/eeprom', mode='r+b', …
```
> Add sysfs mount for pmon container

- files/build_templates/docker_image_ctl.j2
On platforms using the IPMI interface, the current pmon is broken.
```
root@sonic:~# show logging "Could not open device"
2025 Sep 18 02:18:30.578482 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:18:31.689267 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:55.434346 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:57.355865 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:57.355865 sonic INFO …
```
> Add ipmi device for pmon container

- dockers/docker-orchagent/ipinip.json.j2
Currently there is no tunnel being created when more than 128 addresses in the system. 
This PR enables for loopback addresses in this scenario as it's still needed.
- Microsoft ADO **34827134**:
Update the tunnel address to include loopback IPv4 and IPv6 addresses.
202412
> add loopback&vlan into the ipinip tunnel list for large topo

- azure-pipelines.yml
To add an automated T2 topo PR checker to prevent incoming changes breaking fundamentals of SONiC T2.
- Microsoft ADO **(number only)**: 35027068
Change the azure-pipeline template
Check the pipeline results.
> Add T2 PR checker

- platform/nvidia-bluefield/recipes/bluefield-soc.mk
- platform/nvidia-bluefield/recipes/sdk.mk
To include latest fixes and new functionality
* SDK_VERSION_DPU 25.7-RC6 -> 25.7-RC10
* BFSOC_VERSION 4.11.0 -> 4.12.0
Build an image and run tests from "sonic-mgmt".
>  [DPU] Update BFSoC to 4.12.0, SDK to 25.7-RC10

- platform/nvidia-bluefield/sdk-src/nv_hws/Makefile
Because of the missing change, on build servers where the clock is not synced, it might lead to build failure
```
ERROR: Clock skew detected. File /sonic/platform/nvidia-bluefield/sdk-src/nv_hws/nv_hws/obj-aarch64-linux-gnu/../meson.build has a time stamp 10428.1250s in the future.
dh_auto_configure: error: cd obj-aarch64-linux-gnu && LC_ALL=C.UTF-8 meson setup .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/aarch64-linux-gnu --buildtype=release -Ddefault_library=both -Db_lto=true -Dflexio=disabled returned exit code 1
```
Build is successful
> [nvidia-bluefield] Fix clock skew build failure

- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2-FANOUT/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2-LAB/th5-a7060x6-16pe-384c.config.bcm
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2/th5-a7060x6-16pe-384c.config.bcm
This PR is to set `sai_stats_support_mask` to `0x800` for Moby HWSKUs. This is a continuation of https://github.com/sonic-net/sonic-buildimage/pull/23772
* Microsoft ADO **34515971**:
* CSP **CS00012419125**
Update config.bcm
The change is verified by running PFCWD test on a physical testbed.
Set `sai_stats_support_mask` to `0x800` for Moby HWSKUs.
>  Update sai_stats_support_mask for Moby hwsku to remove PFC pause from port counter

- device/arista/x86_64-arista_7060x6_64pe_b/sensors.conf
Update sensor.conf SCD address with value from 'i2cdetect -l'. 
Add chip name and fan ignore to sensor.conf.
This will stop `ALERT pmon#sensord: Sensor alarm: Chip dps800-i2c-30-58: fan3: -1 RPM [ALARM]`
Confirmed that it stopped the log alert on Quicksilver 512 dut.
> [Arista] Update sensor.conf for 7060X6-64PE-B

- files/scripts/arp_update
- This change is being implemented in `arp_update` script to ensure neighbor resolution works properly after firmware upgrades and system repaves.
- This change was originally developed and validated on 202205, 202211 image (https://github.com/sonic-net/sonic-buildimage/pull/15006), and is now being backported to 202305 and newer versions to maintain consistent neighbor resolution across images of all sonic versions.
- The `arp_update` script now defines kernel neighbors (`KERNEIGH4` and `KERNEIGH6`) based on different device subtype to properly handle DualToR.
After firmware upgrades/repaves, devices will experience neighbor resolution issues because kernel neighbor table can be empty/missing entries, and hence traffic going to certain neighbors will drop.
- In Non-DualToRs, …
> [arp_update]Resolve neighbors from config_db

- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7060x6_16pe_384c_b/Arista-7060X6-16PE-384C-B-O128S2/buffers_defaults_t1.j2
- files/build_templates/qos_config.j2
- src/sonic-config-engine/sonic-cfggen
- src/sonic-config-engine/tests/sample-arista-7060x6-t0-minigraph.xml
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7060x6.json
- src/sonic-config-engine/tests/test_j2files.py
Disable pfc and pfcwd on service ports since they carry lossy traffic and do not require any pfc config
Finetune buffer and qos configs
Copy templates onto switch, reload the config and see the new config db
Disable PFC and PFCWD on service ports
All unit tests pass 
```
collected 312 items
tests/test_cfggen.py ....................................................................................                                                            [ 26%]
tests/test_cfggen_from_yang.py ..................                                                                                                                    [ 32%]
tests/test_cfggen_pfx_filter.py . …
```
> [QoS] Disable pfc and pfcwd on service ports

- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample_output/py3/qos-arista7060x6.json
Remove config keys for pfc and pfcwd on service ports
By setting the keys to an empty string "" for `pfcwd_sw_enable`, the buffermgrd still creates corresponding entries in the `PFC_WD` table. This in turn misleads the pfcwd orch to check for TCs where PFCWD is enabled on those service ports which it cannot find since it's an empty string resulting in this constant error stream:
```
2025 Sep 27 12:56:29.631650 str5-7060x6-moby-512-2 NOTICE swss#orchagent: :- registerInWdDb: No lossless TC found on port Ethernet512 
2025 Sep 27 12:56:29.631650 str5-7060x6-moby-512-2 ERR swss#orchagent: :- createEntry: Failed to start PFC Watchdog on port Ethernet512 
2025 Sep 27 12:56:29.631650 str5-7060x6-moby-512-2 NOTICE swss#orchagent: :- registerInWdDb: No lossless TC found on port Ethernet513 
2025 …
```
> [QoS] Remove config keys for pfc and pfcwd on service ports

- .azure-pipelines/template-daemon.yml
- slave.mk
In some cases builds maybe stuck.
Some hangs on docker build and some hangs on dpkg install.
- Microsoft ADO **(number only)**:  35240457
Update pipeline daemon step to avoid docker build stuck.
Add retry limit when dpkg install.
> [build] Refine docker build hanging and dpkg install hanging.

- scripts/build_mirror_config.sh
Update DEFAULT_MIRROR_SECURITY_URLS for buster as it's EOL
update in build_mirror_config.sh
Build buster must be successful
> Fix build sources

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C28S4/BALANCED/buffers_defaults_t0.j2
Fixes Headroom tests for 7050CX3-32C topo: t0-d18u8s4
> Increase egress and ingress buffer pool sizes on Arista-7050CX3-32S-C28S4

- platform/mellanox/mlnx-platform-api/sonic_platform/module.py
- platform/mellanox/mlnx-platform-api/tests/test_module.py
This change is added in order to remove the smartswitch reboot type from the module implementatoin, which was used to improve reboot time by not waiting for the DPU reboot to complete, this method improves reboot time, but causes race conditions with stop command of MFT driver. So at this point we complete the DPU reboot each time
Remove the check whether the type of reboot is `MODULE_REBOOT_DPU` or `MODULE_REBOOT_SMARTSWITCH` and perform complete DPU reboot each time we call the module based reboot
Manually verified to check if the reboot of the DPU is complete after execution of `reboot` on DPU on 202506 image
`tests/test_module.py::TestModule::test_dpu_module PASSED                 [ 52%]`
> [Mellanox][Smartswitch] Set default reboot type as DPU reboot

- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/th5-a7060x6-64pe.config.bcm
- device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/th5-a7060x6-64pe.config.bcm
Currently, Broadcom TH5 switches (Arista 7060X6) use queue 9 to send trimmed packets. This PR changes the `.bcm` config file for two 7060X6 models to use queue 4 for sending trimmed packets.
- Microsoft ADO **(number only)**: 35390583
Updated the `.bcm` config files for the target models.
1. Build an image with these changes (or directly update these files on a TH5 switch).
2. Load the image to your switch (or run `sudo config reload -y` on the switch if you updated these files directly on the switch).
3. Verify that trimmed packets are sent out from queue 4:
```
$ queuestat -p Ethernet64 --all
Last cached time was 2025-10-02T21:22:12.460993
Ethernet64 Last cached time was 2025-10-02T21:22:12.460993
Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes    Trim/pkts …
```
> Changed the trim queue index to 4 for some Broadcom TH5 switches
