sonic-net/sonic-buildimage

dockers/docker-router-advertiser/docker-init.sh

Calls to sonic-cfggen is CPU expensive. This PR reduces calls to
sonic-cfggen to one call during startup when starting radv service.
Reduce time required when invoking swss
Used template batch mode to batch together three calls into one call to sonic-cfggen
```
root@str-s6000-acs-14:/# time ./docker-init-old.sh 
real	0m5.099s
user	0m4.180s
sys	0m0.585s
root@str-s6000-acs-14:/# time ./docker-init-new.sh 
real	0m1.583s
user	0m1.335s
sys	0m0.200s
root@str-s6000-acs-14:/# diff /etc/supervisor/conf.d/supervisord.conf.old /etc/supervisor/conf.d/supervisord.conf.new 
root@str-s6000-acs-14:/# diff /etc/radvd.conf.old /etc/radvd.conf.new 
root@str-s6000-acs-14:/# diff …
```

[radv] Reduce Calls to SONiC Cfggen

---

src/sonic-py-common/sonic_py_common/multi_asic.py

the API `is_port_channel_internal(port_channel, namespace=None):` always returns False.
Fix the checks in the API `is_port_channel_internal`

[Multi Asic]: Fix to prevent classification all  portchannels is External

---

device/virtual/x86_64-kvm_x86_64-r0/pmon_daemon_control.json

Why I did:
skip_thermalctld for VS platform  as it is not supported. 
Otherwise syslog gets flooded with error messages.
How I verify:
root@vlab-01:/# supervisorctl status
dependent-startup                EXITED    Aug 18 06:22 AM
rsyslogd                         RUNNING   pid 18, uptime 0:12:26
start                            EXITED    Aug 18 06:22 AM
supervisor-proc-exit-listener    RUNNING   pid 13, uptime 0:12:27

[201911] skip_thermalctld for VS platform 

---

src/sonic-config-engine/sonic-cfggen
src/sonic-py-common/sonic_py_common/multi_asic.py

Update the name from  get_npu_device_id() -to  get_asic_device_id() and move from device_info.py, to the new file multi_asic.py in sonic-py-common so that it references to the correct valid constants. 
Changed the name at places where we are referring the same.

Updates to move the function get_asic_device_id() into the sonic-py-common

---

src/sonic-config-engine/minigraph.py
src/sonic-py-common/sonic_py_common/interface.py
src/sonic-py-common/sonic_py_common/sonic_interface.py

There are many places in the code where there is hardcoding to the way we refer to the Sonic front-panel/backplane interface prefixes.  The idea with this PR is to keep this SONIC PREFIX naming convention in one place in py-common and all modules/applications use the functions defined here. 
To start with I have add a file sonic_interface.py in sonic-py-common with API's to get the sonic interface prefix string. Can add more sonic interface specific utilities here. This is useful especially in the sonic-utilities show/config modules. 
Newly added  functions were verified with CLI commands.

[sonic-py-common] Add interface utilities

---

Makefile.work

Why I did:
INCLUDE_RESTAPI=y was not taking effect.
Fix the makefile to use include for restapi and telemetry.
As part of cherry-pick from master into 201911 conflict
was not handled correctly.
How I verify:
INLCUDE_RESTAPI is fine after change.
BLDENV=stretch make SONIC_BUILD_JOBS=8 INCLUDE_RESTAPI=y target/docker-syncd-brcm.gz-clean
Build Configuration
"CONFIGURED_PLATFORM"             : "broadcom"
"CONFIGURED_ARCH"                 : "amd64"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "8"
"SONIC_CONFIG_MAKE_JOBS"          : "1"
"SONIC_USE_DOCKER_BUILDKIT"       : ""
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : "" …

[201911] Fix make command line option.

---

device/barefoot/x86_64-accton_as9516bf_32d-r0/pmon_daemon_control.json
device/barefoot/x86_64-accton_wedge100bf_32x-r0/pmon_daemon_control.json
platform/barefoot/sonic-platform-modules-bfn-montara/debian/rules
platform/barefoot/sonic-platform-modules-bfn-montara/plugins/pcie.yaml
platform/barefoot/sonic-platform-modules-bfn-newport/debian/rules
platform/barefoot/sonic-platform-modules-bfn-newport/plugins/pcie.yaml

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
- Add PCIe config file 
- Turn on pcied daemon 
Add support pcied daemon for Barefoot platforms (Montara and Newport)

[BFN] Add support pcied daemon for Montara and Newport

---

platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/fast-reboot_plugin
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/pcisysfs.py
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_bitbang_reset.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_i2c_enumeration.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
platform/broadcom/sonic-platform-modules-dell/s6100/systemd/s6100-i2c-enumerate.service

To resolve ISMT timeout issue, I2C changes has to be ported from master branch.
Verify bit bang  reset logs in the syslog, check whether all the I2C components are coming up and verify show interfaces transceiver commands.
Added I2C enumeration as a service in PMON.
Added Bit bang reset mechanisms.
[201911_i2c.txt](https://github.com/Azure/sonic-buildimage/files/5056301/201911_i2c.txt)

Dell S6100 Port I2C changes to 201911 branch

---

src/sonic-config-engine/sonic-cfggen

Argument to write to config-db is not allowed when using template.
This PR allows cfggen to write to redis db when using template
mode.
Reduce CPU util during bot
relocate write-to-db to new section such that it is not mutually exclusive with new batch mode
I did load minigraph with and without this change and the resulting config_db is the same
```
admin@str-s6000-acs-14:~$ diff config_db.json.new config_db.json.old
admin@str-s6000-acs-14:~$ 
```
During boot profiling, there was about 1~1.5% CPU reduction when batching 4 cfggen calls into one call.
**- A picture of …

[cfggen] Allow Write To Redis DB With Template/Batch Mode

---

files/build_templates/init_cfg.json.j2
files/image_config/hostcfgd/hostcfgd

SNMP and Telemetry services are not critical to switch startup.
They also cause fast-reboot not to meet timing requirements.
In order to delay start those service are associated with systemd
timer units, however when hostcfgd initiate service start, it start
the service and not the timer. This PR fixes this issue by
starting the timer associated with systemd unit.
Fixes  Azure/sonic-buildimage#5172
closes Azure/sonic-buildimage#5172
Mellanox reports fast-reboot is failing due to anmp/telemetry services being started early
Enabled systemd timer unit instead of systemd service unit
fast-reboot :
```
admin@str-s6000-acs-14:~$ docker ps -a
CONTAINER ID        IMAGE …
```

[services] Fix Delay Start of SNMP And Telemetry

---

src/sonic-py-common/sonic_py_common/multi_asic.py

API to get a list of frontend ports from a given list of ports. There are APIs to find the port role but it can only be used one a time resulting in getting the list of ports from config DB for each query.
Get the list of ports only once and check ports that is passed as a port list or set. 
verified using the show command.
```
Before:
admin@str-n3164-acs-2:/usr/bin$ pfcstat -n asic0
Port Rx    PFC0    PFC1    PFC2    PFC3    PFC4    PFC5    PFC6    PFC7                                                                                                         
-------------  ------  ------  ------  ------  ------  ------  ------  ------ …
```

[sonic-py-common][multi ASIC] API to get a list of frontend ports

---

.gitignore
src/sonic-config-engine/.gitignore

- Ignore directories generated by building Python wheel package
- Move all sonic-config-engine ignores from the root .gitignore to src/sonic-config-engine/.gitignore

[sonic-config-engine] Update .gitignore

---

files/build_templates/sonic_debian_extension.j2
files/image_config/caclmgrd/caclmgrd
slave.mk

Following changes were done:
1) Moved from using blocking listen() on Config DB to the select() model
via python-swsscommon since we have to wait on event from multiple
config db's
2) Since  python-swsscommon is not available on host added libswsscommon and python-swsscommon
and dependent packages in the base image (host environment)
3) Made iptables programmed in all namespace using ip netns exec
4) Added Change for Multi-asic to have iptables
rules to accept internal docker tcp/udp traffic needed for syslog and redis-tcp connection.
Testing:
Verified on Multi-Asic Platforms and Single-Asic Platforms.
O/P on Host on Multi-asic platforms:
===========================
sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  -- …

[caclmgrd] Add support for multi-ASIC platforms

---

platform/vs/docker-sonic-vs/Dockerfile.j2
platform/vs/docker-sonic-vs/hwsku.json
platform/vs/docker-sonic-vs/platform.json
platform/vs/docker-sonic-vs/start.sh
platform/vs/tests/breakout/sample_output/sample_new_port_config.json
platform/vs/tests/breakout/test_breakout_cli.py

1. This reverts commit 457674ce00adf2b03d33db24399e5d05b2b7478e. -- **first commit**
2. Also, made a small change in terms of  admin status of all the interfaces from up to down to be compatible with swss vs test cases specially both vnet tests, sflow tests. ->  **second commit**
Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>
Created the VS setup to test DPB functionality.
1. Created "platform.json" for vs docker.
2. Added Test case for Breakout Cli
> we also need to update swss submodule once this PR gets merged so that test_speed.py doesn't have any hard-coded speed dependency. otherwise, this test case will fail.
```
samaity@server09:~/REPO_FACTORY/GIT_REPO/DPB/sonic-buildimage/platform/vs/tests$ sudo pytest -s -vv --dvsname=vs-sa …
```

Revert "Revert 'DPB Breakout Cli Test with proper setup (#3910)' "

---

device/virtual/x86_64-kvm_x86_64-r0/pmon_daemon_control.json
src/sonic-py-common/sonic_py_common/device_info.py

[201911] After PR #https://github.com/Azure/sonic-buildimage/pull/5204
this function is no more needed so cleaning up.

[201911] Multiasic cleanup of get_npu_device_id()

---

.gitignore
sonic-slave-buster/Dockerfile.j2
src/sonic-py-common/.gitignore
src/sonic-py-common/pytest.ini
src/sonic-py-common/setup.cfg
src/sonic-py-common/setup.py
src/sonic-py-common/sonic_py_common/device_info.py
src/sonic-py-common/tests/device_info_test.py

To install the framework for adding unit tests to the sonic-py-common package and report coverage.
** How I did it **
- Incorporate pytest and pytest-cov into sonic-py-common package build
- Updgrade version of 'mock' installed to version 3.0.5, the last version which supports Python 2. This fixes a bug where the file object returned from `mock_open()` was not iterable (see https://bugs.python.org/issue32933)
- Add support for Python 3 setuptools and pytest in sonic-slave-buster environment
- Add tests for `device_info.get_machine_info()` and `device_info.get_platform()` functions
- Also add a .gitignore in the root of the sonic-py-common directory, move all related ignores from main .gitignore file, and add ignores for files and dirs generated by pytest-cov.
**- How to …

[sonic-py-common] Add unit test framework

---

dockers/docker-orchagent/enable_counters.py

Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
**Do not merge yet**,
Should go on top of https://github.com/Azure/sonic-swss/pull/1368
Submodule update:
SAI_Implementation
- reenable port in/oit dropped pkts stats
Introduce separate FC group for port level buffer drop counters as discussed in [#1308](https://github.com/Azure/sonic-swss/pull/1308)

[enable counters] enable port buffer drops by default

---

src/sonic-config-engine/sonic-cfggen

This PR enables cfggen to read/write from Redis DB using pipelines.
Pipelines enables batch read/write from/to Redis DB.
depends: Azure/sonic-buildimage#5249
cfggen uses extensive CPU plus read/write from/to Redis DB is slow
Update sonic cfggen to use Redis pipelines
Current Connector
```
admin@str-s6000-acs-14:~$ time sudo sonic-cfggen -j /etc/sonic/config_db.json --write-to-db
real	0m2.286s
user	0m1.608s
sys	0m0.364s
admin@str-s6000-acs-14:~$ time sonic-cfggen -d --print-data > dump_old_debug.json 
real	0m2.219s
user	0m1.816s
sys	0m0.360s
```
Pipe Connector
```
admin@str-s6000-acs-14:~$ time sudo sonic-cfggen -j /etc/sonic/config_db.json --write-to-db
real	0m1.648s
user …
```

[cfggen] Use Redis Pipeline

---

files/image_config/hostcfgd/hostcfgd

New attribute 'has_timer' introduced to init_cfg.json does not evaluate
as Bool, rather it evaluates as string. This PR fixes this issue. Also,
this PR fixes an issue when there is system config unit (snmp. telemetry) 
has no installation config (WantedBy=, RequiredBy=, Also=, Alias=) settings
in the [Install] section. In the latter case, the .service should not be enabled.
The issue appears to be stemming from config_db as the new has_timer is stored as string in the config_db
```
"FEATURE": {
"bgp": {
"auto_restart": "enabled", 
"has_timer": "False", 
"high_mem_alert": "disabled", 
"state": "enabled"
}, 
"database": {
"auto_restart": "disabled", 
"has_timer": "False", 
"high_mem_alert": "disabled", 
"state": "enabled"
}, …
```

[hostcfgd] Fix Boolean String Evaluation

---

files/build_templates/init_cfg.json.j2
files/build_templates/mgmt-framework.service.j2
files/build_templates/mgmt-framework.timer
files/build_templates/sonic_debian_extension.j2

management framework provides management plane services like rest and
CLI which is not needed right after boot, instead by delaying this
service we give some more CPU for data plane and control plane services
on fast/warm boot.

[services][mgmt-framework] delay mgmt-framework service on boot

---

dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
dockers/docker-fpm-frr/frr/common/functions.conf.j2
src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/all.json
src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/defaults.json

Vnet vlan interfaces should not be part of advertised networks by FRR
Using vtysh
- [x ] 201911

Skip vnet-vxlan interfaces from generating networks

---

src/sonic-py-common/sonic_py_common/interface.py
src/sonic-py-common/sonic_py_common/multi_asic.py
src/sonic-py-common/tests/interface_test.py

Move the common multi-asic/general functions from sonic-utilities to py-common 
validate_namespace()
get_port_table_name()
get_interface_table_name()

[sonic-py-common] Relocate some functions from sonic-utilities

---

dockers/docker-orchagent/ipinip.json.j2
src/sonic-config-engine/tests/multi_npu_data/ipinip.json
src/sonic-config-engine/tests/test_j2files.py

Multi asic platform have 2 Loopback interfaces, Loopback0 and Loopback4096. IPinIP decap entries need to be added for both of them.
Update the ipinip.json.j2 template to add decap entries for Loopback4096.
Add corressponding unit test
Verify the ipinip.json is generated properly.
- [ x] 201911

[Multi-ASIC]:Update the template to add ipinip entry for Loopback4096

---

dockers/docker-snmp-sv2/Dockerfile.j2

[Build] pin down setuptools for build issues
See: https://github.com/Azure/sonic-buildimage/issues/5279
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
This is same as https://github.com/Azure/sonic-buildimage/pull/5280, but cherry-pick won't work due to conflicts so raised another PR.
Build failed
pin down the setuptools version
Build successfully after the fix
It should go to 201811 and 201911

[201911][Build] pin down setuptools for build issues

---

src/iccpd/src/iccp_cmd_show.c

Signed-off-by: Sun Dandan <sundandan@asterfusion.com>
The cmd "mclagdctl dump state" would goes wrong when there are two or more mclag_groups configured. The field "MCLAG Interface" can not be displayed in some group.
Reset the len in each csm.
When 4 mclag_groups were configured, running cmd "mclagdctl dump state" display all mclag_group correctly.

[iccpd] Fix the bug of iccp cmd show.

---

platform/vs/docker-sonic-vs/Dockerfile.j2
platform/vs/docker-sonic-vs/start.sh

sonic-py-common package relies on the `PLATFORM` environment variable to be set at runtime in the SONiC VS container. Exporting the variables in the start.sh script causes the variables to only be available to the shell running start.sh and any subshells it spawns. However, once the script exits, the variable is lost. This is resulting in the failure of tests which are run in the VS container, as they call applications which in turn call sonic-py-common functions which rely on `PLATFORM` to be set (e.g., https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-all-pr/4805/console)
Setting the environment variables in the Dockerfile allows them to persist through the entire runtime of the container.
Set the `PLATFORM` and `HWSKU` …

[docker-sonic-vs] Set PLATFORM and HWSKU env vars in Dockerfile

---

platform/vs/docker-sonic-vs/Dockerfile.j2
platform/vs/docker-sonic-vs/start.sh

Copying platform.json file into an empty /usr/share/sonic/platform directory does not mimic an actual device. A more correct approach is to create a /usr/share/sonic/platform symlink which links to the actual platform directory; this is more like what is done inside SONiC containers. Then, we only need to copy the platform.json file into the actual platform directory; the symlink takes care of the alternative path, and also exposes all the other files in the platform directory.
One question: Since the SONiC VS container mimics the host OS of a physical switch, do we even need to create the /usr/share/sonic/platform and /usr/share/sonic/hwsku symlinks? Maybe we can remove these in a future patch.
Create /usr/share/sonic/platform symlink in start.sh
**- …

[docker-sonic-vs] Create /usr/share/sonic/platform symlink

---

dockers/docker-snmp-sv2/Dockerfile.j2

[Build] pin down setuptools for build issues
See: https://github.com/Azure/sonic-buildimage/issues/5279
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
Build failed
pin down the setuptools version
Build successfully after the fix
It should go to 201811 and 201911

[201811][Build] pin down setuptools for build issues

---

files/image_config/caclmgrd/caclmgrd

What I did:-
Submodule update of sonic-swss-common with PR's
[schema] Make schema header support C project (#373)
Removed DB specific get api's from Selectable class (#378)
With the change as part of PR#378 caclmgrd client need to be updated
to use new client side Get API to access namespace.
How I verify:
Verify caclmgrd service works fine after this changes.

submodule update of sonic-swss-common and corresponding caclmgrd client changes.

---

build_debian.sh
files/build_templates/docker_image_ctl.j2

sonic-cfggen is now using Unix Domain Socket for Redis DB. The socket
is created using root account. Subsequently, services that are started
as admin fail to start. This PR creates redis group and add admin
user to redis group. It also grants read/write access on redis.sock
for redis group members.
closes #5277 
resolves #5277 
Access to redis.sock fails when using admin account
Added `redis` group
Changed `redis.sock` group to the new group `redis`
Gave read/write access to `redis` group on `redis.sock`
without this change
```
admin@str-s6000-acs-14:~$ groups
admin sudo docker
admin@str-s6000-acs-14:~$ ls -alrt /var/run/redis/redis.sock 
srwx------ 1 root root 0 Aug 31 …
```

[redis] Add redis Group And Grant Read/Write Access to Members

---

build_debian.sh

This would enable the coredump_compress script to retrieve additional info regarding the crashing process.
To facilitate coredump_compress script. Currently there is a need to identify the namespace of a crashing  process.
By passing %P as part of core-pattern, which translates to "` %P  PID of dumped process, as seen in the initial PID namespace`"
You can use the last parameter to be able look  into /proc/<pid>/ folder for crashing process from the coredump_compress script.
Backport to all branches that support multi-asic.

Pass pid of process as seen  in host to coredump_compress script

---

dockers/docker-orchagent/swssconfig.sh

Why I did:
Fixes the issue https://github.com/Azure/sonic-buildimage/issues/5255
Root Cause: Waiting on Restore count != 0 can lead to race condition
between orchagent process and swssconfig.sh.
Ideally check of  Restore count != 0 is not needed as the State DB
cannot be flushed as if it was flushed then Warm Restart or swss-restart
enable flag should not be true also.
How I verify:
After removing check did not hit race condition that resulted the error.

[warm-boot] Fix the issue as reported in https://github.com/Azure/sonic-buildimage/issues/5255

---

src/sonic-config-engine/portconfig.py
src/sonic-config-engine/sonic-cfggen
src/sonic-py-common/sonic_py_common/device_info.py

This PR addresses fixes in sonic-py-common to imitate the behavior inside 
sonic-cfggen. Essentially this is a fix for accessing the port-config file. 
First check if there is a platform.json file for config generation 
and then for legacy port_config.ini. 
Also updating the sub-module sonic-utilities. 
sonic-utilities update submodule includes all these PR's 
Fix pfcwd stats crash with invalid queue name (#1077)
[show][bgp]Display the Total number of neighbors in the show ip bgp(v6) summary. (#1079)
[config] Update SONiC Environment Vars When Loading Minigraph (#1073)
Multi asic platform changes for interface, portchannel commands (#878)
Update Command-Reference.md (#1075)
[filter-fdb] Fix Filter FDB With IPv6 Present in Config DB (#1059)
[config] Remove _get_breakout_cfg_file_name …

[sonic-utilities][sonic-py-common] Move logic to get port config file path to sonic-py-common and update sonic-utilities to comply

---

device/dell/x86_64-dell_s6100_c2538-r0/installer.conf
files/image_config/platform/rc.local

We want to support pick configuration from /dev/sda12 automatically after cold reboot for s6100
1. Append nos-config-part to ONIE_PLATFORM_EXTRA_CMDLINE_LINUX
1. Always mkdir before migrate nos configuration
1. Always migrate nos configuration
1. Build image and install to a 6100 SONiC DUT
1. Copy configurations to ```/etc/sda12```
1. Clear /host/old_config
1. Reboot and verify if the configuration been picked
[conf] support pick configuration from /dev/sda12 by configure installer.conf

[conf] append nos-config-part for s6100

---

dockers/docker-base-buster/Dockerfile.j2
dockers/docker-database/Dockerfile.j2
platform/vs/docker-sonic-vs/Dockerfile.j2

Upstream link broken and the build is failed
Use redis-server and redis-tools in blob storage

[redis] Use redis-server and redis-tools in blob storage to prevent upstream link broken

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
dockers/docker-lldp/supervisord.conf.j2
dockers/docker-nat/supervisord.conf
dockers/docker-orchagent/supervisord.conf
dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
dockers/docker-router-advertiser/docker-router-advertiser.supervisord.conf.j2
dockers/docker-sflow/supervisord.conf
dockers/docker-snmp/supervisord.conf
dockers/docker-sonic-mgmt-framework/supervisord.conf
dockers/docker-sonic-restapi/supervisord.conf
dockers/docker-sonic-telemetry/supervisord.conf
dockers/docker-teamd/supervisord.conf
platform/barefoot/docker-syncd-bfn/supervisord.conf
platform/broadcom/docker-syncd-brcm/supervisord.conf
platform/centec-arm64/docker-syncd-centec/supervisord.conf
platform/innovium/docker-syncd-invm/supervisord.conf
platform/marvell-arm64/docker-syncd-mrvl/supervisord.conf
platform/marvell-armhf/docker-syncd-mrvl/supervisord.conf
platform/marvell/docker-syncd-mrvl/supervisord.conf
platform/mellanox/docker-syncd-mlnx/supervisord.conf
platform/nephos/docker-syncd-nephos/supervisord.conf
platform/vs/docker-syncd-vs/supervisord.conf
src/sonic-config-engine/tests/sample_output/docker-dhcp-relay.supervisord.conf

When stopping the swss, pmon or bgp containers, log messages like the following can be seen:
```
Aug 23 22:50:43.789760 sonic-dut INFO swss#supervisord 2020-08-23 22:50:10,061 ERRO pool dependent-startup event buffer overflowed, discarding event 34
Aug 23 22:50:43.789760 sonic-dut INFO swss#supervisord 2020-08-23 22:50:10,063 ERRO pool dependent-startup event buffer overflowed, discarding event 35
Aug 23 22:50:43.789760 sonic-dut INFO swss#supervisord 2020-08-23 22:50:10,064 ERRO pool dependent-startup event buffer overflowed, discarding event 36
Aug 23 22:50:43.789760 sonic-dut INFO swss#supervisord 2020-08-23 22:50:10,066 ERRO pool dependent-startup event buffer overflowed, discarding event 37
```
This is due to the number of programs in the container managed by supervisor, all …

[dockers][supervisor] Increase event buffer size for dependent-startup

---

device/barefoot/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
Due to https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation, yaml.load(input) is deprecated.  Added a specifying parameter to fix this issue.

[BFN] Fix vulnerability in eeprom.py

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/dhcpmon/src/dhcp_device.c
src/dhcpmon/src/dhcp_device.h
src/dhcpmon/src/dhcp_devman.c
src/dhcpmon/src/dhcp_devman.h
src/dhcpmon/src/dhcp_mon.c
src/dhcpmon/src/main.c
src/sonic-config-engine/tests/sample_output/docker-dhcp-relay.supervisord.conf

When BGP routes are missing, DHCP packets get relayed over mgmt
interface. This results in dhcpmon alerting that DHCP packets are
not being relayed. This is PR include mgmt interface as uplink
device, and so, if DHCP packet gets relayed over mgmt interface,
regular dhcpmon alert will not be issues. Instead, dhcpmon will
check the mgmt interface counts and issue a separate alert regarding
packets travelling through mgmt network.
In addition, this PR include the following enhancements:
1. Add SIGUSR1 handler that prints out current packet counts
2. Increase alert grace window to 3 minutes from current 2 min
3. Time is not computed more accurately
4. Print vlan name before counters
DHCP Monitor is alerting when DHCP …

[dhcpmon] Monitor Mgmt Interface For DHCP Packets

---

Makefile.cache
Makefile.work
slave.mk

Most of the devs know how they configured their build.
Instead of generating a huge header for every make operation, allow the
user to silence it via an environment variable.
Also add SONIC_BUILDER_EXTRA_ENV variable which allows the user to
inject arbitrary options to the docker run cmdline for the builder as part of tooling.
Just added a few ifdef in some Makefiles.
Set the SONIC_BUILD_QUIETER environment variable with any value to prevent
make from displaying all the build options.
```
SONIC_BUILD_QUIETER=y make ...
bash% SONIC_BUILD_QUIETER=1 NOJESSIE=1 NOSTRETCH=1 make configure PLATFORM=broadcom
+++ Making configure +++
BLDENV=buster make -f Makefile.work configure
make[1]: Entering directory …
```

Allow user to silence variable dump during make

---

.gitignore
slave.mk

This change introduces the `rules/config.user` file.
Since this path is tracked by `.gitignore`, it provides a mean to change 
the configuration of a sonic build without dirtying the git tree.
This configuration gets loaded after `rules/config` as a mean to override default values.
Thus it allows the default configuration to grow with new default values without having
to track each and single one of them when one generates a configuration.
If the `rules/config.user` configuration file does not exists this step is ignored.
Here is an example of the use of `rules/config.user`
```
echo DEFAULT_PASSWORD=password > rules/config.user
```
You should now see the new password being displayed when running a `make` operation.
Running `git …

Add a user defined rules/config file not tracked by git

---

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfplpmget.py
device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfplpmset.py
device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfpreset.py
platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py

Refactor SFP reset, low power get/set API, and plugins with new SDK SX APIs. Previously they were calling SDK SXD APIs which have glibc dependency because of shared memory usage.   
Remove implementation "set_power_override", "tx_disable_channel", "tx_disable" which using SXD APIs, once related SDK SX API available, will add them back based on new SDK SX APIs.
Refactor these API/Plugins with new set of SDK sx_mgmt_* APIs.
Use sfputil command to test the plugin; load platform APIs and test changed APIs
[Mellanox] Refactor SFP related platform API and plugins with new SDK API
**- A picture of a cute animal (not mandatory …

[Mellanox] Refactor SFP related platform API and plugins with new SDK API

---

device/mellanox/x86_64-mlnx_msn2010-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn2100-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn2410-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn2700-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn2740-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn3420-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn3700-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn3700c-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn3800-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn4600c-r0/platform_components.json
device/mellanox/x86_64-mlnx_msn4700-r0/platform_components.json

* Updated Mellanox platform components config files
* N/A
1. show platform firmware updates
* N/A
```
'//||\\`
''``
```

[Mellanox] Update platform components config files

---

files/image_config/hostcfgd/hostcfgd

In order to make hostcfgd not to fail if feature has no 'has_timer' field
Change the update_feature_state call to pass False by default.
Enable feature that has no 'has timer' field and make sure hostcfgd not failing. 

Change update_feature_state call to pass False as default if feature has no 'has_timer' field

---

files/image_config/procdockerstatsd/procdockerstatsd

Eliminate duplicate logging code by inheriting from DaemonBase class in sonic-py-common package.
Ensure procdockerstatsd functionality is unchanged

[procdockerstatsd] Inherit DaemonBase class from sonic-py-common package

---

dockers/docker-lldp/lldpmgrd

Eliminate duplicate logging and signal handling code by inheriting from DaemonBase class in sonic-py-common package.
Ensure lldpmgrd functionality is unchanged

[lldpmgrd] Inherit DaemonBase class from sonic-py-common package

---

files/image_config/pcie-check/pcie-check.service
files/image_config/pcie-check/pcie-check.sh

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
pci-check.service and pcied daemon set different variables in STATE_DB.
- _pci-check.service_ set `"PCIE_STATUS|PCIE_DEVICES"` variable with type _**string**_, 
- _pcied daemon_ set  `"PCIE_STATUS|" -> "PCIE_DEVICES"`  variable with type _**hash**_.  
Change type for variable with PCI device status from `string` to `hash` ("PCIE_STATUS|PCIE_DEVICES" --> "PCIE_DEVICES" "status"), because haven't got [API ](https://github.com/Azure/sonic-py-swsssdk/blob/91cc6c651e903b65b95838dc3b2cd1d2751c63b6/src/swsssdk/dbconnector.py#L305) for work with string variable from Python. …

Fix bug with pcie-check.service

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/dhcpmon/debian/rules
src/dhcpmon/src/dhcp_device.c
src/dhcpmon/src/dhcp_device.h
src/dhcpmon/src/dhcp_devman.c
src/dhcpmon/src/dhcp_devman.h
src/dhcpmon/src/dhcp_mon.c

Printing both snapshot and current counter sets will make it easier to pinpoint
which message type(s) is/are not being relayed. This PR prints both counter sets.
Also, this PR defines gnu11 as a C standard to compile with in order to avoid
making change when porting to 201811 branch.
It is easier to see which message type is not being relayed when both snapshot and current counters are printed
Printed snapshot counters
Shutdown BGP sessions and run DHCP transactions
```
Sep 15 17:11:07.517450 str-s6000-acs-14 ALERT dhcp_relay#dhcpmon[43]: dhcpmon detected DHCP packets traveling through mgmt interface (please check BGP routes.) Duration: 270 (sec) for intf: 'eth0'
Sep 15 …
```

[dhcpmon] Print Both Snapshot And Current Counters

---

files/image_config/interfaces/interfaces.j2
src/sonic-config-engine/tests/sample_output/interfaces
src/sonic-config-engine/tests/sample_output/mvrf_interfaces

As per the VOQ HLDs, internal networking between the linecards and supervisor is required within a chassis.
Allocating 127.X/16 subnets for private communication within a chassis is a good candidate.
It doesn't require any external IP allocation as well as ensure that the traffic will not leave the chassis.
References:
https://github.com/Azure/SONiC/pull/622
https://github.com/Azure/SONiC/pull/639
Changed the `interfaces.j2` file to add `127.0.0.1/16` as the `lo` ip address.
Then once the interface is up, the post-up command removes the `127.0.0.1/8` ip address.
The order in which the netmask change is made matters for `127.0.0.1` to be reachable at all times.
```
root@sonic:~# ip address show dev lo
1: lo: …
```

Change the loopback interface netmask from /8 to /16

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/dhcpmon/debian/rules
src/dhcpmon/src/dhcp_device.c
src/dhcpmon/src/dhcp_device.h
src/dhcpmon/src/dhcp_devman.c
src/dhcpmon/src/dhcp_devman.h
src/dhcpmon/src/dhcp_mon.c
src/dhcpmon/src/main.c
src/sonic-config-engine/tests/sample_output/docker-dhcp-relay.supervisord.conf

commit 959f73a4a564fb39138641b9ac88dd0d2425de26 (HEAD -> taahme/port-dhcpmon-to-201811, fork/taahme/port-dhcpmon-to-201811)
Author: Tamer Ahmed <tamer.ahmed@microsoft.com>
Date:   Tue Sep 15 15:27:36 2020 -0700
[dhcpmon] Print Both Snapshot And Current Counters (#5374)
Printing both snapshot and current counter sets will make it easier to pinpoint
which message type(s) is/are not being relayed. This PR prints both counter sets.
Also, this PR defines gnu11 as a C standard to compile with in order to avoid
making changes when porting to 201811 branch.
commit 79013f03dfb16b63445b854a5d1752f03f161c89
Author: Tamer Ahmed <tamer.ahmed@microsoft.com>
Date:   Wed Sep 9 18:37:01 2020 -0700
[dhcpmon] Monitor Mgmt Interface For DHCP Packets …

port dhcpmon to 201811

---

files/image_config/process-reboot-cause/process-reboot-cause

Eliminate duplicate logging code by importing Logger class from sonic-py-common package.
Ensure process-reboot-cause functionality is unchanged

[process-reboot-cause] Use Logger class from sonic-py-common package

---

dockers/docker-orchagent/base_image_files/swssloglevel

Add the option -n to specify the swss docker instance running in a particular namespace to invoke swssloglevel. 
Update the script swssloglevel.
The following options in multi-asic platform.
```
admin@str-acs-1:~$ swssloglevel 
Usage: /usr/bin/swssloglevel -n [0 to 3] [OPTION]... 
admin@str-acs-1:~$ swssloglevel -h
Usage: /usr/bin/swssloglevel -n [0 to 3] [OPTION]...
admin@str--acs-1:~$ swssloglevel -n 0 
Invalid loglevel value
Usage: swssloglevel [OPTIONS]
SONiC logging severity level setting.
Options:
-h	print this message
-l	loglevel value
-c	component name in DB for which loglevel is applied (provided with -l)
-a	apply loglevel to all components (provided with -l)
-s	apply loglevel for SAI api component (equivalent to adding …
```

[multi-Asic] Add support for multi-asic to swssloglevel

---

files/image_config/caclmgrd/caclmgrd

Why/What i did:
Fix for multi-asic where we should allow namespace docker local communication on its docker/eth0 ip
. Without this TCP Connection to Redis Server running on docker eth0 ip does not happen in namespace if there is Catch all DROP Rule.
Found this issue as part of debugging
a)  lldpmgrd was not able to start in namespace (uses Redis TCP Connection)
b) Feature auto restart not working for namespace docker (supervisor-proc-exit-listener also  uses Redis TCP Connection)
How I verify:
After fix both issue (a) and (b) are working fine.

[Multi-Asic] Fix for multi-asic where we should allow namespace docker local communication on its docker/eth0 ip

---

dockers/docker-database/database_config.json.j2

Add new DB for Restapi.
This DB is used for storing RESTAPI docker's:
1. Reset info
2. Server Guid
3. Uptime

Add new DB for Restapi to database config

---

dockers/docker-orchagent/docker-init.sh

Arp update process was not being started due to an issue with
the directory name having an extra 'd' in supervisor as in
'/etc/supervisord/conf.d/arp_update.conf'.
related to: #5217
arp_update script is not running
Fixed a bug with the dir name
`/etc/supervisord/conf.d/` --> `/etc/supervisor/conf.d/`
After reboot, `arp_update` process should be running
```
admin@str-s6000-acs-14:~$ sudo zgrep arp_update /var/log/syslog*
Sep 17 01:32:29.345680 str-s6000-acs-14 INFO swss#supervisord 2020-09-17 01:32:25,607 INFO Included extra file "/etc/supervisor/conf.d/arp_update.conf" during parsing
Sep 17 01:33:09.656047 str-s6000-acs-14 INFO swss#supervisord 2020-09-17 01:33:02,318 INFO …
```

[swss] Start Arp Update Process

---

dockers/docker-sonic-mgmt/Dockerfile.j2

- Bump sonic-mgmt version to 18.04
- Update installation methods
- Add virtualenv for python3
1. We need (at least) python3.6 for the test reporting features.
2. We will eventually need python3.6+ support in the mgmt container to start migrating to python3
1. Bumped the version to 18.04
2. Moved from easy_install to apt to fix the pip installation
3. Used the "all in one" az-cli install to fix the az-cli install (which also fixed the az keyvault bug)
4. Added a python3 venv for test reporting
Ran it on our test server and verified that:
1. 201811 virtualenv still works
2. test-reporting-env works
3. pytest still works
4. ansible still works (config-based-on-testbed, add-topo, …

[mgmt] Upgrade sonic-mgmt container to stretch

---

platform/broadcom/sai.mk

ugprade Broadcom SAI to 3.5.3.5-2
Including following Broadcom patches:
- CS00010869953, CS00010914668(KB29456), CS00010503275(KB0029315), CS00010914673(KB0029442)
Nightly test.

[201811][bcm SAI] ugprade Broadcom SAI to 3.5.3.5-2

---

device/celestica/x86_64-cel_seastone-r0/Seastone-DX010-10-50/hwsku.json
device/celestica/x86_64-cel_seastone-r0/Seastone-DX010-25-50/hwsku.json
device/celestica/x86_64-cel_seastone-r0/Seastone-DX010-50-40/hwsku.json
device/celestica/x86_64-cel_seastone-r0/Seastone-DX010-50/hwsku.json
device/celestica/x86_64-cel_seastone-r0/Seastone-DX010/hwsku.json
device/celestica/x86_64-cel_seastone-r0/platform.json

[DPB Seastone] On boarding DPB feature to Seastone HWSKUs
This include the platform.json for Seastone platform and
individual hwsku.json for each HWSKU
port_config.ini will be removed once the CLI/parser library etc changes are merged
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
On boarding DPB feature to Seastone HWSKUs
Add platform.json for Seastone and hwsku.json files to relevant HWSKUs.
```
sudo sonic-cfggen -H -k Seastone-DX010 --preset=t1 > config_db.json
sudo config reload config_db.json -y
show interface status:
admin@lnos-x1-a-csw03:~$ show interfaces status 
Interface            Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  ----- …
```

[DPB Seastone] On boarding DPB feature to Seastone HWSKUs

---

dockers/docker-fpm-frr/base_image_files/monit_bgp
dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2
src/sonic-bgpcfgd/bgpmon.py
src/sonic-bgpcfgd/setup.py

This PR is to auto start the bgpmon (BGP Monitor) Daemon under the BGP docker.
The purpose of bgpmon (BGP Monitor daemon) is to assist gathering BGP related information periodically based on BGP activity detection to store BGP Neighbor information into State DB.  For components such as SNMP agent that uses this new BGP related DB in  state DB to support the MIB operation.
This PR is to auto start the bgpmon daemon under the BGP docker. There is another PR which I originally used to implements the bgpmon processing code (https://github.com/Azure/sonic-swss/pull/1429) that was later decided to be moved into this PR instead of under the sonic-swss repo.  Many valuable comments are still in that PR so reader should refer to that PR for review comments history purpose only.
Note: This new …

Add bgpmon to be started as a new daemon under BGP docker

---

platform/broadcom/sonic-platform-modules-dell/common/dell_pmc.c
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iom_power_off.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iom_power_on.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_i2c_enumeration.sh

For fixing PCA MUX attachment issue in Dell S6100 platform.
Wait till IOM MUX powered up properly and start I2C enumeration.
Check i2cdetect -l | wc -l and verify whether all the 82 I2C devices are attached.
Verified fast boot number is not affected by this change.
Ran power cycle script and the issue is not seen.
UT: 
[S6100_MUX_UT.txt](https://github.com/Azure/sonic-buildimage/files/5243771/S6100_MUX_UT.txt)
[fastboot test results.txt](https://github.com/Azure/sonic-buildimage/files/5244067/fastboot.test.results.txt)

Dell S6100- Fix PCA MUX attachment issue

---

dockers/docker-base-stretch/Dockerfile.j2

Install a newer version of rsyslog from stretch-backports to support -iNONE
Previous backport from master use -iNONE option which is only
available after v8.32.0
back port #5410 
TBD

[201911][docker-base-stretch]: install rsyslog from stretch-backports

---

dockers/docker-base-stretch/Dockerfile.j2

Install a newer version of rsyslog from stretch-backports to support -iNONE
Previous backport from master use -iNONE option which is only
available after v8.32.0
Previous backport from master use -iNONE option which is only
available after v8.32.0
Install a newer version of rsyslog from stretch-backports to support -iNONE
test the build image

[docker-base-stretch]: install rsyslog from stretch-backports

---

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_i2c_enumeration.sh

IOM completion log is not seen in syslog.
Modified the init script IOM condition
Check "cat /var/log/syslog | grep -a IOM | grep S6100_"
Changed the if condition to log the mux state.
**- A picture of a cute animal (not m
[201811_muxlog_UT.txt](https://github.com/Azure/sonic-buildimage/files/5253870/201811_muxlog_UT.txt)
andatory but encouraged)**

Dell S6100 fix mux log issue

---

files/image_config/logrotate/logrotate.d/alternatives

To fix the following error when running
`logrotate /etc/logrotate.conf` :
```
error: dpkg:10 duplicate log entry for /var/log/alternatives.log
error: found error in file dpkg, skipping
```
update-alternatives is provided with dedicated logrotate config in newer dpkg package versions (probably starting from buster)
[logrotate] create separate logrotate.d config for update-alternatives

[logrotate] create separate logrotate.d config for update-alternatives

---

device/dell/x86_64-dell_s6000_s1220-r0/plugins/pcie.yaml
device/dell/x86_64-dell_s6100_c2538-r0/plugins/pcie.yaml

To support "pcieutil pcie-check" command in DellEMC S6000, S6100.
Add 'pcie.yaml' consisting of the PCIe devices, in device/dell/[PLATFORM]/plugins/ directory.
Execute "pcieutil pcie-check" command.
Logs: [S6000_pcie_check_logs.txt](https://github.com/Azure/sonic-buildimage/files/5193662/S6000_pcie_check_logs.txt), [S6100_pcie_check_logs.txt](https://github.com/Azure/sonic-buildimage/files/5193667/S6100_pcie_check_logs.txt)
DellEMC: PCIe config files for S6000, S6100

DellEMC: PCIe config files for S6000, S6100

---

files/docker/docker.service.conf

Why/What I did:-
Enabling ipv6 support on docker container network (Ref: https://docs.docker.com/config/daemon/ipv6/)
Needed for ipv6 communication between container and host in multi-asic
platforms. Address is assign is private subnet address space of fd::/80
with prefix len selected as 80 (Ref: Ref:https://medium.com/@skleeschulte/how-to-enable-ipv6-for-docker-containers-on-ubuntu-18-04-c68394a219a2) so that last 48 bits can be
container mac address and and  prevents NDP neighbor cache
invalidation issues in the Docker layer. 
How I test:
a) O/p of docker inspect bridge
"Containers": { …

Enabling ipv6 support on docker container network.

---

device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/buffers_defaults_t0.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/buffers_defaults_t1.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/buffers_defaults_t0.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/buffers_defaults_t1.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D24C52/buffers_defaults_t0.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D24C52/buffers_defaults_t1.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/buffers_defaults_t0.j2
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/buffers_defaults_t1.j2

Update buffer configuration for SKUs based on SN3800
C64: 32 100G down links and 32 100G up links.
D112C8: 112 50G down links and 8 100G up links.
D24C52: 24 50G down links, 20 100G down links, and 32 100G up links.
D28C50: 28 50G down links, 18 100G down links, and 32 100G up links.
Run QoS test

[Mellanox] Update buffer configuration for single ingress pool on SKUs based on SN3800

---

dockers/docker-sonic-mgmt/Dockerfile.j2

`sudo bash` doesn't work properly behind a proxy because the environment variables are lost, and `apt` is used in the installation script, so we can't run it in user mode.
Move the installation before we switch context to $user so that we have access to the proxy environment variables and can run the install script without sudo.
Verified that `az` commands work inside the container. Ran w/ proxy configured and build succeeds.

[mgmt] Fix Azure CLI install behind proxy

---

platform/broadcom/sonic-platform-modules-dell/common/dell_pmc.c
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iom_power_off.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iom_power_on.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_i2c_enumeration.sh

- Why I did it
For fixing PCA MUX attachment issue in Dell S6100 platform.
- How I did it
Wait till IOM MUX powered up properly and start I2C enumeration.
Check i2cdetect -l | wc -l and verify whether all the 82 I2C devices are attached.
Verified fast boot number is not affected by this change.
Ran power cycle script and the issue is not seen.
UT:
[master_s6100_mux_UT.txt](https://github.com/Azure/sonic-buildimage/files/5254008/master_s6100_mux_UT.txt)

Dell S6100 fix mux issue

---

platform/broadcom/sonic-platform-modules-dell/common/dell_pmc.c
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iom_power_off.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iom_power_on.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_i2c_enumeration.sh

- Why I did it
For fixing PCA MUX attachment issue in Dell S6100 platform.
- How I did it
Wait till IOM MUX powered up properly and start I2C enumeration.
Check i2cdetect -l | wc -l and verify whether all the 82 I2C devices are attached.
Verified fast boot number is not affected by this change.
Ran power cycle script and the issue is not seen.
UT:
[201911_mux_UT.txt](https://github.com/Azure/sonic-buildimage/files/5254042/201911_mux_UT.txt)

[201911] Dell S6100 fix mux issue

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Fixes #5425 
Explicitly installed the `ip` command in the mgmt container. This seems to be a new requirement in the 18.04 docker image.
Log into the built container and run `ip`, `ip addr`, `ip route`, `ip -6 addr`, etc.

[mgmt] Install ip command in mgmt docker

---

platform/vs/docker-sonic-vs/Dockerfile.j2

libzmq5 is tcp/ipc communication library, needed by sairedis/syncd to communicate, as a new way (compared to current REDIS channel) to exchange messages which is faster than REDIS library and allows synchronous mode
this library is required in sairedis repo, swss repo, sonic-buildimage and sonic-build-tools to make it work

Add libzmq5 to docker-sonic-vs

---

files/build_templates/buffers_config.j2

Why I did:
Fix test failure of  test_multinpu_cfggen.py when port2cable length is define in buffer_default_*.j2
because of which internal cable length never gets
define and cause failure in test case test_multinpu_cfggen.py 
How I did:
Added 'internal' key always in port2cable dict if not previously define
How I verify:
Test case was passing after the change.

Fix test failure of  test_multinpu_cfggen.py when port2cable length is define in buffer_default_*.j2

---

files/image_config/caclmgrd/caclmgrd
src/sonic-config-engine/sonic_device_util.py

Need support to allow/deny packets coming to CPU based on source IP.
Added the ANY to allow/deny any protocol packets matching the source IP.
Loaded the CTRLPLANE ACL configs with just source IP and verified the iptable rules in the kernel.
UT:
```
root@sonic:/home/admin# cat acl-cfg
{
"ACL_RULE": {
"IP6_ACL|RULE_1": {
"IP_PROTOCOL": "any",
"PACKET_ACTION": "ACCEPT",
"PRIORITY": "9999",
"SRC_IPV6": "2001::/64"
},
"IP6_ACL|RULE_2": {
"IP_PROTOCOL": "any",
"PACKET_ACTION": "ACCEPT",
"PRIORITY": "9998",
"SRC_IPV6": "fe80::/10"
},
"IP6_ACL|RULE_3": {
"IP_PROTOCOL": "any",
"PACKET_ACTION": "ACCEPT",
"PRIORITY": "9997",
"SRC_IPV6": "2002::/10"
},
"IP_ACL|RULE_1": { …
```

[caclmgrd] Add support to allow/deny any IP/IPv6 protocol packets coming to CPU based on source IP

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Fixes #5444. 
Install the [corresponding ubuntu package](http://manpages.ubuntu.com/manpages/bionic/man8/dhclient.8.html) for dhclient.
Verify dhclient works inside the mgmt docker container.

[mgmt] Install dhclient in sonic-mgmt docker

---

platform/centec-arm64/docker-syncd-centec/critical_processes

This file was added recently, but was created using the old syntax. Update to the new syntax.

[Centec-ARM64] Update docker-syncd-centec critical_processes file to use new syntax

---

src/sonic-py-common/sonic_py_common/multi_asic.py

In multi ASIC platforms, CLIs commands can be under a namespace using the following command, which is now broken.
>> sudo ip netns exec asic0 show ....
NOTE: CLI commands that support "-n" option will still give an error when run with "sudo ip netns exec ... " option. This behavior is intended to encourage users to use "-n" option.
The preferred way of running a CLI command for a namespace is using "-n" option of the CLI command. At this point not all 'show' CLIs have the support of specifying "-n" option. "sudo ip netns exec asicX" is the only way run a command for a namespace.
The command was failing as it was trying to connect to DB in different namespace. Made change so that get namespace API returns the current namespace if it is run under a non …

[CLI][Multi ASIC] Allow commands that don't support "-n" option to be run with "sudo ip netns.." option.

---

dockers/docker-orchagent/supervisord.conf

SWSS config script restore ARP/FDB/Routes. Restore neighbor script
uses config DB ARP information to restore ARP entries and so needs
to be started after swssconfig exits.
Fixes: #5217
Closes: #5217
Fixes start dependencies that causes ARP entries to not be restored during fast-reboot
Change supervisord config on order to ensure restore_neigh runs after swssconfig.sh
fast-reboot succeeds

[swss] Start Restore Neighbor After SWSS Config

---

dockers/docker-database/base_image_files/monit_database
dockers/docker-fpm-frr/base_image_files/monit_bgp
dockers/docker-lldp-sv2/base_image_files/monit_lldp
dockers/docker-orchagent/base_image_files/monit_swss
dockers/docker-sflow/base_image_files/monit_sflow
dockers/docker-snmp-sv2/base_image_files/monit_snmp
dockers/docker-sonic-restapi/base_image_files/monit_restapi
dockers/docker-sonic-telemetry/base_image_files/monit_telemetry
dockers/docker-teamd/base_image_files/monit_teamd
files/build_templates/sonic_debian_extension.j2
files/image_config/monit/process_checker
platform/barefoot/docker-syncd-bfn/base_image_files/monit_syncd
platform/broadcom/docker-syncd-brcm/base_image_files/monit_syncd
platform/cavium/docker-syncd-cavm/base_image_files/monit_syncd
platform/centec/docker-syncd-centec/base_image_files/monit_syncd
platform/marvell-arm64/docker-syncd-mrvl/base_image_files/monit_syncd
platform/marvell-armhf/docker-syncd-mrvl/base_image_files/monit_syncd
platform/marvell/docker-syncd-mrvl/base_image_files/monit_syncd
platform/mellanox/docker-syncd-mlnx/base_image_files/monit_syncd
platform/nephos/docker-syncd-nephos/base_image_files/monit_syncd
rules/docker-teamd.mk

We want to let Monit to unmonitor the processes in containers which are disabled in FEATURE table such that
Monit will not generate false alerting messages into the syslog.
Monit will periodically run a script which accepts three parameters: <container_name>, <process_name> and
<process_cmdline>. This script will first check whether the container is disabled in the FEATURE table or not.
If it is disabled, Monit will skip monitoring the processes. Otherwise, this script will leverage psutil library to inspect
the process tree in host to look for the processes. If the process is not found, then an alerting message will be written
into syslog.
We can change the state field of a container in FEATURE table from enabled to disabled …

[201911][Monit] Unmonitor processes in disabled containers

---

files/image_config/procdockerstatsd/procdockerstatsd

The redis-py 3.0 used in master branch only accepts user data as bytes,
strings or numbers (ints, longs and floats). Attempting to specify a key
or a value as any other type will raise a DataError exception.
The procdockerstatsd script write a datatime object as value to redis, and will get stuck. 
This PR address the issue bt converting datetime to str
Verified on Celestica-DX010-C32, running a master image.
```
Before the update, the **DOCKER_STATS|LastUpdateTime** will never be updated successfully.
After Update:
root@str-dx010-acs-4:~# redis-cli -n 6 hgetall 'DOCKER_STATS|LastUpdateTime'
1) "lastupdate"
2) "2020-09-25 07:27:00.417102"
```
**- …

[procdockerstatsd & redis] Fix exception when attempting to write a datetime object to db

---

src/sonic-py-common/sonic_py_common/device_info.py

Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>
As discussed, This PR covers the below points.
1. Give precedence to platform.json only if both platform.json and  hwsku.json file exist.  In case only platform.json exists, we don’t allow breakout for that HWSKU and fallback to port_config.ini.
check for `hwsku.json` file presence under get_path_to_port_config_file function.
```
admin@lnos-x1-a-csw07:~$ sudo sonic-cfggen -H -k Celestica-DX010-D48C8  --preset=t1
('Celestica-DX010-D48C8', 'x86_64-cel_seastone-r0', '/usr/share/sonic/device/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/port_config.ini', None, None)
{
"BGP_NEIGHBOR": {
"10.0.0.1": {
"asn": "65200",
"holdtime": "180",
"keepalive": "60",
"local_addr": …
```

[portconfig] Fallback to port_config.ini if  hwsku.json is not available

---

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
platform/mellanox/mlnx-platform-api/sonic_platform/platform.py

***This PR has a dependency on https://github.com/Azure/sonic-platform-common/pull/121***
- Platform API implementation using sonic-cfggen to get platform name and SKU name, which will fail when the database is not available.
- Chassis name is not correctly assigned, it shall be assigned with EEPROM TLV "Product Name", instead of SKU name  
- Chassis model is not implemented, it shall be assigned with EEPROM TLV "Part Number"
1. Chassis
> - Get platform name from /host/machine.conf
> - Remove get SKU name with sonic-cfggen
> - Get Chassis name and model from EEPROM TLV "Product Name" and "Part Number" 
> - Add function to return model
2. EEPROM
> - Add function to return product name and part number
3. Platform
> - Init EEPROM on the host side, so …

[Mellanox] Refactor platform API to remove dependency on database

---

files/build_templates/docker_image_ctl.j2
files/image_config/caclmgrd/caclmgrd

The SNMP loopback health check and other SNMP requests coming through the front panel interfaces where not getting serviced by the SNMP agent running in the SNMP container in the linux host network namespace. This change is to create translation rules so that the SNMP packets coming in would be translated and forwarded to the agent running in linux host.
Create NAT rules for trapping the SNMP packets coming in the front panel interface in the linux network namespace and sent to the docker0 subnet 240.12.1.x. The NAT rules added will be for  SNMP packets, which are UDP + dest port 161
* change the destination IP to that of the docker0 eth0 IP address in the host which is 240.127.1.1. This is DNAT rule 
* change the Source IP to that of the docker0 eth0 …

[Multi-Asic] Forward SNMP requests received on front panel interface to SNMP agent in host.

---

src/sonic-py-common/sonic_py_common/daemon_base.py

There is a syntax error (self is missing for log_info and log_warning) in signal_handler in daemon_base.py, which causes an exception
```
INFO lldp#supervisord: lldpmgrd Traceback (most recent call last):
INFO lldp#supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 224, in <module>
INFO lldp#supervisord: lldpmgrd     main()
INFO lldp#supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 220, in main
INFO lldp#supervisord: lldpmgrd     lldpmgr.run()
INFO lldp#supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 181, in run
INFO lldp#supervisord: lldpmgrd     (state, c) = sel.select(SELECT_TIMEOUT_MS)
INFO lldp#supervisord: lldpmgrd   File "/usr/lib/python2.7/dist-packages/swsscommon/swsscommon.py", line 965, in select
INFO lldp#supervisord: lldpmgrd     return …
```

[sonic_py_common] Fix exception in daemon_base.py

---

slave.mk

Why I did:
After picking PR#https://github.com/Azure/sonic-buildimage/pull/5309 into 201911 there is compilation error when building
sonic_bgpcfgd-1.0-py2-none-any.whl because of dependency with swsscommon and python-swsscommon deb package.
What I did:
Added Support to add Debian package dependency for Python Debs and Python Wheel target.
This change are based of master corresponding changes.
How I verify:
Package build fine locally.

[201911] Added Support to add Debian package depedency for Python Debs and Python Wheel target

---

dockers/docker-fpm-frr/base_image_files/vtysh

Add the option -n to specify the bgp container running in a namespace.
Update the vtysh script with new option `-n <namespace_id>`
This option is no applicable for single asic.
```
admin@str-acs-2:~/arlakshm$ vtysh
Usage: /usr/bin/vtysh -n [0 to 5] [OPTION]... 
admin@str-acs-2:~/arlakshm$ vtysh -n 0 -c "show ip bgp summary"
IPv4 Unicast Summary:
BGP router identifier 8.0.0.0, local AS number 65100 vrf-id 0
BGP table version 12826
RIB entries 12833, using 2306 KiB of memory
Peers 4, using 82 KiB of memory
Peer groups 4, using 256 bytes of memory
Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
10.0.0.1        4 …
```

Vtysh support for multi asic

---

dockers/docker-fpm-frr/base_image_files/monit_bgp
dockers/docker-snmp/base_image_files/monit_snmp

This PR provides a fix for system health monitoring:
```
root@sonic:/home/admin# monit summary -B
Monit 5.20.0 uptime: 30m
Service Name                     Status                      Type
sonic-switch                     Running                     System
rsyslog                          Running                     Process
root-overlay                     Accessible                  Filesystem
var-log                          Accessible                  Filesystem
routeCheck                       Status ok                   Program
telemetry|telemetry              Status ok                   Program
telemetry|dialout_client         Status ok                   Program
teamd|teamsyncd                  Status ok                   Program …
```

[monit]: Fix process checker

---

src/sonic-bgpcfgd/bgpcfgd

BGP_MONITORS sessions don't have corresponding DEVICE_NEIGHBOR_METADATA CONFIG_DB entries in the minigraphs. Prevent bgpcfgd to wait on such entries for BGP_MONITORS sessions.
Set constructor argument to False that means - don't wait for device neighbors metadata info for BGP_MONITORS
Build an image, write on your device, use a minigraph with BGP_MONITORS sessions. Check that sessions are populated in the config. 

[bgpcfgd]: Don't use neighbor metadata in bgpmon sessions

---

src/sonic-config-engine/config_samples.py
src/sonic-config-engine/tests/sample_output/l2switch.json
src/sonic-config-engine/tests/test_j2files.py

sonic-cfggen may not read from Redis, so override hostname will impact existing ConfigDB. Fix test_l2switch_template test case to test preset l2 feature.
This is same as https://github.com/Azure/sonic-buildimage/pull/5510 but targeting 201911 branch.

Fix generate_l2_config: don't override hostname or device role (ToRRouter)

---

platform/vs/docker-sonic-vs/Dockerfile.j2

Fixed https://github.com/Azure/sonic-buildimage/issues/5404
Below commits are cherry-picked from master branch, and mistakenly applied to `platform/vs/docker-sonic-vs/Dockerfile.j2`.
```
65bd3857 2020-09-08 | [redis] Use redis-server and redis-tools in blob storage to prevent upstream link broken (#5340) [Qi Luo]
0a864966 2020-07-28 | [redis] Upgrade redis version (#5060) [Qi Luo]
```
On master, docker-sonic-vs is from debian:buster
on 202006, docker-sonic-vs is from debian:stretch
So we revert back the redis-tools version to the original one.
Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>
**- A picture of a …

Revert redis-tools version in docker-sonic-vs which is from debian:stretch

---

platform/broadcom/sonic-platform-modules-juniper/README.md
platform/broadcom/sonic-platform-modules-juniper/qfx5200/utils/README

This patch set updates the documentation for
QFX5200 & QFX5210 Juniper switching platforms.
Signed-off-by: Ciju Rajan K <crajank@juniper.net>

[Juniper] Updating platform documentation

---

src/sonic-py-common/sonic_py_common/multi_asic.py

Why I did:
After Recent PR https://github.com/Azure/sonic-buildimage/pull/5446  sonic-util command failure on Multi-asic platforms. 
How I verify:
After fix command were working fine.

Fix sonic-util command failure on Multi-asic platforms.

---

platform/broadcom/docker-syncd-brcm/start_led.sh

Some platforms don't leverage the brcm led coprocessor.
However ledinit will try to load a non existing file and exit with an
error code.
This change is a cosmetic fix mostly.
Check if the `led_proc_init.soc` exists or exit gracefully.
Boot a platform without the configuration and verify in the syslog that the exit status of ledinit is 0
Boot a platform with the configuration and verify in the syslog that the exit status of ledinit is 0 and the leds are working.
Verified by adding a dumb `led_proc_init.soc` on an Arista platform which usually doesn't use it.
This is a cosmetic fix, but it's better to avoid an `unexpected exit status` in the syslog.
**- …

[brcm] Skip ledinit if there is no led_proc_init.soc file

---

rules/docker-telemetry.mk

Issue:  https://github.com/Azure/sonic-buildimage/issues/5525
Removed unused /var/platfrom from telemetry docker make file causing failure

[Telemetry] remove unused mount from telemetry docker make file 

---

platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py

The manufacture date returned from platform API was truncated, time is not included.
05/11/2017 17:20:17  ------>   05/11/2017
Revise the regular expression used for matching.
Call the platform API and check whether the manufacture date is correctly returned.

[Mellanox] Fix truncated manufacture date returned from platform API

---

files/image_config/platform/rc.local

To address issue #5525 
Explicitly control the grub installation requirement when it is needed. We have scenario where configuration migration happened but grub installation is not required.
Build image and test on S6100.

[rc.local] separate configuration migration and grub installation logic

---

platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py

ACS-MSN3420 has 2 physical CPU and 2 CPU temperature sensors, but it initialize 4 thermals in platform API implementation.
Change CPU core number from 4 to 2
Manual test

[Mellanox] Fix issue: there should be 2 cpu core temperature sensors in ACS-MSN3420 (201911)

---

platform/barefoot/sonic-platform-modules-bfn-montara/debian/rules
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/platform_thrift_client.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py
platform/barefoot/sonic-platform-modules-bfn/debian/rules

[barefoot] Platform API 2.0 fixups

---

dockers/docker-fpm-frr/docker_init.sh

Why I did:
After PR https://github.com/Azure/sonic-buildimage/pull/5418
Extending the changes done for v4 in https://github.com/Azure/sonic-buildimage/pull/4774 to v6 now.
How I verify
Before:
sudo ip  -6 -n asic0 route show ::/0
default via fd00::1 dev eth0 metric 1024  pref medium
After:
sudo ip  -6 -n asic0 route show ::/0
default via fc00::2 dev PortChannel0002 proto 186 src fc00:1::32 metric 20  pref medium
default via fc00::6 dev PortChannel0005 proto 186 src fc00:1::32 metric 20  pref medium
default via fd00::1 dev eth0 metric 3523215360  pref medium

[Multi-asic] Fixed IPv6 Default Route to be BGP Learned

---

platform/broadcom/saibcm-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c

Why/How I did:
The error message is updated to provide correct information
of Netdevice link being down for Tx Drop
Taken the change from BRCM SAI 4.2.1.3 (6.5.19 hsdk) (https://github.com/Azure/sonic-buildimage/pull/5532/files#diff-9787d8debde44bb0dd3ce502443bf25cR5362)

[201911] Fix the error message for Tx Drop happening when netdev link is down

---

files/build_templates/sonic_debian_extension.j2

Signed-off-by: Jon Goldberg <jon.goldberg@nokia.com>
The problem was proxy was missing on "pip install".  This is to fix the build behind the proxy.

fix build behind proxy

---

device/arista/x86_64-arista_7060px4_32/Arista-7060PX4-C64/th3-a7060px4-32-64x100G.config.bcm
device/arista/x86_64-arista_7060px4_32/Arista-7060PX4-O32/th3-a7060px4-o32-32x400G.config.bcm
src/sonic-device-data/tests/permitted_list

This is to fix pcie firmware check assert in Broadcom SDK once the SAI changes merges. This will be in the future but adding the soc property in the broadcom config now.
Verified the image is fine with the additional soc property on the platform.

[Arista] Add disable_pcie_firmware_check soc property

---

platform/broadcom/sonic-platform-modules-dell/common/dell_ich.c

- xcvrd daemon crashes in Dell S6100 with the following errors.
Oct  6 00:52:43.603633 CYS04-0101-0321-12T1 ERR pmon#xcvrd: System failed to recover in 120 secs. Exiting...
Oct  6 00:52:43.603633 CYS04-0101-0321-12T1 INFO pmon#xcvrd: State transition from 0 to 2
Oct  6 00:52:44.912121 CYS04-0101-0321-12T1 ERR pmon#xcvrd: Error: dom info update thread received stop event, 
exiting...
Oct  6 00:52:44.925275 CYS04-0101-0321-12T1 ERR pmon#xcvrd: Xcvrd main task stopped, exiting...
- During platform deinitialization, dell_ich is not removed properly and when we do initialize s6100 platform, ICH driver sysfs attributes are not attached. Because of this, get_transceiver_change_event returns error and this leads xcvrd to crash. 
- Do …

[Dell S6100] Properly release memory upon ICH driver deinit

---

files/image_config/caclmgrd/caclmgrd

Why I did:
Optimized caclmgrd ACL Rule Table Notification handling. 
Previously any event happening on ACL Rule Table (eg DATAACL rules
programmed) caused control plane default action to be triggered
and invoking iptables commands
Now Control Place ACTION will be trigger only
for ACL Rule belonging to Control ACL Table
Check for Table Type for ACL Rule notification
Run crm/test_crm.py which populate DATAACL Rules for ACL Counters and made sure DATACL ACL
rules prgrammed do not trigger Control plane Action

Optimized caclmgrd ACL Rule Table Notification handling. 

---

device/barefoot/x86_64-accton_as9516bf_32d-r0/syncd.conf

To make the newport platform choose the Y1 profile on startup.

[barefoot] Switch to Y profiles for Newport board

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-metadata.xml
src/sonic-config-engine/tests/test_cfggen.py

Add resource_type from minigraph to DEVICE_METADATA section
Add parsing for field in minigraph metadata section
Unit testing in sonic-config-engine
Add minigraph resource_type to DEVICE_METADATA section

Minigraph resource type changes

---

rules/functions
update_screen.sh

print cache status when use cached file in the build process
Without DPKG cache support :
[ building ] [ target/docker-base.gz ]
[ finished ] [ target/docker-base.gz ]
With DPKG cache support :
[ building ] [ target/docker-base.gz ]
[ cached   ] [ target/docker-base.gz ]
extracted from PR 4595 by Kalimuthu Velappan
print cache status when use cached file in the build process
Without DPKG cache support :
[ building ] [ target/docker-base.gz ]
[ finished ] [ target/docker-base.gz ]
With DPKG cache support :
[ building ] [ target/docker-base.gz ]
[ cached   ] [ target/docker-base.gz ]
modify update_screen.sh
**- …

[build]: Added support for cache status on the build output

---

Makefile.work

I am using a long standing checked out repo to build dev images. From time to time the repo is too out-sync'ed with remotes and some submodule stay behind even after make reset and make init call. This causes build to fail unexpectedly.
With further tests, I moved the recursive "git remote update' to make reset code block and placed in front of recursive --init. The original change has the ordering wrong but that was hidden by the fact that make init was executed multiple times in master branch and 201911 branch.
The summary is:
- for a newly cloned repo. existing 'make init' is enough.
- for long standing repo, when things are getting too out dated, or when we switching branch, we usually need to do a make reset before build again. Place the fix in …

[make init] update submodule's remotes

---

src/sonic-py-common/sonic_py_common/device_info.py

Summary:
For this PR the motivation is to add logic so that platform.json is considered for port configuration candidates only if platform.json has an interfaces key 
and the length of the key is greater than zero. This happened with new platform.json file utilized to test platform_api's infrastructure which in turn had interfaces key without any port configs. 
To make sure platform.json is not used for sonic-cfggen if it does not have "interfaces" key populated
added logic to check if platform.json is present, check if "interfaces" key size is greater than zero
Run it on a mellanox-acs2700 platform and verify cfggen does not cause errors
platform.json should be present without "interfaces" key populated
Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>

[sonic-py-common] Add platform.json to port_config files candidates only if interfaces are present within platform.json

---

dockers/docker-snmp-sv2/base_image_files/monit_snmp

Why I did:
Fix https://github.com/Azure/sonic-buildimage/issues/5529 of monit complaining about SNMP.
In 201911 branch we start the process "python3.6 -m sonic_ax_impl"
Updated the semantics in monit file also.

[201911] Monit snmp fix

---

dockers/docker-fpm-frr/frr/zebra/zebra.interfaces.conf.j2
src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/interfaces.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/zebra.conf
src/sonic-config-engine/tests/sample_output/py2/frr.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-vni-zebra.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-zebra.conf
src/sonic-config-engine/tests/sample_output/py2/zebra_frr.conf
src/sonic-config-engine/tests/sample_output/py3/frr.conf
src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-vni-zebra.conf
src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-zebra.conf
src/sonic-config-engine/tests/sample_output/py3/zebra_frr.conf
src/sonic-config-engine/tests/sample_output/t2-chassis-fe-pc-zebra.conf

FRR introduced [next hop tracking](http://docs.frrouting.org/projects/dev-guide/en/latest/next-hop-tracking.html) functionality. 
That functionality requires resolving BGP neighbors before setting BGP connection (or explicit ebgp-multihop command). Sometimes (BGP MONITORS) our neighbors are not directly connected and sessions are IBGP. In this case current configuration prevents FRR to establish BGP connections.  Reason would be "waiting for NHT". To fix that we need either add static routes for each not-directly connected ibgp neighbor, or enable command `ip nht resolve-via-default`
Put `ip nht resolve-via-default` into the config
Build an image. Enable BGP_MONITOR entry and check that entry is Established or Connecting in FRR …

[bgp]: Enable next-hop-tracking through default

---

files/image_config/caclmgrd/caclmgrd

What I did:
Optimize ACL Table/Rule notification handling
to loop pop() until empty to consume all the data in a batch
This way we prevent multiple call to iptable updates
Loaded (sudo acl-loader update full acl.json) with 100 rules and verified all the set notification are batch together in one update to iptables .
Similarly (sudo acl-loader delete) batch all del operation in one update.

Optimze ACL Table/Rule notification handling

---

src/sonic-py-common/sonic_py_common/device_info.py

It was observed that the docker stats o/p of pmon docker showed up increased memory usage. Here we see it is 159 MB.
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e1f547f0bea4        pmon                1.11%               159.5MiB / 7.785GiB   2.00%               0B / 0B             12.7MB / 119kB      12
```
It was found that each process running in the pmon docker was having an anonymous memory allocation of 35MB in the heap. On debugging it happens when we import of yaml module in sonic_py_common/device_info.py.
```
admin@str-s6000-acs-8:~$ sudo pmap 3183
3183:   /usr/bin/python /usr/bin/psud
00005602e6544000   3228K r-x-- python2.7
00005602e6a6a000      8K r---- …
```

[201911] increased memory usage in the pmon processes

---

files/image_config/sysctl/sysctl-net.conf

netlink out of memory seen for 8K neighbor updates.
1) Config IP to 2 interfaces connected to ixia. Ethernet1 (21.0.0.1/16) and Ethernet4 (24.1.1.1/24)
2) DUT copp rules are as ARP CIR=2000 and IP2ME CIR=6000
3) Start Continuous Traffic (5G) is started from ixia connected to Ethernet4 with the DIP matching with the 8K ARP Host Range before learning ARP entries. These traffic will be software forwarded from linux kernel.
4) DUT is configured to learn ARP through ARP Reply packets
echo 1 > /proc/sys/net/ipv4/conf/Ethernet1/arp_accept
5) Start continuous ARP Reply Packet is sent from IXIA connected to Ethernet1 Port at 2K Packet/Secs with Host IP starting from 20.20.0.2 and Incrementing for 8K.
After step (5), expectation is all 5G traffic must be …

 Set sock rx Buf size to 3MB.

---

src/sonic-config-engine/redis_bcc.py

This PR makes two changes:
- Store Jinja2 cache in LOGLEVEL DB instead of STATE DB
- Store bytecode cache encoded in base64
Tested with the following command: "redis-dump -d 3 -k JINJA2_CACHE"

[sonic-cfggen] store jinja2 cache in log level db.

---

build_debian.sh
platform/vs/docker-sonic-vs/Dockerfile.j2

It should no longer be necessary to explicitly install the 'wheel' package, as SONiC packages built as wheels should specify 'wheel' as a dependency in their setup.py files. Therefore, pip[3] should check for the presence of 'wheel' and install it if it isn't present before attempting to call 'setup.py bdist_wheel' to install the package.

[Host OS][docker-vs] No longer install 'wheel' package explicitly

---

platform/mellanox/mlnx-sai/Makefile

Example of syslog message from Mellanox SAI:
"Oct  7 15:39:11.482315 arc-switch1025 INFO syncd#supervisord: syncd Oct 07 15:39:11 NOTICE  SAI_BUFFER: mlnx_sai_buffer.c[3893]- mlnx_clear_buffer_pool_stats: Clear pool stats pool id:1"
There is a log INFO from supervisord which actually printed NOTICE and
date again. This confusion happens becuase if SAI is not built to log
to syslog it will log everything to stdout with format "[date] [level]
[message]" so supervisord sends it to syslog with level INFO.
New logs look like:
"Oct  7 15:40:21.488055 arc-switch1025 NOTICE syncd#SDK  [SAI_BUFFER]: mlnx_sai_buffer.c[3893]- mlnx_clear_buffer_pool_stats: Clear pool stats pool id:17"
Misleading log messages from SAI with INFO …

[Mellanox] Configure SAI to log to syslog instead of stdout.

---

device/accton/x86_64-accton_as7116_54x-r0/sonic_platform/chassis.py
device/celestica/x86_64-cel_e1031-r0/sonic_platform/chassis.py
device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
device/celestica/x86_64-cel_silverstone-r0/sonic_platform/chassis.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-cel/services/platform_api/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-inventec/d7054q28b/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-juniper/sonic_platform/chassis.py
platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py

The `get_serial_number()` method in the ChassisBase and ModuleBase classes was redundant, as the `get_serial()` method is inherited from the DeviceBase class. This method was removed from the base classes in sonic-platform-common and the submodule was updated in https://github.com/Azure/sonic-buildimage/pull/5625.
This PR aligns the existing vendor platform API implementations to remove the `get_serial_number()` methods and ensure the `get_serial()` methods are implemented, if they weren't previously.
Note that this PR does not modify the Dell platform API implementations, as this will be handled as part of https://github.com/Azure/sonic-buildimage/pull/5609
Remove `get_serial_number()` methods from existing platform API implementations (except Dell …

[platform] Remove references to deprecated get_serial_number() method in Chassis class

---

files/image_config/procdockerstatsd/procdockerstatsd

Python 2 is deprecated and no longer supported. This is part of moving all Python code in SONiC to Python 3.
Make procdockerstatsd Python 3-compliant and set interpreter to python3 in shebang. Also some other cleanup to improve code reuse.
Run procdockerstatsd, ensure it functions correctly.

[procdockerstatsd] Convert to Python 3

---

device/mellanox/x86_64-mlnx_msn2010-r0/sensors.conf

Add sensors labels for human readable output for MSN2010
Configured the correct labels on 'sensors.conf' file
run 'sensors' command

[Mellanox] Add sensors labels for human readable output for MSN2010

---

device/mellanox/x86_64-mlnx_msn2410-r0/sensors.conf

Add sensors labels for human readable output for MSN2410
Configured the correct labels on 'sensors.conf' file
run 'sensors' command

[Mellanox] Add sensors labels for human readable output for MSN2410

---

files/image_config/caclmgrd/caclmgrd

When a large number of changes occur to the ACL table of Config DB, caclmgrd will get flooded with notifications, and previously, it would regenerate and apply the iptables rules for each change, which is unnecessary, as the iptables rules should only get applied once after the last change notification is received. If the ACL table contains a large number of control plane ACL rules, this could cause a large delay in caclmgrd getting the rules applied.
This patch causes caclmgrd to delay updating the iptables rules until it has not received a change notification for at least 0.5 seconds.
Resolves https://github.com/Azure/sonic-buildimage/issues/5275
When an ACL table change notification is received for a particular namespace, we spawn an update thread …

[caclmgrd] Prevent unnecessary iptables updates

---

device/mellanox/x86_64-mlnx_msn2700-r0/sensors.conf

Add sensors labels for human readable output for MSN2700
Configured the correct labels on 'sensors.conf' file
run 'sensors' command

[Mellanox] Add sensors labels for human readable output for MSN2700

---

device/mellanox/x86_64-mlnx_msn2740-r0/sensors.conf

Add sensors labels for human readable output for MSN2740
Configured the correct labels on 'sensors.conf' file
run 'sensors' command

[Mellanox] Add sensors labels for human readable output for MSN2740

---

files/image_config/constants/constants.yml
src/sonic-bgpcfgd/bgpcfgd/managers_allow_list.py
src/sonic-bgpcfgd/tests/test_allow_list.py

I was asked to change "Allow list" prefix-list generation rule.
Previously we generated the rules using following method:
``` 
For each {prefix}/{masklen} we would generate the prefix-rule
permit {prefix}/{masklen} ge {masklen}+1
Example:
Prefix 1.2.3.4/24 would have following prefix-list entry generated
permit 1.2.3.4/24 ge 23
```
But we discovered the old rule doesn't work for all cases we have.
So we introduced the new rule:
```
For ipv4 entry,  
For mask  < 32 , we will add ‘le 32’ to cover all  prefix masks to be sent by T0  
For mask =32 , we will not add any ‘le mask’ 
For ipv6 entry, we will add le 128 to cover all the prefix mask to be sent by T0  
For mask < 128 , we will add ‘le 128’ to cover all prefix masks to be sent by T0 
For mask = 128 , we will not add …
```

[bgpcfgd]: Change prefix-list generation for "Allow prefix" feature

---

dockers/docker-base-buster/etc/rsyslog.conf
dockers/docker-base-stretch/etc/rsyslog.conf
dockers/docker-base/etc/rsyslog.conf
files/image_config/rsyslog/rsyslog-container.conf.j2

Temporary fix for #5570 
There is currently a bug where messages from swss with priority lower than the current log level are still being counted against the syslog rate limiting threshhold. This leads to rate-limiting in syslog when the rate-limiting conditions have not been met, which causes several sonic-mgmt tests to fail since they are dependent on LogAnalyzer. It also omits potentially useful information from the syslog. Only rate-limiting messages of level INFO and lower allows these tests to pass successfully.
Add `$SystemLogRateLimitSeverity` option to `rsyslog.conf` in the base Dockerfiles
Build a new orchagent image and install it. Run the ACL tests, which should now …

[docker-base]: Rate limit priority INFO and lower in syslog

---

platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py

Now we are reading base mac, product name from eeprom data, and the data read from eeprom contains multiple "\0" characters at the end, need trim them to make the string clean and display correct.
Strip all "\0" for the data read from eeprom
Manual test

[Mellanox] Fix issue: read data from eeprom should trim tail \0

---

dockers/docker-database/docker-database-init.sh
files/build_templates/docker_image_ctl.j2

use correct chassisdb.conf path while bringing up chassis_db service on VoQ modular switch.chassis_db service on VoQ modular switch.
resolves #5631 
Signed-off-by: Honggang Xu <hxu@arista.com>

Use correct path for chassisdb.conf file.

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/multi_npu_data/sample_port_config-0.ini
src/sonic-config-engine/tests/multi_npu_data/sample_port_config-1.ini
src/sonic-config-engine/tests/multi_npu_data/sample_port_config-2.ini
src/sonic-config-engine/tests/multi_npu_data/sample_port_config-3.ini
src/sonic-config-engine/tests/test_multinpu_cfggen.py

Why I did:
Everflow and Dataacl should not get binded to Backplane port-channels.
However with updated port alias mapping it was getting binded.
Reason is because we were relying on port_alias_asic_map dictionary
but that dictionary can't be used as alias name format has changed.
How I verify:
After updating alias name in *.ini  uni-test were failing.
With updating logic in minigraph.py test are passing.
Also verified on Multi-asic platforms.

Everflow and Dataacl should not get binded to Backplane port-channels.

---

platform/barefoot/sonic-platform-modules-bfn-montara/debian/rules

Signed-off-by: Petro Bratash petrox.bratash@intel.com
Platforms .deb-package  is not installed into the right directory, because variable `PLATFORM ` was defined previously and variable in the makefile is ignored.
https://www.gnu.org/software/make/manual/html_node/Overriding.html
Rename variable. 
`PLATFORM  ---->  PLATFORM_NAME
`
Сheck if the file exists (on Montara device):
`/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/pcie.yaml
`

[BFN] Rename variable in Montara platform debian/rules

---

device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/td3-s5232f-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/td3-s5232f-8x100G+48x50G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/td3-s5232f-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/td3-s5232f-96x10G+8x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/td3-s5232f-96x25G+8x100G.config.bcm

Modified the correct settings for DellEMC S5232 buffer settings.
Increased Egress pool size from 28MB to 32 MB.
Edid buffer_defaults_t0.j2 and buffer_defaults_t1.j2 files 
Verify ingress and egress register values in NPU shell. 

DellEMC S5232 Buffer profile changes

---

files/image_config/hostcfgd/hostcfgd

If we ran the CLI commands `sudo config feature autorestart snmp disabled/enabled` or `sudo config feature autorestart swss disabled/enabled`, then SNMP container will be stopped and started. This behavior was not expected since we updated the
`auto_restart` field not update `state` field in `FEATURE` table. The reason behind this issue is that either `state` field or `auto_restart` field was updated, the function `update_feature_state(...)` will be invoked which then starts snmp.timer service.
The snmp.timer service will first stop snmp.service and later start snmp.service. 
In order to solve this issue, the function `update_feature_state(...)` will be only invoked if `state` field in `FEATURE` table was
updated.
**- How …

[hostcfgd] Enable/disable the container service only when the feature state was changed.

---

files/image_config/misc/docker-wait-any
files/scripts/swss.sh
src/sonic-py-common/sonic_py_common/device_info.py

On teamd docker restart, the swss and syncd needs to be restarted as there are dependent resources present.
Add the teamd as a dependent service for swss
Updated the docker-wait script to handle service and dependent services separately.
Handle the case of warm-restart for the dependent service   
Verified the following scenario's with the following testbed 
VM1 ----------------------------[DUT 6100] -----------------------VM2,  ping traffic continuous between VMs
1. Stop teamd docker alone  
>  swss, syncd dockers seen going away
>  The LAG reference count error messages seen for a while till swss docker stops.
>  Dockers back up.
2. Enable WR mode for teamd. Stop teamd docker alone  
>  swss, syncd dockers not removed.
>  The …

Add teamd as a depedent service to swss

---

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py

SFP object will be initialized to a certain type even if no SFP present. A case could be:
1. A SFP object is initialized to QSFP type by default when there is no SFP present
2. User insert a SFP with an adapter to this QSFP port
3. The SFP object fail to read EEPROM because it still treats itself as QSFP.
This PR fixes this issue.
When detecting a new SFP insertion, read its SFP type and DOM capability from EEPROM again.
Manual test

[Mellanox] Re-initialize SFP object when detecting a new SFP insertion

---

src/sonic-py-common/sonic_py_common/daemon_base.py
src/sonic-py-common/sonic_py_common/logger.py

Current implementation of logger class is based on standard python syslog library.  
Thus, logger class can be instantiated in different places and share the same context across the entire process.  
This means that reducing log severity level will affect other modules which use logging facility.
* To fix syslog implicit min priority override
* Added per instance log severity check
1. Run code snippet
```
from sonic_py_common import logger
log1 = logger.Logger(log_identifier='myApp1')
log1.set_min_log_priority_debug()
log1.log_error("=> this is error")
log1.log_warning("=> this is warning")
log1.log_notice("=> this is notice")
log1.log_info("=> this is info")
log1.log_debug("=> …
```

[sonic-py-common]: Fix syslog implicit min priority override

---

src/sonic-py-common/sonic_py_common/daemon_base.py
src/sonic-py-common/sonic_py_common/logger.py

Current implementation of logger class is based on standard python syslog library.  
Thus, logger class can be instantiated in different places and share the same context across the entire process.  
This means that reducing log severity level will affect other modules which use logging facility.
* To fix syslog implicit min priority override
* Added per instance log severity check
1. Run code snippet
```
from sonic_py_common import logger
log1 = logger.Logger(log_identifier='myApp1')
log1.set_min_log_priority_debug()
log1.log_error("=> this is error")
log1.log_warning("=> this is warning")
log1.log_notice("=> this is notice")
log1.log_info("=> this is info")
log1.log_debug("=> …
```

[201911][sonic-py-common]: Fix syslog implicit min priority override

---

dockers/docker-base-buster/Dockerfile.j2
dockers/docker-base-stretch/Dockerfile.j2

syncd support use zmq as rpc channel
syncd support use zmq as rpc channel
install libzmq5 in syncd docker
install libzmq5 in vs syncd docker

[syncd]: install libzmq5 in syncd docker

---

platform/mellanox/mlnx-platform-api/sonic_platform/fan.py
platform/mellanox/mlnx-platform-api/sonic_platform/utils.py

As new hw-mgmt expose the sysfs for PSU fan max speed, we need support max/min speed for PSU fan in mellanox platform API.
Read the max fan speed from sysfs.
Manual test and run existing regression.

[Mellanox] Support max/min speed for PSU fan

---

files/image_config/monit/process_checker

The ```psutil``` library used in ```process_checker``` create a cache for each process when calling ```process_iter```. So, there is a small possibility that one process exists when calling process_iter, but not exists when calling cmdline, which will raise a ```NoSuchProcess``` exception. 
```
File "/usr/bin/process_checker", line 57, in <module>
main()
File "/usr/bin/process_checker", line 53, in main
check_process_existence(args.container_name, ' '.join(args.process_cmdline))
File "/usr/bin/process_checker", line 31, in check_process_existence
if ((' '.join(process.cmdline())).startswith(process_cmdline) and process.status() in ["running", "sleeping"]):
File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 694, in cmdline
return self._proc.cmdline() …
```

[process_checker] Fix 'NoSuchProcess' exception in process_checker

---

files/image_config/misc/docker-wait-any

Getting the following error in 201911 branch 
Oct 27 00:30:20.120613 str-msn2700-02 INFO swss.sh[3928]: Traceback (most recent call last):
Oct 27 00:30:20.121455 str-msn2700-02 INFO swss.sh[3928]:   File "/usr/bin/docker-wait-any", line 35, in <module>
Oct 27 00:30:20.122256 str-msn2700-02 INFO swss.sh[3928]:     from docker import APIClient
Oct 27 00:30:20.123295 str-msn2700-02 INFO swss.sh[3928]: ImportError: cannot import name APIClient
There is a difference between the docker Python package in master and 201911 (via an earlier PR  (https://github.com/Azure/sonic-buildimage/commit/aec51c8aafbbb3d745a6a669ddc532245455148e)
Removed the import of APIClient.
**- Which release branch to backport (provide reason below if …

[201911] Fix to remove the import of APIClient

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml
src/sonic-config-engine/tests/test_minigraph_case.py

Allow setting VLAN MAC address from minigraph information
While parsing DpgDec, search for `<MacAddress>` tags in VLAN interfaces.
Run the update sonic-config-engine tests.

[minigraph.py]: Parse VLAN MAC address from minigraph when present

---

device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-C64/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-C64/th2-z9264f-64x100G.config.bcm
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-C8D112/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-C8D112/th2-z9264f-8x100G-112x50G.config.bcm
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-Q64/buffers_defaults_t0.j2
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-Q64/buffers_defaults_t1.j2
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-Q64/th2-z9264f-64x40G-t0.config.bcm
device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-Q64/th2-z9264f-64x40G-t1.config.bcm

Converted two SP model to single pool model and modified the buffer size.
Changed buffer_default settings for all the DellEMC Z9264f HWSKU's.
Check SP register values in NPU shell.
Need to be cherry picked for 201911 branch.

DellEMC Z9264f buffer changes

---

platform/broadcom/sai.mk

**- What I didt**
Upgrade Broadcom SAI to version 3.5.3.5-3
- Include change to CS00011229318 (reference count issue when removing next hop).

[bcm SAI] Upgrade Broadcom SAI to version 3.5.3.5-3

---

device/arista/x86_64-arista_7800r3_48cq2_lc/platform_reboot
device/arista/x86_64-arista_7800r3_48cqm2_lc/platform_reboot

We don't need a custom platform reboot on Clearwater2(Ms). They are expected to be rebooted via a normal linux soft reboot.
Remove symlink to the arista common platform reboot for those 2 platforms.
Tested that reboot command on Clearwater2 works as expected and goes through normal linux reboot sequence.

[arista/7800r3_48cq(m)2_lc] remove platform_reboot

---

platform/broadcom/sonic-platform-modules-dell/common/dell_pmc.c
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/__init__.py
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan_drawer.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/__init__.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/fan_drawer.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/__init__.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/fan_drawer.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/__init__.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/fan_drawer.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/thermal.py

- Implement FanDrawer and get_high_critical_threshold Platform API for S6000, S6100, Z9100 and Z9264F.
- Fix incorrect fan direction values in S6100, Z9100
-  Added a new file fan_drawer.py for FanDrawer implementation.
-  Modified chassis.py to use FanDrawer for updating _fan_drawer_list and _fan_list.
-  Added ‘get_high_critical_threshold’ method in thermal.py for supported sensors in S6100, Z9100, Z9264.
Wrote a python script to load chassis class and call the appropriate methods.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/5407692/UT_logs.txt)
[DellEMC]: FanDrawer and …

[DellEMC]: FanDrawer and get_high_critical_threshold Platform API implementation for S6000, S6100, Z9100 and Z9264F

---

dockers/docker-config-engine-buster/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2
sonic-slave-stretch/Dockerfile.j2

Upgrading pip3 after pip2 caused the `pip` command to be aliased to the `pip3` command. However, since we are still transitioning from Python 2 to Python 3, most `pip` commands in the codebase are expecting `pip` to alias to `pip2`. The proper solution here is to explicitly call `pip2` and `pip3`, and no longer call `pip`, however this will require extensive changes and testing, so to quickly fix this issue, we upgraded pip2 after pip3 to ensure that pip2 is installed after pip3.
Fix issues introduced via https://github.com/Azure/sonic-buildimage/pull/5656
Upgrade pip2 after pip3 in slave containers and config engine container.
Ensure image builds are all containers start properly …

Upgrade pip2 after upgrading pip3

---

dockers/docker-base-buster/Dockerfile.j2
dockers/docker-lldp/Dockerfile.j2
dockers/docker-orchagent/Dockerfile.j2
dockers/docker-platform-monitor/Dockerfile.j2
dockers/docker-platform-monitor/start.sh
files/build_templates/sonic_debian_extension.j2

As part of the transition from Python 2 to Python 3, we are installing both pip2 and pip3 in the slave and config-engine containers. This PR replaces calls to `pip` in these containers with an explicit call to `pip2` to ensure the proper version of pip is executed, no matter which version of pip is aliased to `pip`, as we no longer rely on that alias.
Also some other pip-related cleanup

Explicitly call `pip2` rather than `pip` in locations where both pip2 and pip3 are installed

---

dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2

Found error logs in syslog:
```
Oct 10 12:41:09.148655 arc-switch1029 INFO pmon#supervisord 2020-10-10 12:41:07,689 INFO gave up: thermalctld entered FATAL state, too many start retries too quickly
```
The issue is related to the "startsecs" configuration of thermalctld in /etc/supervisor/conf.d/supervisord.conf. The current configuration setting the "startsecs" to 10, which means that it require thermalctld process running at least 10 seconds or supervisord will not restart it after it exiting even if the exit code is expected. 
See the official document for "startsecs" at http://supervisord.org/configuration.html:
```
startsecs
The total number of seconds which the program needs to stay running after a startup to consider the start successful. If the program does not …
```

[thermalctld] Enlarge startretries value to avoid thermalctld not able to restart during regression test

---

files/image_config/hostcfgd/hostcfgd

The update_all_feature_states can run in the range of 20+ seconds to one minute. With load of AAA & Tacacs preceding it, any DB updates in AAA/TACACS during the long running feature updates would get missed. To avoid, switch the order.
Do a load after after updating all feature states. 
Not a easy one
Have a script that 
restart hostcfgd
sleep 2s
run redis-cli/config command to update AAA/TACACS table
Run the script above and watch the file /etc/pam.d/common-auth-sonic for a minute.
***_When it repro:
The updates will not reflect in /etc/pam.d/common-auth-sonic  …

Load config after subscribe

---

dockers/docker-database/base_image_files/monit_database
dockers/docker-fpm-frr/base_image_files/monit_bgp
dockers/docker-lldp/base_image_files/monit_lldp
dockers/docker-orchagent/base_image_files/monit_swss
dockers/docker-sflow/base_image_files/monit_sflow
dockers/docker-snmp/base_image_files/monit_snmp
dockers/docker-sonic-restapi/base_image_files/monit_restapi
dockers/docker-sonic-telemetry/base_image_files/monit_telemetry
dockers/docker-teamd/base_image_files/monit_teamd
files/image_config/monit/conf.d/sonic-host
platform/barefoot/docker-syncd-bfn/base_image_files/monit_syncd
platform/broadcom/docker-syncd-brcm/base_image_files/monit_syncd
platform/cavium/docker-syncd-cavm/base_image_files/monit_syncd
platform/centec/docker-syncd-centec/base_image_files/monit_syncd
platform/marvell-arm64/docker-syncd-mrvl/base_image_files/monit_syncd
platform/marvell-armhf/docker-syncd-mrvl/base_image_files/monit_syncd
platform/marvell/docker-syncd-mrvl/base_image_files/monit_syncd
platform/mellanox/docker-syncd-mlnx/base_image_files/monit_syncd
platform/nephos/docker-syncd-nephos/base_image_files/monit_syncd
src/monit/patch/0002-change_monit_alert_log_error.patch
src/monit/patch/series

Why/How I did:
1. Make sure first error syslog is triggered based on FAULT TOLERANCE condition. 
2. Added support of repeat clause with alert action. This is used as trigger
for generation of periodic syslog error messages if error is persistent
3. Updated the monit conf files with repeat every x cycle for the alert action
For example:
Make sure monit is honoring below clause in generating error syslog.
if status != 0 for x cycle then alert repeat every y cycle.
With above clause error syslog will be generated after x cycle and for
every yth cycle if error is persistent
How I verify:
a) check program routeCheck with path "/usr/bin/route_check.py"
every 1 cycles
if status != 0 for 3 cycle then alert repeat every 3 cycles
Oct 26 18:12:54.773398  ERR monit[480]: 'routeCheck' status failed …

[monit] Adding patch to enhance syslog error message generation for monit alert action when status is failed.

---

files/image_config/interfaces/interfaces.j2
src/sonic-config-engine/tests/sample_output/py2/interfaces
src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces
src/sonic-config-engine/tests/sample_output/py3/interfaces
src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces

Fix https://github.com/Azure/SONiC/issues/551
When eth0 IP address is configured, an ip rule is getting added for eth0 IP address through the interfaces.j2 template. This code exists from the beginning; it is not clear on why this is required.
This eth0 ip rule creates an issue when VRF (data VRF or management VRF) is also created in the system.
When any VRF (data VRF or management VRF)  is created, a new rule is getting added automatically by kernel as "1000: from all lookup [l3mdev-table]".
This l3mdev IP rule is never getting deleted even if VRF is deleted.
Once if this l3mdev IP rule is added, if user configures IP address for the eth0 interface, interfaces.j2 adds an eth0 IP rule as "1000:from 100.104.47.74 lookup default ". Priority 1000 is automatically chosen by …

Kannankvs mvrf ip rule priority change to 32765

---

dockers/docker-platform-monitor/start.sh

On Arista platforms, sonic_platform packages are not installed in the PMon container, but are rather mounted into the container from the host OS. Therefore, `pip show sonic_platform` will fail in the PMon container.  This change will first check if we can import sonic_platform. If this fails, it will then fall back to checking if the package is installed. If both fail, it will attempt to install the package.

[docker-platform-monitor] Check if sonic_platform package is available before checking if installed

---

platform/mellanox/mlnx-sai.mk

* Updated SAI to v.1.17.7
* N/A
Enhancements and new features:
- L3 VXLAN new VRF pipeline
- FB Vlan allocation optimization
- FW dump me now is part of SAI debug dump
- Improve various logging messages
- Implement create method for several switch attributes
- SN4410 system support
Bug fix:
- Remove route with empty next hop group
```
//// / …
```

[201911][Mellanox] Update SAI to v.1.17.7.

---

dockers/docker-base-buster/etc/rsyslog.conf
dockers/docker-base-stretch/etc/rsyslog.conf
dockers/docker-base/etc/rsyslog.conf
files/image_config/rsyslog/rsyslog-container.conf.j2

Reverts Azure/sonic-buildimage#5666
Since Azure/sonic-sairedis#680 has been merged, this is no longer necessary.

Revert "[docker-base]: Rate limit priority INFO and lower in syslog"

---

device/mellanox/x86_64-mlnx_lssn2700-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn2010-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn2100-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn2410-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn2700-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn2700_simx-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn2740-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn3420-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn3700-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn3700_simx-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn3700c-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn3800-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn4600c-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn4700-r0/pcie.yaml
device/mellanox/x86_64-mlnx_msn4700_simx-r0/pmon_daemon_control.json

**This PR has a dependency on community change to move PCIe config files from $PLATFORM/plugin folder to $PLATFORM/ folder**
To support PCIed daemon on Mellanox platforms
Add PCIed config yaml files for all Mellanox platforms
Update pmon daemon config files for SimX platforms
Check PCIed running status and pcieutil commands output.

[Mellanox] add PCIed config files for Mellanox platforms

---

files/scripts/core_cleanup.py

**- Why I did it / How I did it**
- Fix bug: `CORE_FILE_DIR` previously was set to `os.path.basename(__file__)`, which would resolve to the script name. Fix this by hardcoding to `/var/core/`
- Remove locally-define logging functions; use Logger class from sonic-py-common instead
Test the script works properly

[201911][core_cleanup.py] Fix core file path; Improve code reuse

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

- BFN platform was affected by ACL changes that add IPV6_NEXT_HEADER support.
- Bugfixes
- Updated SDK packages to 20201023

[BFN] Updated SDK packages to 20201023

---

dockers/docker-base-buster/Dockerfile.j2
dockers/docker-database/Dockerfile.j2
platform/vs/docker-sonic-vs/Dockerfile.j2

Prevent intermittent build failures when building Sonic for the ARM platform architecture due to version upgrades of the redis-tools and redis-server packages.
Modify select Dockerfile templates to download the redis-tools and redis-server packages from sonicstorage rather than from debian.org.
This PR has been made possible by the inclusion of ARM versions of redis-tools and redis-server into sonicstorage as described in Issue# 5701
ARM Sonic images contain the expected versions of redis-tools and redis-server.
ARM build: Download redis-tools and redis-server from sonicstorage
**- A picture of a cute animal (not …

ARM build: Download redis-tools and redis-server from sonicstorage

---

Makefile.cache

Fix #5692 
It fixes the folling error when DPKG cache enabled.
make: execvp: /bin/bash: Argument list too long
make: *** [slave.mk:389: target/debs/buster/sonic-device-data_1.0-1_all.deb] Error 127
Number of dependent file list is more than 2K which causes bash arg long error. 
Used file operation to store the dependency list.
Build with dpkg enabled

Fix for - execvp: /bin/bash: Argument list too long error

---

dockers/docker-platform-monitor/Dockerfile.j2

Recent changes to dependencies caused the 'enum34' package to cease being installed for Python 2 in the PMon container. This broke Arista platforms, where the Arista sonic_platform package imports 'enum'. This is because on Arista devices, the sonic_platform wheel is not installed in the container. Instead, the installation directory is mounted from the host OS. However, this method doesn't ensure all dependencies are installed in the container.
Install Python 2 'enum34' package explicitly in PMon container for now.
Ensure sonic_platform package functions properly in the PMon container on Arista devices.

[docker-platform-monitor] Explicitly install Python 2 'enum34' package to fix Arista platforms

---

device/accton/x86_64-accton_as5812_54t-r0/plugins/sfputil.py
device/accton/x86_64-accton_as5812_54x-r0/plugins/sfputil.py
platform/broadcom/sonic-platform-modules-accton/as5712-54x/utils/accton_as5712_util.py
platform/broadcom/sonic-platform-modules-accton/as5812-54x/utils/accton_as5812_util.py

Signed-off-by: roy_lee <roy_lee@edge-core.com>
python pickle package is not secure. 
Remove pickle relative code, which are used as a cache.
sfputil show eeprom
Pickle is applied to save the order of i2c adapters at installation. 
With pickle removed, it just checks the order of i2c buses every time it needs.

[device/accton] Remove the use of python pickle package

---

device/dell/x86_64-dellemc_z9264f_c3538-r0/plugins/eeprom.py

Executing "show version" in DellEMC Z9264f reports following error:
root@sonic:~# show version
SONiC Software Version: SONiC.201911.30-781abed7
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 781abed7
Build date: Mon Nov 2 15:13:34 UTC 2020
Built by: johnar@jenkins-worker-8
Platform: x86_64-dellemc_z9264f_c3538-r0
HwSKU: DellEMC-Z9264f-C64
ASIC: broadcom
File "/usr/bin/decode-syseeprom", line 166, in <module>
exit(main())
File "/usr/bin/decode-syseeprom", line 50, in main
t = class_('board', '','','')
File "/usr/share/sonic/device/x86_64-dellemc_z9264f_c3538-r0/plugins/eeprom.py", line 24, in _init_
if os.path.exists(f):
NameError: global name 'os' is not defined
Serial Number:
Uptime: 07:08:49 up 3 min, 1 user, load …

DellEMC Z9264f: Fix show version error

---

files/scripts/core_cleanup.py

**- Why I did it / How I did it**
- Convert to Python 3
- Fix bug: `CORE_FILE_DIR` previously was set to `os.path.basename(__file__)`, which would resolve to the script name. Fix this by hardcoding to `/var/core/`
- Remove locally-define logging functions; use Logger class from sonic-py-common instead
Test the script works properly

[core_cleanup.py] Convert to Python 3; Fix core file path; Use logger from sonic-py-common for uniform logging 

---

src/sonic-device-data/tests/config_checker
src/sonic-device-data/tests/media_checker
src/sonic-device-data/tests/platform_json_checker

- Convert config_checker, media_checker and platform_json_checker scripts to Python 3
- Reorganize imports per PEP8 standard
Ensure scripts still function correctly

[sonic-device-data] Convert Python files to Python 3

---

files/build_templates/sonic_debian_extension.j2
files/image_config/corefile_uploader/core_uploader.py

- Convert core_uploader.py script to Python 3
- Use logger from sonic-py-common for uniform logging
- Reorganize imports alphabetically per PEP8 standard
- Remove unnecessary global variable declarations
Ensure core_uploader.py still functions correctly

[core_uploader.py] Convert to Python 3; Use logger from sonic-py-common for uniform logging 

---

build_debian.sh
files/build_templates/sonic_debian_extension.j2
files/image_config/misc/docker-wait-any

- Convert docker-wait-any script to Python 3
- Install Python 3 Docker Engine API in host OS
Ensure docker-wait-any script still functions correctly

[docker-wait-any] Convert to Python 3, install dependency in host OS

---

dockers/docker-orchagent/enable_counters.py

- Convert enable_counters.py script to Python 3
- Reorganize imports per PEP8 standard
Ensure enable_counters.py script still functions correctly

[enable_counters.py] Convert to Python 3

---

dockers/docker-sflow/port_index_mapper.py

A memory issue was discovered during system test for scaling. The issue is documented here.
https://docs.pyroute2.org/ipdb.html
> One of the major issues with IPDB is its memory footprint. It proved not to be suitable for environments with thousands of routes or neighbours. Being a design issue, it could not be fixed, so a new module was started, NDB, that aims to replace IPDB. IPDB is still more feature rich, but NDB is already more fast and stable.
- Rewrote the port_index_mapper.py script to use dB events.
- Convert to Python 3
Enabled the sflow container and verified the PORT_INDEX_TABLE was populated properly
- [] 201911
**- Description for the …

[sflow] Fix port_index_mapper.py script; Convert to Python 3

---

dockers/docker-nat/restore_nat_entries.py

- Convert restore_nat_entries.py script to Python 3
- Use logger from sonic-py-common for uniform logging
- Reorganize imports alphabetically per PEP8 standard
Ensure restore_nat_entries.py still functions correctly

[restore_nat_entries.py] Convert to Python 3; Use logger from sonic-py-common for uniform logging

---

files/image_config/hostcfgd/hostcfgd

Our use case is to register new features in runtime. The previous change which introduced the cache broke this capability and caused hostcfgd crash.
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>

[hostcfgd] If feature state entry not in the cache, add a default state

---

dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.conf.j2/all.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/all.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/defaults.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.conf
src/sonic-config-engine/tests/sample_output/py2/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/py2/frr.conf
src/sonic-config-engine/tests/sample_output/py3/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/py3/frr.conf

To avoid log messages like:
```
Nov  5 22:12:10.741378 str-s6100-acs-1 INFO bgp#bgpd[55]: Prefix-list LOCAL_VLAN_IPV4_PREFIX prefix changed from 192.168.0.1/21 to 192.168.0.0/21 to match length
Nov  5 22:12:10.741378 str-s6100-acs-1 INFO bgp#bgpd[55]: Prefix-list LOCAL_VLAN_IPV6_PREFIX prefix changed from fc02:1000::1/64 to fc02:1000::/64 to match length
```
I used jinja2 filter inside of sonic-config-engine to convert ip host address with mask to the ip network address.
Build an image and run on your DUT.
vtysh -c 'show run' | grep LOCAL_VLAN should show correct output
```
root@str-s6100-acs-1:~# sonic-cfggen -d -t /usr/share/sonic/templates/bgpd/bgpd.conf.j2 -y /etc/sonic/constants.yml | grep LOCAL_VLAN
ip prefix-list …
```

[BGP]: Convert ip address to network address for the LOCAL_VLAN filter

---

files/build_templates/init_cfg.json.j2

currently only vs platform has gdbsyncd feature built
currently only vs platform has gdbsyncd feature built
use jinja2 template to enable the feature only on vs platform.
will download the image built and try.

[init_cfg.json.j2]: only enable gbsyncd feature for vs platform

---

files/image_config/monit/process_checker

- Convert process_checker script to Python 3
Ensure check_install.py script still functions correctly

[Monit process_checker] Convert to Python 3

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml
src/sonic-config-engine/tests/test_minigraph_case.py

IP-in-IP tunnel support
Take tunnel info from `<TunnelInterface>` tag in minigraph, and create tables in config_DB:
```
"TUNNEL": {
"MUX_TUNNEL_0": {
"tunnel_type": "IPINIP",
"dst_ip": "26.1.1.10",
"dscp_mode": "uniform",
"encap_ecn_mode": "standard",
"ecn_mode": "copy_from_outer",
"ttl_mode": "pipe"
}
}
```

[minigraph.py]: Parse IP-in-IP tunnels from minigraph

---

dockers/docker-sflow/Dockerfile.j2
dockers/docker-sflow/port_index_mapper.py

* Fix some spelling error and add addition check in port_index_mapper.py
script.
* Remove unneeded pyroute2 python module from sFlow container
Signed-off-by: Garrick He <garrick_he@dell.com>
This PR just addresses some minor spelling issue in the port_index_mapper.py script and removes an unneeded module.
Update a 2 files
Check the stateDB to ensure PORT_INDEX_TABLE is created and ensure the pyroute2 module is not installed.
* Fix some spelling error and add addition check in port_index_mapper.py
script.
* Remove unneeded pyroute2 python module from sFlow container

[sflow] Clean-up sFlow container and port_index_mapper.py script

---

src/sonic-bgpcfgd/bgpmon/bgpmon.py

Simply looping through `dict_key` object instead of index-subscribing to
fix this.
fixes #5858 
`bgpmon` fails to run and flooding syslogs with errors like:
```
Nov  8 03:30:20.736704 str-dx010-acs-4 INFO bgp#/bgpmon: bgpmon service started
Nov  8 03:30:24.209370 str-dx010-acs-4 INFO bgp#supervisord 2020-11-08 03:30:19,574 ERRO pool dependent-startup event buffer overflowed, discarding event 3948
Nov  8 03:30:24.209370 str-dx010-acs-4 INFO bgp#supervisord 2020-11-08 03:30:19,575 INFO exited: bgpmon (exit status 1; not expected)
Nov  8 03:30:24.209370 str-dx010-acs-4 INFO bgp#supervisord 2020-11-08 03:30:20,576 ERRO pool dependent-startup event buffer overflowed, discarding event 3949
Nov  8 03:30:24.209370 …
```

[bgpmon] Fix `dict_keys` unsubscriptable error

---

dockers/docker-fpm-frr/base_image_files/monit_bgp
dockers/docker-lldp/base_image_files/monit_lldp

lldpmgrd, bgpcfgd, and bgpmon are reported error status not running due
to recent change of shebang to use `Python3`. Modifying the argument of
`process_checker` to follow this change.
fixes #5864 
```
Nov  9 04:36:38.750321 str-dx010-acs-4 ERR monit[519]: 'lldp|lldpmgrd' status failed (1) -- 'python /usr/bin/lldpmgrd' is not running.
Nov  9 04:36:38.916896 str-dx010-acs-4 ERR monit[519]: 'bgp|bgpcfgd' status failed (1) -- '/usr/bin/python /usr/local/bin/bgpcfgd' is not running.
Nov  9 04:36:38.941334 str-dx010-acs-4 ERR monit[519]: 'bgp|bgpmon' status failed (1) -- '/usr/bin/python /usr/local/bin/bgpmon' is not running.
```
* actually command line for `lldpmgrd`, `bgpcfgd` and `bgpmon`:
```
admin@str-dx010-acs-4:~$ ps …
```

[monit] Fix status error due to shebang change

---

files/scripts/update_chassisdb_config

- Convert update_chassisdb_config script to Python 3
- Reorganize imports per PEP8 standard
Ensure check_install.py script still functions correctly

[update_chassisdb_config] Convert to Python 3

---

dockers/docker-fpm-frr/frr/bgpd/templates/internal/instance.conf.j2
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v6.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v6.conf
src/sonic-bgpcfgd/tests/test_templates.py
src/sonic-py-common/sonic_py_common/multi_asic.py

Update the routine is_bgp_session_internal() by checking the BGP_INTERNAL_NEIGHBOR table. 
Additionally to address the review comment https://github.com/Azure/sonic-buildimage/pull/5520#discussion_r513721041
Add timer settings as will in the internal session templates and keep it minimal as these sessions which will always be up.
Updates to the internal tests data + add all of it to template tests.
Updated the APIs and the template files.
Verified the internal BGP sessions are displayed correctly with show commands with this API is_bgp_session_internal()

[multi-ASIC] util changes with the BGP_INTERNAL_NEIGHBOR table.

---

dockers/docker-teamd/base_image_files/teamdctl

What I did:
Enhanced teamdctl bash script to work for Multi-asic. Added option -n [0 to n] (asic number).
Changes are similar to other scripts swssloglevel/bcmcmd that has multi-asic support.
Why I did:
Some of sonic-mgmt test case (test_lag_2.py)  uses teamdctl command from test script.
How I Verify:
Usage: /usr/bin/teamdctl -n [0 to n] [OPTION]...
Single ASIC:
```
teamdctl PortChannel0002 state
setup:
runner: lacp
ports:
Ethernet0
link watches:
link summary: up
```
Multi ASIC
```
teamdctl -n 0 PortChannel0002 state
setup:
runner: lacp
ports:
Ethernet0
link watches:
link summary: up
instance[link_watch_0]:
name: ethtool
link: up
down count: 0
runner:
aggregator ID: 139, Selected
selected: yes
state: current
Ethernet4
link watches:
link summary: up
instance[link_watch_0]:
name: ethtool …
```

[multi-asic] Updated teamdctl bash script to support for multi-asic

---

files/build_templates/docker_image_ctl.j2

Why I did:
API getMount() API was not updated to handle multi-asic platforms
because of which mount point comparison always return FALSE
and we were always creating new container image when doing config load_minigraph/reload/reboot.
How I did:
Updated API getMount() to return abspath() for Docker Mount Point
and use that one for mount point comparison
How I Verify:
- Verify on Single ASIC platforms behavior is same as present
- Verify on Multi-asic platforms we do not create new container when doing config load_minigraph/reload/reboot.
- Also sonic-mgmt copp test were failing on Multi-asic platform 
since test case update copp.json in swss docker and restart docker but that
change did not took impact since we were creating new container. 
After this changes test case is working fine

[multi-asic] Enhanced the getMount() API and  docker mount point check 

---

device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/buffers.json.j2
device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/buffers_defaults_t0.j2
device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/buffers_defaults_t1.j2
device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/qos.json.j2

On Arista-7050CX3-32S-C32, there are constant stream of errors like following.
Nov  3 21:56:24.415190 str2-7050cx3-acs-06 NOTICE swss#orchagent: :- registerInWdDb: No lossless TC found on port Ethernet68
Which causes:
1. loganalyzer to claim test failed.
2. leaving the system without MMU configuration. Which couldn't be good for any IO test.
Added these MMU configuraions are copied from another platform and guaranteed to be incorrect for hwsku Arista-7050CX3-32S-C32.
Adding them so that we have A MMU configuration and the system won't throw a whole bunch of errors and leave MMU unconfigured. The correct MMU configuration will come later.
This configuration is definitely not suitable for testing system performance or QoS behavior.
Signed-off-by: Ying …

[Arista 7050cx3] add dummy MMU configurations for Arista-7050CX3-32S-C32

---

dockers/docker-fpm-frr/frr/bgpd/templates/internal/instance.conf.j2
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v6.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v6.conf
src/sonic-bgpcfgd/tests/test_templates.py
src/sonic-py-common/sonic_py_common/multi_asic.py

Reverts Azure/sonic-buildimage#5760
Couple of python3 fixes were missed as the py2 --> py3 transition is going on.

Revert "[multi-ASIC] util changes with the BGP_INTERNAL_NEIGHBOR table."

---

src/sonic-bgpcfgd/setup.py
src/sonic-yang-mgmt/setup.py
src/sonic-yang-models/setup.py

setup.py files are not executable, and thus have no need for shebangs.
- Also remove unnecessary comments

Remove shebangs from setup.py files

---

dockers/docker-fpm-frr/frr/bgpd/templates/internal/instance.conf.j2
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v6.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v6.conf
src/sonic-bgpcfgd/tests/test_templates.py
src/sonic-py-common/sonic_py_common/multi_asic.py

Reintroduce https://github.com/Azure/sonic-buildimage/pull/5760, along with the fix needed in the template file for python3 compatibility

[multi-ASIC] util changes with the BGP_INTERNAL_NEIGHBOR table

---

src/sonic-host-services/scripts/caclmgrd

- Why I did it
To make Control plane ACLs handle case insensitive ACL rules. Currently, it handles only upper case ACL rules.
- How I did it
I set the rule prop dictionary to be all upper case before reading the rule props for processing.
Configure ACL rules with any combination of case of ACL rules, either it be upper case or lower case. All rules should be created properly in the switch and working properly.
The change is a one line change in caclmgrd script.

Accomadating lower case ACL rules for Control Plane ACLs

---

src/sonic-config-engine/openconfig_acl.py

Python 3 is more strict with `__slots__`. As per the [documentation](https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots):
> \_\_slots\_\_ are implemented at the class level by creating descriptors (Implementing Descriptors) for each variable name. As a result, class attributes cannot be used to set default values for instance variables defined by \_\_slots\_\_; otherwise, the class attribute would overwrite the descriptor assignment.
This was apparently missed when making sonic-config-engine compliant with Python 3, and errors like the following would be seen:
```
tests/acl_loader_test.py:10: in <module>
from acl_loader.main import *
acl_loader/main.py:8: in <module>
import openconfig_acl
/usr/local/lib/python3.7/dist-packages/openconfig_acl.py:24: …
```

[sonic-config-engine] openconfig_acl.py: Make compliant with Python 3

---

files/image_config/sudoers/sudoers

In multi asic platforms the "show ip bgp summary" commands is not available for user with read only privileges, so fix this the vtysh command with the new` "-n"` option, added for multi asic platforms, needs to be added to the READ_ONLY_COMMANDS list in the sudoers files 
Add the command `vtysh -n [0-9] -c show *` to list of READ_ONLY_COMMANDS in the sudoers files
Verify show ip bgp summary is working for user accounts with read-only privilages
- [X ] 201911

Add the vtysh command with newly added "-n"  option for multi asic  to  the read_only_cmds

---

files/image_config/interfaces/interfaces.j2
src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces
src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces
src/sonic-config-engine/tests/t0-sample-graph-mvrf.xml

When forced mgmt routes are present, the issue fixed as part of https://github.com/Azure/sonic-buildimage/pull/5754 is not complete.
Added a preference(priority) field to forced mgmt route ip rules
Verified on device 

Set preference for forced mgmt routes

---

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py

New driver support fetching additional pages from the cable EEPROM.
There are additional information to parse now: RX/TX power, TX bias, TX fault and RX LOS.
Set the flag to 'True' for supporting these fields.
Correct the offset in the EEPROM.
Connect a QSFP-DD active cable to the switch.
Run 'show interface transceiver eeprom Ethernet# -d' command.
Observe the "ChannelMonitorValues" output.
QSFP-DD DOM information: RX/TX power, TX bias, TX fault and RX LOS.

[Mellanox] Enhance QSFP-DD DOM information

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init

The original code tried to initialize PCA9541 without having the driver loaded. As result the initialization didn't take effect.
Recently PCA9541 driver was added to the kernel and since then the initialization takes effect and has negatively impacted the
platform stability.
Commenting the initialization code out to restore the original behavior while analyzing further.
Manually made the change on a device subject to the issue. Reboot the device and the device becomes healthy. Particularly, able to access psu status. And can run test_link_flap without triggering sanity check failures.

[celestica dx010] comment out the initialization of PCA9541

---

src/sonic-bgpcfgd/tests/test_bbr_templates.py
src/sonic-bgpcfgd/tests/test_ipv6_nexthop_global.py
src/sonic-bgpcfgd/tests/test_templates.py
src/sonic-bgpcfgd/tests/util.py

To check that constants.yml has required information to support BBR templates
The test read all peer-groups, which has BBR settings and then checks that constants.yml has the peer-group configured.
```
cd sonic-buildimage/src/sonic-bgpcfgd
pytest tests/test_bbr_t*
```

[bgpcfgd]: Implement BBR template test

---

src/libteam/patch/0011-Remove-extensive-debug-output.patch
src/libteam/patch/series

resolves #5855
Remove extensive output in teamd to fix #5855 
By commenting out the debug output in the code
Build and image, run on your dut. Check that `grep 'usock: calling method' /var/log/teamd.log` shows nothing.

[teamd]: Remove extensive debug output for libteamdctl

---

check_install.py
sonic-slave-buster/Dockerfile.j2

- Convert check_install.py script to Python 3
- Reorganize imports per PEP8 standard
Ensure check_install.py script still functions correctly

[check_install.py] Convert to Python 3

---

src/sonic-py-common/sonic_py_common/device_info.py

Avoiding failure getting system mac on Marvell asic platforms 
utilize syseeprom for system mac first and remove dependency on get_hwsku 
boot marvell platforms and execute OC tests 
utilize eeprom for system mac and remove dependency on get_hwsku

[Marvell] Utilize eeprom for system mac and remove dependency on get_hwsku

---

rules/sonic-utilities.mk

Recently updated the sonic-utilities Jenkins build environment [here](https://github.com/Azure/sonic-build-tools/pull/185) to begin running tests on the Python 3 version of the sonic-utilities package. However, the build is failing because it attempts to copy the Python 3 sonic-yang-mgmt package from the artifacts of the latest VS build, but the package does not exist because there are no targets which specify it as a dependency. This PR will ensure the Python 3 package is built during the image build process.
Add Python 3 sonic-yang-mgmt package as a dependency in sonic-utilities makefile.
Ensure sonic_yang_mgmt-1.0-py3-none-any.whl appears in the artifacts of the VS image build …

[sonic-utilities] Add Python 3 sonic-yang-mgmt package as a dependency

---

build_debian.sh
dockers/docker-base-stretch/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2

[armhf] Update SSL CA certificates to verify downloads
[redis] Using redis-tools from blob sonic-storage for docker-base-stretch
**- What I did it**
1. Update SSL ca certificates for verifying secure downloads (specific to arm).
2. Changed redis tools version to redis-tools_6.0.6-1~bpo10 and using redis-tools from blob sonic-storage for docker-base-stretch
Compiled and verified for armhf arch

[armhf] Compilation fixes for armhf arch

---

files/build_templates/buffers_config.j2

Backend devices do not have cable lengths properly configured because the device role is not recognized in the buffers_config template.
Remove 'backend' from the device roles so that backend devices are configured the same as non-backend devices
Render the template on a device with type 'BackEndTorRouter' or 'BackEndLeafRouter' and confirm that the cable lengths are set correctly.

[buffers_config.j2]: Use correct cable lengths for backend devices

---

files/image_config/caclmgrd/caclmgrd

To make Control plane ACLs handle case insensitive ACL rules. Currently, it handles only upper case ACL rules.
I set the rule prop dictionary to be all upper case before reading the rule props for processing.
Configure ACL rules with any combination of case of ACL rules, either it be upper case or lower case. All rules should be created properly in the switch and working properly.
The change is a one line change in caclmgrd script.

[201911][caclmgrd] Accomadating case insensitive rule props for Control plane ACLs

---

platform/centec-arm64/docker-syncd-centec.mk
platform/centec-arm64/rules.mk
platform/centec-arm64/sai.mk

Build depends have been optimized in PR #4880 and PR #5039. These optimizations need to be merged to Centec ARM64 platform. 
Remove the dependency
Compile Centec ARM64 based images
LIBSAIREDIS isn't depend on CENTEC_SAI, Remove this dependency

[CENTEC ARM64]LIBSAIREDIS isn't depend on CENTEC_SAI, Remove this dependency

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml
src/sonic-config-engine/tests/test_cfggen.py
src/sonic-config-engine/tests/test_minigraph_case.py
src/sonic-config-engine/tests/test_multinpu_cfggen.py

- Parse device IPv6 loopback addresses when available
- Add MUX_CABLE table to config DB:
```
'MUX_CABLE': {
'Ethernet4': {
'state': 'auto',
'server_ipv4': '10.10.10.1/32',
'server_ipv6': 'fe80::0001/128'
}
}
```

[minigraph.py]: Parse mux cable table

---

src/sonic-py-common/sonic_py_common/device_info.py
src/sonic-py-common/sonic_py_common/multi_asic.py

The behavior of `subprocess.Popen()` changed in Python 3 such that stdin, stdout and stderr are treated as bytes by default. Adding the `universal_newlines=True` argument changes this behavior to return strings, matching the behavior of Python 2.
**- How to verify it**'
Call the affected functions using both Python 2 and Python 3 and ensure both provide the same, correct results.

[sonic-py-common] Add 'universal_newlines=True' arg to all Popen calls to properly support Python 3

---

platform/mellanox/mlnx-platform-api/sonic_platform/fan.py
platform/mellanox/mlnx-platform-api/sonic_platform/utils.py

Cherry-pick Azure#5682 to 201911
As new hw-mgmt expose the sysfs for PSU fan max speed, we need support max/min speed for PSU fan in mellanox platform API.
Read the max fan speed from sysfs.
Manual test and run existing regression.

[Mellanox] Support max/min speed for PSU fan for 201911 (#5682)

---

files/image_config/constants/constants.yml
src/sonic-bgpcfgd/bgpcfgd/managers_bbr.py
src/sonic-bgpcfgd/tests/test_bbr.py

The current implementation of BBR has two issues:
1. constants.yml uses key "bgp.bbr.enabled" as a key to enable disable BBR feature and as a default state for the BBR feature.
2. If the current configuration doesn't have some peer-groups, which are listed in constants.yml bgp.peers.*.bbr bgpcfgd will report an error of updating such peer-groups.
1. I added a key bgp.bbr.default_state with values "enabled" or "disabled" into constants.yml. Now bgp.bbr.enabled controls will bgpcfgd support BBR feature or not. And bgp.bbr.default_state control initial state of the BBR.
2. I added an extra-code to check what peer-groups in the current config. After that bgpcfgd skips all peer-groups from constants,yml which are not presented in bgp config. 
**- How to …

[bgpcfgd]: Fixes for BBR

---

files/image_config/warmboot-finalizer/finalize-warmboot.sh

There is a issue for counters after warm-reboot:
If I clear counters by command "sonic-clear counters", then execute 'warm-reboot' and whenSONiC is restart, the counters showed with command "show interface counters" is still old counters before "sonic-clear".  It is not the right counters because the counters file in '/tmp' is lost in warm-reboot process.
I fixed it by saving '/tmp/portstat-0' folders in '/host/' before executing 'warm-reboot'  (in pull request Azure/sonic-utilities#1099 ), and restore the counters folders back to '/tmp/' after warm-reboot process is finished.
1.  Clear counters by command 'sonic-clear'
sonic-clear counters
sonic-clear dropcounters
sonic-clear pfccounters
sonic-clear queuecounters
sonic-clear …

fix error: interface counters is mismatch after warm-reboot

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/test_minigraph_case.py

Dual ToR devices require specific VLAN_INTERFACE attributes to be set

[minigraph.py]: Add VLAN_INTERFACE attributes for dual ToR devices

---

src/sonic-frr/patch/0007-frr-remove-frr-log-outchannel-to-var-log-frr.log.patch
src/sonic-frr/patch/series

frr is creating /var/log/frr/frr.log inside the frr docker and letting it grow. It will eventually exhaust hard drive space.
To fixe issue #5965 
Remove rsyslog file outchannel so that frr won't generate /var/log/frr/frr.log inside the docker.
Manually removed the outchannel and restart BGP docker, making sure that /var/log/frr/frr.log is no longer created inside the docker.
While restarting bgp docker, observed that base image /var/log/quagga/bgpd.log continued to grow and captured all FRR logs.

[frr] remove FRR rsyslog file outchannel

---

src/sonic-config-engine/data/l2switch.j2
src/sonic-config-engine/tests/test_j2files.py

The l2switch.j2 template does not include all fields for PORT. This could be incompatible with the 201911 image or later. 
Update l2switch.j2 template and add a unit test.

[L2 switch mode] Update l2switch.j2 template

---

platform/mellanox/mlnx-platform-api/sonic_platform/fan.py

There is a missing variable assignment in fan.get_presence, and it causes fan.get_presence always return false.
Set the variable with proper value
Run platform regressions 

[Mellanox] Fix issue: fan.get_presence always return false for 201911

---

dockers/docker-fpm-frr/TSC

Fixes: https://github.com/Azure/sonic-buildimage/issues/5957
It is addition to https://github.com/Azure/sonic-buildimage/pull/5906
When TSC checks for route-maps, skip all route-maps which are not included V4 or V6. Check the previous PR
First restart dut, then do sudo config reload -y, then TSA, then TSC. See the example below:
```
admin@str-s6100-acs-1:~$ uptime
00:38:55 up 1 min,  1 user,  load average: 4.03, 1.69, 0.62
admin@str-s6100-acs-1:~$ TSC
Traffic Shift Check:
System Mode: Normal
admin@str-s6100-acs-1:~$ sudo config reload -y
Executing stop of service telemetry...
Warning: Stopping telemetry.service, but it can still be activated by:
telemetry.timer
Executing stop of service swss...
Executing stop of service lldp... …
```

[TSA]: Fix TSC. Avoid 'Not consistent' state

---

README.md

Jenkins job does not exist any more
This reverts commit f2e8187400d3bcb76686c4d9bb7eb5838f9c0abd.
Reverts Azure/sonic-buildimage#4923

Revert "[build]: Add build badge for Barefoot 202006 build (#4923)"

---

files/image_config/bash/bash.bashrc

To support reverse SSH for console connection, we need to add the script to attach to console line automatically after user login with reverse SSH.
(see HLD for more detail: https://github.com/Azure/SONiC/blob/master/doc/console/SONiC-Console-Switch-High-Level-Design.md#313-reverse-ssh)
The script will be executed only when this feature is available in SONiC: https://github.com/Blueve/openssh-portable/pull/1
Add script to `/etc/bash.bashrc` to support reverse ssh function.
**Functional Test**
_My first pet. My cutest boy. My favorite friend, My family. My …

[bash.bashrc] Add reverse SSH script to bash.bashrc

---

platform/barefoot/docker-syncd-bfn/supervisord.conf
platform/broadcom/docker-syncd-brcm/supervisord.conf
platform/centec-arm64/docker-syncd-centec/supervisord.conf
platform/centec/docker-syncd-centec/supervisord.conf
platform/innovium/docker-syncd-invm/supervisord.conf
platform/marvell-arm64/docker-syncd-mrvl/supervisord.conf
platform/marvell-armhf/docker-syncd-mrvl/supervisord.conf
platform/marvell/docker-syncd-mrvl/supervisord.conf
platform/nephos/docker-syncd-nephos/supervisord.conf

Some syncd containers are still based on Debian Stretch, and thus do not have Python 3 available. For these containers, we must still rely on Python 2 to run supervisord_dependent_startup and supervisor-proc-exit-listener
Explicitly start supervisord_dependent_startup and supervisor-proc-exit-listener with Python 2 in syncd containers which are still based on Debian Stretch.
Ensure the syncd container starts properly and both supervisord_dependent_startup and supervisor-proc-exit-listener do not exit unexpectedly.

Syncd containers still based on Stretch must still use Python 2

---

dockers/docker-fpm-frr/frr/bgpd/templates/general/policies.conf.j2
dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_all.conf
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_base.conf
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_deny.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v6.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v6.conf
src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_back.conf
src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_front.conf
src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_back.conf
src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_front.conf
src/sonic-bgpcfgd/tests/test_ipv6_nexthop_global.py

Without the rule, IPv6 route-map entries were skipped.
Added 'on-match next' rule after 'set ipv6 next-hop prefer-global.
Updated a test to check that we have 'on-match next' rule with the 'set ipv6 next-hop prefer-global'
Build an image. Run on your dut. Add a route-map entry after 'set ipv6 next-hop prefer-global'. Check that the route-map entry works  

[bgpcfgd]: Add on-match next rule for set ipv6 next-hop prefer-global

---

platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/eeprom.py

Make EEPROM platform APIs Python3 compliant in DellEMC platforms.
Handle `bytearray` type returned by `read_eeprom` and `read_eeprom_bytes` methods.
Wrote a python script to load Chassis class and then call the APIs accordingly.
Logs:  [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/5561422/UT_logs.txt)
[DellEMC]: EEPROM platform API Python3 compliance changes

[DellEMC]: EEPROM platform API Python3 compliance changes

---

src/libyang/patch/large_file_support_arm32.patch
src/libyang/patch/series

In the emulated armhf environment, the function readdir()returns NULL on a ext4 file system directory. When running the libyang test cases, it will require to load the plugins from the files (such as metadata.so), because the readdir() is failing, the plugins can’t be loaded in the emulated armhf environment, so it causes libyang test error. This error is a combination of the following reasons.
• Emulation of a 32-bit target from a 64-bit host –> qemu from x86_64 to armhf
• Glibc version > 2.27 – Debian buster is using glibc 2.28
Enabled large file support by setting _FILE_OFFSET_BITS=64 for libyang.
Compiled and verified libyang unit tests in arm32, amr64 and intel …

[libyang] Adding LFS support for arm32

---

device/mellanox/x86_64-mlnx_msn3700c-r0/ACS-MSN3700C/hwsku.json
device/mellanox/x86_64-mlnx_msn3700c-r0/platform.json

Created capability files according to platform specification SN3700C
Verification in progress

[DPB] added capability files for SN3700C platform

---

files/build_templates/init_cfg.json.j2
files/scripts/supervisor-proc-exit-listener
src/sonic-host-services/scripts/hostcfgd

Why I did:
Fixes Issue#https://github.com/Azure/sonic-buildimage/issues/5999
How I did:
- Added new flag value 'always_enabled' for the state and auto-restart field of feature table
- init_cfg.json is updated to initialize state field of database/swss/syncd/teamd feature and auto-restart field of database feature 
as always_enabled 
- Once the state/auto-restart value is initialized as "always_enabled" it is immutable and cannot be change via feature config commands. (config feature..) PR#https://github.com/Azure/sonic-utilities/pull/1271
- hostcfgd will not take any action if state field value is 'always_enabled'
- Since we have always_enabled field for auto-restart updated supervisor-proc-exit-listener
not to have special check for database and always rely  on value from Feature table. …

Enhanced Feature table to support 'always_enabled' value for state and auto-restart fields.

---

src/sonic-bgpcfgd/bgpcfgd/config.py
src/sonic-bgpcfgd/bgpcfgd/frr.py
src/sonic-bgpcfgd/bgpcfgd/main.py
src/sonic-bgpcfgd/bgpcfgd/managers_allow_list.py
src/sonic-bgpcfgd/bgpcfgd/managers_bbr.py
src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
src/sonic-bgpcfgd/bgpcfgd/managers_setsrc.py
src/sonic-bgpcfgd/bgpcfgd/runner.py
src/sonic-bgpcfgd/bgpcfgd/utils.py
src/sonic-bgpcfgd/tests/test_allow_list.py
src/sonic-bgpcfgd/tests/test_bbr.py
src/sonic-bgpcfgd/tests/test_config.py
src/sonic-bgpcfgd/tests/test_frr.py
src/sonic-bgpcfgd/tests/test_ipv6_nexthop_global.py

vtysh -f command is slow. It sometimes takes about 3 seconds.
When we need to run many vtysh -f commands that slows down the system.
With this fix bgcfgd configuration time reduced from 10.58 sec to 2.80 sec on my dut.
1. Read as many messages as possible from the database
2. Run through bgpcfgd all the messages, collecting  frr updates;
3. commit all updates as a batch
Build an image and run on your dut. All tests must be working

[bgpcfg]: Batch bgp updates

---

src/sonic-host-services-data/debian/sonic-host-services-data.process-reboot-cause.service

The path should be /usr/local/bin not /usr/bin
Change the ExecStart path
Check if it starts
Addresses an issue mentioned in https://github.com/Azure/sonic-buildimage/issues/6009, but does not close the issue.

Fix the ExecStart path for process-reboot-cause

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
platform/broadcom/sonic-platform-modules-cel/dx010/cfg/dx010-modules.conf

Fix the i2c device to address conflicts behind the PCA9548 switch.
Load the i2c-mux-pca954x with parameter __force-deselect-on-exit=1__.
Stress read the temperature that has the same I2C address with the following steps:
1. Run the stress temperature sensors read of **lm75b-i2c-5-48** and **lm75b-i2c-14-48**.
2. Heat up one of the temperature sensors.
3. Inspect that the temperature read value. 
- The temperature of the heat-up sensor should raise up.
- The temperature of another sensor MUST be steady. 
Test Log: [5.lm75b-i2c-5-48_lm75b-i2c-14-48-pca9548-force-close.log](https://github.com/Azure/sonic-buildimage/files/5523785/5.lm75b-i2c-5-48_lm75b-i2c-14-48-pca9548-force-close.log) …

[platform-drv/cls] Dx010: fix pca9548 downstream device address collision

---

dockers/docker-fpm-frr/frr/bgpd/templates/general/instance.conf.j2
dockers/docker-fpm-frr/frr/bgpd/templates/general/peer-group.conf.j2
src/sonic-bgpcfgd/bgpcfgd/managers_bbr.py
src/sonic-bgpcfgd/tests/data/general/instance.conf/param_all_v4.json
src/sonic-bgpcfgd/tests/data/general/instance.conf/param_all_v6.json
src/sonic-bgpcfgd/tests/data/general/instance.conf/param_base_v4.json
src/sonic-bgpcfgd/tests/data/general/instance.conf/param_base_v6.json
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_all_v4.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_all_v6.conf
src/sonic-bgpcfgd/tests/test_bbr.py

FRR 7.2.1 has a bug: when 'allowas-in' is configured on peer-group, and we remove that configuration, the neighbors, which had that configuration, keeps that configuration.
To fix the bug I apply the configuration to all neighbors, which are configured with the peer-groups, which should support BBR.
1. Build an image
2. Run on your dut
3. Check that the test https://github.com/Azure/sonic-mgmt/blob/master/tests/bgp/test_bgp_bbr.py not fails

[bgpcfgd]: Use peer commands for BBR, not peer-group

---

src/sonic-frr/patch/0007-frr-remove-frr-log-outchannel-to-var-log-frr.log.patch

Fix issue #6043 
We are disabling in container frr log. The log entries are sent to base image and are logged in /var/log/quagga/bgpd.log.
However, we need to remove the whole outchannel config block to avoid an error message raised by rsyslogd.
Without the change, test_autorestart bgp container will fail on loganalyer errors. With the change, restarting bgp container is no longer generating error message and the test will pass.
The log generated by frr continued appearing in /var/log/quagga/bgpd.log

[FRR] remove the whole block of outchannel properly

---

src/sflow/hsflowd/Makefile

* Bump the hsflowd version in the Makefile using variables
instead of hardcore.
Signed-off-by: Garrick He <garrick_he@dell.com>
Even though we bumped the hsflowd version in sflow.mk, the new version is not picked up in the hsflowd Makefile because it is hardcoded. So the lastest images are still using the old version of hsflowd.
Updated the Makefile to use variables instead of hardcore the version.
Rebuild sflow container and verify hsflowd version with (`hsflowd -v`) to ensure it is 2.0.28
N/A
* Bump the hsflowd version in the Makefile using variables
instead of hardcore.

[sflow] Bump hsflowd version

---

README.md

Innovium make target and syncd docker image information was missing
Added Innovium make target and syncd docker image information
Verified 
https://sonic-jenkins.westus2.cloudapp.azure.com/job/innovium/job/buildimage-invm-201911/lastSuccessfulBuild/artifact/target/docker-syncd-invm.gz
- [ X] 201911
- [X ] 202006
Update Readme with Innovium support

sonic-buildimage: Update Readme with Innovium support

---

platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py

EEPROM cache file is not refreshed after install a new ONIE version even if the eeprom data is updated. The current Eeprom class always try to read from the cache file when the file exists. The PR is aimed to fix it. 
When eeprom object init, always remove the cache file and read eeprom data from hardware.
Run platform related regression test cases

[Mellanox] Remove eeprom cache file when first time init eeprom object

---

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh

For determining reboot-cause while running newer BIOS, SMF firmware.
Made changes in reboot-cause determination script to add support for behavior of newer firmware.
Performed different type of resets and verified "show reboot-cause" provides the correct reason.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/5487072/UT_logs.txt)
DellEMC S6100: Update reboot-cause determination to support new firmware

DellEMC S6100: Update reboot-cause determination to support new firmware

---

device/arista/x86_64-arista_7170_64c/sensors.conf

Rename chip name dps1900-i2c-X-58 to pmbus-i2c-X-58 in sensors.conf for Arista 7170 due to latest updates for Arista driver submodules #5686. After these updates adapter dps1900 was renamed and sensors.conf file is not applied properly. Issue was observed started from BFN SONiC image 16. See logs below
SONiC 13
```
admin@sonic:~$ sensors -A -u
dps1900-i2c-7-58
vin:
in1_input: 0.000
in1_alarm: 0.000
vout1:
in2_input: 0.000
in2_lcrit: 10.750
in2_crit: 14.250
in2_lcrit_alarm: 0.000
in2_crit_alarm: 0.000
fan1:
fan1_input: 7888.000
fan1_alarm: 0.000
fan1_fault: 0.000
PSU2 primary hotspot temp:
temp1_input: 0.000
temp1_alarm: 0.000
PSU2 inlet temp:
temp2_input: 0.000
temp2_alarm: 0.000
iin:
curr1_input: 0.000
curr1_max: 10.000
curr1_max_alarm: 0.000
iout1:
curr2_input: 0.000
curr2_max: 71.875 …
```

[Arista] Rename chip in sensors.conf for 7170 platform

---

src/sonic-host-services/scripts/hostcfgd

'always_enabled' feature can still be disabled/enabled.
When checking if a feature is 'always_enabled', check the cached state to prevent new change to be accepted.
Fix an issue where cache value is updated before all the check is done.
Restore 'always_enabled' value in config db if someone wants to change.
Without the change:
root@str2-dx010-acs-6:/home/admin# show feature status
Feature         State           AutoRestart
--------------  --------------  --------------
...
teamd           always_enabled  enabled
...
root@str2-dx010-acs-6:/home/admin# config feature state  teamd disabled
root@str2-dx010-acs-6:/home/admin# show feature status
Feature         State …

[hostcfgd] check cached state instead of the next state

---

src/sonic-bgpcfgd/bgpcfgd/managers_allow_list.py

This change is to fix the bgp crash issue after BGP allow list configuration is added. If load BGP allow list configuration, the `bgp` service will crash:
```
admin@vlab-03:~$ cat /tmp/allow_list.json 
{
"BGP_ALLOWED_PREFIXES": {
"DEPLOYMENT_ID|0": {
"prefixes_v6": [
"2000:172:16:10::/64"
], 
"prefixes_v4": [
"172.16.10.0/24"
]
}, 
"DEPLOYMENT_ID|0|1010:1010": {
"prefixes_v6": [
"2000:172:16:30::/64"
], 
"prefixes_v4": [
"172.16.30.0/24"
]
}
}
admin@vlab-03:~$ sonic-cfggen -j /tmp/allow_list.json -w
admin@vlab-03:~$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                     PORTS               NAMES
78fd2e87f307        docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe鈥   About an hour ago   Up About …
```

Fix bgp crash after BGP allow list configuration is added

---

device/mellanox/x86_64-mlnx_msn2700-r0/pmon_daemon_control.json
dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2

Delay start xcvrd on mellanox platform to save CPU cost during fast-reboot. With this change, fast-reboot saves about 8~9 seconds.
Add a sleep before xcvrd start in pmon supervisor.conf
Manual test

[Mellanox] Add a configuration to delay start xcvrd for fast-reboot

---

device/dell/x86_64-dell_s6100_c2538-r0/plugins/eeprom.py

Make Dell S6100 eeprom plugin handle `bytearray` returned by TlvInfoDecoder 
Resolves #6081 
Decode the 'serial number' in bytearray type to string.
Execute `decode-syseeprom -s` and verify the output format. 
```
root@S6100-7758:/home/admin# decode-syseeprom -s
50YQG02
root@S6100-7758:/home/admin# show version
SONiC Software Version: SONiC.S6100_eeprom.0-dirty-20201202.144431
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 443f81f9
Build date: Wed Dec  2 09:58:05 UTC 2020
Built by: abalac@sonic-maa
Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
Serial Number: 50YQG02
Uptime: 16:57:24 up  1:34,  1 user,  load average: 2.25, 3.32, 3.28
``` …

DellEMC S6100: Handle bytearray in eeprom plugin

---

build_debian.sh
files/build_templates/sonic_debian_extension.j2
rules/ntp.dep
rules/ntp.mk
slave.mk
sonic-slave-buster/Dockerfile.j2
src/ntp/.gitignore
src/ntp/Makefile
src/ntp/patch/bug1970-UNLINK_EXPR_SLIST_empty_list.patch
src/ntp/patch/changelog
src/ntp/patch/series
src/ntp/patch/update_ENOBUFS_log_level.patch

- NTP Bug 1970 (UNLINK_EXPR_SLIST empty list) Fix
- ENOBUFS log message level set to WARN
- Fix audit message seen on console apparmor
extracted from https://github.com/Azure/sonic-buildimage/pull/6033

[ntp]: build ntp with various fixes

---

files/build_templates/sflow.service.j2

* Under certain conditions, the sFlow service can start before
interface configurations are sucessfully applied. This will
cause hsflowd to get a socket error.
This fix ensures all interface configurations are successfully
applied before the sFlow service (hsflowd) starts.
Signed-off-by: Garrick He <garrick_he@dell.com>
During testing we saw this error from hsflowd if interface configs were not successfully applied before hsflowd started.
```
ERR sflow#hsflowd: socket sendto error: Network is unreachable
```
no FLOW samples can be seen. This can be consistently reproducible if you force sFlow service to start before interface-config.service.
Ensure the sFlow service (hsflowd) doesn't start until interface configs are started. I use `hostcfgd.service` …

[sflow] Fix race-condition seen with mVRF configured

---

rules/frr.dep

The soinc-frr module has src/sonic-frr/frr submodule.  The FRR sub module dependency files are not added to the DPKG file tracking.  The patch includes the following.
1. Included the submodule dependency files
2. Removes the symbolic files.
Missing depdency files in the FRR module.
Added missing sub module files.
make target/debs/buster/frr_7.2.1-sonic-0_amd64.deb

Fix for missing dependency in frr module

---

dockers/docker-orchagent/Dockerfile.j2
files/initramfs-tools/modules.arm
files/initramfs-tools/union-mount.j2
platform/marvell-armhf/platform.conf
platform/marvell-armhf/sai.mk
platform/marvell-armhf/sonic-platform-et6448m/debian/install
platform/marvell-armhf/sonic-platform-et6448m/entropy.py
platform/marvell-armhf/sonic-platform-et6448m/et6448m_plt_setup.sh
platform/marvell-armhf/sonic-platform-et6448m/inband_mgmt.sh
sonic-slave-buster/Dockerfile.j2

Added Arm 32-bit arch build fixes
Added marvell armhf platform specific changes
Compiled for arm 32-bit sonic image and verified it

[platform][marvell] Arm 32-bit Arch support changes

---

Makefile.work

It is to simplify the Makefile.work to build slave docker images. The same code is used in multiple time in the Makefile.

Simplify the Makefile to build slave

---

files/image_config/ntp/ntp-config.service
files/image_config/ntp/ntp-config.sh

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
Make sure ntp-config service is executed before ntpd
Updated ntp-config service files to force dependency with ntp service. Also resolved circular dependency with --no-block flag. (needed as ntp-config service internally invokes systemd to restart ntp which in turn waits for ntp-config to complete)
Existing ntp pytest.
Adjusted the ordering of ntp-config service to run before ntp service. 
Avoided circular dependency due to above change with --no-block flag

NTP service ordering

---

dockers/docker-database/docker-database-init.sh
files/build_templates/docker_image_ctl.j2

The database-chassis service crash when the platform boots due to missing waits.
The /usr/bin/database.sh script tries to operate on a missing socket and fails.
It eventually ends up working though it needs fixing.
We now wait for the chassis database to be ready the same way we do database.
During boot the database-chassis is not reported as failed by `systemctl list-units`
Fix how database-chassis starts

[database-chassis] Fix how database-chassis starts

---

src/sonic-host-services/scripts/hostcfgd

- Kdump configurations stored and manipulated in ConfigDB are now processed
by hostcfgd and applied asynchronously
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
Allow Kdump configuration to be stored and manipulated in ConfigDB. Configuration
change events are handled by hostcfgd asynchronously.
Added ConfigDB change handlers for the KDUMP table in hostcfgd service
config kdump disable
config kdump enable
config kdump memory <xxx>
config kdump num-dumps <xxx>
Implement Kdump configuration handlers

Implement Kdump configuration handler

---

files/image_config/monit/process_checker
src/sonic-py-common/sonic_py_common/multi_asic.py

Why I did:
Enhanced the monit process checked to support multi-asic .
How I did:
- For given feature we get the host and network namespace instances it's processes should be running
based on it's scope (global/asic) and add it to expected set.
- From psutil we get number of running instances of the processes and add where it is running (host/network namespace) using "ip netns identify"  to the the actual set
- Difference between expected and actual set provides instances where the processes are not running
and will be logged as syslog message by monit
How I verify:
- O/P from Multi-asic platform
```
admin@str2-xxxxx-acs-3:/var/log$ /usr/bin/process_checker lldp python /usr/bin/lldpmgrd
'python /usr/bin/lldpmgrd' is not running in host
admin@str2-xxxx-acs-3:/var/log$ …
```

[multi-asic] Enhancing monit process checker for multi-asic.

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py

`show interface status` and `sfpshow eeprom` commands show not correct information about sfp status.
`show interface status` command result:
```
admin@sonic:~$ show interfaces status
Interface            Lanes    Speed    MTU    FEC        Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  -----------  ------  ------  -------  ---------------  ----------
Ethernet0          0,1,2,3     100G   9100    N/A    Ethernet0  routed    down       up              N/A         N/A
Ethernet8        8,9,10,11     100G   9100    N/A    Ethernet8  routed    down       up  QSFP28 or later         N/A
Ethernet16      16,17,18,19     100G   9100    N/A   Ethernet16  routed    down       up  QSFP28 or later         N/A …
```

[Barefoot]: fix unresolved SFP type on Newport/Montara

---

device/celestica/x86_64-cel_e1031-r0/installer.conf

To prevent Celestica E1031 from going to hang state abruptly
Preventing CPU sleep; setting idle cstate to 0
- [- ] 201811
Potential fix for Celestica E1031 hang issue

Potential fix for Celestica E1031 device hang

---

device/celestica/x86_64-cel_e1031-r0/sonic_platform/psu.py
device/celestica/x86_64-cel_seastone-r0/sonic_platform/psu.py

Fixes https://github.com/Azure/sonic-buildimage/issues/6126.
There is a bug in getting the path of voltage, current and power. The list object is directly converted to string to format the file path. As a result, ```read_txt_file``` will get ```None``` value and a ```WARNING``` will be recorded. This commit fix the issue.
Add a ```join``` to convert ```list``` to ```string```.
Verified on DX010, and no WARNING is seen after this update.
Fix incorrect file path for voltage, current and power.

[psu] Fix incorrect file path for voltage, current and power.

---

installer/x86_64/install.sh

Usually for a use case like networking - should not be configured to reach c6, the maximum used is c1e – due to the added latency getting in & out of states (bad for networking).
Following a recommendation by Intel, networking system should avoid getting in & out of states which introduce latency. The recommended state is c1e and no state change enabling.
In addition, c-state sole purpose is to save power and when inside a networking switch its really negligent being such a tiny consumer vs. the whole cluster.
Added a new argument to the grub cmdline to set c-states to 0.
* install 'linux-cpupower' tool.
* Run 'turbostat --debug' command
* Observe the c-states is constantly on …

[kernel] Change grub cmdline to set c-states to 0 for "Intel" CPUs

---

sonic-slave-buster/Dockerfile.j2
sonic-slave-jessie/Dockerfile.j2
sonic-slave-stretch/Dockerfile.j2

The maintainers of the m2crypto Python package pushed two new versions of the package to PyPI today, version 0.37.0 followed a few hours later by 0.37.1 (https://pypi.org/project/M2Crypto/0.37.1/#history). It appears as though these packages are failing to build/install properly in our image.
The problem was noticed in the Jessie container, where we were not previously explicitly installing the Debian m2crypto package. As part of this PR, I install m2crypto via pip in the Jessie container and pin down the version. I also modified the Stretch and Buster Dockerfiles to install the package vi pip in the same fashion for consistency.
Install m2crypto via pip and pin down version to 0.36.0, the last known working version.
Build an …

Pin version of m2crypto Python package in slave containers

---

Makefile

make init executed 3 times, which is unnecessary.
reorganize the makefile so that init only executed once.
make reset
make init

[makefile] re-organize makefile so init only execute once

---

files/initramfs-tools/modules
installer/x86_64/install.sh

In order to install a SONiC image on top of a NVMe SSD disc properly with ONIE we must configure it properly on the installer.sh script.
Added relevant data to 'installer.sh' script to support nvme.
Try to install a SONiC image including this PR on a system with a NVMe disc installed and a compatible ONIE.

[NVMe] Add NVMe SSD disc type support to installer.sh script

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/test_minigraph_case.py

Enable console mgmt feature for console device while parsing minigraph.
1. Introduced a list `console_device_types` which contains the device types that support console management feature
2. Inject `CONSOLE_SWITCH:console_mgmt` table with `enabled:yes` or `enabled:no`
Please notice that the `CONSOLE_SWTICH` conversion between minigraph to config_db is single direction only. There is no field indicate the `CONSOLE_SWTICH` table directly in minigraph.
Added unit tests and passed.
```
test_minigraph_console_mgmt_feature (tests.test_minigraph_case.TestCfgGenCaseInsensitive) ... ok
```
Enable console mgmt feature for console …

[sonic-config-engine/minigraph] Enable console mgmt feature for console device

---

build_debian.sh

Originally this line is used to mark all previously installed packages (deboostrap installed) as auto, so later if no other packages depend on anyone of them, it will be auto removed. Seems we gained little from this line, so let's remove it.
Check the build log after `sudo LANG=C chroot ./fsroot apt-get -y autoremove` and the removed packages are unchanged.
```
The following packages will be REMOVED:
binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-8 gcc-8 libasan5
libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libexpat1-dev
libgcc-8-dev libgomp1 libisl19 libitm1 liblsan0 libmpc3 libmpfr6 libmpx2
libquadmath0 libtsan0 libubsan1 linux-libc-dev
0 upgraded, 0 newly installed, 25 to remove and 5 not upgraded.
``` …

[hostimage] No need to mark packages as auto since all debootstrap installed packages are fundamental and will not be removed

---

files/image_config/logrotate/logrotate.d/rsyslog
files/image_config/rsyslog/rsyslog.d/00-sonic.conf

Move frr logs from syslog from the directory /var/log/quagga/*.log to  /var/log/frr/*.log
Updated the rsyslog config files.
In multi-asic, the following logs were seen in the respective files.
```
admin@str--acs-1:/var/log/frr$ ls -lrt
total 560
-rw-r----- 1 root adm   3793 Nov 29 01:59 zebra.log
-rw-r----- 1 root adm 561672 Nov 29 02:00 bgpd.log
bgpd.log
Nov 25 23:20:43.881961 str--acs-1 INFO bgp2#bgpd[67]: %ADJCHANGE: neighbor 2603:10e2:400:1::11(str--acs-1) in vrf default Up
Nov 25 23:20:43.882390 str--acs-1 INFO bgp4#bgpd[67]: %ADJCHANGE: neighbor 2603:10e2:400:1::12(str--acs-1) in vrf default Up
Nov 25 23:20:44.076345 str--acs-1 INFO bgp4#bgpd[67]: %ADJCHANGE: neighbor 2603:10e2:400:1::2(str--acs-1) in vrf default Up
Nov 25 …
```

Move frr logs from syslog to /var/log/frr/*.log

---

dockers/docker-database/Dockerfile.j2
dockers/docker-database/docker-database-init.sh
dockers/docker-database/flush_unused_database
dockers/docker-database/supervisord.conf.j2

* restoring each database  with all data before warmboot and then flush unused data in each instance, following the multiDB warmboot design at https://github.com/Azure/SONiC/blob/master/doc/database/multi_database_instances.md
* restore needs to be done in database docker since we need to know the database_config.json in new version
* copy all data rdb file into each instance restoration location andthen flush unused database
* other logic is the same as before
*  backing up database part is in another PR at sonic-utilities https://github.com/Azure/sonic-utilities/pull/1205, they depend on each other
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

[MultiDB] add mutidb warmboot support - restoring database

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml
src/sonic-config-engine/tests/test_minigraph_case.py

PEER_SWITCH table in config DB expects a standalone IP address w/o a prefix length

[minigraph.py]: Remove prefix length from peer switch loopback address

---

sonic-slave-buster/Dockerfile.j2

Install the 'wheel' package in sonic-slave-buster container to eliminate error messages like the following:
```
Running setup.py bdist_wheel for watchdog: started
Running setup.py bdist_wheel for watchdog: finished with status 'error'
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Qd3K08/watchdog/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-0AHpMe --python-tag cp27:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel'
Failed …
```

Install 'wheel' package in sonic-slave-buster

---

files/build_templates/sonic_debian_extension.j2

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
ntp-systemd-wrapper file from files/image_config/ntp was not getting picked up.
Added a line on sonic_debian_extension.j2 to copy over the file from files/image_config/ntp after installing the debian package.
cross check the file after loading a fresh image.

ntp-systemd-wrapper file is getting overwritten

---

device/nokia/armhf-nokia_ixs7215_52x-r0/plugins/led_control.py
platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py

- clean up corner condition when SDK reset and SFP's move
fix rare corner conditions
system leds -  in some conditions when CPSS has been reset the gpio driver led state it controls should be reset also
dom support in sfp - change reading of SFP+ dom capability from init routine to dynamic check - works any daemon
combinations of “sudo systemctl restart swss” “sudo systemctl restart syncd” and swapping SFP+ types around

IXS7215:fix for dynamic changes reading DOM and LED

---

src/isc-dhcp/patch/0011-dhcp-relay-Prevent-Buffer-Overrun.patch
src/isc-dhcp/patch/0011-relay-Prevent-Buffer-Overrun.patch
src/isc-dhcp/patch/series

The add/strip relay agent options do not take into account the buffer
length and so it is possible to overrun the buffer. The issue will
result in contents from previous packet being added to the current one.
closes #6052  
resolves #6052 

[relay]: Prevent Buffer Overrun Of Malformed DHCP Packet

---

build_debian.sh

It makes no difference during build.

[baseimage]: No need to `apt-mark manual`

---

platform/vs/docker-syncd-vs.mk

Since `DOCKER_SYNCD_VS` is no longer being used, the mount option does not properly mount the warmboot file directory. Fix the mount option so that the directory is properly mounted.
Use `DOCKER_SYNCD_BASE` instead of `DOCKER_SYNCD_VS`

[201811][syncd] Fix directory mount for vs syncd docker

---

src/sonic-device-data/src/sai.vs_profile

This PR adds the changes in https://github.com/Azure/sonic-buildimage/pull/6198 to 201811 branch to support warm-reboot image upgrade for kvm images.
The sai.profile file in kvm images overrides the warmboot file with path `/var/cache/sai_warmboot.bin`. Since the directory `/var/cache` is not mounted in syncd, it will be cleared in an image upgrade, the warm-reboot image upgrade will fail if the file is put in the directory.
Remove the path that overrides the default path. The warmboot file path will then be the default value `/var/warmboot/sai-warmboot.bin`. Since `/var/warmboot/` is mounted by `/host/warmboot/` in the host, it could survive an image upgrade.
**- Which release branch to backport (provide reason below if …

[201811][warm-reboot] Remove warmboot file path that overrides the default path

---

platform/marvell-armhf/sonic-platform-et6448m/entropy.py
platform/marvell-armhf/sonic-platform-et6448m/inband_mgmt.sh

**- What I did it**
In marvell_et644m platform scripts, I have added a check to confirm the file availability before accessing it.
Verified the modified scripts on marvell-armhf platform

[marvell][platform] Checking file presence before access

---

dockers/docker-config-engine-buster/Dockerfile.j2
dockers/docker-config-engine-stretch/Dockerfile.j2
files/build_templates/sonic_debian_extension.j2
rules/ntp.mk
sonic-slave-buster/Dockerfile.j2
sonic-slave-stretch/Dockerfile.j2

libxslt-dev and libz-dev are dependencies for lxml==4.6.1 which is required for pyangbind==0.8.1
verified in armhf and arm64 archs

[sonic-config-engine] Adding dependent pkgs needed for arm compilation

---

files/image_config/kdump/kdump-tools

The default /etc/default/kdump-tools file provided by the kdump-tools
package doesn't set a value for KDUMP_CMDLINE_APPEND.
The default kdump command line arguments need to be set in order
to extend them to use additional arguments required for SONiC
platforms.
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
Fixes https://github.com/Azure/sonic-buildimage/pull/6113
kdump-tools.service is not starting as the kdump specific command line arguments are not passed to the crash kernel
Specify the default KDUMP_CMDLINE_APPEND value as part of SONiC specific kdump configuration file.
config kdump enable
reboot
echo c > /proc/sysrq-trigger
show kdump files
**- Which release branch to backport (provide reason below if …

kdump: Add default kdump command line arguments

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml

In some minigraph deployments, the `type` attribute in the `<Device>` tag (`<PngDec> -> <Devices>`) sometimes includes the XML namespace (e.g. instead of "BackEndLeafRouter" the value is "a:BackEndLeafRouter").
When parsing devices, prefer the `<ElementType>` tag usually found inside of `<Device>`, and use the `type` attribute as a fallback in case it is not found.
Run the sonic-config-engine tests

[minigraph.py]: Prefer parsing device type from <ElementType> 

---

dockers/docker-orchagent/Dockerfile.j2
platform/vs/docker-sonic-vs/Dockerfile.j2

[docker-vs][docker-orchagent] install python3 dependent packages for restore_neighbors.py
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
convert restore_neighbor.py to support python3 as python2 is EOL.  See: https://github.com/Azure/sonic-swss/pull/1542
Install the necessary python3 dependent packages.
swss vs tests and HW test.

[docker-vs][docker-orchagent] install python3 dependent packages for restore_neighbors.py

---

build_debian.sh
files/build_templates/sonic_debian_extension.j2

Install the 'wheel' package in host OS (along with python3 and python3-distutils which are also needed for building some Python packages) to eliminate error messages like the following:
```
Running setup.py bdist_wheel for watchdog: started
Running setup.py bdist_wheel for watchdog: finished with status 'error'
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Qd3K08/watchdog/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-0AHpMe --python-tag cp27:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command …
```

Install 'wheel' package in host OS; upgrade pip and setuptools

---

files/build_templates/snmp.timer

Fixes #5663 
It's currently possible for the SNMP timer to conflict with `config reload` (specifically if the timer triggers while `config reload` is stopping the SWSS service). `config reload` triggers SWSS to shutdown, which causes SNMP to shutdown, which conflicts with the SNMP timer causing SNMP to startup. See the linked issue for more details.
Including the `After` ordering dependency forces the SNMP timer to wait until SWSS finishes stopping, preventing the conflict. If there is an ordering dependency between two units (e.g. one unit is ordered `After` another), if one unit is shutting down while the other is starting up, the shutdown will always be ordered before the startup. In this case, …

[build_templates]: Start SNMP timer after SWSS service

---

device/arista/x86_64-arista_7050_qx32/system_health_monitoring_config.json
device/arista/x86_64-arista_7050_qx32s/system_health_monitoring_config.json
device/arista/x86_64-arista_7050cx3_32s/system_health_monitoring_config.json
device/arista/x86_64-arista_7060_cx32s/system_health_monitoring_config.json
device/arista/x86_64-arista_7060cx2_32s/system_health_monitoring_config.json
device/arista/x86_64-arista_7060dx4_32/system_health_monitoring_config.json
device/arista/x86_64-arista_7060px4_32/system_health_monitoring_config.json
device/arista/x86_64-arista_7170_32c/system_health_monitoring_config.json
device/arista/x86_64-arista_7170_32cd/system_health_monitoring_config.json
device/arista/x86_64-arista_7170_64c/system_health_monitoring_config.json
device/arista/x86_64-arista_7260cx3_64/system_health_monitoring_config.json
device/arista/x86_64-arista_7280cr3_32d4/system_health_monitoring_config.json
device/arista/x86_64-arista_7280cr3_32p4/system_health_monitoring_config.json
device/arista/x86_64-arista_7800_sup/system_health_monitoring_config.json
device/arista/x86_64-arista_7800r3_48cq2_lc/system_health_monitoring_config.json
device/arista/x86_64-arista_7800r3_48cqm2_lc/system_health_monitoring_config.json
device/arista/x86_64-arista_common/system_health_monitoring_config.json

Prevent system-healthd from service from failing at boot time due to missing configuration.
Also adds basic support for healthd.
The following caveat exists with this placeholder configuration:
- No PSU monitoring (sensors/fans)
- No ASIC temperature monitoring
Added `system_health_monitoring_config.json` to all Arista platforms.
Check `systemctl status system-health` after boot.
No healthd errors in `/var/log/syslog`.
Verify that the output of `journalctl -u system-health` is sane.
Add placeholder system-health configuration for all Arista platforms

[Arista] Add placeholder system-health configuration for all platforms

---

platform/mellanox/mlnx-sai.mk

Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>
To add VNET route diff tool (SAI/SDK part) to 201911 release
Updated SAI submodule
Build an image and verify that "vnet route diff" script is available in syncd docker
[Mellanox] Update SAI submodule

[Mellanox] Update SAI submodule

---

src/sonic-host-services/scripts/determine-reboot-cause
src/sonic-host-services/tests/determine-reboot-cause_test.py
src/system-health/scripts/healthd

Fix errors seen in VS image after reboot - both determine-reboot-cause and healtd fail with errors shown in syslog.
Error seen during `determine-reboot-cause`:
```
Dec  4 11:09:03.985425 vlab-01 INFO determine-reboot-cause: Starting up...
Dec  4 11:09:03.985661 vlab-01 INFO determine-reboot-cause: /proc/cmdline indicates reboot type: warm-reboot
Dec  4 11:09:03.985817 vlab-01 WARNING determine-reboot-cause: sonic_platform package not installed. Unable to detect hardware reboot causes.
Dec  4 11:09:03.986717 vlab-01 INFO determine-reboot-cause[512]: Traceback (most recent call last):
Dec  4 11:09:03.986847 vlab-01 INFO determine-reboot-cause[512]:   File "/usr/local/bin/determine-reboot-cause", line 236, in <module>
Dec  4 11:09:03.986926 vlab-01 INFO …
```

Fix post-reboot errors in platforms without sonic_platform package

---

src/sonic-host-services/scripts/hostcfgd

The change is done to make sure the system initialization is done before starting the hostcfgd service.
use the command` systemctl is-system-running --wait ` to wait till system has finished booting up
Checkout journctl command output if the hostcfgd is waiting
<pre>
admin@vlab-01:~$ sudo journalctl -u hostcfgd                                                                                                                                                                                 -- Logs begin at Thu 2020-12-17 01:06:59 UTC, end at Thu 2020-12-17 01:20:52 UTC. -- …

[hostcfgd]: wait  till system initialization is done before starting hostcfgd

---

sonic-slave-buster/Dockerfile.j2

Doxygen https://github.com/opencomputeproject/SAI/blob/master/Makefile#L23
SAI submodule in libsairedis builds meta using doxygen
Debian buster doxygen for ARMHF (32bit) fails to recursively
read subdirectories to parse the header files.
This issue is described at https://bugs.launchpad.net/qemu/+bug/1805913
The solution to this is to add FILE_OFFSET_BITS to 64 as desribed at
https://bugzilla.kernel.org/show_bug.cgi?id=205957
This issue is not seen in stretch which has glibc 2.24 and is seen only
on buster which has glibc version 2.28. The above bugs needs to be
tracked to get rid of this PR change, once debian moves forward to next
version.
This PR addresses the readdir() issue for 32bit arch, by adding
cflag _FILE_OFFSET_BITS=64 through cmake definition to the doxygen
source downloaded …

[slave-buster] Armhf sairedis build fix

---

src/openssh/Makefile

The openssh build fails to retrieve dependent debian packages when operating
behind a proxy server.
Fix build break when building from behind a proxy server.
Specify coordinates of proxy server when installing dependent packages.
Build from behind a proxy server.

openssh: Fix build break when using http proxy

---

build_debian.sh
files/image_config/ntp/ntp-apparmor

Certain platform specific packages sonic-platform-xyz, installs files onto rootfs, which would be placed on read-write mount path on /host/image-name/rw/...
when ntpd starts it tries to do read access on /usr/bin /usr/sbin/ /usr/local/bin , which inturn links further to the read-write mount path also.
Where ntpd would get below Apparmor Warning message
LOG:-
audit: type=1400 audit(1606226503.240:21): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/image-HEAD-dirty-20201111.173951/rw/usr/local/bin/" pid=3733 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit: type=1400 audit(1606226503.240:22): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/image-HEAD-dirty-20201111.173951/rw/usr/sbin/" pid=3733 comm="ntpd" requested_mask="r" …

[ntp][apparmor] Allow apparmor read permission for ntpd under rw mount path of rootfs

---

platform/broadcom/sai.mk

In SAI 4.2.1.5 there is a Warm-reboot issue discovered by nightly test (https://github.com/Azure/sonic-buildimage/issues/6069)
It appears that this issue was due to the new SAI added additional checking (FALSE Positive) that rejected the attempt to delete the hotif IP2ME trap.  BRCM case was raised by DELL (CS00011466224) and a fix was provided by BRCM.
With the new libsai debian with the patch fix warm-reboot no longer encounter this hostif IP2ME trap delete failure and warm-reboot completes successfully.
Moving BRCM SAI 4.2.1.5-6 to 4.2.1.5-7 to pick up fix WARM BOOT "Removing the ip2me trap entry returns error & crash Orchagent (CS00011466224)"
Fixes #https://github.com/Azure/sonic-buildimage/issues/6069

BRCM SAI 4.2.1.5-7 fix WARM BOOT "Removing the ip2me trap entry returns error & crash Orchagent"

---

files/image_config/hostcfgd/hostcfgd

The change is done to make sure the system initialization is done before starting the hostcfgd  sets the feature states.
This is port of the PR https://github.com/Azure/sonic-buildimage/pull/6232. 
Since the systemctl version in 201911 doesnt support `--wait`. 
Added a function to check the output of ` systemctl is-system-running ` every second, till the command system is done booting up.
For now this change is only applicable to multi asic platforms based on the testing  this change will be extended to all platforms in the future PR.
Checkout journctl command output to see 
<pre>
admin@sonic:~$ sudo journalctl -u hostcfgd
-- Logs begin at Thu 2020-12-17 …

[201911][hostcfgd]:wait updating the feature table till system init is done

---

src/sonic-build-hooks/Makefile

In some build machine, it may be not able to run as root during the build, only has root authority in docker containers.
Remove the sudo in Makefile
cd src/sonic-build-hooks
make all

Remove unnecessary sudo authority in build Makefile

---

files/image_config/config-setup/config-setup

Why/What I did:
To copy telemetry certificate during image upgrade from previous image to new image
Closing Issue https://github.com/Azure/sonic-buildimage/issues/5955.
How I did:
Added "telemetry directory" to the list of files/directory that gest copied when new images booted.
How I verify:
- Verified Telemetry Certificate are restored from 201811 to 201911
- Verified Telemetry Certificate are restored from 201911 to 201911

Telemetry Certificate Copy Across Image Upgrade.

---

src/sonic-yang-models/tests/yang_model_tests/yangTest.json
src/sonic-yang-models/yang-models/sonic-flex_counter.yang

DPB fall with log errors:
```
Dec 10 16:30:38.260263 sonic ERR ConfigMgmt: Data Loading Failed#012All Keys are not parsed in FLEX_COUNTER_TABLE#012dict_keys(['BUFFER_POOL_WATERMARK'])
Dec 10 16:30:38.260560 sonic ERR ConfigMgmt: ConfigMgmt Class creation failed
```

[DPB] update flex counter yang model, fix BUFFER_POOL_WATERMARK

---

src/sonic-config-engine/minigraph.py

Latest master image crashes when loading minigraph
Fixing #6265 
Avoid converting 'None' to ipaddress.
On a system crashing with the issue, manually patch minigraph.py with the change in PR and load minigraph succeeded.

[minigraph parse] avoid crash when peer switch lo address is not available

---

files/Aboot/boot0.j2

To limit IO and space usage on the flash device the `boot0` script makes sure the SWI is in memory.
Because SONiC maps `/tmp` on the flash, some logic is required to make sure of it.
However it is possible for some provisioning mechanism to already download the swi in a memory file system.
This was not properly handled by the `boot0` script.
It now properly detect if the image is on a `tmpfs` or a `ramfs` and keep it there if that is the case.
Check the filesystem on which the SWI pointed by `swipath` lies.
If this filesystem is a `ramfs` or a `tmpfs` the `move_swi_to_tmpfs` becomes a no-op.
Made sure the cleanup logic would not behave unexpectedly.
In SONiC:
1) Download the swi under `/tmp` and makes sure it gets moved to …

[Arista] Better handle arbitrary tmpfs in boot0

---

platform/mellanox/mlnx-platform-api/sonic_platform/led.py

Fix return False if unsupported color request.
Return 'False' when unsupported led color is requested, preventing an exception.
Try to set PSU LED color to unsupported color with Mellanox platform device.

[Mellanox] PSU led platform API fixes

---

files/build_templates/init_cfg.json.j2

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom>
- What I did
Added support for snat, dnat and ipmc resources under CRM module.
- How I did it
New feature NAT adds new resources snat_enty and dnat_entry that needs to be monitored. ipmc_entry tracks IP multicast resources used by switch.
sonic-utilities tests and crm spytest
- Associated PRs
Azure/sonic-swss#1511
Azure/sonic-utilities/pull/1258

Add support for snat, dnat and ipmc crm resources

---

src/sonic-bgpcfgd/setup.py
src/sonic-config-engine/setup.py

importlib-resources v4.0.0 was released today (2020-12-23) and drops support for Python 2. This caused the sonic-config-engine Python 2 wheel build to fail.
Reference: https://pypi.org/project/importlib-resources/
Example failure:
```
16:23:36    File "/sonic/src/sonic-config-engine/tests/../sonic-cfggen", line 33, in <module>
16:23:36      import netaddr
16:23:36    File "/sonic/src/sonic-config-engine/.eggs/netaddr-0.8.0-py2.7.egg/netaddr/__init__.py", line 18, in <module>
16:23:36      from netaddr.core import (AddrConversionError, AddrFormatError,
16:23:36    File "/sonic/src/sonic-config-engine/.eggs/netaddr-0.8.0-py2.7.egg/netaddr/core.py", line 11, in <module>
16:23:36      from netaddr.compat import _callable, _iter_dict_keys
16:23:36    File …
```

[sonic-config-engine] Pin 'importlib-resources' package to v3.3.1 for Python 2

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init

Remove the unused codes addressed in #5891 on Dx010 platform.
Update the DX1010 init script.
Boot the DX010 with the updated init script and check for all I2C device can be inited successfully.
Remove unused pca954x device init from DX010 init script 

[platform/dx010] Remove unused pca9541 device init line

---

device/barefoot/x86_64-accton_as9516_32d-r0/syncd.conf

For this platform, it is expected to work on any Y profile. but after the latest changes, the first Y profile is always used.
To be able to set another Y profile
Extend logic to check if the Y profile is already used

[barefoot] Fix y_profile_set to not reset link

---

build_debian.sh

Clean up qemu-arm-static bin after collecting post-versions info
scripts/collect_host_image_version_files.sh fails with below error:
+ scripts/collect_host_image_version_files.sh target ./fsroot
/usr/sbin/chroot: failed to run command 'post_run_buildinfo': No such file or directory
/bin/cp: cannot stat './fsroot/usr/local/share/buildinfo/post-versions': No such file or directory
Issues is because qemu-arm-static is removed before this step. So, I moved the cleanup step to the end.
Compiled and verified for marvell-armhf
**- A picture of a cute animal (not …

[arm] [build_debian] arm build fix

---

Makefile

disable sonic-slave jessie by default
set NOJESSIE=1
run make sonic-slave-bash and verify jessie docker is skipped.

[build]: disable build sonic-slave-jessie by default

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.install
platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.postinst
platform/broadcom/sonic-platform-modules-cel/haliburton/scripts/cpu_wdt
platform/broadcom/sonic-platform-modules-cel/haliburton/systemd/cpu_wdt.service

- Haliburton needed watchdog daemon to monitor the basic health of a machine. If something goes wrong, such as a crashing program overloading the CPU, or no more free memory on the system, watchdog can safely reboot the machine,
- Implement the cpu _wdt script to enable watchdog timer with keepalive messaging.
- Run cpu _wdt with a longer timeout set than a keep alive interval configuration.
- Test log : [cpu_wdt_1.0-201811.log](https://github.com/Azure/sonic-buildimage/files/5741552/cpu_wdt_1.0-201811.log)

[platform/cel-haliburton]: add watchdog service

---

Makefile.work
rules/config

- add config option ENABLE_DOCKER_BASE_PULL to pull sonic-slave docker from registry
- use REGISTRY_PORT, REGISTRY_SERVER to specify docker registry
add docker pull command before docker build
checked following option and make sure the the behavior work as expected
- ENABLE_DOCKER_BASE_PULL=y BLDENV=buster make -f Makefile.work sonic-slave-build
- BLDENV=buster make -f Makefile.work sonic-slave-build
- change rule/config and check

[build]: add option to pull sonic-slave docker from registry

---

rules/sonic-utilities.mk

submodule sonic-utilities in sonic-buildimage has not been updated for a while and there were many fixes needed to be picked up to ease debug/development in master branch.
Here are the list of changes that this update will bring in:
1.   Added show ip/v6 route summary support for multi-asic platform (#1320)
2.   [pytest][qos][config] Added pytests for "config qos reload" commands (#1266)
3.   [CRM]Add support for snat, dnat and ipmc crm resources (#1258)
4.   Retain fgnhg state db table entry during warm reboot (#1315)
5.   Fix exception handling in python3 (#1324)
6.   [config] Add unit tests for 'config interface breakout' command (#1223)
7.   [dropcounters] Fix clear for non-root users (#1253)
8.   Kubernetes support commands update (#1133)
9. VXLAN config and show …

[sonic-utilities] Update sonic-utilities submodule to pick set of new fixes 

---

files/build_templates/init_cfg.json.j2

swss/teamd/syncd services were changed to always enabled
in commit fad481edc1796126bf92c9b9230303401b515364 as a workaround
for not letting hostcfgd start service during the bootup process.
commit 317a4b34106cd84054194ad2255a85978471c028 introduce
wait till full system bootup before updating feature states in hostcfgd.
Thus, workaround introduced in commit fad481ed can be removed
change teamd/swss/syncd to enabled state.
check if hostcfgd update feature state after system fully bootup.

[init_cfg]: allow enable/disable swss/teamd/syncd services

---

dockers/docker-fpm-frr/frr/frr.conf.j2
dockers/docker-fpm-frr/frr/staticd/staticd.conf.j2
dockers/docker-fpm-frr/frr/staticd/staticd.loopback_route.conf.j2
src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/staticd/staticd.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/staticd/staticd.conf.json
src/sonic-bgpcfgd/tests/data/sonic-cfggen/staticd/staticd.loopback_route.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/staticd/staticd.loopback_route.conf.json
src/sonic-bgpcfgd/tests/test_sonic-cfggen.py
src/sonic-config-engine/tests/sample_output/py2/frr.conf
src/sonic-config-engine/tests/sample_output/py2/staticd_frr.conf
src/sonic-config-engine/tests/sample_output/py3/frr.conf
src/sonic-config-engine/tests/sample_output/py3/staticd_frr.conf
src/sonic-config-engine/tests/test_frr.py

frr does not advertise route if local route is not reachable, as a result
loopback route /64 is not advertised to the neighbors. Add static route
allows frr to advertise the route to its peers
- change staticd template
- add swss orchagent code to ignore the loopback route
in t0 topology, check the neighbor advertisement
also checked warm reboot

[docker-frr]: add static ipv6 loopback route for bgp to advertise

---

build_debian.sh
files/build_templates/sonic_debian_extension.j2

As part of migrating the SONiC codebase from Python 2 to Python 3
- No longer install Python 2 packages in host:
- libpython2.7-dev
- docker
- ipaddress
- netifaces
- azure-storage
- watchdog
- futures
- Install Python 3 versions of the following packages in host:
- docker
- azure-storage
- watchdog
- redis
- swsssdk (install unconditionally)

No longer install some unnecessary Python 2 packages in host

---

Makefile.work

use bash -t test flag to check if input device is tty or not
TERM variable is not reliable way to detect input device is tty or not.
use bash -t test flag to check if input device is tty or not
use bash -t test flag to check if input device is tty or not
test under both tty and non-tty env

[build]: setup -t option in docker run correctly

---

Makefile.work

sonic-slave tag only allows all lower case. In case the user
name is mixed case, we need to change user name to all lower case.
https://stackoverflow.com/questions/36858837/lowercase-images-names-in-docker
change user name to all lower case
test username with mixed case.

[build]: change user name to lower case when used in sonic-slave tag

---

build_debian.sh

Depending on the performance characteristics of a given hardware platform, it's possible to exceed the default 120 second kernel timeout during I/O intensive operations like image installation. This can cause a kernel panic like so:
kernel:[  852.441781] Kernel panic - not syncing: hung_task: blocked tasks
If this happens during image installation, it's possible for the install to become corrupted and leave the device in an unreachable state that requires a power cycle to resolve. This risk increases as image size continues to increase. So, we need to increase the timeout so that we don't encounter kernel panics on devices with lower disk throughput.

[sysctl] Increase hung_task_timeout_secs to 300

---

platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/eeprom.py

Make EEPROM platform APIs Python3 compliant in Nokia platform.
Handle bytearray type returned by read_eeprom and read_eeprom_bytes methods.
Boot Nokia ixs7215 and verify PMON docker running and show platform syseeprom 

[Nokia]: EEPROM platform API Python3 compliance changes

---

src/sonic-host-services/scripts/determine-reboot-cause
src/sonic-host-services/tests/determine-reboot-cause_test.py

Fix unit tests in `determine-reboot-cause` to skip calling platform module libraries in unit test scope.
MELLANOX build is failing for the recent PRs. The errors are due to platform library being invoked in a unit test for `determine-reboot-cause` script.
```
[2020-12-30T11:03:13.516Z] tests/determine-reboot-cause_test.py:102: 
[2020-12-30T11:03:13.516Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2020-12-30T11:03:13.516Z] scripts/determine-reboot-cause:107: in find_hardware_reboot_cause
[2020-12-30T11:03:13.516Z]     platform  = sonic_platform.platform.Platform()
[2020-12-30T11:03:13.516Z] /usr/local/lib/python3.7/dist-packages/sonic_platform/platform.py:21: in __init__
[2020-12-30T11:03:13.516Z] …
```

[determine-reboot-cause] Skip invoking platform code for unit tests for hardware_reboot_cause

---

dockers/docker-fpm-frr/start.sh

There is no /usr/share/sonic/templates/supervisord/ folder
and no supervisord.conf.j2 template.
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
To fix an issue that frr config files are not generated.
Remove non-existent template that caused sonic-cfggen to fail
Install image, verify /etc/sonic/frr/ has config files generated.

[fpm-frr] fix start.sh template paths

---

platform/broadcom/sonic-platform-modules-accton/as5712-54x/utils/accton_as5712_util.py
platform/broadcom/sonic-platform-modules-accton/as5812-54t/utils/accton_as5812_util.py
platform/broadcom/sonic-platform-modules-accton/as5812-54x/utils/accton_as5812_util.py
platform/broadcom/sonic-platform-modules-accton/as5835-54t/utils/accton_as5835_54t_util.py
platform/broadcom/sonic-platform-modules-accton/as5835-54x/utils/accton_as5835_54x_util.py
platform/broadcom/sonic-platform-modules-accton/as6712-32x/utils/accton_as6712_util.py
platform/broadcom/sonic-platform-modules-accton/as7312-54x/utils/accton_as7312_util.py
platform/broadcom/sonic-platform-modules-accton/as7312-54xs/utils/accton_as7312_util.py
platform/broadcom/sonic-platform-modules-accton/as7315-27xb/utils/accton_as7315_util.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/utils/accton_as7326_util.py
platform/broadcom/sonic-platform-modules-accton/as7712-32x/utils/accton_as7712_util.py
platform/broadcom/sonic-platform-modules-accton/as7716-32x/utils/accton_as7716_util.py
platform/broadcom/sonic-platform-modules-accton/as7716-32xb/utils/accton_as7716_32xb_util.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/utils/accton_as7726_32x_util.py
platform/broadcom/sonic-platform-modules-accton/as7816-64x/utils/accton_as7816_util.py
platform/broadcom/sonic-platform-modules-accton/as9716-32d/utils/accton_as9716_32d_util.py
platform/broadcom/sonic-platform-modules-accton/minipack/utils/accton_minipack_util.py

Accton util applies lsmod to check if drivers are installed.
But lsmod may return error on startup and skip module installation.
Signed-off-by: Brandon Chuang <brandon_chuang@edge-core.com>
- Why I did it
Reported that sometimes the peripherals cannot be polled.
- How I did it
It's found that lsmod command may failed on startup, the accton util misjudges that drivers have been installed.
The change here is not to apply lsmod to poll installed drivers.
The bug can be probably replicated during several time of reboot.
Replace with new script and reboot 100 times.
Drivers are all well installed on these 100 reboot.
- Which release branch to backport (provide reason below if selected)
- Description for the changelog

[device/accton] Fix accton driver not been installed

---

build_debian.sh
scripts/collect_host_image_version_files.sh

$ ls -ld target/versions/host-image/
drwxr-xr-x 4 **root root** 4096 Jan  1 11:16 target/versions/host-image/
Unable to run "git clean -ffdx" and "git reset --hard 
Access to the path '/agent/_work/1/s/target/versions/host-image/pre-versions/versions-deb-buster-amd64' is denied.)) (Access to the path '/agent/_work/1/s/target/versions/host-image/pre-versions/versions-deb-buster-amd64' is denied.
Relative Change: https://github.com/Azure/sonic-buildimage/pull/6289/files

Fix the host image version path permission issue

---

src/sonic-py-common/sonic_py_common/device_info.py

Added an API to get the file path containing SONiC version so that the API can be mocked during unit tests.
Added the API.
Manual verification.
```
Last login: Mon Dec 28 18:32:34 2020 from 100.127.20.23
admin@str-s6000-acs-9:~$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
>>> from sonic_py_common import device_info                                                                                                                                           
>>> device_info.get_sonic_version_file()
'/etc/sonic/sonic_version.yml'
>>> 
```
**- Description for the …

[sonic-py-common] Added an API to get file path containing SONiC version

---

platform/broadcom/sai.mk

the control file version is 4.2.1.5-7
sonic$ sudo dpkg -i target/debs/buster/libsaibcm-dev_4.2.1.5-8_amd64.deb
(Reading database ... 175880 files and directories currently installed.)
Preparing to unpack .../libsaibcm-dev_4.2.1.5-8_amd64.deb ...
Unpacking libsaibcm-dev (4.2.1.5-7) over (4.2.1.5-7) ...
Setting up libsaibcm-dev (4.2.1.5-7) ...
lgh@491d842369cf:/sonic$ sudo dpkg -i target/debs/buster/libsaibcm_4.2.1.5-8_amd64.deb
(Reading database ... 175880 files and directories currently installed.)
Preparing to unpack .../libsaibcm_4.2.1.5-8_amd64.deb ...
Unpacking libsaibcm (4.2.1.5-7) over (4.2.1.5-7) ...
Setting up libsaibcm (4.2.1.5-7) ...
Processing triggers for libc-bin (2.28-10) ...
match the filename version and the …

[broadcom]: match the brcm sai filename version to control file version

---

src/libyang1/Makefile

- Why I did it
In the emulated armhf environment, the function readdir()returns NULL on a ext4 file system directory. When running the libyang1 test cases, it will require to load the plugins from the files (such as metadata.so), because the readdir() is failing, the plugins can’t be loaded in the emulated armhf environment, so it causes libyang1 test error. This error is a combination of the following reasons.
• Emulation of a 32-bit target from a 64-bit host –> qemu from x86_64 to armhf
• Glibc version > 2.27 – Debian buster is using glibc 2.28
- How I did it
Enabled large file support by setting _FILE_OFFSET_BITS=64 for libyang1.
Compiled and verified libyang1 unit tests in arm32
**- Which release branch …

[libyang1] Adding LFS support for arm32

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py

To fix syntax error during xcvrd start in the latest SONiC
```
root@sonic:/# python3 /usr/local/bin/xcvrd
File "/usr/local/bin/xcvrd", line 5, in <module>
from xcvrd.xcvrd import main
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 24, in <module>
from .xcvrd_utilities import y_cable_helper
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd_utilities/y_cable_helper.py", line 11, in <module>
from sonic_y_cable import y_cable
File "/usr/local/lib/python3.7/dist-packages/sonic_y_cable/y_cable.py", line 10, in <module>
import sonic_platform.platform
File "/usr/local/lib/python3.7/dist-packages/sonic_platform/__init__.py", line 2, in <module>
from . import platform
File …
```

[BFN] Convert platform modules to python 3

---

platform/broadcom/sonic-platform-modules-dell/s5232f/systemd/platform-modules-s5232f.service
platform/broadcom/sonic-platform-modules-dell/s6000/systemd/platform-modules-s6000.service
platform/broadcom/sonic-platform-modules-dell/s6100/systemd/platform-modules-s6100.service
platform/broadcom/sonic-platform-modules-dell/z9100/systemd/platform-modules-z9100.service
platform/broadcom/sonic-platform-modules-dell/z9264f/systemd/platform-modules-z9264f.service
platform/broadcom/sonic-platform-modules-dell/z9332f/systemd/platform-modules-z9332f.service

To ensure platform initialization is complete before `determine-reboot-cause.service` executes. 
resolves #6082 
Added a systemd rule to make platform-modules service as a prerequisite for determine-reboot-cause service. 
Verify determine-reboot-cause.service is executed and reset reason is updated.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/5753901/UT_logs.txt)
[DellEMC] Add platform-modules as prerequisite for determine-reboot-cause

[DellEMC] Add platform-modules as prerequisite for determine-reboot-cause

---

platform/vs/docker-sonic-vs/Dockerfile.j2

combine multiple same operation into one operation to reduce
the build steps. this is to avoid max depth exceeded issue
in the build.
combine copy, apt_dpkg operations into one step.
build docker-sonic-vs.
steps reduce from 131 to 75.

[docker-sonic-vs]: reduce the build steps for docker-sonic-vs

---

src/lldpd/patch/0010-Ported-fix-for-length-exceeded-from-lldp-community.patch
src/lldpd/patch/0011-fix-med-location-len.patch
src/lldpd/patch/series

The details are as follows:
1. 0010-Ported-fix-for-length-exceeded-from-lldp-community.patch
Ported fix lldpd/lldpd#408 from LLDP community.
lib: remove limit on system description length
The limit was introduced in 9c49ced while fixing a memory leak.
The state data is used to ensure we don't interleave operations. We
need to handle the case where the value is truncated because it is
larger than the allocated size.
Fix #408.
2. 0011-fix-med-location-len.patch
Ported fix lldpd/lldpd#422 from community.
lib: fix LLDP-MED location parsing in liblldpctl
Some bounds were not checked correctly when parsing LLDP-MED civic
location fields. This triggers out-of-bound reads (no write) in
lldpcli, ultimately leading to a crash.
Fix #420
Signed-off-by: sudhanshukumar22 <sudhanshu.kumar@broadcom.com> …

lldp defect miscellaneous fixes as patches 

---

scripts/prepare_slave_container_buildinfo.sh
scripts/versions_manager.py

Install the latest version of the sonic build hooks in slave container
Fix version empty issue when generating version files.
Checkout the latest master branch, without any exception after applying the fix.
make SONIC_CONFIG_BUILD_JOBS=1  INSTALL_DEBUG_TOOLS=y target/sonic-aboot-broadcom.swi
make freeze FREEZE_VERSION_OPTIONS=-r

Install the latest version of the sonic build hooks in slave container

---

files/image_config/config-setup/config-setup

Issue : After first bootup, the FEATURE table is not present in CONFIG_DB
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*FEAT\*
(With Fix from PR - https://github.com/Azure/sonic-utilities/pull/1232)
root@sonic:/home/admin# config feature state nat enabled
Feature 'nat' doesn't exist
And then, If I do 'cold reboot' or 'config reload', the FEATURE table gets added to CONFIG_DB.
After reboot/config-reload,
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*FEAT\*
FEATURE|nat
FEATURE|bgp
FEATURE|syncd
FEATURE|sflow
FEATURE|telemetry
FEATURE|snmp
FEATURE|pmon
FEATURE|swss
FEATURE|mgmt-framework
FEATURE|database
FEATURE|radv
FEATURE|lldp
FEATURE|teamd
FEATURE|dhcp_relay
Rootcause:
While first boot up, the …

After first bootup, the FEATURE table is not present in CONFIG_DB

---

src/sonic-host-services/scripts/determine-reboot-cause

Reboot cause prints "Non-Hardware" instead of showing software reboot cause.
```
admin@vlab-01:~$ show reboot-cause
Non-Hardware (N/A)
admin@vlab-01:~$
```
Fixed the handling for Non Hardware reboot cause. Ignore if `Non-Hardware` is present in the hardware_reboot_cause output.
This will make software reboot cause to be taken as the effective reboot-cause.
With fix, the hardware reboot cause is ignored (if it is non hw):
```
admin@vlab-01:~$ show reboot-cause 
User issued 'warm-reboot' command [User: admin, Time: Mon 04 Jan 2021 05:20:49 PM UTC]
admin@vlab-01:~$ 
``` …

[determine-reboot-cause] Ignore non-hardware reboot cause

---

device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/buffers.json.j2
device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/qos.json.j2
platform/marvell-armhf/rules.mk
slave.mk

To enable Telemetry on armhf architecture and provide required qos/buffers files that 
config qos reload --no-dynamic-buffer now requires for the Nokia ixs7215 
Removed the hardcoded disable of Telemetry in slave.mk for armhf architecture and provided 
required qos/buffers files for the config qos reload code to succeed as stubs since they do not 
generate buffer settings to Marvell SAI for this MO based role
config load_minigraph -y succeeds for OC testing 

[Nokia]: Enable Telemetry for armhf and provide required qos files

---

platform/broadcom/sai.mk

Update the version of the SAI debian package to reflect the actual version 3.7.5.2-1
Updated the changelog in the SAI 3.7 package and build the image 
Check the debian package version 
```
root@str--acs-1:/# dpkg -l| grep libsaibcm
ii  libsaibcm    3.7.5.2-1      amd64        Switch Abstraction Interface sdk based on Broadcom SAI
```

[SAI 3.7] Update the SAI version in the bcm SAI debian package.

---

platform/broadcom/sai.mk

Starting from build (master) 176 the warm reboot on BRCM Platform started to experience syncd crash.  Upon further debug by Ying it was determined that the crash was related to the following new change:
[Dynamic buffer calc]  Support dynamic buffer calculation (#1338)
Ying also debugged further and found The crash was caused by buffer pool profile setting operation SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH 
A case has filed with BRCM while a potential fix was tried by Ying that seems to have addressed this issue and we are making this change available in master branch so that it will allow further feature validation/testing especially in the warm reboot area.
Once an official fix is provided by BRCM, we will then remove this in house fix and apply the official fix.
**- …

BRCM SAI 4.2.1.5-9 Fix _brcm_sai_indexed_data_get () with unexpected queue causing _brcm_sai_switch_assert () after warm reboot

---

src/system-health/health_checker/utils.py

- Pass `universal_newlines=True` parameter to `subprocess.Popen()`; no longer use `.encode('utf-8')` on resulting stdout.
This was missed in https://github.com/Azure/sonic-buildimage/pull/5886
Note: I would prefer to use `text=True` instead of `universal_newlines=True`, as the former is an alias only available in Python 3 and is more understandable than the latter. However, Even though the setup.py file for this package only specifies Python 3, the LGTM tool finds other Python 2 code in the repo and validates the code as Python 2 code and alerts that `text=True` is an invalid parameter. Will stick with `universal_newlines=True` for now. Once all Python code in the repo has been converted to Python 3, I will change all `universal_newlines=True` to `text=True`.
**- How I …

[system-health] Make `run_command()` Python 3-compliant

---

.artifactignore
azure-pipelines.yml

[skip ci]
Set up CI with Azure Pipelines
add azure pipeline
https://dev.azure.com/sonicswitch/build/_build/results?buildId=1249&view=results

[ci]: Set up CI with Azure Pipelines

---

files/build_templates/sonic_debian_extension.j2
files/image_config/monit/conf.d/sonic-host
files/image_config/monit/container_checker
files/image_config/monit/monitoring_containers

This PR aims to monitor the running status of each container. Currently the auto-restart feature was enabled. If a critical process exited unexpected, the container will be restarted. If the container was restarted 3 times during 20 minutes, then it will not run anymore unless we cleared the flag using the command `sudo systemctl reset-failed <container_name>` manually. 
We will employ Monit to monitor a script. This script will generate the expected running container list and compare it with the current running containers. If there are containers which were expected to run but were not running, then an alerting message will be written into syslog.
I tested this feature on a lab device `str-a7050-acs-3` which has single ASIC and …

[Monit] Monitoring the running status of containers.

---

dockers/docker-fpm-frr/TSA
dockers/docker-fpm-frr/TSB
dockers/docker-fpm-frr/TSC
dockers/docker-fpm-frr/frr/bgpd/templates/general/policies.conf.j2
dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.isolate.conf.j2
dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.unisolate.conf.j2
src/sonic-bgpcfgd/bgpcfgd/managers_allow_list.py
src/sonic-bgpcfgd/tests/data/general/policies.conf/param_all.json
src/sonic-bgpcfgd/tests/data/general/policies.conf/param_deny.json
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_all.conf
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_deny.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/isolate.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/tsa/unisolate.conf
src/sonic-bgpcfgd/tests/test_allow_list.py

1. Change TSA route-map entry sequence numbers to 20 and 30 instead of 2 and 3. With this change standard SONiC sequence number rules order should be following: 
- 1 for ipv6 default nexthop rule. Applicable for ipv6 route-maps only
- 10-11 for "Allow prefix" route-map rules
- 20-30 for "TSA" rules
- 100 and larger for standard rules
2. Add support dynamic default action for "Allow prefix"
To enable dynamic default action parameter for "Allow prefix" feature.
I introduce another field into the "Allow prefix" controlling object.
I added field with name "default_action", which must have either "permit" or "deny" value
```
admin@str-s6100-acs-1:~$ cat 5
{
"BGP_ALLOWED_PREFIXES": {
"DEPLOYMENT_ID|0|1010:1010": {
"prefixes_v4": [
"10.20.0.0/16", …
```

[bgpcfgd]: Support default action for "Allow prefix" feature

---

platform/broadcom/sai.mk

ugprade Broadcom SAI to version 3.5.3.6-2
- Rebase to Broadcom release 3.5.3.6.
- Taking fixes for: CS00011229318, CS00010775359, CS00011331832, CS00011444035, CS00011222060 and CS00010318905
- Taking CS00011581499 patch from Broadcom.

[201811][bcm SAI] ugprade Broadcom SAI to version 3.5.3.6-2

---

platform/centec-arm64/docker-syncd-centec.mk
platform/centec-arm64/docker-syncd-centec/Dockerfile.j2
platform/centec/docker-syncd-centec.mk
platform/centec/docker-syncd-centec/Dockerfile.j2
slave.mk

1. Enable telemetry by default for ARM64 arch
2. Upgrade Centec syncd docker to buster
1. Remove the hardcoded disable of telemetry in slave.mk for ARM64 architecture
2. Use docker-config-engine-buster for syncd docker
3. Remove libjemalloc1 from Dockerfile.j2 for Centec ARM64 syncd docker . libjemalloc1 is replaced by libjemalloc2 in buster, and libjemalloc2 have been installed in docker-base-buster

[Centec ARM64]Upgrade Centec syncd docker to buster and Enable Telemetry on ARM64

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/test_minigraph_case.py

To make the peer switch hostname easily accessible from config DB
Add `peer_switch` field to DEVICE_METADATA table
Run the sonic-cfggen tests

[minigraph.py]: Add peer switch hostname to device metadata

---

src/sonic-build-hooks/scripts/buildinfo_base.sh

Need to add the follow redirection option -L when downloading the package with rediction.
Example: 
curl -L https://github.com/aristanetworks/sonic-firmware/raw/78a3df2/phy/phy-credo_1.0_amd64.deb | md5sum

Fix web package md5 hash not correct issue

---

files/image_config/updategraph/updategraph

During upgrade, if config is loaded from minigraph, it would miss TACACS credentials. This leads to device losing remote user accessibility
During update graph, when config is loaded from minigraph, look for TACACS credentials back-up and load that if available
Remove /etc/sonic/config-db.json, save TACACS credentials in /etc/sonic/tacacs.json and do a Image upgrade. Do image upgrade and boot into new image. Verify remote user access is available.
NOTE: This change is available in master via PR #6285

[201811] Restore from TACACS backup during config-update as needed

---

src/sonic-config-engine/minigraph.py

Server IPv4 loopbacks do not always arrive with /32 prefix, which is a requirement for the MUX_CABLE table in config DB

[minigraph.py]: Force /32 prefix for mux cable server IPv4 loopbacks

---

platform/broadcom/sai.mk

From time to time the BRCM SAI debian built may be using one version of libprotobuf-dev while a different version being picked during installation.  This causes the installation failure.  We should anchor to a specific version during SAI debian build via the debian control file dependency specification to eliminate this type of failures.
Change the SAI debian control file to specify a specific dependency version:
Depends: libprotobuf-dev, libprotobuf-lite17, libprotobuf17
Remove the use of "sudo apt install -y libprotobuf-dev" at build script.
Incorporate this new SAI debian on a private sonic-buildimage and build for BRCM binary and installed to a BRCM SKU DUT to validate the entire process did not encounter any issue and that …

Anchor "libprotobuf-dev" version to a specific version by using debian control file dependency

---

platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py

In rare case can see that xcvrd failed due to "UnboundLocalError: local variable 'label_port' referenced before assignment"
Init "label_port" as None at the beginning of the function, to avoid the case that "label_port" not assigned.
run SFP related test on Mellanox platforms.

[Mellanox] [platform API] Fix “local variable 'label_port' referenced before assignment” error

---

device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/buffers.json.j2
device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/qos.json.j2
dockers/docker-platform-monitor/Dockerfile.j2
platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/watchdog.py

fix platform driver breakage due to python3 upgrade and fix load minigraph errors with config load_minigraph -y
added python3-smbus to the pmon docker template since the previous was python2 specific 
fixed additional "ord" python2 specific code 
fixed the jinja templates used by qos reload - the template logic required data to be parsed 
run "show platform XXX" commands and verify output
run "sudo config load_minigraph -y" and verify configuration 
run "show interfaces XXX" and verify output 

[Platform][nokia]: python3-smbus package add with python3 and jinja fixes 

---

platform/marvell-armhf/sonic-platform-nokia/debian/sonic-platform-nokia-7215.install
platform/marvell-armhf/sonic-platform-nokia/entropy.py
platform/marvell-armhf/sonic-platform-nokia/inband_mgmt.sh
platform/marvell-armhf/sonic-platform-nokia/nokia-7215_plt_setup.sh

This PR provides the following updates to the Nokia ixs7215 platform
1. The Marvell Armada-38x SOC requires SW assistance to improve the system
entropy value available early on in the Sonic boot sequence.
2. The Nokia ixs7215 platform does not have a dedicated Out-Of-Band (OOB) mgmt
port and thus requires additional logic to optionally support configuring
front panel port 48 as an In-Band mgmt port. This commit provides additional
logic to manage and maintain the operation of this In-Band mgmt port.
These changes are similar to those made for the Marvell et6448m platform as provided in PR#      https://github.com/Azure/sonic-buildimage/pull/5749
- Improve random number generation during early Sonic initialization by providing SW updates to Linux entropy value.
- Improve …

[Nokia ixs7215] Add SW assist for platform entropy & fix inband mgmt

---

src/sonic-build-hooks/scripts/buildinfo_base.sh
src/sonic-build-hooks/scripts/symlink_build_hooks

The pip3 is installed the /usr/local/bin, the hook command pip3 does not work correctly. Change to use /usr/local/sbin.
Enable the version control and set the version of the pip package importlib-metadata to 3.3.0, run the following command.
pip3 install importlib-metadata
Before fixing the issue, the version 3.4.0 is installed.
After fixing the issue, the version 3.3.0 installed as expected.

Fix py3 version changed even version control enabled issue

---

sonic-slave-buster/Dockerfile.j2

This is part of the python2 to python3 migration effort.
Fixed swi-tools code to work with `python3`
Updated the version of swi-tools downloaded by the `sonic-slave-buster/Dockerfile.j2`
Other Dockerfiles still use the `python2` version, though swi-tools is not used within the stretch builder.
Build an image with `SONIC_ENABLE_IMAGE_SIGNATURE = y` and verify that build passes.
Install the image on a secureboot enabled product to verify that it works.
It is pretty much a harmless change that push python2 to python3 conversion closer to the finish line.
Update the swi-tools version used by buster Dockerfile

Update swi-tools in buster Dockerfile

---

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py

Found test_sfp.py failed due to use a method without importing it.
Import the relevant python module
Run the failed test case and it passed after the fix

[Mellanox] Fix issue: need import initialize_sdk_handle in get_sdk_handle

---

azure-pipelines.yml

use trap to clean up fsroot reliably
cleanup fsroot reliably
use trap to clean up fsroot reliably

[ci]: cleanup fsroot reliably

---

platform/vs/rules.dep
rules/functions
rules/sonic-platform-common.dep
rules/sonic-ztp.dep

1. Fixes the missing DPKG file for gbsyncd-vs package
2. Fixes the softlink issue on the Platform-common and ztp package
3. Fixes the PYTHNON_DEBS list is missing for DBG dockers.

Fix for missing dependencies in the DPKG framework

---

dockers/docker-fpm-frr/TSA
dockers/docker-fpm-frr/TSB
dockers/docker-fpm-frr/TSC

Earlier today we found a bug in the SONiC TSA implementation.
TSC shows incorrect output (see below) in case we have a route-map which contains TSA route-map as a prefix.
```
admin@str-s6100-acs-1:~$ TSC
Traffic Shift Check:
System Mode: Not consistent
```
The reason is that TSC implementation has too loose regexps in TSA utilities, which match wrong route-map entries:
For example, current TSC matches following
```
route-map TO_BGP_PEER_V4 permit 200
route-map TO_BGP_PEER_V6 permit 200
```
But it should match only
```
route-map TO_BGP_PEER_V4 permit 20
route-map TO_BGP_PEER_V4 deny 30
route-map TO_BGP_PEER_V6 permit 20
route-map TO_BGP_PEER_V6 deny 30
```
I fixed it by using egrep with `^` and `$` regexp markers which match begin and end of the line. …

[TSA]: Use egrep to match TSA rules better 

---

files/image_config/warmboot-finalizer/finalize-warmboot.sh

Fix issue #6383 
Define the component with its associated service. Only wait for components that have associated service enabled to reconcile during warm reboot.
Run warm reboot with the change (note that 'natsyncd' is no longer in the wait list:
/var/log/syslog.1:Jan 14 18:28:41.239710 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Wait for database to become ready...
/var/log/syslog.1:Jan 14 18:28:41.730254 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Database is ready...
/var/log/syslog.1:Jan 14 18:28:42.104362 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Restoring counters folder after warmboot...
/var/log/syslog.1:Jan 14 18:28:46.043684 str-7260cx3-acs-1 …

[warm boot finalizer] only wait for enabled components to reconcile

---

platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py

“time" module was missed to be imported and will cause an error when the branch hit.
Add "import time"
make the condition to be true by mocking and let the code run, can see it run w/o error.

[Mellanox][platform api] fix a missing module import

---

src/sonic-config-engine/minigraph.py

Some non-production minigraphs will have an empty `ClusterName` tag
Check if `ClusterName` tag is empty before trying to access text

[minigraph.py]: Check for empty cluster tag before parsing

---

platform/broadcom/sonic-platform-modules-accton/as7816-64x/utils/accton_as7816_monitor.py

Signed-off-by: roy_lee <roy_lee@edge-core.com>
It's been reported that accton fan monitor process keeps consuming memory after few days.
The amount of memory occupied increases in linear and never leased.
Just move declaration of thermal and fan object outside the loop.
Just put in on for more than 5 days, check if the memory of accton fan montor increases.
Just move declaration of thermal and fan object outside the loop.

[device/accton] As7816-64x, fix memory leakage on accton fan monitor.

---

platform/mellanox/hw-management/0001-Make-SONiC-determine-reboot-cause-service-start-afte.patch

On the Mellanox platform, reboot cause is fetched from some certain sysfs which is created by the hw-management service. So determine-reboot-cause service shall start after hw-management, otherwise it could fail due to the related sysfs is not available yet.
Add a patch to the hw-management service to make sure determine-reboot-cause service should start after it.
run on Mellanox platform to check whether determine-reboot-cause can be success on various reboot.

[Mellanox] Make determine-reboot-cause service start after hw-management service

---

sonic-slave-buster/Dockerfile.j2

When building the sonic-slave-buster docker container, the node.js package is
installed to meet the requirements of the Azure DevOPs pipleline
build. Recently this install of node.js has been failing as described within
Sonic issue #6445. This commit fixes that build break by upgrading the
sonic-slave-buster build to install version 14.x of node.js which is the
current LTS version for buster.
Resolves issue #6445
The armhf build is broken.
Update the node.js version within sonic-slave-buster to avoid this build break
Build sonic-slave-buster for the armhf platform …

[build arm] fix sonic-slave-buster build break

---

src/sonic-config-engine/minigraph.py

Avoid sonic-cfggen crashing when a server does not have a configured loopback address in the minigraph

[minigraph.py]: Don't create mux table entries for servers w/o loopbacks

---

src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
src/sonic-yang-models/tests/yang_model_tests/yangTest.json
src/sonic-yang-models/yang-models/sonic-breakout_cfg.yang
src/sonic-yang-models/yang-models/sonic-port.yang

All Mellanox platforms require DPB modes with a specific set of speeds [example](https://github.com/Azure/sonic-buildimage/pull/6021/files)
Extended regex pattern inside YANG model.
Supported platforms: `SN2010`, `SN2100`, `SN2410`, `SN2700`, `SN3420`, `SN3700`, `SN3700C`, `SN3800`, `SN4600C`, `SN4410`, `SN4700`
Manually tested DPB CLI on all platform with all modes

[DPB][YANG-models] extended regex pattern according to Mellanox systems speeds requirements

---

device/mellanox/x86_64-mlnx_msn3800-r0/ACS-MSN3800/hwsku.json
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/hwsku.json
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/hwsku.json
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D24C52/hwsku.json
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/hwsku.json
device/mellanox/x86_64-mlnx_msn3800-r0/platform.json

Created capability files according to platform specification `SN3800`

[DPB] [Mellanox] added capability files for SN3800 platform

---

device/mellanox/x86_64-mlnx_msn2410-r0/ACS-MSN2410/hwsku.json
device/mellanox/x86_64-mlnx_msn2410-r0/platform.json

Created capability files according to platform specification `SN2410`

[DPB] [Mellanox] added capability files for SN2410 platform

---

device/mellanox/x86_64-mlnx_msn3700-r0/ACS-MSN3700/hwsku.json
device/mellanox/x86_64-mlnx_msn3700-r0/platform.json

Created capability files according to platform specification `SN3700`

[DPB] [Mellanox] added capability files for SN3700 platform

---

scripts/build_kvm_image.sh

debug some rare failure for building kvm image
add debug cmd for build_kvm_image.sh
dump netstat info on error

[kvm]: add debug cmd for build_kvm_image.sh

---

azure-pipelines.yml

exit kvm test on the first error
stop kvmtest on the first error

[ci]: stop kvmtest on the first error

---

dockers/docker-fpm-frr/Dockerfile.j2
dockers/docker-fpm-frr/bgpd.sh
dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2

There is a race condition between zebra server accepts connections and bgpd tries to connect. Bgpd has a chance to try to connect before zebra is ready. In this scenario, bgpd will try again after 10 seconds and operate as normal within these 10 seconds. As a consequence, whatever bgpd tries to sent to zebra will be missing in the 10 seconds. To avoid such a scenario, bgpd should start after zebra is ready to accept connections.
Fix https://github.com/Azure/sonic-buildimage/issues/5026
Check and wait until zebra is ready to accept connections before starting bgpd. …

[bgpd] Check zebra is ready to connect when starting bgpd

---

device/mellanox/x86_64-mlnx_msn3420-r0/ACS-MSN3420/hwsku.json
device/mellanox/x86_64-mlnx_msn3420-r0/platform.json

Created capability files according to platform specification `SN3420`

[DPB] [Mellanox] added capability files for SN3420 platform

---

src/sonic-build-hooks/hooks/git

Some component's make process need thirdparty source file which is downloaded by "git clone", not using a specific commit. When source file is changed, Build process may fail. 
1. Add a version file, files/build/versions/versions-git, to record thirdparty source code version(commit ID).
2. Replace git binary by a bash script. In the script, when 'git clone' is done, 'git reset' will reset HEAD to the commit recorded in the version file.
3. When update version file, you need to set parameter 'SONIC_VERSION_CONTROL_COMPONENTS ' and build. At last replace 'files/build/versions/versions-git' by 'files/build/versions/versions-git-latest'
'files/build/versions/versions-git.log' records some infomation.
**- Which release branch to …

[files/build/versions]: support reproduceable build for git

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml
src/sonic-config-engine/tests/test_minigraph_case.py

Meet the requirement for the MUX_CABLE table that IPv6 loopbacks have a /128 prefix
Manually remove existing prefix by splitting IP string, then use Python's `ipaddress` module to implicitly add /128 prefix.
Note that this change only affects the MUX_CABLE table, all other tables continue to use the loopback address provided in minigraph.
Run the sonic-config-engine tests

[minigraph.py]: Force /128 prefix for server IPv6 loopbacks

---

dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2

Ledd is the last daemon that is not enabled to run in python3.
Even though there is a plan to deprecate this daemon and to replace it by something else it's one simple step toward python2 deprecation.
Changed the `command=` line for `ledd` in the `supervisord` configuration of `pmon`.
Copied what was done for other daemons.
Booting a product that has a `led_control.py` should now show the ledd running in python3.
I ran `python3 -m pylint` on all `led_control.py` plugin which means that most of them should be python3 compliant.
There is however still a risk that some might not work.
Run ledd in python3 unless excluded by …

[pmon] Run ledd using python3 unless excluded

---

src/sonic-bgpcfgd/bgpcfgd/managers_bbr.py
src/sonic-bgpcfgd/tests/test_bbr.py

Why/What I did:
Currently BBR Manager looks for peer-group name to start with value define in constants.yml (https://github.com/Azure/sonic-buildimage/blob/master/files/image_config/constants/constants.yml#L40). Peer-name need to be exact string match.
The change in this PR is to make BBR configured for peer-group if it's name starts with (prefixed) with the string define in constants.yml.
This is needed because Peer name can have deployment id at the end with the string "DEPLOYMENT_ID_NUM".
Eg: TIER0_V4_DEPLOYMENT_ID_0
How I verify:
- Added Unit test cases (test___set_prepare_config_enabled_multiple_peers and test___set_prepare_config_disabled_multiple_peers)
```
adosi@68cd7f721b7f:/sonic/src/sonic-bgpcfgd$ pytest tests/test_bbr.py::test___set_prepare_config_enabled_multiple_peers …
```

Updated BBR to use peer group name as prefix.

---

dockers/docker-orchagent/orchagent.sh
files/image_config/logrotate/logrotate.d/rsyslog

This PR has the changes to support having different swss.rec and sairedis.rec for each asic.
The logrotate script is updated as well
- Update the orchagent.sh script to use the logfile name options in these PRs(https://github.com/Azure/sonic-swss/pull/1546 and https://github.com/Azure/sonic-sairedis/pull/747) 
In multi asic platforms the record files will be different for each asic, with the format `swss.asic{x}.rec `and `sairedis.asic{x}.rec` 
- Update the logrotate script for multiasic platform .
The following tests are done to verify
**Verification logs multi asic**
- Check the record files are created
```
admin@sonic:/var/log/swss$ ls -l
total 29532 …
```

[Multi Asic] support of swss.rec and sairedis.rec for multi asic

---

sonic-slave-buster/Dockerfile.j2

Installing newst buster version of libboost (v1.71) in build docker.
version 1.71 of libboost is required by linkmgrd
Installed dev version of libboost 1.71 in build docker
*.deb builds OK

[build-docker-buster]: Install libboost 1.171 In Build Docker

---

src/sonic-host-services/pytest.ini

To view unit test coverage of sonic-host-services package upon build
Add pytest.ini file with necessary options to report coverage
Build the sonic-host-services package, ensure that unit test coverage is output to stdout

[sonic-host-services] Report unit test coverage

---

build_debian.sh

With the release of pip21.0 (https://pypi.org/project/pip/#history)  on branch 201911 stretch build is failing with below error logs:
As per https://pypi.org/project/pip/ pip21.0 does not not support python2 from Jan 2021. To fix this tag the pip to 20.3.3 version which was being used last and is working fine. 
```
Writing /tmp/easy_install-RW_rZo/pip-21.0/setup.cfg
Running pip-21.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-RW_rZo/pip-21.0/egg-dist-tmp-OUShb6
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
warnings.warn(msg)
warning: no files found matching 'docs/docutils.conf'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap' …
```

[201911] Fix Build error when installing pip

---

files/build_templates/docker_image_ctl.j2
src/sonic-ctrmgrd/ctrmgr/container

The Portchannels were not getting cleaned up as the cleanup activity was taking more than 10 secs which is default docker timeout after which a SIGKILL will be send.
Fixes https://github.com/Azure/sonic-buildimage/issues/6199
To check if it works out for this issue in 201911 ? https://github.com/Azure/sonic-buildimage/issues/6503
This issue is significantly seen in master branch compared to 201911 because the Portchannel cleanup takes more time in master. **Test on a DUT with 8 Port Channels.**
**master**
```
admin@str-s6000-acs-8:~$ time sudo systemctl stop teamd
real    0m15.599s
user    0m0.061s
sys     0m0.038s
```
**Sonic 201911.v58**
```
admin@str-s6000-acs-8:~$ time sudo systemctl stop teamd
real    0m5.541s
user    0m0.020s
sys     0m0.028s
```
**- How I did …

[teamd]: Increase wait timeout for teamd docker stop to clean Port channels.

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py

Signed-off-by: Antonina Melnyk antoninax.melnyk@intel.com
There was a mismatch with Eeprom class methods names and methods called from Eeprom class. 
Renamed methods properly and added missing ones.

[barefoot] Fixes for platform API

---

device/mellanox/x86_64-mlnx_msn4700-r0/ACS-MSN4700/hwsku.json
device/mellanox/x86_64-mlnx_msn4700-r0/platform.json

`platform.json` and `hwsku.json` files has not a full set of speeds for split modes
Extended set of speeds for split modes for `SN4700` platform
Manually run DPB CLI commands

[DPB] [Mellanox] added capability files for SN4700 platform 

---

device/mellanox/x86_64-mlnx_msn3700c-r0/ACS-MSN3700C/hwsku.json
device/mellanox/x86_64-mlnx_msn3700c-r0/platform.json

`platform.json` and `hwsku.json` files has not a full set of speeds for split modes
Extended set of speeds for split modes for `SN3700C` platform
Manually run DPB CLI commands

[DPB] [Mellanox] added capability files for SN3700C platform 

---

src/sonic-config-engine/portconfig.py
src/sonic-device-data/src/Makefile
src/sonic-device-data/tests/hwsku_json_checker

For now `hwsku.json` and `platform.json` dont support optional fields. For example no way to add `fec` or `autoneg` field using `platform.json` and `hwsku.json`.
Added parsing of optional fields from hwsku.json.
Add optional field to `hwsku.json`. After first boot will be generated new `config_db.json` or you can generate it using `sonic-cfggen` command. In this file must be optional field from `hwsku.json` or check using command `redis-cli hgetall PORT_TABLE:Ethernet0`
Example of `hwsku.json`, that must be parsed:
```
{
"interfaces": {
"Ethernet0": {
"default_brkout_mode": "1x100G[40G]",
"fec": "rs",
"autoneg": "0"
},
...
}
```
Example of generated `config_db.json`:
```
"PORT": {
"Ethernet0": {
"alias": "Ethernet0",
"lanes": …
```

[config] parse optional fields from hwsku

---

platform/vs/tests/bgp/files/default_route/bgpd.conf
platform/vs/tests/bgp/files/default_route/default_route.conf
platform/vs/tests/bgp/test_default_route.py

Check #6483
add test to make sure default route change in eth0 does not
affect the default route in the default vrf
add regression test for #6483 
add vstest
run vstest and failed. will make sure it success after issued fixed.

[vstest]: add default route vs test

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/sonic-config-engine/tests/t0-sample-graph.xml

Recent changes brought L2 vlan concept which do not have DHCP
clients behind them and so DHCP relay is not required. Also,
dhcpmon fails to launch on those vlans as their interfaces
lack IP addresses. This PR limit launch of both DHCP relay
and dhcpmon to L3 vlans only.
Stop non functioning DHCP relay from being launched and also disable error being thrown by dhcpmon
Added extra check for presence of vlan in the vlan_interface table
PR check passes

[dhcp-relay]: Launch DHCP Relay On L3 Vlan

---

azure-pipelines.yml

reset the owner for all files under working directory. some files were owned by root after build, which cause
next build to fail since directory cannot be cleanned.
reset the owner for all files under working directory after build.

[ci]: reset the owner for all files under working directory

---

azure-pipelines.yml

this is due to command line change in
https://github.com/Azure/sonic-mgmt/commit/1e12790a93e9a2fa49691d8759b940bf67430676
this is due to command line change in
https://github.com/Azure/sonic-mgmt/commit/1e12790a93e9a2fa49691d8759b940bf67430676
add -k ceos option to setup t0 testbed

[ci]: add -k ceos option to setup t0 testbed

---

azure-pipelines.yml

- archive logs
- archive kvm memdump when failed
- publish kvm test results
- archive logs
- archive kvm memdump when failed
- publish kvm test results

[ci]: archive kvmtest artifacts

---

azure-pipelines.yml

Currently we have an empty branch view on Azure pipeline webpage. I added all branches into trigger.

[ci]: add more branches into azure-pipelines trigger

---

platform/mellanox/hw-management/0002-hw-mgmt-events-Add-support-for-SDK-OFFLINE-event-for.patch

During ISSU, "mlxsw_minimal" driver still trying to access firmware, in some cases FW could return some wrong critical threshold value which will cause switch shutdown. 
In order to prevent "mlxsw_minimal" driver from accessing ASIC during ISSU, SDK will raise "OFFLINE" 'udev' event
at the early beginning of such flow. When this event is received, hw-managemnet will remove "mlxsw_minimal" driver.
There is no need to implement the opposite "ONLINE" event since this flow is ended up with "kexec".
repeatedly perform warm reboot, make sure there is no switch shutdown occurred.
**- A picture of a cute animal (not mandatory …

[201911][Mellanox] Add hw-mgmt patch to support SDK OFFLINE event handling during ISSU

---

src/sonic-bgpcfgd/bgpmon/bgpmon.py

It is possible that BGP neighbors in IPv4 and IPv6 address families share the same name. 
For example, if belowing config is applied to creare a bgp monitor:
```
{
"BGP_MONITORS": {
"11.0.0.1": {
"admin_status": "up",
"asn": "4200065100",
"holdtime": "10",
"keepalive": "3",
"local_addr": "10.1.0.32",
"name": "bgp_monitor",
"nhopself": "0",
"rrclient": "0"
}
}
}
```
Then a bgp neighbor named ```11.0.0.1``` will exist in both ipv4 and ipv6 neighbors.
```
root@str-7260cx3-acs-2:/var/log# show ip bgp sum
IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 4200065100 vrf-id 0
BGP table version 45133
RIB entries 12807, using 2458944 bytes of memory
Peers 5, using 109080 KiB of memory
Peer groups 5, using 320 …
```

[bgpmon]: Fix exception in bgpmon caused by duplicate bgp neighbor ID

---

platform/mellanox/hw-management/0002-hw-mgmt-events-Add-support-for-SDK-OFFLINE-event-for.patch

During ISSU, "mlxsw_minimal" driver still trying to access firmware, in some cases FW could return some wrong critical threshold value which will cause switch shutdown.
In order to prevent "mlxsw_minimal" driver from accessing ASIC during ISSU, SDK will raise "OFFLINE" 'udev' event
at the early beginning of such flow. When this event is received, hw-management will remove "mlxsw_minimal" driver.
There is no need to implement the opposite "ONLINE" event since this flow is ended up with "kexec".
repeatedly perform warm reboot, make sure there is no switch shutdown occurred. …

[Mellanox] Add hw-mgmt patch to support SDK OFFLINE event handling during ISSU

---

device/arista/x86_64-arista_7050_qx32/pmon_daemon_control.json
device/arista/x86_64-arista_7050_qx32/thermal_policy.json
device/arista/x86_64-arista_7050_qx32s/pmon_daemon_control.json
device/arista/x86_64-arista_7050_qx32s/thermal_policy.json
device/arista/x86_64-arista_7050cx3_32s/pmon_daemon_control.json
device/arista/x86_64-arista_7050cx3_32s/thermal_policy.json
device/arista/x86_64-arista_7060_cx32s/pmon_daemon_control.json
device/arista/x86_64-arista_7060_cx32s/thermal_policy.json
device/arista/x86_64-arista_7060cx2_32s/pmon_daemon_control.json
device/arista/x86_64-arista_7060cx2_32s/thermal_policy.json
device/arista/x86_64-arista_7060px4_32/pmon_daemon_control.json
device/arista/x86_64-arista_7060px4_32/thermal_policy.json
device/arista/x86_64-arista_7170_32c/pmon_daemon_control.json
device/arista/x86_64-arista_7170_32c/thermal_policy.json
device/arista/x86_64-arista_7170_32cd/pmon_daemon_control.json
device/arista/x86_64-arista_7170_32cd/thermal_policy.json
device/arista/x86_64-arista_7170_64c/pmon_daemon_control.json
device/arista/x86_64-arista_7170_64c/thermal_policy.json
device/arista/x86_64-arista_7260cx3_64/pmon_daemon_control.json
device/arista/x86_64-arista_7260cx3_64/thermal_policy.json
device/arista/x86_64-arista_7280cr3_32p4/pmon_daemon_control.json
device/arista/x86_64-arista_7280cr3_32p4/thermal_policy.json
device/arista/x86_64-arista_common/pmon_daemon_control.json
device/arista/x86_64-arista_common/thermal_policy.json

There is a preference to use thermalctld instead of fancontrol for 201911 release branch. The Arista platform submodule updates and thermal policies in the platforms will allow Arista devices to use thermalctld instead of fancontrol.
I cherry-picked the necessary commits from master branch for sonic-platform-modules-arista into 201911 branch. I've also added the file to skip fancontrol and added the thermal policies json.
On Gardena, Upperlake, Clearlake, and Lodoga thermalctld is up and running with no errors. Fans show ~29%.

[201911][Arista] Use thermalctld instead of fancontrol

---

platform/mellanox/mlnx-sai.mk

Changes in the new release:
1. Policy based hashing optimization
2. New attribute support for Max port headroom
3. Tunnel ECN map fixes
4. Tunnel EVPN skeleton extensions (peer attrib, maps)
5. Bridge port admin not affecting port admin (optimize port down time)
6. CRM new API for neighbors and tunnel termination entries
7. Improve FDB event for flush by bridge port (before, null bridge was reported to SONiC, now the bridge will be extracted from bridge port)
8. DHCP L2 v4+v6 traps (for ZTP use case)
9. Generic counter implementation
Update the version number in SAI make file, update the mlnx-sai submodule pointer.
Run full regression tests (T0 and T1-Lag) on Mellanox platforms …

[Mellanox] Update SAI version 1.18.1.0

---

dockers/docker-fpm-frr/frr/supervisord/critical_processes.j2
files/scripts/supervisor-proc-exit-listener

remove blank lines in criticial_process
make proc-exit-listener more robust to handle blank lines
see the pr
tested on kvm.

[docker-fpm-frr]: fix proc-exit-listener crash

---

azure-pipelines.yml

I notice that I rerun a failed job (not the stages), the nfs store is already cleaned by previous failed jobs.
Use artifacts instead.

[ci]: Download artifact instead of using nfs storage

---

rules/functions
slave.mk

Some commands used during build will prompt user interactively, but this is not expected during build. Since most output is collected into log file, user could not see the prompt and feel the build process hangs.
1. Use `mv` command in non interactive mode
2. Redirect stdin to null if command output is collected into log file.
Manual test in local build

Stop prompt during build

---

platform/vs/docker-sonic-vs.mk

sonic-utilities will become dependent upon sonic-platform-common as of https://github.com/Azure/sonic-utilities/pull/1386.
- Add sonic-platform-common as a dependency in docker-sonic-vs.mk
- Additionally, no longer install Python 2 packages of swsssdk and sonic-py-common, as they should no longer be needed.
Build docker-sonic-vs and ensure sonic-platform-common package is installed (e.g., `pip list | grep sonic-platform-common`)

[docker-sonic-vs] Install sonic-platform-common package

---

files/image_config/sudoers/sudoers

The command `sudo ip netns identify <pid>` is used  in function  [ get_current_namespace](https://github.com/Azure/sonic-buildimage/blob/0e7287856cf2873b1f130063e04cb44d7ecd3c98/src/sonic-py-common/sonic_py_common/multi_asic.py#L141)
to check in the cli command is running in host context or within a namespace.
This function is used for every CLI command and command `sudo ip netns identify <pid>` needs to be added in sudoer files to allow users with `RO` access to run show cli commands
This problem is not there on single asic platforms.
Add `ip netns identify *` to sudoers file.
Verify on multi asic platforms
- before the change
```
user_ro@sonic~$ show …
```

[multi asic] add ip netns identify command to sudoer

---

rules/sonic-utilities.mk

This reverts commit 470ed18a6bc2ab752ec1f929296f346f15aa0ae5.

Revert "[build]: disable unit tests for sonic-utilities"

---

files/image_config/sudoers/sudoers

fixes https://github.com/Azure/sonic-utilities/issues/1389
With the recent changes in sudoer files. The  show commands fails for the read-only users. 
The problem here is the 'docker ps' is failing in the function [get_routing_stack()](https://github.com/Azure/sonic-utilities/blob/8a1109ed30576f0287fcd98a4349617f7fb55700/show/main.py#L54) therefore all the CLI commands are failing.
add `docker ps` to the sudoers file
Verify the show commands works for read-only users
```
user_ro@vlab-01:~$ show vers
SONiC Software Version: SONiC.master.629-10436783
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 10436783
Build date: Sat Jan 23 07:09:55 …
```

[baseimage]: add docker ps to the sudoer file

---

build_debian.sh

As per https://pypi.org/project/pip/ pip 21.0 does not not support Python 2 from Jan 2021. Most places in the codebase have already been pinned, but this one was missed.
Pin pip2 < version 21 in build_debian.sh

[build_debian.sh] Freeze pip2 < version 21

---

device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/td3-a7050cx3-32s-32x100G.config.bcm
device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/td3-a7050cx3-32s-48x50G+8x100G.config.bcm
src/sonic-device-data/tests/permitted_list

Update Tunnel and ECMP paramaters for brcm 7050cx3 48x50G+8x100G SKU.
To enable new IPinIP tunnel feature for dual ToR
Add new parameter for brcm 7050cx3 48x50G+8x100G SKU
Verified on target and tunnel are created.

[sonic-device-data]: Update BRCM Tunnel/ECMP Parameter For 7050cx3 48x50G+8x100G

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py

To improve python3 support of berefoot's sonic_platform

[barefoot][platform] platform API 2.0 fixes

---

azure-pipelines.yml
build_debian.sh
dockers/docker-config-engine/Dockerfile.j2

With the release of pip21.0 (https://pypi.org/project/pip/#history) on branch
201811 stretch build is failing with below error logs:
As per https://pypi.org/project/pip/ pip21.0 does not not support python2
from Jan 2021. To fix this tag the pip to 20.3.3 version which was being used last
and is working fine.
With the release of pip21.0 (https://pypi.org/project/pip/#history) on branch
201811 stretch build is failing with below error logs:
As per https://pypi.org/project/pip/ pip21.0 does not not support python2
from Jan 2021. To fix this tag the pip to 20.3.3 version which was being used last
and is working fine.
**- Which release branch to backport (provide reason below if …

[201811][pip2]: pin down pip to 20.3.3

---

platform/broadcom/docker-syncd-brcm/Dockerfile.j2

Starting with BRCM SAI 4.3.1.5 we see the following :ethtool not fount" error in syslog during boot up:
```
Jan 27 07:36:14.712472 str-s6100-acs-1 INFO syncd#/supervisord: syncd sh: 1:
Jan 27 07:36:14.712844 str-s6100-acs-1 INFO syncd#/supervisord: syncd ethtool: not found
Jan 27 07:36:14.713228 str-s6100-acs-1 INFO syncd#/supervisord: syncd #015
Jan 27 07:36:14.713840 str-s6100-acs-1 INFO syncd#syncd: [0] SAI_API_HOSTIF:_brcm_sai_hostif_speed_set:11894 cmd ethtool -s Ethernet39 speed 40000 rc:32512
Jan 27 07:36:14.717204 str-s6100-acs-1 NOTICE swss#orchagent: :- setHostIntfsOperStatus: Set operation status DOWN to host interface Ethernet39
Jan 27 07:36:14.717204 str-s6100-acs-1 NOTICE swss#orchagent: :- initPort: Initialized port Ethernet39
Jan 27 07:36:14.717204 …
```

Fix BRCM Syncd Error:syncd#/supervisord: syncd sh: 1: ethtool: not found

---

device/accton/x86_64-accton_as7326_56x-r0/Accton-AS7326-56X/td3-as7326-48x25G+8x100G.config.bcm
device/accton/x86_64-accton_as7726_32x-r0/Accton-AS7726-32X/td3-as7726-32x100G.config.bcm
device/celestica/x86_64-cel_seastone_2-r0/Seastone_2/td3-seastone_2-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/td3-s5232f-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/td3-s5232f-8x100G+48x50G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/td3-s5232f-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/td3-s5232f-96x10G+8x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/td3-s5232f-96x25G+8x100G.config.bcm
device/dell/x86_64-dellemc_s5248f_c3538-r0/DellEMC-S5248f-P-10G/td3-s5248f-10g.config.bcm
device/dell/x86_64-dellemc_s5248f_c3538-r0/DellEMC-S5248f-P-25G/td3-s5248f-25g.config.bcm
device/dell/x86_64-dellemc_s5296f_c3538-r0/DellEMC-S5296f-P-10G/td3-s5296f-10g.config.bcm
device/dell/x86_64-dellemc_s5296f_c3538-r0/DellEMC-S5296f-P-25G/td3-s5296f-25g.config.bcm
device/delta/x86_64-delta_ag9032v2a-r0/Delta-ag9032v2a/td3-ag9032v2a-32x100G+1x10G.config.bcm
device/inventec/x86_64-inventec_d6332-r0/INVENTEC-D6332/td3-d6332-32x100G-SR4.config.bcm
device/inventec/x86_64-inventec_d6356-r0/INVENTEC-D6356/td3-d6356-48x25G-8x100G.config.bcm
device/quanta/x86_64-quanta_ix7_rglbmc-r0/Quanta-IX7-32X/td3-ix7-32x100G.config.bcm
device/quanta/x86_64-quanta_ix8_rglbmc-r0/Quanta-IX8-56X/td3-ix8-48x25G+8x100G.config.bcm
device/quanta/x86_64-quanta_ix8c_bwde-r0/Quanta-IX8C-56X/td3-ix8c-48x25G+8x100G.config.bcm

BRCM SDK 6.5.21 includes firmware updates (premier cancun) for TD3 platforms. The firmware update is required on TD3 platforms, which is packaged with BCMSAI 4.3.0.10.
Updated BCM config with a new variable that specifies the firmware package path. SDK uses this path to locate firmware packages and load during cold boot.
```
bsv
BRCM SAI ver: [4.3.0.10], OCP SAI ver: [1.7.1], SDK ver: [sdk-6.5.21] CANCUN ver: [5.3.3]
drivshell>
admin@str2-7050cx3-acs-02:~$ bcmsh
Press Enter to show prompt.
Press Ctrl+C to exit.
NOTICE: Only one bcmsh or bcmcmd can connect to the shell at same time.
drivshell>cancun stat
cancun stat
UNIT0 CANCUN:
CIH: LOADED
Ver: 06.06.01
CMH: LOADED
Ver: 06.06.01
SDK Ver: 06.05.21
CCH: LOADED
Ver: 06.06.01
SDK …
```

[BCM Config] Update BCM config with parameters to update firmware on TD3 platforms

---

azure-pipelines.yml
check_install.py
scripts/build_kvm_image.sh

increase the pexpect timeout from 30 to 60 seconds
follow three commits:
* 006764bb 2021-01-30 | [ci]: cleanup source directory upon checkout (HEAD -> kvm, lgh/kvm) [Guohan Lu]
* 6481c225 2021-01-30 | [kvm]: install net-tools package for debug [Guohan Lu]
* 3ffa352a 2021-01-29 | [ci]: reset the repo (origin/master, origin/HEAD, master) [Guohan Lu]

[kvm]: increase the pexpect timeout from 30 to 60 seconds

---

src/system-health/health_checker/hardware_checker.py

In thermalctd, when speed of fan exceeds threashold, the fan status will be saved as "bad". So in system health, it is better to check fan speed before fan status. In this case, if fan speed exceeds threashold, we get more deatil information.
Move fan speed check logic before fan status check
Manual test

[system-health] Check fan speed before check fan status

---

platform/barefoot/docker-syncd-bfn-rpc/Dockerfile.j2
platform/broadcom/docker-syncd-brcm-rpc/Dockerfile.j2
platform/centec-arm64/docker-syncd-centec-rpc/Dockerfile.j2
platform/centec/docker-syncd-centec-rpc/Dockerfile.j2
platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2

Fix issue: ptf_nn_agent isn't able to start in syncd-rpc docker on buster.
The issue is fixed by installing python-dev, cffi and nnpy for python 2 explicitly.
Run copp test on RPC image.

[syncd-rpc docker] Fix issue: ptf_nn_agent isn't able to start in syncd-rpc docker on buster

---

platform/broadcom/sai.mk

1. BRCM SAI Debian build need not have any Kernel version dependency -  Starting with 4.3 BRCM made changes in SAI so that this dependency has been cleaned up.  We can now remove the Kernel Version dependency from Azure Pipeline build script.
2. Bypass PEER_MODE p2mp setting causing SYNCd crash on non-TD3 SKUs - Temporarily patch BRCM SAI code to not cause SYNCd crash when Orchagent program SAI_TUNNEL_ATTR_PEER_MODE: SAI_TUNNEL_PEER_MODE_P2MP on Non-TD3 SKUs. Will remove this when BRCM provide proper fix to address this issue.
Item 1:  Attempt the new SAI Debian build with Kernel version dependency removed from build script and verified successful Debian built and it can be used to bring up BRCM DUT without any issue.
Item 2: Load current 4.3 …

Remove BRCM SAI Deb Kernel version dependency + Bypass PEER_MODE p2mp setting causing SYNCd crash on non-TD3 SKUs

---

src/snmpd/Makefile

Disable snmp's parallel make for now, because it causes compile fail with file truncated.
snmpd's compile is always failed with file truncated on ARM64 arch, the error log is like "/usr/bin/ld: mibgroup/ip-forward-mib/inetCidrRouteTable/.libs/inetCidrRouteTable_interface.o: file not recognized: file truncated"
Disable snmp's parallel make for now on ARM64 compile.
make configure PLATFORM=centec-arm64 PLATFORM_ARCH=arm64
make target/debs/buster/libsnmp-base_5.7.3+dfsg-5_all.deb  NOSTRETCH=1

[arm64]disable snmp's parallel make for now, because it causes compile fail with file truncated

---

.azure-pipelines/run-test-template.yml
azure-pipelines.yml

add t1-lag testbed tests
use template

[ci]: add t1-lag testbed

---

src/sonic-bgpcfgd/bgpcfgd/managers_intf.py
src/sonic-bgpcfgd/tests/test_bgp.py
src/sonic-bgpcfgd/tests/test_db.py
src/sonic-bgpcfgd/tests/test_directory.py
src/sonic-bgpcfgd/tests/test_frr.py
src/sonic-bgpcfgd/tests/test_intf.py
src/sonic-bgpcfgd/tests/test_setsrc.py

Add unit tests for bgpcfgd
Add unit tests for bgpcfgd and fix a minor bug in `manager_intf.py` found in testing
Test coverage with this PR
```
Name                             Stmts   Miss  Cover
----------------------------------------------------
bgpcfgd/__init__.py                  0      0   100%
bgpcfgd/__main__.py                  3      3     0%
bgpcfgd/config.py                   69      0   100%
bgpcfgd/directory.py                63      0   100%
bgpcfgd/frr.py                      49      1    98%
bgpcfgd/log.py                      15      2    87%
bgpcfgd/main.py                     53     53     0%
bgpcfgd/manager.py                  41     21    49%
bgpcfgd/managers_allow_list.py     425     29    93%
bgpcfgd/managers_bbr.py …
```

[Bgpcfgd] Add unit tests

---

files/Aboot/boot0.j2
files/image_config/secureboot/allowlist_paths.conf
files/initramfs-tools/arista-convertfs.j2
files/initramfs-tools/arista-hook
files/initramfs-tools/union-mount.j2

A few issues where discovered with crashkernel on Arista platforms.
1) platforms using `docker_inram=on` would end up OOM in kdump environment.
This happens because the same initramfs is used by SONiC and the crashkernel.
With `docker_inram=on` the `dockerfs.tar.gz` is extracted in a `tmpfs` created for the occasion.
Since `dockerfs.tar.gz` weights more than 1.5G, it doesn't fit into the kdump environment and ends up OOM.
This OOM event can in turn trigger a panic.
2) Arista platforms with `secureboot` enabled would fail to load the crashkernel because the kernel parameter would be discarded on boot.
This happens because the `boot0` in secureboot mode is strict about kernel parameter injection.
3) The secureboot path allowlist would remove kernel crash reports.
4) The …

[kdump] Fix OOM events in crashkernel

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-case.xml
src/sonic-config-engine/tests/test_minigraph_case.py

To make  the kubernetes server IP & enabled/disabled status configurable through minigraph.
Saved cluster name into "DEVICE_METADATA|localhost" , so this can be available for kubernetes use.
Updated the parser (minigraph.py) to get it from MetadataDeclaration/Devices/DeviceMetadata section for this device.
Add to "DEVICE_METADATA|localhost" , if ClusterName is available in PngDec/Devices/Device for localhost
Unit test is added to parse & test out.
For manual test add the following to MetadataDeclaration/Devices/DeviceMetadata section. call "config load_minigraph" and verify through "show kube server config"
Look for "DEVICE_METADATA": { "localhost": { ... "cluster": "<this device cluster name", ...}}, if minigraph.xml does carry …

Update minigraph.py to parse kubernetes config from minigraph.xml

---

device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/port_config.ini

`port_config.ini` for HWSKU `Arista-7050CX3-32S-C32` has missing speed column and duplicated lanes.
The incorrect speed causes issues in Orchagent RESTARTCHECK as the below task remains as the remaining item during swss shutdown.
Fixes: https://github.com/Azure/sonic-buildimage/issues/6569
Updated port_config.ini file with speed, and removed duplicated lanes.
Generated new minigraph, and installed it on a 7050CX3 device, the RESTARTCHECK passes and warm-reboot proceeds.

[port_config.ini] 7050CX3-32S-C32: Remove unused 10G ports and update speed

---

platform/barefoot/sonic-platform-modules-bfn-montara/debian/postinst
platform/barefoot/sonic-platform-modules-bfn-newport/debian/postinst
platform/barefoot/sonic-platform-modules-bfn/debian/postinst

SONiC design requires sonic_platform package to be installed in SONiC host environment, not only in docker containers.
For now, sonic_platform python wheel package, that is used by pmon, is provided via device-specific platform modules deb packages that unpacks the wheel package file into specific device's directory on lazy-install.
The PR makes deb packages' postinst script also install these unpacked wheel packages to host.
python3 -c "import sonic_platform" should succeed when running on host.

[platform][barefoot] Install sonic_platform to host

---

device/accton/x86_64-accton_as7326_56x-r0/Accton-AS7326-56X/td3-as7326-48x25G+8x100G.config.bcm
device/accton/x86_64-accton_as7726_32x-r0/Accton-AS7726-32X/td3-as7726-32x100G.config.bcm
device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/td3-a7050cx3-32s-32x100G.config.bcm
device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/td3-a7050cx3-32s-48x50G+8x100G.config.bcm
device/celestica/x86_64-cel_seastone_2-r0/Seastone_2/td3-seastone_2-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/td3-s5232f-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/td3-s5232f-8x100G+48x50G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/td3-s5232f-32x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/td3-s5232f-96x10G+8x100G.config.bcm
device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/td3-s5232f-96x25G+8x100G.config.bcm
device/dell/x86_64-dellemc_s5248f_c3538-r0/DellEMC-S5248f-P-10G/td3-s5248f-10g.config.bcm
device/dell/x86_64-dellemc_s5248f_c3538-r0/DellEMC-S5248f-P-25G/td3-s5248f-25g.config.bcm
device/dell/x86_64-dellemc_s5296f_c3538-r0/DellEMC-S5296f-P-10G/td3-s5296f-10g.config.bcm
device/dell/x86_64-dellemc_s5296f_c3538-r0/DellEMC-S5296f-P-25G/td3-s5296f-25g.config.bcm
device/delta/x86_64-delta_ag9032v2a-r0/Delta-ag9032v2a/td3-ag9032v2a-32x100G+1x10G.config.bcm
device/inventec/x86_64-inventec_d6332-r0/INVENTEC-D6332/td3-d6332-32x100G-SR4.config.bcm
device/inventec/x86_64-inventec_d6356-r0/INVENTEC-D6356/td3-d6356-48x25G-8x100G.config.bcm
device/quanta/x86_64-quanta_ix7_rglbmc-r0/Quanta-IX7-32X/td3-ix7-32x100G.config.bcm
device/quanta/x86_64-quanta_ix8_rglbmc-r0/Quanta-IX8-56X/td3-ix8-48x25G+8x100G.config.bcm
device/quanta/x86_64-quanta_ix8c_bwde-r0/Quanta-IX8C-56X/td3-ix8c-48x25G+8x100G.config.bcm

BRCM SDK 6.5.21 includes firmware updates (premier cancun ISSU capable version 6.4.1) for TD3 platforms. The firmware update is required on TD3 platforms, which is packaged with BCMSAI 4.3.0.10.  
Update all TD3 based bcm.config files to use the ISSU capable Premium Cancun version 6.4.1
```
drivshell>cancun stat
cancun stat
UNIT0 CANCUN:
CIH: LOADED
Ver: 06.04.01
CMH: LOADED
Ver: 06.04.01
SDK Ver: 06.05.21
CCH: LOADED
Ver: 06.04.01
SDK Ver: 06.05.21
CEH: LOADED
Ver: 06.04.01
SDK Ver: 06.05.21
CFH: LOADED
Ver: 06.04.01
```
[BCM Config] Update TD3 bcm.config files to use ISSU capable premium CANCUN 6.4.1

[BCM Config] Update TD3 bcm.config files to use ISSU capable premium CANCUN 6.4.1

---

.artifactignore

Archive compiled Debian packages and Python wheels so that the artifacts can be downloaded and used by other pipelines.
Also archive related log files.

[ci] Archive compiled Debian packages and Python wheels

---

azure-pipelines.yml

Do some cleanup before checking out the code.
The folder fsroot cannot be removed when checking out code by azure pipeline

[ci]: Cleanup fsroot before checking out code

---

src/sonic-bgpcfgd/tests/test_bgp.py

The check for `check_neig_meta` was not following the value in `constants`. Fix it to match the value in `constants`.
Use the value in `constants` in assertion for `check_neig_meta`.
Run the unit test locally

[bgpcfgd] Fix unit test for bgp manager

---

platform/broadcom/sai.mk

Porting the same workaround frix from BRCM SAI 4.2.1.5-9 to SAI 4.3.0.10-4 to address the same WARM Reboot SYNCd crash issue.
See (https://github.com/Azure/sonic-buildimage/pull/6374)
A case has filed with BRCM. We are porting this change in master branch that has moved on to SAI 4.3.0.10 release so that it will allow further feature validation/testing especially in the warm reboot area.
Once an official fix is provided by BRCM, we will then remove this in house fix and apply the official fix.
This PR fixes (https://github.com/Azure/sonic-buildimage/issues/6655)
Just perform warm reboot with any master code prior to this PR you should see SYNCd crash issue with something as the following in the syslog:
```
Feb 2 19:56:56.585774 str-s6100-acs-2 …
```

BRCM SAI 4.3.0.10-4 Fix _brcm_sai_indexed_data_get () with unexpected  queue causing _brcm_sai_switch_assert () after warm reboot

---

platform/broadcom/docker-syncd-brcm.dep
platform/mellanox/docker-syncd-mlnx.dep

The docker image docker-syncd-brcm.gz not use the right libsai.

Fix syncd dpkg cache dependency issue

---

platform/mellanox/mlnx-fw-upgrade.j2

Reduce the time it takes for the ASIC FW burn as part of the automatic FW upgrade procedure.
Add -d option to mlxfwmanager tool to use the faster MST device and not the default one which is not the fastest one.
I manually changed ASIC FW followed by reboot command in order for FW upgrade to take place on deinit.
I manually changed ASIC FW followed by hard reset in order for FW upgrade to take place on init.

[Mellanox] Update FW upgrade script to use 'mlxfwmanager -d' option for specifying MST device in FW burn operation

---

files/image_config/pcie-check/pcie-check.sh
files/image_config/sudoers/sudoers

As of https://github.com/Azure/sonic-utilities/pull/1297, subcommands of pcieutil have changed to remove the redundant `pcie-` prefix. This PR adapts calling applications (pcie-check) to the new syntax.
Resolves https://github.com/Azure/sonic-buildimage/issues/6676
- Remove `pcie-` prefix from pcieutil subcommands in calling applications
- Also add `pcieutil *` to sudoers file, as pcieutil requires elevated permissions

[pcie-check] Update underlying pcieutil command and add to sudoers file

---

files/build_templates/per_namespace/teamd.service.j2

Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
In multi-asic VS, topology service is run after database service to set up the internal asic topology.
swss and syncd have a dependency to start after topology service is run so that the interfaces are moved to right namespace and created in the right namespace. In case of multi-asic vs, during the initial boot up, when there is no configuration added, teamd service starts and swss/syncd do not start as topology service does not start. Upon loading configuration using config_db or minigraph, swss and sycnd start up , but teamd is not restarted as swss is not stopped and started. This causes teamd to be in a bad state and requires a reload of config.
Add dependency in teamd service to start after …

[multi_asic][vs]: Add dependency in teamd service to start after topology service.

---

installer/x86_64/install.sh
installer/x86_64/tests/sample_machine.conf
installer/x86_64/tests/test_read_conf.sh

Encounter error when install SONiC image if there are some onie_discovery variables assigned with multiple values inside machine.conf
Replace original ". /machine.conf" method and add another function to do the same thing.
1. Add a item inside /host/machine.conf like `onie_disco_ntpsrv=10.254.141.10 10.254.141.131`
2. Do `sonic_installer install` to check if any error occurs
Add a new function 'read_conf_file' to read the settings from machine.conf when the value in machine.conf are separated by space without double quotes between them.

[installer] Fix variable inside machine.conf caused install.sh error

---

device/dell/x86_64-dell_s6000_s1220-r0/platform_reboot

Reboot command in Dell S6000 failed to reboot the switch. 
Added retry mechanism and CPU reset.
Execute reboot command in Dell S6000.  
[S6000_reboot_UT.txt](https://github.com/Azure/sonic-buildimage/files/5916698/S6000_reboot_UT.txt)

Dell S6000: Fix reboot failure issue

---

device/accton/x86_64-accton_as7116_54x-r0/sonic_platform/sfp.py
device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
device/celestica/x86_64-cel_silverstone-r0/sonic_platform/sfp.py
device/dell/x86_64-dellemc_s5232f_c3538-r0/plugins/sfputil.py
device/dell/x86_64-dellemc_s5248f_c3538-r0/plugins/sfputil.py
device/dell/x86_64-dellemc_s5296f_c3538-r0/plugins/sfputil.py
device/dell/x86_64-dellemc_z9264f_c3538-r0/plugins/sfputil.py
device/juniper/x86_64-juniper_qfx5200-r0/plugins/sfputil.py
device/juniper/x86_64-juniper_qfx5210-r0/plugins/sfputil.py
device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py
device/mellanox/x86_64-mlnx_msn4410-r0/plugins/sfputil.py
platform/broadcom/sonic-platform-modules-cel/services/platform_api/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-inventec/d6332/sonic_platform/qsfp.py
platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform/qsfp.py
platform/broadcom/sonic-platform-modules-inventec/d7054q28b/sonic_platform/sfp.py
platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py

PR https://github.com/Azure/sonic-platform-common/pull/102 modified the name of the SFF-8436 (QSFP) method to align the method name between all drivers, renaming it from `parse_qsfp_dom_capability` to `parse_dom_capability`. Once the submodule was updated, the callers using the old nomenclature broke. This PR updates all callers to use the new naming convention.
Update the name of the function globally for all calls into the SFF-8436 driver.
Note that the QSFP-DD driver still uses the old nomenclature and should be modified similarly. I will open a PR to handle this separately.
Ensure method is called properly and callers no longer crash.

[platform] Update QSFP method name 'parse_qsfp_dom_capability' -> 'parse_dom_capability'

---

device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/port_config.ini

https://github.com/Azure/sonic-buildimage/pull/6638 brought in changes which made ProtOrch crash with below error:
```
Feb  5 19:30:55.923878 str2-7050cx3-acs-01 ERR syncd#syncd: [none] SAI_API_PORT:brcm_sai_flex_port_oper:10451 port resource multi set failed with error Invalid parameter (0xfffffffc).
Feb  5 19:30:55.924407 str2-7050cx3-acs-01 INFO syncd#/supervisord: syncd 0:_bcmi_xgs5_port_flexible_validate: FlexPort operation is not enabled on physical port 128#015
Feb  5 19:30:55.924612 str2-7050cx3-acs-01 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_REMOVE failed in syncd mode: SAI_STATUS_FAILURE
Feb  5 19:30:55.924787 str2-7050cx3-acs-01 ERR swss#orchagent: :- remove: remove status: SAI_STATUS_FAILURE
Feb  5 19:30:55.926302 str2-7050cx3-acs-01 INFO …
```

[7050CX3-32S-C32] Add the 10G ports with updated speed

---

platform/barefoot/sonic-platform-modules-bfn-montara/debian/prerm
platform/barefoot/sonic-platform-modules-bfn-newport/debian/prerm
platform/barefoot/sonic-platform-modules-bfn/debian/prerm

prerm is needed for platform modules package to be properly removed.
Added prerm to remove installed in postinst wheel packages.

[barefoot][platform] Fix sonic-platform host installation

---

rules/sonic-utilities.mk

sonic-utilities will become dependent upon sonic-platform-common as of https://github.com/Azure/sonic-utilities/pull/1386.

[sonic-utilities] Depend on sonic-platform-common

---

platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/accton_as4630_54pe_util.py

Accton util applies lsmod to check if drivers are installed.
But lsmod may return error on startup and skip module installation.
Signed-off-by: roy_lee <roy_lee@edge-core.com>
Reported that sometimes the peripherals cannot be polled.
It's found that lsmod command may failed on startup, the accton util misjudges that drivers have been installed.
The change here is not to apply lsmod to poll installed drivers.
The bug can be probably replicated during several time of reboot.
Replace with new script and reboot 100 times. 
Drivers are all well installed on these 100 reboot.  

[device/accton/as4630-54pe] Fix accton driver not been installed

---

platform/mellanox/mlnx-platform-api/sonic_platform/thermal_conditions.py
platform/mellanox/mlnx-platform-api/tests/test_thermal_policy.py

After migrating to python3, the operator '/' always get a float result, but it gets integer result in python2. Need fix this in thermal_conditions.
1. cast float value to int
2. change the unit test case to cover this situation
Manually test and regression test

[Mellanox] Fix dynamic minimum fan table issue caused by python3

---

platform/vs/docker-gbsyncd-vs/Dockerfile.j2
platform/vs/docker-syncd-vs/Dockerfile.j2

Fix #6711 
the requirement was introduced in commit 75104bb35d86e3ec5565abe1cb49809e7790a155
to support sflow in stretch build. in buster build, the requirement
is met, no need to pin down the version.
remove pindown version for iproute2
check pr build

[syncd-vs]: remove pindown version for iproute2 and libcap2-bin

---

platform/barefoot/docker-syncd-bfn-rpc/Dockerfile.j2
platform/broadcom/docker-syncd-brcm-rpc/Dockerfile.j2
platform/cavium/docker-syncd-cavm-rpc/Dockerfile.j2
platform/centec-arm64/docker-syncd-centec-rpc/Dockerfile.j2
platform/centec/docker-syncd-centec-rpc/Dockerfile.j2
platform/innovium/docker-syncd-invm-rpc/Dockerfile.j2
platform/marvell-arm64/docker-syncd-mrvl-rpc/Dockerfile.j2
platform/marvell-armhf/docker-syncd-mrvl-rpc/Dockerfile.j2
platform/marvell/docker-syncd-mrvl-rpc/Dockerfile.j2
platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2
platform/nephos/docker-syncd-nephos-rpc/Dockerfile.j2

When Building syncd-rpc, libthrift has dependency on libboost-atomic1.71.0, libqt5core5a, 
and libqt5network5 however debian packager fails to resolve the dependencies. It instead
installs libthrift from debian along with its dependencies which result in symbols not found.
closes #6622 
resolves #6622
Please provide the following information:
-->
resolve issue loading sync-rpc
ensured dependecies are installed before installing libthrift
load docker sync-rpc on target and there should not be errors find symbol thrift server symbol
```
Preparing to unpack .../libthrift-0.11.0_0.11.0-4_amd64.deb ...
Unpacking libthrift-0.11.0 (0.11.0-4) ...
[91mdpkg: dependency problems …
```

[syncd-rpc] Install Libboost Atomic 1.71, Libqtcore And Libqtnetwork

---

platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/watchdog.py

To make watchdog.arm() method python3 compatible in DellEMC S6100.
Use `bytes` instead of `str` as input for os.write().
Load sonic_platform package and verify no errors are seen when watchdog.arm() method is invoked.
DellEMC S6100: Watchdog - Make arm() method Python3 compatible

DellEMC S6100: Watchdog - Make arm() method Python3 compatible

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.init

This PR is to fix issue: https://github.com/Azure/sonic-buildimage/issues/6603
The CP210x driver not attached properly after first login (cold-plug), `lsusb` and `dmesg` shown that the usb devices has been recognized but driver is missing.
The CP210x driver is embedded in Kernel, so we don't need install it manually.
Add `modprode cp210x` to haliburton service initialization stage.
After this change, all driver are attached and udev rule is working well
```
Debian GNU/Linux 10 sonic ttyS1
sonic login: admin
Password: 
Linux sonic 4.19.0-9-2-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
You are on
____   ___  _   _ _  ____
/ ___| / _ \| \ | (_)/ ___|
\___ \| | | |  \| | | |
___) | |_| | |\  | | |___
|____/ \___/|_| …
```

[Celestica][haliburton][cp210x] modprobe cp210x to ensure the driver can be load properly

---

.azure-pipelines/build-template.yml

cleanup directory that cannot be archived

[ci]: move cleanup before archive artifacts

---

rules/docker-restapi.mk

We don't need to keep this port open anymore
Remove the port in container startup arguments
- [ * ] 201911

Disable port 8090 for restapi container

---

slave.mk

We stopped building our own custom python-click package via https://github.com/Azure/sonic-buildimage/pull/5549. This target should have been removed at that time but was missed.
Remove PYTHON_CLICK target from slave.mk

[slave.mk] Remove PYTHON_CLICK target

---

platform/broadcom/sai.mk

Upgrading bcmsai from 4.3.0.10-5 to 4.3.0.13.
Merged bcmsai  4.3.0.13 code to top of master bcmsai 4.3.0.10-5.
Ran nightly regression on T0 and T1 topology using bcmsai 4.3.0.13. Test results are better than previous runs.
For T0 -  
New test passing - CRM, Decap, FDB, platform test, VxLAN
New test failing – PFC unknown MAC
For T1 – 
New test passing – Port Channel
New test failing – platform test
Upgrading bcmsai from 4.3.0.10-5 to 4.3.0.13.

Upgrading bcmsai from 4.3.0.10-5 to 4.3.0.13

---

files/build_templates/per_namespace/syncd.service.j2
files/scripts/syncd.sh

[systemd] Increase syncd startup script timeout to support FW upgrade on init (Mellanox only).
Add prints to syslog in syncd startup script to indicate FW upgrade is in progress.
This change should be merged after the following PRs were merged:
https://github.com/Azure/sonic-sairedis/pull/774 (master)
https://github.com/Azure/sonic-sairedis/pull/776 (201911)
There is no PR for 201912 yet (I will make sure to add one).
Signed-off-by: liora <liora@nvidia.com>
To support FW upgrade on init.
Change timeout value
I manually changed ASIC and Gearbox FW followed by hard reset in order for FW upgrade to take place on init.

[Mellanox] [systemd] Increase syncd startup script timeout to complete ASIC FW update

---

platform/barefoot/sonic-platform-modules-bfn/debian/rules

platform modules' deb package rules for x86_64-accton_wedge100bf_65x-r0 was missing the code that installs the sonic_platform wheel package file under device directory on host (which is checked by pmon deamon on start)
Added the required code
install the package

[platform][barefoot] Fix sonic_platform for x86_64-accton_wedge100bf_65x-r0

---

device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/th3-z9332f-32x100G.config.bcm
device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-32x400G.config.bcm
device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm

SER test script is failing as mem_cache flag is disabled.
Edit NPU config
Check cache command in NPU shell after enabling mem_cache_enable flag

DellEMC: Z9332f enable mem cache flag

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py

sonic-platform fixups for Barefoot

[barefoot][sonic-platform] Fix get_system_eeprom_info and refactor eeprom.py

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py

Use separate file for each sfp eeprom operation

[barefoot][sonic-platform] Refactor sfp.py

---

.azure-pipelines/build-template.yml
.azure-pipelines/official-build.yml
.azure-pipelines/run-test-template.yml
azure-pipelines.yml

build vs image in official build
- use template for vs image

[ci]: build vs image in official build

---

platform/broadcom/sai.mk

This PR is needed to fix the show interface counters output issue where the counters are not correct due to an issue introduced in BRCM SAI 4.3.
Without the fix if one injects packets, the expected counters for the interfaces involved do not show correct count values. The RX count looks to be TX count while TX count looks to be RX count but even that the values could not be trusted.
After the fix the counters started to look correct.  Here is one sample output taken after the fix is applied where I manually injected 10,000 packets into Ethernet92 to be routed out of the port channel member port Ethernet40. Also injected 10,000 invalid packets into the same Ethernet92  and all 10,000 packets were shown RX_DRP correctly.
```
admin@str-s6000-acs-8:~$ show interface counters
Last cached time …
```

BRCM SAI 4.3.0.13-1 Pick up BRCM Patch to fix bogus interface counters

---

files/build_templates/sonic_debian_extension.j2

Fix marvell-armhf build break
The azure-storage package depends on the cryptography package. Newer
versions of cryptography require the rust compiler, the correct version
for which is not readily available in buster. Hence we pre-install an
older version here to satisfy the azure-storage dependency.
Note: This is not a problem for other architectures as pre-built versions
of cryptography are available for those. This sequence can be removed
after upgrading to debian bullseye.
Resolve azure-storage package dependency issue on cryptography package
Successfully build sonic-marvel-armhf.bin

[armhf build] Fix azure-storage dependency on cryptography package

---

platform/broadcom/sonic-platform-modules-cel/haliburton/script/udev_prefix.sh

https://github.com/Azure/sonic-utilities/pull/1431 changes the path to the `udevprefix.conf` file. The file previously inappropriately resided in the `<platform>/plugins/` directory. That directory is reserved for now-deprecated Python platform plugins, and will be removed in the near future.
Update all references to udevprefix.conf to reflect the new path, directly under the `<platform>/` directory
Note that this PR requires https://github.com/Azure/sonic-utilities/pull/1431. For the master branch, this means that this PR should be merged at the same time as the sonic-utilities submodule update here: https://github.com/Azure/sonic-buildimage/pull/6777. For the 202012 branch, this change should be cherry-picked along with an updated 202012 branch of sonic-utilities which includes the …

[platform] Update path to udevprefix.conf file

---

files/scripts/swss.sh

All SWSS dependent services should stop before SWSS service to avoid future possible issues.
For example 'teamd' service will stop before to allow the driver unload netdev gracefully. 
This is to stop all LAG's before restarting syncd service when running 'config reload' command.
Change the order of dependent services of SWSS.
Run 'config reload' command.
Previously the operation failed when a large number of PortChannel configured on the system.
Change the order of the service stop to be the opposite order of the start.

Change the order of stopping dependent services of SWSS on master

---

sonic-slave-stretch/Dockerfile.j2

Why I did:
Fix the build failure of asyncsnmp-2.1.0-py3-none-any.whl . 
Looks like a recent update on https://packages.debian.org/stretch/libpython3.5-stdlib
3.5.3-1+deb9u1 -> 3.5.3-1+deb9u3 break the build command `python3 setup.py bdist_wheel`
How I fixed:
Installl setuptool tools explicitly via pip3 install

[201911] Fix the build failure

---

dockers/docker-orchagent/enable_counters.py

Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
**depends on** : 
https://github.com/Azure/sonic-swss/pull/1600 , 
https://github.com/Azure/sonic-utilities/pull/1355
**merge priority:**
https://github.com/Azure/sonic-swss/pull/1600
https://github.com/Azure/sonic-utilities/pull/1355
https://github.com/Azure/sonic-buildimage/pull/6444
PG drop counters should be enabled by default
Add PG drop counter enable option to dockers/docker-orchagent/enable_counters.py
run `counterpoll show` CLI command and then you will see **PG_STAT_DROP** enabled there

Enable PG drop counters by default

---

build_debian.sh

As we are currently in the process of removing Python 2 from SONiC, to ensure a seamless transition to Python 3.
Install Python 3 scapy version 2.4.4 in host OS in build_debian.sh
`pip3 show scapy`

[build] Install Python 3 scapy version 2.4.4 in host OS

---

dockers/docker-sonic-telemetry/telemetry.sh

adding noTLS mode for debugging purpose
Removing config-set for port 8080. It fails to start telemetry if docker restarts in case on noTLS mode because it expects log_level config to be present as well. 
Built telemetry standalone with noTLS support.
Replaced binaries on device. 
Updated telemetry.sh script inside docket and ran it
Test results:
**Server on noTLS:**
root@str-s6000-acs-10:/usr/sbin# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.2  58964 21304 pts/0    Ss+  Feb05   0:18 /usr/bin/python /usr/bin/supervisord
root         9  0.0  0.1  51908 16088 pts/0    S    Feb05   0:00 python /usr/bin/supervisor-proc-exit-listener --container-name telemetry
root        13  0.0  0.0 262984  3588 …

[StreamingTelemetry] add noTLS support for debug purpose

---

files/scripts/swss.sh

When large number of port channels (more than 64) is configured, a config reload command might ends with not all port channel configured and up. Further debug shows that unloading the port channels on the ASIC driver take a lot of time.
With the change, deleting all port channels before the syncd restart will free resources better and the ASIC driver will unload all netdev fast and the operation will execute properly.
Change the order of dependent services of SWSS.
Before the fix: 
- Configure more than 80 port channel each with IP address.
- Run 'config reload' command. ASIC driver failure observed and not all port channels are configured properly and up. 
After the fix:
- …

Change the order of stopping dependent services of SWSS on 201911

---

device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/topology.sh
files/image_config/topology/topology.sh

Update topology script to retrieve hwsku from minigraph
if hwsku information is not available in config_db.
Fix clean up of interfaces in msft_multi_asic_vs hwsku
topology script.
When bringing up multi-asic VS switch, topology service is started during boot up.
Topology service starts a shell script which runs the topology script present in /usr/share/sonic/device/<platfrom>/<hwsku> directory. To invoke hwsku specific script, the topology script tries to retrieve hwsku information from config_db.
During initial boot up config_db might not be populated. In order to start topology service before config_db is updated,
update topology script to get hwsku information from minigraph.xml if it is available.
This will …

[multi-asic][vs]: Update topology script to retrieve hwsku from minigraph

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph.xml
src/sonic-config-engine/tests/test_cfggen.py

It is possible that one interface attaches multiple vlans. The VlanInterface should be in tagged mode.
Unit test

[minigraph] Support tagged VlanInterface if attached to multiple vlans

---

device/dell/x86_64-dell_s6000_s1220-r0/system_health_monitoring_config.json
device/dell/x86_64-dell_s6100_c2538-r0/system_health_monitoring_config.json
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/psu.py

Needed support for platform system health in Dell platforms 
Made platform specific system health config to support the need.
Check show system-health summary/detail/monitor-list CLI output.
UT:
[s6x00_system_health_UT.txt](https://github.com/Azure/sonic-buildimage/files/5987824/s6x00_system_health_UT.txt)

Dell S6000,S6100 system health changes

---

files/build_templates/sonic_debian_extension.j2

Install pyroute2 for sonic-utilities. This change is needed for https://github.com/Azure/sonic-utilities/pull/1437

[201911] Install pyroute2 for sonic-utilities

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Fix runtime issues caused by SONiC update
- new attribute SAI_ACL_ENTRY_ATTR_FIELD_ACL_IP_TYPE  supported 
- new attribute SAI_SWITCH_ATTR_AVAILABLE_IPMC_ENTRY supported

[BFN]: Update SDK packages

---

files/image_config/sudoers/sudoers

`show ip interfaces` is enhanced recently to support multi ASIC platforms in this [PR ](https://github.com/Azure/sonic-utilities/pull/1396). The `ipintutil` script as to run as `sudo`  user, to get the ip interface from each namespace.
Add this script to the sudoer file so that `show ip interface` command is available for user with read-only permissions
Add script `ipintutil` to the read-only allowed commands list.
**- Before the change**
```
user_ro@vlab-01:~$ id
uid=1002(user_ro) gid=1002(user_ro) groups=1002(user_ro)
user_ro@vlab-01:~$ show ip int
Make sure your account has RW permission to current device.
Otherwise sudo requests will be rejected.
[sudo] password for user_ro:
Aborted!
user_ro@vlab-01:~$
```
**- …

[baseimage] add ipintutil in sudoer file

---

.gitmodules

* fix url for
* submodule "platform/mellanox/hw-management/hw-mgmt"
* remove trailing / from url
Signed-off-by: Don Newton don@opennetworking.org
During make init submodule`` "platform/mellanox/hw-management/hw-mgmt" fails to clone due to trailing / on the url
Removed the trailing /
`make init` and look for errors
- [x ] 202012
ONF is using the 202012 branch as the base for our effort
Correct the url line for submodule "platform/mellanox/hw-management/hw-mgmt"

 .gitmodules: Fix make init

---

files/image_config/sudoers/sudoers

This PR is port of https://github.com/Azure/sonic-buildimage/pull/6845 for `201911`
`show ip interfaces` is enhanced recently to support multi ASIC platforms in this https://github.com/Azure/sonic-utilities/pull/1437. The `ipintutil` script as to run as `sudo`  user, to get the ip interface from each namespace.
Add this script to the sudoer file so that `show ip interface` command is available for user with read-only permissions
Add script `ipintutil` to the read-only allowed commands list.

[201911][baseimage] add ipintutil in sudoer file

---

platform/mellanox/docker-syncd-mlnx/Dockerfile.j2

Signed-off-by: allas <allas@nvidia.com>
Mellanox SDK APIs support python 2 at the moment.
Mellanox SDK APIs support python 2 at the moment.
Add python 2 to Mellanox syncd only.
docker exec -t syncd /bin/bash -c "sx_api_dbg_generate_dump.py /home/sx_api_dbg_dump"
You can see that it will work and generate /home/sx_api_dbg_dump

[Mellanox] [syncd] Added support for python2

---

src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
src/sonic-yang-models/tests/yang_model_tests/yangTest.json
src/sonic-yang-models/yang-models/sonic-crm.yang

Fix DPB crash caused of new entries in config db.
Details: https://github.com/Azure/sonic-buildimage/issues/6331
Updated crm yang model

[yang] update crm yang model for dynamic port breakout

---

platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/watchdog.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/watchdog.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/thermal.py

To incorporate the below changes in DellEMC S5232, Z9264, Z9332 platforms.
- Update thermal high threshold values
- Make watchdog API Python2 and Python3 compatible
- Fix LGTM alerts
- Z9264: Fix get_change_event timer value
- Use 'universal_newlines=True' in subprocess.Popen call.
- Change the timeout in 'get_change_event' to milliseconds to match specification in sonic_platform_common/chassis_base.py
Wrote a python script to load Chassis class and then call the APIs accordingly and verify the return type.
[UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/6033516/UT_logs.txt)
DellEMC: S5232, Z9264, Z9332 - Platform API fixes

DellEMC: S5232, Z9264, Z9332 - Platform API fixes

---

src/sonic-host-services/scripts/procdockerstatsd
src/sonic-host-services/tests/determine-reboot-cause_test.py
src/sonic-host-services/tests/procdockerstatsd_test.py
src/sonic-py-common/sonic_py_common/daemon_base.py

Migrate from using the `imp` module to using the `importlib` module. As of Python 3, the `imp` module has been deprecated in favor of the `importlib` module.
Eliminate all importing of the `imp` module, and replace all which were actually used with imports of the `importlib` module, and modify all affected code appropriately.
- Ensure determine-reboot-cause_test.py unit tests pass
- Ensure procdockerstatsd_test.py unit tests pass
- Ensure sonic_py_common.DaemonBase.load_platform_util() still functions correctly with old plugins (which are deprecated and will be removed soon anyway)

Use 'importlib' module in lieu of deprecated 'imp' module

---

platform/mellanox/hw-management/0003-Make-hw-mgmt-SimX-compatiable.patch
platform/mellanox/mlnx-fw-upgrade.j2

System is stuck on 'starting' state on SimX platform because of infinite loop on 'hw-management-ready.sh' script .
The loop is polling to check if the hw-mgmt sysfs created before proceeding with the flow, for SimX platform the sysfs will never create so the system is not starting properly.
Add a condition to poll on hw-mgmt sysfs only if the switch is real HW and not SimX platform.
Check "systemctl status hw-management.service" output on a SimX switch with this patch, the state will be "active".

[Mellanox] Add hw-mgmt patch for SimX platform adaptation

---

src/sonic-host-services/scripts/caclmgrd

What I did:-
- For multi-asic platforms added iptable v4 rule to communicate on docker bridge ip
- For multi-asic platforms extend iptable v4 rule for iptable v6 also
-  For multi-asic program made all internal rules applicable for all protocols (not filter based on tcp/udp). This is done to be consistent same as local host rule
- For multi-asic platforms made nat rule (to forward traffic from namespace to host) generic for all protocols and also use Source IP if present for matching
Why I did:
- We need iptable v4 rule to communicate on docker bridge ip since syslog on multi-asic platforms uses docker bridge ip and for 
host docker syslog is sent with both source and destination ip as docker bridge ip
- iptable v6 rules are added as  enhancement and to be symmetric as iptable v4 rules.
- …

[multi-asic] Enhanced iptable default rules

---

platform/mellanox/mlnx-platform-api/sonic_platform/component.py
platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py

In preparation for the merging of https://github.com/Azure/sonic-platform-common/pull/173, which properly defines class and instance members in the Platform API base classes.
It is proper object-oriented methodology to call the base class initializer, even if it is only the default initializer. This also future-proofs the potential addition of custom initializers in the base classes down the road.
Ensure the base class initializer is called in all concrete initializers
Run image on affected Mellanox platforms, ensure platform API continues to function properly

[Mellanox] Ensure concrete platform API classes call base class initializer

---

platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/watchdog.py
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/watchdog.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/watchdog.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/watchdog.py

In preparation for the merging of https://github.com/Azure/sonic-platform-common/pull/173, which properly defines class and instance members in the Platform API base classes.
It is proper object-oriented methodology to call the base class initializer, even if it is only the default initializer. This also future-proofs the potential addition of custom initializers in the base classes down the road.
Ensure the base class initializer is called in all concrete initializers
Run image on affected DellEMC platforms, ensure platform API continues to function properly

[DellEMC] Ensure concrete platform API classes call base class initializer

---

device/celestica/x86_64-cel_e1031-r0/sonic_platform/thermal.py
device/celestica/x86_64-cel_e1031-r0/sonic_platform/watchdog.py
device/celestica/x86_64-cel_seastone-r0/sonic_platform/thermal.py
device/celestica/x86_64-cel_seastone-r0/sonic_platform/watchdog.py
device/celestica/x86_64-cel_seastone_2-r0/sonic_platform_config/watchdog.py
device/celestica/x86_64-cel_silverstone-r0/sonic_platform/fan.py

In preparation for the merging of https://github.com/Azure/sonic-platform-common/pull/173, which properly defines class and instance members in the Platform API base classes.
It is proper object-oriented methodology to call the base class initializer, even if it is only the default initializer. This also future-proofs the potential addition of custom initializers in the base classes down the road.
Ensure the base class initializer is called in all concrete initializers
Run image on affected Celestica platforms, ensure platform API continues to function properly

[Celestica] Ensure concrete platform API classes call base class initializer

---

files/scripts/supervisor-proc-exit-listener

In the configuration of `rsyslog`, duplicate messages will be suppressed and reported in the format of `message repeated n times`.
Due to this behavior, if a critical process in a container exited unexpectedly, the alerting message will be written into syslog once
and not be written into syslog anymore until the second critical process exited. This PR aims to differentiate these alerting messages such that they will not be suppressed by `rsyslogd` and can appear in the syslog periodically.
This PR adds a counter into the alerting message and shows how many minutes a critical process was not running.
I verified and test this implementation on a physical DUT.
Feb 23 01:24:36.541111 str-dx010-acs-1 INFO lldp#supervisord 2021-02-23 01:24:36,540 …

[Supervisord] Deduplicate the alerting messages of critical processes from Supervisord.

---

dockers/docker-fpm-frr/frr/bgpd/templates/internal/peer-group.conf.j2
src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_back.conf
src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_front.conf

What I did:
Enable BBR config `allowas-in 1` for internal peers 
Why I did:
To advertise BBR routes learnt via e-BGP peer in one asic/namespace to another iBGP asic/namespace via Route Reflector.
How I Verify:
- Verify manually route advertisement.
- https://github.com/Azure/sonic-mgmt/pull/3022

[multi-asic] BBR support on internal-peers for multi-asic platfroms.

---

device/mellanox/x86_64-mlnx_msn4600-r0/pcie.yaml

PCIEd pollutes log with the next errors:
```
Feb 25 14:20:06.051698 sonic WARNING pmon#pcied[66]: PCIe Device: Ethernet controller: Mellanox Technologies Device cf70 Not Found
Feb 25 14:20:06.051698 sonic WARNING pmon#pcied[66]: PCIe Device: Ethernet controller: Intel Corporation I210 Gigabit Network Connection (rev 03) Not Found
Feb 25 14:20:06.052063 sonic ERR pmon#pcied[66]: PCIe device status check : FAILED
```
* To fix PCIEd log errors
* Fixed `pcie.yaml`
1. supervisorctl restart pcied
* N/A
```
'//||\\`
''``
```

[Mellanox]: Fix PCIEd config for SN4600

---

device/mellanox/x86_64-mlnx_msn4600c-r0/pcie.yaml

PCIEd pollutes log with the next errors:
```
Feb 25 14:20:06.051698 sonic WARNING pmon#pcied[66]: PCIe Device: Ethernet controller: Mellanox Technologies Device cf70 Not Found
Feb 25 14:20:06.051698 sonic WARNING pmon#pcied[66]: PCIe Device: Ethernet controller: Intel Corporation I210 Gigabit Network Connection (rev 03) Not Found
Feb 25 14:20:06.052063 sonic ERR pmon#pcied[66]: PCIe device status check : FAILED
```
* To fix PCIEd log errors
* Fixed `pcie.yaml`
1. supervisorctl restart pcied
* N/A
```
'//||\\`
''``
```

[Mellanox]: Fix PCIEd config for SN4600c

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/t0-sample-graph.xml
src/sonic-config-engine/tests/test_cfggen.py
src/sonic-config-engine/tests/test_minigraph_case.py

Some platforms have difficult to attach egress ACL to vlan.
For egress ACL attaching to vlan, break them into vlan members.
Unit test
Tested in DUT

[minigraph] For egress ACL attaching to vlan, break them into vlan members

---

files/build_templates/docker_image_ctl.j2

Put the fix https://github.com/Azure/sonic-buildimage/pull/6537 in 201911.

[teamd] Increase wait timeout for teamd docker stop to clean Port channels

---

build_debian.sh

As of the merging of PR https://github.com/Azure/sonic-buildimage/pull/6799, we are now installing a newer version of scapy via pip, therefore there is no longer a need to install the older Debian package.

[build] No longer install scapy Debian package in host

---

device/mellanox/x86_64-mlnx_msn4600-r0/ACS-MSN4600/hwsku.json
device/mellanox/x86_64-mlnx_msn4600-r0/platform.json

To add support for the dynamic breakout on Mellanox platform x86_64-mlnx_msn4600
Add the relevant files describing Mellanox platform x86_64-mlnx_msn4600 breakout modes to a new device folder.
System bringup is completed, all interfaces are up. 
Platform tests suits all is passing.

[DPB] [Mellanox] added capability files for SN4600 platform

---

src/sonic-config-engine/openconfig_acl.py
src/sonic-config-engine/sonic-acl-extension.yang

There is a bug in how pyangbind translates yang models into python bindings. The model always sets integer values to 0 by default, so there is no way to check if a user has provided a value that is equal to 0. This is problematic for ICMP and VLAN (among others) because 0 is a valid input value.
We also discovered that if the input is an integer and a string value is provided then the field will be silently ignored, which may be problematic in the case of ACL rules.
I converted ICMP and VLAN fields to `union` types so that `acl-loader` will treat them as null values unless a user explicitly adds an integer value.
Run `sonic-mgmt` tests to verify existing acl behavior is intact. See also new tests in …

[openconfig_acl] Allow setting ICMP type/code to 0

---

src/sonic-ctrmgrd/tests/common_test.py
src/sonic-host-services/tests/determine-reboot-cause_test.py
src/sonic-host-services/tests/procdockerstatsd_test.py
src/sonic-py-common/sonic_py_common/daemon_base.py

Fix a strange bug introduced by https://github.com/Azure/sonic-buildimage/pull/6832 which would only occur in environments with both Python 2 and Python 3 installed (e.g., the PMon container). Error messages such as the following would be seen:
```
ERR pmon#ledd[29]: Failed to load ledutil: module 'importlib' has no attribute 'machinery'
```
This is very odd, and it seems like the Python 2 version of importlib, which is basically just a stub, is taking precedence over the Python 3 version. I found that this occurs when calling `import importlib`. However, calling `import importlib.machinery` and `import importlib.util` causes the proper package to be referenced, and the `machinery` and `util` modules are loaded successfully. This is how it is specified in the official documentation, …

Fix Python 3 'importlib' bug; Add support for Python 2 back in sonic-py-common

---

platform/broadcom/sai.mk

This is to address the issue when "mmuconfig -p egress_lossy_profile" is executed which causes SYNCd failure with SAI_STATUS_INSUFFICIENT_RESOURCE for attr SAI_BUFFER_PROFILE_ATTR_RESERVED_BUFFER_SIZE.
This change also requires the change from (https://github.com/Azure/sonic-swss/pull/1649)
This SAI change was already tested as part of the (https://github.com/Azure/sonic-swss/pull/1649) PR.
Please refer to (https://github.com/Azure/sonic-swss/pull/1649) for details on the verification performed.
None.
Pick up fix for "mmuconfig -p egress_lossy_profile" causing SYNCd error SAI_STATUS_INSUFFICIENT_RESOURCE wit attr SAI_BUFFER_PROFILE_ATTR_RESERVED_BUFFER_SIZE (CS00011729558)

BRCM SAI 3.7.5.2-2 Pick up fix CS00011729558 SAI_STATUS_INSUFFICIENT_RESOURCE wit attr SAI_BUFFER_PROFILE_ATTR_RESERVED_BUFFER_SIZE

---

device/mellanox/x86_64-mlnx_msn2700_simx-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn3700_simx-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn4700_simx-r0/pmon_daemon_control.json

[thermalctld] Disable thermalctld on Mellanox simx platforms.
This commit is targeted to 201911 since master and 202012 already contain this content.
Signed-off-by: liora <liora@nvidia.com>
Service thermalctld should not run on simx systems.
Update simx systems pmon_daemon_control.json which is being written to supervisord.conf
Verify supervisord status that thermalctld is not running.
**- Which release branch to backport**
None

[thermalctld] Disable thermalctld on Mellanox simx platforms

---

src/sonic-config-engine/openconfig_acl.py
src/sonic-config-engine/sonic-acl-extension.yang

There is a bug in how pyangbind translates yang models into python bindings. The model always sets integer values to 0 by default, so there is no way to check if a user has provided a value that is equal to 0. This is problematic for ICMP and VLAN (among others) because 0 is a valid input value.
Because 201911 is still using python2, we need a separate PR from https://github.com/Azure/sonic-buildimage/pull/6932.
Generated the bindings for python2.
Run sonic-mgmt tests to verify existing acl behavior is intact. See also new tests in Azure/sonic-utilities#1469.

[201911][openconfig_acl] Allow setting ICMP type/code to 0

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/sonic-config-engine/tests/sample_output/py2/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/py2/bgpd_quagga.conf
src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay.supervisord.conf
src/sonic-config-engine/tests/sample_output/py2/frr.conf
src/sonic-config-engine/tests/sample_output/py2/ipinip.json
src/sonic-config-engine/tests/sample_output/py2/wait_for_intf.sh
src/sonic-config-engine/tests/sample_output/py3/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/py3/bgpd_quagga.conf
src/sonic-config-engine/tests/sample_output/py3/docker-dhcp-relay.supervisord.conf
src/sonic-config-engine/tests/sample_output/py3/frr.conf
src/sonic-config-engine/tests/sample_output/py3/ipinip.json
src/sonic-config-engine/tests/sample_output/py3/wait_for_intf.sh
src/sonic-config-engine/tests/t0-sample-graph.xml

It is possible to have DHCP relay configuration with no servers/
helpers which result in DHCP container to crash. This PR fixes this
issue by not starting DHCP relay for vlans with no DHCP helpers.
signed-of-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
resolves: #6931 
closes: #6931 
Do not add program group for dhcp relay with not dhcp helpers
Unit test

Start DHCP Relay When Helpers IPs Are Available

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/test_cfggen.py

To adjust config db generated via minigraph per matchmode changes in fine grained ecmp. The changes are done so that nexthop IP based filtering can occur to determine routes as requiring Fine Grained ECMP, in the past the only mode was to use the IP prefix of the route for filtering, with this matchmode change we will use nexthop IP based filtering
https://github.com/Azure/SONiC/pull/727
Change will modify config db entry created for FG_NHG to include 'match_mode': 'nexthop-based' so that nexthop IP based filtering can occur to determine routes as requiring Fine Grained ECMP. Changes also remove FG_NHG_PREFIX entry since its not needed under matchmode nexthop-based.
sonic-config-engine unit test

[minigraph] Adjust minigraph parsing per Fine Grained ECMP matchmode changes

---

device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8/hwsku.json

Additional file for DPB in order to support SKU SN2700-D40C8S8 on master
Add hwsku.json file
Enforce  "Mellanox-SN2700-D40C8S8 SKU on Master and see it works as expected, meaning:
Port 1/3 will be used as 4x10G
Port 2/4 - Not exist (blocked since 1 and 3 split to 4)
Port 7/8/9/10/23/24/25/26 will used as 100G
All other ports will be used as 2x50G
This PR should be added on top of PR:
https://github.com/Azure/sonic-buildimage/pull/6876
Adding hwsku.json file to SN2700-D40C8S8 SKU

[DPB] [Mellanox] added capability files for SN2700-D40C8S8 SKU

---

platform/vs/README.vsvm.md

Readme file should be updated with steps required to bring up multi-asic virtual switch.
Update readme file.
Follow the steps in the readme file to bring up multi-asic vs.

[multi-asic][vs]: Update readme file to create multi-asic vs

---

files/image_config/monit/conf.d/sonic-host

Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>
To run VNET route consistency check periodically.
For any failure, the monit will raise alert based on return code.
The tool will log required details.
Added configuration entry to "SONiC monit"
Configure VNET routes then remove some in ASIC_DB or APP_DB and verify logs for error messages.
- [] 201911
[monit] Periodically monitor VNET route consistency

[201911][monit] Periodically monitor VNET route consistency

---

files/image_config/monit/conf.d/sonic-host

Reverts Azure/sonic-buildimage#6819
This commit broke 201911 image. We need revert if non-critical.
```
$ which vnet_route_check.py
/usr/bin/vnet_route_check.py
$ sudo config load_minigraph
Reload config from minigraph? [y/N]: y
Executing stop of service telemetry...
Warning: Stopping telemetry.service, but it can still be activated by:
telemetry.timer
Executing stop of service restapi...
Executing stop of service swss...
Executing stop of service lldp...
Executing stop of service bgp...
Executing stop of service hostcfgd...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db
Running command: pfcwd start_default
Running command: config qos reload
Running command: /usr/local/bin/sonic-cfggen  -d -t …
```

Revert "[201911][monit] Periodically monitor VNET route consistency"

---

device/celestica/x86_64-cel_e1031-r0/sonic_platform/chassis.py
device/celestica/x86_64-cel_e1031-r0/sonic_platform/event.py
device/celestica/x86_64-cel_e1031-r0/sonic_platform/fan.py
device/celestica/x86_64-cel_e1031-r0/sonic_platform/helper.py
device/celestica/x86_64-cel_e1031-r0/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.install
platform/broadcom/sonic-platform-modules-cel/debian/rules
platform/broadcom/sonic-platform-modules-cel/services/platform_api/platform_api_mgnt.sh

- The xcvrd service requires an event detection function, unplug or plug in the transceiver.
- Add sysfs interrupt to notify userspace app of external interrupt
- Implement get_change_event() in chassis api.
- Also begin installing Python 3 sonic-platform package for Celestica platforms
- Verify xcvrd running with error in syslog
- Verify port status and port information with this following command
- `show interfaces status`
- `show interfaces transceiver eeprom`
- Log :
**Signed-off-by**: Wirut Getbamrung [wgetbumr@celestica.com]

[device/celestica]: Add xcvrd event support for Haliburton

---

src/isc-dhcp/patch/0009-Support-for-dual-tor-scenario.patch

Include all vlan interfaces into downstream interface set to allow each dhcp instance to scan over them. Note that with this change, downstream interface set includes not only vlan interfaces but also portchannels. However, this doesn't matter as dhcp uses giaddr or yiaddr to choose out interface.
Tested and verified on a virtual testbed.

dhcp for dual tor: include all vlan intf into downstream intf

---

dockers/docker-ptf/Dockerfile.j2

ref: https://bootstrap.pypa.io/2.7/get-pip.py
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/2.7/get-pip.py

Fix get-pip 2.7 url according to upstream announcement

---

files/build_templates/sonic_debian_extension.j2
src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py
src/sonic-ctrmgrd/ctrmgr/kube_commands.py
src/sonic-ctrmgrd/tests/kube_commands_test.py

We skip install of CNI plugin, as we don't need. But this leaves node in "not ready" state, upon joining master. 
To fix, we copy this dummy .conf file in /etc/cni/net.d
Keep this file in /usr/share/sonic/templates and copy to /etc/cni/net.d upon joining k8s master.
Upon configuring master-IP and enable join, watch node join and move to ready state.
You may verify using `kubectl get nodes` command

Copy dummy flannel.conf to get around absence of CNI Network

---

rules/phy-credo.mk

This package was outdated and did not properly install on buster due to dependency changes.
This version should work on all `DCS-7280CR3*-32[PD]4` platforms.
Make sure the phy-credo.service succeeds and that it initialized the phys by looking at the syslog
The version of this package is also outdated on 202012.
202012 currently has the same base image and dependencies that master and should install just fine.
Update phy-credo gearbox code

[Arista] Update phy-credo gearbox code

---

src/sonic-config-engine/sonic-cfggen

Closes issue https://github.com/Azure/sonic-buildimage/issues/6982.
The issue was root caused as we were using the unix_socket for reading from DB as a default mechanism (https://github.com/Azure/sonic-buildimage/pull/5250). The redis unix socket is created as follows. 
```
admin@str--acs-1:~$ ls -lrt /var/run/redis/redis.sock 
srwxrw---- 1 root redis 0 Mar  6 01:57 /var/run/redis/redis.sock
```
So it used to work fine for the user "root" or if user is part of redis group ( admin was made part of redis group by default )
Check if the user is with sudo permissions then use the redis unix socket, else fallback to tcp socket. 
Checked "show running all" command from a user which is not part of redis group.
- [ x] 201911
- [ x] 202006
- [x ] 202012

Control usage of unix socket on DB read.

---

rules/frr.mk

Update FRR to 7.5.1. The following is a list of new commits.
```
df7ab485b FRRouting Release 7.5.1
f4ed841b8 Merge pull request #8187 from opensourcerouting/rpmfixes-75
86d5a20e3 Merge pull request #8193 from mjstapp/fix_signals_7_5
b339cc149 lib: avoid signal-handling race with event loop poll call
0f7b432c3 lib: add debug output for signal mask
c0290c86d lib: add sigevent_check api
7a5348665 doc: Fix CentOS 7 Documentation
2a8e69f48 Merge pull request #8064 from donaldsharp/foo
cf4d1a744 redhat: Fix changelog incorrect date format
b78dcb209 Merge pull request #8181 from idryzhov/7.5-zebra-blackhole
2032e7e72 zebra: don't use kernel nexthops for blackhole routes
e52003567 bgpd: When deleting a neighbor from a peer-group the PGNAME is optional
aa86a6a6f Merge pull request #8161 from …
```

[frr]: upgrade frr to frr-7.5.1

---

dockers/docker-sonic-mgmt/Dockerfile.j2

sonic-mgmt-docker build was failing.
pin cryptography version to 3.3.2
build sonic-mgmt docker.

[sonic-mgmt docker] pin cryptography version to 3.3.2

---

platform/mellanox/mlnx-platform-api/sonic_platform/platform.py
platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
platform/mellanox/mlnx-platform-api/sonic_platform/utils.py

Recently, CLI sfputil replace the old sonic platform utils with sonic platform API. However, sonic platform API does not suport SFP low power mode and reset related operation. The PR is to fix it.
The change to replace platform utils with sonic platform API was reverted on 202012, once this PR is merged, we can cherry-pick these two PRs to 202012 together.
In low power mode and reset related operation, use "docker exec" if the command is running on host side.
Manual test

[Mellanox] Fixes issue: CLI sfputil does not work based on sonic platform API

---

platform/barefoot/sonic-platform-modules-bfn-montara/debian/postinst
platform/barefoot/sonic-platform-modules-bfn-montara/debian/prerm
platform/barefoot/sonic-platform-modules-bfn-montara/debian/rules
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py
platform/barefoot/sonic-platform-modules-bfn-newport/debian/rules
platform/barefoot/sonic-platform-modules-bfn-newport/debian/sonic-platform-modules-bfn-newport-as9516.postinst
platform/barefoot/sonic-platform-modules-bfn-newport/debian/sonic-platform-modules-bfn-newport-as9516.prerm
platform/barefoot/sonic-platform-modules-bfn-newport/debian/sonic-platform-modules-bfn-newport-as9516bf.postinst
platform/barefoot/sonic-platform-modules-bfn-newport/debian/sonic-platform-modules-bfn-newport-as9516bf.prerm
platform/barefoot/sonic-platform-modules-bfn/debian/postinst
platform/barefoot/sonic-platform-modules-bfn/debian/prerm
platform/barefoot/sonic-platform-modules-bfn/debian/rules

python2 eol
removed python2 support

[platform][barefoot] Drop python2 support

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/fan_drawer.py
platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/thermal.py

To support fan_drawer and thermal
[barefoot] Add support for fans and thermals to sonic_platform package

[barefoot][platform] Support fans and thermal

---

src/sonic-bgpcfgd/bgpmon/bgpmon.py

Why I did:
Fixes below exception on 201911. Master branch is fine.
```
Mar 11 16:37:09.247008 str2-nxxx-acs-3 INFO bgp3#supervisord: bgpmon Traceback (most recent call last):
Mar 11 16:37:09.247008 str2-nxxxx-acs-3 INFO bgp3#supervisord: bgpmon   File "/usr/local/bin/bgpmon", line 8, in <module>
Mar 11 16:37:09.251225 str2-nxxx-acs-3 INFO bgp3#supervisord: bgpmon
Mar 11 16:37:09.251225 str2-nxxx-acs-3 INFO bgp3#supervisord: bgpmon sys.exit(main())
Mar 11 16:37:09.252281 str2-nxxxx-acs-3 INFO bgp3#supervisord: bgpmon   File "/usr/local/lib/python2.7/dist-packages/bgpmon/bgpmon.py", line 156, in main
Mar 11 16:37:09.252281 str2-nxxxx-acs-3 INFO bgp3#supervisord: bgpmon
Mar 11 16:37:09.253009 str2-nxxxx-acs-3 INFO bgp3#supervisord: bgpmon syslog.syslog(syslog.LOG_ERR, "{}: error exit 1, …
```

[201911] Fix bgpmon.py syslog exception

---

platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_eeprom.py
platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_psu.py
platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py

- Python3 compatibility changes for PDDF eeprom class
- Adding API for temperature in PDDF psu class
- PEP8 standard changes and adding missing method in PDDF sfp class
- Using python3 to invoke the sonic_platform module in PDDF based platform
- Running autopep8 tool to comply to PEP8 standards
```
root@sonic:/home/admin# decode-syseeprom -s
781664X1827043
root@sonic:/home/admin# decode-syseeprom -p
7816-64X-O-AC-F
root@sonic:/home/admin# decode-syseeprom -m
3C:2C:99:F0:C5:80
```
```
root@sonic:/home/admin# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
>>> import sonic_platform
>>> ch = sonic_platform.platform.Platform().get_chassis()
>>> …
```

Few more python3 compatibility changes, PEP8 standard changes and add missing methods in PDDF common base APIs

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/bfn_extensions/platform_sensors.py

[platform][barefoot] Use urllib.parse.quote

---

device/dell/x86_64-dellemc_s5248f_c3538-r0/pmon_daemon_control.json

To skip thermalctld in DellEMC S5248F platform since it requires platform API.
Add 'skip_thermalctld:true' in pmon_daemon_control.json for DellEMC S5248F platform.
Verified thermalctld not running in PMON.
````
admin@S5248F-10860:~$ docker exec pmon ps -eaf
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Mar07 pts/0    00:01:48 /usr/bin/python3 /usr/local/bin/supervisord
root        23     1  0 Mar07 pts/0    00:00:21 python3 /usr/bin/supervisor-proc-exit-listener --container-name pmon
root        26     1  0 Mar07 pts/0    00:00:26 /usr/sbin/rsyslogd -n -iNONE
root        30     1  0 Mar07 pts/0    00:15:26 python2 /usr/local/bin/xcvrd
root        31     1  0 Mar07 pts/0    00:07:12 python2 /usr/local/bin/psud
root        32     1  0 Mar07 pts/0    00:03:04 …
```

Skip thermalctld for DellEMC S5248F platform

---

files/build_scripts/mask_disabled_services.py
src/sonic-host-services/.gitignore
src/sonic-host-services/pytest.ini
src/sonic-host-services/scripts/hostcfgd
src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
src/sonic-host-services/tests/hostcfgd/mock_configdb.py
src/sonic-host-services/tests/hostcfgd/test_vectors.py

Features may be enabled/disabled for the same topology based on run-time
configuration. This PR adds the ability to enable/disable feature based
on config db data.
Dual ToR topology have mux docker while non single ToR topology does not and hence the need to disable feature during run-time.
Added the ability to pass Jinja2 template to hostcfgd. The template could be as follows:
`"{% if 'subtype' in DEVICE_METADATA['localhost'] and DEVICE_METADATA['localhost']['subtype'] == 'DualToR' %}enabled{% else %}always_disabled{% endif %}"`
On Target:
Single ToR
```
admin@str-s6000-acs-14:~$ show feature statu
Feature     State            AutoRestart     SystemState    UpdateTime …
```

[hostcfgd]: Add Ability To Configure Feature During Run-time

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.postinst
platform/broadcom/sonic-platform-modules-cel/haliburton/script/reload_udev.sh

The udev rules does not work for sonic first boot.
Use udevadm to trigger the udev rules on the first boot
1. Connect C0 with E1031;
2. Install or upgrade the sonic os to 202012 branch;
3. When access to sonic  check if /dev/C0-1 to /dev/C0-48 are existed.

Fix E1031 udev rules not work for sonic os first boot after be installed

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2

Add -si support in dhcp docker template
Tested and verified on a vs testbed.

DHCP Relay: add -si support in dhcp docker template

---

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/sonic-config-engine/tests/sample_output/bgpd_frr.conf
src/sonic-config-engine/tests/sample_output/bgpd_quagga.conf
src/sonic-config-engine/tests/sample_output/docker-dhcp-relay.supervisord.conf
src/sonic-config-engine/tests/sample_output/frr.conf
src/sonic-config-engine/tests/sample_output/ipinip.json
src/sonic-config-engine/tests/sample_output/wait_for_intf.sh
src/sonic-config-engine/tests/t0-sample-graph.xml

It is possible to have DHCP relay configuration with no servers/
helpers which result in DHCP container to crash. This PR fixes this
issue by not starting DHCP relay for vlans with no DHCP helpers.
resolves: #6931
closes: #6931
Do not add program group for dhcp relay with not dhcp helpers
Unit test

Start DHCP Relay When Helpers IPs Are Available (#6961)

---

device/mellanox/x86_64-mlnx_msn3700-r0/pcie.yaml

[Mellanox]: Update addresses in PCIEd configuration file for SN3700 system.
To resolve an issue where we try to access not existing PCI address.
Update pcie.yaml with the right PCI addresses.
Check logs, operation occurs each minute.
N/A

[Mellanox]: Fix PCIEd configuration file for SN3700 system

---

src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
src/sonic-yang-models/tests/yang_model_tests/yangTest.json
src/sonic-yang-models/yang-models/sonic-acl.yang
src/sonic-yang-models/yang-models/sonic-device_neighbor.yang
src/sonic-yang-models/yang-models/sonic-interface.yang
src/sonic-yang-models/yang-models/sonic-loopback-interface.yang
src/sonic-yang-models/yang-models/sonic-port.yang
src/sonic-yang-models/yang-models/sonic-portchannel.yang
src/sonic-yang-models/yang-models/sonic-vlan.yang

To follow consistent naming-conventions for key-attributes of all different types of interfaces in sonic-yang-models
As discussed in the yang subgroup community meeting, this change is bring consistent naming-conventions for all different type  of interfaces in sonic-yang-model. Particularly the key-attribute name. Since the relevant interface container does have a context about that interface, having a simple & clear key-attribute name will be sufficient. For e.g. PORT/PORT_LIST/port_name has been renamed as PORT/PORT_LIST/name. Similar changes are done for portchannel, VLAN & loopback interfaces as well.

To follow consistent naming-conventions for key-attributes of all different types of interfaces in sonic-yang-models

---

files/image_config/procdockerstatsd/procdockerstatsd

Bug exists in 201911 branch where unit conversion for docker stats is incorrect. Both MiB/GiB to byes conversion is incorrect
Example: 
`admin@str-s6000-acs-10:/usr/bin$ docker stats --no-stream -a`
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e958c81d27a8        mgmt-framework      0.00%               0B / 0B               0.00%               0B / 0B             0B / 0B             0
9b6b7b4361d5        telemetry           3.13%               86.31MiB / 7.785GiB   1.08%               0B / 0B             0B / 106kB          30
e7fee0b617fe        snmp                70.28%              57.03MiB / 7.785GiB   0.72%               0B / 0B             0B / 102kB          9 …

[201911][procdockerstatsd] Fix unit conversion for docker stats

---

dockers/docker-fpm-frr/frr/bgpd/templates/internal/instance.conf.j2
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_back_v6.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v4.conf
src/sonic-bgpcfgd/tests/data/internal/instance.conf/result_front_v6.conf

It was observed that on a multi-asic DUT bootup, the BGP internal sessions between ASIC's was taking more time to get ESTABLISHED than external BGP sessions. The internal sessions was coming up almost exactly 120 secs later. 
In multi-asic platform the bgp dockers ( which is per ASIC ) on switch start are bring brought up around the same time and they try to make the bgp sessions with neighbors (in peer ASIC's) which may be not be completely up. This results in BGP connect fail and the retry happens after 120sec which is the default **Connect Retry Timer**
Add the command to set the bgp neighboring session retry timer to 10sec for internal bgp neighbors.
With this fix the sessions come up along with external BGP neighboring sessions 
Before the fix:
```
Neighbhor      V     AS    MsgRcvd …
```

Decrease Connect Retry Timer for internal bgp neighbors.

---

platform/vs/docker-gbsyncd-vs/supervisord.conf

Eliminate the need for `gbsyncd_start.sh`, which simply calls `exec "/usr/bin/gbsyncd_startup.py"`. The shell script is unnecessary.
Once this PR merges, we can remove `gbsyncd_start.sh` from the sonic-sairedis repo.

[docker-gbsyncd-vs] Run gbsyncd_startup.py directly

---

src/isc-dhcp/patch/0012-add-option-si-to-support-using-src-intf-ip-in-relay.patch
src/isc-dhcp/patch/series

add option -si to support using src intf ip in relay
Tested and verified on a vs testbed.

DHCP Relay: add option -si to support using src intf ip in relay

---

device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/sai_2010.xml
device/mellanox/x86_64-mlnx_msn2100-r0/ACS-MSN2100/sai_2100.xml
device/mellanox/x86_64-mlnx_msn2410-r0/ACS-MSN2410/sai_2410.xml
device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/sai_2700.xml
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-C28D8/sai_2700_8x50g_28x100g.xml
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8/sai_2700_8x100g_40x50g_8x10g.xml
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai_2700_48x50g_8x100g.xml
device/mellanox/x86_64-mlnx_msn2740-r0/ACS-MSN2740/sai_2740.xml

SAI profile files speed configuration have wrong bitmap value for 10/50G speed option.
Fix to the correct value for all SPC1 devices.
Configure on these platforms ports with 10/50G speed using this fix.

[Mellanox] [201911] Fix for all SPC1 devices sai profile speed configurations

---

platform/mellanox/mlnx-platform-api/sonic_platform/led.py

The existing Fan led and Psu led object initialize itself to green color in __init__ method. However, there are multiple daemons calls sonic platform API and there could be a case that:
1. A PSU is removed from system
2. Reboot switch
3. psud detects that 1 PSU is missing and set PSU led to red
4. Other daemon just start up and call sonic platform API, the API set PSU led to green by call PsuLed.__init__
This PR is a partial fix for the issue. As we also need guarantee that the led is initialized with a correct value. I checked existing psud and thermalctld code. psud always initialize the PSU led color on boot up, thermalcltd need some changes to initialize led color on the first run
Remove the led color initialization code from FanLed.__init__ and PsuLed.__init__
Manual test

[Mellanox] Fix issue: should not initialize led color in __init__ funcation as platform API will be called by multiple daemons

---

.azure-pipelines/run-test-template.yml

gzip vm image disk and memdmp to save download time

[ci]: gzip the vm image disk and memdmp

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py

In order to reduce Chassis object initialization time
Initialize fans and thermals lists on demand; make them properties
Initialize fans and thermals lists on demand to reduce Chassis object initialization time

[platform][barefoot] Lazy initialize fans and thermals list

---

files/image_config/procdockerstatsd/procdockerstatsd

Fixing same issue in 201911 as mention here https://github.com/Azure/sonic-buildimage/pull/7151

[201911][procdockerstatsd] Add missing unit conversion

---

platform/barefoot/.gitignore
platform/barefoot/bfn-modules/configs/bfn-modules.conf
platform/barefoot/bfn-modules/debian/install

* add '.gitignore' to the 'barefoot' subdirectory to overwrite ignore "platform/**/debian/*" in the root directory
The psample module was not loaded on barefoot platform. The loading of this module is a prerequisite for testing SFlow.
Update SONiC build/packaging scripts to install 'psample.ko' on BFN platform boot.
Do the command after booting SONiC:
`lsmod | grep psam`
psample module must be loaded
`psample                20480  0 `

Add 'psample' module to load at boot time on BFN platform

---

dockers/docker-fpm-frr/frr/bgpd/templates/general/instance.conf.j2
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_all_v4.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_all_v6.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_base_v4.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_base_v6.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_l2vpn.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_shutdown_1.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_shutdown_2.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_timers_1.conf
src/sonic-bgpcfgd/tests/data/general/instance.conf/result_timers_2.conf

The default bgp connect retry timer is 120 seconds. A reconnection will happen 120 seconds if the initial connection fails. This PR aims to allow a more frequent retry.
Reduce bgp connect retry timer for general template to 10 seconds.
Verify that bgp neighbor has bgp connect retry timer of 10 seconds:
```
BGP Connect Retry Timer in Seconds: 10
```

Reduce bgp connect retry timer for general template

---

platform/vs/docker-gbsyncd-vs/critical_processes
platform/vs/docker-gbsyncd-vs/supervisord.conf

To improve management of docker-gbsyncd-vs. `gbsyncd_startup.py` simply spawned syncd processes and then exited. In that case, supervisord would no longer manage any processes in the container, and thus there was no way to know if a critical process had exited.
I recently created `gbsyncdmgrd` to be a more complete, robust replacement for `gbsyncd_startup.py`.
NOTE: This PR is dependent on the inclusion of `gbsyncdmgrd` in the sonic-sairedis repo. A submodule update is pending at 
https://github.com/Azure/sonic-buildimage/pull/7089
Replace references to `gbsyncd_startup.py` with `gbsyncdmgrd`.
Ensure gbsyncdmgrd spawns all applicable syncd processes, and that it will exit if any of the syncd subprocesses exits.

[docker-gbsyncd-vs] Run new gbsyncdmgrd in lieu of deprecated gbsyncd_startup.py

---

platform/broadcom/sai.mk

To add latest SAI drop REL_4.3.3.3 to SONIC which addresses the following CSP cases:
- CS00012058054: [4.3][IPinIP][TTL-PIPE] IPinIP TTL Pipe Mode is NOT working it is behaving UNIFORM mode even programed as PIPE mode
- CS00011227466: [4.3] Warmboot support with tunnel encap
Updated bcmsai to latest sai drop version 4.3.3.3
Ran basic test cases and running regression as well.
Updated bcmsai to latest sai drop version 4.3.3.3

Updated BRCM SAI to latest drop REL_4.3.3.3

---

src/sonic-yang-models/tests/yang_model_tests/yangTest.json

* IPV4ANY is not valid value, fix to IPv4ANY
* without this change, test case failed sometimes when the validation on IP_TYPE happens first and then PACKET_ACTION.
```
INFO:YANG-TEST:
------------------- Test 10: Configure undefined packet_action in ACL_RULE table.---------------------
INFO:YANG-TEST:{"sonic-port:sonic-port": {"sonic-port:PORT": {"PORT_LIST": [{"admin_status": "up", "description": "Ethernet0", "mtu": 9000, "alias": "eth0", "speed": 25000, "port_name": "Ethernet0"}, {"admin_status": "up", "description": "Ethernet1", "mtu": 9000, "alias": "eth1", "speed": 25000, "port_name": "Ethernet1"}]}}, "sonic-acl:sonic-acl": {"sonic-acl:ACL_TABLE": {"ACL_TABLE_LIST": [{"stage": "EGRESS", "type": "L3", "ACL_TABLE_NAME": "NO-NSW-PACL-V4", "ports": ["Ethernet0", "Ethernet1"], …
```

[sonic-yang-models] fix ip_type value in test cases

---

dockers/docker-database/supervisord.conf.j2
dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
dockers/docker-fpm-frr/supervisord.conf
dockers/docker-fpm-gobgp/supervisord.conf
dockers/docker-fpm-quagga/supervisord.conf
dockers/docker-lldp-sv2/supervisord.conf.j2
dockers/docker-nat/supervisord.conf
dockers/docker-orchagent/supervisord.conf
dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
dockers/docker-router-advertiser/docker-router-advertiser.supervisord.conf.j2
dockers/docker-sflow/supervisord.conf
dockers/docker-snmp-sv2/supervisord.conf
dockers/docker-sonic-mgmt-framework/supervisord.conf
dockers/docker-sonic-restapi/supervisord.conf
dockers/docker-sonic-telemetry/supervisord.conf
dockers/docker-teamd/supervisord.conf
platform/barefoot/docker-syncd-bfn/supervisord.conf
platform/broadcom/docker-syncd-brcm/supervisord.conf
platform/cavium/docker-syncd-cavm/supervisord.conf
platform/centec/docker-syncd-centec/supervisord.conf
platform/innovium/docker-syncd-invm/supervisord.conf
platform/marvell-arm64/docker-syncd-mrvl/supervisord.conf
platform/marvell-armhf/docker-syncd-mrvl/supervisord.conf
platform/marvell/docker-syncd-mrvl/supervisord.conf
platform/mellanox/docker-syncd-mlnx/supervisord.conf
platform/nephos/docker-syncd-nephos/supervisord.conf
platform/vs/docker-syncd-vs/supervisord.conf
src/sonic-config-engine/tests/sample_output/docker-dhcp-relay.supervisord.conf

Backport of https://github.com/Azure/sonic-buildimage/pull/7083 to the 201911 branch.
To prevent error [messages](https://dev.azure.com/mssonic/build/_build/results?buildId=2254&view=logs&j=9a13fbcd-e92d-583c-2f89-d81f90cac1fd&t=739db6ba-1b35-5485-5697-de102068d650&l=802) like the following from being logged:
```
Mar 17 02:33:48.523153 vlab-01 INFO swss#supervisord 2021-03-17 02:33:48,518 ERRO pool supervisor-proc-exit-listener event buffer overflowed, discarding event 46
```
This is basically an addendum to https://github.com/Azure/sonic-buildimage/pull/5247, which increased the event buffer size for dependent-startup. While supervisor-proc-exit-listener doesn't subscribe to as many events as dependent-startup, there is still a chance some containers (like swss, as in the example above) …

[201911][dockers][supervisor] Increase event buffer size for process exit listener; Set all event buffer sizes to 1024

---

scripts/versions_manager.py

py2/py3 packages names are case insensitive, and the versions map
key should be the same for packages whose name can have different cases.
For example, in files/build/versions/default/versions-py3, package
"click==7.1.2" is pinned; and in
files/build/versions/dockers/docker-sonic-vs/versions-py3, package
"Click==7.0" is pinned.
Without this fix, the aggregated versions-py3 file used for building
docker-sonic-vs looks like below:
...
click==7.1.2
Click==7.0
...
However, we actually want "click==7.0" to overwrite "click==7.1.2" for
docker-sonic-vs build.

Update versions_manager.py to make versions map key unique

---

dockers/docker-sonic-restapi/supervisord.conf

`go-server-server` doesn't start in `restapi` container.  
`restapi` is `docker-config-engine-stretch` base container, and it has no `Python3` but only `Python2`.
I changed from `python3` to `python` in `supervisord.conf`.
`go-server-server` starts in `restapi` container, if specified `RESTAPI` configs in `/etc/sonic/config_db.json`.
```
$ show services
...<snip>
restapi docker
---------------------------
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  59276 21512 pts/0    Ss+  Mar12   1:05 /usr/bin/python /usr/local/bin/supervisord
root        12  0.0  0.0 262988  3592 pts/0    Sl   Mar12   0:00 /usr/sbin/rsyslogd -n -iNONE
root        24  0.0  0.1 1010616 19320 pts/0   Sl   Mar12   0:03 /usr/sbin/go-server-server -enablehttp=true …
```

fix restapi startup

---

files/build_templates/docker_image_ctl.j2

System lag in VOQ based chassis systems requires unique id for system port aggregator id attribute in LAG object.
This id is generated by lag id generator within set boundary. The boundaries are system capability specific and should
be set during system boot. 
Ref: https://github.com/Azure/SONiC/pull/697
Changes for setting platform specific lag id boundary id in the chassis
app db. The platform specific lag id boundaries are supplied via
chassisdb.conf in the supervisor card. The lag_id_start and lag_id_end boundary values sourced
from this file are set in chassis app db which will be used by lag id
allocator to allocate unique lag id in atomic fashion
- Update chassisdb.conf in supervisor card with two parameters …

[voq/systemlag] Lag id boundary setting for system lag functionality

---

device/barefoot/x86_64-accton_as9516_32d-r0/pmon_daemon_control.json

Temporary skip psud  for Newport.
Temporary skip psud for Newport, for Barefoot needs.
Temporary skip psud for Newport, for Barefoot needs.

[device][barefoot] Skip psud for Newport

---

src/thrift/Makefile
src/thrift/patch/0002-cve-2017-1000487.patch

Plexus-utils before 3.0.16 is vulnerable to command injection because it does not correctly process the contents of double quoted strings.
Upgrade to 3.0.16

Fix CVE-2017-1000487 security alert

---

dockers/docker-lldp/lldpmgrd
dockers/docker-lldp/supervisord.conf.j2
platform/vs/docker-sonic-vs/start.sh
src/sonic-py-common/sonic_py_common/interface.py

Inband port can be made available in PORT table. But regular port handlngs are
not applicable for Inband port.
Changes in this PR are to make LLDP to consider Inband port and to avoid regular
port handling on Inband port.
Currently the Inband interface is used for VOQ chassis systems for asic to asic communications.
Ref: VOQ HLD https://github.com/Azure/SONiC/blob/master/doc/voq/voq_hld.md
- Changes done in supervisor conf for LLDP to include Inband in the interface list
- Changes done in platform common files to handle Inand port similar to how backplane port is handled
- Expose a port with name prefixed with "Inband" to SONiC via port_config.ini
- Have an entry in the PORT table for this port with name "Inband"
- When the …

[voq/inbandif] Support for inband port as regular port

---

files/image_config/monit/container_checker

Since we introduced a new value `always_disabled` for the `state` field in `FEATURE` table, the `expected` running container list
should exclude the `always_diabled` containers. This bug was found by nightly test and posted at here: [issue](https://github.com/Azure/sonic-buildimage/issues/7210). This PR fixes #7210.
I added a logic condition to decide whether the value of `state` field of a container was `always_disabled` or not. 
I verified this on the device `str-dx010-acs-1`.
- [ x] 202012

[container_checker] Exclude the 'always_disabled' container from expected running container list

---

src/sonic-device-data/tests/media_checker

- Build failure were seen in https://github.com/Azure/sonic-buildimage/pull/6984 as media settings test case is not updated and resulting in unknown fields error.
- Added the media settings fields in device data test case. 
- Verify whether sonic-device deb is built.

Update Media settings test case

---

platform/broadcom/sai.mk

This is the new BRCM SAI drop that potentially  have addressed the following CSP Cases:
```
[4.3] INFO level syslogs from SAI apiCS00011610083
[4.3][TH][VxLAN Decap] VxLAN Decap Test failed on 4.3CS00011976879
[4.3] Do not re-encap vxlan/IPinIP decap packetsCS00011193634
[4.3][WARMBOOT] SAI failed at warmboot pre-shutdown stage with "SAI_API_ACL:_brcm_sai_free_hostif:10237 field range destroy failed
[4.3] Need to support MMU profile for TH3CS00011817704 
[4.3][ACL] Adding an ACL matching ICMP packets without specifying an IP_PROTOCOL value fails.CS00012059079 
[4.3] Support DHCPv6 relayCS00011817771
[4.3] [ECMP] Unable to create ECMP group with Tunnel NH memberCS00011833367
```
Once we have this PR merged, will validate each one of the above to ensure they are indeed fixed...
Preliminary …

BRCM SAI 4.3.3.4 Pick up 8 major bug fixes

---

.azure-pipelines/build-template.yml

get build logs when build fails for debugging

[ci]: get build logs when build fails

---

installer/x86_64/install.sh

The motivation of these changes is to fix (https://github.com/Azure/sonic-buildimage/pull/6051):
```bash
root@sonic:/home/admin# sonic_installer install sonic-mellanox.bin
New image will be installed, continue? [y/N]: y
Installing image SONiC-OS-SONIC.202012.50-50e4cc15 and setting it as default...
Command: ./sonic-mellanox.bin
/tmp/tmp.jLYyWStLHy/installer/install.sh: 547: /tmp/tmp.jLYyWStLHy/installer/install.sh: [[: not found
```
* To fix CPU cstates configuration
* Updated code to be POSIX compatible 
1. root@sonic:/home/admin# sonic_installer install sonic-mellanox.bin
* N/A
``` …
```

[install.sh] Fix CPU cstates configuration

---

src/sonic-config-engine/config_samples.py
src/sonic-config-engine/tests/sample_output/py2/l2switch_dualtor.json
src/sonic-config-engine/tests/sample_output/py3/l2switch_dualtor.json
src/sonic-config-engine/tests/test_j2files.py

* L2 switch mode support is needed for dual ToR devices
* When generating L2 preset, check for dual ToR setting from CLI option
* `-a '{"is_dualtor": true}'`
* When dual ToR is specified, add `subtype` field to `DEVICE_METADATA` table
* When dual ToR is specified, add `MUX_CABLE`, `TUNNEL`, and `PEER_SWITCH` tables
Run the sonic-config-engine tests

[sonic-config-engine]: Update L2 preset for dualtor

---

src/system-health/health_checker/hardware_checker.py

ASIC key used in system health daemon is not present in Dell platforms.
Fixes https://github.com/Azure/sonic-buildimage/issues/6343 
Got the thermal sensor list using 2.0 API and retrieved the ASIC keys.
Check "show system-health summary/detail/monitor-list" 
Get the platform based ASIC keys used in thermal sensor list.
UT logs:
[system_health_UT.txt](https://github.com/Azure/sonic-buildimage/files/5867573/system_health_UT.txt)

System Health: Fix ASIC key issue in Dell platform

---

sonic-slave-stretch/Dockerfile.j2

Add this package to help https://github.com/Azure/sonic-utilities/pull/1547
Only needed on 201911 branch because future branchs build sonic-utilities in sonic-slave-buster.

Add deepdiff python package for sonic-utilities test

---

dockers/docker-orchagent/base_image_files/monit_swss

Avoid the following error messages while dynamic buffer calculation is enabled
```
ERR monit[491]: 'swss|buffermgrd' status failed (1) -- '/usr/bin/buffermgrd -l' is not running in host
```
Change `/usr/bin/buffermgrd -l` to `/usr/bin/buffermgrd`. The buffermgrd is started by `-l` for traditional model or `-a` for dynamic model.
So we need to use the common section of both.
Manually test.

[monit] Avoid monit error log by removing "-l" from monit_swss|buffermgrd

---

device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/fabriclanemap.ini
src/sonic-device-data/src/sai.vs_profile

Signed-off-by: ngocdo <ngocdo@arista.com>
This PR will add fabric lane mapping for vs tests. The fabric lane mapping will be used by vslib similarly it is doing with front panel lane mapping.
The lane mapping has lane for 16 fabric ports. Each port has one lane.
This PR is part of fabric support on Sonic, together with https://github.com/Azure/sonic-swss/pull/1459.

Add fabric lane mapping to vs Force10-S6000 sai.profile

---

platform/mellanox/mlnx-platform-api/sonic_platform/platform.py

There was a change to replace platform utils with sonic platform API in psuutil. However, psu API is not initialized on host side. The PR is to fix it.
Backport of https://github.com/Azure/sonic-buildimage/pull/7016 to the 202012 branch.
Initialize PSU API on both host and non-host side
Manual test

[Mellanox] [202012] Initialize PSU API on both host and docker side

---

platform/mellanox/mlnx-fw-upgrade.j2

Basically mlnx-fw-upgrade.sh is used in two places:
1. https://github.com/Azure/sonic-buildimage/blob/201811/files/scripts/syncd.sh#L109
```bash
/usr/bin/mst start
/usr/bin/mlnx-fw-upgrade.sh
/etc/init.d/sxdkernel start
/sbin/modprobe i2c-dev
```
2. https://github.com/Azure/sonic-buildimage/blob/201811/device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot#L32
```bash
ParseArguments "$@"
${FW_UPGRADE_SCRIPT} --upgrade --verbose
EXIT_CODE="$?"
```
In first case the `stdout` is redirected to `syslog` directly by `systemd`.
Thus, the `syslog` logger is only required in second case.
* To improve ASIC/CPLD FW upgrade logging
* To improve CPLD upgrade time
* Added `syslog` logger support
* Replaced `_pciconf0` -> `_pci_cr0` to reduce CPLD …

[Mellanox] Improve FW upgrade logging: add syslog logger

---

build_debian.sh
installer/x86_64/install.sh

Update systemd to v247 in order to pick the fix for "core: coldplug possible nop_job" https://github.com/systemd/systemd/pull/13124
Install systemd, systemd-sysv from buster-backports. Pass "systemd.unified_cgroup_hierarchy=0" as kernel argument to force systemd to not use unified cgroup hierarchy, otherwise dockerd won't start https://github.com/moby/moby/issues/16238.
Also, chown $FILSYSTEM_ROOT for root, otherwise apt systemd installation complains, see similar https://unix.stackexchange.com/questions/593529/can-not-configure-systemd-inside-a-chrooted-environment
Install on the switch, perform basic sanity tests/
Update systemd to v247

[debian] install systemd version 247 from buster-backports

---

build_debian.sh

Default  groupadd for redis, takes 1000 by default. This forces, subsequently created admin group to get 1001.
As all TACACS users are created with 1000 as their gid, they end up in redis group.
Explicitly provide the gid for redis group.
Check /etc/group & group of RW users via TACACS
```
admin@str-s6000-acs-9:~$ cat /etc/group | grep -e "admin\|redis"
sudo:x:27:admin,user_rw
docker:x:999:admin,user_rw
redis:x:1001:admin               --- takes 1001
admin:x:1000:                       --- retains 1000
admin@str-s6000-acs-9:~$
admin@str-s6000-acs-9:~$ ls -l /home
total 4
drwxr-xr-x 2 admin   admin   66 Apr  7 14:53 admin
drwxr-xr-x 2 user_rw admin 4096 Apr  7 15:47 user_rw  -- RW user get admin group
```
- [x ] 201911
- [x ] 202006
- [x ] 202012

[baseimage]: specify gid for redis group.

---

platform/pddf/i2c/utils/pddf_util.py

2.0 Platform APIs python3 wheel package should get installed on the HOST as well as PMON docker
Adjusting the PDDF utility with python3 commands
Check for the python3 package installation on a PDDF supported platform
```
root@sonic:/home/admin# pip3 show sonic-platform
Name: sonic-platform
Version: 1.0
Summary: SONiC platform API implementation on Accton Platforms
Home-page: https://github.com/Azure/sonic-buildimage
Author: SONiC Team
Author-email: linuxnetdev@microsoft.com
License: Apache 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires:
Required-by:
root@sonic:/home/admin# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
>>> import sonic_platform
>>> ch = …
```

Invoking python3 installation for PDDF 2.0 PAI package

---

src/sonic-ctrmgrd/setup.py
src/sonic-ctrmgrd/tests/common_test.py
src/sonic-ctrmgrd/tests/container_test.py
src/sonic-ctrmgrd/tests/ctrmgr_tools_test.py
src/sonic-host-services/setup.py
src/sonic-host-services/tests/determine-reboot-cause_test.py
src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
src/sonic-host-services/tests/procdockerstatsd_test.py
src/sonic-py-common/sonic_py_common/daemon_base.py
src/sonic-py-common/sonic_py_common/general.py

To eliminate the need to write duplicate code in order to import a Python module from a source file.
Add `general` module to sonic-py-common, which contains a `load_module_from_source()` function which supports both Python 2 and 3.
Call this new function in:
- sonic-ctrmgrd/tests/container_test.py
- sonic-ctrmgrd/tests/ctrmgr_tools_test.py
- sonic-host-services/tests/determine-reboot-cause_test.py
- sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- sonic-host-services/tests/procdockerstatsd_test.py
- sonic-py-common/sonic_py_common/daemon_base.py

[sonic-py-common] Add 'general' module with load_module_from_source() function

---

sonic-slave-stretch/Dockerfile.j2

Fix #7248 
Issue is similiar to martinblech/xmltodict#47
The correct solution is to change mockredispy to move 
nose from setup_requirement to test_requirement.
The quick workaround is to install nose explicitly.
fix build issue:
05:09:37    Downloading mockredispy-2.9.3.tar.gz (17 kB)
05:09:39  ?[91m    ERROR: Command errored out with exit status 1:
05:09:39       command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sypos2ry/mockredispy_ab86cd14995544df90f78a63ab7041a3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sypos2ry/mockredispy_ab86cd14995544df90f78a63ab7041a3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' …

[sonic-slave-stretch]: use pip to install nose package directly

---

dockers/docker-router-advertiser/docker-init.sh

[PR:4599](https://github.com/Azure/sonic-buildimage/pull/4599) changed startup
script name from wait_for_intf.sh.j2 to wait_for_link.sh.j2, however
when [PR:5178](https://github.com/Azure/sonic-buildimage/pull/5178) was cherry-
picked, the script name was not changed to wait_for_link.sh.

[201911][radv] Fix Script Name Change

---

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py

Fixes https://github.com/Azure/sonic-buildimage/issues/7162
The platform name for MSN4600C in sfputil pliugin is not complete:  "x86_64-mlnx_msn4600c" -> "x86_64-mlnx_msn4600c-r0"
Correct the platform name
run "sfputil show presence" command

[Mellanox] Fix incomplete platform name for MSN4600C in sfputil plugin

---

src/sonic-py-common/sonic_py_common/task_base.py

Allowing an application to set a stop timeout for processes and threads provides the following benefits:
1. Prevents the application from hanging indefinitely in the case a process or thread does not exit
2. Allow ProcessTaskBase a chance to let the process exit gracefully before attempting to kill it
Default values are as follows:
- ProcessTaskBase: 1 second
- ThreadTaskBase: No timeout
- Add optional `stop_timeout_secs` parameter to initializers of ProcessTaskBase and ThreadTaskBase
- Additionally:
- Prefix private attributes with an underscore
- Remove obsolete comments
Create concrete implementations of the classes and test the timeout functionality.

[sonic-py-common.task_base] Provide ability to set stop timeouts

---

dockers/docker-fpm-frr/TS
dockers/docker-fpm-frr/TSA
dockers/docker-fpm-frr/TSB
dockers/docker-fpm-frr/TSC

With the latest 201911 image, the following error was seen on staging devices with TSB command ( for both single asic, multi asic ). Though this err message doesn't affect the TSB functionality, it is good to fix.
```
admin@STG01-0101-0102-01T1:~$ TSB
BGP0 : % Could not find route-map entry TO_TIER0_V4 20
line 1: Failure to communicate[13] to zebra, line: no route-map TO_TIER0_V4 permit 20
% Could not find route-map entry TO_TIER0_V4 30
line 2: Failure to communicate[13] to zebra, line: no route-map TO_TIER0_V4 deny 30
```
In addition, in this PR I am fixing the message displayed to user when there are no BGP neighbors configured on that BGP instance. In multi-asic device there could be case where there are **no BGP neighbors** configured on a particular ASIC **(in BGP2 in below …

BGP TSA/B/C : Handler error message seen with TSB command.

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/azure-pipelines-image-template.yml

It is to fix the wrong usage of the build parameter in the azure pipelines' template. The build parameter PLATFORM=XXX can only be set when making configure (by command make configuration). To build platform images, we should avoid to set the value.
make PLATFORM=vs configuration
Bad usage:
make PLATFORM=vs  target/sonic-vs.img.gz
Good usage:
make target/sonic-vs.img.gz
Change the environment PLATFORM to PLATFORM_AZP to avoid to pass the parameter.

[CI] Fix the wrong environment variable PLATFORM passing into the slave container issue

---

build_debian.sh

Seeing this error intermittently:
```
+ sudo https_proxy= LANG=C chroot ./fsroot easy_install pip==20.3.3
Searching for pip==20.3.3
Reading https://pypi.python.org/simple/pip/
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for pip==20.3.3
error: Could not find suitable distribution for Requirement.parse('pip==20.3.3')
```
How I fix:
- Install `python-pip` via apt-get
- Pin the version to 20.3.3
- Master has same changes.
How I verify:
- Build is sucessfull
```
admin@str-sxxxx-xx-2:~$ pip --version
pip 20.3.3 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

[201911] Fix easy_install error when installing pip

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/azure-pipelines-image-template.yml

Fix the wrong build options and improve display name for some tasks
1. Fix the wrong build architecture for arm64 and armhf
2. Fix the build timeout parameter
See the build below, arm64/armhf option is correct after applying the fix.
Centec-arm64: https://dev.azure.com/mssonic/build/_build/results?buildId=10483&view=logs&j=88e1b2d1-110a-5bbf-c794-091704096bca&t=41cf5733-fbe6-5db0-23ba-ae081db3aefb
Marvell-armhf: https://dev.azure.com/mssonic/build/_build/results?buildId=10485&view=logs&j=268525a4-f0a8-5106-2898-2602f02ebdb0&t=6a001da7-517d-5aaf-2db9-5992b323c8e5

[ci] Fix the wrong build options issue

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-metadata.xml
src/sonic-config-engine/tests/test_cfggen.py

So that downstreamsubrole values can be used for policies
Added downstream_subrole to DEVICE_METADATA section of config_db
Unit testing in sonic-config-engine

[minigraph] Add downstreamsubrole parsing to minigraph.py

---

installer/arm64/install.sh
installer/armhf/install.sh
installer/x86_64/install.sh

This improvement reads current SONiC version directly from `/proc/cmdline`.
it supports `grub/aboot/uboot` bootloaders.
**Code snippet**:
```bash
cat /proc/cmdline | sed -n 's/^.*loop=\/*image-\(\S\+\)\/.*$/\1/p'
```
**Description**:
```
-n         don't print lines
s          substitute
^.*        matches anything before the <image_version>
loop=      matches <loop> kernel parameter
\/*image-  matches <image_version> prefix
\(\S\+\)   matches <image_version> group and assigns it to \1
\/.*$      matches anything after the <image_version>
\1         replace everything with <image_version>
p          print it
```
closes #6267
* To fix #6267
* Fixed installer scripts
1. Write invalid SONiC version to sonic_version.yml
2. Run SONiC-To-SONiC …

[installer]: Prevent filesystem corruption

---

.azure-pipelines/azure-pipelines-image-template.yml

Fix the SONiC version starting with HEAD issue. For example, sonic-broadcom-HEAD.40620469-1d98d18cf.bin.
Set the correct branch name after the code checked out.
After applied the change "git checkout -b 201911", the version is good.
```
$ git branch
* (HEAD detached at cf54cbc5)
$ sonic_get_version
HEAD.0-cf54cbc5
$ git checkout -b 201911
Switched to a new branch '201911'
$ sonic_get_version     
201911.0-cf54cbc5
```

Fix the SONiC version starting with HEAD issue

---

device/dell/x86_64-dell_s6100_c2538-r0/plugins/sfputil.py
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh

- xcvrd crash was seen in latest 201811 images.
- For Dell S6100,API 2.0 uses poll mode while 1.0 was still using interrupt mode.
- Modified get_transceiver_change_event in 1.0 to poll mode.
- Do OIR testing, check xcvrd status and syslogs.
[UT:]
[s6100_xcvr_UT.txt](https://github.com/Azure/sonic-buildimage/files/6305328/s6100_xcvr_UT.txt)

Dell S6100: Modify transceiver change event from interrupt to poll mode

---

platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-haliburton.install

There is an issue where HLX module failed to do postinit script.
The issue were introduced in this PR: https://github.com/Azure/sonic-buildimage/pull/7043
Basically, this is a low impact issue because the postinit script failed at last line and all required module service has started before the script crash.
Copy the required script file before postinit run
No this kind of log raise again
```
[   27.556949] rc.local[384]: /var/lib/dpkg/info/platform-modules-haliburton.postinst: 12: /var/lib/dpkg/info/platform-modules-haliburton.postinst: /usr/local/bin/reload_udev.sh: not found
[   27.761279] rc.local[384]: dpkg: error processing package platform-modules-haliburton (--install):
[   27.869157] rc.local[384]:  installed platform-modules-haliburton package post-installation script subprocess …
```

[HLX] Fix issue where HLX module failed to do postinit

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/azure-pipelines-image-template.yml

Failed to build the centec-arm64 for no space in docker data root.
Change to use the data root to the folder under /data.
See detail info about DOCKER_DATA_ROOT_FOR_MULTIARCH in the file Makefile.work.
Set the environment variable, then the /data used as docker root.

[ci] Fix no enough space issue in docker root in multi arch build

---

dockers/docker-sonic-mgmt/Dockerfile.j2

For the migration of tests that involves tgen from `abstract` to `snappi`, snappi library is needed
dependent PR: https://github.com/Azure/sonic-mgmt/pull/3298

adding snappi to docker

---

device/accton/x86_64-accton_as7326_56x-r0/pddf/pd-plugin.json
device/accton/x86_64-accton_as7326_56x-r0/pddf/pddf-device.json
platform/broadcom/sonic-platform-modules-accton/as7326-56x/service/as7326-56x-pddf-platform-monitor.service
platform/broadcom/sonic-platform-modules-accton/as7326-56x/service/as7326-platform-handle_mac.service
platform/broadcom/sonic-platform-modules-accton/as7326-56x/service/pddf-platform-init.service
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/__init__.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/platform.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform_setup.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/utils/accton_as7326_pddf_monitor.py
platform/broadcom/sonic-platform-modules-accton/as7326-56x/utils/pddf_switch_svc.py
platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7326-56x.install
platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7326-56x.postinst

Add to support PDDF.
Implement pddff related code.
Test pddf cmd, sfputil , sensors.
root@sonic:~# pddf_psuutil seninfo
PSU1 is Not OK
PSU2 is OK
Output Voltage: 12062.0 mv
Output Current: 17000.0 ma
Output Power: 206000.0 mw
Fan1 Speed: 6144 rpm
root@sonic:~#
root@sonic:~# pddf_psuutil mfrinfo
PSU1 is Not OK
PSU2 is OK
Manufacture Id: ACBEL
Model: FSF019
Serial Number: FSF0191813105530
Fan Direction: Exhaust
root@sonic:~#
root@sonic:~# pddf_psuutil status
PSU    Status
-----  --------
PSU1   NOT OK
PSU2   OK
root@sonic:~# sensors
fan_ctrl-i2c-11-66
Adapter: i2c-1-mux (chan_id 2)
fan1:        23200 RPM
fan2:        19200 RPM
fan3:        23400 RPM
fan4:        19500 RPM
fan5:        24000 RPM
fan6:        19600 RPM
fan7:           0 …

[as7326-56x] Add to support PDDF

---

.gitmodules

Recently created a 202012 branch of sonic-platform common. Update .gitmodules to track that branch of the submodule in the 202012 branch of sonic-buildimage.

[202012][sonic-platform-common] Track 202012 branch of submodule

---

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh

dell_ich driver was removed as part of https://github.com/Azure/sonic-buildimage/pull/7309 and it is needed for watchdog tickle in S6100 platform.
Modified S6100 platform init to include dell_ich driver 
Do modprobe dell_ich/modprobe -r dell_ich or do platform init/deinit and verify the dell_ich sysfs.
[dell_ich_UT.txt](https://github.com/Azure/sonic-buildimage/files/6316580/dell_ich_UT.txt)

Dell S6100: Add dell ich driver

---

Makefile.work
README.md
slave.mk

Lack of having the support for no_proxy in SONiC build environment limits enterprise companies to put some internal hacks to ensure the proxy's dont refer to some Intranet site for artifactory downloads etc. Today. Using no_proxy is familiar in proxy settings terminology and excludes traffic destined to certain hosts. 
Most Web clients hence support connection to proxy servers via environment variables:
http_proxy / HTTP_PROXY
https_proxy / HTTPS_PROXY
no_proxy / NO_PROXY
These variables tell the client what URL should be used to access the proxy servers and which exceptions should be made.
Add a new variable called 'no_proxy' where proxy settings are specified. A user may choose not to use the same. 
Simply set up the variable in the bash shell at build time. 
export …

Support no_proxy environment variable in Azure SONiC build files

---

build_debian.sh

To fix systemd is older version.
Install systemd explicitelly
systemd --version

[202012][build_debian.sh] fix systemd is not from backports buster

---

src/sonic-ctrmgrd/ctrmgr/container
src/sonic-ctrmgrd/ctrmgr/kube_commands.py
src/sonic-ctrmgrd/tests/common_test.py
src/sonic-ctrmgrd/tests/container_test.py
src/sonic-ctrmgrd/tests/kube_commands_test.py

1) Dropped non-required IP update in admin.conf, as all masters use VIP only
2) Don't clear VERSION during stop, as it would overwrite new version pending to go.
3) subprocess, get return value from proc and do not imply with presence of data in stderr.
Join a cluster and verify admin.conf has VIP address
- [x ] 202012

Kubernetes - update and a fix

---

Makefile.work

rules/config.user allows overriding default properties without
touching tracked files. This change makes sure all properties
can be set and not just the ones used in slave.mk.
I want to set `SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD` which is read by `Makefile.work`.
I extended the existing functionality introduced in https://github.com/Azure/sonic-buildimage/pull/5325.
```
echo 'SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD = y` > rules/config.user
make [some target]
ps ax | grep 'docker.sock' --color
```
Extending functionality of `rules/config.user` to include all build options.

[build] Extend rules/config.user to more Makefiles

---

Makefile.work
build_debian.sh
dockers/docker-base-buster/Dockerfile.j2
dockers/docker-base-stretch/Dockerfile.j2
dockers/docker-base/Dockerfile.j2
dockers/docker-ptf/Dockerfile.j2
files/build_templates/sonic_debian_extension.j2
platform/centec-arm64/platform.conf
platform/marvell-arm64/platform.conf
platform/marvell-armhf/platform.conf
scripts/build_debian_base_system.sh
slave.mk
sonic-slave-buster/Dockerfile.j2
sonic-slave-buster/Dockerfile.user.j2
sonic-slave-stretch/Dockerfile.j2
sonic-slave-stretch/Dockerfile.user.j2
src/ethtool/Makefile
src/snmpd/Makefile

1. Support compile sonic arm image on arm server.  If arm image compiling is executed on arm server instead of using qemu mode on x86 server, compile time can be saved significantly.
2. Add kernel argument systemd.unified_cgroup_hierarchy=0 for upgrade systemd to version 247, according to #7228
When it is detected that the arm compiling is executed on the arm server, the emulated mode of compiling is skipped.  If the arm compiling isn't executed on arm server, the emulated mode should work normally.
1. build arm sonic image on arm server
2. build arm sonic image on x86 server with emulated mode
3. build x86 sonic image on x86 server
```
if [[ $CONFIGURED_ARCH == armhf || $CONFIGURED_ARCH == arm64 ]]; then
sudo LANG=C DEBIAN_FRONTEND=noninteractive chroot $FILESYSTEM_ROOT apt-get -y …
```

[arm]Support compile sonic arm image on arm server

---

slave.mk

There was an existing omission in the build jobs that SONIC_CONFIG_MAKE_JOBS wasn't being passed through to the underlying make command in SONIC_MAKE_DEBS, meaning we weren't fully utilizing all of the CPUs during builds.
Added "-j$(SONIC_CONFIG_MAKE_JOBS)" to the make command

[build] Pass number of CPUs as jobs parameter to make command for SONIC_MAKE_DEBS

---

device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/sai_2010.xml
device/mellanox/x86_64-mlnx_msn2100-r0/ACS-MSN2100/sai_2100.xml
device/mellanox/x86_64-mlnx_msn2410-r0/ACS-MSN2410/sai_2410.xml
device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/sai_2700.xml
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-C28D8/sai_2700_8x50g_28x100g.xml
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8/sai_2700_8x100g_40x50g_8x10g.xml
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai_2700_48x50g_8x100g.xml
device/mellanox/x86_64-mlnx_msn2740-r0/ACS-MSN2740/sai_2740.xml

SAI profile files speed configuration have wrong bitmap value for 10/50G speed option.
Fix to the correct value for all SPC1 devices.
For 10G added 10GB_CX4_XAUI, 10GB_KX4, 10GB_KR, 10GB_SR and 10GB_ER_LR 
For 50G added 50GB_SR2 
This bitmask represents all the options available for interface type and some were missing.
Note: it was working just fine if you were setting the value from SONiC CLI but not from the default SAI Profile.
Configure on these platforms ports with 10/50G speed using this fix.

[Mellanox] Fix for all Spectrum based systems:  SAI profile speed configurations

---

files/image_config/config-setup/config-setup

Encounter error during "config-setup boot" if the updategraph is enabled.
Correct the code inside the config-setup script.
Remove the space between the assignment operator.
Remove the /etc/sonic/config_db.json and reboot the device.
Originally, it will return following error after boot up.
`rv: command not found`
After modification, it can correctly parse the status of updategraph without error.
Fix a bug of checking if updategraph is enabled in config-setup script.

[config-setup]: Fix a bug of checking if updategraph is enabled

---

files/Aboot/boot0.j2

Recent systemd upgrade from #7228 requires an extra cmdline parameter for dockerd to start properly.
Updating boot0 was missed as part of the systemd upgrade change.
Just added the missing cmdline parameter in files/Aboot/boot0.j2
This change fixes #7372
Boot the image and dockerd should start normally.
I'm not sure if systemd will be upgraded in 202012.
If it is, this change will have to be cherry-picked.
Fix dockerd issue on Arista platforms due to missing cmdline parameter

[Arista] Fix dockerd issue on Arista platforms

---

platform/broadcom/sai.mk

To make TD3 MMU init patch available as part of BCM SAI. It covers MMU settings related to CPU and Multicast. Official changes will be available as part of next SAI code drop from BRCM.
Applied the patch on latest REL 4.3.3.4 SAI. 
Verified new settings with updated chip configuration.
Make TD3 MMU init patch available as part of BCM SAI. It covers MMU settings related to CPU and Multicast.

TD3 MMU init patch for libsaibcm covering CPU and MCAST

---

device/dell/x86_64-dell_s6100_c2538-r0/plugins/sfputil.py
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh

- xcvrd crash was seen in latest 201811 images.
- For Dell S6100,API 2.0 uses poll mode while 1.0 was still using interrupt mode.
- Modified get_transceiver_change_event in 1.0 to poll mode in all the related branches.
- Do OIR testing, check xcvrd status and syslogs.
UT:
[201911_change_event_UT.txt](https://github.com/Azure/sonic-buildimage/files/6315412/201911_change_event_UT.txt)

[201911] Dell S6100: Modify transceiver change event from interrupt to poll mode

---

platform/broadcom/sai.mk

* 1d588e38 2021-03-25 | Pending changes for CS00011808451 (bcm_sai/REL_3.5.3, INT_3.5) [BrcmSAI]
* 53efbe91 2021-03-18 | Fix for CS00011810218 [BRCM-DevOps]
* ca0dc86c 2021-03-11 | Fix for CS00011808451 (msazure/INT_3.5, bcm_sai/REL_3.5.3, INT_3.5) [BrcmSAI]
* 208ea62e 2021-01-08 | Update changelog [BRCM-DevOps]
* 3961673c 2021-01-08 | Update version after sdk patch and egress obj leak fixes. [BRCM-DevOps]
* ce3818ad 2021-01-08 | Fix for CS00011581499 [BrcmSAI]
* 1e06157f 2021-01-08 | Merged SDk patch for CS00011651922 [BrcmSAI]
* 4d0c2c86 2021-04-06 | Merged PR 4328641: Add support for AN/LT (HEAD -> 3.5-201811, msazure/3.5-201811) [Joe LeVeque]

[201811][bcm sai] ugprade Broadcom SAI to 3.5.3.7-2

---

device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-C32/th-a7060-cx32s-32x100G-t1.config.bcm
device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-D48C8/th-a7060-cx32s-8x100G+48x50G.config.bcm
device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t0.config.bcm
device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t1.config.bcm
device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/th2-a7260cx3-64-64x100G-t0.config.bcm
device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/th2-a7260cx3-64-64x100G-t1.config.bcm
device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/th2-a7260cx3-64-112x50G+8x100G.config.bcm
device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/th2-a7260cx3-64-64x40G.config.bcm
device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t1.config.bcm
device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm

To enable autonegotiation/link training on some Broadcom-based platforms (Arista 7060 and 7260, Celestica DX010)
- Add appropriate SOC property for enabling the feature to the Broadcom config files of appropriate platforms
- Also convert line endings to UNIX format for one Celestica file

[201811] Add SOC property to enable AN/LT on some platforms (A7060, A7260, DX010)

---

src/sonic-device-data/tests/permitted_list

201811 build was failing due to the newly added bcm config file key word was not on the permitted list
add phy_an_lt_msft to permitted list.
Build device package.

[201811][device] add phy_an_lt_msft to permitted list

---

files/build_templates/sonic_debian_extension.j2
files/image_config/systemd/network/99-default.link

Fix #7364 
99-default.link - was always in SONiC, but previous systemd (<247) had an issue and it did not work due to issue systemd/systemd#3374. Now systemd 247 works.
However, such policy overrides teamd provided mac address which causes teamd netdev to use a random mac 
address. Therefore, needs to be disabled.
Disable default systemd udev rules for interfaces.
Execute https://github.com/Azure/sonic-buildimage/issues/7364 reproduction script.

[systemd] disable default systemd udev rules for interfaces

---

build_debian.sh

PR# 7249 introduced a new bit of logic _after_ the point where the qemu based
build environment for ARM is removed. Hence the new logic fails when building
for ARM. Builds for AMD64 were not affected.
This commit moves the new logic introduced by PR# 7249 to just _before_ the
point where the qemu based build environment for ARM is removed. A comment is
added to reduce the likelihood of this sort of ARM build break from happening
again.
Fix armhf build error introduced by PR# 7249
Build marvell-armhf image

build: Fix ARM build break introduced in PR# 7249

---

src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
src/sonic-yang-models/yang-models/sonic-device_metadata.yang

The fix for the issue [[DPB][YANG] sonic-device_metadata.yang is not aligned with newest changes in CONFIG_DB](https://github.com/Azure/sonic-buildimage/issues/6330)
CONFIG_DB was extended with the field `buffer_model` - added representation of this field inside the  [sonic-device_metadata.yang](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-device_metadata.yang) 
Run the command `config interface breakout <interface> <breakout_mode>`

[DPB][YANG] extended yang-model - added 'buffer_model' field

---

platform/broadcom/sai.mk

This is the SAI 4.3.3.5 code drop from BRCM to address 2 CSP case and initial MMU changes 
Note the MMU changes is the same as that of SAI 4.3.3.4-1 (https://github.com/Azure/sonic-buildimage/pull/7341) but with official patch.
```
Case CS00012178716 [4.3] Polling SAI_QUEUE_STAT_SHARED_WATERMARK_BYTES fails often on TH3
Case CS00012159273 [4.3.3.3] [TD3][IPFWD] subnet broadcast flooding end with extra VLAN Tag if member port of VLAN interface deleted then added back to VLAN
```
Once we have this PR merged, will validate each one of the above to ensure they are indeed fixed...
Preliminary tests looks fine. BGP neighbors were all up with proper routes programmed
interfaces are all up
Manually ran the following test cases on TD3 DUT and all passed:
```
ipfwd/test_dir_bcast.py …
```

[202012] BRCM SAI 4.3.3.5 pick up 2 bug fixes and MMU changes

---

dockers/docker-dhcp-relay/base_image_files/monit_dhcp_relay.j2

Since we will have multiple `dhcrelay` processes if there exists different VLANs in the table `VLAN_INTERFACE` of `CONIFG_DB`, 
we should use unique service name for each `dhcrelay` process in Monit configuration file. Otherwise, Monit service will fail to work.
I append the VLAN name to the end of each service name such that they are unique.
I verified this on a virtual testbed.

[201911][Monit] Use VLAN name to differentiate each Monit service of dhcp_relay

---

.azure-pipelines/azure-pipelines-build.yml
azure-pipelines.yml

Fix the boolean value case sensitive issue in Azure Pipelines
When passing parameters to a template, the "true" or "false" will have case sensitive issue, it should be a type casting issue.
To fix it, we change the true/false to yes/no, to escape the trap.
Support to override the job groups in the template, so PR build has chance to use different build parameters, only build simple targets. For example, for broadcom, we only build target/sonic-broadcom.bin, the other images, such as swi, debug bin, etc, will not be built.

[ci] Fix the boolean value case sensitive issue in Azure Pipelines

---

.azure-pipelines/azure-pipelines-image-template.yml

Improve the version of the Pull Request build by changing the local branch name.
Change the default branch name merge to [target_branch_name]-[pullrequestid].
For official build, the version is not changed.
For pull request build, the version as below:
```
<target branch name>-<pullrequest id>.<azure pipelines build id>-<merge commit id>
Example: master-7381.11668-43df5c87
```

Improve the PR build version

---

.azure-pipelines/azure-pipelines-build.yml

When submitting a new official build for broadcom, vs, it prompts a error message, which says the job is not defined.
It was caused by the default option "[]", which is not empty, it is used as the jobGroups parameter.
Change "[]" to "''".

[ci] Fix official build not existing issue

---

slave.mk

apt-package handling: These are part of the Export variables for .j2 files and is needed for Debian and its derivatives.  
Add support to slave.mk files to export APT_PACKAGES and DBG_APT_PACKAGES
The apt package, provides the apt management tool, a high-level command-line interface for better interactive usage. APT also includes command-line programs for dealing with packages, which use the library. Three such programs are apt, apt-get and apt-cache and can be verified for their existence.

[build]: Provide support for apt install packages

---

.github/workflows/label.yml

Fix the labeler workflow permission issue when merging from fork repo.
It impacts the labeler workflow to support auto-merge for package versions upgrade on 202012 branch. The current workaround is to add the label "automerge" on the PR sent by mssonicbld, then the automerge workflow will merge the PR.
For adding labels, need to use pull_request_target.
See 
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#example-1-passing-the-github_token-as-an-input

[ci] Fix workflow permission issue when merging from the fork repo

---

dockers/docker-sonic-mgmt/Dockerfile.j2

The aiohttp package is required by azure.kusto.data which is used by  sonic-mgmt/test_reporting.
Older version of azure.kusto.data does not need this package. Newer version of azure.kusto.data
requires this 'aiohttp' package.
This change is to ensure that the dependent package is installed in the sonic-mgmt docker.
Update the sonic-mgmt Dockerfile to ensure that the aiohttp python package is installed during build.

[sonic-mgmt] Install aiohttp package to sonic-mgmt docker

---

device/accton/x86_64-accton_as7726_32x-r0/pddf/pd-plugin.json
device/accton/x86_64-accton_as7726_32x-r0/pddf/pddf-device.json
platform/broadcom/sonic-platform-modules-accton/as7726-32x/service/as7726-32x-pddf-platform-monitor.service
platform/broadcom/sonic-platform-modules-accton/as7726-32x/service/pddf-platform-init.service
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/__init__.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/platform.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/thermal.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/watchdog.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform_setup.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/utils/accton_as7726_32x_pddf_monitor.py
platform/broadcom/sonic-platform-modules-accton/as7726-32x/utils/pddf_post_driver_install.sh
platform/broadcom/sonic-platform-modules-accton/as7726-32x/utils/pddf_switch_svc.py
platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7726-32x.install
platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7726-32x.postinst

Support PDDF
Implement code
Test sensors and pddf cmd.
admin@sonic:~$ sensors
ym2651-i2c-50-5b
Adapter: i2c-2-mux (chan_id 1)
fan1:           0 RPM
temp1:         +0.0°C
power1:        0.00 W
lm75-i2c-55-4b
Adapter: i2c-2-mux (chan_id 6)
temp1:        +27.0°C  (high = +80.0°C, hyst = +75.0°C)
lm75-i2c-55-4a
Adapter: i2c-2-mux (chan_id 6)
temp1:        +27.5°C  (high = +80.0°C, hyst = +75.0°C)
as7726_32x_fan-i2c-54-66
Adapter: i2c-2-mux (chan_id 5)
fan1:        9900 RPM
fan2:        9800 RPM
fan3:        9700 RPM
fan4:        9900 RPM
fan5:        10000 RPM
fan6:        10000 RPM
fan11:       8500 RPM
fan12:       8300 RPM
fan13:       8300 RPM
fan14:       8400 RPM
fan15:       8400 RPM
fan16:       8400 RPM
pch_haswell-virtual-0 …

[as7726-32x] Support PDDF

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/sample-voq-graph.xml
src/sonic-config-engine/tests/test_cfggen.py

Contains the following changes:
- Add support for system ports configuration to minigraph
- Add support for SwitchId, SwitchType and MaxCores to minigraph
- Add support for inband vlan configuration in minigraph
- Make `asic_name` in `CONFIG_DB` mandatory for VoQ switches
- Added `sample-voq-graph.xml` and updated `test_cfggen.py` to test for VoQ switches config attributes
Adding support for configuring a VoQ switch using a minigraph.xml file.
Added the following new sections to the minigraph.xml file:
- `VoqInbandInterfaces` to `DeviceDataPlaneInfo`
Contains a list of `VoQInbandInterface` for this device. Example:
```xml
<a:VoqInbandInterface>
<Name>Vlan3094</Name>
<Type>vlan</Type>
<a:PrefixStr>1.1.1.1/24</a:PrefixStr>
</a:VoqInbandInterface>
```
- …

VoQ configuration using minigraph.xml file

---

platform/broadcom/sai.mk

This is the SAI 4.3.3.5 code drop from BRCM to provide MMU changes and couple other fixes
1. MMU fixes
2. Case CS00012178716 [4.3] Polling SAI_QUEUE_STAT_SHARED_WATERMARK_BYTES fails often on TH3
3. Case CS00012159273 [4.3.3.3] [TD3][IPFWD] subnet broadcast flooding end with extra VLAN Tag if member port of VLAN 
interface deleted then added back to VLAN
Merged related commit to libsaibcm, built it and updated sonic-buildimage with binary.
Preliminary tests looks fine. BGP neighbors were all up with proper routes programmed
interfaces are all up
Manually ran the following test cases on TD3 DUT and all passed:
ipfwd/test_dir_bcast.py
vxlan/test_vxlan_decap.py 
Updated libsaibcm with 4.3.3.5 to commit MMU fixes and others

Updated bcmsai to 4.3.3.5 to include MMU fixes and others

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Add the platform filter to ignore some platforms not ready to use
The platform centos-arm64 and the platform marvell-armhf are not ready to use now. We will add it when it is available.
Create a new azure pipeline to test it, see https://dev.azure.com/mssonic/build/_build/results?buildId=12804&view=results

[ci] Add the platform filter to ignore some platforms not ready to use

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Fix the generating version file failure issue caused by artifacts folder change.
When changing to use the same template for PR build, official build and packages version upgrade, the artifacts folder adding a "target" folder, the version upgrade task should be changed accordingly.
The old artifacts: sonic-buildimage.broadcom/docker-database.gz
See https://dev.azure.com/mssonic/build/_build/results?buildId=12268&view=artifacts&pathAsName=false&type=publishedArtifacts
The new artifacts: sonic-buildimage.broadcom/**target**/docker-database.gz
See: https://dev.azure.com/mssonic/build/_build/results?buildId=12645&view=artifacts&pathAsName=false&type=publishedArtifacts

[ci] Fix the generating version file failure issue caused by artifacts folder change

---

dockers/docker-platform-monitor/base_image_files/monit_pmon.j2
files/image_config/monit/generate_monit_config
rules/docker-platform-monitor.mk

This PR aims to monitor the critical processes in PMon container by Monit in 201911 branch.
I created a template configuration file of Monit and it will be rendered to generate Monit configuration file of PMon container
by a service `generate_monit_config.service`.
I verified this on a Mellanox device `str-msn2700-03` and an Arista device `str-a7050-acs-1`.
- [x ] 201911

[201911][Monit] Monitor critical processes in PMon contianer.

---

sonic-slave-stretch/Dockerfile
sonic-slave/Dockerfile

Signed-off-by: Sangita Maity <samaity@linkedin.com>
for 201811 build image, swsssdk wheel package is not getting build due to `redis==2.10.6` requirement issue. Notied that after upgrading pip to 20.3.3, we are experiencling this issue.
**the issue**
```
21:10:41  /sonic/src/sonic-py-swsssdk /sonic
21:10:41  running test
21:10:41  Searching for redis==2.10.6
21:10:41  Reading https://pypi.python.org/simple/redis/
21:10:41  Couldn't find index page for 'redis' (maybe misspelled?)
21:10:41  Scanning index of all packages (this may take a while)
21:10:41  Reading https://pypi.python.org/simple/
21:10:41  No local packages or download links found for redis==2.10.6
21:10:41  error: Could not find suitable distribution for Requirement.parse('redis==2.10.6')
21:10:41  [  FAIL LOG END  ] [ …
```

[201811] Fix swsssdk build by installing redis explicitly

---

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py

The following error message is observed during chassis object being destroyed
```
Exception ignored in: <function Chassis.__del__ at 0x7fd22165cd08>
File "/usr/local/lib/python3.7/dist-packages/sonic_platform/chassis.py", line 83, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
```
The chassis tries to import deinitialize_sdk_handle during being destroyed for the purpose of releasing the sdk_handle.
However, importing another module during shutting down can cause the error because some of the fundamental infrastructures are no longer available.
This error occurs when a chassis object is created and then destroyed in the Python shell.
To fix it, record the …

[Mellanox] Bug fix: exception occurred during chassis object being destroyed

---

device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai.profile
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/sai.profile
device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/sai.profile

Enable VXLAN src port range configuration via SAI profile for the following HWSKU:
SN3800:
• Mellanox-SN3800-D28C50
• Mellanox-SN3800-C64
SN2700:
• Mellanox-SN2700-D48C8
Added SAI_VXLAN_SRCPORT_RANGE_ENABLE=1 configuration to appropriate sai.profile
```
py.test vxlan/test_vnet_vxlan.py --inventory "../ansible/inventory, ../ansible/veos" --host-pattern (testbed)-t0 --module-path                ../ansible/library/ --testbed (testbed)-t0 --testbed_file ../ansible/testbed.csv --allow_recover  --assert plain --log-cli-level info --show-capture=no -ra --showlocals --disable_loganalyzer --skip_sanity --upper_bound_udp_port 65535  --lower_bound_udp_port 64128
```
should be merged after this PRs:
1. [Mellanox] Update SAI version 1.18.3.2 https://github.com/Azure/sonic-buildimage/pull/7428
2. …

[Mellanox] Add support to VXLAN src port range setting via SAI profile for specific SKUs

---

src/sonic-host-services/scripts/caclmgrd

Previously, a brief sleep was necessary in order to get Python threads to progress. The root cause of this has since been found and fixed in sonic-swss-common: https://github.com/Azure/sonic-swss-common/pull/477. The submodule was updated [here](https://github.com/Azure/sonic-buildimage/pull/7467), so we can now safely remove this sleep.
This PR should also be cherry-picked to the 202012 branch once the submodule is updated there to also include the fix.
Ensure the update threads progress in caclmgrd

[caclmgrd] Remove sleep which allowed threads to progress

---

sonic-slave/Dockerfile

sonic snmp subagent build was failing recently.
install python-arptable and psutil in sonic slave docker to address sonic snmp subagent build issue.
build 201811 image locally.

[201811][build] install python-arptable and psutil in sonic slave docker

---

Makefile.work

After PR #7344, 'make init' and/or 'make reset' will also build sonic slave dockers.
'-include rules/config.user' is supposed to be fine when the file is missing.  However, when the file is missing, it generates a delayed error which later causes make init and make reset trying to build the sonic slave dockers.
Define a do-nothing target for config.user to catch config.user build therefore preventing other builds to be triggered unexpectedly.
did make init and it is now only doing submodule init.

[makefile] define a do-nothing target for config.user

---

dockers/docker-orchagent/ndppd.conf.j2
src/sonic-config-engine/tests/sample_output/py2/ndppd.conf
src/sonic-config-engine/tests/sample_output/py3/ndppd.conf

Fixes #6823 
`ndppd` by default reads `/proc/net/ipv6_route` ever 30 seconds. Since T1s advertise so many routes to ToRs, this file is extremely large, and reading it causes `ndppd`'s CPU usage to spike every 30 seconds
Increase the delay for reading this file to the maximum possible value (max integer value), which will result in CPU spikes every ~24 days instead of every 30 seconds
Start `ndppd` with the new config file, confirm that no CPU spikes are seen except at startup

[docker-orchagent]: Increase ndppd kernel poll interval

---

platform/mellanox/mlnx-platform-api/sonic_platform/fan.py

Adjust PSU fan name to align with sysfs file name
Change PSU fan name from psu_{psu_index}_fan_{fan_index} to psu{psu_index}_fan{fan_index}
Manually test

[Mellanox] Adjust PSU fan name to align with sysfs file name

---

build_debian.sh

Install haveged package on 201911/stretch to accelerate the entropy collect process
Recently, we found on some of our testbeds the entropy collecting process finishes more than 60 seconds after the system started.
This results in some daemons start slowly.
To install haveged can accelerate the entropy collect process.

[201911] Install haveged in 201911

---

device/dell/x86_64-dell_s6100_c2538-r0/plugins/sfputil.py
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh

- xcvrd crash was seen in latest 201811 images.
- For Dell S6100,API 2.0 uses poll mode while 1.0 was still using interrupt mode.
- Modified get_transceiver_change_event in 1.0 to poll mode in all the related branches.
- Do OIR testing, check xcvrd status and syslogs.
UT logs:
[201811_s6100_change_event_UT.txt](https://github.com/Azure/sonic-buildimage/files/6315166/201811_s6100_change_event_UT.txt)

[201811] Dell S6100:  Modify transceiver change event from interrupt to poll mode

---

platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
platform/mellanox/mlnx-platform-api/sonic_platform/fan.py
platform/mellanox/mlnx-platform-api/sonic_platform/fan_drawer.py

Adopt a single way to get fan direction for all ASIC types.
It depends on hw-mgmt V.7.0010.2000.2303. Depends on https://github.com/Azure/sonic-buildimage/pull/7419
Originally, the get_direction was implemented by fetching and parsing `/var/run/hw-management/system/fan_dir` on the Spectrum-2 and the Spectrum-3 systems. It isn't supported on the Spectrum system.
Now, it is implemented by fetching `/var/run/hw-management/thermal/fanX_dir` for all the platforms.
1. Regression test.
- Mock random legal value: 0 - intake or 1 - exhaust
- Mock an invalid value: values other than 0 or 1
- Mock the case that file doesn't exist
2. Manually test.

[Mellanox] Adopt single way to get fan direction for all ASIC types

---

device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C49S1/sai.profile

Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
Enable VXLAN src port range configuration via SAI profile for the following HWSKU:
SN3800:
• Mellanox-SN3800-D28C49S1
Added SAI_VXLAN_SRCPORT_RANGE_ENABLE=1 configuration to appropriate sai.profile
```
py.test vxlan/test_vnet_vxlan.py --inventory "../ansible/inventory, ../ansible/veos" --host-pattern (testbed)-t0 --module-path                ../ansible/library/ --testbed (testbed)-t0 --testbed_file ../ansible/testbed.csv --allow_recover  --assert plain --log-cli-level info --show-capture=no -ra --showlocals --disable_loganalyzer --skip_sanity --upper_bound_udp_port 65535  --lower_bound_udp_port 64128
```

[Mellanox] Add support to VXLAN src port range setting via SAI profile for SN3800-D28C49S1

---

platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/platform_reboot_pre_check
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_mon.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh
platform/broadcom/sonic-platform-modules-dell/s6100/scripts/soft-reboot_plugin

- Added soft-reboot plugin support.
- Added SSD version s16425cq check
- Added error message to display in console/SSH in case reboot is called in faulty/non-upgraded devices.
On branch 201911_ssd_plugin
(use "git reset HEAD <file>..." to unstage)
modified:   ../../debian/platform-modules-s6100.install
modified:   platform_reboot_pre_check
modified:   s6100_ssd_mon.sh
modified:   s6100_ssd_upgrade_status.sh
new file:   soft-reboot_plugin
Attached logs for reference.
[test-3IE3-2018-2019.txt](https://github.com/Azure/sonic-buildimage/files/6294065/test-3IE3-2018-2019.txt)
[test-3IE-2018-2019.txt](https://github.com/Azure/sonic-buildimage/files/6294066/test-3IE-2018-2019.txt)

[201911] DellEMC S6100 SSD Monitor additional changes

---

platform/mellanox/mlnx-platform-api/sonic_platform/psu.py

We want to add the ability for the command `show platform psustatus` to show the serial number and part number of the PSU devices on Mellanox platforms. This will be useful for data-center management of field replaceable units (FRUs) on switches.
I implemented the platform 2.0 functions `get_model()` and `get_serial()` for the PSU in the mellanox platform API by referencing the sysfs nodes provided by the [hw-management](https://github.com/Azure/sonic-buildimage/tree/master/platform/mellanox/hw-management) module.
I ran `show platform psustatus` and verified that the serial number and model number were present on platforms where the information was accessible through sysfs. (Currently functioning on all mellanox platforms other than MSN2100 and MSN2010)
None
[platform] Add serial number …

[platform] Add serial number and model number to Mellanox PSU platform implementation

---

.azure-pipelines/azure-pipelines-build.yml

Disable the reproducible build for arm64 and armhf temporarily.
The package version upgrade has been disabled for armhf and armhf for long run time, so disable the reproducible build for the official builds as well. we will enable it when arm64 azure agent ready.

[ci] Disable the reproducible build for arm64 and armhf temporarily

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/simple-sample-graph-metadata.xml
src/sonic-config-engine/tests/test_cfggen.py

So that downstreamsubrole values can be used for policies. Backport PR, same as https://github.com/Azure/sonic-buildimage/pull/7193
Added downstream_subrole to DEVICE_METADATA section of config_db
Unit testing in sonic-config-engine

[minigraph] Add downstreamsubrole parsing to 20911 minigraph.py (#7193)

---

platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py

400G media EEPROM and DOM information are not populated properly in DellEMC Z9332f platform.
Handled QSFP_DD, QSFP28/QSFP+, SFP+ accordingly based on media type detected.  
Check sfpshow eeprom -d, sfpshow presence.
verify whether pmon is running properly and check the syslogs related to pmon docker
UT:
[z9332f_sfp_UT.txt](https://github.com/Azure/sonic-buildimage/files/6389366/z9332f_sfp_UT.txt)

DellEMC: Z9332f SFP enhancements

---

platform/broadcom/sai.mk

This is to pick up BRCM SAI 4.3.3.5-1 which supports special 100G AN/LT mode if enabled by setting special SOC property where AN is only triggering LT only.  So as long as the SOC property is not set, this SAI behaves exactly the same as SAI 4.3.3.5 in every aspect.
Preliminary tests looks fine. BGP neighbors were all up with proper routes programmed
interfaces are all up
Manually ran the following test cases on S6100 DUT and all passed:
```
ipfwd/test_dir_bcast.py
```
Merged in new BRCM SAI 4.3.3.5-1 to 202012 branch

[202012] BRCM SAI 4.3.3.5-1 Added Support for 100G special AN/LT mode

---

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
platform/mellanox/mlnx-platform-api/tests/test_sfp.py

Originally, SFP modules were always accessed from platform daemons, and arbitrary SFP modules can be accessed in the daemon. So all SFP modules were initialized in one shot once one of the following chassis APIs called
- get_all_sfps
- get_sfp_numbers
- get_sfp
Recently, we noticed that SFP modules can also be accessed from CLI, eg. the latest refactor of `sfputil`.
In this case, only one SFP module is accessed in the chassis object's life cycle.
To initialize all SFP modules in one shot is waste of time and causes the CLI to take much more time to finish.
So we would like to optimize the initialization flow by introducing a two-phase initialization approach:
- Partial initialization, which means the `chassis._sfp_list` has been initialized with proper length and all elements being `None` …

[Mellanox] Optimize SFP modules initialization

---

src/sonic-yang-models/tests/test_sonic_yang_models.py

[sonic-yang-models]: fix unit test failure
it is not quite understood why the unit test suddenly failed as below.
but add ietf yang model explicitly to the build process fix the test
failure.
tests/test_sonic_yang_models.py .F [ 66%]
tests/yang_model_tests/test_yang_model.py . [100%]
Failed: pyang -f tree ./yang-models/*.yang > ./yang-models/sonic_yang_tree
----------------------------- Captured stderr call -----------------------------
./yang-models/sonic-acl.yang:8: error: module "ietf-inet-types" not found in search path
./yang-models/sonic-device_metadata.yang:8: error: module "ietf-yang-types" not found in search path

[sonic-yang-models]: fix unit test failure
