src/Makefile
Add dependency to libteam for swss package to fix compilation issue.
=> Update Makefile to fix to swss package compilation

Makefile, dockers/docker-team/Dockerfile
Added required docker-team dependency to Makefile to copy dep packages
to dockers/docker-team/deps/ directory. Changed order of deb packages
installation to fix dependency issue.
=> Fix issue with team docker build.

platform/mellanox/rules.mk, platform/mellanox/sdk.mk
Define sx-kernel pckages in sdk.mk
Add them to SONIC_ALL
=> Add sx-kernel to all targets

sonic-slave/Dockerfile
Fix git/stg complains once running build.sh inside sonic-slave 
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>
=> Fix git/stg error

platform/cavium/docker-syncd-cavm/Dockerfile.j2, platform/cavium/docker-syncd-cavm/profile.ini
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>
=> Added profile.ini into docker-syncd-cavm

slave.mk
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [slave.mk]: Add installer to clean targets.

build_debian.sh
Include kexec-tools package which could be used for fast reboot
=> [baseimage]: Add kexec-tools package into the baseimage

slave.mk
Fix https://github.com/Azure/sonic-buildimage/pull/400 and reopen another PR
=> Support submodule patching if provided

dockers/docker-snmp-sv2/supervisord.conf
Will merge after https://github.com/Azure/sonic-snmpagent/pull/19
=> Disable snmpd ip module, will use snmp subagent implementation

dockers/docker-orchagent/start.sh, files/dhcp/dhclient.conf, files/dhcp/graphserviceurl, files/image_config/updategraph/updategraph, src/sonic-config-engine/translate_acl
=> Revert 432 taoyl/acl dhcp

dockers/docker-snmp-sv2/alias_map.j2, src/sonic-config-engine/tests/test_j2files.py
=> [snmp] Fix a bug in SNMP alias mapping

src/sonic-config-engine/minigraph.py
=> [sonic-cfggen]: Remove extra Nones when return

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/test_cfggen.py
=> [minigraph]: Fix a bug of minigraph_neighbors

device/mellanox/x86_64-mlnx_msn2410-r0/plugins/eeprom.py, device/mellanox/x86_64-mlnx_msn2700-r0/plugins/eeprom.py
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [device]: Fix mellanox eeprom plugins.

platform/broadcom/sdk.mk
=> [Broadcom]: Update debian package versions

platform/broadcom/docker-syncd-brcm-rpc/Dockerfile.j2, platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2
Previously Dockerfile didn't reinstall syncd correctly
=> [docker-syncd-rpc]: Fix Dockerfile

platform/broadcom/sdk.mk
=> [Broadcom]: Update Broadcom SDK to 3.2.2.2-4

platform/broadcom/sai.mk, platform/broadcom/sdk.mk
=> [Broadcom]: Update broacom SDK to 3.2.2.2-5 and SAI to 2.1.5.1-5

platform/broadcom/sai.mk, platform/broadcom/sdk.mk
=> [Broadcom]: Update Broadcom SDK to 3.2.2.2-6 and SAI to 2.1.5.1-6

platform/broadcom/sai.mk, platform/broadcom/sdk.mk
=> Use local build BRCM SDK and SAI

files/image_config/logrotate.d/rsyslog
fix bug for logrotate sairedis log
=> [submodule]: update swss/sairedis/swss-common submodule

files/image_config/apt/sources.list.d/debian_archive_trafficmanager_net_debian.list, platform/broadcom/sai.mk, platform/broadcom/sdk.mk
=> Update libsaibcm version

src/igb/Makefile
=> [igb]: change download url to azure storage url (#770)

platform/cavium/cavm-sai.mk
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>
=> [cavium] Update cavium libsai

platform/broadcom/sai.mk
Add Arista-7050-Q16S64 config.bcm file
=> [Broadcom]: Update SAI to 2.1.5.1-15

platform/broadcom/sai.mk
Add Inventec-D7032Q28B-C32 config.bcm file
=> [Broadcom]: Update SAI to 2.1.5.1-16

device/celestica/x86_64-cel_seastone-r0/sensors.conf
Update labels in sensors.conf for Celestica DX010 model.
=> [device/celestica] Label more chip sensors in DX010 model.

device/mellanox/x86_64-mlnx_msn2700-r0/minigraph.xml
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [device]: Remove illegal character from MSN2700 minigraph

platform/broadcom/sai.mk
Due to newer versions issue, the version draws back from 3.0.3.1 to 3.0.2.3
=> [Broadcom]: Update SAI version to previous version

.gitmodules
These update required for Fast-Reboot with SAI v1.0.3
=> [Submodule update]: sonic-utilities

dockers/docker-config-engine/Dockerfile.j2
=> [translate-acl] Specify pyangbind version to avoid introducing new dependency

device/mellanox/x86_64-mlnx_msn2100-r0/plugins/sfputil.py, device/mellanox/x86_64-mlnx_msn2410-r0/plugins/sfputil.py, device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py, device/mellanox/x86_64-mlnx_msn2740-r0/plugins/sfputil.py
get presence, get/set lpmode, reset are not implemented
=> [devices]: sfputil plugins for mellanox devices for new platform API

dockers/docker-fpm-frr/bgpd.conf.j2, dockers/docker-fpm-frr/zebra.conf.j2, dockers/docker-fpm-gobgp/zebra.conf.j2, dockers/docker-fpm-quagga/bgpd.conf.j2, dockers/docker-fpm-quagga/zebra.conf.j2, src/sonic-config-engine/minigraph.py, src/sonic-config-engine/sonic-cfggen, src/sonic-config-engine/tests/test_cfggen.py
Reverts Azure/sonic-buildimage#919
Will submit again after migrate all data fields
=> Revert "Migrate DEVICE_METADATA to db"

device/arista/x86_64-arista_7060_cx32s/plugins/led_control.py, device/arista/x86_64-arista_7260cx3_64/plugins/led_control.py, rules/docker-platform-monitor.mk, slave.mk
* Bump sonic-platform-modules-arista submodule
* Allow image specific mount option for containers
* Add led plugin for DCS-7060CX-32S
* Add led plugin for DCS-7260CX3-64
=> [devices]: Add led plugin for Arista 7060CX-32S and 7260CX3-64

dockers/docker-orchagent/swssconfig.sh
Change the command of getting the `HWSKU`.
Modify the `swssconfig.sh` file and restart the docker-swss and check if the QOS/buffer configurations are successfullly applied.
=> [swss]: Fix the command to get HWSKU with sonic-cfggen

platform/cavium/cavm-sai.mk
Signed-off-by: Nadiya Stetskovych <Nadiya.Stetskovych@cavium.com>
=> [cavm] Update cavium SAI revision

device/ingrasys/x86_64-ingrasys_s8900_64xc-r0/plugins/sfputil.py
Add Ingrasys S8900-64XC sfputil function and QSFP auto SI service.
* Add S8900-64XC SFP QSFP CPLD kernel module.
* Fixed QSFP function call in i2c_utils.sh.
* Add QSFP monitor service for SFP and QSFP SI.
* Check with the sfputil commands. If no error occurs, it is passed.
* Swap between AOC and DAC cables and check the link. If link is up, it is passed.
Add Ingrasys S8900-64XC sfputil function and update submodule.
=> Add Ingrasys S8900-64XC sfputil function and update submodule.

platform/broadcom/sai.mk
Update Seastone config.bcm files
=> [Broadcom]: Update SAI version to 3.0.3.2-4

platform/broadcom/sai.mk
- Add additional DropCancel and CopyToCpuCancel action rules for every redirect
=> [Broadcom]: Update SAI version to 3.0.3.2-5

platform/broadcom/sai.mk
Update Inventec config.bcm files
=> [Broadcom]: Update Broadcom SAI package to 3.0.3.2-8

dockers/docker-orchagent/orchagent.sh
@sihuihan88 Please make sure to merge this commit only when updating the submodule.
=> [swss]: Change the env name from ASIC to platform

.gitmodules
update sonic-utilities submodule
N/A
update sonic-utilities submodule
=> [submodule]: update sonic-utilities

platform/broadcom/sai.mk, platform/broadcom/sdk.mk
Update OpenNSL to 3.2.3.3-2
Update SAI to 3.0.3.2-10
This commit fixes S6100 CPU high usage issue
=> [Broadcom]: Update Broadcom OpenNSL/SAI packages

README.md
add build badge for marvell and nephos build
Modify README.md
NA
add build badge for marvell and nephos build
=> add build badge for marvell and nephos build

README.md
add build badge for broadcom and mellanox on 201709 release
update README.md
N/A
add build badge for broadcom and mellanox on 201709 release
=> [build]: add build badge for broadcom and mellanox on 201709 release

dockers/docker-orchagent/msn27xx.32ports.buffers.json.j2, src/sonic-config-engine/tests/sample_output/msn27.32ports.json
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Update dynamic threshold and size for some buffer profiles
=> Update Mellanox buffer profiles config

platform/broadcom/sai.mk, platform/broadcom/sdk.mk
Update Broadcom OpenNSL to 3.2.3.7-1
Update Broadcom SAI to 3.0.3.3
=> [Broadcom]: Update Broadcom SDK/SAI package

platform/broadcom/sai.mk
add SAI_ROUTER_INTERFACE_ATTR_MTU support in broadcom SAI
Update broadcom SAI to 3.0.3.3-1
Tested on broadcom platform
add SAI_ROUTER_INTERFACE_ATTR_MTU support in broadcom SAI
=> [broadcom]: update sai to 3.0.3.3-1

README.md
add build badge for nephos platform
=> [build]: add build badge for nephos platform

device/ingrasys/x86_64-ingrasys_s8810_32q-r0/plugins/psuutil.py, device/ingrasys/x86_64-ingrasys_s9100-r0/plugins/psuutil.py, device/ingrasys/x86_64-ingrasys_s9100-r0/sensors.conf, device/ingrasys/x86_64-ingrasys_s9200_64x-r0/plugins/psuutil.py, device/ingrasys/x86_64-ingrasys_s9200_64x-r0/sensors.conf
Signed-off-by: Wade He <chihen.he@gmail.com>
Add psuutil and update submodule for Ingrasys S9100-32X, S8810-32Q, S9200-64X on 201712 branch
* Add I2C CPLD kernel module for psuutil.
* Support psuutil script.
* Add voltage min and max threshold on S9100-32X.
* Add tmp75 sensors config on S9200-64X
* Check the psuutil command worked.
* Check sensors command show correct min and max threshold in voltage column
* Check sensors command show correct thermal data.
Add psuutil and update submodule for Ingrasys S9100-32X, S8810-32Q, S9200-64X on 201712 branch
=> [Platform] Add psuutil and update submodule for Ingrasys S9100-32X, S8810-32Q, S9200-64X on 201712 branch

device/ingrasys/x86_64-ingrasys_s9130_32x-r0/plugins/psuutil.py
1. Add psuutil support on S9130-32X
2. Update psuutil and psu kernel module on S9230-64X
Add psu kernel module and psuutil.py files on S9130-32X
execute "psuutil status" command on devices
1. Add psuutil support on S9130-32X
2. Update psuutil and psu kernel module on S9230-64X
=> [Platform] Add psuutil support for Ingrasys S9130-32X

build_debian.sh
Fixed https://github.com/Azure/sonic-buildimage/issues/1277.
=> [sonic_version] Explicitly specify kernel_version as string

build_debian.sh
Fixed https://github.com/Azure/sonic-buildimage/issues/725
=> Let debootstrap uses the same sources link as apt

rules/docker-snmp-sv2.mk
```
➜  ~ snmpwalk -v2c -c <community string><IP address> .1.3.6.1.4.1.9.9.117
iso.3.6.1.4.1.9.9.117.1.1.2.1.2.1 = INTEGER: 2
iso.3.6.1.4.1.9.9.117.1.1.2.1.2.2 = INTEGER: 2
```
=> [arista]: Update Arista platform modules and mount libraries to snmp docker

device/dell/x86_64-dell_s6100_c2538-r0/plugins/psuutil.py, device/dell/x86_64-dell_z9100_c2538-r0/plugins/psuutil.py
Reverts Azure/sonic-buildimage#1264
Also requires submodule update.
=> Revert "psusutil sysfs attribute changes for hwmon"

device/ingrasys/x86_64-ingrasys_s9130_32x-r0/INGRASYS-S9130-32X/port_config.nps, device/ingrasys/x86_64-ingrasys_s9130_32x-r0/led_proc_init.nps, device/ingrasys/x86_64-ingrasys_s9230_64x-r0/INGRASYS-S9230-64X/port_config.nps, device/ingrasys/x86_64-ingrasys_s9230_64x-r0/led_proc_init.nps, platform/nephos/rules.mk, platform/nephos/sai.mk, platform/nephos/sdk.mk
Updating switch configuration files and download link of SAI/SDK
Updating related switch configuration files in device/ingrasys
Updating related mk files in platform/nephos
Check system and network feature is worked as well
Update switch configuration files and download link for Ingrasys S9130-32X/S9230-64X
=> [Platform] Update switch configuration files and download link for Ingrasys S9130-32X/S9230-64X

dockers/docker-orchagent/swssconfig.sh
Following https://github.com/Azure/sonic-buildimage/pull/1263
=> Fix Mellanox sku check

platform/broadcom/sai.mk
- update Arista 7050-QX32S config.bcm file
- update Accton th-as771*-32x100G.config.bcm files
=> [Broadcom]: Update Broadcom SAI package to 3.0.3.3-3

files/build_templates/docker_image_ctl.j2
Run docker containers with /tmp and /var/tmp mounted to tmpfs
Use --tmpfs option of the docker engine
df inside of the container
Use tmpfs for /tmp and /var/tmp inside of the docker container
=> [base system]: Run docker containers with /tmp and /var/tmp mounted to tmpfs

device/arista/x86_64-arista_7260cx3_64/platform_reboot
Add Arista7260cx3 platform specific reboot tool. This PR is related to https://github.com/Azure/sonic-utilities/pull/188
This platform specific tool reboots device with power cycle.
Tested on 7260cx3 platform.
=> [Arista7260cx3] Add platform specific reboot tool

platform/broadcom/sai.mk
- update Arista 7050-QX32S config.bcm file
- update Accton th-as771*-32x100G.config.bcm files
=> [Broadcom]: Update Boradcom SAI package to 3.0.3.3-3 (#1312)

platform/broadcom/sonic-platform-modules-delta/debian/control, platform/broadcom/sonic-platform-modules-inventec/debian/control
change platform modules to depend on 3.16.0-5-amdn64 kernel
change debian module control file
Still missing a few platforms:
- arista
- accton
- ~~dell z9100/s6100~~
- cel_seastone
- ingrasys
change platform modules to depend on 3.16.0-5-amdn64 kernel
=> [devices]: change platform modules to depend on 3.16.0-5-amdn64 kernel

files/image_config/platform/rc.local
Change rc.local execution option, to log its execution to /var/log/syslog
Changed on dut, rebooted the dut, and verified that rc.local execution was logged in syslog.
=> [boot] log rc.local execution in syslog

installer/x86_64/install.sh
Resolves https://github.com/Azure/sonic-utilities/issues/200
=> [install.sh] Don't treat failure to install image with same version as running SONiC image as an error

dockers/docker-orchagent/swssconfig.sh, files/build_templates/docker_image_ctl.j2
Updated submodule sonic-buildimage
git submodule update --remote src/sonic-utilities
Check hash for submodule src/sonic-utilites.
=> [Submodule update]: Update submodule sonic-utilities

platform/broadcom/sonic-platform-modules-delta/ag9032v1/modules/Makefile, platform/broadcom/sonic-platform-modules-delta/ag9032v1/modules/delta_ag9032v1_cpupld.c, platform/broadcom/sonic-platform-modules-delta/ag9032v1/modules/delta_ag9032v1_platform.c, platform/broadcom/sonic-platform-modules-delta/debian/platform-modules-ag9032v1.init
Signed-off-by: Stanley Chi <stanley.chi@deltaww.com>
=> [Delta ag9032v1]Add attributes for cpupld and swpld.

device/mellanox/x86_64-mlnx_msn2740-r0/sensors.conf
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Added sensors.conf for msn2740
Run sensors test
=> [Mellanox] Add sensors config for MSN2740

device/accton/x86_64-accton_as7212_54x-r0/plugins/sfputil.py, device/marvell/x86_64-marvell_slm5401_54x-r0/plugins/sfputil.py
Updating SFPUtil plugin for 2 devices:
Marvell SLM5401 54x
Accton AS7212 54x
=> Updating SFPUtil plugin with the new APIs

push_docker.sh
Refine docker tag for build number
Add more string into the tag
Local push docker
Currently the build number tag is conflict with sonic version string format. Since the docker build number tag is not used much, make it more verbose.
=> Refine docker tag for build number

build_debian.sh
Added fixes for Copp test according to the following discussion:
https://github.com/Azure/sonic-mgmt/issues/308
Added net.core.wmem_max value 
Run Copp test
=> Added net.core.wmem_max value required by Copp test

README.md
=> [doc]: add build badge for 201712 release

device/accton/x86_64-accton_as5712_54x-r0/plugins/psuutil.py, device/accton/x86_64-accton_as5712_54x-r0/plugins/sfputil.py
Modify sfputil for support oom and access sfp by cpld. Add psuutil
Modify sfp code, Add psuutil code
sfputil show  presence. psuutiul status
=> Modify sfp to support oom and sfp access by cpld. Add psuutil

device/ingrasys/x86_64-ingrasys_s9180_32x-r0/plugins/eeprom.py
Change the i2c address for show platform syseeprom on CPU EEPROM
Change the i2c address for show platform syseeprom on CPU EEPROM
show platform syseeprom and check the EEPROM info
=>  Update syseeprom I2C address.

dockers/docker-lldp-sv2/lldpmgrd
Updated sonic-swss-common, sonic-swss, sonic-sairedis and lldpmgrd.
Changes in sonic-swss-common enabled using priority for Selectables
Regular way, git submodule update
Build whole image and test it. It was tested locally before.
Introduce priority into Selectables.
=> Use refactored Selectables from sonic-swss-common

dockers/docker-snmp-sv2/snmpd-config-updater
=> [snmpd]: Fix typo in is_platform_arista

device/mitac/x86_64-mitac_ly1200_b32h0_c3-r0/plugins/psuutil.py
Add psuutiul 
Implement psuutil.py
psuutiul status
=> [device] Add PSU utility for platform ly1200 of MiTAC

device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-D48C8/buffers_defaults_t0.j2
Revert xoff value
Modified buffers_t0.j2
N/A
N/A
=> Reverting the xoff value for t0 topology

platform/broadcom/sai.mk
upgrade Broadcom SAI to version 3.1.3.4-12
=> [broadcom sai] upgrade Broadcom SAI to version 3.1.3.4-12

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/test_cfggen.py
This reverts commit d7ed6388b667387b142452dea0eb676db189fbe6.
=> Revert "[minigraph parser] Fix minigraph parser issue when handling LAG related ACL table configuration (#1712)"

platform/broadcom/sai.mk
Signed-off-by: Sihui Han <sihan@microsoft.com>
Update SAI version to 3.1.3.4-15
Include change:
PFC fix to only change pfc profile when changing priority_flow_control
=> [sai]: update SAI version to 3.1.3.4-15

platform/cavium/cavm-sai.mk
Updated Cavium SAI headers debian package.
=> Updated Cavium SAI headers.

platform/broadcom/sai.mk
* Add function pointers for extended get stats API
fix broadcom sai 1.3 bug
* Add function pointers for extended get stats API
load to DUT and test it
=> [broadcom]: update sai.mk

platform/vs/tests/conftest.py
clean up process when vs test exits
run vs test
=> [vs]: clean up process running in server namespace

files/build_templates/docker_image_ctl.j2
Otherwise, postStartAction() will run and make no sense.
=> Exit if docker run fails

device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/port_config.ini, device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/port_config.ini
add sonic interface alias for msn2700 platform
pending on night test
=> add sonic port alias for mellanox SN2700 platform

build_debian.sh
Fix https://github.com/Azure/sonic-buildimage/issues/1924
=> [baseimage]: simplify script to install docker

files/build_templates/swss.service.j2
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
Fixed post stop action in swss service template
Fixed invalid post stop action in jinja2 template for swss systemd service 
Build an image, deploy and verify that all successfully started
[mellanox]: Fix post stop action in swss service template
=> [mellanox]: Fix post stop action in swss service template

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Update debian pkg url for bfn platforms
Updated bfn specific .mk files
Build image and load it onto switch
=> Update bfn deb pkg urls for 201807

platform/broadcom/sai.mk
Fix get_fdb_entry_attribute bridge port ID [Shuotian Cheng]
=> [broadcom]: upgrade SAI to 3.1.3.5-8

platform/broadcom/sai.mk
fix sdk alpm parity error issue
=> [broadcom]: update sai to 3.1.3.4-17

device/arista/x86_64-arista_7050_qx32/fancontrol, device/arista/x86_64-arista_7050_qx32s/Arista-7050-QX-32S/hwsku-init, device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/hwsku-init, device/arista/x86_64-arista_7060_cx32s/fancontrol, device/arista/x86_64-arista_7260cx3_64/fancontrol, files/Aboot/boot0.j2, sonic-slave-stretch/Dockerfile
Update arista drivers submodules
Update fancontrol files for 7050QX-32, 7060CX-32S and 7260CX3-64
=> [arista] Update Arista drivers submodule

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk, platform/barefoot/docker-syncd-bfn-rpc/Dockerfile.j2, platform/barefoot/docker-syncd-bfn/Dockerfile.j2, platform/barefoot/sonic-platform-modules-bfn-montara/debian/control, platform/barefoot/sonic-platform-modules-bfn/debian/control, platform/barefoot/sonic-platform-modules-bfn/modules/bf_tun.c, platform/barefoot/sonic-platform-modules-wnc-osw1800/modules/bf_tun.c
Fixed build for BFN platform on Azure/SONiC master
Updated Kernel driver to work with Debian Stretch (kern ver 4.9.x), updated bfn sde sai(1.3.3) package.
Build sde for platform=barefoot
Fix issues with build -update for kernel version and sai version
=> Fix SONiC Build for BFN platforms

src/snmpd/patch-5.7.3+dfsg/0003-CHANGES-BUG-2743-snmpd-crashes-when-receiving-a-GetN.patch, src/snmpd/patch-5.7.3+dfsg/series
[security] Fixes for DSA-4314-1 net-snmp
CVE-case:
https://security-tracker.debian.org/tracker/CVE-2018-18065
Fixes for DSA-4314-1 net-snmp
Patch is here:
https://sourceforge.net/p/net-snmp/code/ci/7ffb8e25a0db851953155de91f0170e9bf8c457d/
Patch code manually, generate patch and add to patch series.
Build fine.
=> [security] Fixes for DSA-4314-1 net-snmp

files/scripts/syncd.sh
Add syncd docker individual warm restart support.
=> [warm boot] syncd warm start could be individual warm start

platform/broadcom/docker-syncd-brcm/start.sh
- Move functions to top of file
- Move code to remove stale files together, first thing
=> [docker-syncd-brcm] Reorganize start.sh

files/image_config/updategraph/updategraph
Signed-off-by: Wenda <wenni@microsoft.com>
=> In the case of upgrade, have pfcwd enabled on the upgraded sonic

device/arista/x86_64-arista_7170_64c/Arista-7170-64C/board_lane_map.json
Modified board mapping file for arista 7170
**- How to verify it*
Build SONiC image and boot on arista 7170
=> change board map json format

dockers/docker-teamd/start.sh, rules/docker-teamd.mk
Added /host filesystem into teamd docker
using mount points of the docker container
Build an image and run on your DUT.
=> Add /host filesystem into teamd docker

src/thrift/Makefile
In case the official links are not stable
=> Store thrift source packages in blob

src/thrift/Makefile
The bug is introduced by https://github.com/Azure/sonic-buildimage/pull/2255
=> Fix bug: let wget rename saved file

device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers.json.j2, device/arista/x86_64-arista_7050_qx32s/Arista-7050-QX-32S/buffers.json.j2, device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers.json.j2
Update pg headroom, and update egress service pool accordingly for a7050 and s6000.
Signed-off-by: Wenda <wenni@microsoft.com>
=> pg headroom update

files/scripts/syncd.sh, platform/broadcom/docker-syncd-brcm/start.sh
Skip ledinit during syncd warm restart
=> [syncd] skip ledinit during syncd warm start

check_install.py
=> [vs]: connect to localhost instead 127.0.0.1 in check_install.py

dockers/docker-orchagent/start.sh
sonic_version yaml provision for switch template. 
=> Provide asic_type to switch template

dockers/docker-orchagent/orchagent.sh
=> [orchagent]: Fix typo

platform/broadcom/docker-syncd-brcm/start.sh
Change if condition [ cond ] to [[ cond ]]
Boot up, verified that led init is done.
=> [syncd script] fix bash script syntax error

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/eeprom.py
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
=> [eeprom] a minor fix to eeprom plugin

files/Aboot/boot0.j2
Update aristanetworks/sonic submodule to fix issue for the 7170
Fix an install issue in boot0 for 7050QX-32 and 7050QX-32S
=> [device/Arista] fix small issue for the 7170

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated Debian packages related to Barefoot Platform and SAI 
Rebuilt Barefoot SDK with required changes
SONIC Testing
Update Debian Package to 8.5.x.59217b4
=> updating deb package for platform and sai

platform/mellanox/sdk.mk
New SDK version contains fixes for Mellanox fastfast boot
=> [mellanox] Update SDK to 4.3.0132

device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/sai_2700.xml, device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai_2700_48x50g_8x100g.xml
Depends on https://github.com/Azure/sonic-buildimage/pull/2374
=> [mellanox|ffb] enable ISSU feature for SN2700

device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t0.j2, device/arista/x86_64-arista_7050_qx32s/Arista-7050-QX-32S/buffers_defaults_t0.j2, device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t0.j2
Signed-off-by: Wenda <wenni@microsoft.com>
=> Add buffer defaults for t0 on s6000 and a7050

dockers/docker-fpm-frr/daemons
dockers/docker-fpm-frr/daemons: Enable FPM 
* Enable FPM in Zebra options
Signed-off-by: Wei Bai <baiwei0427@gmail.com>
=> [docker-frr]: Enable FPM

build_debian.sh, files/image_config/interfaces/interfaces-config.sh
Disable accepting router advertisement for eth0. 
Use system control setting
```
cat /proc/sys/net/ipv6/conf/eth0/accept_ra
0
```
=> Disable IPv6 ra for eth0 interface

device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/sai.profile
=> [mlnx] Fix sai xml path for boxer platform

.gitmodules
sub module sonic-swss-common tracking 201811 branch. And include change:
Submodule src/sonic-swss-common e8caaea..a40837a:
> [pyext] enable types in stdint.h (#259)
Submodule src/sonic-swss-common a40837a..594f4e8:
> Optimized ProducerStateTable set/del notification processing to avoid… (#257)
=> [sub module] sub module sonic-swss-common tracking 201811 branch

platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2
=> [docker-syncd-mlnx-rpc]: fix mellanox syncd docker build

rules/quagga.mk
=> [quagga]: collect quagga-dbg debian package

.gitmodules
Advance 201811 branch sub-modules:
Submodule src/sonic-sairedis d57222a..54b02a1:
> Add support for fdb_event MOVE and check fdb event oids (#420)
> [vslib] add missing port attributes for virtual switch (#419)
Submodule src/sonic-swss 584490c..62e2a20:
> [fdborch] Store vlan id of FDB entry instead of port pvid into stateD… (#759)
> [portsorch] Change speed set flow (#764)
> Create egress ACL table group during the PFCWD stats list installment (#787)
Submodule src/sonic-swss-common 286ef34..2592b0c:
> Add support for WarmStart::setDataCheckState() (#242)
Submodule src/sonic-utilities b44b462..d409987 (start using 201811 branch):
> [sonic_installer] Improve error handling (#460)
> [clock] sync os time to CMOS before rebooting (#465)
=> [201811 submodules] advance sairedis, swss, swss-common, utilities

build_debian.sh, files/initramfs-tools/arista-hook
We are going to use initramfs hook for firmware upgrades
Add initramfs premount script
To install Arista hook:
- create folder /mnt/flash/<image dir>/platform/hooks/boot1/ from Aboot or
/host/<image dir>/platform/hooks/boot1/ from Sonic
- add executable script to created folder
=> Add initramfs hook for Arista devices

files/build_templates/buffers_config.j2
Signed-off-by: Wenda Ni <wenni@microsoft.com>
Tested on DUT.
=> Add hook to allow customizing link cable lengths

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
=> Bfn sde update

src/sonic-config-engine/sonic_platform.py
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
This change should have been added to master branch only.
Reverted commit 8a602c67f9ab18a714ddc9e12c146297b05487ac
=> revert 'Remove MAC alignment WA for Mellanox platforms.'

sonic-slave/Dockerfile
* 1b734f1 2019-03-22 | use pytest in setuptools (#490) [lguohan]
* 7030c97 2019-03-21 | [show] show interface status added vlan and portchannels to command (#483) [Travis Van Duyn]
* a30d1a8 2019-03-21 | [warm/fast reboot] setup control plane assistant when available (#487) [Ying Xie]
* 8182dfa 2019-03-21 | [reboot script] add -h, -? options (#484) [Ying Xie]
=> [sonic-utilities]: fix sonic-utilities build error

platform/broadcom/sai.mk
Address parity error in XOR bank for TH device
=> [Broadcom]: Update SAI to 3.1.3.4-20

.gitmodules, platform/mellanox/mlnx-sai.mk, platform/mellanox/mlnx-sai/Makefile
Make SAI-Implementation a submodule
Build sonic-mellanox.bin
[mellanox] Make mellanox SAI-Implementation as submodule
=> [mellanox] Make mellanox SAI-Implementation as submodule

dockers/docker-sonic-mgmt/Dockerfile.j2
install pytest-ansible module in sonic-mgmt docker
build the sonic-mgmt docker
=> install pytest-ansible for running pytests in sonic-mgmt

platform/broadcom/sai.mk
Broadcom SAI 3.3 GA release 20190402.
=> [Bcm SAI] ugprade Broadcom SAI to version 3.3.5.4m-1

dockers/docker-fpm-quagga/bgpd.conf.j2, src/sonic-config-engine/minigraph.py
Add support of PeerAsn and Address nodes in CPG. 
Changing minigraph.py and bgpd.conf
Run pytest tests in src/sonic-config-engine
=> Add support for PeerAsn and UpdateAddress

device/mellanox/x86_64-mlnx_lssn2700-r0/platform_reboot, device/mellanox/x86_64-mlnx_msn2010-r0/platform_reboot, device/mellanox/x86_64-mlnx_msn2100-r0/platform_reboot, device/mellanox/x86_64-mlnx_msn2410-r0/platform_reboot, device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot, device/mellanox/x86_64-mlnx_msn2740-r0/platform_reboot, platform/mellanox/mlnx-fw-upgrade.j2
Add FW upgrade before reboot feature for Mellanox
Cherry pick of two commits from 201811
Applied on .99 and tested upgrade to 201811
=> [Mellanox] Add FW upgrade before reboot feature

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/eeprom.py
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Updated eeprom plugin to retry when failed (5 retries)
Check if eeprom available. If not - wait 1 sec and retry
=> Improve eeprom access reliability

platform/broadcom/sai.mk
Update hashing coverage for HashIP4TcpUdpPortsEqualField
=> [Broadcom]: Update SAI to 3.1.3.4-21

rules/docker-orchagent.mk
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
* Added missing swssloglevel utility
* Fixed rules/docker-orchagent.mk
1. swssloglevel
* N/A
=> Added missing swssloglevel utility

platform/broadcom/sai.mk
Update SAI to 3.1.3.4-22
BCM patch applied
=> [Broadcom]: Update SAI to 3.1.3.4-22 [L3 MTU Fix]

device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/port_config.ini, device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/switch-tna-sai.conf, device/barefoot/x86_64-accton_wedge100bf_65x-r0/mavericks/port_config.ini, device/barefoot/x86_64-accton_wedge100bf_65x-r0/mavericks/switch-tna-sai.conf, platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
* fixed barefoot platform build
* added TNA config
* updated port_config.ini
```
make init
make configure PLATFORM=barefoot
make target/sonic-barefoot.bin
```
=> [bfn] fixed build failure

src/sonic-config-engine/sonic-cfggen
--write-to-db is frequently used.
=> [sonic-cfggen]: Add -w as short for --write-to-db

platform/nephos/sai.mk
upgrade sai.mk to cbb99f for support sai 1.4.1
upgrade sai.mk 
have build local and test it
=> upgrade sai.mk to cbb99f for support sai 1.4.1

sonic-slave-stretch/Dockerfile
=> [build]: install rsyslog and vim in sonic-slave-stretch

platform/broadcom/sonic-platform-modules-dell/z9264f/scripts/platform_sensors.py
Bug fixed in DellEmc- Z9264f platform specific python script .
Based on fan presence value we are updating the fan air flow status.
show environment
sensors
[Z9264f_UT-LOGS.txt](https://github.com/Azure/sonic-buildimage/files/3191664/Z9264f_UT-LOGS.txt)
=> DellEmc-Z9264f: Bug fixed in platform specific sensor script

dockers/docker-fpm-frr/start.sh
fix a bug introduced in #2961 
build vm and test
=> [docker-frr]: fix frr separated and unified configuration mode

platform/broadcom/sai.mk
Update hash seed algorithm to add entrophy
=> [Broadcom]: Update SAI to 3.1.3.4-24

platform/broadcom/sai.mk
=> [Broadcom]: Update SAI version to 3.5.2.3

sonic-slave/Dockerfile
=> [sonic-slave]: install openjdk-8 for jenkins slave

device/arista/x86_64-arista_7170_64c/Arista-7170-64C/switch-tna-sai.conf, device/arista/x86_64-arista_7170_64c/Arista-7170-Q59S20/switch-tna-sai.conf, device/ingrasys/x86_64-ingrasys_s9180_32x-r0/INGRASYS-S9180-32X/switch-tna-sai.conf, device/ingrasys/x86_64-ingrasys_s9280_64x-r0/INGRASYS-S9280-64X/switch-tna-sai.conf, device/wnc/x86_64-wnc_osw1800-r0/OSW1800-48x6q/switch-tna-sai.conf
Added TNA config files for all devices that run BFN
Switch to A0 profile
=> [bfn] added TNA config for all devices

platform/nephos/sai.mk, platform/nephos/sdk.mk
upgrade sai and sdk to support linux kernel 3.16.0-9
recompile sdk and sai use linux header 3.16.0-9 and update sai.mk and sdk.mk
recompile sonic and test is ok
=> upgrade sdk to support linux kernel 3.16.0-9

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
=> fix SFP initialization in the Chassis for mlnx-platform-api

device/accton/x86_64-accton_as7312_54xs-r0/plugins/sfputil.py
Signed-off-by: brandon_chuang <brandon_chuang@edge-core.com>
CPU: Intel Atom® Processor C2538
MAC: Broadcom Tomahawk BCM56963
BMC: None
What I did
Add lpmode in sfputil.py for as7312-54xs.
.
How I did it
Implement get_low_power_mode/set_low_power_mode in sfputil.py
sfputil show lpmode
sfputil lpmode off
sfputil lpmode on
Description for the changelog
Access eeprom from transceiver to get/set lpmode status
If "Power override" bit is not set, return the H/W pin status depended on H/W design.
For as7312-54xs, this pin is pulled low which is High Power Mode.
If "Power override" bit is set, retrun the S/W lpmode status read from eeprom.
Below is the Power Mode Truth Table defined in sff-8436
LPMode_Pin Power_overide_Bit Power_set_Bit Module_Power_Allowed
1 0 X Low Power
0 0 X …
=> [devices]: Add lpmode in sfputil.py for Accton AS7312-54XS

device/accton/x86_64-accton_as7326_56x-r0/Accton-AS7326-56X/td3-as7326-48x25G+8x100G.config.bcm
Added dport mappings for possible-breakout ports
Modified config.bcm file
breakout ports and verify links up
Add Dport mapping for possible breakout sub-ports make sure breakout ports link up on AS7326
=> Fix Accton as7326 port breakout

platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2
=> [syncd-rpc] fix syncd rpc build and add cleanup

src/sonic-config-engine/tests/test_cfggen.py, src/sonic-config-engine/tests/test_cfggen_t2_chassis_fe.py, src/sonic-config-engine/tests/test_j2files.py, src/sonic-config-engine/tests/test_j2files_t2_chassis_fe.py, src/sonic-config-engine/tests/test_minigraph_case.py
=> [sonic-cfggen]: Remove trailing spaces

device/accton/x86_64-accton_as5835_54x-r0/Accton-AS5835-54X/port_config.ini
Signed-off-by: derek_sun <derek_sun@edge-core.com>
Change port speed.
Modify port_config.ini file.
Modify as5835_54x port_config.ini 25G to 10G.
=> [device]: Modify as5835_54x port_config.ini

platform/nephos/sai.mk, platform/nephos/sdk.mk
update sai and sdk support 4.9.0-9
Updated sai.mk  and sdk.mk
have build and test 
=> update sai and sdk support 4.9.0-9

sonic-slave-stretch/Dockerfile.j2, sonic-slave/Dockerfile.j2
Remove the downloaded tar ball after installation
=> [slave]: Remove temporarily downloaded file

onie-image-arm64.conf, onie-image-armhf.conf, onie-image.conf
checked raw image build and make sure it does not fail.
=> [image]: increase raw disk size to 2G for raw image

device/arista/x86_64-arista_7170_64c/fancontrol, device/arista/x86_64-arista_7260cx3_64/fancontrol
Backport the drivers from the master branch for 201811
This will incorporate all the new changes regarding the platform API.
It also pulls some improvements that happened over time.
=> [device/arista] Update arista drivers submodules

platform/marvell-armhf/linux/Makefile, platform/marvell-armhf/sai/Makefile
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [Platform] Update Marvell-switching github URL

platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/eeprom.py
Implement EEPROM platform2.0 API for DellEMC S6000 platform
Added new file eeprom.py for EEPROM platform2.0 API implementation
Wrote a python script to load Eeprom class and then call the APIs accordingly.
UT logs - [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/3473383/UT_logs.txt)
DellEMC S6000 : Platform2.0 API implementation for EEPROM
=> DellEMC S6000 : Platform2.0 API implementation for EEPROM

device/dell/x86_64-dellemc_z9264f_c3538-r0/media_settings.json
Updated pre-emphasis for Z9264f based on the recent hardware specification
Modified media_settings.json
=> [Dell][Z92464f]Updating pre-emphasis for Z9264f based on updated HW Spec

device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/th2-a7260cx3-64-64x40G.config.bcm
- add mmu_init_config to HWSKU Arista-7260CX3-Q64
QOS test.
=> [mmu] add mmu_init_config to HWSKU Arista-7260CX3-Q64

device/accton/x86_64-accton_as4630_54pe-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as5712_54x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as5812_54x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as5835_54t-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as5835_54x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as6712_32x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7116_54x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7212_54x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7312_54x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7312_54xs-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7315_27xb-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7326_56x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7512_32x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7712_32x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7716_32x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7716_32xb-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7726_32x-r0/pmon_daemon_control.json, device/accton/x86_64-accton_as7816_64x-r0/pmon_daemon_control.json
Signed-off-by: brandon_chuang <brandon_chuang@edge-core.com>
Add pmon_daemon_control.json for accton devices which do not need led_control
Add "skip_ledd": true into pmon_daemon_control.json
check /var/log/syslog to see if there is any led_control error message
=> [device] Add pmon_daemon_control.json for accton

device/arista/x86_64-arista_7170_64c/Arista-7170-64C/switch-tna-sai.conf, device/arista/x86_64-arista_7170_64c/Arista-7170-Q59S20/switch-tna-sai.conf, device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/switch-tna-sai.conf, device/barefoot/x86_64-accton_wedge100bf_65x-r0/mavericks/switch-tna-sai.conf, device/ingrasys/x86_64-ingrasys_s9180_32x-r0/INGRASYS-S9180-32X/switch-tna-sai.conf, device/ingrasys/x86_64-ingrasys_s9280_64x-r0/INGRASYS-S9280-64X/switch-tna-sai.conf, device/wnc/x86_64-wnc_osw1800-r0/OSW1800-48x6q/switch-tna-sai.conf, platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
- updated SDK to 9.0 pre-release
- fixed switch-tna-sai.conf for A0/B0 profiles
=> [barefoot]: updated SDK to 9.0 pre-release

device/celestica/x86_64-cel_e1031-r0/sonic_platform/chassis.py, device/celestica/x86_64-cel_e1031-r0/sonic_platform/fan.py, device/celestica/x86_64-cel_e1031-r0/sonic_platform/psu.py, device/celestica/x86_64-cel_e1031-r0/sonic_platform/sfp.py, device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py, device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan.py, device/celestica/x86_64-cel_seastone-r0/sonic_platform/psu.py, device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
- Update APIs follow sonic_platform_base
1. Add Psu APIs
- get_voltage()
- get_current()
- get_power()
- get_powergood_status()
- get_status_led
2. Update Fan API to support PSU fan
3. Modify SFP APIs to use sfputilhelper instead of sfputilbase
4. Add get_transceiver_info() to SFP API
- Create python script follow the new platform API design doc to verify it (Azure/SONiC#285.)
Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com
=> [device/celestica]: Update new platform APIs

files/image_config/platform/rc.local
=> Log message containing SONiC version to syslog at boot

dockers/docker-snmp-sv2/supervisord.conf
Add a pause before start of snmpd.
Add sleep before the start
Put changes in to your DUT. After that restart DUT and check that snmpd started.
Then kill snmpd and check that snmpd restarted with delay.
=> Wait 5 second before start/restart snmpd

rules/docker-platform-monitor.mk
- Add support for fans in new platform API
- Mount platform API in pmon for arista platforms
- Fans can be fetched from platform API's chassis
- Fan plug in/out events can be detected from platform API's chassis
=> Update arista submodule

dockers/docker-database/database_config.json, dockers/docker-database/supervisord.conf.j2
* add 'hostname' field based on review suggestion
* rename 'socket' to 'unix_socket_path' based on review suggestion
* add new DB define SNMP_OVERLAY_DB(7) in default config
* update script to understand new name 'unix_socket_path'
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
=> update multiBD config file database_config.json for adding  'hostname' field  and rename 'socket'

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
- What I did
- updated SDK to 9.0.0 released package
=> [barefoot]: updated SDK to 9.0.0 released debian package

files/build_templates/buffers_config.j2, files/build_templates/qos_config.j2, src/sonic-config-engine/tests/sample_output/buffers-dell6100.json, src/sonic-config-engine/tests/sample_output/qos-dell6100.json
Signed-off-by: Wenda Ni <wenni@microsoft.com>
=> Adopt per-port buffer & qos profile apply

device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/th2-a7260cx3-64-64x100G.config.bcm, device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/th2-a7260cx3-64-112x50G+8x100G.config.bcm, device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/th2-a7260cx3-64-64x40G.config.bcm, device/delta/x86_64-delta_ag9064-r0/Delta-ag9064/th2-ag9064-64x100G.config.bcm
Enable sram scan per Broadcom's recommendations.
=> [bcm config] enable sram scan

dockers/docker-database/database_config.json
* add separator field to database_config.json
* Will replace python lib database.json file later using  database_config.json
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
=> add separator field to database_config.json

onie-image.conf
increase docker ramfs from 800MB to 900MB
=> [baseimage]: increase docker ramfs from 800MB to 900MB

device/barefoot/x86_64-accton_wedge100bf_32x-r0/plugins/sfputil.py
sudo sfputil show  lpmode 
sudo sfputil lpmode off Ethernet8
sudo sfputil show  lpmode
=> [platform] Fixed return code processing in set_low_power_mode() for BFN platform

platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Support SN3800 in platform api
1. add port position tuple for SN3800
make sure chassis loaded successfully and check whether all the sfps are in the STATE_DB
=> [Mellanox] Support SN3800 in platform api

files/build_templates/qos_config.j2
Signed-off-by: Wenda Ni <wenni@microsoft.com>
=> Fix syntax error for qos_config template

platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py, platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/component.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/component.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py, platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/chassis.py, platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/component.py
Implement Component platform2.0 API for DellEMC S6000, S6100 and Z9100 platforms.
Added new file component.py for Component platform2.0 API implementation.
Wrote python script to load Chassis class and then call the APIs accordingly.
UT Logs - [UT_logs-S6000.txt](https://github.com/Azure/sonic-buildimage/files/3711631/UT_logs-S6000.txt), [UT_logs-S6100.txt](https://github.com/Azure/sonic-buildimage/files/3711632/UT_logs-S6100.txt), [UT_logs-Z9100.txt](https://github.com/Azure/sonic-buildimage/files/3711633/UT_logs-Z9100.txt)
Test Script - [component_test_py.txt](https://github.com/Azure/sonic-buildimage/files/3711646/component_test_py.txt)
DellEMC : Platform2.0 API Implementation for Component …
=> DellEMC : Platform2.0 API Implementation for Component [S6000, S6100, Z9100]

platform/marvell/docker-syncd-mrvl.mk, platform/marvell/docker-syncd-mrvl/Dockerfile.j2, platform/marvell/rules.mk, platform/marvell/sai.mk, platform/marvell/sai/Makefile, platform/marvell/sdk.mk, platform/marvell/sdk/Makefile
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [Platform] Updated Marvell x86 platform makefiles

files/build_templates/buffers_config.j2, src/sonic-config-engine/tests/sample_output/buffers-dell6100.json
This reverts commit 8861cbe98edbe513aac5d1ee2c5943bf6179c905.
=> Revert "Configure buffer profile to all ports (#3561)"

platform/broadcom/sai.mk, platform/mellanox/mlnx-sai.mk
* 1f4a1d7 2019-09-24 | Add warm boot support with removed/created port (#515) (HEAD, origin/master, origin/HEAD) [Kamil Cudnik]
* 59e530a 2019-09-20 | Add support for debug counters (#517) [Danny Allen]
* 1ed09e0 2019-09-20 | fully support bulk_remove in sairedis (#516) [Dong Zhang]
* 6cb1b31 2019-09-17 | Add support for port remove and port create (no warm boot) (#500) [Kamil Cudnik]
* 83d86ed 2019-09-17 | Fix c_str() in printf for string (#514) [Kamil Cudnik]
* 11b44b5 2019-09-16 | Advance SAI reference pointer to v1.5.0 (#509) [Wenda Ni]
* 38c6945 2019-09-14 | support sflow on virtual switch (#498) [Rakesh Datta]
* e7d766e 2019-09-09 | Add acl counter match logic based on acl entry field (#511) [Kamil Cudnik]
* 58845ce 2019-09-06 |  Add extra check for warm boot discovered RIDs (#502) …
=> [submodule]: use SAI 1.5.1 header

device/mellanox/x86_64-mlnx_msn3800-r0/pmon_daemon_control.json
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
* Updated SN3800 device config
* N/A
* N/A
=> [mellanox] Update SN3800 device config

README.md
=> [doc]: Add SONiC management docker image

build_debian.sh
- explicitly set file permission on passwd, group, shadow
=> [file permission] explicitly set file permission on passwd, group, shadow

files/image_config/cron.d/core_cleanup
[core_cleanup] Fix issue where core_cleanup job runs too frequently
=> [core_cleanup] Fix issue where core_cleanup job runs too frequently

dockers/docker-fpm-quagga/bgpcfgd
Added new table for rendering
By listening to other keys
Build a new image, install to new DUT, use NEIGHBOR_METADATA in your bgp templates
=> [bgpcfgd]: Add NEIGHBOR_METADATA info into render

files/build_templates/dhcp_relay.service.j2, files/build_templates/lldp.service.j2, files/build_templates/radv.service.j2, files/build_templates/sflow.service.j2, files/build_templates/snmp.service.j2, files/build_templates/telemetry.service.j2
=> [services] improve startup time by changing startup order

device/accton/x86_64-accton_as7326_56x-r0/plugins/sfputil.py, platform/broadcom/sonic-platform-modules-accton/as7326-56x/modules/accton_i2c_cpld.c
Signed-off-by: brandon_chuang <brandon_chuang@edge-core.com>
CPU: Intel Broadwell-DE XeonD-1518 1.6G 4 Core
MAC: Broadcom Trident3 BCM56873
BMC: None
Add reset in sfputil.py for as7326-56x.
Implement reset() in sfputil.py
Add module_reset_* attribute in sysfs driver and read/write the attribute in sfputil.py to make reset work.
=> [device/platform] Add reset in sfputil.py for Accton AS7326-56X

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Signed-off-by: Vitaliy Senchyshyn <vsenchyshyn@barefootnetworks.com>
Updated BFN packages in order to fix the BFN platform build
Updated the links to the packages which work with the latest SONiC 
Built the SONiC with the packages uploaded and ran the CT regression
=> [build]: Fixed BFN target build

platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/watchdog.py
- Implement Watchdog platform2.0 API for DellEMC S6100 platform.
- Added new file watchdog.py in sonic_platform directory.
- Enabled API support to Enable/disable watchdog.
- Attached Unit test case results.
[DellEMC] Platform2.0 API Implementation for Watchdog [S6100]
[Unit test - Watchdog.txt](https://github.com/Azure/sonic-buildimage/files/3801888/Unit.test.-.Watchdog.txt)
=> [DellEMC] Platform2.0 API Implementation for Watchdog [S6100]

platform/broadcom/sai.mk
* afe2a0d 2019-10-30 | [vs]: Fix learn fdb events after fdb flush event (#524) (HEAD, origin/master, origin/HEAD) [Kamil Cudnik]
* d29760f 2019-10-28 | [sai_redis_interface_query] Add sairedis support for sai_object_type_get_availability (#528) [Danny Allen]
* ff5306e 2019-10-28 | [sai_redis_interface_query] Add sairedis support for sai_query_attribute_enum_values_capability (#525) [Danny Allen]
=> [submodule]: update sonic-sairedis

device/arista/x86_64-arista_7170_64c/Arista-7170-64C/switch-sai.conf, device/arista/x86_64-arista_7170_64c/Arista-7170-64C/switch-tna-sai.conf, device/arista/x86_64-arista_7170_64c/Arista-7170-Q59S20/switch-sai.conf, device/arista/x86_64-arista_7170_64c/Arista-7170-Q59S20/switch-tna-sai.conf, device/barefoot/x86_64-accton_as9516bf_32d-r0/newport/switch-tna-sai.conf, device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/switch-sai.conf, device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/switch-tna-sai.conf, device/barefoot/x86_64-accton_wedge100bf_65x-r0/mavericks/switch-sai.conf, device/barefoot/x86_64-accton_wedge100bf_65x-r0/mavericks/switch-tna-sai.conf, device/ingrasys/x86_64-ingrasys_s9180_32x-r0/INGRASYS-S9180-32X/switch-sai.conf, device/ingrasys/x86_64-ingrasys_s9180_32x-r0/INGRASYS-S9180-32X/switch-tna-sai.conf, device/ingrasys/x86_64-ingrasys_s9280_64x-r0/INGRASYS-S9280-64X/switch-sai.conf, device/ingrasys/x86_64-ingrasys_s9280_64x-r0/INGRASYS-S9280-64X/switch-tna-sai.conf, device/wnc/x86_64-wnc_osw1800-r0/OSW1800-48x6q/switch-sai.conf, device/wnc/x86_64-wnc_osw1800-r0/OSW1800-48x6q/switch-tna-sai.conf, platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
**What I did**
Updated BFN debian packages
Migration from libswitchsai.so to libsai.so
**How I verified it**
Private build of BFN target
=> [barefoot][build] Fixed BFN platform build failure

dockers/docker-sonic-mgmt/Dockerfile.j2
check  https://github.com/Azure/sonic-mgmt/pull/1213
=> [sonic-mgmt]: install ansible 2.8.7 and pytest-ansible 2.2.2

dockers/docker-base-stretch/Dockerfile.j2, dockers/docker-ptf/Dockerfile.j2
1. Make a link to from vim.tiny to vim.
2. Add tmux to docker-ptf
Using linux technologies
Build docker containers and check them
=> [dockers]: Various improvements

dockers/docker-ptf/Dockerfile.j2
=> [docker-ptf]: add ethtool and telnet package in ptf

.gitmodules
Updated FRR with latest changes from FRR repositary
Updated submodule
Build an image and run on your DUT
=> [FRR]: Update frr with latest changes from frr master

check_install.py
retry connect every 1 second for 10 maximum times
=> [kvm]: reconnect during kvm installation process

README.md
=> Add Innovium Jenkins build

device/marvell/armhf-marvell_et6448m_52x-r0/et6448m/port_config.ini
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [Marvell HwSKU] port configration updated with speed

slave.mk
Fix an issue with SONIC_ONLINE_DEBS with curl by instructing curl to follow http redirects
=> [slave.mk] make curl follow HTTP redirects

device/juniper/x86_64-juniper_qfx5210-r0/Juniper-QFX5210-64C/buffers.json.j2, device/juniper/x86_64-juniper_qfx5210-r0/Juniper-QFX5210-64C/buffers_defaults_t1.j2, device/juniper/x86_64-juniper_qfx5210-r0/Juniper-QFX5210-64C/qos.json.j2
Adding buffers.json.j2, buffers_defaults_t1.j2 and
qos.json.j2 for qfx5210 platform.
Signed-off-by: Ciju Rajan K <crajank@juniper.net>
=> [Juniper][QFX5210] Adding qos.json

device/dell/x86_64-dell_s6000_s1220-r0/sensors.conf
- What I did
Change PSU MAX temperature to 80 degree.
- How I did it
Updated sensors.conf for DellEMC S6000.
Run sensors command.
[sensors.txt](https://github.com/Azure/sonic-buildimage/files/4006764/sensors.txt)
=> DellEMC S6000 PSU Temperature

platform/mellanox/hw-management/0001-Make-hw-mgmt-SimX-compatiable.patch
Update the hw-mgmt patch for simx on V.7.0000.2308
Regenerate the patch against V.7.0000.2308
Verify whether all dockers can start on simx.
=> [Mellanox]Update the hw-mgmt patch for simx on V.7.0000.2308

files/build_templates/sonic_debian_extension.j2, rules/monit.mk, src/monit/Makefile
=> [201811][monit] address build issue: hard code ARCH to amd64

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
- Updated SDK package with X1/X2 profiles
=> [barefoot]: Update SDK package

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
updated BFN SDK to 9.1.0 released package
=> [barefoot]: updated SDK to 9.1.0 released debian packages

platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
Fix gearbox ambient thermal name
Rename it.
=> [Mellanox]Fix gearbox ambient thermal file name

files/image_config/procdockerstatsd/procdockerstatsd
Removed space from #! /usr/bin/env python
Changed on the device and verified daemon up and active
=> [procdockerstatsd] removing space from shebang

files/build_templates/sonic_debian_extension.j2, platform/marvell-armhf/sai.mk
Moving sai version to 1.5.1 on marvell-armhf
changed the sai version to 1.5.1
changed the platform related file
compile the marvell-armhf platform
changed the sai version to 1.5.1
=> Sai1.5 marvell

device/dell/x86_64-dellemc_s5232f_c3538-r0/plugins/eeprom.py, device/dell/x86_64-dellemc_s5248f_c3538-r0/plugins/eeprom.py, device/dell/x86_64-dellemc_s5248f_c3538-r0/plugins/sfputil.py, platform/broadcom/sonic-platform-modules-dell/s5232f/scripts/s5232f_platform.sh, platform/broadcom/sonic-platform-modules-dell/s5248f/scripts/s5248f_platform.sh
* Dynamic bus detection and loading driver for eeprom on s5248,s5232
* sfputil fix for S5248
* Dynamic bus detection and loading driver for eeprom on s5248,s5232
* sfputil fix for S5248
Modified  Dell EMC platform specific files
Verified on S5232 and S5248 platfoms.
logs below.
=>  DellEMC: DellEMC platform bug fixes

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Added GENL3 dependency for BFN SAI
```
make init
make configure PLATFORM=barefoot
time make all
```
=> [bfn] Added GENL3 dependency for SAI

platform/broadcom/platform-modules-dell.mk, platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install, platform/broadcom/sonic-platform-modules-dell/tools/0002-Flashrom-support-for-Intel-Rangeley-and-Denverton-CP.patch, platform/broadcom/sonic-platform-modules-dell/tools/flashrom.sh
- Added BIOS upgrade support for DellEMC S6100 platform.
- flahrom utitily is needed for BIOS upgrade support in S6100. 
- flashrom and associated patch file is added in vendor section. "flashrom" binary will be generated at the time of build-creation. 
- Dell specific BIOS image is uploaded in appropriate device directory.
- To upgrade BIOS below command needs to be executed:
```flashrom -p internal -w /usr/share/sonic/device/x86_64-dell_s6100_c2538-r0/bin/S6100-BIOS-3.25.0.2-7.bin```
- You can check the BIOS version in boot logs:
```
BIOS Boot Selector for S6100
Primary BIOS Version 3.25.0.2-7<----version
SMF Version: MSS 2.1, FPGA 1.1
Last POR=0x11, Reset Cause=0x44
POST Configuration
CPU Signature 406D8
```
- or you can use …
=> DellEMC S6100 BIOS upgrade support

files/scripts/arp_update
arp_update to refresh neighbor entries from APP_DB
Modified arp_update script
Run on DUT 
=> Update arp_update to refresh neighbor entries from APP_DB

rules/docker-nat.mk, rules/docker-sonic-mgmt-framework.mk
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Fixes #4118 
=> [rules] remove leftover --net=host docker run options

files/scripts/arp_update
Added a timeout option to ping command
```
root@str-7260cx3-acs-7:/# timeout 0.2 ping -I Vlan1000 -n -q -i 0 -c 1 -W 0 192.168.0.44
PING 192.168.0.44 (192.168.0.44) from 192.168.0.1 Vlan1000: 56(84) bytes of data.
```
=> Added timeout to ping command

files/image_config/procdockerstatsd/procdockerstatsd.service
=> [procdockerstatsd] Fix incorrect case issue in service file

README.md
Add build badge for Innovium 201911 build
=> Add build badge for Innovium 201911 build

platform/innovium/invm-sai.mk
Updated Innovium debian package path for 201911
Build
=> Add Innvoium build support for 201911

device/mellanox/x86_64-mlnx_msn3700-r0/ACS-MSN3700/sai_3700.xml, device/mellanox/x86_64-mlnx_msn3800-r0/ACS-MSN3800/sai_3800.xml
=> [mellanox] enable ISSU on SPC2 systems

device/arista/x86_64-arista_7050cx3_32s/fancontrol, device/arista/x86_64-arista_7050cx3_32s/sensors.conf
Add the config file of fancontrol for Arista 7050cx3_32s
=> [device] Add fancontrol for arista 7050cx3

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py
Fix an syntax error introduced by [#4035](https://github.com/azure/sonic-buildimage/pull/4035)
=> [sfputil]Fix an syntax error

platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/chassis.py, platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/thermal.py
Implement Thermal platform2.0 API for DellEMC Z9264 platform.
Added new file thermal.py for Thermal platform2.0 API implementation.
Wrote a python script to load chassis class and call the appropriate methods.
Logs : [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/4230015/Z9264_thermal_UT.txt)
DellEMC: Z9264-Platform2.0 Implementation [Thermal]
=> DellEMC: Z9264-Platform2.0 Implementation [Thermal]

build_debian.sh
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
* Added utility for SSD maintenance: hdparm
* N/A
* N/A
```
'//||\\`
''``
```
=> [201811][image]: Add SSD maintenance utility - hdparm

build_debian.sh
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
* Added utility for SSD maintenance: hdparm
* N/A
* N/A
```
'//||\\`
''``
```
=> [image]: Add SSD maintenance utility - hdparm

dockers/docker-snmp-sv2/start.sh
=> [snmp] remove hostname change as it share uts namespace with host

dockers/docker-sonic-mgmt-spytest/Dockerfile.j2, rules/docker-sonic-mgmt-spytest.mk
=> [spytest] Create new sonic-mgmt docker for running spytests

platform/broadcom/sai.mk
=> [bcmsai] Update BRCM SAI Debian to 3.7.3.3-3

files/build_templates/init_cfg.json.j2
Added NAT entry into CONTAINER_FEATURE in config_db.json template
=> [Service] Added NAT entry into CONTAINER_FEATURE. Fixes #4247.

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated Barefoot DEBs to 20200205
=> [BFN] Updated Barefoot DEBs to 20200205

dockers/docker-ptf/Dockerfile.j2
setup ntp server to do the test
=> [docker-ptf]: install ntp related package

README.md
=> Add build badge for Barefoot 201911 build

Makefile.work
- What I did**
Make error message clearer. And give install command.
Tested the error message by putting it outside the if block (since I already installed the j2 package).
=> [makefile] make error message clearer with instructions

rules/lm-sensors.mk, rules/snmpd.mk
https://sonic-jenkins.westus2.cloudapp.azure.com/job/workers/job/test-buildimage-brcm-all-rcache/17/console
https://sonic-jenkins.westus2.cloudapp.azure.com/job/workers/job/test-buildimage-brcm-all-rcache/13/console
=> Fix DPKG Cache derived package issue

device/celestica/x86_64-cel_e1031-r0/pmon_daemon_control.json, device/celestica/x86_64-cel_e1031-r0/sonic_platform/chassis.py, device/celestica/x86_64-cel_e1031-r0/sonic_platform/sfp.py, device/celestica/x86_64-cel_midstone-r0/pmon_daemon_control.json, device/celestica/x86_64-cel_seastone-r0/pmon_daemon_control.json, device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py, device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py, device/celestica/x86_64-cel_silverstone-r0/pmon_daemon_control.json
- Fix https://github.com/Azure/sonic-buildimage/issues/3302 on 201911 branch
- Fix sonic_platform issue
- Cherry pick https://github.com/Azure/sonic-buildimage/commit/34579c277b1ed99f4d36744cdcb1b2dd42560394 from master  
- Verify pmon docker status
Signed-off-by: Wirut Getbamrung [wgetbumr@celestica.com]
=> [device/celestica]: Fix xcvrd error on 201911 branch

dockers/docker-sonic-mgmt/Dockerfile.j2
=> [docker-sonic-mgmt]: Fix virtual environment bug

platform/mellanox/sdk.mk
* fixes an issue when /host/warmboot/issu_bank.txt is empty/corrupted
switch is not able to over come this and enters continuos reload/reboot
failure.
=> [mellanox] update SDK to 4.3.1646

scripts/build_kvm_image.sh
print out kvm_log on error
manually create failure and tested.
=> [kvmbuild]: print out kvm_log on error

README.md
Add branch 201911/201811 status support for Nephos platform
=> Add 201911/201811 status support for Nephos

device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/port_config.ini, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/sai_preinit_cmd.soc, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/td3-s5232f-32x100G.config.bcm, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/sai_preinit_cmd.soc, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/td3-s5232f-32x100G.config.bcm, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/sai_preinit_cmd.soc, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/td3-s5232f-96x10G+8x100G.config.bcm, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/sai_preinit_cmd.soc, device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/td3-s5232f-96x25G+8x100G.config.bcm, device/dell/x86_64-dellemc_s5232f_c3538-r0/led_proc_init.soc, device/dell/x86_64-dellemc_s5232f_c3538-r0/plugins/psuutil.py, device/dell/x86_64-dellemc_s5232f_c3538-r0/plugins/sfputil.py, device/dell/x86_64-dellemc_s5232f_c3538-r0/pmon_daemon_control.json, platform/broadcom/sonic-platform-modules-dell/s5232f/modules/dell_s5232f_fpga_ocores.c, platform/broadcom/sonic-platform-modules-dell/s5232f/scripts/platform_sensors.py, platform/broadcom/sonic-platform-modules-dell/s5232f/scripts/s5232f_platform.sh
FPGA driver crash fix for stale buffer in i2c transfer
LED firmware load issue fix.
10G port swapfix
psu/sfp bug fixes to report correct states/status of hw
issues fixed related to 
FPGA driver crash fix for stale buffer in i2c transfer
LED firmware load issue fix
psu/sfp bug fixes to report correct states/status of hw
Code changes done in platform related areas
Verified on S5232 platform. Logs in comments section
=> [DellEMC] S5232 platform updates

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
=> [BFN] Update Barefoot SDK packages

device/accton/x86_64-accton_as7116_54x-r0/sonic_platform/sfp.py
=> [device/accton] Fix Python error in sfp.py for as7116-54x

platform/broadcom/sonic-platform-modules-accton/as4630-54pe/classes/fanutil.py
- Fix Python indentation error
- Add newline at EOF
=> [Accton AS4630-54PE] Fix Python indentation error

src/tacacs/nss/0006-fix-compiling-warning-about-token-dereference.patch, src/tacacs/nss/Makefile
=> [libnss]: fix compiling issue under gcc 8

Makefile.work
This is to build sonic-slave-base target for user to download
=> [Build]: add build target to build sonic-slave-base

device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py
Add ACS-MSN4700 support to sfputil plugin
Add ACS-MSN4700 to hwsku-dict of sfputil plugin
run "sfputil lpmode/reset/..."   command to test 
=> [Mellanox] bug fix - adpt sfputil plugin to support ACS-MSN4700

Makefile.cache, rules/docker-iccpd.dep, rules/iccpd.dep
It addresses the following:
Added DPKG support for ICCPD package
Added warning support for missing dependency files that causes the incorrect SHA generation.
Added DPKG support for iccpd and warning message for missing dep files.
Build with DPKG cache enabled
=> DPKG evaluation review comments and bug fixes 

.github/PULL_REQUEST_TEMPLATE.md
it is important to understand the motivation of the PR.
what I did is usually the PR title, so remove.
=> [doc]: ask the motivation of the PR

device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/sai_3800_112x50g_8x100g.xml
[Mellanox]Mellanox-SN3800-D112C8 support warm-reboot
=> [Mellanox]Mellanox-SN3800-D112C8 support warm-reboot

src/iccpd/include/iccp_cmd_show.h, src/iccpd/include/iccp_csm.h, src/iccpd/include/iccp_ifm.h, src/iccpd/include/iccp_netlink.h, src/iccpd/include/mlacp_fsm.h, src/iccpd/include/mlacp_link_handler.h, src/iccpd/include/mlacp_sync_prepare.h, src/iccpd/include/mlacp_sync_update.h, src/iccpd/include/mlacp_tlv.h, src/iccpd/include/msg_format.h, src/iccpd/include/port.h, src/iccpd/include/system.h, src/iccpd/src/iccp_cmd_show.c, src/iccpd/src/iccp_ifm.c, src/iccpd/src/iccp_netlink.c, src/iccpd/src/mclagdctl/mclagdctl.c, src/iccpd/src/mclagdctl/mclagdctl.h, src/iccpd/src/mlacp_fsm.c, src/iccpd/src/mlacp_link_handler.c, src/iccpd/src/mlacp_sync_prepare.c, src/iccpd/src/mlacp_sync_update.c, src/iccpd/src/port.c, src/iccpd/src/scheduler.c, src/iccpd/src/system.c
- What I did
mclag support IPv6 ND
- How I did it
accomplish it according MCLAG HLD document, the principle is similar to IPv4 ARP.
Complie and test it on nephos lab
- Description for the changelog
- A picture of a cute animal (not mandatory but encouraged)
=> ICCPD support IPv6 ND

rules/config
=> [docker-iccpd]: disable iccpd build by default

rules/docker-restapi.mk, src/sonic-config-engine/minigraph.py
Add RESTAPI config to Config DB
Through the minigraph.py script
using redis-cli
Add RESTAPI config to Config DB
=> [docker-restapi]: add restapi config to config Db

device/accton/x86_64-accton_as4630_54pe-r0/Accton-AS4630-54PE/port_config.ini, platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/accton_as4630_54pe_util.py
Signed-off-by: derek_sun <derek_sun@edge-core.com>
1) Add port auto-negotiation attribute.
2) Add CPLD command to disable mode.
1) Modify port-config.ini.
2) Modify accton_as4630_54pe_util.py.
1) Running SONiC on as4630_54pe and execute "show interfaces status"
Add port auto-negotiation attribute and Disable CPLD debug mode.
=> [device] Upgrade as4630_54pe for new platform

device/accton/x86_64-accton_minipack-r0/Accton-MINIPACK/config_16Q_FEC544_EVTA_100G.bcm, device/accton/x86_64-accton_minipack-r0/Accton-MINIPACK/config_16Q_FEC544_EVTB_100G.bcm
Signed-off-by: derek_sun derek_sun@edge-core.com
- What I did
Modify as8000 configuration.
- How I did it
Modify config_16Q_FEC544_EVTB_100G.bcm
1) Warm boot test.
2) l3 test case.
- Description for the changelog
Modify as8000 configuration file.
- A picture of a cute animal (not mandatory but encouraged)
=> [device] Modify as8000 configuration

sonic-slave-buster/Dockerfile.j2, sonic-slave-jessie/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2
To have latest stable go version, with the latest fixes and latest toolchain. go 1.11.5 is outdated and has issues.
Change the version string
Check that go binaries were built without issues.
=> Update golang version from 1.11.5 to 1.14.2

device/barefoot/x86_64-accton_wedge100bf_32x-r0/pmon_daemon_control.json, device/barefoot/x86_64-accton_wedge100bf_65x-r0/pmon_daemon_control.json
fancontrol is not supported by these platforms
=> [pmon][barefoot] Disabled fancontrol pmon daemon

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/t0-sample-graph.xml, src/sonic-config-engine/tests/test_cfggen.py
Similar to https://github.com/Azure/sonic-buildimage/pull/4556
But adapt for 201811 branch
=> [minigraph] Support FECDisabled in minigraph parser (#4556)

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated Barefoot SDK to the latest
=> [BFN] Updated Barefoot SDK to 2020-05-07

device/barefoot/x86_64-accton_wedge100bf_32x-r0/pmon_daemon_control.json, device/barefoot/x86_64-accton_wedge100bf_65x-r0/pmon_daemon_control.json
This is cherry-pick of https://github.com/Azure/sonic-buildimage/pull/4528
fancontrol is not supported by these platforms
=> [201911][devices] skip_fancontrol for wedge 100 barefoot platforms (#4528)

platform/broadcom/sonic-platform-modules-juniper/qfx5200/utils/juniper_qfx5200_monitor.py, platform/broadcom/sonic-platform-modules-juniper/qfx5200/utils/juniper_qfx5200_util.py
This patch set implement the following:
- Setting the FAN frequency
- Corrections to the EM policy with respect to platform
defined temperature / fan values
- Updates to the platform monitoring script logging
- Fixes to platform initialization script
Signed-off-by: Ciju Rajan K <crajank@juniper.net>
=> [Juniper][QFX5200] EM policy updates

platform/centec/sonic-platform-modules-e582/debian/rules, platform/centec/sonic-platform-modules-embedway/debian/rules
PR #4605 has two changes that are missing, fix them.
=> Adding missing changes for centec x86 platform

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/simple-sample-graph-metadata.xml, src/sonic-config-engine/tests/test_cfggen.py
Device needs to know in which cloud it is functioning
Parse the data from minigraph
sonic-config-engine tests updated
Read cloud type data from minigraph
=> Read cloudtype info from minigraph

src/sonic-config-engine/sonic_device_util.py
=> [sonic-config-engine][marvell] read mac address fix

device/barefoot/x86_64-accton_wedge100bf_32x-r0/plugins/sfputil.py
Bugfix
Update plugin with latest changes from the internal repo
Run warm-reboot on BFN switch and check xcvrd  process
=> [BFN] Update sfputil plugin

dockers/docker-sonic-mgmt-framework/Dockerfile.j2, sonic-slave-buster/Dockerfile.j2
1. remove non-essential crossbuild packages from buster slave.
2. solving the mgmt-framework build failure on ARM. due to PIP installs grpcio-tools via source code.
=> ARM64 architecture build issues

device/arista/x86_64-arista_7280cr3_32p4/fancontrol
- Sensor and Fan information added to primary platforms for thermal API.
- Refactors involving better abstractions, code reuse and dead code removal.
- Improvements to the diag capabilities
- Pylintrc added to improve code quality. Will become fatal at a later time.
=> [arista] Update drivers submodules

platform/centec/rules.mk
=> centec_syncd_rpc build failed when set ENABLE_SYNCD_RPC=y

device/marvell/armhf-marvell_et6448m_52x-r0/pmon_daemon_control.json
=> [marvell] skip thermal control daemon for marvell device

platform/centec/sdk.mk
=> update SAI to v1.6.1 for centec x86 platform

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Migration of Barefoot SDK to SAI v1.6.1
=> [BFN] Updated SDK packages to SAI v1.6.1

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated SAI and platform packages to 20200618
=> BFN Update SAI and platform packages to 20200618

platform/mellanox/mlnx-sai.mk
1.  Upgrade SAI headers to v1.6.3
2.  Fix traffic lost during FFB related to buffer config + optimize buffer config timing for FB
3.  Add ACL fields BTH, IP flags
4.  Add ACL infrastructure of different fields per ASIC type
Update the SAI-Implementation submodule pointer and change the version number in makefile.
Run regression test on Mellanox platform
=> [Mellanox] Update SAI to 1.16.5

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
=> [barefoot][SAI v1.6.3] Update SAI and platform packages to 20200701

device/arista/x86_64-arista_7050_qx32/pmon_daemon_control.json, device/arista/x86_64-arista_7050_qx32s/pmon_daemon_control.json, device/arista/x86_64-arista_7050cx3_32s/pmon_daemon_control.json, device/arista/x86_64-arista_7060_cx32s/pmon_daemon_control.json, device/arista/x86_64-arista_7060cx2_32s/pmon_daemon_control.json, device/arista/x86_64-arista_7060px4_32/pmon_daemon_control.json, device/arista/x86_64-arista_7170_32c/pmon_daemon_control.json, device/arista/x86_64-arista_7170_32cd/pmon_daemon_control.json, device/arista/x86_64-arista_7170_64c/pmon_daemon_control.json, device/arista/x86_64-arista_7260cx3_64/pmon_daemon_control.json, device/arista/x86_64-arista_7280cr3_32p4/pmon_daemon_control.json, device/arista/x86_64-arista_common/pmon_daemon_control_skip_thermalctld.json
thermalctld throwing error messages because it is not yet fully configured, disabling it for now on arista platforms.
=> [201911][Arista] Disable thermalctld for arista platforms

device/arista/x86_64-arista_7050_qx32/pmon_daemon_control.json, device/arista/x86_64-arista_7050_qx32s/pmon_daemon_control.json, device/arista/x86_64-arista_7050cx3_32s/pmon_daemon_control.json, device/arista/x86_64-arista_7060_cx32s/pmon_daemon_control.json, device/arista/x86_64-arista_7060cx2_32s/pmon_daemon_control.json, device/arista/x86_64-arista_7060px4_32/pmon_daemon_control.json, device/arista/x86_64-arista_7170_32c/pmon_daemon_control.json, device/arista/x86_64-arista_7170_32cd/pmon_daemon_control.json, device/arista/x86_64-arista_7170_64c/pmon_daemon_control.json, device/arista/x86_64-arista_7260cx3_64/pmon_daemon_control.json, device/arista/x86_64-arista_7280cr3_32p4/pmon_daemon_control.json, device/arista/x86_64-arista_common/pmon_daemon_control_skip_thermalctld.json
thermalctld throwing error messages because it is not yet fully configured, disabling it for now on arista platforms.
=> [master][Arista] Disable thermalctld for arista platforms

dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2, src/sonic-config-engine/minigraph.py, src/sonic-config-engine/sonic-cfggen, src/sonic-config-engine/sonic_device_util.py, src/sonic-config-engine/tests/multi_npu_data/sample-minigraph.xml, src/sonic-config-engine/tests/test_multinpu_cfggen.py
This PR is to resubmit the changes for [4825](https://github.com/Azure/sonic-buildimage/pull/4825)
Add the fix for the test failures
=> Multi ASIC loopback changes

build_debian.sh, installer/x86_64/install.sh, platform/barefoot/bfn-modules/debian/control, platform/barefoot/sonic-platform-modules-bfn-montara/debian/control, platform/barefoot/sonic-platform-modules-bfn-newport/debian/control, platform/barefoot/sonic-platform-modules-bfn/debian/control, platform/barefoot/sonic-platform-modules-wnc-osw1800/debian/control, platform/broadcom/saibcm-modules/debian/control, platform/broadcom/saibcm-modules/debian/opennsl-modules.dirs, platform/broadcom/saibcm-modules/debian/opennsl-modules.install, platform/broadcom/saibcm-modules/debian/rules, platform/broadcom/sonic-platform-modules-alphanetworks/debian/control, platform/broadcom/sonic-platform-modules-cel/debian/control, platform/broadcom/sonic-platform-modules-dell/debian/control, platform/broadcom/sonic-platform-modules-delta/debian/control, platform/broadcom/sonic-platform-modules-inventec/debian/control, platform/broadcom/sonic-platform-modules-mitac/debian/control, platform/cavium/cavm_platform_modules/DEBIAN/control, platform/centec/sonic-platform-modules-e582/debian/control, platform/centec/sonic-platform-modules-embedway/debian/control, platform/innovium/sonic-platform-modules-cel/debian/control, platform/innovium/sonic-platform-modules-delta/debian/control, platform/nephos/nephos-modules/debian/control, platform/nephos/sonic-platform-modules-accton/debian/control, platform/nephos/sonic-platform-modules-cig/debian/control, platform/nephos/sonic-platform-modules-pegatron/debian/control, rules/linux-kernel.mk
upgrade kernel to latest maintenance version 4.9.118
upgrade kernel patch.
rely on kvm testing
=> [kernel]: upgrade linux kernel to 4.9.118

rules/redis.mk
=> Fix `make clean` for redis-tools

device/mellanox/x86_64-mlnx_msn4700-r0/ACS-MSN4700/sai_4700.xml
Support warm reboot on MSN4700.
=> [Mellanox] Support warm reboot on MSN4700

platform/broadcom/sonic-platform-modules-dell/z9264f/scripts/z9264f_platform.sh
- In Z9264 by default, all the ports have disabled low power mode except the last two 10G ports.
- Disabled low power mode in the last two 10G ports.
On branch z9264f-lpmode
(use "git reset HEAD <file>..." to unstage)
modified:   platform/broadcom/sonic-platform-modules-dell/z9264f/scripts/z9264f_platform.sh
- Using command `sfputil show lpmode`.
- Attached logs as reference.
[Logs.txt](https://github.com/Azure/sonic-buildimage/files/4883582/Logs.txt)
[DellEMC] Z9264f Disable low power mode in 10G ports
=> [DellEMC] Z9264f Disable low power mode in 10G ports

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Barefoot, updated SAI and platform packages to 20200710
Barefoot, Updated SAI and platform packages to 20200710
=> [202006][BFN] Update SAI and platform packages to 20200710

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Barefoot, updated SAI and platform packages to 20200710
Barefoot, Updated SAI and platform packages to 20200710
=> [BFN] Update SAI and platform packages to 20200710

device/mellanox/x86_64-mlnx_lssn2700-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn2010-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn2100-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn2410-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn2700-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn2700_simx-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn2740-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn3420-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn3700-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn3700_simx-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn3700c-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn3800-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn4600c-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn4700-r0/system_health_monitoring_config.json, device/mellanox/x86_64-mlnx_msn4700_simx-r0/system_health_monitoring_config.json
The new feature system health support a platform based configuration file. Add configuration files for all Mellanox platform.
Add a configuration file for SN2700, other platform will use a soft link to it.
Manual test on SN2700, SN2410, SN4600C
=> [Mellanox] Add system health configuration file for Mellanox platforms

platform/centec/sdk.mk
update sai to v1.6.3 for centec E582 platform(x86 CPU)
=> [centec][SAI v1.6.3] update sai to v1.6.3

device/arista/x86_64-arista_7280cr3_32p4/fancontrol
Merge most of the changes that recently made it to master.
This will be the last such merge operation and future commits will only cherry-pick fixes and targeted features.
Major fixes and features,
- reboot cause enhancement with more hardware reboot cause reporting
- fix reboot cause parsing issue with 201811 release
- fix get_change_event logic
- fix error message on missing sysfs entry by our plugins
- final piece of the platform refactors for fan and sensor reporting through the platform API
=> [arista] update Arista drivers submodules

device/juniper/x86_64-juniper_qfx5200-r0/Juniper-QFX5200-32C-S/buffers.json.j2, device/juniper/x86_64-juniper_qfx5200-r0/Juniper-QFX5200-32C-S/buffers_defaults_t1.j2, device/juniper/x86_64-juniper_qfx5200-r0/Juniper-QFX5200-32C-S/qos.json.j2
Adding buffers.json.j2, buffers_defaults_t1.j2 and
qos.json.j2 for qfx5200 platform.
Signed-off-by: Ciju Rajan K <crajank@juniper.net>
=> [Juniper][QFX5200] Adding qos.json

files/build_templates/nat.service.j2
Otherwise, it may cause issues for warm restarts, warm reboot.
Warm restart of swss will start nat which is not expected for warm
restart. Also it is observed that during warm-reboot script execution
nat container gets started after it was killed. This causes removal of
nat dump generated by nat previously:
A check [ -f /host/warmboot/nat/nat_entries.dump ] || echo "NAT dump
does not exists" was added right before kexec:
```
Fri Jul 17 10:47:16 UTC 2020 Prepare MLNX ASIC to fastfast-reboot:
install new FW if required
Fri Jul 17 10:47:18 UTC 2020 Pausing orchagent ...
Fri Jul 17 10:47:18 UTC 2020 Stopping nat ...
Fri Jul 17 10:47:18 UTC 2020 Stopped nat ...
Fri Jul 17 10:47:18 UTC 2020 Stopping radv ...
Fri Jul 17 10:47:19 UTC 2020 Stopping bgp ...
Fri Jul 17 10:47:19 UTC 2020 Stopped bgp …
```
=> [services] remove swss from WantedBy for nat service

device/barefoot/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py
Because of platform-specific reasons I have to increase init timeout in (platform-plugin)/eeprom.py
[barefoot][platform] increase init timeout in eeprom.py
=> [barefoot][platform] increase init timeout in eeprom.py

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
* Update SDK packages to SAI 1.6.4
* Add SAI_SWITCH_TYPE_NPU attribute support
=> [bfn] Updated SDK packages to SAI v1.6.4

device/barefoot/x86_64-accton_as9516bf_32d-r0/pmon_daemon_control.json
Signed-off-by: Olha Oliynyk <olhax.oliynyk@intel.com>
=> Added skip_fancontrol, skip_thermalctld for Newport

dockers/docker-base-buster/Dockerfile.j2, dockers/docker-database/Dockerfile.j2, platform/vs/docker-sonic-vs/Dockerfile.j2
buster-backports updated and the old version disappeared.
=> [redis] Upgrade redis version

files/image_config/caclmgrd/caclmgrd.service
Resolves https://github.com/Azure/sonic-buildimage/issues/4971
=> [caclmgrd] Always restart service upon process termination

README.md
Remove obsoleted build job's badge
=> Update README.md: Remove obsoleted build job's badge

scripts/convert-pfx-cert-format.sh
Not necessary to remove the certificate attributes by grep when exporting the private/public certificate.
=> [build]: simplify the function to covert PFX certificate

device/barefoot/x86_64-accton_as9516bf_32d-r0/pmon_daemon_control.json, device/barefoot/x86_64-accton_wedge100bf_32x-r0/pmon_daemon_control.json, device/barefoot/x86_64-accton_wedge100bf_65x-r0/pmon_daemon_control.json
Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
Added skip_pcied for Barefoot platforms
=> [BFN] Added skip_pcied for Barefoot platforms

.github/PULL_REQUEST_TEMPLATE.md
Fix a spelling error in the template. Also make a few other minor tweaks.
=> [.github] Update pull request template

README.buildsystem.md
What I did:-
Fixed Debug Docker run instruction
Verified:
Able to run Debug Docker correctly.
=> [README.buildsystem.md] Fix debug docker run instruction.

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/sonic-cfggen, src/sonic-config-engine/tests/multi_npu_data/sample_port_config-0.ini, src/sonic-config-engine/tests/multi_npu_data/sample_port_config-1.ini, src/sonic-config-engine/tests/multi_npu_data/sample_port_config-2.ini, src/sonic-config-engine/tests/multi_npu_data/sample_port_config-3.ini, src/sonic-config-engine/tests/test_multinpu_cfggen.py, src/sonic-py-common/sonic_py_common/multi_asic.py
The PR implements few common functions needed for CLI and other modules. 
The following common APIs are added for multi ASIC
- an  API to check if a given port is a internal or external port
- an  API to check if a given port-channel is internal or external
- an API to check if a bgp-session is internal or external
- an  API to connect to the config and other dbs in the a given namespace
- added common APIs to the sonic_py_common library.
- update the sample port-config.ini with role column and add corresponding test to verify the ports configuration is - generated properly.
=> [201911] Common functions for Multi ASIC CLIs

src/iccpd/src/iccp_ifm.c
To declare *tb[] but do not initialize it, it might be very risky.
We get iccpd exception during processing arp/nd event.
To declare and initialize *tb[] variable.
Test it based MC-LAG L2 scenario in HLD doc.
=> [iccpd] Fix uninitialized variable.

dockers/docker-orchagent/enable_counters.py
- enable port buffer drops by default
- mellanox/mlnx-sai/SAI-Implementation submodule update:
- reenable port in/out dropped pkts stats
=> Update SAI-Implementation submodule and enable port in/out dropped pkts stats

src/sonic-py-common/sonic_py_common/daemon_base.py
Platform monitor changes in daemon_base for multi_asic to take care of db_connect to databases in different namesapces + additional support API's and class.
Updated the db_connect API and added a new class multiAsic with namespace support functions.
Verified with the xcvrd and ledd processes in pmon docker.
=> Platform monitor changes in daemon_base for multi_asic

src/sonic-py-common/sonic_py_common/device_info.py
Added one more common function to retrieve hostname.
=> [sonic-py-common] Add function to get hostname

rules/docker-platform-monitor.mk, rules/docker-snmp-sv2.mk
- fix watchdog timeout units
- remove arista bind mounts for docker-snmp
- add python3 mounts for pmon
=> [201911][Arista] Update arista drivers submodules

device/arista/x86_64-arista_7800_sup/platform_reboot, device/arista/x86_64-arista_7800_sup/plugins, device/arista/x86_64-arista_7800_sup/pmon_daemon_control.json, device/arista/x86_64-arista_7800r3_48cq2_lc/platform_reboot, device/arista/x86_64-arista_7800r3_48cq2_lc/plugins, device/arista/x86_64-arista_7800r3_48cqm2_lc/platform_reboot, device/arista/x86_64-arista_7800r3_48cqm2_lc/plugins, files/Aboot/boot0.j2
- Merge chassis codebase upstream
- Add support for Otterlake supervisor
- Add support for NorthFace and Camp chassis
- Add support for Eldridge, Dragonfly and Brooks fabrics
- Add support for Clearwater2 and Clearwater2Ms linecards
- Add new arista Cli to power on/off cards
- Add new arista show Cli to inspect supervisor, chassis, fabrics and linecards
=> [Arista] Updating driver submodules

platform/mellanox/mlnx-sai.mk
Signed-off-by: Noa Or <noaor@nvidia.com>
N/A
Change SAI version to 1.17.3
Verified on MSN2700, MSN3800
- Fast boot optimizations
- Added aggregate bridge drops counters per interface via Key/Value setting in SAI XML. In addition don't set soft discard for L2 traps
- Fix RIF mcast enable attribute set/get
=> [Mellanox] Update SAI version to 1.17.3

files/image_config/caclmgrd/caclmgrd
Eliminate duplicate logging code by inheriting from DaemonBase class in sonic-py-common package.
Ensure caclmgrd functionality is unchanged
=> [caclmgrd] Inherit DaemonBase class from sonic-py-common package

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh
To log HW reboot reason registers in DellEMC S6100.
Include the HW reboot reason registers in syslog message.
Logs: [S6100_reboot_logs.txt](https://github.com/Azure/sonic-buildimage/files/5210254/S6100_reboot_logs.txt)
DellEMC S6100: Log HW reboot reason registers
=> DellEMC S6100: Log HW reboot reason registers

rules/docker-platform-monitor.mk
- Fix `show platform firmware` platform plugin error
- Fix import behavior for arista's `sonic_platform` implementation
- Fix fan led color and detection on Smartsville
=> [Arista] Update driver submodules.

dockers/docker-sonic-restapi/restapi.sh, src/sonic-config-engine/minigraph.py
Earlier key name was not accurate.
Change the minigraph.py script
- [*] 201911
=> Rename RestAPI CA cert Conf DB key

README.md
=> Add build badge for Barefoot 202006 build

sonic-slave-buster/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2
libzmq is communication library which will be needed for new communication channel between OA/sairedis and syncd
=> Add libzmq to sonic-slave dockers

platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
Update dynamic minimum fan speed table according to data provided by thermal team.
Update static table in device_data.py.
Manually test.
=> [Mellanox] Update dynamic minimum table for MSN4700, MSN3420 and MSN4600C

platform/p4/docker-sonic-p4.mk, platform/vs/docker-sonic-vs.mk, slave.mk
Make Python3-swsscommon available in image.
=> [baseimage]: add Python3-swss-common package to baseimage.

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated SDK packages to 20201009
=> [BFN] Updated SDK packages to 20201009

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/__init__.py, platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py
=> [barefoot][platform] Platform API 2.0 fixups

platform/broadcom/saibcm-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c
Created a repro where Tx drops were seen
Built an image with the changes in the patch and verified that Tx drops are no longer seen
Broadcom patch to address Tx drop No DMA resource issue
=> [knet] Address Tx drop No DMA resource issue

files/build_templates/swss_vars.j2, src/sonic-config-engine/minigraph.py
To enable synchronous mode by default.
Modify `swss_vars.j2` template file and add enabling synchronous mode in minigraph parser.
=> [synchronous-mode] Enable synchronous mode by default

rules/docker-platform-monitor.mk
- Change `/run/arista` mount to pmon by `/var/run/platform_cache`
- Python3 by default for Arista platform initialisation
- Fix outstanding py2/3 compatibility issues (eeprom mostly)
- Use pytest for unit testing
- Miscellaneous modular fixes
=> [Arista] Update arista driver submodules

src/sonic-yang-models/tests/yang_model_tests/yangModelTesting.py, src/sonic-yang-models/tests/yang_model_tests/yangTest.json, src/sonic-yang-models/yang-models/sonic-acl.yang, src/sonic-yang-models/yang-models/sonic-port.yang, src/sonic-yang-models/yang-models/sonic-portchannel.yang
To partially address https://github.com/Azure/sonic-buildimage/issues/5417, We need few new fields in already added YANG models.
[yang-models]: New fields as per sonic-mgmt minigraph file and to match Azure\Master.
Changes:
-- ACL stage allow lower and upper.
-- ACL include services leaf-list.
-- PORT include pfc_asym leaf.
-- PORT fec allow none as per code.
-- 3 Tests for above changes.
Changes:
-- ACL stage allow lower and upper.
-- ACL include services leaf-list.
-- PORT include pfc_asym leaf.
-- PORT fec allow none as per code.
-- 3 Tests for above changes.
Built PKGs with new build time tests:
```
make[1]: Leaving directory '/home/pchaudha/srcCode/azure_myforks/sonic-buildimage' …
```
=> Yang model update fields

platform/mellanox/mlnx-sai.mk
* Updated SAI to v.1.17.6
* N/A
Enhancements and new features:
- L3 VXLAN new VRF pipeline
- FB vLAN allocation optimization
- Enhanced SAI debug dump with FW dumps
- Implement create method for several switch attributes
- Fine grain ECMP support
- SN4410 system support
- Add bridge disable learn attribute
- Unified log messages format
- Improve various logging messages
Bugs fix:
- Remove route with empty next hop group
```
.---. …
```
=> [Mellanox] Update SAI to v.1.17.6

sonic-slave-buster/Dockerfile.j2
Install Python 3 dependencies in sonic-slave-buster container
=> [sonic-slave-buster] Install Python 3 dependencies in container

platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Wrong object init broke the API.
Replace object to the correct type.
Run api/sfp_test.py on 'sonic-mgmt' case 'test_get_reset_status'.
nature generated with `git commit -s` **
If this is a bug fix, make sure your description includes "fixes #xxxx", or
"closes #xxxx" or "resolves #xxxx"
Please provide the following information:
-->
**- A …
=> [Mellanox] Fix for QSFP-DD channel status

device/dell/x86_64-dellemc_s5232f_c3538-r0/pmon_daemon_control.json, platform/broadcom/sonic-platform-modules-dell/s5232f/modules/dell_s5232f_fpga_ocores.c, platform/broadcom/sonic-platform-modules-dell/s5232f/scripts/platform_sensors.py, platform/broadcom/sonic-platform-modules-dell/s5232f/scripts/s5232f_platform.sh, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/__init__.py, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/chassis.py, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/component.py, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/eeprom.py, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/fan.py, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/fan_drawer.py, platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/thermal.py
* Fix platform sensors
* fpga driver update for bug fixes
* Update fixes for API 2.0 code
Fixes identified in S5232 platform code are fixed in community code
Change to platform specific code under platform directory specific to s5232
verified on s5232 platform logs attached
* Fix platform sensors
* Fix issues reported in fpga driver
* Update fixes for API 2.0 platform code
=> [DellEMC S5232f] Updates and bug fixes for platform

platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan.py, platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/platform.py, platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/psu.py, platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/sfp.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/fan.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/platform.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/psu.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py, platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/watchdog.py
Fix platform API issues in DellEMC S6000, S6100.
- Change return type of SFP methods to match specification in sonic_platform_common/sfp_base.py
- Use init methods of base classes to initialize common instance variables
- Handle negative timeout values in S6100's watchdog ‘arm’ method
- Return appropriate values for 'get_target_speed', 'set_status_led' to avoid false warnings 
Wrote a python script to load Chassis class and then call the APIs accordingly and verify the return type.
[DellEMC]: S6100, S6000 - Platform API fixes
=> [DellEMC]: S6100, S6000 - Platform API fixes

rules/sonic-host-service.dep
It fixes the following error during build.
>>> fatal: not a git repository (or any of the parent directories): .git
"SONIC_DPKG_CACHE_METHOD"         : "cache"
"DPKG_CACHE_PATH"                 : "/var/cache/sonic/artifacts"
Fatal error is show.
Host service is added for build with conditional directives.
Full build.
=> Fixes: fatal: not a git repository error during build

check_install.py, dockers/docker-fpm-quagga/bgpcfgd, dockers/docker-lldp/lldpmgrd, dockers/docker-nat/restore_nat_entries.py, dockers/docker-orchagent/enable_counters.py, dockers/docker-sflow/port_index_mapper.py, files/build_scripts/generate_asic_config_checksum.py, files/image_config/corefile_uploader/core_uploader.py, files/image_config/misc/docker-wait-any, files/scripts/core_cleanup.py, files/scripts/supervisor-proc-exit-listener, files/scripts/update_chassisdb_config
Align style with slightly modified PEP8 standards (extend maximum line length to 120 chars). This will also help in the transition to Python 3, where it is more strict about whitespace, plus it helps unify style among the SONiC codebase. Will tackle other directories in separate PRs.
Using `autopep8 --in-place --max-line-length 120` and some manual tweaks.
=> [Python] Align files in root dir, dockers/ and files/ with PEP8 standards

files/Aboot/boot0.j2
- Enhance eeprom parsing robustness on corrupted fields
- Add chassis provisioning service
- Disable CPU sleep state on some systems
- Complete refactor for FanSlots
- Fix module unload while still in use
=> [Arista] Update driver submodules

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
Support for dual tor option in dhcp docker template
=> Support for dual tor option in dhcp docker template

platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
Add high threshold and high critical threshold support for gearbox
Read gearbox thermal related threshold from sysfs
Manual test
=> [Mellanox] Add high threshold and high critical threshold support for gearbox

dockers/docker-ptf/Dockerfile.j2
Upgrading the reference for the Python GNMI tool repository. [The commit for the new payload](https://github.com/lguohan/gnxi/commit/53901aba9ead82be21f1408a601b6266dcf1e3e4)
Commit reference updated in the PTF docker file where that tool is needed.
PyTest suite for telemetry service should pass.
NA
Upgrading the reference for the Python GNMI tool repository to latest commit.
```
,_     _
|\\_,-~/
/ _  _ |    ,--.
(  @  @ )   / ,-'
\  _T_/-._( (
/         `. \
|         _  \ |
\ \ ,  /      |
|| |-_\__   /
((_/`(____,-'
```
source: www dot asciiart dot eu
=> Updating Python-based GNMI client

platform/marvell-armhf/sai.mk
Updated sai deb version to v1.7.1 for marvell platforms.
=> [marvell] update sai version to v1.7.1

platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/z9332f_platform.sh, platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/__init__.py, platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
Fixed issues identified in dev/system test
Changing platform api 2.0 code and platform startup script
verified on target 9332
[DellEMC-Z9332f] Fix platform issues
* Change to optoe driver
* fix API 2.0 issues
* Support reboot reason
=> [DellEMC-Z9332f] Fix platform issues

src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py, src/sonic-yang-models/tests/yang_model_tests/yangTest.json, src/sonic-yang-models/yang-models/sonic-acl.yang, src/sonic-yang-models/yang-models/sonic-portchannel.yang, src/sonic-yang-models/yang-models/sonic-vlan.yang
[yang-models]: Default value for leaf-lists and tests.
Changes:
-- Add Default value for leaf-lists in ACL and portchannel.
-- Remove members in VLAN.
-- Test modifications.
Used default statement of YANG RFC 7950.
Build Time Tests
=> [yang-models]: Default value for leaf-lists and tests.

dockers/docker-sonic-mgmt/Dockerfile.j2
Signed-off-by: Wei Bai webai@microsoft.com
Tgen API 0.0.42 has many problems. We have fixed them in 0.0.70. 
Modify docker file of sonic mgmt
Run tests in sonic mgmt docker. 
=> [sonic-mgmt] Upgrade Tgen API in sonic mgmt docker

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
=> [BFN] Updated SAI headers to v1.7.1

Makefile.work
* To fix build issue
* Fixed Makefile.work
* N/A
```
'//||\\`
''``
```
=> [buildsystem] Fix syntax error: unexpected end of file

platform/broadcom/sonic-platform-modules-cel/haliburton/script/50-ttyUSB-C0.rules
Udev rules need to support 2*C0 devices totally 96 ports. But it only support 48 ports before.
Add more items into the udev rules
use command consutil show can shows 1~96. Disconnect 2*C0 device from E1031 it pops out that port 1 to port 96 been disconnected. consutil connect X can connect to the assigned port.
**- loginfo**
=> Update udev rules to support 96 ttyUSB ports

device/barefoot/x86_64-accton_as9516_32d-r0/syncd.conf
To fix the default profile used for that platform
Cherry-pick fixes from master
=> [Barefoot] [201911] Fix default profile for Newport

README.md
To update the README for the 202012 release.
Created the 202012 build jobs on Jenkins and added the badges here.
n/a
=> [README] Update build badges to include 202012 build status

azure-pipelines.yml
add mellanox build to azure-pipeline
=> [ci]: add mellanox build to azure-pipeline

sonic-slave-buster/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2
=> Upgrade python lxml library version to 4.6.2

device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/hwsku.json, device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-C28D8/hwsku.json, device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/hwsku.json, device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700/hwsku.json, device/mellanox/x86_64-mlnx_msn2700-r0/platform.json
Created capability files according to platform specification `SN2700`
=> [DPB] [Mellanox] added capability files for SN2700 platform

device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/hwsku.json, device/mellanox/x86_64-mlnx_msn2010-r0/platform.json
Created capability files according to platform specification `SN2010`
=> [DPB] [Mellanox] added capability files for SN2010 platform

device/mellanox/x86_64-mlnx_msn2100-r0/ACS-MSN2100/hwsku.json, device/mellanox/x86_64-mlnx_msn2100-r0/platform.json
Created capability files according to platform specification `SN2100`
=> [DPB] [Mellanox] added capability files for SN2100 platform

device/mellanox/x86_64-mlnx_msn4410-r0/ACS-MSN4410/hwsku.json, device/mellanox/x86_64-mlnx_msn4410-r0/platform.json
Created capability files according to platform specification `SN4410`
=> [DPB] [Mellanox] added capability files for SN4410 platform

device/mellanox/x86_64-mlnx_msn4600c-r0/ACS-MSN4600C/hwsku.json, device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D112C8/hwsku.json, device/mellanox/x86_64-mlnx_msn4600c-r0/platform.json
Created capability files according to platform specification `SN4600C`
=> [DPB] [Mellanox] added capability files for SN4600C platform

platform/mellanox/hw-management/Makefile
sudo leave the build system files with root
use dpkg-buildpackage build with fakeroot
build the package
=> [mellanox]: fix mellanox hw-management build

.artifactignore, azure-pipelines.yml
build docker-sonic-vs.gz in kvm build pipeline
check the build results
=> [ci]: build docker-sonic-vs.gz in kvm build pipeline

files/image_config/sudoers/sudoers
=> Cleanup sudoers file

azure-pipelines.yml
build ptf and syncd-rpc for broadcom and mellanox
build in the ci
check build
=> [ci]: build ptf and syncd-rpc for broadcom and mellanox

azure-pipelines.yml
add vs tests in the azure pipeline
modify ci file
=> [ci]: add vs tests

azure-pipelines.yml
fix archive memdump facts when kvmtest fails
correct ownership of artifacts
=> [ci]: correct ownership of artifacts

sonic-slave-buster/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2, src/sonic-bgpcfgd/setup.py, src/sonic-config-engine/setup.py, src/sonic-frr-mgmt-framework/setup.py
RCE resolved in new version https://github.com/yaml/pyyaml/issues/420
=> Bump pyyaml from 5.3.1 to 5.4.1

.github/CODEOWNERS
=> [codeowners]: Add as owners of some folders

azure-pipelines.yml
exclude .github from trigger build
=> [ci]: exclude .github from trigger build

device/barefoot/x86_64-accton_wedge100bf_65x-r0/mavericks/hwsku.json, device/barefoot/x86_64-accton_wedge100bf_65x-r0/platform.json
platform.json and hwsku.json replacement for deprecated port_config.ini. Also this files need for Dynamic Port Breakout.
Added platform.json, hwsku.json files according to platform specification.
=> [barefoot] add platform.json, hwsku.json for mavericks

Makefile.work, src/sonic-build-hooks/hooks/git
bug fix for reproducible build of git
What I fixed is the commit "bac9309". git used unexpected env REAL_COMMAND.
=> Version control git

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
To fix Barefoot platform 201911 build
=> [BFN] Updated SAI/SDK packages to 20210128

.azure-pipelines/build-template.yml, .azure-pipelines/cleanup.yml, .azure-pipelines/official-build.yml
add marvel armhf official build
=> [ci]: add marvel armhf official build

device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/hwsku.json, device/barefoot/x86_64-accton_wedge100bf_32x-r0/platform.json
platform.json and hwsku.json replacement for deprecated port_config.ini. Also this files need for Dynamic Port Breakout.
Added platform.json, hwsku.json files according to platform specification.
=> [barefoot] Add hwsku.json, platform.json for montara

.azure-pipelines/build-template.yml, azure-pipelines.yml
=> [ci]: use build-template for pr build

.azure-pipelines/build-template.yml, .azure-pipelines/cleanup.yml
restructure repo clean up to make it robust
current clean up code still having issue.
https://dev.azure.com/mssonic/build/_build/results?buildId=3222&view=logs&j=a5b8631f-d2a8-5bf4-c5b7-ed5dd46e146c&t=87efb6df-f2c3-5473-8b4b-3f370bdf0008
verify locally.
=> [ci]: restructure repo clean up to make it robust

platform/broadcom/saibcm-modules/debian/opennsl-modules.install
match linux kernel version
check pr build
=> [saibcm-modules]: match linux kernel version

device/accton/x86_64-accton_as7312_54x-r0/sonic_platform/sfp.py, platform/broadcom/sonic-platform-modules-cel/services/platform_api/sonic_platform/sfp.py, platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
Submodule commits included:
* src/sonic-platform-common 6ad0004...bd4dc03 (1):
> [sonic_sfp/qsfp_dd.py] Update DOM capability method name to align with other drivers (#163)
Also align all calling function names to match.
=> [sonic-platform-common] Update submodule

device/barefoot/x86_64-accton_wedge100bf_32x-r0/plugins/sfputil.py
Fixed sfp reset in Barefoot's  sfputil
=> [barefoot][device][plugins] Fix sfp reset

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py
Fix wrong sfp reset return value
=> [barefoot][sonic-platform] Fix sfp reset

device/dell/x86_64-dell_s6000_s1220-r0/platform.json, device/dell/x86_64-dell_s6100_c2538-r0/platform.json
To add platform.json used for sonic-mgmt testing in DellEMC S6000, S6100 platforms.
Include platform.json in respective platform's device/ directory.
Ran sonic-mgmt platform api test cases that require platform facts and verified that they pass.
[DellEMC] Add platform.json for S6000, S6100
=> [DellEMC] Add platform.json for S6000, S6100

device/dell/x86_64-dell_s6000_s1220-r0/platform_reboot
Reboot command in Dell S6000 failed to reboot the switch.
Added retry mechanism and CPU reset.
Execute reboot command in Dell S6000.
[S6000_reboot_UT.txt](https://github.com/Azure/sonic-buildimage/files/5930031/S6000_reboot_UT.txt)
=> [201811] Dell: Fix S6000 reboot issue 

dockers/docker-router-advertiser/docker-router-advertiser.supervisord.conf.j2
=> Disable radv for specific deployment_id

platform/barefoot/sonic-platform-modules-bfn-newport/configs/network/interfaces.d/eth2
It is needed for the current platform to pass MTU testcase
Edit interface file 
run mtu CT on Newport DUT
Fixed MTU test for Newport device
=> [BFN] Fix MTU for internal interface

.azure-pipelines/azure-pipelines-Official.yml, .azure-pipelines/azure-pipelines-UpgrateVersion.yml, .azure-pipelines/azure-pipelines-build.yml, .azure-pipelines/azure-pipelines-job-groups.yml
Support SONiC reproducible build on 202012
Add the 202012 official azure pipeline and the version upgrade azure pipeline, the version upgrade azure pipeline builds the same targets with the official azure pipeline, only different build options.
Send the version change pull request automatically in the version upgrade azure pipeline.
The 202012 official azure pipeline is copied from Jenkins pipelines, including vs, broadcom, centec, innovium, mellanox and nephos.
Official Pipeline:
https://dev.azure.com/mssonic/build/_build?definitionId=21&_a=summary
Version Upgrade Pipeline:
https://dev.azure.com/mssonic/build/_build?definitionId=40&_a=summary
Pull Request Example:
https://github.com/xumia/sonic-buildimage-1/pull/17/files
=> Add azure pipelines for reproducible build

platform/marvell-armhf/sai.mk
=> [Marvell] Updated armhf SAI deb version info.

platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/sfp.py, platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/sfp.py, platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
EEPROM read failure was seen in Dell platforms
Make python 2/3 compliant API's to fix the issue 
Check sfpshow eeprom and dom CLI output.
=> DellEMC: Fix EEPROM read error

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/t0-sample-graph.xml, src/sonic-config-engine/tests/test_cfggen.py, src/sonic-config-engine/tests/test_minigraph_case.py
Same as https://github.com/Azure/sonic-buildimage/pull/6895
But target against 201911 branch
=> For egress ACL attaching to vlan, we break them into vlan members

sonic-slave-stretch/Dockerfile.j2
Install pyroute2 need for sonic-utilities in sonic-slave-stretch docker.
Submodule update of sonic-utilities to the commit `9297d5c5a00e64b5dea94a49a69cb776ac862bdc`
Update the ` sonic-slave-stretch/Dockerfile.j2 ` to install pyroute2
=> [201911][baseimage] Install pyroute and submodule update sonic-utilities 

device/mellanox/x86_64-mlnx_msn3700c-r0/pcie.yaml, device/mellanox/x86_64-mlnx_msn3800-r0/pcie.yaml
To fix PCIEd errors in log.
Update pcie.yaml with the right PCI addresses.
Check logs, operation occurs each minute.
N/A
=> [Mellanox]: Fix PCIEd configuration files for SN3700 and SN3800 systems

device/mellanox/x86_64-mlnx_msn4600-r0/platform.json
Fix the build and fix the SN4600 DPB support
Fix port configuration file for SN4600 based on recent changes 
System bringup is completed, all interfaces are up.
Platform tests suits all is passing.
=> [DPB] [Mellanox] Fix files for SN4600 platform

platform/broadcom/sai.mk
Upgrading bcmsai from 4.3.0.13 to 4.3.3.1
Merged bcmsai 4.3.3.1 code to top of master bcmsai 4.3.0.13.
Ran basic tests on T0 like bgp sessions, interface up, fib, fdb tests
Upgrading bcmsai from 4.3.0.13  to 4.3.3.1
=> Updated BCM SAI to latest 4.3.3.1 drop

dockers/docker-fpm-frr/start.sh, files/image_config/hostcfgd/hostcfgd
Why I did:-
This PR is cherry-pick of master for 201911
https://github.com/Azure/sonic-buildimage/pull/6920
Signed-off-by: Abhishek Dosi <abdosi@microsoft.com>
Co-authored-by: Arvind <arlakshm@microsoft.com>
=> [201911] Add support for BGP Monitors on multi asic SONiC platforms.

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
[barefoot] Improve sonic_platform PSU support
=> [barefoot][platform] Extend sonic_platform psu.py

device/barefoot/x86_64-accton_as9516_32d-r0/pmon_daemon_control.json, device/barefoot/x86_64-accton_wedge100bf_32x-r0/pmon_daemon_control.json, device/barefoot/x86_64-accton_wedge100bf_65x-r0/pmon_daemon_control.json
NOTE
depended on #7004
[barefoot] Enable thermalctld
=> [barefoot][device] Enable thermalctld

.artifactignore, azure-pipelines.yml
=> [ci]: add ci/pr build for 202012

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
Add -si support in dhcp docker template
=> DHCP Relay: add -si support in dhcp docker template

files/image_config/procdockerstatsd/procdockerstatsd
Fixed incorrect name in script
Ran script locally and checked stats-db for values
=> [201911][procdockerstatsd] Fix bug in procdockerstatsd

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Fix for vlan-id ACL filter introduced in [SONiC 201911 #234](https://sonic-jenkins.westus2.cloudapp.azure.com/job/barefoot/job/buildimage-bf-201911/234/changes#95ec75e24ed2c95186c9ab8367bc17dfadc0d44b)
=> [BFN] Updated SAI/SDK packages to 20210317

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
- Update unsupported SAI attr ('SAI_ACL_TABLE_ATTR_FIELD_OUTER_VLAN_ID') to fix issues on acl table create
Updated SDK packages to 20210324
Build and run SONiC on BFN platform
BFN SDK updated to 20210324
=> [BFN] Updated SDK packages to 20210324

files/image_config/procdockerstatsd/procdockerstatsd
=> [201911][procdockerstatsd] fix typo for variable name 

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated SDE due to issue in driver part
=> [BFN] Updated SAI/SDK packages to 20210405

files/image_config/updategraph/updategraph
To introduce a new devicetype EPMS
- [-] 201811
=> [201811]: Disable PFCWD on new devicetype EPMS

sonic-slave-buster/Dockerfile.j2, sonic-slave-stretch/Dockerfile.j2
nose package is required by mockredispy
Fix #7248 
use pr test
=> [sonic-slave]: install nose package explicity

.github/labeler.yml, .github/workflows/automerge.yml, .github/workflows/label.yml
Support to merge the SONiC package versions upgrade pull request automatically.
Add the automerge tag in the pull request.
1. Sent by the author mssonicbld
2. Only contains changes in files/build/**/*
3. Only for the specified branch 202012
Merge the pull request.
1. Sent by the author mssonicbld
2. The Azure Pipelines checker complete and successful
3. The pull request contains label automerge
=> [ci] Support to merge SONiC package versions change pr automatically

README.buildsystem.md, README.md
Fix typos in documents
Fix typos in documents
=> [doc]: Fix typos in documents

.azure-pipelines/azure-pipelines-image-template.yml, .azure-pipelines/cleanup.yml, azure-pipelines.yml
Use the same build template in build process.
=> [CI] Use the same template in both PR build and official build.

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
=> [CI] Support 202012 branch reproducible build to generate version files.

azure-pipelines.yml
PR build in 202012 branch is already enabled. Sync up from 202012 to master
=> [CI] Update azure PR pipeline file. Not affect pipeline running

.azure-pipelines/azure-pipelines-build.yml
Improve the SONiC version, fix the "azure pipeline build id" part
```
<target branch name>-<pullrequest id>.<azure pipelines build id>-<merge commit id>
Example: master-7381.11668-43df5c87
```
Relative PR: https://github.com/Azure/sonic-buildimage/pull/7381
The current PR merge validation version is correct.
```
"SONIC_IMAGE_VERSION"             : "master-7406.12156-d1515fde"
```
https://dev.azure.com/mssonic/build/_build/results?buildId=12156&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318
=> [ci] Export the azure pipeline build id for SONiC version

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
In SONiC master 182 SAI 1.8.1 have  been introduced
Update bfn SDK with SAI 1.8.1 support 
Run sanity on top of SONiC Master 182 with SDE SAI 1.8.1
=> [ BFN ] Updated SAI to 1.8.1

.azure-pipelines/azure-pipelines-UpgrateVersion.yml, .azure-pipelines/azure-pipelines-build.yml, .azure-pipelines/azure-pipelines-image-template.yml, .azure-pipelines/azure-pipelines-job-groups.yml, .azure-pipelines/build-template.yml, .azure-pipelines/cleanup.yml, .azure-pipelines/official-build.yml, .azure-pipelines/run-test-template.yml, azure-pipelines.yml
Signed-off-by: Shilong Liu <shilongliu@microsoft.com>
Copy directory '.azurepipelines' in master branch into 202012, to setup official build in 202012.
=> [CI] Add azure pipeline file for official build in 202012 branch

dockers/docker-sonic-mgmt/Dockerfile.j2
Signed-off-by Wei Bai webai@microsoft.com
Upgrade Tgen API
Modify dockerfile
Run IXIA tests in SONiC mgmt docker with new Tgen API version
=> Upgrade Tgen version in SONiC mgmt docker

files/build_templates/swss_vars.j2
* To support new configuration attribute
* N/A
* N/A
* N/A
```
'//||\\`
''``
```
=> [swss_vars] Add 'resource_type' attribute

src/dhcpmon/src/dhcp_device.c, src/dhcpmon/src/dhcp_device.h, src/dhcpmon/src/dhcp_devman.c, src/dhcpmon/src/dhcp_devman.h, src/dhcpmon/src/main.c
dhcpmon: support dual tor scenario with option <-u interface>
Tested and verified on a vs testbed.
=> dhcpmon: support dual tor scenario

dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
dhcpmon: support dual tor in docker template with option <-u interface>
=> dhcpmon: support dual tor in docker template

device/mellanox/x86_64-mlnx_msn2010-r0/platform.json, device/mellanox/x86_64-mlnx_msn2100-r0/platform.json, device/mellanox/x86_64-mlnx_msn2410-r0/platform.json, device/mellanox/x86_64-mlnx_msn2700-r0/platform.json, device/mellanox/x86_64-mlnx_msn2740-r0/platform.json, device/mellanox/x86_64-mlnx_msn3420-r0/platform.json, device/mellanox/x86_64-mlnx_msn3700c-r0/platform.json, device/mellanox/x86_64-mlnx_msn3800-r0/platform.json, device/mellanox/x86_64-mlnx_msn4410-r0/platform.json, device/mellanox/x86_64-mlnx_msn4600-r0/platform.json, device/mellanox/x86_64-mlnx_msn4600c-r0/platform.json, device/mellanox/x86_64-mlnx_msn4700-r0/platform.json
Current platform.json lacks some peripheral device related facts, like chassis/fan/pasu/drawer/thermal/components names, numbers, etc.
Add platform device facts to the platform.json file
Run sonic-mgmt platform API tests which depend on these facts.
=> [Mellanox] Enhance the platform.json with adding more platform device facts.

azure-pipelines.yml
build swi on broadcom platform for pr
=> [ci]: build swi on broadcom platform for pr

files/build_templates/swss_vars.j2
* To support new configuration attribute
* N/A
* N/A
* N/A
```
'//||\\`
''``
```
=> [swss_vars]: Add 'resource_type' attribute

sonic-slave-buster/Dockerfile.j2
Possible fix for https://github.com/Azure/sonic-buildimage/issues/7465
=> Add aspell-en to main package list sonic-slave-buster docker file

sonic-slave-buster/Dockerfile.j2
Read more here: https://bugs.launchpad.net/qemu/+bug/1805913
Read https://github.com/Azure/sonic-buildimage/issues/7465
=> Disable aspell on armhf

sonic-slave-buster/Dockerfile.j2
Read more here: https://bugs.launchpad.net/qemu/+bug/1805913
Read https://github.com/Azure/sonic-buildimage/issues/7465
=> [202012] Disable aspell for armhf

device/mellanox/x86_64-mlnx_msn2010-r0/platform.json, device/mellanox/x86_64-mlnx_msn2100-r0/platform.json, device/mellanox/x86_64-mlnx_msn2410-r0/platform.json, device/mellanox/x86_64-mlnx_msn2700-r0/platform.json, device/mellanox/x86_64-mlnx_msn2740-r0/platform.json, device/mellanox/x86_64-mlnx_msn3420-r0/platform.json, device/mellanox/x86_64-mlnx_msn3700-r0/platform.json, device/mellanox/x86_64-mlnx_msn3700c-r0/platform.json, device/mellanox/x86_64-mlnx_msn3800-r0/platform.json, device/mellanox/x86_64-mlnx_msn4410-r0/platform.json, device/mellanox/x86_64-mlnx_msn4600-r0/platform.json, device/mellanox/x86_64-mlnx_msn4600c-r0/platform.json, device/mellanox/x86_64-mlnx_msn4700-r0/platform.json
Current platform.json lacks some peripheral device related facts, like chassis/fan/pasu/drawer/thermal/components names, numbers, etc.
Add platform device facts to the platform.json file
Run sonic-mgmt platform API tests which depend on these facts.
=> [Mellanox] [202012] Enhance the platform.json with adding more platform device facts.

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
Fix some of the versions in files/build/versions folder not cleanup issue when generating new version configuration.
Remove the older versions
=> [ci] Fix old versions not cleanup issue

.azure-pipelines/official-build.yml
Signed-off-by: Shilong Liu <shilongliu@microsoft.com>
=> [CI] Enable azp official build in release branch

dockers/docker-fpm-frr/base_image_files/rvtysh
Change the type issue in the command rvtysh
change PARA/para to PARAM/param
=> Fix the type issue in rvtysh

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Includes fix for ACL counter (changed to 64 bit)
=> [BFN] Updated SAI/SDK packages to 20210519

device/barefoot/x86_64-accton_wedge100bf_65x-r0/pcie.yaml, device/barefoot/x86_64-accton_wedge100bf_65x-r0/pmon_daemon_control.json
Add pcie.yaml to enable pcied on Mavericks platform
=> [barefoot][device] Support pcied on Mavericks

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/platform_reboot_pre_check, platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh
- To recover the SSD upgrade state in case, if ONIE-uninstall or ssd_fw_upgrade folder got deleted.
- To handle newer SSD version(S21506G - 3IE GPIO7 low devices).
- Also correcting the error messages for non-upgraded S6100s.
On branch s6100_ssd_status
(use "git reset HEAD <file>..." to unstage)
modified:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/platform_reboot_pre_check
modified:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh
Attached logs for reference.
[PR logs.txt](https://github.com/Azure/sonic-buildimage/files/6531550/PR.logs.txt)
root@sonic:~# ls -l /host/ssd_fw_upgrade/
total 8
-rw-r--r-- 1 root root    0 May 23 04:41 GPIO7_pending_upgrade
-rw-r--r-- 1 root root 6508 May 23 04:41 upgrade.log …
=> [DellEMC] 201911 Recovering the SSD upgrade status post reload in S6100

files/build_templates/per_namespace/swss.service.j2
Requirement to remove ordering dependency between SWSS and pmon
=> [swss.service]: Remove ordering with pmon

.azure-pipelines/official-build.yml
Adjust azp official build artifacts and platform to keep same with Jenkins.
=> [CI] Adjust azp build artifacts and platform to keep same with Jenkins

device/mellanox/x86_64-mlnx_msn4600-r0/get_sensors_conf_path, device/mellanox/x86_64-mlnx_msn4600-r0/sensors.conf.a1, platform/mellanox/hw-management/0002-hw-mgmt-system-MSN4600-A1-BU-config1-fix.patch
Add support to Mellanox MSN4600 A1 system
Add new sensor conf for MSN4600 A1 system
Add a Mellanox hw-management patch to support MSN4600 A1 system
Run regression test on this new system, no failed seen related to this new platform.
=> [Mellanox] Add support for MSN4600 A1 system

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/fan_drawer.py
To fix https://github.com/Azure/sonic-buildimage/issues/7758
Fixed typo
Fix Fan.set_speed in barefoot's sonic_platform
=> [barefoot][sonic-platform] Fix Fan.set_speed

.azure-pipelines/azure-pipelines-build.yml
To enable syncd-rpc for Barefoot build
Set the flag
```
ENABLE_SYNCD_RPC=y make configure PLATFORM=barefoot
ENABLE_SYNCD_RPC=y make all
```
=> [BFN] Enable syncd-rpc build

device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/fan.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/psu.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/sfp.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/thermal.py
Add get_status api and fix for read fan direction sysfs to fan.py
Fix code.
Test fan case in sonic_platform
=> [AS5835-54x] Add get_status api and fix bug to fan.py

files/image_config/config-setup/config-setup
=> Fixed typos in config-setup

.azure-pipelines/azure-pipelines-build.yml
To fix syncd-rpc build for BFN paltform
Add missed argument
Run azure-pipelines-build.yml
=> [BFN] Add missed param for syncd-rpc build

.azure-pipelines/azure-pipelines-build.yml
=> [ci]: set -ex for official build to exit on any build failures

src/sonic-config-engine/minigraph.py, src/sonic-config-engine/tests/sample_output/ports.json, src/sonic-config-engine/tests/simple-sample-graph.xml, src/sonic-config-engine/tests/test_cfggen.py
Backport #7744
Build sonic_config_engine-1.0-py2-none-any.whl successfully
=> [201911] Add support to parse bandwidth for DeviceMgmtLinks

.azure-pipelines/azure-pipelines-build.yml
There is no rule to build swi target. The correct target is *.bin.
Fix official build target for Innovium
=> [CI] Fix azp targets for innovium platform

platform/marvell-armhf/sai.mk
Migrate SAI deb version to 1.8.1 for Marvell armhf platforms.
sai.mk file changed.
Loaded sai deb with master commit.
=> [Marvell] Updated Marvell armhf sai deb version to 1.8.1

.azure-pipelines/docker-sonic-mgmt.yml
Test team need to download artifacts from pipeline.
Add publish artifacts step in azure pipeline
=> [CI] Add publish step in docker-sonic-mgmt azure pipeline

device/accton/x86_64-accton_as9716_32d-r0/plugins/sfputil.py
sfputil eeprom need to support QSFP-DD
plugins/sfputil.py include inf8628.py
Use the command "sfputil show eeprom" to verify get eeprom info is correct.
Ex:
Ethernet96: SFP EEPROM detected
Identifier: QSFP-DD Double Density 8X Pluggable Transceiver
Interrupt Asserted: On
Module State: Unknown State 0
Revision Compliance: 3.0
Vendor Name: EdgecoreNetworks
Vendor Part Number: ET7502-DAC-2.5M
Vendor Revision: A0
Vendor Serial Number: J22033303008
This PR only want to merge on 202012 branch.
=> [as9716-32d] Accton sfputil support QSFP-DD on 202012 branch.

platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/psu.py
Updated Z9332f PSU threshold values.
Fetch the PSU voltage and temperature threshold via ipmitool
Check "show system-health summary/detail,show psu temperature" and verify whether pmon is running fine.
[Z9332f PSU threshold UT.txt](https://github.com/Azure/sonic-buildimage/files/6623446/Z9332f.PSU.threshold.UT.txt)
=> DellEMC: Z9332f update PSU threshold

src/sonic-py-common/sonic_py_common/device_info.py
Fixed Switch MAC address parsing logic for Marvell platforms.
Fixed parsing logic in file "src/sonic-py-common/sonic_py_common/device_info.py"
sonic-cfggen -H --print-data
=> [Marvell] Fix system MAC parsing logic for Marvell platform.

.azure-pipelines/azure-pipelines-build.yml
Support the rpc image for mellanox.
Jenkins Pipeline reference:
https://github.com/Azure/sonic-build-tools/blob/master/jenkins/mellanox/buildimage-mlnx-202012-rpc/Jenkinsfile
https://github.com/Azure/sonic-build-tools/blob/master/jenkins/mellanox/buildimage-mlnx-201911-rpc/Jenkinsfile
Rename the sync_rpc_image to docker_syncd_rpc_image
Add a new parameter syncd_rpc_image to build sonic-mellanox-rpc.bin
See the artifacts in https://dev.azure.com/mssonic/build/_build/results?buildId=20099&view=results
=> [ci]: Support the rpc image for mellanox

platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/psu.py
- Fix missing PSUBase class methods
Failures observed when running the open community platform test suite (sonic-mgmt)
Call PSUBase class initializer from derived class
Run the TestPsuApi platform test
[Nokia ixs7215]: Fix missing PSUBase class methods
=> [Nokia ixs7215] Platform API 2.0 improvements

platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py, platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
Cherry-pick https://github.com/Azure/sonic-buildimage/pull/7808
Remove EEPROM cache file and use DB instead
1. Read EEPROM data from DB if possible
2. If data is not ready in DB, read from hardware using a visitor pattern
Manual test and regression
=> [Mellanox] [202012] Backport 'Read EEPROM data from DB if possible'(7808) to 202012

.azure-pipelines/azure-pipelines-build.yml
Support the rpc image for mellanox.
Rename the sync_rpc_image to docker_syncd_rpc_image
Add a new parameter syncd_rpc_image to build sonic-mellanox-rpc.bin
=> [ci]: build rpc image for mellanox (#7905)

device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/__init__.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/chassis.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/component.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/eeprom.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/eeprom.py.bak, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/event.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/fan.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/helper.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/platform.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/psu.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/sfp.py, device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/thermal.py, platform/broadcom/sonic-platform-modules-accton/as5835-54x/sonic_platform_setup.py, platform/broadcom/sonic-platform-modules-accton/as5835-54x/utils/accton_as5835_54x_util.py, platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as5835-54x.install
Add support API2 to 202012 branch
Implement sonic_platform need files
Test sensors.
root@sonic:/home/admin# sensors
ym2401-i2c-11-58
Adapter: i2c-2-mux (chan_id 1)
in3:         +11.91 V
fan1:        3000 RPM
temp1:        +35.0 C
power2:       75.00 W
curr2:        +6.82 A
lm75-i2c-21-4a
Adapter: i2c-2-mux (chan_id 3)
temp1:        +28.5 C  (high = +80.0 C, hyst = +75.0 C)
ym2401-i2c-12-5b
Adapter: i2c-2-mux (chan_id 2)
in3:          +0.00 V
fan1:           0 RPM
temp1:        +27.0 C
power2:        0.00 W
curr2:        +0.00 A
lm75-i2c-19-4c
Adapter: i2c-2-mux (chan_id 1)
temp1:        +31.0 C  (high = +80.0 C, hyst = +75.0 C)
as5835_54x_fan-i2c-3-63
Adapter: i2c-0-mux (chan_id 1)
fan1:        9750 RPM
fan2:        9750 RPM
fan3: …
=> [as5835-54x] Add api2 and modify sfp.py to 202012br

.azure-pipelines/official-build-cache.yml
This job will make cache file more quickly than official build.
Migrate this job to azp from Jenkins.
=> [CI] Azp add cache-building job

platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
QSFP-DD DOM RX/TX values are not retrieved properly.
Defined DOM offsets as defined in CMIS 4 spec.
Check "show interfaces transceiver eeprom -d" output.
[QSFP_DD_DOM_UT.txt](https://github.com/Azure/sonic-buildimage/files/6717625/QSFP_DD_DOM_UT.txt)
=> DellEMC: Fix Z9332f QSFP-DD DOM issue

files/image_config/sudoers/sudoers
Fix vtysh shell-ingestion security issue
Only expose the limited parameters of the command vtysh show.
=> Fix vtysh shell-ingestion security issue

.github/pull_request_template.md
Add checkbox for backport request to 202106 branch to PR template
=> [PR template] Add checkbox for backport request to 202106 branch

Makefile.work, src/sonic-build-hooks/hooks/git
Enable reproducible build for git component in 202012 branch.
Cherry-pick source code from master branch. Former PR is Version control git(#6562)
=> Enable reproducible build for git in 202012 branch. (redo 6562)

src/sonic-build-hooks/hooks/git
=> Bug fix for reproducible build

README.md
Update README.md build badge for azure pipeline.
=> Update README.md build badge for azure pipeline

scripts/docker_version_control.sh, scripts/prepare_docker_buildinfo.sh, scripts/versions_manager.py
when build docker image, we need a base image. now base image is specified by tag. we can use sha256 to specify docker image.
=> Reproducible build support docker image

.azure-pipelines/official-build.yml, azure-pipelines.yml
Support azure pipelines for 202106 branch
=> [ci]: Support azure pipelines for 202106 branch

platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/accton_as4630_54pe_util.py
Modify  accton_as4630_54pe_util.py to support Python3 and remove not need code.
Modify  accton_as4630_54pe_util.py to support Python3 and remove not need code.
Test,
./accton_as4630_54pe_util.py install and can setup device well
/accton_as4630_54pe_util.py install and can remove device well
=> [AS4630-54PE] Modify util.py to python3 and remove code

platform/broadcom/sonic-platform-modules-accton/as7726-32x/utils/accton_as7726_32x_util.py
Modify util.py to support python3. Remove not needed code.
Modify util.py to support python3. Remove not needed code.
Test accton_as7726_32x_util.py install and accton_as7726_32x_util.py remove can work well.
=> [AS7726-32X] Modify util.py to support python3

src/sonic-yang-mgmt/tests/libyang-python-tests/test_SonicYang.json
format test sonic yang json file
use json_pp
=> [sonic-yang]: format test sonic yang json file

build_debian.sh, files/build_templates/sonic_debian_extension.j2, rules/config, slave.mk, src/sonic-ctrmgrd/ctrmgr/ctrmgr_iptables.py, src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py, src/sonic-ctrmgrd/ctrmgr/ctrmgrd.service, src/sonic-ctrmgrd/ctrmgr/remote_ctr.config.json, src/sonic-ctrmgrd/tests/ctrmgr_iptables_test.py, src/sonic-ctrmgrd/tests/ctrmgrd_test.py, src/sonic-ctrmgrd/tests/http_proxy.conf, src/sonic-ctrmgrd/tests/no_proxy.conf
Cherry-pick PR #8158 & PR #8205, since they are needed on 202012 together.
=> cherry-pick PR #8158 & PR #8205 into 202012

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
Add arm related build job in auto version upgrade pipeline.
=> Add arm related build job in auto version upgrade pipeline

platform/broadcom/sonic-platform-modules-accton/as7816-64x/utils/accton_as7816_util.py
1. Modify accton_as7816_util.py to support python3
2.  Remove not needed code.
Modify accton_as7816_util.py
Test "./accton_as7816_util.py install" and "./accton_as7816_util.py clean". Results are fine
=> [AS7816-64x] Modify util to support python3

platform/broadcom/sonic-platform-modules-accton/as9716-32d/utils/accton_as9716_32d_util.py
1. Modify accton_as9716_32d_util.py to support python3.
2. Remove not needed code.
1. Modify accton_as9716_32d_util.py to support python3.
2. Remove not needed code.
Do ./accton_as9716_32d_util.py install and ./accton_as9716_32d_util.py device.
It can install drv and device well. It also can clean drv/device well.
=> [AS9716-32D] Modify util to support python3 and remove extra code

device/arista/x86_64-arista_7170_32c/Arista-7170-32C-C32/board_lane_map.json, device/arista/x86_64-arista_7170_32c/default_sku, device/arista/x86_64-arista_7170_32c/sensors.conf, device/arista/x86_64-arista_7170_32cd/sensors.conf
- Improve chassis linecard restartability
- Fix 'show system-health' cli by adding non standard api
- Fix ledd crash on linecards with Recycle/Inband ports
- Refactor DPM management and add ADM1266 support
- Add state machine to update DPM RTC clock periodically
- Improve xcvr temperature reporting
- Fix lane mapping and `default_sku` for `x86_64-arista_7170_32c` platform
- Fix `7170-32C/CD` platform definition
=> [Arista] Update platform library submodules

device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t0.j2, device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t1.j2, device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/buffers_defaults_t0.j2, device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/buffers_defaults_t1.j2, device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/buffers_defaults_t0.j2, device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/buffers_defaults_t1.j2, device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_def.j2, device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t0.j2, device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t1.j2
Reverts Azure/sonic-buildimage#8298
Sonic-cfggen testcase failures seen
=> Revert "Update default cable len to 0m for TD2"

.azure-pipelines/azure-pipelines-build.yml
Building image for arm platform needs more time.
lengthen time limit from 1.5 days to 2 days
=> [CI] Lengthen time limit for arm platform

.azure-pipelines/docker-sonic-slave.yml, .azure-pipelines/official-build.yml
Enable reproducible build, to avoid build break for version issues.
=> Enable reproducible build for git/docker

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh
To handle newer SSD firmware version in DellEMC S6100 platform (S210506G - 3IE devices).
Update `s6100_ssd_upgrade_status.sh` to handle newer SSD firmware version.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/6847794/UT_logs.txt)
[201911] DellEMC S6100: Update SSD upgrade status checker
=> [201911] DellEMC S6100: Update SSD upgrade status checker

scripts/docker_version_control.sh
1. Add version control for debian* docker image to white list.
2. Always record docker image sha256 value, regardless of white list.
=> Reproducible build add docker image debian* to white list.

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
[BFN]: Updated SAI/SDK packages to 20210805 
Created new packages for 202012 image
Run regression for profiles
=> [BFN]: Updated SAI/SDK packages to 20210805 

platform/barefoot/bfn-platform.mk, platform/barefoot/bfn-sai.mk
Updated SAI/SDK package to 20210811. Includes fix for pfc_wd. 
Created new package 
Run regression, all TC passed
=> [BFN]: Updated SAI/SDK packages to 20210811

platform/broadcom/sonic-platform-modules-accton/as5835-54x/utils/accton_as5835_54x_util.py
Modify accton_as5835_54x_util.py to support python3 and remove not needed code.
Modify accton_as5835_54x_util.py
Test "./accton_as5835_54x_util.py install"  and "./accton_as5835_54x_util.py clean" work well.
=> [AS5835-54X] Modify util to support python3

files/image_config/monit/conf.d/sonic-host
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>
To run VNET route consistency check periodically.
For any failure, the monit will raise alert based on return code.
The tool will log required details.
Depends on https://github.com/Azure/sonic-utilities/pull/1300
Added configuration entry to "SONiC monit"
Configure VNET routes then remove some in ASIC_DB or APP_DB and verify logs for error messages.
[monit] Periodically monitor VNET route consistency
=> [monit] Periodically monitor VNET route consistency

azure-pipelines.yml
fix artifact download syntax error for vstest
=> [ci]: fix artifact download syntax error for vstest

platform/broadcom/sonic-platform-modules-accton/as7326-56x/modules/accton_as7326_56x_leds.c
CPLD offset in led drv is incorrect. 
Fix cpld  offset and add need feature code.
echo 1  > brightness, show green on in DIAG led
echo 3  > brightness, show red on in DIAG led
echo 4  > brightness, show blue on in DIAG led
echo 5  > brightness, show green blinking in DIAG led
Please merge to 202006, 202012 and 202106 due to there is bug in led drv
-->Fix led drv bug
-->Fix led drv bug
-->Fix led drv bug
=> [AS7326-56X] Fix led drv bug

dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
Pcied running by python 2. 
dropped python2 support and add python3 support for pcied  in  file docker-pmon.supervisord.conf.j2
docker exec pmon supervisorctl status
=> [Pcied]  run by python 3

.azure-pipelines/docker-sonic-slave.yml
change for docker-slave didn't tested.
=> Fix azp pipeline file which is involved by former PR

dockers/docker-sonic-mgmt/Dockerfile.j2
In order to check the RPC connection from mgmt agent, there needs a thrift python package.
Install the thrift 0.11 in docker-mgmt
local build docker-sonic-mgmt
=> Add thrift in the docker-sonic-mgmt

device/virtual/x86_64-kvm_x86_64-r0/brcm_gearbox_vs/gearbox_config.json
These two attributes are must-have of attribute sanity check in swss GearboxParser.
Add "context_id" and "hwinfo" fields for PHY object
=> [gearbox] Update gearbox_config.json for platform vs

platform/marvell-armhf/sai.mk
Signed-off-by: Rajkumar Pennadam Ramamoorthy rpennadamram@marvell.com
Fixed Marvell SAI issues. 
Load the deb installed with SONiC image and validate changes.
Fixed Squashfs errors. "resolves #8479"
=> [Marvell] Updated SAI version(1.7.1-2) of armhf platform.

platform/innovium/sonic-platform-modules-wistron/sw-to3200k/utils/sonic-fanthrml-monitor
Why I did it
Thermal mapping is wrong with BMC return value
How I did it
Correct the thermal mapping
Sonic PTF
Which release branch to backport (provide reason below if selected)
201911
=> [201911] [Innovium] Update sonic-fanthrml-monitor

src/sonic-host-services/pytest.ini, src/sonic-host-services/setup.py, src/sonic-host-services/tests/caclmgrd/caclmgrd_dhcp_test.py, src/sonic-host-services/tests/caclmgrd/test_dhcp_vectors.py, src/sonic-host-services/tests/common/mock_configdb.py, src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- add test code to check dhcp acl update
- port to 202012 branch from https://github.com/Azure/sonic-buildimage/pull/8359
=> caclmgrd: add test code to check dhcp acl update

dockers/docker-sonic-mgmt/Dockerfile.j2
=> Snappi version updated to 0.5.11

src/dhcpmon/src/dhcp_device.c, src/dhcpmon/src/dhcp_device.h, src/dhcpmon/src/dhcp_devman.c, src/dhcpmon/src/dhcp_devman.h, src/dhcpmon/src/dhcp_mon.c, src/dhcpmon/src/dhcp_mon.h, src/dhcpmon/src/main.c
NOTE: This is cherry-pick from master to 202012.
https://github.com/Azure/sonic-buildimage/pull/8060
Enhance DHCP monitor application following the implementation PR: https://github.com/Azure/sonic-buildimage/pull/7772
Add the support for monitoring DHCPv6 packets.
Install an image with this PR and the implementation PR.
(cherry picked from commit bef5477d0f8533e347187ba9675c9c289690a8f7)
=> [dhcp_relay] Enhance DHCP monitor application to support DHCPv6

dockers/docker-router-advertiser/radvd.conf.j2
Shorten router advertisement frequency from 10 minutes to 3 minutes
Change radv template
=> Change radv interval to 3min

platform/marvell-armhf/sai.mk
Fixed issues reported in testing.
Load SAI deb in syncd docker and check the fix
Fixed security concerns & ping issue.
=> [202012][Marvell] Update armhf SAI to ver 1.7.1-4
