sonic-net/sonic-buildimage

- platform/broadcom/sonic-platform-modules-ruijie/b6510-48vs8cq/sonic_platform/__init__.py
- platform/broadcom/sonic-platform-modules-ruijie/common/Makefile
- platform/broadcom/sonic-platform-modules-ruijie/common/depmod_conf/distsearch.conf
Signed-off-by: pettershao-ragilenetworks <pettershao@ragilenetworks.com>
fix below issue:
```
root@sonic:/home/admin# show version
SONiC Software Version: SONiC.master.13806-15be1539
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
Build commit: 15be1539
Build date: Wed May  5 23:33:22 UTC 2021
Built by: AzDevOps@sonic-build-workers-0008G2
Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
ASIC Count: 1
File "/usr/local/bin/decode-syseeprom", line 32, in instantiate_eeprom_object
eeprom = sonic_platform.platform.Platform().get_chassis().get_eeprom()
AttributeError: module 'sonic_platform' has no attribute 'platform'
During handling of the above exception, another exception occurred:
File …
```
> [ruijie] Fix show version error info

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/td3-a7050cx3-32s-32x100G.config.bcm
- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/td3-a7050cx3-32s-48x50G+8x100G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-C32/th-a7060-cx32s-32x100G-t1.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-D48C8/th-a7060-cx32s-8x100G+48x50G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q24C8/th-a7060-cx32s-8x100G+24x40G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t0.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t1.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-T96C8/th-a7060-cx32s-8x100G+96x25G.config.bcm
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t1.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm
- src/sonic-device-data/tests/permitted_list
To enable autonegotiation/link training on some Broadcom-based platforms (Arista 7060CX, 7260CX3, 7050cx3, Celestica DX010)
- Add 'phy_an_lt_msft' to BCM config file permitted list
- Add appropriate SOC property for enabling the feature to the Broadcom config files of appropriate platforms
- Also convert line endings to UNIX format for one Celestica file
> [202012] Add SOC property to enable AN/LT on some platforms

- dockers/docker-platform-monitor/Dockerfile.j2
fuser support is required since new cisco hardware watchdog plugin uses them to check anyone else use's /dev/watchdogX resource. The actual validation happens in the platform code, but the package is required for pmon container. Currently the /dev/watchdogX  is being used by cisco platform-monitor service. Cisco chassis level watchdog plugin uses "fuser" to claim the watchdog release from platform-monitor service.
Extend  dockers/docker-platform-monitor/Dockerfile.j2 to bring in psmisc package
cmd = "fuser {}".format(device)
while True:
return_code = runcommand(cmd)
if return_code == 1:
break#### Which release branch to backport (provide reason below if selected)
> add psmisc to bring fuser that identifies processes that are using files or sockets

- build_debian.sh
Need to cleanup the build commands after build finished.
We had a timeout issue where preload firmware:
sonic:~$ sudo /tmp/anpscripts/preload_firmware sonic-aboot-broadcom-20201231.beta.15.swi http://10.20.17.0/firmware/ACS/sonic-aboot-broadcom-20201231.beta.15.swi af124e131bd18e4d66af90935b0d5bac
The timeout is caused by following command started by build command
/usr/bin/curl -Lks http://10.20.17.0/firmware/ACS/sonic-aboot-broadcom-20201231.beta.15.swi | md5sum | cut -d' ' -f1
Why timeout?
It is caused by using the wrong interface, need add "--interface eth0" in curl, it takes more than 1 hours to complete the command if not using the right interface.
```
sonic:~$ curl -f 'http://10.20.17.0/firmware/ACS/sonic-aboot-broadcom-20201231.beta.15.swi' -o …
```
> [bug] Fix build wrapper commands not cleanup issue

- platform/broadcom/docker-syncd-brcm/start_led.sh
`LED_PROC_INIT_SOC` variable was incorrectly referenced as `LED_SOC_INIT_SOC`. Introduced in https://github.com/Azure/sonic-buildimage/pull/5483
Rather than fixing the typo, I decided to simplify the script, removing the need for the conditional altogether by moving the bcmcmd call inside the conditional which checks for the presence of `LED_SOC_INIT_SOC`.
> [docker-syncd-brcm] Fix and simplify start_led.sh

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json
- src/sonic-yang-models/yang-models/sonic-portchannel.yang
This PR depends on https://github.com/Azure/sonic-swss/pull/1660
To update the yang model to support the new key interduced in https://github.com/Azure/sonic-swss/pull/1660
Add to the portchanels yang file an definition for the lacp_key
Run the command `config interface breakout <interface> <breakout_mode>`
> [DPB][YANG-models] Update portchannel yang model to have lacp_key

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
- Xcvrd crashes with the below message in Z9332f platform.
“May  6 05:12:37.446235 S1G2 ERR pmon#xcvrd[5292]: This functionality is currently not implemented for this platform”
- Changed the return type in SFP API's.
- Check whether xcvrd is running properly. 
[xcvrd_UT.txt](https://github.com/Azure/sonic-buildimage/files/6435262/xcvrd_UT.txt)
> DellEMC: Fix Z9332f xcvrd crash

- files/build/versions/dockers/docker-sonic-vs/versions-py3
202012 branch is using reproducible build. The versions-py3 file must contains correct pip3 package version. Otherwise we will get a build error
```
Step 31/74 : RUN pip3 install          scapy==2.4.4          pyroute2==0.5.14          netifaces==0.10.9
---> Running in d7a2401dd21d
Collecting scapy==2.4.4
Downloading scapy-2.4.4.tar.gz (1.0 MB)
Collecting pyroute2==0.5.14
Downloading pyroute2-0.5.14.tar.gz (873 kB)
ERROR: Cannot install netifaces==0.10.9 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested netifaces==0.10.9
The user requested (constraint) netifaces==0.10.7
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency …
```
> Update the netifaces pip3 package version

- rules/docker-telemetry.mk
Reverts Azure/sonic-buildimage#7062
> Revert "[Telemetry docker] add memory and memory swap limits"

- device/accton/x86_64-accton_as4630_54pe-r0/sensors.conf
- device/accton/x86_64-accton_as4630_54te-r0/sensors.conf
- device/accton/x86_64-accton_as5712_54x-r0/sensors.conf
- device/accton/x86_64-accton_as5812_54t-r0/sensors.conf
- device/accton/x86_64-accton_as5812_54x-r0/sensors.conf
- device/accton/x86_64-accton_as5835_54t-r0/sensors.conf
- device/accton/x86_64-accton_as5835_54x-r0/sensors.conf
- device/accton/x86_64-accton_as7315_27xb-r0/sensors.conf
- device/accton/x86_64-accton_as7326_56x-r0/sensors.conf
- device/accton/x86_64-accton_as7716_32x-r0/sensors.conf
- device/accton/x86_64-accton_as7726_32x-r0/sensors.conf
- device/accton/x86_64-accton_as7816_64x-r0/sensors.conf
- device/accton/x86_64-accton_as9716_32d-r0/sensors.conf
Improve readability of `show environment` output.
In all sensors.conf, give the customized labels according to HW specifications for each model.
Installed the built sonic bin and check the prompt of `$ show environment` or  `$ sensors`, see if every label works nicely.
e.g., on model accton/as5812-54t
```
admin@sonic:~$ sensors
lm75-i2c-16-49
Adapter: i2c-1-mux (chan_id 6)
Main Board Temperature:  +31.0 C  (high = +80.0 C, hyst = +75.0 C)
lm75-i2c-17-4a
Adapter: i2c-1-mux (chan_id 7)
Main Board Temperature:  +31.5 C  (high = +80.0 C, hyst = +75.0 C)
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +30.0 C  (high = +98.0 C, crit = +98.0 C)
Core 1:       +30.0 C  (high = +98.0 C, crit = +98.0 C)
Core 2:       +32.0 C  (high = +98.0 C, crit = +98.0 C)
Core 3:       +31.0 C  (high = +98.0 …
```
> [accton] Add sensors.conf to multiple models

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/buffers_defaults_t1.j2
To unblock T1 testing for 7050CX3 HW SKU
Using T0 MMU settings for T1 for now.
Verified to be working fine for basic test cases. Note - These settings are not optimized for T1 rather placeholder till final settings are in place.
Updated MMU settings for Arista-7050CX3-32S-C32 T1 topology
> Updated MMU settings for Arista-7050CX3-32S-C32 T1 topology

- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/sai.profile
Extended Vxlan src port range for lab breakout SKU - Mellanox-SN3800-D112C8
This is in addition to PR - https://github.com/Azure/sonic-buildimage/pull/7394
Added the option and tested on lab device
> [Mellanox] Vxlan src port range for breakout SKU

- src/sonic-build-hooks/scripts/buildinfo_base.sh
Skip to use the web proxy when the packages have been in the proxy server.
For sai packages or the other packages, we will upload the the proxy server directly, the reproducible will skip to check the site, not necessary to change the version files.
> Skip the web proxy when downloading packages from proxy endpoint

- dockers/docker-lldp/lldpmgrd
This PR allows listen to hostname changes and mgmt ip changes.
These are db error related fixes in lldpmgrd. These fixes handle frequent DB access in lldpmgrd due to which sometimes, client used to terminate (python crash in lldpmgrd).
If the management information changes, check and update the new management address in the lldp frames.
Also when there are multiple DB access due to port up/down events etc, sometimes, DB access error can happen in PORT DB, CONFIG DB etc. In such a case, sometimes, python(lldpmgrd) can crash.
To avoid this,
1. Move to unix domain socket for redis connections.
2. During the init time, connect to the tables and use that handle to connect to DB later.
For e.g., do not connect to the PORT DB everytime port comes up or goes …
> lldpd: listen to mgmt-address and port init changes

- src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
- src/sonic-bgpcfgd/tests/test_static_rt.py
Enable redistribution of static routes
Enable redistribution of static routes when the first route is added to STATIC_ROUTE table of Config_DB and disable the redistribution when the last route is removed from STATIC_ROUTE table.
Check the redistribution is enabled after adding a static route in STATIC_ROUTE table of Config_DB and the route is advertised to other peers
```
admin@vlab-01:~$ sudo sonic-cfggen -a '{"STATIC_ROUTE":{"default|10.2.0.0/24": {"nexthop": "10.0.0.57"}}}' --write-to-db
vlab-01# show running-config
...
router bgp 65100
...
address-family ipv4 unicast
network 10.1.0.32/32
network 192.168.0.0/21
redistribute static
...
address-family ipv6 unicast
network fc00:1::/64
network fc02:1000::/64
redistribute static
...
ARISTA03T1>show ip route 10.2.0.0/24
VRF: default
Codes: …
```
> [bgpcfgd] Redistribute static routes

- files/build_templates/macsec.service.j2
MACsec service cannot be enabled by "sudo config feature state macsec enabled"
Bind MACsec service to sonic.target
Refer to this PR: https://github.com/Azure/sonic-buildimage/pull/5705
```
sudo config feature state macsec enabled
```
We should see the macsec container was enabiled
```
admin@sonic:~$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
83e7bea5e130        docker-macsec:latest                 "/usr/local/bin/supe…"   33 seconds ago      Up 31 seconds                           macsec
```
> [service]: Bind macsec service to sonic.target

- platform/broadcom/sonic-platform-modules-accton/minipack/lib/fbfpgaiomodule.c
Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>
> [Minipack] Modify fbfpgaiomodule.c to support both python2 and python3

- files/image_config/pcie-check/pcie-check.service
start pcie-check.service after config-setup.service since pcie_util depends on device_info which is available with config db metadata.
Add config-setup.service as a dependency of pcie-check.service
Upon reboot, check if the pcie-check.sh throws the platform api error which is dependent on DEVICE_METADATA
> add config-setup.service as dependency for pcie-check.service

- dockers/docker-fpm-frr/base_image_files/rvtysh
- dockers/docker-fpm-quagga/base_image_files/rvtysh
- files/image_config/sudoers/sudoers
- rules/docker-fpm-frr.mk
- rules/docker-fpm-quagga.mk
Why I did it
Support readonly version of the command vtysh
How I did it
Check if the command starting with "show", and verify only contains single command in script.
> Support readonly vtysh for sudoers (#7383)

- src/sonic-bgpcfgd/bgpcfgd/main.py
Fixes #7531
To enable bgp sessions to be established over subinterfaces
Listen to VLAN_SUB_INTERFACE table in config db
Bgp sessions were established successfully
```
admin@str-s6000-on-5:~$ show ip bgp summary
IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 12806
RIB entries 12807, using 2458944 bytes of memory
Peers 4, using 87264 KiB of memory
Peer groups 4, using 256 bytes of memory
Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.57      4  64600       6454      12859         0      0       0 …
```
> [bgpcfgd] Enable BGP sessions over subinterfaces

- files/build_templates/qos_config.j2
Map priority 0 to TC 1 and priority 1 to TC 0
Modified mappings in DOT1P_TO_TC_MAP in qos_config.j2 template
Send traffic on priority 0 and 1 and verified that it gets mapped correctly in hw
> [qos] Modify dot1p to tc mapping

- dockers/docker-database/flush_unused_database
To avoid the following logs 
```
Mar 15 15:52:04.599302 igk-dut-04 INFO database#/supervisord: flushdb /bin/bash: /usr/local/bin/flush_unused_database: /usr/bin/python: bad interpreter: No such file or directory
Mar 15 15:52:04.599947 igk-dut-04 INFO database#supervisord 2021-03-15 15:52:04,599 INFO exited: flushdb (exit status 126; not expected)
```
Fix  shebang
Check the logs
> [docker-database] Fix python version in shebang

- files/image_config/ntp/ntp.conf.j2
- src/sonic-config-engine/tests/data/ntp/ntp_interfaces.json
- src/sonic-config-engine/tests/ntp.conf.j2
- src/sonic-config-engine/tests/sample_output/py2/ntp.conf
- src/sonic-config-engine/tests/sample_output/py3/ntp.conf
- src/sonic-config-engine/tests/test_j2files.py
Currently, there is a bug in the ntp.conf jinja2 template where it will ignore the `src_intf` directive in CONFIG_DB if there are multiple IP addresses associated with an interface. This code change fixes that bug and allows the template to select the correct source interface for NTP. 
I did this by modifying the macro in `ntp.conf.j2` which determines if there is an ip address associated with an interface to set a state variable when it detects a valid interface entry in CONFIG_DB instead of outputting "true" directly (which could result in multiple "trues" outputted for interfaces with multiple valid IP addresses). 
1. Add two ipv4 addresses to an interface in SONiC
2. Add the following configuration to `config_db.json` 
```
{
"NTP": {
"global": {
"src_intf": "Ethernet1"
}
}
}
``` …
> [ntp] Fix ntp.conf template to allow setting of source port in CONFIG_DB

- .azure-pipelines/official-build.yml
Signed-off-by: Shilong Liu <shilongliu@microsoft.com>
enable official build of sonic image in azure pipeline on 201911 branch.
change azure pipeline file
check it in azure pipeline
> [CI] enable official build in release branch

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
xcvrd crashes when the application advertisement capability flag is not seen for few transceivers.
Initialize the additional application capability in dunder init 
Check sfpshow eeprom, xcvrd status after the fix and verify the behavior.
UT:
[sfp_UT.txt](https://github.com/Azure/sonic-buildimage/files/6525869/sfp_UT.txt)
> DellEMC: Z9332f fix SFP issues

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
This pull request allows calls to be made through the platform 2.0 API that retrieve the PSU and Chassis hardware revision on Mellanox platforms. Access to these values will aid customers in determining their hardware revisions for debugging and technical support. These values are intended to be eventually exposed through the CLI. 
For the PSU hardware revision I used the existing VPD function calls implemented in https://github.com/Azure/sonic-buildimage/pull/7382
For the Chassis hardware revision I parsed the SMBIOS / DMI type 2 information to retrieve the information. 
To verify on a switch open a python 3 interpreter with root access and run the following script....
```
import sonic_platform
platform_chassis = sonic_platform.platform.Platform().get_chassis()
chassis_rev = …
```
> [Mellanox] Implement Hardware Revision Platform API Call for Mellanox Chassis and PSU

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_infos.py
- platform/mellanox/mlnx-platform-api/tests/mock_platform.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal_policy.py
According to thermalctld hld, each fan must belong to a fan drawer, if the fan drawer does not physically exist, put fan into a virtual fan drawer. This PR is to clear fan from chassis._fan_list
1. Don't put fan to chassis._fan_list
2. Always query fan from fan_drawer
Adjust unit test to verify the change
> [Mellanox] clear fan from chassis._fan_list

- files/image_config/kdump/vmcore-sysctl.conf
If a process limits using nodes by mempolicy/cpusets, and those nodes become memory exhaustion status, one process may be killed by oom-killer.
No panic occurs in this case, because other node's memory may be free.
This means system total status may be not fatal yet.
Remove 'vm.panic_on_oom=1' kernel flag from 'vmcore-sysctl.conf '
> [kdump] Remove vm.panic_on_oom=1 to change it back to 2

- dockers/docker-router-advertiser/docker-router-advertiser.supervisord.conf.j2
docker radv can't startup if DEVICE_METADATA.localhost.type not exist
add check for DEVICE_METADATA.localhost.type exist
build the sonic image, run on board, and radv can startup
> [radv] fix bug for radv can't startup if DEVICE_METADATA.localhost.type not exist

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
When FECDisabled is set to true in minigraph.py, push 'fec' 'none' explicitly to config_db. When 'fec' is defined in port_config.ini do not override it with 'rs' for 100G
Modified minigraph Parser
Load minigraph with FECDisabled and after config load_minigraph check the config_db whether 'fec' 'none' is populated. Modified port_config.ini to check if a value in port_config.ini does not get overridden by 'fec' 'rs'
> FEC none config through minigraph

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
Porting https://github.com/Azure/sonic-buildimage/pull/7667 to 202012 since there were conflicts
When FECDisabled is set to true in minigraph.py, push 'fec' 'none' explicitly to config_db. When 'fec' is defined in port_config.ini do not override it with 'rs' for 100G
Modified minigraph Parser
Load minigraph with FECDisabled and after config load_minigraph check the config_db whether 'fec' 'none' is populated. Modified port_config.ini to check if a value in port_config.ini does not get overridden by 'fec' 'rs'
> [202012] FEC none config through minigraph

- dockers/docker-sonic-restapi/supervisord.conf
docker ```restapi``` is ```docker-config-engine-stretch``` and ```python3``` is not available. Hence ```supervisor-proc-exit-listener``` is not able to startup. This PR is to address the issue.
```
root@str-msn4600c-acs-02:/# supervisorctl status
dependent-startup                EXITED    May 24 03:06 AM
restapi                          RUNNING   pid 290, uptime 0:00:15
rsyslogd                         RUNNING   pid 73, uptime 0:09:58
start                            EXITED    May 24 03:06 AM
supervisor-proc-exit-listener    FATAL     Exited too quickly (process log may have details)
```
Specific ```python2``` environment.
Verified by checking the status of ```supervisor-proc-exit-listener```
```
root@str-msn4600c-acs-02:/# supervisorctl …
```
> Fix supervisor-proc-exit-listener startup issue in restapi

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
To fix the following:
```
File "/usr/local/bin/psuutil", line 8, in <module>
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File …
```
> [platform][barefoot] Add Psu.get_name

- platform/broadcom/sai.mk
To pick up following Broadcom SAI patches:
- CS00012108770, CS00012115932: Sesto phy WB support + WB recovery + log messages
upgrade broadcom SAI to version 3.5.3.7-4
> [201811] upgrade broadcom SAI to version 3.5.3.7-4

- src/sonic-bgpcfgd/bgpcfgd/main.py
Signed-off-by: Neetha John nejo@microsoft.com
Why I did it
This is to backport changes in #7654 to 202012.
How I did it
Listen to VLAN_SUB_INTERFACE table in config db
Bgp sessions were established successfully over subinterface
> [202012] [bgpcfgd] Enable BGP sessions over subinterfaces

- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers.json.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
Arista-7260CX3-Q64 is missing T1 MMU configuration.
Define T1 MMU configuration for Arista-7260CX3-Q64.
> [MMU] define T1 MMU configuratino for Arista-7260CX3-Q64

- dockers/docker-teamd/supervisord.conf
Adding a missing part of https://github.com/Azure/sonic-buildimage/pull/6537
Resolves  #7591 
* To fix LAG IP configuration race
* Extended timeout for teammgrd
1. Add >80 router LAGs
2. Do config reload
* N/A
```
'//||\\`
''``
```
> [201911][docker-teamd]: Increase teammgrd timeout to allow graceful shutdown

- dockers/docker-sonic-telemetry/base_image_files/monit_telemetry
- files/build_templates/sonic_debian_extension.j2
- files/image_config/monit/memory_checker
- files/image_config/monit/restart_service
This PR aims to monitor the memory usage of streaming telemetry container and restart streaming telemetry container if memory usage is larger than the pre-defined threshold.
I borrowed the system tool Monit to run a script `memory_checker` which will periodically check the memory usage of streaming telemetry container. If the memory usage of telemetry container is larger than the pre-defined threshold for 10 times during 20 cycles, then an alerting message will be written into syslog and at the same time Monit will run the script `restart_service` to restart the streaming telemetry container.
I verified this implementation on device `str-7260cx3-acs-1`.
May 14 21:40:44.944347 str-7260cx3-acs-1 INFO systemd[1]: Starting LSB: service and …
> [Monit] Restart telemetry container if memory usage is beyond the threshold

- dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
I added `chassis_db_init` to the startup tasks for the `docker-platform-monitor` docker so that the script is run on startup of the switch and the chassis info is correctly provisioned to STATE_DB.
**NOTE: THIS DEPENDS ON https://github.com/Azure/sonic-platform-daemons/pull/183 DO NOT MERGE**
I modified the supervisord template in order to define the new task to be started. 
Run `sudo redis-cli -n 6 hgetall "CHASSIS_INFO|chassis 1"`
Expected output (exact values will differ per platform)
```
1) "serial"
2) "MT1822K07815"
3) "model"
4) "MSN2700-CS2FO"
5) "revision"
6) "A1"
7) "psu_num"
8) "2"
```
[dockers][platform-monitor] Add chassis_db_init to platform monitor tasks
> [dockers][platform-monitor] Add chassis_db_init to platform monitor tasks

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample_output/ports.json
- src/sonic-config-engine/tests/simple-sample-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
Backport #7744 
Ran sonic-cfggen on a minigraph and verified that interface of type DeviceMgmtLink has speed set in the PORT table from the bandwidth attribute in the minigraph
> [201811] Parse bandwidth for DeviceMgmtLinks

- src/systemd-sonic-generator/.gitignore
- src/systemd-sonic-generator/Makefile
- src/systemd-sonic-generator/debian/rules
- src/systemd-sonic-generator/ssg-test.cc
- src/systemd-sonic-generator/systemd-sonic-generator.c
- src/systemd-sonic-generator/systemd-sonic-generator.h
- src/systemd-sonic-generator/tests/testfiles/multi_inst_a.service
- src/systemd-sonic-generator/tests/testfiles/multi_inst_a@.service
- src/systemd-sonic-generator/tests/testfiles/multi_inst_b.service
- src/systemd-sonic-generator/tests/testfiles/multi_inst_b@.service
- src/systemd-sonic-generator/tests/testfiles/single_inst.service
- src/systemd-sonic-generator/tests/testfiles/test.service
- src/systemd-sonic-generator/tests/testfiles/test.timer
Signed-off-by: Anand Mehra <anamehra@cisco.com>
1. systemd-sonic-generator limits multi-asic unit file instances to 10 (single digit instance number 0 - 10). This limitation needs to be removed to handle more than 10 asics.
2. MAX_NUM_TARGETS and MAX_NUM_INSTALL_LINES limits to 15 which is not sufficient for systems with more than 15 asics.
3. Inside get_unit_files(), strcmp produce incorrect results due to non null terminated string being compared.
1. In function insert_instance_number instance_string was malloced for 2 char
size which was limiting the instance number value in instance_name to 1 digit.
Fixed insert_instance_number to use asprintf to generate instancd_name for
any number of instances. Added _GNU_SOURCE to CFLAGS for asprintf.
2. Fixed get_unit_files() to use calloc …
> [multi-asic] Fixed systemd-sonic-generator for multi-asic

- src/sonic-config-engine/tests/test_cfggen.py
Noticed build failure on 201811 branch
Address the sonic-config-engine assertion ordering issue.
Build 201811 branch image.
> [201811] address build error in sonic-config-engine

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample_output/py2/ports.json
- src/sonic-config-engine/tests/sample_output/py3/ports.json
- src/sonic-config-engine/tests/simple-sample-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
The current code skips parsing bandwidth for DeviceMgmtLinks. We have a use case to set the speed for these type of links based on the bandwidth attribute in the minigraph 
Ran sonic-cfggen on a minigraph and verified that interface of type DeviceMgmtLink has speed set in the PORT table from the bandwidth attribute in the minigraph
> [minigraph] Parse bandwidth for DeviceMgmtLinks

- dockers/docker-lldp/lldpmgrd
This PR is to fix #7740 
```lldpmgrd``` crashed during test with following errors
```
syslog.54.gz:May 27 11:49:47.677883 str2-msn4600c-acs-01 INFO lldp#lldpmgrd[36]: Starting up...
syslog.54.gz:May 27 11:49:47.741594 str2-msn4600c-acs-01 INFO lldp#/supervisord: lldpmgrd Traceback (most recent call last):
syslog.54.gz:May 27 11:49:47.741594 str2-msn4600c-acs-01 INFO lldp#/supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 364, in <module>
syslog.54.gz:May 27 11:49:47.741594 str2-msn4600c-acs-01 INFO lldp#/supervisord: lldpmgrd     main()
syslog.54.gz:May 27 11:49:47.741594 str2-msn4600c-acs-01 INFO lldp#/supervisord: lldpmgrd   File "/usr/bin/lldpmgrd", line 347, in main
syslog.54.gz:May 27 11:49:47.741594 str2-msn4600c-acs-01 INFO lldp#/supervisord: lldpmgrd     lldpmgr.run() …
```
> Fix lldpmgrd syntax issue

- dockers/docker-database/flush_unused_database
To avoid the following error
```
File "/usr/local/bin/flush_unused_database", line 10, in <module>
if 'PONG' in output:
TypeError: a bytes-like object is required, not 'str'
```
`communicate` method returns the strings if streams were opened in text mode; otherwise, bytes.
In our case text arg  in Popen is not true and that means that `communicate` return the bytes
Set `text=True` to get strings instead of bytes
run `/usr/local/bin/flush_unused_database` inside database container
> [docker-database] Fix Python3 issue

- src/sonic-py-common/sonic_py_common/device_info.py
- src/sonic-py-common/tests/device_info_test.py
- src/sonic-py-common/tests/mock_swsssdk.py
These methods were added to make some convenient platform and chassis information methods accessible through sonic-py-common. These methods were refactored from sonic-utilities and are used in the `show platform summary` and `show version` commands. 
There are two methods, one is `get_platform_info()` which simply calls local methods to collect useful platform information into a dictionary format, this came directly from sonic-utilities.
The other method is `get_chassis_info()` which retrieves the chassis model, serial number, and hardware revision from the STATE_DB directly. 
Open a python3 interpreter and enter the following lines
```
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
>>> from …
```
> [sonic-py-common] Add platform and chassis info methods to device_info

- device/virtual/x86_64-kvm_x86_64-r0/msft_four_asic_vs/0/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_four_asic_vs/1/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_four_asic_vs/2/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_four_asic_vs/3/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/0/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/1/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/2/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/3/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/4/context_config.json
- device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs/5/context_config.json
For multi-asic platforms, orchagent process in swss docker is started by passing device_ids(or asic_ids). 
Each swss docker starts orchagent with a different device_id. This device_id is passed as Hardware info to syncd. For syncd to start with the right hwinfo, context_config.json is passed as an argument. context_config.json file is looked up to get the hwinfo information. 
sonic-sairedis PRs required for this diff to be used to bring up multi-asic VS:
https://github.com/Azure/sonic-sairedis/pull/830
https://github.com/Azure/sonic-sairedis/pull/832
Add context_config.json for each asic in the same structure as provided here: https://github.com/Azure/sonic-sairedis/blob/master/lib/src/context_config.json
Each asic …
> [multi-asic][vs]: Add context_config.json files for multi-asic vs hwskus

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
Work in progress!
Test PR to trigger azure-pipelines-UpgradeVersion.
__Why I did it__
[Build failed with error "Failed to verify the package"](https://dev.azure.com/mssonic/build/_build/results?buildId=13879&view=logs&j=993d6e22-aeec-5c03-fa19-35ecba587dd9&t=d0538dec-1681-5ff8-bd45-c0de13be9706&l=694)
[The reason of the fail is version verification](https://github.com/Azure/sonic-buildimage/blob/3db6572e6785ffcd4ef0a4575b16f95c7606c327/src/sonic-build-hooks/scripts/buildinfo_base.sh#L79)
[Version manager didn't find dependencies for the barefoot platform](https://github.com/Azure/sonic-buildimage/commit/b0460c7ce182de8abac85294b207eae85fd942b3)
The possible reason is absence of artifacts for the barefoot platform, because the job for barefoot is filtered out.
> [Barefoot][azure-pipelines] fix sonic build 202012 bfnplatform

- dockers/docker-sonic-mgmt/Dockerfile.j2
[sonic-mgmt docker]: Added allure-pytest library to sonic-mgmt docker container
* Modified Dockerfile.j2 - added allure-pytest library
Signed-off-by: Petro Pikh <petrop@nvidia.com>
This library will allow us to have more human readable test reports
Added allure-pytest library to Docker file template
Executed tests, using new docker-sonic-mgmt container which have installed library allure-pytest
Added support for Allure reports 
:)
> [sonic-mgmt docker]: Added allure-pytest library to sonic-mgmt docker container

- slave.mk
Provide possibility to specify curl options as the present curl support provided in Azure/sonic does not extend capability for options like --user which some of the cisco artifacts are requiring. 
Add extensions to the slave.mk file to include curl options as follows: 
$($*_CURL_OPTIONS)
Option 1) use curl -u, and environment variables
it with --user <user:password> curl_options. Ex: --user foo:'bar!'
curl -u ${BASIC_AUTH_HEADER} https://foo.bar
This works to obscure password/credential in a terminal session that someone else might see directly or via screen share. 
Option 2)  Option 1: use curl -n
If you run linux, create a ~/.netrc file and insert your creds there, and use curl -n. 
chmod the file to 400. curl knows how to extract your creds from the file silently. You never have to …
> Provide curl options in curl command

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
Make PSU name returned from platform API aligned with the convention "PSU {X}" instead of "PSU{X}".
Add a extra space in the PSU name
manually call the platform API psu.get_name() to check the name returned from it.
> [Mellanox] Align PSU name convention returned from psu.get_name platform API

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/sfp.py
On our platforms syncd must be up while using the sonic_platform.
The issue is warm-reboot script first disables syncd then instantiate Chassis, which tries to connect syncd in __init__.
Refactor Chassis to lazy initialize components.
> [barefoot][platform] Refactor chassis.py

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
Make PSU name returned from platform API aligned with the convention "PSU {X}" instead of "PSU{X}".
This PR is to backport https://github.com/Azure/sonic-buildimage/pull/7783
Add a extra space in the PSU name
manually call the platform API psu.get_name() to check the name returned from it.
> [201911][Mellanox] Align PSU name convention returned from psu.get_name platform API

- Makefile.work
- sonic-slave-buster/Dockerfile.j2
- sonic-slave-jessie/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
Usecase:
export DOCKER_EXTRA_OPTS="--registry-mirror=https://some.host" - to avoid DockerHub pull rate limiting.
Added DOCKER_EXTRA_OPTS
export DOCKER_EXTRA_OPTS="--registry-mirror=https://some.host"
make target/sonic-mellanox.bin
> [Makefile.work] Add DOCKER_EXTRA_OPTS

- platform/broadcom/sonic-platform-modules-accton/as7726-32x/modules/accton_as7726_32x_cpld.c
Fix modules_reset sysfs due to need to do revert.
Add to do revert when read modules_reset sysfs
#cat module_reset_1
1
#echo 1 > module_reset_1
#cat module_reset_1
1
#echo 0 > module_reset_1
#cat module_reset_1
0
0
1
0
> [as7726-32x] Fix module_reset sysfs

- dockers/docker-orchagent/enable_counters.py
after "config reload" or "docker swss restart" all counterpoll counters were enabled even if they were disabled before
check if entry already exist before set default values
disable few counters
```
counterpoll pg-drop disable
counterpoll port disable
```
Save and reload
```
config save
config reload
```
> [enable_counters] Set default values only on the first start

- device/arista/x86_64-arista_7170_32cd/pcie.yaml
Process pcied failed on Arista-7170-32CD-C32
```
root@sonic:/# supervisorctl 
chassis_db_init                  EXITED    Jun 03 08:48 AM
dependent-startup                EXITED    Jun 03 08:48 AM
ledd                             RUNNING   pid 28, uptime 3:07:49
lm-sensors                       EXITED    Jun 03 08:48 AM
pcied                            FATAL     Exited too quickly (process log may have details)
```
Generated pcie.yaml with `pcieutil generate`
> [Arista] Added pcie.yaml for x86_64-arista_7170_32cd

- dockers/docker-teamd/supervisord.conf
The PR is a cherry-pick of #7662. 
Same issue is detected in ```202012```.
Add a timeout for ```teammgrd```.
Verified by running ```test_po_cleanup``` on ```SN4600```, with 24 portchannels. 
Increase teammgrd timeout to allow graceful shutdown
> [docker-teamd]: Increase teammgrd timeout to allow graceful shutdown

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
To fix determine-reboot-cause service which was failing due to non-implemented thrown from get_reboot_case, if the reboot was done with `sudo reboot` (cold reboot)
Added get_reboot_case implementation that will always return Non-Hardware reason.
barefoot implementation of sonic_platform.chassis.Chassis.get_reboot_cause
> [barefoot][platform] Chassis.get_reboot_cause

- platform/mellanox/docker-syncd-mlnx.mk
To have access to MFT tools in the Syncd container on Mellanox switches due to SAI dump API implementation enhancements
Add MFT to the dependencies of docker-syncd-mlnx
Verify that MFT tools are presents on Syncd in a Mellanox switch
> [Mellanox] Install MFT packages on syncd container

- build_debian.sh
Watchdog does not trigger a kernel panic on Arista 7170 platform because this parameter is missing on 201911 but not on master.
Add the relevant parameter (panic_on_unrecovered_nmi) to build_debian.sh
The relevant kernel code that needs this parameter is here: https://github.com/torvalds/linux/blob/master/arch/x86/kernel/nmi.c#L292
> [201911] Add panic_on_unrecovered_nmi to kernel settings

- platform/mellanox/sdk-src/python-sdk-api/Makefile
Adjust the Makefile for SDK/python-SDK-API to support both python2 and python3
Build the image and check whether python2 and python3 are both supported by SDK API.
> [Mellanox] Adjust Makefile for SDK/python-sdk-api to support both python2 and python3

- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Dynamic Port Breakout falls cause of PG_DROP yang model missing
Add PG_DROP yang model and add check this field in unit test for yang model
Firstly try to do DPB (2x50G) for Ethernet0 port:
`sudo config interface breakout Ethernet0 2x50G -f`
After that try to do DPB (1x100G[40G]) for Ethernet0 port:
`sudo config interface breakout Ethernet0 1x100G[40G] -f`
Both commands should work correctly.
> Add PG_DROP yang model

- files/build_templates/sonic_debian_extension.j2
- files/build_templates/tacacs-config.service
- files/build_templates/tacacs-config.timer
- files/image_config/config-setup/config-setup
Why I did it
In upgrade scenarios, where config_db.json is not carry forwarded to new image, it could be left w/o TACACS credentials.
Added a service to trigger 5 minutes after boot and restore TACACS, if /etc/sonic/old_config/tacacs.json is present.
How I did it
By adding a service, that would fire 5 mins after boot.
This service apply tacacs if available.
Upgrade and watch status of tacacs.timer & tacacs.service
You may create /etc/sonic/old_config/tacacs.json, with updated credentials
(before 5mins after boot) and see that appears in config & persisted too.
Which release branch to backport (provide reason below if selected)
201911
202006
202012
> Add service to restore TACACS from old config (#7560)

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.conf.j2/all.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/all.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/defaults.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.conf
- src/sonic-config-engine/tests/sample_output/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/bgpd_frr_frontend_asic.conf
Port this PR to 201911 https://github.com/Azure/sonic-buildimage/pull/7878
Verify the internal loopback address are present in the all the frontend asics
```
admin@sonic:~$ bcmcmd -n 0 "l3 ip6route show" | grep 2603:10e2:0400:0000:0000:0000:0000
1888  0        2603:10e2:0400:0000:0000:0000:0000:0000/128  00:00:00:00:00:00 100003    0     0     0    1 n
67424 0        2603:10e2:0400:0000:0000:0000:0000:0004/128  00:00:00:00:00:00 100004    0     0     0    0 n
1889  0        2603:10e2:0400:0000:0000:0000:0000:0005/128  00:00:00:00:00:00 100005    0     0     0    0 n
67428 0        2603:10e2:0400:0000:0000:0000:0000:0001/128  00:00:00:00:00:00 200258    0     0     0    0 n      (ECMP)
1895  0 …
```
> [201911][multi-asic] fix network command for internal ipv6 loopback

- rules/sonic-config.dep
The PR checkers do not re-run the sonic-config-engine test cases, caused by some of the config files changes not detected.
https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all/660/console
…
07:13:24  ======================================================================
07:13:24  ERROR: test_bgpd_quagga (tests.test_j2files.TestJ2Files)
07:13:24  ----------------------------------------------------------------------
…
07:13:24  ======================================================================
07:13:24  ERROR: test_zebra_quagga (tests.test_j2files.TestJ2Files)
07:13:24  ----------------------------------------------------------------------
…
07:13:24  error: Test failed: <unittest.runner.TextTestResult run=161 errors=2 failures=0>
07:13:24  [  FAIL LOG …
> [build]: Fix missing the depended files of dpkg cache in config engine

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
For `MgmtTsToR` device, it can manage 48/96 devices via console. Besides, it also have it own console port (console) which will be modeled in minigraph as a device serial link. Current code will generate configuration for it, but there are no change to do the reverse control and the configuration can lead confuse for users.
Only generate console config for console ports which is in digital format.
Add new test data and existing unit test will cover this case.
```
test_minigraph_console_port (tests.test_minigraph_case.TestCfgGenCaseInsensitive) ... ok
```
> [console][minigraph] Avoid generate config for self console port

- .azure-pipelines/docker-sonic-mgmt.yml
UserID is different with the image built by Jenkins if we build docker-sonic-mgmt in sonicbld pool.
So we build this image in sonictest pool. There is a sonictmp user with UserID 1001.
This will make docker image same as the image built in Jenkins
> [CI] Fix azp built docker-sonic-mgmt image

- platform/mellanox/mlnx-platform-api/sonic_platform/component.py
- platform/mellanox/mlnx-platform-api/tests/test_firmware.py
The Mellanox platform is required to support the `fwutil auto-update` feature defined [here ](https://github.com/sujinmkang/SONiC/blob/357485991d768a9fa78873bb083e3979fbc5cf71/doc/fwutil/fwutil.md#2224-update-all-commands)
This is to allow switches, when performing SONiC upgrades to choose whether to perform firmware upgrades that may interrupt the data plane through a cold boot. 
Two methods were added to the component implementations for mellanox. 
In the base `Component` class we add a default function that chooses to skip the installation of any firmware unless the `cold` boot option is provided. This is because the Mellanox platform, by default, does not support installing firmware on ONIE, the CPLD, or the BIOS "on-the-fly". 
In the `ComponentSSD` class we add a function that …
> [Mellanox] Implement auto_firmware_update platform API for to support fwutil auto-update

- files/build_templates/init_cfg.json.j2
- src/libnl3/.gitignore
- src/libnl3/Makefile
- src/libnl3/patch/0001-mpls-encap-accessors.patch
- src/libnl3/patch/0002-mpls-remove-nl_addr_valid.patch
- src/libnl3/patch/series
What I did
SONiC buildimage support for MPLS:
1) New accessors in libnl3 for MPLS attributes
2) bug fixes in libnl3 for MPLS attribute parsing
Why I did it
SONiC libnl3 support for MPLS
How I verified it
Unit-tests in sonic-swss/tests/test_mpls.py and sonic-utilities/tests
System tests in sonic-mgmt
Details if related
Refer to HLD: Azure/SONiC#706
> libnl3 updates for MPLS

- files/image_config/pcie-check/pcie-check.sh
…able name to match with pcied changes
Support multiple pcie configuration file and change the pcie status table name
This is to match with below two PRs.
https://github.com/Azure/sonic-platform-common/pull/195
https://github.com/Azure/sonic-platform-daemons/pull/189
Check pcie configuration file with wild card and change the device status table name
Restart with changes and see if the pcie check works as expected.
> Support multiple pcie configuration file and change the pcie status table name

- src/sonic-host-services/setup.py
Recently, the build started failing with messages like
```
2021-06-16T16:55:02.8675603Z tests/hostcfgd/hostcfgd_test.py:5: in <module>
2021-06-16T16:55:02.8676208Z     from parameterized import parameterized
2021-06-16T16:55:02.8677145Z E   ModuleNotFoundError: No module named 'parameterized'
```
Unit tests for hostcfgd depend on the `parameterized` Python package, but it was never added as a dependency to the setup.py file. This dependency was added ~3 months ago. I'm not sure why we only started seeing this failure recently.
Add 'parameterized' package as a test dependency in setup.py for sonic-host-services package
> [sonic-host-services] Add 'parameterized' package as a test dependency

- platform/broadcom/docker-syncd-brcm/start_led.sh
For BRCM platform where LED INIT is required there was an issue with BRCM SAI 4.3.3 which can cause all the interfaces flap if this is executed.  A fix was provided in BRCM SAI 4.3.3.7 where we now can safely re-enable LED INIT at warm reboot time as well.  This is needed for WARM REBOOT. If not done, a device went through WARM REBOOT will see its LED not functioning any more.
We will map this same change to master branch later when we can validate that the same fix is in BRCM SAI 5.0.
There is a similar SAI change based on SAI 3.7 is not yet validated. Once that is ready a separate PR will be raised to include this change for 201911 branch.
The verification was done using S6100 SKU where we first observed the issue.
Attempt Warm reboot and without the fix you can see the LED are OFF. …
> [202012] [BRCM} start_led.sh re-enable LED INIT for Warm Reboot

- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers.json.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_dynamic.json.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/hwsku.json
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/pg_profile_lookup.ini
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/port_config.ini
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/qos.json.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/sai_4600C.xml
Add new SKU of SN4600C switch: Mellanox-SN4600c-c64
Added all relevant files to support the new SKU requirements:
- Port configuration: No breakout required. All ports configured with 100G
- Buffer configuration
• Shared headroom enable. over-subscription ratio as in SN3800
• Dynamic Buffer disable
- Switch configuration
• Warmboot enabled. Added to SAI profile
• Is VxLAN source port range set as in SN3800
- Number of Uplinks/Downlinks:
• t0: 32 100G down links and 32 100G up links.
• t1: 56 100G down links and 8 100G up links.
Set the SKU in config_db.json to Mellanox-SN4600C-C64 and test the 100G ports coming up on the switch.
Changes are in sonic-buildimage/device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/ folder.
> [Mellanox] Add new SKU Mellanox-SN4600C-C64

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
Updated DellEMC Z9332f reboot reason
Edited chassis.py::get_reboot_cause() to update the reboot reason.
Perform different types of reboot and verify reboot cause.
UT: 
[z9332f reboot reason UT.txt](https://github.com/Azure/sonic-buildimage/files/6655596/z9332f.reboot.reason.UT.txt)
> DellEMC: Update Z9332f reboot reason

- build_debian.sh
To allow SSH connections from IPv6 addresses
Resolves https://github.com/Azure/sonic-buildimage/issues/7668
In build_debian.sh, modify sshd_config file so as to enable listening for IPv6 connections
SSH to SONiC device using an IPv6 address
> [build_debian.sh] Configure sshd to listen for IPv6 connections

- platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
Depends on https://github.com/Azure/sonic-platform-common/pull/193
Remove EEPROM cache file and use DB instead
1. Read EEPROM data from DB if possible
2. If data is not ready in DB, read from hardware using a visitor pattern
Manual test and regression
> [Mellanox] Read EEPROM data from DB if possible

- installer/sharch_body.sh
while sonic upgrade, Image will be extracted to tmpfs for installation so tmpfs size should be larger than image size. Image installation will fail if image size is larger than tmpfs size.
we are facing below error while installing debug image with size greater than tmpfs which is 1.5g in marvell armhf platform.
sonic-installer install <url>
New image will be installed, continue? [y/N]: y
Downloading image...
...99%, 1744 MB, 708 KB/s, 0 seconds left...
Installing image SONiC-OS-202012.0-dirty-20210311.224845 and setting it as default...
Command: bash /tmp/sonic_image
tar: installer/fs.zip: Wrote only 7680 of 10240 bytes
tar: installer/onie-image-arm64.conf: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors
Verifying image checksum ... OK. …
> Support for updating tmpfs size according to Image size

- device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/sai.profile
- device/mellanox/x86_64-mlnx_msn2100-r0/ACS-MSN2100/sai.profile
- device/mellanox/x86_64-mlnx_msn2410-r0/ACS-MSN2410/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-C28D8/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai.profile
- device/mellanox/x86_64-mlnx_msn2740-r0/ACS-MSN2740/sai.profile
- device/mellanox/x86_64-mlnx_msn3420-r0/ACS-MSN3420/sai.profile
- device/mellanox/x86_64-mlnx_msn3700-r0/ACS-MSN3700/sai.profile
- device/mellanox/x86_64-mlnx_msn3700c-r0/ACS-MSN3700C/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/ACS-MSN3800/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D24C52/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C49S1/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/sai.profile
- device/mellanox/x86_64-mlnx_msn4410-r0/ACS-MSN4410/sai.profile
- device/mellanox/x86_64-mlnx_msn4600-r0/ACS-MSN4600/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/ACS-MSN4600C/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D112C8/sai.profile
- device/mellanox/x86_64-mlnx_msn4700-r0/ACS-MSN4700/sai.profile
- device/mellanox/x86_64-mlnx_msn4800-r0/ACS-MSN4800/sai.profile
This PR depends on https://github.com/Azure/sonic-sairedis/pull/833
To create SDK dump on Mellanox devices when SDK event has occurred.
Set the SKUs keys needed to initialize the feature in SAI.
Simulate SDK event and check that dump is created in the expected path.
> [Mellanox] Update SKUs to enable SDK dumps

- files/build_templates/docker_image_ctl.j2
Following the discussion in another PR https://github.com/Azure/sonic-buildimage/pull/7708#discussion_r642933510 , since there will be multi subfolders under **/var/log/mellanox**, so we agreed to only mount this folder and the subfolders will be created afterward on demand.  
during the syncd docker creation, only mount  folder **/var/log/mellanox**
build an Mellanox image and verify the related folder on the host and docker side.
> [Mellanox] Only mount '/var/log/mellanox' folder to syncd docker instead of mounting every sub folder

- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/fabriclanemap.ini
- src/sonic-device-data/src/sai.vs_profile
This PR is actually https://github.com/Azure/sonic-buildimage/pull/6185 that was merged and then reverted to avoid test failure in swss. 
Now https://github.com/Azure/sonic-swss/pull/1459/ merged, and so this PR could merge to enable fabric test in swss.
Signed-off-by: ngocdo <ngocdo@arista.com>
> Add fabric lane mapping to vs (sai.profile) and HWSKU Force10-S6000

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
The methods `get_model`, `get_serial`, and `get_revision` have been implemented by reading relevant information from VPD and then recording the information into relevant fields.
However, there is no VPD data on platforms with fixed PSUs and relevant fields haven't been initialized, which causes the methods to throw exceptions. which in turn prevents `psud` from inserting fields into PSU table.
Eventually, this causes `show platform psustatus` doesn't output correct info.
```
admin@sonic:~$ show platform psustatus 
PSU    Model    Serial    HW Rev    Voltage (V)    Current (A)    Power (W)    Status    LED
-----  -------  --------  --------  -------------  -------------  -----------  --------  -----
PSU 1 …
```
> [Mellanox] Return N/A for PSU's model, serial and revision on platforms with fixed PSU

- rules/functions
During SONiC build with  `INSTALL_DEBUG_TOOLS=y` an exception is raised:
```
[ 01 ] [ target/docker-sonic-mgmt-framework-dbg.gz ]
File "/usr/local/bin/j2", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 206, in main
sys.argv[1:]
File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 186, in render_command
result = renderer.render(args.template, context)
File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 87, in render
.render(context) \
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception …
```
> Fix build with INSTALL_DEBUG_TOOLS=y

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.conf.j2/all.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/all.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/defaults.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.conf
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_frontend_asic.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_frontend_asic.conf
In the multi asic platforms all the ASIC are advertising the same IPv6 /64 network from Loopback4096.
Therefore, the IPv6 loopback address of backend asic is not learnt on the frontend asic.
Change this to advertise the Loopback4096 address as /128 
Change the `bgpd.conf.main.conf.j2 `template file.
Verify the route to Loopback4096 address of backend asic is programmed on the Frontend linecard
- Loopback4096 ipv6 address on backend asics
```
admin@sonic:~$ show ipv6 int -d all -n asic4 | grep -i loopback4096
Loopback4096               2603:10e2:400::4/128                       up/up         N/A             N/A
fe80::fc68:56ff:fe3a:7f37%Loopback4096/64                N/A             N/A
admin@sonic:~$ show ipv6 int …
```
> [multi-asic] fix network command for internal ipv6 loopback

- .azure-pipelines/official-build.yml
Add rpc image target for 201911 branch.
201911 branch overwrited official-build.yml. Only changing template file does not work.
> [CI] Fix azp build rpc image targets.

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-graph-resource-type.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
The current logic generates 'VLAN_SUB_INTERFACE' table if the device type is backend and cluster name contains 'str'. This is not a reliable method to determine a storage backend device
Updated the logic to generate 'VLAN_SUB_INTERFACE' table if any of the following conditions hold true
1. device is of type backend and ResourceType attribute is None
2. device is of type backend and ResourceType attribute contains "Storage"
3. device is of type backend and graph contains "Subinterface" section
Also updated the logic to set "is_storage_device" to True 
1. for Backend, if any of the above conditions hold true  
2. for Frontend, if ResourceType attribute contains "Storage"
Added new tests to verify the code changes and built sonic_config_engine-1.0-py3-none-any.whl successfully
> [minigraph] Update parsing logic for Storage backend devices

- src/sonic-config-engine/sonic-cfggen
There was a discussion and requirement in Chassis discussion forum to not make the asic-id field in the DEVICE_METADATA mandatory. If this field "asic-id" is not present the orchagent will be started without the -i <asic_id> parameter 
Ref: https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-orchagent/orchagent.sh#L39
Made the check to see if the asic-id is valid and update the asic-id field in the DEVICE_METADATA
> [multi-asic] Make asic-id in DEVICE_METADATA optional 

- device/mellanox/x86_64-mlnx_msn2010-r0/ACS-MSN2010/sai.profile
- device/mellanox/x86_64-mlnx_msn2100-r0/ACS-MSN2100/sai.profile
- device/mellanox/x86_64-mlnx_msn2410-r0/ACS-MSN2410/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/ACS-MSN2700/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-C28D8/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8/sai.profile
- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai.profile
- device/mellanox/x86_64-mlnx_msn2740-r0/ACS-MSN2740/sai.profile
- device/mellanox/x86_64-mlnx_msn3420-r0/ACS-MSN3420/sai.profile
- device/mellanox/x86_64-mlnx_msn3700-r0/ACS-MSN3700/sai.profile
- device/mellanox/x86_64-mlnx_msn3700c-r0/ACS-MSN3700C/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/ACS-MSN3800/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D24C52/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C49S1/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/sai.profile
- device/mellanox/x86_64-mlnx_msn4600-r0/ACS-MSN4600/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/ACS-MSN4600C/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D112C8/sai.profile
- device/mellanox/x86_64-mlnx_msn4700-r0/ACS-MSN4700/sai.profile
- device/mellanox/x86_64-mlnx_msn4800-r0/ACS-MSN4800/sai.profile
To create SDK dump on Mellanox devices when SDK event has occurred.
Set the SKUs keys needed to initialize the feature in SAI.
Simulate SDK event and check that dump is created in the expected path.
> [Mellanox] Update SKUs to enable SDK dumps (#7708)

- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/sai_preinit_cmd.soc
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/th3-z9332f-32x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/sai_preinit_cmd.soc
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-16x400G-64x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/sai_preinit_cmd.soc
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/led_proc_init.soc
Front end LED fw is not loaded in DellEMC Z9332f. 
Enabled LED fw files
Check LED status after loading the firmware.
> DellEMC: Enable Z9332f LED firmware

- src/sonic-py-common/tests/device_info_test.py
- src/sonic-py-common/tests/interface_test.py
To ensure any environment variables which are configured in the build/test environment do not influence the behavior of sonic-py-common during unit tests. For example, variables which might be set by continuous integration pipelines.
Add class-scoped pytest fixture to `TestDeviceInfo` class which stashes the current environment variables, clears them and yields. Once all the test cases in the class finish, the fixture will restore the original environment variables.
Also remove unnecessary unittest-style setup and teardown functions from interface_test.py
Ensure unit tests pass during package build with the following commands:
```
PLATFORM=not_a_valid_platform_string make target/python-wheels/sonic_py_common-1.0-py2-none-any.whl
PLATFORM=not_a_valid_platform_string make …
```
> [sonic-py-common] Clear environment variables before running device_info tests

- dockers/docker-sonic-mgmt/Dockerfile.j2
- src/sonic-config-engine/setup.py
A recent version of contextlib2 (https://pypi.org/project/contextlib2/21.6.0/#history) has broken Python2 compatibility, so the version picked up by netaddr when using Python2 must be specified, or else builds fail
Changed where netaddr is downloaded to also download the previous version of contextlib2
Build targets e.g. docker-sonic-mgmt-framework.gz
- [ X] 202012
- May also need variations applied to earlier branches
Reason is that an external dependency has changed, which needs to be fixed on any branch that uses that dependency
Specify contextlib2 version for use with Python2
> Fix sonic-cfggen contextlib err

- device/arista/x86_64-arista_7170_64c/pcie.yaml
Platform pcie configuration file doesn't exist for x86_64-arista_7170_64c
Generate pcie.yml
Started pcie daemon (pcied RUNNING   pid 63, uptime 0:00:19)
> [Arista] Generated pcie.yml for x86_64-arista_7170_64c

- platform/broadcom/saibcm-modules/make/Make.config
We hit an issue recently in the chassis bringup where the linux bde attach failed with the following ioctl error. 
[ 9058.585960] linux-user-bde (897363): Error: Invalid ioctl (00004c1d)
[ 9105.668237] linux-user-bde (901002): Error: Invalid ioctl (00004c1d)
Debugged with Broadcom team, who suggested to use this flag BCM_INSTANCE_SUPPORT to support multi-instance scenarios ( platforms with more than one asic where there are separate sai/syncd docker instances running controller each asic instance).
This flag was introduced since SDK-6.5.21 and need to be present in SAI and SAI GPL kernel module makefile.
Add the flag in this flag BCM_INSTANCE_SUPPORT in gpl modules 
Found the linux bde attach succeeding and orchagent/syncd up in a  chassis with multiple ASIC's.
Also verified that single …
> Add BCM multi-instance support in saibcm-modules for XGS and DNX platforms

- scripts/build_debian_base_system.sh
Multiple build failed in 202012 branch
It is caused by the disorder of the package urls retrieved from the command "apt-get download --print-urls <packages>"
> Fix the apt-get download package disorder issue

- .azure-pipelines/azure-pipelines-build.yml
Disable the nephos docker syncd rpc image temporarily
The package libboost-atomic1.71.0 does not exist in the debian:stretch, it has no chance to build a successful rpc image.
Revert the change until the rpc image upgraded to buster.
> [ci]: Disable nephos docker syncd rpc temporarily

- dockers/docker-platform-monitor/Dockerfile.j2
The libpci library provides portable access to configuration registers of devices connected to the PCI bus. 
update dockers/docker-platform-monitor/Dockerfile.j2. Total usage is: 
root@sonic:/var/log#  dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | grep libpci3
102     libpci3
Verify PCI based devices are mounted successfully on the PCI bus 
The libpci library provides portable access to configuration registers of devices connected to the PCI bus.
```
root@sonic:/home/admin# dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | grep libpci3
102     libpci3
```
> Add libpci3 pkg to docker-platform-monitor

- dockers/docker-platform-monitor/Dockerfile.j2
ethtool can be used to query and change settings such as speed, auto- negotiation and checksum offload on many network devices, especially Ethernet devices. 
add package extension to docker-platform-monitor/Dockerfile.j2 
ethtool -y 
more examples are @ https://linuxhint.com/ethtool_commands_examples/
ethtool can be used to query and change settings such as speed, auto- negotiation and checksum offload on many network devices, especially Ethernet devices. 
```
root@sonic:/# dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | grep ethtool
593     ethtool
```
> Add ethtool to docker-platform-monitor 

- files/build_templates/docker_image_ctl.j2
In VOQ chassis systems, system lag id boundary is set in redis-chassis server immediately after starting the database-chassis container in the supervisor card. This system lad id boundary was not set correctly all the time. Intermittently there was failure in setting these values in CHASSIS_APP_DB in redis-chassis server. This PR has fix for this.
The voq system lag id boundary is set in redis-chassis. Changes include
setting this from database-chassis container. This fixes a timing issue
in finding datbase_config.json file from redis directory which is
created from database container. Since database container usually
starts after database-chassis container the existence of this file is
unreliable while running the command. Running the command under
database-chassis container makes sure …
> [voqsystemlagid] Fix for timing issue in setting system lag id boundary

- dockers/docker-iccpd/iccpd.j2
- dockers/docker-iccpd/start.sh
The process of config generation (sonic-cfggen) fails, but the services continue to run with invalid config
* add exit with error on errors in start.sh script (because supervisord relies on start.sh return code).
* fix jinja template. Jinja use common python expressions under the hood and `has_key` method was removed from dict in py3, so use check by `in` operator as it is supported by both py2 and py3.
* compile sonic with enabled iccp. 
* add mclag config to CONFIG_DB. 
``` 
'MC_LAG|1' => {
"local_ip": "10.0.0.2",
"peer_ip": "10.0.0.3",
"peer_link": "Ethernet8",
"mclag_interface": "Ethernet12" 
}
* unmaks, enable and start swss and iccpd services in sonic.
* log in into the iccpd container and check the config file `/etc/iccpd/iccpd.conf`
* expected config:
```
mclag_id:1 …
> [iccpd][docker] fix initial startup configuration

- files/image_config/kdump/kdump-tools
[  342.439096] kdump-tools[13655]: /etc/init.d/kdump-tools: 117: /etc/default/kdump-tools: KDUMP_CMDLINE_APPEND+= panic=10 debug hpet=disable pcie_port=compat pci=nommconf sonic_platform=x86_64-accton_as7326_56x-r0: not found
The below error message is seen when a reboot is issued.
[  342.439096] kdump-tools[13655]: /etc/init.d/kdump-tools: 117: /etc/default/kdump-tools: KDUMP_CMDLINE_APPEND+= panic=10 debug hpet=disable pcie_port=compat pci=nommconf sonic_platform=x86_64-accton_as7326_56x-r0: not found
dash doesn't support += operation to append to a variable's value.
Use KDUMP_CMDLINE_APPEND="${KDUMP_CMDLINE_APPEND} " instead
Fix kdump error message when a reboot is issued
> [kdump] Fix kdump error message when a reboot is issued

- rules/phy-credo.mk
Signed-off-by: Boyang Yu <byu@arista.com>
phy-credo.service was only run once in booting. With this change, it will be restarted when running 'config reload'
Change the service from WantedBy=multi-user.target to wantedBy=sonic.target
Checked that service is restarted after running 'config reload -y', and the ports are still brought up.
> [Arista] Update phy-credo service for config load

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/td3-a7050cx3-32s-32x100G.config.bcm
- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/td3-a7050cx3-32s-48x50G+8x100G.config.bcm
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- src/sonic-device-data/tests/permitted_list
For DualToR There will be expected packet drops that should not be counted towards interface RX_DRP counters.
SAI support this feature but is only enabled if the proper SOC property is set in the device's conf.bcm file.
this change is to add the necessary SOC property for the HW SKUs that are purposed for DualToR Roles.
This is to port the exact same fix from master PR (https://github.com/Azure/sonic-buildimage/pull/7945) to 202012 branch due to cherry pick encountered conflict.
Send packet that is expected to be drop and check that it is not being counted towards interface RX_DRP counter.
Also tested with the case where  SAI change is not yet there but SOC is already enabled and observe it does not cause any undesirable side-effect.
Add SOC property to not count ACL Drops towards …
> [202012] Add BRCM SOC Property to not count ACL drops towards interface RX_DRP for DualToR platforms

- src/sonic-host-services/scripts/hostcfgd
- src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- src/sonic-host-services/tests/hostcfgd/test_vectors.py
Currently hostcfgd is implemented in a way each feature which is enabled/disabled triggering execution of systemctl enable/unmask commands which eventually trigger 'systemctl daemon-reload' command.
Each call like this cost 0.6s and overall add a overhead of ~12 seconds of CPU time.
This change will verify the desired state of a feature and the current state of this feature on systemd and trigger a system call only when must.
Check each feature status on systemd before executing a system call to enable and reload the systemctl daemon.
Build an image with this change and observe less system calls are executed.
> [hostcfgd] Enhance hostcfgd to check feature state and run less system calls

- .azure-pipelines/azure-pipelines-build.yml
- azure-pipelines.yml
Enable PR checks for 201811
Fix target/docker-sonic-vs.gz build break.
Not need to build docker-sonic-vs.gz in 201811 branch, the target is not built in Jenkins 201811 branch.
> [ci]: Support PR checks for 201811

- src/thrift/Makefile
- src/thrift/patch/0002-cve-2017-1000487.patch
Plexus-utils before 3.0.16 is vulnerable to command injection because it does not correctly process the contents of double quoted strings.
Upgrade to 3.0.16
> Fix CVE-2017-1000487 security alert (#7173)

- sonic-slave-buster/Dockerfile.j2
Fix a mess package version issue
Use SONiC's libnl instead of vanilla's.
> Remove vanilla libnl3 and libhiredis from slave buster

- files/build_templates/init_cfg.json.j2
- files/image_config/copp/copp_cfg.j2
- src/sonic-host-services/tests/hostcfgd/test_vectors.py
Currently dhcp packets are disabled by the COPP manager for non ToRRouter type switches.
Even if the feature is enabled, DHCP packets wont hook to the CPU since the COPP manager will not trap this packets.
This change is to disable dhcp_relay by default for non ToRRouter switches from init_cfg.json.
With this approach, if the user want to enable the feature for non ToRRouter switches, manual enablement is required by the 'feature' configuration.
This is to keep the current approach for MSFT production issue with dhcp relay for non ToRRouter switched and allow the user to decide if to use it or not.
Configure dhcp_relay 'disabled' by default on init_cfg.json for non ToRRouter switches.
Remove the exclusion of dhcp packets on copp_cfg.json …
> [dhcp_relay] Disable dhcp_relay for ToRRouter switches type by the feature manager

- src/libteam/patch/0012-Increase-min_ports-upper-limit-to-1024.patch
- src/libteam/patch/series
- src/sonic-yang-models/tests/yang_model_tests/tests/portchannel.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/portchannel.json
- src/sonic-yang-models/yang-models/sonic-portchannel.yang
Signed-off-by: Raphael Tryster <raphaelt@nvidia.com>
Restrict the min-links parameter in "config portchannel" to the range 1-1024.
Fixes Azure/sonic-buildimage#6781 in conjunction with https://github.com/Azure/sonic-buildimage/pull/1630.
Align YANG model with limits in libteam and sonic-utilties.
PR 1630 in sonic-utilities prevents CLI user from entering a value outside the allowed range.  This PR does the following:
- Increases the maximum value of min-links from 128 to 1024.
- Provides validation in libteam, incorporating as a patch the code in https://git.kernel.org/pub/scm/linux/kernel/git/jpirko/libteam.git/commit/?id=69a7494bb77dc10bb27076add07b380dbd778592.
- Updates the Yang model upper limit from 128 to 1024 (was inconsistent with libteam value).
- Updates the Yang model lower …
> Increase min-links limit for portchannel from 128 to 1024.

- dockers/docker-orchagent/enable_counters.py
Called RIF enable counters in enable_counters.py script.
* Install 201911 image on SONiC switch.
* make sure RIF counters are enabled.
> [201911] Change RIF counters to be enabled by default

- .azure-pipelines/azure-pipelines-image-template.yml
- .azure-pipelines/docker-sonic-slave.yml
- slave.mk
We didn't enabled reproducible build when building sonic-slave-[buster|stretch] image.
Recently some build failure shows up because of this issue.
Enable reproducible build in docker sonic-slave-*. That is adding BUILD_OPTIONS in make command.
This includes two pipeline jobs: docker-sonic-slave & official build, step: 'make PLATFORM=? configure'.
> Fix reproducible build related azure pipeline bug. 

- src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
- src/sonic-bgpcfgd/tests/test_static_rt.py
Static route configuration should not depend on BGP_ASN. Remove the dependency on BGP_ASN for StaticRouteMgr.
Fix https://github.com/Azure/sonic-buildimage/issues/8027
Check if BGP_ASN field before configuring static route redistribution and wait until BGP_ASN is available to enable static route redistribution.
Add unit test to cover the scenario and verify the functionality on a virtual switch.
> [bgpcfgd] Remove unnecessary dependency for StaticRouteMgr

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/t0-sample-graph.xml
Allow deploying DHCPv6 servers following the implementation PR: https://github.com/Azure/sonic-buildimage/pull/7772
Add DHCPv6 to minigraph.py on sonic-cfggen tool and improve the unit test to cover this change.
Try to deploy a switch with DHCPv6 servers.
> [dhcp_relay] DHCPv6 relay minigraph parsing support

- src/sonic-host-services/scripts/hostcfgd
- src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- src/sonic-host-services/tests/hostcfgd/test_vectors.py
Currently hostcfgd is implemented in a way each feature which is enabled/disabled triggering execution of systemctl enable/unmask commands which eventually trigger 'systemctl daemon-reload' command.
Each call like this cost 0.6s and overall add a overhead of ~12 seconds of CPU time.
This change will verify the desired state of a feature and the current state of this feature on systemd and trigger a system call only when must.
Check each feature status on systemd before executing a system call to enable and reload the systemctl daemon.
Build an image with this change and observe less system calls are executed.
> [hostcfgd] [202012] Enhance hostcfgd to check feature state and run less system calls

- rules/config
Allows users to host their own local docker registries and utilize them via the `REGISTRY_SERVER` and `REGISTRY_PORT` environmental variables
Only set `REGISTRY_SERVER` and `REGISTRY_PORT` in `rules/config` if they are unset.
1. Export environmental variables `REGISTRY_SERVER` and `REGISTRY_PORT` to an alternative docker registry. Export the environmental variable `ENABLE_DOCKER_BASE_PULL` to `y`.
2. Ensure the required `sonic-slave` docker images are not present locally, but are available in the docker registry
3. Execute `make init` and `make configure`
4. Confirm that the appropriate docker images were pulled from the appropriate docker registry, and not built locally
Allow build-time specification of alternative docker registries
> [build]: Allow build-time specification of alternative docker registries

- files/Aboot/boot0.j2
- files/image_config/config-setup/config-setup
- files/image_config/platform/rc.local
- files/image_config/secureboot/allowlist_paths.conf
The port state will be reset to up if user use `config load_minigraph` to recover configurations.
In another PR, we supported consume `port_config.json` file with minigraph: Related PR: https://github.com/Azure/sonic-utilities/pull/1705
This PR is for support `port_config.json` in image level, includes migration/secure boot.
The usage of `port_config.json` is very similar with `acl.json`, thus I modified existing codebase and add `port_config.json` to all places that involved `acl.json`
TODO
1. Modified `Aboot/boot0.j2` to support remove `port_config.json` during flash cleaning
2. Modified `config-setup` script to support copy `port_config.json` file to backup directory
3. Modified `platform/rc.local` script to support decode/unzip/copy `port_config.json` during nos migration and support …
> [port_config] Introduce ad-hoc mport_config.json file

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample-graph-resource-type.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
Backport #7944 
The current logic generates 'VLAN_SUB_INTERFACE' table if the device type is backend and cluster name contains 'str'. This is not a reliable method to determine a storage backend device
Updated the logic to generate 'VLAN_SUB_INTERFACE' table if any of the following conditions hold true
1. device is of type backend and ResourceType attribute is None
2. device is of type backend and ResourceType attribute contains "Storage"
3. device is of type backend and graph contains "Subinterface" section
Also updated the logic to set "is_storage_device" to True
1. for Backend, if any of the above conditions hold true
2. for Frontend, if ResourceType attribute contains "Storage"
Added new tests to verify the code changes and built sonic_config_engine-1.0-py3-none-any.whl successfully
> [202012] [minigraph] Update parsing logic for Storage backend devices

- build_debian.sh
- files/build_templates/sonic_debian_extension.j2
- rules/config
- src/sonic-ctrmgrd/ctrmgr/ctrmgr_iptables.py
- src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py
- src/sonic-ctrmgrd/ctrmgr/ctrmgrd.service
- src/sonic-ctrmgrd/ctrmgr/remote_ctr.config.json
- src/sonic-ctrmgrd/tests/ctrmgr_iptables_test.py
- src/sonic-ctrmgrd/tests/ctrmgrd_test.py
- src/sonic-ctrmgrd/tests/http_proxy.conf
- src/sonic-ctrmgrd/tests/no_proxy.conf
The original PR is found to work good. Hence reverting the revert,
> Revert "Revert "[Kubernetes]: The kube server could be used as http-proxy for docker""

- src/sonic-yang-mgmt/sonic_yang.py
- src/sonic-yang-mgmt/tests/libyang-python-tests/test_SonicYang.json
Backlinks are none when there is 0 backlinks. without this change `backlinks.number()` throws an exception when backlinks==None.
Allow backlinks to be None, so we get an empty list as a return from find_data_dependencies
```python
def test_find_leaf_dependencies_no_schema_dependencies(self):
sy = sonic_yang.SonicYang(YANG_DIR)
sy.loadYangModel()
sy.loadData(json.loads("""
{
"PORT": {
"Ethernet0": {
"alias":"eth0",
"lanes": "65",
"speed": "100000"
}
}
}
"""))
xpath = "/sonic-port:sonic-port/PORT/PORT_LIST[name='Ethernet0']/alias"
deps = sy.find_data_dependencies(xpath)
self.assertEqual(0, len(deps))
```
(added UT for the same idea)
> [sonic-yang] Backlinks are none when there is 0 backlinks

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/buffers_defaults_t0.j2
To update SONIC buffer pool settings to accommodate SAI adjustment for TD3 calculations
Updated buffers_default_t0.j2 file.
Verified all QoS tests to be working for this new change. Needed to update sonic-mgmt test params file accordingly.
Updated buffer pool settings to accommodate SAI adjustment for TD3
> Updated buffer pool settings to accommodate SAI adjustment for TD3

- platform/mellanox/mlnx-platform-api/sonic_platform/watchdog.py
[WARM-REBOOT] fix issue of watch-dog on mellanox simulator platform when executing warm-reboot
to prevent python exception error when executing warm-reboot command on mellanox simulator platform
return None on the watchdog python script on cases that watchdog file is not exist
warm-reboot is running well without the python error. error message will appear on log on these cases.
in order to avoid this error message we can simulate the watchdog on mellanox simulator platform
[WARM-REBOOT] fix issue of watch-dog on mellanox simulator platform when executing warm-reboot
> [WARM-REBOOT] [Mellanox] fix watchdog issue on mellanox simulator platform when executing warm-reboot

- src/sonic-host-services/scripts/hostcfgd
It can be that service is not enabled but UnitFilePreset=enabled (case
for Application Extension):
```
Loaded: loaded (/lib/systemd/system/cpu-report.service; disabled; vendor preset: enabled)
```
This makes existing logic skip enabling the service.
To fix an issue when a 3rd party package cannot be started by hostcfgd.
Check explicitely for UnitFileState.
Ran UT & ran it on the switch.
Installed 3rd party package and enabled it in config db, verified feature can start.
> [hostcfgd] differentiate between UnitFileState and UnitFilePreset

- files/build_templates/sonic_debian_extension.j2
- rules/config
- slave.mk
This helps not to hard code the docker proxy IP, but take it from config file during build time.
> Get Docker proxy info from config

- platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
- platform/mellanox/mlnx-platform-api/sonic_platform/platform.py
[PMON] syseepromd fix for  mellanox simulator platform - avoid initializing sfp/thermal/components/fan/psu/leds on simx and create vpd_info file on hw_management when we use mellanox simulator platform
this is a fix for issue in mellanox simulator platforms. the syseepromd failed on the pmon docker. also "decode-syseeprom" failed also
- before initializing thermal/components/fan/psu/leds --> check if we are running on simx
- creating the vpd_info on the hw_management folder.
- check if syseepromd process was loaded properly on the pmon docker.
- decode-syseeprom is working well without errors/warnings
fix issues on syseeprom on mellanox simulator platforms. problem was discovered on 202012 release.
> [PMON] [Mellanox] fix syseepromd issue on simx

- dockers/docker-sonic-mgmt/Dockerfile.j2
Signed-off-by: Sharon Lutati <slutati@nvidia.com>
the motivation for this PR is to add retry_call to several test cases in the community, for example, the following cases:
- test_show_platform_fanstatus_mocked
- test_show_platform_temperature_mocked
are executing a command once and comparing the output to the expected mock data,
sometimes differences between the mock and the actual are causing the tests to fail. 
retry will make these tests more stable.
retry will also be more efficient than sleep which will cause the tests to run longer because sometimes it is not necessary to sleep all that time, retry will only run a function only until it passed.
added retry to the docker file
I run the tests with retry on the docker after installing the retry package 
adding retry to dockerfile so …
> Added retry to sonic-mgmt docker container

- platform/broadcom/sai.mk
Move SAI libraries for Broadcom for XGS and DNX families to 5.0.0.6
Included fixes 
```
CS00012195263 | [4.3][5.0][TD3]   Packets with broken IP headers received on VLAN interface are not dropped
CS00012192505 | [4.3] Re-encap   IPinIP decap packets
CS00012192502 | [3.7.5.2] Start   LED shell script execution on all DELL based platforms causing all ports   flapping on SAI 3.7.5.2
CS00012191363 | [4.3] Support   of memscan thread to detect TCAM parity error
CS00012190932 | [4.3]   SAI_PORT_PFC_X_RX_PKTS incremented incorrectly even when no PFC frames are   received on that priority
CS00012183901 | [4.3][WARMBOOT]   WARMReboot with active traffic causes port flap reported during warm reboot
CS00011382163 | [4.4] Support   warm-boot from 3.5 to 4.3
CS00011318937 | [4.3] MACSec   SAI Support …
```
> Brcm SAI bcm update to 5.0.0.6-1

- device/accton/x86_64-accton_as4630_54te-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/__init__.py
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/chassis.py
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/fan.py
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/fan_drawer.py
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/helper.py
- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/psu.py
- device/accton/x86_64-accton_as4630_54te-r0/system_health_monitoring_config.json
1. Implement FanDrawer-Fan hierarchy.
2. Enable thermalctld, disable pcied.
3. Implement SystemLED in Chassis.
4. Correct Fan direction
5. Implement require Fan APIs for SystemHealthMonitoring.
6. Handle non-ascii character while reading PSU model/serial num.
To support system health monitoring feature.
Mainly provided a config file, system_health_monitoring_config.json. Then implement the SystemLED part that'd be manipulated by HealthChecker. Others are just to correct the provided information which will be utilized by HardwareChecker.
Check if System-health can pass the check and display the SystemLED correctly.
```
///////// booting, DIAG_LED = GREEN_BLINKING /////////
root@sonic:/tmp# show system-health detail 
System is currently booting...
root@sonic:/tmp# cat …
```
> [Accton] AS4630-54TE support SystemHealthMonitor

- platform/broadcom/sonic-platform-modules-accton/as9716-32d/modules/pddf_custom_psu.c
AS9716-32D PSU. So need DRV to support it.
Add needed code to pddf_custom_psu.c to deal with multi PSU and get SN.
Plugin new PSU (3Y) and test,
root@sonic:/sys/bus/i2c/drivers/psu/9-0050# cat psu_serial_num
S0A000X601919000013
root@sonic:/sys/bus/i2c/drivers/psu/9-0050# cat psu_model_name
YESM1300AM
root@sonic:/home/admin# pddf_psuutil mfrinfo
PSU    Status    Manufacturer ID    Model       Serial                Fan Airflow Direction
-----  --------  -----------------  ----------  --------------------  -----------------------
PSU1   NOT OK    3Y POWER           YESM1300AM  S0A000X601919000007  exhaust
PSU2   OK        3Y POWER           YESM1300AM  S0A000X601919000013  exhaust
> [AS9716-32D]Support multi PSU SN in PDDF

- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/port_config.ini
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/port_config.ini
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/port_config.ini
Backport the fix (444cede11) that was made for the default SKU
to the alternative SKUs.
The `tenGigE1/33` and `tenGigE1/34` works with the default SKU configuration, but not with the one I want to use - `DellEMC-S5232f-P-25G`.
I looked at the differences between these SKUs as well as the state in `bcmsh` and saw that the `ps` output looked off when `Ethernet129` was enabled.
- Connect a device to one of the two 10G slots (not both)
- Load e.g. the 25G SKU: `sonic-cfggen -H -k DellEMC-S5232f-P-25G --print-data > /etc/sonic/config_db.json; reboot`
- Enable the port: `sudo config int startup Ethernet129`
- Observe the port still being down: `show int status | grep tenGig`
- Enable the other port: `sudo config int startup Ethernet128`
- Observe the first port now being up, while the SFP …
> [DellEmc] Fix port lanes on alternative S5232 SKUs

- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C8D48/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-100G/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-10G/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-P-25G/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-C64/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-C8D112/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_z9264f_c3538-r0/DellEMC-Z9264f-Q64/buffers_defaults_t0.j2
In QoS buffer profile, mode field is not needed.
Edited buffer_defaults_t0/t1 for Dell HWSKU's.
Check syslog, swss processes and buffer values in NPU shell
UT logs: 
[buffer_UT.txt](https://github.com/Azure/sonic-buildimage/files/6810746/buffer_UT.txt)
> DellEMC: Buffer profile changes

- platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-accton/as7816-64x/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-accton/as9716-32d/sonic_platform/chassis.py
Add get_sfp() to chassis to handle port_config.ini port index start from 1.
Configure use port start from 1, but code sfp_list[]  is start from 0.  It will cause port range error.
Implement get_sfp() to chassis.py
Test script to check port range is ok from 1 to 58 on as7326 and other DUT.
> [PDDF] Add get_sfp() to chassis to handle port idx

- src/dhcpmon/src/dhcp_device.c
- src/dhcpmon/src/dhcp_device.h
- src/dhcpmon/src/dhcp_devman.c
- src/dhcpmon/src/dhcp_devman.h
- src/dhcpmon/src/dhcp_mon.c
- src/dhcpmon/src/dhcp_mon.h
- src/dhcpmon/src/main.c
Enhance DHCP monitor application following the implementation PR: https://github.com/Azure/sonic-buildimage/pull/7772
Add the support for monitoring DHCPv6 packets.
Install an image with this PR and the implementation PR.
> [dhcp_relay] Enhance DHCP monitor application to support DHCPv6

- platform/mellanox/mlnx-platform-api/sonic_platform/pcie.py
BIOS upgrade on rare cases cannot guarantee bus value remain the same on every BIOS release. Ignoring this field in order for pcied not to fail but still verify device id in a different way. The solution is future proof and will not require changes in code when new BIOS version is available
Since bus is not a fixed value (it is determined by the bios version) we are ignoring this field, and instead checking if there is a device that match on all other fields that and in addition has a matching device id.
Verify no errors or failures in pcied on different BIOS version with the same code base.
> [Mellanox][pcied] Ignore bus on pcie.yaml for Mellanox switches

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.conf.j2/all.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/all.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/defaults.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/frr.conf.j2/all.conf
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr.conf
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/py2/bgpd_frr_frontend_asic.conf
- src/sonic-config-engine/tests/sample_output/py2/frr.conf
- src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-bgpd.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_backend_asic.conf
- src/sonic-config-engine/tests/sample_output/py3/bgpd_frr_frontend_asic.conf
- src/sonic-config-engine/tests/sample_output/py3/frr.conf
- src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-bgpd.conf
There are scenarios that End-of-RIB comes from a part of the peers arrives after reconciliation. In such scenarios, if the route selection deferral timer has the default value of 360 seconds, FRR would not set up routes and all routes would be removed after reconciliation. This PR reduces the route selection deferral timer so that at least routes to parts of the peers get restored at the point of reconciliation.
Fix https://github.com/Azure/sonic-buildimage/issues/7488
Reduce route selection deferral timer for bgp graceful restart to 15 seconds.
> Reduce route selection deferral timer for bgp graceful restart

- dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/voq_chassis.conf
- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/voq_chassis.json
- src/sonic-bgpcfgd/tests/test_sonic-cfggen.py
For multiasic, the back end asics use ip addresss of Loopback4096 for BGP router id. In VOQ multi-asic chassis there are no back end asics. All the asics are front end and the iBGP connections are established via Ethernet-IB of asics. Since these asics are not designated as BackEnd, the ip address of interface Loopback0 is used as BGP router id. Since the ip address of Loopback0 is same for all the asics in the line card, same router id is used for voq iBGP configurations and hence the iBGP connections are not established. Changes are done to fix this
To fix this (i.e., to have different router ids for differen iBGP peers), we need to use the ip address of Loopback4096 for
the front end asics also in VOQ chassis systems. The bgp main configuration template is adjusted to take ip address …
> [multiasic][voq][bgpconf] Fix for the issue of same BGP router id in all asics

- src/sonic-bgpcfgd/tests/data/sonic-cfggen/bgpd.main.conf.j2/voq_chassis.conf
To fix Azure pipeline failure due to unit test failure in sonic-bgpcfgd submodule. 
The unit test failure was due to missing bgp graceful restart select defer time configuration in voq_chassis.conf. Modified sample output data file voq_chassis.conf to include this configuration.
- Trigger Azure pipeline build. 
- Observe pipeline completes successfully.
N/A
Fix for unit test failure in bgpcfgd for voq switch
> [bgpcfgd][voq] Fix for unit test failure in bgpcfgd config for voq switch

- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_defaults_t1.j2
1) Removed ingress_lossy_pool from the BUFFER_POOL list
2) Fx the the egress_lossless_pool_size value 
1) Reboot with the updated SKU.
2) Perform a qos reload avd verify if the buffer profiles are applied properly without any error
> [Mellanox] [SKU] Fix the shared headroom for 4600C-C64 SKU

- device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/buffers_defaults_t1.j2
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_def.j2
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t0.j2
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t1.j2
As part of the buffer reclamation efforts for TD2, setting the default cable len to 0m which means unused ports will have a cable len of 0m. 
To align with the changes in Azure/sonic-swss#1830
With the default cable len set to 0m and the associated changes in swss, CABLE_LENGTH table had '0m' set for unused ports and accordingly more space was reserved for the shared pool
> Update default cable len to 0m for TD2

- platform/mellanox/mlnx-platform-api/sonic_platform/pcie.py
A device that contains only decimal digits was mistreated as a decimal integer resulting in failure to find it in the id to bus map.
Made sure id from the yaml file was treated as a string
Open log on 4600, make sure no error appear.
> [Mellanox][Pcie] Fix issue on pcied with an id that contains only decimal digits was treated as a decimal number

- files/build_templates/sonic_debian_extension.j2
j2cli provides access to jinja library. Our platform.py requires j2cli to handle jinja template configuration files.
add j2cli to sonic_debian_extension.j2 file 
install j2cli
> add j2cli to sonic_debian_extension.j2

- src/sonic-ctrmgrd/ctrmgr/remote_ctr.config.json
disable http_proxy for docker by default. by default, we should not use proxy.
> [k8s]: disable http_proxy for docker by default

- src/snmpd/Makefile
Signed-off-by: Justin Sherman <jusherma@cisco.com>
I have been seeing intermittent (~40%) build failures with the same error described in PR https://github.com/Azure/sonic-buildimage/pull/6592, even with that fix present
```
/usr/bin/ld: mibgroup/ip-forward-mib/ipCidrRouteTable/.libs/ipCidrRouteTable_interface.o: file not recognized: file truncated
...
libtool:   error: 'mibgroup/ip-forward-mib/inetCidrRouteTable/inetCidrRouteTable_interface.lo' is not a valid libtool object
make[5]: *** [Makefile:1020: libnetsnmpmibs.la] Error 1
make[5]: *** Waiting for unfinished jobs....
```
Use `-j1` for the libsnmp build regardless of the value of `$(MULTIARCH_QEMU_ENVIRON)`
Performed 10 builds of the libsnmp target (`target/debs/buster/libsnmp-base_5.7.3+dfsg-5_all.deb`) with and without this …
> [build] Always use -j1 for libsnmp to avoid race condition

- rules/sonic-config.dep
Changes in the buffer template did not trigger a new sonic-config-engine wheel build and the cached build was used for the PR merge. When the new wheel build got trigged, few sonic-cfggen testcases started failing because of the changes made in the buffer templates.
Updated the dependency to include buffer templates and built sonic_config_engine-1.0-py3-none-any.whl. Testcase failure was seen as expected
> [sonic-config] Include buffer templates in config dependency list

- dockers/docker-platform-monitor/critical_processes
- dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
To fix the issue #8239 
Enable Autorestart of the daemons in PMON for unexpected exit 
Remove the daemon list from the critical_process which prevent the PMON
from restarting when the individual daemon crashes.
Run sonic-mgmt/tests/platform-test/daemon/test_ledd.py and 
verify the test_pmon_ledd_kill_and_start_status
> Enable Autorestart of the daemons in PMON for unexpected exit

- src/systemd-sonic-generator/debian/changelog
Signed-off-by: Raphael Tryster <raphaelt@nvidia.com>
Malformed changelog file causes build to fail when SONIC_PROFILING_ON = y.
Changed the number and position of spaces in the file.
In rules/config, uncomment the line: SONIC_PROFILING_ON = y
make configure PLATFORM=mellanox
make target/sonic-mellanox.bin-clean
make target/sonic-mellanox.bin
Expect NOT to see warnings or errors relating to debian/changelog, such as
dpkg-genchanges: warning: debian/changelog(l3): found end of file where expected more change data or trailer
However, the build may still fail as long as Azure#8316 is not fixed, due to another issue.
Fixed changelog format.
> Fixed changelog file - 1 space at start of line, 2 spaces before day

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_serial_getty_monitor
serial-getty service exited in Dell S6100 device randomly. 
Added serial-getty to monit services.
Stop serial-getty in ssh session and check whether the service restarts or not.
UT: 
[s6100_UT.txt](https://github.com/Azure/sonic-buildimage/files/6914543/s6100_UT.txt)
> Dell S6100: Monitor serial-getty service

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/platform_reboot_override
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/reboot_plugin
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- Added a check in determining CPU reset in fast-/warm-reboot in their respective platform plugin.
- Introducing reboot plugin for "reboot" command to handle its own platform plugin.
On branch s6100_fast_warm_check
(use "git reset HEAD <file>..." to unstage)
modified:   ../../debian/platform-modules-s6100.install
modified:   ../scripts/fast-reboot_plugin
modified:   ../scripts/platform_reboot_override
new file:   ../scripts/reboot_plugin
modified:   ../scripts/track_reboot_reason.sh
modified:   chassis.py
- Triggered cold-reset inside fast-reboot to test out the reboot-cause 2.0 API.
[s6100-logs.txt](https://github.com/Azure/sonic-buildimage/files/6737835/s6100-logs.txt)
> [DellEMC] S6100 Reboot cause determining CPU reset in fast-reboot

- dockers/docker-orchagent/Dockerfile.j2
This is for fixing issue: https://github.com/Azure/sonic-buildimage/issues/8337
Explicitly install the `iputils-ping` which include the `ping6` tool to the orchagent docker
Install `iputils-ping` to orchagent docker for arm platform
> [ARM] Fix issue whre the ping6 tool is missing from orchagent docker

- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-16x400G-64x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/buffers_defaults_t0.j2
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/buffers_defaults_t1.j2
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm
Optimize MMU settings for Dell Z9332 systems in T0/T1 topology
Updated SONIC buffer profile settings for TH3 in T0/T1 topology
I cross-verify the MMU configuration with BRCM spreadsheet as well as did basic test on systems.
- [x ] 202012
Updated SONIC buffer profile settings for TH3 in T0/T1 topology
> Dell Z9332 systems optimized MMU settings for T0/T1 topology

- device/arista/x86_64-arista_7170_32c/Arista-7170-32C-C32/board_lane_map.json
- device/arista/x86_64-arista_7170_32c/default_sku
- device/arista/x86_64-arista_7170_32c/sensors.conf
- device/arista/x86_64-arista_7170_32cd/sensors.conf
- rules/docker-platform-monitor.mk
This PR only contains backports from master
- Fix leak discovered on master, though 202012 is not affected it's better to have the fix (fixes #7515)
- Fix `EepromDecoder`implementation in the platform API (fixes #8263)
- Fix Mineral platform definition and configuration
- Fix build issues in environments where `/proc` is not mounted/restricted (fixes #7800)
- Fix some pytest issues
- Add sfp-eeprom C API and also mount it in pmon
> [202012][Arista] Update platform library submodules

- device/dell/x86_64-dellemc_z9332f_d1508-r0/pcie.yaml
To support "pcied" and "pcieutil" commands in DellEMC Z9332f.
Add 'pcie.yaml' in device/dell/[PLATFORM]/ directory.
Execute "pcieutil check" command.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/6935430/UT_logs.txt)
DellEMC: Add pcie.yaml for Z9332f
> DellEMC: Add pcie.yaml for Z9332f

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
platform test suite failed for few API's in DellEMC Z9332f platform.
Modified the API's to return the expected values in the script.
Run platform test suite after making the changes.
Platform test suite has passed after making the API changes.
UT: 
[z9332f_UT.txt](https://github.com/Azure/sonic-buildimage/files/6877574/z9332f_UT.txt)
> DellEMC: Z9332f platform API changes

- device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/buffers_defaults_t1.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/buffers_defaults_t1.j2
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_def.j2
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t0.j2
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/buffers_defaults_t1.j2
- src/sonic-config-engine/tests/test_multinpu_cfggen.py
Reverts #8320 and align sonic-cfggen testcases with the new change
> Revert "Revert "Update default cable len to 0m for TD2""

- files/image_config/hostcfgd/hostcfgd
The time gap between last  config load & db-listen seem to have increased.
Any config updates that occurred in this gap gets missed by db-listen.
This could miss updating /etc/pam.d/common-auth-sonic
Add a one shot timer, just before db-listen. The timer will fire after the subscribe is done
When the timer fires, reload tacacs & aaa
A tough repro. So you may explicitly add  some sleep just before listen.
Make sure the sleep is at least 10 seconds less than timer.
Write a log just before sleep.
restart hostcfgd and watch syslog for the added log line
Upon this log, make some tacacs updates that would have some change in
/etc/pam.d/common-auth-sonic.
Watch for changes in that file
> hostcfgd: Handle missed tacacs updates between load & listen

- platform/broadcom/sai.mk
Updated Broadcom SAI Debian package to 3.7.6.1  Following are the major changes here:
```
- CS00011651922/CS00012192502 SID:Parity error in TDM Calendar memories causes traffic drop after SER correction
- CS00011222060 soc_mem_alpm_delete: unit 0: ALPM delete operation[L3_DEFIP_ALPM_IPV6_128] encountered parity error
- Cesto Phy Recovery enhancement.
- SDK compile with flag -DBCM_MONOTONIC_TIME and -DBCM_MONOTONIC_MUTEXES
```
How I verify:
Manual verification looks fine . (Link/LLDP/LACP/BGP are fine)
```
drivshell>bsv
bsv
BRCM SAI ver: [3.7.6.1], OCP SAI ver: [1.5.2], SDK ver: [6.5.16]
```
> [201911] Updated Broadcom SAI Debian package to 3.7.6.1

- files/build_templates/arp_update_vars.j2
- files/scripts/arp_update
* `arp_update` fails to ping those neighbors over vlan sub interfaces.
* modify `arp_update_vars.j2` to get vlan sub interfaces with ipv6 addresses assigned.
* modify `arp_update` to send ipv6 pings over those retrieved vlan sub interfaces.
* run `arp_update` on `t0-backend` topology with `set -x`
```
root@str2-7050qx-32s-acs-02:/# ./arp_update
+ ARP_UPDATE_VARS_FILE=/usr/share/sonic/templates/arp_update_vars.j2
+ /bin/true
++ sonic-cfggen -d -t /usr/share/sonic/templates/arp_update_vars.j2
+ ARP_UPDATE_VARS='{
"interface": "",
"pc_interface" : "",
"vlan_sub_interface": "Ethernet100.10 Ethernet104.10 Ethernet108.10 Ethernet112.10 Ethernet116.10 Ethernet120.10 Ethernet124.10 Ethernet80.10 Ethernet84.10 Ethernet88.10 Ethernet92.10 Ethernet96.10 ",
"vlan" : "Vlan1000"
}'
++ echo '{' …
```
> [swss][arp_update] Send ipv6 pings over vlan sub interfaces

- dockers/docker-platform-monitor/critical_processes
- dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
To fix the issue #8239
Enable Autorestart of the daemons in PMON for unexpected exit
Remove the daemon list from the critical_process which prevent the PMON
from restarting when the individual daemon crashes.
Run sonic-mgmt/tests/platform-test/daemon/test_ledd.py and
verify the test_pmon_ledd_kill_and_start_status
> [202012] Enable Autorestart of the daemons in PMON for unexpected exit

- slave.mk
print out the process that hold the dpkg frontend lock.
add debug info for dpkg frontend lock
print out the process that hold the dpkg frontend lock.
run parallel build
> [build]: add debug info for dpkg frontend lock

- build_debian.sh
- files/build_templates/sonic_version.yml.j2
- platform/vs/sonic-version/build_sonic_version.sh
the branch refers the branch name, for example
master, 202012, 201911, ...
will modify 'show version' command to output this as well.
example for master branch
```
build_version: 'master.602-6efc0a88'
debian_version: '10.7'
kernel_version: '4.19.0-9-2-amd64'
asic_type: vs
commit_id: '6efc0a88'
branch: 'master'
release: 'none'
build_date: Tue Dec 29 06:54:02 UTC 2020
build_number: 602
built_by: johnar@jenkins-worker-23
```
example for 202012 release branch
```
build_version: '202012.602-6efc0a88'
debian_version: '10.7'
kernel_version: '4.19.0-9-2-amd64'
asic_type: vs
commit_id: '6efc0a88'
branch: '202012'
release: '202012'
build_date: Tue Dec 29 06:54:02 UTC 2020
build_number: 602
built_by: johnar@jenkins-worker-23
```
**- Which …
> [build]: add branch and release tag in sonic_version.yml

- src/sonic-host-services/pytest.ini
- src/sonic-host-services/tests/caclmgrd/caclmgrd_dhcp_test.py
- src/sonic-host-services/tests/caclmgrd/test_dhcp_vectors.py
- src/sonic-host-services/tests/common/mock_configdb.py
- src/sonic-host-services/tests/hostcfgd/hostcfgd_radius_test.py
- src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- add test code to check dhcp acl update
> caclmgrd: add test code to check dhcp acl update

- sonic-slave-buster/Dockerfile.j2
- src/openssh/Makefile
install build dep causes dpkg lock issue in parallel build
install build dep causes dpkg lock issue in parallel build
move build-dep into sonic-slave docker
did parallel build and check
> [openssh]: move build dep installation to sonic-slave-buster

- src/sonic-host-services/scripts/caclmgrd
Bug fix:
- assign state_db_id even if the mode is not dual_tor
- upon state_db change, state_db_id will be referred for comparison
- fix the issue https://github.com/Azure/sonic-buildimage/issues/8388
> Caclmgrd: fix a minor bug

- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/th3-z9332f-32x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-16x400G-64x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm
- src/sonic-device-data/tests/permitted_list
To fix tunnel termination issue on TH3 which resulted in warm-reboot failure tracked by issue - https://github.com/Azure/sonic-buildimage/issues/8397
Add SOC property to enable tunnel termination entry creation for TH3
Verified logs and ASIC-DB for tunnel termination entry creation, tested warm-reboot on 9332f platforms. Failure seen before adding SOC property was resolved after this change.
Add SOC property to enable Tunnel termination entry creation on TH3
> Fix TH3 Warm-reboot failure due to Tunnel termination SAI failure

- src/sonic-host-services-data/debian/sonic-host-services-data.aaastatsd.service
- src/sonic-host-services-data/debian/sonic-host-services-data.aaastatsd.timer
- src/sonic-host-services-data/debian/sonic-host-services-data.hostcfgd.service
- src/sonic-host-services-data/debian/sonic-host-services-data.hostcfgd.timer
hostcfgd is starting at the same time as 'create_switch' method is called on orchagent process.
This introduce a degradation on the function execution time which eventually cause the fast-boot flow and a boot scenarion in general to run slower (~6 seconds).
This change will delay the start time of this daemon.
The aaastatsd will delay as well since it has a dependency on hostcfgd, so it is required to delay both.
90 seconds determined as the maximum allowed downtime for control plane to come back up on fast-boot flow.
Add two timers for hostcfgd and aaastatsd  services in order to delay the startup of these services.
Install an image with this change and observe the daemons start 90 seconds after the system boot.
> [hostcfgd] Delay hostcfgd and aaastatsd for faster boot time

- src/sonic-host-services-data/debian/sonic-host-services-data.hostcfgd.service
- src/sonic-host-services-data/debian/sonic-host-services-data.hostcfgd.timer
hostcfgd is starting at the same time as 'create_switch' method is called on orchagent process.
This introduce a degradation on the function execution time which eventually cause the fast-boot flow and a boot scenario in general to run slower (~6 seconds).
This change will delay the start time of this daemon.
90 seconds determined as the maximum allowed downtime for control plane to come back up on fast-boot flow.
Add a timer for hostcfgd service in order to delay the startup of this service.
Install an image with this change and observe the daemon start 90 seconds after the system boot.
> [hostcfgd] [202012] Delay hostcfgd for faster boot time

- src/sonic-host-services/scripts/determine-reboot-cause
Install sonic image from ONIE. Once system is up, execute "config reload" command.
Root cause is that "determine-reboot-cause.service" was in failed state.
root@sonic:/host/reboot-cause# systemctl list-units --failed
UNIT LOAD ACTIVE SUB DESCRIPTION
● determine-reboot-cause.service loaded failed failed Reboot cause determination service
"determine-reboot-cause" script fails with below error.
Jun 17 10:52:13 sonic chassis: Platform api returns reboot cause Non-Hardware, None
Jun 17 10:52:13 sonic chassis: Platform api returns reboot cause Non-Hardware, None
Jun 17 10:52:13 sonic chassis: Platform api indicates reboot cause Non-Hardware
Jun 17 10:52:13 sonic chassis: Reboot cause file /host/reboot-cause/reboot-cause.txt …
> [reboot-cause] Fixed determine-reboot-cause.service failure.

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_serial_getty_monitor
serial-getty service exited in Dell S6100 device randomly.
Added serial-getty to monit services.
Stop serial-getty in ssh session and check whether the service restarts or not.
UT: 
[202012_UT.txt](https://github.com/Azure/sonic-buildimage/files/6960310/202012_UT.txt)
> [202012] Dell S6100: Monitor serial getty service

- platform/broadcom/rules.dep
[ DPKG ] Cache is not enabled for platform-modules-ruijie-b6510-48vs8cq_1.0_amd64.deb package 
[ DPKG ] Cache is not enabled for platform-modules-ragile-ra-b6510-48v8c_1.0_amd64.deb package 
Add the platform ruihie and ragile .dep file to platform/broadcom/rules.dep
Run a build and check if the warning message is there or not and also check the packages are copied under 'target/cache' directory after the first build.
> Enable the cache build for the platform ragile and ruijie.

- src/sonic-device-data/tests/hwsku_json_checker
enable automated test suites to selectively run relevant tests ( or not run tests ) based upon a new port_type identifier in hwsku.json
Modified the valid optional fields in validity check for hwsku.json per recommendation from Joe in 
https://github.com/Azure/sonic-mgmt/pull/2654/files
backport to 202012 so that the enhanced automation tests can skip copper ports for sfp tests
> [sonic-device-data]: add port_type to OPTIONAL_PORT_ATTRIBUTES

- device/arista/x86_64-arista_7050_qx32/Arista-7050-Q16S64/td2-a7050-qx32-16x40G+32x10G+8x40G.config.bcm
- device/arista/x86_64-arista_7050_qx32/Arista-7050-QX32/td2-a7050-qx32-32x40G.config.bcm
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/td2-a7050-q31s4-31x40G-4x10G.config.bcm
- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX32S-Q32/td2-a7050-qx32s-32x40G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-C32/th-a7060-cx32s-32x100G-t1.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-D48C8/th-a7060-cx32s-8x100G+48x50G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q24C8/th-a7060-cx32s-8x100G+24x40G.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t0.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-Q32/th-a7060-cx32s-32x40G-t1.config.bcm
- device/arista/x86_64-arista_7060_cx32s/Arista-7060CX-32S-T96C8/th-a7060-cx32s-8x100G+96x25G.config.bcm
- device/arista/x86_64-arista_7060px4_32/Arista-7060PX4-C64/th3-a7060px4-32-64x100G.config.bcm
- device/arista/x86_64-arista_7060px4_32/Arista-7060PX4-O32/th3-a7060px4-o32-32x400G.config.bcm
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-D108C8/config.bcm.j2
- device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-Q64/config.bcm.j2
- device/broadcom/x86_64-bcm_xlr-r0/BCM956960K/th_32x100.config.bcm
- device/celestica/x86_64-cel_e1031-r0/Celestica-E1031-T48S4/helix4-e1031-48x1G+4x10G.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
- device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm
- device/celestica/x86_64-cel_seastone-r0/th-seastone-dx010-config-flex-all.bcm
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000-Q20S48/td2-s6000-20x40G-48x10G.config.bcm
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000-Q24S32/td2-s6000-24x40G-32x10G.config.bcm
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000-Q28S16/td2-s6000-28x40G-16x10G.config.bcm
- device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/td2-s6000-32x40G.config.bcm
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t0.config.bcm
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t1.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/th3-z9332f-32x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-16x400G-64x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm
For all BRCM ACL Drops there is a way not to count these packet drops towards the interface RX_DRP counters by enabling a new SOC property. This SOC property is being enabled on the chosen BRCM HW SKUs config.bcm files.
Send packet that is expected to be drop due to ACL and check that it is not being counted towards interface RX_DRP counter.
Also tested on S6100, 7260, and TD3 WARM Reboot scenario where this SOC property was not present before the WARM Reboot but become enabled after WARM Reboot.
Add SOC property to not count ACL Drops towards interface RX_DRP for All BRCM HW SKUs.
> [202012] BRCM Disable ACL Drop counted towards interface RX_DRP counters

- dockers/docker-ptf/Dockerfile.j2
add xmlrunner to generate the test report in xunit format
add xmlrunner to generate the test report in xunit format
built the ptf docker and check the function with test cases
- vxlan/test_vxlan_decap.py
- local test case for sai testing
> [docker-ptf]PTF adds xmlrunner for xunit report

- .gitignore
- Makefile
- platform/checkout/cisco-8000.ini
- platform/checkout/template.j2
Update Makefile, so it does the following:
For a given platform, verify if platform/checkout/.ini exists and
hence run the platform/checkout/template.j2. This allows platform
code to be checked out during the 'make configure' stage.
Signed-off-by: Anand Mehra <anamehra@cisco.com>
> Platform/cisco-8000 module for sonic-buildimage (8172)

- device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/hwsku.json
hwsku.json port_type attribute is the preferred method for test to differentiate copper vs sfp+ for Nokia-7215.
added PR 8370 on which this PR depends first -  then added hwsku.json file according to platform specification. 
Depends on PR 8370 
Needed for Nokia 7215 test pass
> [Nokia] Add hwsku.json for the Nokia-7215

- Makefile.work
- dockers/docker-base-buster/Dockerfile.j2
- dockers/docker-base-stretch/Dockerfile.j2
- dockers/docker-base/Dockerfile.j2
- slave.mk
Support to build armhf/arm64 platforms on arm based system without qemu simulator.
When building the armhf/arm64 on arm based system, it is not necessary to use qemu simulator.
Build armhf on armhf system, or build arm64 on arm64 system, by default, qemu simulator will not be used.
When building armhf on arm64, and you have enabled armhf docker, then it will build images without simulator automatically. It is based how the docker service is run.
Docker base image change:
For amd64, change from debian:<os-release>to amd64/debian:<os-release>
For arm64, change from multiarch/debian-debootstrap:arm64-<release> to arm64v8/debian:<os-release>
For armhf, change from multiarch/debian-debootstrap:armhf-<release> to arm32v7/debian:<os-release>
See …
> Support to build armhf/arm64 platforms on arm based system

- platform/broadcom/docker-saiserver-brcm/Dockerfile.j2
- platform/broadcom/docker-saiserver-brcm/supervisord.conf
Add dependences in saiserver docker
- install libboost-atomic1.71.0 which is dependent by thrift 0.11
- add gdb                 
- replace the dep install script with a function
- 
deploy it on broadcom device with sonic in version 202012
run saiserver docker and run test from ptf
Thrift only upgraded in 202012 and 202106
> [saiserver docker]adds saiserver dependences

- azure-pipelines.yml
- files/build_templates/sonic_debian_extension.j2
- files/image_config/interfaces/interfaces.j2
- files/image_config/rsyslog/rsyslog-config.sh
- platform/barefoot/docker-syncd-bfn-rpc.mk
- platform/broadcom/docker-pde.mk
- platform/broadcom/docker-saiserver-brcm.mk
- platform/cavium/docker-syncd-cavm-rpc.mk
- platform/cavium/docker-syncd-cavm.mk
- platform/innovium/docker-syncd-invm-rpc.mk
- platform/marvell-arm64/docker-saiserver-mrvl.mk
- platform/marvell-arm64/docker-syncd-mrvl-rpc.mk
- platform/marvell-armhf/docker-saiserver-mrvl.mk
- platform/marvell-armhf/docker-syncd-mrvl-rpc.mk
- platform/marvell/docker-syncd-mrvl-rpc.mk
- platform/mellanox/docker-saiserver-mlnx.mk
- platform/nephos/docker-syncd-nephos-rpc.mk
- platform/template/docker-gbsyncd-base.mk
- rules/ifupdown2.mk
- slave.mk
- sonic-slave-bullseye/Dockerfile.j2
- src/ifupdown2/Makefile
- src/ifupdown2/patch/0001-fix-broadcast-addr-encoding.patch
- src/ifupdown2/patch/series
- src/sonic-config-engine/tests/sample_output/py2/interfaces
- src/sonic-config-engine/tests/sample_output/py2/mvrf_interfaces
- src/sonic-config-engine/tests/sample_output/py3/interfaces
- src/sonic-config-engine/tests/sample_output/py3/mvrf_interfaces
- src/tacacs/nss/patch/0009-fix-compile-error-strncpy.patch
- src/tacacs/nss/patch/series
These changes are in preparation for upgrading the base OS to Bullseye.
1. Upgrade ifupdown2 from 1.2.8 to 3.0.0 (the latest version). Add a patch to fix handling broadcast addresses.
2. Remove `--net=host` from the `RUN_OPT` of other docker containers. This is now handled by `files/build_templates/docker_image_ctl.j2`. Specifying this twice in a `docker run` command will be considered an error starting from Docker 20.10.
3. For tacplus, fix a code issue that gets detected with GCC 10 related to `strncpy` not guaranteeing that the destination buffer will have a null byte.
4. Update the Bullseye slave image with some changes needed there.
5. For deb package builds that are done directly from `slave.mk`, do a clean after building it, to remove generated and compiled files. This will be …
> Upgrade ifupdown2, and clean up some code 

- files/scripts/arp_update
Fix #7968 
Issue is detected on `SONiC.20201231.11`
In `test_static_route.py::test_static_route_ecmp` static routes are configured, but neighbors are not resolved after config reload even after 10 minutes.
It looks like the `arp_update` script is starting to ping when Vlan1000 is not fully configured.
When issue is reproduced, stuck ping6 process is observed in swss container :
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         180  0.1  0.0   6296  1272 pts/0    S    17:03   0:03 ping6 -I Vlan1000 -n -q -i 0 -c 1 -W 0 ff02::1
```
And when arp_update script successfully resolves neighbors, we observe `sleep 300` instead of ping process 
Add sleep to be sure that all interfaces in up state and can be reachable by ping command
Run it manually with -x …
> [202012] Fix arp_update script

- src/sonic-frr-mgmt-framework/templates/bgpd/bgpd.conf.db.route_map.j2
This change makes the template match PREFIX_SET and the documentation.
Fix #6943.
Signed-off-by: Christian Svensson <blue@cmd.nu>
See #6943.
I updated the cases in the template as suggested in https://github.com/Azure/sonic-buildimage/issues/6943#issuecomment-789884878.
Apply the patch and follow the repro in #6943.
Why: This is a breaking issue for a quite critical feature in BGP outside datacenter use.
frr: Fix mode case for prefix lists.
> Fix constant casing for prefix-list mode

- device/nokia/armhf-nokia_ixs7215_52x-r0/plugins/sfputil.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/component.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
Deliver sfputil support for sfputil show eeprom and sfputil reset along with some component test case fixes 
Run sonic-mgmt test_component.py and test_sfputil.py test cases
> [Nokia ixs7215] sfputil support + component tests

- files/Aboot/boot0.j2
- files/initramfs-tools/union-mount.j2
Master/202012 image size grew quite a bit. 3.7G harddrive can no longer hold one image and safely upgrade to another image. Every bit of harddrive space is precious to save now.
Also sh syntax seemingly changed, [ condition ] && action was a legit syntax in 201911 branch but it is an error when condition not met with 202012 or later images. Change the syntax to if statement to avoid the issue.
> [aboot] use ram partition for /var/log for devices with 3.7G disks

- files/build/versions/default/versions-web
Barefoot pipeline is broken, because version has not been update by ci build yet.
Manually replaced version for bfn packages to fix pipeline, until ci build not updated the version.
> Fix bfn version

- platform/broadcom/saibcm-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c
This is to address the issue (https://github.com/Azure/sonic-buildimage/issues/8404)
The original fix which was introduced by (https://github.com/Azure/sonic-buildimage/pull/3895) was removed when onboarding BRCM SAI 4.3  (https://github.com/Azure/sonic-buildimage/pull/6526).  
At that time this change was removed because there was another way to set the port default MTU to 9100 which caused this change being removed.  It was most likely not anticipated that user may need to change the port MTU via CLI at which time this fix when not present will cause portmrgd to crash.
I have create a Case with BRCM (CS00012203989) to ask them to look into this issue to either take this change in and include it to all their future SAI releases and patch their current SAI releases or provide a better …
> Reapply the fix to address set MTU > 1500 causing portmgrd crash on BRCM platforms

- device/accton/x86_64-accton_as4630_54pe-r0/plugins/sfputil.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/modules/x86-64-accton-as4630-54pe-cpld.c
Add QSFP  reset and lpmode sysfs
Add QSFP  reset and lpmode sysfs
Test and check lpmode and reset sysfs work well.
> [AS4630-54PE] Add QSFP reset and lpmode sysfs

- src/sonic-frr/Makefile
This is useful to avoid "branch exists" error while rebuild FRR.
Signed-off-by: Praveen Chaudhary<pchaudhary@linkedin.com>
If branch exist already, today FRR build fails. Branch may exist on rebuild.
With this PR,  we will Checkout branch gracefully if branch exists already.
Use git checkout $(FRR_BRANCH) || git checkout -b $(FRR_BRANCH) origin/$(FRR_BRANCH) in src/sonic-frr/Makefile.
Rebuild works fine. Fresh build works fine as well.
> [sonic-frr/Makefile]: Checkout gracefully if branch exists already.

- files/build_templates/docker_image_ctl.j2
Use a predefined variable to get vendor information when the swss docker container is created
Use `{{ sonic_asic_platform }}` instead of `$SONIC_CFGGEN -y /etc/sonic/sonic_version.yml -v asic_type`
Manually test.
> [docker-swss] Use predefined variable to get vendor information

- src/sonic-host-services/scripts/caclmgrd
caclmgrd: monitor mux_cable_table in state_db to update dhcp acl
- if the state changes to 'standby', add acl to block dhcp packets based on ingress interfaces
- if the state changes to 'active', delete acl
- if the state changes to 'unknown', also delete acl to avoid potential disconnect
- both addition and deletion follow checking the existence of the rules
The change has been verified on a virtual switch based testbed.
Port to 202012 branch from https://github.com/Azure/sonic-buildimage/pull/8222
> caclmgrd: monitor state_db to update dhcp acl

- device/celestica/x86_64-cel_seastone_2-r0/Seastone_2/port_config.ini
- device/celestica/x86_64-cel_seastone_2-r0/Seastone_2/td3-seastone_2-32x100G.config.bcm
The SFP1 port was disabled in the default configuration.
This commit enables the 10G front port for usage.
This was done using a DX030 together with an Arista switch using `bcmsh` and `phy diag xe0 dsc` to figure out what lane mappings make sense.
Validated on Celestica Seastone2 DX030.
1. Own a Celestica DX030
2. Connect the front SFP1 port to something.
3. It works :-)
You can do `tcpdump -i Ethernet128 -n` and you will see both incoming and outgoing LLDP.
Reason: If 202106 is still open for these additions it would be nice for it to be in.
If not, master is fine as well.
[Celestica Seastone2] Add SFP1 front port
> [Celestica Seastone2] Add 10G SFP1 front port

- src/sonic-config-engine/sonic-cfggen
during fresh install and start of sonic in multi asic, /var/run/redisX/ is created after database docker is
started. Currently sonic-cfggen is throwing exception while reading platform string from /usr/bin/database.sh
sonic python3[2259]: :- parseDatabaseConfig: Sonic database config file doesn't exist at /var/run/redis/sonic-db/../../redis0/sonic-db/database_config.json
sonic python3[2259]: :- initializeGlobalConfig: Sonic database config file syntax error >> Sonic database config file doesn't exist at /var/run/redis/sonic-db/../../redis0/sonic-db/database_config.json
sonic database.sh[2259]: Traceback (most recent call last):
sonic database.sh[2259]:   File "/usr/local/bin/sonic-cfggen", line 452, in <module>
sonic database.sh[2259]:     main()
sonic database.sh[2259]:   File …
> [multi-asic] Fix for sonic-cfggen exception during platform string read

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_serial_getty_monitor
serial-getty service exited in Dell S6100 device randomly.
Added serial-getty to monit services.
Stop serial-getty in ssh session and check whether the service restarts or not
UT:
[201911_UT.txt](https://github.com/Azure/sonic-buildimage/files/6960402/201911_UT.txt)
> [201911] Dell S6100:Add serial-getty service to monit

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_serial_getty_monitor
serial-getty service exited in Dell S6100 device randomly.
Added serial-getty to monit services.
Stop serial-getty in ssh session and check whether the service restarts or not.
UT: 
[console_UT.txt](https://github.com/Azure/sonic-buildimage/files/6960074/console_UT.txt)
> [201811] Dell S6100:Add serial-getty service to monit

- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
Fix for open community test test_sfp.py test_get_name 
Account for sfputil_helper indexing being 0 based 
Run sonic-mgmt test_sfp.py test cases
> [Nokia ixs7215] sfp get_name test case fix

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
DHCP is rather generic and can be used for DHCP servers/other options in future.
Changed corresponding name in minigraph to Dhcprelay and changed "DHCP" table name to "DHCP_RELAY" in config.
'DHCP_RELAY': {
'Vlan1000': {
'dhcpv6_servers': [
'fc02:2000::1',
'fc02:2000::2'
],
'dhcpv6_option|rfc6939_support': 'true'
},
'Vlan2000': {
'dhcpv6_servers': [
'fc02:2000::3',
'fc02:2000::4'
],
'dhcpv6_option|rfc6939_support': 'false'
}
}
> Changed DHCP table name to DHCP_RELAY

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/port_config.ini
This change introduce 3 columns in the port_config.ini file.
These are coreId, corePortId and numVoq.
The ports for inband and recirc were also renamed properly.
This change is desired on 202106 for chassis support
Fix port_config.ini for Clearwater2
> [Arista] Add VOQ information for Clearwater2

- src/ifupdown2/patch/0002-disable-checks-when-using-no-wait.patch
- src/ifupdown2/patch/series
Add a patch in ifupdown2 such that if DHCP is used for an interface, and
the policy setting sets dhcp-wait to no (meaning don't wait for dhclient
to acquire an IP address), then don't check to see if the interface has
a new IP address, since dhclient will still be working.
Fixes #8512.
SONiC ZTP (zero-touch provisioning) needs `dhcp-wait` to be set to `no` for ifupdown2, so that it won't wait for dhclient to get an address before moving on to the next interface. Since setting that policy then causes a failure (because of checks that ifupdown2 does to see if dhclient succeeded), add a patch to have it not check and see if dhclient succeeded or not.
Within a KVM image:
1. Log into console.
2. Bring down eth0 using `sudo ifdown eth0`.
3. …
> ifupdown2: Don't check for new IP addresses if dhcp-wait is set to no

- platform/components/docker-gbsyncd-credo.mk
The credo driver packages provides firmware, sai sdk for gearbox (external PHY) in Arista 7280.
> [gearbox] Add credo driver packages

- .gitmodules
- src/sonic-config-engine/portconfig.py
- src/sonic-config-engine/sonic-cfggen
- src/sonic-config-engine/tests/test_cfggen_platformJson.py
Signed-off-by: liora <liora@nvidia.com>
Allow cfggen to work on system without ports in platform.json or in port_config.ini
Add json write of PORT section only if the dictionary that contains the ports is not empty.  
sonic-cfggen -k ACS-MSN3700 -H -j /etc/sonic/init_cfg.json --print-data
> [sonic-cfggen] Allow cfggen to work on system without ports

- files/image_config/copp/copp_cfg.j2
This change enables the control packets of MACsec to be processed by CPU.
> [macsec] Add eapol to copp config

- dockers/docker-sonic-mgmt-framework/mgmt_vars.j2
The issue was discussed [on the mailing list](https://groups.google.com/g/sonicproject/c/l_XADXY2Mqs) and should be pretty obvious.
The issue:
```
Aug 13 23:12:29.901117 adele WARNING mgmt-framework#python3: :- operator(): Key 'JINJA2_CACHE' field 'f773745d995b9beba2b87a460e6956e2f0c03c1b' unavailable in database 'LOGLEVEL_DB'
Aug 13 23:12:29.922928 adele INFO mgmt-framework#/supervisord: rest-server Traceback (most recent call last):
Aug 13 23:12:29.922928 adele INFO mgmt-framework#/supervisord: rest-server   File "/usr/local/bin/sonic-cfggen", line 431, in <module>
Aug 13 23:12:29.922928 adele INFO mgmt-framework#/supervisord: rest-server     main()
Aug 13 23:12:29.922928 adele INFO mgmt-framework#/supervisord: rest-server   File "/usr/local/bin/sonic-cfggen", line 396, in main
Aug 13 …
```
> Fix REST_SERVER typo in mgmt_vars.j2

- dockers/docker-dhcp-relay/cli-plugin-tests/test_config_dhcp_relay.py
- dockers/docker-dhcp-relay/cli-plugin-tests/test_show_dhcp_relay.py
- dockers/docker-dhcp-relay/cli/config/plugins/dhcp_relay.py
- dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py
- Adapt config/show CLI commands to support DHCPv6 relay
- Support multiple dhcp servers assignment in one command
- Fix IP validation
- Adapt UT and add new UT cases
- Modify config/show dhcp relay files
- Modify config/show UT files
This PR has a dependency on PR https://github.com/Azure/sonic-utilities/pull/1717
Build an image with the dependent PR and this PR
Use config/show DHCPv6 relay commands.
> [dhcp_relay] Adapt config/show CLI commands to support DHCPv6 relay

- files/Aboot/boot0.j2
The Lodoga platform also matched crow which was hardcoding the flash
size to 3700. 
By removing the 3700 hardcoding on crow, this change enables autodetect on Clearlake
which in turns allows autodetect for Lodoga.
The threshold was also bumped from 3700 to 4000 because size computation can
differ slightly and report slightly above 3700.
Verify that `docker_inram` is no longer set on `/proc/cmdline`
Fix flash size computation in boot0 for Lodoga
> [Arista] Fix flash size computation for Lodoga

- device/arista/x86_64-arista_7800_sup/chassisdb.conf
Configure LAG Id range in chassisdb.conf for 7800 chassis.
> [Arista]: Set LAG Id range for 7800 chassis

- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/th3-z9332f-32x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-16x400G-64x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm
LED errors were seen in DELLEMC Z9332f during bootup(https://github.com/Azure/sonic-buildimage/issues/8620). 
Initialized led_fw_path variable
Verified the led status and the color displayed on the switch.
> DellEMC: Z9332f fix LED issue

- device/arista/x86_64-arista_7050_qx32s/Arista-7050QX-32S-S4Q31/hwsku.json
The first 4 ports on this dut are breakout ports. They might not always be connected in lab. Mark them as 'RJ45' to skip the SFP check since they are by default disabled.
run platform test_reboot.py
> [7050] define hwsku.json for Arista-7050QX-32S-S4Q31 to skip SFP checks for first 4 ports

- src/sonic-yang-models/yang-models/sonic-nat.yang
Fixing issue [[sonic-utilities] Unit test failed when building sonic-utilities #1761](https://github.com/Azure/sonic-utilities/issues/1761)
Importing `sonic-acl` caused getting references by `backlinks()` to break, 
solution is to comment out the importing statement as it is not used anyway.
Ran sonic-utilities unit-tests locally after the fix, and all passed.
> [yang-models] Removing sonic-acl import from sonic-nat.yang

- dockers/docker-orchagent/enable_counters.py
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Reset flex counters delay flag on config DB when enable_counters script is called to allow enablement of flex counters in orchagent.
Push to config DB 'false' value for delay indication when enable_counters script is called before enabling the counters.
Observe counters are created when enable_counters script is called.
> [Flex Counters] Reset flex counters delay flag on config DB when enable_counters script is called

- src/sonic-yang-models/tests/yang_model_tests/tests/crm.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/crm.json
- src/sonic-yang-models/yang-models/sonic-crm.yang
- src/sonic-yang-models/yang-models/sonic-interface.yang
- src/sonic-yang-models/yang-models/sonic-portchannel.yang
- src/sonic-yang-models/yang-models/sonic-vlan.yang
What I did
SONiC YANG model support in buildimage for MPLS:
1) sonic-yang-model support for MPLS enable/disable
2) sonic-yang-model support for MPLS CRM thresholds
Why I did it
SONiC yang-models support for MPLS
How I verified it
Unit-tests in sonic-swss/tests/test_mpls.py and sonic-utilities/tests
System tests in sonic-mgmt
Details if related
Refer to MPLS HLD https://github.com/Azure/SONiC/pull/706
> sonic-yang-models updates for MPLS

- platform/broadcom/sai.mk
Fix https://github.com/Azure/sonic-buildimage/issues/8300
Catch up on fixes from BRCM SUG repo to pick up fixes after 5.0.0.6 all the way up to 5.0.0.8
Fixes include the following:
```
CS00012201827: Warmreboot causes syncd crash with  SAI_API_UNSPECIFIED:syncdb_data_file_read:2230 Failed to parse JSON: error -2
DNX: Fix for ACL table create with v6 next hdr attr
and many unspecified changes that also went into 5.0.0.8
```
Preliminary tests looks fine on both XGS (gechiang) and DNX (judyjoseph)
On XGS testing done as following:
BGP neighbors were all up with proper routes programmed
interfaces are all up
Manually ran the following test cases on 7260CX3 T0 DUT and all passed:
```
ipfwd/test_dir_bcast.py
vlan/test_valn.py
```
Also validated for for …
> BRCM SAI 5.0.0.8 Catch up fixes since 5.0.0.6

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
Power cycle test case fails for Z9332f in sonic-mgmt framework(https://github.com/Azure/sonic-buildimage/issues/8605).
Modified the platform API to return expected strings.
1. Power cycle the device and verify the reboot reason.
2. Run sonic-mgmt test_reboot script.
UT logs: 
[UT logs.txt](https://github.com/Azure/sonic-buildimage/files/7083552/UT.logs.txt)
> DellEMC: Z9332f fix reboot cause issue

- platform/vs/docker-sonic-vs/start.sh
- src/sonic-device-data/Makefile
- src/sonic-device-data/src/sai_mlnx.vs_profile
Updated sai_vs profile based on fake platform provided. Currently vs initializes platform and data structures based on vs profile which is fixed. However, when fake platform env is set , vslib needs to initialize to a different platform.
Created new sai profile for mellanox and when fake_platform is mellanox, this would override the sai.profile file.
Ran test cases with fake_platform and without it confirming it works.
> Enhancing vs support to mock based on platform

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/eeprom.py
To make values returned by 'get_system_eeprom_info' compliant with eeprom_tlvinfo.TlvInfoDecoder. 
Fixes #8573 
Use eeprom_tlvinfo.TlvInfoDecoder's decoder method for all TLVs.
Verify that `platform_tests/cli/test_show_platform.py::test_show_platform_syseeprom` reports Success.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7135694/UT_logs.txt)
DellEMC Z9332f: Platform API - Remove EEPROM Vendor Extension decoder
> DellEMC Z9332f: Platform API - Remove EEPROM Vendor Extension decoder

- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/fan.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/fan_drawer.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/psu.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/thermal.py
This commit delivers the following fixes for the Nokia ixs7215 platform
- Fix bug in a fan API error path
- Add support for setting the fan drawer led
- Add support for getting/setting the front panel PSU status led
- Add support for getting the min/max observed temperature value
Fix bugs in various platform APIs
These fixes improve the sonic-mgmt platform API test pass rate
Run the following sonic-mgmt test cases
- test-fan.py
- test-fan-drawer.py
- test-thermal.py
- test-psu.py
> [Nokia ixs7215] Miscellaneous platform API fixes

- dockers/docker-sonic-mgmt-framework/Dockerfile.j2
Fix error during building docker-sonic-mgmt-framework on 201911
Cause:
While building sonic-mgmt-framework docker, it needs to install `grpcio-tools` version 1.20.0 which has a dependency on `grpcio` version >=1.20.0.
As `>=1.20.0` is specified, it will install the latest version of `grpcio`.
It had worked well until the grpcio package version 1.40.0 was released 3 days ago.
Looks like some new dependencies are introduced by the latest version.
Fix:
Designate `grpcio` version 1.39.0 explicitly, which is the latest version of `grpcio` that worked well.
> [201911] Fix error during building docker-sonic-mgmt-framework

- files/build_templates/docker_image_ctl.j2
Recently, the reserved buffer of admin-down ports is going to be reclaimed.
However, the way to do this differs among vendors.
We need to find a way to pass vendor information to swss docker.
Fetch the ASIC vendor information when the docker is created and pass it to the docker as environment variable `ASIC_VENDOR`.
> [docker-orchagent][201911] Pass ASIC vendor information to swss docker as docker level environment variable

- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/hwsku.json
- device/mellanox/x86_64-mlnx_msn3800-r0/platform.json
Removed 2x40G for SN3800. This mode is not supported by hardware.
Removing it from hwsku.json and platform.json
Load it in the device and check supported modes
> [Mellanox] Remove 2x40G from SN3800 hwsku

- files/image_config/fstrim/fstrim.timer
fstrim has dependency on pmon docker.
start fstrim timer after sonic.target.
local test and PR test.
> [fstrim] delay fstrim timer after sonic.target

- dockers/docker-dhcp-relay/base_image_files/monit_dhcp_relay.j2
This PR aims to fix the bug in Monit template file of `dhcp_relay` container. 
If Multi-VLAN were configured on device, multiple `dhcrelay` processes will be spawned in `dhcp_relay` container. Then there will be an entry for each `dhcrelay` process in Monit configuration file of `dhcp_relay` container.
Currently Monit template file of `dhcp_relay` container can not be rendered correctly to generate configuration file and will cause Monit can not start up.
I removed the indentation in the template file and remove the `minus` sign.
I verify this on DuT `str-msn2700-20` which was installed 20191130.78 image.
################################################################################ …
> [201911][Monit] Fix the template file of dhcp_relay

- src/sonic-host-services/scripts/caclmgrd
Fix https://github.com/Azure/sonic-buildimage/issues/8672
- add two missing commits in https://github.com/Azure/sonic-buildimage/pull/8222 when porting to 202012 branch
> Caclmgrd: port two commits from master to 202012 branch

- device/barefoot/x86_64-accton_as9516_32d-r0/platform_components.json
- device/barefoot/x86_64-accton_wedge100bf_32x-r0/platform_components.json
- device/barefoot/x86_64-accton_wedge100bf_65x-r0/platform_components.json
After running command {{ show platform firmware updates}} shows this error:
Error: [Errno 2] No such file or directory: '/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/platform_components.json'. Aborting...
Aborted!
add platform_components.json for BFN
Run show platform firmware updates
> [BFN] Platform FW config files

- src/sonic-py-common/sonic_py_common/device_info.py
- src/sonic-py-common/sonic_py_common/multi_asic.py
Currently, for all the cli commands, we connect to all databases mentioned in the database_config.json. The database_config.json also includes the databases from chassis redis server from supervisor card. It is unnecessary to connect to databases from chassis redis server when cli commands are executed form linecard. But we need to allow connection to chassis databases when the cli commands are executed from supervisor card. This PR fixes this problem
This PR requires that platform_env.conf in supervisor card includes a variable **"supervisor"** with value 1 to identify the supervisor card. The connect_to_all_dbs_for_ns() is changed to skip chassis databases form the list of collected databases if the card is not supervisor card. This PR requires sonic-utilities PR …
> [multi-asic][cli][chassis-db] Avoid connecting to chassis db when cli commands are executed from linecards

- files/build_templates/sonic_debian_extension.j2
What I did:
Logically same as https://github.com/Azure/sonic-buildimage/pull/8743  but for Stretch we did not copied `logrotate.conf` that has `wtmp` and `btmp` log rotate config.
> [201911] Logrotate for wtmp and btmp files to fix size.

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/scripts/hostcfgd
- src/sonic-host-services/scripts/procdockerstatsd
- src/sonic-host-services/scripts/process-reboot-cause
- src/sonic-host-services/setup.py
- src/sonic-host-services/tests/determine-reboot-cause_test.py
- src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
- src/sonic-host-services/tests/procdockerstatsd_test.py
Backport https://github.com/Azure/sonic-buildimage/pull/8034 to 202012 branch
sonic-swss-common submodule updating includes below commits
```
a6b98da 2021-04-29 | Add support for config_db subscribe and unsubscribe python apis (#481) [arlakshm]
2506ca0 2021-08-22 | [ci] Fix azure pipeline DownloadPipelineArtifact source branch (#514) [Qi Luo]
```
> [202012] Replace swsssdk with swsscommon in sonic-host-services and update submodule sonic-swss-common

- device/virtual/x86_64-kvm_x86_64-r0/brcm_gearbox_vs/context_config.json
- platform/vs/docker-sonic-vs/Dockerfile.j2
- platform/vs/docker-sonic-vs/start.sh
- platform/vs/docker-sonic-vs/supervisord.conf
Support gearbox on  docker-sonic-vs
> [gearbox] support gearbox feature on docker-sonic-vs

- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/fan_drawer.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
Fix error seen when running the sonic_mgmt test-sfp.py platform test cases.
This was reported via Issue# 8745
Add dictionary key to support the type_abbrv_name eeprom attribute
Run the sonic-mgmt SFP platform test cases
> [Nokia ixs7215] Add support for SFP eeprom type_abbrv_name attribute

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/fan.py
Fixes #8656 
Update maximum fan speed based on fan type.
Verify `show platform fan` reports fan speed values in percentage.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7169115/UT_logs.txt)
DellEMC Z9332f: Platform API - Update maximum fan speed
> DellEMC Z9332f: Platform API - Update maximum fan speed

- device/nokia/armhf-nokia_ixs7215_52x-r0/system_health_monitoring_config.json
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/chassis.py
Add support for 'show system-health' command
Add required source code and config file
Run the following commands
show system-health summary
show system-health detail
show system-health monitor-list
> [Nokia ixs7215] Support show system-health

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/psu.py
To implement the below platform APIs for DellEMC  Z9332f
- Chassis - get_revision
- FanDrawer - get_maximum_consumed_power
- PSU - get_revision, get_maximum_supplied_power
Implement the platform API methods in the respective device files
Verified that platform data is displayed by `show platform summary` and `show platform psustatus` commands.
[Z9332f_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7185041/Z9332f_UT_logs.txt)
DellEMC: Z9332f - Platform API implementation
> DellEMC: Z9332f - Platform API implementation

- platform/vs/docker-sonic-vs/database_config.json
Since ASIC_DB always use ':', GB_ASIC_DB has to use same,  regarding to same sairedis and syncd logic
> [docker-sonic-vs] always use separator ':' for GB_ASIC_DB, like ASIC_DB

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
This PR is to update minigraph parser  ```minigraph.py``` to support type ```MIRROR_DSCP```.
A new section defined in ```minigraph.xml``` as below will create an ACL table with type ```MIRROR_DSCP```.
```
<AclInterfaces>
<AclInterface>
<AttachTo>ERSPAN_DSCP</AttachTo>
<InAcl>Everflow_dscp</InAcl>
<Type>Everflow_dscp</Type>
</AclInterface>
</AclInterfaces>
```
Update ```minigraph.py``` to support parsing ```EVERFLOW_DSCP``` into config_db.
1. Verified by UT
2. Verified by updating ```minigraph.xml``` and runing ```config load_minigraph``` on device.
Update minigraph parser to support type MIRROR_DSCP
> Update minigraph parser to support type MIRROR_DSCP

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
This PR is to apply PR #8819 into ```201811``` branch. Since it's not a clean cherry-pick, I have to open a new PR.
Please refer to #8819
1. Verified by UT
2. Verified by running on ```20181130.97```.
> [201811][cherry-pick]Update minigraph parser to support MIRROR_DSCP

- files/build_templates/docker_image_ctl.j2
As part of warmboot, redis database is dumped: 
https://github.com/Azure/sonic-utilities/blob/c97fe546e5a725b9049047293a4fede48fde5223/scripts/fast-reboot#L269
However, this dump file is deleted, after it is loaded back into db post reboot.
The DB dump can be useful for debugging purpose, hence taking a backup of it can be useful.
Instead of deleting the dump, rename and keep the dump.
> [master] Save redis DB dump after warm/fast reboot

- .gitignore
- dockers/docker-ptf/Dockerfile.j2
gdb and pyrasite can be used to print the running python process' stack trace.
It's helpful during debugging multi-thread issues
see : https://gist.github.com/reywood/e221c4061bbf2eccea885c9b2e4ef496
install gdb and pyrasite during image build
> Add gdb and pyrasite to ptf image

- .azure-pipelines/official-build-multi-asic.yml
- .azure-pipelines/run-test-template.yml
To be able to run VS test on official multi asic VS image.
Add a new script to build multi-asic VS image by passing NUM_ASIC build parameter.
Rung multi-asic t1-lag test cases with the built image.
> [azure-pipeline][multi-asic]: Add azure pipeline script to generate multi asic vs image

- platform/vs/docker-sonic-vs/database_config.json
Make the ID numbers of "GB_ASIC_DB", "GB_COUNTERS_DB" and "GB_FLEX_COUNTER_DB" same as the ones in swss-common
> [docker-sonic-vs] Correct GB_ASIC_DB id from 8 to 9

- src/sonic-config-engine/minigraph.py
We are currently receiving a lot of logs from REST-API for every API call. This will consume a lot of disk space which is not required.
resolves https://github.com/Azure/sonic-restapi/issues/86
Change the log level for RESTAPI in the `minigraph.py`
The syslogs should not have anymore logs from RESTAPI other than those of `info` level.
> Reduce logging level for RESTAPI

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/t0-sample-graph.xml
NOTE: This is cherry-pick from master to 202012.
https://github.com/Azure/sonic-buildimage/pull/8125
Allow deploying DHCPv6 servers following the implementation PR: #7772
Add DHCPv6 to minigraph.py on sonic-cfggen tool and improve the unit test to cover this change.
Try to deploy a switch with DHCPv6 servers.
> Add DHCPv6 minigraph parsing support

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_minigraph_case.py
This PR is to apply PR #8819 into ```201911``` branch. Since it's not a clean cherry-pick, I have to open a new PR.
Please refer to #8819
1. Verified by UT
2. Verified by running on ```20191130.77```.
> [201911][cherry-pick] Update minigraph parser to support MIRROR_DSCP

- src/sonic-host-services/scripts/caclmgrd
The database_global.json file is generated only in multi asic scenario. However, caclmgrd calls initialization based on this file without multi npu check.
This leads to following error in single asic scenario
Sep 21 22:35:20.996798 r-leopard-32 ERR caclmgrd[11819]: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
Added if multi npu check before invoking the load global config.
Restart caclmgrd after this change and check if no error log is thrown.
> Load global config in caclmgrd only in multi asic NPU

- src/sonic-yang-mgmt/setup.py
- src/sonic-yang-mgmt/sonic_yang.py
- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-mgmt/tests/libyang-python-tests/test_sonic_yang.py
- src/sonic-yang-models/tests/files/sample_config_db.json
[sonic_yang_ext.py]: Support Grouping translation in YANG Models.
Changes:
-- pre Process Grouping section from all yang models, so it can be used
from any yang model.
-- add jsondiff in setup.py, it is useful for test debugging in case of
failures.
-- use 'stypes' instead of head.
-- pass config DB table name in _createLeafDict().
-- added test config for grouping.
-- white spaces changes.
Note: Changes are done in the way that we can add supoort for other
Generic YANG statement easily for tranlation.
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
Need to support Grouping translation in YANG Models.
Changes:
-- pre Process Grouping section from all yang models, so it can be used
from any yang model. File: src/sonic-yang-mgmt/sonic_yang_ext.py
-- add jsondiff in setup.py, it is …
> Support Grouping translation in YANG Models.

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
NOTE: This is cherry-pick from master to 202012.
https://github.com/Azure/sonic-buildimage/pull/8268
https://github.com/Azure/sonic-buildimage/pull/8476
Add the following dhcp_relay table to minigraph
<pre>
'DHCP_RELAY': {
'Vlan1000': {
'dhcpv6_servers': [
'fc02:2000::1',
'fc02:2000::2'
]
},
'Vlan2000': {
'dhcpv6_servers': [
'fc02:2000::3',
'fc02:2000::4'
]
}
}
</pre>
> Parse DHCP_RELAY table

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
Change thermal recover threshold from temp_trip_norm to temp_trip_high, so that thermal algorithm would set fan speed to minimum allowed earlier and save power.
Change thermal recover threshold from temp_trip_norm to temp_trip_high
Manual test
> [Mellanox] Change thermal recover threshold from temp_trip_norm to temp_trip_high

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-C32/td3-a7050cx3-32s-32x100G.config.bcm
- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/td3-a7050cx3-32s-48x50G+8x100G.config.bcm
- src/sonic-device-data/tests/permitted_list
A new config option was added to control the value of IPV4_INCR_CHECKSUM_ORIGINAL_VALUE_VERIFY in the EGR_FLEX_CONFIG control register (this prevents checksums of 0xffff from being propagated to other devices)
> [device]: Add SAI checksum verify to TD3 config

- platform/broadcom/sonic-platform-modules-dell/s6000/scripts/s6000_platform.sh
PCIe Gen1 settings was needed for Dell S6000 device.
Modified from Gen2 to Gen 1 speed for Dell S6000 PCIe devices 
Check lspci output, verify the syslogs
UT: 
[pcie_UT_s6000.txt](https://github.com/Azure/sonic-buildimage/files/7096879/pcie_UT_s6000.txt)
> Dell S6000: PCIe Gen1 settings

- .azure-pipelines/azure-pipelines-image-template.yml
- .azure-pipelines/official-build-cisco-8000.yml
Setup Azure pipeline for cisco 8000.
Merge the code to the following repo, and setup azp for the repo.
https://github.com/Cisco-8000-sonic/sonic-buildimage
> [ci]: Support azp for cisco 8000

- sonic-slave/Dockerfile
201811 branch image build has been failing due to the certificate expiring: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021. This issue so far only affect Jessie docker because it is using openssl 1.0.
Remove the expired cert and refresh the certs bundle.
Build image.
> [201811][jessie] address Jessie docker cert expiry issue

- platform/broadcom/sai.mk
- Pick up Broadcom patches for CS00011222060 and CS00012204923.
> [201811][sai bcm] upgrade Broadcom SAI to version 3.5.3.7-6

- src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py
- src/sonic-bgpcfgd/tests/test_static_rt.py
- src/sonic-frr-mgmt-framework/frrcfgd/frrcfgd.py
To add portchannel support in frrcfgd and bgpcfgd.
fix Azure/sonic-buildimage#8907
Added handling of the portchannel name as an IP address by adding check in is_zero_ip() to prevent parsing portchannel name with socket.inet_pton().
```
config portchannel add PortChannel0001
config portchannel add PortChannel0002
sudo config route add prefix 20.0.0.1/32 nexthop PortChannel0001
sudo config route add prefix 20.0.0.1/32 nexthop PortChannel0002
```
```
admin@sonic:~$ show ip route
Codes: K - kernel route, C - connected, S - static, R - RIP,
O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
F - PBR, f - OpenFabric,
> - selected route, * - FIB route, q - queued, r - rejected, b - backup
S>* 0.0.0.0/0 [200/0] via 192.168.111.3, eth0, …
```
> [frrcfgd][bgpcfgd] Add portchannel support

- src/sonic-host-services-data/debian/sonic-host-services-data.determine-reboot-cause.service
Since database.service has been moved to execute after rc-local.service,
and determine-reboot-cause.service rely on database.service, we have to
specify that in "After=".
Signed-off-by: Xichen Lin <xichenlin@microsoft.com>
Fixes #8934, "show reboot-cause" always show "Unknown".
Delay execution of determine-reboot-cause, which produces result for "show reboot-cause"
.
Test it on dut.
Include database.service in After and Required for determine-reboot-cause.service.
> [determine-reboot-cause] delay execution

- src/redis-dump-load.patch/0003-use-redis-3.5.3.patch
- src/redis-dump-load.patch/series
Redis 4.0.0b1 has been uploaded to pip as a prerelease version. This
version drops support for Python 2 and only supports Python 3. Because
setup.py is being run, it will use the latest version of a package and
not the latest stable version (which is still 3.5.3).
Therefore, pin the redis package to version 3.5.3, so that it will work
for both Python 2 and 3.
Make sure that redis-dump-load for Python 2 builds today.
> redis-dump-load: Pin the redis package to use 3.5.3

- device/dell/x86_64-dell_s6000_s1220-r0/plugins/sfputil.py
- platform/broadcom/sonic-platform-modules-dell/s6000/modules/dell_s6000_platform.c
- platform/broadcom/sonic-platform-modules-dell/s6000/scripts/s6000_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/sfp.py
- "sfputil show eeprom" and "sfpshow eeprom" commands displays inconsistency results for certain optics.
- For every execution of the commands, various results are displayed.
- Only certain optics EEPROM contents were not retrieved.
On branch Master
Your branch is up to date with 'origin/Master'.
(use "git restore --staged <file>..." to unstage)
modified:   device/dell/x86_64-dell_s6000_s1220-r0/plugins/sfputil.py
modified:   platform/broadcom/sonic-platform-modules-dell/s6000/modules/dell_s6000_platform.c
modified:   platform/broadcom/sonic-platform-modules-dell/s6000/scripts/s6000_platform.sh
modified:   platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/sfp.py
- Just execute "sfputil show eeprom" and "sfpshow eeprom" commands.
> [Dell] S6000 I2C not responding to certain optics

- dockers/docker-dhcp-relay/start.sh
- dockers/docker-dhcp-relay/wait_for_intf.sh.j2
- src/sonic-config-engine/tests/sample_output/py2/wait_for_intf.sh
- src/sonic-config-engine/tests/sample_output/py3/wait_for_intf.sh
Fix the check used to wait for interfaces to come up. The group name in
the supervisor config files has changed from isc-dhcp-relay to
dhcp-relay.
Also, in the wait script, wait 10 additional seconds after the vlans,
port channels, and any interfaces are up. This is because dhcrelay
listens on all interfaces (in addition to port channels and vlans), and
to ensure that it stays in a clean state during runtime, wait some extra
time to make sure that those interfaces are created as well.
In the output of `sudo ss -nlp`, for `dhcrelay` and `dhcp6relay`, verify that all of the sockets that are bound to an interface have a valid interface name, and not some interface index number (e.g. `if512`, `if4294967295`, ...).
Example of sockets bound …
> docker-dhcp-relay: Fix waiting for interfaces to get set up

- src/sonic-device-data/tests/platform_asic_checker
It is required by stretch/sonic-device-data_1.0-1_all.deb, which is required by docker-sonic-mgmt.gz.
Stretch distribution has old Python 3.5.3.
scandir.close() is new in Python version 3.6.
ref: https://docs.python.org/3/library/os.html#os.scandir.close
> Fix platform_asic_checker script in order to run stretch Python 3.5.3

- src/bash/Makefile
This pull request will fix bash build break issue when re-build bash.
src/bash project using quilt to manage patches, and quilt can't apply patch correctly when cache folder '.pc' is not clean.
Add command in make file to remove quilt cache folder before apply patches.
Re-build bash target target/debs/buster/bash_5.1-2_amd64.deb to validate this fix work.
Pass all UT.
N/A
Fix bash build break issue when re-build bash.
> [Bash] Fix bash build break when re-build bash issue.

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/sonic_platform/utils.py
- platform/mellanox/mlnx-platform-api/sonic_platform/vpd_parser.py
This is for 202106 only as there is a big PR https://github.com/Azure/sonic-buildimage/pull/8422 in master which might not be cherry-picked to 202106.
Fix issue:
1. If PSU is missing, error log is printed like "Fail to read PSU1 serial number: No key SN_VPD_FIELD in VPD /var/run/hw-management/eeprom/psu1_vpd"
2. If PSU is replacing by a new one, the model/serial/revision info cannot be updated without a reboot/config reload.
1. If VPD file does not exist, don't print error log
2. Update model/serial/revision info if VPD file is modified
Manual test
> [Mellanox] [202106] Fix issue: PSU model/serial/revision info should be updated after replacing PSU

- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/sai_3800_112x50g_8x100g.xml
Wrong SKU configuration will lead to longer init flow.
This will affect fast-reboot feature by increasing the traffic downtime.
Since MLNX met the required downtime period with this SKU this bug found with a delay.
Add the required split labels for ports.
Run fast-reboot with this platform using SN3800-D112C8 SKU.
> [Mellanox] Fix split configuration for Mellanox SN3800-D112C8 SKU SAI profile for fast-reboot performance

- platform/vs/docker-sonic-vs/Dockerfile.j2
- platform/vs/docker-sonic-vs/orchagent.sh
- platform/vs/docker-sonic-vs/start.sh
Added support for Mellanox-SN2700 based SKU for docker-sonic-vs and to differentiate platform based on hw-sku rather than on fake_platform in VS.
Currently SAI VS library uses hwsku based SAI profile to differentiate and mock different platform implementations. The same functionality in swss is achieved using a fake_platform env variable.
Using a fake_platform has some drawbacks that the vs container appears to still use a different vendor hw-sku
```
env
PLATFORM=x86_64-kvm_x86_64-r0
HOSTNAME=dd21a1637723
PWD=/
HOME=/root
TERM=xterm
HWSKU=Force10-S6000
SHLVL=1
fake_platform=mellanox
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBIAN_FRONTEND=noninteractive
_=/usr/bin/env
```
In order to unify the …
> [docker-sonic-vs]Added support for Mellanox-SN2700 based SKU for docker-sonic-vs

- src/dhcp6relay/src/relay.cpp
Not all relay forward packets are sent to desired dhcpv6_servers.
Sendto error: invalid destination address
Memory gets deallocated at end of loop_relay, need to allocate object on the heap.
Build dhcp6relay debian package and run dhcpv6 relay tests
Signed off by: Kelly Yeh kellyyeh@microsoft.com
> [201811][dhcp_relay] Fix sendto: invalid destination address error

- src/dhcp6relay/src/relay.cpp
Not all relay forward packets are sent to desired dhcpv6_servers.
Sendto error: invalid destination address
Memory gets deallocated at end of loop_relay, need to allocate object on the heap.
Build dhcp6relay debian package and run dhcpv6 relay tests
> [dhcp_relay] Fix sendto: invalid destination address error

- files/scripts/mark_dhcp_packet.py
- update DHCP_PACKET_MARK schema in state_db
- this is an update over https://github.com/Azure/sonic-buildimage/pull/9015
Example output of DHCP_PACKET_MARK table in state_db:
> Update DHCP_PACKET_MARK schema in state_db

- dockers/docker-orchagent/ndppd.conf
During swss container startup, if ndppd starts up before/with vlanmgrd, ndppd will be pinned at nearly 100% CPU usage.
Only start ndppd after vlanmgrd is running. Also, call ndppd directly instead of through bash for improved logging and to prevent orphaned processes.
> [swss]: Start ndppd after vlanmgrd

- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_asic
The  Nokia  IXR7250E supervisor card asic_type should be broadcom-dnx instead of broadcom. Fixes #9140
Changed the "broadcom" to "broadcom-dnx" in the device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_asic file
Edit the file device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_asic on platform to verify it
> [Nokia][supervisor]Fixed the asic_type for Nokia IXR7250E supervisor card

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
To implement SFP API get_error_description for DellEMC Z9332f.
Implement the API in sfp.py
Verified that the return type is as expected. 
UT logs: [Z9332f_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7417380/Z9332f_UT_logs.txt)
DellEMC: Z9332f - SFP API get_error_description implementation
> DellEMC: Z9332f - SFP API get_error_description implementation

- platform/vs/docker-sonic-vs/orchagent.sh
- platform/vs/docker-sonic-vs/start.sh
… used
Removing fake_platform environment variable. Following the merge of https://github.com/Azure/sonic-buildimage/pull/9044 and https://github.com/Azure/sonic-swss/pull/1978 the fake_platform environment variable is not used in any place and removing the stale references.
Cleaned up the places where it is used
Successful execution of vs tests would ensure it is verified.
> [docker-sonic-vs] Removing fake_platform environment variable

- src/sonic-yang-models/yang-models/sonic-types.yang
**What I did**
Allow user to set none value for interface type
Say user has speed=50G, interface_type=CR2, and user wants to change it to 10G and CR. Currently, there is no CLI can support it, because:
1. If you change the interface type to CR first, SAI will get 50G and CR, SAI will report error because not supported
2. If you change the speed to 10G first, SAI will get 10G and CR2, also not supported
The only way for now is to manually change the CONFIG_DB and do a config reload, this is not user friendly.
This PR allow user to set none value to interface type. So there is a way to achieve the goal via CLI:
1. config interface type XXX none
2. config interface speed XXX 10000
3. config interface type XXX CR
**How I verified it**
Manual test
**Details if related**
> [Yang model] Allow user to set none value for interface type

- .azure-pipelines/docker-sonic-slave-arm64.yml
- .azure-pipelines/docker-sonic-slave-armhf.yml
- .azure-pipelines/docker-sonic-slave-template.yml
setup sonic-slave template and use the template
for amd64, arm64 and armhf sonic-slave
build native docker for armhf and arm64
move sonic-slave to template
run several pipeline.
sonic-slave-buster-arm64
sonic-slave-buster-armhf
https://dev.azure.com/mssonic/build/_build?definitionScope=%5Cbldenv
> [ci]: add native arm64/armhf sonic-slave build pipeline

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
…models
python3 setup.py build
python3 setup.py sdist
> [sonic-yang]: introduce yang template for cvl yang

- src/sonic-host-services/scripts/caclmgrd
- src/sonic-host-services/tests/caclmgrd/caclmgrd_dhcp_test.py
- src/sonic-host-services/tests/caclmgrd/test_dhcp_vectors.py
caclmgrd: support packet mark in DHCP chain
enhance caclmgrd
vs testbed
1) use packet mark if corresponding interfaces have marks in state_db
2) use interface name if corresponding interfaces don't have marks in state-db
3) add unitests
> caclmgrd: support packet mark in DHCP chain

- dockers/docker-orchagent/swssconfig.sh
- files/build_templates/docker_image_ctl.j2
During fast-reboot, delayed serdes programming done after transceiver detection results in additional interface flap and traffic loss exceeding the required 30s (Issue: Azure/sonic-buildimage#9165)
Fix includes: 
1. making a backup of media settings from appdb during fast-reboot (Azure/sonic-utilities#1910)
2. loading this to redis after the switch boots up (this PR). 
3. Configuration of serdes triggered by reading media_settings.json file is skipped (https://github.com/Azure/sonic-platform-daemons/pull/221)
Run advanced_reboot/test_advanced_reboot.py::test_fast_reboot on 9332 or similar platform that use media_settings.json and ensure that
* no additional interface flap is seen during fast-reboot
* TRANSCEIVER_INFO & SERDES objects are populated in state and asic db as expected
``` …
```
> Fix for additional interface flap during fast-reboot on platforms due to delayed serdes programming

- src/dhcp6relay/src/relay.cpp
- src/dhcp6relay/src/relay.h
Fix support for DHCPV6 Relay multi vlan functionality
Bind a socket to each vlan interface's global and link-local address.
Socket binded to global address is used for relaying data from client to server and receiving data from servers.
Socket binded to link-local address is used for relaying data received from server back to the client.
Build a image and run two_vlan dhcpv6 tests.
> [201811] DHCPv6 Relay multivlan functionality support

- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py
xcvrd crashes in Dell S6100 while fetching SFP presence
Used try/except block to fix the crash issue
Check whether presence is detected after fix,Verify xcvrd syslogs.
[S6100_UT.txt](https://github.com/Azure/sonic-buildimage/files/7504409/S6100_UT.txt)
> Dell: S6100 fix xcvrd crash

- files/build_templates/mux.service.j2
Dependency is not required between pmon and mux services
> [mux.service]: Remove pmon dependency

- platform/marvell-armhf/sai.mk
fixes #9172 
Fixed SAI error reported in issue #9172 
Load the syncd SAI debian and validate the changes.
Fixes #9172
> [202012][Marvell] Update armhf SAI to ver 1.7.1-6

- src/sonic-device-data/tests/platform_json_checker
Include validation of chassis dict in platform.json unit test
Based on: https://github.com/Azure/SONiC/pull/768
Update `platform_json_checker` to validate fields in chassis dict.
Verified that the unit test reports success for correct values of existing and capabilities fields  in platform.json
[test] Include chassis fields validation in platform.json unit test
> [test] Include chassis fields validation in platform.json unit test

- dockers/docker-orchagent/enable_counters.py
- files/build_templates/init_cfg.json.j2
- src/sonic-config-engine/config_samples.py
- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/sample_output/py3/l1_intfs.json
- src/sonic-config-engine/tests/sample_output/py3/l2switch.json
- src/sonic-config-engine/tests/sample_output/py3/l2switch_dualtor.json
- src/sonic-config-engine/tests/sample_output/py3/l3_intfs.json
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/pfc.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/pfc.json
- src/sonic-yang-models/yang-models/sonic-pfcwd.yang
To support ACL counters on Flex Counter Infrastructure.
Enable ACL FC in init_cfg and minigraph. Disable when genereting configuration from preset.
Together with depends PRs. Run ACL/Everflow test suite.
DEPENDS ON: Azure/sonic-swss-common#533 Azure/sonic-sairedis#953 Azure/sonic-swss#1943
HLD: Azure/SONiC#857
> [ACL] enable ACL FC when genereting config from minigraph but disable by default

- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
To add ACL FC to the YANG model.
Added to the YANG model and added a UT.
Together with depends PRs. Run ACL/Everflow test suite.
DEPENDS ON: Azure/sonic-swss-common#533 Azure/sonic-sairedis#953 Azure/sonic-swss#1943
HLD: Azure/SONiC#857
> [sonic-yang-models] add ACL flex counter group

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
To fix error message during Chassis initialization in pmon.
Handle the absence of bcmcmd in pmon gracefully.
In pmon, instantiate a Chassis object and verify no error messages are seen.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7513306/UT_logs.txt)
DellEMC: Z9332f - Fix error message during Chassis initialization
> DellEMC: Z9332f - Fix error message during Chassis initialization

- src/tacacs/pam/0010-handle-bad-password-set-by-sshd.patch
- src/tacacs/pam/Makefile
When sshd realizes that this login can't succeed due to internal device state
or configuration, instead of failing right there, it proceeds to prompt for
password, so as the user does not get any clue on where is the failure point.
Yet to ensure that this login does not proceed, sshd replaces user provided password
with a specific pattern of characters matching length of user provided password.
This pattern is "<BS><LF><CR><DEL>INCORRECT", which is bound to fail.
If user provided length is smaller/equal, the substring of pattern is overwritten.
If user provided length is greater, the pattern is repeated until length is exhausted.
But if the PAM-tacacs plugin would send this password to AAA, the user could get
locked out by AAA, for providing incorrect value.
Hence this fix, matches …
> TACACS: Don't send sshd's bad password to AAA

- src/dhcp6relay/src/relay.cpp
- src/dhcp6relay/src/relay.h
Fix support for DHCPV6 Relay multi vlan functionality. Make sure the relayed packet is received at correct interface.
Bind a socket to each vlan interface's global and link-local address.
Socket binded to global address is used for relaying data from client to server and receiving data from servers.
Socket binded to link-local address is used for relaying data received from server back to the client.
Build a image and run two_vlan dhcpv6 tests.
> DHCPv6 Relay multivlan functionality support

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Fixes #9061
Few device types were missing in the DEVICE_METADATA type field
Added missing device types to the device metadata yang
Build sonic_yang_mgmt-1.0-py3-none-any.whl and sonic_yang_models-1.0-py3-none-any.whl successfully
> [yang] Add missing device types to the device_metadata yang

- platform/broadcom/sai.mk
BRCM SAI missed implementing the SAI API "sai_query_stats_capability()" which is causing build issue.
The build issue is impacting PR(s) that need to use this API.
This PR is to stubbed BRCM SAI to add this SAI API and return not implemented so that it will fix build issue that it is causing.
No other functional changes were made.
Add the missing SAI API and default it to return NOT_IMPLEMENTED.
It will be validated by the other PR that is having build dependency on this PR.
[BRCM-SAI] 6.0.0.10-1 Stubbed missing SAI API sai_query_stats_capability() that was causing PR build issue.
> [BRCM-SAI] 6.0.0.10-1 Stubbed missing SAI API sai_query_stats_capability()

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Reverts Azure/sonic-buildimage#9226
> Revert "[yang] Add missing device types to the device_metadata yang"

- device/dell/x86_64-dell_s6000_s1220-r0/platform.json
- device/dell/x86_64-dell_s6100_c2538-r0/platform.json
- device/dell/x86_64-dellemc_z9332f_d1508-r0/platform.json
- device/dell/x86_64-dellemc_z9332f_d1508-r0/system_health_monitoring_config.json
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
To include capabilities fields in platform.json of DellEMC S6000, S6100, Z9332f platforms.
Add the capabilities fields in each platform's respective platform.json. 
Ran sonic-mgmt platform api test cases that use capabilities fields and verified that the results are as expected.
DellEMC: S6000, S6100, Z9332f - Add capabilities fields in platform.json
> DellEMC: S6000, S6100, Z9332f - Add capabilities fields in platform.json

- src/sonic-py-common/sonic_py_common/device_info.py
Add APIs to find if the device is part of chassis, and the type of chassis. 
Also display the chassis type in 'show platform summary --json'
Detect chassis type by checking the 'switch_type' defined in device metadata. 
```
dmin@str2-chassis-lc3-1:~$ show platform summary --json
{
"asic_count": 1,
"asic_type": "broadcom",
"hwsku": "chassis",
"model": "chassis-LC",
"platform": "chassis_lc",
"revision": "N/A",
"serial": "xyz",
"switch_type": "voq"
}
admin@str2-chassis-lc3-1:~$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
>>> import sonic_py_common.device_info as device_info
>>> device_info.is_chassis()
True
>>> device_info.is_packet_chassis()
False
>>> device_info.is_voq_chassis()
True
>>> …
```
> [sonic_py_common][device info] APIs to return chassis type

- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-z9332f.install
some platform script has to be added in DellEMC Z9332f platform.
The script has to be present independently even though API is available and it will be useful for debugging purpose. 
Verified in DellEMC Z9332f platform.
> DellEMC Z9332f: Add platform scripts

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Adding missing YANG model for synchronous mode in DEVICE_METADATA
Add YANG model leaf for synchronous mode and default value
> [YANG] Add YANG model for synchronous mode

- platform/centec-arm64/tsingma-bsp/src/gpio-ctc/gpiolib-acpi.h
gpiolib-acpi.h was missing.
Add gpiolib-acpi.h under tsingma-bsp directory.
make target/debs/bullseye/tsingma-bsp_1.0_arm64.deb
```
make[2]: Entering directory '/usr/src/linux-headers-5.10.0-8-2-arm64'
CC [M]  /sonic/platform/centec-arm64/tsingma-bsp/src/gpio-ctc/gpio-ctc.o
MODPOST /sonic/platform/centec-arm64/tsingma-bsp/src/gpio-ctc/Module.symvers
CC [M]  /sonic/platform/centec-arm64/tsingma-bsp/src/gpio-ctc/gpio-ctc.mod.o
LD [M]  /sonic/platform/centec-arm64/tsingma-bsp/src/gpio-ctc/gpio-ctc.ko
make[2]: Leaving directory '/usr/src/linux-headers-5.10.0-8-2-arm64'
```
> [centec][arm64] fix compile problem for tsingma-bsp

- src/sonic-config-engine/tests/test_cfggen.py
add option to print verbose debug info in unit tests
tested locally.
> [config-engine]: add option to print verbose debug info in unit tests

- dockers/docker-dhcp-relay/dhcp-relay.programs.j2
- dockers/docker-dhcp-relay/dhcpv4-relay.agents.j2
- dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
- dockers/docker-dhcp-relay/dhcpv6-relay.monitors.j2
- dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
- src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay.supervisord.conf
- src/sonic-config-engine/tests/sample_output/py3/docker-dhcp-relay.supervisord.conf
If multiple Vlans are configured to have DHCPv6 relay, only one relay instance is able to capture DHCP packets received from upstream, this is as a result of kernel design to operate this way (SO_REUSEPORT).
DHCPv6 transmit unicast packets to clients, only multicast packets can be captured on multiple application listening on the same UDP port.
This issue causing only one Vlan interface to get packets from servers.
Change the design to neglect Vlan isolation and run only one relay instance serving all Vlans with all configured DHCP servers.
Run DHCPv6 relay test with 2 Vlans configured do have a DHCP relay.
> [DHCPv6 relay] [202106] Fix DHCPv6 design to support multiple VLANS

- device/barefoot/x86_64-accton_as9516_32d-r0/newport/hwsku.json
- device/barefoot/x86_64-accton_as9516_32d-r0/platform.json
Signed-off-by: Mykola Gerasymenko <mykolax.gerasymenko@intel.com>
To support dynamic port breakout configurations on Newport platforms.
Add platform.json and hwsku.json for dynamic port breakout usage.
Manually tested DPB CLI on Newport platform with all modes.
> [barefoot] add platform.json and hwsku.json for Newport

- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
The recent release of redis 4.0.0 or newer (for python3) breaks sonic-config-engine unit test. Fix to last known good version.
ref: https://pypi.org/project/redis/#history
> Fix redis version during pip3 install

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_cfggen.py
- src/sonic-config-engine/tests/test_minigraph_case.py
This field is deprecated.
Fixes https://github.com/Azure/sonic-buildimage/issues/8306
Fixes https://github.com/Azure/sonic-buildimage/issues/9121
> [minigraph] No longer generate the “members” field on the VLAN table in ConfigDB

- src/tacacs/pam/0007-handle-bad-password-set-by-sshd.patch
- src/tacacs/pam/Makefile
[cherry-pick PR #9123 ]
When sshd realizes that this login can't succeed due to internal device state
or configuration, instead of failing right there, it proceeds to prompt for
password, so as the user does not get any clue on where is the failure point.
Yet to ensure that this login does not proceed, sshd replaces user provided password
with a specific pattern of characters matching length of user provided password.
This pattern is `"<BS><LF><CR><DEL>INCORRECT`", which is bound to fail.
If user provided length is smaller/equal, the substring of pattern is overwritten.
If user provided length is greater, the pattern is repeated until length is exhausted.
But if the PAM-tacacs plugin would send this password to AAA, the user could get
locked out by AAA, for providing incorrect value. …
> TACACS: Don't send sshd's bad password to AAA 

- src/sonic-yang-mgmt/tests/libyang-python-tests/test_sonic_yang.py
- src/sonic-yang-models/setup.py
**Description**
Previously the Yang model unit tests pulled directly from the Yang model source code for their models. This worked up to a point where we had jinja templates which needed to be rendered before they could be tested on. Now we need to reference the install location of the rendered templates for the unit tests.
Additionally, PBH yang was never added to the list of models to install onto a switch so I have resolved that (another example why pulling directly from the source was not correct)
My best explanation for why we only saw this failing on mellanox was that these tests could not have possibly been running on the broadcom build (I have not investigated this specifically). There was no way for these tests to pass recently given they were referencing Yang models which did …
> [yang] fix yang model tests to run on installed models

- sonic-slave-bullseye/Dockerfile.j2
[arm64][qemu] upgrade qemu for fix systemd-sonic-generator compile error
for compile error when build systemd-sonic-generator_1.0.0_arm64.deb on qemu arm64 bullseye.
```
boost::filesystem::copy_file: Function not implemented: "tests/testfiles/single_inst.service", "tests/ssg-test/systemd/single_inst.service"
boost::filesystem::copy_file: Function not implemented: "tests/testfiles/multi_inst_b.service", "tests/ssg-test/systemd/multi_inst_b.service"
boost::filesystem::copy_file: Function not implemented: "tests/testfiles/multi_inst_a.service", "tests/ssg-test/systemd/multi_inst_a.service"
boost::filesystem::copy_file: Function not implemented: "tests/testfiles/multi_inst_b@.service", "tests/ssg-test/systemd/multi_inst_b@.service"
boost::filesystem::copy_file: Function not implemented: …
```
> [arm64][qemu] upgrade qemu for fix systemd-sonic-generator compile error

- azure-pipelines.yml
Extend timeout for kvm-t0 test from 300 minutes to 360 minutes
Recently a lot of PRs didn't pass azure pipeline kvm v0 test due to timeout
A dry run was run for one of the failing PRs and passed.
> [CI] Extend timeout for kvm-t0 test from 300 minutes to 360 minutes

- platform/centec-arm64/sai.mk
upgrade centec arm64 sai to v1.9.1 and fix syncd compile error:
```
2021-11-21T19:58:09.0294367Z /usr/bin/ld: libSyncd.a(libSyncd_a-VendorSai.o): in function `syncd::VendorSai::queryStatsCapability(unsigned long, _sai_object_type_t, _sai_stat_capability_list_t*)':
2021-11-21T19:58:09.0297367Z ./syncd/VendorSai.cpp:439: undefined reference to `sai_query_stats_capability'
2021-11-21T19:58:09.0298900Z collect2: error: ld returned 1 exit status
```
upgrade centec arm64 sai to v1.9.1.
build syncd_1.0.0_arm64.deb.
> [centec][arm64] upgrade centec sai to 1.9.1-0

- src/sonic-build-hooks/scripts/buildinfo_base.sh
When we update the a sai package downing from a remote server, we need to update the version file as well currently, but the reproducible build feature is not enabled in master, it can only be detected when merging the code into the release branches, such as 202106, 202012, etc.
The reproducible feature is to reduce the build failure, not need to break the build when the version not specified. If version not specified, the best choice is to accept the version from remote server.
> [Build]: Fix the version not found issue

- rules/functions
Fix a bug in sonic debug image build. That bug is imported in the following PR:
https://github.com/Azure/sonic-buildimage/pull/8920
> [build] Fix rules/functions generate_manifest function

- src/sonic-host-services-data/debian/sonic-host-services-data.hostcfgd.timer
With current code the delay will take place even if simple 'config reload' command executed and this is not desired.
This delay should be used only when fast-rebooting.
Change the type of delay to OnBootSec instead of OnActiveSec.
Fast-reboot with this PR and observe the delay.
Run 'config-reload' command and observe no delay is running.
> [hostcfgd] [202012] Fix the delay type to 'boot' delay instead of a unit activation delay

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_infos.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal_policy.py
When PSU is powered off, the PSU is still on the switch and the air flow is still the same. In this case, it is not necessary to set FAN speed to 100%.
When PSU is powered of, don't treat it as absent.
1. Adjust existing unit test case
2. Add new case in sonic-mgmt
> [Mellanox] Fan speed should not be 100% when PSU is powered off

- dockers/docker-orchagent/buffermgrd.sh
- files/build_templates/buffers_config.j2
- files/build_templates/docker_image_ctl.j2
- files/build_templates/sonic_debian_extension.j2
- platform/vs/docker-sonic-vs/Dockerfile.j2
- platform/vs/docker-sonic-vs/buffermgrd.sh
- platform/vs/docker-sonic-vs/zero_profiles.json
This is to update the common sonic-buildimage infra for reclaiming buffer.
- Render `zero_profiles.j2` to `zero_profiles.json` for vendors that support reclaiming buffer
The zero profiles will be referenced in PR #8768 on Mellanox platforms and there will be test cases to verify the behavior there.
Rendering is done here for passing azure pipeline.
- Load `zero_profiles.json` when the dynamic buffer manager starts
- Generate inactive port list to reclaim buffer
It depends on PR Azure/sonic-swss#1996 and advancing submodule #9288
> [Reclaim buffer] Common infrastructure update for reclaiming buffer

- dockers/docker-database/database_config.json.j2
- files/image_config/logrotate/logrotate.d/rsyslog
- files/scripts/swss.sh
- platform/vs/docker-sonic-vs/database_config.json
- Add APPL_STATE_DB to database_config.json
- Clear APPL_STATE_DB during SwSS container restarts
- Add response path log file to logrotate config:
responsepublisher.rec
Submission containing materials of a third party:
Copyright Google LLC; Licensed under Apache 2.0
Co-authored-by: Mike Attig <mikeattig@google.com>
Co-authored-by: Runming Wu <runmingwu@google.com>
Co-authored-by: Akarsh Gupta <akarshgupta@google.com>
Adds support for APPL_STATE_DB and response path required for PINS.
Described in this HLD:
https://github.com/pins/SONiC/blob/master/doc/pins/appl_state_db_response_path_hld.md
Any build should do the trick, then verify that the APPL_STATE_DB is empty after restarting swss.
None
Add APPL_STATE_DB and response path log rotation
> [PINS] Add APPL_STATE_DB and response path log rotation

- dockers/docker-sonic-mgmt-framework/Dockerfile.j2
Fixes #9376
Because /etc/passwd and /etc/group have been overwritten with symlinks
to /host_etc/passwd and /host_etc/group, the debug container build
fails. This is because the debug container is built without /etc being
mounted at /host_etc in the container (which does happen at runtime).
Because of that, /etc/passwd and /etc/group don't exist, which causes
some package installation errors when openssh-client tries to create a
group.
This is a partial revert of 1347f29178d363b68bbb24e9e884f19e9c49bda2.
> [docker-mgmt-framework]: Don't overwrite /etc/passwd and /etc/group with symlinks

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/bgp.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp.json
- src/sonic-yang-models/yang-models/sonic-bgp-neighbor.yang
#9119
BGP_NEIGHBOR_TEMPLATE_LIST does not have admin_status field.
Add admin_status to BGP_NEIGHBOR_TEMPLATE_LIST.
Follow the steps in #9119.
Build sonic-yang-model.
fix #9119
> [yang]: Add admin_status to BGP_NEIGHBOR_TEMPLATE_LIST.

- device/celestica/x86_64-cel_e1031-r0/platform.json
- Eliminate failed test cases in Platform API test cases in sonic-mgmt that check for HW properties that are not supported by Haliburton devices.
- Add capability configurations to platform.json  file to describe which HW features are supported.
- Run platform api test on sonic-mgmt
> [device/celestica]: Add new platform capabilities to platform.json of Haliburton device

- files/image_config/copp/copp_cfg.j2
- platform/vs/docker-sonic-vs/init_cfg.json.j2
- src/sonic-yang-models/yang-models/sonic-copp.yang
Add the "always_enabled" field to copp_cfg.j2 file, in order to allow traps without an entry in features table, to be installed automatically.
Add the new field, and changed the logic in sonic-swss.
In addition, add all of the enabled features to init_cfg.json.j2 file in order to have the UT passing. 
Check that arp, udld, ip2me and lacp traps are auto installed, and traps that has no feature entry are not auto installed.
> [CoPP] Add always_enabled field

- src/sonic-py-common/sonic_py_common/device_info.py
Sonic utilities tests runs into issues after adding the check for 'is_chassis()' due to version info being None.
Check for None before accessing the version_info
Before
```
samaddik@20139b1eaeb5:/sonic/src/sonic-utilities/tests$ pytest-3 watermarkstat_test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /sonic/src/sonic-utilities/tests, inifile: pytest.ini
plugins: cov-2.6.0
collected 0 items / 1 errors
======================================================================================= ERRORS ================================================================================= …
```
> [sonic-py-common][device info] Check for None before accessing the ASIC type 

- dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/instance.conf.j2
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_all.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_base.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_shutdown_1.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_shutdown_2.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_timers_1.conf
- src/sonic-bgpcfgd/tests/data/voq_chassis/instance.conf/result_timers_2.conf
Currently, voq chassis bgp neighbor timer configuration is done similar to general neighbors. i.e., keepalive and holdtime timers are set to configured values, if configured,, otherwise set to default of 60 and 180. This is causing a problem of configuring timer values to 0 & 0 since minigraph configures 0 & 0 for voq chassis neighbors. Voq chassis neighbors are equivalent to multi-asic internal neighbors but we need to configure timers to values other than 0 & 0 since the voq chassis bgp neighbors may go down due to line card failures, for example. This PR fixes this problem of having 0 and 0 timer confiuration for voq chassis neighbors.
Since the voq chassis bgp neighbors are similar to multi-asic internal neighbors, the voq chassis bgp timers are configured similar to multi-asic …
> [voq][bgpcfg] BGP_VOQ_CHASSIS_NEIGHBORS timers config

- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
Add trap flow counter to yang model
Add a new container for yang model and add unit test config
Build
> [YANG] Add trap flow counter to yang model

- files/build_templates/docker_image_ctl.j2
Fix for issue https://github.com/Azure/sonic-buildimage/issues/8389
The /etc/rsyslog.conf is empty file which cause the FATAL of the process rsyslogd in the global instance database container.  The function updateSyslogConf() should only generate the rsyslog.conf for containers in the namespace. it should not do it for the containers in the global instance. Instead, default rsyslog.conf should be used.  Especially for database container, updateSyslogConf() is called before the database container is created.  The result cause the sonic-cfggen failed to generate the rsyslog.conf.  
-- Go to the database container and execute the supervisorctl status command:
```
admin@sonic:~$ docker exec -it database bash
root@sonic:/# supervisorctl status
flushdb                          EXITED    Aug 08 …
```
> [rsyslogd][multiasic] fixed rsyslogd FATAL issue in the database container in multi-asic box

- rules/swss-common.mk
Bring in the following commit:
```
405f1df Use build profiles instead of distro version for Python 2 binding build (#558)
```
This change requires a corresponding change in this repo to set a build
profile to not build the python 2 bindings on Bullseye.
> [sonic-swss-common]: Submodule update

- files/build_templates/database.service.j2
- files/build_templates/docker_image_ctl.j2
- files/build_templates/sonic_debian_extension.j2
- files/build_templates/swss.service.j2
- files/image_config/process-reboot-cause/determine-reboot-cause
- files/image_config/process-reboot-cause/determine-reboot-cause.service
- files/image_config/process-reboot-cause/process-reboot-cause
[201811] Check platform reboot cause to see if any reset happened during fast/warm-reboot
To recover syncd and swss from any cold reset during fast/warm-reboot
Check platform reboot-cause to see if any cold reset happens for fast-reboot power up
Manual test
> [201811] Check platform reboot cause to see if any reset happened during fast/warm-reboot

- src/sonic-build-hooks/scripts/buildinfo_base.sh
- src/sonic-build-hooks/scripts/post_run_buildinfo
- src/sonic-build-hooks/scripts/pre_run_buildinfo
The reproducible build mirrors are only used during the build, the mirrors can be removed after that.
Add a comment character # in front of the mirror source list after build.
Run "sudo apt-get update" to verify the reproducible mirrors not used.
> [Build]: Cleanup the reproducible mirrors when build complete

- platform/broadcom/sai.mk
For broadcom sai, we only need to upgrade the version, not necessary the token part in the url.
> Simplify the broadcom sai packages reference

- slave.mk
**Before:**
```
+ SONIC_PACKAGE_MANAGER_FOLDER=/var/lib/sonic-package-manager/
+ sudo mkdir -p ./fsroot-mellanox//var/lib/sonic-package-manager/
+ sudo tee ./fsroot-mellanox//var/lib/sonic-package-manager//packages.json
+ target_machine=mellanox
+ j2 files/build_templates/packages.json.j2
{
"": {
"repository": "docker-database-dbg",
"description": "SONiC  package",
"default-reference": "",
"installed-version": "",
"built-in": true,
"installed": true
},
"": {
"repository": "docker-fpm-frr-dbg",
"description": "SONiC  package",
"default-reference": "",
"installed-version": "",
"built-in": true,
"installed": true
},
"": {
"repository": "docker-lldp-dbg",
"description": "SONiC  package",
"default-reference": "",
"installed-version": "", …
```
> [build]: Fix SAE to support debug flavor build

- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/sfp.py
As part of SFP refactoring, LP mode is implemented for CMIS devices.
CMIS devices has to invoke common API instead of HW pin.
Made changes in platform SFP LP mode API.
Verified in DellEMC Z9332f platform.
**Note:**
Please merge this PR only when sonic-platform-common submodule is updated with https://github.com/Azure/sonic-platform-common/pull/247
UT:
[LPmode_UT.txt](https://github.com/Azure/sonic-buildimage/files/7617677/LPmode_UT.txt)
> DellEMC: Change Platform LP mode API

- scripts/build_kvm_image.sh
Fix no space left on device issue in tmpfs.
2021-12-01T06:30:40.1651742Z cp: write error: No space left on device
2021-12-01T06:30:40.1652225Z Failure: local_fs_run():/dev/vdb Unable to copy /tmp/tmp.gl4Sgp/onie-installer.bin to tmpfs
> [Build]: Fix tmpfs space not enough issue when building vs image

- .azure-pipelines/azure-pipelines-image-template.yml
- azure-pipelines.yml
Support marvell-armhf dpkg cache and the azp check.
Waiting for merging PR https://github.com/Azure/sonic-buildimage/pull/9381 to 202012 branch, so only azp template change in this PR.
Move the VS build to a new stage BuildVS, change the Test stage only depending on BuildVS, running the BuildVS and the other platform's build in parallel. The Test stage do not has dependency on the marvel-armhf build, reduce the overall build time caused by longer build time of marvel-armhf build.
> [Build]: Enable arm pr check

- device/arista/x86_64-arista_7280cr3mk_32p4/Arista-7280CR3-C40/gearbox_config.json
- device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/gearbox_config.json
For platforms with macsec enabled,  a special IPG has to be set on the ports of ASIC to avoid packet loss. This change sets macsec_ipg for Arista platforms with the assumption that SCI is included.
> [macsec] Add macsec_ipg setting to Arista platforms

- device/dell/x86_64-dell_s6100_c2538-r0/installer.conf
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/watchdog.py
- To support iTCO watchdog using watchdog APIs.
- Implemented a new watchdog class `WatchdogTCO`  for interfacing with iTCO watchdog.
- Updated reboot cause determination logic.
Verified that the watchdog APIs' return values are as expected.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7459593/UT_logs.txt)
[DellEMC] S6100 - iTCO watchdog support and reboot cause determination changes
> [DellEMC] S6100 - iTCO watchdog support and reboot cause determination changes

- slave.mk
Fix issue:
```
stepanb@9091511f691b:/sonic$ make -f slave.mk list
SONiC Build System
Build Configuration
"CONFIGURED_PLATFORM"             : "vs"
"CONFIGURED_ARCH"                 : "amd64"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "12"
"SONIC_USE_DOCKER_BUILDKIT"       : ""
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"ENABLE_PFCWD_ON_START"           : ""
"SONIC_BUFFER_MODEL"              : ""
"INSTALL_DEBUG_TOOLS"             : ""
"ROUTING_STACK"                   : "frr"
"FRR_USER_UID"                    : "300"
"FRR_USER_GID"                    : "300"
"ENABLE_SYNCD_RPC" …
```
> [slave.mk] fix error: recursive variable references itself.

- src/sonic-config-engine/minigraph.py
Local variable may not be created in minigraph parsing, causing crash
Moved variable creation earlier
> Fix uninitialized variable in minigraph parsing

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_infos.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal_policy.py
Backport https://github.com/Azure/sonic-buildimage/pull/9258 to 201911
- Why I did it
When PSU is powered off, the PSU is still on the switch and the air flow is still the same. In this case, it is not necessary to set FAN speed to 100%.
- How I did it
When PSU is powered of, don't treat it as absent.
Adjust existing unit test case
Add new case in sonic-mgmt
Conflicts:
platform/mellanox/mlnx-platform-api/sonic_platform/thermal_infos.py
> [Mellanox] [201911] Fan speed should not be 100% when PSU is powered off

- .azure-pipelines/docker-sonic-slave.yml
- src/sonic-build-hooks/scripts/buildinfo_base.sh
Merged from master branch: https://github.com/Azure/sonic-buildimage/pull/9443
Fix the nodesource.list cannot read issue, it is cased by the full path not used.
```
2021-12-03T06:59:26.0019306Z Removing intermediate container 77cfe980cd36
2021-12-03T06:59:26.0020872Z  ---> 528fd40e60f6
2021-12-03T06:59:26.0021457Z Step 81/81 : RUN post_run_buildinfo
2021-12-03T06:59:26.0841136Z  ---> Running in d804bd7e1b06
2021-12-03T06:59:29.1626594Z [91mDEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove …
```
> [Bug][Build]: fix the file not found issue caused by the relative path

- platform/mellanox/mlnx-platform-api/sonic_platform/led.py
- platform/mellanox/mlnx-platform-api/tests/test_led.py
Nvidia platform API does not support set LED to orange 
Allow user to set LED to orange
Added unit test
Manual test
> [Mellanox] Allow user to set LED to orange

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
#9122
DEVICE_METADATA does not have cloudtype and region.
Add cloudtype and region to DEVICE_METADATA.
Follow the steps in #9122.
Build sonic-yang-model.
fix #9122
> [yang]: update Yang models for cloudtype and region

- device/accton/x86_64-accton_as4630_54te-r0/sonic_platform/sfp.py
- device/accton/x86_64-accton_as5835_54x-r0/sonic_platform/sfp.py
- device/accton/x86_64-accton_as7116_54x-r0/sonic_platform/sfp.py
- device/accton/x86_64-accton_as7312_54x-r0/sonic_platform/sfp.py
- device/accton/x86_64-accton_as9726_32d-r0/sonic_platform/sfp.py
- device/celestica/x86_64-cel_e1031-r0/sonic_platform/sfp.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
- device/celestica/x86_64-cel_silverstone-r0/sonic_platform/sfp.py
- device/juniper/x86_64-juniper_qfx5200-r0/plugins/sfputil.py
- device/juniper/x86_64-juniper_qfx5210-r0/plugins/sfputil.py
- device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfputil.py
- platform/broadcom/sonic-platform-modules-alphanetworks/snj60d0-320f/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-cel/services/platform_api/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-inventec/d6332/sonic_platform/qsfp.py
- platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform/qsfp.py
- platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-inventec/d7054q28b/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix7-bwde-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix8-56x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix8a-bwde-56x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix8c-56x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-quanta/ix9-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-ruijie/b6510-48vs8cq/sonic_platform/sfp.py
- platform/innovium/sonic-platform-modules-netberg/aurora-715/sonic_platform/sfp.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py
Fixes the issue https://github.com/Azure/sonic-platform-common/issues/250
Modified transceiver dict keys for all the vendors
Check "sfpshow eeprom".
Check xcvrd logs.
**Note:**
Merge this PR only when https://github.com/Azure/sonic-platform-daemons/pull/231 is merged
> [SFP-Refactor] Modify transceiver key name

- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/cable_length.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/cable_length.json
- src/sonic-yang-models/yang-models/sonic-cable-length.yang
Add YANG model support for table `CABLE_LENGTH`
1. Add the YANG model file
2. Add the test description file and config file
3. add list `CABLE_LENGTH_LIST` to the `qos_maps_model ` list in `sonic-yang-ext`, as it has an inner list.
Build `sonic-yang-model` and `sonic-yang-mgmt`
> [YANG] add YANG model support for CABLE_LENGTH

- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp.json
- src/sonic-yang-models/yang-models/sonic-bgp-common.yang
fixing https://github.com/Azure/sonic-buildimage/issues/9350 "[yang-models] BGP neighbor admin_status should be up/down"
> sonic-bgp-cmn/admin_status fixed

- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Signed-off-by: Abhishek Dharwadkar <48468617+abhishekd0@users.noreply.github.com>
Currently only IP ACL and related model is defined. Support for MAC ACL is missing. Added support for it.
ACL_RULE table is added with new MAC ACL related fields namely Source MAC, Destination MAC, Ethertype (Pattern updated to match any valid Ethertypes), VLAN, PCP, DEI
Yang model tests are attached.
Add support for MAC ACL yang model.
> SONiC MAC ACL Yang model update to add support for Source MAC, Destination MAC, Ethertype pattern update, VLAN_ID, PCP, DEI fields.

- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/port_config.ini
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/sai_4600c_100x50g_12x100g_2x10g.xml
Missing NVIDIA copyright header from some files.
Added copyright header
N/A
[mellanox] Add copyright headers to Mellanox-SN4600C-D100C12S2 SKU
> [Mellanox] Add copyright headers to Mellanox-SN4600C-D100C12S2 SKU

- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Fixing issue #9294
Updating ACL yang model
Validating issue with `config patch-apply` is fixed.
- Start a KVM
- Add file `add-ctrl-plane-tbl.json-patch ` with content:
```json
[
{
"op": "add",
"path": "/ACL_TABLE/ACTRLPLANETABLE",
"value": {
"policy_desc": "ACTRLPLANETABLE",
"services": [
"SSH"
],
"stage": "ingress",
"type": "CTRLPLANE"
}
}
]
```
- Run `sudo config apply-patch add-ctrl-plane-tbl.json-patch`
Before:
```
Patch Applier: The patch was sorted into 4 changes:
Patch Applier:   * [{"op": "add", "path": "/ACL_TABLE/ACTRLPLANETABLE", "value": {"type": "CTRLPLANE"}}]
Patch Applier:   * [{"op": "add", "path": "/ACL_TABLE/ACTRLPLANETABLE/policy_desc", "value": "ACTRLPLANETABLE"}]
Patch Applier:   * [{"op": "add", "path": "/ACL_TABLE/ACTRLPLANETABLE/services", "value": ["SSH"]}]
Patch …
```
> [yang-models] Validating 'services' exist if ACL type is 'CTRLPLANE'

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Bring back the changes in #9226 that were reverted. Unable to do a revert-revert.
Why I did it
Few device types were missing in the DEVICE_METADATA type field
How I did it
Added missing device types to the device metadata yang
> [yang] Add missing device types to the device_metadata yang 

- device/dell/x86_64-dell_s6000_s1220-r0/pmon_daemon_control.json
- device/dell/x86_64-dell_s6100_c2538-r0/pmon_daemon_control.json
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/psu.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/fan.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/psu.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/thermal.py
To incorporate the below changes in DellEMC S6100, S6000 platforms.
- Enable thermalctld
- Backport Platform API changes from master branch.
- Remove 'skip_thermalctld:true' in pmon_daemon_control.json
- Implement the platform API methods in the respective device files
Verified that platform data is displayed by `show platform fan` and `show platform temperature` commands.
UT Logs:
[S6000_platform_api_201911_logs.txt](https://github.com/Azure/sonic-buildimage/files/7608789/S6000_platform_api_201911_logs.txt)
[S6100_platform_api_201911_logs.txt](https://github.com/Azure/sonic-buildimage/files/7608790/S6100_platform_api_201911_logs.txt)
[201911] DellEMC: S6000, S6100 - Enable thermalctld, Platform API changes
> [201911] DellEMC: S6000, S6100 - Enable thermalctld, Platform API changes

- check_install.py
- install_sonic.py
- scripts/build_kvm_image.sh
When the image is installed from within KVM and then loaded, some files
(such as timer stamp files) are created as part of that bootup that then
get into the final image. This can cause some side effects, such as
systemd thinking that some persistent timers need to run because the
last trigger time got missed.
Therefore, at the end of the check_install.py script, remove the rw
folder so that it doesn't exist in the image, and that when this image
is started up in a KVM setup for the first time, it starts with a truly
clean slate.
Without this change, the issue seen was that for fstrim.timer, a stamp
file would be present in /var/lib/systemd/timers (and for other timers
that are marked as persistent). This would then cause fstrim.service to
get started immediately when starting a QEMU …
> Remove the rw folder from the image after installing in KVM

- dockers/docker-router-advertiser/start.sh
Wrong logic in start radv if statement. 
Was not detected before when tested because the if statement had wrong syntax that caused the loop to be skipped..
Change "||" to "&&"
Run on M0 device, test radv starts and the if statement took effect.
> [201811] Fix radv start condition logic

- files/build_templates/init_cfg.json.j2
Reverts Azure/sonic-buildimage#9238
We met test issue https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/58353/logs/33
```
2021-12-10T17:56:58.2382264Z + sudo LANG=C DOCKER_HOST= chroot ./fsroot-vs /usr/local/bin/generate_shutdown_order.py
2021-12-10T17:56:58.2382658Z sonic_yang(3):All Keys are not parsed in CRM
2021-12-10T17:56:58.2383548Z dict_keys(['srv6_my_sid_entry_threshold_type', 'srv6_my_sid_entry_low_threshold', 'srv6_my_sid_entry_high_threshold', 'srv6_nexthop_threshold_type', 'srv6_nexthop_low_threshold', 'srv6_nexthop_high_threshold'])
2021-12-10T17:56:58.2384117Z sonic_yang(3):exceptionList:[]
2021-12-10T17:56:58.2384485Z sonic_yang(3):Data Loading Failed:All Keys are not parsed in CRM
2021-12-10T17:56:58.2385395Z …
```
> Revert "CRM init config for SRV6 Nexthop and MY_SID resource"

- src/sonic-py-common/sonic_py_common/interface.py
This interface type is used for recirculation on chassis.
The definition is required to prevent this interface from being
considered a physical interface in sonic-platform-common and sonic-platform-daemon
Required for chassis work
Add recirc_prefix definition in sonic_py_common
> [sonic-py-common] Add recirc_prefix definition

- files/build_templates/docker_image_ctl.j2
database.sh failed to create the database for namespace in multiasic platform.
The latest code Docker version 20.10.x, command "docker create" no longer takes optional  "NET=" with empty value. Syntax error show with current docker create command in database.sh.  Issue #9503
Modify the docker_image_ctl.j2 to set default network setting  NET="bridge" instead of empty for namespace database.  
boot up the new image in a multiasic platform.  the namespace database containers should be created.  Also the following error message should not be seen in syslog file
``` 
docker: no name set for network.
See 'docker create --help'.
Failed to docker run
```
> [multiasic][database]database.sh failed to create the database for namespace in multiasic platform

- platform/mellanox/mlnx-platform-api/sonic_platform/led.py
Backport https://github.com/Azure/sonic-buildimage/pull/9259 to 202012
Nvidia platform API does not support set LED to orange. 
Allow user to set LED to orange
Manual test
> [Mellanox] [202012] Allow user to set LED to orange

- platform/mellanox/mlnx-platform-api/sonic_platform/led.py
- platform/mellanox/mlnx-platform-api/tests/test_led.py
Backport https://github.com/Azure/sonic-buildimage/pull/9259 to 202106
Nvidia platform API does not support set LED to orange. 
Allow user to set LED to orange
1. Manual test
2. unit test
> [Mellanox] [202106] Allow user to set LED to orange

- dockers/docker-ptf/Dockerfile.j2
To enable test support for BFD-related features, the PTF docker needs to have the proper support for BFD. This PR aims to add BFD support in ptf docker.
Clone and build OpenBFDD for PTF docker.
Build locally and verify BFD is supported.
> [ptf-docker] Add OpenBFDD into ptf docker

- src/lldpd/patch/0012-fix-recreate-socket-on-ifindex-change.patch
- src/lldpd/patch/series
Signed-off-by: tomeri <tomeri@nvidia.com>
when we remove a port and add it back immediately - lldp is keep failing
warning message keeps appearing:
...
[WARN/lldp] unable to send packet on real device for Ethernet4: No such device or address
...
on delete link events it will immediately execute delete without using aggregate events mechanism.
manual tests and run mellanox lldp regression tests
[LLDPD] fix to port remove and immediately create a problem - on delete link events it will immediately execute delete without using aggregate events mechanism.
This patch was added to LLDPD on this PR:
https://github.com/lldpd/lldpd/pull/492
> [LLDPD] fix to port remove and immediately create problem

- src/sonic-yang-models/tests/yang_model_tests/tests/loopback.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/loopback.json
- src/sonic-yang-models/yang-models/sonic-loopback-interface.yang
Fix issue https://github.com/Azure/sonic-utilities/issues/1962
The problem is current implementation of [sonic-yang-mgmt::find_data_dependencies](https://github.com/Azure/sonic-buildimage/blob/f2774b635dee2d5c0e30489632b47e0210a712dd/src/sonic-yang-mgmt/sonic_yang.py#L518) does not get referrers if they are using `must` statement, it has to use `leafref`.
For now we can convert `must` to `leafref` if possible. In the future we will investigate get referrers by `must` statements as well https://github.com/Azure/sonic-buildimage/issues/9534
Instead of `must` use `leafref`
unit-test
> [yang-model] Using 'leafref' instead of 'must' for loopback

- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
> [sonic-slave]: Upgrade python lxml library version to 4.6.5

- build_debian.sh
- files/build_templates/sonic_debian_extension.j2
- src/tacacs/audisp/patches/0001-Porting-to-sonic.patch
1. Fix auditd log file path, because known issue: https://github.com/Azure/sonic-buildimage/issues/9548
2. When SONiC change to based on bullseye, auditd version upgrade from 2.8.4 to 3.0.2, and in auditd 3.0.2 the plugin file path changed to /etc/audit/plugins.d, however the upstream auditisp-tacplus project not follow-up this change, it still install plugin config file to /etc/audit/audisp.d. so the plugin can't be launch correctly, the code change in src/tacacs/audisp/patches/0001-Porting-to-sonic.patch fix this issue.
Fix tacacs plugin config file path.
Create /var/log/audit folder for auditd.
Pass all UT, also run per-command acccounting UT to validate plugin loaded.
Fix tacacs plugin config file path.
Create /var/log/audit folder for auditd.
> [TACACS] Fix auditd can't load tacplus plugin issue.

- device/arista/x86_64-arista_7060_cx32s/platform-init
- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-orchagent/docker-init.sh
The platform-init, similar to hwsku-init, would be scripts that need to
be called for a specific platform.
Arista 7060 platform has a rare and unreproduceable PCIe timeout that could possibly be solved with increasing the switch PCIe timeout value. To do this we'll call a script for this platform to increase the PCIe timeout on boot-up.
No issues would be expected from the setpci command. From the PCIe spec:
"Software is permitted to change the value in this field at any
time. For Requests already pending when the Completion
Timeout Value is changed, hardware is permitted to use either
the new or the old value for the outstanding Requests, and is
permitted to base the start time for each Request either on when
this value was changed or on when each request was issued. "
Add …
> [Arista] Increase switch PCIe timeout for 7060

- src/dhcp6relay/src/relay.cpp
- src/dhcp6relay/src/relay.h
(cherry picked from commit f2ee94d201a5b8a6ebf09d0680a526fc14cc41a2)
This is a cheery pick for PR https://github.com/Azure/sonic-buildimage/pull/9283
DHCPv6 Counter updates counter only on received messages, not relayed messages
Update counter on messages relayed by DHCPv6 Relay
Check the counter with CLI or in state db
> [dhcp_relay] Update DHCPv6 counter on relayed messages (#9283)

- src/sonic-yang-models/tests/yang_model_tests/tests/pfc.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/pfc.json
- src/sonic-yang-models/yang-models/sonic-pfcwd.yang
POLL_INTERVAL cannot be set if any of the detection/restoration times in this table is less than the POLL_INTERVAL.
Add "must" constraint to make sure detection/restoration times are greater than POLL_INTERVAL.
Use apply-patch command to update POLL_INTERVAL.
Build sonic-yang-model.
Fix #9490
> [yang]: Add constraint for pfcwd

- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/buffers_default_objects.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D112C8/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D112C8/buffers_defaults_t1.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D48C40/buffers_defaults_t0.j2
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D48C40/buffers_defaults_t1.j2
Fix typo and missing files in SN3800 and SN4600C's buffer templates
1. ingress_lossless_xoff_size => ingress_lossless_pool_xoff
2. add missing files for SN4600C-D100C12S2
Deploy the fix and verify whether the device can be up.
> [Mellanox] Fix typo and missing file in buffer templates

- src/sonic-config-engine/tests/pc-test-graph.xml
- src/sonic-config-engine/tests/sample-graph-resource-type.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/sample_graph.xml
- src/sonic-config-engine/tests/simple-sample-graph.xml
- src/sonic-config-engine/tests/t0-sample-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
Config db schema generated from test minigraph can't pass yang validation.
Update minigraph xml to add DeploymentId.
Run command 'sonic-cfggen -m xxx.xml --print-data', and check deployment_id field.
Fix #9550
> [sonic-cfggen]: Update test minigraph to add deployment_id

- device/mellanox/x86_64-mlnx_msn4410-r0/ACS-MSN4410/port_config.ini
The capability files were incorrect in comparison to the marketing spec of the SN4410 platform.
Aligned the capability files according to the marketing spec.
Did basic manual sanity checks:
- Check if critical docker containers were UP
- Check if interfaces were created and were UP
- Check if interfaces created in the syncd docker container by executing – sx_api_ports_dump.py script
- Check the logs from the start of the switch – everything was OK
- Verified the port breakout
> [Mellanox] [SN4410] [202012] Fixed port_config.ini

- src/sonic-config-engine/tests/sample_graph.xml
Config db schema generated from test minigraph can't pass yang validation.
Update test minigraph to fix interface
Run command 'sonic-cfggen -m xxx.xml --print-data', and check interface table and port table.
Fix #9552
> [sonic-cfggen]: Update test minigraph to fix interface

- src/sonic-config-engine/tests/sample-voq-graph.xml
- src/sonic-config-engine/tests/simple-sample-graph-case.xml
- src/sonic-config-engine/tests/simple-sample-graph-metadata.xml
'SYSLOG_SERVER': {'': {}, '10.0.10.5': {}, '10.0.10.6': {}},
Config db schema generated by minigraph can’t pass yang validation, server address can't be empty.
Update test minigraph to remove wrong configuration.
Run command 'sonic-cfggen -m xxx.xml --print-data', and SYSLOG_SERVERS table.
Fix #9571
> [sonic-cfggen]: Fix syslog_server output

- dockers/docker-sonic-mgmt/Dockerfile.j2
https://pypi.org/project/lazy-object-proxy/#description
lazy-object-proxy's latest version does not support python2, while pylint denpends on lazy-object-proxy.
1.7.1 (2021-12-15)
Removed most of the Python 2 support code and fixed python_requires to require at least Python 3.6.
Note that 1.7.0 has been yanked because it could not install on Python 2.7. Installing lazy-object-proxy on Python 2.7 should automatically fall back to the 1.6.0 release now.
> [build] Fix docker-sonic-mgmt pylint dependency lazy-object-proxy version

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/feature.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/feature.json
- src/sonic-yang-models/yang-models/sonic-feature.yang
The feature state can be a jinja template, like in this file - https://github.com/Azure/sonic-buildimage/blob/master/files/build_templates/init_cfg.json.j2#L39.
Without this change it is not possible to validate a configuration file.
Relaxes the constraint on feature state. Feature state leaf can be any string.
Run UT.
> [sonic-yang] W/A the feature "state" field validation

- platform/pddf/i2c/service/pddf-platform-init.service
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan.py
Some platforms need to run few steps before the PDDF service is actually started.
Added a pre_pddf_init script execution as ExecStartPre in the service file
Verified on AS7816 and AS9716 platforms. Please check
https://github.com/Azure/sonic-buildimage/pull/7826 
https://github.com/Azure/sonic-buildimage/pull/7827
> Adding pre_pddf_init script in the service file

- device/dell/x86_64-dell_s6000_s1220-r0/platform.json
- device/dell/x86_64-dell_s6100_c2538-r0/platform.json
- device/dell/x86_64-dellemc_z9332f_d1508-r0/platform.json
To include newer Fan LED, thermal capabilities fields in platform.json of DellEMC S6000, S6100, Z9332f platforms.
Add the capabilities fields in each platform's respective platform.json.
Ran sonic-mgmt platform api test cases that use capabilities fields and verified that the results are as expected.
DellEMC: S6000, S6100, Z9332f - Update Fan LED, Thermal fields in platform.json
> DellEMC: S6000, S6100, Z9332f - Update Fan LED, Thermal fields in platform.json 

- device/dell/x86_64-dell_s6100_c2538-r0/platform.json
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/psu.py
- platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/psu.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py
To incorporate the below changes in DellEMC S6100, S6000 platforms.
- S6100, S6000:
- Implement 'get_revision' method for Chassis
- Implement 'get_maximum_consumed_power' method for FanDrawer
- Implement 'get_revision', 'get_maximum_supplied_power' methods for PSU
- Implement 'get_error_description' method for SFP.
- S6100:
- Implement 'get_module_index' method for Chassis
- Implement 'get_description', 'get_maximum_consumed_power', 'get_oper_status', 'get_slot' methods for Module
- Update component names in platform.json
Implement the platform API methods in the respective device files
Verified that the respective sonic-mgmt platform API test cases report success.
Logs:
[S6100_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/7735344/S6100_UT_logs.txt) …
> DellEMC: S6100, S6000 - Platform API implementation

- dockers/docker-dhcp-relay/dhcpv6-relay.monitors.j2
Why I did:
DHCP Relay docker does not start if we don't have v6 DHCP Relay address as this caused jinja2 template generation failure.
What I did:
Fixed the template . The fix is to make template generation same as present in master code.
How I verify:
Manual Verification and make sure dhcp relay docker is running fine.
> [201811] Fix DHCP Relay Monitor Jinaja2 Template file.

- sonic-slave-stretch/Dockerfile.j2
Fix the gmock not found issue in debian stretch slave container.
Some of platforms, such as naphos, innovium, have such issue.
See https://dev.azure.com/mssonic/build/_build/results?buildId=62861&view=logs&j=1111c693-39b7-5a16-3aee-406c790b3886&t=d6851b2d-8b22-5ce8-7267-f54b7a47081b
```
2022-01-03T09:03:27.8890266Z /usr/bin/ld: cannot find -lgmock
2022-01-03T09:03:27.8891526Z /usr/bin/ld: cannot find -lgmock_main
2022-01-03T09:03:27.8892509Z collect2: error: ld returned 1 exit status
2022-01-03T09:03:27.8893983Z Makefile:467: recipe for target 'tests' failed
2022-01-03T09:03:27.8895220Z make[4]: *** [tests] Error 1
2022-01-03T09:03:27.8896751Z make[4]: Leaving directory '/sonic/src/sonic-swss-common/tests'
2022-01-03T09:03:27.8898681Z Makefile:439: recipe for target 'all-recursive' failed …
```
> [Build]: Fix gmock not found issue in debian stretch slave container

- src/sonic-yang-mgmt/sonic_yang.py
- src/sonic-yang-mgmt/sonic_yang_ext.py
Fixes https://github.com/Azure/sonic-utilities/issues/1871
From [generic-config-updater](https://github.com/Azure/sonic-utilities/tree/master/generic_config_updater) we call `sonic-yang-mgmt` multiple times in order to check a certain change to ConfigDb is valid or not. It is expected for some changes to be invalid, so always printing errors from `sonic-yang-mgmt` makes the output hard to read.
In this PR, we are adding a way to control if logs should be printed or not.
- Added `print_log_enabled` flag to sonic_yang ctor
- Converted all `print` statements to `sysLog(..., doPrint=True)`
unit-test passing means the change did not break logs.
libyang provides an extensive logging logic which can support a lot of scenarios:
- ly_log_level: setting logging level
- LY_LLERR
- LY_LLWRN
- ... 
- …
> [sonic-yang-mgmt] Adding flag to disable/enable log printing

- src/sonic-build-hooks/scripts/buildinfo_base.sh
when using 'sed -i' the directory must also be writable as sed will create a temporary file in that directory first.
This issue breaks building sonic-mgmt docker image.
we should use sudo to resolve this issue, but sonic-base image haven't installed sudo tool.
So we should use both 'sed -i' and 'sudo sed -i'
add retry with sudo.
> Fix docker-sonic-mgmt reproducible related issue.

- platform/broadcom/sonic-platform-modules-dell/s5212f/scripts/pcisysfs.py
- platform/broadcom/sonic-platform-modules-dell/s5212f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/scripts/pcisysfs.py
- platform/broadcom/sonic-platform-modules-dell/s5224f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5232f/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s5296f/scripts/pcisysfs.py
Reboot cause is not working in S52xx platforms.
Modified platform API's.
Check "show reboot-cause" to verify the reboot reason
> [DellEMC] S52xx fix reboot cause issue

- src/sonic-config-engine/tests/fg-ecmp-sample-minigraph.xml
Config db schema generated by minigraph can’t pass yang validation, there's no Vlan31 in 'VLAN' table.
Update test minigraph to add vlan interface.
Build sonic-yang-models.
Run command 'sonic-cfggen -m tests/fg-ecmp-sample-minigraph.xml -p tests/mellanox-sample-port-config.ini --print-data', and run yang validation.
Fix #9581
> [sonic-cfggen]: Fix missing vlan interface

- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal.py
Recently additional sensors that were needed only for specific system added to all systems and caused errors.
Enhanced current implementation to support inclusions per sensor type.
Run show platform temperature
This PR is fixing issue in "show platform temperature", now the right sensors are being showed.
> [Mellanox] Include CPU board and switch board sensors only on SN2201 system

- src/sonic-yang-models/tests/yang_model_tests/tests/vlan.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan.json
- src/sonic-yang-models/yang-models/sonic-vlan.yang
Config db schema generated by minigraph can’t pass yang validation, and there's no 'alias' field in yang model.
Minigraph parser supports 'alias' field for VLAN.
Add 'alias' field to sonic-vlan.yang
Build sonic-yang-models.
Run command 'sonic-cfggen -m xxx.xml --print-data', and run yang validation.
Fix #9557
> [yang]: Support VLAN alias

- platform/centec-arm64/docker-saiserver-centec.mk
- platform/centec-arm64/docker-syncd-centec-rpc.mk
- platform/centec/docker-saiserver-centec.mk
- platform/centec/docker-syncd-centec-rpc.mk
Fix docker-syncd-centec-rpc build fail. Detail fail log can be derived from https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/60120/logs/9.
Add docker-syncd-centec-rpc and docker-saiserver-centec to buster docker image list. These 2 docker images are based on docker-config-engine-buster.
make ENABLE_SYNCD_RPC=y target/docker-syncd-centec-rpc.gz
make ENABLE_SYNCD_RPC=y target/docker-saiserver-centec.gz
> [centec][build] Fix docker-syncd-centec-rpc build fail

- src/sonic-config-engine/tests/sample-graph-resource-type.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/simple-sample-graph.xml
Config db schema generated by minigraph can’t pass yang validation, portchannel_member has invalid port.
Update test minigraph to remove invalid port channel.
Run command 'sonic-cfggen -m xxx.xml --print-data', and check port channel member.
Fix #9554
> [sonic-cfggen]: Remove wrong portchannel members

- scripts/build_debian_base_system.sh
When the package name with special characters, such as +, the package name may be encoded as %2b, the package url will not be found when reproducible build enabled.
see https://dev.azure.com/kamelnetworks/53a5c7e8-3f52-4611-a688-a61ab05a4216/_apis/build/builds/24/logs/10
```
2022-01-05T15:12:48.9426322Z 2022-01-05 15:12:48 (119 MB/s) - 'target/baseimage/var/cache/apt/archives/libssl1.1_1.1.1k-1+deb11u1_amd64.deb' saved [1554464/1554464]
2022-01-05T15:12:48.9426584Z 
2022-01-05T15:12:48.9426887Z No found package or found multiple package for package libstdc++6, url: 
2022-01-05T15:12:48.9427392Z [  FAIL LOG END  ] [ target/sonic-aboot-broadcom.swi ]
```
Fix the filename encoding issue.
Fix the buster hardcode issue.
```
root@491bb27ffd95:~# encoded_packagename=$(urlencode $packagename) …
```
> [Bug][Build]: Fix the package url not found when package name encoded issue

- src/sonic-py-common/sonic_py_common/multi_asic.py
Signed-off-by: anamehra <anamehra@cisco.com>
On a multi-asic Supervisor card, running commands like
'show interface counter' opens a confid_db connection per
namespace per interface which results in many duplicate connections
exceeding the allowed open file handles. This causes the command to fail.
Caching the connections to prevent duplicate handles.
> [multi-asic] Cache connection handles to prevent duplicate

- src/sonic-config-engine/minigraph.py
It should be handled by `ConfigDBConnector.typed_to_raw()`.
This is a bug for `sonic-cfggen -m --print-data` only
```
"PORTCHANNEL_MEMBER": {
"PortChannel0001|Ethernet112": {
"NULL": "NULL"
},
"PortChannel0002|Ethernet116": {
"NULL": "NULL"
},
"PortChannel0003|Ethernet120": {
"NULL": "NULL"
},
"PortChannel0004|Ethernet124": {
"NULL": "NULL"
}
},
```
But not appears in `sonic-cfgen -d --print-data`.
```
"PORTCHANNEL_MEMBER": {
"PortChannel0001|Ethernet112": {},
"PortChannel0002|Ethernet116": {},
"PortChannel0003|Ethernet120": {},
"PortChannel0004|Ethernet124": {}
},
```
Tested in a T0 KVM.
> [minigraph] do not use NULL:NULL explicitly in json

- rules/thrift_0_13_0.mk
Correct thrift.0.13.0 dependent package name.
In previous code, the buildout target was named as PYTHON3_THRIFT_0_13_0
But when add the prackage to LIBTHRIFT_0_13_0, it typo as PYTHON_THRIFT_0_13_0
> Correct the pkg name for thrift.0.13.0

- sonic-slave-bullseye/Dockerfile.j2
- sonic-slave-buster/Dockerfile.j2
- sonic-slave-stretch/Dockerfile.j2
Reverts Azure/sonic-buildimage#9317
Since upstream fixed the issue https://github.com/redis/redis-py/pull/1726
We can continue use latest version on master branch.
Fixes https://github.com/Azure/sonic-buildimage/issues/9318
> Revert "Fix redis version during pip3 install"

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vlan_sub_interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan_sub_interface.json
- src/sonic-yang-models/yang-models/sonic-vlan-sub-interface.yang
Add YANG model file for table `VLAN_SUB_INTERFACE`
1. Add YANG model file `sonic-vlan-sub-interface.yang` to describe data structure
2. modify existing unit-test to cover vlan sub interface
Build sonic-yang-models and sonic-yang-mgmt without errors
> [Yang] Add YANG model support for vlan sub interface

- src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vlan.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
- src/sonic-yang-models/yang-models/sonic-port.yang
- src/sonic-yang-models/yang-models/sonic-vlan.yang
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Fixes #9561
Fixes #9570 
Fixes #9563
Partial fix for #9556 
- Attributes for dual ToR configs lack YANG model support
- Extend YANG tests to cover dual ToR use cases
- Extend YANG model to cover dual ToR use cases
- Reduce the default log level to warning so only test failures are printed
- Run the YANG model unit tests
> [YANG]: Add support for dual ToR attributes

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/feature.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/feature.json
- src/sonic-yang-models/yang-models/sonic-feature.yang
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
* Add boolean as typedef to sonic-types
* Fix boolean in sonic-feature yang model
* Fix boolean in sonic-flex_counter yang model
Signed-off-by: Mykola Gerasymenko <mykolax.gerasymenko@intel.com>
It was request to cherry-pick fix from master (#9418) to 202111 branch to fix issue when boolean is used in different literal cases.
Added boolean to sonic-types as typedef with different literal cases.
Run the command config interface breakout <interface_name> <breakout_mode>
> [DPB][YANG] Fix cases when boolean is used in different literal cases

- src/sonic-build-hooks/scripts/buildinfo_base.sh
When build docker-sonic-mgmt image, variable USER is not set.
Replace USER with whoami
> [build] docker-sonic-mgmt replace USER by whoami

- src/sonic-config-engine/tests/sample-voq-graph.xml
Config db schema generated by minigraph can’t pass yang validation, bgp_asn must not be None.
Update sampe-voq-graph.xml to add bgp_asn.
Run command 'sonic-cfggen -m tests/sample-voq-graph.xml -p tests/voq-sample-port-config.ini --print-data', and check bgp_asn.
Fix #9576
> [sonic-cfggen]: Add bgp asn for yang validation

- src/sonic-yang-models/tests/yang_model_tests/tests/aaa.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/aaa.json
- src/sonic-yang-models/yang-models/sonic-system-aaa.yang
AAA yang model is not up to date.
Add fallback and trace field, and replace boolean_type
Run UT for sonic_yang_models.
Follow the steps from #9710 
Fix #9710
> [yang]: Update AAA yang models

- device/accton/x86_64-accton_as7326_56x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7726_32x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7816_64x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as9716_32d-r0/pddf/pddf-device.json
- platform/broadcom/sonic-platform-modules-accton/as4630-54te/utils/accton_as4630_54te_util.py
- platform/broadcom/sonic-platform-modules-accton/as7312-54x/utils/accton_as7312_util.py
- platform/broadcom/sonic-platform-modules-accton/as7315-27xb/utils/accton_as7315_util.py
- platform/broadcom/sonic-platform-modules-accton/as7326-56x/utils/pddf_post_device_create.sh
- platform/broadcom/sonic-platform-modules-accton/as7726-32x/utils/pddf_post_device_create.sh
- platform/broadcom/sonic-platform-modules-accton/as7816-64x/utils/pddf_post_device_create.sh
- platform/broadcom/sonic-platform-modules-accton/as9716-32d/utils/pddf_post_device_create.sh
- platform/broadcom/sonic-platform-modules-accton/as9726-32d/utils/accton_as9726_32d_util.py
Enable pca954x idle_disconnect to avoid possible I2C device address conflict.
Change pca954x device_attr idle_state to -2 (MUX_IDLE_DISCONNECT).
Cat pca954x device_attr idle_state and confirm the value is -2.
[Accton] Enable pca954x devices' idle_disconnect for 5.10 kernel
> [Accton] Enable pca954x i2c mux idle_disconnect for 5.10 kernel

- dockers/docker-snmp/supervisord.conf
resolves https://github.com/Azure/sonic-buildimage/issues/8779
snmpd writes the below error message in syslog :
snmp#snmpd[27]: truncating integer value > 32 bits
This message is written in syslog when the hrSystemUptime(1.3.6.1.2.1.25.1.1.0 / system uptime) or sysUpTime(1.3.6.1.2.1.1.3 network management portion or snmpd uptime) is queried when either of these counters overflow beyond 32 bit value. This happens the device uptime or snmpd uptime is more than 497 days.
Reference: https://access.redhat.com/solutions/367093 and https://linux.die.net/man/1/snmpcmd
To avoid seeing this message if the counter grows, the snmpd error log level is changed to display  LOG_EMERG, LOG_ALERT, LOG_CRIT, and LOG_DEBUG.
Without this change, …
> [docker-snmp]: Modify log level of snmpd

- platform/mellanox/hw-management/Makefile
Taken from https://github.com/Azure/sonic-buildimage/pull/9539
To fix an issue that hw-mgmt patches were not applied. One patch was already in upstream hw-mgmt package thus applying it again caused an error and no other patches were applied. Also, I did it to improve the Makefile, so that the make will fail in case patches fail to apply.
Removed obsolete patch, made applying patches a hard failure in the build.
Run the make and verify patches are applied.
> [Mellanox] [202012] fail the build when hw-mgmt patches do not apply

- device/accton/x86_64-accton_as9716_32d-r0/Accton-AS9716-32D/th3-as9716-32x400G.config.bcm
- device/arista/x86_64-arista_7060dx4_32/Arista-7060DX4-C32/th3-a7060dx4-c32-32x400G.config.bcm
- device/arista/x86_64-arista_7060px4_32/Arista-7060PX4-C64/th3-a7060px4-32-64x100G.config.bcm
- device/arista/x86_64-arista_7060px4_32/Arista-7060PX4-O32/th3-a7060px4-o32-32x400G.config.bcm
- device/celestica/x86_64-cel_silverstone-r0/Silverstone-128x100/th3-128x100G.config.bcm
- device/celestica/x86_64-cel_silverstone-r0/Silverstone/th3-32x400G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-C32/th3-z9332f-32x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-M-O16C64/th3-z9332f-16x400G-64x100G.config.bcm
- device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/th3-z9332f-32x400G.config.bcm
- device/delta/x86_64-delta_agc032-r0/Delta-agc032/th3-agc032-32x400G.config.bcm
- device/quanta/x86_64-quanta_ix9_bwde-r0/Quanta-IX9-32X/th3-ix9-32x400G.config.bcm
- src/sonic-device-data/tests/permitted_list
This is to fix issue reported by (https://github.com/Azure/sonic-buildimage/issues/8558)
The fix requires 2 changes:
1.  in BRCM SAI 4.3.5.2 which can be found in this PR (https://github.com/Azure/sonic-buildimage/pull/9754)
2.  This PR itself where it needs to set 2 SOC properties in order to activate the code changed in BRCM SAI 4.3.5.2
1. Repeat the steps documented in issue (https://github.com/Azure/sonic-buildimage/issues/8558) without these 2 SOC properties on a TH3 based HWSKU (Z9332F) and with any BRCM SAI (including 4.3.5.2) and see the issue.
2. Enable these two SOC properties and repeat the same steps again with Z9332F running with BRCM SAI 4.3.5.2 and observe that the problem no longer can be reproduced.
Once verified that the fix that went into SAI 4.3.5.2 is also present in …
> [202012][BRCM TH3] Add SOC properties to prevent FDB events during warmboot

- Makefile.cache
- rules/linux-kernel.dep
Improve the linux kernel build cache hit rate.
Current the the hit rate is around 85.8% (based on the last 3 month, 3479 PR builds totally, 494 PR build not hit).
We can improve the hit rate up to 95% or better.
The Linux kernel build will take really long time, most of the PRs are nothing to do with the kernel change. The remaining cache options should be enough to detect the Linux kernel cache status (dirty or not).
Some of the file changes are not relative to the Linux kernel build, such as sonic-slave-stretch/Dockerfile.j2, we can exclude it.
> [Build]: Improve the linux kernel build cache hit rate

- device/arista/x86_64-arista_7050_qx32s/default_sku
Booting SONiC on a 7050QX-32S without configuration led to a broken state.
This happened because the previous default_sku uses a `hwsku.json` which is incompatible with `platform.json`
This product has this capability of either enabling the first 4 SFP(1-4) ports or the first QSFP(5).
It is currently not possible to express this in terms of SONiC DPB.  
Change the `default_sku` to point to the 32x40G DPB HwSku for the 7050QX-32S.
Allowing the broken HwSku to work will be a much bigger task, but this should be good enough for now.
Fixes https://github.com/Azure/sonic-buildimage/issues/9090 and https://github.com/aristanetworks/sonic/issues/35
Boot SONiC without minigraph.xml nor config_db.json, validates that ports show up in `show interface status`
Change default_sku for 7050QX-32S
> [Arista] Change default_sku for 7050QX-32S

- dockers/docker-dhcp-relay/cli/clear/plugins/clear_dhcp6relay_counter.py
Import issue will cause:
root@sonic:/# sudo sonic-clear arp
failed to import plugin clear.plugins.dhcprelay: No module named 'show_dhcp_relay'
Fix the import.
run sudo sonic-clear arp
> [dhcp_relay] Fix import for dhcp_counters on clear_dhcp6relay_counter.py

- device/celestica/x86_64-cel_seastone_2-r0/plugins/sfputil.py
- device/celestica/x86_64-cel_seastone_2-r0/sonic_platform_config/event.py
- device/celestica/x86_64-cel_seastone_2-r0/sonic_platform_config/sfp.json
- platform/broadcom/sonic-platform-modules-cel/debian/rules
I noticed `show interfaces transceiver presence` was not showing correct state for our inserted transceivers
Redis database was missing `TRANSCEIVER_INFO` keys and found out that xcvrd process was crashing:
```
Dec 28 22:54:12.246211 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd Traceback (most recent call last):
Dec 28 22:54:12.246246 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 8, in <module>
Dec 28 22:54:12.246280 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     sys.exit(main())
Dec 28 22:54:12.247190 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd.py", line 1441, in main
Dec 28 22:54:12.247190 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     xcvrd.run()
Dec 28 22:54:12.247190 ixp-kg-sw1 INFO pmon#/supervisord: …
```
> [Celestica Seastone2] Build correct platform files

- platform/barefoot/bfn-modules/debian/control
- platform/barefoot/bfn-modules/debian/rules
- platform/barefoot/sonic-platform-modules-bfn-montara/debian/control
- platform/barefoot/sonic-platform-modules-bfn-montara/debian/rules
- platform/barefoot/sonic-platform-modules-bfn-newport/debian/control
- platform/barefoot/sonic-platform-modules-bfn-newport/debian/rules
- platform/barefoot/sonic-platform-modules-bfn/debian/control
- platform/barefoot/sonic-platform-modules-bfn/debian/rules
- platform/barefoot/sonic-platform-modules-wnc-osw1800/debian/control
- platform/barefoot/sonic-platform-modules-wnc-osw1800/debian/rules
Build failed.
Due to the error message looks like build failed because `pyversions` utility was not found.
`pyversions` utility is a part of `python2-minimal` package and it wasn't installed.
To avoid installing python2 just specify explicit python version `--with python3` and use build system for py3 `--buildsystem=pybuild`
Run build
Fix SONiC build.
> [dockers] Barefoot fix bulleye build

- Makefile.work
According to official README, command has changed.
https://github.com/multiarch/qemu-user-static/pull/78
> Update multiarch related command.

- files/image_config/sudoers/sudoers
Prevent radius passkey and snmp community string into syslog.
Add radius and snmp config command to PASSWD_CMDS
Run and pass all UTs.
Add radius and snmp config command to PASSWD_CMDS to prevent radius passkey and snmp community string into syslog.
> [image]: Prevent radius passkey and snmp community string into syslog. 

- src/sonic-yang-mgmt/sonic_yang_ext.py
To fix https://github.com/Azure/sonic-buildimage/issues/9606 
root@sonic:~# config interface breakout Ethernet0 1x400G -y -f -v
Running Breakout Mode : 4x100G
Target Breakout Mode : 1x400G
Ports to be deleted :
{
"Ethernet0": "100000",
"Ethernet2": "100000",
"Ethernet4": "100000",
"Ethernet6": "100000"
}
Ports to be added :
{
"Ethernet0": "400000"
}
After running Logic to limit the impact
Final list of ports to be deleted :
{
"Ethernet0": "100000",
"Ethernet2": "100000",
"Ethernet4": "100000",
"Ethernet6": "100000"
}
Final list of ports to be added :
{
"Ethernet0": "400000"
}
sonic_yang(3):Yang Models Load failed:[priority,] message string
Yang Models Load failed
[priority,] message string
ConfigMgmt Class creation failed
Failed to break out Port. Error: Failed to load the config. Error: …
> [DPB] Fix verbose mode issue

- device/mellanox/x86_64-mlnx_msn4410-r0/system_health_monitoring_config.json
- device/mellanox/x86_64-mlnx_msn4600-r0/system_health_monitoring_config.json
- device/mellanox/x86_64-mlnx_msn4700-r0/system_health_monitoring_config.json
For MSN4410/MSN4600/MSN4700 now they can support fetching PSU voltage threshold, no need to skip the psu voltage check in system health monitoring, so update the system health monitoring configuration file for these platforms.
remove skip PSU change config from the system_health_monitoring_config.json file
Build image run on these platforms, system health monitoring will not report error against PSU voltage
> [Mellanox] update system_health_monitoring_config for MSN4410/MSN4600/MSN4700

- device/celestica/x86_64-cel_seastone_2-r0/led_proc_init.soc
The DX030 platform has all LEDs shining green, no port status indication.
Looking at other platforms that are Trident 3 based, we figured out that the LED configuration blobs are checked in but not loaded. We tested a few different ways of loading these blobs and the proposed one worked fine.
Tested on a Celestica Seastone2 DX030 switch
Testing scenarios:
- Various QSFP ports in both normal and breakout config.
- 100G and 40G link speed show different colors.
- SFP1 port works.
Data forwarding of course still works.
Reason: Having the LEDs work is considered essential for a lot of people when considering platforms.
cel/seastone2: Enable interface LEDs
> [Celestica/Seastone2] Load interface LEDs

- dockers/docker-dhcp-relay/cli-plugin-tests/test_show_dhcp_relay.py
- dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py
We want to move DHCP_RELAY CLI away from VlanBrief.
Delete dhcpv6_servers from VlanBrief. 
"Show vlan brief" will no longer output dhcpv6 servers.
Run "show vlan brief"
> [dhcp_relay] Remove dhcpv6 servers from VlanBrief

- src/sonic-yang-models/tests/yang_model_tests/tests/bgp.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp.json
- src/sonic-yang-models/yang-models/sonic-bgp-common.yang
- src/sonic-yang-models/yang-models/sonic-bgp-monitor.yang
- src/sonic-yang-models/yang-models/sonic-bgp-neighbor.yang
end2end test is blocked by Yang model for BGP monitor.
Create new yang files for BGP monitor, and add UT.
Follow the steps in #9711.
Run UT for sonic-yang-models.
Fix #9711
> [yang]: Add Yang models for BGP monitor

- src/sonic-config-engine/minigraph.py
ConfigDB schema generated by minigraph parser can't pass yang validation.
Modify minigraph.py, and use 'state' to replace 'status'.
Run UT for sonic-config-engine.
Use minigraph parser to generate ConfigDB schema, and run yang validation.
Fix #9551
> [sonic-cfggen]: Feature should use 'state' to replace 'status'

- device/arista/x86_64-arista_7800_sup/platform.json
- device/arista/x86_64-arista_7800r3_48cq2_lc/platform.json
- device/arista/x86_64-arista_7800r3_48cqm2_lc/platform.json
Add missing platform.json configuration files for chassis skus
Needed for the chassis testing effort
Add missing platform.json configurations for chassis sup and linecards
> [Arista] Add platform.json configs for all chassis SKUs

- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-types.yang.j2
Fixes https://github.com/Azure/sonic-buildimage/issues/9638
ACL have ACCEPT action indeed, but yang doesn't support it.
Add 'ACCEPT' enum to sonic-types.yang.j2
Run the YANG model unit tests
> [yang] support acl ACCEPT action

- build_image.sh
Fix https://github.com/Azure/sonic-buildimage/issues/9759
`sonic-broadcom-dnx.bin` should be able to installed on DNX supported platform, whereas it doesn't.
Changed `CONFIGUTED_PLATFORM` to `TARGET_MACHINE` to distinguish `broadcom` and `broadcom-dnx`
tar `sonic-broadcom-dnx.bin` and verify its `platforms_asic` contians dnx platforms
> [broadcom-dnx] Fix dnx image and dnx platform mismatch issue

- dockers/docker-fpm-frr/base_image_files/TSA
- dockers/docker-fpm-frr/base_image_files/TSB
- dockers/docker-fpm-frr/base_image_files/TSC
Add TSA/B/C dualtor support
For TSA, toggle all the mux to standby if the device type is `dualtor` and there are active mux ports.
For TSC, add mux status output.
Run TSA/B/C on a dualtor setup
> Add dualtor TSA/B/C support

- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/port_config.ini
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t0.config.bcm
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t1.config.bcm
To fix https://github.com/Azure/sonic-buildimage/issues/9475
Added 10G ports back.
Check whether Orchagent crashes after the fix. Verify syslogs,CLI commands
> Dell S6100: Addition of 10G ports

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Minigraph parser added a new field 'cluster' to device_metadata, and then yang validation is blocked.
Add 'cluster' to  device_metadata yang models.
Run UT for sonc-yang-models.
Use minigraph parser to generate ConfigDB schema and run yang validation.
Fix #9699
> [yang]: Update yang models to support 'cluster'

- src/dhcp6relay/src/configInterface.cpp
- src/dhcp6relay/src/relay.cpp
1. the strcpy and buffer allocation is not safe, it corrupts 1 byte on the stack. Depending on the memory layout, it may or may not cause issue immediately.
2. message type is not validated before updating the counter. Which could cause segment fault.
1. Remove the unsafe strcpy, use config->interface.c_str() instead.
2. Check message type before updating counters.
The issue (1) caused segment fault on a specific platform. The fix was validated there. Issue (2) was precautionary. Added log in case it triggers.
> [dhcp6relay] a couple memory access protections

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
Python select.select accept a optional timeout value in seconds, however, the value passes to it is a value in millisecond.
Transfer the value to millisecond.
Manual test
> [Mellanox] Fix select timeout in sfp event

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
Fix issue: 'sx_port_mapping_t' object has no attribute 'slot_id'. sx_port_mapping_t only has attribute slot.
Change slot_id to slot.
Manual test
> Fix issue: 'sx_port_mapping_t' object has no attribute 'slot_id'

- src/system-health/health_checker/manager.py
- src/system-health/health_checker/service_checker.py
- src/system-health/health_checker/utils.py
- src/system-health/scripts/healthd
- src/system-health/tests/test_system_health.py
Depends on https://github.com/Azure/sonic-utilities/pull/2022. Suggest merge order:
1. Merge https://github.com/Azure/sonic-utilities/pull/2022 first
2. Merge this and update sonic-utilities submodule pointer
For SYSTEM READY feature. Currently, there is a booting stage in system health service to indicate that the system is loading SONiC component. This booting stage is no longer needed because SYSTEM READY feature will treat that stage as system "NOT READY".
1. Remove booting stage
2. Adjust unit test cases
1. Manual test
2. Unit test
3. sonic-mgmt Regression
> [system-health] Remove booting stage in system health service

- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/port_config.ini
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t0.config.bcm
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t1.config.bcm
This reverts commit 533471231af6a59d81b92312e3e779d7ff94f6bb.
Master image build break - changes to reviewed and re-merged with appropriate fix
```
====================================================================== 
FAIL: test_buffers_dell6100_render_template (tests.test_j2files.TestJ2Files) 
---------------------------------------------------------------------- 
Traceback (most recent call last): 
File "/sonic/src/sonic-config-engine/tests/test_j2files.py", line 246, in test_buffers_dell6100_render_template 
self._test_buffers_render_template('dell', 'x86_64-dell_s6100_c2538-r0', 'Force10-S6100', 'sample-dell-6100-t0-minigraph.xml', 'buffers.json.j2', 'buffers-dell6100.json') 
File "/sonic/src/sonic-config-engine/tests/test_j2files.py", line 243, in _test_buffers_render_template …
```
> Revert "Dell S6100: Addition of SFP ports (#9820)"

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/feature.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/feature.json
- src/sonic-yang-models/yang-models/sonic-feature.yang
Backport https://github.com/Azure/sonic-buildimage/pull/9587
The feature state can be a jinja template, like in this file - https://github.com/Azure/sonic-buildimage/blob/master/files/build_templates/init_cfg.json.j2#L39.
Without this change it is not possible to validate a configuration file.
Relaxes the constraint on feature state. Feature state leaf can be any string.
Run UT.
> [202111][sonic-yang] fix the feature state type (#9587)

- src/dhcp6relay/src/configInterface.cpp
- src/dhcp6relay/src/relay.cpp
This is a cherry-pick of PR https://github.com/Azure/sonic-buildimage/pull/9851
the strcpy and buffer allocation is not safe, it corrupts 1 byte on the stack. Depending on the memory layout, it may or may not cause issue immediately.
message type is not validated before updating the counter. Which could cause segment fault.
Remove the unsafe strcpy, use config->interface.c_str() instead.
Check message type before updating counters.
The issue (1) caused segment fault on a specific platform. The fix was validated there. Issue (2) was precautionary. Added log in case it triggers.
> [201811][dhcp6relay] a couple memory access protections

- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-models/yang-models/sonic-lldp.yang
If the grouping is in the same file in the module, fetching the grouping fails
fixing the `uses_module_name` when the grouping is under the same file
Enabled a grouping under the same file which is `lldp`, there is a test in sonic-yang-mgmt that translates `sample-config-db` into yang format. This test passes with grouping in `lldp` used.
> [yang] Fixing groupings when grouping is in the same module file

- platform/marvell-armhf/sai.mk
Move marvell armhf SAI deb to 1.9.1 to address build failures.
> [Marvell] Update armhf SAI deb version 1.9.1

- device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D48C8/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C49S1/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D28C50/sai.profile
- dockers/docker-orchagent/docker-init.sh
- dockers/docker-orchagent/swssconfig.sh
- dockers/docker-orchagent/vxlan.json.j2
- rules/sonic-config.dep
Need to:
- remove obsolete parameter that enables static VXLAN src port range 
- provide functionality no generate json config file according to appropriate parameter in **config_db**
Done for
SN3800:
• Mellanox-SN3800-D28C50
• Mellanox-SN3800-C64
• Mellanox-SN3800-D28C49S1 (New 10G SKU)
SN2700:
• Mellanox-SN2700-D48C8
- Remove SAI_VXLAN_SRCPORT_RANGE_ENABLE=1 from appropriate sai.profile files
- Created **vxlan.json** file and added few params that depends on DEVICE_METADATA.localhost.vxlan_port_range
File **/etc/swss/config.d/vxlan.json**  should be generated inside swss docker when it restart
```
[
{
"SWITCH_TABLE:switch": {
"vxlan_src": "0xFF00",
"vxlan_mask": "8"
},
"OP": "SET"
}
]
```
> [Mellanox][VXLAN] add params to vxlan.json file in order to configure VXLAN src port range feature

- src/dhcp6relay/src/relay.cpp
- src/dhcp6relay/src/relay.h
Allow dhcp6relay to relay DHCPv6 Relay messages.
Encapsulate Relay-Forward message in a new Relay-Forward message. No changes needed on the Relay-Reply from server.
Send a Relay Forward message, check if a new Relay Forward message was constructed and sent to the servers.
Tested with https://github.com/Azure/sonic-mgmt/pull/5051
> [dhcp6relay] Support relaying Relay-Forward message

- dockers/docker-dhcp-relay/cli-plugin-tests/test_show_dhcpv6_helper.py
Spun out from discussion in #9826 - https://github.com/Azure/sonic-buildimage/pull/9826#discussion_r796239870
docker-dhcp-relay: Fix test call to MockConfigDb
None this time ;-)
> docker-dhcp-relay: Fix test call to MockConfigDb

- files/image_config/bash/bash.bashrc
- files/image_config/sudoers/sudoers
Signed-off-by: Prince George <prgeor@microsoft.com>
The default sudo [password prompt timeout](https://www.sudo.ws/docs/man/1.7.10/sudoers.man/#:~:text=disable%20word%20wrap\).-,passwd_timeout,-Number%20of%20minutes) is NOT working. This is causing the console session to be held up even though the user in active for a long period of time. Due to this, TMOUT or auto-logout is not taking effect because user cannot login to bash, leaving the console unusable.
Explicitly set the password prompt timeout in sudoers
Verified 
1. The sudo password prompt timeout after 5 mins of inactivity
2. After user has logged in to bash via console, the session timeout if user has not pressed key for more than 15 mins (TMOUT)
- [x ] 202106
> Close console session due to user inactivity

- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t0.config.bcm
- device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/th-s6100-64x40G-t1.config.bcm
To fix #9475
**How I did it**
Added 10G ports back.
**How to verify it**
Check whether Orchagent crashes after the fix. Verify syslogs,CLI commands
> [Dell S6100] Addition of 10G ports

- installer/x86_64/install.sh
The test plan described in the `How to verify it` section caused an issue when 3 images (instead of 2) were present when executing `show boot` or `sonic-installer list` commands:
```
root@sonic:/home/admin# show boot
Current: SONiC-OS-master.0-dirty-20220118.165941
Next: SONiC-OS-master.0-dirty-20220118.165941
Available: 
SONiC-OS-master.0-dirty-20220118.165941
SONiC-OS-202012.201-a0376a6e5_Internal
SONiC-OS-202012.201-a0376a6e5_Internal_RPC
```
Fixed the `sed` pattern to match the current image revision in the `install.sh` script.
Test plan:
1. Install the `imageA` by using ONIE
2. Install the `imageA-rpc` by using `sonic-installer`
3. Reboot the switch
4. Swap to the `imageA` - `sonic-installer set-default imageA`
5. Reboot the switch
6. …
> [install.sh] Fixed the sed pattern to match the current image revision

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/qos.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/qos.json
- src/sonic-yang-models/yang-models/sonic-scheduler.yang
PR9611 - sonic-scheduler.yang pattern issue
Modified the scheduler name pattern string to accept any string 
Sonic yang tests
> [yang] Fix for sonic-scheduler.yang name pattern

- device/accton/x86_64-accton_as7726_32x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7726_32x-r0/pmon_daemon_control.json
- platform/broadcom/sonic-platform-modules-accton/as7726-32x/modules/Makefile
- platform/broadcom/sonic-platform-modules-accton/as7726-32x/modules/pddf_custom_psu.c
This DUT support different PSU
Add drv code to read from PSU eeprom to get model name and then get serial number
Test via pddf_psu cmd,
root@sonic:/home/admin# pddf_psuutil mfrinfo
PSU    Status    Manufacturer ID    Model       Serial              Fan Airflow Direction
-----  --------  -----------------  ----------  ------------------  -----------------------
PSU1   OK        ACBEL              FSF019-611  FSF0192105002864    EXHAUST
PSU2   OK        3Y POWER           YM-2651Y    SA070V581905000055  EXHAUST
> [AS7726-32X] Add to support mulit PSU SN in PDDF

- dockers/docker-orchagent/tunnel_packet_handler.py
The tunnel packet handler gradually leaks memory
- Remove call to the `link_lookup` method from the Pyroute2 library
- Use the `store=0` argument for the Scapy sniffer
- Run the packet handler and observe SWSS memory usage using `docker stat`
> [swss]: Reduce tunnel_packet_handler memory usage

- rules/sonic-config.dep
sonic-config-engine unit test always fails. let's restrict using cache in sonic-config-engine
restrict using cache when building sonic-config-engine
sonic-config-engine unit test failing rate is high.
> [build] Add more dependencies to sonic-config-engine

- platform/barefoot/bfn-platform.mk
- platform/barefoot/bfn-sai.mk
- platform/barefoot/docker-syncd-bfn/Dockerfile.j2
- Added support of SAI bridge ports isolation group needed for MC-LAG
```
make init
make configure PLATFORM=barefoot
make all
```
> [BFN] Updated SDK to 20220127_sai_1.9.1

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/chassisdb.conf
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_ndk.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/chassisdb.conf
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/platform_ndk.json
Signed-off-by: Sakthivadivu Saravanaraj <sakthivadivu.saravanaraj@nokia.com>
Added midplane_subnet in chassisdb.conf for interfaces-config.sh to create midplane interface in multi-asic namespaces.
Added midplane_subnet in chassisdb.conf for nokia platforms
Verified all the dockers are up in all IMM's and CPM, ports are up and OC tests are passing.
> [Nokia][platform] Modified Nokia device data to support midplane communication

- device/mellanox/x86_64-mlnx_msn4600c-r0/platform.json
platform.json of 4600C only has 2 CPU core thermal sensors, but there are 4 actually
Added thermal sensors for CPU core 2 and core 3.
Build.
> [Mellanox] Fix issue: 4600C has 4 CPU core thermal sensors

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/test_minigraph_case.py
We need use device type to decide if enable DHCP server in SONiC.
Simply check current device type and decide if enable DHCP server feature flag.
> [sonic-config-engine]: Update minigraph parser to support enable DHCP server for BmcMgmtToRRouter

- device/accton/x86_64-accton_as4630_54pe-r0/pddf/pd-plugin.json
- device/accton/x86_64-accton_as4630_54pe-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as4630_54pe-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as4630_54pe-r0/system_health_monitoring_config.json
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/service/as4630-54pe-pddf-platform-monitor.service
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/service/pddf-platform-init.service
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/__init__.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/event.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/fan.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/platform.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/psu.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/watchdog.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform_setup.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/accton_as4630_54pe_pddf_monitor.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/pddf_post_device_create.sh
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/utils/pddf_switch_svc.py
- platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as4630-54pe.install
- platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as4630-54pe.postinst
Support PDDF
Implement PDDF related code
Test pddf cmd.
root@sonic:/usr/local/bin# pddf_psuutil seninfo
PSU    Status      Output Voltage (V)    Output Current (A)    Output Power (W)    Temperature1 (C)    Fan1 Speed (RPM)
-----  --------  --------------------  --------------------  ------------------  ------------------  ------------------
PSU1   NOT OK                    0.00                  0.00                0.00               39.00                   0
PSU2   OK                       54.44                  0.83               54.00               30.00               12896
root@sonic:/usr/local/bin#
root@sonic:/usr/local/bin#
root@sonic:/usr/local/bin# pddf_psuutil mfrinfo
PSU    Status    Manufacturer ID    Model       Serial …
> [AS4630-54PE] Add to support PDDF

- device/accton/x86_64-accton_as7712_32x-r0/pddf/pd-plugin.json
- device/accton/x86_64-accton_as7712_32x-r0/pddf/pddf-device.json
- device/accton/x86_64-accton_as7712_32x-r0/pmon_daemon_control.json
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/service/as7712-pddf-platform-monitor.service
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/service/pddf-platform-init.service
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/__init__.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/component.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/eeprom.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/event.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/fan.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/platform.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/psu.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/watchdog.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform_setup.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/utils/accton_as7712_pddf_monitor.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/utils/pddf_switch_svc.py
- platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7712-32x.install
- platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7712-32x.postinst
Add to support PDDF
Implement needed code.
Test via pddf cmd.
root@sonic:/home/admin# pddf_psuutil seninfo
PSU    Status       Output Voltage (V)    Output Current (A)    Output Power (W)    Temperature1 (C)    Fan1 Speed (RPM)
-----  -----------  --------------------  --------------------  ------------------  ------------------  ------------------
PSU1   NOT PRESENT  N/A                   N/A                   N/A                 N/A                 N/A
PSU2   OK           11.906                17.218                205.0               26.0                6200
root@sonic:/home/admin# pddf_psuutil mfrinfo
PSU    Status       Manufacturer ID    Model    Serial              Fan Airflow Direction
-----  -----------  ----------------- …
> [AS7712-32X] Add to support PDDF

- dockers/docker-snmp/snmpd.conf.j2
The SNMP contact was not generating correctly when a docker container was restarted.
Root Cause: 
This was an incompatibility between python2 vs python3. 
```
>>> from swsssdk import ConfigDBConnector, SonicV2Connector, SonicDBConfig
>>> config_db = ConfigDBConnector()
>>> config_db.connect()
>>> SNMP = config_db.get_table('SNMP')
>>> SNMP['CONTACT'].keys()[0]
'SN:MT2115X12126;Asset:12518181;PIN:mls-dla_tor_leaf;'
>>>
Python3
>>> config_db = ConfigDBConnector()
>>> config_db.connect()
>>> SNMP = config_db.get_table('SNMP')
>>> SNMP 
{'LOCATION': {'Location': 'public'}, 'CONTACT': {'SN:MT2115X12126;Asset:12518181;PIN:mls-dla_tor_leaf;': 'labneteng@microsoft.com'}}
>>> 
>>> 
>>> 
>>> SNMP['CONTACT'] …
```
> updated jinja template for snmp contact python2 vs python3 issue

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Fixing the issue https://github.com/Azure/sonic-buildimage/issues/9915
Added 'not-provisioned' as a supported value for type field in DEVICE_METADATA type. This value is set during initial ZTP bring up
Added UT to verify it.
> [yang] Adding not-provisioned to type field in DEVICE_METADATA table

- platform/broadcom/sai.mk
Upgrade Broadcom SAI to version 3.5.3.8 to installnclude following fixes:
CS00012225760, CS00012212820, CS00012215529, CS00012218100
> [bcmsai] upgrade Broadcom SAI to 3.5.3.8

- files/Aboot/boot0.j2
Added a kernel parameter to add quirks to 
> [201811][Arista] Add emmc quirks for Upperlake

- files/Aboot/boot0.j2
Added a kernel parameter to add quirks to 
> [201911][Arista] Add emmc quirks for Upperlake

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
Fix issue: SFP index got from get_change_event is wrong when an xSFP module is plugged in/out
The error message like `Fail to re-initialize SFP 54 - IndexError('list index out of range')` is observed.
Manually test and regression test.
> [Mellanox] Fix issue: SFP index got from get_change_event is wrong when an xSFP module is plugged in/out

- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/sai.profile
- device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D112C8/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-C64/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D100C12S2/sai.profile
- device/mellanox/x86_64-mlnx_msn4600c-r0/Mellanox-SN4600C-D48C40/sai.profile
Need to remove old static configs from sai.profile files.
New implementation: https://github.com/Azure/sonic-swss/pull/1959
New configuration: https://github.com/Azure/sonic-buildimage/pull/9658
remove SAI_VXLAN_SRCPORT_RANGE_ENABLE=1 lines from files per HWSKU
When static config is removed folloving test will fail (src port will be in range 0-255)
py.test vxlan/test_vnet_vxlan.py --inventory "../ansible/inventory, ../ansible/veos" --host-pattern (testbed)-t0 --module-path ../ansible/library/ --testbed (testbed)-t0 --testbed_file ../ansible/testbed.csv --allow_recover --assert plain --log-cli-level info --show-capture=no -ra --showlocals --disable_loganalyzer --skip_sanity --upper_bound_udp_port 65535 --lower_bound_udp_port 64128
> [mellanox][vxlan] remove old static config for VXLAN src port range feature 

- device/mellanox/x86_64-mlnx_msn4410-r0/platform_components.json
The chassis name in MSN4410 platform_components.json is not correct
fix the chassis name
run relevant platform API test
> [Mellanox] fix MSN4410 chassis name in platform_components.json

- slave.mk
It prints too many unuse logs in marvell-armhf build. See https://dev.azure.com/mssonic/build/_build/results?buildId=71963&view=logs&j=268525a4-f0a8-5106-2898-2602f02ebdb0&t=59457689-49a2-5da2-bad6-5355ff2da0c7
It is caused by the bad format of the marvell sai package mrvllibsai_armhf_1.7.1-6.deb, see https://github.com/Azure/sonic-buildimage/blob/b621dafff77642db541553f5a2f8ec85e70ea695/platform/marvell-armhf/sai.mk#L4 and https://github.com/Marvell-switching/sonic-marvell-binaries/tree/master/armhf/sai-plugin, the expected package is mrvllibsai_1.7.1-6_armhf.deb, in the format as below:
```
<PackageName>_<VersionNumber>-<DebianRevisionNumber>_<DebianArchitecture>.deb
```
It is not to fix the marvell package name, only add waiting time to reduce the issue, print less logs.
Add relative …
> [Build]: Fix hundreds of thousands lines of logs printed in marvell-armhf build

- platform/broadcom/sonic-platform-modules-dell/z9332f/scripts/z9332f_platform.sh
Following thermalctld warning is seen in DellEMC Z9332f platform:
Feb  8 07:14:47.349301 str2-z9332f-05 WARNING pmon#thermalctld: Update fan and temperature status took 33.02897024154663 seconds, there might be performance risk
ipmi_si driver is polling more frequently and causes delay in processing IPMI query.
Modified ipmi_si polling time.
Check syslogs after the fix and verify whether warning logs are present
UT logs:
[thermalctl_UT.txt](https://github.com/Azure/sonic-buildimage/files/8053279/thermalctl_UT.txt)
> DellEMC Z9332f: Fix thermalctld warning logs

- files/build_templates/qos_config.j2
- src/sonic-config-engine/tests/sample-dell-9332-t1-minigraph.xml
- src/sonic-config-engine/tests/sample_output/py2/qos-dell9332.json
- src/sonic-config-engine/tests/sample_output/py3/qos-dell9332.json
- src/sonic-config-engine/tests/test_j2files.py
…DellEMC-Z9332f-M-O16C64
This is to fulfill specific traffic requirements for HWSKUs [DellEMC-Z9332f-O32 & DellEMC-Z9332f-M-O16C64] in production.
For deployment with above HWSKUs, parser will generate configuration file with updated scheduler settings.
Verified that configuration file is generated properly as well as HW settings is good if ResourceType is correctly set for above HWSKUs.
DUT output after applying new settings:-
d chg MMU_QSCH_L0_WEIGHT_MEM_PIPE0 0 12
MMU_QSCH_L0_WEIGHT_MEM_PIPE0.mmu_eb0[0]: <WEIGHT=1,PARITY=1,ECCP=0x13,ECC=3,DATA=1>
MMU_QSCH_L0_WEIGHT_MEM_PIPE0.mmu_eb0[1]: <WEIGHT=1,PARITY=1,ECCP=0x13,ECC=3,DATA=1>
MMU_QSCH_L0_WEIGHT_MEM_PIPE0.mmu_eb0[2]: <WEIGHT=1,PARITY=1,ECCP=0x13,ECC=3,DATA=1>
MMU_QSCH_L0_WEIGHT_MEM_PIPE0.mmu_eb0[3]: …
> Updated traffic scheduler settings for HWSKUs : DellEMC-Z9332f-O32 & DellEMC-Z9332f-M-O16C64

- files/image_config/logrotate/rsyslog.j2
This issue causes negative threshold value and thus deleting log files even when there is enough space.
To fix an issue when log files get deleted even if there is enough space.
Fixed an typo.
Run the portion of the script that calculates threshold, see that the threshold is calculated correctly.
> [rsyslog.j2] fix typo in VAR_LOG_SIZE_KB

- files/image_config/hostcfgd/hostcfgd
There is a small window between load & listen to config-DB. If TACACS config got updated during that gap, the listen will not show it, hence hostcfgd would miss it, until another update.
porting PR #8223, which uses one shot timer to reload tacacs config.
Copy this binary to a 201811 device and 
Run config reload & restart of hostcfd concurrently, multiple times to see, if hostcfgd miss the update or not.
Ran a repeated config reload for testing.
It did succeed.
But it could not really hit the repro, which is kind of expected as it is is very hard to hit the repro in 201811
[_Tweaked code with a log message, that dumps the read value with isTimer to indicate normal load vs via timer_]
```
admin@str-s6000-acs-8:/var/log$ zgrep -i istimer syslog*
syslog:Feb 16 18:53:25.006739 …
```
> hostcfgd: Add one shot timer to reload tacacs config from CONFIG-DB

- files/Aboot/boot0.j2
Added a kernel parameter to add quirks to
> [202012][Arista] Add emmc quirks to boot0

- src/sonic-host-services/scripts/caclmgrd
Fixes #9916.
I detected that all traffic that uses a source port TCP/179 will be allowed with no option of disabling this.
An attacker can trivially send packets with any source port they wish, so this would allow bypassing any control plane ACL.
I removed these statements. They appear to be for allowing BGP, but the needed rules are already present:
- Allow destination port 179
- Allow established connections
If this patch is wrong BGP would not work, so test BGP and see that it works.
Also, you can check in a running instance /without/ this patch that `iptables -vnL` shows that 0 packets have been accepted into the `tcp spt:179` rule.
Reason: Security patch. caclmgrd was introduced in 202012 it seems.
caclmgrd: Remove explicit permit source port 179
> [Security] caclmgrd: remove permit source port 179

- platform/marvell-armhf/sai.mk
- platform/marvell-armhf/sai/Makefile
Fix marvell build break issue, see below:
buildId | jobName | attempt | startTime | branchName | reason | url
-- | -- | -- | -- | -- | -- | --
70560 | marvell_armhf | 1 | 2022-02-07 07:20:06.9566667 | 202012 | pullRequest | https://dev.azure.com/mssonic/build/_build/results?buildId=70560
71680 | marvell_armhf | 1 | 2022-02-11 04:00:26.0200000 | 202012 | schedule | https://dev.azure.com/mssonic/build/_build/results?buildId=71680
71726 | marvell_armhf | 1 | 2022-02-11 07:18:33.1366667 | 202012 | manual | https://dev.azure.com/mssonic/build/_build/results?buildId=71726
71779 | marvell_armhf | 1 | 2022-02-11 08:21:08.3266667 | 202012 | manual | https://dev.azure.com/mssonic/build/_build/results?buildId=71779
71780 | marvell_armhf | 1 | 2022-02-11 08:21:25.0600000 | 202012 | manual | …
> [Build]: Fix marvell sai package version parsing issue

- src/tacacs/pam/0006-handle-bad-password-set-by-sshd.patch
- src/tacacs/pam/Makefile
sshd overrides user password with a bad one, when pre-auth fails.
Refer [PR #9123 ](https://github.com/Azure/sonic-buildimage/pull/9123) for more details
Manual cherry pick of [PR #9123 ](https://github.com/Azure/sonic-buildimage/pull/9123)
1) Pick a user alias that has not logged into the switch yet
2) Add this alias to /etc/tacplus_user
3) Attempt to login as that user
4) Look for the error message in /var/log/syslog
e.g. "Feb 18 19:16:41.592191 sonic ERR sshd[5233]: auth fail: Password incorrect. user: user_xyz"
> libpam: Block sshd's INCORRECT password to AAA server

- platform/broadcom/docker-saiserver-brcm/start.sh
- platform/broadcom/docker-saiserver-brcm/supervisord.conf
Generate the sai.profile base on the brcm j2 file if the sai.profile
is not existing in the dut mounted folder.
Change the supervisor service configuration accordingly.
Testing done:
Add the script and config in dut
saiservice server can start automatically with [systemctl start saiserver]
cherry-pick the change at https://github.com/Azure/sonic-buildimage/pull/10022
> [Cherry-Pick]Generate sai.profile from j2 tempalte when saiserver start

- scripts/build_kvm_image.sh
Info: Attempting file://dev/vdb/onie-installer ...
Info: Attempting file://dev/vdb/onie-installer.bin ...
cp: write error: No space left on device
Failure: local_fs_run():/dev/vdb Unable to copy /tmp/tmp.CPY0ad/onie-installer.bin to tmpfs
vs image is failing. Increase kvm device space.
> [build] Fix tmpfs space not enough issue when building vs image

- build_debian.sh
When upgrading from an older image (with an older kernel that doesn't
support zstd) to 202012, the squashfs filesystem from the 202012 image
can't be mounted on the older image, because zstd was introduced in
4.14, and older images will likely be running 4.9.
Therefore, disable zstd compression in the squashfs image for 202012
image. When upgrading from 202012 to newer images, since 202012 is
running on 4.19, it can read and mount zstd-compressed squashfs images.
This reverts commit 35e88e5f6a743422496d79540e46e4cb464186be.
The kernel in 201811 image (4.9 kernel) doesn't support zstd. In some cases, it may be needed to mount the squashfs image from the new image while the current (old) image is booted. If the squashfs image is compressed with zstd, then it cannot be mounted on a 4.9 …
> [202012] Revert "[build]: Use zstd compression for base filesystem squashfs"

- platform/broadcom/docker-saiserver-brcm/start.sh
- platform/broadcom/docker-saiserver-brcm/supervisord.conf
Generate sai.profile from j2 template when saiserver start
Generate the sai.profile base on the brcm j2 file if the sai.profile
is not existing in the dut mounted folder.
Change the supervisor service configuration accordingly.
Testing done:
Add the script and config in dut
saiservice server can start automatically with [systemctl start saiserver]
> Generate sai.profile from j2 template when saiserver start

- platform/broadcom/sonic-platform-modules-cel/services/platform_api/sonic_platform/eeprom.py
Fixes #10020
The platform api for parsing syseeprom information read from STATE DB has issue
with parsing the value part that has whitespace in the middle. The current
code assumes that the value part does not have whitespace. So everything after
the whitespace will be ignored. The syseeprom values returned from platform
API do not match the output of "show platform syseeprom".
This change improved the regular expression for parsing syseeprom values to
accommodate whitespaces in the value.
Locally updated the code on a dx010 device. Call the platform API:
```
>>> import sonic_platform
>>> platform = sonic_platform.platform.Platform()
>>> chassis = platform.get_chassis()
>>> chassis.get_system_eeprom_info()
{'0x21': 'DX010', '0x22': 'R0872-F0020-02', '0x23': 'DX010B2F030A27BY200002', …
```
> Fix issue of parsing syseeprom value with whitespace in middle

- files/image_config/monit/container_checker
This PR of finding running containers via feature table does not consider 'database' containers as feature in multi-asic devices: https://github.com/Azure/sonic-buildimage/pull/7474
Change in this PR is to add database containers for multi-asic, to always_running_containers, as their status is 'always_enabled'
Before this change on a multi-asic device, container_status says database containers are not running even if they are:
Program 'container_checker'
status Status ok
monitoring status Monitored
monitoring mode active
on reboot start
last exit value 3
last output Expected containers not running: database0, database5, database1, database2, database, database4, database3
data collected Wed, 09 Feb 2022 19:15:35
After change, result of 'monit status':
Program 'container_checker'
status …
> Update container_checker for multi-asic devices when state is 'always_enabled'

- .azure-pipelines/run-test-template.yml
- azure-pipelines.yml
Introduce 2 sub jobs for kvmtest t0 job in sonic-mgmt  repo in PR https://github.com/Azure/sonic-mgmt/pull/4861
But in sonic-buildimage repo, because section parameter is null, it always run the part 2 test scripts in kvmtest t0 job.
It missed the part 1 test scripts in kvmtest.sh.
Split kvmtest t0 job into two sub jobs such as sonic-mgmt repo and run them in parallel to save time.
Submit PR will trigger the pipeline to run.
> Split kvmtest t0 job into two jobs and run in parallel

- src/system-health/health_checker/service_checker.py
swsscommon.ConfigDBConnector does not automatically close connection when the instance is recycled by python. So, it should not create this instance each time calling `check_services`. It will cause error like `Failed to read from file /var/run/hw-management/led/led_status_capability - OSError(24, 'Too many open files')`
Only connect DB once in __init__
Manual test
> [system-health] Fix file handle leak

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal.py
In SONiC thermal control algorithm, it compares thermal zone temperature with thermal zone threshold. Previously, a thermal zone with no thermal sensor can still get its threshold. However, a recently driver patch changes this behavior: a thermal zone with no thermal sensor will return 0 for threshold.  We need to ignore such thermal zone.
Ignore thermal zones whose temperature is 0.
1. Added unit test case
2. Manual test
> [Mellanox] Fix issue: thermal zone threshold value 0 causes fan speed stuck at 100%

- files/scripts/write_standby.py
It is currently possible for the write_standby script to timeout before orchagent is able to create the IPinIP tunnel
Increase the timeout duration to 60 seconds
> [write_standby]: Increase timeout to 60s

- src/tacacs/pam/0007-handle-bad-password-set-by-sshd.patch
Desired the log message destination to be syslog and it misses the critical info.
Non logical code changes only.
Logging update, just for one message only
a) The log message is directed to /var/log/syslog, instead of /var/log/auth.log
b) Include user alias in the message
1. Pick a user alias that has not logged into the switch yet
2. Add this alias to /etc/tacplus_user
3. Attempt to login as that user
4. Look for the error message in /var/log/syslog
e.g. "Feb 18 19:16:41.592191 sonic ERR sshd[5233]: auth fail: Password incorrect. user: user_xyz"
> pam: sshd patch: Update the log message

- dockers/docker-sonic-mgmt-framework/Dockerfile.j2
See https://security.archlinux.org/CVE-2021-33503
Upgrade urllib3 to 1.26.5 to fix the vulnerability.
> [Security]: Upgrade urllib3 to fix CVE-2021-33503

- .azure-pipelines/azure-pipelines-image-template.yml
- sonic-slave-buster/Dockerfile.j2
Upstream breaking change, ref discussion https://github.com/pallets/markupsafe/issues/282
> sonic-slave-buster pins the versions of Jinja2 and MarkupSafe in py3

- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-orchagent/docker-init.j2
- dockers/docker-orchagent/ndppd.conf
- dockers/docker-orchagent/supervisord.conf.j2
- dockers/docker-orchagent/wait_for_link.sh.j2
If the VLAN interface is not up when ndppd starts, it will fail to enable `allmulti` mode on the interface and be unable to process received NDP packets
The following logs are seen:
```
/var/log/syslog.33.gz:Feb 18 10:33:12.825406 sonic INFO swss#/supervisord: ndppd (error) Failed to set allmulti: No such device
```
Use the `wait_for_link` script currently used by `radv` to delay ndppd startup until the vlan interface is ready
Apply the changes to a device. `config reload` the device and confirm that the above error logs are not observed when ndppd starts. Run the `arp/test_arp_dualtor.py::test_proxy_arp` test case and verify it passes.
> [swss]: Wait for vlan intf to start ndppd

- dockers/docker-ptf-sai/Dockerfile.j2
Add xmlrunner python3 version to generate the test report in xunit format
Add xmlrunner python3 version to generate the test report in xunit format
built the ptf-sai docker and check the function with test cases
* local test case for sai testing
> [PTF-SAIv2] Add xmlrunner python3 version to generate test report

- platform/mellanox/hw-management/0003-Remove-unused-non-upstream-kernel-modules-from-load.patch
The latest upgrade of Mellanox hw-mgmt V7.0020.1300 introduced a couple new kernel modules for new Mellanox platforms that have yet to be upstreamed to the linux kernel. 
As these new platforms do not have SONiC support we elected not to upstream these new drivers to sonic-linux-kernel but hw-mgmt expects them to exist which is causing a non-functional error on switch boot. 
```
Feb 15 00:09:55.374130 r-leopard-simx-74 ERR systemd-modules-load[269]: Failed to find module 'emc2305'
Feb 15 00:09:55.374141 r-leopard-simx-74 ERR systemd-modules-load[269]: Failed to find module 'ads1015'
```
To resolve this we can patch hw-mgmt to no longer attempt to load these modules by default. 
Added a SONiC patch to Mellanox hw-mgmt in order to remove the unused kernel modules which were not upstreamed …
> [Mellanox] Add patch to hw-mgmt to prevent loading of non-existant kernel modules

- platform/broadcom/sai.mk
Fix the expiry date on the libsaibcm debian packages.
Update the debian pckages URL.
built sonic-braoadcom.bin image
> [libsaibcm] Fix the expiry date on the libsaibcm debian packages.

- build_debian.sh
Fixes #9548 and #10015
PR #9481 changed auditd's log directory to be /var/log instead of
/var/log/audit, because SONiC mounts a disk image at /var/log during
runtime, and so the /var/log/audit directory might not exist (since it
would've been created during package installation, mounting another
partition at /var/log will hide it). However, for security reasons,
auditd changes the log directory to have 0750 permissions, so that not
everyone knows about the audit logs or read them.
This means that not even admin can list files in /var/log, which is a
regression from previous images.
To fix this, revert the change to auditd's log directory, and tell
systemd to create the audit log directory at runtime if it doesn't
exist. Because the …
> [build_debian.sh]: Fix /var/log having 0750 permissions instead of 0755

- files/build_templates/buffers_config.j2
- src/sonic-config-engine/tests/sample_output/py2/buffers-dell6100.json
- src/sonic-config-engine/tests/sample_output/py2/buffers-mellanox2410-dynamic.json
- src/sonic-config-engine/tests/sample_output/py2/buffers-mellanox2410.json
- src/sonic-config-engine/tests/sample_output/py2/buffers-mellanox2700.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-dell6100.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox2410-dynamic.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox2410.json
- src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox2700.json
amrhf build fails while building sonic-config-engine whl package
https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/77089/logs/9
The reason for the failure is due to the fact that there is a new line generated at the top of the file in buffer config test cases while building for broadcom based platform and this issue is not seen in Marvell based platforms.
Removed the new line for all the buffer test cases as there is no need to add it and accordingly changed the buffer_config.j2 where the new line is generated.
Build sonic-config-engine py2/py3 whl package for both broadcom and Marvell platforms.
> Fix Azure build failures

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/nvgre.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/nvgre.json
- src/sonic-yang-models/yang-models/sonic-nvgre-tunnel.yang
`NVGRE Tunnel` feature extends the Config DB with new tables. These tables require a new YANG model.
Added a new YANG model `sonic-nvgre-tunnel.yang`
Added YANG test cases.
> [nvgre] Added YANG model and tests

- platform/pddf/i2c/utils/pddfparse.py
As per linux kernel 5.10, 'force_deselct_on_exit' parameter used for driver i2c_mux_pca954x is no longer valid. Instead an attribute 'idle_state' is added per MUX device. This needs to be set to 
-1 : For leaving the mux state as is
-2 : For deselecting the channel upon exit
<num> : To always set a channel <num> upon exit
This needs to be accommodated inside the PDDF JSON parser as well.
Added an 'idle_state' dev_attr in the PDDF JSON object related to the MUX
I verified it on AS7712 platform. Below are the logs,
```
root@sonic:/home/admin# cat /sys/bus/i2c/drivers/pca954x/*/idle_state
-2
-2
-2
-2
-2
-2
root@sonic:/home/admin# decode-syseeprom
TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 168
TLV Name             Code Len Value …
```
> Support for idle_state device parameter is required for muxes using i2c_mux_pca954x driver

- platform/broadcom/sonic-platform-modules-accton/as7326-56x/utils/pre_pddf_init.sh
- platform/broadcom/sonic-platform-modules-accton/debian/sonic-platform-accton-as7326-56x.postinst
Modify to check eeprom by pre_pddf_init.sh
Add pre_pddf_init.sh to code base.
Test eeprom and other pddf cmd that are fine
> [as7326-56x] Modify to check eeprom by pre_pddf_init.sh

- dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2
Code review was still in progress when https://github.com/Azure/sonic-buildimage/pull/9858 was merged and upon further testing I have arrived at a better solution. 
Modified supervisord configuration j2 template for pmon to require no minimum uptime for `chassisd_db_init` and to remove the redundant `exit_codes` directive
Boot switch and verify in syslog that there are no errors related to chassis_db_init
[pmon] Clean up supervisord chassis_db_init entry and fix startsecs
> [pmon] Clean up supervisord chassis_db_init entry and fix startsecs

- files/image_config/monit/container_checker
Fixed the monit container_checker fails due to unexpected "database-chassis" docker running on Supervisor card in  the VOQ chassis.  fixes #9042
Added database-chassis to the always running docker list if platform is supervisor card.
Execute the CLI command  "sudo monit status container_checker"
```
admin@sonic:~$ sudo monit status container_checker
Monit 5.20.0 uptime: 22h 18m
Program 'container_checker'
status                       Status ok
monitoring status            Monitored
monitoring mode              active
on reboot                    start
last exit value              0
last output                  -
data collected               Fri, 22 Oct 2021 15:12:50 
```
> [supervisor]monit container-checker failed due to unexpected "database-chassis" docker running

- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py
Fixes https://github.com/Azure/sonic-buildimage/issues/10038
Added 10G ports in sfp_list
Check syslogs, xcvrd status.
UT logs: 
[sfp_ut.txt](https://github.com/Azure/sonic-buildimage/files/8166691/sfp_ut.txt)
> Dell S6100: Fix xcvrd fix

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/bgp.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp.json
- src/sonic-yang-models/yang-models/sonic-bgp-allowed-prefix.yang
end2end test is blocked by Yang model for BGP allowed prefix list.
Create new yang files for BGP allowed prefix list, and add UT.
Run UT for sonic-yang-models.
Fix: #9866
> [yang]: Add yang models for table BGP_ALLOWED_PREFIXES

- files/build/versions/dockers/docker-sonic-mgmt-framework/versions-py3
it is already updated in Dockerfile 
ref: https://github.com/Azure/sonic-buildimage/pull/10024
To fix the build of 202012 branch.
> [build] Fix the urllib3 version in sonic-mgmt-framework constrain file because

- platform/marvell-armhf/sai.mk
- platform/marvell-armhf/sai/Makefile
1) Fixed SAI debian version name issue reported in https://github.com/Marvell-switching/sonic-marvell-binaries/issues/62
2) Implement DHCP, DHCv6 traps as per SAI Specifications
3) Added support to return SAI_STATUS_NOT_SUPPORTED for ERSPAN feature #9830 
Verify the SONiC compilation and SAI functionality.
Fix SAI debian name, DHCP trap and added support to return SAI_STATUS_NOT_SUPPORTED error code for ERSPAN feature #9830
> [Marvell][build] Marvell armhf SAI debian.

- src/sonic-yang-models/tests/yang_model_tests/tests/aaa.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/aaa.json
- src/sonic-yang-models/yang-models/sonic-system-aaa.yang
end2end test is blocked by Yang model for AAA login pattern.
Add pattern to AAA yang models.
Run UT for sonc-yang-models.
Fix #9713
> [yang]: AAA login pattern

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/port.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/port.json
- src/sonic-yang-models/yang-models/sonic-port.yang
Multi-asic platform add aisc_port_name and role to PORT table, and port_index range is changed.
Update sonic-port.yang, add asic_port_name and role, and remove range limitation.
Run UT for sonic-yang-models.
Fix #9580
> [YANG]: Update port Yang models to support multi-asic platform

- files/build_templates/sonic_debian_extension.j2
The marvel-armhf build is hung, it does not exist after waiting for a long time.
I is caused by the process /etc/entropy.py which is started by the postinst script in target/debs/buster/sonic-platform-nokia-7215_1.0_armhf.deb
```
$ cat postinst 
sh /usr/sbin/nokia-7215_plt_setup.sh
...
$ cat usr/sbin/nokia-7215_plt_setup.sh | tail
python /etc/entropy.py &
$ cat etc/entropy.py 
if path.exists("/proc/sys/kernel/random/entropy_avail"):
while 1:
while avail() < 2048:
with open('/dev/urandom', 'rb') as urnd, open("/dev/random", mode='wb') as rnd:
d = urnd.read(512)
t = struct.pack('ii', 4 * len(d), len(d)) + d
fcntl.ioctl(rnd, RNDADDENTROPY, t)
time.sleep(30)
```
It is a workaround to fix the build issue, need to fix debian package, and revert the change.
> Fix marvell-armhf build hung issue

- .azure-pipelines/official-build-cisco-8000.yml
Support to use the cisco sai packages built by azp
Download the sai packages from azure storage and override the sai package which from GitHub release.
Prerequisite tasks: [done]
1. When push on the cisco sai repo, azp will start an Azure Pipeline build.
2. When azp build finished, it will trigger an artifacts uploading pipelines to publish to azure storage.
https://dev.azure.com/mssonic/cisco/_build/results?buildId=76434&view=logs&j=62f941c1-829a-538b-5bf0-e540f1e71cee&t=1762bf4f-25d9-58cc-9916-0fe8be7bbaff
```
Line 40: 2022-02-28T13:29:47.3008983Z + wget 'https://***/cisco-gibraltar-dev_1.47.11.9-sai-1.7.1-buster-911d3aeb1fb_amd64.deb***' -O cisco-gibraltar-dev_1.47.11.9-sai-1.7.1-buster-911d3aeb1fb_amd64.deb
Line 1267: 2022-02-28T13:29:51.4232229Z 2022-02-28 13:29:51 (16.9 MB/s) - …
```
> [Build][Ci]: Support to use the cisco sai packages built by azp

- src/sonic-config-engine/minigraph.py
- src/sonic-config-engine/tests/t0-sample-deployment-id.xml
- src/sonic-config-engine/tests/test_cfggen.py
Config db schema generated by minigraph can’t pass yang validation, deployment_id can’t be none for yang validation.
Update minigraph.py, skip deployment_id with None value
Run UT for sonic-config-enginue.
Run command 'sonic-cfggen -m tests/multi_npu_data/sample-minigraph-noportchannel.xml -p tests/multi_npu_data/sample_port_config-3.ini -n asic3 --print-data'.
Fix #9592
> [sonic-cfggen]: Fix generated deployment_id

- build_image.sh
It is to fix the issue https://github.com/Azure/sonic-buildimage/issues/10048
When building .raw image, for instance, target/sonic-broadcom.raw, it will generate a .bin image, target/sonic-broadcom.bin, as the intermediate file. The intermediate file is a build target which may contains different dependencies with the raw one.
Rename the intermediate file.
> [Build]: Fix the bin image generated from raw image issue

- dockers/docker-sonic-mgmt/Dockerfile.j2
Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>
This PR includes necessary changes for the setup of the Python3  virtual environment in the sonic-mgmt docker container.
1. Connect to the sonic-mgmt container
```
$ docker exec -ti sonic-mgmt bash
```
2. Activate the virtual environment
```
$ source /var/user/env-python3/bin/activate
```
Migration of sonic-mgmt codebase from Python 2 to Python 3
Added all necessary dependencies to the env-python3 virtual environment.
> Add necessary changes for python3 virtual environment of sonic-mgmt docker container

- platform/broadcom/docker-saiserver-brcm/start.sh
- platform/broadcom/docker-saiserver-brcm/supervisord.conf
Generate the sai.profile base on the brcm j2 file if the sai.profile (cherry-pick from #10022)
is not existing in the dut mounted folder.
Change the supervisor service configuration accordingly.
Testing done:
Add the script and config in dut
saiservice server can start automatically with [systemctl start saiserver]
> [Cherry-pick][202111]Generate sai.profile from j2 tempalte when saiserver start

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Fix https://github.com/Azure/sonic-buildimage/issues/9591
Add 'sub_role' to device_metadata yang models.
Run UT for sonc-yang-models.
> [yang]: Update DEVICE_METADATA yang models to support 'sub_role'

- build_debian.sh
Signed-off-by: Pavan Naregundi <pnaregundi@marvell.com>
uboot env get and set commands fw_printenv/fw_setenv are not available in bullseye sonic image. Some platforms using them where failing. Ex: sonic-installer commands in marvell-armhf.
In case of buster, u-boot-tools was providing these commands.
Added libubootenv-tool which provides these tools along with other uboot tools in build_debian.sh. 
root@localhost:~# fw_printenv serverip
serverip=10.4.50.39
root@localhost:~# fw_setenv serverip 10.4.50.38
root@localhost:~# fw_printenv serverip
serverip=10.4.50.38
Fix needs to be backported to releases using bullseye.
Adding libubootenv-tool into bullseye image
> Adding libubootenv-tool into bullseye image

- build_debian.sh
- files/build_templates/sonic_debian_extension.j2
It does not make sense to unmount /proc in the slave container.
It has impact multiple programs, for example:
```
root@8f495bfec510:/# umount /proc
root@8f495bfec510:/# ps -a       
Error, do this: mount -t proc proc /proc
```
Another example, the slave container will become unreachable when /proc unmounted.
```
$ docker exec 8f495bfec510 uname -m
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "close exec fds: open /proc/self/fd: no such file or directory": unknown
```
> [Build]: Fix /proc not mounted issue

- files/image_config/platform/rc.local
- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/fast-reboot_plugin
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform_startup.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/systemd/s6100-platform-startup.service
- To reduce the processing time of rc.local, refactoring s6100 platform initialization.
- Fixing https://github.com/Azure/sonic-buildimage/issues/10150 
```
On branch 202012-s6100-rclocalChanges to be committed:  (use "git restore --staged <file>..." to unstage)
modified:   ../../../../files/image_config/platform/rc.local        
modified:   ../debian/platform-modules-s6100.install        
modified:   scripts/fast-reboot_plugin
modified:   scripts/s6100_platform.sh
renamed:    scripts/s6100_i2c_enumeration.sh -> scripts/s6100_platform_startup.sh
renamed:    systemd/s6100-i2c-enumerate.service -> systemd/s6100-platform-startup.service
```
- Attached UT logs.
[logs.zip](https://github.com/Azure/sonic-buildimage/files/8201021/logs.zip)
- In short,
```
| Images upgraded to                 | …
```
> [202012] Refactoring DELL platform init to reduce rc.local processing time

- files/image_config/logrotate/rsyslog.j2
In parallel of this change Arista added a custom logrotate configuration as part of its driver library.
Having 2 logrotate configuration for the same log file triggers an issue.
Fixes https://github.com/aristanetworks/sonic/issues/38 
Arista merged a few changes in sonic-buildimage which added a logrotate configuration https://github.com/aristanetworks/sonic/commit/e43c7977f7473be67a7e8be7846c9dd71357feae
It is therefore the right path to remove the `arista.log` line from the `logrotate.d/rsyslog` configuration.
Logrotate works without any error message, arista log rotation happens and arista daemons still append logs once file was truncated.
Issue also present on 202111
Remove duplicate arista.log logrotate from logrotate.d/rsyslog
> [Arista] Remove duplicate logrotate configuration for arista.log

- build_debian.sh
[Build]: Clean up pip cache
Fix the issue: https://github.com/Azure/sonic-buildimage/issues/10101
> [Build]: Clean up pip cache

- dockers/docker-sonic-mgmt/Dockerfile.j2
This fix is to address issue: https://github.com/Azure/sonic-mgmt/issues/5280
In the sonic-mgmt Dockerfile, python package `allure-pytest` is installed after `ENV USER $user`.
Consequently the package is installed to path `/home/$user/.local` and is only available to the $user
account. If we use root account in sonic-mgmt docker container to run tests, any script importing
the `allure` package will fail with `ImportError`. We need to install the `allure-pytest` package to global
directory instead of user local directory.
Update the sonic-mgmt Dockerfile to ensure that the `allure-pytest` package is installed to global directory
1. Build a new sonic-mgmt docker image based on the changes.
2. Use sonic-mgmt docker container of the newly built image to run test scripts that depend on the …
> Install the allure-pytest package globally in sonic-mgmt docker

- src/sonic-build-hooks/hooks/apt
- src/sonic-build-hooks/hooks/apt-get
- src/sonic-build-hooks/scripts/buildinfo_base.sh
Fix the debian packages installing in parallel issue.
Add apt hook command to support apt to print no version control info.
Add a file lock, it can block the apt/apt-get installation for 10 min in max if another apt/apt-get installation command is running. It only has effect on the build time.
Clarify the feature to the lock in slave.mk:
Currently, we already has a lock in the slave.mk, it has no effect when installing the package inside of the makefile. Comparing the method, the method in the pr is more general, take effect when using the command apt/apt-get.
And it is not as a replacement for the debian installation lock in the slave.mk, another feature of the lock in slave.mk is to block some of the conflict packages installation, so make the conflict targets not building in the same …
> [Build]: Fix installing dpkg packages in parallel issue

- files/build_templates/sonic_debian_extension.j2
Fix build broken issue, caused by grpc packages cannot be installed
Confirmed by nokia, not need to install for armhf/arm64, see https://github.com/Azure/sonic-buildimage/pull/8366
If really want to support it, we need to install the build tools in the base image.
Exclude the pip3 packages in armhf/arm64
> [Build]: only install grpc in amd64

- files/initramfs-tools/union-mount.j2
When mounting the partition that contains `/host` during initramfs, the
mount binary available there (coming from busybox) tries each filesystem
in `/proc/filesystems` and sees which one succeeds. During this time,
there may be some error messages logged into dmesg because some of the
incorrect filesystems failed to mount the partition.
Specify the filesystem type explicitly so that initramfs knows it's that
type, and we know what filesystem will always get used there.
Fixes #9998
> Specify the filesystem type when mounting to /host

- files/build_templates/sonic_debian_extension.j2
The marvel-armhf build is hung, it does not exit after waiting for a long time.
It is caused by the process /etc/entropy.py which is started by the postinst script in target/debs/buster/sonic-platform-nokia-7215_1.0_armhf.deb
$ cat postinst
sh /usr/sbin/nokia-7215_plt_setup.sh
...
$ cat usr/sbin/nokia-7215_plt_setup.sh | tail
python /etc/entropy.py &
$ cat etc/entropy.py
if path.exists("/proc/sys/kernel/random/entropy_avail"):
while 1:
while avail() < 2048:
with open('/dev/urandom', 'rb') as urnd, open("/dev/random", mode='wb') as rnd:
d = urnd.read(512)
t = struct.pack('ii', 4 * len(d), len(d)) + d
fcntl.ioctl(rnd, RNDADDENTROPY, t)
time.sleep(30)
It is a workaround to fix the build issue, need to fix debian package, and revert the change.
Kill the hung installation process.
Master build …
> [build]: Fix marvell-armhf build hung issue (#10156)

- src/sonic-config-engine/tests/test_j2files.py
When tests in sonic-config-engine failed, there is no detail massage.
Using existing function to show failure details when assert failed.
> Add failure details in sonic-config-engine unit test.

- files/scripts/teamd.sh
This can save 6 sec for teamd LAG restoration - the time between:
```
Mar  9 13:51:10.467757 r-panther-13 WARNING teamd#teamd_PortChannel1[28]: Got SIGUSR1.
Mar  9 13:52:33.310707 r-panther-13 INFO teamd#teamd_PortChannel1[27]: carrier changed to UP
```
Optimize warm boot. Specifically reduce the time needed for LAG restoration.
Kill teamd docker after graceful shutdown of teamd processes.
Run warm reboot.
> [teamd.sh] kill teamd docker on warm shutdown for faster shutdown

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_sfp.py
All the SFP platform API classes need to use SFP refactoring framework. The platforms which use PDDF, derive their SFP API class from a common pddf_sfp.py. Hence pddf_sfp.py needs to comply with SFP refactoring. 
Used sfpOptoeBase class in PddfSfp
Verified with the following logs on AS7326 platform.
```
root@sonic:/home/admin# sfputil show presence
Port        Presence
----------  -----------
Ethernet0   Not present
Ethernet1   Not present
Ethernet2   Not present
Ethernet3   Present
Ethernet4   Present
Ethernet5   Not present
Ethernet6   Present
Ethernet7   Present
Ethernet8   Not present
Ethernet9   Not present
Ethernet10  Not present
Ethernet11  Not present
Ethernet12  Not present
Ethernet13  Not present
Ethernet14  Not present
Ethernet15  Not present
Ethernet16  Not present
Ethernet17 …
```
> Using SFP refactoring framework in PDDF sfp class

- dockers/docker-base-bullseye/Dockerfile.j2
- dockers/docker-base-buster/Dockerfile.j2
- dockers/docker-config-engine-bullseye/Dockerfile.j2
- dockers/docker-config-engine-buster/Dockerfile.j2
- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-sonic-mgmt-framework/Dockerfile.j2
- files/Aboot/boot0.j2
- files/initramfs-tools/varlog
- installer/arm64/install.sh
- installer/armhf/install.sh
- installer/x86_64/install.sh
Reduce the disk space taken up during bootup and runtime.
1. Remove python package cache from the base image and from the containers.
2. During bootup, if logs are to be stored in memory, then don't create the `var-log.ext4` file just to delete it later during bootup.
3. For the partition containing `/host`, don't reserve any blocks for just the root user. This just makes sure all disk space is available for all users, if needed during upgrades (for example).
> Image disk space reduction

- dockers/docker-sonic-mgmt/Dockerfile.j2
Add scapy support for python3 virtual environment in the sonic-mgmt docker container
Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>
Migration of sonic-mgmt codebase from Python 2 to Python 3
Added scapy dependencies to the env-python3 virtual environment.
Run test case
```
py.test --testbed=testbed-t0 --inventory=../ansible/lab --testbed_file=../ansible/testbed.csv --host-pattern=testbed-t0 -- module-path=../ansible/library lldp
```
> Add scapy support for python3 virtual environment in the sonic-mgmt docker container

- platform/broadcom/sonic-platform-modules-dell/common/ipmihelper.py
- platform/broadcom/sonic-platform-modules-dell/common/onie_stage_fwpkg
- platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
- platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/component.py
To update the available and current firmware versions provided by Component APIs
Update the platform API methods in component.py
Verified that component data is displayed by `show platform firmware status`.
Logs: [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/8220041/UT_logs.txt)
DellEMC: Z9332f - Component API Fixes
> DellEMC: Z9332f - Component API Fixes

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan_drawer.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_psu.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_thermal.py
1. fan_drawer support was missing in PDDF common platform APIs. This resulted in 'thermalctld' not working and 'show platform fan' and 'show platfomr temperature' commands not working.
2. _thermal_list array inside PSU class was not initialized. Made changes to attach the PSU related thermal sensors in the PSU instance.
Added a common class pddf_fan_drawer.py. This class uses the PDDF JSON to fetch the platform specific data. A platform which uses PDDF would follow the below hierarchy.
> fan_drawer_base.py --->  pddf_fan_drawer.py ---> fan_drawer.py 
Run the 'show platform fan' and 'show platform temperature' commands and check the o/p.
o/p on AS7326:
```
root@sonic:/home/admin# show platform fan
s  Drawer    LED         FAN    Speed    Direction    Presence    Status          Timestamp …
```
> Adding support for fan_drawer class in PDDF common platform APIs

- src/sonic-yang-models/tests/yang_model_tests/tests/mirror_session.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/mirror_session.json
- src/sonic-yang-models/yang-models/sonic-mirror-session.yang
PR  https://github.com/Azure/sonic-utilities/pull/1825 added validation for the input of `config mirror session add`, and only decimal value is accepted.
An issue https://github.com/Azure/sonic-buildimage/issues/10096 was raised to suggest accepting HEX value as well, and the suggestion makes sense to me.
To accept HEX value for GRE type, and keep backward compatibility as well, I updated the YANG model to support both decimal and hexadecimal input for GRE type.
Update the regex for GRE type.
Verified by UT
```
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-yang-models
plugins: pyfakefs-4.5.4, cov-2.10.1
collected 3 items …
```
> Update YANG model for mirror session to support decimal value for GRE type

- src/sonic-build-hooks/hooks/apt-get
- src/sonic-build-hooks/scripts/buildinfo_base.sh
Fix the warning message not printed as expected issue
If a version is not specified in the command line, and not in the version control file, then print a warning message as below:
```
apt-get -y install python3-dev
Warning: the version of the package python3-dev is not specified.
Reading package lists... Done
Building dependency tree       
...
```
> [Build][Bug]: fix the warning message not printed as expected issue

- build_debian.sh
- files/build_templates/sonic_debian_extension.j2
[Build]: Fix /proc not mounted issue
Merged code from https://github.com/Azure/sonic-buildimage/pull/10164
> [Build]: Fix /proc not mounted issue (#10164)

- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
4600C is using wrong thermal profile and it displays 2 CPU core thermal in `show platform temperature` output, there should be 4 CPU core thermal.
Change 4600C to use thermal profile 10.
Manual test
> [Mellanox] [202012] Fix issue: 4600C is using wrong thermal profile

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/tests/test_psu.py
Fix issue: psu might use wrong voltage sysfs which causes invalid voltage value. The flow is like:
1. User power off a PSU
2. All sysfs files related to this PSU are removed
3. User did a reboot/config reload
4. PSU will use wrong sysfs as voltage node
Always try find an existing sysfs.
Manual test
> [Mellanox] Fix issue: psu might use wrong voltage sysfs which causes invalid voltage value

- rules/thrift_0_13_0.mk
Correct thrift.0.13.0 dependent package name.
In previous code, the buildout target was named as PYTHON3_THRIFT_0_13_0
But when add the prackage to LIBTHRIFT_0_13_0, it typo as PYTHON_THRIFT_0_13_0
> [202111][Cherry-pick]Correct the pkg name for thrift.0.13.0 (#9688)

- src/sonic-build-hooks/hooks/apt-get
- src/sonic-build-hooks/scripts/collect_version_files
- src/sonic-build-hooks/scripts/post_run_buildinfo
- src/sonic-build-hooks/scripts/pre_run_buildinfo
support to collect version when purging debian package
Support to collect version multiple times
Add the collection action before purging.
> [Build]: support to collect version when purging debian package

- files/initramfs-tools/arista-net
On some products the pci enumeration adds randomness into which nic gets
initialized first.
Because SONiC doesn't use deterministic interface naming but instead old
style interface naming, this leads to eth0 not always being the
management port.
To make sure eth0 is always the management port (SONiC expectation)
rename the interfaces in the initramfs for Arista products.
Rename interfaces in the initramfs based on kernel cmdline parameters
eth0 is the management port
Rename management interface to always be eth0 on Arista devices
> [Arista] rename management interface in initrd

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform.json
- device/nokia/x86_64-nokia_ixr7250e_sup-r0/Nokia-IXR7250E-SUP-10/platform.json
Update the Nokia IXR7250E platform platform.json files with correct thermal info table.  (This PR is created to replace PR9536 since the LGTM analysis: Python verification failed)
Modify the platform.json file for Nokia IXR7250E linecard x86_64-nokia_ixr7250e_36x400g-r0 and supervisor card x86_64-nokia_ixr7250e_sup-r0
1)  login the IXR7250E linecard x86_64-nokia_ixr7250e_36x400g-r0
2)  check file /usr/share/sonic/device/x86_64-nokia_ixr7250e_36x400g-r0/platform.json .
3) The thermal sensor names in the thermal table should match the name in the output of "show platform temperature"
```
admin@sonic:~$ show platform temperature 
Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
------------  -------------  ---------  -------- …
```
> [Nokia][IXR7250E]Update Nokia IXR7250E platform device data platform.json file

- files/scripts/syncd.sh
improvement of starting barefoot SDK
restart of the interface for cleaning txquee through which communication takes place between Sonic and openBMC 
run sonic autorestart  tests
> [BFN] Reset BMC port on syncd start

- src/sonic-config-engine/portconfig.py
- src/sonic-config-engine/tests/sample_platform.json
To fix https://github.com/Azure/sonic-buildimage/issues/9643
Instead of ast.literal_eval added python2 compat code for json strings unicode -> str convertion.
We need python2 compatibility since py2 sonic config engine (buster/sonic_config_engine-1.0-py2-none-any.whl target) is still included into the build (ENABLE_PY2_MODULES flag is set for buster). Once we abandon buster and python2, this compat and ast.literal_eval could be cleaned up all through the code base.
run steps from the linked issue
> [sonic-config-engine][portconfig] Do not parse JSON as Python AST

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/template-clean-sonic-slave.yml
When build sonic-slave docker, we need remove old docker first.
Current removing code fails when facing some corner cases.
> [ci] Fix remove sonic-slave docker image issue

- files/apt/sources.list.armhf
[Build]: Fix armhf mirrors not existing issue
The mirror endpoint debian-archive.trafficmanager.net does not support armhf, change to use deb.debian.org and security.debian.org.
> [Build]: Fix armhf mirrors not existing issue

- slave.mk
If a target is loaded from cache, it will show [ cached ] not [ finished ].
But for *.gz target, it does not work.
> [build] Fix docker image cached tag issue.

- src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
- src/sonic-yang-models/yang-templates/sonic-acl.yang.j2
Fixes https://github.com/Azure/sonic-utilities/issues/2049
from caclmgr:
- PRIORITY is a required field [code](https://github.com/Azure/sonic-buildimage/blob/3fa18d18d4c06fe38164ebfefdc3187820fc7496/src/sonic-host-services/scripts/caclmgrd#L548)
- PACKET_ACTION is a required field [code](https://github.com/Azure/sonic-buildimage/blob/3fa18d18d4c06fe38164ebfefdc3187820fc7496/src/sonic-host-services/scripts/caclmgrd#L581)
I think PRIORITY is a required field for ACLs not only CTRLPLANE ACLs
Check code.
Unit-test
> [yang] In ACL_RULE PRIORITY is mandatory and also PACKET_ACTION for CTRLPLANE ACLs

- device/nokia/armhf-nokia_ixs7215_52x-r0/plugins/led_control.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/chassis.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/fan.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/psu.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/test/test-chassis.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/thermal.py
The following changes are provided to support bullseye and the latest master
branch content.
- Accommodate relocated fan and thermal sysfs entries in bullseye
- Add support for chassis and PSU HW revision
Fix platform issues introduced by the bullseye kernel upgrade.
Minor fixes to Nokia ixs7215 platform code
Execute the following CLI commands
show platform summary
show platform fan
show platform temperature
> [Nokia ixs7215] Fixes to support Debian bullseye

- dockers/docker-sonic-restapi/supervisord.conf
Python 2 isn't installed by default in Buster and Bullseye containers,
and the scripts/modules can be used with Python 3, so make sure Python 3
is used.
After the Buster and Bullseye upgrade for the restapi container, processes will no longer start because supervisord is trying to call `python` and `python2`, both of which are unavailable.
> Don't use python/python2 for restapi start scripts

- src/sonic-build-hooks/scripts/collect_version_files
For Bullseye, Python 2 isn't present at all. This means that in certain
build cases (such as building something only for Bullseye), the version
file may not exist, and so the sort command would fail.
For most normal build commands, this probably won't be an issue, because
the SONiC build will start with Buster (which has both Python 2 and
Python 3 wheels built), and so the py2 and py3 files will be present
even during the Bullseye builds.
> Check to see that the py2 and py3 version files exist before trying to sort them

- files/image_config/hostcfgd/hostcfgd
- files/image_config/hostcfgd/limits.conf.j2
- files/image_config/hostcfgd/pam_limits.j2
When too many user login concurrently and run commands, SONiC may kernel panic on some device which has very limited memory.
Add j2 template for setup pam_limit plugin for limit SSH session per-user.
Manually validate the j2 template can generate correct config file.
Add j2 template for setup pam_limit plugin for limit SSH session per-user.
> Add j2 template for enable pam_limit and limit SSH session

- device/mellanox/x86_64-nvidia_sn2201-r0/pcie.yaml
- platform/mellanox/asic_table.j2
- platform/mellanox/docker-saiserver-mlnx.mk
- platform/mellanox/docker-saiserver-mlnx/Dockerfile.j2
- platform/mellanox/fw.mk
- platform/mellanox/hw-management.mk
- platform/mellanox/install-pending-fw.mk
- platform/mellanox/install-pending-fw.py
- platform/mellanox/libsaithrift-dev.mk
- platform/mellanox/mft.mk
- platform/mellanox/mlnx-onie-fw-update.sh
- platform/mellanox/mlnx-platform-api/sonic_platform/component.py
- platform/mellanox/mlnx-platform-api/sonic_platform/device_data.py
- platform/mellanox/mlnx-platform-api/sonic_platform/fan.py
- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/sonic_platform/sfp_event.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_actions.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_conditions.py
- platform/mellanox/mlnx-platform-api/sonic_platform/thermal_manager.py
- platform/mellanox/mlnx-platform-api/tests/conftest.py
- platform/mellanox/mlnx-platform-api/tests/test_fan_api.py
- platform/mellanox/mlnx-platform-api/tests/test_firmware.py
- platform/mellanox/mlnx-platform-api/tests/test_psu.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal.py
- platform/mellanox/mlnx-platform-api/tests/test_thermal_policy.py
- platform/mellanox/mlnx-ssd-fw-update.sh
- platform/mellanox/rules.mk
- platform/mellanox/sdk.mk
Signed-off-by: Dror Prital [drorp@nvidia.com](mailto:drorp@nvidia.com)
Update NVIDIA Copyright header to "mellanox" files which were changed since 1.1.2022
Update the copyright header 
Sanity tests and PR checkers.
> [Mellanox] Update NVIDIA Copyright header to "mellanox" files changed since 1.1.2022

- .azure-pipelines/azure-pipelines-image-template.yml
- .azure-pipelines/official-build-cache.yml
- azure-pipelines.yml
[Build]: Enable marvell-armhf PR check
Improve the azp dependencies, make the Test stage only depended on BuildVS stage. The Test stage will be triggered once the BuildVS stage finished, reduce the waiting time.
> [Build]: Enable marvell-armhf PR check

- src/sonic-frr/patch/0008-Backport-PR-https-github.com-FRRouting-frr-pull-8220.patch
- src/sonic-frr/patch/series
What I did:
Backport FRR patch https://github.com/FRRouting/frr/pull/8220 on FRR 7.2. Fixes the Issue https://github.com/FRRouting/frr/issues/8213
Why I did:-
Because of this race-condition we saw GR getting triggered even though BGP shut is given on peer device. 
How I verify:
After patching this fix GR is not triggered on doing BGP shut on peer.
> [201911] Backport FRR patch tp FRR-7.2 to handle pthread race in peer notify message handling

- platform/marvell-armhf/platform.conf
Change-Id: I3e2521780f5ecdb3bdf6cbb6542250814ca11959
Signed-off-by: Pavan Naregundi <pnaregundi@marvell.com>
Kernel hang in during early boot is caused due overwriting of device tree with uncompressing kernel. Added the fdt_high which gives a safe offset from kernel location.
Setting uboot environment variable fdt_high.
Successful boot of bullseye kernel on Marvell Armada 380/385.
As issue is due to migration to bullseye, fix needs to be backported to 202111.
Marvell-armhf: Setting u-boot fdt_high to resolve kernel hung
> [Marvell-armhf] Setting u-boot ftd_high to resolve kernel hung

- files/build_templates/sonic_debian_extension.j2
- files/image_config/haveged/haveged.service
The haveged service file in Debian Buster specifies that haveged should
start after systemd-random-seed starts (this was removed in Bullseye
after systemd changes caused a bootloop). This is a bit
counterproductive, since haveged is meant to be used in environments
with minimal sources of entropy, but one of the checks that
systemd-random-seed does is to verify that entropy is present.
Therefore, override the default .service file for haveged that moves
systemd-random-seed to the Before list, allowing it to start before
systemd-random-seed checks the system entropy level. (systemd doesn't
allow removing items from dependency/ordering entries such as After= and
Before=, so the entire .service file has to be overwritten.)
Note that …
> Start haveged before systemd-random-seed

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/flex_counter.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
- src/sonic-yang-models/yang-models/sonic-flex_counter.yang
HLD: https://github.com/Azure/SONiC/pull/908
Add YANG models for route flow counters
1. Add a new YANG definition for new counter group FLOW_CNT_ROUTE
2. Add a new YANG definition for new table FLOW_COUNTER_ROUTE_PATTERN_TABLE
New unit test cases
> [YANG] Add route flow counter support

- dockers/docker-lldp/lldpmgrd
when adding and removing ports after init stage we saw two issues:
first:
In several cases, after removing a port, lldpmgr is continuing to try to add a port to lldp with lldpcli command. the execution of this command is continuing to fail since the port is not existing anymore.
second:
after adding a port, we sometimes see this warning messgae:
"Command failed 'lldpcli configure ports Ethernet18 lldp portidsubtype local etp5b': 2021-07-27T14:16:54 [WARN/lldpctl] cannot find port Ethernet18"
we added these changes in order to solve it.
port create events are taken from app db only.
lldpcli command is executed only when linux port is up.
when delete port event is received we remove this command from  pending_cmds dictionary
manual tests and running lldp tests
Dynamic port configuration - …
> Dynamic port configuration - solve lldp issues when adding/removing ports

- scripts/prepare_slave_container_buildinfo.sh
- scripts/versions_manager.py
Fix host image debian package version issue.
The package dependencies may have issue, when some of debian packages of the base image are upgraded. For example, libc is installed in base image, but if the mirror has new version, when running "apt-get upgrade", the package will be upgraded unexpected. To avoid such issue, need to add the versions when building the host image.
The package versions of host-image should contain host-base-image.
> [Build]: Fix host image debian package version issue

- dockers/docker-base-buster/Dockerfile.j2
- dockers/docker-config-engine-buster/Dockerfile.j2
- dockers/docker-orchagent/Dockerfile.j2
- dockers/docker-sonic-mgmt-framework/Dockerfile.j2
- files/Aboot/boot0.j2
- files/initramfs-tools/varlog
- installer/arm64/install.sh
- installer/armhf/install.sh
- installer/x86_64/install.sh
* Remove pip2 and pip3 caches from some containers
Only containers which appeared to have a significant pip cache size are
included here.
* Don't create var-log.ext4 if we're storing logs in memory
* Run tune2fs on the device containing /host to not reserve any blocks for just the root user
(cherry picked from commit 5617b1ae3efc6cee52b875651135ada67898ebf0)
Reduce the disk space taken up during bootup and runtime.
1. Remove python package cache from the base image and from the containers.
2. During bootup, if logs are to be stored in memory, then don't create the `var-log.ext4` file just to delete it later during bootup.
3. …
> [202012] Image disk space reduction (#10172)

- device/accton/x86_64-accton_as5835_54t-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as5835_54x-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as7326_56x-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as7712_32x-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as7726_32x-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as7816_64x-r0/pmon_daemon_control.json
- device/accton/x86_64-accton_as9716_32d-r0/pmon_daemon_control.json
When do "skip_thermalcltd: true" will let "show platform fan" and "show platform temp" fail.
When enable thermalctld, these cmd will work well. 
Remove "skip_thermalcltd: true" in pmon_daemon_control.json
Test show platform temp and show platform fan, results are fine in PDDF platform .
> [Accton/PDDF] Enable thermalctld in pmon

- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-accton/as4630-54pe/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-accton/as7712-32x/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-accton/as7726-32x/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as7816-64x/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-accton/as7816-64x/sonic_platform/thermal.py
- platform/broadcom/sonic-platform-modules-accton/as9716-32d/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-accton/as9716-32d/sonic_platform/thermal.py
Support for show platform temp/fan for psu-temp and fan.
Original code doesn't has fan_drawer to support these information.
Support for show platform temp/fan for psu-temp and fan.
Add fan_drawer.py and update thermal.py to add needed code.
It need PDDF common code to support . (Refer to  https://github.com/Azure/sonic-buildimage/pull/10213)
Test show platform temp and show platform fan.
root@as7726-32x-2:~# show platform fan
Drawer    LED         FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ----------  -------  -----------  ----------  --------  -----------------
Fantray1  green  Fantray1_1      38%      EXHAUST     Present        OK  20220311 08:13:04
Fantray1  green  Fantray1_2      38%      EXHAUST     Present        OK  20220311 08:13:04 …
> [Accton/PDDF] Support show cmd for psu-temp and fan

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
cherry-pick to 202106 branch to fix bug.
> [ci] Fix remove sonic-slave-* docker image issue when building sonic-slave* (#10296)

- platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
- platform/mellanox/mlnx-platform-api/tests/input_platform/output_sfp.py
- platform/mellanox/mlnx-platform-api/tests/test_sfp.py
Need to implement **read_eeprom/write_eeprom** API for Credo Y-cable for Dual-Tor
Used **mlxreg** utility for API implementation
run sfp unit tests
> [Mellanox] Credo Y-cable read_eeprom/write_eeprom API implementation

- dockers/docker-orchagent/tunnel_packet_handler.py
Tunnel packet handler can crash at system startup:
```
Mar 19 13:11:07.240465 str2-8102-03 INFO swss#/supervisord: tunnel_packet_handler Traceback (most recent call last):
Mar 19 13:11:07.240465 str2-8102-03 INFO swss#/supervisord: tunnel_packet_handler   File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 1017, in stop
Mar 19 13:11:07.240465 str2-8102-03 INFO swss#/supervisord: tunnel_packet_handler     self.stop_cb()
Mar 19 13:11:07.240529 str2-8102-03 INFO swss#/supervisord: tunnel_packet_handler AttributeError: 'AsyncSniffer' object has no attribute 'stop_cb'
Mar 19 13:11:07.240529 str2-8102-03 INFO swss#/supervisord: tunnel_packet_handler 
Mar 19 13:11:07.240529 str2-8102-03 INFO swss#/supervisord: …
```
> [tun_pkt]: Wait for AsyncSniffer to init fully

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/vlan_sub_interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan_sub_interface.json
- src/sonic-yang-models/yang-models/sonic-vlan-sub-interface.yang
To support vlan sub intf short naming format, like subport `Eth8.100` for parent port`Ethernet8` with vlan id `100`.
Add checks to `must` condition to verify there is a port or portchannel with the index same as the vlan sub intf.
Run the unttests.
> [YANG ] Support vlan sub intf short naming format

- scripts/prepare_slave_container_buildinfo.sh
Fix the command set_reproducible_mirrors not found issue during the build.
Change to run the command after sourcing the common script.
> [build][Bug]: Fix the command set_reproducible_mirrors not found issue

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/docker-sonic-slave-template.yml
Use the same template across branches.
Thus, we don't need to copy template file branch to branch.
> [ci] Use template from master branch in UpgrateVersion/sonic-slave pipeline.

- src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml
sonic-config-engine unit test is using invalid switch_type
Update xml with correct switch_type
Run UT for sonic-config-engine
Fix #10364
> [sonic-cfggen] Fix invalid switch_type

- dockers/docker-orchagent/enable_counters.py
Fastboot will delay all counters in CONFIG DB, it relies on enable_counters.py to recover the delayed counters. However, enable_counters.py does not recover those non-default counters.
For non-default counters, if it is in CONFIG DB, put delay status to false after the waiting.
Manual test
> [counter] Fix issue: non default counters will be delayed forever after fastboot

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
Update the the BCM config file with the recycle ports info for Nokia IXR7250E platform
Modify the the BCM configuration file with the recycle ports configuration
Boot up image with the config_db#.json files which contain recycle ports.  Using the "docker ps -a"  to verify the containers  swss/syncd.  They should be up and running.
```
admin@ixre-egl-board1:~$ docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED             STATUS                      PORTS     NAMES
...
e49cb5fbd2aa   docker-syncd-brcm-dnx:latest         "/usr/local/bin/sup.."   About an hour ago   Up 24 minutes                 syncd0
31123572b3bf   docker-syncd-brcm-dnx:latest         "/usr/local/bin/sup.."   About an hour ago   Up 24 minutes                 syncd1 …
```
> [Nokia][device] Update the BCM config with Recycle ports info for Nokia IXR7250E platform

- .azure-pipelines/docker-sonic-slave-arm64.yml
- .azure-pipelines/docker-sonic-slave-armhf.yml
- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/docker-sonic-slave.yml
Fix bug for wrong resources position.
> [ci] Fix docker-sonic-slave-template issue for resources.

- .azure-pipelines/template-clean-sonic-slave.yml
Should unblock failing checks for https://github.com/Azure/sonic-buildimage/pull/10414
A typo when cleaning up sonic-slave-* containers is causing build failures
FIx the typo
> [azp]: Fix typo in slave container cleanup

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
dhcp_server is introduced, and need to update yang model.
Update yang models and add unit test.
Run unit test for sonic-yang-models.
Fix #10365
> [yang] Update device_metadata to add dhcp_server

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/official-build.yml
- .azure-pipelines/template-clean-sonic-slave.yml
- .azure-pipelines/template-variables.yml
- azure-pipelines.yml
docker hub will limit the pull rate.
Use ACR instead to pull debian related docker image.
Set DEFAULT_CONTAINER_REGISTRY in pipeline.
Log will print DEFAULT_CONTAINER_REGISTRY value.
> [ci] Set default ACR in UpgrateVersion/PR/official pipeline.

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
…s folder change (#7464)
Fix the generating version file failure issue caused by artifacts folder change.
When changing to use the same template for PR build, official build and packages version upgrade, the artifacts folder adding a "target" folder, the version upgrade task should be changed accordingly.
Filed to copy the version file, caused by the artifacts folder change.
Fixed in release branch, but not in master.
> [ci] Fix the generating version file failure issue caused by artifact target change

- .azure-pipelines/docker-sonic-slave.yml
[Ci]: Fix an azp template syntax error
See https://dev.azure.com/mssonic/build/_build/results?buildId=86535&view=results
```
/.azure-pipelines/docker-sonic-slave.yml (Line: 62, Col: 47): Expected a mapping
```
> [Ci]: Fix an azp template syntax error

- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/qosmaps.json
- src/sonic-yang-models/yang-models/sonic-port-qos-map.yang
Signed-off-by: bingwang <wang.bing@microsoft.com>
This PR is to update YANG model `sonic-port-qos-map.yang` to support new table `pfcwd_sw_enable`.
HLD https://github.com/Azure/SONiC/pull/950
Related PR https://github.com/Azure/sonic-buildimage/pull/10176
Update `pfcwd_sw_enable`.
Verified by UT
```
collected 3 items                                                                                                                                                                                     
tests/test_sonic_yang_models.py ..                                                                                                                                                              [ 66%]
tests/yang_model_tests/test_yang_model.py . …
```
> [YANG] Update YANG model for `pfcwd_sw_enable`

- device/arista/x86_64-arista_7280cr3mk_32p4/Arista-7280CR3-C40/gearbox_100G_PAM4.xml
This update the serdes tuning values for Arista 7280cr3mk. The values are for the optical transceivers.
> [arista] Update serdes tuning values for 7280cr3mk

- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/chassis.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/component.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py
- platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/platform_utils.py
Signed-off-by: Taras Keryk <tarasx.keryk@intel.com>
The previous implementaion of component.py expect fwutil run with sudo.
When fwutil run without sudo, there is exception:
```
File "/usr/local/bin/fwutil", line 5, in <module>
from fwutil.main import cli
File "/usr/local/lib/python3.9/dist-packages/fwutil/__init__.py", line 3, in <module>
from . import main
File "/usr/local/lib/python3.9/dist-packages/fwutil/main.py", line 40, in <module>
pdp = PlatformDataProvider()
File "/usr/local/lib/python3.9/dist-packages/fwutil/lib.py", line 159, in __init__
self.__platform = Platform()
File "/usr/local/lib/python3.9/dist-packages/sonic_platform/platform.py", line 21, in __init__
self._chassis = Chassis()
File …
```
> [BFN] Fix exception when fwutil run without sudo

- .azure-pipelines/docker-sonic-slave-template.yml
- .azure-pipelines/docker-sonic-slave.yml
[Ci]: Fix the docker slave azp template issue
1. For multiple repo reference, we need to use the absolute path.
```
template: '/.azure-pipelines/template-clean-sonic-slave.yml@buildimage'
```
2. Fix a usage error, cannot add the variables template in steps.
3. Fix docker slave image publish issue, cannot publish the latest tag in the release branches. It has impacts on the component build, for instance, sonic-swss-common. Some of the required packages are not installed in docker slave images in release branches. See https://github.com/Azure/sonic-swss-common/pull/596#pullrequestreview-929705727
> [Ci]: Fix the docker slave azp template issue

- sonic-slave-bullseye/Dockerfile.j2
[Build]: fix debian package not found issue
Add the missing mirrors in the bullseye slave docker.
> [Build]: fix debian package not found issue

- src/sonic-config-engine/tests/radv-test-sample-graph.xml
- src/sonic-config-engine/tests/sample-graph-resource-type.xml
- src/sonic-config-engine/tests/sample-graph-subintf.xml
- src/sonic-config-engine/tests/simple-sample-graph.xml
- src/sonic-config-engine/tests/t0-sample-graph.xml
- src/sonic-config-engine/tests/test_cfggen.py
ASN range is from 1 to 4294967295, need to remove invalid ASN.
Update unit test and replace ASN 0.
Run unit test for sonic-config-engine.
Fix #10363
> [sonic-cfggen]: Update unit test to remove asn 0

- dockers/docker-router-advertiser/docker-router-advertiser.supervisord.conf.j2
Allow radvd to run on new device type MgmtTsTor
> [radv] Add new device type in docker-router-advertiser.supervisord.conf.j2

- src/sonic-yang-mgmt/sonic_yang_ext.py
- src/sonic-yang-mgmt/tests/libyang-python-tests/test_sonic_yang.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/tacacs.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/tacacs.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
Fix https://github.com/Azure/sonic-buildimage/issues/9746
Split the check condition based on non-exist and zero length.
Run verification script when table contains empty value
> Fix yang validation failure when table contains empty value

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/azure-pipelines-build.yml
Exclude the innovium build in upgrading version build, currently, the builds are always failed, exclude the build temporarily.
Increase the broadcom build timeout.
> [Ci]: exclude innovium build and increase broadcom build timeout

- platform/marvell-armhf/sai.mk
1) L3 DHCP trap support
2) Interface ACL's (Ingress Everflow support)
3) 1G Autoneg support
Added below enhancements in Marvell SAI,
1) L3 DHCP trap support
2) Interface ACL's (Ingress Everflow support)
3) 1G Autoneg support
Load the Marvell SAI deb version 1.9.1-2 and verify the functionality.
Added Feature enhancements
> [Marvell] Update armhf sai deb

- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/test/test-thermal.py
- platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/thermal.py
Incorrect high-threshold and critical-high-threshold values are displayed for
some of the temperature sensors. This commit fixes that.
Incorrect high-threshold and critical-high-threshold values are displayed for
some of the temperature sensors
Modify the thermal sensor Platform API 2.0 implementation to return the correct values.
Ensure that the 'show platform temperature' command show the correct high-threshold and critical-high-threshold values for each thermal sensor.
Values displayed before the fix.
```
admin@localhost:~$ show platform temperature
Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
-----------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
ADT7473-CPU         23 …
```
> [Nokia ixs7215] Platform API temperature threshold value fixes

- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
- device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
Signed-off-by: Sakthivadivu Saravanaraj <sakthivadivu.saravanaraj@nokia.com>
To reduce CPU usage by syncd dockers
Added the .bcm config parameters suggested by BCM
verified that CPU usage by syncd dockers is not high in Nokia-IXR7250E-36x400G
> [Nokia][device] Updated the BCM config file to reduce the CPU usage

- src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
- src/sonic-yang-models/yang-models/sonic-device_metadata.yang
minigraph parser has introduced new type.
Update yang models to support BmcMgmtToRRouter.
Run unit test for sonic-yang-models
Fix #10487
> [yang]: Add support for BmcMgmtToRRouter

- .azure-pipelines/azure-pipelines-build.yml
- .azure-pipelines/check-dirty-version.yml
[Ci]: check if there is a sonic dirty version issue
If there is a dirty version issue in PR build, the build will be failed.
> [Ci]: check if there is a sonic dirty version issue

- dockers/docker-orchagent/switch.json.j2
Add new device type EPMS and MgmtTsToR for setting hash_seed in orchagent docker.
hash_seed is automatically set to 0, this is mainly for reference of where "ToRRouter" is used in orchagent
Update switch.json.j2
> [orchagent] Set hash_seed for EPMS and MgmtTsToR

- dockers/docker-ptf/Dockerfile.j2
Existing dataplane tests cannot be tested under MACsec environment due to the traffic under MACsec link is encrypted. So, I will override the dp_poll of ptf to MACsec dp_poll to decrypt the MACsec packets on injected ports (PR: https://github.com/Azure/sonic-mgmt/pull/5490). MACsec decryption library depends on scapy 2.4.5.
Upgrade scapy library to 2.4.5 by pip.
Check the scapy version in docker-ptf by 
```
python -c "import scapy; print(scapy.__version__)"
2.4.5
```
> [docker-ptf]: Upgrade scapy to 2.4.5 in docker-ptf

- platform/broadcom/saibcm-modules/debian/opennsl-modules.init
- platform/broadcom/saibcm-modules/debian/opennsl-modules.install
For trident4/tomahawk4, linux_ngknet.ko and linux_ngknetcb.ko have to be installed. Also, the kernel modules to load on such chips are different from existing ones, so we add an option is_ltsw_chip to determine the kernel modules to load. The option is_ltsw_chip is controlled by adding 'is_ltsw_chip=1' to platform_env.conf or not.
We verified that existing platforms still work after this change; and for platforms with trident4/tomahawk4, we can load the different kernel modules as expected after adding 'is_ltsw_chip=1' to platform_env.conf
> Add linux_ngknet for trident4/tomahawk4 chips

- files/build_templates/docker_image_ctl.j2
In the bringup of tomahawk4/trident4, we realized that such chips need a larger size of /dev/shm in syncd container, so we added the option --shm-size to the docker create for syncd. The default value for shm-size is 64m; after this change, people can add SYNCD_SHM_SIZE=128m to platform_env.conf to change it to 128m.
We verified that after this change, 1) on existing platforms without platform_env.conf, the size of /dev/shm in syncd container (df -h | grep shm) is still the default 64M; 2) after we add  SYNCD_SHM_SIZE=128m to platform_env.conf, /dev/shm in syncd becomes 128M.
> Add option --shm-size to creating syncd container

- device/accton/x86_64-accton_as9716_32d-r0/pddf/pddf-device.json
- platform/broadcom/sonic-platform-modules-accton/as9716-32d/modules/Makefile
- platform/broadcom/sonic-platform-modules-accton/as9716-32d/modules/accton_as9716_32d_ioport.c
Signed-off-by: Brandon Chuang <brandon_chuang@edge-core.com>
Prevent from i2c bus to get locked.
Add sysfs driver to access ioport.
Command to reset i2c mux:
echo 1 > /sys/devices/platform/as9716_32d_ioport/i2c_mux_rst
Command to bring i2c mux out of reset:
echo 0 > /sys/devices/platform/as9716_32d_ioport/i2c_mux_rst
If i2c mux is under reset state, below command will return error.
i2cget -f -y 0 0x77 0
--> Please merge code to this branch. Some customers need it
> [AS9716-32D] Support i2c mux reset

- src/sonic-config-engine/sonic-cfggen
Fix https://github.com/Azure/sonic-buildimage/issues/9676
[Done] Lanes is fixed by https://github.com/Azure/sonic-buildimage/pull/10362
[Done]Wait for UT speed update
Config db schema generated by minigraph can’t pass yang validation, PORT table does not have 'lanes' field.
cfggen command fail when 'lanes' and 'speed' are not provided
Run 'sonic-cfggen -m xxx.xml --print-data' to make sure command fail when 'lanes' not in PORT table
> [sonic-cfggen] make minigraph parser fail when speed and lanes are not in PORT table

- platform/marvell-armhf/sai.mk
Fixed IPv6 route issue resulting in orchagent crash.
Fixed SAI error resulting in orchagent crash in nokia platform.
Reproduced the issue from sairedis.rec and fixed the bug.
Simplified steps to reproduce the issue and validate the fix.
1)	create route "2603:10e2:11:6000::/54"
2)	create route "2603:10e2:11:6000::/64"
3)	delete route  "2603:10e2:11:6000::/64"
4)	set route  "2603:10e2:11:6000::/54" 
Fixed IPv6 route issue resulting in orchagent crash in nokia platform.
> [Marvell] Marvell armhf SAI debian.

- src/sonic-config-engine/tests/common_utils.py
- src/sonic-config-engine/tests/test_j2files.py
Co-authored-by: azureuser <azureuser@contoso.com>
Fix sonic config engine test not stable issue
> [Unit Test]: Fix sonic config engine test not stable issue(#10147)

- files/Aboot/boot0.j2
- files/initramfs-tools/mke2fs
- files/initramfs-tools/union-mount.j2
- installer/arm64/install.sh
- installer/armhf/install.sh
- installer/x86_64/install.sh
If it is run during image install, it's not guaranteed that the
installation environment will have tune2fs available. Therefore, run it
during initramfs instead.
Remove the tune2fs command from the image installation files, and add
it into initramfs, just after the filesystem gets mounted. 
Tested on a Arista 7060 running 201911 image, and was able to install and
boot a 202012 branch image with 5% reserved blocks.
> Run tune2fs during initramfs instead of image install

- dockers/docker-ptf/Dockerfile.j2
It upgraded scapy to 2.4.5 in docker-ptf container, after this upgrade, all scripts under ansible/roles/test/files/ptftests will import scapy 2.4.5, some test cases will fail because they are not upgraded accordingly. 
Reverts Azure/sonic-buildimage#10507 to avoid breaking regression test.
> Revert "[docker-ptf]: Upgrade scapy to 2.4.5 in docker-ptf"

- files/Aboot/boot0.j2
- files/initramfs-tools/mke2fs
- files/initramfs-tools/union-mount.j2
- installer/arm64/install.sh
- installer/armhf/install.sh
- installer/x86_64/install.sh
If it is run during image install, it's not guaranteed that the
installation environment will have tune2fs available. Therefore, run it
during initramfs instead.
Master branch PR: #10536
Remove the tune2fs command from the image installation files, and add
it into initramfs, just after the filesystem gets mounted.
Tested on a Arista 7060 running 201911 image, and was able to install and
boot a 202012 branch image with 5% reserved blocks.
> [202012] Run tune2fs during initramfs instead of image install

- src/sonic-build-hooks/scripts/buildinfo_base.sh
[Build]: Fix pip version constraint conflict issue
When a version is specified in the constraint file, if upgrading the version in build script, it will have conflict issue.
If a specified version has specified in pip command line, then the version constraint will be skipped.
https://dev.azure.com/mssonic/build/_build/results?buildId=89255&view=results
See the last two commits to verify it works fine in 202111 branch.
> [Build]: Fix pip version constraint conflict issue

- device/arista/x86_64-arista_7170_64c/Arista-7170-64C/buffers_defaults_t0.j2
- device/arista/x86_64-arista_7170_64c/Arista-7170-64C/buffers_defaults_t1.j2
- device/barefoot/x86_64-accton_as9516_32d-r0/newport/buffers_defaults_t0.j2
- device/barefoot/x86_64-accton_as9516_32d-r0/newport/buffers_defaults_t1.j2
- device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/buffers_defaults_t0.j2
- device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/buffers_defaults_t1.j2
Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>
This PR includes necessary changes for correct generating BUFFER_QUEUE values in DB. Changes are based on the [schema.md](https://github.com/Azure/sonic-swss/blob/master/doc/swss-schema.md#buffer_queue_table) 
Change format of generating BUFFER_QUEUE in DB according to [schema.md](https://github.com/Azure/sonic-swss/blob/master/doc/swss-schema.md#buffer_queue_table) and [yang-model](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-buffer-queue.yang).
```
"BUFFER_QUEUE": {
"Ethernet0,Ethernet100,Ethernet104,Ethernet108,Ethernet112,Ethernet116,Ethernet12,Ethernet120,Ethernet124,Ethernet16,Ethernet20,Ethernet24,Ethernet28,Ethernet32,Ethernet36,Ethernet4,Ethernet40,Ethernet44,Ethernet48 …
```
> Updated format of generating BUFFER_QUEUE in buffers_defaults templates

- Makefile.work
- dockers/docker-base-buster/Dockerfile.j2
- dockers/docker-base-stretch/Dockerfile.j2
- dockers/docker-base/Dockerfile.j2
- slave.mk
Why I did it
**Cherry pick https://github.com/Azure/sonic-buildimage/pull/7731 to 202106 and fix code conflict**
Support to build armhf/arm64 platforms on arm based system without qemu simulator.
When building the armhf/arm64 on arm based system, it is not necessary to use qemu simulator.
How I did it
Build armhf on armhf system, or build arm64 on arm64 system, by default, qemu simulator will not be used.
When building armhf on arm64, and you have enabled armhf docker, then it will build images without simulator automatically. It is based how the docker service is run.
Docker base image change:
For amd64, change from debian:to amd64/debian:
For arm64, change from multiarch/debian-debootstrap:arm64- to arm64v8/debian:
For armhf, change from multiarch/debian-debootstrap:armhf- to …
> Support to build armhf/arm64 platforms on arm based system (#7731)

- files/build_templates/init_cfg.json.j2
Enable dhcp_relay on EPMS and MgmtTsTor
Add missing device types in copp_cfg.j2
> [dhcp_relay] Enable dhcp_relay on EPMS, MgmtTsTor, MgmtToRRouter and BackEndToRRouter

- platform/barefoot/bfn-modules/modules/bf_ioctl.h
- platform/barefoot/bfn-modules/modules/bf_kdrv.c
- platform/barefoot/bfn-modules/modules/bf_kdrv.h
- platform/barefoot/sonic-platform-modules-bfn-newport/modules/bf_fpga_ioctl.c
- platform/barefoot/sonic-platform-modules-bfn-newport/modules/bf_fpga_ioctl.h
- platform/barefoot/sonic-platform-modules-bfn-newport/modules/bf_fpga_main.c
- platform/barefoot/sonic-platform-modules-bfn-newport/modules/bf_fpga_priv.h
- platform/barefoot/sonic-platform-modules-bfn-newport/modules/bf_fpga_sysfs.c
- platform/barefoot/sonic-platform-modules-bfn-newport/modules/i2c/bf_fpga_i2c.c
Signed-off-by: Taras Keryk <tarasx.keryk@intel.com>
Update FPGA kernel driver and modules to the latest version.
FPGA provide I2C point to point master interfaces for optical modules. 
It also provide master I2C interface to the CPLD
Update driver and modules sources in the SONiC platform folder
The output of the lsmod command should show successfully loaded drivers bf_fpga, bf_kdrv, bf_tun
> [BFN] Update FPGA kernel driver and modules to the latest version

- .azure-pipelines/azure-pipelines-UpgrateVersion.yml
- .azure-pipelines/azure-pipelines-repd-build-variables.yml
- .azure-pipelines/docker-sonic-slave.yml
- .azure-pipelines/official-build-cache.yml
- .azure-pipelines/official-build.yml
- .github/workflows/label.yml
- azure-pipelines.yml
- src/sonic-build-hooks/scripts/buildinfo_base.sh
- src/sonic-build-hooks/scripts/collect_version_files
Co-authored-by: Ubuntu <xumia@xumia-vm1.jqzc3g5pdlluxln0vevsg3s20h.xx.internal.cloudapp.net>
Cherry-pick PR (#9426, #9443, #10325, #10525) from master to 202106 branch to fix marvell-armhf build broken issue.
> [Build]: Cherry pick PRs from master to 202106 branch

- platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py
Implement newly added reboot causes in PR https://github.com/Azure/sonic-platform-common/pull/277
Map the reboot cause sysfs to the newly added reboot causes.
manual test, check whether the reboot cause is correct after rebooting the switch in various ways.
run the community reboot test to see whether the reboot cause checker is passing.
> [Mellanox] support newly added reboot cause

- .azure-pipelines/template-commonlib.yml
- .azure-pipelines/template-variables.yml
Some component pipelines need packages built in different environment.
Add support to build in different env.
> [ci] Update common lib pipeline to build more distribute packages.

- files/scripts/gbsyncd.sh
- files/scripts/swss.sh
- platform/components/docker-gbsyncd-credo/supervisord.conf.j2
Fix [#10501](https://github.com/Azure/sonic-buildimage/issues/10501)
Fix [#9733](https://github.com/Azure/sonic-buildimage/issues/9733)
If having gearbox, we need
- add gbsyncd as a peer since swss also has dependency on gbsyncd
- add service gbsyncd to FEATURE table if it is missing
- Kill orchagent
```
admin@DUT:~$ docker ps | grep -E 'swss|syncd'
29d108cf328e   docker-gbsyncd-credo:latest          "/usr/bin/docker-ini…"   5 days ago   Up 5 minutes             gbsyncd
0da3a5c5b6b9   docker-syncd-brcm-dnx:latest         "/usr/local/bin/supe…"   5 days ago   Up 5 minutes             syncd
f1e699d0c8fa   docker-orchagent:latest              "/usr/bin/docker-ini…"   5 days ago   Up 5 minutes             swss
admin@DUT:~$ sudo killall orchagent
admin@DUT:~$ docker ps | grep -E 'swss|syncd' …
```
> [gearbox] Add peer gbsyncd for swss if gearbox exists

- files/initramfs-tools/arista-net
The `arista-net` initramfs hook exits early when a mgmt NIC is missing.
This leads to mgmt interfaces not properly renamed and possibly `eth0` missing.
Fixed the line in `arista-net` that fails when one NIC is missing.
The error is tied to the syntax which is incompatible with `set -e`
Tested on products where one of the management NIC is missing.
Backport will be made manually to 202111 and 202012 as `arista-net`
has changed since.
Fix `arista-net` initramfs hook when a mgmt NIC is missing
> [Arista] Fix arista-net initramfs hook

- files/initramfs-tools/arista-net
Backport from #10624 
Fix `arista-net` management interface rename logic in initramfs
> [202012][Arista] Fix arista-net initramfs hook

- files/initramfs-tools/arista-net
Part of this change is a missing backport of #9856 in 202111.
The second part is the fix for `arista-net` renaming logic fixed by #10624 in master.
Fix `arista-net` management interface rename logic in initramfs
> [202111][Arista] Fix arista-net initramfs renaming logic

- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
- platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_fan.py
AS7726 platform was not showing serial number in the output of
- show platform summary
- show version
Issue #10489 
Th root cause was that thePDDF chassis common class was reading the 'service_tag' upon invoking get_serial(). However, Accton platform AS7726 did not have service tag programmed in the EEPROM. Hence throwing 'N/A'. I changed the 'get_serial()' method to fetch the serial number of the board.
- show platform summary
- show platform version
```
root@sonic:/sys/bus/i2c/devices# show ver
SONiC Software Version: SONiC.master.0-dirty-20220408.025810
Distribution: Debian 11.3
Kernel: 5.10.0-8-2-amd64
Build commit: 50067c8e4
Build date: Fri Apr  8 10:03:36 UTC 2022
Built by: fk410167@sonic-lvn-csg-004
Platform: x86_64-accton_as7726_32x-r0
HwSKU: Accton-AS7726-32X
ASIC: broadcom
ASIC …
```
> Fix AS7726 not showing serial number in 'show platform summary' (#10489)

- dockers/docker-sonic-telemetry/base_image_files/monit_telemetry
- files/image_config/monit/memory_checker
This PR aims to fix the Monit issue which shows Monit can't reset its counter when monitoring memory usage of telemetry container.
Specifically the Monit configuration file related to monitoring memory usage of telemetry container is as following:
check program container_memory_telemetry with path "/usr/bin/memory_checker telemetry 419430400"
if status == 3 for 10 times within 20 cycles then exec "/usr/bin/restart_service telemetry"
If memory usage of telemetry container is larger than 400MB for 10 times within 20 cycles (minutes), then it will be restarted.
Recently we observed, after telemetry container was restarted, its memory usage continuously increased from 400MB to 11GB within 1 hour, but it was not restarted anymore during this 1 …
> [Monit] Repeat restarting culprit container if Monit can't reset its counter

- .azure-pipelines/azure-pipelines-download-certificate.yml
- .azure-pipelines/official-build-cisco-8000.yml
[Ci]: Support to sign image for cisco-8000 uefi secure boot
> [Ci]: Support to sign image for cisco-8000 uefi secure boot

- platform/mellanox/mlnx-platform-api/sonic_platform/psu.py
- platform/mellanox/mlnx-platform-api/tests/test_psu.py
InvalidPsuVolWA.run might raise exception if user power off PSU when it is running. This exception is not caught and will be raised to psud which causes psud failed to update PSU data to DB.
1. Change the log level when WA does not work. This could happen when user power off PSU, hence changing the log level from error to warning is better
2. Change the wait time from 5 to 1 to avoid introduce too much delay in psud. 1 second is usually enough per my test
3. Give a default return value for function get_voltage_low_threshold and get_voltage_high_threshold to avoid exception reach to psud
Manual test.
Run sonic-mgmt regression
> [Mellanox] Adjust PSU voltage WA

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
* Optimize dx010 sonic platform init script to speed up init process
* Merge issue #10152: [warm-upgrade][202012] Slow Celestica platform init
in rc.local causes lacp-teardown fix into master branch
Signed-off-by: Eric Zhu <erzhu@celestica.com>
To merge PR #10237 into master branch.
Warm upgrade causes lacp-teardown on Dx010 TOR. platform code initialize slow causing lacp timeout.
Optimize the dx010 sonic platform script to speed up the init process.
- Check the warm reboot log, warm reboot is 8-9s faster than before.
```
[945232.436622] kexec_core: Starting new kernel                                                                                                                                                          
[    5.838762] rc.local[461]: + sed -e s/build_version: //g;s/'//g …
```
> sonic-platform-modules-cel dx010: speed up dx010 platform init script

- build_debian.sh
- files/build/versions/host-image/versions-py3
Cherry-pick PR: https://github.com/Azure/sonic-buildimage/pull/10523
In sonic-utilities repo, it is required to install docker>=4.4.4
https://github.com/Azure/sonic-utilities/blob/f70dc27827a88d70e91e15ecdcde2ebbc446116d/setup.py#L187
> [Build] Upgrade pip3 package docker to 5.0.3 (#10523)

- src/sonic-yang-models/tests/yang_model_tests/tests/vlan_sub_interface.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/vlan_sub_interface.json
- src/sonic-yang-models/yang-models/sonic-vlan-sub-interface.yang
Allow portchannel vlan sub intf long name format as long as it follows Linux interface name length limit(<16).
Modify the leaf name check.
Test case passes.
> [YANG][vlan-sub-intf] Enforce Linux interface name length

- device/arista/x86_64-arista_7060dx4_32/platform.json
There was a requirement to support such configuration on this platform from Microsoft.
Added a "1x100G(4)" breakout mode to platform.json, which allowed it to be set as a default breakout configuration or set on the dut.
When the dut boots with this configuration set, 1x100G connected to ports will come up.
> [Arista] Add 1x100G over 4 lanes configuration for 7060DX4

- dockers/docker-orchagent/docker-init.j2
Asic PCI ID (PCI address) is collected by chassisd (inside pmon -
Azure/sonic-platform-daemons#175) and saved in CHASSIS_STATE_DB (in
redis_chassis). CHASSIS_STATE_DB is accessible by swss containers.
At docker-init.sh (script is called after swss container is created and before
anything that could run in swss like orchagent...), we wait until asic PCI ID
of the corresponding asic is populated by chassisd. We then update asic_id in
CONFIG_DB of asic's database.
A system supporting dynamic asic PCI ID identification requires to have a file
(empty) use_pci_id_chassis in its platform dir.
When orchagent runs, it has correct asic PCI ID in its CONFIG_DB.
Together with this PR:
Azure/sonic-platform-daemons#175
Azure/sonic-platform-common#185
Signed-off-by: Maxime Lorrillere …
> Get asic PCI ID from CHASSIS_STATE_DB and update asic_id in CONFIG_DB

- .gitmodules
- dockers/docker-ptf/Dockerfile.j2
- platform/vs/docker-ptf.mk
- rules/ptf-py3.dep
- rules/ptf-py3.mk
- src/ptf-py3.patch/0001-Remove-ord-in-get_mac-to-avoid-TypeError.patch
- src/ptf-py3.patch/0002-Fill-byte-formatted-client-mac-address-in-DHCP-Disco.patch
- src/ptf-py3.patch/series
Migrate ptftests script to python3, in order to do an incremental migration, add python virtual environment firstly, install all required python packages in virtual env as well.
Then migrate ptftests scripts from python2 to python3 one by one avoid impacting non-changed scripts.
Add python3 virtual environment for docker-ptf. 
Add submodule `ptf-py3` and install patched ptf 0.9.3 into virtual environment as well, two ptf issues were reported here:
https://github.com/p4lang/ptf/issues/173
https://github.com/p4lang/ptf/issues/174
login docker-ptf container and check if there is a folder ` /root/env-python3/bin`
1. Connect to the docker-ptf container,  take kvm testbed as example as below:
```
$ docker exec -ti ptf_vms6-1 bash
```
1. …
> Add python3 virtual environment for docker-ptf

- files/build_templates/sonic_debian_extension.j2
- src/sonic-host-services/scripts/sonic-host-server
- src/sonic-host-services/setup.py
Can not start sonic-hostservice
Install python3-dbus and systemd-python, and replace invalid path
Start the service with below commands:
sudo systemctl start sonic-hostservice
sudo systemctl status sonic-hostservice
Fix #10647
> [sonic-host-services]: Fix import and invalid path

- src/sonic-config-engine/sonic-cfggen
This reverts commit cd330f0e70e646c2ff6fc88c6c8fb9f75e8b40e7.
Revert the PORT table mandatory field check to avoid possible blocks for production flow.
> Revert "[sonic-cfggen] make minigraph parser fail when speed and lanes are not in PORT table (#10228)

- platform/broadcom/sonic-platform-modules-dell/common/actions.sh
- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6000.install
- platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
- platform/broadcom/sonic-platform-modules-dell/s6000/scripts/hw-management-generate-dump.sh
- platform/broadcom/sonic-platform-modules-dell/s6100/scripts/hw-management-generate-dump.sh
- To collect platform based logs along with "show techsupport" on S6000 and S6100 platforms.
- Porting changes of https://github.com/Azure/sonic-buildimage/pull/6410 from master branch to 201911 branch.
On branch 201911_dell_techsupport_dump
(use "git restore --staged <file>..." to unstage)
new file:   platform/broadcom/sonic-platform-modules-dell/common/actions.sh
modified:   platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6000.install
modified:   platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
new file:   platform/broadcom/sonic-platform-modules-dell/s6000/scripts/hw-management-generate-dump.sh
new file:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/hw-management-generate-dump.sh …
> [DellEMC][201911] S6100 S6000 - Show techsupport enhancement porting changes

- rules/restapi.mk
Fix target target/debs/bullseye/sonic-rest-api_1.0.1_arm64.deb not existing issue, the correct target is target/debs/bullseye/sonic-rest-api_1.0.1_armhf.deb.
Fix issue: https://github.com/Azure/sonic-buildimage/issues/9896
```
[ FAIL LOG START ] [ target/debs/stretch/sonic-rest-api_1.0.1_amd64.deb ]
[ REASON ] :      target/debs/stretch/sonic-rest-api_1.0.1_amd64.deb does not exist   NON-EXISTENT PREREQUISITES: 
[ FLAGS  FILE    ] : [] 
```
make target/debs/bullseye/sonic-rest-api_1.0.1_armhf.deb
```
$ ls target/debs/bullseye/sonic-rest-api_1.0.1_armhf.deb
target/debs/bullseye/sonic-rest-api_1.0.1_armhf.deb
```
> [Build]: Fix the build target not existing issue when building sonic-rest-api

- src/sonic-yang-mgmt/sonic_yang_ext.py
Adding exceptlionList to validation exception
Check code.
Ran manually.
- Run full config validation from a KVM
- Print the thrown exception
**Before**
```
Error: Data Loading Failed
All Keys are not parsed in FEATURE
dict_keys(['telemetry'])
```
**After**
```
Error: Data Loading Failed
All Keys are not parsed in FEATURE
dict_keys(['telemetry'])
exceptionList:["'status'"]
```
> [SY] Adding exceptlionList to validation exception

- device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/buffers_defaults_t0.j2
Minor adjustment to ingress pool size to align it with BRCM sai change
Change on sonic-mgmt : https://github.com/Azure/sonic-mgmt/pull/5515
Updated buffer configuration template
Verified on dual ToR system
Minor adjustment to ingress pool size to align it with BRCM sai change
> Dual ToR : Adjustment to ingress pool size to accomodate brcm sai

- device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/buffers_defaults_t2.j2
The buffer pool & profile setting in buffer template was not correct and caused the errors like the following:
ERR swss#orchagent: :- parseReference: malformed reference:[BUFFER_PROFILE|ingress_lossless_profile]. Must not be surrounded by [ ] 
Fix the buffer pool & profile setting by removing "[]".
Loaded image with this fix in a switch and made sure the error was not seen anymore.
> Fix buffer template for Arista SKU.

- src/sonic-yang-mgmt/sonic_yang.py
Need to pass LY_CTX_DISABLE_SEARCHDIR_CWD to Context in order to disable automatically searching for schemas in current working directory (which is by default searched automatically)
add additional attribute into YANG context
Create some invalid link on switch :
1) **ln -s /usr/abc xxx**
2) run **spm list**
--> There should not be these messages:
```
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when …
```
> [yang] add yang options for Context object

- device/accton/x86_64-accton_as7816_64x-r0/installer.conf
The customer report of the PCIe Bus Errors upon the SDK initialization of as7816-64x.
Based on the internal info and discussion, update "pcie_aspm=off" into ONIE_PLATFORM_EXTRA_CMDLINE_LINUX of installer.conf to resolve it.
> [as7816-64x] Update installer.conf

- src/dhcp6relay/src/relay.cpp
dhcp6relay fails to bind to interface's link-local ipv6 addresses from time to time after interface is brought up due to not waiting for a long enough time period for ipv6 addresses to bind to the interface. 
Enhanced syslog to give more meaningful error log
Added a retry mechanism to check for interface's ipv6 global and link-local addresses 3 times, every 5 seconds. If ipv6 address is still missing or binding failed, alert in syslog
Tested retry mechanism:
#1 brings down Vlan interface, start dhcp6relay, check for "Failed to bind socket to ..." error in syslog
ss -nlp | grep dhcp6relay: verify sockets did not bind
#2 remove link-local ip from interface, start dhcp6relay, check for "Retry #(1,2,3) to bind to sockets on interface ..."
ss -nlp | grep dhcp6relay: verify socket did not bind …
> [dhcp6relay] Add retry mechanism for binding socket to interface ipv6 addresses

- src/sonic-yang-models/setup.py
- src/sonic-yang-models/tests/files/sample_config_db.json
- src/sonic-yang-models/tests/yang_model_tests/tests/bgp_voq_chassis_neighbor.json
- src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp_voq_chassis_neighbor.json
- src/sonic-yang-models/yang-models/sonic-bgp-voq-chassis-neighbor.yang
Fixes #10158 
Add yang model for config_db table `BGP_VOQ_CHASSIS_NEIGHBOR` and UT
UT and compile `sonic_yang_models-1.0-py3-none-any.whl` and `sonic_yang_mgmt-1.0-py3-none-any.whl`
> [YANG] yang model for bgp voq chassis neighbor
