src/sonic-host-services/scripts/hostcfgd

Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>
Missing comment change which is supposed to arrive with https://github.com/Azure/sonic-buildimage/pull/8861 is added here

[hostcfgd] Missing comment added 

---

platform/marvell-armhf/sai.mk

Fixed test_null_route_helper fix
Verify related test-case in Test bed.
test_null_route_helper fix

[202012][Marvell] Update armhf SAI to ver 1.7.1-5

---

.azure-pipelines/azure-pipelines-image-template.yml

Some build failure can't reproduce on local machine.
Publish logs and docker images to debug.
Always publish artifacts

Add artifacts for failure build to debug.

---

files/build/versions/default/versions-web
platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Signed-off-by: Mykhailo Onipko <monipko@barefootnetworks.com>
[BFN]: Updated SDK packages to 20211112
Created new packages for 202012 image
Ran regression for profiles

[BFN]: Updated SDK packages to 20211112

---

device/barefoot/x86_64-accton_wedge100bf_32x-r0/platform.json

For sonic-mgmt Platform API tests to have data to compare with
updated platform info for device x86_64-accton_wedge100bf_32x-r0
Run sonic-mgmt Platform API tests get_name fo:
1. chassis
2. fans
3. fan_drawers
4. psus
5. thermals

[BFN] updated platform info for device x86_64-accton_wedge100bf_32x-r0

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Introduced Y2 profile. Removed Y0 profile.

[BFN]: added Y2 profile to BFN SDK

---

.azure-pipelines/azure-pipelines-build.yml

In azure pipeline template 'set -e' not works as expected.

[CI] Stop Azure pipeline when any target failed.

---

.github/CODEOWNERS

Add some auto reviewers for sonic-yang-models folder

[codeowners]: Add some auto reviewers for sonic-yang-models folder

---

device/barefoot/x86_64-accton_as9516_32d-r0/newport/switch-tna-sai.conf

Switch hostif frpom Eth to PCIe to improve performance
TF2 update switch-tna-sai.conf to use pcie cpu instead of eth cpu
Deploy Sonic with this upstream Pr, run sanity tests
Pr: https://github.com/Azure/sonic-buildimage/pull/9220

[Barefoot] TF2 update switch-tna-sai.conf

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

This PR fix SONiC master build failure [master](https://sonic-build.azurewebsites.net/ui/sonic/pipelines/146/builds?branchName=master)
Update SDK package to fix linkage issue caused by missing sai_query_stats_capability() newly added in syncd: https://github.com/Azure/sonic-buildimage/pull/9287
SONiC build successfully finished

[BFN] update SDK package for Barefoot

---

platform/mellanox/mlnx-platform-api/sonic_platform/psu.py

Support PSU voltage high/low thresholds and power max threshold
- Add thresholds support for voltage and power.
As thresholds are not supported on all platforms, we need to check the capability first and fetch thresholds only if it is supported.
Run regression test and manual test.

[Mellanox] Support PSU voltage high/low thresholds and power max threshold

---

.gitmodules

Submodule update for sonic-utilities with following change:
ec9e5ee Backport [generate_dump] remove secrets from dump files #1886 to 202012 (#1938)
ce3b856 [fdbshow]: Handle FDB cleanup gracefully. (#1926)
1437bf2 [202012] Add DHCPv6 Relay counter and ipv6 helper CLI (#1917)
09ebac5 Bug fix in fastboot enhancement (#1928)

[sonic-utilities] submodule update

---

.azure-pipelines/azure-pipelines-image-template.yml

When a failed job retry. Publish artifact will fail for duplicated name

[ci] Fix PR checker archieve artifacts step

---

platform/components/docker-gbsyncd-credo.mk
platform/components/docker-gbsyncd-credo/Dockerfile.j2
platform/components/docker-gbsyncd-credo/crshell

Sonic master has moved to use SAI v1.9.1.  For consistency, use the latest credo sai v0.7.2 package, built with
SAI header v1.9.1 too. 
1. Update credo sai url for v0.7.2
2. Add a debug tool crshell

[gearbox] use credo sai v0.7.2

---

scripts/versions_manager.py

Fix some of the version files not used issue.
One of example version file version-py3-all-armhf, when building marvell-armhf, the version is used as expected, but it not use.

[Build]: Fix reproducible build version not correct issue

---

dockers/docker-router-advertiser/start.sh

Radvd is not running on M0
Edited start.sh to start radv on MgmtToRRouter
Run radv docker on an M0 device

[radv] Run radv on MgmtToRRouter

---

platform/mellanox/mlnx-platform-api/sonic_platform/led.py
platform/mellanox/mlnx-platform-api/tests/test_led.py

**Depends on** https://github.com/Azure/sonic-buildimage/pull/9358
Adjust LED logical according to hw-mgmt change.
Add a trigger to set LED to blink. 
Manual test

[Mellanox] Add a trigger to set LED to blink

---

.azure-pipelines/official-build.yml
azure-pipelines.yml

Enable azp in 202111 branch

---

platform/innovium/sonic-platform-modules-wistron/sw-to3200k/sonic_platform/__init__.py

Cannot retrieve and display the reboot-cause.
Correct the platform initialization definition.
Manual reboot and then 'show reboot-cause'
Update wistron platform definition.

[201911][Innovium] Update Wistron platform definition

---

src/sonic-config-engine/tests/sample_output/py2/buffers-mellanox2410-dynamic.json
src/sonic-config-engine/tests/sample_output/py3/buffers-mellanox2410-dynamic.json
src/sonic-config-engine/tests/test_j2files.py

Fix sonic-config-engine unit test failure
- Do not use pytest fixture in the test since it is not compatible with `unittest` framework which is used by all of the rest test cases.
- Supply 2 missing files
Run unit test or compile the module (when the unit test will run automatically)

[Unit test] Fix sonic config engine unit test failure

---

platform/mellanox/sdk-src/sxd-libs/Makefile

To have an ability to use PRM sniffer.
Enabled the option in configure flags.
Built and ran on switch. Enabled the feature in runtime and checked the sniffer recording.

[Nvidia][SDK] Build SDK with PRM sniffer support

---

platform/checkout/cisco-8000.ini

Update cisco-8000 ref to release: 202012-v0.8

Update cisco-8000 ref to release: 202012-v0.8

---

device/mellanox/x86_64-nvidia_sn4800-r0/platform.json
device/mellanox/x86_64-nvidia_sn4800-r0/platform_components.json

Rename MSN4800 to SN4800 in platform files
Rename MSN4800 to SN4800 in platform files
Run build.

[Mellanox] Fix platform name for SN4800

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

The  character "?" is not supported in azp template trigger branches, only support *.

[Bug][Build]: Fix azp trigger branches error

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Update SDK with fixed for warmboot tofino2 
Added platform interface extension 
Create new package for Y2, Y1, X2, X1 profiles
Run test suites from sonic-mgmt repo

[BFN] update BFN SDK package 

---

.github/CODEOWNERS

Need new code owner for /device
Add new code owners for /device
- [x ] 201811
- [ x] 201911
- [ x] 202006
- [ x] 202012
- [ x] 202106

Update CODEOWNERS for /device

---

device/mellanox/x86_64-mlnx_msn4600c-r0/get_sensors_conf_path
device/mellanox/x86_64-mlnx_msn4600c-r0/sensors.conf.a1

Add sensor conf for MSN4600C A1 platform
Add a new sensor conf file and relevant scripts to support two different versions of the platform 
Run "sensors" cmd to check the output on the A1 platform to see whether it's as expected.

[Mellanox] Add sensor conf for MSN4600C A1 platform

---

platform/checkout/cisco-8000.ini

Update cisco-8000 ref to release: 202012-v0.8-nopatches

---

rules/phy-credo.mk

This is to fix the issue of phy-credo package in bullseye.

[phy-credo] Update package for bullseye

---

dockers/docker-sonic-mgmt/Dockerfile.j2

This PR includes the support for statistics module

Support for Statistics Python Module 

---

platform/checkout/cisco-8000.ini

Signed-off-by: Venkat Garigipati <venkatg@cisco.com>
update platform/cisco-8000 version to 202012-v0.91 tag branch
Changed the platform/checkout/cisco-8000.ini

Updated platform/cisco-8000 version to 202012-v0.91

---

device/mellanox/x86_64-nvidia_sn4800_simx-r0/platform.json

There was a missing file of platform.json on sn4800 SIMx platform
Add symbolic link to platform.json file from the real sn4800 platform
Run sn4800 SIMx and verify that platfrom.json file exist at the following folder:
/usr/share/sonic/device/x86_64-nvidia_sn4800_simx-r0

[Mellanox] Add platform.json file to sn4800 SIMx platform

---

.github/pull_request_template.md

Updating template description to include link to configuration schema for YANG module changes.
Updating template description to include link to configuration schema for YANG module changes. When reviewing yang models it becomes difficult to know the entire schema for the table for which yang is defined. Besides providing a clear picture, it will also help to document the config_db schema which is not upto date.
Updating template file

Update template pull_request_template.md

---

platform/broadcom/sai.mk

Update debian packet with PFC and ECMP nexthop resource fixes
Update debian package URL
Loaded on chassis
Updated BCM SAI packet with two fixes.

[libsaibcm] Update BCM SAI debian package.

---

platform/checkout/cisco-8000.ini

Update cisco-8000 ref to release: 202012-v0.94

---

platform/marvell-armhf/sonic-platform-et6448m/entropy.py
platform/marvell-armhf/sonic-platform-nokia/entropy.py

[Marevell] Fix armhf build failure

---

platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py

Fixes https://github.com/Azure/sonic-buildimage/issues/10038
Added 10G ports in sfp_list
Check syslogs, xcvrd status.
UT logs: 
[xcvrd_UT.txt](https://github.com/Azure/sonic-buildimage/files/8122046/xcvrd_UT.txt)

Dell: S6100 fix xcvrd crash

---

platform/broadcom/sonic-platform-modules-accton/as7326-56x/modules/accton_as7326_56x_leds.c

Fix led drv code bug
Fix code error for extra ")".
Modify code and build to check. Load image to test and led work well.
--> Please merge due to it is code bug.
--> Please merge due to it is code bug.
--> Please merge due to it is code bug.

[AS7326-5X] Fix code bug for led drv

---

src/sonic-config-engine/tests/common_utils.py
src/sonic-config-engine/tests/test_j2files.py

Fix sonic config engine test not stable issue

[Unit Test]: Fix sonic config engine test not stable issue

---

src/sonic-config-engine/tests/common_utils.py
src/sonic-config-engine/tests/test_j2files.py

Co-authored-by: azureuser <azureuser@contoso.com>
cherry-pick #10147  to 202012 branch.

[Unit Test]: Fix sonic config engine test not stable issue(#10147)

---

.gitmodules

Changes: 
1. Update submodule branch  to 202012
1. [sonic-linkmgrd][202012] submodule update 
a8ddff5 Jing Zhang      Fri Feb 25 11:38:28 2022 Incrementing tolerance on mux state inconsistency  (#27)
a3f78a3 Jing Zhang      Thu Feb 17 17:23:56 2022 Update log level for mux probing and mux state chance (#23)
05156fb Jing Zhang      Thu Feb 17 17:21:01 2022   Handle xcvrd crashing scenarios (#22)
74529ef Longxiang Lyu   Mon Feb 14 13:26:07 2022 [make] Enable make extra includes (#24)
To exclude active-active related changes in 202012.

[sonic-linkmgrd][202012] submodule update

---

platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/eeprom.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/fan_drawer.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/sfp.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/thermal.py

N3248TE - Platform API 2.0 changes
Implemented the functional API's needed for Platform API 2.0
Used the API 2.0 test suite to validate the test cases.

DellEMC: N3248TE Platform API 2.0 changes

---

files/build/versions/default/versions-web
platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Updated SDE package for Barefoot platform with fixes for:
1. NAT 
2. VRF 
Create package with fresh SDE image
Run regressions using sonic-mgmt

[ BFN ] update SDE package for BFN platform

---

platform/checkout/cisco-8000.ini

Update cisco-8000 ref to release: 202012-v0.95

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/pltfm_mgr_rpc/pltfm_mgr_rpc.py

Signed-off-by: Taras Keryk <tarasx.keryk@intel.com>
The previous implementaion of API for platform component 
https://github.com/Azure/sonic-buildimage/pull/10180
didn't have the new thrift file
Add the new thrift-generated: pltfm_mgr_rpc.py

[BFN] Regenerated pltfm_mgr_rpc.py to the latest version

---

build_debian.sh

Fix some version info missing in version control files issue
Change to collect version before it cleaned up

[Build]: fix some version info missing in version control files issue

---

azure-pipelines.yml

Some PR builds in 20201/202006 branch failed with wrong dependencies, it should be caused by mirror change.
See https://dev.azure.com/mssonic/build/_build/results?buildId=80941&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318
```
The following packages have unmet dependencies:
python-dev : Depends: libpython-dev (= 2.7.16-1) but it is not going to be installed
Depends: python2.7-dev (>= 2.7.16-1~) but it is not going to be installed
Depends: python2-dev (= 2.7.16-1) but it is not going to be installed
python3-dev : Depends: libpython3-dev (= 3.7.3-1) but it is not going to be installed
Depends: python3.7-dev (>= 3.7.3-1~) but it is not going to be installed
```
Enable PR reproducible build.

[Build]: Enable the PR reproducible build

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Support to set jobFilters
There are no successful nephos builds, we can add the nephos when it succeeds, it has low impact on the version upgrade job.

[Build]: Support to set jobFilters

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/docker-sonic-slave-template.yml

cherry-pick to 202111 branch to fix bug.

[ci] Fix remove sonic-slave-* docker image issue when building sonic-slave* (#10296)

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
scripts/docker_version_control.sh

1. disable docker base pull
2. add debian:* to white list
3. fix null sha256 value in version files.

[build] Fix issues found in reproducible build.

---

.azure-pipelines/build-commonlib.yml
.azure-pipelines/template-commonlib.yml

To remove reference on Azure.sonic-buildimage artifacts.
Azure.sonic-buildimage has a higher failure rate.

[ci] Add azure pipeline to build common libs.

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/build-commonlib.yml
.azure-pipelines/docker-sonic-slave-template.yml
.azure-pipelines/template-clean-sonic-slave.yml
.azure-pipelines/template-commonlib.yml
scripts/docker_version_control.sh

There are some code conflicts. It needs to cherry-pick manually.

Cherry-pick shilong's PR into 202012 branch

---

device/dell/x86_64-dellemc_n3248te_c3338-r0/system_health_monitoring_config.json
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/fan.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-dell/n3248te/sonic_platform/sfp.py

DellEMC: N3248TE platform API2.0 changes
N3248TE Platform API 2.0 changes
- Implemented the functional API's needed for Platform API 2.0
- Added system_health_monitoring_config.json file
Used the API 2.0 test suite to validate the test cases.

DellEMC: N3248TE platform API2.0 changes

---

device/dell/x86_64-dellemc_n3248te_c3338-r0/platform.json

Added platform.json file for N3248TE
Defined the platform.json file with the required components under chassis.
validated the API 2.0 test suite

 DellEMC: Added platform.json file for N3248TE

---

platform/checkout/cisco-8000.ini

Update cisco-8000 ref to release: 202012-v0.96

---

device/barefoot/x86_64-accton_as9516_32d-r0/platform.json

SONiC platform API tests (platform_tests/api) rely on some additional details about DUT from platform.json file.
Updated as9516_32d platform.json with missing information.
Run platform_tests/api TCs from sonic-mgmt.

[BFN] Updated x86_64-accton_as9516_32d-r0/platform.json

---

src/sonic-build-hooks/hooks/apt
src/sonic-build-hooks/hooks/apt-get
src/sonic-build-hooks/scripts/buildinfo_base.sh
src/sonic-build-hooks/scripts/collect_version_files
src/sonic-build-hooks/scripts/post_run_buildinfo
src/sonic-build-hooks/scripts/pre_run_buildinfo

The code is out of sync for a long time in 202106 branch, merge 5 commits from master to 202106.

[Merge]: Merge code to 202106

---

.azure-pipelines/docker-sonic-slave-template.yml
.azure-pipelines/docker-sonic-slave.yml

1. Docker push task template issue.
2. System.PullRequest.TargetBranch can't be used in template

[ci] Fix issues in docker-slave official build.

---

.azure-pipelines/docker-sonic-slave.yml

pipeline bug. Test didn't covered it.

[ci] Fix a docker-sonic-slave pipeline format in variable reference.

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Updated SDE packages for bfn platform
1. introduced X6 profile 
2. fixes for drop counters
3. fixes for platform part
Created new package 
Run sanity cases from sonic-mgmt repo

[BFN] updated SDE packages for BFN platforms

---

platform/checkout/cisco-8000.ini

Update cisco-8000 ref to release: 202012-v0.97

---

build_debian.sh

In sonic-utilities repo, it is required to install docker>=4.4.4
https://github.com/Azure/sonic-utilities/blob/f70dc27827a88d70e91e15ecdcde2ebbc446116d/setup.py#L187

[Build]: Upgrade pip3 package docker to 5.0.3

---

azure-pipelines.yml

When cherry-picking PR(#10341), it involved unexpected codes.
It breaks PR validation.
remove unexpected codes.

[ci] Fix PR validation issue involved by cherry-pick enabling ACR.

---

sonic-slave-bullseye/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2

Add `libgmock-dev` to the package list required by `linkmgrd` unittests.
Required by PR: https://github.com/Azure/sonic-linkmgrd/pull/45
Add the package to the package list.
Build `docker-mux` with ` KEEP_SLAVE_ON=yes` and verify `libgmock-dev` is present.

Add `libgmock-dev` package for `linkmgrd`

---

src/thrift_0_13_0/Makefile
src/thrift_0_13_0/patch/0002-Remove-minimist-packages.patch

resolve alert CVE-2021-44906
Patching on thrift.0.13.0 for package minimist
build thrift 0.13.0 in build docker

[CG-Fix-CVE-2021-44906] Patching on thrift.0.13.0 for package minimist

---

files/image_config/copp/copp_cfg.j2

Add a couple devices to dhcp trap enabled list. Fix one typo

[202012][copp cfg] enable dhcp trap for a couple more devices

---

src/dhcpmon/src/dhcp_device.c

Fixes issue https://github.com/Azure/sonic-buildimage/issues/10326
Adding an offset bound check during DHCPv6 header inspection to prevent segmentation fault issue.
Each time offset is incremented to fetch a different field in the DHCPv6 header, check if the buffer contains this offset and only then try to fetch it.
If the offset is out of the DHCP header bounds, print a message to syslog and return.

[DHCPv6 relay monitor] [202106] Add an offset bound check during DHCPv6 header inspection to prevent segmentation fault

---

.azure-pipelines/azure-pipelines-image-template.yml

When a failed job retry. Publish artifact will fail for duplicated name

[ci] Fix PR checker archieve artifacts step (#9357)

---

src/thrift_0_13_0/Makefile
src/thrift_0_13_0/patch/0003-Remove-underscore-packages.patch

[CG] Fix CG alert about underscore version.

---

src/sonic-yang-models/setup.py
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/bgp_internal.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp_internal.json
src/sonic-yang-models/yang-models/sonic-bgp-internal-neighbor.yang

closes #10157 
Add yang model for the `bgp_internal_neighbor` table in config_db
Add new yang model file and unit tests
UT and compile `sonic_yang_models-1.0-py3-none-any.whl` and `sonic_yang_mgmt-1.0-py3-none-any.whl`

[Yang]: bgp internal neighbor yang model

---

.github/pull_request_template.md

… folder
Update template to point to configuration.md in yang-model folder.

[Template] Update template to point to configuration.md in yang-model folder

---

push_docker.sh

cherry-pick PR from master branch:
[[ci] Support multi tags when pushing docker image](https://github.com/Azure/sonic-buildimage/pull/10771)

Cherry-pick some PRs from master branch.

---

src/dhcp6relay/src/relay.cpp

… addresses (#10712)
(cherry picked from commit 243d0c73f96991ec0efbde76c7ea1358c833cd48)
dhcp6relay fails to bind to interface's link-local ipv6 addresses from time to time after interface is brought up due to not waiting for a long enough time period for ipv6 addresses to bind to the interface.
Enhanced syslog to give more meaningful error log
Added a retry mechanism to check for interface's ipv6 global and link-local addresses 3 times, every 5 seconds. If ipv6 address is still missing or binding failed, alert in syslog

[201811][dhcp6relay] Add retry mechanism for binding socket to interface ipv6 addresses

---

azure-pipelines.yml

[202012] Use 202012 branch for sonic-mgmt

---

src/sonic-config-engine/tests/test_cfggen.py
src/sonic-config-engine/tests/test_minigraph_case.py
src/sonic-config-engine/tests/test_multinpu_cfggen.py

UT for sonic-config-engine is broken.
Remove yang validation.
Run UT for sonic-config-engine.

[sonic-cfggen]: Fix broken UT

---

src/sonic-host-services/scripts/determine-reboot-cause

… file removal issue (#10751)"
This reverts commit dee7655526699e3f66bf3744e098f03203345449.
Original commit was not necessary.
undo the original change.
python os.remove(xxx) can remove a file or a link.

Revert "[reboot-cause] Fix a broken symlink of previous-reboot-cause  file removal issue (#10751)"

---

.azure-pipelines/template-commonlib.yml
slave.mk

cherry-pick PR from master:
https://github.com/Azure/sonic-buildimage/pull/10817

[ci] Add arm artifacts in common lib azure pipeline

---

dockers/docker-mux/supervisord.conf

[sonic-linkmgrd][202012] submodule updates
489cf3 Jing Zhang      Wed May 18 09:59:02 2022 -0700  Avoid switching active when `LinkState == Down` (#77)
a6c9713 Jing Zhang      Tue May 24 11:03:54 2022 -0700  [202012] Add option to enable or disable default route related feature  (#72)
dbb607d Jing Zhang      Thu May 12 08:19:20 2022 -0700  [ci]: uplift diff coverage threshold to 80% (#71)
sign-off: Jing Zhang [zhangjing@microsoft.com](mailto:zhangjing@microsoft.com)

[sonic-linkmgrd][202012] submodule updates

---

.github/CODEOWNERS

[CODEOWNERS]: update code owners for various repos

---

dockers/docker-dhcp-relay/dhcp-relay.monitors.j2
dockers/docker-dhcp-relay/dhcp-relay.programs.j2
dockers/docker-dhcp-relay/dhcpv6-relay.agents.j2
dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay-no-ip-helper.supervisord.conf
src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay.supervisord.conf
src/sonic-config-engine/tests/sample_output/py3/docker-dhcp-relay-no-ip-helper.supervisord.conf
src/sonic-config-engine/tests/t0-sample-no-ip-helper-graph.xml
src/sonic-config-engine/tests/test_j2files.py

Some vlans could have missing ip/ipv6 helpers. Adding unit test to ensure expected processes run in dhcp_relay docker
Build sonic_config_engine python wheel. Run dhcp_relay docker with expected docker supervisord file

[dhcp_relay] Add "vlan missing ip helper" dhcp relay unittest

---

scripts/build_debian_base_system.sh

[Build]: Fix the version files in host-base-image for armhf/arm64 not used issue
https://dev.azure.com/mssonic/build/_build/results?buildId=105620&view=logs&j=88e1b2d1-110a-5bbf-c794-091704096bca&t=41cf5733-fbe6-5db0-23ba-ae081db3aefb
```
+ scripts/build_debian_base_system.sh arm64 bullseye ./fsroot-centec-arm64
E: Version '8.32-4+b1' for 'coreutils' was not found
```
The version "8.32-4+b1" is not as expected, the correct version should be "8.32-4", see https://github.com/Azure/sonic-buildimage/blob/ca284a1bf2bcdb65dd67d5d739dd6a68021f65f7/files/build/versions/host-base-image/versions-deb-bullseye-arm64#L1
See the test on 202111 branch: https://dev.azure.com/mssonic/build/_build/results?buildId=105896&view=results

[Build]: Fix the version files for armhf/arm64 not used issue

---

platform/checkout/cisco-8000.ini

Signed-off-by: Kevin Wang <shengkaiwang@microsoft.com>
Important fixes since 202012-v0.97:
V0.102:
Hwsku changes to Cisco-8102-C64
Fix for watermark clear issue
V0.101:
Fix for dhcp_relay test issue
V0.100:
Fix for container_autorestart test issue
V0.99:
Fix for everflow test issue
Fix for pfcwd test issue
Fix for copp test issue
V0.98:
Fix for qos_sai  test issue
RDMA enhancements dev complete and content included in this drop (flow based VoQ, ECN, Alpha)

Update cisco-8000 ref to release: 202012-v0.102

---

device/arista/x86_64-arista_7050cx3_32s/Arista-7050CX3-32S-D48C8/td3-a7050cx3-32s-48x50G+8x100G.config.bcm
rules/config

This PR is to update submodule `sonic-utilities` for `202012` branch.
Changes include 
```
74bf951 [cherry-pick][202012] Update db_migrator to support pfcwd_sw_enable (#2160)
b3928ed [202012][cherry-pick]Fix validation of input of `config mirror_session add` (#2187)
```

[202012][submodule] Advance `sonic-utilities` submodule

---

.azure-pipelines/azure-pipelines-repd-build-variables.yml

It seems that reproducible build and dood conflicts.
Disable reproducible build first. Investigate the issue later.

[build] Disable reproducible build in 202205 branch.

---

scripts/build_debian_base_system.sh

[Bug]: fix the version file name issue
The version file version-deb not found, it should be versions-deb
Change the version-deb, to versions-deb
https://dev.azure.com/mssonic/build/_build/results?buildId=107587&view=results

[Bug]: fix the version file name issue

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/official-build.yml
azure-pipelines.yml

docker hub will limit the pull rate.
Use ACR instead to pull debian related docker image.
Set DEFAULT_CONTAINER_REGISTRY in pipeline.

[ci] Set default ACR in UpgrateVersion/PR/official pipeline. (#10341)

---

src/sonic-bgpcfgd/bgpcfgd/main.py
src/sonic-bgpcfgd/bgpcfgd/managers_advertise_rt.py
src/sonic-bgpcfgd/bgpcfgd/managers_rm.py
src/sonic-bgpcfgd/tests/test_advertise_rt.py
src/sonic-bgpcfgd/tests/test_rm.py

This is a cherry-pick PR from master to 202012 branch
below is the original PR which merged to master.
https://github.com/Azure/sonic-buildimage/pull/10716

cherry-pick [bgpcfgd] ECMP overlay VxLan with BGP support to 202012

---

rules/sonic-config.dep

Cherry pick PR (#10770 ) from master branch

[build] Add dependencies for sonic-config-engine to block bad PR.

---

rules/sonic-config.dep

Cherry pick PR(#10770 ) from master branch.

[build] Add dependencies for sonic-config-engine to block bad PR. 

---

platform/broadcom/docker-syncd-brcm.mk

Extra line was added by mistake. But seemingly no impact to build, therefore missed.
Remove the extra line
Build.

[brcm docker build] remove extra line

---

device/arista/x86_64-arista_7050dx4_32s/Arista-7050DX4-32S/sai.profile
device/arista/x86_64-arista_7050dx4_32s/Arista-7050DX4-32S/td4-a7050dx4-32s-32x400G.config.bcm
device/arista/x86_64-arista_7050dx4_32s/platform_env.conf
device/arista/x86_64-arista_7050px4_32s/platform_env.conf

Add ASIC configs for blackhawktd4
Verified that 400G ports of 400GBASE-CR8 are up and traffic can pass

[Arista] Add ASIC configs for blackhawktd4

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/template-skipvstest.yml
.azure-pipelines/vstest-exclude
.azure-pipelines/vstest-include
Makefile.cache
azure-pipelines.yml

Cherry pick PR from master:
[[build] Add version files to docker image dependencies](https://github.com/Azure/sonic-buildimage/pull/11179)
[[ci] Support to skip vstest using include/exclude config file. ](https://github.com/Azure/sonic-buildimage/pull/11086)

[build] Add version files to docker image dependencies

---

README.md

Add the branch 202205 and branch 202111 in the README.md

Add the branch 202205 and branch 202111 in the README.md

---

device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
src/sonic-device-data/tests/permitted_list

(cherry-pick of PR 11166) Setting the soc property for num_sa_per_sc on macsec

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Keysight provide a new version with some snappi API source code related fix:  snappi[ixnetwork,convergence]==0.7.44 
Upgrade snappi version to 0.7.44
Whether it's installed in sonic-mgmt docker container

Upgrade snappi version to 0.7.44

---

rules/openssh.mk

Cherry-pick: https://github.com/Azure/sonic-buildimage/pull/11405
Fix the openssh build issue, upgrade from 8.4p1-5 to 8.4p1-5+deb11u1.
https://dev.azure.com/mssonic/build/_build/results?buildId=120209&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318
```
+ sudo dpkg --root=./fsroot-broadcom -i target/debs/bullseye/openssh-server_8.4p1-5_amd64.deb
dpkg: warning: downgrading openssh-server from 1:8.4p1-5+deb11u1 to 1:8.4p1-5
(Reading database ... 44818 files and directories currently installed.)
Preparing to unpack .../openssh-server_8.4p1-5_amd64.deb ...
Unpacking openssh-server (1:8.4p1-5) over (1:8.4p1-5+deb11u1) ...
dpkg: dependency problems prevent configuration of openssh-server:
openssh-server depends on openssh-client (= 1:8.4p1-5); however: …
```

[202205] Upgrade openssh to 8.4p1-5+deb11u1

---

.azure-pipelines/azure-pipelines-repd-build-variables.yml

Enable reproducible build in 202205 branch.
Because there are some package version issues.

[ci] Enable reproducible build in PR checks.

---

src/sonic-yang-models/doc/Configuration.md

**HLD:** https://github.com/sonic-net/SONiC/pull/1002
* To implement Syslog Source IP feature
* Added the relevant yang doc
* N/A
* N/A
[sonic-syslog.yang](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-syslog.yang)
```
'//||\\`
''``
```

[ssip]: Update YANG doc

---

.azure-pipelines/vstest-exclude

[ci] Add vstest skip folder sonic-slave-*

---

.azure-pipelines/azure-pipelines-repd-build-variables.yml

Reproducible build is enabled by fault in master branch.
Change the variable used in official build.

[ci] Disable reproducible build in master branch official build

---

platform/checkout/cisco-8000.ini

Update cisco-8000 platform version to 202012-v0.106

update cisco-8000 platform version to 202012-v0.106

---

azure-pipelines.yml

Transfer organization from Azure to sonic-net for sonic-mgmt

[ci] Transfer organization from Azure to sonic-net for sonic-mgmt

---

azure-pipelines.yml

Why I did it
Transfer organization from Azure to sonic-net for sonic-mgmt
Transfer organization from Azure to sonic-net for sonic-mgmt

[ci] Transfer organization from Azure to sonic-net for sonic-mgmt (#11559)

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Install celery in sonic-mgmt image
Install celery in sonic-mgmt image

Install celery in sonic-mgmt image

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/official-build.yml

[ci] Support the cross build for armhf/arm64
See build: https://dev.azure.com/mssonic/build/_build/results?buildId=128839&view=results

[ci] Support the cross build for armhf/arm64

---

sonic-slave-bullseye/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2
sonic-slave-stretch/Dockerfile.j2

Building docker-sonic-vs requires dependencies installed in sonic-slave-buster
Add libs to sonic-slave-buster and sonic-slave-bullseye
Check files

Event libswsscommon deps

---

.github/workflows/automerge.yml

Fix github action automerge doesn't work issue.

[actions] Fix automerge actions don't work issue.

---

.gitmodules

Kernel:
* 86c4b66 2022-07-28 | [Mellanox] Add new kernel patches from HW-MGMT package V.7.0020.3005 (#287) (HEAD -> 202205) [Kebo Liu]
* 3a8416a 2022-07-05 | [patch] mlxsw: i2c: Prevent transaction execution for special chip (#279) [Stepan Blyshchak]
swss:
* 3f69944 2022-08-10 | Set internal class state to reflect the actual state (#2410) (HEAD -> 202205, tag: foo) [Prince Sunny]
* 87e98eb 2022-08-09 | [portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it (#2400) [Stephen Sun]
* e71ab99 2022-07-29 | portsorch: initial support for link-training (#2359) [Dante (Kuo-Jung) Su]
* ed5e5be 2022-07-08 | Port configuration incremental update support (#2305) [Junchao-Mellanox]
utilities:
* 0df3ba8 2022-08-12 | Revert "Improve the way to check …

[202205][kernel][swss][utilities][platform-daemon][linkmgrd] advance submodule head

---

.gitmodules

PR #11705 introduced extra linux kernel submodule entry.
Remove the duplicate entry.

[202205] address multiple linux-kernel submodule entries issue

---

device/ruijie/x86_64-ruijie_b6510-48vs8cq-r0/monitor.py

The [xml.etree.ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html#module-xml.etree.ElementTree) module is not secure against maliciously constructed data.
Remove xml. Use [lxml](https://pypi.org/project/lxml/) XML parsers package that prevent potentially malicious operation.

[device/ruijie] Mitigation for security vulnerability

---

files/image_config/process-reboot-cause/process-reboot-cause

Add the hardware reboot cause when the previous software reboot failed
Check both hardware reboot cause and software reboot cause.
Add the hardware reboot as actual reboot cause 
if any hardware reboot cause is available for any software reboot.
Perform reboots and verify the reboot-cause
Manual test results >>>
1. HW reboot : power loss
```
admin@SONiC:~$ show reboot-cause
Power Loss
```
2. Cold reboot
```
admin@SONiC:~$ show reboot-cause
User issued 'reboot' command [User: admin, Time: Mon Aug 22 22:54:07 UTC 2022]
```
3. Fast reboot
```
admin@SONiC:~$ show reboot-cause
User issued 'fast-reboot' command [User: admin, Time: Mon Aug 22 23:18:12 UTC 2022]
```
4. Power cycle during warm-reboot
```
admin@SONiC:~$ show reboot-cause
User issued 'warm-reboot' command [User: admin, Time: Mon Aug …
```

[201811] Add the hw reboot cause if it happened during software reboot

---

files/image_config/process-reboot-cause/process-reboot-cause

Why I did it
Add the hardware reboot cause when the previous software reboot failed
How I did it
Check both hardware reboot cause and software reboot cause.
Add the hardware reboot as actual reboot cause
if any hardware reboot cause is available for any software reboot.
Perform reboots and verify the reboot-cause
1. warm reboot 
```
admin@str-msn2700-20:~$ show reboot-cause
User issued 'warm-reboot' command [User: admin, Time: Wed Aug 24 17:29:15 UTC 2022] Actual reboot cause : Power Loss
```
2. power loss
```
admin@str-msn2700-20:~$ show reboot-cause
Power Loss
```
3. soft-reboot
```
admin@str-msn2700-20:~$ show reboot-cause
User issued 'soft-reboot' command [User: admin, Time: Wed Aug 24 17:21:41 UTC 2022]
```
4. cold reboot
```
admin@str-msn2700-20:~$ show reboot-cause …
```

[201911] Add hardware reboot cause when software reboot failed

---

.github/workflows/automerge.yml
.github/workflows/label.yml

Reproducible build version upgrading PR can't be merged automatically because of lacking an approval.
1. Add auto approve step when adding label to version upgrading PR.
2. Use mssonicbld TOKEN to merge version upgrading PR instead of 'github actions'

[actions] Update github actions label and automerge.

---

.azure-pipelines/azure-pipelines-repd-build-variables.yml
.azure-pipelines/official-build.yml
azure-pipelines.yml

1. Restrict reproducible build branch scope.
2. Use pipeline variable template in master branch.

[ci] Update reproducible build related pipeline.

---

.github/workflows/label.yml

Cherry pick a github action related PR(#11736).
1. Add auto approve step when adding label to version upgrading PR.
2. Use mssonicbld TOKEN to merge version upgrading PR instead of 'github actions'

[actions] Update github actions label and automerge. (#11736)

---

.azure-pipelines/azure-pipelines-build.yml

Include following new linux kernel submodule commits:
```
815cb34 [patch]: Add accept_untracked_na kernel param (#291)
fbb76cc Remove kernel config SERIAL_8250_RUNTIME_UARTS (#286)
```
Include following new SWSS submodule commits:
```
eedf59d [intfmgr]: Enable `accept_untracked_na` kernel param (#2439)
bbd4eb7 [BFD]Clean up state_db BFD entries on swss restart (#2434) (#2435)
aa7b546 [FDB] [202012] Fix fbdorch to properly handle syncd FDB FLUSH Notif (#2401)
4190c13 Support for platforms based on Clounix Networks' device (#2399)
```

[202012][kernel][swss]: Linux kernel and SWSS submodule update

---

.github/workflows/label.yml

Approve step needs special permission settings. We already added permission setting to enable bypass merging PR.
So, approve step is not necessary.

[actions] Remove approve step in label action.

---

.github/workflows/label.yml

Cherry pick PR (#11968 )
Approve step needs special permission settings.
We already added permission setting to enable bypass merging PR. So, approve step is not necessary.

[actions] Remove approve step in label action. (#11968)

---

src/sonic-frr/patch/0009-ignore-route-from-default-table.patch
src/sonic-frr/patch/series

Manually cherry-picking #12018 

[202205][zebra] ignore route from default table

---

rules/config

Need to upgrade k8s package version
Change k8s version from 1.21 to 1.22
Command "kubectl version"

Upgrade k8s package version

---

dockers/docker-ptf/Dockerfile.j2

test_sai_qos failed because of the following error:
```
"stderr_lines": [
"Traceback (most recent call last):", 
"  File \"/usr/bin/ptf\", line 522, in <module>", 
"    test_modules = load_test_modules(config)", 
"  File \"/usr/bin/ptf\", line 413, in load_test_modules", 
"    mod = imp.load_module(modname, *imp.find_module(modname, [root]))", 
"  File \"saitests/switch.py\", line 19, in <module>", 
"    import switch_sai_thrift", 
"ImportError: No module named switch_sai_thrift"
], 
```
It's because `test_sai_qos` runs ptf script which imports switch_sai_thrift, switch_sai_thrift is installed from  `python-saithrift_0.9.4_amd64.deb`.
For master image, the deb file is for python3, but ptf only has virtual python3 environment, that's …

Enable system-site-packages for virtual py3 env in ptf docker and install thrift for test_qos_sai

---

dockers/docker-sonic-mgmt/Dockerfile.j2

In order to support Python3 migration of docker-sonic-mgmt, the docker base image should be upgrade first.
Modify docker build file(docker-sonic-mgmt/Dockerfile.j2):
1. Update base image from ubuntu18.04 to ubuntu20.04
2. Fix necessary dependencies.
3. Compared to previous PR#11831, fix issue: #11950 
Randomly select supported testbed, manually run a few tests and all pass:
vxlan/test_vxlan_decap.py
pfcwd/test_pfcwd_all_port_storm.py
acl/null_route/test_null_route_helper.py
acl/test_acl.py
vlan/test_vlan.py
platform_tests/test_reboot.py
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit[None-xoff_1]
Update docker-sonic-mgmt/Dockerfile.j2. After upgrade, Py2 is 2.7.18, Py3 is 3.8.10, Ubuntu is 20.04.

Upgrade docker-sonic-mgmt base image from Ubuntu18.04 to 20.04

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Fix issue of can't import dateutil.parser in show_techsupport/test_auto_techsupport.py
install python-dateutil

install missed package python-dateutil

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Fix the error of pip install
Remove the backslash

Fix pip install error

---

platform/checkout/cisco-8000.ini

Update cisco-8000 submodule to v0.117

---

device/arista/x86_64-arista_720dt_48s/platform.json
device/arista/x86_64-arista_720dt_48s/platform_components.json

Add components data for sonic-mgmt testing
Update platform.json and add platform_components.json
Ran sonic-mgmt tests (test_chassis and test_component)

[Arista] Add components for 720DT-48S

---

.github/pull_request_template.md

Updated the PR template with comment received on removing the reference link on GCU. Hence added text to show reference for GCU PR.

Updated the PR template 

---

rules/debootstrap.mk

Update debootstrap to 1.0.123+deb11u1

---

dockers/docker-sonic-mgmt/Dockerfile.j2

TestbedV2 relies on storage blob related python package to upload logs.
Install storage blob related packages

Install storage blob related packages

---

.github/workflows/pr_cherrypick_prestep.yml

Trigger branch is wrong by mistake.
This change didn't need in release branches.
It only affects master branch.

[action] Fix trigger issue in PR pre-cherry-pick action.

---

platform/broadcom/sonic-platform-modules-brcm-xlr-gts/utils/brcm-xlr-gts-create-eeprom-file.py

`os` - not secure against maliciously constructed input and dangerous if used to evaluate dynamic content.
`os` - use with `subprocess`

[broadcom] Replace popen function

---

src/sonic-config-engine/minigraph.py
src/sonic-config-engine/tests/test_cfggen.py

This is to backport #12251 to 202012

[202012] [minigraph] Remove SLB and bgp monitor peers for storage backend

---

src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/setup.py
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/restapi.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/restapi.json
src/sonic-yang-models/yang-models/sonic-restapi.yang

Reverting PR https://github.com/sonic-net/sonic-buildimage/pull/12374
Fix build issues
This PR fixed https://github.com/sonic-net/sonic-buildimage/issues/10548

add Restapi Yang model

---

dockers/docker-sonic-mgmt/Dockerfile.j2

The Dockerfile of docker-sonic-mgmt became a little bit messy over time. Some packages are also a little bit too old. It would be better to do some cleanup and upgrade some important packages.
* Updated the dockerfile template for building docker-sonic-mgmt.
* Locally built the docker-sonic-mgmt image and used it to run some test scripts.
Changes:
* The `build-essential` package contains `gcc` and `make`. It's unnecessary to install them again.
* The `python-is-python2` package is included in the `python` package for Ubuntu 20.04. It's unnecessary to install it again.
* Sort the apt and pip packages by alphabetic order.
* Cleanup `get-pip.py` after installation.
* Cleanup the python-scapy deb package after installation.
* Ensure that the python `pip`, `setuptools` and `wheel` packages are …

[docker-sonic-mgmt] Cleanup and upgrade some packages

---

.github/workflows/automerge.yml

automerge action shows little message. It is hard to debug.

[action] Add debug info for automerge github action.

---

.github/workflows/automerge.yml
.github/workflows/pr_cherrypick_prestep.yml

1. Changing log level didn't work according to document. Maybe version is too old.
2. Avoid using '-' character in branch name to see if auto cherry-pick PR will be completed.

[action] Update automerge version, change log level and change auto cherry-pick branch name.

---

.azure-pipelines/run-test-template.yml
azure-pipelines.yml

[ci] Fix test job issue on checkout step

---

files/Aboot/boot0.j2

Add support for UpperlakeElite product
Add support for UpperlakeElite product

[Arista] Add support for UpperlakeElite

---

.azure-pipelines/run-test-template.yml
azure-pipelines.yml

The vs build failed but some of the test passed.
See build: https://dev.azure.com/mssonic/build/_build/results?buildId=159753&view=logs&jobId=e2a1d004-6151-514d-dd3b-ba225f574bd9&j=e2a1d004-6151-514d-dd3b-ba225f574bd9&t=f0777b63-8377-5b65-c700-6568122e76b9
```
[ FAIL LOG START ] [ target/python-wheels/buster/sonic_yang_models-1.0-py3-none-any.whl ]
[ REASON ] :      target/python-wheels/buster/sonic_yang_models-1.0-py3-none-any.whl does not exist   NON-EXISTENT PREREQUISITES: target/debs/buster/libyang_1.0.73_amd64.deb-install target/debs/buster/libyang-cpp_1.0.73_amd64.deb-install target/debs/buster/python3-yang_1.0.73_amd64.deb-install 
[ FLAGS  FILE    ] : [] 
[ FLAGS  DEPENDS ] : [vs amd64 buster] 
[ FLAGS  DIFF    ] : [vs amd64 buster ] 
/sonic/src/sonic-yang-models /sonic
running …
```

[Ci] clean up the old artifacts in the agent before downloading the new artifacts

---

.azure-pipelines/azure-pipelines-repd-build-variables.yml
.azure-pipelines/official-build.yml
azure-pipelines.yml

Cherry-pick PRs relative to reproducible build option from master branch.

[202106][ci] Cherry-pick PRs relative to reproducible build option from master branch.

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml

LGTM will be deprecated in December.
Use github code scan instead.

[action] Use github code scan instead of LGTM.

---

.azure-pipelines/azure-pipelines-repd-build-variables.yml
.azure-pipelines/official-build.yml
azure-pipelines.yml

Cherry-pick PRs relative to reproducible build option from master branch.

[202111][ci] Cherry-pick PRs relative to reproducible build option from master branch

---

src/dhcp6relay/src/relay.cpp

[201811] address dhcp relay build issue

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py

syseepromd in pmon crashes because of missing import in python script and doesn't get in running state
Fix missing import issue to avoid python script failing
Boot system and wait till syseepromd gets into running state

[BFN] Fix missing import error

---

.azure-pipelines/official-build.yml
azure-pipelines.yml

Add azp trigger for future release branches.

[ci] Add azp trigger for future release branches.

---

src/sonic-eventd/tools/events_volume_test.py

[sonic-eventd] Replace subprocess with shell=True

---

platform/checkout/cisco-8000.ini

update cisco 8000 tag
update cisco 8000 tag

update cisco 8000 tag: 202205-v0.6

---

.azure-pipelines/trigger-publish-artifacts-build.yml

[ci] Upload the debian packages

[ci] Upload the debian packages

---

src/sonic-py-common/sonic_py_common/device_info.py
src/sonic-py-common/sonic_py_common/multi_asic.py

[sonic-py-common] Remove subprocess with shell=True

---

dockers/docker-lldp/lldpmgrd
dockers/docker-nat/restore_nat_entries.py
files/image_config/corefile_uploader/core_uploader.py
files/image_config/monit/memory_checker
files/image_config/monit/restart_service
files/scripts/mark_dhcp_packet.py

Replace os.system and remove subprocess with shell=True

---

src/sonic-host-services/scripts/hostcfgd
src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
src/sonic-host-services/tests/hostcfgd/test_vectors.py

Cherry-pick of https://github.com/sonic-net/sonic-host-services/pull/14 in 202205 branch
How I verify:
UT coverage for the changes are added.

[202205] Cherry-pick of master PR that handles Feature table changes based on device runtime metadata

---

device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t0.config.bcm
device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-C32/th-seastone-dx010-32x100G-t1.config.bcm
device/celestica/x86_64-cel_seastone-r0/Celestica-DX010-D48C8/th-seastone-dx010-48x50G+8x100G.config.bcm

DX010 platform has limited routing table size.
Enabling LPM.

Enable Dx010 LPM

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/eeprom.py

syseepromd in pmon crashes because of missing import in python script and doesn't get in running state
Fix missing import issue to avoid python script failing
Boot system and wait till syseepromd gets into running state

[BFN]: Add missing import

---

device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D44C10/port_config.ini
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D44C10/sai_2700_44x50g_10x100g.xml

Add NVIDIA Copyright header for new "NVIDIA" files
Add the copyright header as remark at the head of the file

[Mellanox] update NVIDIA copyright header for NVIDIA added files

---

.github/workflows/automerge_scan.yml

Scan mssonicbld's PR and merge those whose checks passed.

[action] Add github action to merge mssonicbld's PRs which can be merged

---

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_ssd_upgrade_status.sh

- `smartctl` tool is available only in PMON docker. Hence, the tool may be not accessible incase PMON docker goes down.
- Using `iSMART_64` tool to fetch the SSD firmware version and device model information.
- Replacing smartctl with iSMART_64.

[DellEMC] Master: S6100: SSD upgrade status: Moving from smartctl to iSMART

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/build-template.yml

Publish docker saiserverv2 in the build pipeline.
Add docker saiserverv2 target in the build template.
Run test in #12836 and the target has been built out successfully.

[202012][SAI-PTF] Publish docker saiserverv2 in 202012 branch

---

.github/pull_request_template.md

Add 202211 backport option
Add option in .github/pull_request_template.md

Add 202211 backport option for the PR review template 

---

.azure-pipelines/run-test-scheduler-template.yml
azure-pipelines.yml

Sync pipeline in 202211 branch with master. 
Sync pipeline in 202211 branch with master. 
1. Remove the timeout in each step of a job, and control the timout outside. 
2. Set all job mandatory.

[TestbedV2][202211]Sync pipeline in 202211 branch with master. 

---

azure-pipelines.yml

Recently, the job of t0-sonic runs stably in 202205 branch, so in this pr, I set it mandatory in azure pipeline.
Recently, the job of t0-sonic runs stably in 202205 branch, so in this pr, I set it mandatory in azure pipeline.
Modify the value of continueOnError in this job from `true` to `false`.

[TestbedV2][202205]Set all jobs mandatory in pipeline. 

---

platform/barefoot/bfn-platform.mk
platform/barefoot/bfn-sai.mk

Signed-off-by: Mykhailo Onipko <mykhailox.onipko@intel.com>
SONiC moved to SAI 1.11.0
Build package with SAI 1.11.0
Ran sanity for all included profiles

[BFN] Update BFN sdk to SAI 1.11.0

---

files/scripts/swss.sh

There's a slowdown in bootup related to the execution of a *show* command during startup of swss service. *show* is a pretty heavy command and takes long time to execute ~2 sec.
I replaced *show* with *sonic-db-cli* which takes a ms to run.
Boot the switch and verify swss is active.

[swss.sh] optimize macsec feature state query

---

Makefile.work
build_debian.sh
files/build_templates/sonic_debian_extension.j2
files/image_config/kubernetes/kubernetes_master_entrance.sh
rules/config
slave.mk

Auto cherry-pick PR from master branch failed, delete one extra line code to fix the conflict and raise this PR
**[original why]** Based on our new design about k8s feature, we need to build a sonic image for k8s master usage, the mainly work is to add k8s master related packages. And only when set INCLUDE_KUBERNETES_MASTER = y, it would take effect
Delete one extra line code to fix the conflict
**[original how]** 1. Install k8s master related packages; 2. Upgrade k8s version from 1.21.1 to 1.22.2
**[original how]** Need to set INCLUDE_KUBERNETES_MASTER = y to enable it

Add k8s master feature (#11637)

---

dockers/docker-dhcp-relay/cli/clear/plugins/clear_dhcp6relay_counter.py

Avoid traceback on sonic-clear command
```
sonic-clear dhcp6relay_counters 
File "/usr/local/bin/sonic-clear", line 8, in <module>
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File …
```

[202205][dhcp_relay]Fix the clear dhcp6relay_counters CLI 

---

device/celestica/x86_64-cel_seastone-r0/platform.json

dx010 platform json config is relative old, does not support capability enhancement config.
Update capability enhancement config for dx010 platform according to [Platform capability file enhancement](https://github.com/sonic-net/SONiC/blob/master/doc/platform_json_enhancement.md). 
pytest testbed.

Seastone add platform json capability enhancement config

---

platform/mellanox/mlnx-fw-upgrade.j2

Fixed CPLD upgrade script
Modified the skip check to be greater than or equal to compared to equal to previously
Upgrade image with changes

[201911][mellanox]Fix CPLD upgrade script

---

.github/CODEOWNERS

[github]: update codeowner from Azure teams to sonic-net teams

---

dockers/docker-platform-monitor/Dockerfile.j2

The performance of request is better than curl.
import request python library for Ragile platform.

Import requests libraries for Ragile platform

---

src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/flex_counter.json
src/sonic-yang-models/yang-models/sonic-flex_counter.yang

Fixes https://github.com/sonic-net/sonic-buildimage/issues/13457
Added Tunnel flex counter group
Added relevant container in sonic-flex_counter yang model
Added UT to verify

[yang] Added Tunnel flex counter group

---

files/scripts/swss.sh

**BACKPORT OF https://github.com/sonic-net/sonic-buildimage/pull/12946**
There's a slowdown in bootup related to the execution of a *show* command during startup of swss service. *show* is a pretty heavy command and takes long time to execute ~2 sec.
I replaced *show* with *sonic-db-cli* which takes a ms to run.
Boot the switch and verify swss is active.

[202211][swss.sh] optimize macsec feature state query (#12946)

---

platform/mellanox/docker-syncd-mlnx/ecmp_calculator/ecmp_calc.py

Add script usage and more information to script description being printed in help option.
Missing information in script description in help option.
Expand script description and add script usage.
Run the script with -h option.

[Mellanox] [ECMP calculator] Add script usage and more information to script description in help option

---

src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/acl.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json
src/sonic-yang-models/yang-templates/sonic-acl.yang.j2

Add new ACL key BTH_OPCODE and AETH_SYNDROME
Add new ACL key BTH_OPCODE and AETH_SYNDROME
1. manual test
2. unit test

[sonic-acl.yang] Add new ACL key BTH_OPCODE and AETH_SYNDROME

---

.github/workflows/automerge_scan.yml
.github/workflows/codeql-analysis.yml
.github/workflows/label.yml
.github/workflows/pr_cherrypick_poststep.yml
.github/workflows/semgrep.yml

1. github action will report error on forked repos. It is not by design.
2. keep 'Approved for xxx branch' label in auto cherry pick workflow.
1. Disable github action on folked repos.
2. Keep 'approved for xxx' label in auto cherry pick workflow.

[action] Update github actions on trigger and label.

---

src/dhcp6relay/src/relay.cpp

double commit https://github.com/sonic-net/sonic-dhcp-relay/pull/29 to 202111.
This commit fix DHCPv6 Advertise counter issue. 
Since PR test use sonic-mgmt master branch, without this fix, DHCPv6 related test case in 202111 PR test will not pass.

double commit sonic-dhcp-relay PR#29 into 202111

---

platform/components/docker-gbsyncd-credo.mk

Update credo sai package to the latest v0.8.2, which also has the fix for https://github.com/aristanetworks/sonic/issues/52.
Update credo sai url for v0.7.5
Basic traffic test on A7280

[gearbox] use credo sai v0.8.2

---

rules/config

Back port GNMI to 202211 branch
Update rules/config to enable host service
Run GNMI end2end test

Enable host service.

---

device/arista/x86_64-arista_7050cx3_32s/platform.json

Some tests under platform_tests/api were failing on the 7050CX3 due to outdated facts in platform.json
Updated platform.json facts with appropriate values
Run tests under platform_tests/api to verify no failures

Fix content of platform.json for DCS-7050CX3-32S

---

rules/config

Need to enable host service to suport GNMI native write
Update rules/config
Run GNMI end2end test

Enable host services

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/azure-pipelines-image-template.yml
.azure-pipelines/template-daemon.yml

Azure pipeline change.
Use common template to make it easy to change common steps.
Fix docker hang issue.

[ci] Fix docker hang issue and change template reference branch.

---

.azure-pipelines/azure-pipelines-build.yml
.azure-pipelines/azure-pipelines-image-template.yml
.azure-pipelines/template-daemon.yml

Cherry pick PR(#13894)
Azure pipeline change.
Use common template to make it easy to change common steps. Fix docker hang issue.

[ci] Fix docker hang issue and change template reference branch (#13894)

---

device/arista/x86_64-arista_7800r3a_36d2_lc/platform.json

Manual rebase of PR #13524 to 202211 branch.
See PR #13524

fix platform.json on Wolverine for thermal sensors

---

azure-pipelines.yml

Add checks for debug image in PR checks.

[ci] Build debug image in PR checks.

---

src/sonic-config-engine/setup.py

Fix CVE-2022-2309, upgrade lxml from 4.6.3 to 4.9.1

[202012][Security][CVE-2022-2309] Upgrade lxml from 4.6.3 to 4.9.1

---

.azure-pipelines/azure-pipelines-build.yml

remove duplicated code for docker hanging issue.
These codes are included in daemon step.
remove these codes.

[ci] Remove dulplicated code, which is to avoid docker hanging.

---

platform/components/docker-gbsyncd-credo.mk

Update credo sai package to the latest v0.9.0.
Update credo sai url for v0.9.0
Basic traffic test on A7280

[gearbox] use credo sai v0.9.0

---

azure-pipelines.yml

Enable to modify Min/Max workers by AZP library
Enable to modify Min/Max workers by AZP library

Enable to modify Min/Max workers by AZP library

---

.github/workflows/automerge_scan.yml

1. Semgrep check has some issues. Ignore it.
2. check automerge label.
3. Ignore Azure.sonic-buildimage sub test jobs. Only check final result.

[action] Update AutoMergeScan action to ignore Semgrep and rerun failed job.

---

dockers/docker-ptf/Dockerfile.j2
dockers/docker-ptf/no-check-valid-until

[Build] Fix the mirror gpg key expired issue
See vs build: https://dev.azure.com/mssonic/build/_build/results?buildId=231680&view=logs&j=cef3d8a9-152e-5193-620b-567dc18af272&t=cf595088-5c84-5cf1-9d7e-03331f31d795
Add the apt option not to check the valid until, the option is set to the SONiC docker base image, docker ptf missing the option.
```
Acquire::Check-Valid-Until "false";
```
The build of docker-ptf is succeeded after fixed.
```
2023-03-11T17:26:35.1801999Z [ building ] [ target/docker-ptf.gz ] 
2023-03-11T17:38:10.1608536Z [ finished ] [ target/docker-ptf.gz ] 
```

[Build] Fix the mirror gpg key expired issue

---

sonic-slave-bullseye/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2

cisco SDK dependencies needed
Add dependencies in sonic-slave docker files
build cisco sonic image

update sonic-slave docker files to include cisco sdk dependencies

---

dockers/docker-sonic-mgmt/Dockerfile.j2

TestbedV2 requires scandir python package
Install scandir packages

Add scandir into sonic-mgmt docker image

---

device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/SAI-M0-48x1G-4x10G.md5
device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/SAI-M0-48x1G-4x10G.xml

Test case "test_drop_ip_packet_with_wrong_0xffff_chksum" fails on Nokia-7215 platform
with error "E Failed: Dropped 0 packets in rx, not in expected range"
Update cnc-base counters to 4096 from 0 in the Marvell SAI Easy bringup XML files
Build new sonic armhf image with these updated XML files and re-run the test case.
The test case passes with new files.
Update cnc-base counters to 4096 from 0 in the Marvell SAI Easy bring up XML files

[Nokia-7215] Update Marvell EZB XML files

---

.gitmodules

create 202205 branch for sonic-dbsyncd submodule

[202205] create 202205 branch for sonic-dbsyncd submodule

---

files/build/versions/dockers/sonic-slave-bullseye/versions-py3
files/build/versions/dockers/sonic-slave-buster/versions-py2
files/build/versions/dockers/sonic-slave-buster/versions-py3
sonic-slave-bullseye/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2
sonic-slave-stretch/Dockerfile.j2

Fix some of vulnerability issue relative python packages #14269
Pillow: [CVE-2021-27921]
Wheel: [CVE-2022-40898]
lxml: [CVE-2022-2309]

[Security] Fix some of vulnerability issue relative python packages (#14269

---

dockers/docker-sonic-mgmt/Dockerfile.j2
dockers/docker-sonic-mgmt/start.sh

1. Add dockeragent necessary packages to sonic-mgmt-docker
2. Remove Python 201811 venv
3. Update some packages in order to meet internal security requirement
Update sonic-mgmt-docker file
sonic-mgmt-docker can run: bash, apt update, apt install and ping.
start.sh is under /azp with exec permission.
env-201811 venv is removed.
jinja2 is upgrade to 2.10.1

Add AZP agent necessary packages to sonic-mgmt-docker

---

files/build/versions/dockers/sonic-slave-bullseye/versions-py3
files/build/versions/dockers/sonic-slave-buster/versions-py2
files/build/versions/dockers/sonic-slave-buster/versions-py3
sonic-slave-bullseye/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2
sonic-slave-stretch/Dockerfile.j2

Fix some of vulnerability issue relative python packages #14269
Pillow: [CVE-2021-27921]
Wheel: [CVE-2022-40898]
lxml: [CVE-2022-2309]

[Security] Fix some of vulnerability issue relative python packages (#14269)

---

azure-pipelines.yml

Check syncd related target in PR checks to avoid build break.

[ci] Add syncd target in PR checks to avoid build break.

---

files/image_config/sudoers/sudoers

Improve sudo cat command for RO user.
RO user can use sudo command show none syslog files.
Improve sudo cat command for RO user.
Pass all UT.
Manually check fixed code work correctly.
Improve sudo cat command for RO user.

Improve sudo cat command for RO user.

---

.azure-pipelines/run-test-scheduler-template.yml

Refine testbedv2 template output

Refine testbedv2 template output

---

dockers/docker-sonic-mgmt/Dockerfile.j2

This is a cherrypick of https://github.com/sonic-net/sonic-buildimage/pull/14062 on 202012 branch

[202012] Add shellcheck and mock modules for running unit and linter test

---

platform/innovium/docker-syncd-invm/critical_processes
platform/innovium/docker-syncd-invm/ivm_start.sh
platform/innovium/docker-syncd-invm/start.sh

Signed-off-by: rck-innovium rck@innovium.com
Add platform files for critical processes and default qos config for Innovium platforms
Added default files for critical processes and qos config
Tested with autorestart/test_container_autorestart.py::test_containers_autorestart
```
PASSED autorestart/test_container_autorestart.py::test_containers_autorestart[sonic-xxx-dut-sonic-xxx-dut|syncd]
```
Add platform files for critical processes and default qos config for Innovium platforms

Add platform files for Innovium platform

---

.azure-pipelines/run-test-scheduler-template.yml

Refine testbedv2 template output

[202205]Refine testbedv2 template output

---

platform/checkout/cisco-8000.ini

Fix for link down issue seen with AOI 100G-PSM4 optics on 8102-64H-O [JIRA ID# MIGSMSFT-23]
update platform module to 0.2.7

[cisco-8000] update platform module to 0.2.7

---

platform/marvell-armhf/sai.mk

Fixed syncd syslog errors reported in issue https://github.com/sonic-net/SONiC/issues/1248
Fixes https://github.com/sonic-net/SONiC/issues/1248
Compile and load the SAI debian in SONiC 202205 image.
Verify PTF autorestart testcase passes.

[Marvell] Update armhf sai debian

---

.github/pull_request_template.md

Update pull request template for test evidence, and work item trackers

Update pull request template for test evidence, and work item trackers

---

files/build/versions/host-image/versions-py3
files/build_templates/sonic_debian_extension.j2

dbus-python-1.3.2 uses latest meson to build.
latest meson v1.1.0 has some issues.

Fix build issue in 202106 branch on dbus-python and meson.

---

build_debian.sh

Import defusedxml packet to fix semgrep error "using `defusedxml` instead of `xml`"
Add "pip3 install defusedxml" in build_debian.sh
NA

Import defusedxml packet

---

build_debian.sh

Reverts sonic-net/sonic-buildimage#14815

Revert "Import defusedxml packet"

---

src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/tests/yang_model_tests/tests/crm_dash.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/crm_dash.json
src/sonic-yang-models/yang-models/sonic-crm.yang
src/sonic-yang-models/yang-models/sonic-device_metadata.yang

Extend the CRM YANG model with DASH attributes.
Add new attributes to the existing CRM YANG model.
Implement tests for DASH CRM attributes.
Build sonic_yang_models packages. The tests will be run automatically.

[DASH][CRM] Extend the CRM YANG model with DASH attributes.

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Innovium platform has build issue.
Remove it from upgrate version pipeline.

[ci] Remove innovium in upgrate version pipeline.

---

slave.mk

To be able to cache, and then retrieve cached "copied" debs
Add missed caching and cache retrieval steps
Build with cache and then clean and rebuild again. The targets added to SONIC_COPY_DEBS should be taken from a cache.

[Cache] Enable missed cache for local debs

---

.azure-pipelines/azure-pipelines-build.yml

Support marvell/marvell-arm64 build
- Microsoft ADO **(number only)**: 19995559

[Ci] Support marvell/marvell-arm64 build

---

src/sonic-config-engine/minigraph.py

There are chassis-packet and Single asic platforms which support this 400G to 100G/40G speed change via config.
Enabling this feature for all platforms which can support this. Keeping it enabled for all does not affect the platforms
which do not support this feature yet.
Removed switch_type and role type check.
Loaded router with default 400G config. Loaded minigraph to convert 400G to 100G speed.

Enable 400G to 100G/40G speed change via minigraph for all platforms

---

azure-pipelines.yml

1. Remove 'kvmtest-t0' and 'kvmtest-t1-lag' test jobs since all the test jobs are required (continueOnError: false) already, and will only enable one of classical and testbedV2 tests, no need to do an unnecessary 'or' compute test job.
2. Change agent pool to reduce cost and avoid congestion
- Microsoft ADO **(number only)**: 21199881

[202205]Refine test job definition and assert logic

---

build_debian.sh

Fix #14974 
Refs: https://github.com/docker/docker-py/pull/3116

[Build] update python package docker in host image to 6.1.1

---

device/mellanox/x86_64-nvidia_sn5600-r0/ACS-SN5600/sai_5600.xml

Update the SN5600 sai file
Install image on SN5600 device

[Mellanox] Update SN5600 SAI XML file

---

build_debian.sh
files/build_templates/sonic_debian_extension.j2

[Build] Upgrade the python docker version to fix bgp not up issue
- Microsoft ADO **(number only)**: 22236397

[Build] Upgrade the python docker version

---

.github/workflows/automerge_scan.yml
.github/workflows/pr_cherrypick_prestep.yml

1. When auto cherry pick workflow create PR, fill the body field.
2. Rerun Azure.sonic-buildimage on failure perday.
- Microsoft ADO **(number only)**: 17979778

[action] Update github workflows about automerge_scan and pr_cherrypick_prestep.

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Provide a method to override build options in webUI.
We can stop python dependency upgrade version.
- Microsoft ADO **(number only)**:  22335854
Add a variable at the tail of make command.

Add OVERRIDE_BUILD_OPTIONS options in UpgrateVersion pipeline.

---

.azure-pipelines/vstest-exclude

Run kvmtest when update package versions to avoid test break.
- Microsoft ADO **(number only)**: 22335854

[ci] Run kvmtest when update package versions to avoid test break.

---

.azure-pipelines/azure-pipelines-build.yml

Fix pipeline issue which breaks 202205 official build.
- Microsoft ADO **(number only)**: 23115245
qemuOrCrossBuild was not cherry picked into 202205 branch.
Remove this feature.

[ci] Fix pipeline error caused by qemuOrCrossBuild missing.

---

azure-pipelines.yml

1. Remove 'kvmtest-t0' and 'kvmtest-t1-lag' test jobs since all the test jobs are required (continueOnError: false) already, and will only enable one of classical and testbedV2 tests, no need to do an unnecessary 'or' compute test job.
2. Change agent pool to reduce cost and avoid congestion
- Microsoft ADO **(number only)**: 21200215

[202211]Refine test job definition and assert logic

---

.azure-pipelines/run-test-scheduler-template.yml

Refine testbedv2 template output

[202012]Refine testbedv2 template output

---

device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D44C10/port_config.ini
device/mellanox/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D44C10/sai_2700_44x50g_10x100g.xml
device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-A96C8V8/sai_4700_8x200g_8x100g_96x25g.xml
device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V48C32/port_config.ini
device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-V48C32/sai_4700_32x100g_48x200g.xml
platform/mellanox/docker-syncd-mlnx/platform_syncd_dump.sh
platform/mellanox/integration-scripts.mk
platform/mellanox/integration-scripts/helper.py
platform/mellanox/integration-scripts/hwmgmt_kernel_patches.py
platform/mellanox/integration-scripts/tests/test_filehandler.py
platform/mellanox/integration-scripts/tests/test_hwmgmtaction.py

Added NVIDIA copyright to missing files under platform/mellanox & device/mellanox

[Mellanox] Add Copyright Headers for missing files

---

azure-pipelines.yml

[CI/CD, 202211] Migrate to SONiC Elastictest

---

azure-pipelines.yml

[CI/CD, 202205] Migrate to SONiC Elastictest

---

azure-pipelines.yml

[CI/CD, 202012] Migrate to SONiC Elastictest 

---

azure-pipelines.yml

[CI/CD] Migrate to SONiC Elastictest

---

.azure-pipelines/run-test-scheduler-template.yml
azure-pipelines.yml

[CI/CD] Refine pr test definition, remove old test jobs and testbedv2 flags

---

.azure-pipelines/run-test-scheduler-template.yml
azure-pipelines.yml

[CI/CD, 202012] Refine pr test definition, remove old test jobs and testbedv2 flags

---

.azure-pipelines/run-test-scheduler-template.yml
azure-pipelines.yml

[CI/CD, 202205] Refine pr test definition, remove old test jobs and testbedv2 flags

---

.azure-pipelines/run-test-scheduler-template.yml
azure-pipelines.yml

[CI/CD, 202211] Refine pr test definition, remove old test jobs and testbedv2 flags

---

build_image.sh
files/Aboot/boot0.j2
files/initramfs-tools/modules
files/initramfs-tools/union-mount.j2

Cherry pick of https://github.com/sonic-net/sonic-buildimage/pull/15046
Will complete description once testing is complete.
MS ADO: 21450507

[202205] Implement zram compression for docker in RAM

---

files/build_templates/per_namespace/bgp.service.j2

Cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/11827
This is to fix issue: [201811->202012] During warm recovery, TOR did not announce Loopback, VLAN route after upgrade
Suspected cause: 202012 does not have system dependency for bgp service to start after interfaces-config.service.
This opens a window for race condition: bgp service completing before interfaces are initialized.
BGP will miss announcing some routes if the interfaces are not ready.
- Microsoft ADO **(number only)**: 24163872
Added a systemctl dependency for bgp service to start after interfaces-config.service has finished.

Start BGP after interfaces-config.service

---

azure-pipelines.yml

Add marvell-arm64 platform build in PR checks to avoid build break.
- Microsoft ADO **(number only)**:  17257160

[ci] Add marvell-arm64 build in PR checks.

---

.azure-pipelines/azure-pipelines-image-template.yml

Set build options in pipeline UI.
Support setting reproducible build options to py2,py3 in release branch and none in master branch.
- Microsoft ADO **(number only)**: 22335854

[ci] Add OVERRIDE_BUILD_OPTIONS in image build template. (#15309)

---

files/build_templates/per_namespace/bgp.service.j2

Cherrypick https://github.com/sonic-net/sonic-buildimage/pull/12381 into 202012
Reverts https://github.com/sonic-net/sonic-buildimage/pull/15312
- Microsoft ADO **(number only)**: 24163872

[202012][BGP] starting BGP service after swss

---

src/sonic-config-engine/tests/test_cfggen.py

Revert the yang validation check accidently removed by https://github.com/sonic-net/sonic-buildimage/pull/13409

Add check for yang validation

---

.github/pull_request_template.md

To include 202305 in the PR template. 
- Microsoft ADO **(21450860)**:
Change the temlate.
pass PR test.

To change the PR template to have 202305

---

src/sonic-frr/patch/0027-bgpd-Ensure-FRR-has-enough-data-to-read-in-peek_for_as4_capability-and-bgp_open_option_parse.patch
src/sonic-frr/patch/0028-bgpd-Ensure-that-bgp-open-message-stream-has-enough-data-to-read.patch
src/sonic-frr/patch/series

Back-porting #15263 (master PRs have merge conflict)
Add patches from PRs
https://github.com/FRRouting/frr/pull/12043
https://github.com/FRRouting/frr/pull/12247
To fix CVEs https://github.com/advisories/GHSA-x7mf-v6gh-vm4g https://github.com/advisories/GHSA-9rqq-99cf-35g5 https://github.com/advisories/GHSA-j7hm-p94x-q9pw
- Microsoft ADO **(number only)**: 23268946
Added patches from the FRR fix PRs

[202205][FRR][CVE] Add FRR patches to fix CVEs: CVE-2022-43681 CVE-2022-40318, CVE-2022-40302  (#15263)

---

device/nokia/armhf-nokia_ixs7215_52x-r0/platform.json
platform/marvell-armhf/sonic-platform-nokia/7215/sonic_platform/sfp.py

Add support for SFP refactor on Nokia-7215 Marvell armhf platform.
Platform: armhf-nokia_ixs7215_52x-r0
HwSKU: Nokia-7215
ASIC: marvell
Port Config: 48x1G + 4x10G (SFP+)
Modify sfp.py to support SFP refactor optoe driver and platform.json to facilitate proper OC test completion.
Build armhf target for Nokia-7215 and verify proper Xcvrd and SFP refactor operation.
[armhf][Nokia-7215]Add SFP refactor support for Nokia-7215 platform

[armhf][Nokia-7215]Add SFP refactor support for Nokia-7215 platform

---

README.md

Add the release 202211/202305 in the README.md
- Microsoft ADO **(number only)**: 24357944

Add the release 202211/202305 in the README.md

---

azure-pipelines.yml

[Ci] Support to build sonic-swss-common for test
- Microsoft ADO **(number only)**: 24341479

[Ci] Support to build sonic-swss-common for test

---

.azure-pipelines/run-test-scheduler-template.yml

Refine PR test template format.
- Microsoft ADO **(number only)**:24382762
Refine PR test template format.
PR test executed normally.

Refine PR test template format

---

src/sonic-host-services/scripts/caclmgrd
src/sonic-host-services/tests/caclmgrd/cacl_external_client_acl_test.py
src/sonic-host-services/tests/caclmgrd/caclmgrd_scale_test.py
src/sonic-host-services/tests/caclmgrd/test_scale_vectors.py
src/sonic-host-services/tests/common/mock_configdb.py

Cherry pick https://github.com/sonic-net/sonic-host-services/pull/62 to 202205.
Fix the issue https://github.com/sonic-net/sonic-buildimage/issues/10883.
- Microsoft ADO **(number only)**: 17795594

[202205]Fix caclmgrd crash issue when applying scale cacl rules

---

.azure-pipelines/run-test-scheduler-template.yml
azure-pipelines.yml

Refine PR test template.
- Microsoft ADO **(number only)**:24382762
Refine PR test template.
PR test executed normally.

Refine PR test template

---

dockers/docker-ptf-sai/Dockerfile.j2

It is to fix the docker-ptf-sai build failure.
https://dev.azure.com/mssonic/build/_build/results?buildId=311315&view=logs&j=cef3d8a9-152e-5193-620b-567dc18af272&t=cf595088-5c84-5cf1-9d7e-03331f31d795
```
2023-07-09T13:53:19.9025355Z [91mTraceback (most recent call last):
2023-07-09T13:53:19.9025715Z   File "/root/ptf/.eggs/setuptools_scm-7.1.0-py3.7.egg/setuptools_scm/_entrypoints.py", line 74, in <module>
2023-07-09T13:53:19.9025933Z     from importlib.metadata import entry_points  # type: ignore
2023-07-09T13:53:19.9026167Z ModuleNotFoundError: No module named 'importlib.metadata'
```
- Microsoft ADO **(number only)**: 24513583

[Build] Fix the python module importlib.metadata not found issue

---

src/sonic-frr/patch/0010-bgpd-change-log-level-of-graceful-restart-events-to-info.patch
src/sonic-frr/patch/series

cherry pick, #15535
Graceful restart is a key event for bgpd, related log print is debug level. To change it to info level to get more visibilities when this kind of event is triggered.
- Microsoft ADO **(13875291)**:
To create patch file to change from debug level to info level. 
To run PR test and capture the print.

[sonic-frr] enable info log for graceful restart events

---

.gitmodules
platform/mellanox/.gitignore
platform/mellanox/mlnx-sai.mk
platform/mellanox/mlnx-sai/.gitignore
platform/mellanox/mlnx-sai/Makefile
platform/mellanox/mlnx-sai/SAI-Implementation/.gitignore

To optimize Mellanox platform SAI build
SAI debs are now downloaded as Spectrum-SDK-Drivers-SONiC-Bins release.
Configure/build for Mellanox platform, check the image and ensure that correct SAI debs are included.

[Mellanox] Update SAI build procedure

---

src/sonic-frr/patch/0029-bgpd-Change-log-level-for-graceful-restart-events.patch
src/sonic-frr/patch/series

cherry pick, https://github.com/sonic-net/sonic-buildimage/pull/15535
Graceful restart is a key event for bgpd, related log print is debug level. To change it to info level to get more visibilities when this kind of event is triggered.
- Microsoft ADO **(13875291)**:
To create patch file to change from debug level to info level.
To run PR test and capture the print.

[sonic-frr] enable info log for graceful restart events - cherry-pick to 202205

---

.gitmodules
platform/mellanox/.gitignore
platform/mellanox/mlnx-sai.mk
platform/mellanox/mlnx-sai/.gitignore
platform/mellanox/mlnx-sai/Makefile
platform/mellanox/mlnx-sai/SAI-Implementation/.gitignore

Backport https://github.com/sonic-net/sonic-buildimage/pull/15728
To optimize Mellanox platform SAI build
SAI debs are now downloaded as Spectrum-SDK-Drivers-SONiC-Bins release.
Configure/build for Mellanox platform, check the image and ensure that correct SAI debs are included.

[202211] [Mellanox] Update SAI build procedure (#15728)

---

azure-pipelines.yml

Use remote PR test template from sonic-mgmt master to run PR test.
Signed-off-by: Chun'ang Li [chunangli@microsoft.com](mailto:chunangli@microsoft.com)
- Microsoft ADO **(24658850)**:
Modify PR test azure pipeline yml file.
PR test executing normally.

[CI/CD] Use remote PR test template from sonic-mgmt master to run PR test

---

platform/mellanox/mft.mk

Update Mellanox MFT tool to version 4.25.0-62
Update the MFT tool make file
Run full sonic-mgmt regression.

[Mellanox] Update MFT tool to version 4.25.0-62

---

device/dell/x86_64-dell_s6100_c2538-r0/platform.json
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/component.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/fan_drawer.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/module.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/watchdog.py

ADO: 24709703
sonic-mgmt platform testcases failed.
Implement platform API 2.0.
Run sonic-mgmt tests.

[202012]Dell s6100 Fix sonic-mgmt platform test failures

---

device/dell/x86_64-dell_s6100_c2538-r0/platform.json

Dell S6100 Platform components needs to be updated.
Modified platform.json to fix the issue.
Run sonic-mgmt component test and check whether it passes.

Dell S6100 Platform fix

---

device/dell/x86_64-dellemc_s5248f_c3538-r0/system_health_monitoring_config.json
device/dell/x86_64-dellemc_s5296f_c3538-r0/system_health_monitoring_config.json
device/dell/x86_64-dellemc_z9264f_c3538-r0/system_health_monitoring_config.json
platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/chassis.py
platform/broadcom/sonic-platform-modules-dell/s5248f/sonic_platform/psu.py
platform/broadcom/sonic-platform-modules-dell/s5296f/sonic_platform/chassis.py

System health config is missing in few Dell platforms.
Added system health monitoring config and its related API's
show system-health summary/detail commands.
UT:
[S5248F_UT.txt](https://github.com/sonic-net/sonic-buildimage/files/12001180/S5248F_UT.txt)

DellEMC: System health config changes

---

dockers/docker-fpm-frr/frr/bgpd/templates/sentinels/policies.conf.j2
src/sonic-bgpcfgd/tests/data/sentinels/policies.conf/result_all.conf

Add no-export to bgp sentinel community-list. So that bgp updates from bgp sentinel service must match sentinel community and no-export, otherwise, the bgp update will be dropped.
- Microsoft ADO **(24946274)**:
Add no-export to bgp sentinel community-list.
Run UT, case would pass. Build the image and start the device. Add bgp sentinel and check that no-export community exist in bgp sentinel community list.

Add no-export to sentinel community-list

---

.azure-pipelines/dpkg-cache-cleanup.yml

Clean old cached file in nfs disk for armhf/arm64
- Microsoft ADO **(number only)**:  24930879

[ci] Add job to cleanup nfs in armhf and arm64 agents.

---

platform/mellanox/mft.mk

Backport (#16149)
Update Mellanox MFT tool to version 4.25.0-62
Update the MFT tool make file
Run full sonic-mgmt regression.

[202211][Mellanox] Update MFT to newer version 4.25.0-62 (#16149)

---

device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/jr2cp-nokia-18x400g-config.bcm
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/jr2cp-nokia-18x400g-config.bcm
src/sonic-device-data/tests/permitted_list

Update CPU transmitted packets to queue 7 for chassis

---

src/system-health/tests/test_system_health.py

Include valid input check for system status in test
Fix for issue#14871
Include valid input check for system status in test
As said in PR, break the publish_system_status function code and build system-health package.
UT:
tests/test_system_health.py:741: in <module>
???
/usr/local/lib/python3.9/dist-packages/mock/mock.py:1423: in patched
return func(*newargs, **newkeywargs)
tests/test_system_health.py:738: in test_publish_system_status
assert call_args in expected_calls
E   AssertionError: assert call('FAIL') in [(('UP',), {}), (('DOWN',), {})]
ERROR tests/test_system_health.py - AssertionError: assert call('FAIL') in [(('UP',), {}), (('DOWN',), {})]

Fix test_system_health.py script related to system-ready's publish_system_status function

---

rules/config

To fix https://github.com/sonic-net/sonic-buildimage/issues/16015
P4RT is causing instability in build due to regular failures. Disabling P4RT by default
Modified rules/config
Building sonic.

[P4RT]Disabling p4rt by default to overcome build issues

---

dockers/docker-sonic-mgmt/Dockerfile.j2

This change is to help us running SSH config generation for our testbed in mgmt container.
Original PR in sonic-mgmt repo can be found here: https://github.com/sonic-net/sonic-mgmt/pull/9773.
- Microsoft ADO **(number only)**: 25007799
Updating sonic-mgmt docker file to add sshconf 0.2.5 into pip install under venv.
Adding sshconf 0.2.5 into sonic-mgmt container.

Adding sshconf 0.2.5 into sonic-mgmt container.

---

platform/centec-arm64/sai.mk
platform/centec/sai.mk

Change makefile to reference to new SAI debian package of v1.12.0-1
Modify sai.mk of arm64 and x86 platform for Centec

update sonic centec-sai reference to v1.12.0-1

---

build_image.sh

To remove compression of the generated raw image during build.
[Port from 201811 PR #15154]
Removed usage of compression tool on the generated raw image.
Initiate build for 'target/sonic-broadcom.raw' and verify that the size of the raw image generated is same as `RAW_IMAGE_DISK_SIZE`.
[build] Remove compression of raw image

[build] Remove compression of raw image

---

rules/docker-telemetry.mk

[telemetry] limit privileged flag for telemetry container

---

dockers/docker-sonic-mgmt/Dockerfile.j2

…rpreter in sonic-mgmt-docker (#15836)"
This reverts commit 51fb6d7d9f0fcee70fa1125437f9bca352472973.

Revert "Upgrade Ansible to 6.7.0 and make Python3 as default"

---

files/build/versions/dockers/docker-ptf/versions-py2

PTF container needs to use new grpcio package.
Update versions-py2
Check pipeline artifact

Fix grpc package for ptf container

---

files/image_config/rsyslog/rsyslog-config.sh
files/image_config/rsyslog/rsyslog.conf.j2
src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/syslog.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/syslog.json
src/sonic-yang-models/yang-models/sonic-syslog.yang

Reverts sonic-net/sonic-buildimage#16179

Revert "revert [syslog] Add remote syslog configuration (cherry-pick to 20230…"

---

README.md

[doc] add pipeline link into README

---

platform/checkout/cisco-8000.ini

Align the ref pointer to latest code drop on 202205

---

azure-pipelines.yml

vstest needs to compile swss-common locally, and the above two packages will soon be required.
- Microsoft ADO **(number only)**: 25027489

Install swig and nlohmann-json3-dev for vstest

---

platform/pddf/README.md

Fix a typo, and some whitespace issues.

Improve `platform/pddf/readme.md`

---

dockers/docker-sonic-mgmt/Dockerfile.j2
src/protobuf/Makefile

Polish protobuf build script
- Microsoft ADO **(number only)**: 17417902
1. Use dget to download the protobuf source code
2. Add official link in sonic-mgmt Dockerfile for protobuf
Check Azp

[protobuf]: Polish protobuf build script

---

device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/sai.profile

**CHERRY-PICK:** https://github.com/sonic-net/sonic-buildimage/pull/7708
* To create SDK dump on Mellanox devices when SDK event has occurred
* N/A
* Set the SKUs keys needed to initialize the feature in SAI
* N/A
* N/A
```
'//||\\`
''``
```

[202205][Mellanox] Update SKUs to enable SDK dumps

---

platform/barefoot/sonic-platform-modules-bfn-montara/sonic_platform/psu.py

SONiC CLI command was broken.
```
admin@sonic:~$ show  platform psustatus 
PSU    Model                        Serial    HW Rev  Voltage (V)    Current (A)      Power (W)  Status    LED
-----  ---------------  ------------------  --------  -------------  -------------  -----------  --------  -----
PSU 1  PFE600-12-054NA  420000956420600006       206  N/A            N/A                  82.00  OK        green
PSU 2  PFE600-12-054NA  420000956420600248       206  N/A            N/A                  60.00  NOT OK    green
```
Fix Python string formating.
Run `show  platform psustatus`
Signed-off-by: Petro Bratash [petrox.bratash@plvision.eu](mailto:petrox.bratash@plvision.eu)

[BFN] Fix 'show platform psustatus' command

---

platform/broadcom/sonic-platform-modules-dell/debian/rules

To include files in path `platform/broadcom/sonic-platform-modules-dell/s6100/bin` during build in Dell S6100 platform deb package.
During Dell S6100 platform deb package build, copy the files to the install location.
1. Copy the required files to `platform/broadcom/sonic-platform-modules-dell/s6100/bin`.
2. Build the SONiC image and install in a Dell S6100 device.
3. The files will be available in `/usr/share/sonic/device/x86_64-dell_s6100_c2538-r0/bin/`.
Logs: [build_logs.txt](https://github.com/sonic-net/sonic-buildimage/files/12617618/build_logs.txt)
[Dell] S6100 - Copy files in platform build path to platform deb package

[Dell] S6100 - Copy files in platform build path to platform deb package

---

src/sonic-eventd/Makefile

The Makefile for `src/sonic-eventd` had no clean target, which means build artifacts may incorrectly get reused across builds, when they need to get rebuilt for whatever reason (build environment changed, libraries changed, etc.).
- Microsoft ADO **(number only)**: 25135443
Add a proper clean target to `src/sonic-eventd/Makefile`.

Add a clean target to sonic-eventd to make sure artifacts get cleaned up

---

src/sonic-yang-models/yang-models/sonic-neigh.yang

vlan import for yang currently doesn't work, so was removed from the original PR: https://github.com/sonic-net/sonic-buildimage/pull/14521
Adds comments to remember to add later

Adding comments for vlan import

---

.azure-pipelines/docker-sonic-slave-template.yml

- Microsoft ADO **(number only)**: 24248940

Allow builds for bookworm in the docker slave template file

---

.azure-pipelines/docker-sonic-slave.yml

- Microsoft ADO **(number only)**: 24248940

Fix slave container builds for bookworm from AzP

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Change the package upgrade PR title
- Microsoft ADO **(number only)**: 25253323

[Ci] Change the package upgrade PR title

---

device/mellanox/x86_64-mlnx_msn2700-r0/default_sku

* Set default SKU for `SN2700`: `Mellanox-SN2700` -> `ACS-MSN2700`
* N/A
* Updated vendor config files
* N/A
* N/A
```
'//||\\`
''``
```

[mellanox]: Update default SKU for SN2700

---

platform/checkout/cisco-8000.ini

Fixes for 
MIGSMSFT-333 / SR 696141124 - Fix OREDERED ECMP NHG drop when route is added before members are added
MIGSMSFT-333 / SR 696141124 – Fix port handling of empty ecmp group to drop packets
update to 202205.2.2.13 release

Update cisco-8000.ini to 202205.2.2.13 release

---

platform/components/docker-gbsyncd-credo.mk

Update credo sai package to the latest v0.9.3, which fixes the issue https://github.com/aristanetworks/sonic/issues/92.
- Microsoft ADO **25437323**
Update credo sai url for v0.9.3
Basic traffic test on A7280

[gearbox] use credo sai v0.9.3  

---

azure-pipelines.yml

Enable an Azp job for checking DPU scenario.
Add a new job for DPU in azure-pipeline.yml
Check Azp status

[azp]: Add dpu topo

---

src/sonic-eventd/rsyslog_plugin/rsyslog_plugin.cpp
src/sonic-eventd/rsyslog_plugin/syslog_parser.h
src/sonic-eventd/rsyslog_plugin_tests/rsyslog_plugin_ut.cpp
src/sonic-eventd/tools/events_tool.cpp

This header file comes from an external package, and a very old version of the header file has been checked into swss-common. This will cause problems for the upcoming Bookworm upgrade.
- Microsoft ADO **(number only)**: 25411155
Change references to the header file to use the Debian package nlohmann-json-dev, instead of from swss-common.
Verified that eventd was running

sonic-eventd: Use json.hpp from nlohmann-json3-dev instead of swss-common

---

dockers/docker-sonic-mgmt/0001-Fix-getattr-AttributeError-in-multi-thread-scenario.patch
dockers/docker-sonic-mgmt/Dockerfile.j2

This PR is part of sonic-mgmt-docker Python3 migration project.
- Microsoft ADO **(number only)**: 24397943
Upgrade Ansible to 6.7.0
Make Python3 as the default interpreter. python is a soft link to python3. If you want to use python2, use the command python2 explicitly.
Upgrade some pip packages to higher version in order to meet security requirement.
Build a private sonic-mgmt-docker successfully.
Verify python is python3.
Verify python2 is working with 202012 and 202205 branch.
Verify python3 is working with master branch.
Verify with github PR test.

Upgrade Ansible to 6.7.0 and make Python3 as the default interpreter in sonic-mgmt-docker

---

platform/checkout/cisco-8000.ini

Drop for 8111-32EH-O:
* Fix for clear_trap_configuration errors
* Fix OREDERED ECMP NHG drop when route is added before members are added
* Fix port handling of empty ecmp group to drop packets
* Fix for link_notification_handle error
* Auto FPD upgrade support
update platform to 202305.1.0.1

Update cisco-8000.ini to 202305.1.0.1

---

device/mellanox/x86_64-mlnx_msn2700a1-r0/platform.json
device/mellanox/x86_64-mlnx_msn2700a1-r0/platform_components.json

New introduced MSN2700 platform has a different platform name compared to the old one, it should be "MSN2700-A1".
Update the name to the new one in platform.json and platform_components.json.
run platform-related sonic-mgmt test cases on the new platform.

[Mellanox] Update new MSN2700 platform name in platform.json and platform_components.json

---

.azure-pipelines/docker-sonic-mgmt-py3-only.yml

- Microsoft ADO **(number only)**: 25858445
sonic-mgmt-docker with both Python2 and Python3 tag is latest
sonic-mgmt-docker with Python3 only tag is py3only

Rename docker-sonic-mgmt Python3-only version tag name to py3only

---

dockers/docker-platform-monitor/Dockerfile.j2
files/build/versions/dockers/docker-platform-monitor/versions-py3

[pmon] update gRPC version to 1.57.0 (#16257)

---

files/build/versions/dockers/docker-syncd-centec/versions-deb-bullseye-arm64
platform/centec-arm64/sonic-platform-modules-e530/debian/rules
platform/centec-arm64/sonic-platform-modules-e530/pca954x/ctc-i2c-mux-pca954x.c
platform/centec-arm64/tsingma-bsp/src/rtc-sd2405/rtc-sd2405.c
platform/centec/centec-dal/dal_kernel.c
platform/centec/sonic-platform-modules-e582/48x2q4z/modules/Makefile
platform/centec/sonic-platform-modules-e582/debian/rules
platform/centec/sonic-platform-modules-e582/pca954x/ctc-i2c-mux-pca954x.c
platform/centec/sonic-platform-modules-v682/48x8c/modules/rtc-sd2405.c
platform/centec/sonic-platform-modules-v682/48y8c/modules/rtc-sd2405.c
platform/centec/sonic-platform-modules-v682/debian/rules

Resolve the compilation error of the centec platform.
Modified platform driver to comply with bookworm kernel. 
Modified python build commands for building whl packages.
Verify whether all the platform bookworm debs are built. 
make target/debs/bookworm/platform-modules-v682-48y8c-d_1.0_amd64.deb 
Load the platform debian into the device and install it in bookworm image. 
Verify the platform related CLI and the functionality.

[Bookworm] Upgrade centec platforms to Bookworm

---

platform/checkout/cisco-8000.ini

FCS/CRC Errors will only be reported as RX_ERR.
Fix to avoid the mac port related errors.
Fix for sharedResSize testcase failure in QoS-SAI
Fix the issue related to voltage in 'show platform psustatus'.
Support WRED drop for lossy queues.
Fixed an issue where lossy traffic was getting dropped.
Enhancement of SAI logging for errors and interrupts
Update Cisco platform to 202305.1.0.3

Update cisco-8000.ini to 202305.1.0.3

---

device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
src/sonic-device-data/tests/permitted_list

This is a 202305 cast of this PR https://github.com/sonic-net/sonic-buildimage/pull/17206

[202305] Disable SA_EQUALS_DA trap on DNX LC SKUs

---

.azure-pipelines/azure-pipelines-build-ubuntu-2004.yml

GTest and boost libraries are needed by building the test of dash-api
```
g++ -std=c++14 \
-D PROTO_PATH=\"proto\" \
-I build -I misc \
misc/tests/utils_unittest.cpp misc/tests/main.cpp \
-Lbuild -ldashapi -lprotobuf -lgtest -lpthread -lboost_system -lboost_filesystem \
-o misc/tests/test
LD_LIBRARY_PATH=build misc/tests/test
misc/tests/utils_unittest.cpp:9:10: fatal error: boost/filesystem.hpp: No such file or directory
9 | #include <boost/filesystem.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:52: test] Error 1
make[1]: Leaving directory '/home/vsts/work/1/s/src/sonic-dash-api'
```
Add these dependencies on the ubuntu20.04 pipelines
Manually check in the local environment

[Azp]: Add dash-api dependencies on building Azp ubuntu20.04

---

files/scripts/gbsyncd.sh

Fix https://github.com/sonic-net/sonic-buildimage/issues/16608 on branch **202311**. Need to gracefully shutdown syncd/gbsyncd individually.
- Microsoft ADO : **26151608**
Manually cherry-pick  https://github.com/sonic-net/sonic-buildimage/pull/16812 and https://github.com/sonic-net/sonic-buildimage/pull/17486

[202311][gbsyncd] Graceful shutdown of syncd process in container gbsyncd

---

.gitmodules

Lock down submodule branches to 202311 branch.
This PR test.

[202311] lock down submodule branches

---

src/sonic-yang-models/yang-models/sonic-passwh.yang

Enhance the feature to support disabling password hardening as Linux support.
-1: expiration will never occur
0: expiration will expired immediately
Opened bug:
https://github.com/sonic-net/sonic-buildimage/issues/17427
Added the -1 value to be supported in hostcfgd and this value will propagate to the relevant Linux files
Pls see the details in the bug description that link attached above

password-hardening: Add support to disable expiration date

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Updating snappi and all relevant snappi modules to exact stable versions since group updates do not translate to the version required for stable test runs, hence versions were made more explicit.
- Microsoft ADO **(number only)**: 26316099
Change dockerfile version for snappi
These exact versions run locally on sonic mgmt docker

[Snappi] Update snappi package on sonic-mgmt docker

---

files/build_templates/per_namespace/swss.service.j2
files/build_templates/per_namespace/syncd.service.j2

This improvement does not bring any warm-reboot degradation, since the database availability (tcp/ip access over the loopback interface) was fixed by these PRs:
* https://github.com/sonic-net/sonic-buildimage/pull/15080
* https://github.com/sonic-net/sonic-buildimage/pull/16490
* Removed dependency on `interfaces-config.service` to speed up the boot, because `interfaces-config.service` takes a lot of time on init
* N/A
* Changed service files for `swss`/`syncd`
* Boot and check `swss`/`syncd` start time comparing to `interfaces-config`
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/17739
* N/A
* N/A
```
//// / // …
```

[202305][swss/syncd]: Remove dependency on interfaces-config.service

---

dockers/docker-dhcp-server/cli-plugin-tests/test_config_dhcp_server.py
dockers/docker-dhcp-server/cli/config/plugins/dhcp_server.py

Add config dhcp_server update.
Need config dhcp_server update
Add function to config tool plugin
Run unittest and manually run on latest master image.
Latest public image
Add config dhcp_server update

[dhcp_server] add config dhcp_server update

---

files/scripts/arp_update

It's possible for the ping6 command to hang indefinitely, which blocks the arp_update script from running.
- Microsoft ADO **26386208**:
Timeout the ping6 command to ensure that it never blocks arp_update from running

[arp_update]: Add timeout to ping6 command

---

src/sonic-host-services-data/debian/sonic-host-services-data.sonic-hostservice.service

When we disable telemetry.service, sonic-hostservice will not start. And root cause is sonic-hostservice is only wanted by telemetry.service.
Add dependency for gnmi.service.
Disable telemetry.service and build new image, and then check sonic-hostservice with new image.

Fix host service for 202305 branch

---

src/sonic-bgpcfgd/staticroutebfd/vars.py
src/sonic-bgpcfgd/tests/test_static_rt_bfd.py

double commit PR-16450 because of cherry pick conflict for [PR#202305](https://github.com/sonic-net/sonic-buildimage/pull/16450)

[staticroutebfd]double commit PR-16450, change bfd to singlehop

---

files/build_templates/per_namespace/swss.service.j2
files/build_templates/per_namespace/syncd.service.j2

This improvement does not bring any warm-reboot degradation, since the database availability (tcp/ip access over the loopback interface) was fixed by these PRs:
* https://github.com/sonic-net/sonic-buildimage/pull/15080
* https://github.com/sonic-net/sonic-buildimage/pull/16490
* Removed dependency on `interfaces-config.service` to speed up the boot, because `interfaces-config.service` takes a lot of time on init
* N/A
* Changed service files for `swss`/`syncd`
* Boot and check `swss`/`syncd` start time comparing to `interfaces-config`
* N/A
* N/A
```
'//||\\`
''`` …
```

[swss/syncd]: Remove dependency on interfaces-config.service

---

azure-pipelines.yml

Use 202311 as the test branch
Use 202311 as the test branch
PR test will verify it

[202311, PR test] Use 202311 as the test branch

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Fix reproducible build Upgrade version pipeline.
1. Remove barefoot build. Because it failed on sai package.
2. add marvell-arm64/pensando build.
- Microsoft ADO **(number only)**:  26515265

[ci] Update reproducible build pipeline, disable barefoot build.

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Remove barefoot platform in pinning version pipeline.
- Microsoft ADO **(number only)**:  26515265

[ci] Remove barefoot build in Pinning Version pipeline.

---

files/scripts/service_mgmt.sh

Unnecessary for logs to be written out to /tmp/${SERVICE}-debug.log as they are already being written to syslog. Therefore, removing writing to a new log in concern for memory space and not being able to startup some services in RO state.
- Microsoft ADO **(number only)**:26458976
Remove DEBUGLOG definition and line that echo's message to mentioned log file.
Manually verified, /tmp/${SERVICE}-debug.log files do not exist and log for service starting still appears in syslog

Remove echo log to /tmp/{$SERVICE}-debug.log in service_mgmt.sh

---

dockers/docker-fpm-frr/TS
dockers/docker-fpm-frr/TSA
dockers/docker-fpm-frr/TSB
dockers/docker-fpm-frr/frr/bgpd/templates/internal/policies.conf.j2
dockers/docker-fpm-frr/frr/bgpd/templates/voq_chassis/policies.conf.j2
dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.isolate.conf.j2
dockers/docker-fpm-frr/frr/bgpd/tsa/bgpd.tsa.unisolate.conf.j2
src/sonic-bgpcfgd/bgpcfgd/managers_device_global.py
src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chassis_packet_isolate.conf
src/sonic-bgpcfgd/tests/data/internal/peer-group.conf/result_chassis_packet_unisolate.conf
src/sonic-bgpcfgd/tests/data/internal/policies.conf/result_chasiss_packet.conf
src/sonic-bgpcfgd/tests/data/voq_chassis/policies.conf/result_base.conf
src/sonic-bgpcfgd/tests/test_device_global.py

Cherry-pick of PR: https://github.com/sonic-net/sonic-buildimage/pull/16732

[chassis] [202305] Added support of isolating given LC in Chassis with TSA mode

---

platform/mellanox/fw.mk

Update NVIDIA SIMX Version to 23.10-1123
Changed fw.mk file

[NVIDIA] Update SIMX version to 23.10-1123

---

.azure-pipelines/azure-pipelines-build-ubuntu-2004.yml

1. The ubuntu 2004 is needed by 202311
2. Because the artifacts of ubuntu2004 are used by other repos, a daily building is needed without an updating of this repo for a long time.
Add a daily building schedule and enable in the every branch
Check Azp

[Azp]: Enable daily building for ubuntu20.04 to every branch

---

src/sonic-bgpcfgd/staticroutebfd/main.py
src/sonic-bgpcfgd/tests/test_static_rt_bfd.py

Double commit to 202305 for PR 15765, because of cherry-pick failure.
https://github.com/sonic-net/sonic-buildimage/pull/15765

[staticroutebfd]double commit for PR 15765 

---

platform/mellanox/nv-syncd-shared/nv-syncd-shared.service

[nvidia][syncd] fix incorrect permission of /tmp in syncd container

---

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/jr2cp-nokia-18x100g-4x25g-config.bcm
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/sai_postinit_cmd.soc
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/jr2cp-nokia-18x100g-4x25g-config.bcm
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/sai_postinit_cmd.soc
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/sai_postinit_cmd.soc
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/sai_postinit_cmd.soc

Update/Add the `sai_postinit_cmd.soc` with the interrupt-ids 
- Microsoft ADO **26730061**:
Update/Add the `sai_postinit_cmd.soc` with the interuppt-ids 
Verify on the Chassis LCs

[chassis][voq] update the sai_post_init soc file with interrupt ids 

---

.github/workflows/automerge_scan.yml
.github/workflows/pr_cherrypick_poststep.yml
.github/workflows/pr_cherrypick_prestep.yml

github workflow is not easy to extend to other repos.
Use github app instead to share the same workflow.
- Microsoft ADO **(number only)**:  26855292

[ci] Disable some workflow use github app instead to have stable performance

---

rules/debootstrap.mk

deb11u1 is deprecated.
Use deb11u2 instead.
Other branches are not impacted, because their reproducible build version files are up to date.
- Microsoft ADO **(number only)**:  26964185

[build] Update debootstrap version from deb11u1 to deb11u2

---

dockers/docker-base-buster/Dockerfile.j2
dockers/docker-base-stretch/Dockerfile.j2
get_docker-base.sh
platform/broadcom/rules.mk
platform/components/docker-gbsyncd-credo.mk
platform/nephos/rules.mk
platform/vs/docker-sonic-vs/Dockerfile.j2
platform/vs/onie.mk
sonic-slave-stretch/Dockerfile.j2
src/ixgbe/Makefile
src/socat/Makefile
src/swig/Makefile
src/thrift/Makefile

Remove secrets in repo. These secrets are revoked.
- Microsoft ADO **(number only)**:  26989114

[202211] [build] Use public storage for public resources.

---

dockers/docker-base-buster/Dockerfile.j2
dockers/docker-base-stretch/Dockerfile.j2
get_docker-base.sh
platform/broadcom/rules.mk
platform/components/docker-gbsyncd-credo.mk
platform/nephos/rules.mk
platform/vs/docker-sonic-vs/Dockerfile.j2
platform/vs/onie.mk
sonic-slave-stretch/Dockerfile.j2
src/ixgbe/Makefile
src/socat/Makefile
src/swig/Makefile
src/thrift/Makefile

Remove secrets in repo. These secrets are revoked.
- Microsoft ADO **(number only)**:  26989114

[202205] [build] Use public storage for public resources.

---

get_docker-base.sh
platform/broadcom/rules.mk
platform/broadcom/sai.mk
platform/nephos/rules.mk
platform/vs/onie.mk
sonic-slave-stretch/Dockerfile.j2
src/iproute2/Makefile
src/ixgbe/Makefile
src/python3/Makefile
src/smartmontools/Makefile
src/snmpd/Makefile
src/socat/Makefile
src/swig/Makefile
src/thrift/Makefile

Remove secrets in repo. These secrets are revoked.
- Microsoft ADO **(number only)**:  26989114

[build] Use public storage for public resources. (#18038)

---

rules/debootstrap.mk

backport https://github.com/sonic-net/sonic-buildimage/pull/18185
deb11u1 is deprecated.
Use deb11u2 instead.
Other branches are not impacted, because their reproducible build version files are up to date.

[202311][build] Update debootstrap version from deb11u1 to deb11u2

---

src/iccpd/src/mlacp_link_handler.c

`set_route_by_linux_route()` is not called by any function within this repo and its submodules, checked on 202106 branch and master branch
```
git grep --recurse-submodules "set_route_by_linux_route"
src/iccpd/src/mlacp_link_handler.c:static void set_route_by_linux_route(struct CSM* csm,
src/iccpd/src/mlacp_link_handler.c:            /*set_route_by_linux_route(csm, set_l3_local_if, 1);*/   /*add static route by linux route tool*/
src/iccpd/src/mlacp_link_handler.c:            /*set_route_by_linux_route(csm, set_l3_local_if, 0);*/    /*del static route by linux route tool*/
```
- Microsoft ADO **(number only)**: 27008034
Remove unused function `set_route_by_linux_route()`

iccpd - remove unused function

---

platform/marvell-arm64/platform.conf
platform/marvell-arm64/sonic-platform-nokia/7215/modules/nokia_7215_ixs_a1_cpld.c
platform/marvell-arm64/sonic-platform-nokia/7215/scripts/nokia-7215-init.sh
platform/marvell-arm64/sonic_fit.its

Update Nokia-7215-A1 platform to address UT and OC test failures.
Update platform init and build files
- Microsoft ADO **(number only)**:27111894
Identify failed test cases from OC run on arm64-nokia_ixs7215_52xb-r0 (Nokia-7215-A1) platform and fix bugs
1) Build a Marvell-arm64 target for Nokia-7215-A1
2) Run this image on arm64-nokia_ixs7215_52xb-r0 and verify all dockers are up and test basic commands like:
- show version
- show platform summary
- show platform syseeprom
- show platform fan
- show platform psustatus
- show platform firmware status
- show platform temperature
- show platform ssdhealth
3) Verify ports are up using "show interface status" command
4) Run unit tests and OC test cases.

[Nokia-7215-A1][arm64]Update platform init files

---

platform/mellanox/mlnx-platform-api/tests/test_modules_mgmt.py

add unit tests to test CMIS host management feature
add new file for testing the feature using python unit tests
run all tests from mlnx-platform-api python wheel and make sure all of them passes

add unit tests for CMIS host management feature

---

rules/phy-credo.mk

For the debian bookworm, we fixed some build issue of phy-credo package and packaged it for the bookworm.
Tested that the interfaces related to the phy-credo platforms are up.

[Arista] Update phy-credo package for bookworm

---

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/platform_env.conf

BCM SAI 9.x/10.X crashes in switch create with master. It is because the later SAI versions started using more shared memory (277M with J2C+ in 10.X) and since syncd dockers are created with 64M shared memory by default, SAI runs out of shared memory during SAI database creation and generates core file. So increased the syncd shared memory size to 512M for Nokia platforms.
Increased the SYNCD_SHM_SIZE to 512m for Nokia devices
Verified that the syncd and swss dockers are coming up,  the ports are up and forwarding the traffic.

[Nokia Device] Increase the syncd docker shared memory size for Nokia devices

---

device/arista/x86_64-arista_7800_sup/Arista-7804R3-FM/fabric_monitor_config.json
device/arista/x86_64-arista_7800_sup/Arista-7808R3-FM/fabric_monitor_config.json
device/arista/x86_64-arista_7800_sup/Arista-7808R3A-FM/fabric_monitor_config.json
device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/fabric_monitor_config.json
device/arista/x86_64-arista_7800r3_48cq2_lc/fabric_monitor_config.json
device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/fabric_monitor_config.json
device/arista/x86_64-arista_7800r3_48cqm2_lc/fabric_monitor_config.json
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/fabric_monitor_config.json

Add fabric capacity monitoring data. 
Adding default values for fabric capacity monitoring.

Add fabric capacity monitoring data

---

platform/broadcom/sonic-platform-modules-dell/common/dell_fpga_ocores.c

Update FPGA driver `dell_fpga_ocores` for Dell S52xx and Z9264 platforms.
(Independent of FPGA firmware version)
Logs: [Dell_S5224_logs.txt](https://github.com/sonic-net/sonic-buildimage/files/14686534/Dell_S5224_logs.txt)
Update FPGA driver for Dell S52xx and Z9264 platforms

[Dell] Update FPGA driver - S52xx, Z9264

---

device/mellanox/x86_64-mlnx_msn4700_simx-r0/get_sensors_conf_path
device/mellanox/x86_64-mlnx_msn4700_simx-r0/sensors.conf
device/mellanox/x86_64-mlnx_msn4700_simx-r0/sensors.conf.a1

Add sensor files for MSN4700 simulation platform
Add the missing files to simulate platform part.
Run sonic-mgmt sensor test to verify all is working
Regression test

[Mellanox] Add sensor files for MSN4700 simulation platform

---

platform/mellanox/mlnx-platform-api/sonic_platform/modules_mgmt.py
platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py

Adjust nvidia platform API log content for module host management feature
1. Add log content for EEPROM read/write
2. Add log content for module detection thread
3. Adjust existing log level/content for module detection thread
Manual test

[Mellanox] Adjust log content for module host management feature

---

platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/Makefile
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/i2c-imc.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/oldjc42.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/wistron_6512_32r_cpld.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/wistron_6512_32r_fan.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/wistron_6512_32r_oom.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/wistron_6512_32r_psu.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/wistron_6512_32r_syseeprom.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/modules/wistron_6512_32r_thermal.c
platform/innovium/sonic-platform-modules-wistron/6512-32r/sonic_platform/sfp.py
platform/innovium/sonic-platform-modules-wistron/6512-32r/sonic_platform/watchdog.py
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/modules/wistron_i2c_psu.c
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/modules/wistron_sw_to3200k_cpld.c
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/modules/wistron_sw_to3200k_fan.c
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/modules/wistron_sw_to3200k_oom.c
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/modules/wistron_sw_to3200k_psu.c
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/modules/wistron_sw_to3200k_thermal.c
platform/innovium/sonic-platform-modules-wistron/sw-to3200k/sonic_platform/sfp.py

Modified kernel driver due to kernel version migration
Build the platform driver with master branch kernel
run on DUT

Correct wistron platform driver

---

platform/innovium/sonic-platform-modules-cel/midstone-200i/modules/mc24lc64t.c

v
Platform driver change for bookworm 
Platform driver change for Bookworm changes
Verified by loading image in Midstone platform

Platform driver change for Bookworm

---

platform/mellanox/mlnx-onie-fw-update.sh

/usr/local/bin/reboot could return execution back to the invoking script in case of using graceful reboot. So, exit the script with reboot return code instead of proceeding with execution.
Fix BIOS fw update procedure.
Return exit code from reboot script in mlnx-onie-fw-update.sh
Tested with successful reboot:
```
root@r-leopard-58:/home/admin# sudo fwutil install chassis component BIOS fw <url>
Downloading firmware:
[##########################################################################################################################################################################################]  100%
Warning: Immediate cold reboot is required to complete BIOS firmware update.
New firmware will be installed, continue? [y/N]: y
Installing firmware: …
```

[Mellanpx] Fix reboot script usage in mlnx-onie-fw-update

---

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/installer.conf
device/nokia/x86_64-nokia_ixr7250e_sup-r0/installer.conf

In Linux kernel v6.0, commit, f26e58bf6f5470 "PCI/AER: Enable error reporting when AER is native" changed the default behavior of Advanced Error Reporting (AER).  Reporting is now enabled by default, which was not the case prior.  There are custom FPGA devices on our PCI bus that are not yet configured nor enabled across reboot until the Sonic platform is initialized.  Therefore this is impacting AER adversely.  Since AER was not enabled in 202205, this is not a regression.

[Nokia-IXR7250E] disable pcie aer

---

files/build_templates/docker_image_ctl.j2

This PR should be merged after PR:  https://github.com/sonic-net/sonic-utilities/pull/3276
Mellanox SDK Sniffer target path was changed from "/var/log/mellanox/sniffer/" To: "/var/log/sdk_dbg"
This PR mount the new folder so it can be accessed from host 
Add /var/log/sdk_dbg to mount 
Run SDK sniffer and make sure the sniffer output file kept in the new location

[Mellanox] Mount /var/log/sdk_dbg folder to host filesystem

---

device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C40/jr2-a7280cr3-32d4-40x100G.config.bcm
device/arista/x86_64-arista_7280cr3_32p4/Arista-7280CR3-C40/jr2-a7280cr3-32p4-40x100G.config.bcm

This is to fix the runtime syncd error for HwSku Arista-7280CR3-C40:
sonic INFO syncd#supervisord: syncd <nounit>:dbx_file_get_db_directory:  Error: Entry not found ; DB was not found in /db0:dbx_file_get_db_location: DB Directory does not exist#015
Add dpp_db_path=/usr/share/bcm/db to the broadcom config file, which has been done on another HwSku Arista-7280CR3-C32D4:
https://github.com/sonic-net/sonic-buildimage/blob/202205/device/arista/x86_64-arista_7280cr3_32d4/Arista-7280CR3-C32D4/jr2-a7280cr3-32d4-32x100G%2B4x400G.config.bcm#L3
Interfaces could come up after the change.

[Arista] add dpp_db_path for Arista-7280CR3-C40

---

device/arista/x86_64-arista_7060px5_64s/sensors.conf

Follow-up to "Misc platform improvements for DCS-7060DX5-64S" filed originally as PR #13875.
While generating a 202305 backport of the aforementioned PR, some fixes were identified and implemented to the sensors.conf file on 202305.  These same changes are being upstreamed as part of this PR to master and 202311 to bring the branches into alignment.
The 202305 backport is tracked under PR #18701.
Sensor modifications corresponding to the platform implementation.
Fixes have been validated in our in-house testing and running sonic-mgmt testing on DCS-7060DX5-64S. 
Tested in-house on builds based on current master and 202311.
Misc sensor updates for DCS-7060DX5-64S
n/a

Misc sensor updates for DCS-7060DX5-64S

---

platform/checkout/cisco-8000.ini

Signed-off-by: Anand Mehra [anamehra@cisco.com](mailto:anamehra@cisco.com)
Support for Cisco-8000 platforms on master/ bookworm

Update cisco-8000.ini to 0.master.0.1 release

---

README.md

[doc]: add 202311 build badge

---

README.md

remove barefoot master build badge.

[doc]: add pensando master build badge

---

src/sonic-bgpcfgd/tests/test_sonic-cfggen.py

Remove unnecessary print introduced by https://github.com/sonic-net/sonic-buildimage/pull/18764
- Microsoft ADO **(number only)**: 27801007
Remove unnecessary print introduced by https://github.com/sonic-net/sonic-buildimage/pull/18764
UT passed

[bgp] Remove unnecessary print in bgpcfd ut

---

device/mellanox/x86_64-nvidia_sn5400-r0/pcie.yaml
device/mellanox/x86_64-nvidia_sn5600-r0/pcie.yaml

To support new bios.
Remove I2C Controller from pcie yaml file for SN5600 and SN5400

[Mellanox] Update pcie yaml file for SN5600 and SN5400

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/azure-pipelines-build.yml

[ci]: build nvidia bluefield dpu image

---

.azure-pipelines/azure-pipelines-Official.yml
.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/build-template.yml
.azure-pipelines/docker-sonic-slave-template.yml
.azure-pipelines/docker-sonic-slave.yml
.azure-pipelines/dpkg-cache-cleanup.yml
.azure-pipelines/official-build-cache.yml
.azure-pipelines/official-build-multi-asic.yml
.azure-pipelines/official-build.yml
.azure-pipelines/template-commonlib.yml
azure-pipelines.yml

Migrate agent pool to fix S360 ticket.
- Microsoft ADO **(number only)**:  27889786

[ci] Migrate ubuntu and sonicbld agent pool to fix S360 alert.

---

platform/mellanox/mft.mk

Upgrade MFT tool to 4.28.0-96
Change the relevant make file to pick up the new MFT version
run full sonic-mgmt regression on Mellanox platforms.

[Mellanox] upgrade MFT tool to 4.28.0-96

---

sonic-slave-bookworm/Dockerfile.j2

Use eatmydata to reduce build time of `sonic-slave-bookworm` docker image.
More info in #15857

[build] use eatmydata for sonic-slave-bookworm

---

README.md

[doc]: add build badge for nvidia bluefield

---

.azure-pipelines/docker-sonic-slave.yml

When upgrade to bookworm container, this file is changed by mistake.
bookworm branch is out of date. It breaks pipeline to build sonic-slave-*.
- Microsoft ADO **(number only)**:  28290170

[ci] Fix false reference in docker slave build pipeline.

---

platform/broadcom/libsaithrift-dev.dep
platform/innovium/libsaithrift-dev.dep
platform/marvell/libsaithrift-dev.dep
platform/vs/libsaithrift-dev.dep
rules/sairedis.dep
rules/syncd.dep

Fix DPKG cache errors when configure or build SONiC:
```
/bin/bash: line 1: cd: src/sonic-sairedis/SAI/bm/behavioral-model: No such file or directory
/bin/bash: line 1: cd: src/sonic-sairedis/SAI/bm/behavioral-model: No such file or directory
```
Submodule `bm/behavioral-model` has been removed from SAI repo in https://github.com/opencomputeproject/SAI/pull/1954
But dep files in `sonic-buildimage` haven't been updated.
Remove bm/behavioral-model from `SMDEP_PATHS` for `sairedis`, `syncd` and `libsaithrift-dev` packages.
Run `make configure` or `make list` and make sure you don't see any error messages about behavioral-model.

Fix dep files for sairedis, syncd and libsaithrift-dev

---

device/mellanox/x86_64-nvidia_sn5400-r0/installer.conf
device/mellanox/x86_64-nvidia_sn5600-r0/installer.conf

Disable TPM module for SN5600 and SN5400 to avoid following error message:
```
ERR kernel: [    3.434153] tpm tpm0: [Firmware Bug]: TPM interrupt not working, polling instead
```
Disable TPM via kernel option "modprobe.blacklist=tpm_tis,tpm_crb,tpm"
Manual test, the error log disappeared

[Mellanox] Disable TPM on SN5600 and SN5400 platform

---

dockers/docker-fpm-frr/frr/bgpd/wcmp/bgpd.wcmp.conf.j2
files/build_templates/init_cfg.json.j2
src/sonic-bgpcfgd/bgpcfgd/managers_device_global.py
src/sonic-bgpcfgd/tests/data/wcmp/wcmp.set.conf
src/sonic-bgpcfgd/tests/data/wcmp/wcmp.unset.conf
src/sonic-bgpcfgd/tests/test_device_global.py
src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/bgp_device_global.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/bgp_device_global.json
src/sonic-yang-models/yang-models/sonic-bgp-device-global.yang

**HLD:** https://github.com/sonic-net/SONiC/pull/1629
* W-ECMP feature implementation is according to the HLD
* N/A
* Added W-ECMP YANG model implementation
* Added W-ECMP BGP OA implementation
1. Run UTs
2. Verified manually with the feature qualification
* N/A
* N/A
```
'//||\\`
''``
```

Add W-ECMP to BGP OA

---

device/mellanox/x86_64-mlnx_msn4410-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn4600-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn4600c-r0/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/pmon_daemon_control.json
device/mellanox/x86_64-mlnx_msn4700-r0/pmon_daemon_control.json
device/mellanox/x86_64-nvidia_sn4800-r0/pmon_daemon_control.json
device/mellanox/x86_64-nvidia_sn4800_simx-r0/pmon_daemon_control.json
device/mellanox/x86_64-nvidia_sn5400-r0/pmon_daemon_control.json
device/mellanox/x86_64-nvidia_sn5400_simx-r0/pmon_daemon_control.json
device/mellanox/x86_64-nvidia_sn5600-r0/pmon_daemon_control.json
files/scripts/syncd.sh

This is a backport of https://github.com/sonic-net/sonic-buildimage/pull/19190
For doing fast-reboot with CMIS active modules.
Removed PMON delay for SKUs with support for CMIS active modules
Run fast-reboot test

[202311][Mellanox] Remove pmon delay for certain platforms

---

platform/checkout/cisco-8000.ini

Enable IP for flow cache
Fix arp reply delay
Update default graphene pfc scrubber state
Avoid headroom drop due to headroom abuse caused by sqg/counter-a transition
Enable l2 ecn for 8111
MAC Ports: Address issue with HW state was down but SW state was UP
Use TC 7 for bfd inject packet
Expediting the code drop for 8111 per request. Run analysis pending for other platforms.
Update cisco-8000.ini to 202305.1.0.13 drop

Update cisco-8000.ini to 202305.1.0.13 drop

---

dockers/docker-orchagent/switch.json.j2
src/sonic-config-engine/tests/sample_output/t0-switch-masic1.json
src/sonic-config-engine/tests/sample_output/t0-switch-masic3.json
src/sonic-config-engine/tests/sample_output/t0-switch.json
src/sonic-config-engine/tests/sample_output/t1-switch.json

Reverts sonic-net/sonic-buildimage#19428

Revert "Revert "[action] [PR:18912] [swss]: Add default ECMP/LAG hash offset values for T0 and T1 (#18912)""

---

files/build_templates/sonic_debian_extension.j2
sonic-slave-bookworm/Dockerfile.j2
sonic-slave-bullseye/Dockerfile.j2
sonic-slave-buster/Dockerfile.j2

Part of fix for issue #9407 
- Microsoft ADO: 25484875
Added blkinfo module to the host
Install image with this change, then run: `pip list | grep blkinfo` and verify the following output:
```
$ pip list | grep blkinfo
blkinfo                    0.2.0
```

Added blkinfo module to host for use by ssdutil

---

dockers/docker-fpm-frr/docker_init.sh
dockers/docker-fpm-frr/frr/zebra/zebra.conf.j2
platform/vs/docker-sonic-vs/frr/zebra.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/zebra.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-vni-zebra.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-zebra.conf
src/sonic-config-engine/tests/sample_output/py2/zebra_frr.conf
src/sonic-config-engine/tests/sample_output/py2/zebra_frr_dualtor.conf
src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-vni-zebra.conf
src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-zebra.conf
src/sonic-config-engine/tests/sample_output/py3/zebra_frr.conf
src/sonic-config-engine/tests/sample_output/py3/zebra_frr_dualtor.conf

Remove dplane_fpm_nl configuration from zebra.conf to fix the following errors in /var/log/frr/zebra.log:
```
Jun 27 10:59:26.839855 qa-eth-vt04-6-3700c ERR bgp#zebra[49]: [SHWNK-NWT5S][EC 100663304] No such command on config line 10: no fpm use-next-hop-groups
Jun 27 10:59:26.839855 qa-eth-vt04-6-3700c ERR bgp#zebra[49]: [SHWNK-NWT5S][EC 100663304] No such command on config line 12: fpm address 127.0.0.1
```
Remove these configs.
Build and run - no errors in the log.

[202311][zebra] remove dplane_fpm_nl config from zebra.conf

---

dockers/docker-fpm-frr/base_image_files/TS
dockers/docker-fpm-frr/base_image_files/TSA
dockers/docker-fpm-frr/base_image_files/TSB
files/build_templates/docker_image_ctl.j2
files/image_config/config-setup/config-setup
src/sonic-bgpcfgd/bgpcfgd/main.py
src/sonic-bgpcfgd/bgpcfgd/managers_chassis_app_db.py
src/sonic-bgpcfgd/bgpcfgd/managers_device_global.py
src/sonic-bgpcfgd/bgpcfgd/runner.py
src/sonic-bgpcfgd/tests/test_chassis_app_db.py
src/sonic-bgpcfgd/tests/test_device_global.py

Conflict resolution of [PR#19217](https://github.com/sonic-net/sonic-buildimage/pull/19217) so that it can be cherry-picked into 2024.05
Cherry-pick commits d702bcec5947d87f4becefbc593d4d174865d49a, 0975f250bbb43ce43000c251138608a23d6e1e0a
Ran reliable_tsa tests from https://github.com/sonic-net/sonic-mgmt/pull/13290 on a T2 chassis.

[202405][TSA] Reliable TSA: Conflict resolution for merging into 2024.05 branch

---

Makefile.work
rules/config
slave.mk

Some UT cases are not strong. They maybe hangs in some environment.
Provide a variable to config timeout on some commands which contains UT.
- Microsoft ADO **(number only)**:  28624525
Add a timeout when running UT.

[build] Add timeout on python target and dpkg helper target.

---

platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh

To retain the contents of 'reboot-cause.txt' updated by 'determine-reboot-cause' in case of unknown reboot.
Updated 'track_reboot_reason.sh' to not modify reboot-cause.txt.
Initiate a reboot by system crash (using "echo c > /proc/sysrq-trigger") and verify the reboot cause is 'Unknown'.
Logs: [S6100_reboot_cause_UT.txt](https://github.com/user-attachments/files/16609028/S6100_reboot_cause_UT.txt)
[Dell] S6100 - Do not modify reboot-cause.txt

[Dell] S6100 - Do not modify reboot-cause.txt

---

platform/innovium/sonic-platform-modules-cel/midstone-200i/modules/mc24lc64t.c

Modified the driver API call for i2c dummy device creation
Compile and validate the image in Midstone

202211 - I2c API change

---

rules/openssh.mk

This brings in fixes for CVE-2021-41617, CVE-2023-48795, and CVE-2023-51385.
- Microsoft ADO **(number only)**: 29189901

[202311] Update OpenSSH to 8.4p1-5+deb11u3

---

src/sonic-host-services/scripts/process-reboot-cause

This is to request picking up [PR](https://github.com/sonic-net/sonic-host-services/pull/126) in branch 202205.

Added code to process-reboot-check that mitigates JSON decoder errors

---

dockers/docker-fpm-frr/frr/bgpd/templates/general/policies.conf.j2
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_all.conf
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_base.conf
src/sonic-bgpcfgd/tests/data/general/policies.conf/result_deny.conf

Fixes https://github.com/sonic-net/sonic-buildimage/issues/19380
To enable idf_isolation route-map towards BGP peer
- Microsoft ADO **(number only)**: 28896562
Added the missing calls to route-map and updated UT
Verify that https://github.com/sonic-net/sonic-buildimage/issues/19380 is fixed

Added the missed route-map calls for idf isolation

---

device/mellanox/x86_64-nvidia_sn5400-r0/installer.conf
device/mellanox/x86_64-nvidia_sn5600-r0/installer.conf

Suppress TPM error log:
```
ERR kernel: [    3.434153] tpm tpm0: [Firmware Bug]: TPM interrupt not working, polling instead
```
By setting kernel option "tpm_tis.interrupts=0"
Manual test and sonic-mgmt regression

[Mellanox] Suppress TPM error log

---

.azure-pipelines/azure-pipelines-build.yml

Creates a manifest.json and bsi.json for all the files in a folder.
This generated manifest can be used to validate the contents of the folder in the future.
- Microsoft ADO **(number only)**:  29207108

Enable MG step in azure pipeline checker.

---

README.md

To add 202405 build badge
Added 202405 build badge
Webpage shows the 202405 status

[doc]: add 202405 build badge

---

dockers/docker-dhcp-relay/cli-plugin-tests/mock_tables.py
dockers/docker-dhcp-relay/cli/show/plugins/show_dhcp_relay.py

Dhcp implementation included inefficient code
Using redis.keys with pattern instead of looping over all keys.
Run unit tests.

[dhcp_relay] optimize dhcp relay cli

---

device/arista/x86_64-arista_7800r3a_36d2_lc/media_settings.json

`Master` PR of https://github.com/sonic-net/sonic-buildimage/pull/20283 which was made for `202405`

Fix tuning values in the media_settings.json of 7800r3a_36d2_lc

---

.azure-pipelines/azure-pipelines-image-template.yml

Fix permission issue on docker-ptf /var/run/sshd.
https://github.com/sonic-net/sonic-mgmt/issues/13545
- Microsoft ADO **(number only)**:  29632874
Check docker-ptf in this build. https://dev.azure.com/mssonic/build/_build/results?buildId=653508&view=results

[ci] Fix permission issue on docker-ptf /var/run/sshd

---

platform/checkout/cisco-8000.ini

Signed-off-by: anamehra@cisco.com
Cisco platform 202405.0.5 release
Cisco platform 202405.0.5 release

Update cisco-8000.ini to 202405.0.5 release

---

platform/checkout/cisco-8000.ini

* G100: Fix to use immediate learning mode instead of delayed learning mode which cannot work with flow cache
* Initialize `learn_records` memories
* Fix static mac entries turning into dynamic entries during mac move
* Synchronize between mac notifications and FDB configuration
* Enable MBIST repair
* 8102_64H_O: Power CPLD upgrade support with single reboot
*Tx PFC Counter fix for SQG level 3 congestion scrubber bug
* Fix for ungraceful reboot handling and the reboot cause in such scenarios
Update to platform module 202305.1.0.19

Update cisco-8000.ini to use 202305.1.0.19 drop

---

platform/checkout/cisco-8000.ini

Signed-off-by: anamehra@cisco.com
Cisco platform 202405.0.7 release
Cisco platform 202405.0.7 release

Update cisco-8000.ini to 202405.0.7 release

---

files/build_templates/sonic_debian_extension.j2
files/image_config/monit/arp_update_checker
files/image_config/monit/conf.d/sonic-host

adding a script arp_update_checker, which will run every 10 minutes to check if arp_update script is stuck. It will check if arp_update ping command is run for longer than 5 seconds. If ping is running for longer than 5 seconds, the script will patch arp_update to add a 0.2 second timeout to ping and restart the process. After 3 failed attempts to restart arp_update, trigger alert.
Alerting generated a lot of false positives for arp_update being stuck. This will attempt to restart arp_update if it gets stuck on ping command and if arp_update gets stuck 3 cycles in a row, monit will alert.
- Microsoft ADO **(number only)**: 28645547
Added a script arp_update_checker which will check for ping child processes that arp_update creates and attempt to restart arp_update if the ping process is up …

[monit][arp_update] Adding monit script to check if arp_update is stuck

---

device/mellanox/x86_64-mlnx_msn2700_simx-r0/installer.conf

* To fix hw-mgmt init on a SimX platform
* N/A
* Disabled W/A for SPC-1 HW resource allocation
1. Check service active state
```bash
systemctl is-active hw-management.service
```
* N/A
* N/A
```
'//||\\`
''``
```

[Mellanox] Update SPC-1 SimX resource allocation

---

dockers/docker-database/supervisord.conf.j2

Fix supervisor config generation for multiple db instance issue support.
- Microsoft ADO **(number only)**:29964282
Correct generation template.

Fix supervisor config generation for multiple db instance issue support.

---

platform/checkout/cisco-8000.ini

Signed-off-by: sakalidi sakalidi@cisco.com
Update cisco-8000.ini to ref=202311.1.0.6

Update cisco-8000.ini to ref=202311.1.0.6

---

device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/buffers_defaults_t2.j2
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/buffers_defaults_t2.j2
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/0/buffers_defaults_t2.j2
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x100G/1/buffers_defaults_t2.j2
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/0/buffers_defaults_t2.j2
device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/Nokia-IXR7250E-36x400G/1/buffers_defaults_t2.j2
src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cq2-lc.json
src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3-48cqm2-lc.json
src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-c36-lc.json
src/sonic-config-engine/tests/sample_output/py2/buffer-arista7800r3a-36dm2-d36-lc.json
src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x100g.json
src/sonic-config-engine/tests/sample_output/py2/buffer-nokia-ixr7250e-36x400g.json
src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cq2-lc.json
src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3-48cqm2-lc.json
src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-c36-lc.json
src/sonic-config-engine/tests/sample_output/py3/buffer-arista7800r3a-36dm2-d36-lc.json
src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x100g.json
src/sonic-config-engine/tests/sample_output/py3/buffer-nokia-ixr7250e-36x400g.json

Backport https://github.com/sonic-net/sonic-buildimage/pull/19653 due to cherrypick conflict.

Backport from master - PR:19653 - Updated MMU settings for ingress lossy profile for Nokia and Arista HWSKU

---

platform/checkout/cisco-8000.ini

Update cisco-8000.ini to 202405.0.8 release
Release Content
* SDK HEALTH event notification causing orchagent crash disabled
* Support for Multiple rconsole sessions to difference LCs from Chassis Supervisor.
* Fixed FC asic init failure on Chassis Supervisor reboot
* Added New CLI to display LC Back Plane port to Sup/RP port mapping. 'show platform npu bp-interface-map -n '
* Fixed Log Analyzer error “counter read timeout”
* Fixed Log Analyzer ERROR avago_sbm_spico_int_read
* Enabled enable_mbist_repair across platforms
* Syncd Rpc docker python version migrated to python3

Update cisco-8000.ini to 202405.0.8 release

---

platform/mellanox/mft.mk

Upgrade MFT tool to 4.30.0-136
Change the relevant make file to pick up the new MFT version
Run full sonic-mgmt regression on Mellanox platforms.

[Mellanox] upgrade MFT tool to 4.30.0-136

---

device/mellanox/x86_64-nvidia_sn4280-r0/chassisdb.conf

`CHASSIS_DB` is required for smartswitch platforms for communication between DPU and switch about DPU health and state information. Hence we need to enable it on the smartsiwtch  
By adding `chassis_db.conf` in the platform folder, The configuration in thsi file enables chassis_db
Check if it the `database-chassis` docker is running or not
```admin@sonic:~$ docker ps| grep chassis
9fac8abab889   docker-database:latest               "/usr/local/bin/dock…"   2 hours ago   Up About an hour             database-chassis
```

[Mellanox][Smartswitch] Enable CHASSIS_DB

---

.gitmodules

Add sonic-stp submodule
Add sonic-stp submodule

Add stp submodule

---

dockers/docker-orchagent/enable_counters.py
files/build_templates/init_cfg.json.j2

Reverts sonic-net/sonic-buildimage#20555

Revert "[202405][FC] Put default counters in init_cfg.json"

---

device/mellanox/x86_64-mlnx_msn2700-r0/pmon_daemon_control.json
dockers/docker-platform-monitor/delay.py
dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2

This pr is used to cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/18907 Delay pmon non-critical daemo, which had conflict against 202405 branch.

[202405] Delay pmon non-critical daemon

---

platform/checkout/cisco-8000.ini

Signed-off-by: Anand Mehra [anamehra@cisco.com](mailto:anamehra@cisco.com)
**Release Content**
Chassis: Added services.conf for startup_tsa_tsb.service
Fixed incorrect acpi log level (MIGSMSFT-723)
Fixed rconsole unresponsive issue (MIGSMSFT-759)
Add sensor offset and scaling factor to fan control sensor block
Fix for platform_tests.api.test_thermal.TestThermalApi failure (MIGSMSFT-674)
Fix for TestPfcwdFunc.test_pfcwd_no_traffic - syslog error (MIGSMSFT-672)
Fixed “[8101] Fail to create switch as SAI_COMMON_API_BULK_CREATE failed with 100G uplink” (MIGSMSFT-680)
Disabled sensord which is replaced by sensormond. Added sensormond test configurations
Increase ACL Table limit from 16 to 32
Various SAI loganalyzer error fixes

Update cisco-8000.ini to 202405.0.9 release

---

device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b27/broadcom-sonic-td3.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b37/broadcom-sonic-td3.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b77/broadcom-sonic-td3.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b78/broadcom-sonic-td4.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b85/broadcom-sonic-td2.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b87/broadcom-sonic-td3.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b88/broadcom-sonic-td4.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b96/broadcom-sonic-th.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b97/broadcom-sonic-th2.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b98/broadcom-sonic-th3.config.bcm
device/broadcom/x86_64-broadcom_common/x86_64-broadcom_b99/broadcom-sonic-th4.config.bcm
src/sonic-device-data/tests/permitted_list

merge common config files from broadcom sonic

---

dockers/docker-dhcp-relay/Dockerfile.j2
dockers/docker-dhcp-relay/docker_init.sh
dockers/docker-fpm-frr/Dockerfile.j2
dockers/docker-fpm-frr/docker_init.sh
dockers/docker-orchagent/Dockerfile.j2
dockers/docker-orchagent/docker-init.j2
files/build_templates/docker_image_ctl.j2
files/build_templates/rsyslog_plugin.conf.j2
files/build_templates/sonic_debian_extension.j2

Reverts sonic-net/sonic-buildimage#20351

Revert "[action] [PR:20248] Move eventd enabled check from build time to runtime (#20248)"

---

platform/checkout/cisco-8000.ini

Fixed SDK for Cisco 8122 platform

Update cisco-8000.ini to 202405.0.11 release

---

platform/mellanox/hw-management.mk
platform/mellanox/hw-management/0001-Make-SONiC-determine-reboot-cause-service-start-afte.patch
platform/mellanox/hw-management/0003-Make-system-health-service-starts-after-hw-managemen.patch

Integrate HW-MGMT 7.0040.2000 Changes
Requires https://github.com/sonic-net/sonic-linux-kernel/pull/446

[Mellanox] Integrate HW-MGMT 7.0040.2000 Changes

---

platform/checkout/cisco-8000.ini

Release Notes:
* Fixed MIGSMSFT-752: missing LC data from "show chassis module status" CLI output
* Fixed MIGSMSFT-504: FC serial number update issue after FC swap/change
* Fixed MIGSMSFT-780: fix the issue: show_techsupport & saidump errors. Included rib-cli in syncd docker.
* Fixed MIGSMSFT-761: [cardevent.py](https://cardevent.py/) error due to connection reset
* Fixed syncd grpcpp srv crash

Update cisco-8000.ini to 202405.0.13 release

---

.gitmodules

Update sub-module branches to 202411

[202411] Update submodule branches to 202411

---

platform/checkout/cisco-8000.ini

Fixed SDK version info
Fixed SDK version info

Update cisco-8000.ini to 202405.0.14 release

---

rules/config

[build] Enable reproducible build options to reduce community build failures.

---

platform/checkout/cisco-8000.ini

Release for Cisco 8800 Chassis, 8101
Chassis 8800
Test case fix test_thermal_global_state_db for FC in slot 7 XR to SONiC migration process broken in two steps
Apply SONiC config as part of XR to SONiC migration via minigraph.xml Fixed BFD staying up on portchannel member down issue
8101
Fix for MIGSMSFT-771 - Link flap with disabled bad link detection

Update cisco-8000.ini to 202405.0.15 release

---

platform/checkout/cisco-8000.ini

Initial 202411 Cisco platform release

Update cisco-8000.ini to release 202411.0.1

---

device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/jr2-a7280cr3-32d4-40x100G.config.bcm
device/arista/x86_64-arista_7800r3_48cq2_lc/Arista-7800R3-48CQ2-C48/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3_48cqm2_lc/Arista-7800R3-48CQM2-C48/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/0/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C36/1/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/0/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-C72/1/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/0/sai_postinit_cmd.soc
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/j2p-a7800r3a-36d-36x400G.config.bcm
device/arista/x86_64-arista_7800r3a_36d2_lc/Arista-7800R3A-36D2-D36/1/sai_postinit_cmd.soc

In SAI 11.x the SAI integrity counters is not supported completely.  So, to detect packet drops due to packet corruptions or credit watchdog timeouts. We enable these interrupts and set the verbose level to `error`. This will generate syslogs which can be used to detect.
- Microsoft ADO **[(30497786)](https://msazure.visualstudio.com/One/_workitems/edit/30497786)**:
Enable specific interrupt-ids via the `sai_postinit_cmd.soc` file. 
Generate these interrupts manually and check if the syslog is generated

[chassis] Add sai_postinit_cmd.soc with interrupt IDs for alerting

---

platform/checkout/cisco-8000.ini

Cisco-8800 Chassis:
Fixed issue: "PSUD DB data keys is not cleared on daemon stop"
Fixed LA error: "'/usr/share/sonic/hwsku/context_config.json': [json.exception.parse_error.101] parse error at line 20"

Update cisco-8000.ini to 202405.1.1.2 release

---

platform/checkout/cisco-8000.ini

Release Content
Cisco-8800 Chassis:
Fixed appdemo process crash.
Fixed BFD ACL rule generation for internal portchannels using production graph.

Update cisco-8000.ini to 202405.1.1.3 release

---

device/mellanox/x86_64-nvidia_sn5640_simx-r0/ACS-SN5640/sai_5640.xml

To have the latest sai.xml for Mellanox SN5640 SIMX platform
Update sai.xml for SN5640 SIMX platform
Deploy an image on Mellanox SN5640 SIMX

[Mellanox] [SIMX] Update SN5640 sai.xml

---

platform/checkout/cisco-8000.ini

Cisco-8800 Chassis:
* Fixed max nhop group setting Q100 asic Line Cards.
* Fixed 'punt packet parse' error causing Loganalyzer failure.
* Fixed do_clear_snoop_config Loganalyzer error

Update cisco-8000.ini to 202405.1.1.4 release

---

platform/checkout/cisco-8000.ini

Reverts sonic-net/sonic-buildimage#21601

Revert "Update cisco-8000.ini to 202405.1.1.4 release"

---

device/mellanox/x86_64-nvidia_sn5640_simx-r0/platform.json

Update the Mellanox SN5640 Simx platform device file.
Update the components in the platform.json file
run platform related test cases.

[Mellanox] Update SN5640 Simx platform.json file

---

platform/marvell/sai.mk

Update SDK SAI deb for 202411 branch and integrate fixes in SDK driver
Updated the patch to pick the correct sai deb for 202411 branch.
Verified sonic image built in SONIC PTF.

[Marvell][202411] Update SDK SAI deb and driver

---

src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/setup.py
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_tests/tests/asic-sensors.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/asic-sensors.json
src/sonic-yang-models/yang-models/sonic-asic-sensors.yang

Why I did it
Add Yang Models support for ASIC_SENSORS configuration.
Work item tracking
Microsoft ADO (number only):
How I did it
Add Yang Models support for the following ASIC_SENSORs configuration
{
"ASIC_SENSORS": {
"ASIC_SENSORS_POLLER_INTERVAL": {
"interval": "10"
},
"ASIC_SENSORS_POLLER_STATUS": {
"admin_status": "enable"
}
}
}
Image Build should be passed.
Signed-off-by: mlok <marty.lok@nokia.com>
(cherry picked from commit cb2286ef781394675d1a6fa2af361488059760f3)

[cherry-pick][YangModel][asic_sensors] Add ASIC_SENSORS yang model (#21218) to branch 202411 

---

platform/checkout/cisco-8000.ini

**Release Content**
Cisco-8000 Chassis:
Enable Cisco-8101-O8V48 HWSKU
[8101] Fixed the failure to create switch as SAI_COMMON_API_BULK_CREATE failed with 100G uplink (MIGSMSFT-861)
8101-32FH-O-C01:
Added beacon LED
Enabled dual-tor tc_to_queue_mode platform flags
Updated volt sensor threshold

Update cisco-8000.ini to release 202411.1.0.2

---

.azure-pipelines/docker-sonic-mgmt-py3-only.yml

There is an indentation issue in PR #21757. This PR addresses this issue. 

[Bugfix] Fix indentation issue of #21757

---

dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2

cherry pick -- https://github.com/sonic-net/sonic-buildimage/pull/21296

[202411] Disabling ports by adding parameter ‘-P 0’

---

azure-pipelines.yml

We have added lots of control plane and data plane test to PR test in master branch, and onboarding test job was created for piloting.
The main branch we are working is master branch, no more scripts need to add in 202411 branch.
Remove onboarding test jobs in 202411

[202411] Remove onboarding test jobs

---

files/image_config/monit/container_checker

new added auditd container failed to be launched due to monit blocker.
- Microsoft ADO **(number only)**:31121982
Skip the unexpected container check logic
Verify via auditd image

Fix auditd container monit startup issue

---

azure-pipelines.yml

Remove onboarding PR test job was using for adding more PR test scripts to PR test set, but now mgmt branch already supported all PR test scripts with pytest mark and conditional mark, onboarding PR test jobs are no longer needed.
Remove onboarding PR test jobs to save more instances.

Remove onboarding PR test jobs

---

.azure-pipelines/docker-sonic-mgmt-py3-only.yml

In #21932, we download the docker image from artifact to validate the image. Before pushing it to registry, we need to re-tag it., otherwise, we will face the issue 
```
The push refers to repository [***-microsoft.azurecr.io/docker-sonic-mgmt]
An image does not exist locally with the tag: ***-microsoft.azurecr.io/docker-sonic-mgmt
```
Re-tag the image before pushing it to registry.
Verify it by pipeline.

[py3] Add a step to tag py3only docker image

---

platform/nvidia-bluefield/recipes/mft.mk

Update MFT package version to 4.30.2-23.
Update version in Makefile.
Run regression tests.

[nvidia-bluefield] Update MFT to v4.30.2-23.

---

platform/nvidia-bluefield/recipes/bluefield-soc.mk

Upgrade DPU package versions.
Change make files responsible for packages compilation
Build an image, run sonic-mgmt tests

[nvidia-bluefield] Update BlueField SOC to version 4.11.0-13582

---

device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/buffers_defaults_objects.j2
device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/qos.json.j2

To have buffers updated to new requirements to following SKUs:
Mellanox-SN5600-C256S1
Mellanox-SN5600-C224O8
Mellanox-SN5610N-C256S2
Mellanox-SN5610N-C224O8
Mellanox-SN5640-C512S2
Mellanox-SN5600-C448O16
sonic-mgmt test update: https://github.com/sonic-net/sonic-mgmt/pull/17788
Set port.alpha to 1/64.
Set queue.alpha for queues 1, 2, and 3 to 1.
Set queue.alpha for queue 4 to infinity or 128
Load an image with the change on Mellanox system, check SDK dumps and run sonic-mgmt test.

[Mellanox] Update SN56xx relevant SKUs buffers_defaults_objects.j2

---

dockers/docker-auditd/auditd_config_files/39-exclusions.rules

The Linux audit system is generating excessive noise in logs, particularly from PATH record messages for routine system operations. This makes it difficult to analyze important file deletion events as they are obscured by a high volume of irrelevant records. The added exclusion rules will reduce this noise while preserving visibility of critical file deletion events.
Added two exclusion rules:
1. `-a always,exclude -F msgtype=PATH -F auid<1000` - Excludes PATH records from system accounts (auid < 1000)
1. `-a always,exclude -F msgtype=PATH -F uid=0 -F gid=0` - Excludes PATH records from processes running with root user and group IDs
These rules filter out noise while preserving our existing file deletion monitoring rules. I placed these exclusion rules …

Add new exclusions for reduce PATH records noise

---

src/sonic-yang-models/tests/yang_model_tests/tests/device_metadata.json
src/sonic-yang-models/tests/yang_model_tests/tests_config/device_metadata.json
src/sonic-yang-models/yang-models/sonic-device_metadata.yang

T2 local anchor support was added by this PR https://github.com/sonic-net/sonic-buildimage/pull/21732
We plan to use a new filed to specified the source of anchor route
Add new field in DEVICE_METADAT
UT

[yang] Add anchor_route_source in DEVICE_METADATA

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Use for unit testing bash scripts.
- Microsoft ADO **(number only)**: 31736455
Add installation at the Dockerfile
1. build sonic-mgmt docker 
```
make -f Makefile.work BLDENV=bullseye SONIC_BUILD_JOBS=$(nproc) DEFAULT_CONTAINER_REGISTRY=publicmirror.azurecr.io ENABLE_DOCKER_BASE_PULL=y LEGACY_SONIC_MGMT_DOCKER=n target/docker-sonic-mgmt.gz
```
2. load it:
```
docker load -i target/docker-sonic-mgmt.gz
f2a185d061e0: Loading layer [==================================================>]  3.267GB/3.267GB
Loaded image: docker-sonic-mgmt:latest
```
3. run bats --version
```
docker run --rm docker-sonic-mgmt:latest bats --version
Bats 1.11.1
```
add bats to sonic-mgmt docker.

Install BATS (Bash Automated Testing System) in sonic-mgmt docker.

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Add a pipeline to generates daily, successful virtual SONiC images
Currently, non-build repos such as sonic-mgmt PR testing is downloading vs images from PR build pipeline of sonic-buildimage, it doesn't make sense. This PR introduces a new pipeline yaml to use the merged code to build daily vs images with full tests.
- Microsoft ADO **(32017130)**:
[CI]Add a pipeline to generates daily, successful virtual SONiC images with full tests.
Set up pipeline based on YAML and update sonic-mgmt getbuild script to retrieve successful builds from the new pipeline.
draft pipeline: https://dev.azure.com/mssonic/build/_build/results?buildId=815418&view=results

[CI]Add a pipeline to generates daily, successful virtual SONiC images

---

dockers/docker-ptf/gnxi-patches/0007-Fix-py_gnmicli.py-POLL-mode.patch
dockers/docker-ptf/gnxi-patches/series

POLL mode fails with "invalid argument" when executing gnmi_cli_py --subscribe_mode 2. Fixes poll mode queries.
Also adds escape '/' logic into py_gnmi_cli similiar to how its done in openconfig. https://github.com/openconfig/gnmi/commit/c0a4ed736848c5707974fa9031d95c642fd56e4f
Check for subscribe mode POLL, send poll requests at interval.
Run gnmi_cli_py POLL mode

Add gnxi patch to fix poll mode in gnmi_cli

---

rules/dash-sai.mk

To have the latest DASH bmv2 pipeline and DASH libsai library, which fixes the below syncd_dash link error by adding dummy sai_query_stats_st_capability and sai_tam_telemetry_get_data.
```
2025-04-22T05:11:05.9790403Z /usr/bin/ld: libSyncd.a(libSyncd_a-VendorSai.o): in function `syncd::VendorSai::VendorSai()':
2025-04-22T05:11:05.9790578Z ./syncd/./syncd/VendorSai.cpp:61: undefined reference to `sai_query_stats_st_capability'
2025-04-22T05:11:05.9790749Z /usr/bin/ld: ./syncd/./syncd/VendorSai.cpp:61: undefined reference to `sai_tam_telemetry_get_data'
2025-04-22T05:11:05.9790930Z collect2: error: ld returned 1 exit status
```
- Microsoft ADO **32481466**
Update DASH_SAI_COMMIT in rules/dash-sai.mk
- Build dash libsai package successfully and it includes the latest DASH bmv2 pipeline, …

[vs][dash libsai] Use the latest DASH commit

---

.azure-pipelines/official-build-vs-with-test.yml

cherry pick: https://github.com/sonic-net/sonic-buildimage/pull/22387

[CI]Add variables for build vs

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Fix 202305 official build vs image kvm-test, remove dpu-test
pipeline: https://dev.azure.com/mssonic/build/_build?definitionId=2925&_a=summary&branchFilter=19371%2C19371%2C19371%2C19371%2C19371%2C19371%2C19371

[CI]Fix 202305 official build vs image kvm-test, remove dpu-test

---

.azure-pipelines/docker-sonic-mgmt.yml

Latest sonic-mgmt docker build pipeline is failing in upload docker image with error message:
```
##[error]An image does not exist locally with the tag: ***-microsoft.azurecr.io/docker-sonic-mgmt
```
Tag docker-sonic-mgmt:latest before push to docker registry
Verified with pipeline

Tag docker-sonic-mgmt:latest before push to docker registry

---

dockers/docker-sonic-mgmt/Dockerfile.j2

udpated docker file to incorporate new snappi and restpy versions
To incorporate new snappi changes
Provided the new snappi version
Once the sonic-mgmt docker is isntalled, check the snappi and snappi-ixnetwork versions along with ixnetwork-restpy

Updated Dockerfile.j2 to incorporate new snappi and restpy versions

---

device/mellanox/x86_64-nvidia_sn5600-r0/Mellanox-SN5600-C256S1/buffers_defaults_objects.j2

Split buffer queue configuration in the buffer template for SN5610/SN5600/SN5640 SKUs 

[Mellanox] Split buffer queue configuration in the buffer template for SN5610/SN5600/SN5640 SKUs 

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Update official build vs pipeline trigger, enable branch push trigger

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Update official build vs pipeline trigger, enable branch push trigger [202305]

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Update official build vs pipeline trigger, enable branch push trigger [202311]

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Update official build vs pipeline trigger, enable branch push trigger [202405]

---

.azure-pipelines/official-build-vs-with-test.yml

[CI]Update official build vs pipeline trigger, enable branch push trigger [202411]

---

platform/checkout/cisco-8000-smartswitch.ini

Update cisco-8000-smartswitch.ini for 202411.1.0.7
This is needed for upstream to pick up the latest released version of cisco-8k 202411 source code
Updated the Ref to 202411.1.0.7
The upstream pipeline should be able to build properly.

Update cisco-8000-smartswitch.ini for 202411.1.0.7

---

src/sonic-yang-models/doc/Configuration.md
src/sonic-yang-models/setup.py
src/sonic-yang-models/tests/files/sample_config_db.json
src/sonic-yang-models/tests/yang_model_pytests/test_acl.py
src/sonic-yang-models/tests/yang_model_pytests/test_buffer_profile.py
src/sonic-yang-models/tests/yang_model_pytests/test_trimming.py
src/sonic-yang-models/yang-models/sonic-buffer-profile.yang
src/sonic-yang-models/yang-models/sonic-trimming.yang
src/sonic-yang-models/yang-templates/sonic-types.yang.j2

**HLD:** https://github.com/sonic-net/SONiC/pull/1898
* Added YANG model as part of Packet Trimming feature development
* N/A
* Added YANG model 
1. Run Packet Trimming UTs
* N/A
* [sonic-trimming.yang](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-trimming.yang)
```
'//||\\`
''``
```

[trim]: Add Packet Trimming YANG model

---

device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128S2/buffers_defaults_lt2.j2
device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE/buffers_defaults_lt2.j2

Fix build issue - https://github.com/sonic-net/sonic-buildimage/issues/22534
Created a file buffers_defaults_lt2.j2

Fix build failures

---

device/nvidia-bluefield/arm64-nvda_bf-bf3comdpu/Nvidia-bf3-com-dpu/context_config.json

Related to changes in https://github.com/sonic-net/sonic-buildimage/pull/21940
To improve performance when programming DPUs via gNMI
- Microsoft ADO **30024522**:

Add context config to enable zmq between orchagent and zmq for BF3 dpus

---

device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-O128
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-P32O64
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-P64

This PR is to create symbol links to 3 new HWSKUs in platform folder `device/arista/x86_64-arista_7060x6_64pe_b`
- Arista-7060X6-64PE-O128 --> ../x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-O128
- Arista-7060X6-64PE-P32O64 --> ../x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-P32O64
- Arista-7060X6-64PE-P64 --> ../x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-P64
Create symbol links.
The change is verified by visiting the symbol links.
202503
Create symbol links to 3 new HWSKUs in platform folder `device/arista/x86_64-arista_7060x6_64pe_b`
No config_db change.

Create symbol link in platform x86_64-arista_7060x6_64pe_b

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
dockers/docker-ptf/Dockerfile.j2

1. We already use apt to install python3-gi in SONiC image according to #22326 
But docker-sonic-vs.gz change is missed in that PR.
- Microsoft ADO **(number only)**:  32869072
1. Install python3-gi in docker-sonic-vs.gz image.

[build] Fix docker-sonic-vs build issue for missing pygobject.

---

device/nokia/x86_64-nokia_ixr7250e_36x400g-r0/installer.conf
device/nokia/x86_64-nokia_ixr7250e_sup-r0/installer.conf

Add idle=poll to grub.cfg to fix the issue of sleep and halt states in AMD which causes panic/or BERT
Adde idle=poll to the grub.cfg to address the sleep and halt state. 
After system bootup, check the file "/proc/cmdline" which should contain "idle=poll"

[Nokia-IXR7250E] Add idle=poll to the grub.cfg for platform Nokia-IXR7250E chassis

---

platform/checkout/pensando.ini

Release artifacts for Pensando dpu to build docker-dpu.tar.gz and libsai debs for 1.87.0-SS-15 release
Changes:
- sonic-sairedis fix to support bulk dash tunnel SAI APIs
```
<path_to_sonic-builldimage>: make init
<path_to_sonic-builldimage>: make configure PLATFORM=pensando PLATFORM_ARCH=arm64
cd <path_to_sonic-builldimage>/platform/pensando/pensando-sonic-artifacts
<path_to_sonic-builldimage>/platform/pensando/pensando-sonic-artifacts: gh release download 1.87.0-SS-15-release
<path_to_sonic-builldimage>: NOJESSIE=1 NOSTRETCH=1 NOBUSTER=0 NOBULLSEYE=0 make target/sonic-pensando.tar
```
Load the SONiC image from ONIE and make sure the interfaces are UP. All containers are up.

Update pensando.init to 1.87.0-SS-15-release

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/azure-pipelines-build-ubuntu-2204.yml

* Ubuntu 20.04 agents are deprecated.

Update azure pipeline to use ubuntu 22.04 agent

---

.azure-pipelines/azure-pipelines-build-ubuntu-2204.yml

Add dependencies for protobuf builds on Ubuntu 22.04

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Upgrade celery to 5.5.2 in sonic-mgmt docker image since origin version is too old.

upgrade celery to 5.5.2 in sonic-mgmt docker image

---

dockers/docker-auditd/auditd_config_files/audit.rules

Improve auditd rate limit to 100/second
Improve auditd event rate limit.
- Microsoft ADO **(number only)**: 33069921
Improve rate limit to 100
Manually verify
Pass all unit test cases.
Improve auditd rate limit to 100/second

Improve auditd rate limit to 100/second

---

platform/nvidia-bluefield/recipes/bluefield-soc.mk

To include latest fixes and new functionality
* BFSOC_VERSION v4.11.0-13582 -> v4.11.0-13611
Build an image and run tests from "sonic-mgmt".

 [DPU] Update BFSoC to v4.11.0-13611

---

platform/nvidia-bluefield/recipes/mft.mk

Update MFT to v4.32.0-120.
Update version in the makefile
Compile image, verify the version is correct when running the image on the switch.
relevant sonic-mgmt tests for the commands used by sonic.

[nvidia-bluefield] Update MFT to v4.32.0-120.

---

dockers/docker-bmp-watchdog/watchdog/src/main.rs

when bmp container is rollout via kubeSonic path, its name is not "bmp", but "ksdatatest.azurecr.io/docker-sonic-bmp"
refer below
- Microsoft ADO **(number only)**:33256759
Update docker health check logic correspondingly, using "ps" instead of relying on container name
via KubeSonic path after build image.

update into kubesonic rollout check logic for bmp container daemon existence

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml

Building for pensando now requires access to a private repo that is currently not available.
- Microsoft ADO **(number only)**: 33407145

Remove pensando from version upgrade pipeline

---

azure-pipelines.yml

Reference: https://github.com/sonic-net/sonic-mgmt/pull/18989
- Microsoft ADO **33280967**:

[CI]update pr test pipeline default timeout to 8 hours to mitigate timeout issues

---

device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128S2/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P32O64/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P64/th5-a7060x6-64pe.config.bcm

Enable srv6 on TH5

---

platform/pddf/i2c/utils/pddfparse.py

Add support for active low parsing for GPIO pin in PDDF.
Added active low sysfs write along with direction and before the value write.
Verified with following combination of values in pddf-device.json to get correct
status from gpio pins.
{"port_num":"0", "direction":"out", "value":"0", "edge":"", "active_low":"1"}
{"port_num":"0", "direction":"in", "value":"", "edge":"", "active_low":""}
$ cat /sys/class/gpio/gpio10224/direction
in
$ cat /sys/class/gpio/gpio10224/active_low
0
$ cat /sys/class/gpio/gpio10200/direction
out
$ cat /sys/class/gpio/gpio10200/active_low
1

[PDDF][GPIO] Add support for active low parsing

---

device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE-64x400G/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe/Arista-7060X6-64PE/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-O128/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P32O64/th5-a7060x6-64pe.config.bcm
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-P64/th5-a7060x6-64pe.config.bcm

Fixed https://github.com/aristanetworks/sonic-qual.msft/issues/645
Update bcm config to set ENABLE to 0.
The change is verified by modifying the bcm config and checking if all ports can be up.

Set ENABLE to 0 for TH5 platform

---

azure-pipelines.yml

Support for release 201911 has ended. This PR disables pipeline CICD triggers for the 201911 branch.
Set pipeline triggers to "none" in pipeline yaml file.
Verify that PR testing is not triggered for this PR.

Disable CICD for 201911 branch

---

azure-pipelines.yml

Support for release 202106 has ended. This PR disables pipeline CICD triggers for the 202106 branch.
Set pipeline triggers to "none" in pipeline yaml file.
Verify that PR testing is not triggered for this PR.

Disable CICD for 202106 branch

---

azure-pipelines.yml

Support for release 202111 has ended. This PR disables pipeline CICD triggers for the 202111 branch.
Set pipeline triggers to "none" in pipeline yaml file.
Verify that PR testing is not triggered for this PR.

Disable CICD for 202111 branch

---

azure-pipelines.yml

Support for release 202205 has ended. This PR disables pipeline CICD triggers for the 202205 branch.
Set pipeline triggers to "none" in pipeline yaml file.
Verify that PR testing is not triggered for this PR.

Disable CICD for 202205 branch

---

Makefile.work
dockers/docker-sonic-gnmi/base_image_files/monit_gnmi
rules/docker-gnmi.mk
slave.mk

Reverts sonic-net/sonic-buildimage#22450

Revert "Update gnmi container memory limit"

---

device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/buffers_defaults_t0.j2
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/buffers_defaults_t1.j2
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/hwsku.json
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C448O16/qos.json.j2
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers.json.j2
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers_defaults_t0.j2
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/buffers_defaults_t1.j2
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/hwsku.json
device/arista/x86_64-arista_7060x6_64pe_b/Arista-7060X6-64PE-B-C512S2/qos.json.j2

Add additional config for Arista-7060X6-64PE-B-C512S2, Arista-7060X6-64PE-B-C448O16

---

device/micas/x86_64-micas_m2-w6510-32c-r0/plugins/ssd_util.py
device/micas/x86_64-micas_m2-w6520-48c8qc-r0/M2-W6520-48C8QC/td4-m2-w6520-48c8qc-48x100G-8x400G.yml
device/micas/x86_64-micas_m2-w6930-64qc-r0/M2-W6930-64QC/th4-m2-w6930-64qc-64x400G.config.yml
device/micas/x86_64-micas_m2-w6940-128qc-r0/M2-W6940-128QC/th5-m2-w6940-128qc-128x400g-config.yml
device/micas/x86_64-micas_m2-w6940-64oc-r0/M2-W6940-64OC/th5-m2-w6940-64oc-64x800G.config.yml
device/micas/x86_64-micas_m2-w6940-64oc-r0/platform.json
platform/broadcom/sonic-platform-modules-micas/m2-w6520-24dc8qc/hal-config/x86_64_micas_m2_w6520_24dc8qc_r0_device.py
platform/broadcom/sonic-platform-modules-micas/m2-w6520-48c8qc/hal-config/x86_64_micas_m2_w6520_48c8qc_r0_device.py
platform/broadcom/sonic-platform-modules-micas/m2-w6520-48c8qc/hal-config/x86_64_micas_m2_w6520_48c8qc_r0_exhaust_device.py
platform/broadcom/sonic-platform-modules-micas/m2-w6930-64qc/hal-config/x86_64_micas_m2_w6930_64qc_r0_device.py
platform/broadcom/sonic-platform-modules-micas/m2-w6940-128qc/sonic_platform/restful_interface.py
platform/broadcom/sonic-platform-modules-micas/m2-w6940-64oc/hal-config/x86_64_micas_m2_w6940_64oc_r0_device.py

[pr 23008](https://github.com/sonic-net/sonic-buildimage/pull/23008) cherry pick to 202505 branch

pr 23008 cherry pick to 202505

---

dockers/docker-fpm-frr/docker_init.sh
dockers/docker-fpm-frr/frr/zebra/zebra.conf.j2
platform/vs/docker-sonic-vs/frr/zebra.conf
src/sonic-bgpcfgd/tests/data/sonic-cfggen/zebra/zebra.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-vni-zebra.conf
src/sonic-config-engine/tests/sample_output/py2/t2-chassis-fe-zebra.conf
src/sonic-config-engine/tests/sample_output/py2/zebra_frr.conf
src/sonic-config-engine/tests/sample_output/py2/zebra_frr_dualtor.conf
src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-vni-zebra.conf
src/sonic-config-engine/tests/sample_output/py3/t2-chassis-fe-zebra.conf
src/sonic-config-engine/tests/sample_output/py3/zebra_frr.conf
src/sonic-config-engine/tests/sample_output/py3/zebra_frr_dualtor.conf

backport https://github.com/sonic-net/sonic-buildimage/pull/23292
33406776

[202405][frr]: Force disable next hop group support

---

dockers/docker-auditd/config_checker.py
dockers/docker-auditd/supervisord.conf

Currently, auditd only checks and updates the configuration once. This PR modifies it to perform the check and update periodically.

fix auditd to periodically check and apply configuration changes

---

dockers/docker-ptf/Dockerfile.j2

To enable tests to install iptable rules to accept/drop packets.
Added iptables to list of packages to be installed.
clone and install docker ptf.

adding iptables

---

src/sonic-bgpcfgd/bgpcfgd/main.py

Align bgpcfgd for SpineRouter with this PR: https://github.com/sonic-net/sonic-buildimage/pull/22337/files#diff-f2a60bd6a3c68f7e519d112b6ef206e57a063ffbe0bdbc47ad36d2516fb8669d
Start PrefixListMgr and AsPathMgr for UpperSpineRouter
Manually test
```
admin@sonic:~$ sonic-db-cli CONFIG_DB hset "DEVICE_METADATA|localhost" "type" "UpperSpineRouter"
0
admin@sonic:~$ sudo tail -f /var/log/syslog | grep bgpcfgd | grep Manager
2025 Jul 28 05:40:17.400381 sonic NOTICE bgp#bgpcfgd: Prefix List Manager and AsPath Manager are enabled for UpperSpineRouter/UpstreamLC
```

[T2] Update role check in bgpcfgd for SpineRouter roles

---

device/arista/x86_64-arista_7280dr3a_36/Arista-7280DR3A-36/0/port_config.ini
device/arista/x86_64-arista_7280dr3a_36/Arista-7280DR3A-36/1/port_config.ini

Fix the port alias  `inb` and `recirc` ports
update port config.ini
Test on the device in lab

update port alias for inb and rec port

---

sonic-slave-buster/Dockerfile.j2

Rust was added to bookworm, but is missing in bullseye build. Sonic-swss-common needs rust to build after https://github.com/sonic-net/sonic-swss-common/pull/1044, and byster vs build failures were seen due to missing rust.

Add rust to buster

---

platform/checkout/cisco-8000.ini

Signed-off-by: Anand Mehra (anamehra@cisco.com)

Update cisco-8000.ini to 202411.1.0.12

---

platform/clounix/rules.mk

[build] Fix url for newly onboarded clounix platform.

---

device/arista/x86_64-arista_7060x6_16pe_384c/platform.json
device/arista/x86_64-arista_7060x6_16pe_384c/platform_components.json
device/arista/x86_64-arista_7060x6_16pe_384c_b/platform.json
device/arista/x86_64-arista_7060x6_16pe_384c_b/platform_components.json

There are several issues with existing moby platform files, including:
- test_get_name failed with : 'name' value is incorrect for Scd address in component (https://github.com/aristanetworks/sonic-qual.msft/issues/750)
- test_get_name failed as Thermal name 'Port Card' is not included
- test_led failed as Status LED color incorrect (expected: amber, actual: off) from PSU 0
This PR fixes the above issues
Confirmed that the same tests can pass this the changes included in this PR

[Moby] Fix platform.json and platform components

---

.azure-pipelines/baseline_test/baseline.test.buildimage.yml

In PR https://github.com/sonic-net/sonic-buildimage/pull/23625, baseline test was using private repo and branch for test, but it needs to be fixed since PR merged and baseline test should be created.
Fix sonic-mgmt repo and branch in baseline test.

Fix sonic-mgmt repo and branch in baseline test

---

files/build_templates/sonic_debian_extension.j2
platform/nvidia-bluefield/nasa-cli-helper/nasa-cli-helper.py

Add a helper script to fetch the status of nasa debugging features
Depends on https://github.com/sonic-net/sonic-utilities/pull/4002
Verified on the switch

[nvidia-bluefield] Add nasa cli helper script

---

platform/checkout/cisco-8000-smartswitch.ini
platform/checkout/cisco-8000.ini

Cisco-8000 SONiC master branch support 

Cisco-8000 SONiC master branch release 

---

onie-image-arm64.conf
onie-image-armhf.conf
onie-image.conf
platform/marvell-prestera/onie-image-arm64.conf

Use normal image instead of slim image for small disk device.
Docker size would be larger than previous branch.
And need to remain at most 800M size for k8s deploy.
- 34433933
Update docker ramfs size from 2500M to 3500M
PR test

update DOCKER_RAMFS_SIZE to 3500M

---

.azure-pipelines/azure-pipelines-UpgrateVersion.yml
.azure-pipelines/azure-pipelines-build.yml
scripts/build_mirror_config.sh

Reproducible build changed debian snapshot mirror URL.
Change upgrade version pipeline accordingly.
- Microsoft ADO **(number only)**:  34899240

[build] Change debian snapshot mirror source.

---

dockers/docker-sonic-mgmt/Dockerfile.j2

Update docker-sonic-mgmt python library for snappi_ixload to 0.0.8
Additional fixes and enhancements to snappi_ixload
Ran with DASH HA testcases on local container

Update docker-sonic-mgmt python library for snappi_ixload to 0.0.8
